Repository mattermost/mattermost-webapp, pull requests merged in 2018-08, with the labels that each got.

#1450 Fix statistics in console when translation too long
  components/analytics/statistic_count.jsx
  sass/routes/_admin-console.scss
  tests/components/analytics/__snapshots__/statistic_count.test.jsx.snap
Labels: 3: Ready to Merge, Setup Test Server

#1483 [MM-10621] Update file preview to have the fileInfos sorted by "create_at" (if not created at the same time) or by "name"
  components/create_comment/create_comment.jsx
  components/create_comment/index.js
  components/create_post/create_post.jsx
  components/create_post/index.js
  components/file_attachment_list/file_attachment_list.jsx
  components/file_preview.jsx
  package-lock.json
  package.json
  tests/components/create_comment/create_comment.test.jsx
  tests/components/create_post/create_post.test.jsx
  utils/constants.jsx
Labels: 2: Dev Review

#1374 Sidebar reorganization
  components/more_channels/more_channels.jsx
  components/more_direct_channels/more_direct_channels.jsx
  components/searchable_channel_list.jsx
  components/sidebar/channel_create.jsx
  components/sidebar/channel_more.jsx
  components/sidebar/index.js
  components/sidebar/more_public_direct_channels.jsx
  components/sidebar/sidebar.jsx
  components/user_settings/modal/index.js
  components/user_settings/modal/user_settings_modal.jsx
  components/user_settings/sidebar/index.js
  components/user_settings/sidebar/user_settings_sidebar.jsx
  i18n/en.json
  sass/components/_modal.scss
  sass/components/_popover.scss
  sass/layout/_sidebar-left.scss
  tests/components/__snapshots__/more_channels.test.jsx.snap
  tests/components/sidebar/__snapshots__/sidebar.test.jsx.snap
  tests/components/sidebar/sidebar.test.jsx
  tests/components/user_settings/__snapshots__/user_settings_sidebar.test.jsx.snap
  tests/components/user_settings/user_settings_sidebar.test.jsx
  utils/utils.jsx
Labels: 3: Ready to Merge

#1502 [MM-11051] LHS: Fix misleading loading text
  components/sidebar/sidebar_channel/index.js
  components/sidebar/sidebar_channel/sidebar_channel.jsx
  components/sidebar/sidebar_channel_button_or_link/sidebar_channel_button_or_link.jsx
  sass/routes/_loading.scss
  tests/components/sidebar/__snapshots__/sidebar_channel_button_or_link.test.jsx.snap
  tests/components/sidebar/sidebar_channel_button_or_link.test.jsx
  utils/utils.jsx
Labels: 3: Ready to Merge

#1453 MM-3736 Change HTML messages to Markdown style
  components/admin_console/admin_definition.jsx
  components/admin_console/schema_admin_settings.jsx
  components/announcement_bar/announcement_bar.jsx
  components/post_view/channel_intro_message/channel_intro_message.jsx
  i18n/en.json
Labels: 2: Dev Review

#1503 [MM-10924] Use reset password screen on web irrespective of device
  components/root/root.jsx
Labels: 2: Dev Review

#1505 Upgrade mattermost-redux
  package-lock.json
  package.json
Labels: 3: Ready to Merge

#1506 Fix key for orderedChannelSections component
  components/sidebar/sidebar.jsx
Labels: 2: Dev Review

#1318 Update commands.jsx
  components/help/components/commands.jsx
Labels: 3: Ready to Merge

#1509 translations PR 20180802 (Adds Romanian)
  i18n/de.json
  i18n/en.json
  i18n/es.json
  i18n/fr.json
  i18n/i18n.jsx
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/tr.json
  i18n/zh-CN.json
  i18n/zh-TW.json
  tests/components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
Labels: 3: Ready to Merge

#1507 Bug fixes
  components/sidebar/header/dropdown/sidebar_header_dropdown.jsx
  components/svg/info_icon.jsx
  sass/components/_modal.scss
  sass/components/_popover.scss
  sass/layout/_headers.scss
  sass/layout/_navigation.scss
  sass/layout/_post.scss
  sass/layout/_sidebar-left.scss
  sass/responsive/_mobile.scss
  sass/responsive/_tablet.scss
  tests/components/navbar/__snapshots__/navbar_info_button.test.jsx.snap
  tests/plugins/__snapshots__/main_menu_action.test.jsx.snap
Labels: 3: Ready to Merge

#1510 Revert "Allow duplicate terms for suggestion box (#1501)"
  components/suggestion/suggestion_box.jsx
  components/suggestion/suggestion_list.jsx
  stores/suggestion_store.jsx
Labels: 2: Dev Review

#1511 MM-11554: Redirects user to last viewed non-archived channel when clo…
  actions/global_actions.jsx
  components/channel_header/channel_header.jsx
  components/channel_header/index.js
  components/channel_view/channel_view.jsx
  components/channel_view/index.js
  selectors/storage.js
  tests/components/channel_header.test.jsx
Labels: 2: Dev Review

#1518 Fix incorrect closed bracket in Markdown formatted string
  i18n/en.json
Labels: 3: Ready to Merge

#1456 Fix typo (openraph -> opengraph) in CSS classes
  components/post_view/post_attachment_opengraph/post_attachment_opengraph.jsx
  sass/layout/_webhooks.scss
  sass/responsive/_tablet.scss
Labels: 3: Ready to Merge

#1513 MM-11053: improve group channel name subsetting
  tests/utils/channel_utils.test.jsx
  utils/channel_utils.jsx
Labels: 3: Ready to Merge

#1521 Fix JS error on posts.order where posts is undefined
  actions/post_actions.jsx
Labels: 2: Dev Review

#1522 MM-11510: Adds delete at value to websocket event.
  actions/websocket_actions.jsx
Labels: 3: Ready to Merge

#1512 [MM-11557 & MM-MM-11571] Remove entity to show up in desktop notification and "commented on", and do not show emoji in "commented on"
  actions/notification_actions.jsx
  components/post_view/post_body/post_body.jsx
  tests/utils/markdown/remove_markdown.test.jsx
  utils/markdown/index.js
  utils/text_formatting.jsx
Labels: 2: Dev Review

#1515 [MM-11498] Use event.key as well to support different english keyboard layouts
  tests/utils/utils.test.jsx
  utils/utils.jsx
Labels: 3: Ready to Merge

#1499 [MM-10918] Filter system_remove_channel messages of a current user based on hiding/showing join/leave messages
  components/post_view/combined_system_message/combined_system_message.jsx
  tests/components/combined_system_message/__snapshots__/combined_system_message.test.jsx.snap
  tests/components/combined_system_message/combined_system_message.test.jsx
Labels: 3: Ready to Merge

#1528 [MM-11491] Fix JS error on stripMarkdown
  tests/utils/markdown/remove_markdown.test.jsx
  utils/markdown/index.js
Labels: 2: Dev Review

#1534 Fix JS error on dot menu
  components/dot_menu/dot_menu.jsx
  tests/components/dot_menu/__snapshots__/dot_menu.test.jsx.snap
Labels: 3: Ready to Merge

#1516 MM-11555: Fix Custom Integrations system console page.
  components/admin_console/admin_console.jsx
  components/admin_console/admin_definition.jsx
  components/admin_console/custom_integrations_settings/custom_integrations_settings.jsx
  components/admin_console/custom_integrations_settings/index.jsx
  i18n/en.json
Labels: 3: Ready to Merge

#1152 [MM-1915] Add Deactivate Account - reborn :)
  components/confirm_modal.jsx
  components/setting_item_max.jsx
  components/user_settings/advanced/index.js
  components/user_settings/advanced/user_settings_advanced.jsx
  i18n/en.json
  tests/components/__snapshots__/setting_item_max.test.jsx.snap
  tests/components/setting_item_max.test.jsx
Labels: 3: Ready to Merge

#1491 change to keydown
  components/confirm_modal.jsx
Labels: 3: Ready to Merge

#1524 MM-11586: Updates redux.
  package-lock.json
  package.json
Labels: 3: Ready to Merge

#1525 MM-11384: More customizable approach to the system notices
  actions/user_actions.jsx
  components/confirm_modal.jsx
  components/login/login_controller/login_controller.jsx
  components/root/root.jsx
  components/setting_item_max.jsx
  components/system_notice/index.js
  components/system_notice/notices.jsx
  components/system_notice/system_notice.jsx
  components/user_settings/advanced/index.js
  components/user_settings/advanced/user_settings_advanced.jsx
  i18n/en.json
  tests/components/__snapshots__/setting_item_max.test.jsx.snap
  tests/components/__snapshots__/system_notice.test.jsx.snap
  tests/components/setting_item_max.test.jsx
  tests/components/system_notice.test.jsx
Labels: 3: Ready to Merge, Awaiting PR

#1539 Revert "MM-11384: More customizable approach to the system notices"
  actions/user_actions.jsx
  components/confirm_modal.jsx
  components/login/login_controller/login_controller.jsx
  components/root/root.jsx
  components/setting_item_max.jsx
  components/system_notice/index.js
  components/system_notice/notices.jsx
  components/system_notice/system_notice.jsx
  components/user_settings/advanced/index.js
  components/user_settings/advanced/user_settings_advanced.jsx
  i18n/en.json
  tests/components/__snapshots__/setting_item_max.test.jsx.snap
  tests/components/__snapshots__/system_notice.test.jsx.snap
  tests/components/setting_item_max.test.jsx
  tests/components/system_notice.test.jsx
Labels: 3: Ready to Merge

#1540 Re-Submitting: MM-11384: More customizable approach to the system notices
  actions/user_actions.jsx
  components/login/login_controller/login_controller.jsx
  components/root/root.jsx
  components/system_notice/index.js
  components/system_notice/notices.jsx
  components/system_notice/system_notice.jsx
  tests/components/__snapshots__/system_notice.test.jsx.snap
  tests/components/system_notice.test.jsx
Labels: 3: Ready to Merge

#1542 Release 5.2 daily merge 20180808
  actions/user_actions.jsx
  components/admin_console/admin_console.jsx
  components/admin_console/admin_definition.jsx
  components/admin_console/custom_integrations_settings/custom_integrations_settings.jsx
  components/admin_console/custom_integrations_settings/index.jsx
  components/dot_menu/dot_menu.jsx
  components/login/login_controller/login_controller.jsx
  components/root/root.jsx
  components/system_notice/index.js
  components/system_notice/notices.jsx
  components/system_notice/system_notice.jsx
  i18n/en.json
  package-lock.json
  package.json
  tests/components/__snapshots__/system_notice.test.jsx.snap
  tests/components/dot_menu/__snapshots__/dot_menu.test.jsx.snap
  tests/components/system_notice.test.jsx
  tests/utils/markdown/remove_markdown.test.jsx
  utils/markdown/index.js
Labels: 2: Dev Review

#1538 [MM-11515] Fix autocomplete of channels
  components/suggestion/channel_mention_provider.jsx
Labels: 3: Ready to Merge

#1536 MM-11584: fix system console links
  components/admin_console/admin_navbar_dropdown/admin_navbar_dropdown.jsx
  components/admin_console/permission_schemes_settings/permission_schemes_settings.jsx
  tests/components/admin_console/permission_schemes_settings/__snapshots__/permission_schemes_settings.test.jsx.snap
Labels: 3: Ready to Merge

#1537 [MM-11591] Fix last channel storage key
  actions/global_actions.jsx
Labels: 3: Ready to Merge

#1248 Total count of users is displayed in direct messages.
  components/more_direct_channels/index.js
  components/more_direct_channels/more_direct_channels.jsx
  components/multiselect/multiselect.jsx
  i18n/en.json
  package-lock.json
  sass/components/_multi-select.scss
  tests/components/__snapshots__/more_direct_channels.test.jsx.snap
  tests/components/more_direct_channels.test.jsx
Labels: 3: Ready to Merge

#1523 MM-11556: leverage getDirectAndGroupChannels
  components/suggestion/switch_channel_provider.jsx
  package-lock.json
  package.json
Labels: 3: Ready to Merge

#1504 MM-11450: Expose 'edit_others_posts' permission in permission schemes.
  components/admin_console/permission_schemes_settings/permissions_tree/permissions_tree.jsx
  i18n/en.json
  tests/components/admin_console/permission_schemes_settings/__snapshots__/permissions_tree.test.jsx.snap
Labels: 2: Dev Review

#1544 MM-11572: Add back button to the Mfa login screen
  components/login/login_controller/login_controller.jsx
Labels: 2: Dev Review

#1549 MM-11633 - Updating position of post controls
  sass/responsive/_tablet.scss
Labels: 3: Ready to Merge

#1547 [MM-11615] Change platform to server in AboutModal
  components/about_build_modal/about_build_modal.jsx
  i18n/en.json
  tests/components/__snapshots__/about_build_modal.test.jsx.snap
Labels: 3: Ready to Merge

#1546 MM-11631: s/Link/a/ for more external links
  components/sidebar_right_menu/sidebar_right_menu.jsx
Labels: 3: Ready to Merge

#1552 MM-11576: Updates redux.
  package-lock.json
  package.json
Labels: 3: Ready to Merge

#1535 Jenkinsfile: docker, node:8, jest-junit
  build/.gitignore
  build/Dockerfile
  build/Jenkinsfile
  package-lock.json
  package.json
Labels: 3: Ready to Merge

#1554 Release 5.2 daily merge 20180810
  actions/global_actions.jsx
  components/about_build_modal/about_build_modal.jsx
  components/admin_console/admin_navbar_dropdown/admin_navbar_dropdown.jsx
  components/admin_console/permission_schemes_settings/permission_schemes_settings.jsx
  components/sidebar_right_menu/sidebar_right_menu.jsx
  components/suggestion/channel_mention_provider.jsx
  components/suggestion/switch_channel_provider.jsx
  i18n/en.json
  package-lock.json
  package.json
  sass/responsive/_tablet.scss
  tests/components/__snapshots__/about_build_modal.test.jsx.snap
  tests/components/admin_console/permission_schemes_settings/__snapshots__/permission_schemes_settings.test.jsx.snap
Labels: 2: Dev Review

#1550 [MM 11170] Remove Loader and someone from LHS
  components/sidebar/sidebar_channel/index.js
  components/sidebar/sidebar_channel/sidebar_channel.jsx
  components/sidebar/sidebar_channel_button_or_link/sidebar_channel_button_or_link.jsx
  sass/routes/_loading.scss
  tests/components/sidebar/__snapshots__/sidebar_channel_button_or_link.test.jsx.snap
  tests/components/sidebar/sidebar_channel_button_or_link.test.jsx
  utils/utils.jsx
Labels: 3: Ready to Merge

#1541 MM-11605: Do not show archived channels in the "more..." public channels selector
  components/more_channels/index.js
  components/more_channels/more_channels.jsx
  tests/components/__snapshots__/more_channels.test.jsx.snap
  tests/components/more_channels.test.jsx
Labels: 3: Ready to Merge

#1514 9091 migrated leave_team_modal component to redux
  actions/global_actions.jsx
  actions/views/webrtc.js
  components/channel_layout/channel_controller.jsx
  components/leave_team_modal.jsx
  components/leave_team_modal/index.js
  components/leave_team_modal/leave_team_modal.jsx
  components/sidebar/header/dropdown/sidebar_header_dropdown.jsx
  components/sidebar_right_menu/sidebar_right_menu.jsx
  reducers/views/webrtc.js
  selectors/views/modals.js
  selectors/webrtc.jsx
  stores/modal_store.jsx
  stores/webrtc_store.jsx
  tests/components/leave_team_modal/__snapshots__/leave_team_modal.test.jsx.snap
  tests/components/leave_team_modal/leave_team_modal.test.jsx
  tests/plugins/__snapshots__/main_menu_action.test.jsx.snap
  tests/redux/actions/views/webrtc.test.js
  tests/redux/reducers/views/webrtc.test.js
  tests/redux/selectors/modals.test.js
  tests/redux/selectors/webrtc.test.js
  utils/constants.jsx
Labels: 3: Ready to Merge

#1555 MM-11294 Update AD/LDAP Button Help Text
  components/admin_console/admin_definition.jsx
  components/admin_console/schema_admin_settings.jsx
  i18n/en.json
  tests/components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
Labels: 3: Ready to Merge

#1560 Add link to developer docs in readme/contributing.md
  CONTRIBUTING.md
  README.md
Labels: 3: Ready to Merge

#1559 Swap order between Romanian and Turkish
  i18n/i18n.jsx
  tests/components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
Labels: 3: Ready to Merge

#1562 [MM-11682] Fix long post when opening/expanding RHS
  components/post_view/post_attachment.jsx
  components/post_view/show_more/index.js
  components/post_view/show_more/show_more.jsx
  tests/components/post_view/__snapshots__/post_attachment.test.jsx.snap
  tests/components/post_view/__snapshots__/post_message_view.test.jsx.snap
  tests/components/post_view/show_more.test.jsx
  tests/plugins/__snapshots__/post_type.test.jsx.snap
Labels: 3: Ready to Merge

#1567 MM-9956: Typo in formatting
  components/integrations/confirm_integration/confirm_integration.jsx
  i18n/en.json
  tests/components/integrations/__snapshots__/confirm_integration.test.jsx.snap
Labels: 2: Dev Review

#1565 MM-11689 Do not show EE upgrade notice if analytics not loaded
  components/system_notice/notices.jsx
Labels: 3: Ready to Merge

#1566 Minor bug fixes
  sass/components/_scrollbar.scss
  sass/responsive/_mobile.scss
  sass/responsive/_tablet.scss
  utils/utils.jsx
Labels: 3: Ready to Merge

#1570 MM-11695: Re-enable editing others posts as per permissions system.
  utils/post_utils.jsx
Labels: 2: Dev Review

#1573 [MM-11702] Fix JS error and only show member count if there are users and total count
  components/multiselect/multiselect.jsx
Labels: 3: Ready to Merge

#1575 MM-11707: Removes edit_others_posts permission from the Reset Default…
  utils/constants.jsx
Labels: 3: Ready to Merge

#1578 Merge release-5.2-20180816094048
  actions/user_actions.jsx
  components/more_channels/index.js
  components/more_channels/more_channels.jsx
  components/post_view/post_attachment.jsx
  components/post_view/post_message_view/post_message_view.jsx
  components/post_view/show_more/index.js
  components/post_view/show_more/show_more.jsx
  components/sidebar/sidebar_channel/index.js
  components/sidebar/sidebar_channel/sidebar_channel.jsx
  components/sidebar/sidebar_channel_button_or_link/sidebar_channel_button_or_link.jsx
  components/system_notice/notices.jsx
  i18n/de.json
  i18n/en.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/tr.json
  i18n/zh-CN.json
  i18n/zh-TW.json
  sass/components/_scrollbar.scss
  sass/layout/_post.scss
  sass/layout/_webhooks.scss
  sass/responsive/_desktop.scss
  sass/responsive/_mobile.scss
  sass/responsive/_tablet.scss
  sass/routes/_loading.scss
  tests/components/__snapshots__/more_channels.test.jsx.snap
  tests/components/more_channels.test.jsx
  tests/components/post_view/__snapshots__/post_attachment.test.jsx.snap
  tests/components/post_view/__snapshots__/post_message_view.test.jsx.snap
  tests/components/post_view/__snapshots__/show_more.test.jsx.snap
  tests/components/post_view/post_attachment.test.jsx
  tests/components/post_view/post_message_view.test.jsx
  tests/components/post_view/show_more.test.jsx
  tests/components/sidebar/__snapshots__/sidebar_channel_button_or_link.test.jsx.snap
  tests/components/sidebar/sidebar_channel_button_or_link.test.jsx
  tests/plugins/__snapshots__/post_type.test.jsx.snap
  utils/constants.jsx
  utils/post_utils.jsx
  utils/utils.jsx
Labels: 3: Ready to Merge

#1580 Revert "MM-11707: Removes edit_others_posts permission from the Reset Default…"
  utils/constants.jsx
Labels: 2: Dev Review

#1582 Merge release-5.2-20180817135450
  package-lock.json
  package.json
  utils/constants.jsx
Labels: 2: Dev Review

#1583 Add postId to the PostDropDownMenuAction and Component for plugins
  components/dot_menu/dot_menu.jsx
  components/dot_menu/dot_menu_item.jsx
  tests/components/dot_menu/__snapshots__/dot_menu.test.jsx.snap
Labels: Docs: Needed

#1590 Send entire post to webhook.
  components/post_markdown/post_markdown.jsx
  package-lock.json
Labels: 2: Dev Review

#1592 Fix inconsistency between enable/disable vs activate/deactivate on Plugins > Management
  components/admin_console/plugin_management/plugin_management.jsx
  i18n/en.json
  tests/components/admin_console/plugin_management/__snapshots__/plugin_management.test.jsx.snap
Labels: 3: Ready to Merge

#1600 MM-11782: Make archived channels experimental and off by default.
  components/admin_console/users_and_teams_settings/users_and_teams_settings.jsx
  components/delete_channel_modal/index.js
  i18n/en.json
Labels: 3: Ready to Merge

#1584 [MM-11280] Migrate activity_log_modal.jsx to use Redux
  components/activity_log_modal/activity_log_modal.jsx
  components/activity_log_modal/components/activity_log.jsx
  components/activity_log_modal/components/more_info.jsx
  components/activity_log_modal/index.js
  package-lock.json
  package.json
  tests/components/activity_log_modal.test.jsx
  tests/components/activity_log_modal/__snapshots__/activity_log.test.jsx.snap
  tests/components/activity_log_modal/__snapshots__/more_info.test.jsx.snap
  tests/components/activity_log_modal/activity_log.test.jsx
  tests/components/activity_log_modal/more_info.test.jsx
Labels: 3: Ready to Merge

#1591 MM-11649: Don't disable channel name field if set to town-square.
  components/rename_channel_modal/rename_channel_modal.jsx
Labels: 2: Dev Review

#1563 MM-11469: Create a telemetry event for telemetry config changed.
  components/admin_console/admin_definition.jsx
  components/admin_console/schema_admin_settings.jsx
Labels: 3: Ready to Merge

#1597 Change SuggestionBox to use focusin and focusout events
  components/admin_console/user_autocomplete_setting.jsx
  components/suggestion/at_mention_provider.jsx
  components/suggestion/channel_mention_provider.jsx
  components/suggestion/command_provider.jsx
  components/suggestion/emoticon_provider.jsx
  components/suggestion/search_channel_provider.jsx
  components/suggestion/search_user_provider.jsx
  components/suggestion/suggestion.jsx
  components/suggestion/suggestion_box.jsx
  components/suggestion/switch_channel_provider.jsx
  components/suggestion/switch_team_provider.jsx
  components/suggestion/timezone_provider.jsx
Labels: 3: Ready to Merge

#1609 Fix messages
  components/admin_console/reset_email_modal/reset_email_modal.jsx
  components/delete_channel_modal/delete_channel_modal.jsx
  i18n/en.json
Labels: 3: Ready to Merge

#1569 Fix incorrect help text for "Enable Webhook Debugging"
  components/admin_console/admin_definition.jsx
  i18n/en.json
Labels: 2: Dev Review

#1614 Merge release-5.2-20180824093640
  components/admin_console/users_and_teams_settings/users_and_teams_settings.jsx
  components/delete_channel_modal/index.js
  i18n/en.json
Labels: 2: Dev Review

#1603 MM-11554: Adds missing import.
  selectors/storage.js
Labels: 2: Dev Review

#1602 MM-11659: Changes intro message for read-only town square.
  components/post_view/channel_intro_message/channel_intro_message.jsx
  i18n/en.json
Labels: 2: Dev Review

#1589 translations PR 20180820
  i18n/de.json
  i18n/en.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/tr.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 3: Ready to Merge

#1604 Add check for mobile implementation in the PR template
  PULL_REQUEST_TEMPLATE.md
Labels: 3: Ready to Merge

#1611 MM-11444 Add default theming to icons in the team sidebar
  sass/layout/_team-sidebar.scss
  utils/utils.jsx
Labels: 2: Dev Review

#1606 Recalculate textContainer height for each image height received
  components/post_view/post_attachment.jsx
  components/post_view/post_message_view/post_message_view.jsx
  components/post_view/show_more/show_more.jsx
  tests/components/post_view/__snapshots__/post_attachment.test.jsx.snap
  tests/components/post_view/__snapshots__/post_message_view.test.jsx.snap
  tests/components/post_view/post_attachment.test.jsx
  tests/components/post_view/post_message_view.test.jsx
  tests/components/post_view/show_more.test.jsx
  tests/plugins/__snapshots__/post_type.test.jsx.snap
Labels: 3: Ready to Merge

#1621 MM-11655: Don't ask me again fix
  actions/user_actions.jsx
  components/reset_status_modal/reset_status_modal.jsx
  components/status_dropdown/index.jsx
  components/status_dropdown/status_dropdown.jsx
Labels: 2: Dev Review

#1613 MM-10532: Adding IdAttribute to SAML authentication
  components/admin_console/saml_settings.jsx
  i18n/en.json
Labels: 3: Ready to Merge

#1596 MM-11790 Add short delay to suggestion updates to prevent spamming
  components/suggestion/suggestion_box.jsx
Labels: 3: Ready to Merge

#1617 Fixing freeze warning.
  components/admin_console/plugin_management/plugin_management.jsx
Labels: 3: Ready to Merge

#1616 MM-11475 Preventing sidebar header menu from closing when new post is received in channel.
  components/sidebar/header/dropdown/sidebar_header_dropdown.jsx
Labels: 3: Ready to Merge

#1626 MM-10532: Add EnableSyncWithLdapIncludeAuth config
  components/admin_console/saml_settings.jsx
  i18n/en.json
Labels: 3: Ready to Merge

#1624 translations PR 20180827
  i18n/de.json
  i18n/en.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/tr.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 2: Dev Review

#1634 MM-11853: Updates redux.
  package-lock.json
  package.json
Labels: 2: Dev Review

#1574 Feature/search after before on
  actions/views/rhs.js
  components/search_bar/search_bar.jsx
  components/suggestion/search_date_provider.jsx
  components/suggestion/suggestion_box.jsx
  components/suggestion/suggestion_date.jsx
  i18n/en.json
  package-lock.json
  package.json
  sass/components/_day-picker.scss
  sass/components/_module.scss
  tests/redux/actions/views/rhs.test.js
  utils/timezone.jsx
  utils/utils.jsx
Labels: 3: Ready to Merge

#1635 MM-11696 Mark GMs open when switching to them
  components/channel_layout/channel_identifier_router.jsx
  package-lock.json
  package.json
Labels: 3: Ready to Merge

#1631 MM-11473: Ignore the not-so-error "ResizeObserver loop limit exceeded"
  root.jsx
Labels: 3: Ready to Merge

#1620 [MM-11279] Migrate access_history_modal to be pure and use redux
  components/access_history_modal/access_history_modal.jsx
  components/access_history_modal/index.js
  package-lock.json
  package.json
  tests/components/access_history_modal.test.jsx
Labels: 3: Ready to Merge

#1622 MM-11711 - Inconsistent spacing in channel menu
  sass/components/_dropdown.scss
  sass/layout/_headers.scss
Labels: 2: Dev Review

#1623 MM-11745 Upgrading dependencies.
  package-lock.json
  package.json
  tests/components/__snapshots__/change_url_modal.test.jsx.snap
  tests/components/__snapshots__/markdown.test.jsx.snap
  tests/components/__snapshots__/new_channel_modal.test.jsx.snap
  tests/components/__snapshots__/view_image.test.jsx.snap
  tests/components/combined_system_message/__snapshots__/combined_system_message.test.jsx.snap
  tests/components/common/__snapshots__/site_name_and_description.test.jsx.snap
  tests/components/create_post/create_post.test.jsx
  tests/components/integrations/__snapshots__/edit_incoming_webhook.test.jsx.snap
  tests/components/post_view/post_info/__snapshots__/post_info.test.jsx.snap
  tests/components/select_team/__snapshots__/select_team_item.test.jsx.snap
  tests/components/sidebar/__snapshots__/sidebar.test.jsx.snap
  tests/components/sidebar/__snapshots__/sidebar_channel_button_or_link.test.jsx.snap
  tests/components/sidebar/sidebar.test.jsx
  tests/components/spinner_button.test.jsx
Labels: 3: Ready to Merge

#1629 [MM-11604] Add E2E to account settings - notifications
  components/user_settings/notifications/user_settings_notifications.jsx
  tests/e2e/pages/accountSettingsModalPage.js
  tests/e2e/tests/3_sidebarLeft/accountSettingsModalPage.element.js
  tests/e2e/tests/3_sidebarLeft/accountSettingsNotification.action.js
Labels: 2: Dev Review

#1615 Small fixes on SearchBarComponent (and fixes MM-11639)
  components/search_bar/search_bar.jsx
  i18n/en.json
Labels: 3: Ready to Merge

#1641 [MM-11798] Change landingPageSeen flag to localStorage
  actions/global_actions.jsx
  stores/browser_store.jsx
  utils/constants.jsx
Labels: 2: Dev Review

#1480 MM-11375: fix period in channel purpose issue
  i18n/de.json
  i18n/en.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ru.json
  i18n/tr.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 3: Ready to Merge

#1632 MM-11444 (part 2) Change default plugin sidebar icons opacity
  sass/layout/_team-sidebar.scss
Labels: 3: Ready to Merge

#1639 MM-11449 Show OpenGraph previews for pages with any of the required fields
  components/post_view/post_attachment_opengraph/post_attachment_opengraph.jsx
  package-lock.json
  package.json
Labels: 3: Ready to Merge

#1643 bug fix: use user's timezone setting for search date flags
  actions/views/rhs.js
  tests/redux/actions/views/rhs.test.js
  utils/timezone.jsx
Labels: 3: Ready to Merge

#1638 Stop saving user's ID to their NotifyProps
  components/user_settings/notifications/user_settings_notifications.jsx
Labels: 3: Ready to Merge

#1630 Domains for AllowedUntrustedInternalConnections are separated with spaces.
  components/admin_console/admin_definition.jsx
  i18n/en.json
Labels: 2: Dev Review, 3: Ready to Merge

#1642 MM-11503 Stopped trying to highlight empty search strings
  utils/text_formatting.jsx
Labels: 2: Dev Review

#1649 MM-11763: Allow to copy generated settings
  components/admin_console/generated_setting.jsx
  sass/routes/_admin-console.scss
Labels: 2: Dev Review
