Repository mattermost/mattermost-webapp, pull requests merged in 2018-05, with the labels that each got.

#1059 Add shadow on link preview image
  sass/components/_videos.scss
Labels: 3: Ready to Merge

#1147 Adding dependencies to NOTICE.txt
  NOTICE.txt
Labels: 3: Ready to Merge

#1151 translations PR 20180430
  i18n/de.json
  i18n/en.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ru.json
  i18n/tr.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 3: Ready to Merge

#1145 MM-9849 Disabled system console settings set using environment variables
  actions/admin_actions.jsx
  components/admin_console/admin_console.jsx
  components/admin_console/admin_definition.jsx
  components/admin_console/admin_settings.jsx
  components/admin_console/boolean_setting.jsx
  components/admin_console/cluster_settings.jsx
  components/admin_console/connection_security_dropdown_setting.jsx
  components/admin_console/connection_settings.jsx
  components/admin_console/custom_brand_settings.jsx
  components/admin_console/custom_emoji_settings.jsx
  components/admin_console/custom_integrations_settings/custom_integrations_settings.jsx
  components/admin_console/data_retention_settings.jsx
  components/admin_console/database_settings.jsx
  components/admin_console/dropdown_setting.jsx
  components/admin_console/elasticsearch_settings.jsx
  components/admin_console/email_settings.jsx
  components/admin_console/external_service_settings.jsx
  components/admin_console/generated_setting.jsx
  components/admin_console/gitlab_settings.jsx
  components/admin_console/index.js
  components/admin_console/legal_and_support_settings.jsx
  components/admin_console/link_previews_settings.jsx
  components/admin_console/message_export_settings.jsx
  components/admin_console/multiselect_settings.jsx
  components/admin_console/native_app_link_settings.jsx
  components/admin_console/oauth_settings.jsx
  components/admin_console/password_settings.jsx
  components/admin_console/plugin_settings.jsx
  components/admin_console/policy_settings/policy_settings.jsx
  components/admin_console/public_link_settings.jsx
  components/admin_console/push_settings.jsx
  components/admin_console/radio_setting.jsx
  components/admin_console/rate_settings.jsx
  components/admin_console/saml_settings.jsx
  components/admin_console/schema_admin_settings.jsx
  components/admin_console/session_settings.jsx
  components/admin_console/set_by_env.jsx
  components/admin_console/setting.jsx
  components/admin_console/signup_settings.jsx
  components/admin_console/storage_settings.jsx
  components/admin_console/text_setting.jsx
  components/admin_console/users_and_teams_settings/users_and_teams_settings.jsx
  components/admin_console/webrtc_settings.jsx
  i18n/en.json
  tests/components/admin_console/__snapshots__/custom_plugin_settings.test.jsx.snap
  tests/components/admin_console/__snapshots__/message_export_settings.test.jsx.snap
  tests/components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
  tests/components/admin_console/admin_console.test.jsx
  tests/components/admin_console/schema_admin_settings.test.jsx
Labels: 2: Dev Review

#890 Add AutoResponder settings
  actions/notification_actions.jsx
  actions/user_actions.jsx
  components/confirm_modal.jsx
  components/create_post/create_post.jsx
  components/create_post/index.js
  components/post_view/post/post.jsx
  components/post_view/post_header/post_header.jsx
  components/post_view/post_info/post_info.jsx
  components/reset_status_modal/index.js
  components/reset_status_modal/reset_status_modal.jsx
  components/rhs_comment/rhs_comment.jsx
  components/search_results_item/search_results_item.jsx
  components/setting_item_max.jsx
  components/status_dropdown/index.jsx
  components/status_dropdown/status_dropdown.jsx
  components/user_settings/notifications/index.js
  components/user_settings/notifications/manage_auto_responder.jsx
  components/user_settings/notifications/user_settings_notifications.jsx
  i18n/en.json
  sass/layout/_headers.scss
  sass/layout/_post.scss
  tests/components/__snapshots__/reset_status_modal.test.jsx.snap
  tests/components/__snapshots__/search_results_item.test.jsx.snap
  tests/components/create_post/create_post.test.jsx
  tests/components/reset_status_modal.test.jsx
  tests/components/user_settings/__snapshots__/manage_auto_responder.test.jsx.snap
  tests/components/user_settings/manage_auto_responder.test.jsx
  utils/constants.jsx
  utils/post_utils.jsx
  utils/utils.jsx
Labels: 3: Ready to Merge

#1162 MM-10327 Fix accidental pass in of getUser selector instead of action
  components/admin_console/system_users/list/index.js
Labels: 3: Ready to Merge

#1166 Fix Incomming > Incoming typo
  i18n/en.json
Labels: 3: Ready to Merge

#1164 MM-10360 Render OpenGraph previews for pages with an empty description
  components/post_view/post_attachment_opengraph/post_attachment_opengraph.jsx
  package-lock.json
  package.json
Labels: 3: Ready to Merge

#1163 Reflect that log settings no longer require a restart
  components/admin_console/admin_definition.jsx
  components/admin_console/admin_definition_constants.jsx
  i18n/en.json
Labels: 2: Dev Review

#1157 [MM-10337] Remove users from Add Members selection whenever it's added by other user
  actions/websocket_actions.jsx
Labels: 3: Ready to Merge

#1172 Update mattermost-redux to point to last master commit (fix MM-10464 bug)
  package-lock.json
  package.json
Labels: 2: Dev Review

#1159 [MM-10102 and MM-10103] Fix focus of textbox for mobile classic app on file upload
  components/create_comment/create_comment.jsx
  components/create_post/create_post.jsx
  tests/components/create_comment/create_comment.test.jsx
  tests/components/create_post/create_post.test.jsx
Labels: 3: Ready to Merge

#1168 System console changes for structured logging.
  components/admin_console/admin_definition.jsx
  components/admin_console/admin_definition_constants.jsx
  i18n/en.json
Labels: 3: Ready to Merge

#1174 MM-10360 Only show OpenGraph previews if they have a url defined
  components/post_view/post_attachment_opengraph/post_attachment_opengraph.jsx
  package-lock.json
  package.json
Labels: 3: Ready to Merge

#1171 MM-10338 Disabled time zones on IE11
  components/local_date_time/index.js
  components/profile_popover/index.js
  selectors/general.js
Labels: 3: Ready to Merge

#1160 Init translation for redux lib
  components/root/root.jsx
Labels: 3: Ready to Merge

#1179 Migrate rate admin console to declarative
  components/admin_console/admin_console.jsx
  components/admin_console/admin_definition.jsx
  components/admin_console/rate_settings.jsx
Labels: 3: Ready to Merge

#1177 Updating team sidebar badge position
  sass/layout/_team-sidebar.scss
Labels: 3: Ready to Merge

#1176 Wording tweaks in NOTICE.txt
  NOTICE.txt
Labels: 3: Ready to Merge

#1181 [MM-9280] Link preview is removed for all users if the user that posted the link removes it
  components/post_view/post_attachment_opengraph/post_attachment_opengraph.jsx
Labels: 3: Ready to Merge

#1188 [MM-10494] Fix blank image after selecting user's profile image
  components/setting_picture.jsx
  tests/components/__snapshots__/setting_picture.test.jsx.snap
  tests/components/setting_picture.test.jsx
Labels: 3: Ready to Merge

#1186 MM-10492 Fix saving plugin settings in the system console
  components/admin_console/custom_plugin_settings/custom_plugin_settings.jsx
  components/admin_console/schema_admin_settings.jsx
  tests/components/admin_console/__snapshots__/custom_plugin_settings.test.jsx.snap
Labels: 3: Ready to Merge

#1189 Fix incorrect post date when data retention has deleted root.
  components/rhs_thread/rhs_thread.jsx
Labels: 2: Dev Review

#1187 MM-10492 (4.9) Fix saving plugin settings in the system console
  components/admin_console/custom_plugin_settings/custom_plugin_settings.jsx
  components/admin_console/schema_admin_settings.jsx
  tests/components/admin_console/__snapshots__/custom_plugin_settings.test.jsx.snap
Labels: 3: Ready to Merge

#1153 MM-9753 - Header UI updates
  sass/components/_search.scss
  sass/layout/_headers.scss
  sass/layout/_sidebar-right.scss
Labels: 2: Dev Review

#1165 MM-10397: Reducing persist debounce
  store/index.js
Labels: 3: Ready to Merge, DO NOT MERGE

#1060 Collapse uploaded image
  components/file_attachment_list/file_attachment_list.jsx
  components/file_attachment_list/index.js
  components/single_image_view/single_image_view.jsx
  sass/components/_files.scss
Labels: 3: Ready to Merge

#1193 MM-10515 Fix the channel switcher after switching to a new DM
  components/suggestion/switch_channel_provider.jsx
Labels: 3: Ready to Merge

#1192 MM-10514: Remove delete channel link for town-square in classic app
  components/navbar/navbar.jsx
  tests/components/navbar/__snapshots__/navbar.test.jsx.snap
  tests/components/navbar/navbar.test.jsx
Labels: 3: Ready to Merge

#1184 Bug fixes
  sass/layout/_post.scss
  sass/responsive/_tablet.scss
  utils/utils.jsx
Labels: 3: Ready to Merge

#1195 MM-10539 Fixed uppercase non-user mentions appearing in lowercase
  components/at_mention/at_mention.jsx
  components/at_mention/index.jsx
  tests/components/at_mention/__snapshots__/at_mention.test.jsx.snap
  tests/components/at_mention/at_mention.test.jsx
  tests/utils/formatting_at_mentions.test.jsx
  utils/post_utils.jsx
  utils/text_formatting.jsx
Labels: 3: Ready to Merge

#1185 translations PR 20180507
  i18n/de.json
  i18n/en.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ru.json
  i18n/tr.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 3: Ready to Merge

#1198 Removed unused functions from utils.jsx
  utils/utils.jsx
Labels: 2: Dev Review

#1204 Removed autolinker.js
  package-lock.json
  package.json
  tests/utils/formatting_email.test.jsx
  utils/text_formatting.jsx
Labels: 2: Dev Review

#1208 MM-10492 (4.9) Fix switching between plugin settings
  components/admin_console/custom_plugin_settings/custom_plugin_settings.jsx
Labels: 3: Ready to Merge

#1197 Bug fixes
  sass/components/_search.scss
  sass/layout/_sidebar-right.scss
Labels: 3: Ready to Merge

#1199 MM-10541 Update announcement banner immediately without refresh
  components/announcement_bar/announcement_bar.jsx
  tests/components/__snapshots__/announcement_bar.test.jsx.snap
  tests/components/announcement_bar.test.jsx
  tests/helpers/localstorage.jsx
Labels: 3: Ready to Merge

#1205 MM-10489 - Fixing quotation marks in compact view
  sass/layout/_post.scss
  sass/responsive/_tablet.scss
Labels: 3: Ready to Merge

#1201 MM-10260: only scroll to new message separator if it doesn't fit in the current screen
  components/post_view/post_list.jsx
Labels: 3: Ready to Merge

#1206 translations PR 20180511
  i18n/de.json
  i18n/fr.json
  i18n/pt-BR.json
  i18n/ru.json
  i18n/tr.json
Labels: 3: Ready to Merge

#1209 MM-10550 Updates to system notice
  components/system_notice/notices.jsx
  components/system_notice/system_notice.jsx
  i18n/en.json
  sass/components/_system-notice.scss
  tests/components/__snapshots__/system_notice.test.jsx.snap
Labels: 3: Ready to Merge

#1216 Merge 4.10 into master
  components/admin_console/custom_plugin_settings/custom_plugin_settings.jsx
  components/announcement_bar/announcement_bar.jsx
  components/post_view/post_list.jsx
  components/suggestion/switch_channel_provider.jsx
  components/system_notice/notices.jsx
  components/system_notice/system_notice.jsx
  i18n/de.json
  i18n/en.json
  i18n/fr.json
  i18n/pt-BR.json
  i18n/ru.json
  i18n/tr.json
  sass/components/_search.scss
  sass/components/_system-notice.scss
  sass/layout/_post.scss
  sass/layout/_sidebar-right.scss
  sass/responsive/_tablet.scss
  tests/components/__snapshots__/announcement_bar.test.jsx.snap
  tests/components/__snapshots__/system_notice.test.jsx.snap
  tests/components/announcement_bar.test.jsx
  tests/helpers/localstorage.jsx
Labels: 2: Dev Review

#1203 MM-4998 Adding LoginIdAttribute to system console.
  components/admin_console/admin_definition.jsx
  i18n/en.json
Labels: 2: Dev Review

#1219 MM-8708 Remove API v3 setting from the system console
  components/admin_console/admin_definition.jsx
  i18n/en.json
Labels: 2: Dev Review, Docs: Needed

#1222 [MM-10609] Make team icon not automatically saved when removed
  components/setting_picture.jsx
  tests/components/__snapshots__/setting_picture.test.jsx.snap
  tests/components/setting_picture.test.jsx
Labels: 3: Ready to Merge

#1225 MM-10617 Fixed checking if a link is an image
  components/post_view/post_body_additional_content/post_body_additional_content.jsx
Labels: 2: Dev Review

#1116 New admin console page for manage system schemes
  components/admin_console/admin_console.jsx
  components/admin_console/admin_definition.jsx
  components/admin_console/admin_settings.jsx
  components/admin_console/admin_sidebar/admin_sidebar.jsx
  components/admin_console/audits/audits.jsx
  components/admin_console/permission_schemes_settings/index.jsx
  components/admin_console/permission_schemes_settings/permission_checkbox.jsx
  components/admin_console/permission_schemes_settings/permission_description.jsx
  components/admin_console/permission_schemes_settings/permission_group.jsx
  components/admin_console/permission_schemes_settings/permission_row.jsx
  components/admin_console/permission_schemes_settings/permission_schemes_settings.jsx
  components/admin_console/permission_schemes_settings/permission_system_scheme_settings/index.jsx
  components/admin_console/permission_schemes_settings/permission_system_scheme_settings/permission_system_scheme_settings.jsx
  components/admin_console/permission_schemes_settings/permissions_tree.jsx
  components/admin_console/server_logs/logs.jsx
  components/form_error.jsx
  components/svg/accordion_toggle_icon.jsx
  components/svg/checkbox_checked_icon.jsx
  components/svg/checkbox_partial_icon.jsx
  i18n/en.json
  package-lock.json
  package.json
  root.jsx
  sass/components/_module.scss
  sass/components/_permissions.scss
  sass/routes/_admin-console.scss
  sass/routes/_statistics.scss
  sass/utils/_variables.scss
  tests/components/admin_console/__snapshots__/custom_plugin_settings.test.jsx.snap
  tests/components/admin_console/__snapshots__/message_export_settings.test.jsx.snap
  tests/components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
  tests/components/admin_console/permission_schemes_settings/__snapshots__/permission_checkbox.test.jsx.snap
  tests/components/admin_console/permission_schemes_settings/__snapshots__/permission_group.test.jsx.snap
  tests/components/admin_console/permission_schemes_settings/__snapshots__/permission_row.test.jsx.snap
  tests/components/admin_console/permission_schemes_settings/__snapshots__/permission_schemes_settings.test.jsx.snap
  tests/components/admin_console/permission_schemes_settings/__snapshots__/permission_system_scheme_settings.test.jsx.snap
  tests/components/admin_console/permission_schemes_settings/__snapshots__/permissions_tree.test.jsx.snap
  tests/components/admin_console/permission_schemes_settings/permission_checkbox.test.jsx
  tests/components/admin_console/permission_schemes_settings/permission_group.test.jsx
  tests/components/admin_console/permission_schemes_settings/permission_row.test.jsx
  tests/components/admin_console/permission_schemes_settings/permission_schemes_settings.test.jsx
  tests/components/admin_console/permission_schemes_settings/permission_system_scheme_settings.test.jsx
  tests/components/admin_console/permission_schemes_settings/permissions_tree.test.jsx
  utils/constants.jsx
Labels: 2: Dev Review, Setup Test Server

#1226 MM-8788: Add Team override schemes
  components/admin_console/permission_schemes_settings/index.jsx
  components/admin_console/permission_schemes_settings/permission_schemes_settings.jsx
  components/admin_console/permission_schemes_settings/permissions_scheme_summary/index.jsx
  components/admin_console/permission_schemes_settings/permissions_scheme_summary/permissions_scheme_summary.jsx
  i18n/en.json
  package-lock.json
  package.json
  sass/components/_permissions.scss
  tests/components/admin_console/permission_schemes_settings/__snapshots__/permission_schemes_settings.test.jsx.snap
  tests/components/admin_console/permission_schemes_settings/__snapshots__/permissions_scheme_summary.test.jsx.snap
  tests/components/admin_console/permission_schemes_settings/permission_schemes_settings.test.jsx
  tests/components/admin_console/permission_schemes_settings/permissions_scheme_summary.test.jsx
Labels: 2: Dev Review

#1227 Updated commit of mattermost-redux which fixes combined posts which ignores custom and other post types
  package-lock.json
  package.json
Labels: 2: Dev Review

#1085 [MM-3996] Improved (add/join/leave/remove from channel/team) system messages
  components/delete_post_modal/delete_post_modal.jsx
  components/post_markdown/system_message_helpers.jsx
  components/post_view/combined_system_message/combined_system_message.jsx
  components/post_view/combined_system_message/index.js
  components/post_view/combined_system_message/last_users.jsx
  components/post_view/post_list.jsx
  i18n/en.json
  tests/components/combined_system_message/__snapshots__/combined_system_message.test.jsx.snap
  tests/components/combined_system_message/__snapshots__/last_users.test.jsx.snap
  tests/components/combined_system_message/combined_system_message.test.jsx
  tests/components/combined_system_message/last_users.test.jsx
  tests/components/delete_post_modal.test.jsx
  utils/post_utils.jsx
  utils/utils.jsx
Labels: 3: Ready to Merge

#1229 Fix flickering
  sass/components/_permissions.scss
Labels: 2: Dev Review

#1232 MM-10506: Hide the invite-code config from Team Settings when no invite permissions.
  components/team_general_tab/index.js
  components/team_general_tab/team_general_tab.jsx
  tests/components/__snapshots__/team_general_tab.test.jsx.snap
  tests/components/team_general_tab.test.jsx
Labels: 3: Ready to Merge

#1213 MM-9692: Add note to use Slack Importer CLI for larger ones.
  components/team_import_tab.jsx
  i18n/en.json
Labels: 1: PM Review

#1242 [MM-10479] Move system console > password settings to team edition
  components/admin_console/password_settings.jsx
  components/admin_console/reset_password_modal/reset_password_modal.jsx
  components/claim/components/ldap_to_email.jsx
  components/claim/components/oauth_to_email.jsx
  components/setting_item_max.jsx
  components/signup/signup_email/signup_email.jsx
  components/user_settings/security/user_settings_security.jsx
  tests/utils/utils.test.jsx
  utils/utils.jsx
Labels: 3: Ready to Merge

#1230 MM-10666: fix RECEIVED_PROFILE_IN_CHANNEL
  actions/websocket_actions.jsx
  package-lock.json
  package.json
Labels: 3: Ready to Merge

#1196 Moved messageHtmlToComponent into its own file
  actions/notification_actions.jsx
  components/channel_header/channel_header.jsx
  components/login/login_controller/login_controller.jsx
  components/message_wrapper.jsx
  components/post_markdown/post_markdown.jsx
  components/post_view/post_attachment.jsx
  plugins/index.js
  tests/utils/__snapshots__/message_html_to_component.test.jsx.snap
  tests/utils/message_html_to_component.test.jsx
  tests/utils/post_utils.test.jsx
  utils/message_html_to_component.jsx
  utils/post_utils.jsx
Labels: 3: Ready to Merge

#1238 MM-10265: Adds button to reset permissions to defaults.
  components/admin_console/permission_schemes_settings/permission_group.jsx
  components/admin_console/permission_schemes_settings/permission_system_scheme_settings/permission_system_scheme_settings.jsx
  i18n/en.json
  package-lock.json
  sass/components/_admin-modal.scss
  sass/components/_module.scss
  sass/routes/_admin-console.scss
  tests/components/admin_console/permission_schemes_settings/__snapshots__/permission_system_scheme_settings.test.jsx.snap
  tests/components/admin_console/permission_schemes_settings/permission_system_scheme_settings.test.jsx
  utils/constants.jsx
Labels: 2: Dev Review

#1180 MM-8622: Improved plugin error reporting
  actions/websocket_actions.jsx
  components/admin_console/plugin_management/index.js
  components/admin_console/plugin_management/plugin_management.jsx
  i18n/en.json
  tests/components/admin_console/plugin_management/__snapshots__/plugin_management.test.jsx.snap
  tests/components/admin_console/plugin_management/plugin_management.test.jsx
  utils/constants.jsx
Labels: 2: Dev Review

#1075 MM-9639 Added ability to collapse long posts
  actions/views/rhs.js
  components/file_attachment_list/file_attachment_list.jsx
  components/logged_in/logged_in.jsx
  components/message_with_additional_content.jsx
  components/post_view/post/post.jsx
  components/post_view/post_body/post_body.jsx
  components/post_view/post_message_view/index.js
  components/post_view/post_message_view/post_message_view.jsx
  components/rhs_header_post/index.js
  components/rhs_header_post/rhs_header_post.jsx
  components/rhs_thread/rhs_thread.jsx
  components/search_results/index.jsx
  components/search_results/search_results.jsx
  components/search_results_header/index.jsx
  components/search_results_header/search_results_header.jsx
  components/search_results_item/index.js
  components/search_results_item/search_results_item.jsx
  components/sidebar_right/index.js
  components/sidebar_right/sidebar_right.jsx
  reducers/views/rhs.js
  sass/components/_files.scss
  sass/layout/_post.scss
  sass/responsive/_desktop.scss
  sass/responsive/_tablet.scss
  selectors/rhs.jsx
  tests/components/search_results_item.test.jsx
  tests/plugins/__snapshots__/post_type.test.jsx.snap
  tests/redux/reducers/views/rhs.test.js
  utils/constants.jsx
  utils/utils.jsx
Labels: 2: Dev Review

#1175 [MM-10406] Ignore extra whitespace in commands that use mentions
  actions/channel_actions.jsx
Labels: 2: Dev Review

#1245 [MM-10609] Add function to save after removing the team icon
  components/setting_picture.jsx
  components/team_general_tab/team_general_tab.jsx
  tests/components/__snapshots__/setting_picture.test.jsx.snap
  tests/components/setting_picture.test.jsx
Labels: 2: Dev Review

#1240 translations PR 20180522
  i18n/de.json
  i18n/en.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ru.json
  i18n/tr.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 3: Ready to Merge

#1246 MM-10402: Adds view for unstarted and in-progress permissions phase 2…
  components/admin_console/permission_schemes_settings/index.jsx
  components/admin_console/permission_schemes_settings/permission_schemes_settings.jsx
  i18n/en.json
  package-lock.json
  sass/components/_permissions.scss
  tests/components/admin_console/permission_schemes_settings/__snapshots__/permission_schemes_settings.test.jsx.snap
  tests/components/admin_console/permission_schemes_settings/permission_schemes_settings.test.jsx
Labels: 2: Dev Review, Awaiting PR

#1244 MM-10599: Accept multiple youtube start time formats.
  components/youtube_video/youtube_video.jsx
  tests/components/youtube_video/youtube_video.test.jsx
Labels: 2: Dev Review

#1139 Adding emoji after word limit is reached will give warning message.
  components/textbox.jsx
  tests/components/__snapshots__/textbox.test.jsx.snap
  tests/components/textbox.test.jsx
Labels: 3: Ready to Merge

#1194 [MM-10430] Fix behavior of ExperimentalTownSquareIsReadOnly and add ExperimentalHideTownSquareinLHS feature
  components/sidebar/sidebar_channel/index.js
  package-lock.json
  package.json
  tests/components/sidebar/__snapshots__/sidebar_channel.test.jsx.snap
  tests/components/sidebar/sidebar_channel.test.jsx
Labels: 3: Ready to Merge, Awaiting PR

#1250 [MM-10645] Remove the desktop notification duration setting
  actions/notification_actions.jsx
  components/user_settings/notifications/desktop_notification_settings.jsx
  components/user_settings/notifications/user_settings_notifications.jsx
  i18n/en.json
  tests/components/user_settings/__snapshots__/desktop_notification_settings.test.jsx.snap
  tests/components/user_settings/desktop_notification_settings.test.jsx
  utils/utils.jsx
Labels: 3: Ready to Merge

#1247 MM-10432: Adds next Redux commit for dot release.
  package-lock.json
  package.json
Labels: 3: Ready to Merge

#1258 Fix UI string ID in system_notice.jsx
  components/system_notice/system_notice.jsx
  tests/components/__snapshots__/system_notice.test.jsx.snap
Labels: 3: Ready to Merge

#1254 Some extra fixes needed for the scheme edition.
  components/admin_console/permission_schemes_settings/permission_schemes_settings.jsx
  components/admin_console/permission_schemes_settings/permission_team_scheme_settings/permission_team_scheme_settings.jsx
  components/admin_console/permission_schemes_settings/permissions_scheme_summary/permissions_scheme_summary.jsx
  tests/components/admin_console/permission_schemes_settings/permission_team_scheme_settings.test.jsx
Labels: 2: Dev Review

#1243 Update to "channel" field help text in "Create Outgoing Webhook" screen
  components/integrations/abstract_outgoing_webhook.jsx
  i18n/en.json
Labels: 3: Ready to Merge

#1259 MM-10710: Hide schemes list view on E10
  components/admin_console/admin_sidebar/admin_sidebar.jsx
  components/admin_console/permission_schemes_settings/permission_system_scheme_settings/permission_system_scheme_settings.jsx
  i18n/en.json
  tests/components/admin_console/permission_schemes_settings/__snapshots__/permission_system_scheme_settings.test.jsx.snap
  tests/components/admin_console/permission_schemes_settings/permission_system_scheme_settings.test.jsx
Labels: 3: Ready to Merge

#1237 MM-10352: Enable locking incoming webhooks to a single channel.
  components/integrations/abstract_incoming_webhook.jsx
  i18n/en.json
  tests/components/integrations/__snapshots__/abstract_incoming_hook.test.jsx.snap
Labels: 3: Ready to Merge

#1263 translations PR 20180528
  i18n/de.json
  i18n/en.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ru.json
  i18n/tr.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 3: Ready to Merge

#1269 MM-10693: Adds new UI to update post edit time limit.
  components/admin_console/permission_schemes_settings/edit_post_time_limit_button/edit_post_time_limit_button.jsx
  components/admin_console/permission_schemes_settings/edit_post_time_limit_button/index.jsx
  components/admin_console/permission_schemes_settings/edit_post_time_limit_modal/edit_post_time_limit_modal.jsx
  components/admin_console/permission_schemes_settings/edit_post_time_limit_modal/index.jsx
  components/admin_console/permission_schemes_settings/permission_description.jsx
  components/admin_console/permission_schemes_settings/permission_group.jsx
  components/admin_console/permission_schemes_settings/permission_row.jsx
  components/admin_console/permission_schemes_settings/permissions_tree.jsx
  i18n/en.json
  package-lock.json
  sass/components/_edit-post-time-limit-button.scss
  sass/components/_edit-post-time-limit-modal.scss
  sass/components/_module.scss
  tests/components/admin_console/permission_schemes_settings/__snapshots__/permission_group.test.jsx.snap
  tests/components/admin_console/permission_schemes_settings/__snapshots__/permissions_tree.test.jsx.snap
Labels: 2: Dev Review

#1260 MM-10719: Changes display name of permission checkbox label.
  i18n/en.json
Labels: 3: Ready to Merge

#1274 Fixing the header of the team statistics in the admin console
  components/analytics/team_analytics/team_analytics.jsx
Labels: 2: Dev Review

#1273 Fix description opacity in permissions tree headers
  sass/components/_permissions.scss
Labels: 2: Dev Review
