Repository mattermost/mattermost-webapp, pull requests merged in 2018-09, with the labels that each got.

#1650 MM-11763: Allow to copy generated settings
  components/admin_console/generated_setting.jsx
  sass/routes/_admin-console.scss
Labels: 3: Ready to Merge

#1640 [MM-10621] Fix order of files in viewing file attachments
  components/file_attachment_list/file_attachment_list.jsx
  components/file_attachment_list/index.js
  tests/components/__snapshots__/file_attachment_list.test.jsx.snap
  tests/components/file_attachment_list.test.jsx
Labels: 3: Ready to Merge

#1651 Merge release-5.3-20180903124816
  components/file_attachment_list/file_attachment_list.jsx
  components/file_attachment_list/index.js
  tests/components/__snapshots__/file_attachment_list.test.jsx.snap
  tests/components/file_attachment_list.test.jsx
Labels: 2: Dev Review

#1648 MM-11725: Fix some cases where we show archived channels
  components/suggestion/search_channel_provider.jsx
  components/suggestion/switch_channel_provider.jsx
Labels: 3: Ready to Merge

#1610 Update plugin based on hackathon observation - working on translate plugin
  components/dot_menu/dot_menu.jsx
  components/post_view/post_message_view/post_message_view.jsx
  plugins/registry.js
  tests/components/post_view/__snapshots__/post_message_view.test.jsx.snap
  tests/components/post_view/post_message_view.test.jsx
  tests/plugins/__snapshots__/post_type.test.jsx.snap
Labels: 3: Ready to Merge

#1660 Release 5.3 daily merge 20180904
  components/login/login_controller/login_controller.jsx
  components/suggestion/search_channel_provider.jsx
  components/suggestion/switch_channel_provider.jsx
Labels: 2: Dev Review

#1576 [MM-3736] Change HTML messages to Markdown style
  components/admin_console/admin_definition.jsx
  components/admin_console/cluster_settings.jsx
  components/admin_console/custom_gif_settings.jsx
  components/admin_console/email_settings.jsx
  components/admin_console/gitlab_settings.jsx
  components/admin_console/license_settings.jsx
  components/admin_console/manage_roles_modal/manage_roles_modal.jsx
  components/admin_console/manage_tokens_modal/manage_tokens_modal.jsx
  components/admin_console/message_export_settings.jsx
  components/admin_console/oauth_settings.jsx
  components/admin_console/plugin_management/plugin_management.jsx
  components/admin_console/push_settings.jsx
  components/admin_console/saml_settings.jsx
  components/admin_console/session_settings.jsx
  components/admin_console/system_users/list/system_users_list.jsx
  components/admin_console/users_and_teams_settings/users_and_teams_settings.jsx
  components/analytics/system_analytics/system_analytics.jsx
  components/analytics/team_analytics/team_analytics.jsx
  components/authorize.jsx
  components/convert_channel_modal/convert_channel_modal.jsx
  components/create_post/create_post.jsx
  components/create_team/components/team_url/team_url.jsx
  components/delete_channel_modal/delete_channel_modal.jsx
  components/integrations/installed_oauth_app.jsx
  components/invite_member_modal/invite_member_modal.jsx
  components/mfa/confirm.jsx
  components/mfa/setup/setup.jsx
  components/post_view/channel_intro_message/channel_intro_message.jsx
  components/search_bar/search_bar.jsx
  components/setting_picture.jsx
  components/sidebar/sidebar_tutorial_tip.jsx
  components/signup/signup_email/signup_email.jsx
  components/system_notice/notices.jsx
  components/team_selector_modal/team_selector_modal.jsx
  components/tutorial/menu_tutorial_tip.jsx
  components/tutorial/tutorial_intro_screens.jsx
  components/user_list_row.jsx
  components/user_list_row_with_error.jsx
  components/user_settings/display/manage_languages.jsx
  components/user_settings/general/user_settings_general.jsx
  components/user_settings/security/user_access_token_section/user_access_token_section.jsx
  i18n/en.json
  tests/components/__snapshots__/delete_channel_modal.test.jsx.snap
  tests/components/__snapshots__/setting_picture.test.jsx.snap
  tests/components/__snapshots__/team_selector_modal.test.jsx.snap
  tests/components/admin_console/__snapshots__/message_export_settings.test.jsx.snap
  tests/components/admin_console/plugin_management/__snapshots__/plugin_management.test.jsx.snap
  tests/components/admin_console/system_users/__snapshots__/system_users_list.test.jsx.snap
  tests/components/create_post/__snapshots__/create_post.test.jsx.snap
  tests/components/create_team/__snapshots__/team_url.test.jsx.snap
  tests/components/create_team/team_url.test.jsx
  tests/components/integrations/__snapshots__/installed_oauth_app.test.jsx.snap
  tests/components/sidebar/__snapshots__/sidebar_tutorial_tip.test.jsx.snap
  tests/components/team_general_tab.test.jsx
Labels: 3: Ready to Merge, Tests: Not Needed

#1659 Refactor "commented on..." into its separate component and be tested
  components/post_view/commented_on/commented_on.jsx
  components/post_view/commented_on/index.js
  components/post_view/post_body/post_body.jsx
  tests/components/post_view/__snapshots__/commented_on.test.jsx.snap
  tests/components/post_view/commented_on.test.jsx
Labels: 3: Ready to Merge

#1663 [MM-11912] ~~Add (revert)~~ Set zero delay before calling emitClearSuggestions
  components/suggestion/suggestion_box.jsx
Labels: 3: Ready to Merge

#1645 MM-11852 Fixing jump to bottom of channel when opening emoji picker.
  components/emoji_picker/emoji_picker.jsx
Labels: 3: Ready to Merge

#1662 MM-11849: Add alphabetical order to Compliance export format selector
  components/admin_console/message_export_settings.jsx
  tests/components/admin_console/__snapshots__/message_export_settings.test.jsx.snap
Labels: 3: Ready to Merge

#1661 Adding Permissions setting to declarative admin console
  components/admin_console/admin_console.jsx
  components/admin_console/admin_definition.jsx
  components/admin_console/index.js
  components/admin_console/schema_admin_settings.jsx
  tests/components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
  tests/components/admin_console/admin_console.test.jsx
  tests/components/admin_console/schema_admin_settings.test.jsx
  utils/constants.jsx
Labels: 3: Ready to Merge

#1665 [MM-11927] Add space between line breaks
  tests/utils/markdown/remove_markdown.test.jsx
  utils/markdown/index.js
  utils/markdown/remove_markdown.js
Labels: 3: Ready to Merge

#1672 MM-12044 Add trailing $ to text formatting tokens
  tests/utils/emoticons.test.jsx
  tests/utils/formatting_at_mentions.test.jsx
  utils/emoticons.jsx
  utils/text_formatting.jsx
Labels: 2: Dev Review, DO NOT MERGE

#1669 [MM-12006] Add SearchHint component and use it on SearchBar and SearchResults
  components/search_bar/search_bar.jsx
  components/search_hint.jsx
  components/search_results/search_results.jsx
  i18n/en.json
  tests/components/__snapshots__/search_hint.test.jsx.snap
  tests/components/search_hint.test.jsx
Labels: 2: Dev Review

#1658 Migrate Oauth to declarative in the Admin Console
  components/admin_console/admin_console.jsx
  components/admin_console/admin_definition.jsx
  components/admin_console/oauth_settings.jsx
  components/admin_console/schema_admin_settings.jsx
  i18n/en.json
Labels: 3: Ready to Merge

#1678 Merge release-5.3 into master
  components/admin_console/admin_console.jsx
  components/admin_console/admin_definition.jsx
  components/admin_console/index.js
  components/admin_console/schema_admin_settings.jsx
  components/channel_notifications_modal/channel_notifications_modal.jsx
  components/emoji_picker/emoji_picker.jsx
  components/suggestion/suggestion_box.jsx
  tests/components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
  tests/components/admin_console/admin_console.test.jsx
  tests/components/admin_console/schema_admin_settings.test.jsx
  tests/components/channel_notifications_modal.test.jsx
  tests/utils/markdown/remove_markdown.test.jsx
  utils/constants.jsx
  utils/markdown/index.js
  utils/markdown/remove_markdown.js
Labels: 2: Dev Review

#1671 MM-11992 Fix for count on DM modal search
  components/multiselect/multiselect.jsx
  tests/components/multiselect/__snapshots__/multiselect.test.jsx.snap
  tests/components/multiselect/multiselect.test.jsx
Labels: 3: Ready to Merge

#1682 MM-11725: Do not show not-member archived channels on mentions suggestion
  components/suggestion/channel_mention_provider.jsx
Labels: 3: Ready to Merge

#1680 MM-11812 Improve positioning of emoji picker
  components/emoji_picker/emoji_picker.jsx
  components/emoji_picker/emoji_picker_overlay.jsx
  components/emoji_picker/emoji_picker_tabs.jsx
  components/gif_picker/gif_picker.jsx
  components/rhs_comment/rhs_comment.jsx
  components/rhs_root_post/rhs_root_post.jsx
  tests/components/__snapshots__/edit_post_modal.test.jsx.snap
  tests/components/create_comment/__snapshots__/create_comment.test.jsx.snap
  tests/components/create_post/__snapshots__/create_post.test.jsx.snap
  tests/components/post_view/post_info/__snapshots__/post_info.test.jsx.snap
Labels: 3: Ready to Merge

#1676 [MM-12058] Fix file upload error on reaching max upload file
  components/file_upload/file_upload.jsx
  tests/components/file_upload/file_upload.test.jsx
Labels: 3: Ready to Merge

#1685 translations PR 20180911
  i18n/de.json
  i18n/en.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/tr.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 2: Dev Review

#1692 Merge release-5.3-20180912130734
  components/emoji_picker/emoji_picker.jsx
  components/emoji_picker/emoji_picker_overlay.jsx
  components/emoji_picker/emoji_picker_tabs.jsx
  components/file_upload/file_upload.jsx
  components/gif_picker/gif_picker.jsx
  components/multiselect/multiselect.jsx
  components/rhs_comment/rhs_comment.jsx
  components/rhs_root_post/rhs_root_post.jsx
  components/suggestion/channel_mention_provider.jsx
  i18n/de.json
  i18n/en.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/tr.json
  i18n/zh-CN.json
  i18n/zh-TW.json
  sass/components/_day-picker.scss
  tests/components/__snapshots__/edit_post_modal.test.jsx.snap
  tests/components/create_comment/__snapshots__/create_comment.test.jsx.snap
  tests/components/create_post/__snapshots__/create_post.test.jsx.snap
  tests/components/file_upload/file_upload.test.jsx
  tests/components/multiselect/__snapshots__/multiselect.test.jsx.snap
  tests/components/multiselect/multiselect.test.jsx
  tests/components/post_view/post_info/__snapshots__/post_info.test.jsx.snap
  utils/utils.jsx
Labels: 2: Dev Review

#1670 Refactor search hints
  components/search_bar/search_bar.jsx
  components/search_hint/data_retention_hint.jsx
  components/search_hint/flag_post_search_hint.jsx
  components/search_hint/no_result_search_hint.jsx
  components/search_hint/pin_post_search_hint.jsx
  components/search_hint/search_hint.jsx
  components/search_results/search_results.jsx
  i18n/en.json
  tests/components/search_hint/__snapshots__/data_retention_hint.test.jsx.snap
  tests/components/search_hint/__snapshots__/flag_post_search_hint.test.jsx.snap
  tests/components/search_hint/__snapshots__/no_result_search_hint.test.jsx.snap
  tests/components/search_hint/__snapshots__/pin_post_search_hint.test.jsx.snap
  tests/components/search_hint/__snapshots__/search_hint.test.jsx.snap
  tests/components/search_hint/data_retention_hint.test.jsx
  tests/components/search_hint/flag_post_search_hint.test.jsx
  tests/components/search_hint/no_result_search_hint.test.jsx
  tests/components/search_hint/pin_post_search_hint.test.jsx
  tests/components/search_hint/search_hint.test.jsx
Labels: 3: Ready to Merge

#1690 MM-12020: Removing explicit action to close channel menu
  components/navbar/navbar.jsx
  tests/components/navbar/__snapshots__/navbar.test.jsx.snap
Labels: 2: Dev Review

#1696 update redux commit
  package-lock.json
  package.json
Labels: 3: Ready to Merge

#1695 MM-12042 Remove different fade out effects for collapsed post attachments
  utils/utils.jsx
Labels: 3: Ready to Merge

#1681 MM-11978 - Updating multi select hint
  components/multiselect/multiselect.jsx
  sass/components/_multi-select.scss
  tests/components/multiselect/__snapshots__/multiselect.test.jsx.snap
Labels: 3: Ready to Merge

#1673 MM-12047: Fix LHS unusably slow scrolling on FF
  components/sidebar/sidebar.jsx
Labels: 3: Ready to Merge, Tests: Done

#1691 MM-11706 Load needed profiles when emoji searching
  components/emoji/emoji_list/emoji_list.jsx
  package-lock.json
  package.json
Labels: 3: Ready to Merge

#1702 Merge release-5.3
  components/multiselect/multiselect.jsx
  package-lock.json
  package.json
  sass/components/_multi-select.scss
  tests/components/multiselect/__snapshots__/multiselect.test.jsx.snap
  utils/utils.jsx
Labels: 3: Ready to Merge

#1698 MM-11969 Prevent plugins scripts being added to the page multiple times
  plugins/index.js
Labels: 2: Dev Review

#1703 Set the react configuration for eslint
  .eslintrc.json
  tests/utils/markdown/remove_markdown.test.jsx
Labels: 3: Ready to Merge

#1688 Migrating saml configuration to declarative
  components/admin_console/admin_console.jsx
  components/admin_console/admin_definition.jsx
  components/admin_console/file_upload_setting.jsx
  components/admin_console/remove_file_setting.jsx
  components/admin_console/saml_settings.jsx
  components/admin_console/schema_admin_settings.jsx
Labels: 2: Dev Review

#1693 [MM-11658] Move hiding join/leave messages to TE
  components/user_settings/advanced/index.js
  components/user_settings/advanced/join_leave_section/index.js
  components/user_settings/advanced/join_leave_section/join_leave_section.jsx
  components/user_settings/advanced/user_settings_advanced.jsx
  tests/components/user_settings/advanced_tab/__snapshots__/join_leave_section.test.jsx.snap
  tests/components/user_settings/advanced_tab/join_leave_section.test.jsx
  utils/constants.jsx
Labels: 2: Dev Review

#1699 MM-10573 Add error page if user doesn't authorize Mattermost for OAuth
  components/error_page/error_message.jsx
  components/error_page/error_page.jsx
  components/error_page/error_title.jsx
  i18n/en.json
  tests/components/error_page/__snapshots__/error_message.test.jsx.snap
  tests/components/error_page/__snapshots__/error_title.test.jsx.snap
  tests/components/error_page/error_message.test.jsx
  tests/components/error_page/error_title.test.jsx
  utils/constants.jsx
Labels: 2: Dev Review

#1704 MM-12159: Add Custom brand to the declarative admin console
  components/admin_console/admin_console.jsx
  components/admin_console/admin_definition.jsx
  components/admin_console/custom_brand_settings.jsx
  components/admin_console/schema_admin_settings.jsx
  utils/constants.jsx
Labels: 3: Ready to Merge

#1705 MM-11738 Support relative Markdown links starting with /
  tests/utils/formatting_links.test.jsx
  utils/markdown/renderer.jsx
Labels: 2: Dev Review

#1697 [MM-11856] Revert unit test of Sidebar by setting empty string to href whenever the favicon is not of type string
  components/sidebar/sidebar.jsx
  tests/components/sidebar/__snapshots__/sidebar.test.jsx.snap
  tests/components/sidebar/sidebar.test.jsx
Labels: 3: Ready to Merge

#1708 MM-12197: Migrate Admin Console Sessions to declarative
  components/admin_console/admin_console.jsx
  components/admin_console/admin_definition.jsx
  components/admin_console/session_settings.jsx
Labels: 2: Dev Review

#1707 MM-12196: Migrate Admin Console Client Versions to declarative
  components/admin_console/admin_console.jsx
  components/admin_console/admin_definition.jsx
  components/admin_console/client_versions_settings.jsx
Labels: 3: Ready to Merge

#1667 MM-11907 Move OpenGraph image visibility into storage
  actions/channel_actions.jsx
  actions/post_actions.jsx
  actions/storage.js
  components/file_attachment_list/index.js
  components/post_view/post_attachment_opengraph/post_attachment_opengraph.jsx
  components/post_view/post_body/index.js
  components/post_view/post_body/post_body.jsx
  components/post_view/post_body_additional_content/index.js
  components/post_view/post_body_additional_content/post_body_additional_content.jsx
  components/rhs_comment/index.js
  components/rhs_thread/index.js
  components/rhs_thread/rhs_thread.jsx
  components/single_image_view/index.js
  components/single_image_view/single_image_view.jsx
  selectors/posts.js
  selectors/rhs.jsx
  stores/browser_store.jsx
  stores/post_store.jsx
  tests/components/post_view/post_body_additional_content/post_body_additional_content.test.jsx
  tests/components/single_image_view.test.jsx
  tests/redux/actions/storage.test.js
  tests/redux/selectors/lhs.test.js
  tests/redux/selectors/rhs.test.js
Labels: 3: Ready to Merge

#1709 MM-11982: Fix slack attachments permanlinks click
  components/post_view/post_attachment.jsx
  tests/components/post_view/__snapshots__/post_attachment.test.jsx.snap
Labels: 3: Ready to Merge

#1701 MM-12056: Improve the state management for schema admin settings
  components/admin_console/admin_console.jsx
  components/admin_console/custom_plugin_settings/custom_plugin_settings.jsx
  components/admin_console/custom_plugin_settings/index.js
  components/admin_console/schema_admin_settings.jsx
Labels: 3: Ready to Merge

#1714 Getting error in resolving mattermost-redux, bump it to latest
  package-lock.json
  package.json
Labels: 3: Ready to Merge

#1700 [MM-11883] Fix at mention rendering when multiple at mentions pattern are typed without space in between
  tests/utils/formatting_at_mentions.test.jsx
  utils/text_formatting.jsx
Labels: 2: Dev Review

#1717 Remove .npminstall and don't explicitly build mattermost-redux
  Makefile
  build/Jenkinsfile
  package-lock.json
  package.json
Labels: 3: Ready to Merge

#1723 MM-11964: internalize escape key handling on edit post modal
  components/edit_post_modal/edit_post_modal.jsx
  tests/components/__snapshots__/edit_post_modal.test.jsx.snap
  tests/components/edit_post_modal.test.jsx
Labels: 2: Dev Review

#1719 MM-3762 Focus textbox immediately when opening edit modal
  components/edit_post_modal/edit_post_modal.jsx
  tests/components/edit_post_modal.test.jsx
Labels: 3: Ready to Merge, Tests: Done

#1402 [MM-9751] : Email verification prompt disappears before email is verified
  components/announcement_bar/announcement_bar.jsx
  components/announcement_bar/index.js
  components/do_verify_email/do_verify_email.jsx
  components/do_verify_email/index.js
  components/user_settings/general/index.js
  components/user_settings/general/user_settings_general.jsx
  components/user_settings/modal/index.js
  components/user_settings/modal/user_settings_modal.jsx
  i18n/en.json
  sass/components/_announcement-bar.scss
  sass/components/_module.scss
  sass/routes/_settings.scss
  tests/components/__snapshots__/announcement_bar.test.jsx.snap
  tests/components/announcement_bar.test.jsx
  tests/components/do_verify_email.test.jsx
  utils/constants.jsx
Labels: 3: Ready to Merge

#1674 [MM-11282] Migrate audit_table to use redux and be pure
  components/access_history_modal/access_history_modal.jsx
  components/admin_console/audits/audits.jsx
  components/audit_table/audit_table.jsx
  components/audit_table/index.js
  tests/components/__snapshots__/access_history_modal.test.jsx.snap
  tests/components/access_history_modal.test.jsx
  tests/components/audit_table/__snapshots__/audit_table.test.jsx.snap
  tests/components/audit_table/audit_table.test.jsx
Labels: 3: Ready to Merge

#1664 Ensuring CJK characters can fallback to sans-serif in IE11
  sass/base/_typography.scss
Labels: 3: Ready to Merge

#1684 Fix JS error on local dev when opening ViewImageModal
  components/view_image/view_image.jsx
  sass/components/_modal.scss
  tests/components/__snapshots__/view_image.test.jsx.snap
Labels: 2: Dev Review

#1712 translations PR 20180917
  i18n/de.json
  i18n/en.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/tr.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 3: Ready to Merge

#1740 Add unit tests for mention and search highlighting
  tests/utils/formatting_at_mentions.test.jsx
  tests/utils/formatting_hashtags.test.jsx
  tests/utils/formatting_mention_highlighting.test.jsx
  tests/utils/formatting_search_highlighting.test.jsx
  tests/utils/formatting_wildcards.text.jsx
  utils/text_formatting.jsx
Labels: 2: Dev Review

#1738 MM-11647 - Updating sidebar item css
  sass/layout/_sidebar-left.scss
  sass/responsive/_mobile.scss
Labels: 2: Dev Review

#1720 Fix dev mode warnings caused by Markdown tables
  utils/markdown/renderer.jsx
Labels: 2: Dev Review

#1718 MM-11822 Close channel autocomplete if multiple tildes are typed
  components/suggestion/channel_mention_provider.jsx
  components/suggestion/provider.jsx
  tests/components/__snapshots__/quick_switch_modal.test.jsx.snap
  tests/components/__snapshots__/textbox.test.jsx.snap
Labels: 3: Ready to Merge, Tests: Done

#1737 MM-12078 - Updating background for image content
  sass/components/_modal.scss
Labels: 3: Ready to Merge

#1725 MM-12153: Remove Default Server Language option from the config panel
  components/admin_console/admin_definition.jsx
  i18n/en.json
Labels: 2: Dev Review

#1734 MM-12028 - Updating firefox placeholder text
  sass/layout/_forms.scss
Labels: 3: Ready to Merge

#1727 [MM-12052] Add account setting option to hide channel switcher button in the sidebar
  components/sidebar/index.js
  components/sidebar/sidebar.jsx
  components/user_settings/modal/user_settings_modal.jsx
  components/user_settings/sidebar/index.js
  components/user_settings/sidebar/user_settings_sidebar.jsx
  i18n/en.json
  tests/components/sidebar/__snapshots__/sidebar.test.jsx.snap
  tests/components/sidebar/sidebar.test.jsx
  tests/components/user_settings/__snapshots__/user_settings_sidebar.test.jsx.snap
  tests/components/user_settings/user_settings_sidebar.test.jsx
Labels: 3: Ready to Merge

#1729 MM-11082: Migrate Admin Console Users and Teams to declarative
  components/admin_console/admin_console.jsx
  components/admin_console/admin_definition.jsx
  components/admin_console/schema_admin_settings.jsx
  components/admin_console/users_and_teams_settings/index.jsx
  components/admin_console/users_and_teams_settings/users_and_teams_settings.jsx
  i18n/en.json
  tests/components/admin_console/admin_definition.test.jsx
Labels: 3: Ready to Merge

#1747 fix audit table snapshots
  tests/components/audit_table/__snapshots__/audit_table.test.jsx.snap
  tests/components/audit_table/audit_table.test.jsx
Labels: 3: Ready to Merge

#1730 MM-11983 - Updating list styling in channel header
  sass/components/_popover.scss
Labels: 3: Ready to Merge

#1724 MM-12048: Add mute/unmute to Channel Header Dropdown.
  components/channel_header/channel_header.jsx
  i18n/en.json
  tests/components/__snapshots__/channel_header.test.jsx.snap
  tests/components/channel_header.test.jsx
Labels: 2: Dev Review

#1757 MM-12285: Migrate Admin Console Plugins screens to declarative
  components/admin_console/admin_console.jsx
  components/admin_console/admin_definition.jsx
Labels: 3: Ready to Merge

#1754 MM-12280: Migrate Admin Console Emoji and Gif to declarative
  components/admin_console/admin_console.jsx
  components/admin_console/admin_definition.jsx
  components/admin_console/custom_emoji_settings.jsx
  components/admin_console/custom_gif_settings.jsx
Labels: 3: Ready to Merge

#1755 MM-12279: Adding missed strings on translations
  i18n/en.json
  utils/constants.jsx
Labels: 3: Ready to Merge

#1731 [MM-12167] Bring back the settings button in the plugin admin page
  components/admin_console/plugin_management/plugin_management.jsx
  tests/components/admin_console/plugin_management/__snapshots__/plugin_management.test.jsx.snap
  tests/components/admin_console/plugin_management/plugin_management.test.jsx
Labels: 3: Ready to Merge

#1758 MM-11707: Allow to change the permission for edit the others posts on TE
  components/admin_console/admin_definition.jsx
  i18n/en.json
  utils/policy_roles_adapter.js
Labels: 3: Ready to Merge

#1739 MM-12168 - Fixing file thumbnails for short images
  sass/components/_files.scss
Labels: 3: Ready to Merge

#1716 MM-11926 Fix shortcuts for different layouts keyboards
  tests/components/create_post/create_post.test.jsx
  tests/utils/utils.test.jsx
  utils/constants.jsx
  utils/utils.jsx
Labels: 3: Ready to Merge

#1760 MM-12203 MM-12226 Fixing sidebar unread indicators and scrolling behaviour.
  components/sidebar/sidebar.jsx
Labels: 2: Dev Review

#1750 [MM-9577] Update pinned posts list on channel switch
  actions/global_actions.jsx
  actions/views/rhs.js
  components/sidebar_right/index.js
  components/sidebar_right/sidebar_right.jsx
Labels: 3: Ready to Merge

#1765 Update mattermost-redux to latest
  package-lock.json
  package.json
Labels: 3: Ready to Merge

#1726 MM-12050: Add tooltips to post info overlay buttons.
  components/common/comment_icon.jsx
  components/dot_menu/dot_menu.jsx
  components/post_view/post_info/post_info.jsx
  i18n/en.json
  tests/components/dot_menu/__snapshots__/dot_menu.test.jsx.snap
  tests/components/post_view/post_info/__snapshots__/post_info.test.jsx.snap
Labels: 3: Ready to Merge

#1612 MM-8477 Add interactive menus to message attachments
  actions/views/posts.js
  components/admin_console/user_autocomplete_setting.jsx
  components/edit_post_modal/index.js
  components/post_view/message_attachments/action_button.jsx
  components/post_view/message_attachments/action_menu/action_menu.jsx
  components/post_view/message_attachments/action_menu/index.js
  components/post_view/message_attachments/message_attachment.jsx
  components/post_view/message_attachments/message_attachment_list.jsx
  components/post_view/post_body_additional_content/post_body_additional_content.jsx
  components/suggestion/at_mention_provider.jsx
  components/suggestion/channel_mention_provider.jsx
  components/suggestion/generic_channel_provider.jsx
  components/suggestion/generic_user_provider.jsx
  components/suggestion/menu_action_provider.jsx
  components/suggestion/suggestion_box.jsx
  components/suggestion/suggestion_list.jsx
  i18n/en.json
  reducers/views/posts.js
  sass/components/_mentions.scss
  sass/components/_suggestion-list.scss
  sass/layout/_forms.scss
  sass/layout/_webhooks.scss
  sass/responsive/_mobile.scss
  sass/utils/_modifiers.scss
  stores/suggestion_store.jsx
  tests/components/__snapshots__/quick_switch_modal.test.jsx.snap
  tests/components/__snapshots__/textbox.test.jsx.snap
  tests/components/post_view/__snapshots__/message_attachment.test.jsx.snap
  tests/components/post_view/message_attachment.test.jsx
  utils/constants.jsx
  utils/utils.jsx
Labels: 3: Ready to Merge

#1733 MM-12066 Typing when not focused on an input goes to post textbox
  components/create_comment/create_comment.jsx
  components/create_comment/index.js
  components/create_post/create_post.jsx
  components/create_post/index.js
  tests/components/create_comment/create_comment.test.jsx
  tests/components/create_post/create_post.test.jsx
  tests/utils/post_utils.test.jsx
  utils/post_utils.jsx
Labels: 3: Ready to Merge

#1599 add copy link to copy to clipboard the token/url from hooks
  components/copy_text.jsx
  components/integrations/confirm_integration/confirm_integration.jsx
  components/integrations/installed_command.jsx
  components/integrations/installed_incoming_webhook.jsx
  components/integrations/installed_oauth_app.jsx
  components/integrations/installed_outgoing_webhook.jsx
  i18n/en.json
  tests/components/integrations/__snapshots__/confirm_integration.test.jsx.snap
  tests/components/integrations/__snapshots__/installed_command.test.jsx.snap
  tests/components/integrations/__snapshots__/installed_incoming_webhook.test.jsx.snap
  tests/components/integrations/__snapshots__/installed_oauth_app.test.jsx.snap
  tests/components/integrations/__snapshots__/installed_outgoing_webhook.test.jsx.snap
  utils/utils.jsx
Labels: 3: Ready to Merge

#1764 MM-6950: restore last viewed on logout
  actions/admin_actions.jsx
  actions/channel_actions.jsx
  actions/global_actions.jsx
  actions/local_storage.jsx
  components/admin_console/system_users/system_users_dropdown.jsx
  components/channel_header/index.js
  components/channel_layout/center_channel/index.js
  components/channel_view/index.js
  components/needs_team/index.js
  components/needs_team/needs_team.jsx
  components/user_settings/advanced/user_settings_advanced.jsx
  selectors/local_storage.js
  selectors/storage.js
  stores/local_storage_store.jsx
  tests/components/needs_team.test.jsx
  tests/stores/local_storage_store.test.jsx
  utils/constants.jsx
Labels: 2: Dev Review

#1753 MM-12278: Migrate Admin Console GitLab to declarative
  components/admin_console/admin_console.jsx
  components/admin_console/admin_definition.jsx
  components/admin_console/gitlab_settings.jsx
  i18n/en.json
Labels: 3: Ready to Merge

#1736 MM-11854 Commented on message for different webhook props
  components/post_view/commented_on/commented_on.jsx
  tests/components/post_view/__snapshots__/commented_on.test.jsx.snap
  tests/components/post_view/commented_on.test.jsx
Labels: 3: Ready to Merge

#1752 [MM-12272] Redirect user to default channel if logged in during email verification
  components/announcement_bar/announcement_bar.jsx
  components/do_verify_email/do_verify_email.jsx
Labels: 3: Ready to Merge

#1744 [MM-11162] Add mute icon to mobile view
  components/navbar/index.js
  components/navbar/navbar.jsx
  sass/layout/_navigation.scss
  tests/components/navbar/__snapshots__/navbar.test.jsx.snap
  tests/components/navbar/navbar.test.jsx
  utils/utils.jsx
Labels: 2: Dev Review

#1749 Add draft indicator in the channel sidebar and channel switcher
  components/sidebar/sidebar_channel/index.js
  components/sidebar/sidebar_channel/sidebar_channel.jsx
  components/sidebar/sidebar_channel_button_or_link/sidebar_channel_button_or_link.jsx
  components/sidebar/sidebar_channel_button_or_link/sidebar_channel_button_or_link_icon.jsx
  components/suggestion/switch_channel_provider.jsx
  components/svg/draft_icon.jsx
  i18n/en.json
  sass/layout/_sidebar-left.scss
  tests/components/sidebar/__snapshots__/sidebar_channel.test.jsx.snap
  tests/components/sidebar/__snapshots__/sidebar_channel_button_or_link.test.jsx.snap
  tests/components/sidebar/__snapshots__/sidebar_channel_button_or_link_icon.test.jsx.snap
  tests/components/sidebar/sidebar_channel.test.jsx
  tests/components/sidebar/sidebar_channel_button_or_link.test.jsx
  tests/components/sidebar/sidebar_channel_button_or_link_icon.test.jsx
Labels: 3: Ready to Merge

#1766 translations PR 20180924
  i18n/de.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/tr.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 3: Ready to Merge

#1746 MM-12053 Increase max height of post textbox
  components/create_comment/create_comment.jsx
  sass/layout/_post-right.scss
  sass/layout/_post.scss
  sass/responsive/_mobile.scss
Labels: 3: Ready to Merge

#1777 MM-12263 Add plugin FilesWillUpload hook
  components/file_upload/file_upload.jsx
  components/file_upload/index.js
  plugins/registry.js
  tests/components/file_upload/file_upload.test.jsx
Labels: 2: Dev Review

#1781 [MM-12336] Fix cursor on hover of navbar info icon
  components/navbar/navbar_info_button/navbar_info_button.jsx
  tests/components/navbar/__snapshots__/navbar_info_button.test.jsx.snap
Labels: 2: Dev Review

#1762 [MM-11959] Add feature to send code block on CTRL + ENTER
  components/create_comment/create_comment.jsx
  components/create_comment/index.js
  components/create_post/create_post.jsx
  components/create_post/index.js
  components/user_settings/advanced/code_block_ctrl_enter_section/code_block_ctrl_enter_section.jsx
  components/user_settings/advanced/code_block_ctrl_enter_section/index.js
  components/user_settings/advanced/user_settings_advanced.jsx
  i18n/en.json
  tests/components/user_settings/advanced_tab/__snapshots__/code_block_ctrl_enter_section.test.jsx.snap
  tests/components/user_settings/advanced_tab/code_block_ctrl_enter_section.test.jsx
  tests/utils/post_utils.test.jsx
  utils/constants.jsx
  utils/post_utils.jsx
Labels: 3: Ready to Merge

#1783 update redux to latest
  package-lock.json
  package.json
Labels: 3: Ready to Merge

#1769 MM-12057: Only show my own archived channels in the channel switcher
  components/suggestion/switch_channel_provider.jsx
Labels: 3: Ready to Merge

#1780 [MM-12335] Add period "." to admin console of gitlab client id description
  components/admin_console/admin_definition.jsx
  i18n/en.json
Labels: 3: Ready to Merge

#1776 Add Consecutive messages support in RHS
  components/rhs_comment/index.js
  components/rhs_comment/rhs_comment.jsx
  components/rhs_thread/rhs_thread.jsx
  sass/layout/_post.scss
Labels: 3: Ready to Merge

#1751 MM-12205: notify on session expiration
  actions/global_actions.jsx
  components/login/login_controller/login_controller.jsx
  components/root/root.jsx
  i18n/en.json
  sass/components/_alerts.scss
  stores/local_storage_store.jsx
  tests/components/login/login_controller/__snapshots__/login_controller.test.jsx.snap
  tests/components/login/login_controller/login_controller.test.jsx
  utils/utils.jsx
Labels: 3: Ready to Merge

#1713 [MM-4712] Add progress bar for uploads
  actions/file_actions.jsx
  components/create_comment/create_comment.jsx
  components/create_post/create_post.jsx
  components/file_preview/file_preview.jsx
  components/file_preview/file_upload_progress.jsx
  components/file_upload/file_upload.jsx
  components/svg/checkmark_icon.jsx
  sass/components/_files.scss
  tests/components/__snapshots__/file_preview.test.jsx.snap
  tests/components/__snapshots__/file_upload_progress.test.jsx.snap
  tests/components/create_comment/__snapshots__/create_comment.test.jsx.snap
  tests/components/create_comment/create_comment.test.jsx
  tests/components/create_post/__snapshots__/create_post.test.jsx.snap
  tests/components/create_post/create_post.test.jsx
  tests/components/file_preview.test.jsx
  tests/components/file_upload/file_upload.test.jsx
  tests/components/file_upload_progress.test.jsx
  utils/utils.jsx
Labels: 3: Ready to Merge, Setup Test Server

#1735 MM-12130: Create a new page for displaying terms of service
  actions/user_actions.jsx
  components/admin_console/admin_definition.jsx
  components/logged_in/index.js
  components/logged_in/logged_in.jsx
  components/login/login_controller/login_controller.jsx
  components/root/index.js
  components/root/root.jsx
  components/select_team/select_team.jsx
  components/terms_of_service/index.js
  components/terms_of_service/terms_of_service.jsx
  i18n/en.json
  package-lock.json
  sass/responsive/_mobile.scss
  sass/routes/_signup.scss
  tests/components/terms_of_service/__snapshots__/terms_of_service.test.jsx.snap
  tests/components/terms_of_service/terms_of_service.test.jsx
  utils/constants.jsx
Labels: 3: Ready to Merge, Setup Test Server

#1788 MM-12241 - Updating help text on DM Modal
  sass/components/_multi-select.scss
  sass/responsive/_mobile.scss
Labels: 3: Ready to Merge

#1773 MM-11954 Simplify "User's message" translation
  components/post_view/commented_on/commented_on.jsx
  i18n/en.json
  tests/components/post_view/__snapshots__/commented_on.test.jsx.snap
Labels: 3: Ready to Merge

#1793 MM-12308 - Updating search popover styling
  sass/components/_popover.scss
Labels: 2: Dev Review

#1789 Remove the reply bar in RHS
  components/rhs_comment/rhs_comment.jsx
  sass/layout/_post.scss
  sass/layout/_sidebar-right.scss
  sass/responsive/_tablet.scss
Labels: 3: Ready to Merge

#1779 [MM-12259] Remove one of two tooltips of unmute icon and replace with aria-label
  components/channel_header/channel_header.jsx
  tests/components/__snapshots__/channel_header.test.jsx.snap
Labels: 3: Ready to Merge

#1791 MM-12351 - Updating default webhooks appearance
  sass/layout/_webhooks.scss
Labels: 2: Dev Review

#1792 MM-12265 - Updating sidebar item css
  sass/layout/_sidebar-left.scss
Labels: 3: Ready to Merge

#1759 MM-12027 Adding paging for elasticsearch results.
  actions/views/rhs.js
  components/search_results/index.jsx
  components/search_results/search_results.jsx
  package-lock.json
  package.json
  reducers/views/rhs.js
  selectors/rhs.jsx
  tests/redux/actions/views/rhs.test.js
  tests/redux/reducers/views/rhs.test.js
Labels: 1: PM Review, 2: Dev Review, Setup Test Server
