Repository mattermost/mattermost-webapp, pull requests merged in 2018-03, with the labels that each got.

#866 Remove mm_config and mm_license global state from webapp, phase 2 (PR #4)
  stores/user_typing_store.jsx
  tests/utils/channel_utils.test.jsx
  tests/utils/utils.test.jsx
  utils/channel_utils.jsx
  utils/license_utils.jsx
  utils/post_utils.jsx
  utils/utils.jsx
Labels: 3: Ready to Merge

#885 Remove unused filtered_user_list component
  components/filtered_user_list.jsx
Labels: 3: Ready to Merge

#893 PLT-5270 Bold, italic and striked links should show link preview when available
  utils/text_formatting.jsx
  utils/utils.jsx
Labels: 3: Ready to Merge

#884 MM-9599 Don't update scroll position immediately after initial scroll
  components/post_view/post_list.jsx
Labels: 3: Ready to Merge

#883 Make ctrl work wherever cmd works on macOS.
  utils/utils.jsx
Labels: 3: Ready to Merge

#848 Discard any change to the storage if is older than the current one.
  actions/storage.js
  reducers/storage.js
  selectors/storage.js
  store/index.js
  tests/redux/actions/storage.test.js
  tests/redux/actions/views/create_comment.test.jsx
  tests/redux/reducers/storage.test.js
  tests/redux/selectors/rhs.test.js
  tests/redux/selectors/storage.test.js
Labels: 3: Ready to Merge

#880 [MM-9694] Replace event.keyCode deprecated attribute with event.key (with backward compatibility)
  components/channel_header/channel_header.jsx
  components/create_comment/create_comment.jsx
  components/create_post/create_post.jsx
  components/delete_modal_trigger.jsx
  components/edit_channel_header_modal/edit_channel_header_modal.jsx
  components/edit_channel_purpose_modal/edit_channel_purpose_modal.jsx
  components/edit_post_modal/edit_post_modal.jsx
  components/file_upload/file_upload.jsx
  components/invite_member_modal/invite_member_modal.jsx
  components/mfa/confirm.jsx
  components/multiselect/multiselect.jsx
  components/multiselect/multiselect_list.jsx
  components/navbar/navbar.jsx
  components/needs_team/needs_team.jsx
  components/new_channel_modal/new_channel_modal.jsx
  components/quick_switch_modal/quick_switch_modal.jsx
  components/search_bar/search_bar.jsx
  components/setting_item_max.jsx
  components/sidebar/sidebar.jsx
  components/suggestion/suggestion_box.jsx
  components/user_settings/modal/user_settings_modal.jsx
  components/user_settings/security/user_settings_security.jsx
  components/view_image/view_image.jsx
  stores/message_history_store.jsx
  tests/components/create_post/create_post.test.jsx
  tests/components/delete_modal_trigger.test.jsx
  tests/components/edit_channel_header_modal.test.jsx
  tests/components/edit_channel_purpose_modal.test.jsx
  tests/components/edit_post_modal.test.jsx
  tests/components/mfa/components/confirm_test.jsx
  tests/components/new_channel_modal.test.jsx
  tests/components/setting_item_max.test.jsx
  tests/components/sidebar/sidebar.test.jsx
  tests/components/view_image.test.jsx
  tests/utils/utils.test.jsx
  utils/constants.jsx
  utils/utils.jsx
Labels: 3: Ready to Merge

#902 Removed unnused stores (message_history and opengraph)
  stores/message_history_store.jsx
  stores/opengraph_store.jsx
Labels: 3: Ready to Merge

#900 translations PR 20180306
  i18n/de.json
  i18n/en.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ru.json
  i18n/tr.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 3: Ready to Merge

#901 MM-9711: Fix post attachment collapsing
  components/post_view/post_attachment.jsx
Labels: 3: Ready to Merge

#899 GH-8402: Invalid latex code, break the entire app (Fixed)
  components/latex_block.jsx
  i18n/en.json
Labels: 1: PM Review, 3: Ready to Merge

#903 Update mattermost-redux to latest webapp-4.8
  package.json
  yarn.lock
Labels: 3: Ready to Merge

#909 T-8 merge release-4.8 into master
  components/latex_block.jsx
  components/post_view/post_attachment.jsx
  components/post_view/post_list.jsx
  i18n/de.json
  i18n/en.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ru.json
  i18n/tr.json
  i18n/zh-CN.json
  i18n/zh-TW.json
  utils/utils.jsx
Labels: 2: Dev Review

#896 GH-8402: Invalid latex code, break the entire app (Fixed)
  components/latex_block.jsx
  i18n/en.json
Labels: 3: Ready to Merge

#879 Return cursor to reply thread input box after deleting a reply from the right-hand sidebar (#8336)
  actions/global_actions.jsx
  components/delete_post_modal.jsx
  components/dot_menu/dot_menu.jsx
  components/dot_menu/dot_menu_item.jsx
  components/rhs_comment/rhs_comment.jsx
Labels: 3: Ready to Merge

#916 Revert announcement bar APIv3 notice
  components/announcement_bar/announcement_bar.jsx
  components/announcement_bar/index.js
  utils/constants.jsx
Labels: 3: Ready to Merge

#915 Release 4.8 fixes
  components/textbox.jsx
  sass/components/_modal.scss
  sass/responsive/_mobile.scss
Labels: 3: Ready to Merge

#911 [MM-9757] Place focus to search_bar input after clicking search icon on tablet view
  components/sidebar_right/sidebar_right.jsx
  components/webrtc/controller/webrtc_controller.jsx
Labels: 3: Ready to Merge

#906 MM-9734 Fix permalink view loading from search results
  components/permalink_view.jsx
Labels: 3: Ready to Merge

#898 MM-9704 - Updating custom emoji css
  components/emoji_picker/components/emoji_picker_item.jsx
  sass/components/_emojisprite.scss
  sass/components/_emoticons.scss
Labels: 3: Ready to Merge

#923 MM-9721 Update settings text when push notifications are disabled on the server
  components/user_settings/notifications/user_settings_notifications.jsx
  i18n/en.json
Labels: 3: Ready to Merge

#918 Added 'make restart'
  Makefile
Labels: 3: Ready to Merge

#353 [PLT-7776] Render at-mentions by the teammate name display
  components/at_mention/at_mention.jsx
  components/post_markdown/system_message_helpers.jsx
  components/user_profile.jsx
  utils/utils.jsx
Labels: 3: Ready to Merge

#747 MM-9274- Add sort=status to Popover List Member call
  components/popover_list_members/popover_list_members.jsx
  tests/utils/utils.test.jsx
  utils/constants.jsx
  yarn.lock
Labels: 3: Ready to Merge

#928 MM-8564 Handle permalinks pointing to incorrect teams
  actions/global_actions.jsx
Labels: 3: Ready to Merge

#927 Update release-4.8 to latest mattermost-redux
  yarn.lock
Labels: 3: Ready to Merge

#932 Clear redux cache before yarn install
  Makefile
Labels: 2: Dev Review

#912 open the main menu during tutorial; fix JS error
  components/sidebar/header/dropdown/sidebar_header_dropdown.jsx
  components/sidebar/header/sidebar_header.jsx
Labels: 3: Ready to Merge

#921 MM-9755: Fix for bouncing new channel modal. Fix for command+enter co…
  components/create_comment/create_comment.jsx
  components/create_post/create_post.jsx
  components/edit_channel_header_modal/edit_channel_header_modal.jsx
  components/edit_channel_purpose_modal/edit_channel_purpose_modal.jsx
  components/edit_post_modal/edit_post_modal.jsx
  components/new_channel_modal/new_channel_modal.jsx
  utils/utils.jsx
Labels: 3: Ready to Merge

#924 MM-9775 Fix race when flagging/unflagging posts
  actions/post_actions.jsx
Labels: 3: Ready to Merge

#922 [MM-9710] Add flex to file-preview (loading) so it will not collapse when container is combined with loaded and loading files
  sass/components/_files.scss
Labels: 3: Ready to Merge

#917 MM-9754 Mark current channel as read from viewed_channel events if window not active
  actions/websocket_actions.jsx
Labels: 3: Ready to Merge

#931 MM-9672: Don't update draft state if there was a server error.
  components/create_comment/create_comment.jsx
Labels: 2: Dev Review

#930 [MM-9785] Fix "add user to channel" from RHS when viewing different channel on center
  components/post_view/post_add_channel_member/index.js
  components/post_view/post_add_channel_member/post_add_channel_member.jsx
  tests/components/post_view/post_add_channel_member/__snapshots__/post_add_channel_member.test.jsx.snap
  tests/components/post_view/post_add_channel_member/post_add_channel_member.test.jsx
Labels: 2: Dev Review

#925 [MM-9771] Cursor focus doesn't return to comment box on the RHS after editing a message on the RHS by removing all of the text in the comment
  actions/post_actions.jsx
  components/dot_menu/dot_menu.jsx
  components/dot_menu/dot_menu_edit.jsx
  components/edit_post_modal/edit_post_modal.jsx
  tests/components/dot_menu/__snapshots__/dot_menu.test.jsx.snap
  tests/components/dot_menu/dot_menu.test.jsx
  tests/components/dot_menu/dot_menu_edit.test.jsx
  tests/redux/actions/posts.test.js
Labels: 3: Ready to Merge

#929 [MM-9783] Fix error when removing file which is on going upload
  components/create_comment/create_comment.jsx
  components/create_post/create_post.jsx
  components/file_upload/file_upload.jsx
  components/file_upload/index.js
Labels: 3: Ready to Merge

#913 MM-9763: fix regression in connecting config.ShowEmailAddress
  components/profile_popover/index.js
  tests/plugins/__snapshots__/pluggable.test.jsx.snap
Labels: 3: Ready to Merge

#943 Fix backticks in System Console help text
  components/admin_console/storage_settings.jsx
  i18n/en.json
Labels: 2: Dev Review

#939 MM-9780: Show name in "removed from team" system message.
  components/post_markdown/system_message_helpers.jsx
Labels: 3: Ready to Merge

#936 MM-9773 Fixed permalinks on IE11
  utils/markdown/renderer.jsx
  utils/utils.jsx
Labels: 3: Ready to Merge

#920 Fix JS errors on draft - post or comment
  actions/views/create_comment.jsx
  components/create_comment/index.js
  components/create_post/index.js
  selectors/rhs.jsx
Labels: 3: Ready to Merge

#940 MM-9756: Don't show flag in menu on system messages.
  components/dot_menu/dot_menu.jsx
  tests/components/dot_menu/__snapshots__/dot_menu_mobile.test.jsx.snap
Labels: 3: Ready to Merge

#947 MM-9743 Fix RHS focus when deleting and editing posts
  actions/views/create_comment.jsx
  components/create_comment/create_comment.jsx
  tests/redux/actions/views/create_comment.test.jsx
Labels: 3: Ready to Merge

#946 MM-9784 Filter out current user when adding member to GM
  components/more_direct_channels/more_direct_channels.jsx
Labels: 3: Ready to Merge

#955 Merge release-4.8 into master
  Makefile
  actions/post_actions.jsx
  actions/views/create_comment.jsx
  actions/websocket_actions.jsx
  components/announcement_bar/announcement_bar.jsx
  components/announcement_bar/index.js
  components/create_comment/create_comment.jsx
  components/create_comment/index.js
  components/create_post/create_post.jsx
  components/create_post/index.js
  components/edit_channel_header_modal/edit_channel_header_modal.jsx
  components/edit_channel_purpose_modal/edit_channel_purpose_modal.jsx
  components/edit_post_modal/edit_post_modal.jsx
  components/emoji_picker/components/emoji_picker_item.jsx
  components/latex_block.jsx
  components/new_channel_modal/new_channel_modal.jsx
  components/permalink_view.jsx
  components/post_markdown/system_message_helpers.jsx
  components/sidebar/header/dropdown/sidebar_header_dropdown.jsx
  components/sidebar/header/sidebar_header.jsx
  components/sidebar_right/sidebar_right.jsx
  components/textbox.jsx
  components/webrtc/controller/webrtc_controller.jsx
  i18n/en.json
  sass/components/_emojisprite.scss
  sass/components/_emoticons.scss
  sass/components/_files.scss
  sass/components/_modal.scss
  sass/layout/_post.scss
  sass/responsive/_mobile.scss
  selectors/rhs.jsx
  utils/constants.jsx
  utils/markdown/renderer.jsx
  utils/utils.jsx
  webpack.config.js
Labels: 2: Dev Review

#944 MM-9816 Fix PDF previews on Firefox
  components/pdf_preview.jsx
  root.jsx
Labels: 3: Ready to Merge

#945 MM-9819 Kept cursor in the correct place on IE11/Windows 7 when typing
  components/autosize_textarea.jsx
  components/quick_input.jsx
  utils/user_agent.jsx
Labels: 3: Ready to Merge

#950 translations PR 20180314
  i18n/de.json
  i18n/en.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ru.json
  i18n/tr.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 3: Ready to Merge

#952 MM-9825: Show again compliance reports
  components/admin_console/compliance_reports/index.js
Labels: 3: Ready to Merge

#953 [MM-9848] Fix search bar focus after clicking pinned or flagged post button
  components/sidebar_right/sidebar_right.jsx
Labels: 3: Ready to Merge

#954 If experimental auth change setting isn't set, default to on
  components/user_settings/security/index.js
Labels: 3: Ready to Merge

#958 MM-9818 Fix blank channel header when leaving team
  actions/global_actions.jsx
Labels: 3: Ready to Merge

#956 MM-9845: Moves event handlers back to img tag.
  components/emoji_picker/components/emoji_picker_item.jsx
Labels: 3: Ready to Merge

#960 Update mattermost-redux to latest webapp-4.8
  yarn.lock
Labels: 3: Ready to Merge

#959 Updating help text on custom emoji creation page
  components/emoji/emoji_list/emoji_list.jsx
  i18n/en.json
Labels: 3: Ready to Merge

#963 Merge branch 'release-4.8' into master
  actions/global_actions.jsx
  components/admin_console/compliance_reports/index.js
  components/autosize_textarea.jsx
  components/emoji_picker/components/emoji_picker_item.jsx
  components/pdf_preview.jsx
  components/quick_input.jsx
  components/sidebar_right/sidebar_right.jsx
  components/user_settings/security/index.js
  i18n/de.json
  i18n/en.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ru.json
  i18n/tr.json
  i18n/zh-CN.json
  i18n/zh-TW.json
  root.jsx
  utils/user_agent.jsx
  yarn.lock
Labels: 2: Dev Review

#961 [MM-9783] Fix file upload removal by setting intl as context types instead of props to easily access component via ref
  components/create_comment/create_comment.jsx
  components/create_post/create_post.jsx
  components/file_upload/file_upload.jsx
  tests/components/create_comment/__snapshots__/create_comment.test.jsx.snap
  tests/components/create_post/__snapshots__/create_post.test.jsx.snap
  tests/components/file_upload/__snapshots__/file_upload.test.jsx.snap
  tests/components/file_upload/file_upload.test.jsx
Labels: 3: Ready to Merge

#942 MM-9776: Don't sync search highlighting with search terms.
  components/search_bar/search_bar.jsx
Labels: 3: Ready to Merge

#905 Migrate admin console to a new declarative way (plugins schema based)
  components/admin_console/admin_console.jsx
  components/admin_console/admin_definition.jsx
  components/admin_console/admin_definition_constants.jsx
  components/admin_console/compliance_settings.jsx
  components/admin_console/configuration_settings.jsx
  components/admin_console/connection_security_dropdown_setting.jsx
  components/admin_console/custom_integrations_settings.jsx
  components/admin_console/custom_plugin_settings/custom_plugin_settings.jsx
  components/admin_console/custom_plugin_settings/index.js
  components/admin_console/dropdown_setting.jsx
  components/admin_console/email_authentication_settings.jsx
  components/admin_console/localization_settings.jsx
  components/admin_console/mfa_settings.jsx
  components/admin_console/privacy_settings.jsx
  components/admin_console/schema_admin_settings.jsx
  components/admin_console/text_setting.jsx
  components/admin_console/users_and_teams_settings.jsx
  package.json
  tests/components/admin_console/__snapshots__/custom_plugin_settings.test.jsx.snap
  tests/components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
  tests/components/admin_console/admin_definition.test.jsx
  tests/components/admin_console/custom_plugin_settings.test.jsx
  tests/components/admin_console/schema_admin_settings.test.jsx
  utils/constants.jsx
  yarn.lock
Labels: 3: Ready to Merge

#965 Update help text for Google API Key
  components/admin_console/external_service_settings.jsx
  i18n/en.json
Labels: 3: Ready to Merge

#910 Removing user typing store
  actions/global_actions.jsx
  actions/websocket_actions.jsx
  components/create_comment/create_comment.jsx
  components/create_post/create_post.jsx
  components/msg_typing.jsx
  components/msg_typing/index.js
  components/msg_typing/msg_typing.jsx
  stores/post_store.jsx
  stores/user_typing_store.jsx
  tests/components/__snapshots__/msg_typing.test.jsx.snap
  tests/components/create_comment/__snapshots__/create_comment.test.jsx.snap
  tests/components/create_post/__snapshots__/create_post.test.jsx.snap
  tests/components/msg_typing.test.jsx
  utils/constants.jsx
Labels: 2: Dev Review

#966 Fix missing messages
  components/admin_console/ldap_settings.jsx
  i18n/en.json
Labels: 3: Ready to Merge

#948 MM-9766 Export text formatting as 'post-utils' for use in plugins
  plugins/index.js
Labels: 3: Ready to Merge

#968 Updating mattermost-redux in yarn.lock
  yarn.lock
Labels: 3: Ready to Merge

#967 Warning when you are uploading 0 bytes files.
  components/file_upload/file_upload.jsx
  i18n/en.json
Labels: 2: Dev Review

#753 fix issues #8210
  components/audit_table.jsx
  i18n/en.json
Labels: 3: Ready to Merge

#951 MM-9814 Fix/change element IDs of SettingItemMin and SettingItemMax for end-to-end testing
  components/channel_notifications_modal/components/collapse_view.jsx
  components/setting_item_max.jsx
  components/setting_item_min.jsx
  tests/components/__snapshots__/setting_item_max.test.jsx.snap
  tests/components/__snapshots__/setting_item_min.test.jsx.snap
  tests/components/channel_notifications_modal/__snapshots__/collapse_view.test.jsx.snap
  tests/components/channel_notifications_modal/__snapshots__/expand_view.test.jsx.snap
  tests/components/user_settings/__snapshots__/email_notification_setting.test.jsx.snap
Labels: 3: Ready to Merge

#926 Cleanup jquery from post_attachment.jsx
  components/post_view/post_attachment.jsx
Labels: 3: Ready to Merge, Awaiting Submitter Action

#964 Update help text for outgoing webhooks callback URL setting
  components/integrations/abstract_outgoing_webhook.jsx
  i18n/en.json
Labels: 3: Ready to Merge

#970 Migrate completely custom sections from the admin to declarative approach.
  components/admin_console/admin_console.jsx
  components/admin_console/admin_definition.jsx
  components/admin_console/admin_definition_constants.jsx
  components/admin_console/log_settings.jsx
  components/admin_console/schema_admin_settings.jsx
  tests/components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
  tests/components/admin_console/admin_definition.test.jsx
  tests/components/admin_console/schema_admin_settings.test.jsx
  utils/constants.jsx
Labels: 3: Ready to Merge

#973 MM-9696 Modifying about Mattermost dialog to show app version, db version, and build number explicitly.
  components/about_build_modal/about_build_modal.jsx
  i18n/en.json
  tests/components/__snapshots__/about_build_modal.test.jsx.snap
  tests/components/about_build_modal.test.jsx
Labels: 1: PM Review, 3: Ready to Merge

#976 Fix make stop
  Makefile
Labels: 2: Dev Review

#975 Add component test to PostAttachment
  tests/components/post_view/__snapshots__/post_attachment.test.jsx.snap
  tests/components/post_view/post_attachment.test.jsx
Labels: 3: Ready to Merge

#892 Show Unread Channels in Channel Selector when input is empty
  components/quick_switch_modal/quick_switch_modal.jsx
  components/suggestion/suggestion_box.jsx
  components/suggestion/switch_channel_provider.jsx
  i18n/en.json
  sass/components/_suggestion-list.scss
  tests/components/__snapshots__/textbox.test.jsx.snap
  utils/constants.jsx
Labels: 3: Ready to Merge

#982 [MM-9844] Make site description (config.CustomDescriptionText) not dependent from config.EnableCustomBrand
  components/admin_console/custom_brand_settings.jsx
  components/common/site_name_and_description.jsx
  components/create_team/create_team.jsx
  components/create_team/index.js
  components/login/login_controller/login_controller.jsx
  components/select_team/index.js
  components/select_team/select_team.jsx
  components/signup/signup_email/signup_email.jsx
  components/signup/signup_ldap/index.js
  components/signup/signup_ldap/signup_ldap.jsx
  tests/components/common/__snapshots__/site_name_and_description.test.jsx.snap
  tests/components/common/site_name_and_description.test.jsx
  tests/components/create_team/__snapshots__/create_team.test.jsx.snap
  tests/components/create_team/create_team.test.jsx
Labels: 3: Ready to Merge

#986 Fix unit tests warnings that prolong test time
  components/channel_members_modal/channel_members_modal.test.jsx
  tests/components/__snapshots__/edit_post_modal.test.jsx.snap
  tests/components/channel_notifications_modal/__snapshots__/describe.test.jsx.snap
  tests/components/channel_notifications_modal/__snapshots__/expand_view.test.jsx.snap
  tests/components/channel_notifications_modal/describe.test.jsx
  tests/components/channel_notifications_modal/expand_view.test.jsx
  tests/components/dot_menu/__snapshots__/dot_menu_item.test.jsx.snap
  tests/components/dot_menu/dot_menu_item.test.jsx
  tests/components/edit_channel_purpose_modal.test.jsx
  tests/components/edit_post_modal.test.jsx
  tests/components/post_view/__snapshots__/date_separator.test.jsx.snap
  tests/components/post_view/date_separator.test.jsx
  tests/components/sidebar/__snapshots__/sidebar.test.jsx.snap
  tests/components/sidebar/sidebar.test.jsx
  tests/components/sidebar/sidebar_channel.test.jsx
  tests/components/team_general_tab.test.jsx
  tests/plugins/__snapshots__/post_type.test.jsx.snap
  tests/plugins/post_type.test.jsx
Labels: 2: Dev Review

#987 Migrate permalink view into redux-style and remove jquery
  components/permalink_view.jsx
  components/permalink_view/index.js
  components/permalink_view/permalink_view.jsx
  tests/components/__snapshots__/permalink_view.test.jsx.snap
  tests/components/permalink_view.test.jsx
Labels: 2: Dev Review

#979 translations PR 20180319
  i18n/de.json
  i18n/en.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ru.json
  i18n/tr.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 2: Dev Review

#817 MM-8840: Add GlobalRelay Configuration Settings
  components/admin_console/message_export_settings.jsx
  i18n/en.json
  tests/components/admin_console/__snapshots__/message_export_settings.test.jsx.snap
  tests/components/admin_console/message_export_settings.test.jsx
Labels: 3: Ready to Merge

#988 MM-9804: simplify ExperimentalEnableAuthenticationTransfer comparisons
  components/create_post/index.js
  components/file_attachment/index.js
  components/file_info_preview/index.js
  components/file_upload/index.js
  components/user_settings/security/index.js
  components/view_image/index.js
  tests/utils/file_utils.test.jsx
  utils/file_utils.jsx
Labels: 2: Dev Review

#985 Minor Ui fixes
  sass/layout/_team-sidebar.scss
  utils/utils.jsx
Labels: 2: Dev Review

#984 Fix typos
  components/admin_console/admin_definition.jsx
  components/admin_console/cluster_settings.jsx
  components/admin_console/custom_brand_settings.jsx
  components/admin_console/database_settings.jsx
  components/admin_console/external_service_settings.jsx
  components/admin_console/gitlab_settings.jsx
  components/admin_console/ldap_settings.jsx
  components/admin_console/metrics_settings.jsx
  components/admin_console/oauth_settings.jsx
  components/admin_console/password_settings.jsx
  components/admin_console/rate_settings.jsx
  components/admin_console/saml_settings.jsx
  components/admin_console/session_settings.jsx
  components/admin_console/storage_settings.jsx
  components/admin_console/webrtc_settings.jsx
  i18n/en.json
Labels: 2: Dev Review

#989 Migrate delete_post_modal.jsx to be pure and use Redux
  actions/global_actions.jsx
  actions/post_actions.jsx
  components/channel_layout/channel_controller.jsx
  components/delete_post_modal/delete_post_modal.jsx
  components/delete_post_modal/index.js
  components/dot_menu/dot_menu.jsx
  components/dot_menu/dot_menu_item.jsx
  components/dot_menu/index.js
  components/edit_post_modal/edit_post_modal.jsx
  components/edit_post_modal/index.js
  tests/components/__snapshots__/delete_post_modal.test.jsx.snap
  tests/components/delete_post_modal.test.jsx
  tests/components/dot_menu/__snapshots__/dot_menu.test.jsx.snap
  tests/components/dot_menu/dot_menu.test.jsx
  tests/components/dot_menu/dot_menu_item.test.jsx
  tests/components/edit_post_modal.test.jsx
  utils/constants.jsx
Labels: 3: Ready to Merge

#518 GH-7659: Migrate channel_notifications_model.jsx to be pure and use Redux
  actions/channel_actions.jsx
  components/channel_notifications_modal/channel_notifications_modal.jsx
  components/channel_notifications_modal/index.js
  tests/components/__snapshots__/channel_notifications_modal.test.jsx.snap
  tests/components/channel_notifications_modal.test.jsx
Labels: 3: Ready to Merge

#992 MM-9843: improve semantics around Forward80To443
  components/admin_console/admin_definition.jsx
  components/admin_console/boolean_setting.jsx
  components/admin_console/schema_admin_settings.jsx
  i18n/en.json
Labels: 2: Dev Review

#990 Define prop-types of "match" from react-router
  .eslintrc.json
  components/admin_console/admin_console.jsx
  components/backstage/backstage_controller.jsx
  components/channel_layout/channel_identifier_router.jsx
  components/channel_view/channel_view.jsx
  components/claim/claim_controller.jsx
  components/create_team/create_team.jsx
  components/help/help_controller.jsx
  components/integrations/commands_container/commands_container.jsx
  components/mfa/mfa_controller/mfa_controller.jsx
  components/needs_team/needs_team.jsx
  components/permalink_view/permalink_view.jsx
Labels: 2: Dev Review

#995 MM-9932: Multiple advanced permissions bug fixes.
  components/channel_header/channel_header.jsx
  components/permissions_gates/channel_permission_gate/channel_permission_gate.jsx
  components/permissions_gates/system_permission_gate/system_permission_gate.jsx
  components/permissions_gates/team_permission_gate/team_permission_gate.jsx
Labels: 2: Dev Review

#974 MM-9772: close rhs on mobile view post time click
  components/post_view/post_time.jsx
Labels: 3: Ready to Merge

#999 Fix channels edit on dot menu
  utils/post_utils.jsx
Labels: 2: Dev Review

#1001 Fix header dropdown menu
  components/sidebar/header/dropdown/sidebar_header_dropdown.jsx
  components/sidebar/header/sidebar_header.jsx
Labels: 2: Dev Review

#1002 Fix incomming webhooks typo
  components/integrations/installed_incoming_webhooks/installed_incoming_webhooks.jsx
Labels: 2: Dev Review

#1000 Fix channel selector for reactions permissions
  components/post_view/post_info/index.js
  components/post_view/reaction_list/index.js
Labels: 2: Dev Review

#1003 Adds missing constant
  components/channel_members_dropdown/index.js
Labels: 2: Dev Review

#998 MM-9801 Update mattermost-redux and handle perf changes
  components/post_view/index.js
  tests/redux/actions/views/create_comment.test.jsx
  yarn.lock
Labels: 2: Dev Review

#1005 translations PR 20180326
  i18n/de.json
  i18n/en.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ru.json
  i18n/tr.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 2: Dev Review

#1006 Use the custom integrations page and users/teams page, not the declartive definition.
  components/admin_console/admin_console.jsx
  components/admin_console/admin_definition.jsx
Labels: 2: Dev Review

#1010 Circular dep fix
  actions/channel_actions.jsx
  components/sidebar/sidebar_channel/index.js
  components/suggestion/switch_channel_provider.jsx
  stores/channel_store.jsx
  yarn.lock
Labels: 2: Dev Review

#1011 MM-9787: remove redundant class manipulation, now handled by Redux
  actions/global_actions.jsx
Labels: 3: Ready to Merge

#831 Remove write access to town square. Hide it when no unread messages.
  components/channel_header/channel_header.jsx
  components/channel_header/index.js
  components/dot_menu/dot_menu.jsx
  components/post_view/channel_intro_message/channel_intro_message.jsx
  components/post_view/post_body/index.js
  components/post_view/post_body/post_body.jsx
  components/post_view/post_info/index.js
  components/post_view/post_info/post_info.jsx
  components/post_view/reaction_list/index.js
  components/rhs_comment/index.js
  components/rhs_comment/rhs_comment.jsx
  components/rhs_root_post/index.js
  components/rhs_root_post/rhs_root_post.jsx
  components/sidebar/sidebar_channel/index.js
  components/sidebar/sidebar_channel/sidebar_channel.jsx
  sass/layout/_post.scss
Labels: 3: Ready to Merge

#1022 Fix redux version (again).
  yarn.lock
Labels: 3: Ready to Merge, DO NOT MERGE

#196 [PLT-4340] Channel Mute and "/mute" command #7617 #7713
  actions/notification_actions.jsx
  actions/websocket_actions.jsx
  components/channel_header/channel_header.jsx
  components/channel_header/index.js
  components/channel_notifications_modal/channel_notifications_modal.jsx
  components/channel_notifications_modal/components/describe.jsx
  components/channel_notifications_modal/components/expand_view.jsx
  components/channel_notifications_modal/components/extra_info.jsx
  components/channel_notifications_modal/components/section_title.jsx
  components/sidebar/sidebar_channel/index.js
  components/sidebar/sidebar_channel/sidebar_channel.jsx
  i18n/en.json
  sass/layout/_headers.scss
  sass/layout/_sidebar-left.scss
  tests/components/__snapshots__/channel_notifications_modal.test.jsx.snap
  tests/components/channel_notifications_modal/__snapshots__/describe.test.jsx.snap
  tests/components/channel_notifications_modal/__snapshots__/expand_view.test.jsx.snap
  tests/components/channel_notifications_modal/__snapshots__/extra_info.test.jsx.snap
  tests/components/channel_notifications_modal/__snapshots__/section_title.test.jsx.snap
  utils/constants.jsx
  yarn.lock
Labels: 2: Dev Review, Hacktoberfest

#994 MM-9781 Get statuses from redux for PopoverListMembers
  components/member_list_channel/member_list_channel.jsx
  components/popover_list_members/index.js
  components/popover_list_members/popover_list_members.jsx
  components/popover_list_members/popover_list_members_item.jsx
  tests/components/__snapshots__/popover_list_members.test.jsx.snap
  tests/components/popover_list_members.test.jsx
  tests/utils/utils.test.jsx
  utils/constants.jsx
  utils/utils.jsx
Labels: 2: Dev Review

#1021 Bug fixes
  sass/layout/_sidebar-left.scss
  sass/responsive/_tablet.scss
Labels: 3: Ready to Merge

#1026 Update mattermost-redux to point to master
  package.json
  yarn.lock
Labels: 3: Ready to Merge

#997 MM-9950 - Updating header UI
  components/svg/mentions_icon.jsx
  components/svg/search_icon.jsx
  sass/components/_search.scss
  sass/layout/_headers.scss
  sass/layout/_sidebar-right.scss
  sass/responsive/_tablet.scss
Labels: 2: Dev Review

#1013 MM-9969 Re-add post removal for user performing the delete
  actions/post_actions.jsx
  components/delete_post_modal/delete_post_modal.jsx
  components/delete_post_modal/index.js
  tests/components/delete_post_modal.test.jsx
Labels: 2: Dev Review

#1030 Bug fixes
  components/admin_console/admin_console.jsx
  sass/layout/_headers.scss
  sass/routes/_admin-console.scss
Labels: 2: Dev Review

#1031 MM-10001 Channel mute hide desktop and push settings
  components/channel_notifications_modal/channel_notifications_modal.jsx
  tests/components/__snapshots__/channel_notifications_modal.test.jsx.snap
Labels: 3: Ready to Merge
