Repository mattermost/mattermost-webapp, pull requests merged in 2018-11, with the labels that each got.

#1972 MM-12429 Add LDAP/AD create account label when redirected from sign-up to login
  components/login/login_controller/login_controller.jsx
  components/signup/signup_controller/signup_controller.jsx
  i18n/en.json
  sass/components/_alerts.scss
  utils/constants.jsx
Labels: 3: Ready to Merge

#1982 MM-12838: Make hashtag highlighting case insensitive.
  tests/utils/text_formatting.test.jsx
  utils/text_formatting.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#1952 Remove flux store usages from utils
  components/logged_in/index.js
  components/needs_team/index.js
  tests/utils/route.test.js
  utils/post_utils.jsx
  utils/route.jsx
  utils/utils.jsx
Labels: 3: Ready to Merge, Tests: Done

#1932 MM-12677 Removing SuggestionStore
  .babelrc
  actions/global_actions.jsx
  actions/integration_actions.jsx
  components/create_post/create_post.jsx
  components/profile_popover/profile_popover.jsx
  components/suggestion/at_mention_provider.jsx
  components/suggestion/channel_mention_provider.jsx
  components/suggestion/command_provider.jsx
  components/suggestion/emoticon_provider.jsx
  components/suggestion/generic_channel_provider.jsx
  components/suggestion/generic_user_provider.jsx
  components/suggestion/menu_action_provider.jsx
  components/suggestion/provider.jsx
  components/suggestion/search_channel_provider.jsx
  components/suggestion/search_date_provider.jsx
  components/suggestion/search_suggestion_list.jsx
  components/suggestion/search_user_provider.jsx
  components/suggestion/suggestion_box.jsx
  components/suggestion/suggestion_date.jsx
  components/suggestion/suggestion_list.jsx
  components/suggestion/switch_channel_provider.jsx
  components/suggestion/switch_team_provider.jsx
  components/suggestion/timezone_provider.jsx
  components/textbox.jsx
  stores/suggestion_store.jsx
  tests/components/__snapshots__/edit_channel_header_modal.test.jsx.snap
  tests/components/__snapshots__/edit_post_modal.test.jsx.snap
  tests/components/__snapshots__/textbox.test.jsx.snap
  tests/components/create_post/__snapshots__/create_post.test.jsx.snap
  tests/stores/suggestion_store.test.jsx
Labels: 3: Ready to Merge, Tests: Done

#1957 [MM-12715] Migrate searchForTerm into redux-style action
  actions/command.js
  actions/post_actions.jsx
  tests/redux/actions/post_actions.test.js
  utils/utils.jsx
Labels: 3: Ready to Merge, QA Review

#1920 MM-12239 Remove "Plugins > Configuration" page, move enabling plugins setting to the Management page
  components/admin_console/admin_console.jsx
  components/admin_console/admin_definition.jsx
  components/admin_console/admin_sidebar/admin_sidebar.jsx
  components/admin_console/plugin_management/plugin_management.jsx
  i18n/en.json
  tests/components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.jsx.snap
  tests/components/admin_console/plugin_management/__snapshots__/plugin_management.test.jsx.snap
Labels: 2: Dev Review, Docs: Needed, Hacktoberfest

#1959 MM-12772 - Updating post header css
  sass/layout/_post.scss
Labels: 3: Ready to Merge, CherryPickApproved

#1961 MM-12776 - Updating comments in RHS (compact view)
  sass/layout/_post-right.scss
Labels: 3: Ready to Merge, CherryPickApproved, Tests: Done

#1989 MM-12708: unify sign-in change redirection
  components/claim/components/email_to_ldap.jsx
  components/claim/components/email_to_oauth.jsx
  components/claim/components/ldap_to_email.jsx
  components/claim/components/oauth_to_email.jsx
  components/login/login_controller/login_controller.jsx
  tests/components/login/login_controller/__snapshots__/login_controller.test.jsx.snap
  tests/components/login/login_controller/login_controller.test.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2000 MM-12493: work around Desktop/Chromium rendering issue
  sass/layout/_sidebar-left.scss
Labels: 3: Ready to Merge, CherryPickApproved

#1954 Remove flux usages from email invite modal
  actions/global_actions.jsx
  components/channel_layout/channel_controller.jsx
  components/invite_member_modal/index.js
  components/invite_member_modal/invite_member_modal.jsx
  components/sidebar/header/dropdown/sidebar_header_dropdown.jsx
  components/sidebar_right_menu/sidebar_right_menu.jsx
  components/tutorial/tutorial_intro_screens/tutorial_intro_screens.jsx
  stores/modal_store.jsx
  tests/plugins/__snapshots__/main_menu_action.test.jsx.snap
  utils/constants.jsx
Labels: 3: Ready to Merge, Tests: Done

#1991 MM-12840 Remove the last usages of the flux stores
  actions/global_actions.jsx
  actions/views/rhs.js
  components/analytics/system_analytics/index.js
  components/analytics/system_analytics/system_analytics.jsx
  components/analytics/team_analytics/index.js
  components/analytics/team_analytics/team_analytics.jsx
  components/integrations/abstract_outgoing_webhook.jsx
  components/logged_in/index.js
  components/logged_in/logged_in.jsx
  components/login/login_controller/index.js
  components/login/login_controller/login_controller.jsx
  components/popover_list_members/index.js
  components/popover_list_members/popover_list_members.jsx
  components/post_markdown/index.js
  components/post_markdown/post_markdown.jsx
  components/post_markdown/system_message_helpers.jsx
  components/post_view/post/index.js
  components/post_view/post/post.jsx
  components/post_view/post_info/post_info.jsx
  components/post_view/post_time/index.js
  components/post_view/post_time/post_time.jsx
  components/rhs_comment/rhs_comment.jsx
  components/rhs_root_post/index.js
  components/rhs_root_post/rhs_root_post.jsx
  components/search_results_item/search_results_item.jsx
  components/sidebar_right/index.js
  tests/components/__snapshots__/search_results_item.test.jsx.snap
  tests/components/logged_in/logged_in.test.jsx
  tests/components/post_view/post_info/__snapshots__/post_info.test.jsx.snap
Labels: 3: Ready to Merge, Tests: Done

#1939 Fix OOO refresh logic that does not always display confirmation modal.
  actions/user_actions.jsx
  components/reset_status_modal/reset_status_modal.jsx
  tests/components/__snapshots__/reset_status_modal.test.jsx.snap
Labels: 3: Ready to Merge, CherryPickApproved

#1999 Add a default timezone 'Etc/UTC' for tests
  tests/components/__snapshots__/shortcuts_modal.test.jsx.snap
  tests/components/__snapshots__/toggle_modal_button_redux.test.jsx.snap
  tests/components/admin_console/request_button/__snapshots__/request_button.test.jsx.snap
  tests/components/navbar/__snapshots__/navbar_info_button.test.jsx.snap
  tests/components/post_view/__snapshots__/date_separator.test.jsx.snap
  tests/components/user_settings/__snapshots__/email_notification_setting.test.jsx.snap
  tests/components/user_settings/__snapshots__/manage_auto_responder.test.jsx.snap
  tests/helpers/intl-test-helper.jsx
  tests/plugins/__snapshots__/pluggable.test.jsx.snap
Labels: 3: Ready to Merge

#1956 [MM-12716] Remove doPostAction from post_actions and rename MessageAttachment and MessageAttachmentList components
  actions/post_actions.jsx
  components/post_view/message_attachments/message_attachment/index.js
  components/post_view/message_attachments/message_attachment/message_attachment.jsx
  components/post_view/message_attachments/message_attachment_list.jsx
  tests/components/post_view/__snapshots__/message_attachment.test.jsx.snap
  tests/components/post_view/message_attachment.test.jsx
Labels: QA Review

#2001 MM-12890 - Fix markdown preview error
  components/post_markdown/index.js
  components/post_view/post_message_view/post_message_view.jsx
Labels: 3: Ready to Merge

#1992 MM-12796 - Updating emoji reaction hover effect
  utils/utils.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#1916 Do not remove edit_others_posts from system admins
  utils/policy_roles_adapter.js
Labels: Hacktoberfest

#1998 MM-12822 - Updating background css for team icons
  sass/layout/_team-sidebar.scss
Labels: CherryPickApproved

#1994 Add link to Freenode
  README.md
Labels: 3: Ready to Merge

#1983 [MM-12712] Remove updatePost from post_actions
  actions/post_actions.jsx
  components/post_view/post_attachment_opengraph/index.js
  components/post_view/post_attachment_opengraph/post_attachment_opengraph.jsx
Labels: 3: Ready to Merge

#1995 MM-11560 - Allow plugins to add channel header tooltips
  components/channel_header/components/header_icon_wrapper.jsx
  plugins/channel_header_plug/channel_header_plug.jsx
  plugins/registry.js
  tests/components/channel_header/components/__snapshots__/header_icon_wrapper.test.jsx.snap
  tests/components/channel_header/components/header_icon_wrapper.test.jsx
  tests/plugins/__snapshots__/channel_header_plug.test.jsx.snap
  tests/plugins/channel_header_plug.test.jsx
Labels: 2: Dev Review

#1984 Migrate loadChannelsForCurrentUser action to redux
  actions/channel_actions.jsx
  actions/global_actions.jsx
  actions/websocket_actions.jsx
  tests/redux/actions/channel_actions.test.js
Labels: 3: Ready to Merge

#2002 remove unused func - fix from https://github.com/mattermost/mattermost-webapp/pull/1976
  components/admin_console/email_settings.jsx
Labels: 3: Ready to Merge

#2007 MM-12892 Fix JS error when uploading plugin
  components/admin_console/plugin_management/plugin_management.jsx
Labels: 2: Dev Review, CherryPickApproved

#2004 [MM-12713] Deleted emitEmojiPosted and added addReaction into post_actions
  actions/post_actions.jsx
  actions/views/create_comment.jsx
  components/create_post/create_post.jsx
  components/create_post/index.js
  components/post_view/post_info/index.js
  components/post_view/post_info/post_info.jsx
  components/post_view/reaction/index.js
  components/post_view/reaction/reaction.jsx
  components/post_view/reaction_list/index.js
  components/post_view/reaction_list/reaction_list.jsx
  components/rhs_comment/index.js
  components/rhs_comment/rhs_comment.jsx
  components/rhs_root_post/index.js
  components/rhs_root_post/rhs_root_post.jsx
  tests/components/create_post/create_post.test.jsx
  tests/components/post_view/reaction.test.jsx
  tests/redux/actions/post_actions.test.js
  tests/redux/actions/views/create_comment.test.jsx
Labels: 2: Dev Review

#1986 Update NOTICE.txt
  NOTICE.txt
Labels: 3: Ready to Merge

#2009 [MM-12778] Fix UnhandledPromiseRejectionWarning when running unit tests
  components/admin_console/permission_schemes_settings/permission_system_scheme_settings/permission_system_scheme_settings.jsx
  package.json
  tests/components/__snapshots__/team_general_tab.test.jsx.snap
  tests/components/add_users_to_team.test.jsx
  tests/components/admin_console/manage_teams_modal/__snapshots__/manage_teams_modal.test.jsx.snap
  tests/components/admin_console/manage_teams_modal/manage_teams_modal.test.jsx
  tests/components/admin_console/permission_schemes_settings/__snapshots__/permission_system_scheme_settings.test.jsx.snap
  tests/components/admin_console/permission_schemes_settings/__snapshots__/permission_team_scheme_settings.test.jsx.snap
  tests/components/admin_console/permission_schemes_settings/permission_system_scheme_settings.test.jsx
  tests/components/admin_console/permission_schemes_settings/permission_team_scheme_settings.test.jsx
  tests/components/edit_post_modal.test.jsx
  tests/components/more_direct_channels.test.jsx
  tests/components/search_results_item.test.jsx
  tests/components/suggestion/suggestion_box.test.jsx
  tests/components/team_general_tab.test.jsx
  tests/redux/actions/views/create_comment.test.jsx
  tests/setup.js
Labels: 3: Ready to Merge

#1890 Update activate/deactive to enable/disable for PATs
  components/user_settings/security/user_access_token_section/user_access_token_section.jsx
  i18n/en.json
Labels: 3: Ready to Merge

#2005 Migrate createPost to redux
  actions/post_actions.jsx
  actions/views/create_comment.jsx
  components/create_post/index.js
  components/post_view/failed_post_options/index.js
  tests/redux/actions/post_actions.test.js
  tests/redux/actions/views/create_comment.test.jsx
Labels: 3: Ready to Merge

#2013 Fix other UnhandledPromiseRejectionWarning
  tests/components/add_users_to_team.test.jsx
  tests/components/create_team/team_url.test.jsx
  tests/components/rename_channel_modal.test.jsx
Labels: 3: Ready to Merge

#2015 [MM-12924] Fix JS error when opening team's view members
  components/member_list_team/index.js
Labels: 3: Ready to Merge

#1987 MM-12736 Migrate MFA actions to redux
  actions/user_actions.jsx
  actions/views/mfa.js
  components/claim/claim_controller.jsx
  components/claim/components/email_to_ldap.jsx
  components/claim/components/email_to_oauth.jsx
  components/claim/components/ldap_to_email.jsx
  components/claim/components/oauth_to_email.jsx
  components/claim/index.js
  components/login/login_controller/index.js
  components/login/login_controller/login_controller.jsx
  components/mfa/setup/index.js
  components/mfa/setup/setup.jsx
  components/setting_item_max.jsx
  components/user_settings/security/index.js
  components/user_settings/security/user_settings_security.jsx
  tests/components/login/login_controller/login_controller.test.jsx
  tests/redux/actions/views/mfa.test.js
  tests/test_store.js
Labels: 3: Ready to Merge

#1919 [MM-10569] Invite links won't work in mobile browser when the user is asked if they want to download the app
  components/get_android_app/get_android_app.jsx
  components/get_ios_app/get_ios_app.jsx
  components/root/root.jsx
  tests/components/get_android_app/__snapshots__/get_android_app.test.jsx.snap
  tests/components/get_android_app/get_android_app.test.jsx
  tests/components/get_ios_app/__snapshots__/get_ios_app.test.jsx.snap
  tests/components/get_ios_app/get_ios_app.test.jsx
Labels: 3: Ready to Merge, Hacktoberfest, Setup Test Server

#1993 MM-12803 - Fixing permanent banner styling
  sass/components/_announcement-bar.scss
  sass/layout/_sidebar-left.scss
  sass/layout/_sidebar-right.scss
  sass/responsive/_mobile.scss
  sass/utils/_variables.scss
Labels: 3: Ready to Merge, CherryPickApproved, Setup Test Server

#1568 New sidebar feature fixed
  components/more_channels/more_channels.jsx
  components/more_direct_channels/more_direct_channels.jsx
  components/new_channel_flow/new_channel_flow.jsx
  components/new_channel_modal/new_channel_modal.jsx
  components/searchable_channel_list.jsx
  components/sidebar/channel_create.jsx
  components/sidebar/channel_more.jsx
  components/sidebar/channel_name.jsx
  components/sidebar/index.js
  components/sidebar/more_public_direct_channels.jsx
  components/sidebar/sidebar.jsx
  components/user_settings/modal/index.js
  components/user_settings/sidebar/index.js
  components/user_settings/sidebar/user_settings_sidebar.jsx
  i18n/en.json
  package-lock.json
  package.json
  sass/components/_modal.scss
  sass/components/_popover.scss
  sass/layout/_sidebar-left.scss
  tests/components/__snapshots__/new_channel_flow.test.jsx.snap
  tests/components/__snapshots__/new_channel_modal.test.jsx.snap
  tests/components/__snapshots__/searchable_channel_list.test.jsx.snap
  tests/components/new_channel_flow.test.jsx
  tests/components/new_channel_modal.test.jsx
  tests/components/sidebar/__snapshots__/sidebar.test.jsx.snap
  tests/components/sidebar/sidebar.test.jsx
  tests/components/user_settings/__snapshots__/user_settings_sidebar.test.jsx.snap
  tests/components/user_settings/user_settings_display.test.jsx
  tests/components/user_settings/user_settings_sidebar.test.jsx
  utils/utils.jsx
Labels: 3: Ready to Merge, Major Change, QA Review, Setup Test Server

#2020 MM-12944: force "Delete" focus on showing delete post modal
  components/delete_post_modal/delete_post_modal.jsx
  tests/components/__snapshots__/delete_post_modal.test.jsx.snap
  tests/components/delete_post_modal.test.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2023 MM-12936 - Fixing alignment of post control menu
  sass/layout/_post.scss
Labels: 3: Ready to Merge, CherryPickApproved

#1607 When mention `@channel/@all` show the timezones affected in the warning message
  components/create_comment/create_comment.jsx
  components/create_comment/create_comment.test.jsx
  components/create_comment/index.js
  components/create_post/create_post.jsx
  components/create_post/create_post.test.jsx
  components/create_post/index.js
  i18n/en.json
Labels: 3: Ready to Merge

#2021 MM-12908: defer enter sending until 500ms after channel switch
  components/create_post/create_post.jsx
  utils/post_utils.jsx
  utils/post_utils.test.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2028 MM-12966: consistently pass NotificationSections.NONE
  components/channel_notifications_modal/channel_notifications_modal.jsx
  components/channel_notifications_modal/components/notification_section.jsx
  components/channel_notifications_modal/components/notification_section.test.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2030 Migrate emoji_action to redux
  actions/emoji_actions.jsx
  components/emoji/add_emoji/__snapshots__/add_emoji.test.js.snap
  components/emoji/add_emoji/add_emoji.jsx
  components/emoji/add_emoji/add_emoji.test.js
  components/emoji/add_emoji/index.js
Labels: 2: Dev Review

#1966 MM-12587 Complete migration of job_actions to redux actions
  actions/job_actions.jsx
  components/admin_console/jobs/__snapshots__/table.test.jsx.snap
  components/admin_console/jobs/index.jsx
  components/admin_console/jobs/table.jsx
  components/admin_console/jobs/table.test.jsx
Labels: 2: Dev Review

#2034 MM-12982 Fix multiple message menus in single post
  actions/views/posts.js
  components/post_view/message_attachments/action_menu/index.js
  reducers/views/posts.js
Labels: 2: Dev Review, CherryPickApproved

#2006 Migrate searchMoreChannels action to redux
  actions/channel_actions.jsx
  actions/channel_actions.test.js
  components/more_channels/index.js
  components/more_channels/more_channels.jsx
  components/more_channels/more_channels.test.jsx
Labels: 3: Ready to Merge

#2033 Migrate open GM/DM actions to redux
  actions/channel_actions.jsx
  actions/views/channel.js
  components/channel_layout/channel_identifier_router/actions.js
  components/more_direct_channels/index.js
  components/more_direct_channels/more_direct_channels.jsx
  components/more_direct_channels/more_direct_channels.test.jsx
  components/popover_list_members/index.js
  components/popover_list_members/popover_list_members.jsx
  components/popover_list_members/popover_list_members.test.jsx
  components/profile_popover/index.js
  components/profile_popover/profile_popover.jsx
  plugins/pluggable/__snapshots__/pluggable.test.jsx.snap
Labels: 3: Ready to Merge

#2016 MM-12760: No heading on from: search filter.
  components/search_bar/search_bar.jsx
  components/suggestion/search_suggestion_list.jsx
  components/suggestion/suggestion_box.jsx
Labels: 3: Ready to Merge

#2039 Fix open DM channels
  components/channel_layout/channel_identifier_router/actions.js
Labels: 3: Ready to Merge

#2035 Add comment for MessageWillFormat plugin hook
  plugins/registry.js
Labels: 2: Dev Review

#2036 [MM-12984] remove 'with' from strings
  components/admin_console/admin_definition.jsx
  i18n/en.json
Labels: 3: Ready to Merge

#1981 [MM-12214] Update strings and set https to default
  components/admin_console/push_settings.jsx
  i18n/en.json
  utils/constants.jsx
Labels: 3: Ready to Merge

#2038 fix typo that prevented accepting tos
  actions/user_actions.jsx
Labels: 3: Ready to Merge

#1988 MM-12736 Refactor MFA section of user settings into its own component
  components/user_settings/security/__snapshots__/mfa_section.test.jsx.snap
  components/user_settings/security/index.js
  components/user_settings/security/mfa_section.test.jsx
  components/user_settings/security/mfa_section/index.js
  components/user_settings/security/mfa_section/mfa_section.jsx
  components/user_settings/security/user_settings_security.jsx
Labels: 3: Ready to Merge

#2044 Fix menu action selection not being shared between center and RHS
  components/post_view/message_attachments/action_menu/index.js
Labels: 3: Ready to Merge, CherryPickCandidate

#2043 MM-13019 Fix Socket disconnect banner not appearing when socket disco…
  actions/websocket_actions.jsx
  components/admin_console/email_settings.jsx
Labels: 3: Ready to Merge

#2046 MM-13020 Revert changes to have Client4 use an explicit ClientError type (5.5)
  package-lock.json
  package.json
Labels: 3: Ready to Merge

#2003 MM-12885: Add UI widgets AdminHeader and FormattedAdminHeader.
  components/admin_console/__snapshots__/message_export_settings.test.jsx.snap
  components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
  components/admin_console/admin_settings.jsx
  components/admin_console/audits/audits.jsx
  components/admin_console/custom_plugin_settings/__snapshots__/custom_plugin_settings.test.jsx.snap
  components/admin_console/license_settings.jsx
  components/admin_console/permission_schemes_settings/__snapshots__/permission_schemes_settings.test.jsx.snap
  components/admin_console/permission_schemes_settings/permission_schemes_settings.jsx
  components/admin_console/plugin_management/__snapshots__/plugin_management.test.jsx.snap
  components/admin_console/schema_admin_settings.jsx
  components/admin_console/server_logs/logs.jsx
  components/admin_console/system_users/__snapshots__/system_users.test.jsx.snap
  components/admin_console/system_users/system_users.jsx
  components/analytics/system_analytics/system_analytics.jsx
  components/analytics/team_analytics/team_analytics.jsx
  components/widgets/admin_console/admin_header.jsx
  components/widgets/admin_console/admin_header.test.jsx
  components/widgets/admin_console/formatted_admin_header.jsx
  components/widgets/admin_console/formatted_admin_header.test.jsx
Labels: 2: Dev Review

#2029 dropdown action button aligned with action buttons
  sass/layout/_webhooks.scss
Labels: 3: Ready to Merge

#2045 [MM-12852] E2E: Write initial test setup with Cypress
  .eslintrc.json
  .gitignore
  NOTICE.txt
  components/channel_layout/channel_controller.jsx
  components/common/__snapshots__/site_name_and_description.test.jsx.snap
  components/common/back_button.jsx
  components/common/site_name_and_description.jsx
  components/header_footer_template/__snapshots__/header_footer_template.test.jsx.snap
  components/header_footer_template/header_footer_template.jsx
  components/login/login_controller/__snapshots__/login_controller.test.jsx.snap
  components/login/login_controller/login_controller.jsx
  components/signup/signup_email/signup_email.jsx
  cypress.json
  cypress/fixtures/users.json
  cypress/integration/login/login_spec.js
  cypress/integration/login/signup_spec.js
  cypress/support/commands.js
  cypress/support/index.js
  package-lock.json
  package.json
Labels: 3: Ready to Merge

#2037 [MM-12328] Scroll to bottom the RHS thread whenever the state.draft.message is not empty on component update
  components/create_comment/create_comment.jsx
  components/create_comment/create_comment.test.jsx
Labels: 3: Ready to Merge

#1686 [MM-11509] Use post metadata
  components/__snapshots__/markdown_image.test.jsx.snap
  components/file_attachment_list/file_attachment_list.jsx
  components/file_attachment_list/index.js
  components/markdown/markdown.jsx
  components/markdown/markdown.test.jsx
  components/markdown_image.jsx
  components/markdown_image.test.jsx
  components/post_markdown/post_markdown.jsx
  components/post_view/commented_on_files_message/commented_on_files_message.jsx
  components/post_view/commented_on_files_message/index.js
  components/post_view/message_attachments/message_attachment/__snapshots__/message_attachment.test.jsx.snap
  components/post_view/message_attachments/message_attachment/message_attachment.jsx
  components/post_view/message_attachments/message_attachment/message_attachment.test.jsx
  components/post_view/message_attachments/message_attachment_list.jsx
  components/post_view/post_attachment_opengraph/index.js
  components/post_view/post_attachment_opengraph/post_attachment_opengraph.jsx
  components/post_view/post_body_additional_content/post_body_additional_content.jsx
  components/post_view/post_image/post_image.jsx
  components/post_view/reaction_list/index.js
  components/post_view/reaction_list/reaction_list.jsx
  package-lock.json
  package.json
  sass/components/_videos.scss
  utils/file_utils.jsx
  utils/file_utils.test.jsx
  utils/message_html_to_component.jsx
Labels: 3: Ready to Merge

#2053 update redux
  package-lock.json
  package.json
Labels: 3: Ready to Merge

#2050 MM-12921 Fix for redirection to last channel from team subpages
  components/backstage/components/backstage_navbar.jsx
Labels: 2: Dev Review

#2048 Promote Romanian from Beta
  components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
  i18n/i18n.jsx
Labels: 3: Ready to Merge

#2054 Update texts for TPNS/HPNS connections
  components/admin_console/push_settings.jsx
  i18n/en.json
Labels: 3: Ready to Merge

#2051 [MM-12591] Add scroll animation for click on more unreads in LHS
  NOTICE.txt
  components/sidebar/sidebar.jsx
  package-lock.json
  package.json
Labels: 3: Ready to Merge

#2059 MM-13020 Update mattermost-redux to make ClientError.message enumerable
  package-lock.json
  package.json
Labels: 2: Dev Review

#1969 [MM-8338] Option to send as message when an invalid slash command is entered
  components/create_post/create_post.jsx
  components/create_post/create_post.test.jsx
  components/message_submit_error.jsx
  components/message_submit_error.test.jsx
  i18n/en.json
  utils/post_utils.jsx
Labels: 3: Ready to Merge, Hacktoberfest

#2047 MM-12770 Fixing opening a GM with the channel switcher.
  components/quick_switch_modal/index.js
  components/quick_switch_modal/quick_switch_modal.jsx
  components/quick_switch_modal/quick_switch_modal.test.jsx
Labels: 2: Dev Review

#2041 MM-12630 Adding debounce to prevent client breaking for very high rate channels.
  actions/websocket_actions.jsx
Labels: 3: Ready to Merge, Setup Test Server, Tests: Not Needed

#2042 Fix pinned post list from refreshing
  components/search_results/index.jsx
  components/search_results/search_results.jsx
  components/search_results_item/index.js
  components/sidebar_right/index.js
  components/sidebar_right/sidebar_right.jsx
Labels: 3: Ready to Merge

#2057 Update minimum software requirements
  components/error_page/__snapshots__/error_message.test.jsx.snap
  components/error_page/error_message.jsx
  i18n/en.json
Labels: 2: Dev Review

#1930 MM-12710 Migration of team_actions to redux
  actions/team_actions.jsx
  components/admin_console/manage_teams_modal/__snapshots__/manage_teams_modal.test.jsx.snap
  components/admin_console/manage_teams_modal/__snapshots__/remove_from_team_button.test.jsx.snap
  components/admin_console/manage_teams_modal/index.jsx
  components/admin_console/manage_teams_modal/manage_teams_dropdown.jsx
  components/admin_console/manage_teams_modal/manage_teams_modal.jsx
  components/admin_console/manage_teams_modal/manage_teams_modal.test.jsx
  components/admin_console/manage_teams_modal/remove_from_team_button.jsx
  components/admin_console/manage_teams_modal/remove_from_team_button.test.jsx
  components/admin_console/system_users/list/system_users_list.test.jsx
  components/invite_member_modal/index.js
  components/invite_member_modal/invite_member_modal.jsx
  components/login/login_controller/index.js
  components/login/login_controller/login_controller.jsx
  components/login/login_controller/login_controller.test.jsx
  components/select_team/index.js
  components/select_team/select_team.jsx
  components/select_team/select_team.test.jsx
  components/signup/signup_controller/index.js
  components/signup/signup_controller/signup_controller.jsx
  components/signup/signup_email/index.js
  components/signup/signup_email/signup_email.jsx
  components/team_members_dropdown/index.js
  components/team_members_dropdown/team_members_dropdown.jsx
  components/team_sidebar/components/team_button.jsx
  components/team_sidebar/index.js
  components/team_sidebar/team_sidebar_controller.jsx
  tests/redux/actions/team_actions.test.js
Labels: 3: Ready to Merge

#2067 [MM-13086] Add space between suggestion and hint
  components/suggestion/__snapshots__/command_provider.test.js.snap
  components/suggestion/command_provider.jsx
  components/suggestion/command_provider.test.js
Labels: 2: Dev Review

#2010 MM-4712 Add progress bar to uploads
  components/create_comment/__snapshots__/create_comment.test.jsx.snap
  components/create_comment/create_comment.jsx
  components/create_comment/create_comment.test.jsx
  components/create_post/__snapshots__/create_post.test.jsx.snap
  components/create_post/create_post.jsx
  components/create_post/create_post.test.jsx
  components/file_preview/__snapshots__/file_preview.test.jsx.snap
  components/file_preview/__snapshots__/file_progress_preview.test.jsx.snap
  components/file_preview/file_preview.jsx
  components/file_preview/file_preview.test.jsx
  components/file_preview/file_progress_preview.jsx
  components/file_preview/file_progress_preview.test.jsx
  components/file_upload/file_upload.jsx
  components/file_upload/file_upload.test.jsx
  i18n/en.json
  sass/components/_files.scss
  utils/constants.jsx
  utils/file_utils.jsx
  utils/file_utils.test.jsx
Labels: 3: Ready to Merge

#2069 update redux deps
  package-lock.json
  package.json
Labels: 3: Ready to Merge

#2068 Fix for inline markdown images key in metadata
  components/markdown_image.jsx
  components/post_view/post_attachment_opengraph/post_attachment_opengraph.jsx
  utils/message_html_to_component.jsx
Labels: 3: Ready to Merge

#2070 Take data retention out of beta
  components/admin_console/admin_sidebar/admin_sidebar.jsx
  components/admin_console/data_retention_settings.jsx
  i18n/en.json
Labels: 2: Dev Review, Docs: Done

#2066 MM-12839: Remove archived channels posts from search results when needed
  actions/websocket_actions.jsx
  components/rhs_thread/rhs_thread.jsx
Labels: 2: Dev Review

#2032 MM-11692 Add infinite scroll to webapp
  actions/post_actions.jsx
  actions/post_actions.test.js
  components/post_view/post_attachment_opengraph/post_attachment_opengraph.jsx
  components/post_view/post_body_additional_content/post_body_additional_content.jsx
  components/post_view/post_image/post_image.jsx
  components/post_view/post_list.jsx
  components/single_image_view/single_image_view.jsx
  sass/layout/_post.scss
  utils/file_utils.jsx
  utils/file_utils.test.jsx
Labels: 3: Ready to Merge

#2064 MM-12981 - Updating custom login buttons
  sass/routes/_signup.scss
Labels: 3: Ready to Merge

#2058 [MM-12980] Add E2E to hide/show channel switcher button in LHS
  components/__snapshots__/setting_item_max.test.jsx.snap
  components/setting_item_max.jsx
  components/user_settings/notifications/__snapshots__/email_notification_setting.test.jsx.snap
  components/user_settings/notifications/__snapshots__/manage_auto_responder.test.jsx.snap
  components/user_settings/sidebar/__snapshots__/user_settings_sidebar.test.jsx.snap
  components/user_settings/sidebar/user_settings_sidebar.jsx
  cypress/fixtures/users.json
  cypress/integration/account_settings/sidebar/channel_switcher_spec.js
  cypress/support/commands.js
Labels: 3: Ready to Merge

#2065 [MM-12971] Fix autocomplete selection for classic app
  components/suggestion/suggestion_box.jsx
  components/suggestion/suggestion_box.test.jsx
Labels: 2: Dev Review, Setup Test Server

#2062 MM-12943 - Updating blockquotes in header
  sass/layout/_headers.scss
Labels: 2: Dev Review

#2074 [MM-13147] Fix for file_upload crash when mimeTypesSuffix is not present
  utils/file_utils.jsx
  utils/file_utils.test.jsx
Labels: 3: Ready to Merge

#2076 [MM-13035] Updated redux commit to take effect sidebar channels sorting
  package-lock.json
  package.json
Labels: 2: Dev Review

#2049 MM-12844/MM-13001 Add interactive dialogs
  actions/command.js
  actions/integration_actions.jsx
  actions/views/posts.js
  actions/websocket_actions.jsx
  components/admin_console/__snapshots__/message_export_settings.test.jsx.snap
  components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
  components/admin_console/custom_plugin_settings/__snapshots__/custom_plugin_settings.test.jsx.snap
  components/admin_console/text_setting.jsx
  components/interactive_dialog/dialog_element.jsx
  components/interactive_dialog/index.js
  components/interactive_dialog/interactive_dialog.jsx
  components/post_view/message_attachments/action_menu/action_menu.jsx
  components/widgets/settings/autocomplete_selector.jsx
  components/widgets/settings/autocomplete_selector.test.jsx
  components/widgets/settings/setting.jsx
  components/widgets/settings/text_setting.jsx
  components/widgets/settings/text_setting.test.jsx
  sass/components/_inputs.scss
  sass/components/_module.scss
  sass/components/_select.scss
  sass/layout/_webhooks.scss
  sass/responsive/_mobile.scss
  sass/routes/_about-modal.scss
  sass/routes/_admin-console.scss
  utils/constants.jsx
  utils/utils.jsx
Labels: 3: Ready to Merge

#1974 MM-12233: local user mention results
  actions/user_actions.jsx
  actions/views/channel.js
  components/__snapshots__/textbox.test.jsx.snap
  components/create_comment/__snapshots__/create_comment.test.jsx.snap
  components/create_comment/create_comment.jsx
  components/create_comment/create_comment.test.jsx
  components/create_post/__snapshots__/create_post.test.jsx.snap
  components/create_post/create_post.jsx
  components/create_post/create_post.test.jsx
  components/edit_channel_header_modal/__snapshots__/edit_channel_header_modal.test.jsx.snap
  components/edit_channel_header_modal/edit_channel_header_modal.jsx
  components/edit_post_modal/__snapshots__/edit_post_modal.test.jsx.snap
  components/edit_post_modal/edit_post_modal.jsx
  components/edit_post_modal/edit_post_modal.test.jsx
  components/suggestion/at_mention_provider/at_mention_provider.jsx
  components/suggestion/at_mention_provider/at_mention_provider.test.jsx
  components/suggestion/at_mention_provider/at_mention_suggestion.jsx
  components/suggestion/at_mention_provider/index.js
  components/suggestion/suggestion_list.jsx
  components/textbox.test.jsx
  components/textbox/index.js
  components/textbox/textbox.jsx
  i18n/en.json
  utils/constants.jsx
Labels: 2: Dev Review, Setup Test Server, Tests: Done

#2017 [MM-12743] Migrate loadProfilesAndTeamMembers of user actions into redux-style
  actions/user_actions.jsx
  actions/user_actions.test.js
  components/admin_console/system_users/index.js
  components/admin_console/system_users/system_users.jsx
  components/admin_console/system_users/system_users.test.jsx
  components/member_list_channel/index.js
  components/member_list_channel/member_list_channel.jsx
  components/member_list_team/index.js
  components/member_list_team/member_list_team.jsx
Labels: 2: Dev Review

#1487 Added Admin Badge to Profile Popover
  actions/views/profile_popover.js
  components/profile_popover/index.js
  components/profile_popover/profile_popover.jsx
  plugins/pluggable/__snapshots__/pluggable.test.jsx.snap
  plugins/pluggable/pluggable.test.jsx
  sass/components/_popover.scss
Labels: 3: Ready to Merge

#2063 MM-12947 - Updating close button on mobile
  sass/responsive/_mobile.scss
Labels: 2: Dev Review

#2061 MM-12922 - Updating bullet point sizing
  sass/layout/_post.scss
Labels: 2: Dev Review

#2075 MM-12825 - Making IE not responsive
  sass/responsive/_mobile.scss
Labels: 3: Ready to Merge

#1918 [MM-12396] Option to add user to a channel from the profile pop-over
  components/add_user_to_channel_modal/__snapshots__/add_user_to_channel_modal.test.jsx.snap
  components/add_user_to_channel_modal/add_user_to_channel_modal.jsx
  components/add_user_to_channel_modal/add_user_to_channel_modal.test.jsx
  components/add_user_to_channel_modal/index.js
  components/profile_popover/__snapshots__/profile_popover.test.jsx.snap
  components/profile_popover/index.js
  components/profile_popover/profile_popover.jsx
  components/profile_popover/profile_popover.test.jsx
  components/suggestion/search_channel_with_permissions_provider.jsx
  components/suggestion/search_channel_with_permissions_provider.test.jsx
  i18n/en.json
  plugins/pluggable/__snapshots__/pluggable.test.jsx.snap
  plugins/pluggable/pluggable.test.jsx
  sass/components/_popover.scss
  utils/constants.jsx
Labels: 3: Ready to Merge

#2080 [MM-13181] Fix JS error after editing a post
  components/edit_post_modal/edit_post_modal.jsx
  components/edit_post_modal/edit_post_modal.test.jsx
Labels: 3: Ready to Merge

#2082 [MM-13118] Add and remove duplicated divider at Sidebar user account setting
  components/user_settings/sidebar/__snapshots__/user_settings_sidebar.test.jsx.snap
  components/user_settings/sidebar/user_settings_sidebar.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2083 MM-13166 Fix image dimensions for singleImage attachment
  components/single_image_view/single_image_view.jsx
  components/single_image_view/single_image_view.test.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#1306 Fix bot indicator style for mobile
  sass/responsive/_mobile.scss
Labels: 3: Ready to Merge

#2085 MM-13025 - Updating show more button css
  sass/layout/_post.scss
Labels: CherryPickCandidate

#2081 MM-12888 Fix redirect after leaving a channel
  actions/views/channel.js
  actions/views/channel.test.js
Labels: 2: Dev Review, CherryPickApproved

#2090 MM-13140 Fix to leave team from MainMenu
  components/leave_team_modal/index.js
Labels: 3: Ready to Merge, CherryPickApproved

#2089 MM-13172 add switchTeam Props to all TeamButtons
  components/team_sidebar/components/team_button.jsx
  components/team_sidebar/team_sidebar_controller.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2087 MM-13098 Fix for Minor scroll pop on firefox
  sass/layout/_post.scss
Labels: 3: Ready to Merge, CherryPickApproved

#2091 MM-13177 Announcement bar fixes.
  actions/views/posts.js
  components/announcement_bar/configuration_bar.jsx
Labels: 2: Dev Review, CherryPickCandidate

#2084 MM-12881 Add edition field to license page
  components/admin_console/license_settings.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2092 Fix joining channels from the quick switcher
  actions/views/channel.js
  components/quick_switch_modal/index.js
  components/quick_switch_modal/quick_switch_modal.jsx
  components/quick_switch_modal/quick_switch_modal.test.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2095 MM-13183 - Updating modal styling
  sass/responsive/_mobile.scss
  sass/routes/_about-modal.scss
  utils/utils.jsx
Labels: CherryPickApproved

#2097 translations PR 20181128 (Adds Ukrainian)
  components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
  i18n/de.json
  i18n/es.json
  i18n/fr.json
  i18n/i18n.jsx
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 3: Ready to Merge

#2098 Add Ukrainian to Mattermost
  components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
  i18n/i18n.jsx
  i18n/uk.json
Labels: 3: Ready to Merge

#2099 MM-13191 Fix channel switcher button and shortcut
  components/channel_header/channel_header.js
  components/channel_header/index.js
  components/sidebar/index.js
  components/sidebar/sidebar.jsx
  components/sidebar/sidebar.test.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2096 Update mattermost-redux to include terms of service changes
  package-lock.json
  package.json
Labels: 3: Ready to Merge

#2101 MM-13144 Fix redirecting to email verification page after sign-up
  components/signup/signup_email/signup_email.jsx
Labels: 2: Dev Review, CherryPickApproved

#2086 MM-12996/MM-13229 - Updating modals on mobile and fixing plugin button on mobile
  plugins/mobile_channel_header_plug/__snapshots__/mobile_channel_header_plug.test.jsx.snap
  plugins/mobile_channel_header_plug/mobile_channel_header_plug.jsx
  plugins/mobile_channel_header_plug/mobile_channel_header_plug.test.jsx
  sass/layout/_navigation.scss
  sass/responsive/_mobile.scss
Labels: CherryPickApproved, Setup Test Server

#2088 MM-13182 Allow clicking on links behind collapsed post fade effect
  sass/layout/_post.scss
Labels: CherryPickApproved

#2109 MM-132223 Fix for error on leaveTeam
  actions/global_actions.jsx
  actions/global_actions.test.js
Labels: 3: Ready to Merge, CherryPickApproved

#2093 MM-13102 - Updating search cross icon on mobile
  sass/responsive/_mobile.scss
Labels: 3: Ready to Merge, CherryPickApproved

#2107 MM-13226 - Updating inactive tab styling in modal
  sass/components/_modal.scss
  utils/utils.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2112 Fix an error with ScrollToBottomArrows
  components/post_view/post_list.jsx
Labels: 3: Ready to Merge

#2111 [MM-13175] Update mattermost-redux commit to take effect fix in sorting of sidebar channels
  package-lock.json
  package.json
Labels: 3: Ready to Merge, CherryPickApproved

#2116 Reverting #2060 to fix SAML login.
  actions/views/root.js
Labels: 2: Dev Review

#2113 Update 'Channel Display Mode' to 'Channel Display'
  components/user_settings/display/__snapshots__/user_settings_display.test.jsx.snap
  components/user_settings/display/user_settings_display.jsx
  i18n/en.json
Labels: 3: Ready to Merge, Docs: Needed
