Repository mattermost/mattermost-webapp, pull requests merged in 2018-02, with the labels that each got.

#687 XYZ-52: Adapts 'Enable Team Creation' on 'Users and Teams' page to re…
  components/admin_console/admin_console.jsx
  components/admin_console/users_and_teams_settings/index.jsx
  components/admin_console/users_and_teams_settings/users_and_teams_settings.jsx
  routes/route_admin_console.jsx
  tests/utils/policy_roles_adapter.test.jsx
  utils/policy_roles_adapter.js
Labels: 2: Dev Review, Awaiting PR

#669 Refactoring Layout components
  components/channel_layout/center_channel/center_channel.jsx
  components/channel_layout/center_channel/index.js
  components/channel_layout/channel_controller.jsx
  components/channel_layout/channel_identifier_router.jsx
  components/needs_team/needs_team.jsx
  components/webrtc/components/webrtc_sidebar.jsx
  selectors/storage.js
Labels: 2: Dev Review

#751 ABC-193: Add webapp commit hash to "about" modal
  components/about_build_modal/about_build_modal.jsx
  i18n/en.json
  tests/components/__snapshots__/about_build_modal.test.jsx.snap
  tests/components/about_build_modal.test.jsx
  webpack.config.js
Labels: 2: Dev Review

#767 update redux
  yarn.lock
Labels: 2: Dev Review

#760 ABC-245: Respect proxy settings for inline image previews
  components/post_view/post_image.jsx
Labels: 2: Dev Review

#776 PLT-7690: fix undefined user reference
  components/profile_picture.jsx
  tests/components/__snapshots__/profile_picture.test.jsx.snap
  tests/components/profile_picture.test.jsx
Labels: 2: Dev Review

#778 ABC-176 Remove UI setting for enabling plugin uploads
  components/admin_console/plugin_settings.jsx
  i18n/en.json
Labels: 3: Ready to Merge

#768 [ICU-746] Fix opening of Add Members modal for GM channel
  components/channel_header/channel_header.jsx
  components/more_direct_channels/index.js
  components/more_direct_channels/more_direct_channels.jsx
  components/navbar/navbar.jsx
  components/sidebar/sidebar.jsx
  stores/modal_store.jsx
  tests/components/sidebar/__snapshots__/sidebar.test.jsx.snap
  utils/constants.jsx
Labels: 3: Ready to Merge

#766 ABC-244: fix team invite link handling
  components/login/login_controller.jsx
  components/signup/signup_controller.jsx
Labels: 3: Ready to Merge

#758 ABC-246 Redirect to landing pages on iOS and Android mobile browsers
  components/root.jsx
Labels: 3: Ready to Merge

#780 Icu 734 - Ctrl-U triggers upload box
  components/file_upload/file_upload.jsx
Labels: 3: Ready to Merge

#773 [ICU-739] Fix issue on leaving a team
  actions/global_actions.jsx
Labels: 3: Ready to Merge

#757 Fixed messageHtmlToComponent returning undefined (#755)
  utils/post_utils.jsx
Labels: 3: Ready to Merge

#749 XYZ-5 New compliance section in admin_console
  components/admin_console/admin_console.jsx
  components/admin_console/admin_sidebar/admin_sidebar.jsx
Labels: 2: Dev Review

#791 PLT-8777 Fixed typo in i18n string
  components/admin_console/gitlab_settings.jsx
Labels: 3: Ready to Merge

#745 [XYZ-66] Fix tabIndex going outside modal in NewChannelModal
  components/new_channel_modal/new_channel_modal.jsx
  tests/components/__snapshots__/new_channel_modal.test.jsx.snap
Labels: 3: Ready to Merge

#790 [PLT-8780] Fix note on adding DM/GM
  components/more_direct_channels/more_direct_channels.jsx
Labels: 3: Ready to Merge

#782 [ICU-747/749/752] Fix unexpected opening of keyboard on classic app
  components/create_post/create_post.jsx
  tests/components/create_post/create_post.test.jsx
Labels: 3: Ready to Merge

#783 ICU-766 Fix go back from deleted permalink
  actions/global_actions.jsx
  components/error_page/index.jsx
  components/file_upload/index.js
  components/needs_team/needs_team.jsx
  components/permalink_view.jsx
Labels: 3: Ready to Merge

#704 XYZ-75: Migrates EnableOnlyAdminIntegrations config in system console to set role permissions.
  components/admin_console/admin_console.jsx
  components/admin_console/custom_integrations_settings/custom_integrations_settings.jsx
  components/admin_console/custom_integrations_settings/index.jsx
  components/admin_console/policy_settings/policy_settings.jsx
  routes/route_admin_console.jsx
  tests/components/integrations/installed_oauth_apps.test.jsx
  utils/policy_roles_adapter.js
Labels: 2: Dev Review

#795 Icu 745- fix lhs popping in an out during tutorial
  components/sidebar_right/sidebar_right.jsx
Labels: 2: Dev Review

#807 fix rightsidebar not hiding properly
  components/sidebar_right/sidebar_right.jsx
Labels: 2: Dev Review

#787 XYZ-111: Checking join rights before join to the team
  components/select_team/components/select_team_item.jsx
Labels: 3: Ready to Merge, Tests: Done

#797 Fix two corner cases for emoji loading
  actions/websocket_actions.jsx
  yarn.lock
Labels: 3: Ready to Merge

#800 MM-8004 - Mobile landing page not scrolling IOS
  sass/routes/_get-app.scss
Labels: 3: Ready to Merge

#803 [MM-9603] Do not show deleted open team at team selection list
  components/select_team/select_team.jsx
Labels: 3: Ready to Merge

#804 MM-9604 Prevent races between emoji picker page incrementing and requesting more emojis
  components/emoji_picker/emoji_picker.jsx
Labels: 3: Ready to Merge

#808 MM-9605: Permalinks to public channels don't join the channels if not in them
  actions/global_actions.jsx
Labels: 3: Ready to Merge

#789 T-3 Merge release-4.7 into master
  actions/global_actions.jsx
  components/admin_console/storage_settings.jsx
  components/channel_header/channel_header.jsx
  components/file_upload/file_upload.jsx
  components/logged_in.jsx
  components/login/login_controller.jsx
  components/more_direct_channels/index.js
  components/more_direct_channels/more_direct_channels.jsx
  components/navbar/navbar.jsx
  components/root.jsx
  components/sidebar/sidebar.jsx
  components/signup/signup_controller.jsx
  i18n/en.json
  i18n/fr.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/ru.json
  i18n/zh-CN.json
  i18n/zh-TW.json
  package.json
  sass/responsive/_mobile.scss
  sass/responsive/_tablet.scss
  stores/modal_store.jsx
  tests/components/sidebar/__snapshots__/sidebar.test.jsx.snap
  utils/constants.jsx
  yarn.lock
Labels: 2: Dev Review

#809 translations PR 20180215
  i18n/de.json
  i18n/en.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ru.json
  i18n/tr.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 3: Ready to Merge

#806 MM-9611 Fix textbox placeholder on IE11
  components/autosize_textarea.jsx
Labels: 3: Ready to Merge

#811 MM-9601 Remove duplicate view channel calls on app focus and channel switch
  actions/global_actions.jsx
  components/needs_team/needs_team.jsx
Labels: 3: Ready to Merge

#801 MM-8555 Fix duplicate get flagged posts requests
  actions/post_actions.jsx
  components/sidebar_right/sidebar_right.jsx
Labels: 3: Ready to Merge

#820 Remove mm_config and mm_license global state from webapp (PR #3)
  components/channel_view/channel_view.jsx
  components/channel_view/index.js
  components/create_post/create_post.jsx
  components/create_post/index.js
  components/do_verify_email/do_verify_email.jsx
  components/do_verify_email/index.js
  components/file_upload/file_upload.jsx
  components/file_upload/index.js
  components/navbar/index.js
  components/navbar/navbar.jsx
  components/tutorial/index.jsx
  components/tutorial/tutorial_intro_screens.jsx
  components/tutorial/tutorial_view.jsx
  tests/components/create_post/__snapshots__/create_post.test.jsx.snap
  tests/components/create_post/create_post.test.jsx
  tests/components/do_verify_email.test.jsx
  tests/components/file_upload/__snapshots__/file_upload.test.jsx.snap
  tests/components/file_upload/file_upload.test.jsx
  tests/utils/file_utils.test.jsx
  utils/file_utils.jsx
Labels: 2: Dev Review

#825 Advanced Permissions: Fix typo
  components/member_list_team/index.js
Labels: 3: Ready to Merge

#823 Remove mm_config and mm_license global state from webapp (PR #6)
  components/channel_header/channel_header.jsx
  components/channel_layout/channel_controller.jsx
  components/channel_members_dropdown/channel_members_dropdown.jsx
  components/channel_members_dropdown/index.js
  components/channel_notifications_modal/channel_notifications_modal.jsx
  components/channel_notifications_modal/index.js
  components/invite_member_modal/index.js
  components/invite_member_modal/invite_member_modal.jsx
  components/more_direct_channels/index.js
  components/more_direct_channels/more_direct_channels.jsx
  components/navbar/navbar.jsx
  components/search_results_item/index.js
  components/search_results_item/search_results_item.jsx
  components/should_verify_email/index.js
  components/should_verify_email/should_verify_email.jsx
  components/team_sidebar/index.js
  components/team_sidebar/team_sidebar_controller.jsx
  tests/components/__snapshots__/search_results_item.test.jsx.snap
  tests/components/navbar/__snapshots__/navbar.test.jsx.snap
  tests/components/navbar/navbar.test.jsx
  tests/components/search_results_item.test.jsx
Labels: 3: Ready to Merge, Awaiting Submitter Action

#822 Remove mm_config and mm_license global state from webapp (PR #5)
  components/create_comment/create_comment.jsx
  components/create_comment/index.js
  components/create_team/create_team_controller/create_team_controller.jsx
  components/create_team/create_team_controller/index.js
  components/create_team/display_name.jsx
  components/create_team/team_url.jsx
  components/get_ios_app/get_ios_app.jsx
  components/get_ios_app/index.js
  components/more_channels/index.js
  components/more_channels/more_channels.jsx
  components/new_channel_modal/index.js
  components/new_channel_modal/new_channel_modal.jsx
  components/root.jsx
  components/search_results/index.jsx
  components/search_results/search_results.jsx
  components/sidebar/header/dropdown/index.js
  components/sidebar/header/dropdown/sidebar_header_dropdown.jsx
  components/sidebar/header/index.js
  components/sidebar/header/sidebar_header.jsx
  components/sidebar/header/sidebar_header_dropdown_button.jsx
  components/sidebar/index.js
  components/sidebar/sidebar.jsx
  components/sidebar_right_menu/index.js
  components/sidebar_right_menu/sidebar_right_menu.jsx
  tests/components/__snapshots__/new_channel_modal.test.jsx.snap
  tests/components/create_comment/__snapshots__/create_comment.test.jsx.snap
  tests/components/create_comment/create_comment.test.jsx
  tests/components/new_channel_modal.test.jsx
  tests/components/sidebar/__snapshots__/sidebar.test.jsx.snap
  tests/components/sidebar/sidebar.test.jsx
  tests/utils/channel_utils.test.jsx
  utils/channel_utils.jsx
Labels: 3: Ready to Merge

#827 Point mattermost-redux at latest master
  package.json
  yarn.lock
Labels: 3: Ready to Merge

#816 Remove mm_config and mm_license global state from webapp (PR #1)
  components/claim/claim_controller.jsx
  components/claim/components/email_to_ldap.jsx
  components/claim/components/email_to_oauth.jsx
  components/claim/components/ldap_to_email.jsx
  components/claim/components/oauth_to_email.jsx
  components/claim/index.js
  components/root.jsx
  components/signup/signup_controller.jsx
  i18n/i18n.jsx
  stores/user_store.jsx
Labels: 2: Dev Review

#829 MM-9628: fix broken channel switching
  components/channel_layout/center_channel/center_channel.jsx
  components/channel_layout/center_channel/index.js
  components/channel_layout/channel_controller.jsx
Labels: 3: Ready to Merge

#821 Remove mm_config and mm_license global state from webapp (PR #4)
  components/admin_console/admin_console.jsx
  components/analytics/format.jsx
  components/analytics/system_analytics/index.js
  components/analytics/system_analytics/system_analytics.jsx
  components/analytics/team_analytics/team_analytics.jsx
  components/announcement_bar/announcement_bar.jsx
  components/announcement_bar/index.js
  components/backstage/backstage_controller.jsx
  components/backstage/components/backstage_navbar.jsx
  components/backstage/components/backstage_sidebar.jsx
  components/backstage/index.js
  components/claim/components/email_to_ldap.jsx
  components/claim/components/email_to_oauth.jsx
  components/claim/components/ldap_to_email.jsx
  components/login/login_controller/index.js
  components/login/login_controller/login_controller.jsx
  components/login/login_mfa.jsx
  components/mfa/confirm.jsx
  components/mfa/mfa_controller/index.js
  components/mfa/mfa_controller/mfa_controller.jsx
  components/mfa/setup/index.js
  components/mfa/setup/setup.jsx
  components/password_reset_form/index.js
  components/password_reset_form/password_reset_form.jsx
  components/youtube_video/index.js
  components/youtube_video/youtube_video.jsx
  tests/components/login/login_mfa.test.jsx
  tests/components/mfa/components/confirm_test.jsx
Labels: 3: Ready to Merge

#815 MM-9618: Don't change default role permissions for policy.
  tests/utils/policy_roles_adapter.test.jsx
  utils/policy_roles_adapter.js
Labels: 2: Dev Review

#833 Rename permissions gates to change perm with permissions
  components/admin_console/system_users/system_users_dropdown.jsx
  components/announcement_bar/index.js
  components/backstage/components/backstage_sidebar.jsx
  components/channel_header/channel_header.jsx
  components/channel_members_dropdown/index.js
  components/integrations/abstract_oauth_app.jsx
  components/integrations/installed_commands/index.js
  components/integrations/installed_incoming_webhooks/index.js
  components/integrations/installed_oauth_apps/index.js
  components/integrations/installed_outgoing_webhooks/index.js
  components/integrations/integrations.jsx
  components/member_list_team/index.js
  components/more_channels/more_channels.jsx
  components/navbar/navbar.jsx
  components/new_channel_modal/new_channel_modal.jsx
  components/permissions_gates/channel_permission_gate/channel_permission_gate.jsx
  components/permissions_gates/channel_permission_gate/index.js
  components/permissions_gates/system_permission_gate/index.js
  components/permissions_gates/system_permission_gate/system_permission_gate.jsx
  components/permissions_gates/team_permission_gate/index.js
  components/permissions_gates/team_permission_gate/team_permission_gate.jsx
  components/post_view/post_info/post_info.jsx
  components/post_view/reaction/index.js
  components/post_view/reaction_list/reaction_list.jsx
  components/rhs_comment/rhs_comment.jsx
  components/select_team/select_team.jsx
  components/sidebar/header/dropdown/sidebar_header_dropdown.jsx
  components/sidebar/sidebar.jsx
  components/sidebar_right_menu/sidebar_right_menu.jsx
  components/team_sidebar/team_sidebar_controller.jsx
  package.json
  tests/components/__snapshots__/new_channel_modal.test.jsx.snap
  tests/components/__snapshots__/permissions_gates.test.jsx.snap
  tests/components/integrations/__snapshots__/abstract_oauth_app.test.jsx.snap
  tests/components/navbar/__snapshots__/navbar.test.jsx.snap
  tests/components/permissions_gates.test.jsx
  tests/components/sidebar/__snapshots__/sidebar.test.jsx.snap
  utils/channel_intro_messages.jsx
  utils/channel_utils.jsx
  utils/post_utils.jsx
  yarn.lock
Labels: 3: Ready to Merge

#834 Fix channel header edit button.
  components/channel_header/channel_header.jsx
Labels: 2: Dev Review

#836 MM-8825: Make consistent INVITE_USER and ADD_USER_TO_TEAM permissions checking
  components/sidebar/header/dropdown/sidebar_header_dropdown.jsx
  components/sidebar_right_menu/sidebar_right_menu.jsx
  tests/utils/policy_roles_adapter.test.jsx
  utils/channel_intro_messages.jsx
  utils/policy_roles_adapter.js
Labels: 2: Dev Review

#837 translations PR 20180219
  i18n/de.json
  i18n/en.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ru.json
  i18n/tr.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 2: Dev Review

#814 PLT-7783: Migrate create_team/* to be pure and use Redux
  components/create_team/components/display_name.jsx
  components/create_team/components/team_url/index.js
  components/create_team/components/team_url/team_url.jsx
  components/create_team/create_team.jsx
  components/create_team/index.js
  components/root.jsx
  tests/components/create_team/__snapshots__/create_team.test.jsx.snap
  tests/components/create_team/__snapshots__/display_name.test.jsx.snap
  tests/components/create_team/__snapshots__/team_url.test.jsx.snap
  tests/components/create_team/create_team.test.jsx
  tests/components/create_team/display_name.test.jsx
  tests/components/create_team/team_url.test.jsx
Labels: 3: Ready to Merge

#838 Optimize post_time.jsx
  components/post_view/post_time.jsx
Labels: 3: Ready to Merge

#824 MM-8681 Adding client ability to use separate websocket endpoint.
  actions/websocket_actions.jsx
Labels: 3: Ready to Merge

#840 MM-9654 Updated channel routing to better handle 26 character long character names
  components/channel_identifier_router.jsx
Labels: 3: Ready to Merge

#842 MM-9659 Render and request emojis in message attachments
  components/post_view/post_attachment.jsx
  yarn.lock
Labels: 3: Ready to Merge

#799 Minor Ui improvements
  components/emoji_picker/components/emoji_picker_item.jsx
  sass/components/_emojisprite.scss
  sass/components/_emoticons.scss
  sass/layout/_post.scss
  utils/utils.jsx
Labels: 3: Ready to Merge

#850 MM-8009 Fix delete button not getting focused from edit modal
  components/create_post/create_post.jsx
  components/delete_post_modal.jsx
  components/edit_post_modal/edit_post_modal.jsx
  tests/components/create_post/create_post.test.jsx
  tests/components/edit_post_modal.test.jsx
Labels: 3: Ready to Merge

#847 MM-8228 Fix resizing window forcing scroll to bottom
  components/post_view/post_list.jsx
Labels: 3: Ready to Merge

#851 MM-8882 Don't show WebRTC icon in non-DM channels in mobile view
  components/navbar/navbar.jsx
Labels: 3: Ready to Merge

#839 [MM-9571] Set number of system emojis count to show
  components/emoji_picker/emoji_picker.jsx
Labels: 3: Ready to Merge

#853 MM-9677 Fixed being unable to go to DMs/GMs using old routes
  components/channel_identifier_router.jsx
Labels: 3: Ready to Merge

#854 MM-9678 Open new DM/GM channel links in the current tab
  utils/markdown/renderer.jsx
Labels: 3: Ready to Merge

#855 MM-9583: improve malformed pdf behavior
  components/pdf_preview.jsx
Labels: 2: Dev Review

#858 Reverting ICU-745 and MM-9149 to fix (To solve MM-9680 and MM-9682)
  components/sidebar_right/sidebar_right.jsx
Labels: 3: Ready to Merge

#859 Fixed Send Message link in profile popover
  components/profile_popover.jsx
Labels: 3: Ready to Merge

#844 [MM-8007] Force focus to textbox when the period since the last blur is greater than the fasterThanHumanWillClick
  components/create_comment/create_comment.jsx
Labels: 2: Dev Review

#846 MM-8777: Highlighting usernames on exact mention
  utils/text_formatting.jsx
Labels: 2: Dev Review

#849 [MM-9055] Fix sidebar unread above indicator
  components/sidebar/sidebar.jsx
Labels: 2: Dev Review

#857 MM-9658 - Fixing bot messages
  sass/layout/_webhooks.scss
Labels: 2: Dev Review

#869 MM-7188: Update unread on server when receive a notification on your channel
  stores/channel_store.jsx
Labels: 3: Ready to Merge

#861 MM-8042: Accepts ⌘+enter to comment (et al)
  components/create_comment/create_comment.jsx
  components/create_post/create_post.jsx
  components/edit_channel_header_modal/edit_channel_header_modal.jsx
  components/edit_channel_purpose_modal/edit_channel_purpose_modal.jsx
  components/edit_post_modal/edit_post_modal.jsx
  components/new_channel_modal/new_channel_modal.jsx
  utils/utils.jsx
Labels: 3: Ready to Merge

#856 Disabling the GlobalRelay support in the interface for 4.8 release
  components/admin_console/message_export_settings.jsx
  i18n/en.json
  tests/components/admin_console/__snapshots__/message_export_settings.test.jsx.snap
Labels: 3: Ready to Merge

#864 MM-8593 Add announcement bar for sysadmins when APIv3 is enabled, other minor clean-up
  components/announcement_bar/announcement_bar.jsx
  components/announcement_bar/index.js
  i18n/en.json
  root.jsx
  tests/helpers/client-test-helper.jsx
  utils/constants.jsx
Labels: 3: Ready to Merge

#870 MM-8219 Fix expanded RHS overlay not covering team sidebar
  sass/layout/_sidebar-left.scss
  sass/layout/_team-sidebar.scss
Labels: 3: Ready to Merge

#868 MM-9681: Fix the click in the emoji picker
  components/emoji_picker/components/emoji_picker_item.jsx
  sass/components/_emoticons.scss
Labels: 2: Dev Review

#871 MM-9586 Fixed CJK typing in the channel switcher/search box on desktop apps
  components/quick_input.jsx
Labels: 3: Ready to Merge

#873 MM-8534: Fix insecure image loading by post author
  components/post_markdown/index.js
  components/post_markdown/post_markdown.jsx
  tests/plugins/__snapshots__/post_type.test.jsx.snap
  utils/markdown/renderer.jsx
  utils/text_formatting.jsx
Labels: 3: Ready to Merge

#877 Merge release-4.7 into master
  components/channel_layout/channel_identifier_router.jsx
  components/post_view/post_attachment.jsx
  components/profile_popover.jsx
  utils/markdown/renderer.jsx
  yarn.lock
Labels: 2: Dev Review

#867 [MM-9685] Update channel header
  components/channel_header/channel_header.jsx
  components/channel_header/components/header_icon_wrapper.jsx
  components/channel_header/index.js
  components/search_bar/search_bar.jsx
  i18n/en.json
  sass/layout/_headers.scss
  sass/responsive/_tablet.scss
  tests/components/channel_header/components/__snapshots__/header_icon_wrapper.test.jsx.snap
  tests/components/channel_header/components/header_icon_wrapper.test.jsx
  utils/utils.jsx
Labels: 3: Ready to Merge

#845 [MM-8008] Add force focus to textbox on handleFileUploadChange which is especially important to mobile classic app
  components/create_comment/create_comment.jsx
  components/create_post/create_post.jsx
  components/file_upload/file_upload.jsx
  tests/components/create_post/create_post.test.jsx
  tests/components/file_upload/file_upload.test.jsx
Labels: 3: Ready to Merge

#878 Fixing bad merge
  yarn.lock
Labels: 3: Ready to Merge

#876 MM-9586 Only update value of certain textboxes after a delay
  components/quick_input.jsx
  components/quick_switch_modal/quick_switch_modal.jsx
  components/search_bar/search_bar.jsx
Labels: 3: Ready to Merge

#886 User lock file to get yarn dependencies
  Makefile
Labels: 3: Ready to Merge

#862 Remove mm_config and mm_license global state from webapp, phase 2 (PR #1)
  components/at_mention/at_mention.jsx
  components/error_page/error_page.jsx
  components/error_page/index.jsx
  components/profile_picture.jsx
  components/profile_popover/index.js
  components/profile_popover/profile_popover.jsx
  components/select_team/index.js
  components/select_team/select_team.jsx
  components/suggestion/switch_channel_provider.jsx
  components/user_profile.jsx
  tests/components/__snapshots__/profile_picture.test.jsx.snap
  tests/plugins/__snapshots__/pluggable.test.jsx.snap
  tests/plugins/pluggable.test.jsx
Labels: 3: Ready to Merge

#865 Remove mm_config and mm_license global state from webapp, phase 2 (PR #3)
  components/audio_video_preview.jsx
  components/channel_header/channel_header.jsx
  components/channel_header/index.js
  components/channel_members_dropdown/channel_members_dropdown.jsx
  components/code_preview.jsx
  components/file_attachment/file_attachment.jsx
  components/file_attachment/index.js
  components/file_attachment_list/file_attachment_list.jsx
  components/file_info_preview/file_info_preview.jsx
  components/file_info_preview/index.js
  components/logged_in/index.js
  components/logged_in/logged_in.jsx
  components/needs_team/index.js
  components/needs_team/needs_team.jsx
  components/pdf_preview.jsx
  components/post_view/channel_intro_message/channel_intro_message.jsx
  components/post_view/channel_intro_message/index.js
  components/post_view/post_list.jsx
  components/single_image_view.jsx
  components/user_settings/notifications/user_settings_notifications.jsx
  components/view_image/image_preview.jsx
  components/view_image/index.js
  components/view_image/popover_bar.jsx
  components/view_image/view_image.jsx
  components/view_image_popover_bar/index.js
  stores/channel_store.jsx
  tests/components/__snapshots__/audio_video_preview.test.jsx.snap
  tests/components/__snapshots__/file_info_preview.test.jsx.snap
  tests/components/__snapshots__/image_preview.test.jsx.snap
  tests/components/__snapshots__/pdf_preview.test.jsx.snap
  tests/components/__snapshots__/view_image.test.jsx.snap
  tests/components/__snapshots__/view_image_popover_bar.test.jsx.snap
  tests/components/audio_video_preview.test.jsx
  tests/components/file_attachment.test.jsx
  tests/components/file_info_preview.test.jsx
  tests/components/image_preview.test.jsx
  tests/components/pdf_preview.test.jsx
  tests/components/view_image.test.jsx
  tests/components/view_image_popover_bar.test.jsx
  utils/file_utils.jsx
  utils/route.jsx
  utils/utils.jsx
Labels: 3: Ready to Merge

#852 [MM-3274] Changed ctrl+/ detection to event.key before event.keyCode
  components/create_post/create_post.jsx
  tests/components/create_post/create_post.test.jsx
  tests/utils/utils.test.jsx
  utils/utils.jsx
Labels: 3: Ready to Merge

#810 Add the autofocus into the login field in login page
  components/login/login_controller/login_controller.jsx
Labels: 3: Ready to Merge
