Repository mattermost/mattermost-webapp, pull requests merged in 2018-04, with the labels that each got.

#1032 MM-9923: Avoid to show a gray screen on jump
  components/permalink_view/permalink_view.jsx
Labels: 2: Dev Review

#1023 use getFileDownloadUrl when attempting to trigger downloads
  components/file_attachment/filename_overlay.jsx
  components/view_image/image_preview.jsx
  tests/components/__snapshots__/image_preview.test.jsx.snap
  tests/components/file_attachment/__snapshots__/filename_overlay.test.jsx.snap
  yarn.lock
Labels: 3: Ready to Merge

#1034 Update mattermost-redux to latest
  yarn.lock
Labels: 2: Dev Review

#1037 MM-10010: upgrade mattermost-redux
  yarn.lock
Labels: 3: Ready to Merge

#1038 translations PR 20180402
  i18n/de.json
  i18n/en.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ru.json
  i18n/tr.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 2: Dev Review

#1039 MM-9974: expose and use react-select's valueKey prop
  components/add_users_to_team/add_users_to_team.jsx
  components/channel_invite_modal/channel_invite_modal.jsx
  components/more_direct_channels/more_direct_channels.jsx
  components/multiselect/multiselect.jsx
  tests/components/__snapshots__/add_users_to_team.test.jsx.snap
Labels: 3: Ready to Merge

#1040 Add ChannelPermissionGate to navbar's add members
  components/navbar/navbar.jsx
  tests/components/navbar/__snapshots__/navbar.test.jsx.snap
Labels: 3: Ready to Merge

#1024 Eliminate yarn test spam
  components/profile_popover/index.js
  components/profile_popover/profile_popover.jsx
  components/sidebar/sidebar.jsx
  package.json
  store/index.js
  tests/components/__snapshots__/channel_notifications_modal.test.jsx.snap
  tests/components/__snapshots__/delete_post_modal.test.jsx.snap
  tests/components/analytics/doughnut_chart.test.jsx
  tests/components/channel_notifications_modal.test.jsx
  tests/components/create_comment/create_comment.test.jsx
  tests/components/delete_post_modal.test.jsx
  tests/components/dot_menu/dot_menu_empty.test.jsx
  tests/components/dot_menu/dot_menu_mobile.test.jsx
  tests/components/navbar/navbar.test.jsx
  tests/components/sidebar/sidebar.test.jsx
  tests/components/sidebar/sidebar_channel.test.jsx
  tests/components/user_settings/user_settings_display.test.jsx
  tests/plugins/__snapshots__/pluggable.test.jsx.snap
  tests/plugins/pluggable.test.jsx
  tests/redux/reducers/views/rhs.test.js
  tests/setup.js
  utils/constants.jsx
  utils/network.js
  utils/storage_utils.js
  yarn.lock
Labels: 2: Dev Review

#1041 [MM-10024] Fix optional parameter of haveIChannelPermission to correctly evaluate whether a user can manage members
  utils/channel_utils.jsx
Labels: 3: Ready to Merge

#1044 MM-10032: Fix permission used to show IsTrusted field in Oauth 2 integrations form
  components/integrations/abstract_oauth_app.jsx
  tests/components/integrations/__snapshots__/abstract_oauth_app.test.jsx.snap
Labels: 3: Ready to Merge

#1028 MM-9909 Allow plugins to add actions to the sidebar dropdowns
  components/sidebar/header/dropdown/index.js
  components/sidebar/header/dropdown/sidebar_header_dropdown.jsx
  components/sidebar_right_menu/index.js
  components/sidebar_right_menu/sidebar_right_menu.jsx
  plugins/index.js
  reducers/plugins/index.js
  tests/plugins/__snapshots__/main_menu_action.test.jsx.snap
  tests/plugins/main_menu_action.test.jsx
  utils/constants.jsx
Labels: 2: Dev Review

#1043 [MM-9959] Sort users of view/manage members per username and not by user's status
  components/member_list_channel/member_list_channel.jsx
Labels: 2: Dev Review

#1033 Updating styles for muted channel
  sass/layout/_headers.scss
  sass/layout/_sidebar-left.scss
Labels: 3: Ready to Merge

#1029 Mm 9995 handle admin console links
  components/admin_console/admin_console.jsx
  components/admin_console/index.js
  tests/components/admin_console/__snapshots__/admin_console.test.jsx.snap
  tests/components/admin_console/admin_console.test.jsx
  utils/markdown/renderer.jsx
Labels: 3: Ready to Merge

#1046 [MM-10033] Make the pinned and member buttons clickable after blur of search box
  components/search_bar/search_bar.jsx
Labels: 3: Ready to Merge

#1016 Update wording on DM restriction config setting
  components/admin_console/users_and_teams_settings/users_and_teams_settings.jsx
  i18n/en.json
Labels: 3: Ready to Merge

#1045 [MM-9989] Fix single image preview when posted at RHS
  components/file_attachment_list/file_attachment_list.jsx
  components/single_image_view/index.js
  components/single_image_view/single_image_view.jsx
Labels: 2: Dev Review

#1004 Removing pure components from gates
  components/permissions_gates/channel_permission_gate/channel_permission_gate.jsx
  components/permissions_gates/system_permission_gate/system_permission_gate.jsx
  components/permissions_gates/team_permission_gate/team_permission_gate.jsx
Labels: 3: Ready to Merge

#1035 MM-9997 Track search box input seaprate from results highlighting
  actions/views/rhs.js
  components/search_bar/search_bar.jsx
  components/search_results/index.jsx
  components/search_results/search_results.jsx
  reducers/views/rhs.js
  selectors/rhs.jsx
  tests/redux/actions/views/rhs.test.js
  tests/redux/reducers/views/rhs.test.js
  utils/constants.jsx
Labels: 3: Ready to Merge

#1047 MM-9860: mark atBottom only after finish initial positioning
  components/post_view/post_list.jsx
Labels: 3: Ready to Merge

#1025 [MM-9956] Remove last uses of IntegrationStore and delete the store
  components/integrations/confirm_integration/confirm_integration.jsx
  components/integrations/confirm_integration/index.js
  stores/integration_store.jsx
Labels: 2: Dev Review

#1042 JS error quick fix on teamId props of RhsComment
  components/rhs_comment/rhs_comment.jsx
  components/rhs_thread/rhs_thread.jsx
Labels: 3: Ready to Merge

#1052 MM-9973: ignore dispatched events against unregistered suggestion boxes
  stores/suggestion_store.jsx
  tests/stores/suggestion_store.test.jsx
Labels: 3: Ready to Merge

#1053 MM-10037 Request next page of users correctly in system console
  components/admin_console/system_users/system_users.jsx
Labels: 3: Ready to Merge

#1056 MM-10040: Fix ALT+UP/ALT+DOWN channel switch
  components/sidebar/index.js
  components/sidebar/sidebar.jsx
  tests/components/sidebar/sidebar.test.jsx
Labels: 3: Ready to Merge

#1058 [MM-9785] Fix timestamp, ability to flag and not respecting teammate name display setting of add to channel ephemeral post on RHS
  actions/global_actions.jsx
  components/post_view/post_add_channel_member/post_add_channel_member.jsx
  components/rhs_comment/rhs_comment.jsx
  tests/components/post_view/post_add_channel_member/post_add_channel_member.test.jsx
Labels: 3: Ready to Merge

#1061 pass the download link to the PopoverBar to "Download"
  components/view_image/view_image.jsx
  tests/components/__snapshots__/view_image.test.jsx.snap
Labels: 3: Ready to Merge

#1054 MM-10041: Fixed reactions permissions on RHS posts
  components/rhs_comment/index.js
  components/rhs_root_post/index.js
  components/rhs_root_post/rhs_root_post.jsx
  components/rhs_thread/rhs_thread.jsx
Labels: 3: Ready to Merge

#1062 MM-10086: fix cancel delete post modal
  components/delete_post_modal/delete_post_modal.jsx
  tests/components/__snapshots__/delete_post_modal.test.jsx.snap
  tests/components/delete_post_modal.test.jsx
Labels: 3: Ready to Merge

#1048 Throttling the postListScrollChange action
  actions/global_actions.jsx
  components/create_post/index.js
Labels: 3: Ready to Merge

#996 Migrate ldap settings to declarative admin
  components/admin_console/admin_console.jsx
  components/admin_console/admin_definition.jsx
  components/admin_console/connection_security_dropdown_setting.jsx
  components/admin_console/ldap_settings.jsx
  components/admin_console/schema_admin_settings.jsx
  tests/components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
  tests/components/admin_console/admin_definition.test.jsx
  tests/components/admin_console/schema_admin_settings.test.jsx
  utils/constants.jsx
Labels: 3: Ready to Merge

#1050 MM-8792: Remove policy and create announcement banner section
  components/admin_console/admin_console.jsx
  components/admin_console/admin_definition.jsx
  components/admin_console/admin_sidebar/admin_sidebar.jsx
  components/admin_console/color_setting.jsx
  components/admin_console/policy_settings/index.jsx
  components/admin_console/policy_settings/policy_settings.jsx
  components/admin_console/schema_admin_settings.jsx
  i18n/en.json
  tests/components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
  tests/components/admin_console/admin_definition.test.jsx
  tests/components/admin_console/schema_admin_settings.test.jsx
  utils/constants.jsx
Labels: 3: Ready to Merge

#1049 replacing unicode character ’ with ascii character '
  README.md
  components/admin_console/admin_definition.jsx
  components/help/components/composing.jsx
  components/help/components/formatting.jsx
  components/more_direct_channels/more_direct_channels.jsx
  components/sidebar/sidebar_tutorial_tip.jsx
  components/tutorial/tutorial_intro_screens.jsx
  i18n/en.json
  root.html
  tests/components/sidebar/__snapshots__/sidebar_tutorial_tip.test.jsx.snap
Labels: 3: Ready to Merge

#1055 Fix loading state of invite channel modal
  components/channel_invite_modal/channel_invite_modal.jsx
Labels: 3: Ready to Merge

#1074 Merge49intomaster
  actions/global_actions.jsx
  components/admin_console/manage_tokens_modal/index.js
  components/admin_console/system_users/system_users.jsx
  components/delete_post_modal/delete_post_modal.jsx
  components/post_view/post_add_channel_member/post_add_channel_member.jsx
  components/rhs_comment/index.js
  components/rhs_comment/rhs_comment.jsx
  components/rhs_root_post/index.js
  components/rhs_root_post/rhs_root_post.jsx
  components/rhs_thread/rhs_thread.jsx
  components/sidebar/index.js
  components/sidebar/sidebar.jsx
  components/view_image/view_image.jsx
  stores/suggestion_store.jsx
  tests/components/__snapshots__/delete_post_modal.test.jsx.snap
  tests/components/__snapshots__/view_image.test.jsx.snap
  tests/components/delete_post_modal.test.jsx
  tests/components/post_view/post_add_channel_member/post_add_channel_member.test.jsx
  tests/components/sidebar/sidebar.test.jsx
  tests/stores/suggestion_store.test.jsx
Labels: 2: Dev Review

#1064 MM-10110: Fix email notifications enable/disable dependencies
  components/admin_console/email_settings.jsx
Labels: 3: Ready to Merge

#1065 MM-10096: Fix permissions checking in mobile view menu
  components/sidebar_right_menu/index.js
Labels: 3: Ready to Merge

#1066 Release 4.9 bug fixes
  components/channel_header/channel_header.jsx
  sass/layout/_headers.scss
  sass/layout/_sidebar-right.scss
  sass/responsive/_mobile.scss
Labels: 3: Ready to Merge

#1076 Add missing getState on forceLogoutIfNecessary
  actions/file_actions.jsx
Labels: 3: Ready to Merge

#1083 MM-8180 Remove connection unsuccessful message now that server returns it
  components/admin_console/email_connection_test/email_connection_test.jsx
  i18n/en.json
Labels: 3: Ready to Merge

#1078 translations PR 20180411
  i18n/de.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ru.json
  i18n/tr.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 3: Ready to Merge

#1082 MM-9805: When hiding/closing team settings modal, reset what is displayed.
  components/team_settings_modal.jsx
Labels: 3: Ready to Merge

#1089 MM-10129: Loads roles for use by system permission gate if not loaded.
  components/select_team/index.js
  components/select_team/select_team.jsx
Labels: 3: Ready to Merge

#1086 MM-10136: Not allowing to edit others posts in the interface
  utils/post_utils.jsx
Labels: 3: Ready to Merge

#1084 MM-9803: Fixes cursor placement in team and user settings.
  components/team_general_tab/team_general_tab.jsx
  components/user_settings/general/user_settings_general.jsx
  components/user_settings/notifications/user_settings_notifications.jsx
  utils/utils.jsx
Labels: 3: Ready to Merge

#1014 MM-9639 Obey max post length as provided by server
  components/create_comment/create_comment.jsx
  components/create_comment/index.js
  components/create_post/create_post.jsx
  components/create_post/index.js
  components/edit_post_modal/edit_post_modal.jsx
  components/edit_post_modal/index.js
  components/textbox.jsx
  tests/components/create_comment/create_comment.test.jsx
  tests/components/create_post/create_post.test.jsx
  tests/components/edit_post_modal.test.jsx
  tests/components/textbox.test.jsx
  utils/constants.jsx
Labels: 3: Ready to Merge

#1057 MM-9958 UI updates to personal access token creation
  components/confirm_modal.jsx
  components/user_settings/modal/user_settings_modal.jsx
  components/user_settings/security/index.js
  components/user_settings/security/user_access_token_section/index.js
  components/user_settings/security/user_access_token_section/user_access_token_section.jsx
  components/user_settings/security/user_settings_security.jsx
  components/user_settings/user_settings.jsx
  i18n/en.json
Labels: 3: Ready to Merge

#1077 MM-10111: Omits PostBodyAdditionalContent if post is deleted.
  components/message_with_additional_content.jsx
  components/rhs_comment/index.js
  components/rhs_comment/rhs_comment.jsx
  components/rhs_root_post/index.js
  components/rhs_root_post/rhs_root_post.jsx
Labels: 3: Ready to Merge

#1093 Fixing missing channel unread and mentions when activating window
  components/needs_team/index.js
  components/needs_team/needs_team.jsx
Labels: 3: Ready to Merge

#1091 JS error quick fix on onHide function of MoreDirectChannels
  components/more_direct_channels/more_direct_channels.jsx
Labels: 3: Ready to Merge

#1088 Release 4.9 fixes
  components/profile_popover/profile_popover.jsx
  sass/responsive/_mobile.scss
  tests/plugins/__snapshots__/pluggable.test.jsx.snap
Labels: 3: Ready to Merge

#1097 MM-10042 Fix 'null' (the string) being sent to addUserToTeamFromInvite
  components/signup/signup_ldap/signup_ldap.jsx
Labels: 2: Dev Review

#1098 Merge release-4.9 into master
  components/admin_console/email_settings.jsx
  components/channel_header/channel_header.jsx
  components/message_with_additional_content.jsx
  components/needs_team/index.js
  components/needs_team/needs_team.jsx
  components/profile_popover/profile_popover.jsx
  components/rhs_comment/index.js
  components/rhs_comment/rhs_comment.jsx
  components/rhs_root_post/index.js
  components/rhs_root_post/rhs_root_post.jsx
  components/select_team/index.js
  components/select_team/select_team.jsx
  components/sidebar_right_menu/index.js
  components/team_settings_modal.jsx
  i18n/de.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ru.json
  i18n/tr.json
  i18n/zh-CN.json
  i18n/zh-TW.json
  sass/layout/_headers.scss
  sass/layout/_sidebar-right.scss
  sass/responsive/_mobile.scss
  tests/plugins/__snapshots__/pluggable.test.jsx.snap
  utils/post_utils.jsx
Labels: 2: Dev Review

#1099 MM-10197 Stopped setting QuickInput value when already set
  components/quick_input.jsx
Labels: 3: Ready to Merge

#1100 MM-10174: reflect that log settings require a restart
  components/admin_console/admin_definition.jsx
  i18n/en.json
Labels: 3: Ready to Merge

#1096 MM-9827 Remove getState usage in SwitchChannelSuggestion
  components/suggestion/switch_channel_provider.jsx
Labels: 3: Ready to Merge

#1095 Fix error in LDAP sync help text
  components/admin_console/admin_definition.jsx
  i18n/en.json
Labels: 3: Ready to Merge

#1090 MM-9831: expunge get state in admin console
  components/admin_console/system_users/index.js
  components/admin_console/system_users/list/index.js
  components/admin_console/system_users/list/selectors.jsx
  components/admin_console/system_users/list/system_users_list.jsx
  components/admin_console/system_users/system_users.jsx
  package.json
  tests/components/admin_console/system_users/__snapshots__/system_users.test.jsx.snap
  tests/components/admin_console/system_users/__snapshots__/system_users_list.test.jsx.snap
  tests/components/admin_console/system_users/selectors.test.jsx
  tests/components/admin_console/system_users/system_users.test.jsx
  tests/components/admin_console/system_users/system_users_list.test.jsx
  yarn.lock
Labels: 3: Ready to Merge

#1105 Merge 4.9 into master
  components/admin_console/admin_definition.jsx
  components/quick_input.jsx
  i18n/en.json
Labels: 2: Dev Review

#1108 MM-8528: prevent duplicate posts on retries
  components/post_view/failed_post_options/failed_post_options.jsx
  components/post_view/failed_post_options/index.js
  tests/components/post_view/__snapshots__/failed_post_options.test.jsx.snap
  tests/components/post_view/failed_post_options.test.jsx
  tests/setup.js
Labels: 3: Ready to Merge

#1081 MM-9858: Declares character encoding in HTML.
  root.html
Labels: 2: Dev Review

#1110 Change Total Users --> Total Active Users in System Console statistics pages
  components/analytics/system_analytics/system_analytics.jsx
  components/analytics/team_analytics/team_analytics.jsx
  i18n/en.json
Labels: 3: Ready to Merge

#1109 Replacing hash usage with token for invitations
  actions/team_actions.jsx
  actions/user_actions.jsx
  components/login/login_controller/login_controller.jsx
  components/signup/signup_controller/signup_controller.jsx
  components/signup/signup_email/signup_email.jsx
  components/signup/signup_ldap/signup_ldap.jsx
Labels: 2: Dev Review

#1111 [MM-9984] Remove WebRTC end user settings
  components/channel_header/channel_header.jsx
  components/navbar/navbar.jsx
  components/profile_popover/profile_popover.jsx
  components/user_settings/advanced/index.js
  components/user_settings/advanced/user_settings_advanced.jsx
  components/webrtc/notification/index.js
  components/webrtc/notification/webrtc_notification.jsx
  i18n/en.json
  utils/constants.jsx
  utils/utils.jsx
Labels: 2: Dev Review

#1113 MM-9988: rename to "Open" external images
  components/post_view/post_body_additional_content/post_body_additional_content.jsx
  components/view_image/popover_bar/index.js
  components/view_image/popover_bar/popover_bar.jsx
  components/view_image/view_image.jsx
  i18n/en.json
  tests/components/__snapshots__/view_image.test.jsx.snap
  tests/components/__snapshots__/view_image_popover_bar.test.jsx.snap
  tests/components/view_image.test.jsx
  tests/components/view_image_popover_bar.test.jsx
  tests/setup.js
Labels: 3: Ready to Merge

#1106 MM-9829 Remove store.getState() usages from user list modals
  actions/team_actions.jsx
  actions/user_actions.jsx
  actions/views/search.js
  components/add_users_to_team/add_users_to_team.jsx
  components/add_users_to_team/index.js
  components/member_list_channel/index.js
  components/member_list_channel/member_list_channel.jsx
  components/member_list_team/index.js
  components/member_list_team/member_list_team.jsx
  components/more_direct_channels/index.js
  components/more_direct_channels/more_direct_channels.jsx
  components/post_view/post_add_channel_member/index.js
  reducers/views/index.js
  reducers/views/search.js
  tests/components/add_users_to_team.test.jsx
  utils/constants.jsx
Labels: 3: Ready to Merge

#1107 MM-9924: Updates placement of date separator.
  components/rhs_thread/rhs_thread.jsx
Labels: 2: Dev Review, Awaiting Submitter Action

#1119 MM-10293: More robust initial load on admin_console pages for loadRolesIfNeeded
  components/admin_console/custom_integrations_settings/custom_integrations_settings.jsx
  components/admin_console/custom_integrations_settings/index.jsx
  components/admin_console/policy_settings/index.jsx
  components/admin_console/policy_settings/policy_settings.jsx
  components/admin_console/users_and_teams_settings/index.jsx
  components/admin_console/users_and_teams_settings/users_and_teams_settings.jsx
Labels: 2: Dev Review

#1123 Revert "MM-8528: prevent duplicate posts on retries (#1108)"
  components/post_view/failed_post_options/failed_post_options.jsx
  components/post_view/failed_post_options/index.js
  tests/components/post_view/__snapshots__/failed_post_options.test.jsx.snap
  tests/components/post_view/failed_post_options.test.jsx
Labels: 2: Dev Review

#1117 Migrating metrics and developer config sections in the admin console
  components/admin_console/admin_console.jsx
  components/admin_console/admin_definition.jsx
  components/admin_console/developer_settings.jsx
  components/admin_console/metrics_settings.jsx
Labels: 2: Dev Review

#1126 Added explicit versions to all packages
  package-lock.json
  package.json
Labels: 2: Dev Review

#1070 [MM-10062] Revert help note when team creation is set to system admin only
  components/select_team/index.js
  components/select_team/select_team.jsx
Labels: 3: Ready to Merge

#1121 MM-10095: Fix for invalid wildcard suffix pattern.
  tests/utils/formatting_wildcards.text.jsx
  utils/text_formatting.jsx
Labels: 3: Ready to Merge

#1131 Fix sign-up and team joining
  components/select_team/select_team.jsx
  components/signup/signup_email/signup_email.jsx
Labels: 3: Ready to Merge

#1124 Update channel parameter help text on incoming webhooks set up page
  components/integrations/abstract_incoming_webhook.jsx
  i18n/en.json
  tests/components/integrations/__snapshots__/abstract_incoming_hook.test.jsx.snap
Labels: 3: Ready to Merge

#1132 Update mattermost-redux to deduplicate retrying posts.
  components/post_view/failed_post_options/failed_post_options.jsx
  components/post_view/failed_post_options/index.js
  package-lock.json
  package.json
  tests/components/post_view/__snapshots__/failed_post_options.test.jsx.snap
  tests/components/post_view/failed_post_options.test.jsx
Labels: 3: Ready to Merge

#1129 Shift+up switch keyboard focus to RHS if it's already open to the current thread
  components/create_post/create_post.jsx
  components/create_post/index.js
  tests/components/create_post/create_post.test.jsx
Labels: 2: Dev Review

#1133 MM-9828 eliminate get state in modal components
  actions/post_actions.jsx
  components/dot_menu/dot_menu_edit.jsx
  components/edit_post_modal/edit_post_modal.jsx
  components/quick_switch_modal/index.js
  components/quick_switch_modal/quick_switch_modal.jsx
  tests/components/__snapshots__/quick_switch_modal.test.jsx.snap
  tests/components/dot_menu/dot_menu_edit.test.jsx
  tests/components/edit_post_modal.test.jsx
  tests/components/quick_switch_modal.test.jsx
  tests/redux/actions/posts.test.js
Labels: 2: Dev Review

#1138 MM-10134 (4.9) Remove unneeded populate channel functions and await on each GM users request
  actions/user_actions.jsx
Labels: 3: Ready to Merge

#1130 Only save config files when config fields are changed
  components/admin_console/admin_settings.jsx
  components/admin_console/custom_integrations_settings/custom_integrations_settings.jsx
  components/admin_console/policy_settings/policy_settings.jsx
  components/admin_console/users_and_teams_settings/users_and_teams_settings.jsx
  i18n/en.json
Labels: 3: Ready to Merge

#1120 MM-10293: More robust initial load on admin_console pages for loadRolesIfNeeded [Backport to 4.9]
  components/admin_console/custom_integrations_settings/custom_integrations_settings.jsx
  components/admin_console/custom_integrations_settings/index.jsx
  components/admin_console/policy_settings/index.jsx
  components/admin_console/policy_settings/policy_settings.jsx
  components/admin_console/users_and_teams_settings/index.jsx
  components/admin_console/users_and_teams_settings/users_and_teams_settings.jsx
Labels: 3: Ready to Merge

#418 #7775: allow team / system admin to convert a channel to private
  components/channel_header/channel_header.jsx
  components/convert_channel_modal/convert_channel_modal.jsx
  components/convert_channel_modal/index.js
  components/navbar/navbar.jsx
  components/post_markdown/system_message_helpers.jsx
  i18n/en.json
  tests/components/navbar/__snapshots__/navbar.test.jsx.snap
  utils/constants.jsx
Labels: Awaiting PR

#1128 MM-10180 Better handle characters after periods in URLs
  package-lock.json
  package.json
Labels: 3: Ready to Merge

#1118 MM-10028 Add system notice feature with API deprecation notice
  actions/views/notice.js
  components/admin_console/admin_console.jsx
  components/backstage/backstage_controller.jsx
  components/channel_layout/channel_controller.jsx
  components/system_notice/index.js
  components/system_notice/notices.jsx
  components/system_notice/system_notice.jsx
  i18n/en.json
  reducers/views/index.js
  reducers/views/notice.js
  sass/components/_buttons.scss
  sass/components/_module.scss
  sass/components/_system-notice.scss
  sass/utils/_modifiers.scss
  sass/utils/_module.scss
  sass/utils/_variables.scss
  tests/components/__snapshots__/system_notice.test.jsx.snap
  tests/components/system_notice.test.jsx
  utils/constants.jsx
  utils/utils.jsx
Labels: 3: Ready to Merge

#1141 Update settings text when email/push notifications are disabled on the server
  components/user_settings/notifications/email_notification_setting.jsx
  components/user_settings/notifications/user_settings_notifications.jsx
  i18n/en.json
  tests/components/user_settings/__snapshots__/email_notification_setting.test.jsx.snap
Labels: 2: Dev Review

#1073 Migrate select team to redux store
  components/select_team/index.js
  components/select_team/select_team.jsx
  package-lock.json
  package.json
  tests/components/select_team/__snapshots__/select_team.test.jsx.snap
  tests/components/select_team/__snapshots__/select_team_item.test.jsx.snap
  tests/components/select_team/select_team.test.jsx
  tests/components/select_team/select_team_item.test.jsx
Labels: 3: Ready to Merge

#1143 Minor Ui fixes
  sass/components/_emoticons.scss
  sass/components/_modal.scss
Labels: 2: Dev Review

#1148 Revert "[MM-1915] Add Deactivate Account (#1115)"
  components/confirm_modal.jsx
  components/setting_item_max.jsx
  components/user_settings/advanced/user_settings_advanced.jsx
  i18n/en.json
  tests/components/__snapshots__/setting_item_max.test.jsx.snap
  tests/components/setting_item_max.test.jsx
Labels: 3: Ready to Merge

#1146 [MM-10354] Add feature to remove team icon
  components/setting_picture.jsx
  components/team_general_tab/index.js
  components/team_general_tab/team_general_tab.jsx
  components/user_settings/general/user_settings_general.jsx
  i18n/en.json
  package-lock.json
  package.json
  sass/components/_buttons.scss
  sass/layout/_team-sidebar.scss
  sass/routes/_settings.scss
  tests/components/team_general_tab.test.jsx
  utils/utils.jsx
Labels: 3: Ready to Merge

#1150 MM-10403 Fixed rendering of text following a latex block
  tests/utils/__snapshots__/post_utils.test.jsx.snap
  tests/utils/post_utils.test.jsx
  utils/markdown/renderer.jsx
Labels: 2: Dev Review
