Repository mattermost/mattermost-webapp, pull requests merged in 2018-07, with the labels that each got.

#1359 [MM-10974] Remove Character Limit in Reset Email Modal
  components/admin_console/reset_email_modal/reset_email_modal.jsx
Labels: 3: Ready to Merge

#1397 MM-10767: Fix the ordering for chrome
  components/team_selector_modal/team_selector_modal.jsx
Labels: 2: Dev Review

#1393 MM-10877 - Updating edited behaviour IE11
  sass/layout/_post.scss
Labels: 3: Ready to Merge

#1398 MM-11113 Used getTheme selector in gif picker
  components/gif_picker/components/Categories/index.jsx
  components/gif_picker/components/Header/index.jsx
  components/gif_picker/components/SearchBar/index.jsx
  components/gif_picker/components/SearchGrid/SearchGrid.jsx
Labels: 3: Ready to Merge

#1394 MM-10981: Fix redirect to last channel http://<host>/ load
  actions/global_actions.jsx
Labels: 3: Ready to Merge

#1340 user.settings.custom_theme.mentionBg typo
  components/user_settings/display/custom_theme_chooser.jsx
  i18n/en.json
Labels: 3: Ready to Merge

#1399 Ui improvements
  components/emoji_picker/emoji_picker.jsx
  components/gif_picker/components/SearchBar/SearchBar.scss
  components/gif_picker/components/SearchBar/index.jsx
  components/gif_picker/components/SearchGrid/SearchGrid.jsx
  components/gif_picker/components/SearchGrid/SearchGrid.scss
  components/svg/attachment_icon.jsx
  components/team_sidebar/team_sidebar_controller.jsx
  sass/components/_emoticons.scss
  sass/layout/_post.scss
  utils/utils.jsx
Labels: 3: Ready to Merge

#1401 translations PR 20180702
  i18n/de.json
  i18n/en.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ru.json
  i18n/tr.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 2: Dev Review

#1409 MM-11158: fix subpath logout
  selectors/general.js
Labels: 3: Ready to Merge

#1403 MM-11075: Fix external link redirects.
  components/sidebar/header/dropdown/sidebar_header_dropdown.jsx
Labels: 3: Ready to Merge

#1386 MM-10647: Fixes "composing" Korean character duplicate post bug.
  components/create_post/create_post.jsx
  utils/constants.jsx
  utils/utils.jsx
Labels: 3: Ready to Merge

#1410 Release 5.1 daily merge 20180706
  components/create_post/create_post.jsx
  components/emoji_picker/emoji_picker.jsx
  components/gif_picker/components/SearchBar/SearchBar.scss
  components/gif_picker/components/SearchBar/index.jsx
  components/gif_picker/components/SearchGrid/SearchGrid.jsx
  components/gif_picker/components/SearchGrid/SearchGrid.scss
  components/post_view/post_message_view/post_message_view.jsx
  components/sidebar/header/dropdown/sidebar_header_dropdown.jsx
  components/svg/attachment_icon.jsx
  components/team_sidebar/team_sidebar_controller.jsx
  i18n/de.json
  i18n/en.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ru.json
  i18n/tr.json
  i18n/zh-CN.json
  i18n/zh-TW.json
  sass/components/_emoticons.scss
  sass/layout/_post.scss
  selectors/general.js
  tests/components/post_view/__snapshots__/post_message_view.test.jsx.snap
  tests/components/post_view/post_message_view.test.jsx
  utils/constants.jsx
  utils/utils.jsx
Labels: 3: Ready to Merge

#1400 MM-9815: Show how many messages were exported in the jobs table.
  components/admin_console/message_export_settings.jsx
  i18n/en.json
  tests/components/admin_console/__snapshots__/message_export_settings.test.jsx.snap
Labels: 2: Dev Review

#1406 Shrink RHS when clicking on the backdrop
  components/sidebar_right/index.js
  components/sidebar_right/sidebar_right.jsx
Labels: 3: Ready to Merge

#1411 Release 5.1 fixes
  components/navbar/navbar.jsx
  components/team_sidebar/components/team_button.jsx
  sass/base/_structure.scss
  sass/layout/_headers.scss
  sass/layout/_post.scss
  sass/responsive/_mobile.scss
  sass/routes/_signup.scss
  tests/components/navbar/__snapshots__/navbar.test.jsx.snap
  utils/utils.jsx
Labels: 3: Ready to Merge

#1418 MM-11163: Handle mobile view switch_team case
  components/get_android_app/get_android_app.jsx
  components/get_ios_app/get_ios_app.jsx
Labels: 3: Ready to Merge

#1412 MM-11170 Fix to remove unknown users from sidebar
  components/sidebar/sidebar_channel/index.js
Labels: 3: Ready to Merge

#1416 MM-11120 Adding new EmableEmailInvitations setting.
  components/admin_console/admin_definition.jsx
  components/sidebar/header/dropdown/index.js
  components/sidebar/header/dropdown/sidebar_header_dropdown.jsx
  i18n/en.json
  tests/plugins/__snapshots__/main_menu_action.test.jsx.snap
  tests/plugins/main_menu_action.test.jsx
  tests/setup.js
Labels: 3: Ready to Merge

#1420 MM-11238 Fix user joining a team though url
  components/needs_team/index.js
Labels: 3: Ready to Merge

#1423 translations PR 20180709
  i18n/de.json
  i18n/en.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ru.json
  i18n/tr.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 3: Ready to Merge

#1421 [MM-11222] Fix overflow issue on help pages
  sass/base/_structure.scss
Labels: 3: Ready to Merge

#1426 MM-10958: Fix elasticsearch settings interdependencies in system console
  components/admin_console/elasticsearch_settings.jsx
Labels: 3: Ready to Merge

#1422 Various plugin updates and fixes
  actions/websocket_actions.jsx
  components/post_profile_picture/post_profile_picture.jsx
  components/post_view/post_list.jsx
  components/sidebar/sidebar.jsx
  components/team_sidebar/team_sidebar_controller.jsx
  components/user_profile.jsx
  plugins/index.js
  plugins/registry.js
  sass/layout/_sidebar-left.scss
  sass/layout/_team-sidebar.scss
  tests/components/sidebar/__snapshots__/sidebar.test.jsx.snap
Labels: 2: Dev Review

#1429 Release 5.1 daily merge 20180710
  components/admin_console/admin_definition.jsx
  components/get_android_app/get_android_app.jsx
  components/get_ios_app/get_ios_app.jsx
  components/navbar/navbar.jsx
  components/needs_team/index.js
  components/sidebar/header/dropdown/index.js
  components/sidebar/header/dropdown/sidebar_header_dropdown.jsx
  components/sidebar/sidebar_channel/index.js
  components/team_sidebar/components/team_button.jsx
  i18n/de.json
  i18n/en.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ru.json
  i18n/tr.json
  i18n/zh-CN.json
  i18n/zh-TW.json
  sass/base/_structure.scss
  sass/layout/_headers.scss
  sass/layout/_post.scss
  sass/responsive/_mobile.scss
  sass/routes/_signup.scss
  tests/components/navbar/__snapshots__/navbar.test.jsx.snap
  tests/plugins/__snapshots__/main_menu_action.test.jsx.snap
  tests/plugins/main_menu_action.test.jsx
  tests/setup.js
  utils/utils.jsx
Labels: 2: Dev Review

#1431 MM-11225: Revert refactor.
  components/create_post/create_post.jsx
Labels: 3: Ready to Merge

#1430 MM-11247: fix ldap port saving
  components/admin_console/admin_definition.jsx
Labels: 3: Ready to Merge

#1424 MM-11248: fix custom emoij on subpath
  stores/emoji_store.jsx
Labels: 3: Ready to Merge

#1427 MM-11246: fix saml link buttons to respect subpath
  components/login/login_controller/login_controller.jsx
Labels: 3: Ready to Merge

#1432 MM-10981: Add support for GMs and DMs on initial redirect
  actions/global_actions.jsx
Labels: 3: Ready to Merge

#1435 MM-11197 Fix awkward English string
  components/admin_console/admin_definition.jsx
  components/user_settings/display/manage_languages.jsx
  i18n/en.json
Labels: 3: Ready to Merge

#1434 translations PR 20180711
  i18n/de.json
  i18n/en.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ru.json
  i18n/tr.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 3: Ready to Merge

#1440 MM-11214 Fix back button for deleted permalinks
  actions/global_actions.jsx
Labels: 3: Ready to Merge

#1407 Move isEmail regex to redux
  components/admin_console/reset_email_modal/reset_email_modal.jsx
  components/invite_member_modal/invite_member_modal.jsx
  components/password_reset_send_link.jsx
  components/signup/signup_email/signup_email.jsx
  components/user_settings/general/user_settings_general.jsx
  tests/utils/utils.test.jsx
  utils/utils.jsx
Labels: 3: Ready to Merge

#1437 Add System to Nickname Blacklist
  utils/constants.jsx
Labels: 2: Dev Review

#1417 MM-11109 Properly highlight mentions followed by an underscore
  utils/text_formatting.jsx
Labels: 3: Ready to Merge

#1443 Release 5.1 daily merge 20180712
  actions/global_actions.jsx
  components/admin_console/admin_definition.jsx
  components/create_post/create_post.jsx
  components/login/login_controller/login_controller.jsx
  i18n/de.json
  i18n/en.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ru.json
  i18n/tr.json
  i18n/zh-CN.json
  i18n/zh-TW.json
  stores/emoji_store.jsx
Labels: 2: Dev Review

#1438 [MM-11289] Fixes app crashing when adding a user to the channel via at-mention
  components/post_view/post/post.jsx
Labels: 3: Ready to Merge

#1436 MM-11238 Fix channel url join from another team
  components/channel_layout/channel_identifier_router.jsx
Labels: 3: Ready to Merge

#1425 [MM-11129] E2E: fix flaky tests on chrome
  tests/e2e/config.js
  tests/e2e/tests/3_sidebarLeft/accountSettingsDisplay.action.js
  tests/e2e/tests/3_sidebarLeft/accountSettingsGeneral.action.js
Labels: 3: Ready to Merge

#1444 Fix performance regression in channel switcher
  components/suggestion/switch_channel_provider.jsx
Labels: 3: Ready to Merge

#1414 Refactor PostList to remove some state and use new lifecycle methods
  components/post_view/post_list.jsx
Labels: 3: Ready to Merge

#1448 Release 5.1 daily merge 20180716
  components/channel_layout/channel_identifier_router.jsx
  components/post_view/post/post.jsx
Labels: 2: Dev Review

#1442 MM-11172: Apply read only town square rules to reactions as posts.
  components/post_view/reaction/index.js
  components/post_view/reaction/reaction.jsx
  sass/layout/_post.scss
  tests/components/post_view/__snapshots__/reaction.test.jsx.snap
Labels: 2: Dev Review

#1447 MM-11153: Sort teams by name in Team Analytics page
  components/analytics/team_analytics/team_analytics.jsx
Labels: 3: Ready to Merge

#1451 MM-11313 Removing unnessisary client side calls on channel delete.
  actions/websocket_actions.jsx
Labels: 2: Dev Review

#1452 MM-10926: updated plugin registry documentation
  plugins/index.js
  plugins/registry.js
Labels: 2: Dev Review

#1441 MM-11291 Prevent duplicate channel autocomplete requests after user presses space
  components/suggestion/channel_mention_provider.jsx
  tests/components/__snapshots__/textbox.test.jsx.snap
Labels: 3: Ready to Merge

#1460 MM-11251: Pluralize word in translation.
  components/claim/components/oauth_to_email.jsx
  i18n/en.json
Labels: 2: Dev Review

#1454 MM-11084 & MM-11100: More addaptative permissions tree
  components/admin_console/permission_schemes_settings/permission_system_scheme_settings/permission_system_scheme_settings.jsx
  components/admin_console/permission_schemes_settings/permission_team_scheme_settings/permission_team_scheme_settings.jsx
  components/admin_console/permission_schemes_settings/permissions_tree.jsx
  components/admin_console/permission_schemes_settings/permissions_tree/index.jsx
  components/admin_console/permission_schemes_settings/permissions_tree/permissions_tree.jsx
  i18n/en.json
  tests/components/admin_console/permission_schemes_settings/__snapshots__/permission_system_scheme_settings.test.jsx.snap
  tests/components/admin_console/permission_schemes_settings/__snapshots__/permission_team_scheme_settings.test.jsx.snap
  tests/components/admin_console/permission_schemes_settings/__snapshots__/permissions_tree.test.jsx.snap
  tests/components/admin_console/permission_schemes_settings/permissions_tree.test.jsx
Labels: 2: Dev Review

#1433 Turn hardcoded link to a clickable link
  components/admin_console/custom_gif_settings.jsx
  i18n/en.json
Labels: 3: Ready to Merge

#1455 MM-11371 - Fixing sidebar spacing issue
  sass/responsive/_mobile.scss
Labels: 3: Ready to Merge

#1462 MM-11418: Channging the admin console banners related to compliance exports
  components/admin_console/admin_definition.jsx
  components/admin_console/message_export_settings.jsx
  i18n/en.json
  tests/components/admin_console/__snapshots__/message_export_settings.test.jsx.snap
Labels: 2: Dev Review

#1465 Update mattermost-redux to latest
  package-lock.json
  package.json
Labels: 3: Ready to Merge

#1466 Change "Reset Email" to "Update Email" in System Console > Users
  components/admin_console/reset_email_modal/reset_email_modal.jsx
  components/admin_console/system_users/system_users_dropdown.jsx
  i18n/en.json
Labels: 3: Ready to Merge

#1463 MM-10999: Fix server ID setting race condition in diagnostics.
  actions/user_actions.jsx
  components/root/index.js
  components/root/root.jsx
Labels: 3: Ready to Merge

#1467 [MM-11422] Fix rendering of embedded images with long URLs in message attachment
  components/post_view/post_attachment.jsx
  components/post_view/post_attachment_opengraph/post_attachment_opengraph.jsx
  sass/layout/_webhooks.scss
  tests/components/post_view/__snapshots__/post_attachment.test.jsx.snap
  tests/components/post_view/post_attachment.test.jsx
  utils/utils.jsx
Labels: 2: Dev Review

#1303 Detect user-agent for mobile firefox and show app download page
  utils/user_agent.jsx
Labels: 3: Ready to Merge

#1384 MM-4858 Updates to Database settings
  components/admin_console/database_settings.jsx
  i18n/en.json
Labels: 3: Ready to Merge

#1446 Update profile picture help text.
  components/setting_picture.jsx
  components/user_settings/general/user_settings_general.jsx
  i18n/en.json
  tests/components/__snapshots__/setting_picture.test.jsx.snap
  tests/components/setting_picture.test.jsx
Labels: 3: Ready to Merge

#1478 addSwitchToEENotification: don't assume there is a current user
  actions/user_actions.jsx
Labels: 3: Ready to Merge

#1445 MM-10616 Refactoring dot menu component to make it easier to add a plugin hook.
  components/dot_menu/dot_menu.jsx
  components/dot_menu/dot_menu_edit.jsx
  components/dot_menu/dot_menu_flag.jsx
  components/dot_menu/dot_menu_item.jsx
  components/dot_menu/index.js
  components/post_view/post_info/post_info.jsx
  components/rhs_comment/rhs_comment.jsx
  components/rhs_root_post/rhs_root_post.jsx
  components/search_results_item/search_results_item.jsx
  tests/components/__snapshots__/search_results_item.test.jsx.snap
  tests/components/dot_menu/__snapshots__/dot_menu.test.jsx.snap
  tests/components/dot_menu/__snapshots__/dot_menu_edit.test.jsx.snap
  tests/components/dot_menu/__snapshots__/dot_menu_empty.test.jsx.snap
  tests/components/dot_menu/__snapshots__/dot_menu_flag.test.jsx.snap
  tests/components/dot_menu/__snapshots__/dot_menu_item.test.jsx.snap
  tests/components/dot_menu/dot_menu.test.jsx
  tests/components/dot_menu/dot_menu_edit.test.jsx
  tests/components/dot_menu/dot_menu_empty.test.jsx
  tests/components/dot_menu/dot_menu_flag.test.jsx
  tests/components/dot_menu/dot_menu_item.test.jsx
  tests/components/dot_menu/dot_menu_mobile.test.jsx
  tests/components/post_view/post_info/__snapshots__/post_info.test.jsx.snap
Labels: 2: Dev Review

#1472 MM-11243: Remove message about Elasticsearch restart.
  components/admin_console/elasticsearch_settings.jsx
  i18n/en.json
Labels: 3: Ready to Merge

#1475 MM-11160 CORS admin console additions.
  components/admin_console/admin_definition.jsx
  i18n/en.json
Labels: 2: Dev Review

#1474 translations PR 20180723
  i18n/de.json
  i18n/en.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ru.json
  i18n/tr.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 3: Ready to Merge

#1473 tweak plugin webpack externals
  plugins/index.js
Labels: 3: Ready to Merge

#1485 Fix JS error/warning on MobileChannelHeaderPlug by not requiring props.components
  plugins/mobile_channel_header_plug/mobile_channel_header_plug.jsx
Labels: 3: Ready to Merge

#1484 Clean up: get rid off ...ownProps
  components/about_build_modal/index.js
  components/access_history_modal/index.js
  components/admin_console/jobs/index.jsx
  components/admin_console/manage_roles_modal/index.js
  components/admin_console/permission_schemes_settings/edit_post_time_limit_button/index.jsx
  components/admin_console/permission_schemes_settings/edit_post_time_limit_modal/index.jsx
  components/admin_console/revoke_token_button/index.js
  components/admin_console/server_logs/index.js
  components/channel_info_modal/index.js
  components/channel_invite_modal/index.js
  components/delete_channel_modal/index.js
  components/file_attachment_list/index.js
  components/get_post_link_modal/index.js
  components/get_public_link_modal/index.js
  components/get_team_invite_link_modal/index.js
  components/header_footer_template/index.js
  components/modal_controller/index.js
  components/post_view/commented_on_files_message/index.js
  components/post_view/failed_post_options/index.js
  components/post_view/post_attachment_opengraph/index.js
  components/profile_popover/index.js
  components/reset_status_modal/index.js
  components/team_general_tab/index.js
  components/team_members_dropdown/index.js
  components/team_members_modal/index.js
Labels: 3: Ready to Merge

#1388 MM-11068: Adds config for TeamSettings.ViewArchivedChannels.
  components/admin_console/users_and_teams_settings/users_and_teams_settings.jsx
  i18n/en.json
Labels: 3: Ready to Merge, Awaiting PR

#1493 MM-11331 Autocomplete all users for system console username setting
  components/admin_console/user_autocomplete_setting.jsx
Labels: 3: Ready to Merge

#1496 Fix JS error on handleDropdownOpened of DotMenu
  components/dot_menu/dot_menu.jsx
Labels: 3: Ready to Merge

#1490 Fix OAuth redirect
  components/authorize.jsx
Labels: 3: Ready to Merge

#1494 translations PR 20180730
  i18n/de.json
  i18n/en.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ru.json
  i18n/tr.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 2: Dev Review

#1500 MM-11369: Hide 'Invite others to this team' link from channel intro w…
  components/post_view/channel_intro_message/channel_intro_message.jsx
  components/post_view/channel_intro_message/index.js
Labels: 2: Dev Review

#1498 MM-11176: Show the banner for licenses without clustering support (E10)
  actions/user_actions.jsx
Labels: 3: Ready to Merge

#1501 Allow duplicate terms for suggestion box
  components/suggestion/suggestion_box.jsx
  components/suggestion/suggestion_list.jsx
  stores/suggestion_store.jsx
Labels: 2: Dev Review
