Repository mattermost/mattermost-webapp, pull requests merged in 2018-10, with the labels that each got.

#1790 MM-12217 - Updating autocomplete css
  sass/base/_typography.scss
  sass/components/_mentions.scss
Labels: 3: Ready to Merge

#1784 MM-12257 preserve extra on logout
  components/login/login_controller/index.js
  components/login/login_controller/login_controller.jsx
  store/index.js
  tests/components/login/login_controller/__snapshots__/login_controller.test.jsx.snap
  tests/components/login/login_controller/login_controller.test.jsx
Labels: 3: Ready to Merge

#1728 MM-12221: Pass channel and channel member to onClick handler for mobile channel header plugins.
  plugins/mobile_channel_header_plug/mobile_channel_header_plug.jsx
Labels: 3: Ready to Merge

#1798 MM-12283 Add loader for more_channels modal
  components/more_channels/index.js
  components/more_channels/more_channels.jsx
  components/searchable_channel_list.jsx
  tests/components/__snapshots__/more_channels.test.jsx.snap
  tests/components/__snapshots__/searchable_channel_list.test.jsx.snap
  tests/components/more_channels.test.jsx
  tests/components/searchable_channel_list.test.jsx
Labels: 3: Ready to Merge

#1799 MM-11807: Add LDAP GroupFilter config field.
  components/admin_console/admin_definition.jsx
  i18n/en.json
Labels: 2: Dev Review

#1805 comment typo
  sass/styles.scss
Labels: 2: Dev Review

#1772 [MM-12264] do not load redirect_location if enablelinkpreview is disabled
  components/post_view/post_body_additional_content/post_body_additional_content.jsx
Labels: 3: Ready to Merge

#1803 [MM-11885] Set required initial config for E2E
  tests/e2e/test.sh
Labels: 3: Ready to Merge

#1812 MM-12443 Fix multiple uploads fail issue
  components/create_post/create_post.jsx
Labels: 3: Ready to Merge

#1813 MM-12403 Fix uploads fail for last attachment
  components/create_comment/create_comment.jsx
  components/create_post/create_post.jsx
Labels: 3: Ready to Merge

#1807 translations PR 20181001
  i18n/de.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/tr.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 3: Ready to Merge

#1767 Update NOTICE.txt
  NOTICE.txt
Labels: 3: Ready to Merge

#1809 [MM-12386 && MM-12397] Fix post textbox on enter
  tests/components/create_post/create_post.test.jsx
  tests/utils/post_utils.test.jsx
  utils/post_utils.jsx
Labels: 3: Ready to Merge

#1819 Draft channel indicator to ignore message with whitespaces only
  components/sidebar/sidebar_channel/index.js
  components/suggestion/switch_channel_provider.jsx
Labels: 3: Ready to Merge

#1818 MM-12434 Fixing old search being combined with new search.
  components/search_results/search_results.jsx
Labels: 3: Ready to Merge

#1817 MM-12447: stop tracking focus for session expiry
  actions/global_actions.jsx
  components/logged_in/logged_in.jsx
  components/login/login_controller/login_controller.jsx
  components/root/root.jsx
Labels: 3: Ready to Merge

#1797 MM-12175 MM-12074 Dependency updates and upgrade to babel 7
  .babelrc
  actions/websocket_actions.jsx
  build/Dockerfile
  build/Jenkinsfile
  components/admin_console/email_settings.jsx
  components/mfa/confirm.jsx
  package-lock.json
  package.json
  root.jsx
  sass/styles.scss
  tests/components/__snapshots__/formatted_markdown_message.test.jsx.snap
  tests/components/__snapshots__/shortcuts_modal.test.jsx.snap
  tests/components/__snapshots__/toggle_modal_button_redux.test.jsx.snap
  tests/components/admin_console/request_button/__snapshots__/request_button.test.jsx.snap
  tests/components/multiselect/__snapshots__/multiselect.test.jsx.snap
  tests/components/navbar/__snapshots__/navbar_info_button.test.jsx.snap
  tests/components/post_view/__snapshots__/date_separator.test.jsx.snap
  tests/components/user_settings/__snapshots__/email_notification_setting.test.jsx.snap
  tests/components/user_settings/__snapshots__/manage_auto_responder.test.jsx.snap
  tests/plugins/__snapshots__/pluggable.test.jsx.snap
  webpack.config.js
Labels: 3: Ready to Merge

#1815 MM-12420: Avoid slash duplications on gitlab urls configuration
  components/admin_console/admin_definition.jsx
Labels: 3: Ready to Merge

#1794 MM-12219 Message toolbar sometimes not displaying on ipad
  components/post_view/post/post.jsx
Labels: 3: Ready to Merge

#1816 MM-12331: Fix listing of deleted channels on searches
  actions/views/rhs.js
  tests/redux/actions/views/rhs.test.js
Labels: 2: Dev Review

#1823 [MM-12473] Do not change setting on pressing cancel at Account Settings > Advanced
  components/user_settings/advanced/code_block_ctrl_enter_section/code_block_ctrl_enter_section.jsx
  components/user_settings/advanced/join_leave_section/join_leave_section.jsx
  tests/components/user_settings/advanced_tab/__snapshots__/code_block_ctrl_enter_section.test.jsx.snap
  tests/components/user_settings/advanced_tab/__snapshots__/join_leave_section.test.jsx.snap
  tests/components/user_settings/advanced_tab/code_block_ctrl_enter_section.test.jsx
  tests/components/user_settings/advanced_tab/join_leave_section.test.jsx
Labels: 3: Ready to Merge

#1822 MM-4712 Revert file_upload progress
  actions/file_actions.jsx
  components/create_comment/create_comment.jsx
  components/create_post/create_post.jsx
  components/file_preview.jsx
  components/file_preview/file_upload_progress.jsx
  components/file_upload/file_upload.jsx
  components/svg/checkmark_icon.jsx
  sass/components/_files.scss
  tests/components/__snapshots__/file_preview.test.jsx.snap
  tests/components/__snapshots__/file_upload_progress.test.jsx.snap
  tests/components/create_comment/__snapshots__/create_comment.test.jsx.snap
  tests/components/create_comment/create_comment.test.jsx
  tests/components/create_post/__snapshots__/create_post.test.jsx.snap
  tests/components/create_post/create_post.test.jsx
  tests/components/file_preview.test.jsx
  tests/components/file_upload/file_upload.test.jsx
  tests/components/file_upload_progress.test.jsx
  utils/utils.jsx
Labels: 3: Ready to Merge

#1828 MM-12421: Fix uploads while reply switching in the RHS
  actions/file_actions.jsx
  components/create_comment/create_comment.jsx
  components/create_comment/index.js
  components/create_post/create_post.jsx
  components/file_upload/file_upload.jsx
  tests/components/create_comment/__snapshots__/create_comment.test.jsx.snap
  tests/components/create_comment/create_comment.test.jsx
  tests/components/create_post/create_post.test.jsx
  tests/components/file_upload/file_upload.test.jsx
Labels: 3: Ready to Merge

#1826 Update redux for master
  package-lock.json
  package.json
Labels: 2: Dev Review

#1834 MM-12260: don't close edit post modal on escape if emoji picker is open
  components/edit_post_modal/edit_post_modal.jsx
  tests/components/edit_post_modal.test.jsx
Labels: 3: Ready to Merge

#1827 [MM-12454] fix formated message when have *** and improve the copy text button
  components/integrations/installed_oauth_app.jsx
  tests/components/integrations/__snapshots__/installed_oauth_app.test.jsx.snap
Labels: 3: Ready to Merge

#1841 MM-12150 - Updating x icon and plugins
  components/channel_header/channel_header.jsx
  components/navbar/navbar.jsx
  plugins/mobile_channel_header_plug/mobile_channel_header_plug.jsx
  sass/components/_dropdown.scss
  sass/layout/_navigation.scss
  sass/responsive/_mobile.scss
  tests/components/navbar/__snapshots__/navbar.test.jsx.snap
  tests/plugins/__snapshots__/mobile_channel_header_plug.test.jsx.snap
Labels: 2: Dev Review

#1821 MM-12416: Adds boolean config for 'memberOf' overlay.
  components/admin_console/admin_definition.jsx
  i18n/en.json
Labels: 1: PM Review, 2: Dev Review

#1838 MM-12499 - Updating badge icon
  components/team_sidebar/components/team_button.jsx
  sass/components/_badge.scss
  sass/components/_module.scss
  sass/layout/_sidebar-left.scss
  sass/layout/_team-sidebar.scss
  utils/utils.jsx
Labels: CherryPickCandidate

#1840 Message hook
  components/post_markdown/index.js
  components/post_markdown/post_markdown.jsx
  plugins/registry.js
  reducers/plugins/index.js
  tests/components/__snapshots__/post_markdown.test.jsx.snap
  tests/components/post_markdown.test.jsx
  tests/components/post_view/__snapshots__/post_message_view.test.jsx.snap
  tests/plugins/__snapshots__/post_type.test.jsx.snap
Labels: 3: Ready to Merge

#1836 MM-12338 - Updating line break on signup markdown
  sass/routes/_signup.scss
Labels: 3: Ready to Merge

#1842 Remove flux store usages from signup components
  components/signup/signup_controller/index.js
  components/signup/signup_controller/signup_controller.jsx
  components/signup/signup_email/index.js
  components/signup/signup_email/signup_email.jsx
Labels: 3: Ready to Merge

#1844 Remove flux store usages from mfa
  components/mfa/setup/index.js
  components/mfa/setup/setup.jsx
Labels: 3: Ready to Merge

#1837 MM-12524 - Updating badge position on desktop app
  sass/layout/_navigation.scss
  sass/layout/_sidebar-left.scss
Labels: 3: Ready to Merge

#1835 MM-12329 - Updating bullet point base styling
  sass/base/_typography.scss
  sass/components/_popover.scss
  sass/layout/_post.scss
Labels: 3: Ready to Merge, CherryPickCandidate

#1854 MM-12482: Fallback to the default channel view when the archived chan…
  components/channel_header/index.js
  components/channel_view/index.js
Labels: 2: Dev Review

#1845 MM-12523: fix announcement bar styling
  components/announcement_bar/announcement_bar.jsx
  sass/base/_structure.scss
  sass/components/_announcement-bar.scss
  sass/layout/_sidebar-left.scss
  sass/layout/_sidebar-right.scss
  sass/responsive/_mobile.scss
  sass/routes/_admin-console.scss
  sass/utils/_variables.scss
Labels: 2: Dev Review, CherryPickApproved, Setup Test Server

#1861 fix problem with mmjstool to extract i18n strings
  components/root/root.jsx
Labels: 3: Ready to Merge

#1846 Refactored to rename "service terms" to "terms of service"
  actions/user_actions.jsx
  components/admin_console/admin_definition.jsx
  components/logged_in/index.js
  components/root/index.js
  components/terms_of_service/index.js
  components/terms_of_service/terms_of_service.jsx
  i18n/en.json
  package-lock.json
  package.json
  tests/components/terms_of_service/terms_of_service.test.jsx
Labels: 3: Ready to Merge, CherryPickCandidate

#1862 translations PR 20181009
  i18n/de.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/zh-CN.json
Labels: 3: Ready to Merge

#1849 MM-12547 - Fixing videos modal
  sass/components/_modal.scss
  sass/responsive/_tablet.scss
Labels: 3: Ready to Merge, CherryPickApproved

#1860 MM-12492 Remove flux store usages from the system console
  components/admin_console/admin_navbar_dropdown/admin_navbar_dropdown.jsx
  components/admin_console/admin_navbar_dropdown/index.js
  components/admin_console/admin_sidebar/admin_sidebar.jsx
  components/admin_console/admin_sidebar_header/admin_sidebar_header.jsx
  components/admin_console/admin_sidebar_header/index.js
  components/admin_console/compliance_reports/compliance_reports.jsx
  components/admin_console/compliance_reports/index.js
  components/admin_console/reset_password_modal/index.js
  components/admin_console/reset_password_modal/reset_password_modal.jsx
  components/admin_console/system_users/index.js
  components/admin_console/system_users/list/system_users_list.jsx
  components/admin_console/system_users/system_users.jsx
  components/admin_console/system_users/system_users_dropdown/index.js
  components/admin_console/system_users/system_users_dropdown/system_users_dropdown.jsx
  tests/components/admin_console/system_users/system_users.test.jsx
Labels: 3: Ready to Merge

#1858 MM-12620/MM-12619 login issues
  actions/storage.js
  components/claim/components/email_to_ldap.jsx
  components/claim/components/email_to_oauth.jsx
  components/claim/components/ldap_to_email.jsx
  components/claim/components/oauth_to_email.jsx
  reducers/storage.js
  store/index.js
Labels: 2: Dev Review, CherryPickApproved

#1863 MM-12572 - Fixing more unreads and badge on mobile
  sass/components/_badge.scss
  sass/responsive/_mobile.scss
Labels: 2: Dev Review, CherryPickCandidate

#1832 Remove flux store usages from suggestion
  components/suggestion/at_mention_provider.jsx
  components/suggestion/channel_mention_provider.jsx
Labels: 3: Ready to Merge

#1871 Update en.json
  i18n/en.json
Labels: 2: Dev Review, Hacktoberfest

#1867 MM-12642: handle callback-style notification API
  components/login/login_controller/login_controller.jsx
  tests/utils/notifications.jsx
  utils/notifications.jsx
  utils/utils.jsx
Labels: CherryPickCandidate

#1856 [MM-12433] Fix expand/collapse of image at RHS root post
  components/rhs_root_post/index.js
  components/rhs_thread/rhs_thread.jsx
Labels: CherryPickCandidate

#1865 MM-12493 Fix channel names are bolded when you hover over them
  sass/layout/_sidebar-left.scss
Labels: 3: Ready to Merge

#1876 MM-12581 Switch UserActions.loadMe to redux
  actions/user_actions.jsx
  actions/views/root.js
  components/mfa/confirm.jsx
  components/root/index.js
  components/root/root.jsx
  components/signup/signup_controller/signup_controller.jsx
  components/signup/signup_email/signup_email.jsx
  tests/components/mfa/components/__snapshots__/confirm.test.jsx.snap
  tests/components/mfa/components/confirm.test.jsx
  tests/components/root/root.test.jsx
Labels: 2: Dev Review

#1874 MM-12656: fix racey ref access
  components/suggestion/suggestion_box.jsx
  tests/components/suggestion/suggestion_box.test.jsx
Labels: 3: Ready to Merge, CherryPickCandidate

#1869 MM-12654 - Updating padding for navbar dropdown
  sass/responsive/_mobile.scss
Labels: 3: Ready to Merge, CherryPickApproved

#1877 [MM-12639] Not allow edit for pending post
  actions/post_actions.jsx
  tests/redux/actions/posts.test.js
Labels: 2: Dev Review, CherryPickApproved

#1878 MM-12513: fix copy link on desktop
  components/copy_url_context_menu/copy_url_context_menu.jsx
  components/copy_url_context_menu/index.js
  tests/components/__snapshots__/copy_url_context_menu.test.jsx.snap
  tests/components/copy_url_context_menu.test.jsx
  utils/utils.jsx
Labels: 2: Dev Review, CherryPickApproved

#1881 MM-12659: unify LoggedIn redirect handling to avoid races
  components/logged_in/logged_in.jsx
  tests/components/logged_in/logged_in.test.jsx
Labels: CherryPickApproved

#1853 MM-11880 Have Team Settings modal use the patch endpoint instead of the update endpoint
  .gitignore
  components/team_general_tab/index.js
  components/team_general_tab/team_general_tab.jsx
  tests/components/team_general_tab.test.jsx
Labels: 3: Ready to Merge, Hacktoberfest

#1850 MM-9820 Adding aria labels for providing accessibility
  components/create_comment/create_comment.jsx
  components/create_post/create_post.jsx
  components/emoji_picker/emoji_picker.jsx
  components/file_upload/file_upload.jsx
  i18n/en.json
  tests/components/create_comment/__snapshots__/create_comment.test.jsx.snap
  tests/components/create_post/__snapshots__/create_post.test.jsx.snap
  tests/components/file_upload/__snapshots__/file_upload.test.jsx.snap
  tests/components/file_upload/file_upload.test.jsx
Labels: 3: Ready to Merge, Hacktoberfest

#1892 MM-12685 Do not restore focus to previous components when closing channel switcher
  components/quick_switch_modal/quick_switch_modal.jsx
  tests/components/__snapshots__/quick_switch_modal.test.jsx.snap
Labels: CherryPickApproved, QA Review, Setup Test Server

#1893 MM-12680: fix switching email to oauth
  components/claim/components/email_to_oauth.jsx
  components/login/login_controller/login_controller.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#1848 MM-12319 - Updating x icon css in search bar
  components/search_bar/search_bar.jsx
  i18n/en.json
  sass/components/_search.scss
Labels: 3: Ready to Merge

#1901 revert react-select dependency update
  package-lock.json
  package.json
  sass/styles.scss
  tests/components/multiselect/__snapshots__/multiselect.test.jsx.snap
Labels: 3: Ready to Merge

#1882 MM-12494 Removing some flux store usage.
  actions/channel_actions.jsx
  actions/views/channel.js
  components/channel_header/channel_header.jsx
  components/channel_header/index.js
  components/channel_invite_modal/channel_invite_modal.jsx
  components/channel_invite_modal/index.js
  components/channel_layout/channel_controller.jsx
  components/channel_layout/channel_identifier_router/channel_identifier_router.jsx
  components/channel_layout/channel_identifier_router/index.js
  components/channel_members_dropdown/channel_members_dropdown.jsx
  components/channel_members_dropdown/index.js
  components/channel_select/channel_select.jsx
  components/channel_select/index.js
  components/channel_view/channel_view.jsx
  components/channel_view/index.js
  components/confirm_modal.jsx
  components/integrations/abstract_incoming_webhook.jsx
  components/integrations/abstract_outgoing_webhook.jsx
  components/leave_private_channel_modal/index.js
  components/leave_private_channel_modal/leave_private_channel_modal.jsx
  components/navbar/index.js
  components/navbar/navbar.jsx
  components/new_channel_flow/index.js
  components/new_channel_flow/new_channel_flow.jsx
  components/notify_counts.jsx
  components/notify_counts/index.js
  components/notify_counts/notify_counts.jsx
  components/post_view/channel_intro_message/channel_intro_message.jsx
  components/post_view/channel_intro_message/index.js
  components/removed_from_channel_modal/index.js
  components/removed_from_channel_modal/removed_from_channel_modal.jsx
  components/sidebar/sidebar.jsx
  components/suggestion/channel_mention_provider.jsx
  components/suggestion/search_channel_provider.jsx
  components/suggestion/switch_channel_provider.jsx
  stores/channel_store.jsx
  tests/components/__snapshots__/channel_header.test.jsx.snap
  tests/components/channel_header.test.jsx
  tests/components/integrations/__snapshots__/abstract_incoming_hook.test.jsx.snap
  tests/components/integrations/__snapshots__/abstract_outgoing_webhook.test.jsx.snap
  tests/components/navbar/__snapshots__/navbar.test.jsx.snap
  tests/components/navbar/navbar.test.jsx
  tests/components/new_channel_flow.test.jsx
  tests/components/sidebar/__snapshots__/sidebar.test.jsx.snap
  tests/utils/channel_utils.test.jsx
  utils/channel_utils.jsx
Labels: Setup Test Server, Tests: Done

#1897 MM-12495 Removing some flux store usage.
  components/rhs_header_post/rhs_header_post.jsx
  components/rhs_thread/rhs_thread.jsx
  components/sidebar/header/dropdown/index.js
  components/sidebar/header/dropdown/sidebar_header_dropdown.jsx
  components/sidebar/header/index.js
  components/sidebar/header/sidebar_header.jsx
  components/sidebar_right/sidebar_right.jsx
  components/sidebar_right_menu/index.js
  components/sidebar_right_menu/sidebar_right_menu.jsx
  components/team_sidebar/components/team_button.jsx
  components/team_sidebar/index.js
  components/team_sidebar/team_sidebar_controller.jsx
  sass/layout/_team-sidebar.scss
  tests/plugins/__snapshots__/main_menu_action.test.jsx.snap
  tests/plugins/main_menu_action.test.jsx
Labels: 2: Dev Review, Setup Test Server, Tests: Done

#1904 MM-12640 Hacky fix for zen-observable getting optimized out by babel
  package-lock.json
  package.json
  store/index.js
Labels: 3: Ready to Merge

#1889 MM-12539: Fix formatting user setting help text.
  components/user_settings/advanced/user_settings_advanced.jsx
  i18n/en.json
Labels: CherryPickApproved

#1880 MM-12496 Remove flux store usages in team* components
  components/admin_console/system_users/system_users_dropdown/index.js
  components/team_members_dropdown/index.js
  components/team_members_dropdown/team_members_dropdown.jsx
  components/team_settings.jsx
  components/team_settings/index.js
  components/team_settings/team_settings.jsx
  components/team_settings_modal.jsx
  components/team_sidebar/index.js
  components/team_sidebar/team_sidebar_controller.jsx
  package-lock.json
  package.json
Labels: 3: Ready to Merge, Tests: Done

#1808 [MM-11675] Username popover on all system messages
  components/post_markdown/system_message_helpers.jsx
  tests/components/__snapshots__/post_markdown.test.jsx.snap
Labels: Hacktoberfest

#1873 Modify the ESLint config to allow .js ext for React component file
  .eslintrc.json
Labels: Hacktoberfest

#1903 MM-12541 Fixing LDAP button to have correct LDAP field name.
  components/signup/signup_controller/index.js
  components/signup/signup_controller/signup_controller.jsx
Labels: 3: Ready to Merge

#1888 [MM-12582 & MM-12745] Migrate PostActions.handleNewPost to redux actions
  actions/global_actions.jsx
  actions/post_actions.jsx
  actions/post_utils.js
  actions/websocket_actions.jsx
  stores/channel_store.jsx
  tests/redux/actions/post_actions.test.js
  tests/redux/actions/post_utils.test.js
  utils/constants.jsx
Labels: 3: Ready to Merge, Tests: Done

#1898 Migrate ChannelActions joinChannel and leaveChannel to redux
  actions/channel_actions.jsx
  actions/global_actions.jsx
  actions/views/channel.js
  components/channel_layout/channel_identifier_router/channel_identifier_router.jsx
  components/leave_private_channel_modal/index.js
  components/leave_private_channel_modal/leave_private_channel_modal.jsx
  components/more_channels/index.js
  components/more_channels/more_channels.jsx
  components/navbar/index.js
  components/navbar/navbar.jsx
  tests/components/__snapshots__/leave_private_channel_modal.test.jsx.snap
  tests/components/__snapshots__/more_channels.test.jsx.snap
  tests/components/leave_private_channel_modal.test.jsx
  tests/components/more_channels.test.jsx
  tests/components/navbar/navbar.test.jsx
Labels: 3: Ready to Merge

#1896 MM-12740 Move translations into redux store and remove LocalizationStore
  actions/global_actions.jsx
  actions/user_actions.jsx
  actions/views/root.js
  components/admin_console/admin_navbar_dropdown/admin_navbar_dropdown.jsx
  components/admin_console/admin_navbar_dropdown/index.js
  components/admin_console/manage_teams_modal/index.jsx
  components/admin_console/manage_teams_modal/manage_teams_modal.jsx
  components/admin_console/system_users/list/system_users_list.jsx
  components/announcement_bar/announcement_bar.jsx
  components/announcement_bar/index.js
  components/file_upload/file_upload.jsx
  components/file_upload/index.js
  components/intl_provider/index.jsx
  components/intl_provider/intl_provider.jsx
  components/login/login_controller/login_controller.jsx
  components/root/root.jsx
  components/suggestion/switch_team_provider.jsx
  components/team_sidebar/index.js
  components/team_sidebar/team_sidebar_controller.jsx
  components/user_settings/display/manage_languages.jsx
  i18n/en.json
  package.json
  reducers/views/i18n.js
  reducers/views/index.js
  selectors/i18n.js
  stores/localization_store.jsx
  tests/components/__snapshots__/intl_provider.test.jsx.snap
  tests/components/admin_console/system_users/__snapshots__/system_users_list.test.jsx.snap
  tests/components/announcement_bar.test.jsx
  tests/components/file_upload/file_upload.test.jsx
  tests/components/intl_provider.test.jsx
  tests/i18n_mock.json
  tests/redux/selectors/i18n.test.js
  tests/utils/team_utils.test.jsx
  tests/utils/utils.test.jsx
  utils/constants.jsx
  utils/license_utils.jsx
  utils/team_utils.jsx
  utils/utils.jsx
Labels: 3: Ready to Merge

#1879 Migrate ChannelActions.goToChannelById and goToChannel to redux
  actions/channel_actions.jsx
  actions/views/channel.js
  components/quick_switch_modal/index.js
  components/quick_switch_modal/quick_switch_modal.jsx
  components/sidebar/index.js
  components/sidebar/sidebar.jsx
  package-lock.json
  tests/components/quick_switch_modal.test.jsx
  tests/components/sidebar/sidebar.test.jsx
Labels: 3: Ready to Merge

#1909 Remove unused legacy setChannelAsRead action
  actions/channel_actions.jsx
Labels: 3: Ready to Merge

#1906 Fix Jest warning of "Cannot read property '_location' of null"
  tests/setup.js
Labels: 2: Dev Review

#1908 Migrate create/delete/patch channel to redux
  actions/channel_actions.jsx
  components/new_channel_flow/index.js
  components/new_channel_flow/new_channel_flow.jsx
  components/rename_channel_modal/index.js
  components/rename_channel_modal/rename_channel_modal.jsx
  components/sidebar/sidebar.jsx
  tests/components/__snapshots__/new_channel_flow.test.jsx.snap
  tests/components/new_channel_flow.test.jsx
  tests/components/rename_channel_modal.test.jsx
Labels: 3: Ready to Merge

#1914 Fixes team id property access.
  components/channel_header/channel_header.jsx
  tests/components/__snapshots__/channel_header.test.jsx.snap
Labels: 2: Dev Review

#1912 MM-12647 Update react-select
  components/add_users_to_team/add_users_to_team.jsx
  components/channel_invite_modal/channel_invite_modal.jsx
  components/more_direct_channels/more_direct_channels.jsx
  components/multiselect/multiselect.jsx
  components/team_selector_modal/team_selector_modal.jsx
  package-lock.json
  package.json
  sass/components/_multi-select.scss
  sass/styles.scss
  tests/components/add_users_to_team.test.jsx
  tests/components/more_direct_channels.test.jsx
  tests/components/multiselect/__snapshots__/multiselect.test.jsx.snap
Labels: QA Review, Tests: Done

#1915 MM-12497 Remove flux store usages from user settings
  actions/channel_actions.jsx
  actions/command.js
  actions/global_actions.jsx
  actions/views/create_comment.jsx
  components/channel_layout/channel_controller.jsx
  components/create_post/create_post.jsx
  components/create_post/index.js
  components/profile_popover/index.js
  components/profile_popover/profile_popover.jsx
  components/sidebar/header/dropdown/index.js
  components/sidebar/header/dropdown/sidebar_header_dropdown.jsx
  components/sidebar_right_menu/sidebar_right_menu.jsx
  components/user_settings/advanced/index.js
  components/user_settings/advanced/user_settings_advanced.jsx
  components/user_settings/display/index.js
  components/user_settings/display/user_settings_display.jsx
  components/user_settings/display/user_settings_theme/color_chooser.jsx
  components/user_settings/display/user_settings_theme/custom_theme_chooser.jsx
  components/user_settings/display/user_settings_theme/index.js
  components/user_settings/display/user_settings_theme/premade_theme_chooser/index.js
  components/user_settings/display/user_settings_theme/premade_theme_chooser/premade_theme_chooser.jsx
  components/user_settings/display/user_settings_theme/user_settings_theme.jsx
  components/user_settings/general/user_settings_general.jsx
  components/user_settings/index.js
  components/user_settings/modal/index.js
  components/user_settings/modal/user_settings_modal.jsx
  components/user_settings/notifications/user_settings_notifications.jsx
  components/user_settings/security/index.js
  components/user_settings/security/user_settings_security.jsx
  components/user_settings/sidebar/user_settings_sidebar.jsx
  components/user_settings/user_settings.jsx
  plugins/export.js
  plugins/index.js
  stores/modal_store.jsx
  tests/components/create_post/create_post.test.jsx
  tests/components/dot_menu/dot_menu_empty.test.jsx
  tests/components/dot_menu/dot_menu_mobile.test.jsx
  tests/components/search_results_item.test.jsx
  tests/components/user_settings/__snapshots__/user_settings_display.test.jsx.snap
  tests/components/user_settings/color_chooser.test.jsx
  tests/plugins/__snapshots__/main_menu_action.test.jsx.snap
  tests/plugins/__snapshots__/pluggable.test.jsx.snap
  tests/plugins/main_menu_action.test.jsx
  tests/redux/actions/views/create_comment.test.jsx
  utils/constants.jsx
Labels: 3: Ready to Merge, Tests: Done

#1922 [MM-12449] Fix babel requirement for e2e and move/use constants to/from globals
  nightwatch.conf.js
  tests/e2e/globals.js
  tests/e2e/pages/accountSettingsModalPage.js
  tests/e2e/pages/centerPage.js
  tests/e2e/pages/channelHeaderPage.js
  tests/e2e/pages/loginPage.js
  tests/e2e/pages/logoutPage.js
  tests/e2e/pages/sidebarLeftPage.js
  tests/e2e/pages/tutorialPage.js
  tests/e2e/tests/1_login_logout/login.element.js
  tests/e2e/tests/1_login_logout/logout.element.js
  tests/e2e/tests/1_login_logout/tutorial.element.js
  tests/e2e/tests/2_center/centerPage.element.js
  tests/e2e/tests/2_center/channelHeader.element.js
  tests/e2e/tests/3_sidebarLeft/accountSettingsDisplay.action.js
  tests/e2e/tests/3_sidebarLeft/accountSettingsGeneral.action.js
  tests/e2e/tests/3_sidebarLeft/accountSettingsModalPage.element.js
  tests/e2e/tests/3_sidebarLeft/accountSettingsNotification.action.js
  tests/e2e/tests/3_sidebarLeft/sidebarLeftPage.element.js
  tests/e2e/utils.js
Labels: 3: Ready to Merge

#1926 Remove flux store usages from global_actions.jsx
  actions/global_actions.jsx
  tests/redux/actions/global_actions.test.js
Labels: 3: Ready to Merge

#1929 Remove flux store usages from integration actions
  actions/integration_actions.jsx
Labels: 3: Ready to Merge

#1875 [MM-12582 & MM-12744] Update flagPost and unflagPost from PostActions and refactor PostFlagIcon component
  actions/post_actions.jsx
  components/dot_menu/index.js
  components/post_view/post_flag_icon/index.js
  components/post_view/post_flag_icon/post_flag_icon.js
  components/post_view/post_info/post_info.jsx
  components/rhs_comment/rhs_comment.jsx
  components/rhs_root_post/rhs_root_post.jsx
  components/search_results_item/search_results_item.jsx
  tests/components/__snapshots__/search_results_item.test.jsx.snap
  tests/components/post_view/__snapshots__/post_flag_icon.test.js.snap
  tests/components/post_view/post_flag_icon.test.js
  tests/components/post_view/post_info/__snapshots__/post_info.test.jsx.snap
Labels: 2: Dev Review, Tests: Done

#1928 Remove flux store usages from post_actions.jsx
  actions/post_actions.jsx
Labels: 2: Dev Review

#1927 Remove flux store usages from team_actions.jsx
  actions/team_actions.jsx
Labels: 2: Dev Review

#1917 MM-12662 Remove flux store usages from ChannelIdentifierRouter
  components/channel_layout/channel_identifier_router/actions.js
  components/channel_layout/channel_identifier_router/channel_identifier_router.jsx
  components/channel_layout/channel_identifier_router/index.js
Labels: 3: Ready to Merge, Tests: Done

#1933 Fix for circular dependency in imports.
  components/at_mention/at_mention.jsx
  components/emoji_picker/emoji_picker_overlay.jsx
  tests/utils/position_utils.test.jsx
  tests/utils/utils.test.jsx
  utils/position_utils.jsx
  utils/utils.jsx
Labels: 2: Dev Review, CherryPickApproved

#1936 Export plugin libs
  components/root/root.jsx
Labels: 3: Ready to Merge

#1924 [MM-12449] Use separate database and default config.json when running end-to-end testing
  Makefile
  tests/e2e/test.sh
Labels: 2: Dev Review

#1923 Remove config setting check for create team button in sidebar
  components/team_sidebar/index.js
  components/team_sidebar/team_sidebar_controller.jsx
Labels: 3: Ready to Merge

#1937 MM-12792 Fix switching to a channel on a different team with the same name
  components/channel_layout/channel_identifier_router/actions.js
  package-lock.json
  package.json
  tests/components/channel_identifier_router/actions.test.js
Labels: 3: Ready to Merge

#1938 MM-12804 Fix slash commands
  actions/integration_actions.jsx
Labels: 2: Dev Review

#1940 MM-12791 Fix switching to DM/GMs from notifications and other places
  components/channel_layout/channel_identifier_router/actions.js
  tests/components/channel_identifier_router/actions.test.js
  utils/utils.jsx
Labels: 3: Ready to Merge

#1944 MM-12682 FIx for expand/collapse not working after an image is posted
  components/file_attachment_list/file_attachment_list.jsx
  components/single_image_view/single_image_view.jsx
  tests/components/__snapshots__/file_attachment_list.test.jsx.snap
  tests/components/single_image_view.test.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#1945 MM-12810 Webapp redirecting to select_team page when base url is hit
  components/root/root.jsx
  tests/components/root/root.test.jsx
Labels: 3: Ready to Merge

#1950 MM-12810 Fix infinite logout loop
  actions/views/root.js
  components/root/root.jsx
  tests/components/root/root.test.jsx
Labels: 3: Ready to Merge

#1960 Update mattermost-redux to latest
  package-lock.json
  package.json
Labels: 2: Dev Review

#1951 Remove last flux store usage from actions
  actions/diagnostics_actions.jsx
  actions/status_actions.jsx
  actions/user_actions.jsx
  actions/websocket_actions.jsx
  components/add_users_to_team/add_users_to_team.jsx
  components/add_users_to_team/index.js
  components/member_list_channel/index.js
  components/member_list_channel/member_list_channel.jsx
  components/member_list_team/index.js
  components/member_list_team/member_list_team.jsx
  components/more_direct_channels/index.js
  components/more_direct_channels/more_direct_channels.jsx
  components/needs_team/index.js
  components/needs_team/needs_team.jsx
  package-lock.json
  package.json
  tests/components/add_users_to_team.test.jsx
  tests/components/more_direct_channels.test.jsx
  tests/components/needs_team.test.jsx
  tests/redux/actions/status_actions.test.js
  tests/setup.js
Labels: 3: Ready to Merge, Tests: Done

#1887 MM-12579 Migration of team_actions to be pure redux
  actions/team_actions.jsx
  components/admin_console/manage_teams_modal/index.jsx
  components/admin_console/manage_teams_modal/manage_teams_modal.jsx
  components/admin_console/system_users/list/index.js
  components/admin_console/system_users/list/system_users_list.jsx
  tests/components/admin_console/manage_teams_modal/__snapshots__/manage_teams_modal.test.jsx.snap
  tests/components/admin_console/manage_teams_modal/manage_teams_modal.test.jsx
  tests/components/admin_console/system_users/__snapshots__/system_users_list.test.jsx.snap
  tests/components/admin_console/system_users/system_users_list.test.jsx
Labels: 3: Ready to Merge

#1965 MM-12807 Fix clicking on multiselect items
  components/multiselect/multiselect.jsx
  tests/components/multiselect/__snapshots__/multiselect.test.jsx.snap
Labels: 2: Dev Review

#1955 MM-12585 Complete migration of file_actions to redux actions
  actions/file_actions.jsx
  components/file_upload/file_upload.jsx
  components/file_upload/index.js
  tests/components/file_upload/file_upload.test.jsx
Labels: 3: Ready to Merge

#1963 MM-12810 Fix for redirection if path is not root
  components/root/root.jsx
  tests/components/root/root.test.jsx
Labels: 3: Ready to Merge

#1839 MM7676 - Migrated removed_from_channel_modal to be pure and use Redux
  actions/websocket_actions.jsx
  components/channel_layout/channel_controller.jsx
  components/removed_from_channel_modal/index.js
  components/removed_from_channel_modal/removed_from_channel_modal.jsx
  tests/components/removed_from_channel_modal/__snapshots__/removed_from_channel_modal.test.jsx.snap
  tests/components/removed_from_channel_modal/removed_from_channel_modal.test.jsx
  utils/constants.jsx
Labels: 3: Ready to Merge, Hacktoberfest

#1958 [MM-12714] Migrate increasePostVisibility into redux-style action
  actions/post_actions.jsx
  tests/redux/actions/post_actions.test.js
Labels: QA Review

#1925 Remove flux store usages from channel_actions.jsx
  actions/channel_actions.jsx
Labels: 3: Ready to Merge

#1949 [MM-12625] Change @undefined to "Someone" in combined system messages
  components/post_view/combined_system_message/combined_system_message.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#1970 MM-12815: Stop using permissions-deprecated config settings in web app
  actions/post_actions.jsx
  components/integrations/index.js
  components/integrations/installed_oauth_apps/index.js
  components/integrations/installed_oauth_apps/installed_oauth_apps.jsx
  components/integrations/integrations.jsx
  components/select_team/index.js
  components/select_team/select_team.jsx
  components/sidebar/header/dropdown/index.js
  components/sidebar_right_menu/index.js
  components/tutorial/index.jsx
  tests/components/edit_post_modal.test.jsx
  tests/components/integrations/installed_oauth_apps.test.jsx
  tests/components/select_team/select_team.test.jsx
  tests/plugins/main_menu_action.test.jsx
  tests/redux/actions/post_actions.test.js
Labels: 3: Ready to Merge

#1977 MM-12820 Fixing users not searchable when adding user to a channel.
  components/channel_invite_modal/channel_invite_modal.jsx
Labels: 3: Ready to Merge

#1967 translations PR 20181029
  i18n/de.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/tr.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 3: Ready to Merge

#1948 Remove flux store usages from websocket_actions.jsx
  actions/global_actions.jsx
  actions/websocket_actions.jsx
  components/channel_info_modal/channel_info_modal.jsx
  components/removed_from_channel_modal/index.js
  components/removed_from_channel_modal/removed_from_channel_modal.jsx
  tests/components/removed_from_channel_modal/__snapshots__/removed_from_channel_modal.test.jsx.snap
  tests/components/removed_from_channel_modal/removed_from_channel_modal.test.jsx
Labels: Tests: Done
