Repository mattermost/mattermost-webapp, pull requests merged in 2018-12, with the labels that each got.

#2108 MM-13209: use textbox channel from context
  actions/views/channel.js
  components/__snapshots__/textbox.test.jsx.snap
  components/textbox/index.js
  components/textbox/textbox.jsx
  package-lock.json
  package.json
Labels: 3: Ready to Merge, CherryPickApproved

#2123 MM-12760: Proper fix for this and also the divider for date input.
  components/suggestion/provider.jsx
  components/suggestion/search_date_provider.jsx
  components/suggestion/search_user_provider.jsx
  components/suggestion/suggestion_box.jsx
Labels: 2: Dev Review, CherryPickApproved

#2126 Always generate full source map.
  Makefile
  package.json
  webpack.config.js
Labels: 3: Ready to Merge

#2122 MM-12948 - Adding dividers for mobile channel menu
  components/channel_header_dropdown/mobile_channel_header_dropdown.js
  sass/responsive/_mobile.scss
Labels: 3: Ready to Merge

#2117 Adding i18n-extract task to the Makefile
  Makefile
Labels: 3: Ready to Merge

#2127 MM-13266: Doing the filter of GMs properly on "more direct channels" modal
  components/more_direct_channels/index.js
Labels: 3: Ready to Merge, CherryPickApproved

#2129 MM-13255 Use correct leave channel action
  components/channel_header_dropdown/menu_items/leave_channel/index.js
  components/sidebar/sidebar_channel/index.js
Labels: 2: Dev Review, CherryPickApproved

#2119 [MM-12897] Fix redirect to default team and channel on team invite link
  components/signup/signup_controller/signup_controller.jsx
  components/signup/signup_email/signup_email.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2125 MM-13258 Fix Show More not being clickable in message attachments
  sass/layout/_post.scss
Labels: 3: Ready to Merge, CherryPickApproved

#2124 Give precedence to metadata on attachments count
  components/file_attachment_list/index.js
Labels: 3: Ready to Merge

#2128 MM-13234 Only update scroll position in multiselect if selection changes
  components/multiselect/multiselect_list.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2120 Fix MultiSelect compatability with react-select v2.0.0
  components/admin_console/multiselect_settings.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2118 NOTICE.txt updates for December 2018
  NOTICE.txt
Labels: 3: Ready to Merge, CherryPickApproved

#2134 Update dependencies
  components/admin_console/admin_definition.test.jsx
  components/copy_url_context_menu/__snapshots__/copy_url_context_menu.test.jsx.snap
  package-lock.json
  package.json
Labels: 3: Ready to Merge

#2139 MM-13321: Fix providers that don't extend Provider.
  components/__snapshots__/textbox.test.jsx.snap
  components/suggestion/command_provider.jsx
  components/suggestion/emoticon_provider.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2121 Adds ability to configure group display name and unique id LDAP attri…
  components/admin_console/admin_definition.jsx
  i18n/en.json
Labels: 3: Ready to Merge

#2142 MM-13178: ignore enter key within 500ms of switching channels
  components/create_post/create_post.jsx
  utils/post_utils.jsx
  utils/post_utils.test.jsx
Labels: 2: Dev Review, CherryPickApproved

#2146 MM-13257 Delete cookie properly on logout
  actions/global_actions.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2136 MM-13102 - Updating x icon on search
  sass/responsive/_mobile.scss
Labels: 3: Ready to Merge, CherryPickApproved

#2143 [MM-13174] Fix text rendering of non-existent emoji when post metadata is enabled
  components/post_emoji/index.jsx
Labels: 2: Dev Review, CherryPickApproved

#2132 MM-13199 Minor performance tweaks
  components/confirm_modal.jsx
  components/create_comment/index.js
  components/create_post/index.js
  webpack.config.js
Labels: 3: Ready to Merge

#2140 Remove participant is typing as soon as the post arrives
  actions/post_actions.test.js
  actions/post_utils.js
  actions/post_utils.test.js
  actions/websocket_actions.jsx
Labels: CherryPickApproved

#2133 [MM-13249] Fix jumping down of channel with mention in Unread section
  components/sidebar/sidebar.jsx
  components/sidebar/sidebar.test.jsx
  utils/constants.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2148 MM-13346 Fix update team WS event handler
  actions/websocket_actions.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2154 MM-13353 Fix pin posts not updating in RHS
  actions/post_actions.jsx
  actions/post_actions.test.js
Labels: 3: Ready to Merge, CherryPickApproved

#2151 MM-13345 Fix to show access denied screen for restricted teams with invite link
  components/signup/signup_controller/__snapshots__/signup_controller.test.jsx.snap
  components/signup/signup_controller/signup_controller.jsx
  components/signup/signup_controller/signup_controller.test.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2144 MM-13240 - Updating modal css for sys console
  sass/components/_modal.scss
Labels: 3: Ready to Merge, CherryPickApproved

#2162 MM-13377 Fix applying theme to all teams
  actions/user_actions.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2164 [MM-13398] Update redux commit to fix sorting of channels at sidebar unreads section
  package-lock.json
  package.json
Labels: 3: Ready to Merge, CherryPickApproved

#2153 MM-13329 - Updating android landing page
  sass/routes/_get-app.scss
Labels: CherryPickApproved

#2156 [MM-13299] Remove usage of localizeMessage from the DotMenu component
  components/dot_menu/dot_menu.jsx
  components/dot_menu/dot_menu.test.jsx
  components/dot_menu/dot_menu_empty.test.jsx
  components/dot_menu/dot_menu_mobile.test.jsx
  components/post_view/post_info/__snapshots__/post_info.test.jsx.snap
  components/search_results_item/__snapshots__/search_results_item.test.jsx.snap
Labels: 2: Dev Review

#2155 MM-13085: update prefix if context changes
  components/suggestion/suggestion_box.jsx
  components/suggestion/suggestion_box.test.jsx
  components/textbox/textbox.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2152 MM-13359 - Updating dividers for dropdown menu
  sass/components/_dropdown.scss
Labels: 3: Ready to Merge, CherryPickApproved

#2141 [GH-9961] Fix boolean setting not updating properly for plugins
  components/admin_console/custom_plugin_settings/custom_plugin_settings.jsx
Labels: 3: Ready to Merge

#2159 MM-13399 more unreads above/below fix for LHS
  components/sidebar/sidebar.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2157 MM-13410 - Updating styles for new channel modal
  components/new_channel_modal/__snapshots__/new_channel_modal.test.jsx.snap
  components/new_channel_modal/new_channel_modal.jsx
  sass/components/_modal.scss
  sass/layout/_forms.scss
Labels: 3: Ready to Merge, CherryPickApproved

#2163 MM-13387 Collapse and expand slash commands not working
  actions/global_actions.jsx
  actions/websocket_actions.jsx
  stores/preference_store.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2138 MM-12934: Extra time to click handling for channel header icons
  components/search_bar/search_bar.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2177 MM-13406 - Updating offline icon css
  utils/utils.jsx
Labels: 2: Dev Review, CherryPickApproved

#2172 MM-13422: Fix manage teams modal usage in system console.
  components/admin_console/manage_teams_modal/manage_teams_modal.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2175 MM-13425: Fix set header option in DM/GM dropdown.
  components/channel_header_dropdown/menu_items/set_channel_header.js
  components/channel_header_dropdown/menu_items/set_channel_header.test.js
Labels: CherryPickApproved

#2170 translations PR 20181210
  i18n/de.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 3: Ready to Merge

#2171 [E2E] Add IDs to multiselect for Se tests
  components/multiselect/__snapshots__/multiselect.test.jsx.snap
  components/multiselect/multiselect.jsx
Labels: 2: Dev Review, CherryPickApproved

#2180 MM-13423 Temporary fix for IE11 where trimRight is not being polyfilled
  components/create_post/create_post.jsx
Labels: 2: Dev Review, CherryPickApproved

#2179 MM-13327 Revert SiteURL message bar color to blue
  components/announcement_bar/configuration_bar.jsx
Labels: 2: Dev Review, CherryPickApproved

#2174 MM-13085: fix React warning passing unexpected prop to DOM
  components/suggestion/suggestion_box.jsx
Labels: 2: Dev Review

#2158 MM-13144 Fix email verification redirect on login
  components/login/login_controller/login_controller.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2182 [MM-13224] Fix showing of browser title as * or mention count for all teams (and not the current team only)
  components/sidebar/index.js
  components/sidebar/sidebar.jsx
Labels: 3: Ready to Merge

#2183 MM-13430 Fix /purpose from the post textbox
  components/create_post/create_post.jsx
  components/create_post/create_post.test.jsx
Labels: 2: Dev Review, CherryPickApproved

#2150 MM-12976: Moving MFA to Team edition
  components/admin_console/admin_definition.jsx
  components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.jsx.snap
  components/admin_console/admin_sidebar/admin_sidebar.jsx
  components/admin_console/system_users/index.js
  components/mfa/mfa_controller/mfa_controller.jsx
  components/user_settings/security/mfa_section/index.js
Labels: 2: Dev Review

#2187 MM-13271 Fix for Leave team making 403 calls
  actions/team_actions.jsx
  components/admin_console/manage_teams_modal/index.jsx
  components/leave_team_modal/index.js
  components/leave_team_modal/leave_team_modal.jsx
  components/leave_team_modal/leave_team_modal.test.jsx
  components/team_members_dropdown/index.js
  components/team_members_dropdown/team_members_dropdown.jsx
  tests/redux/actions/team_actions.test.js
Labels: 2: Dev Review

#2189 [MM-13216] Add E2E for CTRL/CMD+K functionality
  components/quick_switch_modal/__snapshots__/quick_switch_modal.test.jsx.snap
  components/quick_switch_modal/quick_switch_modal.jsx
  components/suggestion/suggestion_list.jsx
  cypress/integration/account_settings/sidebar/channel_switcher_spec.js
  cypress/support/commands.js
Labels: 3: Ready to Merge

#2185 Allow custom theme to only change the code theme
  components/user_settings/display/user_settings_theme/__snapshots__/custom_theme_chooser.test.jsx.snap
  components/user_settings/display/user_settings_theme/custom_theme_chooser.jsx
  components/user_settings/display/user_settings_theme/custom_theme_chooser.test.jsx
Labels: 2: Dev Review, CherryPickApproved

#2186 MM-13393 Fix announcement banner overlapping
  components/announcement_bar/announcement_bar.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2161 MM-13384 Fix clicking username in profile popover
  components/__snapshots__/textbox.test.jsx.snap
  components/add_user_to_channel_modal/__snapshots__/add_user_to_channel_modal.test.jsx.snap
  components/create_comment/__snapshots__/create_comment.test.jsx.snap
  components/create_comment/create_comment.jsx
  components/create_post/__snapshots__/create_post.test.jsx.snap
  components/create_post/create_post.jsx
  components/profile_popover/profile_popover.jsx
  components/quick_switch_modal/__snapshots__/quick_switch_modal.test.jsx.snap
  components/suggestion/suggestion_box.jsx
  components/textbox/textbox.jsx
  components/widgets/settings/autocomplete_selector.test.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2188 MM-13446 Properly clear MMUSERID cookie when EnableCookiesForSubdomains is enabled
  actions/global_actions.jsx
  actions/views/root.js
  store/index.js
Labels: 3: Ready to Merge, CherryPickApproved

#2167 MM-13212 Fix redirect to error page when sysadmin clicks DM/GM permalink
  actions/global_actions.jsx
  components/permalink_view/actions.js
  components/permalink_view/index.js
  components/permalink_view/permalink_view.jsx
  components/permalink_view/permalink_view.test.jsx
Labels: 2: Dev Review

#2173 [MM-13397] Clean up UnhandledPromiseRejectionWarning when running unit tests
  components/admin_console/custom_terms_of_service_settings/custom_terms_of_service_settings.test.jsx
  components/do_verify_email/do_verify_email.test.jsx
  components/emoji/add_emoji/add_emoji.test.js
  components/permalink_view/permalink_view.test.jsx
  components/select_team/select_team.jsx
  components/select_team/select_team.test.jsx
  components/suggestion/search_channel_with_permissions_provider.jsx
  components/suggestion/search_channel_with_permissions_provider.test.jsx
  components/terms_of_service/terms_of_service.jsx
  components/terms_of_service/terms_of_service.test.jsx
  utils/notifications.test.jsx
Labels: 3: Ready to Merge

#2191 MM-13476 Fix for channel types are not being translated in LHS
  components/sidebar/channel_name.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2193 translations PR 20181213
  i18n/de.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 3: Ready to Merge

#2190 MM-13481 Fix rejoining channel from links in posts
  components/channel_layout/channel_identifier_router/actions.js
  components/channel_layout/channel_identifier_router/actions.test.js
Labels: 3: Ready to Merge, CherryPickApproved

#2103 MM-13198 Add placeholder when loading images
  components/__snapshots__/markdown_image.test.jsx.snap
  components/markdown/markdown.jsx
  components/markdown_image.jsx
  components/markdown_image.test.jsx
  components/post_markdown/post_markdown.jsx
  components/post_view/message_attachments/message_attachment/__snapshots__/message_attachment.test.jsx.snap
  components/post_view/message_attachments/message_attachment/message_attachment.jsx
  components/size_aware_image.jsx
  components/size_aware_image.test.jsx
  sass/layout/_webhooks.scss
  utils/image_utils.jsx
  utils/message_html_to_component.jsx
Labels: 3: Ready to Merge

#2192 MM-13468 - Updating x icon for proifle pictures
  sass/routes/_settings.scss
  utils/utils.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2178 MM-13348: Fix TOS reappears on next page refresh
  actions/views/root.js
Labels: 3: Ready to Merge

#2195 MM-13490 Fix routing to DMs by email
  components/channel_layout/channel_identifier_router/actions.js
  components/channel_layout/channel_identifier_router/actions.test.js
Labels: 3: Ready to Merge, CherryPickApproved

#2196 MM-13485 Switch to town square if last viewed channel is current channel
  actions/views/channel.js
  actions/views/channel.test.js
Labels: 2: Dev Review, CherryPickApproved

#2198 MM-13494 Remove fixed class from body when announcement bar is unmounted
  components/announcement_bar/announcement_bar.jsx
Labels: 2: Dev Review, CherryPickApproved

#2200 MM-13504 Fix for invite link to land in the team on login
  components/login/login_controller/login_controller.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2202 MM-13369 - Updating scrollbar for teams sidebar
  components/team_sidebar/team_sidebar_controller.jsx
  sass/layout/_team-sidebar.scss
Labels: 2: Dev Review

#2203 revert PR #1918
  components/add_user_to_channel_modal/__snapshots__/add_user_to_channel_modal.test.jsx.snap
  components/add_user_to_channel_modal/add_user_to_channel_modal.jsx
  components/add_user_to_channel_modal/add_user_to_channel_modal.test.jsx
  components/add_user_to_channel_modal/index.js
  components/profile_popover/__snapshots__/profile_popover.test.jsx.snap
  components/profile_popover/index.js
  components/profile_popover/profile_popover.jsx
  components/profile_popover/profile_popover.test.jsx
  components/suggestion/search_channel_with_permissions_provider.jsx
  components/suggestion/search_channel_with_permissions_provider.test.jsx
  i18n/en.json
  plugins/pluggable/__snapshots__/pluggable.test.jsx.snap
  plugins/pluggable/pluggable.test.jsx
  sass/components/_popover.scss
  utils/constants.jsx
Labels: 3: Ready to Merge

#1905 GH-9679 ordering plugins in alphabetical order
  components/admin_console/admin_sidebar/admin_sidebar.jsx
  package-lock.json
Labels: 3: Ready to Merge

#2197 MM-13268 Fix dimensions of webhook images (5.7)
  components/post_view/message_attachments/message_attachment/__snapshots__/message_attachment.test.jsx.snap
  components/post_view/message_attachments/message_attachment/message_attachment.jsx
  sass/layout/_webhooks.scss
Labels: 3: Ready to Merge

#2212 MM-13243: Spec fix.
  actions/views/create_comment.test.jsx
Labels: 2: Dev Review, CherryPickCandidate

#2214 Fix unit tests
  actions/post_actions.test.js
  actions/post_utils.js
  actions/post_utils.test.js
Labels: 2: Dev Review

#2215 MM-13429: remove help text that is never displayed.
  components/select_team/__snapshots__/select_team.test.jsx.snap
  components/select_team/select_team.jsx
  i18n/en.json
Labels: 3: Ready to Merge

#2210 MM-13520 Fix redirect to sign-up page when there are no user accounts
  components/root/root.jsx
  components/root/root.test.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2209 MM-13248 Load creators for oauth apps when needed
  actions/integration_actions.jsx
  actions/integration_actions.test.js
  components/integrations/installed_oauth_app/__snapshots__/installed_oauth_app.test.jsx.snap
  components/integrations/installed_oauth_app/index.js
  components/integrations/installed_oauth_app/installed_oauth_app.jsx
  components/integrations/installed_oauth_app/installed_oauth_app.test.jsx
  components/integrations/installed_oauth_apps/__snapshots__/installed_oauth_apps.test.jsx.snap
  components/integrations/installed_oauth_apps/index.js
  components/integrations/installed_oauth_apps/installed_oauth_apps.jsx
  components/integrations/installed_oauth_apps/installed_oauth_apps.test.jsx
Labels: 3: Ready to Merge

#2213 MM-13518 - Updating profile popover position
  components/profile_popover/profile_popover.jsx
  components/user_profile.jsx
  sass/components/_popover.scss
  utils/utils.jsx
Labels: CherryPickApproved

#2217 MM-13552: use .size, not .length, for Set returned from getUserIdsInChannels
  actions/user_actions.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2147 MM-8662 Allow plugin upload to overwrite installed plugins
  components/admin_console/plugin_management/plugin_management.jsx
  i18n/en.json
  package-lock.json
  package.json
Labels: QA Review, Setup Test Server

#2223 MM-13569 Add a check for percent value on upload progress to prevent app from crashing
  components/file_preview/__snapshots__/file_progress_preview.test.jsx.snap
  components/file_preview/file_progress_preview.jsx
  components/file_preview/file_progress_preview.test.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2220 MM-13502 - Updating announcement banner
  sass/components/_announcement-bar.scss
Labels: 3: Ready to Merge, CherryPickApproved

#2219 MM-13474 - Updating new channel modal
  components/new_channel_modal/__snapshots__/new_channel_modal.test.jsx.snap
  components/new_channel_modal/new_channel_modal.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2218 Move last remaining test file adjacent to the file being tested
  actions/team_actions.test.js
Labels: 3: Ready to Merge

#2228 MM-13574 Fix cut off of mention count on team sidebar
  sass/layout/_team-sidebar.scss
Labels: 3: Ready to Merge, CherryPickApproved

#2079 MM-13180 Call load posts earlier for infinite scroll
  components/post_view/post_list.jsx
Labels: 3: Ready to Merge

#2231 translations PR 20181224
  i18n/de.json
  i18n/it.json
  i18n/pl.json
  i18n/ro.json
  i18n/tr.json
  i18n/zh-CN.json
Labels: 3: Ready to Merge

#2234 MM-13496 - Updating modal buttons
  components/__snapshots__/setting_picture.test.jsx.snap
  components/admin_console/reset_email_modal/reset_email_modal.jsx
  components/confirm_modal.jsx
  components/delete_channel_modal/__snapshots__/delete_channel_modal.test.jsx.snap
  components/delete_channel_modal/delete_channel_modal.jsx
  components/delete_post_modal/__snapshots__/delete_post_modal.test.jsx.snap
  components/delete_post_modal/delete_post_modal.jsx
  components/edit_channel_header_modal/__snapshots__/edit_channel_header_modal.test.jsx.snap
  components/edit_channel_header_modal/edit_channel_header_modal.jsx
  components/edit_channel_purpose_modal/__snapshots__/edit_channel_purpose_modal.test.jsx.snap
  components/edit_channel_purpose_modal/edit_channel_purpose_modal.jsx
  components/edit_post_modal/__snapshots__/edit_post_modal.test.jsx.snap
  components/edit_post_modal/edit_post_modal.jsx
  components/emoji/add_emoji/__snapshots__/add_emoji.test.js.snap
  components/emoji/add_emoji/add_emoji.jsx
  components/integrations/__snapshots__/abstract_command.test.jsx.snap
  components/integrations/__snapshots__/abstract_incoming_hook.test.jsx.snap
  components/integrations/__snapshots__/abstract_oauth_app.test.jsx.snap
  components/integrations/__snapshots__/abstract_outgoing_webhook.test.jsx.snap
  components/integrations/abstract_command.jsx
  components/integrations/abstract_incoming_webhook.jsx
  components/integrations/abstract_oauth_app.jsx
  components/integrations/abstract_outgoing_webhook.jsx
  components/interactive_dialog/interactive_dialog.jsx
  components/invite_member_modal/invite_member_modal.jsx
  components/new_channel_modal/__snapshots__/new_channel_modal.test.jsx.snap
  components/new_channel_modal/new_channel_modal.jsx
  components/rename_channel_modal/__snapshots__/rename_channel_modal.test.jsx.snap
  components/rename_channel_modal/rename_channel_modal.jsx
  components/searchable_channel_list.jsx
  components/searchable_user_list/searchable_user_list.jsx
  components/setting_picture.jsx
  components/user_settings/import_theme_modal.jsx
  components/user_settings/security/user_access_token_section/user_access_token_section.jsx
  sass/components/_modal.scss
  sass/utils/_variables.scss
  utils/utils.jsx
Labels: 2: Dev Review, CherryPickApproved
