Repository mattermost/mattermost-webapp, pull requests merged in 2018-06, with the labels that each got.

#1278 MM-10757: Changing default_{channel,team}_{user,admin}_role to names instead of ids
  components/admin_console/permission_schemes_settings/permission_team_scheme_settings/index.jsx
  components/admin_console/permission_schemes_settings/permission_team_scheme_settings/permission_team_scheme_settings.jsx
  tests/components/admin_console/permission_schemes_settings/permission_team_scheme_settings.test.jsx
Labels: 2: Dev Review

#1272 Tweak to opacity in permissions CSS
  sass/components/_permissions.scss
Labels: 2: Dev Review

#1271 Allowing empty submission of MFA for hardened mode.
  components/login/login_mfa.jsx
  tests/components/login/login_mfa.test.jsx
Labels: 3: Ready to Merge

#1268 Updates to AD/LDAP settings help text
  components/admin_console/admin_definition.jsx
  i18n/en.json
Labels: 2: Dev Review

#1264 [MM-10718] Move custom branding to TE
  components/admin_console/admin_sidebar/admin_sidebar.jsx
  components/admin_console/custom_brand_settings.jsx
  components/common/site_name_and_description.jsx
  components/create_team/create_team.jsx
  components/create_team/index.js
  components/login/login_controller/index.js
  components/login/login_controller/login_controller.jsx
  components/select_team/index.js
  components/select_team/select_team.jsx
  components/signup/signup_email/index.js
  components/signup/signup_email/signup_email.jsx
  components/signup/signup_ldap/signup_ldap.jsx
  tests/components/common/__snapshots__/site_name_and_description.test.jsx.snap
  tests/components/common/site_name_and_description.test.jsx
  tests/components/create_team/__snapshots__/create_team.test.jsx.snap
  tests/components/create_team/create_team.test.jsx
  tests/components/select_team/__snapshots__/select_team.test.jsx.snap
  tests/components/select_team/select_team.test.jsx
Labels: Awaiting PR

#1218 [MM-10519] Remove channel from MoreChannels whenever a channel is converted form public to private
  actions/websocket_actions.jsx
  components/more_channels/index.js
  components/more_channels/more_channels.jsx
  components/quick_input.jsx
  package-lock.json
  package.json
  tests/components/__snapshots__/more_channels.test.jsx.snap
  tests/components/more_channels.test.jsx
  tests/utils/url.test.jsx
  utils/constants.jsx
  utils/url.jsx
Labels: 3: Ready to Merge

#1283 MM-10372 Fixed linking between teams from channels with the same name
  components/channel_layout/channel_identifier_router.jsx
Labels: 3: Ready to Merge

#1282 MM-10706 Recalculate post height for collapsed post after images load
  components/markdown/markdown.jsx
  components/markdown_image.jsx
  components/post_markdown/post_markdown.jsx
  components/post_view/post_message_view/post_message_view.jsx
  tests/plugins/__snapshots__/post_type.test.jsx.snap
  utils/message_html_to_component.jsx
Labels: 3: Ready to Merge

#1281 Update APIv3 pop-up notice
  components/system_notice/notices.jsx
  i18n/en.json
Labels: 3: Ready to Merge

#1285 MM-10770: Add confirm modal on exit team scheme and system scheme edition
  components/admin_console/permission_schemes_settings/permission_system_scheme_settings/index.jsx
  components/admin_console/permission_schemes_settings/permission_system_scheme_settings/permission_system_scheme_settings.jsx
  components/admin_console/permission_schemes_settings/permission_team_scheme_settings/index.jsx
  components/admin_console/permission_schemes_settings/permission_team_scheme_settings/permission_team_scheme_settings.jsx
  tests/components/admin_console/permission_schemes_settings/__snapshots__/permission_system_scheme_settings.test.jsx.snap
  tests/components/admin_console/permission_schemes_settings/__snapshots__/permission_team_scheme_settings.test.jsx.snap
  tests/components/admin_console/permission_schemes_settings/permission_system_scheme_settings.test.jsx
  tests/components/admin_console/permission_schemes_settings/permission_team_scheme_settings.test.jsx
Labels: 2: Dev Review

#1220 MM-10500 - Implementing Relay chat UI updates
  components/post_view/post_info/post_info.jsx
  components/rhs_comment/rhs_comment.jsx
  components/rhs_root_post/rhs_root_post.jsx
  components/search_results_item/search_results_item.jsx
  components/svg/attachment_icon.jsx
  components/svg/emoji_icon.jsx
  components/team_sidebar/components/team_button.jsx
  components/team_sidebar/team_sidebar_controller.jsx
  sass/components/_dropdown.scss
  sass/components/_search.scss
  sass/layout/_post-right.scss
  sass/layout/_post.scss
  sass/layout/_team-sidebar.scss
  tests/components/__snapshots__/search_results_item.test.jsx.snap
  utils/utils.jsx
Labels: 3: Ready to Merge

#1288 Fixed null pointer when calling onHeightReceived
  components/markdown_image.jsx
Labels: 3: Ready to Merge

#1277 [MM-10727] Fix missing username on combined system messages
  components/post_markdown/system_message_helpers.jsx
  components/post_view/combined_system_message/combined_system_message.jsx
  components/post_view/combined_system_message/index.js
  package-lock.json
  package.json
  tests/components/combined_system_message/__snapshots__/combined_system_message.test.jsx.snap
  tests/components/combined_system_message/combined_system_message.test.jsx
Labels: 3: Ready to Merge

#1280 Permissions pop-up notice
  components/system_notice/notices.jsx
  i18n/en.json
Labels: 3: Ready to Merge

#1217 SKU change: Enable Themes per Team
  components/user_settings/display/user_settings_theme.jsx
  components/user_settings/display/user_settings_theme/index.js
  tests/components/user_settings/__snapshots__/user_settings_display.test.jsx.snap
Labels: 3: Ready to Merge

#1265 Update Image preview setting label and help text
  components/user_settings/display/user_settings_display.jsx
  i18n/en.json
  tests/components/user_settings/__snapshots__/user_settings_display.test.jsx.snap
Labels: 3: Ready to Merge

#1293 MM-10762: Adjusts team and channel role changes to support new permis…
  actions/channel_actions.jsx
  actions/team_actions.jsx
  components/admin_console/manage_teams_modal/manage_teams_dropdown.jsx
  components/admin_console/manage_teams_modal/manage_teams_modal.jsx
  components/admin_console/system_users/list/index.js
  components/admin_console/system_users/list/system_users_list.jsx
  components/channel_members_dropdown/channel_members_dropdown.jsx
  components/channel_members_dropdown/index.js
  components/team_members_dropdown/index.js
  components/team_members_dropdown/team_members_dropdown.jsx
  tests/components/admin_console/system_users/__snapshots__/system_users_list.test.jsx.snap
  tests/components/admin_console/system_users/system_users_list.test.jsx
Labels: 3: Ready to Merge

#1294 Adds next Redux commit.
  package-lock.json
  package.json
Labels: 3: Ready to Merge

#1290 MM-10793: Handle the show/hide custom emojis in menu using permissions
  components/backstage/backstage_controller.jsx
  components/backstage/components/backstage_sidebar.jsx
  components/backstage/index.js
  components/sidebar/header/dropdown/index.js
  components/sidebar/header/dropdown/sidebar_header_dropdown.jsx
  tests/plugins/main_menu_action.test.jsx
  utils/utils.jsx
Labels: 3: Ready to Merge

#1279 [MM-10511] Fix missing users' status indicators on more DM modal
  components/more_direct_channels/index.js
  components/more_direct_channels/more_direct_channels.jsx
  tests/components/__snapshots__/more_direct_channels.test.jsx.snap
  tests/components/more_direct_channels.test.jsx
Labels: 3: Ready to Merge

#1289 Minor 5.0 Bug fixes
  sass/components/_tooltip.scss
  sass/layout/_post.scss
  sass/responsive/_mobile.scss
  utils/utils.jsx
Labels: 3: Ready to Merge

#1291 MM-10713 Fixed collapsed post colour in permalink view
  utils/utils.jsx
Labels: 3: Ready to Merge

#1299 MM-10767: Sort the teams in the teams selector modal
  components/team_selector_modal/team_selector_modal.jsx
Labels: 3: Ready to Merge

#1286 translations PR 20180604
  i18n/de.json
  i18n/en.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ru.json
  i18n/tr.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 3: Ready to Merge

#1287 MM-10555 Update outgoing webhook content-type help text
  components/integrations/abstract_outgoing_webhook.jsx
  i18n/en.json
Labels: 3: Ready to Merge

#1301 [MM-10519] Fix permission error on channel_converted event
  actions/websocket_actions.jsx
Labels: 3: Ready to Merge

#1255 MM-10664: Fix the Centre Channel scroll when using Grammarly in chrome.
  components/logged_in/logged_in.jsx
  sass/base/_structure.scss
Labels: 3: Ready to Merge

#1296 Minor 5.0 bugs
  components/team_sidebar/components/team_button.jsx
  sass/layout/_post.scss
  sass/layout/_team-sidebar.scss
  utils/utils.jsx
Labels: 3: Ready to Merge

#1308 Relese5.0 merge master 20180608
  actions/websocket_actions.jsx
  components/integrations/abstract_outgoing_webhook.jsx
  components/team_selector_modal/team_selector_modal.jsx
  components/team_sidebar/components/team_button.jsx
  i18n/de.json
  i18n/en.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ru.json
  i18n/tr.json
  i18n/zh-CN.json
  i18n/zh-TW.json
  sass/layout/_post.scss
  sass/layout/_team-sidebar.scss
  utils/utils.jsx
Labels: 3: Ready to Merge

#1231 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: 3: Ready to Merge

#1304 MM-10789: propagate post channel_mentions to Markdown
  components/markdown/index.js
  components/post_markdown/post_markdown.jsx
  tests/components/__snapshots__/post_markdown.test.jsx.snap
  tests/components/post_markdown.test.jsx
Labels: 3: Ready to Merge

#1297 [MM-10771] Add E2E for account settings display
  nightwatch.json
  tests/e2e/globals.js
  tests/e2e/test.sh
  tests/e2e/tests/3_sidebarLeft/accountSettingsDisplay.action.js
  tests/e2e/tests/3_sidebarLeft/accountSettingsModalPage.element.js
Labels: 2: Dev Review

#1309 MM-10842 Fix color settings in the admin console and announcement setting disabling
  components/admin_console/admin_definition.jsx
  components/admin_console/color_setting.jsx
  tests/components/admin_console/__snapshots__/color_setting.test.jsx.snap
  tests/components/admin_console/color_setting.test.jsx
Labels: 3: Ready to Merge

#1310 MM-10844: maximum file size is a TYPE_NUMBER
  components/admin_console/admin_definition.jsx
Labels: 3: Ready to Merge

#1319 MM-10647: Fix for Korean character double post on ctrl+enter.
  components/create_post/create_post.jsx
  tests/components/create_post/create_post.test.jsx
Labels: 2: Dev Review

#1316 MM-10876 Removed horizontal scrollbar on some posts in IE11
  sass/layout/_post.scss
Labels: 3: Ready to Merge

#1315 MM-10706 Made sure to update post height when image loads
  components/markdown_image.jsx
Labels: 3: Ready to Merge

#1312 MM-10845 Allowed system console error message to wrap to 2 lines
  sass/routes/_admin-console.scss
  sass/utils/_mixins.scss
Labels: 3: Ready to Merge

#1314 [MM-10834] Fix scaling issue of SVG image
  components/single_image_view/single_image_view.jsx
  tests/components/__snapshots__/single_image_view.test.jsx.snap
  tests/components/single_image_view.test.jsx
Labels: 3: Ready to Merge

#1324 MM-10890: Restore the previous behavior avoiding system admins removing itself from team admin
  components/team_members_dropdown/team_members_dropdown.jsx
Labels: 3: Ready to Merge

#1331 MM-10911: Transforms MiB input to config bytes; config bytes to display MiB.
  components/admin_console/admin_definition.jsx
  components/admin_console/schema_admin_settings.jsx
  tests/components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
  tests/components/admin_console/schema_admin_settings.test.jsx
Labels: 3: Ready to Merge

#1328 translations PR 20180613
  i18n/de.json
  i18n/en.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ru.json
  i18n/tr.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 3: Ready to Merge

#1326 MM-10843: Grammatical tweaks to permissions translations.
  i18n/en.json
Labels: 3: Ready to Merge

#1320 MM-10872 Fix keyboard navigation in emoji picker
  components/emoji_picker/emoji_picker.jsx
Labels: 3: Ready to Merge

#1330 MM-10916: Updates some permissions text to include documentation links. Disables eslint complexity rule.
  .eslintrc.json
  components/admin_console/admin_sidebar/admin_sidebar.jsx
  components/admin_console/permission_schemes_settings/permission_schemes_settings.jsx
  components/admin_console/permission_schemes_settings/permission_system_scheme_settings/permission_system_scheme_settings.jsx
  components/admin_console/permission_schemes_settings/permission_team_scheme_settings/permission_team_scheme_settings.jsx
  components/formatted_markdown_message.jsx
  i18n/en.json
  tests/components/__snapshots__/formatted_markdown_message.test.jsx.snap
  tests/components/admin_console/permission_schemes_settings/__snapshots__/permission_schemes_settings.test.jsx.snap
  tests/components/admin_console/permission_schemes_settings/__snapshots__/permission_system_scheme_settings.test.jsx.snap
  tests/components/admin_console/permission_schemes_settings/__snapshots__/permission_team_scheme_settings.test.jsx.snap
  tests/components/formatted_markdown_message.test.jsx
Labels: 2: Dev Review

#1336 Release 5.0 merge to master 20180614 1
  .eslintrc.json
  components/admin_console/admin_definition.jsx
  components/admin_console/admin_sidebar/admin_sidebar.jsx
  components/admin_console/permission_schemes_settings/permission_schemes_settings.jsx
  components/admin_console/permission_schemes_settings/permission_system_scheme_settings/permission_system_scheme_settings.jsx
  components/admin_console/permission_schemes_settings/permission_team_scheme_settings/permission_team_scheme_settings.jsx
  components/admin_console/schema_admin_settings.jsx
  components/emoji_picker/emoji_picker.jsx
  components/formatted_markdown_message.jsx
  components/team_members_dropdown/team_members_dropdown.jsx
  i18n/de.json
  i18n/en.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ru.json
  i18n/tr.json
  i18n/zh-CN.json
  i18n/zh-TW.json
  tests/components/__snapshots__/formatted_markdown_message.test.jsx.snap
  tests/components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
  tests/components/admin_console/permission_schemes_settings/__snapshots__/permission_schemes_settings.test.jsx.snap
  tests/components/admin_console/permission_schemes_settings/__snapshots__/permission_system_scheme_settings.test.jsx.snap
  tests/components/admin_console/permission_schemes_settings/__snapshots__/permission_team_scheme_settings.test.jsx.snap
  tests/components/admin_console/schema_admin_settings.test.jsx
Labels: 2: Dev Review

#1334 Remove number of members on teams to avoid a lot of requests
  components/team_info.jsx
  components/team_info/index.jsx
  components/team_selector_modal/team_selector_modal.jsx
  tests/components/__snapshots__/team_info.test.jsx.snap
  tests/components/team_info.test.jsx
Labels: 3: Ready to Merge

#1332 MM-10888 Hide parts of combined system messages that don't affect the current user
  components/post_view/combined_system_message/combined_system_message.jsx
  components/post_view/combined_system_message/index.js
  package-lock.json
  package.json
  tests/components/combined_system_message/__snapshots__/combined_system_message.test.jsx.snap
  tests/components/combined_system_message/combined_system_message.test.jsx
Labels: 3: Ready to Merge

#1322 Fix Opening the channel switch modal triggers a JS error when user is undefined
  components/suggestion/switch_channel_provider.jsx
Labels: 3: Ready to Merge

#1317 MM-10875 - Fixing post controls in IE11
  sass/layout/_post-right.scss
  sass/layout/_post.scss
  sass/responsive/_mobile.scss
Labels: 3: Ready to Merge

#1338 MM-10921 Do not show link previews for system messages
  components/post_view/post_attachment_opengraph/post_attachment_opengraph.jsx
Labels: 3: Ready to Merge

#1339 MM-10872 Revert width change of emoji picker to fix keyboard navigation
  components/emoji_picker/emoji_picker.jsx
  sass/components/_emoticons.scss
Labels: 3: Ready to Merge

#1343 Release 5.0 merge to master 20180615
  components/emoji_picker/emoji_picker.jsx
  components/post_view/combined_system_message/combined_system_message.jsx
  components/post_view/combined_system_message/index.js
  components/post_view/post_attachment_opengraph/post_attachment_opengraph.jsx
  components/suggestion/switch_channel_provider.jsx
  components/team_info.jsx
  components/team_info/index.jsx
  components/team_selector_modal/team_selector_modal.jsx
  package-lock.json
  package.json
  sass/components/_emoticons.scss
  sass/layout/_post-right.scss
  sass/layout/_post.scss
  sass/responsive/_mobile.scss
  tests/components/__snapshots__/team_info.test.jsx.snap
  tests/components/combined_system_message/__snapshots__/combined_system_message.test.jsx.snap
  tests/components/combined_system_message/combined_system_message.test.jsx
  tests/components/team_info.test.jsx
Labels: 2: Dev Review

#1323 MM-10812 Attempt to load posts to fill screen
  components/post_view/post_list.jsx
Labels: 3: Ready to Merge

#1342 Clarify logic in EmojiListItem when user isn't loaded
  components/emoji/emoji_list_item/index.js
Labels: 3: Ready to Merge

#1344 fix post menu
  sass/layout/_post.scss
Labels: 2: Dev Review

#1311 Fix deprecated `plarform` string
  components/admin_console/admin_definition.jsx
  components/help/components/formatting.jsx
  i18n/en.json
Labels: 3: Ready to Merge

#1295 Fix incorrect translation id
  components/admin_console/admin_definition.jsx
Labels: 3: Ready to Merge

#1349 Fix ImageProxy settings
  components/admin_console/admin_definition.jsx
Labels: 3: Ready to Merge

#1346 Fixes docs typo.
  components/formatted_markdown_message.jsx
Labels: 2: Dev Review

#1354 MM-10962 Fix capitalization of YouTube
  components/youtube_video/youtube_video.jsx
Labels: 2: Dev Review

#1360 [MM-10929] Update mattermost-redux with fix on duplicated user on combined system messages
  package-lock.json
  package.json
Labels: 2: Dev Review

#1350 translations PR 20180619
  i18n/de.json
  i18n/en.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ru.json
  i18n/tr.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 2: Dev Review

#1363 MM-8701 Get client config after logging in
  package-lock.json
  package.json
Labels: 3: Ready to Merge

#1333 MM-10915 Plus sign missing to add more reactions in GM and DM channels
  components/permissions_gates/channel_permission_gate/index.js
  tests/components/__snapshots__/permissions_gates.test.jsx.snap
  tests/components/permissions_gates.test.jsx
Labels: 3: Ready to Merge

#1357 MM-10951: Change all instances of deleting a channel in strings to archive.
  components/admin_console/users_and_teams_settings/users_and_teams_settings.jsx
  components/audit_table.jsx
  components/channel_header/channel_header.jsx
  components/delete_channel_modal/delete_channel_modal.jsx
  components/navbar/navbar.jsx
  i18n/en.json
  tests/components/__snapshots__/delete_channel_modal.test.jsx.snap
  tests/components/navbar/__snapshots__/navbar.test.jsx.snap
Labels: 3: Ready to Merge

#1369 Upgrading dependencies.
  package-lock.json
  package.json
  tests/components/activity_log_modal.test.jsx
  tests/components/admin_console/request_button/__snapshots__/request_button.test.jsx.snap
  tests/components/create_team/team_url.test.jsx
  tests/components/integrations/abstract_command.test.jsx
  tests/components/integrations/abstract_incoming_hook.test.jsx
  tests/components/integrations/abstract_oauth_app.test.jsx
  tests/components/integrations/edit_oauth_app.test.jsx
  tests/components/integrations/installed_oauth_app.test.jsx
  tests/components/integrations/installed_oauth_apps.test.jsx
  tests/components/navbar/__snapshots__/navbar_info_button.test.jsx.snap
  tests/components/reset_status_modal.test.jsx
Labels: 2: Dev Review

#1347 Clean up combined_system_message component
  components/post_view/combined_system_message/combined_system_message.jsx
  components/post_view/combined_system_message/index.js
  tests/components/combined_system_message/combined_system_message.test.jsx
Labels: Awaiting PR

#1348 MM-10368: react-router subpath
  actions/websocket_actions.jsx
  components/admin_console/system_users/system_users_dropdown.jsx
  components/authorize.jsx
  components/integrations/confirm_integration/confirm_integration.jsx
  components/root/root.jsx
  components/signup/signup_controller/signup_controller.jsx
  components/textbox.jsx
  components/user_settings/security/user_settings_security.jsx
  entry.js
  package-lock.json
  package.json
  root.jsx
  selectors/general.js
  store/index.js
  tests/components/__snapshots__/textbox.test.jsx.snap
  tests/components/edit_post_modal.test.jsx
  tests/utils/formatting_channel_links.test.jsx
  tests/utils/url.test.jsx
  utils/browser_history.jsx
  utils/text_formatting.jsx
  utils/url.jsx
Labels: 3: Ready to Merge, Setup Test Server

#1364 [MM-9392] Add E2E for Account Settings > General Settings
  components/user_settings/general/user_settings_general.jsx
  tests/e2e/pages/accountSettingsModalPage.js
  tests/e2e/tests/3_sidebarLeft/accountSettingsGeneral.action.js
  tests/e2e/tests/3_sidebarLeft/accountSettingsModalPage.element.js
Labels: 3: Ready to Merge

#1370 update admin console help text re: subpath
  components/admin_console/admin_definition.jsx
  i18n/en.json
Labels: 3: Ready to Merge

#1356 Fix image rendering to include uppercase image extensions
  components/post_view/post_body_additional_content/post_body_additional_content.jsx
  tests/components/post_view/post_body_additional_content/post_body_additional_content.test.jsx
Labels: 3: Ready to Merge

#1375 Fix message
  i18n/en.json
Labels: 2: Dev Review

#1376 MM-10873 Preserve newlines in mobile view channel headers
  components/navbar/navbar_info_button.jsx
  sass/layout/_headers.scss
  tests/components/navbar/__snapshots__/navbar_info_button.test.jsx.snap
Labels: 2: Dev Review

#1377 MM-10444 Passed overridden post profile picture through image proxy
  components/post_profile_picture/index.jsx
  components/post_profile_picture/post_profile_picture.jsx
  components/post_view/post/post.jsx
  components/profile_picture.jsx
  components/rhs_comment/rhs_comment.jsx
  components/rhs_root_post/rhs_root_post.jsx
  components/search_results_item/search_results_item.jsx
  tests/components/__snapshots__/search_results_item.test.jsx.snap
  tests/components/search_results_item.test.jsx
  utils/post_utils.jsx
Labels: 3: Ready to Merge

#1337 MM-10833: link other channel references
  components/channel_header/channel_header.jsx
  components/channel_info_modal/channel_info_modal.jsx
  components/post_markdown/system_message_helpers.jsx
  tests/components/__snapshots__/channel_header.test.jsx.snap
  tests/components/__snapshots__/channel_info_modal.test.jsx.snap
  tests/components/__snapshots__/post_markdown.test.jsx.snap
  tests/components/channel_header.test.jsx
  tests/components/channel_info_modal.test.jsx
  tests/components/post_markdown.test.jsx
Labels: 3: Ready to Merge

#1378 translations PR 20180625
  i18n/de.json
  i18n/en.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ru.json
  i18n/tr.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 3: Ready to Merge

#1379 MM-9674 Add plugin API for registering websocket event handlers
  actions/websocket_actions.jsx
  plugins/registry.js
Labels: 3: Ready to Merge

#1390 replace a well-intentioned &nbsp; with a ' ' instead
  components/post_view/post_attachment_opengraph/post_attachment_opengraph.jsx
Labels: 3: Ready to Merge

#1383 Minor Bug fixes
  components/single_image_view/single_image_view.jsx
  sass/components/_emoticons.scss
  sass/components/_files.scss
  tests/components/__snapshots__/single_image_view.test.jsx.snap
Labels: 3: Ready to Merge

#1365 Track the nickname when needed, not the username
  components/user_settings/general/user_settings_general.jsx
Labels: 3: Ready to Merge

#1387 Href corrections to file setting descriptions
  components/admin_console/admin_definition.jsx
  i18n/en.json
Labels: 3: Ready to Merge

#1389 MM-11036: subpath eliminate hardcoded /static/
  components/emoji_picker/components/emoji_picker_item.jsx
  components/emoji_picker/components/emoji_picker_preview.jsx
  components/emoji_picker/emoji_picker.jsx
  config/manifest.json
  package-lock.json
  package.json
  root.html
  stores/emoji_store.jsx
  webpack.config.js
Labels: 2: Dev Review

#1366 Fix allways typo in the edit post modal tests
  tests/components/edit_post_modal.test.jsx
Labels: 3: Ready to Merge

#1382 MM-10956: Add unique id to each permission row
  components/admin_console/permission_schemes_settings/permission_group.jsx
  components/admin_console/permission_schemes_settings/permission_row.jsx
  components/admin_console/permission_schemes_settings/permissions_tree.jsx
  tests/components/admin_console/permission_schemes_settings/__snapshots__/permission_group.test.jsx.snap
  tests/components/admin_console/permission_schemes_settings/__snapshots__/permission_row.test.jsx.snap
  tests/components/admin_console/permission_schemes_settings/__snapshots__/permissions_tree.test.jsx.snap
  tests/components/admin_console/permission_schemes_settings/permission_group.test.jsx
  tests/components/admin_console/permission_schemes_settings/permission_row.test.jsx
Labels: 3: Ready to Merge

#1392 MM-10364 Russian keyboard layout breaks Command+K on a Mac
  tests/utils/utils.test.jsx
  utils/constants.jsx
  utils/utils.jsx
Labels: 3: Ready to Merge

#1391 MM-11091: Fixes config value name; changes value type.
  components/admin_console/admin_definition.jsx
Labels: 2: Dev Review

#1395 Ensure package-lock.json matches package.json
  package-lock.json
Labels: 2: Dev Review

#1396 Updated help text for Gfycat API credentials
  components/admin_console/custom_gif_settings.jsx
  i18n/en.json
Labels: 3: Ready to Merge
