Repository mattermost/mattermost-webapp, pull requests merged in 2019-07, with the labels that each got.

#3021 MM-16393 - Cleaning up mobile header
  components/admin_console/admin_sidebar_header/admin_sidebar_header.jsx
  components/channel_header_dropdown/index.js
  components/channel_header_dropdown/mobile_channel_header_dropdown.js
  components/channel_header_mobile/collapse_lhs_button/collapse_lhs_button.js
  components/sidebar/header/sidebar_header_dropdown_button.jsx
  components/svg/menu_icon.jsx
  sass/layout/_forms.scss
Labels: 3: Reviews Complete

#3038 Update cypress to 3.3.2
  package-lock.json
  package.json
Labels: 3: Reviews Complete

#3022 Fix failing test on search specs
  cypress/integration/search/date_filter_spec.js
  cypress/integration/search/results_post_comment_spec.js
Labels: 2: Dev Review

#3032 E2E: Fix test for email notification
  cypress.json
  cypress/integration/email/mention_email_notification_spec.js
  cypress/integration/signin_authentication/forgot_password_spec.js
  cypress/plugins/get_recent_email.js
  cypress/support/api_commands.js
  cypress/utils/index.js
Labels: 2: Dev Review

#3000 MM-16384, MM-16385 - Sidebar accessibility improvements
  components/channel_header/__snapshots__/channel_header.test.jsx.snap
  components/channel_header/channel_header.js
  components/channel_header/components/__snapshots__/header_icon_wrapper.test.js.snap
  components/channel_header/components/header_icon_wrapper.js
  components/create_comment/__snapshots__/create_comment.test.jsx.snap
  components/create_comment/create_comment.jsx
  components/create_post/__snapshots__/create_post.test.jsx.snap
  components/create_post/create_post.jsx
  components/popover_list_members/__snapshots__/popover_list_members.test.jsx.snap
  components/popover_list_members/popover_list_members.jsx
  components/post_view/post/post.jsx
  components/root/root.jsx
  components/search_bar/search_bar.jsx
  components/sidebar/__snapshots__/sidebar.test.jsx.snap
  components/sidebar/channel_create.jsx
  components/sidebar/channel_name.jsx
  components/sidebar/header/sidebar_header.jsx
  components/sidebar/sidebar.jsx
  components/sidebar/sidebar_channel/__snapshots__/sidebar_channel.test.jsx.snap
  components/sidebar/sidebar_channel/sidebar_channel.jsx
  components/sidebar/sidebar_channel_button_or_link/__snapshots__/sidebar_channel_button_or_link.test.jsx.snap
  components/sidebar/sidebar_channel_button_or_link/sidebar_channel_button_or_link.jsx
  components/sidebar/sidebar_channel_button_or_link/sidebar_channel_button_or_link.test.jsx
  i18n/en.json
  plugins/channel_header_plug/__snapshots__/channel_header_plug.test.jsx.snap
  sass/base/_structure.scss
  sass/layout/_sidebar-left.scss
Labels: 2: Dev Review

#3043 E2E: fix valid name due to recent change
  cypress/integration/login/signup_spec.js
Labels: 3: Reviews Complete

#3045 Fix attempt to use non-string as aria-label
  components/sidebar/sidebar_channel/__snapshots__/sidebar_channel.test.jsx.snap
  components/sidebar/sidebar_channel/sidebar_channel.jsx
  components/sidebar/sidebar_channel/sidebar_channel.test.jsx
  components/sidebar/sidebar_channel_button_or_link/sidebar_channel_button_or_link.jsx
Labels: 3: Reviews Complete

#2814 MM-14040 update marked for parentheses
  package-lock.json
  package.json
Labels: 2: Dev Review

#3042 [MM-16627] Show connection security setting on team edition
  components/admin_console/admin_definition.jsx
Labels: 3: Reviews Complete, CherryPick/Approved, Setup Test Server

#3035 MM-15992 - Updating search bar description
  components/search_bar/search_bar.jsx
Labels: 3: Reviews Complete

#3054 [MM-16727] Hide Change eMail option for currently logged in user in admin area
  components/admin_console/system_users/system_users_dropdown/system_users_dropdown.jsx
Labels: 2: Dev Review

#3037 [MM-15661] Remove the SendEmailNotification check from the invite modal
  components/invite_member_modal/index.js
  components/invite_member_modal/invite_member_modal.jsx
Labels: 3: Reviews Complete

#3046 MM-16673 Only focus RHS textbox when necessary
  components/create_comment/create_comment.jsx
  components/create_comment/create_comment.test.jsx
Labels: 2: Dev Review

#3031 [MM-16376] Install plugin from URL in admin console
  components/admin_console/plugin_management/__snapshots__/plugin_management.test.jsx.snap
  components/admin_console/plugin_management/index.js
  components/admin_console/plugin_management/plugin_management.jsx
  components/admin_console/plugin_management/plugin_management.test.jsx
  i18n/en.json
  package-lock.json
  package.json
Labels: 3: Reviews Complete

#3009 [PLT-4951] Don't send notifications if thread is showing in RHS
  actions/notification_actions.jsx
  actions/notification_actions.test.jsx
  actions/post_utils.js
  actions/post_utils.test.js
Labels: 3: Reviews Complete

#3048 MM-15993 - Making autocomplete a11y compatible
  components/search_bar/search_bar.jsx
  components/suggestion/__snapshots__/command_provider.test.js.snap
  components/suggestion/search_channel_provider.jsx
  components/suggestion/search_suggestion_list.jsx
  components/suggestion/search_user_provider.jsx
  components/suggestion/suggestion.jsx
  sass/components/_search.scss
Labels: 2: Dev Review

#3053 MM-16367 - Updating mobile view sidebar styling
  sass/layout/_headers.scss
  sass/responsive/_mobile.scss
  utils/utils.jsx
Labels: 2: Dev Review

#3056 E2E: fix failing tests
  e2e/cypress/integration/account_settings/theme_color/custom_colors_sidebar_styles_spec.js
  e2e/cypress/integration/channel/channel_settings_spec.js
  e2e/cypress/integration/channel/header_spec.js
  e2e/cypress/integration/channel/message_edit_post_with_attachment_spec.js
  e2e/cypress/integration/markdown/markdown_image_spec.js
  e2e/cypress/integration/search/date_filter_spec.js
  e2e/cypress/support/api_commands.js
  e2e/cypress/support/ui_commands.js
Labels: 2: Dev Review

#3034 MM 15240 - No Status on a System Message
  e2e/cypress/integration/multi_team/system_message_spec.js
  e2e/cypress/support/api_commands.js
Labels: 2: Dev Review

#3060 Increasing test coverage for MM-15012
  e2e/cypress/integration/messaging/emoji_size_spec.js
Labels: 2: Dev Review

#3062 First iteration on styling comments for invitation flow
  components/invitation_modal/__snapshots__/invitation_modal_initial_step.test.jsx.snap
  components/invitation_modal/__snapshots__/invitation_modal_members_step.test.jsx.snap
  components/invitation_modal/invitation_modal.scss
  components/invitation_modal/invitation_modal_guests_step.jsx
  components/invitation_modal/invitation_modal_guests_step.scss
  components/invitation_modal/invitation_modal_initial_step.jsx
  components/invitation_modal/invitation_modal_initial_step.scss
  components/invitation_modal/invitation_modal_members_step.jsx
  components/invitation_modal/invitation_modal_members_step.scss
  components/svg/arrow_right_icon.jsx
  components/svg/close_circle_solid_icon.jsx
  components/widgets/inputs/channels_input.jsx
  components/widgets/inputs/channels_input.scss
  components/widgets/inputs/channels_input.test.jsx
  components/widgets/inputs/emails_input.jsx
  components/widgets/inputs/emails_input.scss
  components/widgets/inputs/users_emails_input.jsx
  components/widgets/inputs/users_emails_input.scss
  components/widgets/inputs/users_emails_input.test.jsx
  components/widgets/modals/full_screen_modal.scss
  i18n/en.json
  utils/utils.jsx
Labels: 3: Reviews Complete

#3059 MM-15652 Render header plugin correctly in mobile view
  plugins/mobile_channel_header_plug/__snapshots__/mobile_channel_header_plug.test.jsx.snap
  plugins/mobile_channel_header_plug/mobile_channel_header_plug.jsx
  plugins/mobile_channel_header_plug/mobile_channel_header_plug.test.jsx
Labels: 3: Reviews Complete, CherryPick/Approved

#3052 MM-16695 Update mattermost-redux to add additional null check
  package-lock.json
  package.json
Labels: 3: Reviews Complete, CherryPick/Approved

#3028 MM-16477 Check for modified users on reconnect
  actions/views/channel.test.js
  actions/websocket_actions.jsx
  actions/websocket_actions.test.jsx
  reducers/views/index.js
  reducers/views/websocket.js
  reducers/views/websocket.test.js
  selectors/views/websocket.js
Labels: 3: Reviews Complete

#3063 [MM-15887] E2E: add test for interactive menus - basic options
  .eslintrc.json
  components/post_view/message_attachments/message_attachment_list.jsx
  e2e/cypress/fixtures/hooks/message_menus.json
  e2e/cypress/fixtures/hooks/message_menus_with_datasource.json
  e2e/cypress/integration/interactive_menu/basic_options.js
  e2e/cypress/plugins/index.js
  e2e/cypress/plugins/post_incoming_webhook.js
  e2e/cypress/plugins/post_message_as.js
  e2e/cypress/support/api_commands.js
  e2e/cypress/utils/index.js
  e2e/package-lock.json
  e2e/package.json
  e2e/webhook_serve.js
Labels: 2: Dev Review

#3070 E2E: Fix messaging and team flaky specs
  e2e/cypress/integration/channel/message_spec.js
  e2e/cypress/integration/team/teams_spec.js
Labels: 3: Reviews Complete

#3041 [MM-15995] 'User Info Card' for new 'User Detail' page
  components/admin_console/__snapshots__/admin_console.test.jsx.snap
  components/admin_console/admin_button_outline/admin_button_outline.jsx
  components/admin_console/admin_button_outline/admin_button_outline.scss
  components/admin_console/admin_definition.jsx
  components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.jsx.snap
  components/admin_console/admin_user_card/__snapshots__/admin_user_card.test.jsx.snap
  components/admin_console/admin_user_card/admin_user_card.jsx
  components/admin_console/admin_user_card/admin_user_card.scss
  components/admin_console/admin_user_card/admin_user_card.test.jsx
  components/admin_console/system_user_detail/__snapshots__/system_user_detail.test.jsx.snap
  components/admin_console/system_user_detail/index.js
  components/admin_console/system_user_detail/system_user_detail.jsx
  components/admin_console/system_user_detail/system_user_detail.scss
  components/admin_console/system_user_detail/system_user_detail.test.jsx
  components/profile_picture.jsx
  components/user_list.jsx
  components/user_list_row_with_error/user_list_row_with_error.jsx
  i18n/en.json
  package-lock.json
  sass/components/_status-icon.scss
Labels: 3: Reviews Complete

#3018 [MM-14720] Add bot post counts per day to System Analytics
  actions/admin_actions.jsx
  components/analytics/system_analytics/system_analytics.jsx
  components/analytics/team_analytics/team_analytics.jsx
  i18n/en.json
  utils/constants.jsx
Labels: 3: Reviews Complete, Do Not Merge/Awaiting PR

#3065 MM-16380, MM-16388 - Updating post navigation and aria-live in the post list
  components/__snapshots__/size_aware_image.test.jsx.snap
  components/common/comment_icon.jsx
  components/dot_menu/__snapshots__/dot_menu.test.jsx.snap
  components/dot_menu/dot_menu.jsx
  components/file_attachment/__snapshots__/file_attachment.test.jsx.snap
  components/file_attachment/__snapshots__/filename_overlay.test.jsx.snap
  components/file_attachment/file_attachment.jsx
  components/file_attachment/filename_overlay.jsx
  components/popover_list_members/__snapshots__/popover_list_members.test.jsx.snap
  components/popover_list_members/popover_list_members.jsx
  components/post_view/post_attachment_opengraph/post_attachment_opengraph.jsx
  components/post_view/post_body_additional_content/__snapshots__/post_body_additional_content.test.jsx.snap
  components/post_view/post_body_additional_content/post_body_additional_content.jsx
  components/post_view/post_flag_icon/__snapshots__/post_flag_icon.test.js.snap
  components/post_view/post_flag_icon/post_flag_icon.js
  components/post_view/post_list_virtualized/post_list_virtualized.jsx
  components/post_view/post_reaction/__snapshots__/post_reaction.test.jsx.snap
  components/post_view/post_reaction/post_reaction.jsx
  components/post_view/reaction/__snapshots__/reaction.test.jsx.snap
  components/post_view/reaction/reaction.jsx
  components/post_view/reaction_list/__snapshots__/reactions_list.test.jsx.snap
  components/post_view/reaction_list/reaction_list.jsx
  components/sidebar/channel_create.jsx
  components/single_image_view/__snapshots__/single_image_view.test.jsx.snap
  components/single_image_view/single_image_view.jsx
  components/size_aware_image.jsx
  components/user_profile/__snapshots__/user_profile.test.jsx.snap
  components/user_profile/user_profile.jsx
  i18n/en.json
  sass/components/_files.scss
  sass/layout/_post.scss
  sass/responsive/_tablet.scss
  sass/utils/_modifiers.scss
  utils/utils.jsx
Labels: 2: Dev Review

#3026 MM-15452 - Add ability to override LHS icon for bot accounts
  components/sidebar/sidebar_channel/index.js
  components/sidebar/sidebar_channel/sidebar_channel.jsx
  components/sidebar/sidebar_channel_button_or_link/sidebar_channel_button_or_link.jsx
  components/sidebar/sidebar_channel_button_or_link/sidebar_channel_button_or_link_icon.jsx
  package-lock.json
  package.json
  sass/layout/_sidebar-left.scss
  utils/utils.jsx
Labels: 2: Dev Review

#3072 Remove beta label from O365 SSO
  components/admin_console/admin_definition.jsx
  i18n/en.json
Labels: 3: Reviews Complete, Docs/Needed

#3076 [MM-16056] Hide add-to-channel option if user in not part of team
  components/profile_popover/__snapshots__/profile_popover.test.jsx.snap
  components/profile_popover/index.js
  components/profile_popover/profile_popover.jsx
  components/profile_popover/profile_popover.test.jsx
Labels: 3: Reviews Complete

#3055 MM-16757: Adds inline public/private text to channel type toggle button.
  components/admin_console/team_channel_settings/channel/details/channel_modes.jsx
  components/admin_console/team_channel_settings/line_switch.jsx
  components/toggle.jsx
  i18n/en.json
  package-lock.json
  sass/components/_toggle.scss
Labels: 3: Reviews Complete

#3075 E2E: add post-verification on Cypress task that the request is successfully completed
  e2e/cypress/integration/at_mentions/at_mentions_spec.js
  e2e/cypress/integration/channel/message_spec.js
  e2e/cypress/integration/interactive_menu/basic_options.js
  e2e/cypress/integration/search/date_filter_spec.js
  e2e/cypress/integration/system_console/demoted_user_spec.js
  e2e/cypress/plugins/post_message_as.js
  e2e/cypress/support/index.js
  e2e/cypress/support/task_commands.js
Labels: 2: Dev Review

#3049 MM-14977 Add bi-directional with loading of last unread post
  actions/views/channel.js
  actions/views/channel.test.js
  components/permalink_view/__snapshots__/permalink_view.test.jsx.snap
  components/post_view/__snapshots__/post_view.test.js.snap
  components/post_view/channel_intro_message/index.js
  components/post_view/index.js
  components/post_view/post_list/__snapshots__/post_list.test.jsx.snap
  components/post_view/post_list/index.js
  components/post_view/post_list/post_list.jsx
  components/post_view/post_list/post_list.test.jsx
  components/post_view/post_list/post_list_virtualized.jsx
  components/post_view/post_list/post_list_virtualized.test.jsx
  components/post_view/post_list_ie/post_list_ie.jsx
  components/post_view/post_list_row/__snapshots__/post_list_row.test.jsx.snap
  components/post_view/post_list_row/post_list_row.jsx
  components/post_view/post_list_row/post_list_row.test.jsx
  components/post_view/post_list_virtualized/index.js
  components/post_view/post_view.jsx
  components/post_view/post_view.test.js
  components/suggestion/at_mention_provider/at_mention_provider.test.jsx
  package-lock.json
  package.json
  utils/constants.jsx
  utils/post_utils.jsx
  utils/post_utils.test.jsx
Labels: 3: Reviews Complete

#3078 [MM-16723] Added aria-label to post components
  components/post_view/post/index.js
  components/post_view/post/post.jsx
  components/rhs_comment/index.js
  components/rhs_comment/rhs_comment.jsx
  components/rhs_root_post/index.js
  components/rhs_root_post/rhs_root_post.jsx
  i18n/en.json
  utils/post_utils.jsx
  utils/post_utils.test.jsx
Labels: 3: Reviews Complete

#3080 translations PR 20190708
  i18n/es.json
  i18n/pt-BR.json
  i18n/tr.json
  i18n/zh-TW.json
Labels: 3: Reviews Complete

#3079 MM-16511 Load missing users who start typing
  actions/websocket_actions.jsx
  actions/websocket_actions.test.jsx
Labels: 2: Dev Review

#3086 MM-16906 - Updating class for size aware images
  components/size_aware_image.jsx
  components/size_aware_image.test.jsx
Labels: 3: Reviews Complete

#3039 Administration permissions and guest account settings
  components/admin_console/admin_definition.jsx
  components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.jsx.snap
  components/admin_console/permission_schemes_settings/guest_permissions_tree/__snapshots__/guest_permissions_tree.test.jsx.snap
  components/admin_console/permission_schemes_settings/guest_permissions_tree/guest_permissions_tree.jsx
  components/admin_console/permission_schemes_settings/guest_permissions_tree/guest_permissions_tree.test.jsx
  components/admin_console/permission_schemes_settings/guest_permissions_tree/index.jsx
  components/admin_console/permission_schemes_settings/permission_system_scheme_settings/__snapshots__/permission_system_scheme_settings.test.jsx.snap
  components/admin_console/permission_schemes_settings/permission_system_scheme_settings/index.jsx
  components/admin_console/permission_schemes_settings/permission_system_scheme_settings/permission_system_scheme_settings.jsx
  components/admin_console/permission_schemes_settings/permission_system_scheme_settings/permission_system_scheme_settings.test.jsx
  components/admin_console/permission_schemes_settings/permissions_tree/permissions_tree.jsx
  i18n/en.json
  sass/components/_permissions.scss
  utils/admin_console_index.test.jsx
Labels: 3: Reviews Complete

#3084 E2E: Fix flaky tests on system message spec and update markdown spec due to latest structure change
  e2e/cypress/integration/markdown/markdown_image_spec.js
  e2e/cypress/integration/multi_team/system_message_spec.js
Labels: 3: Reviews Complete

#3093 MM-16906 Fix styles for size_aware_image component
  components/__snapshots__/size_aware_image.test.jsx.snap
  components/size_aware_image.jsx
  components/size_aware_image.test.jsx
Labels: 3: Reviews Complete

#3091 [MM-15211] Improved User Management (Phase 1)
  components/admin_console/__snapshots__/admin_console.test.jsx.snap
  components/admin_console/admin_button_outline/admin_button_outline.jsx
  components/admin_console/admin_button_outline/admin_button_outline.scss
  components/admin_console/admin_definition.jsx
  components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.jsx.snap
  components/admin_console/admin_user_card/__snapshots__/admin_user_card.test.jsx.snap
  components/admin_console/admin_user_card/admin_user_card.jsx
  components/admin_console/admin_user_card/admin_user_card.scss
  components/admin_console/admin_user_card/admin_user_card.test.jsx
  components/admin_console/system_user_detail/__snapshots__/system_user_detail.test.jsx.snap
  components/admin_console/system_user_detail/index.js
  components/admin_console/system_user_detail/system_user_detail.jsx
  components/admin_console/system_user_detail/system_user_detail.scss
  components/admin_console/system_user_detail/system_user_detail.test.jsx
  components/profile_picture.jsx
  components/user_list.jsx
  components/user_list_row_with_error/user_list_row_with_error.jsx
  i18n/en.json
  package-lock.json
  sass/components/_status-icon.scss
Labels: 3: Reviews Complete

#3088 MM-16803 - Updating post styling
  components/post_view/post_body_additional_content/__snapshots__/post_body_additional_content.test.jsx.snap
  components/post_view/post_body_additional_content/post_body_additional_content.jsx
  sass/layout/_post.scss
  sass/responsive/_mobile.scss
  sass/responsive/_tablet.scss
Labels: 3: Reviews Complete

#3077 MM-16060 Update URL when current channel is renamed
  actions/websocket_actions.jsx
  actions/websocket_actions.test.jsx
Labels: 3: Reviews Complete

#3085 MM-16044 - Updating radio buttons (a11y)
  components/channel_notifications_modal/components/__snapshots__/expand_view.test.jsx.snap
  components/channel_notifications_modal/components/expand_view.jsx
  components/new_channel_modal/__snapshots__/new_channel_modal.test.jsx.snap
  components/new_channel_modal/new_channel_modal.jsx
  components/team_general_tab/team_general_tab.jsx
  components/user_settings/advanced/join_leave_section/__snapshots__/join_leave_section.test.jsx.snap
  components/user_settings/advanced/join_leave_section/join_leave_section.jsx
  components/user_settings/advanced/user_settings_advanced.jsx
  components/user_settings/notifications/__snapshots__/desktop_notification_settings.test.jsx.snap
  components/user_settings/notifications/__snapshots__/manage_auto_responder.test.jsx.snap
  components/user_settings/notifications/desktop_notification_settings.jsx
  components/user_settings/notifications/email_notification_setting/__snapshots__/email_notification_setting.test.jsx.snap
  components/user_settings/notifications/email_notification_setting/email_notification_setting.jsx
  components/user_settings/notifications/manage_auto_responder.jsx
  components/user_settings/notifications/user_settings_notifications.jsx
  components/user_settings/sidebar/__snapshots__/user_settings_sidebar.test.jsx.snap
  components/user_settings/sidebar/user_settings_sidebar.jsx
  sass/layout/_forms.scss
Labels: 3: Reviews Complete

#3099 E2E: Fix flaky test on markdown and team specs
  e2e/cypress/integration/markdown/markdown_image_spec.js
  e2e/cypress/integration/markdown/markdown_text_spec.js
  e2e/cypress/integration/team/teams_spec.js
Labels: 3: Reviews Complete

#3069 Cypress automated test for "Tutorial - Navigation and Links"
  e2e/cypress/integration/login/tutorial_navigation_and_links_spec.js
  e2e/cypress/support/api_commands.js
Labels: 2: Dev Review

#3087 Fix unit test and browser JS warning
  components/channel_selector_modal/channel_selector_modal.test.jsx
  components/post_view/channel_intro_message/channel_intro_message.jsx
  components/post_view/post_list/post_list.test.jsx
Labels: 3: Reviews Complete

#3105 Fixing broken permalinks when access directly to the app
  components/channel_header_dropdown/index.js
Labels: 3: Reviews Complete

#3094 [MM-16533] User deactivation does not work when "Disable bot accounts when owner is deactivated" is set to False
  components/admin_console/system_users/system_users_dropdown/system_users_dropdown.jsx
Labels: 2: Dev Review

#3092 Fix Cypress run script
  e2e/package-lock.json
  e2e/package.json
  e2e/webhook_serve.js
Labels: 2: Dev Review

#3113 MM-16907 White screen when disabling Join/Leave Messages and switching to a specific channel
  components/post_view/post_list_virtualized/index.js
Labels: 3: Reviews Complete

#3058 UX screen review fixes for Admin Console Teams/Channels
  components/add_groups_to_channel_modal/__snapshots__/add_groups_to_channel_modal.test.jsx.snap
  components/add_groups_to_channel_modal/add_groups_to_channel_modal.jsx
  components/add_groups_to_team_modal/__snapshots__/add_groups_to_team_modal.test.jsx.snap
  components/add_groups_to_team_modal/add_groups_to_team_modal.jsx
  components/admin_console/team_channel_settings/abstract_list.jsx
  components/admin_console/team_channel_settings/channel/details/__snapshots__/channel_details.test.jsx.snap
  components/admin_console/team_channel_settings/channel/details/__snapshots__/channel_groups.test.jsx.snap
  components/admin_console/team_channel_settings/channel/details/__snapshots__/channel_modes.test.jsx.snap
  components/admin_console/team_channel_settings/channel/details/__snapshots__/channel_profile.test.jsx.snap
  components/admin_console/team_channel_settings/channel/details/channel_details.jsx
  components/admin_console/team_channel_settings/channel/details/channel_details.test.jsx
  components/admin_console/team_channel_settings/channel/details/channel_groups.jsx
  components/admin_console/team_channel_settings/channel/details/channel_modes.jsx
  components/admin_console/team_channel_settings/channel/details/channel_modes.test.jsx
  components/admin_console/team_channel_settings/channel/details/channel_profile.jsx
  components/admin_console/team_channel_settings/channel/details/channel_profile.test.jsx
  components/admin_console/team_channel_settings/channel/details/index.js
  components/admin_console/team_channel_settings/channel/list/__snapshots__/channel_row.test.jsx.snap
  components/admin_console/team_channel_settings/channel/list/channel_list.jsx
  components/admin_console/team_channel_settings/channel/list/channel_row.jsx
  components/admin_console/team_channel_settings/channel/list/index.js
  components/admin_console/team_channel_settings/errors.jsx
  components/admin_console/team_channel_settings/group/__snapshots__/group_row.test.jsx.snap
  components/admin_console/team_channel_settings/group/__snapshots__/group_users.test.jsx.snap
  components/admin_console/team_channel_settings/group/__snapshots__/group_users_row.test.jsx.snap
  components/admin_console/team_channel_settings/group/group_list.jsx
  components/admin_console/team_channel_settings/group/group_row.jsx
  components/admin_console/team_channel_settings/group/group_users.jsx
  components/admin_console/team_channel_settings/group/group_users_row.jsx
  components/admin_console/team_channel_settings/line_switch.jsx
  components/admin_console/team_channel_settings/team/__snapshots__/team_settings.test.jsx.snap
  components/admin_console/team_channel_settings/team/details/__snapshots__/team_image.test.jsx.snap
  components/admin_console/team_channel_settings/team/details/__snapshots__/team_profile.test.jsx.snap
  components/admin_console/team_channel_settings/team/details/index.js
  components/admin_console/team_channel_settings/team/details/team_details.jsx
  components/admin_console/team_channel_settings/team/details/team_image.jsx
  components/admin_console/team_channel_settings/team/details/team_modes.jsx
  components/admin_console/team_channel_settings/team/details/team_profile.jsx
  components/admin_console/team_channel_settings/team/list/__snapshots__/team_row.test.jsx.snap
  components/admin_console/team_channel_settings/team/list/team_list.jsx
  components/admin_console/team_channel_settings/team/list/team_row.jsx
  components/admin_console/team_channel_settings/team/team_settings.jsx
  components/admin_console/team_channel_settings/users_to_be_removed_modal.jsx
  components/toggle.jsx
  i18n/en.json
  sass/components/_groups.scss
  sass/components/_modal.scss
  sass/components/_module.scss
  sass/components/_team-channel-settings.scss
  sass/layout/_team-button.scss
Labels: 2: Dev Review

#3114 MM-16081 - Updating aria label for team buttons
  components/team_sidebar/components/team_button.jsx
  i18n/en.json
Labels: 2: Dev Review

#3104 Adding the proper link icon in the copy link button
  components/invitation_modal/__snapshots__/invitation_modal_members_step.test.jsx.snap
  components/invitation_modal/invitation_modal_members_step.jsx
  components/invitation_modal/invitation_modal_members_step.scss
  components/svg/link_icon.jsx
  i18n/en.json
Labels: 3: Reviews Complete

#3110 Allow to go back from confirmation screen
  components/invitation_modal/__snapshots__/invitation_modal.test.jsx.snap
  components/invitation_modal/__snapshots__/invitation_modal_confirm_step.test.jsx.snap
  components/invitation_modal/invitation_modal.jsx
  components/invitation_modal/invitation_modal_confirm_step.jsx
  components/invitation_modal/invitation_modal_guests_step.jsx
Labels: 2: Dev Review

#3103 Adding loading spinner to inputs
  components/widgets/inputs/channels_input.jsx
  components/widgets/inputs/users_emails_input.jsx
Labels: 3: Reviews Complete

#3111 Fixing help text of guest invitation users/emails input
  components/invitation_modal/__snapshots__/invitation_modal_guests_step.test.jsx.snap
  components/invitation_modal/invitation_modal_guests_step.jsx
  i18n/en.json
Labels: 3: Reviews Complete

#3108 Fix confirm back/close behavior in the invitation flow modal
  components/invitation_modal/invitation_modal.jsx
  components/invitation_modal/invitation_modal_guests_step.jsx
  components/invitation_modal/invitation_modal_members_step.jsx
Labels: 3: Reviews Complete

#3102 Fixing copy button on invitation flow
  components/get_link_modal.jsx
  components/invitation_modal/__snapshots__/invitation_modal_members_step.test.jsx.snap
  components/invitation_modal/invitation_modal_members_step.jsx
Labels: 3: Reviews Complete

#3082 [MM-16475] Lookup missing user profiles in audit table
  components/audit_table/audit_table.jsx
  components/audit_table/audit_table.test.jsx
  components/audit_table/index.js
Labels: 3: Reviews Complete

#3122 E2E: Update post list content ID
  components/post_view/post_list/__snapshots__/post_list.test.jsx.snap
  components/post_view/post_list/post_list.jsx
Labels: 3: Reviews Complete

#3061 MM-16058 - Making message autocomplete a11y compatible
  components/__snapshots__/textbox.test.jsx.snap
  components/suggestion/search_suggestion_list.jsx
  components/suggestion/suggestion_list.jsx
  components/textbox/textbox.jsx
Labels: 2: Dev Review

#3115 MM-16059 - Updating invite member modal
  components/invite_member_modal/invite_member_modal.jsx
Labels: 2: Dev Review

#3106 MM-16989 Fix for leave team causing a white screen
  components/post_view/index.js
  components/post_view/post_list/post_list.jsx
  components/post_view/post_list/post_list.test.jsx
  components/post_view/post_list/post_list_virtualized.jsx
Labels: 3: Reviews Complete

#3089 MM-16795 - Updating bootstrap tooltips
  components/admin_console/admin_sidebar/admin_sidebar.jsx
  components/admin_console/permission_schemes_settings/permissions_scheme_summary/permissions_scheme_summary.jsx
  components/analytics/table_chart.jsx
  components/announcement_bar/announcement_bar.jsx
  components/change_url_modal/change_url_modal.jsx
  components/channel_header/channel_header.js
  components/common/comment_icon.jsx
  components/copy_text.jsx
  components/create_team/components/team_url/team_url.jsx
  components/file_attachment/__snapshots__/filename_overlay.test.jsx.snap
  components/file_attachment/filename_overlay.jsx
  components/integrations/bots/add_bot/add_bot.jsx
  components/popover_list_members/__snapshots__/popover_list_members.test.jsx.snap
  components/popover_list_members/popover_list_members.jsx
  components/post_view/channel_intro_message/channel_intro_message.jsx
  components/post_view/post_info/post_info.jsx
  components/post_view/post_reaction/__snapshots__/post_reaction.test.jsx.snap
  components/post_view/post_reaction/post_reaction.jsx
  components/post_view/reaction/__snapshots__/reaction.test.jsx.snap
  components/post_view/reaction/reaction.jsx
  components/post_view/reaction_list/reaction_list.jsx
  components/rename_channel_modal/rename_channel_modal.jsx
  components/rhs_card_header/rhs_card_header.jsx
  components/rhs_comment/rhs_comment.jsx
  components/rhs_header_post/rhs_header_post.jsx
  components/rhs_root_post/rhs_root_post.jsx
  components/search_bar/search_bar.jsx
  components/search_results_header/search_results_header.jsx
  components/search_results_item/search_results_item.jsx
  components/select_team/components/__snapshots__/select_team_item.test.jsx.snap
  components/select_team/components/select_team_item.jsx
  components/setting_picture.jsx
  components/sidebar/channel_create.jsx
  components/sidebar/header/sidebar_header_dropdown_button.jsx
  components/sidebar/sidebar_channel_button_or_link/sidebar_channel_button_or_link.jsx
  components/sidebar/sidebar_channel_button_or_link/sidebar_channel_button_or_link_close_button.jsx
  components/team_sidebar/components/team_button.jsx
  components/user_settings/display/user_settings_theme/custom_theme_chooser.jsx
  sass/layout/_sidebar-left.scss
Labels: 3: Reviews Complete

#3116 MM-16133 - Updating form submission for select
  components/setting_item_max.jsx
  components/setting_item_max.test.jsx
  components/user_settings/display/manage_languages/manage_languages.jsx
Labels: 3: Reviews Complete

#3127 [MM-17003] Fix stuck up/down arrow keys in modals
  utils/a11y_controller.js
Labels: 2: Dev Review

#3123 [MM-16039] Updated react-bootstrap commit
  package-lock.json
  package.json
Labels: 2: Dev Review

#3118 MM-16941 - Adding focus-trap to elements
  components/emoji_picker/emoji_picker_tabs.jsx
  components/widgets/menu/menu.jsx
  components/widgets/menu/menu.test.jsx
  components/widgets/menu/menu_wrapper.jsx
  package-lock.json
  package.json
Labels: 3: Reviews Complete

#3112 [MM-16043] Auto focus first interactable element on settings modal
  components/setting_item_max.jsx
Labels: 1: PM Review, Setup Cloud Test Server

#3128 MM-17007 Fix IE11 crash with channel prop error
  components/post_view/post_list_ie/index.js
Labels: 3: Reviews Complete

#3064 [MM-14018] Ignore leading/trailing colon in emoji picker search
  components/emoji_picker/emoji_picker.jsx
  components/emoji_picker/emoji_picker.test.jsx
Labels: 3: Reviews Complete

#3131 Removing focus trap on menu item click
  components/widgets/menu/menu.jsx
  components/widgets/menu/menu.test.jsx
Labels: 2: Dev Review

#3132 Revert "MM-16989 Fix for leave team causing a white screen"
  components/post_view/index.js
  components/post_view/post_list/post_list.jsx
  components/post_view/post_list/post_list.test.jsx
  components/post_view/post_list/post_list_virtualized.jsx
Labels: 3: Reviews Complete

#3124 Address flakiness in search date filter e2e tests
  e2e/cypress/integration/search/date_filter_spec.js
Labels: 2: Dev Review

#3120 fix failing e2e post header specs
  e2e/cypress/integration/post_header/post_header_spec.js
Labels: 2: Dev Review

#3119 Clear all cookies after clearing specific cookies
  e2e/cypress/support/api_commands.js
Labels: 2: Dev Review

#3133 MM-16952 Fix for new message bubble popping up even when at bottom
  package-lock.json
  package.json
Labels: 3: Reviews Complete

#3121 Fix failing test with interactive menus
  e2e/cypress.json
  e2e/cypress/integration/interactive_menu/basic_options.js
  e2e/cypress/plugins/index.js
  e2e/cypress/utils/index.js
Labels: 2: Dev Review

#3100 [MM-16041] Added aria-labels to account settings inputs
  components/__snapshots__/setting_item_max.test.jsx.snap
  components/setting_item_max.jsx
  components/user_settings/general/user_settings_general.jsx
  components/user_settings/notifications/__snapshots__/manage_auto_responder.test.jsx.snap
  components/user_settings/notifications/email_notification_setting/__snapshots__/email_notification_setting.test.jsx.snap
  components/user_settings/notifications/user_settings_notifications.jsx
  components/user_settings/security/user_settings_security.jsx
Labels: 3: Reviews Complete

#3135 [MM-16534] if user has bots, but the bots are disabled, don't show warning that bots will be disabled
  components/admin_console/system_users/system_users_dropdown/__snapshots__/system_users_dropdown.test.js.snap
  components/admin_console/system_users/system_users_dropdown/system_users_dropdown.jsx
  components/admin_console/system_users/system_users_dropdown/system_users_dropdown.test.js
Labels: 2: Dev Review

#3126 Fixing email invitations disabled problem
  actions/invite_actions.jsx
  components/post_view/channel_intro_message/channel_intro_message.jsx
Labels: 3: Reviews Complete

#3140 MM-16907 Fix for White screen when disabling Join/Leave Messages and switching to a specific channel
  components/post_view/post_list_virtualized/index.js
  components/post_view/post_list_virtualized/post_list_virtualized.jsx
  components/post_view/post_list_virtualized/post_list_virtualized.test.jsx
Labels: 3: Reviews Complete

#3138 harden rhs sidebar to a plugin reinstall
  plugins/rhs_plugin/index.js
Labels: 3: Reviews Complete

#3095 [MM-16804] Bot profile image disappears when saving bot details
  components/integrations/bots/add_bot/add_bot.jsx
Labels: 2: Dev Review

#3141 small fixes for failing tests
  e2e/cypress/integration/channel/message_reaction_spec.js
  e2e/cypress/support/ui_commands.js
Labels: 3: Reviews Complete

#3145 Revert "[PLT-4951] Don't send notifications if thread is showing in RHS"
  actions/notification_actions.jsx
  actions/notification_actions.test.jsx
  actions/post_utils.js
  actions/post_utils.test.js
Labels: 2: Dev Review

#3117 MM-15999 - More channels dialog a11y compatible
  components/__snapshots__/searchable_channel_list.test.jsx.snap
  components/searchable_channel_list.jsx
  sass/components/_modal.scss
Labels: 3: Reviews Complete

#3143 Polishing details in invitation flow styles
  components/invitation_modal/invitation_modal.scss
  components/invitation_modal/invitation_modal_confirm_step.scss
  components/invitation_modal/invitation_modal_confirm_step_row.scss
  components/invitation_modal/invitation_modal_confirm_step_table.scss
  components/invitation_modal/invitation_modal_guests_step.jsx
  components/invitation_modal/invitation_modal_guests_step.scss
  components/invitation_modal/invitation_modal_members_step.jsx
  components/invitation_modal/invitation_modal_members_step.scss
  components/widgets/inputs/channels_input.scss
  components/widgets/inputs/emails_input.scss
  components/widgets/inputs/users_emails_input.scss
  components/widgets/modals/full_screen_modal.scss
Labels: 3: Reviews Complete

#3139 MM-15888 Add E2E for interactive dialogs
  components/interactive_dialog/interactive_dialog.jsx
  e2e/cypress/integration/interactive_dialog/interactive_dialog_spec.js
  e2e/cypress/support/api_commands.js
  e2e/utils/webhook_utils.js
  e2e/webhook_serve.js
Labels: 2: Dev Review

#3144 [MM-17003] Only trap a11y keyboard events when needed
  utils/a11y_controller.js
Labels: 3: Reviews Complete

#3130 Mochawesome reporting
  .eslintignore
  .gitignore
  e2e/cypress.json
  e2e/cypress/support/index.js
  e2e/package-lock.json
  e2e/package.json
  e2e/run_tests.js
Labels: 3: Reviews Complete

#3146 Adding header warning for guests in channels
  components/channel_header/channel_header.js
  components/channel_header/index.js
  i18n/en.json
  sass/layout/_headers.scss
Labels: 3: Reviews Complete

#3096 MM-16924 Fix to load more posts automatically if new messages loader is above the fold
  components/post_view/post_list/post_list.jsx
  components/post_view/post_list/post_list.test.jsx
  components/post_view/post_list/post_list_virtualized.jsx
  components/post_view/post_list/post_list_virtualized.test.jsx
Labels: 3: Reviews Complete

#3148 MM-17008: Always displays 'Push Notification Contents' admin console …
  components/admin_console/admin_definition.jsx
Labels: 3: Reviews Complete, CherryPick/Approved

#3149 Automated cherry pick of
  components/admin_console/admin_definition.jsx
Labels: AutomatedCherryPick/Done

#3136 MM-16082, MM-16382, MM-17057 - Updating a11y navigation post create
  components/__snapshots__/autosize_textarea.test.jsx.snap
  components/__snapshots__/textbox.test.jsx.snap
  components/autosize_textarea.jsx
  components/create_comment/__snapshots__/create_comment.test.jsx.snap
  components/create_comment/create_comment.jsx
  components/create_post/__snapshots__/create_post.test.jsx.snap
  components/create_post/create_post.jsx
  components/create_post/create_post.test.jsx
  components/edit_post_modal/__snapshots__/edit_post_modal.test.jsx.snap
  components/edit_post_modal/edit_post_modal.jsx
  components/edit_post_modal/edit_post_modal.test.jsx
  components/emoji_picker/emoji_picker_tabs.jsx
  components/file_upload/__snapshots__/file_upload.test.jsx.snap
  components/file_upload/file_upload.jsx
  components/post_view/post_list/post_list_virtualized.jsx
  components/textbox/textbox.jsx
  components/textbox/textbox_links.jsx
  components/user_settings/notifications/__snapshots__/manage_auto_responder.test.jsx.snap
  i18n/en.json
  sass/components/_admin-sidebar-header.scss
  sass/components/_files.scss
  sass/components/_modal.scss
  sass/layout/_post.scss
  sass/layout/_sidebar-right.scss
  sass/responsive/_mobile.scss
  utils/utils.jsx
Labels: Setup Cloud Test Server

#3153 MM-16937 - Updating padding for channel intro
  sass/layout/_headers.scss
Labels: 3: Reviews Complete, CherryPick/Approved

#3129 [MM-16645] Added IE11 deprecation notice for v5.16
  components/system_notice/notices.jsx
  i18n/en.json
  utils/server_version.jsx
  utils/server_version.test.jsx
Labels: 3: Reviews Complete, CherryPick/Approved

#3160 Automated cherry pick of #3153
  sass/layout/_headers.scss
Labels: AutomatedCherryPick/Done

#3158 Fixing guest disabled on invitation modal
  components/invitation_modal/index.js
Labels: 3: Reviews Complete

#3162 bump lodash
  e2e/package-lock.json
  e2e/package.json
Labels: 2: Dev Review

#3163 MM-17047 - Making post text focusable
  components/post_view/post_message_view/__snapshots__/post_message_view.test.jsx.snap
  components/post_view/post_message_view/post_message_view.jsx
  plugins/test/__snapshots__/post_type.test.jsx.snap
  utils/utils.jsx
Labels: 3: Reviews Complete, CherryPick/Approved

#3151 Update Enable Link Preview console help text
  components/admin_console/admin_definition.jsx
  i18n/en.json
Labels: 3: Reviews Complete, CherryPick/Approved

#3101 [MM-16042] Added aria-labels to profile picture settings buttons
  components/__snapshots__/setting_picture.test.jsx.snap
  components/setting_picture.jsx
  sass/routes/_settings.scss
Labels: 3: Reviews Complete, CherryPick/Approved

#3168 [MM-16054] Accessibility fixes for Manage Members for channel
  components/channel_members_dropdown/channel_members_dropdown.jsx
  components/searchable_user_list/searchable_user_list.jsx
Labels: 3: Reviews Complete, CherryPick/Approved

#3171 Automated cherry pick of #3151
  components/admin_console/admin_definition.jsx
  i18n/en.json
Labels: AutomatedCherryPick/Done

#3164 [MM-16053] Accessibility fixes for Add Members to Team
  components/add_users_to_team/__snapshots__/add_users_to_team.test.jsx.snap
  components/add_users_to_team/add_users_to_team.jsx
  components/channel_invite_modal/__snapshots__/channel_invite_modal.test.jsx.snap
  components/channel_invite_modal/channel_invite_modal.jsx
  components/multiselect/__snapshots__/multiselect.test.jsx.snap
  components/multiselect/multiselect.jsx
  components/multiselect/multiselect_list.jsx
Labels: 3: Reviews Complete, CherryPick/Approved

#3142 [MM-16087] Accessibility changes for the emoji picker
  components/create_comment/create_comment.jsx
  components/create_post/create_post.jsx
  components/emoji_picker/components/emoji_picker_category.jsx
  components/emoji_picker/components/emoji_picker_item.jsx
  components/emoji_picker/emoji_picker.jsx
  i18n/en.json
Labels: 2: Dev Review, 3: Reviews Complete, CherryPick/Approved

#3090 [MM-16723] Added emoji support to post aria-label
  components/post_view/post/post.jsx
  components/rhs_comment/rhs_comment.jsx
  components/rhs_root_post/rhs_root_post.jsx
  utils/post_utils.jsx
  utils/post_utils.test.jsx
Labels: 3: Reviews Complete, CherryPick/Approved

#3161 Automated cherry pick of #3129
  components/system_notice/notices.jsx
  i18n/en.json
  utils/server_version.jsx
  utils/server_version.test.jsx
Labels: AutomatedCherryPick/Done

#3177 Automated cherry pick of #3090
  components/post_view/post/post.jsx
  components/rhs_comment/rhs_comment.jsx
  components/rhs_root_post/rhs_root_post.jsx
  utils/post_utils.jsx
  utils/post_utils.test.jsx
Labels: AutomatedCherryPick/Done

#3175 Automated cherry pick of #3164
  components/add_users_to_team/__snapshots__/add_users_to_team.test.jsx.snap
  components/add_users_to_team/add_users_to_team.jsx
  components/channel_invite_modal/__snapshots__/channel_invite_modal.test.jsx.snap
  components/channel_invite_modal/channel_invite_modal.jsx
  components/multiselect/__snapshots__/multiselect.test.jsx.snap
  components/multiselect/multiselect.jsx
  components/multiselect/multiselect_list.jsx
Labels: AutomatedCherryPick/Done

#3174 Automated cherry pick of #3168
  components/channel_members_dropdown/channel_members_dropdown.jsx
  components/searchable_user_list/searchable_user_list.jsx
Labels: AutomatedCherryPick/Done

#3172 Automated cherry pick of #3101
  components/__snapshots__/setting_picture.test.jsx.snap
  components/setting_picture.jsx
  sass/routes/_settings.scss
Labels: AutomatedCherryPick/Done

#3176 [MM-16057] Accessibility changes for Direct Messages modal
  components/more_direct_channels/__snapshots__/more_direct_channels.test.jsx.snap
  components/more_direct_channels/more_direct_channels.jsx
Labels: 3: Reviews Complete, CherryPick/Approved

#3178 Automated cherry pick of #3176
  components/more_direct_channels/__snapshots__/more_direct_channels.test.jsx.snap
  components/more_direct_channels/more_direct_channels.jsx
Labels: AutomatedCherryPick/Done

#3173 [MM-17086] Don’t run a11y navigation in IE11
  components/root/root.jsx
Labels: 3: Reviews Complete, CherryPick/Approved

#3159 MM-16916 - Updating dot menu tooltip trigger
  components/dot_menu/__snapshots__/dot_menu.test.jsx.snap
  components/dot_menu/dot_menu.jsx
Labels: 3: Reviews Complete, CherryPick/Approved

#3180 Automated cherry pick of #3169
  utils/a11y_controller.js
Labels: AutomatedCherryPick/Done

#3179 Automated cherry pick of #3173
  components/root/root.jsx
Labels: AutomatedCherryPick/Done

#3181 Automated cherry pick of #3159
  components/dot_menu/__snapshots__/dot_menu.test.jsx.snap
  components/dot_menu/dot_menu.jsx
Labels: AutomatedCherryPick/Done

#3050 build: add webpack-dev-server and enable HMR for development
  .babelrc
  Makefile
  components/app.jsx
  package-lock.json
  package.json
  root.html
  root.jsx
  webpack.config.js
Labels: 3: Reviews Complete

#3182 Fix failing E2E test due to recent DOM structure change
  components/file_upload/__snapshots__/file_upload.test.jsx.snap
  components/file_upload/file_upload.jsx
  e2e/cypress/integration/channel/message_draft_with_attachment_then_switch_channel_spec.js
  e2e/cypress/integration/channel/message_edit_post_with_attachment_spec.js
  e2e/cypress/support/ui_commands.js
Labels: 2: Dev Review

#3167 Add invite guest permission to the admin console
  components/admin_console/permission_schemes_settings/permission_schemes_settings.jsx
  components/admin_console/permission_schemes_settings/permissions_tree/permissions_tree.jsx
  i18n/en.json
Labels: 3: Reviews Complete

#3156 MM-17014 - Updating reactions alignment
  sass/layout/_post.scss
Labels: 2: Dev Review, CherryPick/Approved

#3150 More style fixes
  actions/invite_actions.jsx
  components/admin_console/admin_definition.jsx
  components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.jsx.snap
  components/invitation_modal/__snapshots__/invitation_modal_guests_step.test.jsx.snap
  components/invitation_modal/invitation_modal_confirm_step.scss
  components/invitation_modal/invitation_modal_guests_step.jsx
  components/invitation_modal/invitation_modal_guests_step.scss
  components/invitation_modal/invitation_modal_initial_step.scss
  components/invitation_modal/invitation_modal_members_step.scss
  components/svg/close_circle_solid_icon.jsx
  components/widgets/inputs/channels_input.scss
  components/widgets/inputs/emails_input.scss
  components/widgets/inputs/users_emails_input.scss
  i18n/en.json
Labels: 3: Reviews Complete

#3184 Some more fixes to bugs found by QA
  actions/invite_actions.jsx
  components/invitation_modal/invitation_modal.jsx
  components/invitation_modal/invitation_modal.scss
  components/invitation_modal/invitation_modal_confirm_step_table.scss
Labels: 3: Reviews Complete

#3155 MM-16991 - Updating LHS category header weight
  sass/layout/_sidebar-left.scss
Labels: 3: Reviews Complete, CherryPick/Approved

#3170 Automated cherry pick of #3163
  components/post_view/post_message_view/__snapshots__/post_message_view.test.jsx.snap
  components/post_view/post_message_view/post_message_view.jsx
  plugins/test/__snapshots__/post_type.test.jsx.snap
  utils/utils.jsx
Labels: AutomatedCherryPick/Done

#3187 Automated cherry pick of #3155
  sass/layout/_sidebar-left.scss
Labels: AutomatedCherryPick/Done

#3074 [MM-16389] Add emoji icon for profile pictures from webhooks
  components/__snapshots__/profile_picture.test.jsx.snap
  components/add_users_to_team/__snapshots__/add_users_to_team.test.jsx.snap
  components/admin_console/admin_user_card/__snapshots__/admin_user_card.test.jsx.snap
  components/more_direct_channels/__snapshots__/more_direct_channels.test.jsx.snap
  components/post_profile_picture/post_profile_picture.jsx
  components/profile_picture.jsx
  components/profile_picture.test.jsx
  sass/layout/_post.scss
Labels: 3: Reviews Complete, CherryPick/Approved

#3194 Generate short summary to easily pickup for reporting
  e2e/run_tests.js
Labels: 3: Reviews Complete

#3033 [MM-7854] Revoke all sessions from all users (front)
  components/admin_console/system_users/__snapshots__/system_users.test.jsx.snap
  components/admin_console/system_users/index.js
  components/admin_console/system_users/system_users.jsx
  components/admin_console/system_users/system_users.test.jsx
  i18n/en.json
  i18n/es.json
  sass/routes/_admin-console.scss
Labels: 3: Reviews Complete

#3192 MM-17058 - Updating custom theme section css
  components/user_settings/display/user_settings_theme/__snapshots__/custom_theme_chooser.test.jsx.snap
  components/user_settings/display/user_settings_theme/custom_theme_chooser.jsx
  sass/routes/_settings.scss
Labels: 3: Reviews Complete, CherryPick/Approved

#3191 Fix missing message
  i18n/en.json
Labels: 3: Reviews Complete

#3196 MM-16989 Fix for leave team causing blank screen
  components/post_view/index.js
  components/post_view/index.test.js
  components/post_view/post_list/index.js
  components/post_view/post_list/post_list.jsx
  components/post_view/post_list/post_list.test.jsx
  components/post_view/post_list/post_list_virtualized.jsx
Labels: 3: Reviews Complete, CherryPick/Approved

#3198 MM-17114: Associate Amazon SSE to Compliance feature flag and hide options.
  components/admin_console/admin_definition.jsx
  components/admin_console/schema_admin_settings.jsx
Labels: 3: Reviews Complete, CherryPick/Approved

#3152 Added test SC17020 - Revoke All Sessions from System Console
  components/confirm_modal.jsx
  e2e/cypress/integration/system_console/revoke_all_sessions.js
Labels: 3: Reviews Complete

#3197 [MM-16379 cont.] A11y controller updates
  utils/a11y_controller.js
  utils/constants.jsx
Labels: 3: Reviews Complete, CherryPick/Approved

#3157 CSS fixes team/channel admin console
  components/admin_console/team_channel_settings/channel/details/channel_modes.jsx
  components/admin_console/team_channel_settings/line_switch.jsx
  components/toggle.jsx
  i18n/en.json
  sass/components/_toggle.scss
Labels: 2: Dev Review

#3154 MM-16985 - Updating integrations UI item title
  components/integrations/__snapshots__/installed_command.test.jsx.snap
  components/integrations/__snapshots__/installed_incoming_webhook.test.jsx.snap
  components/integrations/__snapshots__/installed_outgoing_webhook.test.jsx.snap
  components/integrations/installed_command.jsx
  components/integrations/installed_incoming_webhook.jsx
  components/integrations/installed_oauth_app/__snapshots__/installed_oauth_app.test.jsx.snap
  components/integrations/installed_oauth_app/installed_oauth_app.jsx
  components/integrations/installed_outgoing_webhook.jsx
Labels: 3: Reviews Complete, CherryPick/Approved

#3210 Automated cherry pick of #3154
  components/integrations/__snapshots__/installed_command.test.jsx.snap
  components/integrations/__snapshots__/installed_incoming_webhook.test.jsx.snap
  components/integrations/__snapshots__/installed_outgoing_webhook.test.jsx.snap
  components/integrations/installed_command.jsx
  components/integrations/installed_incoming_webhook.jsx
  components/integrations/installed_oauth_app/__snapshots__/installed_oauth_app.test.jsx.snap
  components/integrations/installed_oauth_app/installed_oauth_app.jsx
  components/integrations/installed_outgoing_webhook.jsx
Labels: AutomatedCherryPick/Done

#3208 MM-17128 Fix for JavaScript error when posting: Cannot read property 'override_icon_url' of undefined
  actions/views/create_comment.jsx
  components/create_post/create_post.jsx
  components/post_profile_picture/post_profile_picture.jsx
Labels: 2: Dev Review, CherryPick/Approved

#3204 MM-17078 Fix for scroll position with unreads between 30-60
  components/post_view/post_list_virtualized/post_list_virtualized.jsx
  package-lock.json
  package.json
Labels: 3: Reviews Complete, CherryPick/Approved

#3214 Fixing badge positioning in @ suggestions and ctrl k switcher
  components/suggestion/at_mention_provider/at_mention_suggestion.jsx
  components/suggestion/generic_user_provider.jsx
Labels: 3: Reviews Complete, CherryPick/Approved

#3213 Do not enforce MFA for guests when the Guests specific setting is not enabled
  utils/route.jsx
Labels: 3: Reviews Complete, CherryPick/Approved

#3215 Align badges on dms and gms title
  sass/layout/_headers.scss
Labels: 3: Reviews Complete, CherryPick/Approved
