Repository mattermost/mattermost-webapp, pull requests merged in 2019-11, with the labels that each got.

#3578 MM-17059 Add line number to code blocks
  sass/layout/_markdown.scss
  utils/markdown/renderer.jsx
  utils/syntax_highlighting.jsx
Labels: 3: Reviews Complete, QA Review Done

#3785 [MM-18074] Format of Position in User Profile is incorrect
  components/admin_console/admin_user_card/admin_user_card.scss
  components/admin_console/system_user_detail/system_user_detail.scss
Labels: 3: Reviews Complete, QA Review Done, Setup Cloud Test Server, Tests/Not Needed

#4052 [MM-17379] Fixed Management text
  components/admin_console/team_channel_settings/team/list/__snapshots__/team_row.test.jsx.snap
  components/admin_console/team_channel_settings/team/list/team_row.jsx
  i18n/en.json
Labels: 3: Reviews Complete, QA Review Done

#3619 generated texts from the plugin settings and passed the same to gener…
  components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.jsx.snap
  components/admin_console/admin_sidebar/admin_sidebar.jsx
  components/admin_console/admin_sidebar/admin_sidebar.test.jsx
  components/admin_console/custom_plugin_settings/enable_plugin_setting.js
  components/admin_console/custom_plugin_settings/index.js
  tests/helpers/admin_console_plugin_index_sample_pluings.js
  utils/__snapshots__/admin_console_plugin_index.test.js.snap
  utils/admin_console_index.jsx
  utils/admin_console_index.test.jsx
  utils/admin_console_plugin_index.js
  utils/admin_console_plugin_index.test.js
Labels: 3: Reviews Complete, QA Review Done

#4111 MM-19854 - Updating RHS Menu on mobile
  sass/responsive/_mobile.scss
Labels: 2: QA Review, CherryPick/Approved

#3884 [GH 12461] Convert `multiselect` and `multiselect_list` to typescript
  components/add_groups_to_channel_modal/add_groups_to_channel_modal.jsx
  components/add_groups_to_channel_modal/add_groups_to_channel_modal.test.jsx
  components/add_groups_to_team_modal/add_groups_to_team_modal.jsx
  components/add_groups_to_team_modal/add_groups_to_team_modal.test.jsx
  components/channel_invite_modal/channel_invite_modal.jsx
  components/channel_invite_modal/channel_invite_modal.test.jsx
  components/channel_selector_modal/channel_selector_modal.jsx
  components/more_direct_channels/__snapshots__/more_direct_channels.test.jsx.snap
  components/more_direct_channels/more_direct_channels.jsx
  components/more_direct_channels/more_direct_channels.test.jsx
  components/multiselect/__snapshots__/multiselect.test.tsx.snap
  components/multiselect/multiselect.test.tsx
  components/multiselect/multiselect.tsx
  components/multiselect/multiselect_list.tsx
  components/save_button.tsx
  components/team_selector_modal/__snapshots__/team_selector_modal.test.jsx.snap
  components/team_selector_modal/team_selector_modal.jsx
  components/team_selector_modal/team_selector_modal.test.jsx
  package-lock.json
  package.json
Labels: 3: Reviews Complete, Hacktoberfest, QA Review Done, Tests/Not Needed

#4109 MM-19844 - Disallow plugin upload when PluginSettings.RequirePluginSignature is true
  components/admin_console/plugin_management/__snapshots__/plugin_management.test.jsx.snap
  components/admin_console/plugin_management/plugin_management.jsx
  components/admin_console/plugin_management/plugin_management.test.jsx
  i18n/en.json
Labels: 2: QA Review, Docs/Needed

#4113 Automated cherry pick of #4111
  sass/responsive/_mobile.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4098 MM-19738 - Reply counts sometimes missing on Community Daily
  components/post_view/post_list/post_list.jsx
  components/post_view/post_list/post_list.test.jsx
Labels: 3: Reviews Complete, QA Review Done

#4034 Use React lazy and Suspense instead of bundle-loader and AsyncComponent
  components/app.jsx
  components/async_load.jsx
  components/header_footer_template_route.jsx
  components/needs_team/needs_team.jsx
  components/root/root.jsx
  components/team_settings_modal/__snapshots__/team_settings_modal.test.jsx.snap
  components/team_settings_modal/team_settings_modal.jsx
  components/user_settings/modal/user_settings_modal.jsx
  components/view_image/view_image.jsx
  package.json
Labels: 3: Reviews Complete, Hacktoberfest, QA Review Done

#3962 MM-18761 Emoji picker hover effect should match the hover effect on post action menu items
  utils/utils.jsx
Labels: 3: Reviews Complete, QA Review Done

#4120 [MM-8744] Prefetch settings modal during browser idle time
  components/user_settings/modal/user_settings_modal.jsx
Labels: 3: Reviews Complete, QA Review Done

#4058 MM-18962 - Migrate 'components/link_tooltip' module and associated tests to TypeScript
  components/link_tooltip/__snapshots__/link_tooltip.test.tsx.snap
  components/link_tooltip/link_tooltip.test.tsx
  components/link_tooltip/link_tooltip.tsx
Labels: Hacktoberfest, QA Review Done

#4114 [GH-12993] Migrate 'components/admin_console/setting.jsx' and associated tests to TypeScript
  components/admin_console/boolean_setting.jsx
  components/admin_console/color_setting.tsx
  components/admin_console/dropdown_setting.jsx
  components/admin_console/file_upload_setting.jsx
  components/admin_console/multiselect_settings.jsx
  components/admin_console/password_settings.jsx
  components/admin_console/radio_setting.jsx
  components/admin_console/remove_file_setting.jsx
  components/admin_console/setting.tsx
  components/admin_console/user_autocomplete_setting.jsx
Labels: 2: Dev Review, 2: QA Review

#4103 MM-18641 - Updating loading indicator for files
  components/__snapshots__/size_aware_image.test.jsx.snap
  components/size_aware_image.jsx
  sass/components/_files.scss
Labels: 2: Dev Review, QA Review Done, Setup Cloud Test Server

#4053 Remove intl polyfill
  NOTICE.txt
  components/root/root.jsx
  i18n/i18n.jsx
  package-lock.json
  package.json
Labels: 3: Reviews Complete, Hacktoberfest, QA Review Done

#4043 [MM-18777] remove deprecated lifecycle methods in channel settings
  components/edit_channel_purpose_modal/__snapshots__/edit_channel_purpose_modal.test.jsx.snap
  components/edit_channel_purpose_modal/edit_channel_purpose_modal.jsx
  components/edit_channel_purpose_modal/edit_channel_purpose_modal.test.jsx
  components/edit_channel_purpose_modal/index.js
  components/member_list_channel/member_list_channel.jsx
  components/popover_list_members/popover_list_members.jsx
  components/rename_channel_modal/rename_channel_modal.jsx
  components/rename_channel_modal/rename_channel_modal.test.jsx
Labels: 3: Reviews Complete, Hacktoberfest, QA Review Done

#3867 MM-16860 Support Guest Authentication via SAML
  components/admin_console/admin_definition.jsx
  i18n/en.json
Labels: 3: Reviews Complete

#4121 Fixed few flaky tests
  e2e/cypress/integration/channel/add_users_to_channel_spec.js
  e2e/cypress/integration/channel/channel_name_tooltips_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/guest_removal_ui_spec.js
  e2e/cypress/integration/messaging/focus_move_spec.js
Labels: 3: Reviews Complete, QA Review Done

#4064 Bump redux and fix CI
  components/user_settings/display/user_settings_theme/__snapshots__/custom_theme_chooser.test.jsx.snap
  package-lock.json
  package.json
Labels: 2: Dev Review

#3601 Use dark semi-transparent border for code blocks for compatibility with dark and light themes
  sass/layout/_markdown.scss
Labels: 3: Reviews Complete, QA Review Done

#4039 components/pdf_preview: fix embeded download link
  components/pdf_preview.jsx
Labels: 3: Reviews Complete, Hacktoberfest, QA Review Done

#4022 Remove channel memberships when a user is removed from a team
  actions/websocket_actions.jsx
  actions/websocket_actions.test.jsx
Labels: 3: Reviews Complete, CherryPick/Done, QA Review Done

#4128 MM-19142 - Update webapp dependencies
  .eslintrc.json
  .storybook/webpack.config.js
  components/analytics/doughnut_chart.tsx
  components/analytics/format.tsx
  components/color_input.test.tsx
  components/color_input.tsx
  components/copy_url_context_menu/__snapshots__/copy_url_context_menu.test.jsx.snap
  components/error_page/error_page.tsx
  components/multiselect/multiselect.test.tsx
  components/multiselect/multiselect_list.tsx
  components/select_team/components/__snapshots__/select_team_item.test.jsx.snap
  components/widgets/admin_console/admin_header.test.tsx
  components/widgets/admin_console/admin_header.tsx
  package-lock.json
  package.json
  utils/browser_history.jsx
  utils/server_version.tsx
  utils/url.tsx
  webpack.config.js
Labels: 3: Reviews Complete, QA Review Done

#4101 [GH-12977] Migrate 'components/admin_console/generated_settings.jsx' and associated tests to TypeScript
  components/admin_console/generated_setting.tsx
  components/admin_console/schema_admin_settings.jsx
Labels: Hacktoberfest, QA Review Done, Tests/Not Needed

#4134 [MM 19901] Fix keyboard navigation sorting of RHS posts
  components/rhs_comment/rhs_comment.jsx
  components/rhs_root_post/__snapshots__/rhs_root_post.test.jsx.snap
  components/rhs_root_post/rhs_root_post.jsx
  components/rhs_thread/rhs_thread.jsx
  components/search_results/search_results.jsx
  components/search_results_item/search_results_item.jsx
  utils/a11y_controller.js
Labels: 3: Reviews Complete, CherryPick/Done, QA Review Done

#4078 MM-19586 Fix accessibility issues in post list
  components/local_date_time/local_date_time.tsx
  components/post_view/post/post.jsx
  components/post_view/post_attachment_opengraph/post_attachment_opengraph.jsx
  components/post_view/post_attachment_opengraph/post_attachment_opengraph.test.js
  components/post_view/post_list/__snapshots__/post_list.test.jsx.snap
  components/post_view/post_list/post_list.jsx
  components/post_view/post_list/post_list_virtualized.jsx
  components/post_view/post_view.jsx
  e2e/cypress/integration/account_settings/display/channel_display_mode_spec.js
  e2e/cypress/integration/channel/edit_message_spec.js
  e2e/cypress/integration/channel/message_reply_spec.js
  e2e/cypress/integration/channel/message_spec.js
Labels: 3: Reviews Complete, QA Review Done, Tests/Not Needed

#4077 MM-19586 Fix accessibility issues with SVG icons
  components/widgets/icons/member_icon.jsx
  components/widgets/icons/plugin_channel_header_icon.jsx
  plugins/channel_header_plug/__snapshots__/channel_header_plug.test.jsx.snap
Labels: 3: Reviews Complete, QA Review Done, Tests/Not Needed

#4141 Reverting pdfjs-dist version.
  package-lock.json
  package.json
Labels: 3: Reviews Complete

#4117 Remove utils.displayTime in favour of FormattedTime component
  components/admin_console/license_settings/license_settings.jsx
  utils/utils.jsx
Labels: 3: Reviews Complete, QA Review Done

#4099 [GH-12976] Migrate 'components/admin_console/admin_settings.jsx' and associated tests to TypeScript
  components/admin_console/__snapshots__/message_export_settings.test.jsx.snap
  components/admin_console/admin_settings.jsx
  components/admin_console/admin_settings.tsx
  components/admin_console/cluster_settings.jsx
  components/admin_console/custom_terms_of_service_settings/__snapshots__/custom_terms_of_service_settings.test.jsx.snap
  components/admin_console/custom_terms_of_service_settings/custom_terms_of_service_settings.jsx
  components/admin_console/data_retention_settings.jsx
  components/admin_console/database_settings.jsx
  components/admin_console/elasticsearch_settings.jsx
  components/admin_console/message_export_settings.jsx
  components/admin_console/password_settings.jsx
  components/admin_console/plugin_management/__snapshots__/plugin_management.test.jsx.snap
  components/admin_console/plugin_management/plugin_management.jsx
  components/admin_console/push_settings.jsx
Labels: 3: Reviews Complete, Hacktoberfest, QA Review Done, Tests/Not Needed

#4025 E2E: Initial test setup for reusable component
  e2e/cypress.json
  e2e/cypress/integration/widgets/badges/regular_spec.js
  e2e/cypress/support/index.js
  e2e/cypress/support/storybook_commands.js
Labels: 2: Dev Review, QA Review Done, Tests/Not Needed

#4123 Fix storybook for master branch
  .circleci/config.yml
Labels: 3: Reviews Complete, Tests/Not Needed

#4115 webpack: proxy HTTP requests made for plugins' HTTP APIs to mattermost-server
  webpack.config.js
Labels: 3: Reviews Complete

#4122 [MM-19873] Update Privacy policy link in System Console > Enterprise & License
  components/admin_console/license_settings/license_settings.jsx
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#4147 Automated cherry pick of #4122
  components/admin_console/license_settings/license_settings.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4155 MM-19936 - Updating close button spacing mobile
  sass/responsive/_mobile.scss
Labels: 2: Dev Review, CherryPick/Approved, QA Review Done, Tests/Not Needed

#4149 MM-19811 Add Mark as Unread to RHS
  components/dot_menu/dot_menu.jsx
  components/rhs_comment/__snapshots__/rhs_comment.test.jsx.snap
  components/rhs_comment/index.js
  components/rhs_comment/rhs_comment.jsx
  components/rhs_comment/rhs_comment.test.jsx
  components/rhs_root_post/__snapshots__/rhs_root_post.test.jsx.snap
  components/rhs_root_post/index.js
  components/rhs_root_post/rhs_root_post.jsx
  components/rhs_root_post/rhs_root_post.test.jsx
Labels: 3: Reviews Complete

#4139 MM-19866: Remove Digest setting
  components/admin_console/admin_definition.jsx
  i18n/en.json
Labels: 3: Reviews Complete, QA Review Done

#4157 Automated cherry pick of #4155
  sass/responsive/_mobile.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4063 MM-6843 Update at-mention sort
  components/suggestion/at_mention_provider/at_mention_provider.jsx
  components/suggestion/at_mention_provider/at_mention_provider.test.jsx
Labels: 3: Reviews Complete, Hacktoberfest, QA Review Done

#4144 Update storybookUrl to easily override for daily E2E
  e2e/cypress.json
  e2e/cypress/support/storybook_commands.js
Labels: 3: Reviews Complete, QA Review Done

#4125 translations PR 20191104
  i18n/de.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: Tests/Not Needed

#3941 MM-18089 - Support for custom plugin admin settings
  actions/admin_actions.jsx
  actions/admin_actions.test.js
  components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
  components/admin_console/custom_plugin_settings/index.js
  components/admin_console/schema_admin_settings.jsx
  i18n/en.json
  plugins/registry.js
  reducers/plugins/index.js
  sass/routes/_admin-console.scss
  selectors/admin_console.jsx
  utils/constants.jsx
Labels: 3: Reviews Complete, QA Review Done

#4142 MM-19908 - Fixed ProfilePopover not closing on SendMessage
  components/profile_picture.tsx
  components/user_profile/user_profile.jsx
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#4160 MM-19935: System console user filters not returning expected results
  actions/user_actions.jsx
  actions/user_actions.test.js
Labels: 2: Dev Review, CherryPick/Approved, QA Review Done

#4081 [GH-12953] Migrate 'components/admin_console/boolean_setting.jsx' and associated tests to TypeScript
  components/admin_console/boolean_setting.tsx
  components/admin_console/cluster_settings.jsx
  components/admin_console/custom_terms_of_service_settings/custom_terms_of_service_settings.jsx
  components/admin_console/database_settings.jsx
  components/admin_console/elasticsearch_settings.jsx
  components/admin_console/message_export_settings.jsx
  components/admin_console/plugin_management/plugin_management.jsx
  components/admin_console/schema_admin_settings.jsx
Labels: 3: Reviews Complete, Hacktoberfest, QA Review Done, Tests/Not Needed

#4168 Automated cherry pick of #4160
  actions/user_actions.jsx
  actions/user_actions.test.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4170 MM-19995 Fix usage of React.forwardRef for LocalizedInput
  components/__snapshots__/searchable_channel_list.test.jsx.snap
  components/admin_console/__snapshots__/custom_url_schemes_setting.test.jsx.snap
  components/admin_console/compliance_reports/compliance_reports.jsx
  components/admin_console/permission_schemes_settings/permission_team_scheme_settings/__snapshots__/permission_team_scheme_settings.test.jsx.snap
  components/admin_console/system_users/system_users.jsx
  components/claim/components/email_to_ldap.jsx
  components/claim/components/email_to_oauth.jsx
  components/claim/components/ldap_to_email.jsx
  components/claim/components/oauth_to_email.jsx
  components/integrations/__snapshots__/abstract_command.test.jsx.snap
  components/localized_input/__snapshots__/localized_input.test.tsx.snap
  components/localized_input/localized_input.test.tsx
  components/localized_input/localized_input.tsx
  components/login/__snapshots__/login_mfa.test.jsx.snap
  components/login/login_controller/login_controller.jsx
  components/mfa/setup/setup.jsx
  components/new_channel_modal/__snapshots__/new_channel_modal.test.jsx.snap
  components/new_channel_modal/new_channel_modal.jsx
  components/new_channel_modal/new_channel_modal.test.jsx
  components/password_reset_form/__snapshots__/password_reset_form.test.js.snap
  components/password_reset_send_link/__snapshots__/password_reset_send_link.test.js.snap
  components/plugin_marketplace/__snapshots__/marketplace_modal.test.jsx.snap
  components/rename_channel_modal/__snapshots__/rename_channel_modal.test.jsx.snap
Labels: 3: Reviews Complete, QA Review Done

#3919 MM-12449 Migrate 'components/file_upload_overlay.jsx' and associated tests to TypeScript
  components/__snapshots__/file_upload_overlay.test.tsx.snap
  components/channel_view/channel_view.jsx
  components/file_upload_overlay.test.tsx
  components/file_upload_overlay.tsx
  components/sidebar_right/sidebar_right.jsx
Labels: 3: Reviews Complete, Hacktoberfest, Lifecycle/1:stale, QA Review Done

#4174 [No Ticket] Update Twitter link in README
  README.md
Labels: 3: Reviews Complete

#4061 MM-18972
  components/widgets/settings/bool_setting.test.tsx
  components/widgets/settings/bool_setting.tsx
  components/widgets/settings/radio_setting.test.tsx
  components/widgets/settings/radio_setting.tsx
  components/widgets/settings/setting.tsx
  components/widgets/settings/text_setting.test.tsx
  components/widgets/settings/text_setting.tsx
Labels: 3: Reviews Complete, Hacktoberfest, QA Review Done

#3945 MM-17477: Fix for group display name column expanding too large when …
  sass/components/_groups.scss
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#4175 Automated cherry pick of #3945
  sass/components/_groups.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4118 [GH-12457] Migrate 'components/widgets/menu' module and associated tests to TypeScript
  components/channel_header/channel_header.js
  components/channel_header_dropdown/channel_header_dropdown.js
  components/channel_header_dropdown/channel_header_dropdown_items.js
  components/dot_menu/dot_menu.jsx
  components/main_menu/main_menu.jsx
  components/sidebar/header/dropdown/sidebar_header_dropdown.jsx
  components/widgets/menu/menu.stories.tsx
  components/widgets/menu/menu.test.tsx
  components/widgets/menu/menu.tsx
  components/widgets/menu/menu_group.test.tsx
  components/widgets/menu/menu_group.tsx
  components/widgets/menu/menu_items/__snapshots__/menu_item_toggle_modal_redux.test.tsx.snap
  components/widgets/menu/menu_items/menu_item.test.tsx
  components/widgets/menu/menu_items/menu_item.tsx
  components/widgets/menu/menu_items/menu_item_action.test.tsx
  components/widgets/menu/menu_items/menu_item_action.tsx
  components/widgets/menu/menu_items/menu_item_external_link.test.tsx
  components/widgets/menu/menu_items/menu_item_external_link.tsx
  components/widgets/menu/menu_items/menu_item_link.test.tsx
  components/widgets/menu/menu_items/menu_item_link.tsx
  components/widgets/menu/menu_items/menu_item_toggle_modal_redux.test.tsx
  components/widgets/menu/menu_items/menu_item_toggle_modal_redux.tsx
  components/widgets/menu/menu_items/submenu_item.test.tsx
  components/widgets/menu/menu_items/submenu_item.tsx
  components/widgets/menu/menu_modals/submenu_modal/__snapshots__/submenu_modal.test.tsx.snap
  components/widgets/menu/menu_modals/submenu_modal/submenu_modal.test.tsx
  components/widgets/menu/menu_modals/submenu_modal/submenu_modal.tsx
  components/widgets/menu/menu_wrapper.test.tsx
  components/widgets/menu/menu_wrapper.tsx
  components/widgets/menu/menu_wrapper_animation.tsx
Labels: 3: Reviews Complete, QA Review Done, Tests/Not Needed

#4164 MM-19909 Fix for scroll pop with markdown images
  components/__snapshots__/size_aware_image.test.jsx.snap
  components/size_aware_image.jsx
  sass/layout/_markdown.scss
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#4161 Upgrade Cypress and other E2E dependencies
  components/user_settings/display/user_settings_theme/__snapshots__/custom_theme_chooser.test.jsx.snap
  components/user_settings/display/user_settings_theme/custom_theme_chooser.jsx
  e2e/cypress/integration/account_settings/display/code_theme_colors_spec.js
  e2e/cypress/integration/account_settings/display/theme/custom_theme_color_picker_spec.js
  e2e/cypress/integration/account_settings/display/theme/custom_theme_sidebar_styles_spec.js
  e2e/cypress/integration/channel/add_users_to_channel_spec.js
  e2e/cypress/integration/channel/channel_menu_spec.js
  e2e/cypress/integration/channel/channel_name_tooltips_spec.js
  e2e/cypress/integration/emoji/sorted_emojis_spec.js
  e2e/cypress/integration/enterprise/elasticsearch/renaming_spec.js
  e2e/cypress/integration/enterprise/elasticsearch/users_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/guest_experience_ui_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/guest_identification_ui_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/guest_invitation_ui_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/member_invitation_ui_spec.js
  e2e/cypress/integration/integrations/builtin_commands/common_commands_spec.js
  e2e/cypress/integration/integrations/builtin_commands/user_status_commands_spec.js
  e2e/cypress/integration/messaging/message_channel_reference_spec.js
  e2e/cypress/integration/search/search_group_message_spec.js
  e2e/cypress/integration/system_console/inactive_users_spec.js
  e2e/cypress/integration/team/teams_spec.js
  e2e/cypress/support/ui_commands.js
  e2e/package-lock.json
  e2e/package.json
Labels: 3: Reviews Complete, QA Review Done

#4178 Automated cherry pick of #4164
  components/__snapshots__/size_aware_image.test.jsx.snap
  components/size_aware_image.jsx
  sass/layout/_markdown.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4166 [GH-12285] UI Automation: Write an automated test using Cypress for "Posts change order when being sent quickly"
  e2e/cypress/integration/messaging/quick_send_spec.js
Labels: 3: Reviews Complete, QA Review Done

#4159 MM-19944 - Revert SearchResults to bind search text to SearchResultsTerms
  actions/views/rhs.js
  components/search_results/index.jsx
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#4181 Automated cherry pick of #4159
  actions/views/rhs.js
  components/search_results/index.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4107 [MM-18156] Change around RHS search bar such that it's tabbable when RHS is open
  components/channel_header/channel_header.js
  components/channel_header/components/header_icon_wrapper.js
  components/channel_header/index.js
  sass/components/_search.scss
  sass/layout/_content.scss
  sass/layout/_headers.scss
  sass/responsive/_desktop.scss
  sass/responsive/_tablet.scss
Labels: 3: Reviews Complete, QA Review Done, Setup Cloud Test Server

#4108 MM-17549: support upgrading plugins
  actions/marketplace.js
  components/plugin_marketplace/__snapshots__/marketplace_modal.test.js.snap
  components/plugin_marketplace/__snapshots__/marketplace_modal.test.jsx.snap
  components/plugin_marketplace/index.js
  components/plugin_marketplace/marketplace_item/__snapshots__/marketplace_item.test.js.snap
  components/plugin_marketplace/marketplace_item/__snapshots__/marketplace_item.test.jsx.snap
  components/plugin_marketplace/marketplace_item/index.js
  components/plugin_marketplace/marketplace_item/marketplace_item.js
  components/plugin_marketplace/marketplace_item/marketplace_item.jsx
  components/plugin_marketplace/marketplace_item/marketplace_item.test.js
  components/plugin_marketplace/marketplace_modal.js
  components/plugin_marketplace/marketplace_modal.scss
  components/plugin_marketplace/marketplace_modal.test.js
  components/plugin_marketplace/marketplace_modal.test.jsx
  e2e/cypress/integration/plugins/marketplace/marketplace_avaliability_spec.js
  e2e/cypress/integration/plugins/marketplace/marketplace_spec.js
  e2e/cypress/support/api_commands.js
  i18n/en.json
  reducers/views/index.js
  reducers/views/marketplace.js
  reducers/views/marketplace.test.js
  selectors/views/marketplace.js
  selectors/views/marketplace.test.js
  utils/constants.jsx
Labels: 3: Reviews Complete

#3862 MM-18919 Migrate 'utils/syntax_highlighting' to TypeScript
  components/code_preview.jsx
  package-lock.json
  package.json
  types/highlightjs.d.ts
  utils/markdown/renderer.jsx
  utils/syntax_highlighting.tsx
Labels: 3: Reviews Complete, Hacktoberfest

#4173 MM-18677 UI Automation: Clicking on airplane icon does not open file attachment modal but sends the message
  e2e/cypress/integration/messaging/message_by_aeroplane_icon_spec.js
Labels: 3: Reviews Complete, QA Review Done, Tests/Not Needed

#4151 [GH-12304] UI Automation: Write an automated test using Cypress for "Compact view: Markdown quotation"
  e2e/cypress/integration/messaging/quote_notation_spec.js
Labels: 2: Dev Review, 2: QA Review

#4154 MM-19862 - Updating post error css RHS
  components/create_comment/__snapshots__/create_comment.test.jsx.snap
  components/create_comment/create_comment.jsx
  sass/layout/_post.scss
  sass/layout/_sidebar-right.scss
  sass/responsive/_mobile.scss
  sass/utils/_flex.scss
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#4180 MM-19958 - Updating file thumbnail css (IE Fix)
  sass/components/_files.scss
Labels: 2: QA Review, CherryPick/Approved

#4195 Automated cherry pick of #4180
  sass/components/_files.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4176 MM-19757 - Updating heading for channel intro
  components/post_view/channel_intro_message/channel_intro_message.jsx
Labels: 3: Reviews Complete, QA Review Done, Tests/Not Needed

#4177 MM-18708 Fix state of embed visibility for users logging in on same browser/client
  actions/post_actions.jsx
  selectors/posts.js
Labels: 3: Reviews Complete, QA Review Done

#4182 MM-19944 Add E2E on search highlighting
  e2e/cypress/integration/search/results_post_spec.js
Labels: 3: Reviews Complete, QA Review Done

#4124 MM-19519 - PostContext to handle menus opened/closed within Posts
  components/autocomplete_selector.jsx
  components/post_view/message_attachments/action_menu/action_menu.jsx
  components/post_view/post/post.jsx
  components/post_view/post_context.js
Labels: 3: Reviews Complete, QA Review Done

#4162 [MM-19858] Adding an email address to a post directly doesn't add a target="blank" attribute to the resulting anchor tag.
  utils/text_formatting.jsx
  utils/text_formatting_email.test.jsx
  utils/text_formatting_links.test.jsx
Labels: CherryPick/Approved, QA Review Done

#4200 Automated cherry pick of #4162
  utils/text_formatting.jsx
  utils/text_formatting_email.test.jsx
  utils/text_formatting_links.test.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4137 Adding aria label to the invite link input
  components/invitation_modal/__snapshots__/invitation_modal.test.jsx.snap
  components/invitation_modal/__snapshots__/invitation_modal_members_step.test.jsx.snap
  components/invitation_modal/invitation_modal_members_step.jsx
  components/invitation_modal/invitation_modal_members_step.test.jsx
  i18n/en.json
Labels: 3: Reviews Complete, QA Review Done, Tests/Not Needed

#4184 MM-19955 Remove divider from post menu on mobile
  components/dot_menu/__snapshots__/dot_menu.test.jsx.snap
  components/dot_menu/dot_menu.jsx
  components/dot_menu/dot_menu.test.jsx
Labels: 3: Reviews Complete, QA Review Done

#4171 New channel Modal close button a11y issue.
  components/new_channel_modal/__snapshots__/new_channel_modal.test.jsx.snap
  components/new_channel_modal/new_channel_modal.jsx
Labels: 3: Reviews Complete, QA Review Done

#4186 MM-19964 Properly handle whitespace before code block language
  package-lock.json
  package.json
  utils/markdown/index.test.js
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#4204 getting the branch name if is from upstream or fixing if come from PR
  .circleci/config.yml
Labels: 2: Dev Review

#4197 [MM-18014] Hide back button on successful invites
  components/invitation_modal/__snapshots__/invitation_modal_confirm_step.test.jsx.snap
  components/invitation_modal/invitation_modal_confirm_step.jsx
Labels: 3: Reviews Complete, QA Review Done, Tests/Done

#4138 MM-19482 Stop rendering New Messages line differently for manually unread channels
  package-lock.json
  package.json
Labels: 3: Reviews Complete, QA Review Done

#4192 MM-18517: release notes, upgrade confirmation, local-tag
  components/plugin_marketplace/marketplace_item/__snapshots__/marketplace_item.test.js.snap
  components/plugin_marketplace/marketplace_item/marketplace_item.js
  components/plugin_marketplace/marketplace_item/marketplace_item.test.js
  components/plugin_marketplace/marketplace_modal.js
  components/plugin_marketplace/marketplace_modal.scss
  e2e/cypress/integration/plugins/marketplace/marketplace_spec.js
  e2e/cypress/support/api_commands.js
  i18n/en.json
Labels: 3: Reviews Complete

#4199 MM-17943 : Add tests for openGroupChannelToUserIds action
  actions/channel_actions.test.js
Labels: 2: Dev Review, QA Review Done

#4153 [GH-12297] UI Automation: Write an automated test using Cypress for "Edit post with "strikethrough" and ensure channel auto-complete closes after second tilde (~~)"
  e2e/cypress/integration/messaging/strikethrough_spec.js
Labels: 3: Reviews Complete, QA Review Done

#4218 Fixed make check-types by excluding cypress folder
  tsconfig.json
Labels: 2: Dev Review, Tests/Not Needed

#4215 MM-19936 - Updating close button
  sass/responsive/_mobile.scss
Labels: CherryPick/Approved, QA Review Done

#4158 [GH-12291] UI Automation: Write an automated test using Cypress for "Markdown quotation paragraphs"
  e2e/cypress/integration/messaging/markdown_quotation_paragraphs_spec.js
Labels: 3: Reviews Complete, QA Review Done, Tests/Not Needed

#4206 MM-20151 Fix for svg console error about width property
  components/__snapshots__/size_aware_image.test.jsx.snap
  components/size_aware_image.jsx
  sass/layout/_markdown.scss
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done, Tests/Not Needed

#4172 Mobile web: Add aria-labels to navbar buttons #13010
  components/channel_header_mobile/channel_info_button/__snapshots__/channel_info_button.test.js.snap
  components/channel_header_mobile/channel_info_button/channel_info_button.js
  components/channel_header_mobile/show_search_button/show_search_button.js
  i18n/en.json
Labels: 3: Reviews Complete, AutoMerge, QA Review Done

#4211 Fix redirections on empty teams
  actions/global_actions.jsx
  actions/global_actions.test.js
  components/error_page/error_page.tsx
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#4223 MM-20072 - Updating comment box css
  components/create_comment/__snapshots__/create_comment.test.jsx.snap
  components/create_comment/create_comment.jsx
  sass/layout/_post-right.scss
  sass/responsive/_mobile.scss
Labels: QA Review Done, Tests/Not Needed

#4191 MM-20006 - Fixed Display Name order in Channel Header
  components/channel_header/channel_header.js
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done, Setup Cloud Test Server

#4179 [GH-12004] Add tests for openDirectChannelToUserId action
  actions/channel_actions.test.js
Labels: 3: Reviews Complete, QA Review Done

#4227 Linting global actions
  actions/global_actions.test.js
Labels: CherryPick/Approved, Tests/Not Needed

#4228 Automated cherry pick of #4227
  actions/global_actions.test.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4188 [MM-19490][MM-20039] Refactor Complex Display Logic
  components/channel_members_dropdown/channel_members_dropdown.jsx
  components/channel_members_dropdown/channel_members_dropdown.test.jsx
  components/channel_members_dropdown/index.js
  utils/utils.jsx
Labels: 3: Reviews Complete, QA Review Done

#4133 MM-18482 - Popover common component
  Makefile
  components/channel_header/__snapshots__/channel_header.test.jsx.snap
  components/channel_header/channel_header.js
  components/channel_header_mobile/channel_info_button/__snapshots__/channel_info_button.test.js.snap
  components/channel_header_mobile/channel_info_button/channel_info_button.js
  components/popover_list_members/__snapshots__/popover_list_members.test.jsx.snap
  components/popover_list_members/popover_list_members.jsx
  components/profile_popover/__snapshots__/profile_popover.test.jsx.snap
  components/profile_popover/profile_popover.jsx
  components/search_bar/__snapshots__/search_bar.test.jsx.snap
  components/search_bar/search_bar.jsx
  components/suggestion/search_suggestion_list.jsx
  components/suggestion/suggestion_date.jsx
  components/user_settings/display/user_settings_theme/__snapshots__/custom_theme_chooser.test.jsx.snap
  components/user_settings/display/user_settings_theme/custom_theme_chooser.jsx
  components/widgets/popover/__snapshots__/popover.test.tsx.snap
  components/widgets/popover/index.tsx
  components/widgets/popover/popover.stories.js
  components/widgets/popover/popover.test.tsx
  components/widgets/popover/popover_spec.js
  e2e/cypress.json
Labels: 3: Reviews Complete, QA Review Done

#4196 MM-19609 - Add new prepackage configuration settings
  components/admin_console/plugin_management/__snapshots__/plugin_management.test.jsx.snap
  components/admin_console/plugin_management/plugin_management.jsx
  components/admin_console/plugin_management/plugin_management.test.jsx
  i18n/en.json
Labels: 3: Reviews Complete

#4229 Fix release-5.17 tests
  utils/markdown/index.test.js
Labels: 3: Reviews Complete, AutoMerge, QA Review Done

#4226 Automated cherry pick of #4191
  components/channel_header/channel_header.js
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4224 Automated cherry pick of #4206
  components/__snapshots__/size_aware_image.test.jsx.snap
  components/size_aware_image.jsx
  sass/layout/_markdown.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4221 Automated cherry pick of #4215
  sass/responsive/_mobile.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4202 MM-20078: Migrate 'components/admin_console/radio_setting.jsx' and associated tests to TypeScript
  components/admin_console/__snapshots__/radio_setting.test.tsx.snap
  components/admin_console/radio_setting.test.tsx
  components/admin_console/radio_setting.tsx
  components/admin_console/schema_admin_settings.jsx
Labels: 3: Reviews Complete, QA Review Done, Tests/Not Needed

#4222 MM-20144 - Fixed Mattermost typo in System Console -> LDAP Settings
  components/admin_console/admin_definition.jsx
  i18n/en.json
Labels: 3: Reviews Complete, QA Review Done

#4150 Fix weird cursor behaviour when mousing off of post
  components/post_view/post/post.jsx
Labels: 3: Reviews Complete

#4156 [GH-12296] UI Automation: Write an automated test using Cypress for "Link preview - Removing it from my view removes it from other user's view"
  components/post_view/post_attachment_opengraph/post_attachment_opengraph.jsx
  e2e/cypress/integration/messaging/collapse_link_spec.js
  e2e/cypress/support/api_commands.js
Labels: 3: Reviews Complete, QA Review Done

#4131 Adding warning before disabling the guest accounts access
  components/admin_console/__snapshots__/custom_enable_disable_guest_accounts_setting.test.tsx.snap
  components/admin_console/admin_definition.jsx
  components/admin_console/custom_enable_disable_guest_accounts_setting.test.tsx
  components/admin_console/custom_enable_disable_guest_accounts_setting.tsx
  i18n/en.json
Labels: 3: Reviews Complete, QA Review Done, Tests/Done

#4071 Fix UnhandledPromiseRejectionWarning when running unit tests
  components/admin_console/system_user_detail/team_list/__snapshots__/team_list.test.jsx.snap
  components/admin_console/system_user_detail/team_list/team_list.test.jsx
  components/plugin_marketplace/marketplace_modal.test.jsx
Labels: 3: Reviews Complete, AutoMerge, QA Review Done

#3955 MM-19176 - Clear button for search in plugins marketplace
  components/plugin_marketplace/marketplace_modal.jsx
  components/plugin_marketplace/marketplace_modal.scss
Labels: 3: Reviews Complete, AutoMerge, QA Review Done

#4116 MM-19337 Enable users to view archived channels
  actions/channel_actions.jsx
  components/__snapshots__/searchable_channel_list.test.jsx.snap
  components/admin_console/admin_definition.jsx
  components/channel_view/channel_view.jsx
  components/delete_channel_modal/__snapshots__/delete_channel_modal.test.jsx.snap
  components/delete_channel_modal/delete_channel_modal.jsx
  components/more_channels/__snapshots__/more_channels.test.jsx.snap
  components/more_channels/index.js
  components/more_channels/more_channels.jsx
  components/more_channels/more_channels.test.jsx
  components/searchable_channel_list.jsx
  components/searchable_channel_list.test.jsx
  components/sidebar/channel_more.jsx
  components/sidebar/index.js
  components/sidebar/sidebar.jsx
  components/widgets/menu/menu_wrapper.tsx
  e2e/cypress/integration/channel/more_channels_spec.js
  i18n/en.json
  package-lock.json
  package.json
  sass/components/_modal.scss
Labels: QA Review Done, Setup Cloud Test Server

#4237 [No Ticket] Update Marked back to latest version
  package.json
Labels: 3: Reviews Complete

#4148 [MM-19309] Name Display Lock
  components/admin_console/admin_definition.jsx
  components/admin_console/boolean_setting.tsx
  components/admin_console/dropdown_setting.jsx
  components/admin_console/setting.tsx
  components/setting_item_max.jsx
  components/user_settings/display/__snapshots__/user_settings_display.test.jsx.snap
  components/user_settings/display/index.js
  components/user_settings/display/user_settings_display.jsx
  e2e/cypress/integration/system_console/lock_teammate_name_display_spec.js
  i18n/en.json
  package-lock.json
  package.json
Labels: 3: Reviews Complete, QA Review Done

#4235 MM-20072 - Fixing file thumbnail css
  sass/components/_files.scss
Labels: 2: Dev Review, CherryPick/Approved, QA Review Done

#4238 Automated cherry pick of #4235
  sass/components/_files.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4234 Fixing redirection on leave channel
  actions/global_actions.jsx
  actions/global_actions.test.js
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done, Setup Cloud Test Server

#4240 Automated cherry pick of #4234
  actions/global_actions.jsx
  actions/global_actions.test.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3916 Migrate 'components/autosize_textarea.jsx' and associated tests to TypeScript
  components/__snapshots__/autosize_textarea.test.jsx.snap
  components/autosize_textarea.tsx
  components/user_settings/notifications/__snapshots__/manage_auto_responder.test.jsx.snap
Labels: 3: Reviews Complete, Hacktoberfest, QA Review Done, Tests/Not Needed

#4095 MM-19517 Adding ability to disable attachment buttons and fields.
  components/autocomplete_selector.jsx
  components/post_view/message_attachments/action_button.jsx
  components/post_view/message_attachments/action_menu/action_menu.jsx
  components/post_view/message_attachments/message_attachment/message_attachment.jsx
  sass/layout/_webhooks.scss
Labels: Setup Cloud Test Server

#4207 MM-18186 - Direct Messages filtered search results not in alphabetical order
  components/more_direct_channels/index.js
Labels: 3: Reviews Complete, QA Review Done, Tests/Not Needed

#4002 Add missing message to en.json
  components/plugin_marketplace/marketplace_modal.jsx
  i18n/en.json
Labels: 3: Reviews Complete, AutoMerge, QA Review Done, Tests/Not Needed

#4225 MM-20159 Re-add post click handler
  components/post_view/post/post.jsx
Labels: 2: Dev Review

#4209 MM-20019 - Updating markdown text in header
  sass/layout/_headers.scss
Labels: 2: Dev Review, QA Review Done, Tests/Not Needed

#4239 Update Cypress to 3.6.1 and fix failing E2E
  e2e/cypress/integration/account_settings/display/theme/custom_theme_color_picker_spec.js
  e2e/cypress/integration/account_settings/general/nickname_spec.js
  e2e/cypress/integration/channel/channel_mention_autocomplete_spec.js
  e2e/package-lock.json
  e2e/package.json
Labels: 2: Dev Review, 2: QA Review

#4236 [MM-20160] Option to make team admin should not be provided to a guest user
  components/admin_console/manage_teams_modal/__snapshots__/manage_teams_dropdown.test.jsx.snap
  components/admin_console/manage_teams_modal/manage_teams_dropdown.jsx
Labels: 3: Reviews Complete, QA Review Done

#4193 [GH-12298] UI Automation: Write an automated test using Cypress for "Leave a long draft in the main input box"
  e2e/cypress/integration/messaging/long_draft_spec.js
Labels: 3: Reviews Complete, QA Review Done

#4208 MM-14452 - When a non-sysadmin tries to navigate to a system console URL, the login screen flashes briefly before redirecting to Town Square
  components/admin_console/__snapshots__/admin_console.test.jsx.snap
  components/admin_console/admin_console.jsx
  components/admin_console/admin_console.test.jsx
  components/admin_console/index.js
Labels: 2: Dev Review, CherryPick/Approved, QA Review Done, Tests/Not Needed

#4136 Changes to allow focus and keyboard interaction in close and back icons
  components/invitation_modal/__snapshots__/invitation_modal.test.jsx.snap
  components/invitation_modal/__snapshots__/invitation_modal_confirm_step.test.jsx.snap
  components/invitation_modal/__snapshots__/invitation_modal_guests_step.test.jsx.snap
  components/invitation_modal/__snapshots__/invitation_modal_members_step.test.jsx.snap
  components/invitation_modal/invitation_modal.jsx
  components/invitation_modal/invitation_modal.scss
  components/invitation_modal/invitation_modal_confirm_step.jsx
  components/invitation_modal/invitation_modal_confirm_step.test.jsx
  components/invitation_modal/invitation_modal_guests_step.jsx
  components/invitation_modal/invitation_modal_guests_step.test.jsx
  components/invitation_modal/invitation_modal_members_step.jsx
  components/invitation_modal/invitation_modal_members_step.test.jsx
  components/plugin_marketplace/__snapshots__/marketplace_modal.test.jsx.snap
  components/widgets/modals/full_screen_modal.scss
  components/widgets/modals/full_screen_modal.test.tsx
  components/widgets/modals/full_screen_modal.tsx
  i18n/en.json
Labels: CherryPick/Approved, QA Review Done

#4249 Automated cherry pick of #4208
  components/admin_console/__snapshots__/admin_console.test.jsx.snap
  components/admin_console/admin_console.jsx
  components/admin_console/admin_console.test.jsx
  components/admin_console/index.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4212 MM-18517: Plugin Marketplace (Phase 2)
  actions/marketplace.js
  components/plugin_marketplace/__snapshots__/marketplace_modal.test.js.snap
  components/plugin_marketplace/__snapshots__/marketplace_modal.test.jsx.snap
  components/plugin_marketplace/index.js
  components/plugin_marketplace/marketplace_item/__snapshots__/marketplace_item.test.js.snap
  components/plugin_marketplace/marketplace_item/__snapshots__/marketplace_item.test.jsx.snap
  components/plugin_marketplace/marketplace_item/index.js
  components/plugin_marketplace/marketplace_item/marketplace_item.js
  components/plugin_marketplace/marketplace_item/marketplace_item.jsx
  components/plugin_marketplace/marketplace_item/marketplace_item.test.js
  components/plugin_marketplace/marketplace_item/marketplace_item.test.jsx
  components/plugin_marketplace/marketplace_modal.js
  components/plugin_marketplace/marketplace_modal.scss
  components/plugin_marketplace/marketplace_modal.test.js
  components/plugin_marketplace/marketplace_modal.test.jsx
  e2e/cypress/integration/plugins/marketplace/marketplace_avaliability_spec.js
  e2e/cypress/integration/plugins/marketplace/marketplace_spec.js
  e2e/cypress/support/api_commands.js
  i18n/en.json
  package-lock.json
  package.json
  reducers/views/index.js
  reducers/views/marketplace.js
  reducers/views/marketplace.test.js
  selectors/views/marketplace.js
  selectors/views/marketplace.test.js
  utils/constants.jsx
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#4245 Fix failing E2E test at integration/channel
  e2e/cypress/integration/channel/edit_message_spec.js
  e2e/cypress/integration/channel/header_spec.js
  e2e/cypress/integration/channel/message_bullets_spec.js
Labels: 3: Reviews Complete, QA Review Done

#4210 MM-16232 Admin settings for id_loaded push notifications
  components/admin_console/admin_definition.jsx
  i18n/en.json
Labels: CherryPick/Approved, QA Review Done, Setup Cloud Test Server

#4145 MM-16368 - Plugin Signing
  actions/marketplace.js
  components/admin_console/plugin_management/__snapshots__/plugin_management.test.jsx.snap
  components/admin_console/plugin_management/plugin_management.jsx
  components/admin_console/plugin_management/plugin_management.test.jsx
  components/plugin_marketplace/marketplace_item/__snapshots__/marketplace_item.test.js.snap
  components/plugin_marketplace/marketplace_item/marketplace_item.js
  i18n/en.json
  package-lock.json
  package.json
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#4214 MM-18701 Add E2E on permalink loading indicator
  e2e/cypress/integration/messaging/permalink_loading_indicator_spec.js
  e2e/cypress/utils/index.js
Labels: 3: Reviews Complete, QA Review Done

#4183 MM-17444 UI Automation: Write an automated test using Cypress for "Markdown correctly parses "://///" and doesn't break the channel
  e2e/cypress/integration/messaging/message_parse_spec.js
Labels: 3: Reviews Complete, QA Review Done

#4244 MM-18706 Add E2E on reply input box expansion
  e2e/cypress/integration/messaging/message_reply_input_box_expand_spec.js
Labels: 3: Reviews Complete, QA Review Done

#4143 Building properly the notification level string
  components/channel_notifications_modal/components/__snapshots__/describe.test.jsx.snap
  components/channel_notifications_modal/components/describe.jsx
  i18n/en.json
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done, Tests/Not Needed

#4265 Automated cherry pick of #4143
  components/channel_notifications_modal/components/__snapshots__/describe.test.jsx.snap
  components/channel_notifications_modal/components/describe.jsx
  i18n/en.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4129 E2E for sidebar and link navigation of system admin console
  e2e/cypress/integration/enterprise/system_console/sidebar_link_navigation_spec.js
  e2e/cypress/integration/system_console/sidebar_link_navigation_spec.js
Labels: 3: Reviews Complete, QA Review Done

#4126 [MM-18700] UI Automation: "Leave a long draft in reply input box"
  e2e/cypress/integration/messaging/post_textbox_height_spec.js
Labels: 3: Reviews Complete, QA Review Done

#3995 MM-18356: Adds search to channels list.
  components/admin_console/team_channel_settings/abstract_list.jsx
  components/admin_console/team_channel_settings/channel/__snapshots__/channel_settings.test.jsx.snap
  components/admin_console/team_channel_settings/channel/channel_settings.jsx
  components/admin_console/team_channel_settings/channel/list/__snapshots__/channel_list.test.jsx.snap
  components/admin_console/team_channel_settings/channel/list/__snapshots__/channel_row.test.jsx.snap
  components/admin_console/team_channel_settings/channel/list/channel_list.jsx
  components/admin_console/team_channel_settings/channel/list/channel_list.test.jsx
  components/admin_console/team_channel_settings/channel/list/channel_row.jsx
  components/admin_console/team_channel_settings/channel/list/index.js
  e2e/cypress/integration/enterprise/channels/search_channels_spec.js
  i18n/en.json
  package-lock.json
  package.json
  sass/components/_groups.scss
Labels: 2: Dev Review, QA Review Done

#4248 Fix failing tests on search
  e2e/cypress/integration/search/date_filter_spec.js
  e2e/cypress/integration/search/negative_filter_spec.js
Labels: 3: Reviews Complete, QA Review Done

#4194 MM-19303 - When adding a guest to a team from the user management page the Guest is put into a channel not found page and unable to log out or request help
  components/error_page/__snapshots__/error_message.test.tsx.snap
  components/error_page/error_message.test.tsx
  components/error_page/error_message.tsx
  components/error_page/error_page.tsx
  i18n/en.json
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#4232 Refactor login spec
  e2e/cypress/integration/login/login_spec.js
Labels: 2: Dev Review, 2: QA Review

#4163 MM-20016 Initialize EmojiPickerOverlay using props from the constructor
  components/emoji_picker/emoji_picker_overlay.jsx
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done, Tests/Not Needed

#4271 Automated cherry pick of #4194
  components/error_page/__snapshots__/error_message.test.tsx.snap
  components/error_page/error_message.test.tsx
  components/error_page/error_message.tsx
  components/error_page/error_page.tsx
  i18n/en.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4261 translations PR 20191118
  i18n/de.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 3: Reviews Complete

#4273 Automated cherry pick of #4163
  components/emoji_picker/emoji_picker_overlay.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4251 [GH-12272] UI Automation: Write an automated test using Cypress for "Trying to type in middle of text should not send the cursor to end of textbox"
  e2e/cypress/integration/messaging/typing_on_middle_spec.js
Labels: 2: Dev Review, 2: QA Review

#4276 Fix invitation modal back buton (bad merge resolution)
  components/invitation_modal/invitation_modal.jsx
Labels: CherryPick/Approved, QA Review Done, Setup Cloud Test Server
