Repository mattermost/mattermost-webapp, pull requests merged in 2019-04, with the labels that each got.

#2581 MM-14790 Update hash for react-window to solve postoverlap
  package-lock.json
  package.json
Labels: 3: Ready to Merge, CherryPickApproved

#2583 Restored addUserToTeamFromInvite action
  actions/team_actions.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2579 MM-14783: Fix button in progress text in add users to channel/team.
  components/add_users_to_team/__snapshots__/add_users_to_team.test.jsx.snap
  components/add_users_to_team/add_users_to_team.jsx
  components/channel_invite_modal/__snapshots__/channel_invite_modal.test.jsx.snap
  components/channel_invite_modal/channel_invite_modal.jsx
  i18n/en.json
Labels: 3: Ready to Merge, CherryPickApproved

#2580 [MM-14824] Split user profile during autocompletion to be able to match username parts split by special characters
  components/suggestion/at_mention_provider/at_mention_provider.jsx
  components/suggestion/at_mention_provider/at_mention_provider.test.jsx
  utils/constants.jsx
  utils/get_users.js
  utils/get_users.test.js
  utils/utils.jsx
  utils/utils.test.jsx
Labels: 3: Ready to Merge, Awaiting PR, CherryPickApproved

#2563 Fixing some i18n missed strings
  i18n/en.json
  utils/constants.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2564 MM-14792 - Updating autoresponder styling
  components/user_settings/notifications/user_settings_notifications.jsx
  sass/routes/_settings.scss
Labels: 3: Ready to Merge, CherryPickApproved

#2570 MM-14798 Fix drag and dropping text giving wrong error message
  components/file_upload/file_upload.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2576 MM-14820 Fix post menu on mobile view
  components/post_view/post/post.jsx
  components/post_view/post_list.jsx
  components/post_view/post_list_row/post_list_row.jsx
  components/widgets/menu/menu_wrapper.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2589 MM-14761 Loading channel with lot of unreads should show loader at the top
  components/post_view/post_list.jsx
  components/post_view/post_list.test.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2591 MM-14791 Fix for FF and safari jumpiness when loading more posts
  package-lock.json
  package.json
Labels: 3: Ready to Merge, CherryPickApproved

#2567 MM-14775 - Updating banner css in system console
  sass/routes/_admin-console.scss
Labels: 3: Ready to Merge, CherryPickApproved

#2568 MM-14778 - Updating menu functionality
  components/file_upload/__snapshots__/file_upload.test.jsx.snap
  components/file_upload/file_upload.jsx
  components/widgets/menu/menu.jsx
  components/widgets/menu/menu.test.jsx
  sass/responsive/_mobile.scss
Labels: 3: Ready to Merge, CherryPickApproved

#2565 MM-14765 - Updating emoji picker
  components/emoji_picker/emoji_picker.jsx
  components/emoji_picker/emoji_picker_tabs.jsx
  sass/components/_emoticons.scss
  sass/responsive/_mobile.scss
Labels: 3: Ready to Merge, CherryPickApproved

#2586 MM-14692 - Updating css code for placeholder
  components/__snapshots__/autosize_textarea.test.jsx.snap
  components/autosize_textarea.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2547 MM-14671 - Updating dropdown styling
  components/widgets/menu/menu_wrapper_animation.jsx
  sass/layout/_headers.scss
  sass/widgets/menu/_menu.scss
  sass/widgets/menu/_menu_group.scss
  sass/widgets/menu/_menu_item.scss
  utils/utils.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2585 Update NOTICE.txt
  NOTICE.txt
Labels: 3: Ready to Merge, CherryPickApproved

#2596 MM-14810 Fix for channel header loading in center channel
  components/post_view/post_list.jsx
  components/post_view/post_list.test.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2595 Enabling bot accounts UI.
  components/backstage/components/backstage_sidebar.jsx
  components/integrations/integrations.jsx
Labels: 2: Dev Review

#2594 MM-14861 Fix safari perf issues
  package-lock.json
  package.json
Labels: 3: Ready to Merge, CherryPickApproved

#2597 [MM-14826] Disable Safari spellcheck on quick switcher
  components/quick_switch_modal/__snapshots__/quick_switch_modal.test.jsx.snap
  components/quick_switch_modal/quick_switch_modal.jsx
Labels: 3: Ready to Merge

#2587 translations PR 20190401
  i18n/de.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 3: Ready to Merge

#2602 [MM-14746] Show Remove MFA Item in System Console only for Users that enabled MFA
  components/admin_console/system_users/system_users_dropdown/system_users_dropdown.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2611 [MM-14863] Set channel as viewed on channel switch
  actions/global_actions.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2582 MM-14797 - Updating select teams page
  components/select_team/components/__snapshots__/select_team_item.test.jsx.snap
  components/select_team/components/select_team_item.jsx
  sass/routes/_signup.scss
Labels: 2: Dev Review, CherryPickApproved

#2605 MM-14745 - Updating header css
  components/channel_header/channel_header.js
  sass/layout/_headers.scss
Labels: 3: Ready to Merge, CherryPickApproved

#2608 [MM 14801] Don't highlight [at]channel/all/here in usernames
  utils/text_formatting.jsx
  utils/text_formatting.test.jsx
Labels: 3: Ready to Merge, CherryPickCandidate

#2614 MM-14886 Move file input back to be child of button
  components/file_upload/__snapshots__/file_upload.test.jsx.snap
  components/file_upload/file_upload.jsx
Labels: 2: Dev Review, CherryPickApproved

#2593 [MM-14734] Added demoted user test. Added functionality to call api.
  components/admin_console/__snapshots__/admin_console.test.jsx.snap
  components/admin_console/admin_console.jsx
  cypress/integration/system_console/demoted_user_spec.js
  cypress/plugins/external_request.js
  cypress/plugins/index.js
Labels: 3: Ready to Merge

#2604 MM-14829 - Updating inline images
  components/single_image_view/__snapshots__/single_image_view.test.jsx.snap
  components/single_image_view/single_image_view.jsx
  sass/components/_files.scss
Labels: 3: Ready to Merge, CherryPickApproved

#2607 MM-14875 - Updating menu item with help text (DND)
  components/widgets/menu/menu_items/menu_item_action.jsx
  components/widgets/menu/menu_items/menu_item_action.test.jsx
  sass/widgets/menu/_menu_item.scss
Labels: 3: Ready to Merge, CherryPickApproved

#2615 Fixing case where I have only 1 upload plugin
  components/file_upload/__snapshots__/file_upload.test.jsx.snap
  components/file_upload/file_upload.jsx
Labels: 2: Dev Review, CherryPickCandidate

#2606 MM-14787 - Updating dropdown menu on mobile
  components/widgets/menu/menu.jsx
  components/widgets/menu/menu.test.jsx
  components/widgets/menu/menu_wrapper_animation.jsx
  sass/responsive/_mobile.scss
Labels: 3: Ready to Merge, CherryPickApproved

#2561 MM-14617 Updating dependencies.
  .babelrc
  components/__snapshots__/textbox.test.jsx.snap
  components/admin_console/__snapshots__/admin_console.test.jsx.snap
  components/admin_console/admin_sidebar/admin_sidebar.jsx
  components/admin_console/admin_sidebar_category.jsx
  components/admin_console/group_settings/__snapshots__/group_row.test.jsx.snap
  components/admin_console/permission_schemes_settings/permissions_scheme_summary/__snapshots__/permissions_scheme_summary.test.jsx.snap
  components/copy_url_context_menu/__snapshots__/copy_url_context_menu.test.jsx.snap
  components/create_comment/create_comment.jsx
  components/create_comment/create_comment.test.jsx
  components/create_post/create_post.jsx
  components/create_post/create_post.test.jsx
  components/create_team/__snapshots__/create_team.test.jsx.snap
  components/edit_channel_header_modal/edit_channel_header_modal.jsx
  components/edit_post_modal/edit_post_modal.jsx
  components/edit_post_modal/edit_post_modal.test.jsx
  components/emoji/add_emoji/__snapshots__/add_emoji.test.js.snap
  components/file_upload/index.js
  components/integrations/__snapshots__/abstract_command.test.jsx.snap
  components/integrations/__snapshots__/abstract_incoming_hook.test.jsx.snap
  components/integrations/__snapshots__/abstract_oauth_app.test.jsx.snap
  components/integrations/__snapshots__/abstract_outgoing_webhook.test.jsx.snap
  components/integrations/__snapshots__/installed_command.test.jsx.snap
  components/integrations/__snapshots__/installed_incoming_webhook.test.jsx.snap
  components/integrations/__snapshots__/installed_outgoing_webhook.test.jsx.snap
  components/integrations/confirm_integration/__snapshots__/confirm_integration.test.jsx.snap
  components/integrations/installed_oauth_app/__snapshots__/installed_oauth_app.test.jsx.snap
  components/logged_in/logged_in.test.jsx
  components/login/login_controller/__snapshots__/login_controller.test.jsx.snap
  components/permalink_view/__snapshots__/permalink_view.test.jsx.snap
  components/select_team/__snapshots__/select_team.test.jsx.snap
  components/select_team/components/__snapshots__/select_team_item.test.jsx.snap
  components/sidebar/sidebar.jsx
  components/sidebar/sidebar_channel/index.js
  components/sidebar/sidebar_channel_button_or_link/__snapshots__/sidebar_channel_button_or_link.test.jsx.snap
  components/signup/signup_controller/__snapshots__/signup_controller.test.jsx.snap
  components/textbox/index.js
  components/widgets/admin_console/admin_panel_with_link.test.jsx
  components/widgets/menu/menu_items/menu_item_link.test.jsx
  package-lock.json
  package.json
Labels: 2: Dev Review

#2616 Fixing MM-14886 without moving back the input inside the menu
  components/file_upload/file_upload.jsx
  sass/layout/_post.scss
Labels: 2: Dev Review, CherryPickApproved

#2622 Revert virtualised and auto load of posts
  actions/global_actions.jsx
  actions/post_actions.jsx
  actions/post_actions.test.js
  components/create_post/create_post.test.jsx
  components/create_post/index.js
  components/permalink_view/__snapshots__/permalink_view.test.jsx.snap
  components/post_view/floating_timestamp.jsx
  components/post_view/index.js
  components/post_view/message_attachments/message_attachment/message_attachment.jsx
  components/post_view/message_attachments/message_attachment/message_attachment.test.jsx
  components/post_view/new_message_separator/__snapshots__/new_message_separator.test.jsx.snap
  components/post_view/new_message_separator/new_message_separator.jsx
  components/post_view/new_message_separator/new_message_separator.test.jsx
  components/post_view/post/index.js
  components/post_view/post/post.jsx
  components/post_view/post_attachment_opengraph/post_attachment_opengraph.jsx
  components/post_view/post_header/post_header.jsx
  components/post_view/post_image/post_image.jsx
  components/post_view/post_info/post_info.jsx
  components/post_view/post_info/post_info.test.jsx
  components/post_view/post_list.jsx
  components/post_view/post_list.test.jsx
  components/post_view/post_list_row/__snapshots__/post_list_row.test.jsx.snap
  components/post_view/post_list_row/index.js
  components/post_view/post_list_row/post_list_row.jsx
  components/post_view/post_list_row/post_list_row.test.jsx
  components/post_view/post_message_view/post_message_view.jsx
  components/post_view/post_message_view/post_message_view.test.jsx
  components/post_view/reaction_list/reaction_list.jsx
  components/sidebar_right/sidebar_right.jsx
  components/widgets/menu/menu_wrapper.jsx
  package-lock.json
  package.json
  sass/components/_videos.scss
  sass/layout/_post.scss
  selectors/posts.js
  utils/constants.jsx
  utils/event_types.jsx
  utils/global_event_emitter.jsx
  utils/post_utils.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2590 MM-12949 - Updating team sidebar and plugins
  components/team_sidebar/team_sidebar_controller.jsx
  sass/layout/_team-sidebar.scss
  utils/utils.jsx
Labels: 3: Ready to Merge

#2617 Fixing remove list/join public/private teams on save permission in the admin console
  utils/constants.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2623 [MM-14881] Migrates getSuggestion functions to mattermost-redux
  components/suggestion/at_mention_provider/at_mention_provider.jsx
  package-lock.json
  package.json
  utils/utils.jsx
  utils/utils.test.jsx
Labels: 3: Ready to Merge, Awaiting PR, CherryPickApproved

#2619 MM-14888 - Updating sidebar menu
  sass/layout/_sidebar-menu.scss
Labels: 2: Dev Review, CherryPickApproved

#2618 MM-14943: Improve descriptions of emojis permissions
  i18n/en.json
Labels: 3: Ready to Merge, CherryPickApproved

#2610 add check i18n to the pipeline
  Makefile
  build/Jenkinsfile
  i18n/en.json
  package-lock.json
  package.json
Labels: 3: Ready to Merge

#2603 MM-14755/14756: Hides links and buttons to 'remove from team' and 're…
  components/admin_console/manage_teams_modal/manage_teams_dropdown.jsx
  components/channel_members_dropdown/__snapshots__/channel_members_dropdown.test.jsx.snap
  components/channel_members_dropdown/channel_members_dropdown.jsx
  components/channel_members_dropdown/channel_members_dropdown.test.jsx
  components/channel_members_dropdown/index.js
  components/team_members_dropdown/__snapshots__/team_members_dropdown.test.jsx.snap
  components/team_members_dropdown/index.js
  components/team_members_dropdown/team_members_dropdown.jsx
  components/team_members_dropdown/team_members_dropdown.test.jsx
Labels: 3: Ready to Merge

#2627 translations PR 20190408
  i18n/de.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 2: Dev Review

#2631 Revert "MM-12949 - Updating team sidebar and plugins (#2590)"
  components/team_sidebar/team_sidebar_controller.jsx
  sass/layout/_team-sidebar.scss
  utils/utils.jsx
Labels: 3: Ready to Merge

#2624 MM-14351: Removing combination of words inside translation strings
  components/post_view/channel_intro_message/channel_intro_message.jsx
  i18n/en.json
Labels: 3: Ready to Merge

#2621 MM-14860 Localization for client plugins.
  actions/views/root.js
  components/intl_provider/intl_provider.jsx
  components/root/root.jsx
  plugins/index.js
  plugins/registry.js
  reducers/views/i18n.js
Labels: 2: Dev Review

#2626 MM-14932 Focus logs list on mount
  components/admin_console/server_logs/log_list.jsx
Labels: 2: Dev Review, CherryPickApproved

#2625 MM-14138: Allowing to exclude permissions from the roles edition
  components/admin_console/permission_schemes_settings/permission_system_scheme_settings/permission_system_scheme_settings.jsx
  components/admin_console/permission_schemes_settings/permission_team_scheme_settings/permission_team_scheme_settings.jsx
  package-lock.json
  package.json
Labels: 3: Ready to Merge

#2620 MM-14896 Add rootCapture=true to MenuWrapper listeners
  components/widgets/menu/menu_wrapper.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2636 [MM-15039] Revert react-redux to 5.1.1 fixing the issue mostly on profile pop-over and edit channel header components
  components/create_comment/create_comment.jsx
  components/create_comment/create_comment.test.jsx
  components/create_post/create_post.jsx
  components/create_post/create_post.test.jsx
  components/edit_channel_header_modal/edit_channel_header_modal.jsx
  components/edit_post_modal/edit_post_modal.jsx
  components/file_upload/index.js
  components/sidebar/sidebar.jsx
  components/sidebar/sidebar_channel/index.js
  components/textbox/index.js
  package-lock.json
  package.json
Labels: 2: Dev Review

#2639 MM-15041 Fix for center channel to be at last post when textbox expands
  components/textbox/textbox.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2652 MM-14778 - Updating attachment dropdown menu
  components/file_upload/file_upload.jsx
  sass/responsive/_mobile.scss
  sass/widgets/menu/_menu_wrapper.scss
  utils/utils.jsx
Labels: 2: Dev Review, CherryPickApproved

#2646 MM-15068: Impossible to join directly to team by url if is not in the first 200 visible teams
  components/needs_team/index.js
  components/needs_team/needs_team.jsx
  components/needs_team/needs_team.test.jsx
Labels: 2: Dev Review, CherryPickApproved

#2648 MM-15061: Restoring view members in default channels and archived channels
  components/channel_header_dropdown/channel_header_dropdown_items.js
Labels: 3: Ready to Merge, CherryPickApproved

#2644 MM-14978 - Updating login page for fixed banner
  sass/routes/_signup.scss
Labels: 3: Ready to Merge, CherryPickApproved

#2613 MM-8647 Have HelpText use FormattedMarkdownMessage's renderer
  components/__snapshots__/formatted_markdown_message.test.jsx.snap
  components/admin_console/help_text.jsx
  components/admin_console/help_text.test.jsx
  components/formatted_markdown_message.jsx
  components/formatted_markdown_message.test.jsx
Labels: 2: Dev Review

#2651 MM-14929 Fix shortened image links not showing a preview
  components/post_view/post_body_additional_content/post_body_additional_content.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2588 [MM-14534] Re-organize System Console into new sections
  components/admin_console/__snapshots__/admin_console.test.jsx.snap
  components/admin_console/admin_console.jsx
  components/admin_console/admin_console.test.jsx
  components/admin_console/admin_definition.jsx
  components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.jsx.snap
  components/admin_console/admin_sidebar/admin_sidebar.jsx
  components/admin_console/admin_sidebar/admin_sidebar.test.jsx
  components/admin_console/email_settings.jsx
  components/admin_console/index.js
  components/admin_console/push_settings.jsx
  i18n/en.json
  sass/routes/_admin-console.scss
  utils/admin_console_index.jsx
  utils/admin_console_index.test.jsx
Labels: 3: Ready to Merge

#2642 MM-15053 - Updating menu styling
  sass/widgets/menu/_menu_item.scss
  utils/utils.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2598 [MM-14633] Add E2E to leave all teams
  components/leave_team_modal/__snapshots__/leave_team_modal.test.jsx.snap
  components/leave_team_modal/leave_team_modal.jsx
  components/select_team/select_team.jsx
  cypress/integration/team/teams_spec.js
  cypress/support/api_commands.js
  cypress/support/ui_commands.js
Labels: 3: Ready to Merge

#2654 MM-14845 Fix for 4.10
  tests/utils/policy_roles_adapter.test.jsx
  utils/policy_roles_adapter.js
Labels: 3: Ready to Merge

#2657 MM-14875 - Fixing line height for menu items
  sass/widgets/menu/_menu_item.scss
Labels: 3: Ready to Merge, CherryPickApproved

#2658 MM-14713 - Updating help text security panel
  components/user_settings/security/user_settings_security.jsx
Labels: 2: Dev Review, CherryPickApproved

#2655 MM-14484 Remove download attribute from Open external image link
  components/view_image/popover_bar/__snapshots__/popover_bar.test.jsx.snap
  components/view_image/popover_bar/popover_bar.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2609 Reorganize post state and make postsInChannel into a sparse array
  actions/integration_actions.test.js
  actions/post_actions.jsx
  actions/post_actions.test.js
  actions/post_utils.js
  actions/post_utils.test.js
  actions/status_actions.jsx
  actions/status_actions.test.js
  actions/views/channel.js
  actions/views/channel.test.js
  actions/views/create_comment.jsx
  actions/views/create_comment.test.jsx
  actions/views/rhs.js
  actions/views/rhs.test.js
  actions/websocket_actions.jsx
  components/channel_header/channel_header.js
  components/create_post/create_post.jsx
  components/create_post/index.js
  components/post_view/combined_user_activity_post/index.js
  components/post_view/date_separator/date_separator.jsx
  components/post_view/floating_timestamp/floating_timestamp.jsx
  components/post_view/floating_timestamp/index.js
  components/post_view/index.js
  components/post_view/new_messages_below/index.js
  components/post_view/new_messages_below/index.test.js
  components/post_view/new_messages_below/new_messages_below.jsx
  components/post_view/post/index.js
  components/post_view/post/index.test.js
  components/post_view/post_list.jsx
  components/post_view/post_list.test.jsx
  components/post_view/post_list_row/__snapshots__/post_list_row.test.jsx.snap
  components/post_view/post_list_row/post_list_row.jsx
  components/post_view/post_list_row/post_list_row.test.jsx
  components/rhs_thread/rhs_thread.jsx
  package-lock.json
  package.json
  reducers/views/channel.js
  reducers/views/rhs.js
  reducers/views/rhs.test.js
  selectors/posts.js
  utils/constants.jsx
  utils/post_utils.jsx
Labels: 3: Ready to Merge, Major Change

#2664 MM-15107 - Updating emoji picker on mobile
  components/emoji_picker/emoji_picker_tabs.jsx
  sass/responsive/_mobile.scss
Labels: 3: Ready to Merge, CherryPickApproved

#2592 [MM-14681] In integrations backstage, no feedback to user when search returns no results
  components/backstage/components/backstage_list.jsx
  components/integrations/bots/bot.jsx
  components/integrations/bots/bots.jsx
  components/integrations/bots/bots.test.jsx
  components/integrations/installed_command.jsx
  components/integrations/installed_commands/installed_commands.jsx
  components/integrations/installed_incoming_webhook.jsx
  components/integrations/installed_incoming_webhooks/installed_incoming_webhooks.jsx
  components/integrations/installed_oauth_app/installed_oauth_app.jsx
  components/integrations/installed_oauth_apps/__snapshots__/installed_oauth_apps.test.jsx.snap
  components/integrations/installed_oauth_apps/installed_oauth_apps.jsx
  components/integrations/installed_oauth_apps/installed_oauth_apps.test.jsx
  components/integrations/installed_outgoing_webhook.jsx
  components/integrations/installed_outgoing_webhook.test.jsx
  components/integrations/installed_outgoing_webhooks/__snapshots__/installed_outgoing_webhooks.test.jsx.snap
  components/integrations/installed_outgoing_webhooks/installed_outgoing_webhooks.jsx
  components/integrations/installed_outgoing_webhooks/installed_outgoing_webhooks.test.jsx
  cypress/integration/integrations/intergrations_spec.js
  cypress/support/ui_commands.js
  i18n/en.json
Labels: 2: Dev Review

#2667 Revert "MM-14778 - Updating attachment dropdown menu (#2652)"
  components/file_upload/file_upload.jsx
  sass/responsive/_mobile.scss
  sass/widgets/menu/_menu_wrapper.scss
  utils/utils.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2542 Creating the concept of RedirectChannel and use it before the DefaultChannel when we are redirecting the user
  actions/command.js
  actions/views/channel.js
  actions/views/channel.test.js
  actions/websocket_actions.jsx
  components/admin_console/admin_navbar_dropdown/admin_navbar_dropdown.jsx
  components/channel_header_dropdown/index.js
  components/channel_layout/channel_identifier_router/actions.js
  components/create_team/components/team_url/team_url.jsx
  components/login/login_controller/login_controller.jsx
  components/login/login_controller/login_controller.test.jsx
  components/select_team/select_team.jsx
  components/sidebar/sidebar.jsx
  components/sidebar/sidebar.test.jsx
  components/sidebar/sidebar_channel/index.js
  components/sidebar/sidebar_channel/sidebar_channel.jsx
  components/sidebar/sidebar_channel/sidebar_channel.test.jsx
  package-lock.json
  package.json
  stores/local_storage_store.jsx
  utils/channel_utils.jsx
  utils/utils.jsx
Labels: 3: Ready to Merge

#2647 MM-14417: Add messaging for channel mentions of users not in constrained groups.
  components/post_markdown/system_message_helpers.jsx
  components/post_view/post_add_channel_member/__snapshots__/post_add_channel_member.test.jsx.snap
  components/post_view/post_add_channel_member/post_add_channel_member.jsx
  components/post_view/post_add_channel_member/post_add_channel_member.test.jsx
  i18n/en.json
Labels: 3: Ready to Merge, Awaiting PR

#2668 MM-15706 Fetch plugin manifests after uploading a new plugin
  components/admin_console/plugin_management/index.js
  components/admin_console/plugin_management/plugin_management.jsx
  components/admin_console/plugin_management/plugin_management.test.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2660 [MM-14842] fix dismissing the tooltip when clicking the button
  components/link_tooltip/link_tooltip.jsx
Labels: 2: Dev Review

#2522 MM-13542 Cypress test for Open edit modal immediately after making a …
  components/edit_post_modal/__snapshots__/edit_post_modal.test.jsx.snap
  components/edit_post_modal/edit_post_modal.jsx
  cypress/integration/channel/edit_message_spec.js
Labels: 3: Ready to Merge

#2674 MM-15082 - Updating post list spacing
  components/post_view/post_list.jsx
  sass/layout/_post.scss
Labels: 2: Dev Review

#2670 MM-14707 Open dropdowns near the bottom of user lists upwards
  components/admin_console/system_users/system_users_dropdown/system_users_dropdown.jsx
  components/admin_console/system_users/system_users_dropdown/system_users_dropdown.test.js
  components/channel_members_dropdown/__snapshots__/channel_members_dropdown.test.jsx.snap
  components/channel_members_dropdown/channel_members_dropdown.jsx
  components/channel_members_dropdown/channel_members_dropdown.test.jsx
  components/team_members_dropdown/__snapshots__/team_members_dropdown.test.jsx.snap
  components/team_members_dropdown/team_members_dropdown.jsx
  components/team_members_dropdown/team_members_dropdown.test.jsx
  components/user_list.jsx
  components/user_list_row/user_list_row.jsx
  components/user_list_row_with_error/user_list_row_with_error.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2677 MM-14741 Add default option to post action dropdown
  components/post_view/message_attachments/action_menu/action_menu.jsx
  components/post_view/message_attachments/action_menu/action_menu.test.jsx
Labels: 3: Ready to Merge

#2662 [MM-14967] - Bot accounts are listed with an email address when adding a user to a team
  components/add_users_to_team/__snapshots__/add_users_to_team.test.jsx.snap
  components/add_users_to_team/add_users_to_team.jsx
  components/add_users_to_team/add_users_to_team.test.jsx
Labels: 3: Ready to Merge

#2653 [MM-15077] Make the DOM structure of "Mute Channel" and "Leave Channel" be the same with other menu items at channel dropdown
  components/channel_header_dropdown/menu_items/leave_channel/leave_channel.js
  components/channel_header_dropdown/menu_items/toggle_mute_channel/toggle_mute_channel.js
  components/widgets/menu/menu_items/menu_item_action.jsx
  components/widgets/menu/menu_items/menu_item_action.test.jsx
Labels: 2: Dev Review

#2656 [MM-15027] Consistent urls in System Console, fix urls in schemas
  components/admin_console/__snapshots__/admin_console.test.jsx.snap
  components/admin_console/admin_definition.jsx
  components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.jsx.snap
  components/admin_console/admin_sidebar/admin_sidebar.jsx
  components/admin_console/custom_terms_of_service_settings/custom_terms_of_service_settings.jsx
  components/admin_console/database_settings.jsx
  components/admin_console/permission_schemes_settings/__snapshots__/permission_schemes_settings.test.jsx.snap
  components/admin_console/permission_schemes_settings/permission_schemes_settings.jsx
  components/admin_console/permission_schemes_settings/permission_system_scheme_settings/__snapshots__/permission_system_scheme_settings.test.jsx.snap
  components/admin_console/permission_schemes_settings/permission_system_scheme_settings/permission_system_scheme_settings.jsx
  components/admin_console/permission_schemes_settings/permission_team_scheme_settings/__snapshots__/permission_team_scheme_settings.test.jsx.snap
  components/admin_console/permission_schemes_settings/permission_team_scheme_settings/permission_team_scheme_settings.jsx
  components/admin_console/permission_schemes_settings/permissions_scheme_summary/__snapshots__/permissions_scheme_summary.test.jsx.snap
  components/admin_console/permission_schemes_settings/permissions_scheme_summary/permissions_scheme_summary.jsx
  components/admin_console/plugin_management/plugin_management.jsx
  i18n/en.json
  utils/admin_console_index.test.jsx
Labels: 3: Ready to Merge

#2661 [MM-14356] Add i18n string IDs for notification levels
  components/channel_notifications_modal/components/describe.jsx
  i18n/en.json
Labels: 3: Ready to Merge, CherryPickApproved

#2688 translations PR 20190422
  i18n/de.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 2: Dev Review

#2691 [MM-15170] Fix admin console urls and system-scheme permission
  components/admin_console/group_settings/__snapshots__/group_row.test.jsx.snap
  components/admin_console/group_settings/group_row.jsx
Labels: 3: Ready to Merge

#2685 [MM-15195] Bot account can be edited even though it's managed by a plugin
  components/integrations/bots/bot.jsx
  components/integrations/bots/bot.test.jsx
Labels: 3: Ready to Merge

#2643 MM-15019 - Updating post spacing in compact view
  sass/responsive/_tablet.scss
Labels: 3: Ready to Merge, CherryPickApproved

#2645 MM-14872 - Updating autocomplete positioning
  sass/layout/_post.scss
  sass/responsive/_mobile.scss
Labels: 3: Ready to Merge, CherryPickApproved

#2681 MM-15125 - Updating wrapper animation on mobile
  components/widgets/menu/menu_wrapper_animation.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2612 MM-14714 - Updating textarea preview
  sass/layout/_post.scss
Labels: 3: Ready to Merge, CherryPickApproved

#2682 MM-15175 - Updating border-radius for images
  sass/components/_files.scss
Labels: 2: Dev Review, CherryPickApproved

#2435 [MM-12396] Option to add user to a channel from the profile pop-over (permissions fix)
  components/profile_popover/__snapshots__/profile_popover.test.jsx.snap
  components/profile_popover/index.js
  components/profile_popover/profile_popover.jsx
  components/profile_popover/profile_popover.test.jsx
  components/suggestion/search_channel_with_permissions_provider.jsx
Labels: 2: Dev Review

#2577 [MM-14577] add E2E test for toggling pinned badge in center and RHS
  components/dot_menu/__snapshots__/dot_menu.test.jsx.snap
  components/dot_menu/dot_menu.jsx
  cypress/integration/post_header/post_header_spec.js
Labels: 3: Ready to Merge

#2663 MM-14635 Automated test using cypress for Channel name already exists
  components/new_channel_modal/__snapshots__/new_channel_modal.test.jsx.snap
  components/new_channel_modal/new_channel_modal.jsx
  cypress/integration/onboarding/multi_team/existing_channel_name_spec.js
Labels: 3: Ready to Merge

#2694 Do not open user list dropdowns upwards for short lists
  components/admin_console/system_users/system_users_dropdown/system_users_dropdown.jsx
  components/channel_members_dropdown/channel_members_dropdown.jsx
  components/team_members_dropdown/team_members_dropdown.jsx
Labels: 2: Dev Review, CherryPickApproved

#2683 MM-15177 - Updating image shadow
  sass/components/_files.scss
Labels: 3: Ready to Merge, CherryPickApproved

#2701 MM-14951 - Updating badge line-height
  sass/components/_badge.scss
Labels: 3: Ready to Merge, CherryPickApproved

#2584 [MM-13671] Change Team InviteId Change Workflow
  components/team_general_tab/index.js
  components/team_general_tab/team_general_tab.jsx
  components/team_general_tab/team_general_tab.test.jsx
  package.json
Labels: 3: Ready to Merge, CherryPickApproved

#2696 MM-15046: Adding AnyTeamPermissionGate and used with emojis permissions
  components/emoji/emoji_list_item/emoji_list_item.jsx
  components/emoji/emoji_page.jsx
  components/permissions_gates/any_team_permission_gate/__snapshots__/any_team_permission_gate.test.jsx.snap
  components/permissions_gates/any_team_permission_gate/any_team_permission_gate.jsx
  components/permissions_gates/any_team_permission_gate/any_team_permission_gate.test.jsx
  components/permissions_gates/any_team_permission_gate/index.js
Labels: 3: Ready to Merge, CherryPickApproved

#2703 MM-15174 - Updating help text css
  sass/components/_inputs.scss
  utils/utils.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2684 MM-14456 Show search loading indicator until we have no more posts to load to avoid scroll pop
  components/search_results/index.jsx
  components/search_results/search_results.jsx
  package-lock.json
Labels: 2: Dev Review, CherryPickApproved

#2650 [MM-15073] Hide bot accounts from System Console > Users
  components/admin_console/system_users/list/index.js
  components/admin_console/system_users/list/selectors.jsx
  components/admin_console/system_users/list/system_users_list.jsx
  components/admin_console/system_users/system_users_dropdown/system_users_dropdown.jsx
Labels: 3: Ready to Merge

#2699 Quick fix on flaky E2E specs
  components/team_members_dropdown/__snapshots__/team_members_dropdown.test.jsx.snap
  components/team_members_dropdown/team_members_dropdown.jsx
  components/team_members_dropdown/team_members_dropdown.test.jsx
  cypress/integration/channel/header_spec.js
  cypress/integration/channel/message_spec.js
  cypress/integration/system_console/demoted_user_spec.js
  cypress/integration/team/teams_spec.js
  cypress/support/ui_commands.js
Labels: 2: Dev Review

#2704 MM-14931 Fix markdown checkboxes not being rendered correctly after post edits
  utils/message_html_to_component.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2713 Hide loading indicator for pinned and flagged posts
  components/search_results/search_results.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2671 MM-14634 Adding automated UI test using cypress for Email Address Alr…
  components/select_team/__snapshots__/select_team.test.jsx.snap
  components/select_team/select_team.jsx
  components/signup/signup_email/signup_email.jsx
  cypress/fixtures/config.json
  cypress/integration/onboarding/email/existing_email_adress_spec.js
  cypress/support/api_commands.js
Labels: 2: Dev Review

#2678 MM-14572 Add e2e test for @channel, @all, and @here at-mentions
  cypress/integration/at_mentions/at_mentions_spec.js
Labels: 3: Ready to Merge

#2698 MM-15236 - Updating dropdown icon label
  components/channel_header/__snapshots__/channel_header.test.jsx.snap
  components/channel_header/channel_header.js
  sass/components/_admin-sidebar-header.scss
Labels: 3: Ready to Merge, CherryPickApproved

#2629 [MM-14764] Show file upload options in mobile view
  components/file_upload/file_upload.jsx
  components/widgets/menu/menu.jsx
  sass/responsive/_mobile.scss
Labels: 2: Dev Review, CherryPickApproved

#2712 MM-15285: Fixing IE11 initialization problems
  package-lock.json
  package.json
  plugins/index.js
Labels: 3: Ready to Merge

#2702 MM-15161 show bot badge and icon for ephemeral posts from bots
  components/post_profile_picture/index.jsx
  components/post_profile_picture/post_profile_picture.jsx
  components/post_view/post_header/post_header.jsx
Labels: 3: Ready to Merge

#2706 Adding root portal (used later by new invitation modal
  components/root_portal.jsx
  root.html
Labels: 3: Ready to Merge

#2687 MM-14949 Correct scroll when new posts are loaded
  components/file_attachment/__snapshots__/file_attachment.test.jsx.snap
  components/post_view/post_list.jsx
  components/post_view/post_list.test.jsx
  components/post_view/show_more/show_more.jsx
  package-lock.json
  package.json
  sass/layout/_post.scss
Labels: 3: Ready to Merge

#2697 add circleci
  .circleci/config.yml
  Makefile
  build/Jenkinsfile
  package.json
Labels: 2: Dev Review

#2724 MM-15200: Only show permissions schemes prompt when adding a team in …
  components/admin_console/permission_schemes_settings/permission_team_scheme_settings/permission_team_scheme_settings.jsx
  components/team_selector_modal/team_selector_modal.jsx
  utils/constants.jsx
Labels: 2: Dev Review

#2728 MM-15080 Use event emitter to scroll to bottom when sending post
  actions/views/channel.js
  components/create_post/create_post.jsx
  components/create_post/create_post.test.jsx
  components/create_post/index.js
  components/post_view/post_list.jsx
Labels: 2: Dev Review

#2700 Removing unnused files
  actions/oauth_actions.jsx
  components/admin_console/post_edit_setting.jsx
  components/announcement_bar/text_button_with_spinner.jsx
  i18n/en.json
Labels: 2: Dev Review
