Repository mattermost/mattermost-webapp, pull requests merged in 2019-09, with the labels that each got.

#3493 MM-17653 Remove metadata call for youtube links
  components/post_view/post_body_additional_content/__snapshots__/post_body_additional_content.test.jsx.snap
  components/post_view/post_body_additional_content/post_body_additional_content.jsx
  components/youtube_video/__snapshots__/youtube_video.test.jsx.snap
  components/youtube_video/index.js
  components/youtube_video/youtube_video.jsx
  components/youtube_video/youtube_video.test.jsx
  i18n/en.json
  sass/components/_videos.scss
  sass/responsive/_mobile.scss
Labels: 3: Reviews Complete, CherryPick/Approved

#3526 [MM-17067] reorder dot menu items
  components/dot_menu/__snapshots__/dot_menu.test.jsx.snap
  components/dot_menu/dot_menu.jsx
  components/dot_menu/dot_menu.test.jsx
  components/post_view/new_messages_below/index.js
  components/post_view/post_list/index.js
  components/widgets/menu/menu_items/menu_item_action.jsx
  sass/widgets/menu/_menu_item.scss
Labels: 3: Reviews Complete, Do Not Merge/Awaiting PR

#3579 Automated cherry pick of #3493
  components/post_view/post_body_additional_content/__snapshots__/post_body_additional_content.test.jsx.snap
  components/post_view/post_body_additional_content/post_body_additional_content.jsx
  components/youtube_video/__snapshots__/youtube_video.test.jsx.snap
  components/youtube_video/index.js
  components/youtube_video/youtube_video.jsx
  components/youtube_video/youtube_video.test.jsx
  i18n/en.json
  sass/components/_videos.scss
  sass/responsive/_mobile.scss
Labels: AutomatedCherryPick/Done

#3558 [MM-18118] Check locale is valid before sending to intl_provider
  selectors/i18n.js
  selectors/i18n.test.js
Labels: 3: Reviews Complete, CherryPick/Approved

#2794 Adding admin console plugins
  actions/admin_actions.jsx
  actions/admin_actions.test.js
  actions/websocket_actions.test.jsx
  components/admin_console/admin_console.jsx
  components/admin_console/admin_console.test.jsx
  components/admin_console/admin_definition.jsx
  components/admin_console/admin_definition.test.jsx
  components/admin_console/admin_sidebar/admin_sidebar.jsx
  components/admin_console/admin_sidebar/admin_sidebar.test.jsx
  components/admin_console/admin_sidebar/index.js
  components/admin_console/index.js
  plugins/index.js
  plugins/registry.js
  reducers/plugins/index.js
  selectors/admin_console.jsx
  selectors/admin_console.test.jsx
  utils/admin_console_index.jsx
  utils/admin_console_index.test.jsx
  utils/constants.jsx
Labels: 3: Reviews Complete

#3553 [MM-18016] Fix TAB key behaviour in guests invitation modal
  components/invitation_modal/__snapshots__/invitation_modal_guests_step.test.jsx.snap
  components/invitation_modal/invitation_modal_guests_step.jsx
Labels: 3: Reviews Complete

#3554 [MM-17923] Fix Guest Badge alignment when long username/fullname wraps
  components/invitation_modal/invitation_modal_confirm_step_row.jsx
  components/invitation_modal/invitation_modal_confirm_step_row.scss
Labels: 3: Reviews Complete

#3555 [MM-17924] Update message when an existing guest user is added to a single channel
  actions/invite_actions.jsx
  actions/invite_actions.test.js
  components/invitation_modal/__snapshots__/invitation_modal_confirm_step_row.test.jsx.snap
  components/invitation_modal/invitation_modal_confirm_step_row.jsx
  components/invitation_modal/invitation_modal_confirm_step_row.test.jsx
  i18n/en.json
Labels: 3: Reviews Complete

#3565 add user id to be show in the user page in the system console
  components/admin_console/system_users/list/__snapshots__/system_users_list.test.jsx.snap
  components/admin_console/system_users/list/system_users_list.jsx
  i18n/en.json
Labels: 3: Reviews Complete

#3574 Automated cherry pick of #3551
  components/create_comment/__snapshots__/create_comment.test.jsx.snap
  components/create_comment/create_comment.jsx
  components/multiselect/__snapshots__/multiselect.test.jsx.snap
  components/multiselect/multiselect.jsx
  utils/a11y_controller.js
Labels: AutomatedCherryPick/Done

#3586 Automated cherry pick of #3558
  selectors/i18n.js
  selectors/i18n.test.js
Labels: AutomatedCherryPick/Done

#3514 MM-17518 Incoming Webhook URL on the Desktop should not be clickable
  components/integrations/confirm_integration/__snapshots__/confirm_integration.test.jsx.snap
  components/integrations/confirm_integration/confirm_integration.jsx
Labels: 1: PM Review, CherryPick/Approved

#3591 Automated cherry pick of #3514
  components/integrations/confirm_integration/__snapshots__/confirm_integration.test.jsx.snap
  components/integrations/confirm_integration/confirm_integration.jsx
Labels: AutomatedCherryPick/Done

#3590 [MM-17406] Fixed channel switcher setting so that it shows the real setting on exit
  components/user_settings/sidebar/user_settings_sidebar.jsx
Labels: 3: Reviews Complete, CherryPick/Approved

#3432 MM-11359: add hint text for search exclusion
  components/search_hint/__snapshots__/search_hint.test.jsx.snap
  components/search_hint/search_hint.jsx
  i18n/en.json
Labels: 3: Reviews Complete

#3474 [MM-17397] Moved SettingItemMin to redux to use it to keep track of active section to focus edit button
  actions/views/settings.js
  components/channel_notifications_modal/components/__snapshots__/collapse_view.test.jsx.snap
  components/channel_notifications_modal/components/collapse_view.jsx
  components/setting_item_min/__snapshots__/setting_item_min.test.jsx.snap
  components/setting_item_min/index.js
  components/setting_item_min/setting_item_min.jsx
  components/setting_item_min/setting_item_min.test.jsx
  components/team_general_tab/__snapshots__/team_general_tab.test.jsx.snap
  components/team_general_tab/team_general_tab.jsx
  components/user_settings/advanced/join_leave_section/__snapshots__/join_leave_section.test.jsx.snap
  components/user_settings/advanced/join_leave_section/join_leave_section.jsx
  components/user_settings/advanced/join_leave_section/join_leave_section.test.jsx
  components/user_settings/advanced/user_settings_advanced.jsx
  components/user_settings/display/__snapshots__/user_settings_display.test.jsx.snap
  components/user_settings/display/user_settings_display.jsx
  components/user_settings/display/user_settings_display.test.jsx
  components/user_settings/display/user_settings_theme/__snapshots__/user_settings_theme.test.jsx.snap
  components/user_settings/display/user_settings_theme/user_settings_theme.jsx
  components/user_settings/general/user_settings_general.jsx
  components/user_settings/general/user_settings_general.test.js
  components/user_settings/modal/user_settings_modal.jsx
  components/user_settings/notifications/__snapshots__/desktop_notification_settings.test.jsx.snap
  components/user_settings/notifications/desktop_notification_settings.jsx
  components/user_settings/notifications/email_notification_setting/__snapshots__/email_notification_setting.test.jsx.snap
  components/user_settings/notifications/email_notification_setting/email_notification_setting.jsx
  components/user_settings/notifications/user_settings_notifications.jsx
  components/user_settings/notifications/user_settings_notifications.test.js
  components/user_settings/security/mfa_section/__snapshots__/mfa_section.test.jsx.snap
  components/user_settings/security/mfa_section/mfa_section.jsx
  components/user_settings/security/user_access_token_section/user_access_token_section.jsx
  components/user_settings/security/user_settings_security.jsx
  components/user_settings/sidebar/__snapshots__/user_settings_sidebar.test.jsx.snap
  components/user_settings/sidebar/user_settings_sidebar.jsx
  components/user_settings/sidebar/user_settings_sidebar.test.jsx
  components/user_settings/user_settings.jsx
  reducers/views/index.js
  reducers/views/settings.js
  selectors/views/settings.js
  utils/constants.jsx
Labels: 3: Reviews Complete, CherryPick/Approved

#3592 [MM-17975] Updating redux hash
  package-lock.json
  package.json
Labels: 3: Reviews Complete

#3492 MM-17023 - Integrations Marketplace
  components/integrations_marketplace/index.js
  components/integrations_marketplace/marketplace_item/index.js
  components/integrations_marketplace/marketplace_item/marketplace_item.jsx
  components/integrations_marketplace/marketplace_modal.jsx
  components/integrations_marketplace/marketplace_modal.scss
  components/main_menu/__snapshots__/main_menu.test.jsx.snap
  components/main_menu/index.jsx
  components/main_menu/main_menu.jsx
  components/main_menu/main_menu.test.jsx
  components/widgets/icons/plugin_icon.jsx
  i18n/en.json
  package-lock.json
  package.json
  plugins/test/__snapshots__/main_menu_action.test.jsx.snap
  plugins/test/main_menu_action.test.jsx
  sass/base/_css_variables.scss
  sass/components/_modal.scss
  utils/constants.jsx
  utils/utils.jsx
Labels: 3: Reviews Complete

#3356 Emojis show as jumbo in main thread - Multi emoji
  e2e/cypress/integration/messaging/emoji_size_spec.js
Labels: 3: Reviews Complete

#3575 Mm 18093 system console plugin enable
  components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
  components/admin_console/custom_plugin_settings/__snapshots__/custom_plugin_settings.test.jsx.snap
  components/admin_console/custom_plugin_settings/custom_plugin_settings.jsx
  components/admin_console/custom_plugin_settings/custom_plugin_settings.test.jsx
  components/admin_console/custom_plugin_settings/index.js
  components/admin_console/schema_admin_settings.jsx
  components/admin_console/schema_admin_settings.test.jsx
  i18n/en.json
Labels: 3: Reviews Complete, Tests/Done

#3573 Fixing Discard changes submodal z-index on invitation modal
  components/widgets/modals/full_screen_modal.scss
Labels: 3: Reviews Complete

#3600 MM-18139 - Add signature_url param when invoking install_from_url api
  components/integrations_marketplace/marketplace_item/marketplace_item.jsx
  components/integrations_marketplace/marketplace_modal.jsx
  package-lock.json
  package.json
Labels: 2: Dev Review

#3528 MM-16683: leverage /_redirect/integrations/bots
  components/admin_console/admin_definition.jsx
  components/admin_console/group_settings/group_details/__snapshots__/group_users.test.jsx.snap
  components/admin_console/group_settings/group_details/group_users.jsx
  components/admin_console/system_users/system_users_dropdown/__snapshots__/system_users_dropdown.test.js.snap
  components/admin_console/system_users/system_users_dropdown/system_users_dropdown.jsx
  i18n/en.json
Labels: Tests/Done

#3593 Moving AdminPanel component scss code aside the component
  components/widgets/admin_console/admin_panel.scss
  components/widgets/admin_console/admin_panel.tsx
  sass/components/_admin-panel.scss
  sass/components/_module.scss
  sass/widgets/_module.scss
Labels: 3: Reviews Complete

#3599 MM-18134 - Updating css for signup page
  sass/routes/_signup.scss
Labels: CherryPick/Approved

#3603 MM-18243 - Updating header description css
  sass/layout/_headers.scss
Labels: 2: Dev Review, CherryPick/Approved

#3594 [MM-17353] Wait for transition on RHS before rendering expensive sub components
  components/search_results/search_results.jsx
  components/sidebar_right/sidebar_right.jsx
Labels: 3: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server

#3606 Automated cherry pick of #3594
  components/search_results/search_results.jsx
  components/sidebar_right/sidebar_right.jsx
Labels: 3: Reviews Complete, AutomatedCherryPick/Done

#3585 Fix messsage > message typo
  i18n/en.json
Labels: 3: Reviews Complete, CherryPick/Approved

#3607 Automated cherry pick of #3585
  i18n/en.json
Labels: AutomatedCherryPick/Done

#3596 Automated cherry pick of #3474
  actions/views/settings.js
  components/channel_notifications_modal/components/__snapshots__/collapse_view.test.jsx.snap
  components/channel_notifications_modal/components/collapse_view.jsx
  components/setting_item_min/__snapshots__/setting_item_min.test.jsx.snap
  components/setting_item_min/index.js
  components/setting_item_min/setting_item_min.jsx
  components/setting_item_min/setting_item_min.test.jsx
  components/team_general_tab/__snapshots__/team_general_tab.test.jsx.snap
  components/team_general_tab/team_general_tab.jsx
  components/user_settings/advanced/join_leave_section/__snapshots__/join_leave_section.test.jsx.snap
  components/user_settings/advanced/join_leave_section/join_leave_section.jsx
  components/user_settings/advanced/join_leave_section/join_leave_section.test.jsx
  components/user_settings/advanced/user_settings_advanced.jsx
  components/user_settings/display/__snapshots__/user_settings_display.test.jsx.snap
  components/user_settings/display/user_settings_display.jsx
  components/user_settings/display/user_settings_display.test.jsx
  components/user_settings/display/user_settings_theme/__snapshots__/user_settings_theme.test.jsx.snap
  components/user_settings/display/user_settings_theme/user_settings_theme.jsx
  components/user_settings/general/user_settings_general.jsx
  components/user_settings/general/user_settings_general.test.js
  components/user_settings/modal/user_settings_modal.jsx
  components/user_settings/notifications/__snapshots__/desktop_notification_settings.test.jsx.snap
  components/user_settings/notifications/desktop_notification_settings.jsx
  components/user_settings/notifications/email_notification_setting/__snapshots__/email_notification_setting.test.jsx.snap
  components/user_settings/notifications/email_notification_setting/email_notification_setting.jsx
  components/user_settings/notifications/user_settings_notifications.jsx
  components/user_settings/notifications/user_settings_notifications.test.js
  components/user_settings/security/mfa_section/__snapshots__/mfa_section.test.jsx.snap
  components/user_settings/security/mfa_section/mfa_section.jsx
  components/user_settings/security/user_access_token_section/user_access_token_section.jsx
  components/user_settings/security/user_settings_security.jsx
  components/user_settings/sidebar/__snapshots__/user_settings_sidebar.test.jsx.snap
  components/user_settings/sidebar/user_settings_sidebar.jsx
  components/user_settings/sidebar/user_settings_sidebar.test.jsx
  components/user_settings/user_settings.jsx
  reducers/views/index.js
  reducers/views/settings.js
  selectors/views/settings.js
  utils/constants.jsx
Labels: AutomatedCherryPick/Done

#3597 MM-18169 - Updating post error css for RHS
  sass/layout/_sidebar-right.scss
  sass/responsive/_mobile.scss
Labels: 2: Dev Review, CherryPick/Approved

#3569 GH-11994: Add support for footer and footer_icon in attachments
  components/post_view/message_attachments/message_attachment/__snapshots__/message_attachment.test.jsx.snap
  components/post_view/message_attachments/message_attachment/message_attachment.jsx
  components/post_view/message_attachments/message_attachment/message_attachment.test.jsx
  sass/layout/_webhooks.scss
  utils/constants.jsx
Labels: 3: Reviews Complete

#3582 MM-17879 - Google User API Endpoint shows outdated helper text
  components/admin_console/admin_definition.jsx
Labels: 3: Reviews Complete, CherryPick/Approved

#3614 Automated cherry pick of #3582
  components/admin_console/admin_definition.jsx
Labels: AutomatedCherryPick/Done

#3580 MM-18185 Make quick switcher faster
  components/quick_switch_modal/__snapshots__/quick_switch_modal.test.jsx.snap
  components/quick_switch_modal/quick_switch_modal.jsx
  sass/components/_modal.scss
  sass/components/_suggestion-list.scss
Labels: 3: Reviews Complete

#3610 Automated cherry pick of #3597
  sass/layout/_sidebar-right.scss
  sass/responsive/_mobile.scss
Labels: AutomatedCherryPick/Done

#3605 Automated cherry pick of #3603
  sass/layout/_headers.scss
Labels: AutomatedCherryPick/Done

#3604 Automated cherry pick of #3599
  sass/routes/_signup.scss
Labels: AutomatedCherryPick/Done

#3584 deprecate lambda function to upload
  .circleci/config.yml
Labels: 3: Reviews Complete

#3620 Automated cherry pick of #3584
  .circleci/config.yml
Labels: AutomatedCherryPick

#3621 Automated cherry pick of #3584
  .circleci/config.yml
Labels: AutomatedCherryPick

#3622 Automated cherry pick of #3584
  .circleci/config.yml
Labels: AutomatedCherryPick

#3623 Automated cherry pick of #3584
  .circleci/config.yml
Labels: AutomatedCherryPick

#3625 remove request checks and clean up SDF tests
  e2e/cypress/integration/search/date_filter_spec.js
Labels: 2: Dev Review

#3598 MM-18175 - Updating system profile picture svg color
  sass/layout/_post.scss
Labels: 2: Dev Review, CherryPick/Approved

#3588 MM-18190 Fix markdown image overlap in compact view
  components/__snapshots__/markdown_image.test.jsx.snap
  components/markdown_image.jsx
  components/markdown_image.test.jsx
Labels: 3: Reviews Complete, CherryPick/Approved

#3627 Automated cherry pick of #3598
  sass/layout/_post.scss
Labels: AutomatedCherryPick

#3628 Automated cherry pick of #3588
  components/__snapshots__/markdown_image.test.jsx.snap
  components/markdown_image.jsx
  components/markdown_image.test.jsx
Labels: AutomatedCherryPick

#3577 [MM-17450] Focus to remain in RHS textbox each time Reply arrow is clicked
  e2e/cypress/integration/messaging/focus_move_spec.js
Labels: 3: Reviews Complete

#3608 MM-18204 Fix account settings not resetting on close
  components/user_settings/notifications/email_notification_setting/email_notification_setting.jsx
  components/user_settings/notifications/user_settings_notifications.jsx
  components/user_settings/notifications/user_settings_notifications.test.js
  components/user_settings/sidebar/user_settings_sidebar.jsx
  components/user_settings/sidebar/user_settings_sidebar.test.jsx
Labels: 3: Reviews Complete

#3612 MM-18251 Remove old unneeded scroll code and fix JS error
  components/create_comment/create_comment.jsx
Labels: 3: Reviews Complete

#3633 Fix failing E2E
  e2e/cypress/integration/login/tutorial_navigation_and_links_spec.js
  e2e/cypress/integration/search/post_search_display_spec.js
  e2e/cypress/integration/system_console/revoke_all_sessions_spec.js
  e2e/cypress/integration/team/teams_spec.js
Labels: 2: Dev Review

#3631 Fix failing E2E
  e2e/cypress/integration/channel/edit_message_spec.js
  e2e/cypress/integration/channel/header_spec.js
  e2e/cypress/integration/channel/message_spec.js
  e2e/cypress/integration/markdown/markdown_image_spec.js
  e2e/cypress/integration/markdown/markdown_text_spec.js
  e2e/cypress/integration/search/date_filter_spec.js
  e2e/cypress/support/api_commands.js
  e2e/cypress/support/ui_commands.js
Labels: 2: Dev Review

#3635 MM-17550 - Added search in the marketplace modal
  components/integrations_marketplace/marketplace_modal.jsx
  package-lock.json
  package.json
Labels: 3: Reviews Complete

#3629 MM-18340: restore dialog's store.subscribe
  actions/integration_actions.jsx
  plugins/export.js
  plugins/interactive_dialog.js
Labels: 3: Reviews Complete, CherryPick/Approved

#3645 Automated cherry pick of #3629
  actions/integration_actions.jsx
  plugins/export.js
  plugins/interactive_dialog.js
Labels: AutomatedCherryPick

#3637 Revert mm 18139
  components/integrations_marketplace/marketplace_item/marketplace_item.jsx
  components/integrations_marketplace/marketplace_modal.jsx
Labels: 3: Reviews Complete

#3611 Added telemetry events for plugin marketplace
  components/integrations_marketplace/marketplace_item/marketplace_item.jsx
  components/integrations_marketplace/marketplace_modal.jsx
Labels: 2: Dev Review

#3640 MM-17846: render plugin icon, if available
  components/integrations_marketplace/marketplace_item/__snapshots__/marketplace_item.test.jsx.snap
  components/integrations_marketplace/marketplace_item/marketplace_item.jsx
  components/integrations_marketplace/marketplace_item/marketplace_item.test.jsx
  components/integrations_marketplace/marketplace_modal.jsx
  components/integrations_marketplace/marketplace_modal.scss
Labels: 3: Reviews Complete

#3583 MM-15219 Added support for optional introduction text in interactive dialogs
  components/interactive_dialog/__snapshots__/dialog_introduction_text.test.jsx.snap
  components/interactive_dialog/dialog_introduction_text.jsx
  components/interactive_dialog/dialog_introduction_text.test.jsx
  components/interactive_dialog/index.js
  components/interactive_dialog/interactive_dialog.jsx
Labels: 3: Reviews Complete

#3638 translations PR 20190910
  i18n/de.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 3: Reviews Complete

#3647 Fix failing E2E due to pending post
  components/post_view/post/post.jsx
  e2e/cypress/integration/account_settings/display/message_display_mode_spec.js
  e2e/cypress/integration/interactive_menu/basic_options_spec.js
  e2e/cypress/support/index.js
  e2e/cypress/support/ui_commands.js
  e2e/package-lock.json
  e2e/package.json
Labels: 2: Dev Review

#3668 MM-18545 - Updating height for channel-header
  sass/layout/_headers.scss
Labels: 2: Dev Review, CherryPick/Approved

#3669 Automated cherry pick of #3668
  sass/layout/_headers.scss
Labels: AutomatedCherryPick

#3615 [MM 18370] UI polish/fixes
  components/__snapshots__/autosize_textarea.test.jsx.snap
  components/__snapshots__/profile_picture.test.jsx.snap
  components/__snapshots__/unread_channel_indicator.test.jsx.snap
  components/autosize_textarea.jsx
  components/profile_picture.jsx
  components/team_sidebar/components/team_button.jsx
  components/unread_channel_indicator.jsx
  components/widgets/icons/unread_below_icon.jsx
  root.html
  sass/components/_popover.scss
  sass/components/_search.scss
  sass/components/_status-icon.scss
  sass/components/_tooltip.scss
  sass/layout/_headers.scss
  sass/layout/_post.scss
  sass/layout/_sidebar-left.scss
  sass/responsive/_mobile.scss
  sass/utils/_variables.scss
  utils/utils.jsx
Labels: 3: Reviews Complete

#3667 Added Cypress test for validating MM-18039 Members Invitation Flow: Verify UI Elements
  components/invitation_modal/__snapshots__/invitation_modal_initial_step.test.jsx.snap
  components/invitation_modal/__snapshots__/invitation_modal_members_step.test.jsx.snap
  components/invitation_modal/invitation_modal_initial_step.jsx
  components/invitation_modal/invitation_modal_members_step.jsx
  components/widgets/modals/full_screen_modal.test.tsx
  components/widgets/modals/full_screen_modal.tsx
  e2e/cypress/integration/enterprise/guest_accounts/member_invitation_ui_spec.js
  e2e/cypress/support/api_commands.js
Labels: 2: Dev Review

#3676 MM-18521 - Overflow bug in badge on team ucoin
  components/widgets/team_icon/team_icon.scss
  sass/layout/_team-button.scss
Labels: 3: Reviews Complete

#3543 MM-17455 Added test for special keys that shouldn't put focus on main input
  e2e/cypress/integration/messaging/focus_move_spec.js
Labels: 2: Dev Review

#3587 Adds support for 'radio' type in interactive dialogs
  components/interactive_dialog/dialog_element.jsx
  components/interactive_dialog/dialog_element.test.jsx
  components/widgets/settings/bool_setting.test.jsx
  components/widgets/settings/radio_setting.jsx
  components/widgets/settings/radio_setting.test.jsx
  e2e/cypress/integration/interactive_dialog/full_dialog_spec.js
  e2e/utils/webhook_utils.js
Labels: 3: Reviews Complete

#3670 [GH-11997] Replace explicit `this` binding in component methods
  components/about_build_modal/about_build_modal.jsx
  components/admin_console/boolean_setting.jsx
  components/admin_console/brand_image_setting/brand_image_setting.jsx
  components/admin_console/cluster_settings.jsx
  components/admin_console/cluster_table_container.jsx
  components/admin_console/data_retention_settings.jsx
  components/admin_console/database_settings.jsx
  components/admin_console/elasticsearch_settings.jsx
  components/admin_console/generated_setting.jsx
  components/admin_console/message_export_settings.jsx
  components/admin_console/multiselect_settings.jsx
  components/admin_console/password_settings.jsx
  components/admin_console/plugin_management/plugin_management.jsx
  components/admin_console/push_settings.jsx
  components/admin_console/radio_setting.jsx
  components/admin_console/request_button/request_button.jsx
  components/admin_console/reset_password_modal/reset_password_modal.jsx
  components/audio_video_preview.jsx
  components/authorize/authorize.jsx
  components/backstage/components/backstage_list.jsx
  components/claim/components/email_to_ldap.jsx
  components/claim/components/email_to_oauth.jsx
  components/claim/components/ldap_to_email.jsx
  components/claim/components/oauth_to_email.jsx
  components/code_preview.jsx
  components/delete_channel_modal/delete_channel_modal.jsx
  components/emoji_picker/components/emoji_picker_category.jsx
  components/emoji_picker/emoji_picker.jsx
  components/file_attachment_list/file_attachment_list.jsx
  components/get_post_link_modal/get_post_link_modal.jsx
  components/gif_picker/components/InfiniteScroll/index.js
  components/gif_picker/gif_picker.jsx
  components/integrations/installed_incoming_webhook.jsx
  components/integrations/installed_outgoing_webhook.jsx
  components/integrations/installed_outgoing_webhooks/installed_outgoing_webhooks.jsx
  components/more_direct_channels/group_message_option.jsx
  components/multiselect/multiselect_list.jsx
  components/pdf_preview.jsx
  components/post_view/new_messages_below/new_messages_below.jsx
  components/profile_popover/profile_popover.jsx
  components/searchable_channel_list.jsx
  components/searchable_user_list/searchable_user_list.jsx
  components/searchable_user_list/searchable_user_list_container.jsx
  components/setting_upload.jsx
  components/settings_sidebar.jsx
  components/signup/signup_controller/signup_controller.jsx
  components/suggestion/search_date_provider.jsx
  components/suggestion/suggestion.jsx
  components/suggestion/suggestion_list.jsx
  components/team_general_tab/team_general_tab.jsx
  components/team_import_tab.jsx
  components/team_sidebar/components/team_button.jsx
  components/toggle_modal_button.jsx
  components/user_list.jsx
  components/user_list_row_with_error/user_list_row_with_error.jsx
Labels: 3: Reviews Complete

#3602 [GH-12018] Remove the now unnecessary show prop from PopoverBar
  components/view_image/__snapshots__/view_image.test.jsx.snap
  components/view_image/popover_bar/__snapshots__/popover_bar.test.jsx.snap
  components/view_image/popover_bar/popover_bar.jsx
  components/view_image/popover_bar/popover_bar.test.jsx
  components/view_image/view_image.jsx
  components/view_image/view_image.test.jsx
Labels: 3: Reviews Complete

#3652 MM-18466 Change recent date separators to Today/Yesterday
  components/post_view/date_separator/__snapshots__/date_separator.test.jsx.snap
  components/post_view/date_separator/date_separator.jsx
  components/post_view/floating_timestamp/floating_timestamp.jsx
  components/recent_date.jsx
  components/recent_date.test.jsx
  i18n/en.json
Labels: 3: Reviews Complete

#3646 Converted jquery.dragster.js from jquery plugin to vanilla js
  .storybook/webpack.config.js
  components/file_upload/file_upload.jsx
  components/file_upload/file_upload.test.jsx
  non_npm_dependencies/jquery-dragster/jquery.dragster.js
  package.json
  utils/dragster.js
  utils/dragster.test.js
  webpack.config.js
Labels: 3: Reviews Complete

#3549 MM-17468 - Improving performance of fetching threads
  actions/views/channel.js
  actions/views/channel.test.js
  components/post_view/post/index.js
  components/post_view/post/index.test.js
Labels: 3: Reviews Complete

#3552 MM-18099 Hide create channel button if missing public channel creation permission
  components/more_channels/__snapshots__/more_channels.test.jsx.snap
  components/more_channels/more_channels.jsx
  components/new_channel_flow/new_channel_flow.jsx
  components/new_channel_flow/new_channel_flow.test.jsx
Labels: 3: Reviews Complete

#3662 MM-17023: Plugin Marketplace
  components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
  components/admin_console/admin_definition.jsx
  components/admin_console/custom_plugin_settings/__snapshots__/custom_plugin_settings.test.jsx.snap
  components/admin_console/custom_plugin_settings/custom_plugin_settings.jsx
  components/admin_console/custom_plugin_settings/custom_plugin_settings.test.jsx
  components/admin_console/custom_plugin_settings/index.js
  components/admin_console/plugin_management/__snapshots__/plugin_management.test.jsx.snap
  components/admin_console/plugin_management/plugin_management.jsx
  components/admin_console/plugin_management/plugin_management.test.jsx
  components/admin_console/schema_admin_settings.jsx
  components/admin_console/schema_admin_settings.test.jsx
  components/main_menu/__snapshots__/main_menu.test.jsx.snap
  components/main_menu/index.jsx
  components/main_menu/main_menu.jsx
  components/main_menu/main_menu.test.jsx
  components/plugin_marketplace/__snapshots__/marketplace_modal.test.jsx.snap
  components/plugin_marketplace/index.js
  components/plugin_marketplace/marketplace_item/__snapshots__/marketplace_item.test.jsx.snap
  components/plugin_marketplace/marketplace_item/index.js
  components/plugin_marketplace/marketplace_item/marketplace_item.jsx
  components/plugin_marketplace/marketplace_item/marketplace_item.test.jsx
  components/plugin_marketplace/marketplace_modal.jsx
  components/plugin_marketplace/marketplace_modal.scss
  components/plugin_marketplace/marketplace_modal.test.jsx
  components/widgets/icons/plugin_icon.jsx
  e2e/cypress/integration/plugins/marketplace/marketplace_avaliability_spec.js
  e2e/cypress/integration/plugins/marketplace/marketplace_spec.js
  i18n/en.json
  package-lock.json
  package.json
  plugins/test/__snapshots__/main_menu_action.test.jsx.snap
  plugins/test/main_menu_action.test.jsx
  sass/base/_css_variables.scss
  sass/components/_modal.scss
  utils/constants.jsx
  utils/utils.jsx
Labels: CherryPick/Approved, Do Not Merge/Awaiting PR

#3687 [MM-18598] Group settings add team modal doesn't show team name
  components/team_selector_modal/team_selector_modal.jsx
  sass/components/_permissions.scss
Labels: 2: Dev Review, CherryPick/Approved

#3677 Added Cypress test for validating MM-18041 Guest User Invitation Flow - Verify UI Elements
  components/invitation_modal/__snapshots__/invitation_modal_guests_step.test.jsx.snap
  components/invitation_modal/invitation_modal_guests_step.jsx
  e2e/cypress/integration/enterprise/guest_accounts/guest_invitation_ui_spec.js
Labels: 2: Dev Review, CherryPick/Approved

#3675 Fix at-mention spec
  e2e/cypress/integration/at_mentions/at_mentions_spec.js
Labels: 2: Dev Review

#3691 Automated cherry pick of #3677
  components/invitation_modal/__snapshots__/invitation_modal_guests_step.test.jsx.snap
  components/invitation_modal/invitation_modal_guests_step.jsx
  e2e/cypress/integration/enterprise/guest_accounts/guest_invitation_ui_spec.js
Labels: AutomatedCherryPick

#3688 Add vim temporary files to .gitignore
  .gitignore
Labels: 3: Reviews Complete

#3568 [MM-16934] Add ability for channel type toggle (public/private) to go both directions
  components/admin_console/team_channel_settings/channel/details/__snapshots__/channel_details.test.jsx.snap
  components/admin_console/team_channel_settings/channel/details/__snapshots__/channel_modes.test.jsx.snap
  components/admin_console/team_channel_settings/channel/details/channel_details.jsx
  components/admin_console/team_channel_settings/channel/details/channel_details.test.jsx
  components/admin_console/team_channel_settings/channel/details/channel_modes.jsx
  components/admin_console/team_channel_settings/channel/details/channel_modes.test.jsx
  components/admin_console/team_channel_settings/channel/details/index.js
  components/admin_console/team_channel_settings/convert_and_remove_confirm_modal.jsx
  components/admin_console/team_channel_settings/convert_confirm_modal.jsx
  components/admin_console/team_channel_settings/remove_confirm_modal.jsx
  e2e/cypress/integration/system_console/channel_modes_spec.js
  e2e/cypress/support/api_commands.js
  i18n/en.json
Labels: 3: Reviews Complete

#3544 [MM-16003] Create "Add Team" button
  components/admin_console/system_user_detail/__snapshots__/system_user_detail.test.jsx.snap
  components/admin_console/system_user_detail/index.js
  components/admin_console/system_user_detail/system_user_detail.jsx
  components/admin_console/system_user_detail/system_user_detail.scss
  components/admin_console/system_user_detail/system_user_detail.test.jsx
  components/admin_console/system_user_detail/team_list/__snapshots__/abstract_list.test.jsx.snap
  components/admin_console/system_user_detail/team_list/__snapshots__/team_list.test.jsx.snap
  components/admin_console/system_user_detail/team_list/abstract_list.jsx
  components/admin_console/system_user_detail/team_list/abstract_list.scss
  components/admin_console/system_user_detail/team_list/abstract_list.test.jsx
  components/admin_console/system_user_detail/team_list/team_list.jsx
  components/admin_console/system_user_detail/team_list/team_list.test.jsx
  components/admin_console/system_user_detail/team_list/team_row.jsx
  components/admin_console/system_user_detail/team_list/team_row.scss
  i18n/en.json
Labels: 2: Dev Review

#3661 MM-17123 - Updating inline images markdown
  components/help/components/formatting.jsx
  i18n/en.json
  webpack.config.js
Labels: CherryPick/Approved

#3657 MM-18454 - Updating quick switch modal
  components/quick_switch_modal/__snapshots__/quick_switch_modal.test.jsx.snap
  components/quick_switch_modal/quick_switch_modal.jsx
  sass/components/_modal.scss
  utils/utils.jsx
Labels: CherryPick/Approved

#3512 [MM-17066] use ALT+click to mark a post as unread
  components/post_view/post/index.js
  components/post_view/post/post.jsx
Labels: 3: Reviews Complete

#3649 E2E: fix pinning/unpinning a post
  e2e/cypress/integration/account_settings/display/channel_display_mode_spec.js
  e2e/cypress/integration/account_settings/display/code_theme_colors_spec.js
  e2e/cypress/integration/account_settings/display/message_display_mode_spec.js
  e2e/cypress/integration/account_settings/display/theme/settings_view_spec.js
  e2e/cypress/integration/account_settings/general/nickname_spec.js
  e2e/cypress/integration/account_settings/sidebar/channel_switcher_spec.js
  e2e/cypress/integration/at_mentions/at_mentions_spec.js
  e2e/cypress/integration/channel/autocomplete_shown_each_channel_spec.js
  e2e/cypress/integration/channel/channel_settings_spec.js
  e2e/cypress/integration/channel/collapsed_message_spec.js
  e2e/cypress/integration/channel/edit_message_spec.js
  e2e/cypress/integration/channel/header_spec.js
  e2e/cypress/integration/channel/message_bullets_spec.js
  e2e/cypress/integration/channel/message_deletion_spec.js
  e2e/cypress/integration/channel/message_draft_spec.js
  e2e/cypress/integration/channel/message_draft_then_switch_channel_spec.js
  e2e/cypress/integration/channel/message_draft_with_attachment_then_switch_channel_spec.js
  e2e/cypress/integration/channel/message_edit_post_with_attachment_spec.js
  e2e/cypress/integration/channel/message_emoji_jumbo_spec.js
  e2e/cypress/integration/channel/message_reaction_spec.js
  e2e/cypress/integration/channel/message_spec.js
  e2e/cypress/integration/channel/mobile_message_deletion_spec.js
  e2e/cypress/integration/channel/system_message_spec.js
  e2e/cypress/integration/email/mention_email_notification_spec.js
  e2e/cypress/integration/emoji/custom_emoji_spec.js
  e2e/cypress/integration/emoji/recently_used_emoji_spec.js
  e2e/cypress/integration/emoji/sorted_emojis_spec.js
  e2e/cypress/integration/enterprise/elasticsearch/channels_spec.js
  e2e/cypress/integration/enterprise/elasticsearch/renaming_spec.js
  e2e/cypress/integration/enterprise/elasticsearch/system_console_spec.js
  e2e/cypress/integration/enterprise/elasticsearch/users_spec.js
  e2e/cypress/integration/integrations/integrations_spec.js
  e2e/cypress/integration/login/login_spec.js
  e2e/cypress/integration/login/signup_spec.js
  e2e/cypress/integration/login/subpath_login_spec.js
  e2e/cypress/integration/login/tutorial_navigation_and_links_spec.js
  e2e/cypress/integration/markdown/markdown_image_spec.js
  e2e/cypress/integration/markdown/markdown_text_spec.js
  e2e/cypress/integration/messaging/emoji_size_spec.js
  e2e/cypress/integration/messaging/emoji_to_markdown_spec.js
  e2e/cypress/integration/messaging/focus_move_spec.js
  e2e/cypress/integration/messaging/message_pinning_unpinning_spec.js
  e2e/cypress/integration/multi_team/existing_channel_name_spec.js
  e2e/cypress/integration/multi_team/system_message_spec.js
  e2e/cypress/integration/onboarding/email/existing_email_adress_spec.js
  e2e/cypress/integration/post_header/post_header_spec.js
  e2e/cypress/integration/search/date_filter_spec.js
  e2e/cypress/integration/search/post_search_display_spec.js
  e2e/cypress/integration/search/results_post_comment_spec.js
  e2e/cypress/integration/search/search_user_post_spec.js
  e2e/cypress/integration/signin_authentication/forgot_password_spec.js
  e2e/cypress/integration/system_console/demoted_user_spec.js
  e2e/cypress/integration/system_console/revoke_all_sessions_spec.js
  e2e/cypress/integration/team/create_a_team_spec.js
  e2e/cypress/integration/team/teams_spec.js
  e2e/cypress/support/ui_commands.js
Labels: 3: Reviews Complete

#3685 MM-18456 Add E2E for built-in slash commands
  e2e/cypress/integration/integrations/builtin_commands/common_commands_spec.js
  e2e/cypress/integration/integrations/builtin_commands/user_status_commands_spec.js
Labels: 2: Dev Review, 2: QA Review

#3674 E2E: Fix header and teams specs
  e2e/cypress/integration/channel/header_spec.js
  e2e/cypress/integration/team/teams_spec.js
  e2e/cypress/support/ui_commands.js
Labels: 3: Reviews Complete

#3690 Automated cherry pick of #3687
  components/team_selector_modal/team_selector_modal.jsx
  sass/components/_permissions.scss
Labels: AutomatedCherryPick

#3618 [MM-15220] Add support for generic error message in interactive dialog
  components/interactive_dialog/interactive_dialog.jsx
  components/interactive_dialog/interactive_dialog.test.jsx
  sass/components/_modal.scss
Labels: 3: Reviews Complete, Tests/Done

#3581 MM-17696: Move build and build-docker before test in CI workflow
  .circleci/config.yml
Labels: 3: Reviews Complete

#3641 MM-16678 Remove IE11-specific backwards compatible scrolling code
  actions/views/channel.js
  components/needs_team/needs_team.test.jsx
  components/post_view/post_list/index.js
  components/post_view/post_list/post_list_virtualized.jsx
  components/post_view/post_list_ie/index.js
  components/post_view/post_list_ie/post_list_ie.jsx
  components/post_view/reaction_list/index.js
  components/post_view/reaction_list/reaction_list.jsx
  components/post_view/reaction_list/reactions_list.test.jsx
  components/root/root.test.jsx
  components/sidebar_right/index.js
  components/sidebar_right/sidebar_right.jsx
  components/textbox.test.jsx
  components/textbox/index.js
  components/textbox/textbox.jsx
  i18n/en.json
  selectors/posts.js
  selectors/posts.test.js
  utils/constants.jsx
  utils/utils.jsx
Labels: 2: QA Review, CherryPick/Approved

#3703 Automated cherry pick of #3641
  actions/views/channel.js
  components/needs_team/needs_team.test.jsx
  components/post_view/post_list/index.js
  components/post_view/post_list/post_list_virtualized.jsx
  components/post_view/post_list_ie/index.js
  components/post_view/post_list_ie/post_list_ie.jsx
  components/post_view/reaction_list/index.js
  components/post_view/reaction_list/reaction_list.jsx
  components/post_view/reaction_list/reactions_list.test.jsx
  components/root/root.test.jsx
  components/sidebar_right/index.js
  components/sidebar_right/sidebar_right.jsx
  components/textbox.test.jsx
  components/textbox/index.js
  components/textbox/textbox.jsx
  i18n/en.json
  selectors/posts.js
  selectors/posts.test.js
  utils/constants.jsx
  utils/utils.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3692 Fix failing test in at-mentions
  e2e/cypress/integration/at_mentions/at_mentions_spec.js
Labels: 3: Reviews Complete

#3630 MM-18436 Improve perceived performance of emoji picker
  components/emoji_picker/emoji_picker.jsx
  components/emoji_picker/emoji_picker.test.jsx
  components/emoji_picker/emoji_picker_category_section.jsx
  sass/components/_emoticons.scss
  sass/responsive/_mobile.scss
Labels: 3: Reviews Complete, CherryPick/Approved

#3705 Automated cherry pick of #3630
  components/emoji_picker/emoji_picker.jsx
  components/emoji_picker/emoji_picker.test.jsx
  components/emoji_picker/emoji_picker_category_section.jsx
  sass/components/_emoticons.scss
  sass/responsive/_mobile.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3679 [MM-18385] Force screen reader to read whole aria-live section on multiselect option change
  components/multiselect/multiselect_list.jsx
Labels: 3: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server

#3709 Automated cherry pick of #3679
  components/multiselect/multiselect_list.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3609 [MM-17068] use websocket to sync mark as unread status
  actions/websocket_actions.jsx
  actions/websocket_actions.test.jsx
  components/post_view/post/index.js
  components/post_view/post/post.jsx
  utils/constants.jsx
Labels: 2: Dev Review

#3613 [MM-17391] Show remove plugin modal
  components/admin_console/plugin_management/plugin_management.jsx
  i18n/en.json
Labels: Tests/Done

#3696 Automated cherry pick of #3657
  components/quick_switch_modal/__snapshots__/quick_switch_modal.test.jsx.snap
  components/quick_switch_modal/quick_switch_modal.jsx
  sass/components/_modal.scss
  utils/utils.jsx
Labels: AutomatedCherryPick

#3695 Automated cherry pick of #3661
  components/help/components/formatting.jsx
  i18n/en.json
  webpack.config.js
Labels: AutomatedCherryPick

#3698 [MM-18164] Turned on aria-labels for the RHS header buttons
  components/search_bar/search_bar.jsx
Labels: 3: Reviews Complete, CherryPick/Approved

#3720 Automated cherry pick of #3698
  components/search_bar/search_bar.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3712 Added Cypress test for validating MM-18043 Guest User Experience: Verify Guest User Restrictions
  components/popover_list_members/popover_list_members_item.jsx
  e2e/cypress/integration/enterprise/guest_accounts/guest_experience_ui_spec.js
  e2e/cypress/support/api_commands.js
Labels: 3: Reviews Complete

#3721 Automated cherry pick of #3712
  components/popover_list_members/popover_list_members_item.jsx
  e2e/cypress/integration/enterprise/guest_accounts/guest_experience_ui_spec.js
  e2e/cypress/support/api_commands.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3711 MM-18067 - Updating css for plugin list
  sass/layout/_headers.scss
Labels: 2: Dev Review, CherryPick/Approved

#3710 MM-18510 - Updating LDAP Channels screen css
  components/admin_console/team_channel_settings/line_switch.jsx
  sass/components/_line-switch.scss
  sass/components/_module.scss
  sass/components/_team-channel-settings.scss
  sass/responsive/_mobile.scss
Labels: CherryPick/Approved

#3722 Automated cherry pick of #3711
  sass/layout/_headers.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3723 Automated cherry pick of #3710
  components/admin_console/team_channel_settings/line_switch.jsx
  sass/components/_line-switch.scss
  sass/components/_module.scss
  sass/components/_team-channel-settings.scss
  sass/responsive/_mobile.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3453 [MM-12588] Complete migration of channel_actions to redux actions
  actions/channel_actions.jsx
  components/__snapshots__/textbox.test.jsx.snap
  components/add_user_to_channel_modal/__snapshots__/add_user_to_channel_modal.test.jsx.snap
  components/add_user_to_channel_modal/add_user_to_channel_modal.jsx
  components/add_user_to_channel_modal/add_user_to_channel_modal.test.jsx
  components/add_user_to_channel_modal/index.js
  components/search_bar/__snapshots__/search_bar.test.jsx.snap
  components/search_bar/index.jsx
  components/search_bar/search_bar.jsx
  components/search_bar/search_bar.test.jsx
  components/suggestion/channel_mention_provider.jsx
  components/suggestion/search_channel_provider.jsx
  components/suggestion/search_channel_with_permissions_provider.jsx
  components/suggestion/search_channel_with_permissions_provider.test.jsx
  components/textbox.test.jsx
  components/textbox/index.js
  components/textbox/textbox.jsx
Labels: 3: Reviews Complete

#3530 MM-12051 Use react-custom-scrollbars for System Console left-hand sidebar
  components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.jsx.snap
  components/admin_console/admin_sidebar/admin_sidebar.jsx
Labels: 3: Reviews Complete

#3714 [MM-18649] Fixed race condition for /leave action
  actions/command.js
Labels: 3: Reviews Complete, CherryPick/Approved

#3707 MM-18492 - Updating header popover z-index
  sass/components/_popover.scss
Labels: 3: Reviews Complete, CherryPick/Approved

#3706 MM-18244 - Updating username on LHS mobile view
  sass/responsive/_mobile.scss
Labels: 2: Dev Review, CherryPick/Approved

#3729 Automated cherry pick of #3707
  sass/components/_popover.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3730 Automated cherry pick of #3706
  sass/responsive/_mobile.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3713 Added Cypress test for validating MM-18040 Members Invitation Flow: Add New/Existing Users
  e2e/cypress/integration/enterprise/guest_accounts/member_invitation_ui_spec.js
Labels: 3: Reviews Complete, CherryPick/Approved

#3731 Automated cherry pick of #3713
  e2e/cypress/integration/enterprise/guest_accounts/member_invitation_ui_spec.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3686 MM-17945 Added test coverage for addUsersToChannel
  actions/channel_actions.test.js
Labels: 3: Reviews Complete

#3728 Automated cherry pick of #3714
  actions/command.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3701 Fixing Guest labeling in manage users
  components/channel_members_dropdown/__snapshots__/channel_members_dropdown.test.jsx.snap
  components/channel_members_dropdown/channel_members_dropdown.jsx
  components/channel_members_dropdown/channel_members_dropdown.test.jsx
Labels: 3: Reviews Complete, CherryPick/Approved

#3733 Automated cherry pick of #3701
  components/channel_members_dropdown/__snapshots__/channel_members_dropdown.test.jsx.snap
  components/channel_members_dropdown/channel_members_dropdown.jsx
  components/channel_members_dropdown/channel_members_dropdown.test.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3682 MM-18021 - Do not allow Guest invitations to teams that are managed by LDAP Group Sync
  components/invitation_modal/index.js
  components/invitation_modal/index.test.jsx
Labels: 2: QA Review, Setup Cloud Test Server

#3702 [MM-17427] Disable channel settings public/private toggle for default channel
  components/admin_console/team_channel_settings/channel/details/__snapshots__/channel_details.test.jsx.snap
  components/admin_console/team_channel_settings/channel/details/__snapshots__/channel_modes.test.jsx.snap
  components/admin_console/team_channel_settings/channel/details/channel_details.jsx
  components/admin_console/team_channel_settings/channel/details/channel_modes.jsx
  components/admin_console/team_channel_settings/channel/details/channel_modes.test.jsx
  e2e/cypress/integration/system_console/channel_modes_spec.js
  i18n/en.json
Labels: 3: Reviews Complete

#3717 MM-18648 - Disable Marketplace URL if Marketplace is disabled
  components/admin_console/plugin_management/plugin_management.jsx
Labels: 3: Reviews Complete, CherryPick/Approved

#3737 Automated cherry pick of #3717
  components/admin_console/plugin_management/plugin_management.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3538 [MM-14521] Adds a button to validate a SiteURL setting
  actions/admin_actions.jsx
  components/admin_console/admin_definition.jsx
  components/admin_console/request_button/request_button.jsx
  components/admin_console/schema_admin_settings.jsx
  i18n/en.json
Labels: 3: Reviews Complete

#3724 Added Cypress Test for MM-11390 Guest Invitation Flow: Verify Add New/Existing Guest Users
  e2e/cypress/integration/enterprise/guest_accounts/guest_invitation_ui_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/member_invitation_ui_spec.js
  e2e/cypress/support/api_commands.js
Labels: 3: Reviews Complete, CherryPick/Approved

#3732 [MM-18746] Fix channels autocomplete both for interactive dialog and menu
  components/interactive_dialog/dialog_element/dialog_element.jsx
  components/interactive_dialog/dialog_element/dialog_element.test.jsx
  components/interactive_dialog/dialog_element/index.js
  components/post_view/message_attachments/action_menu/action_menu.jsx
  components/post_view/message_attachments/action_menu/action_menu.test.jsx
  components/post_view/message_attachments/action_menu/index.js
  components/suggestion/generic_channel_provider.jsx
Labels: 3: Reviews Complete

#3639 [MM-12898] Allow in-line markdown images to open preview window
  components/__snapshots__/markdown_image.test.jsx.snap
  components/file_info_preview/file_info_preview.jsx
  components/markdown/markdown.jsx
  components/markdown_image.jsx
  components/markdown_image.test.jsx
  components/post_markdown/__snapshots__/post_markdown.test.jsx.snap
  components/post_markdown/post_markdown.jsx
  components/post_markdown/post_markdown.test.jsx
  components/size_aware_image.jsx
  e2e/cypress/fixtures/markdown/markdown_inline_images_6.md
  e2e/cypress/integration/markdown/markdown_image_spec.js
  sass/layout/_markdown.scss
  utils/__snapshots__/message_html_to_component.test.jsx.snap
  utils/message_html_to_component.jsx
  utils/message_html_to_component.test.jsx
  utils/text_formatting.jsx
  utils/text_formatting_imgs.test.jsx
Labels: 3: Reviews Complete

#3708 MM-18580 - Updating css3 variables
  sass/layout/_headers.scss
  sass/layout/_sidebar-left.scss
  utils/utils.jsx
Labels: 3: Reviews Complete, CherryPick/Approved

#3726 MM-17650 - Updating spacing for interactive menu
  sass/layout/_webhooks.scss
Labels: 2: Dev Review, CherryPick/Approved

#3750 Avoid avatars to be shrinked by flexbox policies
  components/post_profile_picture/post_profile_picture.jsx
  components/widgets/users/avatar.scss
  sass/layout/_post.scss
Labels: 3: Reviews Complete, CherryPick/Approved

#3751 Automated cherry pick of #3750
  components/post_profile_picture/post_profile_picture.jsx
  components/widgets/users/avatar.scss
  sass/layout/_post.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3738 Fix E2E on user status and toggling private/public channel
  e2e/cypress/integration/enterprise/system_console/channel_modes_spec.js
  e2e/cypress/integration/integrations/builtin_commands/user_status_commands_spec.js
Labels: 3: Reviews Complete

#3744 MM-18021 - Harden Unit Test
  components/invitation_modal/index.test.jsx
  package-lock.json
Labels: 3: Reviews Complete, Tests/Not Needed

#3718 [MM-18152] Desktop Notifications
  components/logged_in/logged_in.jsx
  package-lock.json
  package.json
  utils/notifications.jsx
  utils/utils.jsx
Labels: CherryPick/Approved

#3753 Automated cherry pick of #3718
  components/logged_in/logged_in.jsx
  package-lock.json
  package.json
  utils/notifications.jsx
  utils/utils.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3745 MM-18570 - Hitting escape to close autocomplete also closes channel header modal
  components/edit_channel_header_modal/__snapshots__/edit_channel_header_modal.test.jsx.snap
  components/edit_channel_header_modal/edit_channel_header_modal.jsx
Labels: QA Review Done

#3740 [MM-18600] Reset SuggestionBox pretext on post submit
  components/suggestion/suggestion_box.jsx
  components/suggestion/suggestion_box.test.jsx
Labels: 3: Reviews Complete

#3762 Automated cherry pick of #3752
  components/channel_members_modal/__snapshots__/channel_members_modal.test.jsx.snap
  components/channel_members_modal/channel_members_modal.jsx
  components/more_direct_channels/__snapshots__/more_direct_channels.test.jsx.snap
  components/more_direct_channels/more_direct_channels.jsx
  components/team_members_modal/__snapshots__/team_members_modal.test.jsx.snap
  components/team_members_modal/team_members_modal.jsx
  components/user_list_row/user_list_row.jsx
  e2e/cypress/integration/enterprise/guest_accounts/guest_experience_ui_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/guest_identification_ui_spec.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3760 E2E: Add timeout in getting current channel ID and update inbucket email provider on local dev
  e2e/cypress/integration/email/mention_email_notification_spec.js
  e2e/cypress/support/ui_commands.js
  e2e/cypress/utils/index.js
Labels: 2: Dev Review, 2: QA Review

#3763 MM-18744 - Updating comment submit function
  components/create_comment/create_comment.jsx
Labels: CherryPick/Approved, QA Review Done

#3764 Mm 18743 - MM-18795 - System console UI changes.
  sass/components/_admin-sidebar-header.scss
  sass/components/_groups.scss
  sass/routes/_admin-console.scss
Labels: CherryPick/Approved, QA Review Done

#3715 MM-16399 Clear current channel when leaving a team
  package-lock.json
  package.json
Labels: 3: Reviews Complete, CherryPick/Approved

#3767 Automated cherry pick of #3763
  components/create_comment/create_comment.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3769 Automated cherry pick of #3764
  sass/components/_admin-sidebar-header.scss
  sass/components/_groups.scss
  sass/routes/_admin-console.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed
