Repository mattermost/mattermost-webapp, pull requests merged in 2019-06, with the labels that each got.

#2885 MM-15919 Fix minor scroll pop for inline markdown images
  sass/layout/_markdown.scss
Labels: 2: Dev Review, CherryPick/Approved

#2894 MM-15403 Fixes highlight for date separators and new messages line on post hover
  sass/layout/_post.scss
Labels: 3: Reviews Complete, CherryPick/Approved

#2893 [MM-15929] Move Plugins into its own section in the system console
  components/admin_console/__snapshots__/admin_console.test.jsx.snap
  components/admin_console/admin_definition.jsx
  components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.jsx.snap
  components/admin_console/admin_sidebar/admin_sidebar.jsx
  components/admin_console/plugin_management/plugin_management.jsx
  i18n/en.json
Labels: 2: Dev Review

#2679 Remove user_actions usage from UI components
  actions/user_actions.jsx
  actions/user_actions.test.js
  components/admin_console/system_users/index.js
  components/admin_console/system_users/system_users.jsx
  components/admin_console/system_users/system_users.test.jsx
  components/admin_console/system_users/system_users_dropdown/index.js
  components/admin_console/system_users/system_users_dropdown/system_users_dropdown.jsx
  components/admin_console/system_users/system_users_dropdown/system_users_dropdown.test.js
  components/needs_team/index.js
  components/needs_team/needs_team.jsx
  components/needs_team/needs_team.test.jsx
  components/password_reset_form/__snapshots__/password_reset_form.test.js.snap
  components/password_reset_form/index.js
  components/password_reset_form/password_reset_form.js
  components/password_reset_form/password_reset_form.test.js
  components/password_reset_send_link/__snapshots__/password_reset_send_link.test.js.snap
  components/password_reset_send_link/index.js
  components/password_reset_send_link/password_reset_send_link.js
  components/password_reset_send_link/password_reset_send_link.test.js
  components/should_verify_email/__snapshots__/should_verify_email.test.js.snap
  components/should_verify_email/index.js
  components/should_verify_email/should_verify_email.js
  components/should_verify_email/should_verify_email.test.js
  components/user_settings/advanced/index.js
  components/user_settings/advanced/user_settings_advanced.jsx
  components/user_settings/advanced/user_settings_advanced.test.jsx
  components/user_settings/display/user_settings_theme/index.js
  components/user_settings/display/user_settings_theme/user_settings_theme.jsx
  components/user_settings/display/user_settings_theme/user_settings_theme.test.jsx
  components/user_settings/security/index.js
  components/user_settings/security/user_settings_security.jsx
  components/user_settings/security/user_settings_security.test.js
Labels: 3: Reviews Complete

#2890 MM-15703 Extra spaces not trimmed on search boxes
  components/channel_invite_modal/channel_invite_modal.jsx
  components/channel_invite_modal/channel_invite_modal.test.jsx
  reducers/views/search.js
  reducers/views/search.test.js
Labels: CherryPick/Approved

#2902 MM-15975 scroll pop when loading a channel if the height of loaded posts is low
  components/post_view/post_list_virtualized/post_list_virtualized.jsx
Labels: 3: Reviews Complete, CherryPick/Approved

#2901 MM-15941: Removes message that users won't be removed from teams now …
  components/admin_console/group_settings/group_details/__snapshots__/group_teams_and_channels_row.test.jsx.snap
  components/admin_console/group_settings/group_details/group_teams_and_channels_row.jsx
  i18n/en.json
Labels: 3: Reviews Complete, CherryPick/Approved

#2891 MM-15830 Fix safari scroll jumps for images
  components/__snapshots__/size_aware_image.test.jsx.snap
  components/size_aware_image.jsx
  components/size_aware_image.test.jsx
Labels: 3: Reviews Complete, CherryPick/Approved

#2892 MM-15950 Removing bot account email from DM list.
  components/more_direct_channels/more_direct_channels.jsx
Labels: 3: Reviews Complete, CherryPick/Approved

#2866 MM-15603 Updating Dependencies
  components/__snapshots__/color_input.test.jsx.snap
  components/admin_console/__snapshots__/color_setting.test.jsx.snap
  components/create_post/create_post.test.jsx
  components/edit_post_modal/edit_post_modal.test.jsx
  components/file_attachment/__snapshots__/file_attachment.test.jsx.snap
  components/file_attachment/file_attachment.test.jsx
  components/post_view/post_list_virtualized/post_list_virtualized.test.jsx
  package-lock.json
  package.json
  webpack.config.js
Labels: 2: Dev Review

#2904 MM-15976 Replace forced refresh with banner alerting users that a new version is available
  actions/global_actions.jsx
  components/admin_console/admin_console.jsx
  components/admin_console/system_users/system_users.jsx
  components/announcement_bar/announcement_bar.jsx
  components/announcement_bar/announcement_bar_controller.jsx
  components/announcement_bar/version_bar/__snapshots__/version_bar.test.jsx.snap
  components/announcement_bar/version_bar/index.js
  components/announcement_bar/version_bar/version_bar.jsx
  components/announcement_bar/version_bar/version_bar.test.jsx
  i18n/en.json
  sass/components/_announcement-bar.scss
  sass/utils/_variables.scss
Labels: 2: Dev Review

#2906 MM-15724 - Fixing minor bug with system console LHS header
  components/admin_console/admin_sidebar_header/admin_sidebar_header.jsx
Labels: 3: Reviews Complete, CherryPick/Approved

#2865 MM-15751 Fix for system messages not rendering in IE
  components/post_view/post_list_ie/index.js
  components/post_view/post_list_ie/post_list_ie.jsx
  components/post_view/post_list_row/__snapshots__/post_list_row.test.jsx.snap
  components/post_view/post_list_row/post_list_row.test.jsx
  package-lock.json
  package.json
  selectors/posts.js
  selectors/posts.test.js
Labels: 3: Reviews Complete, CherryPick/Approved

#2910 MM-16018 Fix for image click to open image preview modal
  components/size_aware_image.jsx
  components/size_aware_image.test.jsx
Labels: 3: Reviews Complete, CherryPick/Approved

#2884 MM-15663: Adds confirm modal when removing a group from a team.
  components/list_modal.jsx
  components/post_view/channel_intro_message/index.js
  components/team_groups_manage_modal/team_groups_manage_modal.jsx
  i18n/en.json
Labels: 3: Reviews Complete

#2857 MM-15551 - Updating emoji styling
  components/channel_view/channel_view.jsx
  sass/components/_emoticons.scss
Labels: 2: Dev Review, CherryPick/Approved

#2913 Fix race in version bar causing the bar to show up when no version change has occurred
  components/announcement_bar/version_bar/version_bar.jsx
Labels: 3: Reviews Complete

#2911 MM-16019: Re-add 'Add Members to Team' menu entry for group-constrain…
  components/main_menu/__snapshots__/main_menu.test.jsx.snap
  components/main_menu/main_menu.jsx
  plugins/test/__snapshots__/main_menu_action.test.jsx.snap
Labels: 3: Reviews Complete, CherryPick/Candidate

#2908 MM-16000: Resets current page to 0 upon search input.
  components/channel_selector_modal/channel_selector_modal.jsx
  components/multiselect/multiselect.jsx
  components/team_selector_modal/team_selector_modal.jsx
Labels: 3: Reviews Complete, CherryPick/Candidate

#2915 MM-14861 Perf improvement for onScroll event
  components/post_view/post_list_virtualized/post_list_virtualized.jsx
  components/post_view/post_list_virtualized/post_list_virtualized.test.jsx
  package-lock.json
  package.json
Labels: 3: Reviews Complete, CherryPick/Approved, Do Not Merge/Awaiting PR

#2880 MM-10078 - Adding label for buttons that trigger dialog
  components/post_view/channel_intro_message/channel_intro_message.jsx
  components/profile_popover/__snapshots__/profile_popover.test.jsx.snap
  components/profile_popover/profile_popover.jsx
  components/toggle_modal_button_redux/__snapshots__/toggle_modal_button_redux.test.jsx.snap
  components/toggle_modal_button_redux/toggle_modal_button_redux.jsx
  components/toggle_modal_button_redux/toggle_modal_button_redux.test.jsx
  components/tutorial/tutorial_intro_screens/tutorial_intro_screen.test.jsx
  components/tutorial/tutorial_intro_screens/tutorial_intro_screens.jsx
  components/widgets/menu/menu_items/menu_item_toggle_modal_redux.jsx
  components/widgets/menu/menu_items/menu_item_toggle_modal_redux.test.jsx
  i18n/en.json
Labels: 3: Reviews Complete, CherryPick/Approved, Do Not Merge/Awaiting Next Release

#2907 [MM-16007] Fix JS errors in system console and channel intro message
  components/admin_console/help_text.jsx
  components/post_view/channel_intro_message/channel_intro_message.jsx
Labels: 3: Reviews Complete, CherryPick/Approved

#2909 [MM-16016] Fix errors and warnings when running unit tests
  components/channel_selector_modal/channel_selector_modal.test.jsx
  components/integrations/bots/bots.test.jsx
  components/list_modal.jsx
  components/permalink_view/permalink_view.test.jsx
Labels: 3: Reviews Complete, CherryPick/Approved

#2924 MM-16029 IE11: image attachments aren't displayed
  components/__snapshots__/size_aware_image.test.jsx.snap
  components/size_aware_image.jsx
  components/size_aware_image.test.jsx
  sass/components/_files.scss
  sass/layout/_markdown.scss
Labels: 3: Reviews Complete, CherryPick/Approved

#2920 MM-15935 - Updating scrolling issue IOS browser
  sass/base/_structure.scss
Labels: 3: Reviews Complete, CherryPick/Approved

#2925 MM-16090: clear cookie with path but without domain
  actions/views/root.js
Labels: 3: Reviews Complete, CherryPick/Approved

#2886 MM-15739 - De-flakify Cypress tests, fix Notifications spy
  cypress/integration/account_settings/display/channel_display_mode_spec.js
  cypress/integration/account_settings/display/code_theme_colors_spec.js
  cypress/integration/account_settings/display/message_display_mode_spec.js
  cypress/integration/account_settings/sidebar/channel_switcher_spec.js
  cypress/integration/account_settings/theme_color/custom_colors_sidebar_styles_spec.js
  cypress/integration/at_mentions/at_mentions_spec.js
  cypress/integration/channel/autocomplete_shown_each_channel_spec.js
  cypress/integration/channel/channel_settings_spec.js
  cypress/integration/channel/collapsed_message_spec.js
  cypress/integration/channel/edit_message_spec.js
  cypress/integration/channel/message_draft_spec.js
  cypress/integration/channel/message_draft_then_switch_channel_spec.js
  cypress/integration/channel/message_draft_with_attachment_then_switch_channel_spec.js
  cypress/integration/channel/message_edit_post_with_attachment_spec.js
  cypress/integration/channel/message_reaction_spec.js
  cypress/integration/channel/message_spec.js
  cypress/integration/integrations/integrations_spec.js
  cypress/integration/onboarding/multi_team/existing_channel_name_spec.js
  cypress/integration/search/search_user_post.js
  cypress/integration/team/teams_spec.js
  cypress/plugins/index.js
  cypress/support/api_commands.js
  cypress/support/index.js
  cypress/support/ui_commands.js
Labels: 3: Reviews Complete

#2897 Update NOTICE.txt
  NOTICE.txt
Labels: 3: Reviews Complete, CherryPick/Approved

#2912 MM-8647 Render plugin settings header/footer like help text
  components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
  components/admin_console/__snapshots__/schema_text.test.jsx.snap
  components/admin_console/custom_plugin_settings/__snapshots__/custom_plugin_settings.test.jsx.snap
  components/admin_console/schema_admin_settings.jsx
  components/admin_console/schema_admin_settings.test.jsx
  components/admin_console/schema_text.jsx
  components/admin_console/schema_text.test.jsx
Labels: 3: Reviews Complete, CherryPick/Approved

#2916 MM-16045 Stop using nonExistentEmoji on web app
  components/post_emoji/index.jsx
  components/post_emoji/post_emoji.jsx
  components/post_emoji/post_emoji.test.jsx
  utils/message_html_to_component.jsx
Labels: 3: Reviews Complete, CherryPick/Approved

#2921 MM-16001 Have client use new bot_description field.
  components/channel_header/channel_header.js
  components/channel_header/channel_header.test.jsx
  components/channel_header/index.js
  components/profile_popover/index.js
  components/profile_popover/profile_popover.jsx
  components/profile_popover/profile_popover.test.jsx
Labels: 3: Reviews Complete, CherryPick/Approved

#2888 MM-15730: Disable editing Position field when LDAP or SAML mapped.
  components/user_settings/general/index.js
  components/user_settings/general/user_settings_general.jsx
  components/user_settings/general/user_settings_general.test.js
Labels: 3: Reviews Complete, CherryPick/Approved

#2919 MM-16033 Mobile view: Show paper plane enabled when uploading a file
  components/create_post/create_post.jsx
  components/create_post/create_post.test.jsx
Labels: 3: Reviews Complete, CherryPick/Approved

#2903 [MM-15872] Update AD/LDAP Feature Flag Description in Experimental Settings to correct location
  components/admin_console/admin_definition.jsx
  i18n/en.json
Labels: 3: Reviews Complete, CherryPick/Approved

#2914 [MM-16062] Replace searchUsers function for searchProfiles in mattermost-redux
  components/channel_invite_modal/channel_invite_modal.jsx
  components/channel_invite_modal/channel_invite_modal.test.jsx
  components/channel_invite_modal/index.js
Labels: 3: Reviews Complete

#2927 Update title of ‘Compliance Monitoring’ page
  components/admin_console/admin_definition.jsx
  i18n/en.json
Labels: 3: Reviews Complete, CherryPick/Approved

#2838 MM-15340 provide InteractiveDialog hook to webapp plugins
  plugins/export.js
  plugins/interactive_dialog.js
Labels: 3: Reviews Complete

#2930 MM-16034 Fix for IE Not removing new message indicator
  components/post_view/post_list_ie/post_list_ie.jsx
Labels: 3: Reviews Complete, CherryPick/Approved

#2932 MM-15791] New messages indicator doesn't clear after viewing the message
  components/post_view/post_list_virtualized/index.js
  components/post_view/post_list_virtualized/post_list_virtualized.jsx
  components/post_view/post_list_virtualized/post_list_virtualized.test.jsx
  utils/post_utils.jsx
  utils/post_utils.test.jsx
Labels: 3: Reviews Complete, CherryPick/Approved

#2936 [MM-16122] Floating date indicator doesn't change the date to reflect the messages being viewed
  components/post_view/post_list_virtualized/post_list_virtualized.jsx
  components/post_view/post_list_virtualized/post_list_virtualized.test.jsx
Labels: 3: Reviews Complete, CherryPick/Approved

#2928 MM-16144 Relabel plugins as "Beta" in the System Console sidebar
  components/admin_console/admin_definition.jsx
  components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.jsx.snap
  i18n/en.json
Labels: 3: Reviews Complete, CherryPick/Approved

#2922 [MM-16105] Revert accidental change to marked's commit
  package.json
Labels: 3: Reviews Complete

#2940 [MM-16052] System Console > Search doesn't return results for "Plugins"
  utils/admin_console_index.jsx
Labels: 2: Dev Review, CherryPick/Approved

#2942 MM-16099 Fix for scroll correction when loading channel header
  components/post_view/post_list_virtualized/post_list_virtualized.jsx
  package-lock.json
  package.json
Labels: 2: Dev Review, CherryPick/Approved

#2937 MM-16080 Remove duplicate setting In System Console > CORS
  components/admin_console/admin_definition.jsx
Labels: 3: Reviews Complete, CherryPick/Approved

#2935 MM-16121 - Updating custom textarea on mobile
  sass/responsive/_mobile.scss
Labels: 2: Dev Review, CherryPick/Approved

#2923 MM-16063: redirectUserToDefaultTeam fixes
  actions/global_actions.jsx
  actions/global_actions.test.js
Labels: 3: Reviews Complete, CherryPick/Approved

#2945 M-16214 Fix styling of Set a Header in channel intro
  components/post_view/channel_intro_message/channel_intro_message.jsx
Labels: 3: Reviews Complete, CherryPick/Approved

#2946 MM-16243 Fix for empty space caused by faiied link preview image
  components/__snapshots__/size_aware_image.test.jsx.snap
  components/size_aware_image.jsx
Labels: 3: Reviews Complete, CherryPick/Approved

#2934 MM-16118 - Updating bot tag
  components/channel_header/channel_header.js
  components/post_view/channel_intro_message/channel_intro_message.jsx
  components/user_profile/__snapshots__/user_profile.test.jsx.snap
  components/user_profile/user_profile.jsx
  components/widgets/badges/badge.jsx
  components/widgets/badges/badge.scss
  components/widgets/badges/badge.test.jsx
  sass/layout/_headers.scss
  utils/utils.jsx
Labels: 3: Reviews Complete, CherryPick/Approved

#2938 MM-15579: Updates styling/behaviour of disabled team setting.
  components/team_general_tab/__snapshots__/team_general_tab.test.jsx.snap
  components/team_general_tab/team_general_tab.jsx
  i18n/en.json
Labels: 3: Reviews Complete

#2929 MM-14712 - Add support for signing SAML requests
  components/admin_console/admin_definition.jsx
  i18n/en.json
Labels: 1: PM Review

#2944 [MM-16089] Compliance reports job table missing
  components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
  components/admin_console/audits/audits.jsx
  components/admin_console/custom_plugin_settings/__snapshots__/custom_plugin_settings.test.jsx.snap
  components/admin_console/schema_admin_settings.jsx
  i18n/en.json
Labels: 2: Dev Review, CherryPick/Approved

#2953 MM-16112: Fix IE11 syntax error
  package-lock.json
  package.json
Labels: 2: Dev Review

#2961 MM-16280 Fix when post fail to send
  package-lock.json
  package.json
Labels: 2: Dev Review

#2860 Rendering less things in the RHS threads
  components/rhs_comment/rhs_comment.jsx
Labels: 3: Reviews Complete

#2964 MM-16282: Removing not necesary code
  components/announcement_bar/announcement_bar.jsx
Labels: 3: Reviews Complete, CherryPick/Approved

#2949 MM-16151 - Updating user info with bot tags
  components/popover_list_members/popover_list_members_item.jsx
  sass/components/_mentions.scss
  sass/components/_modal.scss
  sass/components/_popover.scss
  sass/components/_status-icon.scss
Labels: 2: Dev Review, CherryPick/Approved

#2962 MM-16283 Render markdown in bot account descriptions
  components/integrations/bots/bot.jsx
  components/integrations/bots/bot.test.jsx
Labels: 2: Dev Review, CherryPick/Approved

#2966 [MM-15790] fixing an obscure bug for plugins - copy the array before modifying it
  reducers/plugins/index.js
Labels: 3: Reviews Complete, CherryPick/Approved

#2955 MM-16247/MM-16279 Re-render RHS when post type components change
  components/rhs_comment/rhs_comment.jsx
  components/rhs_root_post/rhs_root_post.jsx
Labels: 3: Reviews Complete, CherryPick/Approved

#2965 MM-16142 - Creating visual display of focus
  components/root/root.jsx
  sass/components/_dropdown.scss
  sass/components/_links.scss
  sass/components/_search.scss
  sass/layout/_headers.scss
  sass/layout/_post.scss
  sass/layout/_sidebar-left.scss
  sass/layout/_sidebar-right.scss
  sass/utils/_modifiers.scss
  sass/widgets/menu/_menu_wrapper.scss
  utils/utils.jsx
Labels: 3: Reviews Complete

#2969 Fix channel sorting when display name is not set
  package-lock.json
  package.json
Labels: 3: Reviews Complete, CherryPick/Approved

#2954 Add new bot account settings page.
  components/admin_console/__snapshots__/admin_console.test.jsx.snap
  components/admin_console/admin_definition.jsx
  components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.jsx.snap
  i18n/en.json
Labels: 2: Dev Review

#2958 MM-15982 - Updating favourites label
  components/channel_header/__snapshots__/channel_header.test.jsx.snap
  components/channel_header/channel_header.js
Labels: 3: Reviews Complete

#2957 MM-15749 Allow channel links in brackets
  utils/text_formatting.jsx
  utils/text_formatting_channel_links.test.jsx
  utils/text_formatting_hashtags.test.jsx
Labels: 3: Reviews Complete, CherryPick/Approved

#2973 MM-16837 Set post list date separator based on user timezone
  package-lock.json
  package.json
Labels: 3: Reviews Complete, CherryPick/Approved

#2947 MM-15954: Display View/Manage Members as appropriate.
  components/main_menu/__snapshots__/main_menu.test.jsx.snap
  components/main_menu/main_menu.jsx
  i18n/en.json
  plugins/test/__snapshots__/main_menu_action.test.jsx.snap
Labels: 3: Reviews Complete, CherryPick/Approved

#2978 Fixing i18n in release-5.13 branch
  components/post_view/channel_intro_message/channel_intro_message.jsx
Labels: 3: Reviews Complete

#2972 MM-15982, MM-15984, Minor Accessibility fixes
  components/__snapshots__/profile_picture.test.jsx.snap
  components/main_menu/__snapshots__/main_menu.test.jsx.snap
  components/main_menu/main_menu.jsx
  components/sidebar/header/sidebar_header_dropdown_button.jsx
  components/sidebar/sidebar_channel_button_or_link/__snapshots__/sidebar_channel_button_or_link_icon.test.jsx.snap
  components/status_dropdown/status_dropdown.jsx
  components/status_icon.jsx
  components/svg/menu_icon.jsx
  components/widgets/menu/menu_items/menu_item_action.jsx
  i18n/en.json
  package-lock.json
  plugins/test/__snapshots__/main_menu_action.test.jsx.snap
  sass/components/_sidebar-header-dropdown-button.scss
  sass/components/_status-icon.scss
  sass/layout/_headers.scss
  sass/layout/_sidebar-left.scss
Labels: 3: Reviews Complete

#2974 translations PR 20190617
  i18n/de.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 3: Reviews Complete

#2975 MM-15988 - Making channel menu accessible
  components/channel_header/__snapshots__/channel_header.test.jsx.snap
  components/channel_header/channel_header.js
  components/channel_header_dropdown/channel_header_dropdown.js
  sass/layout/_headers.scss
Labels: 2: Dev Review

#2926 [MM-9563] Add a red dot to browser favicon when there are unread mentions
  components/sidebar/sidebar.jsx
  components/sidebar/sidebar.test.jsx
  images/favicon/favicon-reddot-16x16.png
  images/favicon/favicon-reddot-32x32.png
  images/favicon/favicon-reddot-96x96.png
  images/favicon/redfavicon-16x16.png
Labels: 3: Reviews Complete

#2933 Fixing channel menu in mobile view with zoom plugin activated
  plugins/mobile_channel_header_plug/__snapshots__/mobile_channel_header_plug.test.jsx.snap
  plugins/mobile_channel_header_plug/mobile_channel_header_plug.jsx
  plugins/mobile_channel_header_plug/mobile_channel_header_plug.test.jsx
Labels: 3: Reviews Complete, CherryPick/Approved

#2879 added the warning message when a user with bot account gets deleted
  components/admin_console/system_users/system_users_dropdown/__snapshots__/system_users_dropdown.test.js.snap
  components/admin_console/system_users/system_users_dropdown/index.js
  components/admin_console/system_users/system_users_dropdown/system_users_dropdown.jsx
  components/admin_console/system_users/system_users_dropdown/system_users_dropdown.test.js
  i18n/en.json
Labels: 3: Reviews Complete

#2985 Fix failing E2E by adding required header when logging in
  cypress/plugins/external_request.js
  cypress/plugins/post_message_as.js
  cypress/support/api_commands.js
Labels: 2: Dev Review

#2950 Fixed text color of dropdown text
  sass/components/_dropdown.scss
Labels: 3: Reviews Complete

#2984 MM-16444 - Adding usernames back to compact view
  components/rhs_comment/rhs_comment.jsx
  sass/layout/_post.scss
  sass/responsive/_tablet.scss
Labels: 3: Reviews Complete, CherryPick/Approved

#2983 MM-16299 - Updating menu divider css on mobile
  sass/responsive/_mobile.scss
Labels: 2: Dev Review, CherryPick/Approved

#2980 MM-16086 - Adding support for navigation to different sections for accessibility
  components/channel_header/__snapshots__/channel_header.test.jsx.snap
  components/channel_header/channel_header.js
  components/create_comment/__snapshots__/create_comment.test.jsx.snap
  components/create_comment/create_comment.jsx
  components/create_post/__snapshots__/create_post.test.jsx.snap
  components/create_post/create_post.jsx
  components/post_view/post/post.jsx
  components/post_view/post_list_virtualized/post_list_virtualized.jsx
  components/rhs_comment/rhs_comment.jsx
  components/rhs_root_post/rhs_root_post.jsx
  components/rhs_thread/rhs_thread.jsx
  components/root/root.jsx
  components/search_bar/search_bar.jsx
  components/sidebar/__snapshots__/sidebar.test.jsx.snap
  components/sidebar/header/sidebar_header.jsx
  components/sidebar/sidebar.jsx
  i18n/en.json
  sass/base/_structure.scss
  sass/layout/_headers.scss
  sass/layout/_sidebar-right.scss
  sass/utils/_modifiers.scss
  utils/utils.jsx
Labels: 2: Dev Review

#2977 MM-16073: File up/download restrictions behind Compliance licence flag.
  components/admin_console/admin_definition.jsx
Labels: 3: Reviews Complete, CherryPick/Approved

#2939 MM-2954: Add a separate post type for /me messages and update formatting
  components/post_markdown/system_message_helpers.jsx
  components/post_view/post/post.jsx
  cypress/integration/channel/message_spec.js
  utils/constants.jsx
Labels: 3: Reviews Complete

#2979 MM-16363 - Fix some flaky Cypress E2E tests
  cypress/fixtures/markdown/markdown_inline_images_3.html
  cypress/fixtures/markdown/markdown_inline_images_4.html
  cypress/fixtures/markdown/markdown_inline_images_5.html
  cypress/integration/channel/message_edit_post_with_attachment_spec.js
  cypress/integration/integrations/integrations_spec.js
  cypress/integration/login/signup_spec.js
  cypress/integration/markdown/markdown_spec.js
  cypress/integration/onboarding/multi_team/existing_channel_name_spec.js
  cypress/integration/system_console/demoted_user_spec.js
  cypress/support/api_commands.js
Labels: 2: Dev Review

#2827 [MM-10017] Plugin framework: add support for plugins to override right-hand sidebar
  actions/views/rhs.js
  components/search_results/search_results.jsx
  components/search_results_header/search_results_header.jsx
  components/sidebar_right/index.js
  components/sidebar_right/sidebar_right.jsx
  plugins/pluggable/pluggable.jsx
  plugins/registry.js
  plugins/rhs_plugin/index.js
  plugins/rhs_plugin/rhs_plugin.jsx
  reducers/views/rhs.js
  reducers/views/rhs.test.js
  selectors/rhs.jsx
  utils/constants.jsx
Labels: 2: Dev Review

#2734 MM-14530 Displays emoji in poll after the poll is ended.
  components/post_view/message_attachments/message_attachment/__snapshots__/message_attachment.test.jsx.snap
  components/post_view/message_attachments/message_attachment/message_attachment.jsx
Labels: 3: Reviews Complete

#2898 [MM-15942] Split user profile details by whitespace during autocomplete
  components/suggestion/at_mention_provider/at_mention_provider.jsx
  components/suggestion/at_mention_provider/at_mention_provider.test.jsx
  package-lock.json
  package.json
Labels: 3: Reviews Complete, CherryPick/Approved

#2988 [MM-16149] Fix username validation message for Bot creation.
  components/integrations/bots/add_bot/add_bot.jsx
Labels: 2: Dev Review

#2996 Fix E2E flaky tests
  cypress/integration/account_settings/display/channel_display_mode_spec.js
  cypress/integration/account_settings/general/nickname.js
  cypress/integration/at_mentions/at_mentions_spec.js
  cypress/integration/channel/edit_message_spec.js
  cypress/integration/channel/message_deletion_spec.js
  cypress/integration/channel/message_draft_spec.js
  cypress/integration/channel/message_draft_then_switch_channel_spec.js
  cypress/integration/channel/message_edit_post_with_attachment_spec.js
  cypress/integration/email/mention_email_notification_spec.js
  cypress/integration/login/login_spec.js
  cypress/integration/login/signup_spec.js
  cypress/integration/post_header/post_header_spec.js
  cypress/integration/search/search_user_post.js
  cypress/plugins/post_message_as.js
  cypress/support/api_commands.js
  cypress/support/ui_commands.js
Labels: 2: Dev Review

#2993 Added livereload support
  package-lock.json
  package.json
  webpack.config.js
Labels: 2: Dev Review

#2992 [MM 7970] Support maintaining online status while the Desktop App is in the background ... and other things.
  actions/global_actions.jsx
  client/websocket_client.jsx
  components/logged_in/logged_in.jsx
  utils/webapp_connector.js
Labels: 3: Reviews Complete

#2981 MM-16423 Fix for missing messages on socket reconnect
  actions/views/channel.js
  actions/views/channel.test.js
  actions/websocket_actions.jsx
  actions/websocket_actions.test.jsx
  components/post_view/index.js
  components/post_view/post_list_virtualized/post_list_virtualized.jsx
  components/post_view/post_list_virtualized/post_list_virtualized.test.jsx
  reducers/views/channel.js
  reducers/views/index.js
  reducers/views/websocket.js
  reducers/views/websocket.test.js
  selectors/views/channel.js
  selectors/views/websocket.js
  utils/constants.jsx
Labels: 3: Reviews Complete, CherryPick/Approved

#2749 [MM-13500] Add group channel search to the More Direct Channels component
  actions/user_actions.jsx
  actions/user_actions.test.js
  components/more_direct_channels/index.js
  components/more_direct_channels/more_direct_channels.jsx
  components/more_direct_channels/more_direct_channels.test.jsx
  package-lock.json
  package.json
Labels: 3: Reviews Complete

#2968 [MM-16244] Add Elasticsearch SkipTLSVerification to the admin console
  components/admin_console/admin_definition.jsx
  components/admin_console/elasticsearch_settings.jsx
  i18n/en.json
Labels: 3: Reviews Complete

#2989 [MM-16235] System Console: Plugins section is missing for restricted system admin
  components/admin_console/admin_definition.jsx
  components/admin_console/plugin_management/__snapshots__/plugin_management.test.jsx.snap
  components/admin_console/plugin_management/plugin_management.jsx
  components/admin_console/plugin_management/plugin_management.test.jsx
  i18n/en.json
Labels: 3: Reviews Complete, CherryPick/Approved

#2997 Build docker image for PR
  .circleci/config.yml
Labels: 3: Reviews Complete

#2995 MM-16381 Fix for Channel intro content sometimes disappears on opening a channel
  package-lock.json
  package.json
Labels: 3: Reviews Complete, CherryPick/Approved

#3001 MM-16442: deprecate use of has_reactions
  components/post_view/reaction_list/__snapshots__/reactions_list.test.jsx.snap
  components/post_view/reaction_list/reaction_list.jsx
  components/post_view/reaction_list/reactions_list.test.jsx
Labels: 2: Dev Review

#3010 MM-16480 Update mattermost-redux
  actions/views/channel.test.js
  package-lock.json
  package.json
Labels: 3: Reviews Complete, CherryPick/Approved

#3005 MM-16527 - Updating bot label in search
  components/admin_console/admin_sidebar_header/admin_sidebar_header.jsx
  components/suggestion/search_channel_provider.jsx
  sass/components/_popover.scss
Labels: 3: Reviews Complete, CherryPick/Approved

#3007 Fix failing E2E specs and add capability to retry twice
  cypress.json
  cypress/integration/channel/header_spec.js
  cypress/integration/channel/system_message_spec.js
  cypress/integration/login/login_spec.js
  cypress/integration/login/signup_spec.js
  cypress/integration/team/teams_spec.js
  cypress/support/api_commands.js
  cypress/support/index.js
  package-lock.json
  package.json
Labels: 3: Reviews Complete

#2982 MM-16259 - Fixing RHS overlap on tablets
  sass/responsive/_tablet.scss
Labels: 3: Reviews Complete, CherryPick/Approved

#3006 MM-15551 - Updating emoji styling on windows
  sass/layout/_post.scss
Labels: 2: Dev Review, CherryPick/Approved

#3014 Fix another batch of failing e2e tests
  components/signup/signup_email/signup_email.jsx
  cypress/fixtures/markdown/markdown_block_quotes_2.html
  cypress/fixtures/markdown/markdown_inline_images_1.html
  cypress/fixtures/markdown/markdown_inline_images_2.html
  cypress/fixtures/markdown/markdown_inline_images_3.html
  cypress/fixtures/markdown/markdown_inline_images_4.html
  cypress/fixtures/markdown/markdown_inline_images_5.html
  cypress/integration/at_mentions/at_mentions_spec.js
  cypress/integration/channel/message_spec.js
  cypress/integration/login/login_spec.js
  cypress/integration/login/signup_spec.js
  cypress/integration/markdown/markdown_image_spec.js
  cypress/integration/markdown/markdown_text_spec.js
  cypress/integration/onboarding/email/existing_email_adress_spec.js
  cypress/integration/search/date_filter_spec.js
  cypress/integration/search/post_search_display.js
  cypress/integration/signin_authentication/forgot_password_spec.js
  cypress/integration/system_console/demoted_user_spec.js
  cypress/plugins/external_request.js
  cypress/plugins/post_message_as.js
  cypress/support/api_commands.js
  cypress/support/index.js
Labels: 2: Dev Review

#3011 translations PR 20190624
  i18n/de.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 3: Reviews Complete

#3016 MM-16552 - Updating system console height
  sass/routes/_admin-console.scss
Labels: 3: Reviews Complete, CherryPick/Approved

#2991 [MM-15381] Write an automated test using Cypress for "Whitespace with emojis does not affect size"
  cypress/integration/messaging/emoji_size_spec.js
Labels: 2: Dev Review

#2987 MM-16152: always focus RHS on SELECT_POST
  actions/post_actions.jsx
  actions/views/rhs.js
  actions/views/rhs.test.js
  components/create_comment/create_comment.jsx
  components/create_comment/create_comment.test.jsx
  components/create_comment/index.js
  reducers/views/rhs.js
  reducers/views/rhs.test.js
  selectors/rhs.jsx
  selectors/rhs.test.js
Labels: 3: Reviews Complete

#2986 MM-16403: LDAP Groups Enable Config only with licence feature.
  components/admin_console/admin_definition.jsx
Labels: CherryPick/Approved

#3020 GH-10574: Added Automated Cypress Test to verify 'M15011 - Emojis show as jumbo in reply thread'
  cypress/integration/channel/message_emoji_jumbo_spec.js
Labels: 3: Reviews Complete

#3003 [MM-16236] System Console restricted admin: Notifications items are missing for restricted system admin
  components/admin_console/admin_definition.jsx
Labels: 3: Reviews Complete, CherryPick/Approved

#3008 MM-15990 - Adding aria-label to header buttons and making members popover button focusable
  components/channel_header/__snapshots__/channel_header.test.jsx.snap
  components/channel_header/channel_header.js
  components/channel_header/components/header_icon_wrapper.js
  components/popover_list_members/__snapshots__/popover_list_members.test.jsx.snap
  components/popover_list_members/popover_list_members.jsx
  components/search_bar/search_bar.jsx
  i18n/en.json
  sass/layout/_headers.scss
  utils/utils.jsx
Labels: 3: Reviews Complete

#2876 GH-10862: Support file upload on paste when File constructor is not supported
  components/file_upload/file_upload.jsx
  components/file_upload/file_upload.test.jsx
Labels: 3: Reviews Complete

#3015 MM-16538 - Updating bot label styling
  components/post_view/post_header/post_header.jsx
  components/rhs_comment/rhs_comment.jsx
  components/rhs_root_post/rhs_root_post.jsx
  components/search_results_item/__snapshots__/search_results_item.test.jsx.snap
  components/search_results_item/search_results_item.jsx
  components/user_profile/__snapshots__/user_profile.test.jsx.snap
  components/user_profile/user_profile.jsx
  components/widgets/badges/badge.scss
  sass/components/_mentions.scss
  sass/components/_popover.scss
  sass/layout/_post.scss
Labels: 2: Dev Review, CherryPick/Approved

#2976 Implementing dark theme for the invitation flow
  components/invitation_modal/__snapshots__/invitation_modal_confirm_step_table.test.jsx.snap
  components/invitation_modal/invitation_modal.scss
  components/invitation_modal/invitation_modal_confirm_step.scss
  components/invitation_modal/invitation_modal_confirm_step_row.scss
  components/invitation_modal/invitation_modal_confirm_step_table.jsx
  components/invitation_modal/invitation_modal_confirm_step_table.scss
  components/invitation_modal/invitation_modal_guests_step.scss
  components/invitation_modal/invitation_modal_initial_step.scss
  components/invitation_modal/invitation_modal_members_step.scss
  components/svg/close_circle_icon.jsx
  components/widgets/inputs/channels_input.scss
  components/widgets/inputs/users_emails_input.scss
  components/widgets/modals/full_screen_modal.scss
  utils/utils.jsx
Labels: 3: Reviews Complete

#3023 MM-16555 - Fixing status icon and status dropdown
  sass/components/_sidebar-header.scss
  sass/layout/_headers.scss
  sass/layout/_sidebar-left.scss
Labels: 3: Reviews Complete

#3013 Auto focus search box in admin console
  components/admin_console/admin_sidebar/admin_sidebar.jsx
Labels: 1: PM Review, 2: Dev Review

#3019 Changes to manage guests (admin console and manage channel and team members)
  components/admin_console/system_users/system_users.jsx
  components/admin_console/system_users/system_users_dropdown/index.js
  components/admin_console/system_users/system_users_dropdown/system_users_dropdown.jsx
  components/admin_console/system_users/system_users_dropdown/system_users_dropdown.test.js
  components/channel_members_dropdown/__snapshots__/channel_members_dropdown.test.jsx.snap
  components/channel_members_dropdown/channel_members_dropdown.jsx
  components/team_members_dropdown/team_members_dropdown.jsx
  i18n/en.json
  package-lock.json
  package.json
  utils/constants.jsx
  utils/get_users.js
Labels: 3: Reviews Complete

#2990 MM-14868 Team Admin can use Next button to page through list in Manage Members
  components/searchable_user_list/searchable_user_list.jsx
  cypress/integration/team/teammates_pagination_spec.js
  cypress/support/api_commands.js
Labels: 2: Dev Review

#3029 E2E: Fix failing tests on account_settings specs
  cypress/integration/account_settings/display/message_display_mode_spec.js
  cypress/integration/account_settings/theme_color/custom_colors_sidebar_styles_spec.js
  cypress/support/index.js
Labels: 2: Dev Review

#3030 MM-16648 - Updating bot badge in center channel
  components/user_profile/__snapshots__/user_profile.test.jsx.snap
  components/user_profile/user_profile.jsx
Labels: 3: Reviews Complete, CherryPick/Approved

#2843 Updating help text and error message for choosing username on sign up page
  components/signup/signup_email/signup_email.jsx
  i18n/en.json
Labels: 3: Reviews Complete

#3024 MM-15324-DOC post types can apply for ephemeral posts
  plugins/registry.js
Labels: 3: Reviews Complete
