Repository mattermost/mattermost-webapp, pull requests merged in 2019-10, with the labels that each got.

#3779 Added Cypress Test to verify behavior when Guest User is removed from channel
  components/removed_from_channel_modal/__snapshots__/removed_from_channel_modal.test.jsx.snap
  components/removed_from_channel_modal/removed_from_channel_modal.jsx
  components/team_sidebar/team_sidebar_controller.jsx
  e2e/cypress/integration/enterprise/guest_accounts/guest_removal_ui_spec.js
  e2e/cypress/support/api_commands.js
Labels: 2: QA Review, CherryPick/Approved

#3819 Automated cherry pick of #3779
  components/removed_from_channel_modal/__snapshots__/removed_from_channel_modal.test.jsx.snap
  components/removed_from_channel_modal/removed_from_channel_modal.jsx
  components/team_sidebar/team_sidebar_controller.jsx
  e2e/cypress/integration/enterprise/guest_accounts/guest_removal_ui_spec.js
  e2e/cypress/support/api_commands.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3806 Automated cherry pick of #3802
  components/search_results/search_results.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3792 Added Cypress testcase to verify the restrictions when a Guest User is promoted as a Regular member
  e2e/cypress/integration/enterprise/guest_accounts/guest_experience_ui_spec.js
  e2e/cypress/support/api_commands.js
Labels: Awaiting Submitter Action, CherryPick/Approved

#3775 MM18716 - Add e2e test to remove last post in channel
  e2e/cypress/integration/messaging/remove_last_post_in_channel_spec.js
Labels: 3: Reviews Complete

#3803 MM-18932 - Updating header quotes css
  sass/layout/_headers.scss
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#3795 [MM-18875] Blur file attachment link on click
  components/file_attachment/__snapshots__/filename_overlay.test.jsx.snap
  components/file_attachment/file_attachment.jsx
  components/file_attachment/file_attachment.test.jsx
  components/file_attachment/filename_overlay.jsx
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done, Setup Cloud Test Server

#3827 Automated cherry pick of #3795
  components/file_attachment/__snapshots__/filename_overlay.test.jsx.snap
  components/file_attachment/file_attachment.jsx
  components/file_attachment/file_attachment.test.jsx
  components/file_attachment/filename_overlay.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3788 Added Cypress test to Verify Guest Invitation Flow when different feature settings are disabled
  e2e/cypress/integration/enterprise/guest_accounts/guest_invitation_ui_spec.js
Labels: 3: Reviews Complete, CherryPick/Approved

#3830 Automated cherry pick of #3788
  e2e/cypress/integration/enterprise/guest_accounts/guest_invitation_ui_spec.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3826 [MM-19042] Plugins settings page won't load in 5.16
  components/admin_console/custom_plugin_settings/index.js
Labels: 3: Reviews Complete, CherryPick/Approved

#3831 Automated cherry pick of #3826
  components/admin_console/custom_plugin_settings/index.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3794 Make hover/focus effect more subtle
  sass/layout/_post.scss
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#3699 M17451 Channel shortlinking
  e2e/cypress/integration/channel/message_shortlinking_spec.js
Labels: 3: Reviews Complete, QA Review Done

#3716 MM-18620 - Marketplace icons white background
  components/plugin_marketplace/__snapshots__/marketplace_modal.test.jsx.snap
  components/plugin_marketplace/marketplace_item/__snapshots__/marketplace_item.test.jsx.snap
  components/plugin_marketplace/marketplace_item/marketplace_item.jsx
  components/plugin_marketplace/marketplace_modal.jsx
  components/plugin_marketplace/marketplace_modal.scss
Labels: 2: Dev Review, CherryPick/Approved, QA Review Done

#3836 Automated cherry pick of #3716
  components/plugin_marketplace/__snapshots__/marketplace_modal.test.jsx.snap
  components/plugin_marketplace/marketplace_item/__snapshots__/marketplace_item.test.jsx.snap
  components/plugin_marketplace/marketplace_item/marketplace_item.jsx
  components/plugin_marketplace/marketplace_modal.jsx
  components/plugin_marketplace/marketplace_modal.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3812 MM-18915 Migrate 'utils/paste.jsx' to TypeScript
  components/create_comment/create_comment.jsx
  components/create_post/create_post.jsx
  components/file_upload/file_upload.jsx
  utils/paste.test.jsx
  utils/paste.test.tsx
  utils/paste.tsx
Labels: 3: Reviews Complete, Hacktoberfest, QA Review Done

#3727 MM-18481 - Common component: Separator
  components/post_view/date_separator/__snapshots__/date_separator.test.jsx.snap
  components/post_view/date_separator/date_separator.jsx
  components/post_view/new_message_separator/__snapshots__/new_message_separator.test.jsx.snap
  components/post_view/new_message_separator/new_message_separator.jsx
  components/widgets/separator/__snapshots__/separator.test.tsx.snap
  components/widgets/separator/basic-separator.tsx
  components/widgets/separator/notification-separator.scss
  components/widgets/separator/notification-separator.tsx
  components/widgets/separator/separator.scss
  components/widgets/separator/separator.stories.js
  components/widgets/separator/separator.test.tsx
  sass/layout/_post.scss
  sass/responsive/_desktop.scss
  sass/responsive/_mobile.scss
  sass/routes/_print.scss
Labels: QA Review Done

#3821 MM-18913: Migrate latinise.tsx and tests to Typescript
  utils/latinise.test.jsx
  utils/latinise.test.tsx
  utils/latinise.tsx
  utils/url.jsx
Labels: 3: Reviews Complete, Hacktoberfest

#3824 Automated cherry pick of #3803
  sass/layout/_headers.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3814 Automated cherry pick of #3799
  components/permalink_redirector/permalink_redirector.test.jsx
  components/root/root.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3834 Automated cherry pick of #3794
  sass/layout/_post.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3743 translations PR 20190923
  i18n/de.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 2: Dev Review

#3822 MM-18849 Remove default selection of the first emoji
  components/emoji_picker/emoji_picker.jsx
  components/emoji_picker/emoji_picker.test.jsx
Labels: 2: Dev Review, CherryPick/Approved, QA Review Done

#3833 Migrating components/analytics/format.jsx to typescript.
  components/analytics/format.tsx
  components/analytics/system_analytics/system_analytics.jsx
  components/analytics/team_analytics/team_analytics.jsx
Labels: 3: Reviews Complete, Hacktoberfest

#3847 Automated cherry pick of #3822
  components/emoji_picker/emoji_picker.jsx
  components/emoji_picker/emoji_picker.test.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3807 Re-add semver package
  package-lock.json
  package.json
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#3839 MM-18926 Migrate 'components/analytics/statistic_count.jsx' to TypeScript
  components/analytics/__snapshots__/statistic_count.test.tsx.snap
  components/analytics/statistic_count.test.tsx
  components/analytics/statistic_count.tsx
  components/analytics/system_analytics/system_analytics.jsx
  components/analytics/team_analytics/team_analytics.jsx
Labels: 3: Reviews Complete, Hacktoberfest

#3849 [MM-17624] Update redux commit to pull in changes
  package-lock.json
  package.json
Labels: 3: Reviews Complete

#3850 [MM-17624] Redux update
  package-lock.json
  package.json
Labels: 3: Reviews Complete

#3844 MM-18991 - Migrate components/spinner_button and related tests to Typescript
  components/__snapshots__/spinner_button.test.tsx.snap
  components/emoji/add_emoji/add_emoji.jsx
  components/integrations/abstract_command.jsx
  components/integrations/abstract_incoming_webhook.jsx
  components/integrations/abstract_oauth_app.jsx
  components/integrations/abstract_outgoing_webhook.jsx
  components/integrations/bots/add_bot/add_bot.jsx
  components/spinner_button.test.tsx
  components/spinner_button.tsx
Labels: 3: Reviews Complete, Hacktoberfest

#3851 Cypress E2E - Add additional waits when searching search date filter
  e2e/cypress/integration/search/date_filter_spec.js
Labels: 2: QA Review

#3766 [MM-18108] User settings: remove teams, edit roles
  components/admin_console/system_user_detail/system_user_detail.scss
  components/admin_console/system_user_detail/team_list/__snapshots__/abstract_list.test.jsx.snap
  components/admin_console/system_user_detail/team_list/__snapshots__/team_list.test.jsx.snap
  components/admin_console/system_user_detail/team_list/abstract_list.test.jsx
  components/admin_console/system_user_detail/team_list/index.js
  components/admin_console/system_user_detail/team_list/team_list.jsx
  components/admin_console/system_user_detail/team_list/team_list.test.jsx
  components/admin_console/system_user_detail/team_list/team_list_dropdown.jsx
  components/admin_console/system_user_detail/team_list/team_row.jsx
  components/admin_console/system_user_detail/team_list/team_row.scss
  components/widgets/icons/ellipsis_h_icon.jsx
  components/widgets/menu/menu_items/menu_item_action.jsx
  i18n/en.json
Labels: 3: Reviews Complete, QA Review Done

#3757 MM-18013 Allow configuration of SAML crypto hashing algorithms
  components/admin_console/admin_definition.jsx
  components/admin_console/admin_definition.test.jsx
  components/admin_console/schema_admin_settings.jsx
  i18n/en.json
Labels: 3: Reviews Complete

#3816 change the plugins icon in the channel header - in case of multiple p…
  components/widgets/icons/plugin_channel_header_icon.jsx
  i18n/en.json
  plugins/channel_header_plug/__snapshots__/channel_header_plug.test.jsx.snap
  plugins/channel_header_plug/channel_header_plug.jsx
  plugins/channel_header_plug/channel_header_plug.test.jsx
  sass/layout/_headers.scss
Labels: Hacktoberfest

#3842 [MM-18918] Migrate 'utils/server_version.jsx' and associated tests to TypeScript
  components/announcement_bar/version_bar/version_bar.jsx
  components/system_notice/notices.jsx
  utils/server_version.test.tsx
  utils/server_version.tsx
Labels: 3: Reviews Complete, Hacktoberfest

#3832 Showing properly guest badge on channel group message header with full name
  components/channel_header/channel_header.js
  components/channel_header/index.js
Labels: 3: Reviews Complete, CherryPick/Approved

#3854 Automated cherry pick of #3832
  components/channel_header/channel_header.js
  components/channel_header/index.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3843 [MM-18980] Migrate components/form-error to TypeScript
  components/admin_console/admin_settings.jsx
  components/admin_console/brand_image_setting/brand_image_setting.jsx
  components/admin_console/multiselect_settings.jsx
  components/admin_console/permission_schemes_settings/permission_system_scheme_settings/permission_system_scheme_settings.jsx
  components/admin_console/permission_schemes_settings/permission_team_scheme_settings/permission_team_scheme_settings.jsx
  components/admin_console/schema_admin_settings.jsx
  components/admin_console/system_user_detail/system_user_detail.jsx
  components/authorize/authorize.jsx
  components/emoji/add_emoji/add_emoji.jsx
  components/form_error.tsx
  components/integrations/abstract_command.jsx
  components/integrations/abstract_incoming_webhook.jsx
  components/integrations/abstract_oauth_app.jsx
  components/integrations/abstract_outgoing_webhook.jsx
  components/integrations/bots/add_bot/add_bot.jsx
  components/integrations/installed_oauth_app/installed_oauth_app.jsx
  components/login/login_controller/login_controller.jsx
  components/setting_picture.jsx
  components/signup/signup_controller/signup_controller.jsx
Labels: 3: Reviews Complete, Hacktoberfest, QA Review Done

#3852 E2E Cypress: leverage wait until in the system_console_spec for elastic search
  e2e/cypress/integration/enterprise/elasticsearch/system_console_spec.js
Labels: 3: Reviews Complete

#3497 [MM-13675] [e2e-UI Automation] Copy a permalink and paste into another channel
  components/dot_menu/__snapshots__/dot_menu.test.jsx.snap
  components/dot_menu/dot_menu.jsx
  e2e/cypress/integration/messaging/message_permalink_spec.js
  e2e/cypress/support/api_commands.js
Labels: 2: Dev Review, Hacktoberfest, QA Review Done

#3787 GH 12301 - Adding mobile view profile popover test
  e2e/cypress/integration/messaging/mobile_profile_popover_spec.js
Labels: 2: Dev Review, Hacktoberfest, QA Review Done

#3859 Remove ESLint rule for typescript non null assertion operator
  .eslintrc.json
Labels: 3: Reviews Complete

#3865 MM-19151 - Plugin Marketplace: Typing fast on search box does not ret…
  components/plugin_marketplace/marketplace_modal.jsx
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#3868 Automated cherry pick of #3865
  components/plugin_marketplace/marketplace_modal.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3546 [MM-17388] Selecting an emoji from emoji picker should insert it at the cursor position
  components/__snapshots__/textbox.test.jsx.snap
  components/create_comment/__snapshots__/create_comment.test.jsx.snap
  components/create_comment/create_comment.jsx
  components/create_comment/create_comment.test.jsx
  components/create_post/__snapshots__/create_post.test.jsx.snap
  components/create_post/create_post.jsx
  components/create_post/create_post.test.jsx
  components/edit_post_modal/__snapshots__/edit_post_modal.test.jsx.snap
  components/edit_post_modal/edit_post_modal.jsx
  components/edit_post_modal/edit_post_modal.test.jsx
  components/textbox/textbox.jsx
  utils/post_utils.jsx
  utils/post_utils.test.jsx
Labels: 3: Reviews Complete, Hacktoberfest

#3838 MM-18923 Migrate 'components/analytics/doughnut_chart.jsx' to TypeScript
  components/analytics/__snapshots__/doughnut_chart.test.tsx.snap
  components/analytics/doughnut_chart.test.tsx
  components/analytics/doughnut_chart.tsx
  components/analytics/system_analytics/system_analytics.jsx
  package-lock.json
  package.json
Labels: 3: Reviews Complete, Hacktoberfest

#3719 MM-17930 - Remove saveConfig action
  actions/admin_actions.jsx
  components/admin_console/admin_console.jsx
  components/admin_console/admin_settings.jsx
  components/admin_console/custom_terms_of_service_settings/custom_terms_of_service_settings.jsx
  components/admin_console/index.js
Labels: 3: Reviews Complete, Hacktoberfest

#3864 Update eslint-config for typescript
  package-lock.json
  package.json
Labels: 2: Dev Review

#3856 [MM-18958] Migrate components/get_android_app to TypeScript
  components/get_android_app/__snapshots__/get_android_app.test.tsx.snap
  components/get_android_app/get_android_app.test.tsx
  components/get_android_app/get_android_app.tsx
  components/get_android_app/index.js
  package-lock.json
  package.json
Labels: 3: Reviews Complete, Hacktoberfest, QA Review Done

#3818 migrate 'utils/dragster' to typescript
  components/file_upload/file_upload.jsx
  utils/dragster.test.ts
  utils/dragster.ts
Labels: 3: Reviews Complete, Hacktoberfest, QA Review Done

#3881 [MM-18984] Migrate components/loading_screen to TypeScript
  components/access_history_modal/access_history_modal.jsx
  components/access_history_modal/access_history_modal.test.jsx
  components/activity_log_modal/activity_log_modal.jsx
  components/activity_log_modal/activity_log_modal.test.jsx
  components/admin_console/audits/audits.jsx
  components/admin_console/cluster_table_container.jsx
  components/admin_console/compliance_reports/compliance_reports.jsx
  components/admin_console/custom_terms_of_service_settings/custom_terms_of_service_settings.jsx
  components/admin_console/manage_teams_modal/manage_teams_modal.jsx
  components/admin_console/manage_tokens_modal/manage_tokens_modal.jsx
  components/admin_console/permission_schemes_settings/permission_schemes_settings.jsx
  components/admin_console/permission_schemes_settings/permission_system_scheme_settings/permission_system_scheme_settings.jsx
  components/admin_console/permission_schemes_settings/permission_team_scheme_settings/permission_team_scheme_settings.jsx
  components/admin_console/plugin_management/plugin_management.jsx
  components/admin_console/schema_admin_settings.jsx
  components/admin_console/server_logs/logs.jsx
  components/analytics/team_analytics/team_analytics.jsx
  components/backstage/components/backstage_list.jsx
  components/do_verify_email/do_verify_email.jsx
  components/emoji/emoji_list/emoji_list.jsx
  components/integrations/edit_command/edit_command.jsx
  components/integrations/edit_incoming_webhook/edit_incoming_webhook.jsx
  components/integrations/edit_oauth_app/edit_oauth_app.jsx
  components/integrations/edit_outgoing_webhook/edit_outgoing_webhook.jsx
  components/list_modal.jsx
  components/loading_screen.tsx
  components/logged_in/logged_in.jsx
  components/login/login_controller/login_controller.jsx
  components/multiselect/multiselect_list.jsx
  components/plugin_marketplace/marketplace_modal.jsx
  components/post_view/post_list/post_list.jsx
  components/post_view/post_view.jsx
  components/select_team/select_team.jsx
  components/signup/signup_controller/signup_controller.jsx
  components/signup/signup_email/signup_email.jsx
  components/terms_of_service/terms_of_service.jsx
  components/user_list.jsx
Labels: 3: Reviews Complete, Hacktoberfest, QA Review Done

#3739 Improving redirect on guest accounts
  components/channel_layout/channel_controller.jsx
  components/channel_layout/channel_controller.test.jsx
  components/channel_layout/channel_identifier_router/actions.js
  components/channel_view/channel_view.jsx
  components/needs_team/__snapshots__/needs_team.test.jsx.snap
  components/needs_team/needs_team.jsx
  components/needs_team/needs_team.test.jsx
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#3791 MM-17767: Changes for the removal of ExperimentalLdapGroupSync config.
  components/admin_console/admin_definition.jsx
  components/admin_console/admin_sidebar/admin_sidebar.test.jsx
  e2e/cypress/integration/enterprise/system_console/channel_modes_spec.js
  i18n/en.json
Labels: Do Not Merge/Awaiting PR, QA Review Done

#3899 Automated cherry pick of #3886
  components/channel_header/index.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3855 MM-18925 - Migrate 'components/analytics/line_chart.jsx' and associated tests to TypeScript
  components/analytics/__snapshots__/line_chart.test.tsx.snap
  components/analytics/line_chart.test.tsx
  components/analytics/line_chart.tsx
  components/analytics/system_analytics/system_analytics.jsx
  components/analytics/team_analytics/team_analytics.jsx
  package-lock.json
  package.json
Labels: 3: Reviews Complete, Hacktoberfest

#3755 Update NOTICE.txt
  NOTICE.txt
Labels: 3: Reviews Complete, CherryPick/Approved

#3900 Automated cherry pick of #3755
  NOTICE.txt
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3863 [MM-18949] prevent context menu to appear when holding the left click
  components/copy_url_context_menu/__snapshots__/copy_url_context_menu.test.jsx.snap
  components/copy_url_context_menu/copy_url_context_menu.jsx
Labels: 1: PM Review, QA Review Done

#3632 MM-18441 Clarify bot account creation flow
  components/admin_console/admin_definition.jsx
  components/integrations/bots/bots.jsx
  i18n/en.json
Labels: 3: Reviews Complete, CherryPick/Approved

#3861 Showing server error when trying to use a team invite link as a guest
  components/signup/signup_controller/signup_controller.jsx
Labels: 2: QA Review, CherryPick/Approved

#3901 [MM-19247] Fix Invite Guests Permission in custom Team Scheme
  utils/constants.jsx
Labels: 3: Reviews Complete, CherryPick/Approved

#3912 Automated cherry pick of #3901
  utils/constants.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3909 Automated cherry pick of #3861
  components/signup/signup_controller/signup_controller.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3913 Fixing problem saving config because saveConfig function has disappeared
  components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
  components/admin_console/custom_plugin_settings/custom_plugin_settings.test.jsx
  components/admin_console/schema_admin_settings.jsx
  components/admin_console/schema_admin_settings.test.jsx
Labels: QA Review Done, Setup Cloud Test Server

#3902 force click for profile popover e2e test
  e2e/cypress/integration/messaging/mobile_profile_popover_spec.js
Labels: 3: Reviews Complete

#3880 Migrate 'components/post_emoji' module and associated tests to TypeScript
  components/post_emoji/index.jsx
  components/post_emoji/post_emoji.test.tsx
  components/post_emoji/post_emoji.tsx
Labels: 2: Dev Review, Hacktoberfest, QA Review Done, Tests/Not Needed

#3903 MM-18993 Migrate 'components/toggle.jsx' to TypeScript
  components/toggle.tsx
Labels: 3: Reviews Complete

#3357 MM-16946 plugin dot_menu submenus
  actions/global_actions.jsx
  components/dot_menu/dot_menu.jsx
  components/widgets/menu/menu.jsx
  components/widgets/menu/menu.scss
  components/widgets/menu/menu_items/menu_item.scss
  components/widgets/menu/menu_items/submenu_item.jsx
  components/widgets/menu/menu_items/submenu_item.test.jsx
  components/widgets/menu/menu_modals/submenu_modal/__snapshots__/submenu_modal.test.jsx.snap
  components/widgets/menu/menu_modals/submenu_modal/submenu_modal.jsx
  components/widgets/menu/menu_modals/submenu_modal/submenu_modal.scss
  components/widgets/menu/menu_modals/submenu_modal/submenu_modal.test.jsx
  i18n/en.json
  plugins/registry.js
  reducers/plugins/index.js
  sass/responsive/_mobile.scss
  utils/constants.jsx
Labels: QA Review Done

#3841 [MM-18969] Migrate components/search_hint to TypeScript
  components/search_hint/__snapshots__/search_hint.test.tsx.snap
  components/search_hint/search_hint.test.tsx
  components/search_hint/search_hint.tsx
Labels: 3: Reviews Complete, Hacktoberfest

#3756 MM-18512 Correctly filter and request inactive users in system console user list
  actions/user_actions.jsx
  actions/user_actions.test.js
  components/admin_console/system_users/list/system_users_list.jsx
  components/admin_console/system_users/list/system_users_list.test.jsx
  components/admin_console/system_users/system_users.jsx
  components/admin_console/system_users/system_users.test.jsx
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#3879 Migrate 'components/get_ios_app' module and associated tests to TypeScript
  components/get_ios_app/__snapshots__/get_ios_app.test.tsx.snap
  components/get_ios_app/get_ios_app.test.tsx
  components/get_ios_app/get_ios_app.tsx
  components/get_ios_app/index.js
Labels: 3: Reviews Complete, Hacktoberfest, QA Review Done, Tests/Not Needed

#3925 Automated cherry pick of #3756
  actions/user_actions.jsx
  actions/user_actions.test.js
  components/admin_console/system_users/list/system_users_list.jsx
  components/admin_console/system_users/list/system_users_list.test.jsx
  components/admin_console/system_users/system_users.jsx
  components/admin_console/system_users/system_users.test.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3872 [MM-18965] Migrate components/msg_typing to TypeScript
  components/msg_typing/__snapshots__/msg_typing.test.tsx.snap
  components/msg_typing/index.js
  components/msg_typing/msg_typing.test.tsx
  components/msg_typing/msg_typing.tsx
Labels: 3: Reviews Complete, Hacktoberfest, QA Review Done, Tests/Not Needed

#3876 [GH-12442] Convert profile_picture and related test to typescript
  components/__snapshots__/profile_picture.test.tsx.snap
  components/admin_console/admin_user_card/admin_user_card.jsx
  components/channel_invite_modal/channel_invite_modal.jsx
  components/more_direct_channels/more_direct_channels.jsx
  components/post_view/channel_intro_message/channel_intro_message.jsx
  components/profile_picture.test.tsx
  components/profile_picture.tsx
  components/user_list_row/user_list_row.jsx
  components/user_list_row_with_error/user_list_row_with_error.jsx
  package-lock.json
  package.json
  types/images.d.ts
Labels: 3: Reviews Complete, Hacktoberfest, QA Review Done, Tests/Not Needed

#3837 typescript for components/widgets/users
  .storybook/config.js
  components/admin_console/manage_tokens_modal/manage_tokens_modal.jsx
  components/widgets/users/avatar.test.tsx
  components/widgets/users/avatar.tsx
  components/widgets/users/users.stories.tsx
Labels: 3: Reviews Complete, Hacktoberfest

#3813 Migrate position utils to typescript
  components/at_mention/at_mention.jsx
  components/emoji_picker/emoji_picker_overlay.jsx
  utils/position_utils.jsx
  utils/position_utils.test.jsx
  utils/position_utils.test.tsx
  utils/position_utils.tsx
Labels: 3: Reviews Complete, Hacktoberfest, QA Review Done

#3915 MM-19199 - Page/tab title when leaving all teams shows 'undefined'
  components/sidebar/sidebar.jsx
  components/sidebar/sidebar.test.jsx
  i18n/en.json
Labels: 2: Dev Review, CherryPick/Approved, QA Review Done

#3906 MM-18881 - Attempting to configure uninstalled plugins gets stuck at Loading... without timeout.
  components/plugin_marketplace/index.js
  components/plugin_marketplace/marketplace_modal.jsx
  components/plugin_marketplace/marketplace_modal.test.jsx
Labels: QA Review Done

#3922 [MM-19339] Fix tabbing in modals and multi post-hover-menus
  utils/a11y_controller.js
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#3935 Automated cherry pick of #3922
  utils/a11y_controller.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3933 Automated cherry pick of #3915
  components/sidebar/sidebar.jsx
  components/sidebar/sidebar.test.jsx
  i18n/en.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3914 Fixing guest being removed from other not-visible user from a channel
  actions/websocket_actions.jsx
  actions/websocket_actions.test.jsx
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#3940 Automated cherry pick of #3914
  actions/websocket_actions.jsx
  actions/websocket_actions.test.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3939 Fix settings for guest MFA authentication in the admin console
  components/admin_console/admin_definition.jsx
Labels: 3: Reviews Complete, CherryPick/Approved

#3905 [MM-19217] Include iPad in check for ios web
  utils/user_agent.jsx
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#3942 Automated cherry pick of #3939
  components/admin_console/admin_definition.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3944 Automated cherry pick of #3905
  utils/user_agent.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3923 MM-18823 - Saving empty string on Marketplace URL resets the URL instead of showing error
  components/admin_console/plugin_management/__snapshots__/plugin_management.test.jsx.snap
  components/admin_console/plugin_management/plugin_management.jsx
  i18n/en.json
Labels: QA Review Done

#3958 translations PR 20191014
  i18n/de.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 3: Reviews Complete, Tests/Not Needed

#3926 MM-19110 - Updating dropdown menu item
  components/widgets/menu/menu_items/menu_item.scss
  sass/layout/_headers.scss
Labels: 3: Reviews Complete, QA Review Done, Tests/Not Needed

#3961 Showing Leave channel for guest accounts in town square
  components/channel_header_dropdown/channel_header_dropdown_items.js
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#3963 Automated cherry pick of #3961
  components/channel_header_dropdown/channel_header_dropdown_items.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3931 Mm 19290 MM-19107 - Minor theme improvements
  components/permalink_view/permalink_view.jsx
  components/widgets/separator/separator.scss
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#3930 MM-19221 - Updating profile popover
  components/__snapshots__/profile_picture.test.tsx.snap
  components/at_mention/__snapshots__/at_mention.test.jsx.snap
  components/at_mention/at_mention.jsx
  components/profile_picture.tsx
  components/user_profile/__snapshots__/user_profile.test.jsx.snap
  components/user_profile/user_profile.jsx
  sass/components/_popover.scss
Labels: 3: Reviews Complete, QA Review Done

#3928 MM-19220 - Updating channel switcher modal mobile
  sass/responsive/_mobile.scss
Labels: 2: Dev Review, CherryPick/Approved, QA Review Done

#3967 Automated cherry pick of #3928
  sass/responsive/_mobile.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3817 Help text in the status dropdown updated to Disables desktop, email a…
  components/status_dropdown/status_dropdown.jsx
  i18n/en.json
Labels: 3: Reviews Complete, Hacktoberfest, QA Review Done

#3846 MM-19108 Hide profile pic for consecutive messages of the same user
  components/post_view/post/post.jsx
  e2e/cypress/integration/channel/message_spec.js
Labels: 3: Reviews Complete, QA Review Done

#3829 MM-18920 Migrate 'utils/url.jsx' and associated tests to TypeScript
  actions/command.js
  actions/websocket_actions.jsx
  components/admin_console/group_settings/group_details/group_users.jsx
  components/admin_console/group_settings/group_settings.jsx
  components/admin_console/message_export_settings.jsx
  components/admin_console/system_users/system_users_dropdown/system_users_dropdown.jsx
  components/channel_info_modal/channel_info_modal.jsx
  components/create_team/components/display_name.jsx
  components/create_team/components/team_url/team_url.jsx
  components/get_post_link_modal/index.js
  components/help/components/formatting.jsx
  components/integrations/confirm_integration/confirm_integration.jsx
  components/integrations/installed_incoming_webhook.jsx
  components/invitation_modal/invitation_modal_members_step.jsx
  components/markdown/index.js
  components/more_channels/more_channels.jsx
  components/new_channel_modal/new_channel_modal.jsx
  components/rename_channel_modal/index.js
  components/rename_channel_modal/rename_channel_modal.jsx
  components/root/root.jsx
  components/tutorial/tutorial_intro_screens/tutorial_intro_screens.jsx
  plugins/index.js
  utils/markdown/renderer.jsx
  utils/url.test.tsx
  utils/url.tsx
Labels: 3: Reviews Complete, Hacktoberfest, QA Review Done

#3869 MM-12463 Migrate 'components/localized_input' module and associated tests to TypeScript
  components/localized_input/__snapshots__/localized_input.test.tsx.snap
  components/localized_input/localized_input.jsx
  components/localized_input/localized_input.test.tsx
  components/localized_input/localized_input.tsx
Labels: 3: Reviews Complete, Hacktoberfest, QA Review Done

#3895 MM-12446 Migrate 'components/loading_image_preview.jsx' and associated tests to TypeScript
  components/__snapshots__/loading_image_preview.test.tsx.snap
  components/loading_image_preview.test.tsx
  components/loading_image_preview.tsx
Labels: 3: Reviews Complete, Hacktoberfest, QA Review Done

#3882 Migrate 'components/message_submit_error.jsx' and associated tests to TypeScript
  components/message_submit_error.test.tsx
  components/message_submit_error.tsx
Labels: 3: Reviews Complete, Hacktoberfest, QA Review Done

#3972 Automated cherry pick of #3968
  components/channel_members_dropdown/__snapshots__/channel_members_dropdown.test.jsx.snap
  components/channel_members_dropdown/channel_members_dropdown.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3943 MM-19252 - Making max length visible on mobile
  sass/responsive/_mobile.scss
Labels: CherryPick/Approved, QA Review Done

#3924 Added UI checks for boolean checkbox for interaction dialog e2e test
  e2e/cypress/integration/interactive_dialog/full_dialog_spec.js
  e2e/utils/webhook_utils.js
Labels: 2: QA Review

#3934 MM-18860 Update react-window to re-render posts correctly
  package-lock.json
  package.json
Labels: 2: Dev Review, QA Review Done

#3904 MM-12443 Migrate 'components/post_deleted_modal.jsx' and associated tests to TypeScript
  components/__snapshots__/post_deleted_modal.test.tsx.snap
  components/create_comment/create_comment.jsx
  components/create_post/create_post.jsx
  components/post_deleted_modal.test.tsx
  components/post_deleted_modal.tsx
Labels: 3: Reviews Complete, Hacktoberfest, QA Review Done

#3975 MM-19331 - Updating actions structure in backstage
  components/integrations/__snapshots__/installed_command.test.jsx.snap
  components/integrations/__snapshots__/installed_incoming_webhook.test.jsx.snap
  components/integrations/__snapshots__/installed_outgoing_webhook.test.jsx.snap
  components/integrations/bots/bot.jsx
  components/integrations/installed_command.jsx
  components/integrations/installed_incoming_webhook.jsx
  components/integrations/installed_oauth_app/__snapshots__/installed_oauth_app.test.jsx.snap
  components/integrations/installed_oauth_app/installed_oauth_app.jsx
  components/integrations/installed_outgoing_webhook.jsx
  sass/responsive/_mobile.scss
  sass/routes/_backstage.scss
Labels: 2: Dev Review, QA Review Done, Tests/Done

#3896 MM-18994 - Migrate `components/unread_channel_indicator` to TypeScript
  components/__snapshots__/unread_channel_indicator.test.tsx.snap
  components/sidebar/sidebar.jsx
  components/unread_channel_indicator.test.tsx
  components/unread_channel_indicator.tsx
Labels: 3: Reviews Complete, Hacktoberfest, QA Review Done

#3966 [MM-18689] UI Automation: Write an automated test using Cypress for ""Message too long" warning text"
  e2e/cypress/integration/messaging/message_reply_too_long_spec.js
Labels: 3: Reviews Complete, QA Review Done

#3952 remove unused method, addEmoji
  actions/emoji_actions.jsx
Labels: 3: Reviews Complete, Hacktoberfest, QA Review Done

#3893 MM18697 - Add tests to check if tooltips show up when post menu icons are hovered
  components/common/comment_icon.jsx
  components/post_view/post_reaction/__snapshots__/post_reaction.test.jsx.snap
  components/post_view/post_reaction/post_reaction.jsx
  e2e/cypress/integration/messaging/tooltip_visual_verification_spec.js
Labels: 3: Reviews Complete, Hacktoberfest

#3986 Automated cherry pick of #3863
  components/copy_url_context_menu/__snapshots__/copy_url_context_menu.test.jsx.snap
  components/copy_url_context_menu/copy_url_context_menu.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3959 [MM-19373] When cancel button has focus in ConfirmModal, pressing enter should cancel
  components/confirm_modal.jsx
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#3988 Automated cherry pick of #3906
  components/plugin_marketplace/index.js
  components/plugin_marketplace/marketplace_modal.jsx
  components/plugin_marketplace/marketplace_modal.test.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3989 Automated cherry pick of #3959
  components/confirm_modal.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3992 Cherry pick of #3885 Fix basename in paths to System Console
  components/admin_console/admin_definition.jsx
  components/announcement_bar/configuration_bar/configuration_bar.jsx
  components/announcement_bar/configuration_bar/index.js
  components/integrations/bots/bots.jsx
  components/plugin_marketplace/__snapshots__/marketplace_modal.test.jsx.snap
  components/plugin_marketplace/index.js
  components/plugin_marketplace/marketplace_modal.jsx
  components/plugin_marketplace/marketplace_modal.test.jsx
  i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed

#3991 Automated cherry pick of #3923
  components/admin_console/plugin_management/__snapshots__/plugin_management.test.jsx.snap
  components/admin_console/plugin_management/plugin_management.jsx
  i18n/en.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3985 [MM-19497] Fixed focusing on search results/mentions RHS
  components/search_results_item/__snapshots__/search_results_item.test.jsx.snap
  components/search_results_item/search_results_item.jsx
  components/search_results_item/search_results_item.test.jsx
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#3994 Automated cherry pick of #3985
  components/search_results_item/__snapshots__/search_results_item.test.jsx.snap
  components/search_results_item/search_results_item.jsx
  components/search_results_item/search_results_item.test.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3823 MM-18508 For empty or broken links - show a broken image
  components/__snapshots__/markdown_image.test.jsx.snap
  components/markdown_image.jsx
  components/markdown_image.test.jsx
  images/icons/brokenimage.png
Labels: CherryPick/Approved, QA Review Done, Tests/Not Needed

#3848 MM-18784 Removed deprecated methods
  components/channel_view/channel_view.jsx
  components/permalink_view/permalink_view.jsx
  components/permalink_view/permalink_view.test.jsx
  components/post_view/new_messages_below/new_messages_below.jsx
  components/rhs_thread/rhs_thread.jsx
  components/rhs_thread/rhs_thread.test.jsx
  sass/layout/_post.scss
Labels: 3: Reviews Complete, Hacktoberfest, QA Review Done

#3768 Remove displayDate method from utils.jsx
  components/admin_console/license_settings/license_settings.jsx
  utils/utils.jsx
Labels: QA Review Done

#3984 Added E2E test for negative search filters
  e2e/cypress/integration/search/negative_filter_spec.js
Labels: 2: Dev Review, 2: QA Review

#3990 E2E: Minor clean up on markdown and interactive menu
  e2e/cypress/fixtures/markdown/markdown_carriage_return_two_lines.html
  e2e/cypress/fixtures/markdown/markdown_code_block.html
  e2e/cypress/fixtures/markdown/markdown_not_autolink.html
  e2e/cypress/fixtures/markdown/markdown_not_in_code_block.html
  e2e/cypress/integration/interactive_menu/basic_options_spec.js
Labels: 3: Reviews Complete, QA Review Done

#3956 E2E to list many inactive users in system console
  components/admin_console/system_users/system_users.jsx
  components/user_list_row_with_error/user_list_row_with_error.jsx
  e2e/cypress/integration/system_console/inactive_users_spec.js
  e2e/cypress/support/api_commands.js
Labels: 3: Reviews Complete, QA Review Done

#3980 [MM-19498] Added accessibility for jump to messages on permalink view
  components/permalink_view/__snapshots__/permalink_view.test.jsx.snap
  components/permalink_view/permalink_view.jsx
  utils/a11y_controller.js
  utils/utils.jsx
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done, Tests/Done

#4000 Automated cherry pick of #3980
  components/permalink_view/__snapshots__/permalink_view.test.jsx.snap
  components/permalink_view/permalink_view.jsx
  utils/a11y_controller.js
  utils/utils.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3993 [MM-19113] Fix formatting in search hint component
  components/search_hint/__snapshots__/search_hint.test.tsx.snap
  components/search_hint/search_hint.tsx
  i18n/en.json
Labels: 3: Reviews Complete, QA Review Done

#3982 Fix issue when visiting newly created channel
  e2e/cypress/integration/channel/add_users_to_channel_spec.js
  e2e/cypress/integration/channel/message_reply_spec.js
  e2e/cypress/support/ui_commands.js
Labels: 3: Reviews Complete, QA Review Done

#3801 [MM-17537] Scroll to bottom of rhs when an upload error occurs
  components/create_comment/create_comment.jsx
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#4003 Automated cherry pick of #3801
  components/create_comment/create_comment.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3815 added the initial set of test for commands.js - tested /search and /s…
  actions/command.test.js
Labels: 3: Reviews Complete, Hacktoberfest, QA Review Done, Tests/Not Needed

#4005 Automated cherry pick of #3975
  components/integrations/__snapshots__/installed_command.test.jsx.snap
  components/integrations/__snapshots__/installed_incoming_webhook.test.jsx.snap
  components/integrations/__snapshots__/installed_outgoing_webhook.test.jsx.snap
  components/integrations/bots/bot.jsx
  components/integrations/installed_command.jsx
  components/integrations/installed_incoming_webhook.jsx
  components/integrations/installed_oauth_app/__snapshots__/installed_oauth_app.test.jsx.snap
  components/integrations/installed_oauth_app/installed_oauth_app.jsx
  components/integrations/installed_outgoing_webhook.jsx
  sass/responsive/_mobile.scss
  sass/routes/_backstage.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4006 Automated cherry pick of #3930
  components/__snapshots__/profile_picture.test.jsx.snap
  components/at_mention/__snapshots__/at_mention.test.jsx.snap
  components/at_mention/at_mention.jsx
  components/profile_picture.jsx
  components/user_profile/__snapshots__/user_profile.test.jsx.snap
  components/user_profile/user_profile.jsx
  sass/components/_popover.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4007 Automated cherry pick of #3943
  sass/responsive/_mobile.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3977 MM-19129 - Updating emoji style
  sass/components/_emoticons.scss
Labels: 3: Reviews Complete, CherryPick/Approved

#3973 MM-19358 - Updating webhooks css
  sass/components/_select.scss
  sass/layout/_webhooks.scss
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#4009 Automated cherry pick of #3977
  sass/components/_emoticons.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4010 Automated cherry pick of #3973
  sass/components/_select.scss
  sass/layout/_webhooks.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3987 [MM-18117] Add F6 navigation to search/mentions/flagged/pinned RHS views
  components/search_results/search_results.jsx
  components/search_results_item/__snapshots__/search_results_item.test.jsx.snap
  components/search_results_item/index.js
  components/search_results_item/search_results_item.jsx
  components/search_results_item/search_results_item.test.jsx
  i18n/en.json
Labels: 3: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server

#4011 Automated cherry pick of #3987
  components/search_results/search_results.jsx
  components/search_results_item/__snapshots__/search_results_item.test.jsx.snap
  components/search_results_item/index.js
  components/search_results_item/search_results_item.jsx
  components/search_results_item/search_results_item.test.jsx
  i18n/en.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3976 [MM-18883] Fixed hiding text when no results
  components/admin_console/group_settings/groups_list/__snapshots__/groups_list.test.jsx.snap
  components/admin_console/group_settings/groups_list/groups_list.jsx
  components/admin_console/system_user_detail/team_list/__snapshots__/abstract_list.test.jsx.snap
  components/admin_console/system_user_detail/team_list/abstract_list.jsx
Labels: 3: Reviews Complete, QA Review Done

#4001 [MM-19357] Filter out users not in team from list when adding users to a channel
  components/channel_invite_modal/channel_invite_modal.jsx
  components/channel_invite_modal/channel_invite_modal.test.jsx
  components/channel_invite_modal/index.js
Labels: CherryPick/Approved, QA Review Done

#3929 [MM-18579] add transition to about, team members, settings modal closing
  components/about_build_modal/__snapshots__/about_build_modal.test.jsx.snap
  components/about_build_modal/about_build_modal.jsx
  components/about_build_modal/about_build_modal.test.jsx
  components/team_members_modal/team_members_modal.jsx
  components/team_settings_modal/__snapshots__/team_settings_modal.test.jsx.snap
  components/team_settings_modal/team_settings_modal.jsx
  components/team_settings_modal/team_settings_modal.test.jsx
Labels: 3: Reviews Complete, QA Review Done

#4013 Automated cherry pick of #4001
  components/channel_invite_modal/channel_invite_modal.jsx
  components/channel_invite_modal/channel_invite_modal.test.jsx
  components/channel_invite_modal/index.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#3996 MM-19506 Fix attaching files on devices with touch events
  components/file_upload/__snapshots__/file_upload.test.jsx.snap
  components/file_upload/file_upload.jsx
  components/file_upload/file_upload.test.jsx
Labels: CherryPick/Approved, QA Review Done

#3983 MM-19183: handle plugins without homepage
  components/plugin_marketplace/marketplace_item/__snapshots__/marketplace_item.test.jsx.snap
  components/plugin_marketplace/marketplace_item/marketplace_item.jsx
  components/plugin_marketplace/marketplace_item/marketplace_item.test.jsx
Labels: CherryPick/Approved, QA Review Done

#3870 Replace functionality in deprecated lifecycle methods
  components/change_url_modal/change_url_modal.jsx
  components/change_url_modal/change_url_modal.test.jsx
  components/edit_channel_header_modal/edit_channel_header_modal.jsx
  components/edit_channel_header_modal/edit_channel_header_modal.test.jsx
  components/more_direct_channels/more_direct_channels.jsx
  components/new_channel_flow/new_channel_flow.jsx
  components/new_channel_flow/new_channel_flow.test.jsx
  components/new_channel_modal/new_channel_modal.jsx
  components/new_channel_modal/new_channel_modal.test.jsx
  components/searchable_channel_list.jsx
  components/searchable_channel_list.test.jsx
Labels: 3: Reviews Complete, Hacktoberfest, QA Review Done
