Repository mattermost/mattermost-webapp, pull requests merged in 2019-05, with the labels that each got.

#2673 [MM-14877] add description above post:all
  components/integrations/bots/add_bot/add_bot.jsx
  components/integrations/bots/add_bot/add_bot.test.jsx
  sass/routes/_backstage.scss
Labels: 3: Ready to Merge

#2676 MM-14119 - Upating header button styling
  utils/utils.jsx
Labels: 3: Ready to Merge

#2720 upgrading to the last mattermost-redux version
  package-lock.json
  package.json
Labels: 2: Dev Review

#2730 MM-15214: fix a regression re: env overrides
  components/admin_console/index.js
Labels: 3: Ready to Merge

#2731 MM-12902 - Updating announcement banner (making it fixed at the top)
  components/announcement_bar/__snapshots__/announcement_bar.test.jsx.snap
  components/announcement_bar/announcement_bar.jsx
  sass/components/_announcement-bar.scss
  sass/components/_tooltip.scss
Labels: 3: Ready to Merge

#2675 MM-15169 - Removing plugin bar border
  sass/layout/_team-sidebar.scss
  utils/utils.jsx
Labels: 3: Ready to Merge

#2705 Adding full screen modal (will be used for guest invites)
  components/svg/close_icon.jsx
  components/widgets/modals/full_screen_modal.jsx
  components/widgets/modals/full_screen_modal.scss
  components/widgets/modals/full_screen_modal.test.jsx
  i18n/en.json
Labels: 3: Ready to Merge

#2727 MM-15360: Updates help text description.
  components/admin_console/admin_definition.jsx
  i18n/en.json
Labels: 3: Ready to Merge, CherryPickDone

#2690 Enable syntax highlighting for VHDL and SystemVerilog files
  utils/constants.jsx
  utils/syntax_highlighting.jsx
Labels: 3: Ready to Merge, Docs: Needed

#2736 MM-15257 Changing channels which have more than 150 posts in store causes older posts not to load in view.
  package-lock.json
  package.json
Labels: 2: Dev Review

#2733 Remove outdated information from contributing file
  CONTRIBUTING.md
Labels: 2: Dev Review

#2695 Fixing a typo
  components/admin_console/admin_definition.jsx
  i18n/en.json
Labels: 3: Ready to Merge

#2714 [MM-15313] Revert section highlight styling; subsection indentation
  sass/routes/_admin-console.scss
Labels: 3: Ready to Merge

#2742 MM-15196 Fix missing 'Commented on' after separators
  components/post_view/post/index.js
  components/post_view/post/index.test.js
Labels: 2: Dev Review

#2533 [MM-12958] Support running two Mattermost instances on the same domain using subpaths
  actions/views/root.js
  cypress/integration/login/subpath_login_spec.js
  cypress/support/ui_commands.js
  selectors/general.js
  stores/local_storage_store.jsx
  stores/local_storage_store.test.jsx
Labels: 2: Dev Review

#2740 MM-15359 Fix double loading search indicators
  components/search_results/search_results.jsx
Labels: 3: Reviews Complete, CherryPick/Approved

#2743 MM-15386 Allow license expiring message to be dismissed and show it as an announcement type
  components/announcement_bar/announcement_bar_controller.jsx
  components/announcement_bar/configuration_bar/configuration_bar.jsx
  components/announcement_bar/configuration_bar/index.js
  components/announcement_bar/index.js
Labels: 3: Reviews Complete

#2521 [MM-14014] UI Automation: Write an automated test using Cypress for "Recently used emojis are shown 1st"
  components/emoji_picker/emoji_picker.jsx
  cypress/integration/emoji/recently_used_emoji_spec.js
Labels: 3: Reviews Complete

#2741 MM-15318 Fix batching of newly received posts
  actions/websocket_actions.jsx
  actions/websocket_actions.test.jsx
Labels: 3: Reviews Complete

#2744 MM-15322 Change PostList.checkBottom to use onScroll
  components/post_view/index.js
  components/post_view/post_list.jsx
  components/post_view/post_list.test.jsx
Labels: 2: Dev Review

#2717 Adding emails_input wdiget (will be used as part of the new invite process)
  components/svg/mail_icon.jsx
  components/svg/mail_plus_icon.jsx
  components/widgets/inputs/emails_input.jsx
  components/widgets/inputs/emails_input.scss
  components/widgets/inputs/emails_input.test.jsx
  i18n/en.json
  webpack.config.js
Labels: 3: Reviews Complete

#2745 MM-15056: Adding Guest badge to identify guest users
  components/add_users_to_team/add_users_to_team.jsx
  components/channel_header/channel_header.js
  components/channel_invite_modal/channel_invite_modal.jsx
  components/channel_members_dropdown/channel_members_dropdown.jsx
  components/more_direct_channels/more_direct_channels.jsx
  components/popover_list_members/popover_list_members_item.jsx
  components/post_view/post_header/index.js
  components/post_view/post_header/post_header.jsx
  components/profile_popover/profile_popover.jsx
  components/suggestion/at_mention_provider/at_mention_suggestion.jsx
  components/suggestion/generic_user_provider.jsx
  components/suggestion/switch_channel_provider.jsx
  components/user_list_row/user_list_row.jsx
  components/user_profile/user_profile.jsx
  components/widgets/badges/guest_badge.jsx
  components/widgets/badges/guest_badge.scss
  components/widgets/badges/guest_badge.test.jsx
  i18n/en.json
  sass/layout/_headers.scss
  sass/responsive/_mobile.scss
  utils/utils.jsx
Labels: 2: Dev Review

#2718 Adding channels input widget (will be used for guest invites)
  components/widgets/inputs/channels_input.jsx
  components/widgets/inputs/channels_input.scss
  components/widgets/inputs/channels_input.test.jsx
  i18n/en.json
Labels: 3: Reviews Complete

#2723 Adding users/emails input widget (will be used for guest invites)
  components/widgets/inputs/emails_input.jsx
  components/widgets/inputs/users_emails_input.jsx
  components/widgets/inputs/users_emails_input.scss
  components/widgets/inputs/users_emails_input.test.jsx
  i18n/en.json
Labels: 3: Reviews Complete

#2737 MM-15113 Adds e2e to check for emoji reaction added (#10612)
  components/emoji_picker/components/emoji_picker_item.jsx
  components/post_view/reaction/__snapshots__/reaction.test.jsx.snap
  components/post_view/reaction/reaction.jsx
  components/post_view/reaction_list/__snapshots__/reactions_list.test.jsx.snap
  components/post_view/reaction_list/reaction_list.jsx
  cypress/integration/channel/message_reaction_spec.js
Labels: 3: Reviews Complete

#2715 Fix mattermost/mattermost-server#10689
  components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.jsx.snap
  components/admin_console/admin_sidebar/admin_sidebar.jsx
  components/admin_console/admin_sidebar/admin_sidebar.test.jsx
Labels: 3: Reviews Complete

#2739 MM-15237: Fixing redirect on leave channel
  actions/global_actions.jsx
  actions/views/channel.js
  actions/views/channel.test.js
  components/channel_layout/center_channel/index.js
  stores/local_storage_store.jsx
Labels: 3: Reviews Complete

#2757 MM-14861 Fix safari perf issues
  components/post_view/post_list.jsx
  package-lock.json
  package.json
Labels: 3: Reviews Complete

#2748 translations PR 20190506
  i18n/de.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 2: Dev Review

#2747 MM-14975 remove virt_list for IE11
  actions/views/channel.js
  components/needs_team/needs_team.test.jsx
  components/permalink_view/__snapshots__/permalink_view.test.jsx.snap
  components/post_view/channel_intro_message/index.js
  components/post_view/index.js
  components/post_view/new_messages_below/index.js
  components/post_view/post_list_ie/index.js
  components/post_view/post_list_ie/post_list_ie.jsx
  components/post_view/post_list_row/__snapshots__/post_list_row.test.jsx.snap
  components/post_view/post_list_row/index.js
  components/post_view/post_list_row/post_list_row.jsx
  components/post_view/post_list_virtualized/index.js
  components/post_view/post_list_virtualized/post_list_virtualized.jsx
  components/post_view/post_list_virtualized/post_list_virtualized.test.jsx
  components/post_view/reaction_list/index.js
  components/post_view/reaction_list/reaction_list.jsx
  components/post_view/reaction_list/reactions_list.test.jsx
  components/root/root.test.jsx
  components/sidebar_right/index.js
  components/sidebar_right/sidebar_right.jsx
  components/textbox.test.jsx
  components/textbox/index.js
  components/textbox/textbox.jsx
  i18n/en.json
  sass/layout/_post.scss
  utils/constants.jsx
  utils/utils.jsx
Labels: 3: Reviews Complete

#2753 [MM-15017] Split out SMTP, Email & Push Notifications settings into discrete pages
  components/admin_console/__snapshots__/admin_console.test.jsx.snap
  components/admin_console/admin_definition.jsx
  components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.jsx.snap
  components/admin_console/email_settings.jsx
  components/admin_console/push_settings.jsx
  i18n/en.json
Labels: 1: PM Review, 2: Dev Review, Setup Test Server

#2760 [MM-15451] Fix failing E2E tests due to recent changes
  cypress/integration/account_settings/theme_color/custom_colors_sidebar_styles_spec.js
  cypress/integration/team/teams_spec.js
  cypress/support/ui_commands.js
Labels: 2: Dev Review

#2716 MM-15228 consecutive bot posts maintain the profile image
  components/post_view/post/post.jsx
Labels: 3: Reviews Complete

#2762 MM-15001 - Updating margin for wrapper sys console
  sass/routes/_admin-console.scss
Labels: 2: Dev Review, CherryPick/Approved

#2773 MM-15525 Use ES5 transpiled flexsearch to fix IE11
  utils/admin_console_index.jsx
Labels: 2: Dev Review

#2771 Update help text for at-here, at-channel, at-all
  components/suggestion/at_mention_provider/at_mention_suggestion.jsx
  i18n/en.json
Labels: 3: Reviews Complete

#2777 Upgrading mattermost utilities to add new line at the end of the generated files
  i18n/en.json
  package-lock.json
  package.json
Labels: 3: Reviews Complete

#2776 Fixing LocalizeInput extraction (temporary solution)
  components/admin_console/compliance_reports/compliance_reports.jsx
  components/admin_console/custom_url_schemes_setting.jsx
  components/admin_console/permission_schemes_settings/permission_team_scheme_settings/permission_team_scheme_settings.jsx
  components/admin_console/system_users/system_users.jsx
  components/claim/components/email_to_ldap.jsx
  components/claim/components/email_to_oauth.jsx
  components/claim/components/ldap_to_email.jsx
  components/claim/components/oauth_to_email.jsx
  components/emoji/emoji_list/emoji_list.jsx
  components/emoji_picker/emoji_picker.jsx
  components/gif_picker/components/SearchBar/index.jsx
  components/integrations/abstract_command.jsx
  components/login/login_controller/login_controller.jsx
  components/login/login_mfa.jsx
  components/mfa/setup/setup.jsx
  components/new_channel_modal/new_channel_modal.jsx
  components/password_reset_form/password_reset_form.jsx
  components/password_reset_send_link.jsx
  components/team_general_tab/team_general_tab.jsx
  i18n/en.json
Labels: 3: Reviews Complete

#2779 Revert "Revert "MM-14975 remove virt_list for IE11 (#2747)""
  actions/views/channel.js
  components/needs_team/needs_team.test.jsx
  components/permalink_view/__snapshots__/permalink_view.test.jsx.snap
  components/post_view/channel_intro_message/index.js
  components/post_view/index.js
  components/post_view/new_messages_below/index.js
  components/post_view/post_list_ie/index.js
  components/post_view/post_list_ie/post_list_ie.jsx
  components/post_view/post_list_row/__snapshots__/post_list_row.test.jsx.snap
  components/post_view/post_list_row/index.js
  components/post_view/post_list_row/post_list_row.jsx
  components/post_view/post_list_virtualized/index.js
  components/post_view/post_list_virtualized/post_list_virtualized.jsx
  components/post_view/post_list_virtualized/post_list_virtualized.test.jsx
  components/post_view/reaction_list/index.js
  components/post_view/reaction_list/reaction_list.jsx
  components/post_view/reaction_list/reactions_list.test.jsx
  components/root/root.test.jsx
  components/sidebar_right/index.js
  components/sidebar_right/sidebar_right.jsx
  components/textbox.test.jsx
  components/textbox/index.js
  components/textbox/textbox.jsx
  i18n/en.json
  sass/layout/_post.scss
  utils/constants.jsx
  utils/utils.jsx
Labels: 3: Reviews Complete

#2763 [MM-14767] Sorting BOTs at the bottom of channel member list below offline users is not working
  utils/utils.jsx
  utils/utils.test.jsx
Labels: 2: Dev Review

#2781 Fix bot badges on manage team members
  components/user_list_row/user_list_row.jsx
Labels: 3: Reviews Complete

#2638 MM-14977 Remove metadata backwards compatibility
  actions/views/create_comment.jsx
  components/admin_console/admin_definition.jsx
  components/create_post/create_post.jsx
  components/file_attachment_list/file_attachment_list.jsx
  components/file_attachment_list/file_attachment_list.test.jsx
  components/file_attachment_list/index.js
  components/post_emoji/index.jsx
  components/post_view/commented_on_files_message/__snapshots__/commented_on_files_message.test.jsx.snap
  components/post_view/commented_on_files_message/commented_on_files_message.jsx
  components/post_view/commented_on_files_message/commented_on_files_message.test.jsx
  components/post_view/commented_on_files_message/index.js
  components/post_view/post_attachment_opengraph/index.js
  components/post_view/post_attachment_opengraph/post_attachment_opengraph.jsx
  components/post_view/post_attachment_opengraph/post_attachment_opengraph.test.js
  components/post_view/post_body_additional_content/post_body_additional_content.jsx
  components/post_view/post_body_additional_content/post_body_additional_content.test.jsx
  components/post_view/reaction_list/__snapshots__/reactions_list.test.jsx.snap
  components/post_view/reaction_list/index.js
  components/post_view/reaction_list/reaction_list.jsx
  components/post_view/reaction_list/reactions_list.test.jsx
  components/size_aware_image.jsx
  i18n/en.json
  package-lock.json
  package.json
Labels: 3: Reviews Complete

#2767 MM-15168 Do not show current user's profile image or name in GM intro message
  components/post_view/channel_intro_message/channel_intro_message.jsx
  components/post_view/channel_intro_message/index.js
Labels: 3: Reviews Complete

#2765 MM-15456 Fix flaky Cypress specs on /integrations/channel
  cypress/integration/account_settings/display/code_theme_colors_spec.js
  cypress/integration/account_settings/display/message_display_mode_spec.js
  cypress/integration/at_mentions/at_mentions_spec.js
  cypress/integration/channel/autocomplete_shown_each_channel_spec.js
  cypress/integration/channel/collapsed_message_spec.js
  cypress/integration/channel/edit_message_spec.js
  cypress/integration/channel/header_spec.js
  cypress/integration/channel/message_bullets_spec.js
  cypress/integration/channel/message_deletion_spec.js
  cypress/integration/channel/message_draft_spec.js
  cypress/integration/channel/message_draft_then_switch_channel_spec.js
  cypress/integration/channel/message_edit_post_with_attachment_spec.js
  cypress/integration/channel/message_reaction_spec.js
  cypress/integration/channel/message_spec.js
  cypress/integration/channel/mobile_message_deletion_spec.js
  cypress/integration/channel/system_message_spec.js
  cypress/integration/post_header/post_header_spec.js
  cypress/integration/search/results_post_comment_spec.js
  cypress/support/index.js
  cypress/support/ui_commands.js
  cypress/support/validators.js
  package-lock.json
  package.json
Labels: 3: Reviews Complete

#2764 MM-15343 Rely entirely on post metadata for embedded content
  components/post_view/post_attachment_opengraph/__snapshots__/post_attachment_opengraph.test.js.snap
  components/post_view/post_attachment_opengraph/index.js
  components/post_view/post_attachment_opengraph/post_attachment_opengraph.jsx
  components/post_view/post_attachment_opengraph/post_attachment_opengraph.test.js
  components/post_view/post_body/index.js
  components/post_view/post_body/post_body.jsx
  components/post_view/post_body_additional_content/__snapshots__/post_body_additional_content.test.jsx.snap
  components/post_view/post_body_additional_content/index.js
  components/post_view/post_body_additional_content/post_body_additional_content.jsx
  components/post_view/post_body_additional_content/post_body_additional_content.test.jsx
  components/post_view/post_image/post_image.jsx
  components/post_view/post_image/post_image.test.jsx
  components/view_image/index.js
  components/youtube_video/youtube_video.jsx
  components/youtube_video/youtube_video.test.jsx
  utils/utils.jsx
Labels: 3: Reviews Complete

#2772 MM-15505 Fix i18n fallback text for email to ldap password field
  components/claim/components/email_to_ldap.jsx
Labels: 3: Reviews Complete, CherryPick/Approved

#2778 Promote Polish to 'official'
  components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
  i18n/i18n.jsx
Labels: 3: Reviews Complete

#2782 Add permissions checks needed for guest accounts
  components/sidebar/__snapshots__/sidebar.test.jsx.snap
  components/sidebar/channel_more.jsx
  components/sidebar/sidebar.jsx
  components/widgets/badges/guest_badge.jsx
  components/widgets/badges/guest_badge.scss
  components/widgets/badges/guest_badge.test.jsx
Labels: 3: Reviews Complete

#2784 MM-15457 E2E - Fix integrations Cypress spec
  components/backstage/components/backstage_list.jsx
  components/backstage/components/backstage_section.jsx
  components/backstage/components/backstage_sidebar.jsx
  components/channel_select/channel_select.jsx
  components/integrations/__snapshots__/abstract_command.test.jsx.snap
  components/integrations/__snapshots__/abstract_incoming_hook.test.jsx.snap
  components/integrations/__snapshots__/abstract_oauth_app.test.jsx.snap
  components/integrations/__snapshots__/abstract_outgoing_webhook.test.jsx.snap
  components/integrations/abstract_command.jsx
  components/integrations/abstract_incoming_webhook.jsx
  components/integrations/abstract_oauth_app.jsx
  components/integrations/abstract_outgoing_webhook.jsx
  components/integrations/bots/add_bot/add_bot.jsx
  components/integrations/bots/bots.jsx
  components/integrations/confirm_integration/__snapshots__/confirm_integration.test.jsx.snap
  components/integrations/confirm_integration/confirm_integration.jsx
  components/integrations/installed_commands/installed_commands.jsx
  components/integrations/installed_incoming_webhooks/installed_incoming_webhooks.jsx
  components/integrations/installed_oauth_apps/__snapshots__/installed_oauth_apps.test.jsx.snap
  components/integrations/installed_oauth_apps/installed_oauth_apps.jsx
  components/integrations/installed_outgoing_webhooks/__snapshots__/installed_outgoing_webhooks.test.jsx.snap
  components/integrations/installed_outgoing_webhooks/installed_outgoing_webhooks.jsx
  cypress/integration/integrations/integrations_spec.js
  cypress/integration/integrations/intergrations_spec.js
  cypress/support/ui_commands.js
Labels: 2: Dev Review

#2785 MM-15399: Properly setting filenames on upload saml certificates
  actions/admin_actions.jsx
  components/admin_console/schema_admin_settings.jsx
Labels: 2: Dev Review

#2756 Fix capitalization error for "Create teams" in permissions schemes
  i18n/en.json
Labels: 2: Dev Review

#2788 MM-15534 - Updating sidebar css on mobile
  sass/responsive/_mobile.scss
Labels: 3: Reviews Complete, CherryPick/Approved

#2791 MM-15562 Add a way to unregister post type components
  plugins/registry.js
Labels: 3: Reviews Complete

#2775 [MM-13274] Show a tooltip with the full channel name when hovering over group message channels in the sidebar
  components/sidebar/sidebar_channel_button_or_link/__snapshots__/sidebar_channel_button_or_link.test.jsx.snap
  components/sidebar/sidebar_channel_button_or_link/sidebar_channel_button_or_link.jsx
  components/sidebar/sidebar_channel_button_or_link/sidebar_channel_button_or_link.test.jsx
Labels: 3: Reviews Complete

#2787 MM-15432 Change isFirstReply to return false for non-comments
  components/post_view/post/index.js
  components/post_view/post/index.test.js
Labels: 3: Reviews Complete

#2795 MM-15583 Fix static embeds being hidden when image previews are collapsed
  components/post_view/post_body_additional_content/__snapshots__/post_body_additional_content.test.jsx.snap
  components/post_view/post_body_additional_content/post_body_additional_content.jsx
  components/post_view/post_body_additional_content/post_body_additional_content.test.jsx
Labels: 3: Reviews Complete

#2735 [MM-15172] Point to react-bootstrap Mattermost repository
  package-lock.json
  package.json
Labels: 3: Reviews Complete

#2758 MM-14898: Updates team settings modal if team is group constrained.
  components/team_general_tab/__snapshots__/team_general_tab.test.jsx.snap
  components/team_general_tab/team_general_tab.jsx
  components/team_general_tab/team_general_tab.test.jsx
  i18n/en.json
  sass/routes/_settings.scss
Labels: 3: Reviews Complete

#2786 MM-15320 Use new header to calculate file loading progress for gzipped responses
  utils/utils.jsx
Labels: 3: Reviews Complete

#2789 [MM-14973] Remove password length limit from reset password form (closes #10523)
  components/admin_console/reset_password_modal/reset_password_modal.jsx
Labels: 3: Reviews Complete

#2732 MM-15345 slicing posts in post_list
  components/post_view/post_list_virtualized/post_list_virtualized.jsx
  components/post_view/post_list_virtualized/post_list_virtualized.test.jsx
  package-lock.json
  package.json
Labels: 3: Reviews Complete

#2798 MM-15487: Adding suggestion.archive to the translatable strings
  i18n/en.json
  utils/constants.jsx
Labels: 2: Dev Review

#2796 MM-15343 Look in post metadata for OpenGraph image dimensions
  components/post_view/post_attachment_opengraph/__snapshots__/post_attachment_opengraph.test.js.snap
  components/post_view/post_attachment_opengraph/get_nearest_point.js
  components/post_view/post_attachment_opengraph/get_nearest_point.test.js
  components/post_view/post_attachment_opengraph/index.js
  components/post_view/post_attachment_opengraph/post_attachment_opengraph.jsx
  components/post_view/post_attachment_opengraph/post_attachment_opengraph.test.js
  components/post_view/post_attachment_opengraph/post_attachment_opengraph.test.jsx
Labels: 3: Reviews Complete

#2692 [MM-14751] Take group_constrained into account when adding users to teams and channels
  actions/global_actions.test.js
  components/add_users_to_team/add_users_to_team.jsx
  components/add_users_to_team/add_users_to_team.test.jsx
  components/add_users_to_team/index.js
  components/channel_invite_modal/channel_invite_modal.jsx
  package-lock.json
  package.json
Labels: 2: Dev Review

#2751 MM-14723 - Add System Console setting to enable/disable bot accounts
  components/admin_console/admin_definition.jsx
  components/integrations/bots/bots.jsx
  components/integrations/bots/index.js
  i18n/en.json
Labels: 3: Reviews Complete

#2803 MM-15499 Load YouTube thumbnail through image proxy
  components/youtube_video/index.js
  components/youtube_video/youtube_video.jsx
  components/youtube_video/youtube_video.test.jsx
Labels: 3: Reviews Complete

#2759 MM-15324 Allow plugins override ephemeral posts
  components/post_view/post_body/post_body.jsx
  components/post_view/post_message_view/post_message_view.jsx
Labels: 3: Reviews Complete

#2807 MM-15273 - Updating textbox preview styling
  components/textbox/textbox.jsx
  sass/layout/_post.scss
Labels: 2: Dev Review

#2689 [MM-15016] Combine Compliance page with Compliance Reporting in System Console
  components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
  components/admin_console/admin_console.jsx
  components/admin_console/admin_definition.jsx
  components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.jsx.snap
  components/admin_console/audits/audits.jsx
  components/admin_console/audits/index.js
  components/admin_console/compliance_reports/compliance_reports.jsx
  components/admin_console/custom_plugin_settings/__snapshots__/custom_plugin_settings.test.jsx.snap
  components/admin_console/permission_schemes_settings/__snapshots__/permission_schemes_settings.test.jsx.snap
  components/admin_console/permission_schemes_settings/permission_schemes_settings.jsx
  components/admin_console/permission_schemes_settings/permission_schemes_settings.test.jsx
  components/admin_console/permission_schemes_settings/permission_system_scheme_settings/__snapshots__/permission_system_scheme_settings.test.jsx.snap
  components/admin_console/permission_schemes_settings/permission_system_scheme_settings/permission_system_scheme_settings.jsx
  components/admin_console/permission_schemes_settings/permissions_scheme_summary/__snapshots__/permissions_scheme_summary.test.jsx.snap
  components/admin_console/permission_schemes_settings/permissions_scheme_summary/permissions_scheme_summary.jsx
  components/admin_console/push_settings.jsx
  components/admin_console/schema_admin_settings.jsx
  i18n/en.json
  sass/routes/_admin-console.scss
Labels: 2: Dev Review, Setup Test Server

#2710 [MM-15052] add E2E test for close buttons on channels
  components/sidebar/__snapshots__/sidebar.test.jsx.snap
  components/sidebar/channel_more.jsx
  components/sidebar/sidebar.jsx
  cypress/integration/channel/channel_settings_spec.js
Labels: 3: Reviews Complete

#2800 MM-15227 Permalink is not loading more posts into the view when reacheded to the top
  components/post_view/post_list_virtualized/index.js
Labels: 3: Reviews Complete

#2801 Fix select default channel
  actions/views/channel.js
  actions/views/channel.test.js
  package-lock.json
  package.json
Labels: 3: Reviews Complete

#2804 MM-15485: Updates out-of-group at-mention message.
  components/post_view/post_add_channel_member/__snapshots__/post_add_channel_member.test.jsx.snap
  components/post_view/post_add_channel_member/post_add_channel_member.jsx
  i18n/en.json
Labels: 2: Dev Review

#2808 MM-15577: Updates channel intro message links for group-constrained c…
  components/post_view/channel_intro_message/channel_intro_message.jsx
  components/post_view/channel_intro_message/index.js
  i18n/en.json
Labels: 3: Reviews Complete

#2809 MM-15578: Hides 'Leave Team' menu in a group-constrained team.
  components/main_menu/main_menu.jsx
  plugins/test/__snapshots__/main_menu_action.test.jsx.snap
Labels: 2: Dev Review

#2722 MM-15010 Adding Cypress test for - Pinning or un-pinning older post d…
  components/search_results_header/search_results_header.jsx
  cypress/integration/onboarding/messaging/message_pinning_unpinning_spec.js
  cypress/support/api_commands.js
  cypress/support/ui_commands.js
Labels: 3: Reviews Complete

#2818 MM-15680 - Updating channel header icon styling
  sass/layout/_headers.scss
Labels: 3: Reviews Complete

#2821 MM-15693 - Updating css for dropdown menu
  sass/widgets/menu/_menu_item.scss
  utils/utils.jsx
Labels: 3: Reviews Complete

#2825 MM-15681 Fix for scroll position when initRangeRender is smaller than number of posts
  package-lock.json
  package.json
Labels: 3: Reviews Complete, CherryPick/Approved

#2811 MM-13483 Cleared search term should not reappear as RHS is reopened
  cypress/integration/channel/header_spec.js
Labels: 3: Reviews Complete

#2805 MM-15517 - Updating post spacing in the RHS
  sass/layout/_post-right.scss
Labels: 2: Dev Review, CherryPick/Approved

#2823 MM-15544: Fixing selector selection with arrows on more direct channels
  components/multiselect/multiselect_list.jsx
Labels: 3: Reviews Complete

#2709 Example of css variables + css-vars-ponyfill
  package-lock.json
  package.json
  sass/base/_css_variables.scss
  sass/base/_module.scss
  sass/routes/_loading.scss
  utils/utils.jsx
Labels: 3: Reviews Complete

#2802 MM-15634 Add custom command to create and login with new user
  cypress/integration/system_console/demoted_user_spec.js
  cypress/integration/team/create_a_team_spec.js
  cypress/integration/team/teams_spec.js
  cypress/support/api_commands.js
  cypress/support/ui_commands.js
Labels: 3: Reviews Complete

#2828 MM-14134 Do not auto close notifications on Mac desktop app
  utils/notifications.jsx
Labels: 3: Reviews Complete

#2816 MM-15657 additional message on bot creation to add to channel/team
  components/integrations/confirm_integration/confirm_integration.jsx
  i18n/en.json
Labels: 3: Reviews Complete, CherryPick/Approved

#2792 MM-15560 - E2E Fix: update markdown html fixtures
  cypress/fixtures/markdown/markdown_inline_images_1.html
  cypress/fixtures/markdown/markdown_inline_images_2.html
  cypress/fixtures/markdown/markdown_inline_images_3.html
  cypress/fixtures/markdown/markdown_inline_images_4.html
  cypress/fixtures/markdown/markdown_inline_images_5.html
  cypress/fixtures/timeouts.js
  cypress/integration/account_settings/sidebar/channel_switcher_spec.js
  cypress/integration/channel/header_spec.js
  cypress/integration/channel/message_draft_then_switch_channel_spec.js
  cypress/integration/channel/mobile_message_deletion_spec.js
  cypress/integration/emoji/recently_used_emoji_spec.js
  cypress/integration/markdown/markdown_spec.js
  cypress/support/ui_commands.js
Labels: 3: Reviews Complete

#2817 MM-15531 Add client-side slashCommandWillBePosted hook
  actions/hooks.js
  actions/hooks.test.js
  actions/views/create_comment.jsx
  actions/views/create_comment.test.jsx
  components/create_post/create_post.jsx
  components/create_post/create_post.test.jsx
  components/create_post/index.js
  plugins/registry.js
Labels: 3: Reviews Complete, CherryPick/Approved

#2819 MM-15662: Change config setting to EnableBotAccountCreation
  components/admin_console/admin_definition.jsx
  components/integrations/bots/index.js
  i18n/en.json
Labels: 2: Dev Review, CherryPick/Approved

#2810 [MM-14252] After clearing search query, search options display #10308
  components/search_results/search_results.jsx
  cypress/integration/search/post_search_display.js
Labels: 2: Dev Review

#2761 MM-15001 - Updating system console structure
  components/admin_console/__snapshots__/message_export_settings.test.jsx.snap
  components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
  components/admin_console/admin_settings.jsx
  components/admin_console/audits/audits.jsx
  components/admin_console/custom_plugin_settings/__snapshots__/custom_plugin_settings.test.jsx.snap
  components/admin_console/custom_terms_of_service_settings/__snapshots__/custom_terms_of_service_settings.test.jsx.snap
  components/admin_console/group_settings/__snapshots__/group_settings.test.jsx.snap
  components/admin_console/group_settings/group_details/__snapshots__/group_details.test.jsx.snap
  components/admin_console/group_settings/group_details/group_details.jsx
  components/admin_console/group_settings/group_settings.jsx
  components/admin_console/license_settings.jsx
  components/admin_console/permission_schemes_settings/__snapshots__/permission_schemes_settings.test.jsx.snap
  components/admin_console/permission_schemes_settings/permission_schemes_settings.jsx
  components/admin_console/permission_schemes_settings/permission_system_scheme_settings/__snapshots__/permission_system_scheme_settings.test.jsx.snap
  components/admin_console/permission_schemes_settings/permission_system_scheme_settings/permission_system_scheme_settings.jsx
  components/admin_console/permission_schemes_settings/permission_team_scheme_settings/__snapshots__/permission_team_scheme_settings.test.jsx.snap
  components/admin_console/permission_schemes_settings/permission_team_scheme_settings/permission_team_scheme_settings.jsx
  components/admin_console/plugin_management/__snapshots__/plugin_management.test.jsx.snap
  components/admin_console/plugin_management/plugin_management.jsx
  components/admin_console/schema_admin_settings.jsx
  components/admin_console/server_logs/logs.jsx
  components/admin_console/settings_group.jsx
  components/admin_console/system_users/__snapshots__/system_users.test.jsx.snap
  components/admin_console/system_users/system_users.jsx
  components/analytics/system_analytics/system_analytics.jsx
  components/analytics/team_analytics/team_analytics.jsx
  components/widgets/admin_console/admin_header.jsx
  components/widgets/admin_console/admin_header.test.jsx
  sass/routes/_admin-console.scss
  sass/routes/_statistics.scss
  sass/widgets/admin-console/_admin-panel.scss
Labels: 3: Reviews Complete, CherryPick/Approved

#2826 MM-15709 certain aspect ratio of images cause pop on firefox
  components/__snapshots__/size_aware_image.test.jsx.snap
  components/size_aware_image.jsx
Labels: 3: Reviews Complete, CherryPick/Approved

#2835 translations PR 20190522
  i18n/de.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 2: Dev Review

#2824 MM-15700 Manual load more trigger in virt list does not load more messages
  utils/post_utils.jsx
  utils/post_utils.test.jsx
Labels: 2: Dev Review, CherryPick/Approved

#2834 [MM 15656] Pass only postIds for previousListId
  components/post_view/post_list_virtualized/post_list_virtualized.jsx
  utils/post_utils.jsx
  utils/post_utils.test.jsx
Labels: 3: Reviews Complete, CherryPick/Approved

#2813 MM-15343 Stop confusing proxied and unproxied image URLs
  components/post_view/post_attachment_opengraph/__snapshots__/post_attachment_opengraph.test.js.snap
  components/post_view/post_attachment_opengraph/post_attachment_opengraph.jsx
  components/post_view/post_attachment_opengraph/post_attachment_opengraph.test.js
Labels: 3: Reviews Complete, CherryPick/Approved

#2769 MM-15377 Match spacing and new lines of posts to markdown preview
  sass/layout/_post.scss
Labels: 2: Dev Review, CherryPick/Approved

#2839 MM-15746: Updates button text.
  components/channel_groups_manage_modal/channel_groups_manage_modal.jsx
  components/team_groups_manage_modal/team_groups_manage_modal.jsx
  i18n/en.json
Labels: 3: Reviews Complete, CherryPick/Approved

#2837 MM-15660: Resets the current page upon some user inputs.
  components/admin_console/group_settings/groups_list/groups_list.jsx
Labels: 3: Reviews Complete, CherryPick/Approved

#2829 Quick fix: update writing test step guide for E2E
  cypress/integration/account_settings/display/channel_display_mode_spec.js
  cypress/integration/account_settings/display/code_theme_colors_spec.js
  cypress/integration/account_settings/display/message_display_mode_spec.js
  cypress/integration/account_settings/general/nickname.js
  cypress/integration/account_settings/sidebar/channel_switcher_spec.js
  cypress/integration/account_settings/theme_color/custom_colors_sidebar_styles_spec.js
  cypress/integration/at_mentions/at_mentions_spec.js
  cypress/integration/channel/autocomplete_shown_each_channel_spec.js
  cypress/integration/channel/channel_settings_spec.js
  cypress/integration/channel/collapsed_message_spec.js
  cypress/integration/channel/edit_message_spec.js
  cypress/integration/channel/header_spec.js
  cypress/integration/channel/message_bullets_spec.js
  cypress/integration/channel/message_deletion_spec.js
  cypress/integration/channel/message_draft_spec.js
  cypress/integration/channel/message_draft_then_switch_channel_spec.js
  cypress/integration/channel/message_edit_post_with_attachment_spec.js
  cypress/integration/channel/message_reaction_spec.js
  cypress/integration/channel/mobile_message_deletion_spec.js
  cypress/integration/channel/system_message_spec.js
  cypress/integration/emoji/recently_used_emoji_spec.js
  cypress/integration/integrations/integrations_spec.js
  cypress/integration/login/login_spec.js
  cypress/integration/login/signup_spec.js
  cypress/integration/login/subpath_login_spec.js
  cypress/integration/markdown/markdown_spec.js
  cypress/integration/onboarding/email/existing_email_adress_spec.js
  cypress/integration/onboarding/messaging/message_pinning_unpinning_spec.js
  cypress/integration/onboarding/multi_team/existing_channel_name_spec.js
  cypress/integration/post_header/post_header_spec.js
  cypress/integration/search/results_post_comment_spec.js
  cypress/integration/system_console/demoted_user_spec.js
  cypress/integration/team/create_a_team_spec.js
  cypress/integration/team/teams_spec.js
  cypress/support/ui_commands.js
Labels: 3: Reviews Complete

#2849 MM-15725: Fixing NONE security in SMTP admin console config
  components/admin_console/admin_definition.jsx
Labels: 3: Reviews Complete, CherryPick/Approved

#2840 E2E: Add commands to update system config and clear whitelisted cookies
  cypress/fixtures/config.json
  cypress/integration/integrations/integrations_spec.js
  cypress/integration/login/subpath_login_spec.js
  cypress/integration/markdown/markdown_spec.js
  cypress/integration/onboarding/email/existing_email_adress_spec.js
  cypress/support/api_commands.js
  package-lock.json
  package.json
Labels: 3: Reviews Complete

#2815 MM-15586 Bot tag missing for bots in channel switcher
  components/suggestion/switch_channel_provider.jsx
Labels: 3: Reviews Complete, CherryPick/Approved

#2812 MM-15422: Fixes for channel, team, and group selector modals.
  components/add_groups_to_channel_modal/add_groups_to_channel_modal.jsx
  components/add_groups_to_team_modal/add_groups_to_team_modal.jsx
  components/admin_console/group_settings/group_details/__snapshots__/group_details.test.jsx.snap
  components/admin_console/group_settings/group_details/group_details.jsx
  components/channel_selector_modal/__snapshots__/channel_selector_modal.test.jsx.snap
  components/channel_selector_modal/channel_selector_modal.jsx
  components/channel_selector_modal/channel_selector_modal.test.jsx
  components/channel_selector_modal/index.js
  components/team_selector_modal/team_selector_modal.jsx
Labels: 3: Reviews Complete, CherryPick/Approved, Do Not Merge/Awaiting PR

#2831 MM-15696 - Updating plugin buttons
  sass/layout/_webhooks.scss
  sass/responsive/_mobile.scss
Labels: 2: Dev Review, CherryPick/Approved

#2766 [MM-14250] Fix rage emoticon from being grabbed by mention regex
  utils/text_formatting.jsx
  utils/text_formatting_at_mentions.test.jsx
Labels: 3: Reviews Complete, Awaiting Submitter Action, CherryPick/Approved

#2850 MM-15757 Fix scroll pop caused by long posts in compact view
  components/post_view/message_attachments/message_attachment/__snapshots__/message_attachment.test.jsx.snap
  components/post_view/message_attachments/message_attachment/message_attachment.jsx
  components/post_view/post_message_view/__snapshots__/post_message_view.test.jsx.snap
  components/post_view/post_message_view/post_message_view.jsx
  components/post_view/show_more/__snapshots__/show_more.test.jsx.snap
  components/post_view/show_more/index.js
  components/post_view/show_more/show_more.jsx
  components/post_view/show_more/show_more.test.jsx
  plugins/test/__snapshots__/post_type.test.jsx.snap
  sass/layout/_post.scss
  sass/responsive/_tablet.scss
Labels: 3: Reviews Complete, CherryPick/Approved

#2847 MM-15675: Fixing help button on edit channel modal
  components/post_view/channel_intro_message/channel_intro_message.jsx
Labels: 3: Reviews Complete

#2844 MM-15747 Add missing Terms of Service link from System console
  components/admin_console/admin_definition.jsx
  i18n/en.json
Labels: 3: Reviews Complete, CherryPick/Approved

#2855 MM-15733 Scroll position is not at `new message` indicator on a recurring visit to a channel
  package-lock.json
  package.json
Labels: 3: Reviews Complete, CherryPick/Approved

#2856 MM-15667 if post was removed exclude it from postsInChannel
  package-lock.json
  package.json
Labels: 3: Reviews Complete, CherryPick/Approved

#2854 Render RHS dots menu only on hover or when is open
  components/rhs_comment/rhs_comment.jsx
Labels: 2: Dev Review

#2833 [MM-14344] E2E for email notification
  cypress.json
  cypress/fixtures/users.json
  cypress/integration/email/mention_email_notification_spec.js
  cypress/plugins/get_recent_email.js
  cypress/plugins/index.js
Labels: 2: Dev Review

#2842 [MM-11287] Add support for plus sign and period/dot in custom URL schemes (#9155)
  package-lock.json
  package.json
  utils/text_formatting_links.test.jsx
Labels: 3: Reviews Complete

#2851 MM-15753 IE:11 Fix for system message not loading at the top
  components/post_view/post_list_ie/post_list_ie.jsx
Labels: 3: Reviews Complete, CherryPick/Approved

#2852 MM-15754 IE:11 Fix for grouping of messages
  components/post_view/post_list_ie/post_list_ie.jsx
Labels: 3: Reviews Complete, CherryPick/Approved

#2861 MM-15756 Scroll correction fix for addition of channel header when at bottom
  components/post_view/post_list_virtualized/post_list_virtualized.jsx
  components/post_view/post_list_virtualized/post_list_virtualized.test.jsx
Labels: 3: Reviews Complete, CherryPick/Approved

#2862 MM-14676: Fix member roles changes on team manage members modal
  components/team_members_dropdown/index.js
  components/team_members_dropdown/team_members_dropdown.jsx
  components/team_members_dropdown/team_members_dropdown.test.jsx
Labels: 3: Reviews Complete

#2848 MM-15726: Adding again Smtp test button to the admin console
  actions/admin_actions.jsx
  components/admin_console/admin_definition.jsx
  components/admin_console/email_connection_test/__snapshots__/email_connection_test.test.jsx.snap
  components/admin_console/email_connection_test/email_connection_test.jsx
  components/admin_console/email_connection_test/email_connection_test.test.jsx
  components/admin_console/email_connection_test/index.js
  i18n/en.json
Labels: 2: Dev Review, CherryPick/Approved

#2841 MM-14843 Fix IME composition for non-Chrome browsers in multiselect components
  package-lock.json
  package.json
Labels: 3: Reviews Complete, CherryPick/Approved

#2832 MM-15724 - Updating system console spacing and UI
  components/admin_console/admin_definition.jsx
  components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.jsx.snap
  components/admin_console/admin_sidebar_header/admin_sidebar_header.jsx
  sass/routes/_admin-console.scss
Labels: 3: Reviews Complete, CherryPick/Approved

#2869 MM-12320 - Change "about" section references to use the site name when it is configured
  components/about_build_modal/__snapshots__/about_build_modal.test.jsx.snap
  components/about_build_modal/about_build_modal.jsx
  components/admin_console/admin_navbar_dropdown/admin_navbar_dropdown.jsx
  components/admin_console/admin_navbar_dropdown/index.js
  components/main_menu/index.jsx
  components/main_menu/main_menu.jsx
  components/main_menu/main_menu.test.jsx
  i18n/en.json
  plugins/test/main_menu_action.test.jsx
Labels: 3: Reviews Complete

#2780 MM-10072 - Updating list modals for accessibility
  components/access_history_modal/__snapshots__/access_history_modal.test.jsx.snap
  components/access_history_modal/access_history_modal.jsx
  components/activity_log_modal/__snapshots__/activity_log_modal.test.jsx.snap
  components/activity_log_modal/activity_log_modal.jsx
  components/more_direct_channels/__snapshots__/more_direct_channels.test.jsx.snap
  components/more_direct_channels/more_direct_channels.jsx
  i18n/en.json
  sass/components/_modal.scss
Labels: 3: Reviews Complete, CherryPick/Approved

#2830 Bot name is truncated and bot indicator is shown in RHS
  components/user_profile/__snapshots__/user_profile.test.jsx.snap
  components/user_profile/user_profile.jsx
  components/widgets/badges/badge.scss
  sass/layout/_post.scss
Labels: 3: Reviews Complete, CherryPick/Approved

#2863 MM-15763: Displays custom error message when rejected to join team vi…
  components/select_team/__snapshots__/select_team.test.jsx.snap
  components/select_team/index.js
  components/select_team/select_team.jsx
  i18n/en.json
Labels: 2: Dev Review

#2872 MM-15310: Be less restrictive about channels name in the frontend part
  components/change_url_modal/__snapshots__/change_url_modal.test.jsx.snap
  components/new_channel_modal/__snapshots__/new_channel_modal.test.jsx.snap
  components/rename_channel_modal/__snapshots__/rename_channel_modal.test.jsx.snap
  components/rename_channel_modal/rename_channel_modal.test.jsx
  utils/constants.jsx
  utils/url.jsx
Labels: 3: Reviews Complete, CherryPick/Approved

#2874 MM-15806 Removing bot account email from manage team member's dialog
  components/user_list_row/user_list_row.jsx
Labels: 2: Dev Review, CherryPick/Approved

#2846 S14672 Search "in:[username]" returns results in DMs
  components/sidebar/channel_create.jsx
  cypress/integration/search/search_user_post.js
Labels: 2: Dev Review

#2845 M14126 Message Draft Pencil Icon - No text, only file attachment
  cypress/integration/channel/message_draft_with_attachment_then_switch_channel_spec.js
Labels: 2: Dev Review

#2783 [MM-15459] Add mechanism to prevent suggestion close when clicking suggestion list
  components/suggestion/suggestion_box.jsx
  components/suggestion/suggestion_list.jsx
Labels: 3: Reviews Complete, CherryPick/Approved

#2875 Fix flaky tests on some specs
  cypress/integration/channel/message_draft_spec.js
  cypress/integration/channel/message_draft_then_switch_channel_spec.js
  cypress/integration/channel/message_edit_post_with_attachment_spec.js
  cypress/integration/integrations/integrations_spec.js
  cypress/support/ui_commands.js
Labels: 2: Dev Review

#2726 MM-15128 - add support for interactive dialogs with no elements
  components/interactive_dialog/interactive_dialog.jsx
Labels: 2: Dev Review

#2871 MM-12900 Consolidating ctrl enter settings into just one
  components/user_settings/advanced/code_block_ctrl_enter_section/__snapshots__/code_block_ctrl_enter_section.test.jsx.snap
  components/user_settings/advanced/code_block_ctrl_enter_section/code_block_ctrl_enter_section.jsx
  components/user_settings/advanced/code_block_ctrl_enter_section/code_block_ctrl_enter_section.test.jsx
  components/user_settings/advanced/code_block_ctrl_enter_section/index.js
  components/user_settings/advanced/index.js
  components/user_settings/advanced/user_settings_advanced.jsx
  i18n/en.json
  utils/constants.jsx
Labels: 3: Reviews Complete

#2877 MM-12320 - Change "about" section references to use the site name when it is configured
  components/admin_console/admin_navbar_dropdown/index.js
Labels: 2: Dev Review

#2878 MM-15892: Disabling leave teams from the main menu for experimentalPrimarTeam enabled
  components/main_menu/__snapshots__/main_menu.test.jsx.snap
  components/main_menu/main_menu.jsx
Labels: 2: Dev Review, CherryPick/Approved

#2858 MM-15764 - Updating styling for names in modal
  sass/components/_modal.scss
Labels: 3: Reviews Complete, CherryPick/Approved

#2859 [MM-15755] fix old links to use the new urls in system console
  components/admin_console/__snapshots__/message_export_settings.test.jsx.snap
  components/admin_console/group_settings/group_details/__snapshots__/group_details.test.jsx.snap
  components/admin_console/group_settings/group_details/group_details.jsx
  components/admin_console/message_export_settings.jsx
  components/announcement_bar/configuration_bar/configuration_bar.jsx
  i18n/en.json
Labels: 3: Reviews Complete, CherryPick/Approved, Setup Test Server

#2882 [MM-15329] Add Enabled beside post:all and post:channel checkboxes
  components/integrations/bots/add_bot/add_bot.jsx
  i18n/en.json
  sass/layout/_forms.scss
Labels: 2: Dev Review, Setup Test Server

#2853 MM-15008 E2E: Test forgot password for email with valid account on server
  components/login/login_controller/login_controller.jsx
  components/password_reset_form/password_reset_form.jsx
  components/password_reset_send_link.jsx
  cypress/integration/email/mention_email_notification_spec.js
  cypress/integration/signin_authentication/forgot_password_spec.js
  cypress/support/api_commands.js
  cypress/utils/index.js
Labels: 3: Reviews Complete

#2883 MM-15737 - Updating sidebar icons for GM and Private
  sass/components/_status-icon.scss
  sass/layout/_sidebar-left.scss
Labels: 3: Reviews Complete

#2887 MM-15920 - Updating compact view header
  sass/layout/_post.scss
Labels: 2: Dev Review, CherryPick/Approved

#2889 MM-15904 Only set Client user and roles if user is defined
  package-lock.json
  package.json
Labels: CherryPick/Approved

#2806 MM-15403 Fixes highlight for date separators and new messages line on post hover
  components/logged_in/logged_in.jsx
  components/post_view/post_list_virtualized/post_list_virtualized.jsx
  components/post_view/post_list_virtualized/post_list_virtualized.test.jsx
  package-lock.json
  package.json
  sass/layout/_post.scss
  sass/responsive/_tablet.scss
Labels: 3: Reviews Complete, CherryPick/Approved
