Repository mattermost/mattermost-webapp, pull requests merged in 2019-02, with the labels that each got.

#2312 MM-13508 Fixing react warning with invalid subtype.
  components/interactive_dialog/dialog_element.jsx
  components/interactive_dialog/dialog_element.test.jsx
  components/widgets/settings/text_setting.jsx
Labels: 2: Dev Review

#2316 Fix JS warnings on props.restrictTeamInvite
  components/tutorial/tutorial_intro_screens/tutorial_intro_screens.jsx
  components/tutorial/tutorial_view.jsx
Labels: 3: Ready to Merge

#2307 MM-13836 - Updating compact view css
  sass/layout/_post-right.scss
  sass/responsive/_mobile.scss
Labels: 3: Ready to Merge, CherryPickApproved

#2317 MM-13922 Fix wide image previews aspect ratio in posts
  components/__snapshots__/size_aware_image.test.jsx.snap
  components/post_view/message_attachments/message_attachment/message_attachment.jsx
  components/post_view/post_image/post_image.jsx
  components/size_aware_image.jsx
  components/size_aware_image.test.jsx
  utils/image_utils.jsx
Labels: CherryPickApproved

#2310 MM-13472: Displays 'Create New Channel' button in if has permission t…
  components/more_channels/__snapshots__/more_channels.test.jsx.snap
  components/more_channels/more_channels.jsx
Labels: 3: Ready to Merge, CherryPickCandidate

#2315 [MM-13927 & MM-13907] Fix user profile and status issue
  components/post_profile_picture/index.jsx
  components/profile_popover/index.js
  components/user_profile/index.js
Labels: 3: Ready to Merge, CherryPickApproved

#2302 MM-13864 - Updating image preview loader
  components/__snapshots__/loading_image_preview.test.jsx.snap
  components/loading_image_preview.jsx
  sass/components/_files.scss
  sass/components/_modal.scss
Labels: 3: Ready to Merge, CherryPickCandidate

#2301 MM-13862 - Updating emoji picker position
  components/create_comment/__snapshots__/create_comment.test.jsx.snap
  components/create_comment/create_comment.jsx
  components/create_post/__snapshots__/create_post.test.jsx.snap
  components/create_post/create_post.jsx
  components/edit_post_modal/__snapshots__/edit_post_modal.test.jsx.snap
  components/edit_post_modal/edit_post_modal.jsx
  components/emoji_picker/emoji_picker_overlay.jsx
  components/post_view/post_info/__snapshots__/post_info.test.jsx.snap
  components/post_view/post_info/post_info.jsx
  components/rhs_comment/rhs_comment.jsx
  components/rhs_root_post/rhs_root_post.jsx
  utils/constants.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2205 Adding *.log file preview
  utils/constants.jsx
Labels: 3: Ready to Merge

#2325 MM-13941 Fix rounded corners for link preview images
  components/post_view/post_image/post_image.jsx
Labels: 3: Ready to Merge

#2319 MM-13935 - Updating post right css
  sass/layout/_post-right.scss
Labels: 3: Ready to Merge, CherryPickApproved

#2318 Set method for File Upload to ensure CSRF Token will be added
  actions/file_actions.jsx
Labels: 3: Ready to Merge

#2323 [MM-13939] Fix for unicode emoji rending on separate line from the rest of a sentence in a post
  components/__snapshots__/size_aware_image.test.jsx.snap
  components/size_aware_image.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2329 MM-11848 Allowing clicking on username to open profile popover for webhook posts.
  components/post_view/post_header/post_header.jsx
Labels: 3: Ready to Merge

#2324 [MM 13677] Fix to ensure unsupported unicode emoji can be rendered jumbo size
  NOTICE.txt
  package-lock.json
  package.json
  sass/components/_emoticons.scss
  sass/layout/_post.scss
  utils/text_formatting.jsx
  utils/text_formatting.test.jsx
Labels: 2: Dev Review

#2233 [MM-13297] Remove usage of localizeMessage and dangerouslySetInnerHTML from components in `components/help`
  components/help/components/attaching.jsx
  components/help/components/commands.jsx
  components/help/components/composing.jsx
  components/help/components/formatting.jsx
  components/help/components/mentioning.jsx
  components/help/components/messaging.jsx
  i18n/en.json
Labels: 3: Ready to Merge

#2332 translations PR 20190204
  i18n/de.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 3: Ready to Merge

#2304 [MM-13839] Check for password when updating the eMail
  components/user_settings/general/user_settings_general.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2340 MM-13564 Add e2e to test ellipsis in channel if header description too long
  cypress/integration/channel/header_spec.js
  cypress/support/index.js
  cypress/support/validators.js
Labels: 3: Ready to Merge, Hackfest

#2320 [MM-12737] Migrate preference-related actions from user_actions.jsx t…
  actions/user_actions.jsx
  components/tutorial/tutorial_intro_screens/__snapshots__/tutorial_intro_screen.test.jsx.snap
  components/tutorial/tutorial_intro_screens/index.jsx
  components/tutorial/tutorial_intro_screens/tutorial_intro_screen.test.jsx
  components/tutorial/tutorial_intro_screens/tutorial_intro_screens.jsx
  components/tutorial/tutorial_tip/__snapshots__/tutorial_tip.test.jsx.snap
  components/tutorial/tutorial_tip/index.js
  components/tutorial/tutorial_tip/tutorial_tip.jsx
  components/tutorial/tutorial_tip/tutorial_tip.test.jsx
  components/user_settings/advanced/index.js
  components/user_settings/advanced/user_settings_advanced.jsx
  components/user_settings/advanced/user_settings_advanced.test.jsx
  components/user_settings/display/index.js
  components/user_settings/display/user_settings_display.jsx
  components/user_settings/display/user_settings_display.test.jsx
  components/user_settings/display/user_settings_theme/__snapshots__/user_settings_theme.test.jsx.snap
  components/user_settings/display/user_settings_theme/user_settings_theme.jsx
  components/user_settings/display/user_settings_theme/user_settings_theme.test.jsx
  components/user_settings/notifications/email_notification_setting/__snapshots__/email_notification_setting.test.jsx.snap
  components/user_settings/notifications/email_notification_setting/email_notification_setting.jsx
  components/user_settings/notifications/email_notification_setting/email_notification_setting.test.jsx
  components/user_settings/notifications/email_notification_setting/index.js
  components/user_settings/notifications/user_settings_notifications.jsx
Labels: 3: Ready to Merge, Hackfest

#2336 Mark some missed strings to be translable
  components/user_settings/notifications/desktop_notification_settings.jsx
Labels: 3: Ready to Merge, CherryPickCandidate

#2326 MM-13701: E2E test consecutive message does not repeat profile info
  cypress/integration/channel/message_spec.js
Labels: 3: Ready to Merge, Hackfest

#2330 Fix for jumping to posts via relative links.
  utils/markdown/renderer.jsx
Labels: 3: Ready to Merge

#2346 MM-12948 - Fixing dividers in dropdown menu mobile
  components/channel_header_dropdown/mobile_channel_header_dropdown.js
  sass/responsive/_mobile.scss
Labels: 2: Dev Review, CherryPickApproved

#2328 MM-13225 Add E2E test for channel display modes
  cypress/integration/account_settings/display/channel_display_mode_spec.js
  cypress/support/index.js
Labels: 3: Ready to Merge, Hackfest

#2347 [MM-13728] Fix pixelated Mattermost icon in Chrome bookmark rendering
  root.html
  webpack.config.js
Labels: 2: Dev Review

#2342 MM-13867 - Updating pending post css
  sass/layout/_post.scss
  utils/utils.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2345 MM-13998 - Updating badge alignment
  sass/components/_badge.scss
Labels: 3: Ready to Merge, CherryPickApproved

#2344 MM-13948 - Fixing post highlight spacing in RHS
  sass/layout/_post-right.scss
  sass/responsive/_mobile.scss
Labels: 2: Dev Review, CherryPickApproved

#2341 MM-13583: Preventing delete/edit posts on edit post modal when you haven't the right permission
  components/edit_post_modal/__snapshots__/edit_post_modal.test.jsx.snap
  components/edit_post_modal/edit_post_modal.jsx
  components/edit_post_modal/edit_post_modal.test.jsx
  components/edit_post_modal/index.js
Labels: 3: Ready to Merge

#2354 MM-14048 - Updating secondary button on modal
  components/admin_console/reset_password_modal/reset_password_modal.jsx
  components/change_url_modal/__snapshots__/change_url_modal.test.jsx.snap
  components/change_url_modal/change_url_modal.jsx
  components/convert_channel_modal/convert_channel_modal.jsx
  components/leave_team_modal/__snapshots__/leave_team_modal.test.jsx.snap
  components/leave_team_modal/leave_team_modal.jsx
  components/leave_team_modal/leave_team_modal.test.jsx
Labels: 2: Dev Review, CherryPickApproved

#2338 [MM-13847] Fix highlighting of at-channel, at-all, at-here when immediately followed by a period
  utils/text_formatting.jsx
  utils/text_formatting.test.jsx
Labels: 2: Dev Review

#2353 [MM-12750] Remove getMissingProfiles from user_actions.jsx
  actions/user_actions.jsx
Labels: 3: Ready to Merge, Hackfest

#2229 [MM-13279] Add automated test using cypress for Account Settings > Add Nickname
  components/searchable_user_list/searchable_user_list.jsx
  cypress/integration/account_settings/general/nickname.js
Labels: 2: Dev Review

#2322 Update NOTICE.txt
  NOTICE.txt
Labels: 3: Ready to Merge, CherryPickApproved

#2360 [MM-14051] Hides user count when user status filter is applied
  components/searchable_user_list/searchable_user_list.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2359 [MM-12749] Remove loadMyTeamMembers from user_actions.jsx
  actions/user_actions.jsx
  components/team_members_dropdown/index.js
  components/team_members_dropdown/team_members_dropdown.jsx
Labels: Hackfest

#2364 MM-14054 Fix license announcement bar
  components/announcement_bar/configuration_bar.jsx
Labels: 2: Dev Review, CherryPickApproved

#2357 GH-10205 Escape should not close modal when an autocomplete drop down is in use
  components/edit_post_modal/__snapshots__/edit_post_modal.test.jsx.snap
  components/edit_post_modal/edit_post_modal.jsx
  components/emoji_picker/emoji_picker_tabs.jsx
  cypress/integration/channel/edit_message_spec.js
Labels: Hackfest

#2367 [MM-13979] Refactor PostInfo for E2E
  components/post_view/post_info/__snapshots__/post_info.test.jsx.snap
  components/post_view/post_info/index.js
  components/post_view/post_info/post_info.jsx
  components/post_view/post_info/post_info.test.jsx
  components/post_view/post_reaction/__snapshots__/post_reaction.test.jsx.snap
  components/post_view/post_reaction/index.js
  components/post_view/post_reaction/post_reaction.jsx
  components/post_view/post_reaction/post_reaction.test.jsx
  components/rhs_comment/index.js
  components/rhs_comment/rhs_comment.jsx
  components/rhs_root_post/index.js
  components/rhs_root_post/rhs_root_post.jsx
Labels: 3: Ready to Merge

#2169 MM-13188 Fix for channels with unreads having loading indicator placed above unread messages line
  actions/post_actions.test.js
  actions/post_utils.js
  actions/post_utils.test.js
  actions/websocket_actions.jsx
  package-lock.json
  package.json
Labels: 3: Ready to Merge, Awaiting Next Release

#2327 Exposes Reply-To email header configuration in UI.
  components/admin_console/email_settings.jsx
  i18n/en.json
Labels: 2: Dev Review

#2348 MM-13945 - Updating spinner icon
  components/widgets/loading/loading_spinner.jsx
  components/widgets/loading/loading_spinner.test.jsx
  sass/components/_files.scss
Labels: 3: Ready to Merge, CherryPickApproved

#2369 MM-14080 - Updating help text and dropdown at system console
  sass/routes/_settings.scss
Labels: 2: Dev Review, CherryPickApproved

#2365 MM-14002 Do not open internal markdown links in a new tab if site URL is not set
  utils/markdown/renderer.jsx
  utils/text_formatting.jsx
Labels: 2: Dev Review, CherryPickApproved

#2287 MM-13832: Changes docs link.
  components/admin_console/group_settings/__snapshots__/group_settings.test.jsx.snap
  components/admin_console/group_settings/group_settings.jsx
  i18n/en.json
Labels: 3: Ready to Merge, CherryPickCandidate

#2300 MM-9478: set autofocus on default section in account settings modal
  components/user_settings/display/__snapshots__/user_settings_display.test.jsx.snap
  components/user_settings/display/user_settings_display.jsx
  components/user_settings/display/user_settings_theme/user_settings_theme.jsx
  components/user_settings/display/user_settings_theme/user_settings_theme.test.jsx
  components/user_settings/modal/user_settings_modal.jsx
  components/user_settings/security/user_settings_security.jsx
  components/user_settings/sidebar/__snapshots__/user_settings_sidebar.test.jsx.snap
  components/user_settings/sidebar/user_settings_sidebar.jsx
Labels: 3: Ready to Merge, Hackfest

#2368 translations PR 20190211
  i18n/de.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 2: Dev Review

#2371 MM-14153 - Updating buttons on signup page
  sass/routes/_signup.scss
Labels: 3: Ready to Merge, CherryPickApproved

#2374 MM-14124 - Updating sys console header height
  sass/routes/_admin-console.scss
Labels: 2: Dev Review

#2335 [MM-13872] UI Automation: Write an automated test using `cypress` for "Create a Team"
  components/create_team/components/__snapshots__/display_name.test.jsx.snap
  components/create_team/components/display_name.jsx
  components/create_team/components/team_url/__snapshots__/team_url.test.jsx.snap
  components/create_team/components/team_url/team_url.jsx
  cypress/integration/team/create_a_team_spec.js
  cypress/utils/index.js
  package-lock.json
Labels: 2: Dev Review, Hackfest

#2378 MM-14158 - Updating badge in sidebars
  sass/components/_badge.scss
Labels: 3: Ready to Merge, CherryPickApproved

#2372 [MM-14125] Fix endless spinner on image placeholder for invalid image URL
  components/post_view/message_attachments/message_attachment/message_attachment.test.jsx
  components/post_view/post_image/post_image.jsx
  components/size_aware_image.jsx
  components/size_aware_image.test.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2376 [MM-14142] Saved recent emojis per user on local storage so it can be retrieved on user login
  actions/global_actions.jsx
  actions/local_storage.jsx
  components/logged_in/logged_in.jsx
  stores/local_storage_store.jsx
Labels: 3: Ready to Merge

#2337 MM-13951: add c and sh in syntaxe highlighting
  utils/constants.jsx
Labels: Hackfest

#2313 Clarify that "Restrict account creation to specified email domains" setting only applies to email login
  components/admin_console/admin_definition.jsx
  i18n/en.json
Labels: 3: Ready to Merge

#2361 [MM-12746] Migrate user update actions from user_actions.jsx to redux
  actions/user_actions.jsx
  components/admin_console/system_users/system_users_dropdown/index.js
  components/admin_console/system_users/system_users_dropdown/system_users_dropdown.jsx
  components/admin_console/system_users/system_users_dropdown/system_users_dropdown.test.js
  components/claim/claim_controller.jsx
  components/claim/components/ldap_to_email.jsx
  components/claim/components/ldap_to_email.test.js
  components/claim/index.js
  components/team_members_dropdown/index.js
  components/team_members_dropdown/team_members_dropdown.jsx
  components/team_members_dropdown/team_members_dropdown.test.js
  components/user_settings/advanced/index.js
  components/user_settings/advanced/user_settings_advanced.jsx
  components/user_settings/advanced/user_settings_advanced.test.jsx
  components/user_settings/display/__snapshots__/user_settings_display.test.jsx.snap
  components/user_settings/display/manage_languages/index.js
  components/user_settings/display/manage_languages/manage_languages.jsx
  components/user_settings/display/manage_languages/manage_languages.test.js
  components/user_settings/display/manage_timezones/index.js
  components/user_settings/display/manage_timezones/manage_timezones.jsx
  components/user_settings/display/manage_timezones/manage_timezones.test.js
  components/user_settings/display/user_settings_display.jsx
  components/user_settings/general/index.js
  components/user_settings/general/user_settings_general.jsx
  components/user_settings/general/user_settings_general.test.js
  components/user_settings/notifications/index.js
  components/user_settings/notifications/user_settings_notifications.jsx
  components/user_settings/notifications/user_settings_notifications.test.js
  components/user_settings/security/index.js
  components/user_settings/security/mfa_section/__snapshots__/mfa_section.test.jsx.snap
  components/user_settings/security/mfa_section/mfa_section.test.jsx
  components/user_settings/security/user_settings_security.jsx
  components/user_settings/security/user_settings_security.test.js
Labels: 3: Ready to Merge, Hackfest

#2370 Update test keys and description of all Cypress specs
  cypress/integration/account_settings/display/channel_display_mode_spec.js
  cypress/integration/account_settings/general/nickname.js
  cypress/integration/account_settings/sidebar/channel_switcher_spec.js
  cypress/integration/channel/edit_message_spec.js
  cypress/integration/channel/header_spec.js
  cypress/integration/channel/message_draft_spec.js
  cypress/integration/channel/message_spec.js
  cypress/integration/team/create_a_team_spec.js
  cypress/integration/team/teams_spec.js
Labels: 2: Dev Review, QA Review

#2362 [MM-13302] Created the LocalizedInput component to remove usage of th…
  components/__snapshots__/searchable_channel_list.test.jsx.snap
  components/admin_console/__snapshots__/custom_url_schemes_setting.test.jsx.snap
  components/admin_console/compliance_reports/compliance_reports.jsx
  components/admin_console/custom_url_schemes_setting.jsx
  components/admin_console/custom_url_schemes_setting.test.jsx
  components/admin_console/permission_schemes_settings/permission_team_scheme_settings/__snapshots__/permission_team_scheme_settings.test.jsx.snap
  components/admin_console/permission_schemes_settings/permission_team_scheme_settings/permission_team_scheme_settings.jsx
  components/admin_console/system_users/system_users.jsx
  components/claim/components/email_to_ldap.jsx
  components/claim/components/email_to_oauth.jsx
  components/claim/components/ldap_to_email.jsx
  components/claim/components/oauth_to_email.jsx
  components/emoji/emoji_list/emoji_list.jsx
  components/emoji_picker/emoji_picker.jsx
  components/gif_picker/components/SearchBar/index.jsx
  components/integrations/__snapshots__/abstract_command.test.jsx.snap
  components/integrations/abstract_command.jsx
  components/invite_member_modal/invite_member_modal.jsx
  components/localized_input/__snapshots__/localized_input.test.jsx.snap
  components/localized_input/localized_input.jsx
  components/localized_input/localized_input.test.jsx
  components/login/__snapshots__/login_mfa.test.jsx.snap
  components/login/login_controller/login_controller.jsx
  components/login/login_mfa.jsx
  components/mfa/setup/setup.jsx
  components/new_channel_modal/__snapshots__/new_channel_modal.test.jsx.snap
  components/new_channel_modal/new_channel_modal.jsx
  components/password_reset_form/password_reset_form.jsx
  components/password_reset_send_link.jsx
  components/rename_channel_modal/__snapshots__/rename_channel_modal.test.jsx.snap
  components/rename_channel_modal/rename_channel_modal.jsx
  components/searchable_channel_list.jsx
  components/searchable_user_list/searchable_user_list.jsx
  components/team_general_tab/team_general_tab.jsx
Labels: 2: Dev Review, Hackfest

#2352 [MM-13975] Add ToS and privacy links to About Mattermost modal
  components/about_build_modal/__snapshots__/about_build_modal.test.jsx.snap
  components/about_build_modal/about_build_modal.jsx
  components/about_build_modal/about_build_modal.test.jsx
  i18n/en.json
  sass/routes/_about-modal.scss
Labels: 2: Dev Review, Hackfest

#2383 [MM 14024] Stop leading spaces from preventing jumbo emoji
  utils/text_formatting.jsx
  utils/text_formatting.test.jsx
Labels: 2: Dev Review

#2244 MM-13260: Adding AdminPanel component to be used in the admin console
  components/admin_console/admin_panel.jsx
  components/admin_console/group_settings/__snapshots__/group_settings.test.jsx.snap
  components/admin_console/group_settings/group_details/__snapshots__/group_details.test.jsx.snap
  components/admin_console/group_settings/group_details/group_details.jsx
  components/admin_console/group_settings/group_settings.jsx
  components/admin_console/permission_schemes_settings/__snapshots__/permission_schemes_settings.test.jsx.snap
  components/admin_console/permission_schemes_settings/permission_schemes_settings.jsx
  components/admin_console/permission_schemes_settings/permission_system_scheme_settings/__snapshots__/permission_system_scheme_settings.test.jsx.snap
  components/admin_console/permission_schemes_settings/permission_system_scheme_settings/permission_system_scheme_settings.jsx
  components/admin_console/permission_schemes_settings/permission_system_scheme_settings/permission_system_scheme_settings.test.jsx
  components/admin_console/permission_schemes_settings/permission_team_scheme_settings/__snapshots__/permission_team_scheme_settings.test.jsx.snap
  components/admin_console/permission_schemes_settings/permission_team_scheme_settings/permission_team_scheme_settings.jsx
  components/admin_console/permission_schemes_settings/permission_team_scheme_settings/permission_team_scheme_settings.test.jsx
  components/widgets/admin_console/admin_panel.jsx
  components/widgets/admin_console/admin_panel.test.jsx
  components/widgets/admin_console/admin_panel_togglable.jsx
  components/widgets/admin_console/admin_panel_togglable.test.jsx
  components/widgets/admin_console/admin_panel_with_button.jsx
  components/widgets/admin_console/admin_panel_with_button.test.jsx
  components/widgets/admin_console/admin_panel_with_link.jsx
  components/widgets/admin_console/admin_panel_with_link.test.jsx
  sass/components/_permissions.scss
  sass/widgets/_module.scss
  sass/widgets/admin-console/_admin-panel.scss
Labels: 2: Dev Review

#2385 Fixed usage of the LocalizedInput component with a "value" prop provided
  components/localized_input/localized_input.jsx
Labels: 2: Dev Review, Hackfest

#2311 MM-13727 Broken image displays on login page if custom branding is enabled but no image has been uploaded
  components/login/login_controller/login_controller.jsx
Labels: 3: Ready to Merge, Setup Test Server

#2388 Fix message id
  components/message_submit_error.jsx
Labels: 3: Ready to Merge, CherryPickApproved, Hackfest

#2384 Update mattermost-redux to latest
  package-lock.json
  package.json
Labels: 3: Ready to Merge

#2377 [MM-14012] added e2e test for focus move to main input box
  cypress/integration/channel/message_spec.js
  cypress/support/commands.js
Labels: 3: Ready to Merge, Hackfest

#2389 [MM-13979] Add commands, test specs for post header, and upgrade Cypress to 3.1 due to Chrome 72 issue
  components/common/comment_icon.jsx
  components/dot_menu/__snapshots__/dot_menu.test.jsx.snap
  components/dot_menu/dot_menu.jsx
  components/post_view/post_flag_icon/__snapshots__/post_flag_icon.test.js.snap
  components/post_view/post_flag_icon/post_flag_icon.js
  components/post_view/post_info/__snapshots__/post_info.test.jsx.snap
  components/post_view/post_info/post_info.jsx
  components/post_view/post_time/post_time.jsx
  components/rhs_header_post/rhs_header_post.jsx
  components/rhs_thread/rhs_thread.jsx
  components/search_results_item/__snapshots__/search_results_item.test.jsx.snap
  components/search_results_item/search_results_item.jsx
  cypress/integration/post_header/post_header_spec.js
  cypress/support/commands.js
  package-lock.json
  package.json
Labels: 3: Ready to Merge, Awaiting PR

#2390 translations PR 20190218
  i18n/de.json
  i18n/es.json
  i18n/fr.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 3: Ready to Merge

#2382 [MM 14083] Support emoji like `:)` followed by additional non-word characters
  utils/emoticons.jsx
  utils/emoticons.test.jsx
Labels: 2: Dev Review

#2394 MM-13415: Focus should move to search field when Direct Message tab is selected in the combined join modal
  components/sidebar/more_public_direct_channels.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2380 wait for the response from getChannelTimezone
  components/create_comment/create_comment.jsx
  components/create_comment/create_comment.test.jsx
  components/create_post/create_post.jsx
  components/create_post/create_post.test.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2356 [MM-13840] Change eMail as a post-verification action
  components/announcement_bar/announcement_bar_controller.jsx
  components/announcement_bar/configuration_bar.jsx
  components/announcement_bar/index.js
  components/do_verify_email/do_verify_email.jsx
  components/do_verify_email/do_verify_email.test.jsx
  components/do_verify_email/index.js
  components/user_settings/general/index.js
  components/user_settings/general/user_settings_general.jsx
  components/user_settings/general/user_settings_general.test.js
  i18n/en.json
  i18n/ko.json
  utils/constants.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2351 MM-10516: Added interactive action support to ephemeral messages
  actions/views/posts.js
  components/post_view/message_attachments/action_button.jsx
  components/post_view/message_attachments/action_menu/action_menu.jsx
  components/post_view/message_attachments/message_attachment/__snapshots__/message_attachment.test.jsx.snap
  components/post_view/message_attachments/message_attachment/index.js
  components/post_view/message_attachments/message_attachment/message_attachment.jsx
  components/post_view/message_attachments/message_attachment/message_attachment.test.jsx
  package.json
Labels: 2: Dev Review

#2373 MM-14050 - Updating sys console UI for Users
  sass/responsive/_tablet.scss
  sass/routes/_admin-console.scss
Labels: 3: Ready to Merge, CherryPickApproved

#2395 MM-13731: Not updating property inside the component
  components/analytics/doughnut_chart.jsx
  components/analytics/line_chart.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2358 [MM-9912] Show "user is typing..." in Japanese IME hiragana mode
  components/create_comment/__snapshots__/create_comment.test.jsx.snap
  components/create_comment/create_comment.jsx
  components/create_post/__snapshots__/create_post.test.jsx.snap
  components/create_post/create_post.jsx
  components/suggestion/suggestion_box.jsx
  components/textbox/textbox.jsx
Labels: 3: Ready to Merge, Hackfest

#2401 [MM-13548] Added E2E test for adding new team member
  components/add_users_to_team/__snapshots__/add_users_to_team.test.jsx.snap
  components/add_users_to_team/add_users_to_team.jsx
  components/team_members_dropdown/team_members_dropdown.jsx
  components/team_sidebar/components/team_button.jsx
  cypress/fixtures/users.json
  cypress/integration/team/teams_spec.js
  cypress/support/commands.js
Labels: 3: Ready to Merge, Hackfest

#2400 MM-14187 Fix for Emojis are not appearing right away on posts
  actions/websocket_actions.jsx
  actions/websocket_actions.test.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2398 [MM-14281] Updated option value for multiselect to react-select 2.x
  components/add_users_to_team/__snapshots__/add_users_to_team.test.jsx.snap
  components/add_users_to_team/add_users_to_team.jsx
  components/channel_invite_modal/__snapshots__/channel_invite_modal.test.jsx.snap
  components/channel_invite_modal/channel_invite_modal.jsx
  components/channel_selector_modal/__snapshots__/channel_selector_modal.test.jsx.snap
  components/channel_selector_modal/channel_selector_modal.jsx
  components/more_direct_channels/__snapshots__/more_direct_channels.test.jsx.snap
  components/more_direct_channels/more_direct_channels.jsx
  components/multiselect/__snapshots__/multiselect.test.jsx.snap
  components/multiselect/multiselect.jsx
  components/team_selector_modal/__snapshots__/team_selector_modal.test.jsx.snap
  components/team_selector_modal/team_selector_modal.jsx
Labels: 3: Ready to Merge, Hackfest

#2392 MM-13332: Infinite scroll in search results has no loading indicator
  components/search_results/search_results.jsx
  sass/layout/_sidebar-right.scss
Labels: 3: Ready to Merge, CherryPickApproved

#2396 E2E: Quick fix for flaky tests
  cypress/integration/account_settings/display/channel_display_mode_spec.js
  cypress/integration/account_settings/sidebar/channel_switcher_spec.js
  cypress/integration/channel/edit_message_spec.js
  cypress/integration/channel/message_draft_spec.js
  cypress/integration/login/login_spec.js
  cypress/support/commands.js
  package-lock.json
Labels: 2: Dev Review

#2343 MM-13957 Reorganize post actions
  actions/integration_actions.test.js
  actions/post_actions.jsx
  actions/post_actions.test.js
  actions/post_utils.js
  actions/post_utils.test.js
  actions/status_actions.test.js
  actions/views/rhs.js
  actions/views/rhs.test.js
  actions/websocket_actions.jsx
  components/channel_header/channel_header.js
  components/post_view/index.js
  components/post_view/post_list.jsx
  package-lock.json
  package.json
  reducers/views/channel.js
  reducers/views/rhs.js
  reducers/views/rhs.test.js
  utils/constants.jsx
Labels: 3: Ready to Merge

#2405 [MM-14193] Render emojis in Message Attachment title
  components/post_view/message_attachments/message_attachment/__snapshots__/message_attachment.test.jsx.snap
  components/post_view/message_attachments/message_attachment/message_attachment.jsx
  components/post_view/message_attachments/message_attachment/message_attachment.test.jsx
Labels: 2: Dev Review, Hackfest

#2397 [MM-13697] UI Automation: Write an automated test using Cypress for "Edit post that has attachment, paste text in middle"
  components/dot_menu/dot_menu.jsx
  components/dot_menu/dot_menu_item.jsx
  components/edit_post_modal/__snapshots__/edit_post_modal.test.jsx.snap
  components/edit_post_modal/edit_post_modal.jsx
  components/signup/signup_controller/__snapshots__/signup_controller.test.jsx.snap
  cypress/fixtures/mattermost-icon.png
  cypress/integration/channel/message_edit_post_with_attachment_spec.js
  cypress/support/commands.js
  tests/setup.js
Labels: 2: Dev Review, Hackfest

#2415 add reporter to cypress
  cypress.json
  package-lock.json
  package.json
Labels: 3: Ready to Merge

#2381 MM-11263: expose various experimental settings
  components/admin_console/admin_console.jsx
  components/admin_console/admin_definition.jsx
  components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.jsx.snap
  components/admin_console/admin_sidebar/admin_sidebar.jsx
  i18n/en.json
Labels: 3: Ready to Merge

#2408 translations PR 20190225
  i18n/de.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 3: Ready to Merge

#2413 [MM-12945] Display alternate title text when mute is enabled
  components/channel_notifications_modal/components/__snapshots__/collapse_view.test.jsx.snap
  components/channel_notifications_modal/components/collapse_view.jsx
  components/channel_notifications_modal/components/describe.jsx
  i18n/en.json
Labels: 3: Ready to Merge, CherryPickApproved

#2418 update package
  package-lock.json
Labels: 3: Ready to Merge

#2416 [MM-14301 && MM-14296] Fix email notification setting being out of sync with the RN apps
  components/user_settings/notifications/email_notification_setting/__snapshots__/email_notification_setting.test.jsx.snap
  components/user_settings/notifications/email_notification_setting/email_notification_setting.jsx
  components/user_settings/notifications/email_notification_setting/email_notification_setting.test.jsx
  components/user_settings/notifications/email_notification_setting/index.js
  components/user_settings/notifications/index.js
  components/user_settings/notifications/user_settings_notifications.jsx
  utils/utils.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2409 [MM-13672] Handle opening GM from modal pressing ENTER key
  components/more_direct_channels/more_direct_channels.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2424 fix devdeps
  package-lock.json
  package.json
Labels: 3: Ready to Merge

#2414 MM-14104 Update logic for Markdown emphasis from upstream
  package-lock.json
  package.json
  utils/text_formatting_email.test.jsx
Labels: 2: Dev Review, CherryPickApproved

#2387 [MM-12738] Migrate OAuth app actions from user_actions.jsx and admin_…
  actions/admin_actions.jsx
  actions/user_actions.jsx
  components/authorize/authorize.jsx
  components/authorize/authorize.test.js
  components/authorize/index.js
  components/user_settings/security/index.js
  components/user_settings/security/user_settings_security.jsx
  components/user_settings/security/user_settings_security.test.js
Labels: 3: Ready to Merge, Hackfest

#2422 Small fixes in the new menus
  components/channel_header_dropdown/channel_header_dropdown_items.js
  components/file_upload/file_upload.jsx
  sass/widgets/menu/_menu_item.scss
  sass/widgets/menu/_menu_wrapper.scss
Labels: 3: Ready to Merge

#2426 Handle pending posts when dispatching RECEIVED_NEW_POST
  package-lock.json
  package.json
Labels: 3: Ready to Merge, CherryPickApproved

#2402 MM-14033 Fix scrolling on IE11 when changing notification settings
  components/user_settings/notifications/user_settings_notifications.jsx
Labels: 2: Dev Review

#2407 [MM-12748] Migrate system console user list actions from user_actions.jsx to redux
  actions/user_actions.jsx
  components/admin_console/system_users/index.js
  components/admin_console/system_users/system_users.jsx
  components/admin_console/system_users/system_users.test.jsx
  components/admin_console/system_users/system_users_dropdown/index.js
  components/admin_console/system_users/system_users_dropdown/system_users_dropdown.jsx
  components/admin_console/system_users/system_users_dropdown/system_users_dropdown.test.js
  components/user_settings/advanced/index.js
  components/user_settings/advanced/user_settings_advanced.jsx
  components/user_settings/advanced/user_settings_advanced.test.jsx
Labels: 2: Dev Review, Hackfest

#2410 [MM-14242] Remove props such as lastPostCount, idCount and idPrefix which were previously used for Se E2E
  components/common/comment_icon.jsx
  components/dot_menu/dot_menu.jsx
  components/dot_menu/dot_menu.test.jsx
  components/dot_menu/dot_menu_empty.test.jsx
  components/dot_menu/dot_menu_mobile.test.jsx
  components/post_view/post/index.js
  components/post_view/post/post.jsx
  components/post_view/post_body/post_body.jsx
  components/post_view/post_flag_icon/__snapshots__/post_flag_icon.test.js.snap
  components/post_view/post_flag_icon/post_flag_icon.js
  components/post_view/post_flag_icon/post_flag_icon.test.js
  components/post_view/post_header/post_header.jsx
  components/post_view/post_info/__snapshots__/post_info.test.jsx.snap
  components/post_view/post_info/post_info.jsx
  components/post_view/post_info/post_info.test.jsx
  components/post_view/post_list.jsx
  components/post_view/post_message_view/__snapshots__/post_message_view.test.jsx.snap
  components/post_view/post_message_view/post_message_view.jsx
  components/post_view/post_message_view/post_message_view.test.jsx
  components/post_view/post_reaction/post_reaction.jsx
  components/post_view/post_reaction/post_reaction.test.jsx
  components/post_view/post_time/post_time.jsx
  components/rhs_comment/rhs_comment.jsx
  components/rhs_root_post/rhs_root_post.jsx
  components/rhs_thread/rhs_thread.jsx
  components/search_results/search_results.jsx
  components/search_results_item/__snapshots__/search_results_item.test.jsx.snap
  components/search_results_item/search_results_item.jsx
  components/search_results_item/search_results_item.test.jsx
  cypress/integration/post_header/post_header_spec.js
  cypress/support/commands.js
  plugins/test/__snapshots__/post_type.test.jsx.snap
  plugins/test/post_type.test.jsx
  utils/constants.jsx
Labels: 2: Dev Review
