Repository mattermost/mattermost-webapp, pull requests merged in 2019-12, with the labels that each got.

#4345 [MM-20341] Add E2E test to verify customizable system config "About Link"
  components/widgets/settings/setting.tsx
  components/widgets/settings/text_setting.tsx
  e2e/cypress/integration/system_console/ui_and_api/customization_spec.js
Labels: 3: Reviews Complete, QA Review Done

#4364 GH-13145: Add label to search bar
  components/search_bar/__snapshots__/search_bar.test.jsx.snap
  components/search_bar/search_bar.jsx
Labels: 3: Reviews Complete, AutoMerge, QA Review Done

#4363 Fix failing test on channels and post header specs
  e2e/cypress/integration/channel/more_channels_spec.js
  e2e/cypress/integration/post_header/post_header_spec.js
  e2e/cypress/support/ui_commands.js
Labels: 2: Dev Review, 2: QA Review

#3978 GH-12345 Remove deprecated lifecycle methods from System Console
  components/admin_console/manage_roles_modal/manage_roles_modal.jsx
  components/admin_console/manage_tokens_modal/manage_tokens_modal.jsx
  components/admin_console/system_users/list/system_users_list.jsx
  components/analytics/line_chart.tsx
Labels: 3: Reviews Complete, QA Review Done

#4383 MM-20793 Fixing file upload progress bar.
  components/file_preview/__snapshots__/file_progress_preview.test.jsx.snap
  components/file_preview/file_progress_preview.jsx
  sass/components/_files.scss
Labels: CherryPick/Approved, QA Review Done

#4403 update context and change s3 buckets
  .circleci/config.yml
Labels: 3: Reviews Complete, CherryPick/Approved

#4330 MM-20330 add E2E for "Can change Help Link setting"
  e2e/cypress/integration/system_console/ui_and_api/customization_spec.js
Labels: AutoMerge, QA Review Done

#4360 MM-20310 - Updating suggestion list max height
  components/suggestion/suggestion_box.jsx
  components/suggestion/suggestion_list.jsx
  components/textbox/textbox.jsx
  utils/constants.jsx
Labels: 3: Reviews Complete, AutoMerge, CherryPick/Approved, QA Review Done, Tests/Not Needed

#4404 Automated cherry pick of #4383
  components/file_preview/__snapshots__/file_progress_preview.test.jsx.snap
  components/file_preview/file_progress_preview.jsx
  sass/components/_files.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4407 Automated cherry pick of #4360
  components/suggestion/suggestion_box.jsx
  components/suggestion/suggestion_list.jsx
  components/textbox/textbox.jsx
  utils/constants.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4397 MM-20768 - Updating channel dropdown css
  components/searchable_channel_list.jsx
  sass/components/_modal.scss
Labels: 2: Dev Review, CherryPick/Approved, QA Review Done, Tests/Not Needed

#4373 MM-20311: plugin signing permalink
  components/admin_console/plugin_management/__snapshots__/plugin_management.test.jsx.snap
  components/admin_console/plugin_management/plugin_management.jsx
  i18n/en.json
Labels: 3: Reviews Complete, QA Review Done

#4372 MM-20749: restrict post menu nesting
  plugins/registry.js
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#4410 Automated cherry pick of #4397
  components/searchable_channel_list.jsx
  sass/components/_modal.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4411 Automated cherry pick of #4372
  plugins/registry.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4274 [MM-20164] Member to Admin not updating has been fixed in Channnel Member Dropdown
  actions/websocket_actions.jsx
  components/popover_list_members/popover_list_members.jsx
  components/user_list_row/user_list_row.jsx
  e2e/cypress/integration/channel/user_to_admin_updates_manage_channel_members_modal_spec.js
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#4412 Automated cherry pick of #4274
  actions/websocket_actions.jsx
  components/popover_list_members/popover_list_members.jsx
  components/user_list_row/user_list_row.jsx
  e2e/cypress/integration/channel/user_to_admin_updates_manage_channel_members_modal_spec.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4365 Fix E2E on teams and integrations specs
  e2e/cypress/integration/integrations/builtin_commands/user_status_commands_spec.js
  e2e/cypress/integration/interactive_menu/basic_options_spec.js
  e2e/cypress/integration/team/teams_spec.js
Labels: 3: Reviews Complete, QA Review Done

#4415 translations PR 20191202
  i18n/de.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 3: Reviews Complete

#4263 [GH-12284] UI Automation: Write an automated test using Cypress for "Delete a GIF from RHS reply thread, other user viewing in center and RHS sees GIF preview disappear from both"
  e2e/cypress/integration/messaging/remove_gif_spec.js
Labels: 3: Reviews Complete, QA Review Done

#4395 [GH-13198] Improve WCAG score related to tabIndex on modals
  components/admin_console/reset_email_modal/reset_email_modal.jsx
  components/admin_console/reset_password_modal/reset_password_modal.jsx
  components/change_url_modal/__snapshots__/change_url_modal.test.jsx.snap
  components/change_url_modal/change_url_modal.jsx
  components/convert_channel_modal/convert_channel_modal.jsx
  components/tutorial/tutorial_intro_screens/__snapshots__/tutorial_intro_screen.test.jsx.snap
  components/tutorial/tutorial_intro_screens/tutorial_intro_screens.jsx
  components/user_settings/import_theme_modal.jsx
Labels: QA Review Done, Tests/Not Needed

#4414 Fixing error handling for schema admin settings
  components/admin_console/schema_admin_settings.jsx
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#4419 Automated cherry pick of #4414
  components/admin_console/schema_admin_settings.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4388 [GH-13174] UI Automation: Write an automated test using Cypress for "Can change Mattermost Apps Download Page Link setting"
  e2e/cypress/integration/system_console/ui_and_api/customization_spec.js
Labels: 3: Reviews Complete, AutoMerge, QA Review Done

#4408 Remove erroneous parameter for debounce
  components/admin_console/system_users/system_users.jsx
  components/admin_console/system_users/system_users.test.jsx
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#4420 Automated cherry pick of #4408
  components/admin_console/system_users/system_users.jsx
  components/admin_console/system_users/system_users.test.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4405 MM-20181 - Removing vertical scrollbar from css
  components/rhs_thread/rhs_thread.jsx
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#4401 MM-19942 - Updating backstage url and help css
  components/backstage/components/backstage_list.jsx
  components/integrations/__snapshots__/installed_incoming_webhook.test.jsx.snap
  components/integrations/__snapshots__/installed_outgoing_webhook.test.jsx.snap
  components/integrations/installed_incoming_webhook.jsx
  components/integrations/installed_oauth_app/__snapshots__/installed_oauth_app.test.jsx.snap
  components/integrations/installed_oauth_app/installed_oauth_app.jsx
  components/integrations/installed_outgoing_webhook.jsx
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done, Tests/Not Needed

#4423 Automated cherry pick of #4401
  components/backstage/components/backstage_list.jsx
  components/integrations/__snapshots__/installed_incoming_webhook.test.jsx.snap
  components/integrations/__snapshots__/installed_outgoing_webhook.test.jsx.snap
  components/integrations/installed_incoming_webhook.jsx
  components/integrations/installed_oauth_app/__snapshots__/installed_oauth_app.test.jsx.snap
  components/integrations/installed_oauth_app/installed_oauth_app.jsx
  components/integrations/installed_outgoing_webhook.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4422 Automated cherry pick of #4405
  components/rhs_thread/rhs_thread.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4400 MM-20763 - Updating MenuItem css
  components/widgets/menu/menu_items/menu_item.scss
Labels: 2: Dev Review, CherryPick/Approved, QA Review Done, Setup Cloud Test Server

#4424 Automated cherry pick of #4400
  components/widgets/menu/menu_items/menu_item.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4399 MM-20747 - Updating separator css
  components/widgets/separator/separator.scss
  sass/layout/_post-right.scss
  sass/layout/_post.scss
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#4426 Automated cherry pick of #4399
  components/widgets/separator/separator.scss
  sass/layout/_post-right.scss
  sass/layout/_post.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4398 MM-20754 - Fixing RHS spacing with banner
  sass/responsive/_tablet.scss
Labels: CherryPick/Approved, QA Review Done

#3877 [MM-15232] [MM-18158] Add a container to small images, Fix UX issues when markdown images are used in channel header
  components/__snapshots__/markdown_image.test.jsx.snap
  components/__snapshots__/size_aware_image.test.jsx.snap
  components/markdown/markdown.jsx
  components/markdown_image.jsx
  components/markdown_image.test.jsx
  components/post_markdown/__snapshots__/post_markdown.test.jsx.snap
  components/post_markdown/post_markdown.test.jsx
  components/post_markdown/system_message_helpers.jsx
  components/single_image_view/__snapshots__/single_image_view.test.jsx.snap
  components/single_image_view/single_image_view.jsx
  components/single_image_view/single_image_view.test.jsx
  components/size_aware_image.jsx
  components/size_aware_image.test.jsx
  components/view_image/view_image.jsx
  e2e/cypress/fixtures/MM-logo-horizontal.png
  e2e/cypress/fixtures/image-small-height.png
  e2e/cypress/fixtures/image-small-width.png
  e2e/cypress/fixtures/small-image.png
  e2e/cypress/integration/channel/image_attachment_spec.js
  e2e/cypress/integration/markdown/markdown_image_spec.js
  sass/components/_files.scss
  sass/layout/_markdown.scss
  utils/__snapshots__/message_html_to_component.test.jsx.snap
  utils/markdown/renderer.jsx
  utils/message_html_to_component.jsx
  utils/message_html_to_component.test.jsx
  utils/text_formatting.jsx
  utils/text_formatting_imgs.test.jsx
Labels: 3: Reviews Complete, Hacktoberfest, QA Review Done

#4428 Automated cherry pick of #4398
  sass/responsive/_tablet.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4421 MM-20867: Fix for mutating props.
  components/admin_console/team_channel_settings/team/list/team_list.jsx
Labels: CherryPick/Approved, QA Review Done

#4429 Automated cherry pick of #4421
  components/admin_console/team_channel_settings/team/list/team_list.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4278 Fixes #13162 : added autofocus on plugin marketplace modal open
  components/plugin_marketplace/marketplace_modal.js
  e2e/cypress/integration/plugins/marketplace/marketplace_spec.js
  package-lock.json
Labels: 3: Reviews Complete, QA Review Done

#4376 GH-13176: Add automated cypress test for Support Email setting
  e2e/cypress/integration/system_console/ui_and_api/customization_spec.js
  package-lock.json
Labels: 3: Reviews Complete, AutoMerge, QA Review Done

#4384 GH-13175: Add automated Cypress test for "Can change Android App Download Link setting"
  e2e/cypress/integration/system_console/ui_and_api/customization_spec.js
Labels: 3: Reviews Complete, QA Review Done

#4282 [MM-20150] re-enable loading the whole thread if its incomplete on RHS
  components/rhs_thread/rhs_thread.jsx
  components/rhs_thread/rhs_thread.test.jsx
  utils/utils.jsx
Labels: 3: Reviews Complete, AutoMerge, QA Review Done

#4385 GH-13171: Add Cypress automated test for "Can change iOS App Download Link setting"
  e2e/cypress/integration/system_console/ui_and_api/customization_spec.js
Labels: 3: Reviews Complete, QA Review Done

#4390 [GH-13266] Fix isRHS passing
  components/search_results_item/__snapshots__/search_results_item.test.jsx.snap
  components/search_results_item/search_results_item.jsx
Labels: 3: Reviews Complete, QA Review Done

#4382 [MM-16541] Remove perfect-scrollbar package
  NOTICE.txt
  components/access_history_modal/access_history_modal.jsx
  components/access_history_modal/access_history_modal.test.jsx
  components/activity_log_modal/activity_log_modal.jsx
  components/activity_log_modal/activity_log_modal.test.jsx
  components/channel_notifications_modal/channel_notifications_modal.jsx
  components/popover_list_members/popover_list_members.jsx
  components/root/root.jsx
  components/team_general_tab/team_general_tab.jsx
  components/team_settings_modal/team_settings_modal.jsx
  components/team_settings_modal/team_settings_modal.test.jsx
  components/user_settings/modal/user_settings_modal.jsx
  package-lock.json
  package.json
  sass/styles.scss
Labels: 3: Reviews Complete, QA Review Done

#4288 MM-18609: Settings - "Send message on Ctrl+Enter" should say "Cmd+Enter" on a Mac
  components/user_settings/advanced/user_settings_advanced.jsx
  components/user_settings/advanced/user_settings_advanced.test.jsx
  i18n/en.json
Labels: 3: Reviews Complete, QA Review Done

#4437 Fixing JS error on channel leave or being removed from the channel
  components/sidebar/sidebar.jsx
Labels: 3: Reviews Complete, CherryPick/Approved

#4439 Automated cherry pick of #4437
  components/sidebar/sidebar.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4430 Fix e2e on more channels, channels and search
  e2e/cypress/integration/channel/more_channels_spec.js
  e2e/cypress/integration/messaging/channel_read_after_permalink_spec.js
  e2e/cypress/integration/search/search_group_message_spec.js
Labels: 3: Reviews Complete, QA Review Done

#4432 Fixed E2E tests on Guest Accounts
  e2e/cypress/integration/enterprise/guest_accounts/guest_invitation_ui_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/member_invitation_ui_spec.js
Labels: 3: Reviews Complete, QA Review Done

#4436 Fixing color pickers in the admin console
  components/admin_console/color_setting.tsx
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#4440 Automated cherry pick of #4436
  components/admin_console/color_setting.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4230 [MM-18944] Convert access_history_modal to TypeScript
  components/access_history_modal/__snapshots__/access_history_modal.test.tsx.snap
  components/access_history_modal/access_history_modal.test.tsx
  components/access_history_modal/access_history_modal.tsx
  components/access_history_modal/index.ts
Labels: 3: Reviews Complete, QA Review Done

#4435 MM-19813 - Focusing back the message input box on preview disable
  components/create_comment/create_comment.jsx
  components/create_comment/create_comment.test.jsx
Labels: 3: Reviews Complete, QA Review Done, Tests/Done

#4337 MM-20334 add E2E for "Can change Privacy Policy Link setting"
  e2e/cypress/integration/system_console/ui_and_api/customization_spec.js
Labels: 3: Reviews Complete, QA Review Done

#4438 Adding enter inside blocks work properly on edit and take into consideration the position of the cursor
  components/create_comment/create_comment.jsx
  components/create_post/create_post.jsx
  components/edit_post_modal/edit_post_modal.jsx
  components/edit_post_modal/edit_post_modal.test.jsx
  components/edit_post_modal/index.js
  utils/post_utils.jsx
  utils/post_utils.test.jsx
Labels: 3: Reviews Complete, QA Review Done, Setup Cloud Test Server

#4379 MM-20786 Migrate TutorialTip to use React.createRef
  components/tutorial/tutorial_tip/tutorial_tip.jsx
Labels: QA Review Done

#4394 [GH-12303] UI Automation: Write an automated test using Cypress for "Input box on main thread can expand with RHS open"
  e2e/cypress/integration/messaging/input_box_expands_with_rhs_spec.js
Labels: 3: Reviews Complete, QA Review Done

#4441 MM-20797 - Updating RHS css (separator fix)
  components/widgets/separator/separator.scss
  sass/components/_search.scss
  sass/layout/_post-right.scss
Labels: 2: Dev Review, CherryPick/Approved, QA Review Done

#4452 Automated cherry pick of #4441
  components/widgets/separator/separator.scss
  sass/components/_search.scss
  sass/layout/_post-right.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4442 MM-20671 - Updating team icon content
  components/widgets/team_icon/team_icon.scss
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#4456 Automated cherry pick of #4442
  components/widgets/team_icon/team_icon.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4444 MM-20926 - Updating help text truncation in menu
  components/widgets/menu/menu_items/menu_item.scss
Labels: CherryPick/Approved, QA Review Done

#4462 Automated cherry pick of #4444
  components/widgets/menu/menu_items/menu_item.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4450 MM-20965 - Fixing menus overflow
  components/widgets/menu/menu.scss
  sass/routes/_admin-console.scss
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#4464 Automated cherry pick of #4450
  components/widgets/menu/menu.scss
  sass/routes/_admin-console.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4445 MM-19818 - Updating whitespace for th in markdown
  sass/layout/_markdown.scss
  sass/layout/_post-right.scss
  utils/utils.jsx
Labels: 3: Reviews Complete, QA Review Done, Setup Cloud Test Server

#4454 [MM-20044] Public and private channel text update
  components/admin_console/team_channel_settings/channel/details/channel_modes.jsx
  i18n/en.json
Labels: 3: Reviews Complete, CherryPick/Approved

#4465 Automated cherry pick of #4454
  components/admin_console/team_channel_settings/channel/details/channel_modes.jsx
  i18n/en.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4425 MM-20866: Guest Filter and Guest Attributes should be disabled/hidden in the LDAP and SAML settings when Guest Access is disabled.
  components/admin_console/admin_definition.jsx
  i18n/en.json
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#4466 Automated cherry pick of #4425
  components/admin_console/admin_definition.jsx
  i18n/en.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4448 MM-17555 Implement custom intlShape
  components/admin_console/admin_navbar_dropdown/admin_navbar_dropdown.jsx
  components/admin_console/admin_sidebar/admin_sidebar.jsx
  components/admin_console/jobs/table.jsx
  components/admin_console/permission_schemes_settings/permission_description.jsx
  components/announcement_bar/configuration_bar/configuration_bar.jsx
  components/audit_table/audit_table.jsx
  components/backstage/components/backstage_header.jsx
  components/channel_groups_manage_modal/channel_groups_manage_modal.jsx
  components/channel_header/channel_header.js
  components/create_comment/create_comment.jsx
  components/create_post/create_post.jsx
  components/edit_channel_header_modal/edit_channel_header_modal.jsx
  components/edit_post_modal/edit_post_modal.jsx
  components/emoji_picker/components/emoji_picker_item.jsx
  components/file_upload/file_upload.jsx
  components/formatted_markdown_message.jsx
  components/login/login_controller/login_controller.jsx
  components/main_menu/main_menu.jsx
  components/permalink_view/permalink_view.jsx
  components/post_view/combined_system_message/combined_system_message.jsx
  components/post_view/combined_system_message/last_users.jsx
  components/post_view/post/post.jsx
  components/post_view/post_list/post_list_virtualized.jsx
  components/profile_popover/profile_popover.jsx
  components/rename_channel_modal/rename_channel_modal.jsx
  components/rhs_comment/rhs_comment.jsx
  components/rhs_root_post/rhs_root_post.jsx
  components/save_button.tsx
  components/search_results/search_results.jsx
  components/search_results_item/search_results_item.jsx
  components/select_team/components/select_team_item.jsx
  components/shortcuts_modal.jsx
  components/sidebar/channel_more.jsx
  components/sidebar/sidebar.jsx
  components/sidebar/sidebar_channel/sidebar_channel.jsx
  components/signup/signup_controller/signup_controller.jsx
  components/system_notice/system_notice.jsx
  components/team_groups_manage_modal/team_groups_manage_modal.jsx
  components/team_import_tab.jsx
  components/team_sidebar/components/team_button.jsx
  components/toggle_modal_button_redux/toggle_modal_button_redux.jsx
  components/tutorial/tutorial_intro_screens/tutorial_intro_screens.jsx
  components/user_settings/display/user_settings_theme/custom_theme_chooser.jsx
  components/user_settings/general/user_settings_general.jsx
  components/user_settings/modal/user_settings_modal.jsx
  components/user_settings/sidebar/user_settings_sidebar.jsx
  components/widgets/icons/fa_next_icon.tsx
  components/widgets/icons/fa_previous_icon.tsx
  components/widgets/icons/fa_warning_icon.tsx
  components/widgets/inputs/channels_input.jsx
  components/widgets/inputs/users_emails_input.jsx
  components/widgets/loading/loading_spinner.tsx
  tests/helpers/intl-test-helper.jsx
  utils/react_intl.ts
Labels: 3: Reviews Complete

#4406 MM-20260 - Email notification still sent while disabled in UI
  components/user_settings/notifications/email_notification_setting/__snapshots__/email_notification_setting.test.jsx.snap
  components/user_settings/notifications/email_notification_setting/email_notification_setting.jsx
  components/user_settings/notifications/email_notification_setting/email_notification_setting.test.jsx
  package-lock.json
  package.json
Labels: 3: Reviews Complete, AutoMerge, QA Review Done

#4443 Fix more channels and members modal
  e2e/cypress/integration/channel/more_channels_spec.js
  e2e/cypress/integration/channel/user_to_admin_updates_manage_channel_members_modal_spec.js
  e2e/cypress/integration/login/tutorial_navigation_and_links_spec.js
  e2e/cypress/support/api_commands.js
Labels: 3: Reviews Complete, QA Review Done

#4152 MM-19908 Add E2E for "Send Message" via profile popover
  e2e/cypress/integration/channel/send_message_via_profile_popover_spec.js
Labels: 2: QA Review

#4431 MM-20269: WCAG: Remove duplicate id uses by the search container
  components/search_bar/search_bar.jsx
  components/sidebar_right/sidebar_right.jsx
Labels: 3: Reviews Complete, QA Review Done

#4336 MM-20336 add E2E for "Can change Custom Brand Image setting"
  components/admin_console/brand_image_setting/brand_image_setting.jsx
  e2e/cypress/integration/system_console/ui_and_api/customization_spec.js
Labels: 3: Reviews Complete, QA Review Done

#4433 [MM-20766] Fix binding functions and references to reenable scroll
  components/suggestion/search_channel_provider.jsx
  components/suggestion/search_channel_with_permissions_provider.jsx
  components/suggestion/search_date_provider.jsx
  components/suggestion/search_suggestion_list.jsx
  components/suggestion/search_user_provider.jsx
  components/suggestion/suggestion_list.jsx
  components/suggestion/switch_channel_provider.jsx
  components/suggestion/switch_team_provider.jsx
  components/suggestion/timezone_provider.jsx
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#4467 [MM-20975] Fix spacing on RHS Pinned and flag icon
  sass/layout/_sidebar-right.scss
  sass/responsive/_tablet.scss
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#4482 Automated cherry pick of #4467
  sass/layout/_sidebar-right.scss
  sass/responsive/_tablet.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4485 Fixing Team icons opacity in teams menu
  sass/layout/_team-sidebar.scss
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#4491 Automated cherry pick of #4485
  sass/layout/_team-sidebar.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4481 Automated cherry pick of #4433
  components/suggestion/search_channel_provider.jsx
  components/suggestion/search_channel_with_permissions_provider.jsx
  components/suggestion/search_date_provider.jsx
  components/suggestion/search_suggestion_list.jsx
  components/suggestion/search_user_provider.jsx
  components/suggestion/suggestion_list.jsx
  components/suggestion/switch_channel_provider.jsx
  components/suggestion/switch_team_provider.jsx
  components/suggestion/timezone_provider.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4377 MM-17555 Remove some unneeded refs
  components/select_team/components/select_team_item.jsx
  components/sidebar/header/sidebar_header_dropdown_button.jsx
  plugins/channel_header_plug/channel_header_plug.jsx
Labels: 3: Reviews Complete, QA Review Done

#4484 Fixing admin console links in the announcements banner
  components/announcement_bar/__snapshots__/text_dismissable_bar.test.jsx.snap
  components/announcement_bar/configuration_bar/configuration_bar.jsx
  components/announcement_bar/text_dismissable_bar.jsx
  components/announcement_bar/text_dismissable_bar.test.jsx
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done, Setup Cloud Test Server, Tests/Done

#4497 Automated cherry pick of #4484
  components/announcement_bar/__snapshots__/text_dismissable_bar.test.jsx.snap
  components/announcement_bar/configuration_bar/configuration_bar.jsx
  components/announcement_bar/text_dismissable_bar.jsx
  components/announcement_bar/text_dismissable_bar.test.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4498 [MM-21174] Fix UI not aligned
  components/admin_console/team_channel_settings/group/__snapshots__/group_users_row.test.jsx.snap
  components/admin_console/team_channel_settings/group/group_users_row.jsx
Labels: 2: Dev Review, CherryPick/Approved, QA Review Done, Tests/Done

#4501 Automated cherry pick of #4498
  components/admin_console/team_channel_settings/group/__snapshots__/group_users_row.test.jsx.snap
  components/admin_console/team_channel_settings/group/group_users_row.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4409 MM-18679 : added test for post options menu in mobile view
  e2e/cypress/integration/messaging/post_options_menu_spec.js
  package-lock.json
Labels: 3: Reviews Complete

#4474 translations PR 20191209
  i18n/de.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ru.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 3: Reviews Complete

#4496 Fixing spacing between markdown special blocks
  utils/__snapshots__/admin_console_plugin_index.test.js.snap
  utils/markdown/remove_markdown.js
  utils/markdown/remove_markdown.test.js
Labels: 2: Dev Review, CherryPick/Approved, QA Review Done, Setup Cloud Test Server

#4502 Automated cherry pick of #4496
  utils/__snapshots__/admin_console_plugin_index.test.js.snap
  utils/markdown/remove_markdown.js
  utils/markdown/remove_markdown.test.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4463 MM-20988 Fix post time due to unsupported timezone by react-intl
  components/local_date_time/local_date_time.test.tsx
  components/local_date_time/local_date_time.tsx
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#4503 Automated cherry pick of #4463
  components/local_date_time/local_date_time.test.tsx
  components/local_date_time/local_date_time.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4487 MM-21042 test for "No items match" feedback
  e2e/cypress/integration/interactive_menu/basic_options_spec.js
Labels: 3: Reviews Complete, QA Review Done

#4459 fix "install plugins" button on plugin marketplace page
  components/plugin_marketplace/__snapshots__/marketplace_modal.test.js.snap
  components/plugin_marketplace/marketplace_modal.js
  e2e/cypress/integration/plugins/marketplace/marketplace_spec.js
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#4483 Fixing test needed before save in elasticsearch
  components/admin_console/__snapshots__/elasticsearch_settings.test.jsx.snap
  components/admin_console/elasticsearch_settings.jsx
  components/admin_console/elasticsearch_settings.test.jsx
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done, Setup Cloud Test Server, Tests/Done

#4486 Fixing active state for mentions and flagged posts
  components/channel_header/__snapshots__/channel_header.test.jsx.snap
  components/channel_header/channel_header.js
  components/channel_header/channel_header.test.jsx
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done, Tests/Done

#4488 MM-21105: Switching email/password signin to LDAP fails with error in console
  components/claim/components/email_to_ldap.jsx
Labels: 3: Reviews Complete, CherryPick/Approved

#4505 Automated cherry pick of #4483
  components/admin_console/__snapshots__/elasticsearch_settings.test.jsx.snap
  components/admin_console/elasticsearch_settings.jsx
  components/admin_console/elasticsearch_settings.test.jsx
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4506 Automated cherry pick of #4459
  components/plugin_marketplace/__snapshots__/marketplace_modal.test.js.snap
  components/plugin_marketplace/marketplace_modal.js
  e2e/cypress/integration/plugins/marketplace/marketplace_spec.js
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4499 MM-20939 - File picker opens twice when trying to attach a file through the paperclip button in mobile view
  components/file_upload/__snapshots__/file_upload.test.jsx.snap
  components/file_upload/file_upload.jsx
  components/file_upload/file_upload.test.jsx
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done, Setup Cloud Test Server

#4507 Automated cherry pick of #4486
  components/channel_header/__snapshots__/channel_header.test.jsx.snap
  components/channel_header/channel_header.js
  components/channel_header/channel_header.test.jsx
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4509 Automated cherry pick of #4488
  components/claim/components/email_to_ldap.jsx
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4510 Automated cherry pick of #4499
  components/file_upload/__snapshots__/file_upload.test.jsx.snap
  components/file_upload/file_upload.jsx
  components/file_upload/file_upload.test.jsx
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4378 MM-20785 Migrate modal body refs to React.createRef
  components/activity_log_modal/activity_log_modal.jsx
  components/channel_info_modal/channel_info_modal.jsx
  components/removed_from_channel_modal/removed_from_channel_modal.jsx
  components/shortcuts_modal.jsx
  components/team_settings_modal/team_settings_modal.jsx
Labels: 3: Reviews Complete, QA Review Done

#4508 MM-21198: Add beta tag to LHS and top of the groups page
  components/admin_console/admin_definition.jsx
  components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.jsx.snap
  components/admin_console/group_settings/__snapshots__/group_settings.test.jsx.snap
  components/admin_console/group_settings/group_settings.jsx
  i18n/en.json
Labels: 3: Reviews Complete, CherryPick/Approved, Docs/Done, QA Review Done

#4512 Automated cherry pick of #4508
  components/admin_console/admin_definition.jsx
  components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.jsx.snap
  components/admin_console/group_settings/__snapshots__/group_settings.test.jsx.snap
  components/admin_console/group_settings/group_settings.jsx
  i18n/en.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4492 MM-21057 Fix for New message line cutoff at the top of channel
  components/__snapshots__/size_aware_image.test.jsx.snap
  components/size_aware_image.jsx
  sass/components/_files.scss
  sass/layout/_markdown.scss
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#4476 MM-19870 - reset at-mention selection
  components/suggestion/suggestion_box.jsx
  components/suggestion/suggestion_box.test.jsx
Labels: 3: Reviews Complete, QA Review Done

#4370 [MM-20329] UI Automation: "Can change Terms of Service Link setting"
  e2e/cypress/integration/system_console/ui_and_api/customization_spec.js
Labels: 3: Reviews Complete, QA Review Done

#4250 [GH-12263] UI Automation: Write an automated test using Cypress for "At-mention user autocomplete does not overlap with channel header when drafting a long message containing a file attachment"
  e2e/cypress/integration/messaging/mention_autocomplete_overlap_spec.js
Labels: 3: Reviews Complete, AutoMerge, QA Review Done

#4515 Fix failing tests due to bad request when creating new user
  e2e/cypress/support/api_commands.js
Labels: 3: Reviews Complete

#4511 MM-21197: Hides some groups-related inputs and menu items without the…
  components/admin_console/admin_definition.jsx
  components/channel_header_dropdown/channel_header_dropdown_items.js
  components/channel_header_dropdown/index.js
  components/main_menu/index.jsx
  components/main_menu/main_menu.jsx
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done, Setup Cloud Test Server

#4519 Automated cherry pick of #4511
  components/admin_console/admin_definition.jsx
  components/channel_header_dropdown/channel_header_dropdown_items.js
  components/channel_header_dropdown/index.js
  components/main_menu/index.jsx
  components/main_menu/main_menu.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4516 MM-21222 Hover effect on inline markdown images cutoff on the right edge in RHS
  sass/layout/_markdown.scss
  utils/__snapshots__/message_html_to_component.test.jsx.snap
  utils/text_formatting.jsx
  utils/text_formatting_imgs.test.jsx
Labels: CherryPick/Approved, QA Review Done

#4517 Updated Groups Label to Groups (Beta) in LHS and Header Title
  e2e/cypress/integration/enterprise/system_console/sidebar_link_navigation_spec.js
Labels: QA Review Done

#4494 Fixed few flaky E2E Tests
  e2e/cypress/integration/channel/send_message_via_profile_popover_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/guest_invitation_ui_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/guest_removal_ui_spec.js
  e2e/cypress/integration/system_console/revoke_all_sessions_spec.js
Labels: 2: Dev Review

#4513 MM-21153 Count mentions in DM channels using mention_count
  package-lock.json
  package.json
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#4521 MM-21144- Disable Marketplace URL if RemoteMarketplace is false
  components/admin_console/plugin_management/__snapshots__/plugin_management.test.jsx.snap
  components/admin_console/plugin_management/plugin_management.jsx
  components/admin_console/plugin_management/plugin_management.test.jsx
Labels: 3: Reviews Complete

#4391 MM-20339 add E2E for "Can change Enable Custom Branding setting"
  e2e/cypress/integration/system_console/ui_and_api/customization_spec.js
Labels: 3: Reviews Complete, QA Review Done

#4500 MM-19614 - Display local plugins when remote marketplace is unavailable
  actions/marketplace.js
  e2e/cypress/integration/plugins/marketplace/marketplace_spec.js
Labels: 3: Reviews Complete, QA Review Done

#4514 [MM-21076] Make longer <MenuItem>s wrap instead of truncate with ellipsis
  components/widgets/menu/menu_items/__snapshots__/menu_item_toggle_modal_redux.test.tsx.snap
  components/widgets/menu/menu_items/menu_item.scss
  components/widgets/menu/menu_items/menu_item_action.test.tsx
  components/widgets/menu/menu_items/menu_item_action.tsx
  components/widgets/menu/menu_items/menu_item_toggle_modal_redux.test.tsx
  components/widgets/menu/menu_items/menu_item_toggle_modal_redux.tsx
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done, Setup Cloud Test Server

#4529 Automated cherry pick of #4514
  components/widgets/menu/menu_items/__snapshots__/menu_item_toggle_modal_redux.test.tsx.snap
  components/widgets/menu/menu_items/menu_item.scss
  components/widgets/menu/menu_items/menu_item_action.test.tsx
  components/widgets/menu/menu_items/menu_item_action.tsx
  components/widgets/menu/menu_items/menu_item_toggle_modal_redux.test.tsx
  components/widgets/menu/menu_items/menu_item_toggle_modal_redux.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4532 Revert "[MM-21076] Make longer <MenuItem>s wrap instead of truncate with ellipsis (#4514)"
  components/widgets/menu/menu_items/__snapshots__/menu_item_toggle_modal_redux.test.tsx.snap
  components/widgets/menu/menu_items/menu_item.scss
  components/widgets/menu/menu_items/menu_item_action.test.tsx
  components/widgets/menu/menu_items/menu_item_action.tsx
  components/widgets/menu/menu_items/menu_item_toggle_modal_redux.test.tsx
  components/widgets/menu/menu_items/menu_item_toggle_modal_redux.tsx
Labels: QA Review Done, Setup Cloud Test Server

#4534 Automated cherry pick of #4532
  components/widgets/menu/menu_items/__snapshots__/menu_item_toggle_modal_redux.test.tsx.snap
  components/widgets/menu/menu_items/menu_item.scss
  components/widgets/menu/menu_items/menu_item_action.test.tsx
  components/widgets/menu/menu_items/menu_item_action.tsx
  components/widgets/menu/menu_items/menu_item_toggle_modal_redux.test.tsx
  components/widgets/menu/menu_items/menu_item_toggle_modal_redux.tsx
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4528 MM-19614 - Updating Redux hash
  package-lock.json
  package.json
Labels: 3: Reviews Complete

#4526 Fixed few E2E tests based on the latest run
  e2e/cypress/integration/channel/mobile_message_deletion_spec.js
  e2e/cypress/integration/markdown/markdown_image_spec.js
  e2e/cypress/integration/messaging/remove_gif_spec.js
  e2e/cypress/integration/search/search_group_message_spec.js
Labels: 3: Reviews Complete, QA Review Done

#4493 [MM-20986] close modal on focus change due to shortcut
  components/channel_header/channel_header.js
  e2e/cypress/integration/account_settings/sidebar/channel_switcher_spec.js
  e2e/cypress/support/ui_commands.js
Labels: AutoMerge, QA Review Done

#4518 [MM-21087] Remove IE11 workaround from size_aware_image component
  components/__snapshots__/size_aware_image.test.jsx.snap
  components/size_aware_image.jsx
  components/size_aware_image.test.jsx
Labels: 3: Reviews Complete, QA Review Done

#4140 Add full screen modal focus trap
  components/invitation_modal/__snapshots__/invitation_modal.test.jsx.snap
  components/invitation_modal/__snapshots__/invitation_modal_confirm_step.test.jsx.snap
  components/invitation_modal/__snapshots__/invitation_modal_guests_step.test.jsx.snap
  components/invitation_modal/__snapshots__/invitation_modal_initial_step.test.jsx.snap
  components/invitation_modal/__snapshots__/invitation_modal_members_step.test.jsx.snap
  components/invitation_modal/invitation_modal.jsx
  components/invitation_modal/invitation_modal.test.jsx
  components/invitation_modal/invitation_modal_confirm_step.jsx
  components/invitation_modal/invitation_modal_guests_step.jsx
  components/invitation_modal/invitation_modal_initial_step.jsx
  components/invitation_modal/invitation_modal_members_step.jsx
  components/plugin_marketplace/__snapshots__/marketplace_modal.test.js.snap
  components/plugin_marketplace/marketplace_modal.js
  components/widgets/modals/full_screen_modal.test.tsx
  components/widgets/modals/full_screen_modal.tsx
Labels: 3: Reviews Complete, QA Review Done

#4525 Fix inline markdown paragraph styles
  sass/layout/_markdown.scss
  utils/markdown/renderer.jsx
Labels: 3: Reviews Complete, QA Review Done

#4375 MM-20784 Remove unneeded refs from RHS body
  components/create_comment/create_comment.jsx
  components/create_comment/create_comment.test.jsx
  components/rhs_card/rhs_card.jsx
  components/rhs_thread/__snapshots__/rhs_thread.test.jsx.snap
  components/rhs_thread/rhs_thread.jsx
  plugins/rhs_plugin/rhs_plugin.jsx
Labels: 3: Reviews Complete, QA Review Done

#4380 MM-20787 Remove ref from ConfirmModal
  components/confirm_modal.jsx
  components/confirm_modal.test.jsx
Labels: 3: Reviews Complete, QA Review Done

#4446 MM-17445 add test for "Words that trigger mentions support Chinese"
  e2e/cypress/integration/at_mentions/at_mentions_spec.js
Labels: 3: Reviews Complete, QA Review Done

#4537 Automated cherry pick of #4476
  components/suggestion/suggestion_box.jsx
  components/suggestion/suggestion_box.test.jsx
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4538 Automated cherry pick of #4406
  components/user_settings/notifications/email_notification_setting/__snapshots__/email_notification_setting.test.jsx.snap
  components/user_settings/notifications/email_notification_setting/email_notification_setting.jsx
  components/user_settings/notifications/email_notification_setting/email_notification_setting.test.jsx
  package-lock.json
  package.json
Labels: AutoMerge

#4539 Automated cherry pick of #4438
  components/create_comment/create_comment.jsx
  components/create_post/create_post.jsx
  components/edit_post_modal/edit_post_modal.jsx
  components/edit_post_modal/edit_post_modal.test.jsx
  components/edit_post_modal/index.js
  utils/post_utils.jsx
  utils/post_utils.test.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4470 MM-17555 Add LocalizedIcon component
  components/admin_console/request_button/__snapshots__/request_button.test.jsx.snap
  components/backstage/components/__snapshots__/backstage_header.test.jsx.snap
  components/backstage/components/backstage_header.jsx
  components/create_post/__snapshots__/create_post.test.jsx.snap
  components/create_post/create_post.jsx
  components/localized_icon.test.tsx
  components/localized_icon.tsx
  components/permalink_view/__snapshots__/permalink_view.test.jsx.snap
  components/permalink_view/permalink_view.jsx
  components/profile_popover/__snapshots__/profile_popover.test.jsx.snap
  components/profile_popover/profile_popover.jsx
  components/select_team/components/__snapshots__/select_team_item.test.jsx.snap
  components/select_team/components/select_team_item.jsx
  components/select_team/components/select_team_item.test.jsx
  components/signup/signup_controller/__snapshots__/signup_controller.test.jsx.snap
  components/signup/signup_controller/signup_controller.jsx
  components/system_notice/__snapshots__/system_notice.test.jsx.snap
  components/system_notice/system_notice.jsx
  components/user_settings/display/user_settings_theme/__snapshots__/custom_theme_chooser.test.jsx.snap
  components/user_settings/display/user_settings_theme/color_chooser.jsx
  components/user_settings/display/user_settings_theme/custom_theme_chooser.jsx
  components/user_settings/sidebar/__snapshots__/user_settings_sidebar.test.jsx.snap
  components/user_settings/sidebar/user_settings_sidebar.jsx
  components/widgets/icons/fa_next_icon.tsx
  components/widgets/icons/fa_previous_icon.tsx
  components/widgets/icons/fa_warning_icon.tsx
  components/widgets/loading/loading_spinner.test.tsx
  components/widgets/loading/loading_spinner.tsx
  package-lock.json
  package.json
Labels: 3: Reviews Complete, QA Review Done

#4468 MM-17555 Change MainMenu to use injectIntl
  components/main_menu/main_menu.jsx
  components/main_menu/main_menu.test.jsx
  components/profile_popover/__snapshots__/profile_popover.test.jsx.snap
  components/toggle_modal_button_redux/__snapshots__/toggle_modal_button_redux.test.jsx.snap
  components/toggle_modal_button_redux/toggle_modal_button_redux.jsx
  components/widgets/menu/menu_items/__snapshots__/menu_item_toggle_modal_redux.test.tsx.snap
  components/widgets/menu/menu_items/menu_item_toggle_modal_redux.test.tsx
  components/widgets/menu/menu_items/menu_item_toggle_modal_redux.tsx
  plugins/test/main_menu_action.test.jsx
Labels: 3: Reviews Complete, QA Review Done

#4523 MM-21039 searching within the list of options
  e2e/cypress/integration/interactive_menu/basic_options_spec.js
Labels: 3: Reviews Complete, QA Review Done

#4536 Stop propagating divider click handler to avoid toggle
  components/widgets/menu/menu.test.tsx
  components/widgets/menu/menu.tsx
  components/widgets/menu/menu_group.test.tsx
  components/widgets/menu/menu_group.tsx
  e2e/cypress/integration/menus/hamburguer_menu_spec.js
Labels: 3: Reviews Complete, QA Review Done

#4333 MM-14675: Remove the implicit groupteam when a groupchannel is added.…
  components/admin_console/group_settings/group_details/__snapshots__/group_teams_and_channels.test.jsx.snap
  components/admin_console/group_settings/group_details/group_details.jsx
  components/admin_console/group_settings/group_details/group_details.test.jsx
  components/admin_console/group_settings/group_details/group_teams_and_channels.jsx
  components/admin_console/group_settings/group_details/group_teams_and_channels_row.jsx
Labels: 3: Reviews Complete, QA Review Done

#4119 MM-14622 Pass post id as well as link when retrieving opengraph data
  components/post_view/post_attachment_opengraph/index.js
  components/post_view/post_body_additional_content/__snapshots__/post_body_additional_content.test.jsx.snap
  components/post_view/post_body_additional_content/post_body_additional_content.jsx
  components/youtube_video/index.js
  package-lock.json
  package.json
Labels: 3: Reviews Complete, QA Review Done

#4469 MM-17555 Change FileUpload to use injectIntl
  components/create_comment/__snapshots__/create_comment.test.jsx.snap
  components/create_comment/create_comment.jsx
  components/create_post/__snapshots__/create_post.test.jsx.snap
  components/create_post/create_post.jsx
  components/file_upload/file_upload.jsx
  components/file_upload/file_upload.test.jsx
Labels: 3: Reviews Complete, QA Review Done

#4381 MM-20788 Migrate autocomplete components to use React.createRef
  components/suggestion/search_suggestion_list.jsx
  components/suggestion/suggestion_box.jsx
  components/suggestion/suggestion_date.jsx
  components/suggestion/suggestion_list.jsx
Labels: 3: Reviews Complete, QA Review Done

#4549 Automated cherry pick of #4536
  components/widgets/menu/menu.test.tsx
  components/widgets/menu/menu.tsx
  components/widgets/menu/menu_group.test.tsx
  components/widgets/menu/menu_group.tsx
  e2e/cypress/integration/menus/hamburguer_menu_spec.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4542 MM-20332 UI Automation: System Console for "Can change Site Description setting"
  e2e/cypress/integration/system_console/ui_and_api/customization_spec.js
Labels: 3: Reviews Complete, QA Review Done

#4473 MM-17555 Use FormattedMessage in CustomThemeChooser
  components/user_settings/display/user_settings_theme/__snapshots__/custom_theme_chooser.test.jsx.snap
  components/user_settings/display/user_settings_theme/custom_theme_chooser.jsx
Labels: 3: Reviews Complete, QA Review Done
