Repository mattermost/mattermost-webapp, pull requests merged in 2019-01, with the labels that each got.

#2237 [MM-13591] Remove From Team fails with TypeError in console
  components/team_members_dropdown/team_members_dropdown.jsx
Labels: 2: Dev Review, CherryPickApproved

#2236 translations PR 20181231
  i18n/pl.json
  i18n/ro.json
Labels: 3: Ready to Merge

#2226 MM-13437 Deleting a reply from center channel should not show "This post has ... comments" in confirmation modal
  components/delete_post_modal/__snapshots__/delete_post_modal.test.jsx.snap
  components/delete_post_modal/delete_post_modal.jsx
  components/delete_post_modal/delete_post_modal.test.jsx
Labels: 3: Ready to Merge

#2216 MM-13497: Fix profile picture setDefault + change picture
  components/setting_picture.jsx
Labels: 2: Dev Review

#2241 Fix snapshot test of delete post modal
  components/delete_post_modal/__snapshots__/delete_post_modal.test.jsx.snap
Labels: 3: Ready to Merge

#2238 Handling nulls in getMyCurrentChannelMembership
  components/channel_notifications_modal/channel_notifications_modal.jsx
Labels: 3: Ready to Merge

#2239 MM-13518 - Updating profile popover in RHS
  components/profile_popover/profile_popover.jsx
  components/search_results_item/__snapshots__/search_results_item.test.jsx.snap
  components/search_results_item/search_results_item.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2056 MM-13638 Add support for Elixir syntax highlighting
  utils/constants.jsx
  utils/syntax_highlighting.jsx
Labels: 3: Ready to Merge

#2225 Disable edition on dot menu properly
  components/dot_menu/dot_menu.jsx
  components/dot_menu/dot_menu.test.jsx
  components/dot_menu/dot_menu_empty.test.jsx
  components/dot_menu/dot_menu_mobile.test.jsx
  components/dot_menu/index.js
  utils/post_utils.jsx
Labels: 2: Dev Review

#2243 MM-13580: disable red favicon
  components/sidebar/sidebar.jsx
Labels: CherryPickApproved

#2242 MM-13612: Always shows 'view members' for default channel.
  components/channel_header_dropdown/menu_items/__snapshots__/view_and_manage_members.test.js.snap
  components/channel_header_dropdown/menu_items/view_and_manage_members.js
Labels: 2: Dev Review, CherryPickCandidate

#2232 [GH-10035] Added the cypress spec for cancel out leave a team modal
  components/leave_team_modal/__snapshots__/leave_team_modal.test.jsx.snap
  components/leave_team_modal/leave_team_modal.jsx
  cypress/integration/team/teams_spec.js
Labels: 2: Dev Review

#2250 Fix getMyChannelMember selector usage
  actions/global_actions.jsx
  actions/notification_actions.jsx
Labels: 3: Ready to Merge

#2135 MM-13301 Remove usage of localizeMessage from Team Settings modal
  components/team_settings_modal.jsx
Labels: 3: Ready to Merge

#2249 MM-13627 Fix DM and GM mention counts missing from browser tab
  components/sidebar/index.js
Labels: 3: Ready to Merge, CherryPickApproved

#2258 MM-13522: make wording clearer about access tokens.
  i18n/en.json
Labels: 2: Dev Review, CherryPickApproved

#2259 Update mm-redux hash
  package-lock.json
  package.json
Labels: 3: Ready to Merge

#2252 [MM-11936] Remove "shown for 5 seconds" for desktop notifications in Account Settings > Notifications
  components/user_settings/notifications/__snapshots__/desktop_notification_settings.test.jsx.snap
  components/user_settings/notifications/desktop_notification_settings.jsx
  i18n/en.json
Labels: 2: Dev Review

#2254 MM-13352 - Fixing blockquotes in channel header
  sass/components/_popover.scss
  sass/layout/_headers.scss
  sass/layout/_markdown.scss
Labels: 3: Ready to Merge

#2240 [MM-13590] Fix posts padding when 12H time format is used
  sass/layout/_post.scss
  sass/responsive/_tablet.scss
Labels: 3: Ready to Merge, CherryPickApproved

#2247 [MM-13593] Remove NightwatchJS
  Makefile
  components/widgets/loading/loading_spinner.jsx
  components/widgets/loading/loading_spinner.test.jsx
  cypress.json
  cypress/integration/login/login_spec.js
  nightwatch.json
  package-lock.json
  package.json
  tests/e2e/commands/fillInput.js
  tests/e2e/commands/getChromeLogs.js
  tests/e2e/config.js
  tests/e2e/globals.js
  tests/e2e/pages/accountSettingsModalPage.js
  tests/e2e/pages/centerPage.js
  tests/e2e/pages/channelHeaderDropdownPage.js
  tests/e2e/pages/channelHeaderPage.js
  tests/e2e/pages/loginPage.js
  tests/e2e/pages/logoutPage.js
  tests/e2e/pages/sidebarLeftPage.js
  tests/e2e/pages/tutorialPage.js
  tests/e2e/test.sh
  tests/e2e/tests/1_login_logout/login.element.js
  tests/e2e/tests/1_login_logout/logout.element.js
  tests/e2e/tests/1_login_logout/tutorial.element.js
  tests/e2e/tests/2_center/centerPage.element.js
  tests/e2e/tests/2_center/channelHeader.dropdown.action.js
  tests/e2e/tests/2_center/channelHeader.element.js
  tests/e2e/tests/3_sidebarLeft/accountSettingsDisplay.action.js
  tests/e2e/tests/3_sidebarLeft/accountSettingsGeneral.action.js
  tests/e2e/tests/3_sidebarLeft/accountSettingsModalPage.element.js
  tests/e2e/tests/3_sidebarLeft/accountSettingsNotification.action.js
  tests/e2e/tests/3_sidebarLeft/sidebarLeftPage.element.js
Labels: 2: Dev Review

#2260 MM-13580: explicitly configure a favicon
  webpack.config.js
Labels: 2: Dev Review, CherryPickApproved

#1964 Ldap groups phase1
  components/admin_console/admin_console.jsx
  components/admin_console/admin_definition.jsx
  components/admin_console/admin_panel.jsx
  components/admin_console/admin_sidebar/admin_sidebar.jsx
  components/admin_console/group_settings/__snapshots__/group_row.test.jsx.snap
  components/admin_console/group_settings/__snapshots__/group_settings.test.jsx.snap
  components/admin_console/group_settings/group_details/__snapshots__/group_details.test.jsx.snap
  components/admin_console/group_settings/group_details/__snapshots__/group_profile.test.jsx.snap
  components/admin_console/group_settings/group_details/__snapshots__/group_teams_and_channels.test.jsx.snap
  components/admin_console/group_settings/group_details/__snapshots__/group_teams_and_channels_row.test.jsx.snap
  components/admin_console/group_settings/group_details/__snapshots__/group_users.test.jsx.snap
  components/admin_console/group_settings/group_details/__snapshots__/group_users_row.test.jsx.snap
  components/admin_console/group_settings/group_details/group_details.jsx
  components/admin_console/group_settings/group_details/group_details.test.jsx
  components/admin_console/group_settings/group_details/group_profile.jsx
  components/admin_console/group_settings/group_details/group_profile.test.jsx
  components/admin_console/group_settings/group_details/group_teams_and_channels.jsx
  components/admin_console/group_settings/group_details/group_teams_and_channels.test.jsx
  components/admin_console/group_settings/group_details/group_teams_and_channels_row.jsx
  components/admin_console/group_settings/group_details/group_teams_and_channels_row.test.jsx
  components/admin_console/group_settings/group_details/group_users.jsx
  components/admin_console/group_settings/group_details/group_users.test.jsx
  components/admin_console/group_settings/group_details/group_users_row.jsx
  components/admin_console/group_settings/group_details/group_users_row.test.jsx
  components/admin_console/group_settings/group_details/index.jsx
  components/admin_console/group_settings/group_row.jsx
  components/admin_console/group_settings/group_row.test.jsx
  components/admin_console/group_settings/group_settings.jsx
  components/admin_console/group_settings/group_settings.test.jsx
  components/admin_console/group_settings/groups_list/__snapshots__/groups_list.test.jsx.snap
  components/admin_console/group_settings/groups_list/groups_list.jsx
  components/admin_console/group_settings/groups_list/groups_list.test.jsx
  components/admin_console/group_settings/groups_list/index.js
  components/admin_console/jobs/__snapshots__/table.test.jsx.snap
  components/admin_console/jobs/table.jsx
  components/channel_selector_modal/__snapshots__/channel_selector_modal.test.jsx.snap
  components/channel_selector_modal/channel_selector_modal.jsx
  components/channel_selector_modal/channel_selector_modal.test.jsx
  components/channel_selector_modal/index.js
  components/team_import_tab.jsx
  i18n/en.json
  package-lock.json
  package.json
  reducers/views/channel_selector_modal.js
  reducers/views/index.js
  sass/components/_admin-panel.scss
  sass/components/_groups.scss
  sass/components/_modal.scss
  sass/components/_module.scss
  selectors/views/channel_selector_modal.js
  utils/utils.jsx
Labels: 1: PM Review, DO NOT MERGE

#2263 MM-13338: Fixes status icon hover wobble.
  sass/layout/_headers.scss
Labels: 3: Ready to Merge

#2266 MM-13723: Guard against null imagesMetadata.
  components/login/login_controller/login_controller.jsx
  utils/message_html_to_component.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2270 [MM-13760] Allow to close the announcement banner for email and site URL
  components/announcement_bar/configuration_bar.jsx
  i18n/en.json
Labels: 3: Ready to Merge, CherryPickApproved

#2227 [MM-13434] Prevent passing too much of user and status and rely on userId to prevent unnecessary re-render of component
  components/__snapshots__/profile_picture.test.jsx.snap
  components/at_mention/__snapshots__/at_mention.test.jsx.snap
  components/at_mention/at_mention.jsx
  components/at_mention/at_mention.test.jsx
  components/post_profile_picture/index.jsx
  components/post_profile_picture/post_profile_picture.jsx
  components/post_view/channel_intro_message/channel_intro_message.jsx
  components/post_view/post/index.js
  components/post_view/post/post.jsx
  components/post_view/post_header/index.js
  components/post_view/post_header/post_header.jsx
  components/profile_picture.jsx
  components/profile_popover/__snapshots__/profile_popover.test.jsx.snap
  components/profile_popover/index.js
  components/profile_popover/profile_popover.jsx
  components/rhs_comment/index.js
  components/rhs_comment/rhs_comment.jsx
  components/rhs_root_post/index.js
  components/rhs_root_post/rhs_root_post.jsx
  components/rhs_thread/rhs_thread.jsx
  components/search_results_item/__snapshots__/search_results_item.test.jsx.snap
  components/search_results_item/index.js
  components/search_results_item/search_results_item.jsx
  components/sidebar_right/index.js
  components/sidebar_right/sidebar_right.jsx
  components/user_profile.jsx
  components/user_profile/__snapshots__/user_profile.test.jsx.snap
  components/user_profile/index.js
  components/user_profile/user_profile.jsx
  components/user_profile/user_profile.test.jsx
  package-lock.json
  plugins/pluggable/__snapshots__/pluggable.test.jsx.snap
  plugins/pluggable/pluggable.test.jsx
Labels: 3: Ready to Merge

#2257 MM-13646 - Updating header popover position
  sass/responsive/_tablet.scss
Labels: 3: Ready to Merge

#2207 [MM-7865] Option to send as message when an invalid slash command is entered in RHS chat
  actions/views/create_comment.jsx
  actions/views/create_comment.test.jsx
  components/create_comment/create_comment.jsx
  components/create_comment/create_comment.test.jsx
Labels: 3: Ready to Merge

#2100 Fix setStates on async callbacks
  components/file_attachment/file_attachment.jsx
  components/post_view/message_attachments/message_attachment/message_attachment.jsx
  components/post_view/post_attachment_opengraph/post_attachment_opengraph.jsx
  components/post_view/post_body_additional_content/post_body_additional_content.jsx
  components/post_view/post_image/post_image.jsx
  components/post_view/post_list.jsx
  components/single_image_view/single_image_view.jsx
Labels: 2: Dev Review

#2264 MM-13603 Manifest for mobile browser
  webpack.config.js
Labels: 2: Dev Review

#2055 [MM 10682] Enable emoji picker for mobile web view
  components/create_comment/__snapshots__/create_comment.test.jsx.snap
  components/create_comment/create_comment.jsx
  components/create_post/__snapshots__/create_post.test.jsx.snap
  components/create_post/create_post.jsx
  components/dot_menu/dot_menu.jsx
  components/dot_menu/index.js
  components/edit_post_modal/__snapshots__/edit_post_modal.test.jsx.snap
  components/edit_post_modal/edit_post_modal.jsx
  components/emoji_picker/components/__snapshots__/emoji_picker_header.test.jsx.snap
  components/emoji_picker/components/emoji_picker_header.jsx
  components/emoji_picker/components/emoji_picker_header.test.jsx
  components/emoji_picker/emoji_picker.jsx
  components/emoji_picker/emoji_picker_overlay.jsx
  components/emoji_picker/emoji_picker_tabs.jsx
  components/post_view/post_info/__snapshots__/post_info.test.jsx.snap
  components/post_view/post_info/post_info.jsx
  components/post_view/reaction_list/__snapshots__/reactions_list.test.jsx.snap
  components/post_view/reaction_list/reaction_list.jsx
  components/rhs_comment/rhs_comment.jsx
  components/rhs_root_post/rhs_root_post.jsx
  i18n/en.json
  sass/components/_emoticons.scss
  sass/layout/_post.scss
  sass/responsive/_mobile.scss
  sass/utils/_variables.scss
  utils/utils.jsx
Labels: 3: Ready to Merge

#2283 MM-13712 remove user is typing when the user post the message
  actions/post_actions.test.js
  actions/post_utils.js
  actions/post_utils.test.js
Labels: 2: Dev Review

#2268 MM-13680 Modify return value of getLanguages
  i18n/i18n.jsx
Labels: 3: Ready to Merge

#2277 translations PR 20190121
  i18n/de.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 2: Dev Review

#2286 MM-13758 - Updating fa-chevron icon to fa-angle
  components/admin_console/permission_schemes_settings/permission_system_scheme_settings/__snapshots__/permission_system_scheme_settings.test.jsx.snap
  components/admin_console/permission_schemes_settings/permission_system_scheme_settings/permission_system_scheme_settings.jsx
  components/admin_console/permission_schemes_settings/permission_team_scheme_settings/__snapshots__/permission_team_scheme_settings.test.jsx.snap
  components/admin_console/permission_schemes_settings/permission_team_scheme_settings/permission_team_scheme_settings.jsx
  components/common/back_button.jsx
  components/icon/dropdown_icon.jsx
  components/icon/logout_icon.jsx
  components/icon/next_icon.jsx
  components/icon/previous_icon.jsx
  components/search_bar/search_bar.jsx
  sass/base/_typography.scss
  sass/components/_buttons.scss
  sass/layout/_sidebar-right.scss
  sass/routes/_admin-console.scss
  sass/routes/_settings.scss
  sass/routes/_signup.scss
Labels: 3: Ready to Merge

#2230 [GH-7494] Implement the system_admin and inactive filters for users under system console
  actions/user_actions.jsx
  actions/views/search.js
  components/admin_console/system_users/__snapshots__/system_users.test.jsx.snap
  components/admin_console/system_users/index.js
  components/admin_console/system_users/list/__snapshots__/system_users_list.test.jsx.snap
  components/admin_console/system_users/list/index.js
  components/admin_console/system_users/list/selectors.jsx
  components/admin_console/system_users/list/selectors.test.jsx
  components/admin_console/system_users/list/system_users_list.jsx
  components/admin_console/system_users/list/system_users_list.test.jsx
  components/admin_console/system_users/system_users.jsx
  components/admin_console/system_users/system_users.test.jsx
  i18n/en.json
  sass/routes/_admin-console.scss
  utils/constants.jsx
  utils/get_users.js
  utils/get_users.test.js
Labels: 3: Ready to Merge

#2273 MM-13788: Guards against null post prop, for example when previewing …
  components/post_markdown/post_markdown.jsx
Labels: 3: Ready to Merge, CherryPickCandidate

#2224 [MM-12861] Improve sorting in emoji autocomplete and emoji picker
  actions/emoji_actions.jsx
  components/emoji_picker/emoji_picker.jsx
  components/suggestion/emoticon_provider.jsx
  utils/emoji.test.jsx
  utils/emoji_utils.jsx
Labels: 3: Ready to Merge

#2282 MM-13765 Update dependencies.
  components/__snapshots__/color_input.test.jsx.snap
  components/admin_console/__snapshots__/color_setting.test.jsx.snap
  components/admin_console/schema_admin_settings.jsx
  package-lock.json
  package.json
Labels: Awaiting Next Release

#2289 MM-13801 Fix User Profile for root post in RHS
  components/rhs_root_post/rhs_root_post.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2293 adding timeout to jenkins job
  build/Jenkinsfile
Labels: 3: Ready to Merge

#2284 MM-13784 - Updating team modal and dropdown
  components/admin_console/manage_teams_modal/__snapshots__/manage_teams_modal.test.jsx.snap
  components/admin_console/manage_teams_modal/manage_teams_dropdown.jsx
  components/admin_console/manage_teams_modal/manage_teams_modal.jsx
  sass/components/_modal.scss
Labels: 3: Ready to Merge

#2294 [MM-13167] Fix for scroll lock when loading more posts
  components/post_view/post_list.jsx
Labels: 3: Ready to Merge, CherryPickCandidate, Setup Test Server

#2295 translations PR 20190128
  i18n/de.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 3: Ready to Merge

#2279 MM-13687 Removing rows from Send Email Invite modal doesn't remove them immediately
  components/invite_member_modal/invite_member_modal.jsx
Labels: 3: Ready to Merge

#2280 [MM-13811] fixes wrong stylings on several modals
  components/__snapshots__/get_link_modal.test.jsx.snap
  components/get_link_modal.jsx
  components/invite_member_modal/invite_member_modal.jsx
  components/multiselect/__snapshots__/multiselect.test.jsx.snap
  components/multiselect/multiselect.jsx
Labels: 2: Dev Review

#2298 MM-13857 Stop showing loading indicator when adding users from user list.
  components/multiselect/multiselect.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2248 [MM-10346] CSRF Token Implementation (Wipe cookie on logout)
  actions/views/root.js
  components/login/login_controller/login_controller.jsx
  root.jsx
  utils/utils.jsx
Labels: 2: Dev Review

#2296 MM-13761 Properly request external image through proxy when viewed in preview modal
  components/post_view/post_body_additional_content/post_body_additional_content.jsx
  components/post_view/post_body_additional_content/post_body_additional_content.test.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2290 MM-13853 - Updating emoji picker bg
  sass/components/_emoticons.scss
Labels: 3: Ready to Merge

#2308 MM-13854 - Updating post textarea css
  sass/layout/_post.scss
Labels: 3: Ready to Merge, CherryPickApproved
