Repository mattermost/mattermost-webapp, pull requests merged in 2019-08, with the labels that each got.

#3291 [MM-17291] Show username for consecutive RHS comments, on mobile-browser view
  components/rhs_comment/rhs_comment.jsx
Labels: 3: Reviews Complete

#3324 Automated cherry pick of #3320
  components/admin_console/team_channel_settings/channel/details/channel_details.jsx
Labels: AutomatedCherryPick/Done

#3307 Hide post menu for deleted posts
  components/post_view/post_info/__snapshots__/post_info.test.jsx.snap
  components/post_view/post_info/post_info.test.jsx
  components/rhs_comment/__snapshots__/rhs_comment.test.jsx.snap
  components/rhs_comment/rhs_comment.jsx
  components/rhs_comment/rhs_comment.test.jsx
  components/rhs_root_post/__snapshots__/rhs_root_post.test.jsx.snap
  components/rhs_root_post/rhs_root_post.jsx
  components/rhs_root_post/rhs_root_post.test.jsx
  components/search_results_item/__snapshots__/search_results_item.test.jsx.snap
  components/search_results_item/search_results_item.jsx
  components/search_results_item/search_results_item.test.jsx
  utils/post_utils.jsx
Labels: 3: Reviews Complete, CherryPick/Approved

#3329 Automated cherry pick of #3307
  components/post_view/post_info/__snapshots__/post_info.test.jsx.snap
  components/post_view/post_info/post_info.test.jsx
  components/rhs_comment/__snapshots__/rhs_comment.test.jsx.snap
  components/rhs_comment/rhs_comment.jsx
  components/rhs_comment/rhs_comment.test.jsx
  components/rhs_root_post/__snapshots__/rhs_root_post.test.jsx.snap
  components/rhs_root_post/rhs_root_post.jsx
  components/rhs_root_post/rhs_root_post.test.jsx
  components/search_results_item/__snapshots__/search_results_item.test.jsx.snap
  components/search_results_item/search_results_item.jsx
  components/search_results_item/search_results_item.test.jsx
  utils/post_utils.jsx
Labels: AutomatedCherryPick/Done

#3299 MM-17393: Fix StartTLS and TLS strings.
  i18n/en.json
Labels: CherryPick/Approved

#3330 use sha1 instead of branch name
  .circleci/config.yml
Labels: 2: Dev Review

#3333 Automated cherry pick of #3330
  .circleci/config.yml
Labels: AutomatedCherryPick/Done

#3332 Automated cherry pick of #3330
  .circleci/config.yml
Labels: AutomatedCherryPick/Done

#3334 Automated cherry pick of #3330
  .circleci/config.yml
Labels: AutomatedCherryPick/Done

#3081 GH-11568 Adds cypress test for inserting emoji via keyboard input
  components/emoji_picker/components/emoji_picker_preview.jsx
  components/emoji_picker/emoji_picker.jsx
  e2e/cypress/integration/messaging/emoji_keyboard_entry_spec.js
Labels: 3: Reviews Complete

#3331 Automated cherry pick of #3299
  i18n/en.json
Labels: AutomatedCherryPick/Done

#3297 [MM-17019] Filter archived teams out of team membership selectors
  actions/global_actions.test.js
  components/permissions_gates/any_team_permission_gate/any_team_permission_gate.test.jsx
  package-lock.json
  package.json
Labels: 3: Reviews Complete

#3298 [MM-17019] Filter archived teams out of team membership selectors (release 5.14)
  actions/global_actions.test.js
  components/permissions_gates/any_team_permission_gate/any_team_permission_gate.test.jsx
  package-lock.json
  package.json
Labels: 3: Reviews Complete

#3335 MM-17429 - Updating post header css
  sass/layout/_post.scss
  sass/layout/_sidebar-right.scss
Labels: 2: Dev Review, 2: QA Review, CherryPick/Approved

#3321 [MM-16054] Accessibility fixes to buttons on Manage Members for channel
  components/channel_members_dropdown/__snapshots__/channel_members_dropdown.test.jsx.snap
  components/channel_members_dropdown/channel_members_dropdown.jsx
Labels: 3: Reviews Complete

#3337 Automated cherry pick of #3335
  sass/layout/_post.scss
  sass/layout/_sidebar-right.scss
Labels: AutomatedCherryPick/Done

#3327 MM-17294 - Revert "MM-15452 - Add ability to override LHS icon… (#3311)
  components/sidebar/sidebar_channel/index.js
  components/sidebar/sidebar_channel/sidebar_channel.jsx
  components/sidebar/sidebar_channel_button_or_link/sidebar_channel_button_or_link.jsx
  components/sidebar/sidebar_channel_button_or_link/sidebar_channel_button_or_link_icon.jsx
  package-lock.json
  package.json
  sass/layout/_sidebar-left.scss
  utils/utils.jsx
Labels: AutomatedCherryPick/Done

#3323 MM-17354 Fix for date line being cutoff when entering a channel with unreads
  components/post_view/post_list/post_list_virtualized.jsx
  components/post_view/post_list/post_list_virtualized.test.jsx
Labels: CherryPick/Approved

#3057 [MM-14593] Add password type for Interactive Dialogs
  components/interactive_dialog/dialog_element.test.jsx
  components/widgets/settings/text_setting.jsx
Labels: 3: Reviews Complete, Docs/Needed, Tests/Done

#3319 MM-17361 - Send messages on preview mode
  components/create_comment/__snapshots__/create_comment.test.jsx.snap
  components/create_comment/create_comment.jsx
  components/create_post/__snapshots__/create_post.test.jsx.snap
  components/create_post/create_post.jsx
  components/create_post/create_post.test.jsx
  components/edit_post_modal/__snapshots__/edit_post_modal.test.jsx.snap
  components/edit_post_modal/edit_post_modal.jsx
  components/textbox/textbox.jsx
  components/textbox/textbox_links.jsx
  sass/components/_modal.scss
  sass/layout/_forms.scss
  sass/layout/_post.scss
  utils/utils.jsx
Labels: 3: Reviews Complete, CherryPick/Approved

#3296 [MM-16042] Navigation fixes around profile picture settings
  components/__snapshots__/setting_picture.test.jsx.snap
  components/setting_picture.jsx
Labels: 2: Dev Review, CherryPick/Approved, Setup Cloud Test Server

#3348 Automated cherry pick of #3296
  components/__snapshots__/setting_picture.test.jsx.snap
  components/setting_picture.jsx
Labels: AutomatedCherryPick/Done

#3290 [MM-16723] Reworked post list reading to avoid duplicates
  components/post_view/post/index.js
  components/post_view/post/post.jsx
  components/post_view/post_list/index.js
  components/post_view/post_list/post_list.jsx
  components/post_view/post_list/post_list_virtualized.jsx
  components/post_view/post_list/post_list_virtualized.test.jsx
  utils/post_utils.jsx
Labels: 3: Reviews Complete, CherryPick/Approved

#3326 MM-17460 - Removing focus trap
  components/channel_header/__snapshots__/channel_header.test.jsx.snap
  components/channel_header/channel_header.js
  components/emoji_picker/emoji_picker_tabs.jsx
  components/widgets/menu/menu.jsx
  components/widgets/menu/menu.test.jsx
  components/widgets/menu/menu_wrapper.jsx
  package.json
Labels: 3: Reviews Complete, CherryPick/Approved

#3352 [MM-17490] Moved defaultAriaLabelRenderer up to multiselect.jsx
  components/add_groups_to_channel_modal/__snapshots__/add_groups_to_channel_modal.test.jsx.snap
  components/add_groups_to_team_modal/__snapshots__/add_groups_to_team_modal.test.jsx.snap
  components/channel_selector_modal/__snapshots__/channel_selector_modal.test.jsx.snap
  components/multiselect/__snapshots__/multiselect.test.jsx.snap
  components/multiselect/multiselect.jsx
  components/multiselect/multiselect_list.jsx
  components/team_selector_modal/__snapshots__/team_selector_modal.test.jsx.snap
Labels: 2: Dev Review, CherryPick/Approved, Setup Old Test Server

#3355 Automated cherry pick of #3352
  components/add_groups_to_channel_modal/__snapshots__/add_groups_to_channel_modal.test.jsx.snap
  components/add_groups_to_team_modal/__snapshots__/add_groups_to_team_modal.test.jsx.snap
  components/channel_selector_modal/__snapshots__/channel_selector_modal.test.jsx.snap
  components/multiselect/__snapshots__/multiselect.test.jsx.snap
  components/multiselect/multiselect.jsx
  components/multiselect/multiselect_list.jsx
  components/team_selector_modal/__snapshots__/team_selector_modal.test.jsx.snap
Labels: AutomatedCherryPick/Done

#3317 [MM-16727] Fix incorrect value comparison using an invalid user id reference
  components/admin_console/system_users/system_users_dropdown/system_users_dropdown.jsx
Labels: 3: Reviews Complete, Changelog/Not Needed, CherryPick/Approved, Docs/Not Needed

#3359 Automated cherry pick of #3317
  components/admin_console/system_users/system_users_dropdown/system_users_dropdown.jsx
Labels: AutomatedCherryPick/Done

#3349 Mm 17385 Error when switching to channel with too many unread posts
  components/post_view/post_list/__snapshots__/post_list.test.jsx.snap
  components/post_view/post_list/index.js
  components/post_view/post_list/post_list.jsx
  components/post_view/post_list/post_list.test.jsx
  package-lock.json
  package.json
Labels: 3: Reviews Complete, CherryPick/Approved

#3353 MM-17495 - Adding spinner instead of loading bars
  components/__snapshots__/pdf_preview.test.jsx.snap
  components/code_preview.jsx
  components/pdf_preview.jsx
  components/post_view/post_body/post_body.jsx
  components/widgets/loading/loading_bars.jsx
  components/widgets/loading/loading_bars.test.jsx
  images/load.gif
Labels: 3: Reviews Complete, CherryPick/Approved

#3067 Increase test coverage for UI Automation for Theme Colors - Color Picker
  components/__snapshots__/color_input.test.jsx.snap
  components/color_input.jsx
  components/color_input.test.jsx
  components/user_settings/display/user_settings_theme/__snapshots__/color_chooser.test.jsx.snap
  components/user_settings/display/user_settings_theme/__snapshots__/custom_theme_chooser.test.jsx.snap
  components/user_settings/display/user_settings_theme/color_chooser.jsx
  components/user_settings/display/user_settings_theme/custom_theme_chooser.jsx
  e2e/cypress/integration/account_settings/theme_color/custom_colors_sidebar_styles_spec.js
Labels: 2: Dev Review

#3361 Automated cherry pick of #3353
  components/__snapshots__/pdf_preview.test.jsx.snap
  components/code_preview.jsx
  components/pdf_preview.jsx
  components/post_view/post_body/post_body.jsx
  components/widgets/loading/loading_bars.jsx
  components/widgets/loading/loading_bars.test.jsx
  images/load.gif
Labels: AutomatedCherryPick/Done

#3238 Increasing test coverage for Focus Move
  e2e/cypress/integration/messaging/focus_move_spec.js
Labels: 2: Dev Review

#3137 [MM-16856] Remove no notification check
  components/admin_console/admin_definition.jsx
  components/user_settings/general/index.js
  components/user_settings/general/user_settings_general.jsx
  i18n/en.json
Labels: 3: Reviews Complete

#3246 [MM-17215] Show different channel not found message for guest
  components/error_page/__snapshots__/error_message.test.jsx.snap
  components/error_page/error_message.jsx
  components/error_page/error_page.jsx
  components/error_page/index.jsx
  i18n/en.json
Labels: 3: Reviews Complete

#3363 Update integration backstage titles to consistently use plural form
  components/integrations/integrations.jsx
  i18n/en.json
Labels: 3: Reviews Complete

#3367 Fix E2E for team spec
  components/invitation_modal/__snapshots__/invitation_modal.test.jsx.snap
  components/invitation_modal/__snapshots__/invitation_modal_members_step.test.jsx.snap
  components/invitation_modal/invitation_modal.jsx
  components/invitation_modal/invitation_modal_members_step.jsx
  components/main_menu/__snapshots__/main_menu.test.jsx.snap
  components/main_menu/main_menu.jsx
  e2e/cypress/integration/team/teams_spec.js
  plugins/test/__snapshots__/main_menu_action.test.jsx.snap
Labels: 3: Reviews Complete

#3303 Move Ukrainian from Beta to Alpha
  components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
  i18n/i18n.jsx
Labels: 3: Reviews Complete, CherryPick/Approved

#3369 Automated cherry pick of #3303
  components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
  i18n/i18n.jsx
Labels: AutomatedCherryPick/Done

#3336 Fixing text and adding a test covering that part
  components/select_team/__snapshots__/select_team.test.jsx.snap
  components/select_team/select_team.jsx
  components/select_team/select_team.test.jsx
  i18n/en.json
Labels: 3: Reviews Complete

#3325 Making minor modifications to the css around input fields and chips
  components/widgets/inputs/channels_input.scss
  components/widgets/inputs/users_emails_input.scss
Labels: 3: Reviews Complete, Setup Cloud Test Server, Tests/Not Needed

#3338 Invitation Confirmation Screen Tweaks
  components/invitation_modal/__snapshots__/invitation_modal_confirm_step_table.test.jsx.snap
  components/invitation_modal/invitation_modal_confirm_step.scss
  components/invitation_modal/invitation_modal_confirm_step_table.jsx
  components/invitation_modal/invitation_modal_confirm_step_table.scss
  components/widgets/modals/full_screen_modal.scss
Labels: 3: Reviews Complete

#3350 [MM-16723] Reworked post list reading to avoid duplicates (#3290) - cherry-pick
  components/post_view/post/index.js
  components/post_view/post/post.jsx
  components/post_view/post_list/index.js
  components/post_view/post_list/post_list.jsx
  components/post_view/post_list/post_list_virtualized.jsx
  components/post_view/post_list/post_list_virtualized.test.jsx
  utils/post_utils.jsx
Labels: CherryPick/Done

#3339 [MM-17074] Force focus to textbox on emoji picker toggle off
  components/create_comment/create_comment.jsx
  components/create_post/create_post.jsx
Labels: 3: Reviews Complete

#3351 MM-17482 - Updating account settings spacing
  components/user_settings/notifications/__snapshots__/desktop_notification_settings.test.jsx.snap
  components/user_settings/notifications/desktop_notification_settings.jsx
  components/user_settings/notifications/user_settings_notifications.jsx
Labels: 2: Dev Review, CherryPick/Approved

#3340 MM-17465 - Updating files scss
  components/__snapshots__/size_aware_image.test.jsx.snap
  components/size_aware_image.jsx
  components/size_aware_image.test.jsx
  sass/components/_files.scss
Labels: 2: Dev Review, CherryPick/Approved

#3373 Automated cherry pick of #3340
  components/__snapshots__/size_aware_image.test.jsx.snap
  components/size_aware_image.jsx
  components/size_aware_image.test.jsx
  sass/components/_files.scss
Labels: AutomatedCherryPick/Done

#3341 More reliable approach in copy link code
  components/invitation_modal/invitation_modal_members_step.jsx
Labels: 3: Reviews Complete

#3370 Changing translation key as suggested in PR #3336
  components/select_team/__snapshots__/select_team.test.jsx.snap
  components/select_team/select_team.jsx
  i18n/en.json
Labels: 3: Reviews Complete, Tests/Not Needed

#3362 MM-17517 Remove ambiguity on LDAP and SAML System Console help texts
  components/admin_console/admin_definition.jsx
  i18n/en.json
Labels: 3: Reviews Complete

#3372 Automated cherry pick of #3351
  components/user_settings/notifications/__snapshots__/desktop_notification_settings.test.jsx.snap
  components/user_settings/notifications/desktop_notification_settings.jsx
  components/user_settings/notifications/user_settings_notifications.jsx
Labels: AutomatedCherryPick/Done

#3378 Update NOTICE.txt
  NOTICE.txt
Labels: CherryPick/Approved

#3384 Automated cherry pick of #3378
  NOTICE.txt
Labels: AutomatedCherryPick/Done

#3371 Fix failing E2E
  e2e/cypress/fixtures/users.json
  e2e/cypress/integration/channel/system_message_spec.js
  e2e/cypress/support/ui_commands.js
Labels: 2: Dev Review

#3381 Updated cypress to 3.4.1
  e2e/package-lock.json
  e2e/package.json
Labels: 3: Reviews Complete

#3382 MM-17515 - Updating settings-min css
  components/__snapshots__/setting_item_min.test.jsx.snap
  components/setting_item_min.jsx
  sass/responsive/_mobile.scss
  sass/routes/_settings.scss
Labels: CherryPick/Approved

#3354 [MM-13837] Updated marked dependency
  package-lock.json
  package.json
  utils/markdown/link_only_renderer.test.jsx
Labels: 3: Reviews Complete

#3368 translations PR 20190805
  i18n/de.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 3: Reviews Complete

#3345 MM-17334: Better handling of counter of success/error invitation texts
  components/invitation_modal/__snapshots__/invitation_modal_confirm_step.test.jsx.snap
  components/invitation_modal/invitation_modal_confirm_step.jsx
  components/invitation_modal/invitation_modal_confirm_step.test.jsx
  i18n/en.json
Labels: 3: Reviews Complete

#3386 Automated cherry pick of #3382
  components/__snapshots__/setting_item_min.test.jsx.snap
  components/setting_item_min.jsx
  sass/responsive/_mobile.scss
  sass/routes/_settings.scss
Labels: AutomatedCherryPick/Done

#3390 MM-17595 - Updating status menu css
  components/team_general_tab/team_general_tab.jsx
  components/user_settings/general/user_settings_general.jsx
  i18n/en.json
  sass/components/_sidebar-header.scss
  sass/layout/_forms.scss
Labels: 1: PM Review, 3: Reviews Complete, CherryPick/Approved

#3392 Automated cherry pick of #3390
  components/team_general_tab/team_general_tab.jsx
  components/user_settings/general/user_settings_general.jsx
  i18n/en.json
  sass/components/_sidebar-header.scss
  sass/layout/_forms.scss
Labels: AutomatedCherryPick/Done

#3376 [MM-17551] Fixed so that team icon settings displays removal tooltip properly
  sass/routes/_settings.scss
Labels: 3: Reviews Complete, CherryPick/Approved

#3395 Automated cherry pick of #3376
  sass/routes/_settings.scss
Labels: AutomatedCherryPick/Done

#3394 MM-17602 Load statuses when opening channel member list from header
  actions/user_actions.jsx
  actions/user_actions.test.js
  components/popover_list_members/index.js
  components/popover_list_members/popover_list_members.jsx
  components/popover_list_members/popover_list_members.test.jsx
Labels: 3: Reviews Complete, CherryPick/Approved

#3398 Automated cherry pick of #3394
  actions/user_actions.jsx
  actions/user_actions.test.js
  components/popover_list_members/index.js
  components/popover_list_members/popover_list_members.jsx
  components/popover_list_members/popover_list_members.test.jsx
Labels: AutomatedCherryPick/Done

#3399 MM-17622 - Updating menu wrapper
  components/widgets/menu/menu_wrapper.jsx
Labels: CherryPick/Approved

#3391 MM-17600 - Updating file upload (setting picture)
  components/__snapshots__/setting_picture.test.jsx.snap
  components/setting_picture.jsx
Labels: CherryPick/Approved

#3383 MM-17552 - Preventing settings update on cancel
  components/__snapshots__/setting_item_max.test.jsx.snap
  components/setting_item_max.jsx
  components/setting_item_max.test.jsx
  components/user_settings/notifications/__snapshots__/manage_auto_responder.test.jsx.snap
  components/user_settings/notifications/email_notification_setting/__snapshots__/email_notification_setting.test.jsx.snap
Labels: 2: Dev Review, CherryPick/Approved

#3312 MM-16730: e2e test for replying to an older message
  components/post_view/commented_on/__snapshots__/commented_on.test.jsx.snap
  components/post_view/commented_on/commented_on.jsx
  components/single_image_view/__snapshots__/single_image_view.test.jsx.snap
  components/single_image_view/single_image_view.jsx
  e2e/cypress/integration/channel/message_reply_spec.js
  e2e/cypress/support/task_commands.js
Labels: 3: Reviews Complete

#3344 [MM-17094] Spacebar now activates add button when focused on multiselect
  components/multiselect/__snapshots__/multiselect.test.jsx.snap
  components/multiselect/multiselect.jsx
Labels: 3: Reviews Complete

#3403 Automated cherry pick of #3391
  components/__snapshots__/setting_picture.test.jsx.snap
  components/setting_picture.jsx
Labels: AutomatedCherryPick/Done

#3322 [MM-17441] Fix bug preventing CMD+~ to switch between open Safari windows
  utils/a11y_controller.js
Labels: 3: Reviews Complete, CherryPick/Approved

#3401 MM-17487 - Updating plugin dropdown alignment
  plugins/channel_header_plug/__snapshots__/channel_header_plug.test.jsx.snap
  plugins/channel_header_plug/channel_header_plug.jsx
Labels: CherryPick/Approved

#3406 Automated cherry pick of #3322
  utils/a11y_controller.js
Labels: AutomatedCherryPick/Done

#3404 Automated cherry pick of #3383
  components/__snapshots__/setting_item_max.test.jsx.snap
  components/setting_item_max.jsx
  components/setting_item_max.test.jsx
  components/user_settings/notifications/__snapshots__/manage_auto_responder.test.jsx.snap
  components/user_settings/notifications/email_notification_setting/__snapshots__/email_notification_setting.test.jsx.snap
Labels: AutomatedCherryPick/Done

#3402 Automated cherry pick of #3399
  components/widgets/menu/menu_wrapper.jsx
Labels: AutomatedCherryPick/Done

#3407 Automated cherry pick of #3401
  plugins/channel_header_plug/__snapshots__/channel_header_plug.test.jsx.snap
  plugins/channel_header_plug/channel_header_plug.jsx
Labels: AutomatedCherryPick/Done

#3342 Automated cherry pick of #3323
  components/post_view/post_list/post_list_virtualized.jsx
  components/post_view/post_list/post_list_virtualized.test.jsx
Labels: AutomatedCherryPick/Done

#3410 MM-17671 Permalink does not render posts in IE11
  components/post_view/post_list_ie/index.js
  components/post_view/post_list_ie/post_list_ie.jsx
Labels: 2: QA Review, 3: Reviews Complete, CherryPick/Approved

#3396 MM-17485 Fix for missing messages on socket reconn for channels visited only once preiously
  actions/views/channel.js
  actions/views/channel.test.js
Labels: 3: Reviews Complete, CherryPick/Approved

#3418 Automated cherry pick of #3396
  actions/views/channel.js
  actions/views/channel.test.js
Labels: AutomatedCherryPick/Done

#3417 Automated cherry pick of #3410
  components/post_view/post_list_ie/index.js
  components/post_view/post_list_ie/post_list_ie.jsx
Labels: AutomatedCherryPick/Done

#3374 Showing with correct colors fullname and nick name in invite users autocomplete
  components/widgets/inputs/users_emails_input.jsx
  components/widgets/inputs/users_emails_input.scss
  utils/utils.jsx
Labels: 3: Reviews Complete

#3415 MM-17672 - Updating flex css for header
  sass/layout/_headers.scss
Labels: 3: Reviews Complete, CherryPick/Approved

#3420 Automated cherry pick of #3415
  sass/layout/_headers.scss
Labels: AutomatedCherryPick/Done

#3343 Using tabSelectsValue and removing unnused component
  components/widgets/inputs/channels_input.jsx
  components/widgets/inputs/channels_input.test.jsx
  components/widgets/inputs/emails_input.jsx
  components/widgets/inputs/emails_input.scss
  components/widgets/inputs/emails_input.test.jsx
  components/widgets/inputs/users_emails_input.jsx
  components/widgets/inputs/users_emails_input.test.jsx
  i18n/en.json
Labels: 2: Dev Review

#3409 MM-17650 - Updating webhooks css
  sass/layout/_webhooks.scss
Labels: 1: PM Review, CherryPick/Approved

#3388 Fixing users autocomplete search in the guests invitation modal
  components/invitation_modal/invitation_modal_guests_step.jsx
Labels: 3: Reviews Complete

#3346 Showing correct text on MFA disabled/not-enforced on Guest accounts configuration
  components/admin_console/admin_definition.jsx
  i18n/en.json
Labels: 3: Reviews Complete

#3375 E2E: Rearrange custom color specs
  e2e/cypress/integration/account_settings/display/theme/custom_theme_color_picker_spec.js
  e2e/cypress/integration/account_settings/display/theme/custom_theme_sidebar_styles_spec.js
  e2e/cypress/integration/account_settings/display/theme/settings_view_spec.js
  e2e/cypress/integration/account_settings/theme_color/custom_colors_sidebar_styles_spec.js
Labels: 2: Dev Review

#3412 MM-17652 - Very long email addresses overlap with Role column on LDAP group sync warning modal
  components/admin_console/team_channel_settings/group/__snapshots__/group_users.test.jsx.snap
  components/admin_console/team_channel_settings/group/__snapshots__/group_users_row.test.jsx.snap
  components/admin_console/team_channel_settings/group/group_users.jsx
  components/admin_console/team_channel_settings/group/group_users_row.jsx
  sass/components/_groups.scss
Labels: 2: Dev Review

#3421 MM-17690 - Updating language select functionality
  components/user_settings/display/manage_languages/manage_languages.jsx
  sass/components/_modal.scss
Labels: 1: PM Review, 2: Dev Review, CherryPick/Approved

#3428 Automated cherry pick of #3421
  components/user_settings/display/manage_languages/manage_languages.jsx
  sass/components/_modal.scss
Labels: AutomatedCherryPick/Done

#3385 MM-17686 - Adjusting auto focus for settings section on expand
  components/__snapshots__/setting_item_max.test.jsx.snap
  components/__snapshots__/setting_picture.test.jsx.snap
  components/setting_item_max.jsx
  components/setting_picture.jsx
  components/user_settings/display/user_settings_theme/user_settings_theme.jsx
  components/user_settings/notifications/__snapshots__/manage_auto_responder.test.jsx.snap
  components/user_settings/notifications/email_notification_setting/__snapshots__/email_notification_setting.test.jsx.snap
Labels: 3: Reviews Complete, CherryPick/Approved

#3430 Automated cherry pick of #3385
  components/__snapshots__/setting_item_max.test.jsx.snap
  components/__snapshots__/setting_picture.test.jsx.snap
  components/setting_item_max.jsx
  components/setting_picture.jsx
  components/user_settings/display/user_settings_theme/user_settings_theme.jsx
  components/user_settings/notifications/__snapshots__/manage_auto_responder.test.jsx.snap
  components/user_settings/notifications/email_notification_setting/__snapshots__/email_notification_setting.test.jsx.snap
Labels: AutomatedCherryPick/Done

#3422 MM-17691 - Updating picture component
  components/__snapshots__/setting_picture.test.jsx.snap
  components/setting_picture.jsx
Labels: CherryPick/Approved

#3405 MM-17119: Updates LDAP id attribute config help text to outline optio…
  Makefile
  components/admin_console/admin_definition.jsx
  i18n/en.json
Labels: 3: Reviews Complete

#3387 Fixing strange behavior on blur
  components/widgets/inputs/channels_input.scss
  components/widgets/inputs/users_emails_input.scss
Labels: 3: Reviews Complete

#3393 Lower cases some words in translation.
  i18n/en.json
Labels: 2: Dev Review

#3397 Guest Badges - Sizes and Placements
  components/invitation_modal/invitation_modal_confirm_step_row.scss
  components/widgets/badges/badge.scss
  components/widgets/inputs/users_emails_input.scss
Labels: 3: Reviews Complete

#3433 Fix cypress report by escaping characters on title
  e2e/run_tests.js
Labels: 3: Reviews Complete

#3416 [MM-17569] Added assets for unsupported browser page
  images/browser-icons/chrome.png
  images/browser-icons/edge.png
  images/browser-icons/firefox.png
  images/browser-icons/mac.png
  images/browser-icons/safari.png
  images/browser-icons/windows.png
  webpack.config.js
Labels: 2: QA Review

#3439 MM-17749 - Updating channel header modal links
  components/edit_channel_header_modal/__snapshots__/edit_channel_header_modal.test.jsx.snap
  components/edit_channel_header_modal/edit_channel_header_modal.jsx
Labels: 2: Dev Review, CherryPick/Approved

#3426 Automated cherry pick of #3409
  sass/layout/_webhooks.scss
Labels: AutomatedCherryPick/Done

#3358 [MM-17213] Change text for team domain restrictions
  components/admin_console/admin_definition.jsx
  i18n/en.json
Labels: 3: Reviews Complete

#3441 Automated cherry pick of #3439
  components/edit_channel_header_modal/__snapshots__/edit_channel_header_modal.test.jsx.snap
  components/edit_channel_header_modal/edit_channel_header_modal.jsx
Labels: AutomatedCherryPick/Done

#3431 Automated cherry pick of #3422
  components/__snapshots__/setting_picture.test.jsx.snap
  components/setting_picture.jsx
Labels: AutomatedCherryPick/Done

#3424 translations PR 20190812
  i18n/de.json
  i18n/es.json
  i18n/fr.json
  i18n/ja.json
  i18n/ko.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 3: Reviews Complete

#3435 MM-17760 - Updating flex css in header
  sass/layout/_headers.scss
Labels: 3: Reviews Complete, CherryPick/Approved

#3434 [MM-17657] Removed unnecessary focus call on component update
  components/searchable_user_list/searchable_user_list.jsx
Labels: 3: Reviews Complete, CherryPick/Approved

#3443 [MM-17603] Added null check to label generator on suggestion list
  components/suggestion/search_suggestion_list.jsx
Labels: 3: Reviews Complete, CherryPick/Approved, Tests/Not Needed

#3445 [MM-17799] Remove "install plugin by url" component from admin console
  components/admin_console/plugin_management/__snapshots__/plugin_management.test.jsx.snap
  components/admin_console/plugin_management/plugin_management.jsx
  components/admin_console/plugin_management/plugin_management.test.jsx
  i18n/en.json
Labels: 3: Reviews Complete, CherryPick/Approved

#3454 Updated unsupported browser icons to SVGs
  images/browser-icons/chrome.png
  images/browser-icons/chrome.svg
  images/browser-icons/edge.png
  images/browser-icons/edge.svg
  images/browser-icons/firefox.png
  images/browser-icons/firefox.svg
  images/browser-icons/mac.png
  images/browser-icons/safari.png
  images/browser-icons/safari.svg
  images/browser-icons/windows.png
  images/browser-icons/windows.svg
Labels: 2: Dev Review, 2: QA Review

#3452 Automated cherry pick of #3445
  components/admin_console/plugin_management/__snapshots__/plugin_management.test.jsx.snap
  components/admin_console/plugin_management/plugin_management.jsx
  components/admin_console/plugin_management/plugin_management.test.jsx
  i18n/en.json
Labels: AutomatedCherryPick/Done

#3438 MM-17788, MM-17656 - Updating images css
  sass/components/_files.scss
Labels: 3: Reviews Complete, CherryPick/Approved

#3455 Automated cherry pick of #3438
  sass/components/_files.scss
Labels: AutomatedCherryPick/Done

#3276 [MM-17374] Add user id label to user detail page in system console
  components/admin_console/admin_user_card/__snapshots__/admin_user_card.test.jsx.snap
  components/admin_console/admin_user_card/admin_user_card.jsx
  components/admin_console/admin_user_card/admin_user_card.scss
  i18n/en.json
Labels: 1: PM Review, 2: Dev Review, Setup Cloud Test Server

#3451 Automated cherry pick of #3434
  components/searchable_user_list/searchable_user_list.jsx
Labels: AutomatedCherryPick/Done

#3442 Moving divider hidding logic from css to javascript
  components/widgets/menu/menu.jsx
  components/widgets/menu/menu.test.jsx
  sass/widgets/menu/_menu_group.scss
Labels: 3: Reviews Complete

#3389 Allowing to search by email properly
  components/invitation_modal/invitation_modal_guests_step.jsx
  components/invitation_modal/invitation_modal_members_step.jsx
  components/widgets/inputs/users_emails_input.jsx
Labels: 3: Reviews Complete

#3450 MM-17805: Only adds history entry to select team if there's a current…
  actions/global_actions.jsx
Labels: 2: Dev Review, CherryPick/Approved

#3440 More robust menu animation for safari
  components/widgets/menu/menu_wrapper_animation.jsx
  sass/widgets/menu/_menu.scss
  sass/widgets/menu/_menu_wrapper.scss
Labels: 2: Dev Review

#3458 Automated cherry pick of #3450
  actions/global_actions.jsx
Labels: AutomatedCherryPick/Done

#3436 MM-17619 Fix for scroll correction issue in Edge
  components/post_view/post_list/post_list_virtualized.jsx
  components/post_view/post_list/post_list_virtualized.test.jsx
Labels: 3: Reviews Complete, CherryPick/Approved

#3365 Fixing roles update on team member roles updates
  actions/websocket_actions.jsx
Labels: 2: Dev Review

#3461 Minor accessibility fixes
  components/channel_header/__snapshots__/channel_header.test.jsx.snap
  components/channel_header/channel_header.js
  components/create_comment/__snapshots__/create_comment.test.jsx.snap
  components/create_comment/create_comment.jsx
  components/create_post/__snapshots__/create_post.test.jsx.snap
  components/create_post/create_post.jsx
  components/local_date_time/local_date_time.jsx
  components/post_view/post/post.jsx
  components/post_view/post_time/post_time.jsx
  components/rhs_comment/__snapshots__/rhs_comment.test.jsx.snap
  components/rhs_comment/rhs_comment.jsx
  components/rhs_root_post/__snapshots__/rhs_root_post.test.jsx.snap
  components/rhs_root_post/rhs_root_post.jsx
  components/rhs_thread/rhs_thread.jsx
  components/search_results_item/__snapshots__/search_results_item.test.jsx.snap
  components/search_results_item/search_results_item.jsx
  components/sidebar/header/sidebar_header.jsx
Labels: CherryPick/Approved

#3462 Automated cherry pick of #3461
  components/channel_header/__snapshots__/channel_header.test.jsx.snap
  components/channel_header/channel_header.js
  components/create_comment/__snapshots__/create_comment.test.jsx.snap
  components/create_comment/create_comment.jsx
  components/create_post/__snapshots__/create_post.test.jsx.snap
  components/create_post/create_post.jsx
  components/local_date_time/local_date_time.jsx
  components/post_view/post/post.jsx
  components/post_view/post_time/post_time.jsx
  components/rhs_comment/__snapshots__/rhs_comment.test.jsx.snap
  components/rhs_comment/rhs_comment.jsx
  components/rhs_root_post/__snapshots__/rhs_root_post.test.jsx.snap
  components/rhs_root_post/rhs_root_post.jsx
  components/rhs_thread/rhs_thread.jsx
  components/search_results_item/__snapshots__/search_results_item.test.jsx.snap
  components/search_results_item/search_results_item.jsx
  components/sidebar/header/sidebar_header.jsx
Labels: AutomatedCherryPick/Done

#3463 MM-17780 Fix for scroll position wrong at times when opening channel
  package-lock.json
  package.json
Labels: 2: Dev Review, CherryPick/Approved

#3459 [MM-17539] User is unable to send messages again if the user flags a deleted post on RHS
  components/rhs_root_post/__snapshots__/rhs_root_post.test.jsx.snap
  components/rhs_root_post/rhs_root_post.jsx
  components/rhs_root_post/rhs_root_post.test.jsx
Labels: 2: Dev Review, CherryPick/Approved

#3456 MM-17806 - Updating emoji reactions wrap
  sass/layout/_post.scss
Labels: 1: PM Review, 3: Reviews Complete, CherryPick/Approved

#3465 Automated cherry pick of #3456
  sass/layout/_post.scss
Labels: AutomatedCherryPick/Done

#3466 udpate snapshots
  components/rhs_root_post/__snapshots__/rhs_root_post.test.jsx.snap
Labels: 3: Reviews Complete

#3464 Automated cherry pick of #3459
  components/rhs_root_post/__snapshots__/rhs_root_post.test.jsx.snap
  components/rhs_root_post/rhs_root_post.jsx
  components/rhs_root_post/rhs_root_post.test.jsx
Labels: AutomatedCherryPick/Done

#3379 MM-17452 E2E: Focus does not move when it has already been set elsewhere
  e2e/cypress/integration/messaging/focus_move_spec.js
Labels: 3: Reviews Complete

#3449 [MM-17390] Rate limited posts fail to load threads
  actions/websocket_actions.jsx
  actions/websocket_actions.test.jsx
  package-lock.json
  package.json
Labels: 3: Reviews Complete

#3380 [MM-17440] SVG attachments bleed over into subsequent posts
  components/single_image_view/__snapshots__/single_image_view.test.jsx.snap
  components/single_image_view/single_image_view.jsx
Labels: 1: PM Review, 2: QA Review

#3477 [MM-17085] Add more interactive dialog tests
  e2e/cypress/integration/interactive_dialog/full_dialog_spec.js
  e2e/utils/webhook_utils.js
Labels: 2: Dev Review

#3469 MM-15887 E2E for interactive menu for long option
  components/widgets/settings/autocomplete_selector.jsx
  components/widgets/settings/autocomplete_selector.test.jsx
  e2e/cypress/integration/interactive_menu/basic_options_spec.js
Labels: 3: Reviews Complete

#2333 [MM-8421] Fix tiff preview - webapp
  utils/constants.jsx
Labels: 3: Reviews Complete

#3414 [MM-17446] Emojis to markdown.
  e2e/cypress/integration/messaging/emoji_to_markdown_spec.js
Labels: 3: Reviews Complete

#3483 [MM-15574] Create the read-only elements of “Team and Channel Membership” component
  actions/admin_actions.jsx
  components/__snapshots__/profile_picture.test.jsx.snap
  components/admin_console/admin_user_card/__snapshots__/admin_user_card.test.jsx.snap
  components/admin_console/admin_user_card/admin_user_card.jsx
  components/admin_console/admin_user_card/admin_user_card.scss
  components/admin_console/system_user_detail/__snapshots__/system_user_detail.test.jsx.snap
  components/admin_console/system_user_detail/system_user_detail.jsx
  components/admin_console/system_user_detail/system_user_detail.scss
  components/admin_console/system_user_detail/team_list/__snapshots__/abstract_list.test.jsx.snap
  components/admin_console/system_user_detail/team_list/__snapshots__/team_list.test.jsx.snap
  components/admin_console/system_user_detail/team_list/abstract_list.jsx
  components/admin_console/system_user_detail/team_list/abstract_list.test.jsx
  components/admin_console/system_user_detail/team_list/index.js
  components/admin_console/system_user_detail/team_list/team_image.jsx
  components/admin_console/system_user_detail/team_list/team_list.jsx
  components/admin_console/system_user_detail/team_list/team_list.test.jsx
  components/admin_console/system_user_detail/team_list/team_row.jsx
  components/more_direct_channels/__snapshots__/more_direct_channels.test.jsx.snap
  components/profile_picture.jsx
  components/profile_picture.scss
  components/user_list_row_with_error/user_list_row_with_error.jsx
  i18n/en.json
  sass/components/_status-icon.scss
Labels: 2: QA Review

#3460 Update E2E tests
  e2e/cypress/integration/channel/message_reply_spec.js
  e2e/cypress/integration/channel/message_spec.js
  e2e/cypress/integration/login/login_spec.js
  e2e/cypress/integration/login/subpath_login_spec.js
  e2e/cypress/integration/markdown/markdown_image_spec.js
  e2e/cypress/integration/messaging/emoji_keyboard_entry_spec.js
  e2e/cypress/integration/team/teams_spec.js
  e2e/cypress/support/ui_commands.js
Labels: 2: Dev Review

#3484 translations PR 20190819
  i18n/de.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 3: Reviews Complete

#3364 MM-15989 - Making members popover accessible
  components/popover_list_members/__snapshots__/popover_list_members.test.jsx.snap
  components/popover_list_members/popover_list_members.jsx
  components/popover_list_members/popover_list_members_item.jsx
  components/svg/message_icon.jsx
  i18n/en.json
  sass/components/_popover.scss
  utils/utils.jsx
Labels: 3: Reviews Complete, CherryPick/Approved

#3486 Updating fix for post area
  components/create_comment/__snapshots__/create_comment.test.jsx.snap
  components/create_comment/create_comment.jsx
  components/create_post/__snapshots__/create_post.test.jsx.snap
  components/create_post/create_post.jsx
Labels: 2: Dev Review, CherryPick/Candidate, Setup Cloud Test Server

#3419 Improving autocompletion for users and channels
  components/invitation_modal/__snapshots__/invitation_modal_confirm_step_row.test.jsx.snap
  components/invitation_modal/invitation_modal.jsx
  components/invitation_modal/invitation_modal_confirm_step_row.jsx
  components/invitation_modal/invitation_modal_confirm_step_row.scss
  components/invitation_modal/invitation_modal_confirm_step_row.test.jsx
  components/invitation_modal/invitation_modal_confirm_step_table.jsx
  components/invitation_modal/invitation_modal_guests_step.jsx
  components/invitation_modal/invitation_modal_members_step.jsx
  components/svg/alert_icon.jsx
  components/widgets/inputs/channels_input.jsx
  components/widgets/inputs/channels_input.scss
  components/widgets/inputs/channels_input.test.jsx
  components/widgets/inputs/users_emails_input.jsx
  components/widgets/inputs/users_emails_input.scss
  components/widgets/inputs/users_emails_input.test.jsx
  i18n/en.json
Labels: 3: Reviews Complete

#3408 Showing correct messages for guests when they are members of the team
  actions/invite_actions.jsx
  actions/invite_actions.test.js
Labels: 3: Reviews Complete

#3360 Wrapping the emails on invitation confirm step if needed
  components/invitation_modal/__snapshots__/invitation_modal_confirm_step_row.test.jsx.snap
  components/invitation_modal/invitation_modal_confirm_step_row.jsx
  components/invitation_modal/invitation_modal_confirm_step_row.scss
Labels: 3: Reviews Complete

#3494 Updating redux hash
  package-lock.json
  package.json
Labels: 3: Reviews Complete
