Repository mattermost/mattermost-webapp, pull requests merged in 2019-03, with the labels that each got.

#2406 [MM-14081] Remove checkMFA invocations and replace with error-based MFA handling
  actions/views/mfa.js
  actions/views/mfa.test.js
  components/claim/claim_controller.jsx
  components/claim/components/email_to_ldap.jsx
  components/claim/components/email_to_oauth.jsx
  components/claim/components/ldap_to_email.jsx
  components/claim/components/ldap_to_email.test.js
  components/claim/index.js
  components/login/login_controller/index.js
  components/login/login_controller/login_controller.jsx
  components/login/login_controller/login_controller.test.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2420 [MM-13824] add one_you strings for better translatability
  components/post_view/combined_system_message/combined_system_message.jsx
  i18n/en.json
Labels: 2: Dev Review, Hackfest

#2423 [MM-14278] Display same recent emoji only once
  actions/emoji_actions.jsx
  components/emoji_picker/emoji_picker.jsx
Labels: 3: Ready to Merge

#2417 MM-13126: Adds back arrow to group configuration view.
  components/admin_console/group_settings/group_details/__snapshots__/group_details.test.jsx.snap
  components/admin_console/group_settings/group_details/group_details.jsx
Labels: 2: Dev Review

#2440 Update NOTICE.txt
  NOTICE.txt
Labels: 3: Ready to Merge

#2432 MM-14210 Updating dependancies.
  components/admin_console/request_button/__snapshots__/request_button.test.jsx.snap
  components/create_comment/create_comment.test.jsx
  components/file_attachment/__snapshots__/file_attachment.test.jsx.snap
  components/select_team/components/__snapshots__/select_team_item.test.jsx.snap
  package-lock.json
  package.json
Labels: 2: Dev Review

#2431 [MM-14296] Fix default email notification interval from never to immediate
  components/user_settings/notifications/email_notification_setting/index.js
Labels: 3: Ready to Merge, CherryPickApproved

#2427 fix for UnhandledPromiseRejectionWarning in test
  components/user_settings/security/user_settings_security.test.js
Labels: 3: Ready to Merge, Hackfest

#2448 [MM-13800] Fix adding emoji to recent list when reacting to a post
  components/post_view/reaction_list/index.js
Labels: 2: Dev Review, CherryPickApproved

#2386 [MM-9622] Allow plugins to create link tooltips
  components/link_tooltip/__snapshots__/link_tooltip.test.jsx.snap
  components/link_tooltip/link_tooltip.jsx
  components/link_tooltip/link_tooltip.test.jsx
  components/markdown/markdown.jsx
  components/post_markdown/index.js
  components/post_markdown/post_markdown.jsx
  package.json
  plugins/registry.js
  utils/__snapshots__/message_html_to_component.test.jsx.snap
  utils/message_html_to_component.jsx
  utils/message_html_to_component.test.jsx
Labels: 3: Ready to Merge, Hackfest

#2443 Promote Polish from Alpha to Beta
  components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
  i18n/i18n.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2436 All routes and menus generated using admin definitions
  components/admin_console/__snapshots__/admin_console.test.jsx.snap
  components/admin_console/admin_console.jsx
  components/admin_console/admin_console.test.jsx
  components/admin_console/admin_definition.jsx
  components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.jsx.snap
  components/admin_console/admin_sidebar/admin_sidebar.jsx
  components/admin_console/admin_sidebar/admin_sidebar.test.jsx
  components/admin_console/schema_admin_settings.jsx
Labels: 3: Ready to Merge

#2452 Fixing ldap groups route in the admin console autogenerated routes
  components/admin_console/admin_definition.jsx
Labels: 3: Ready to Merge

#2451 MM-13604 timezone for post dates
  components/local_date_time/local_date_time.jsx
  components/local_date_time/local_date_time.test.jsx
  components/post_view/__snapshots__/date_separator.test.jsx.snap
  components/post_view/date_separator.test.jsx
  components/post_view/date_separator/__snapshots__/date_separator.test.jsx.snap
  components/post_view/date_separator/date_separator.jsx
  components/post_view/date_separator/date_separator.test.jsx
  components/post_view/date_separator/index.js
  components/post_view/post_list.jsx
  components/rhs_thread/rhs_thread.jsx
  components/search_results_item/__snapshots__/search_results_item.test.jsx.snap
  components/search_results_item/search_results_item.jsx
  package.json
Labels: 2: Dev Review

#2460 [MM-13863] Fix unnecessary sorting of channels recency on reaction to a post
  package-lock.json
  package.json
Labels: 3: Ready to Merge

#2446 [MM-13694] Modify helper text of SiteName config field to specify the default value
  components/admin_console/admin_definition.jsx
  i18n/en.json
  i18n/ko.json
Labels: 3: Ready to Merge

#2457 MM-14297 Match DM sidebar and channel switcher visibility check
  components/suggestion/switch_channel_provider.jsx
  package-lock.json
  package.json
Labels: 3: Ready to Merge

#2339 Using new splited emojis and webhooks permissions
  components/admin_console/permission_schemes_settings/permission_schemes_settings.jsx
  components/admin_console/permission_schemes_settings/permissions_tree/__snapshots__/permissions_tree.test.jsx.snap
  components/admin_console/permission_schemes_settings/permissions_tree/permissions_tree.jsx
  components/backstage/backstage_controller.jsx
  components/backstage/components/backstage_sidebar.jsx
  components/backstage/index.js
  components/emoji/emoji_list_item/emoji_list_item.jsx
  components/emoji/emoji_page.jsx
  components/integrations/installed_incoming_webhooks/index.js
  components/integrations/installed_outgoing_webhooks/index.js
  components/integrations/integrations.jsx
  components/main_menu/__snapshots__/main_menu.test.jsx.snap
  components/main_menu/index.jsx
  components/main_menu/main_menu.jsx
  components/main_menu/main_menu.test.jsx
  i18n/en.json
  plugins/test/__snapshots__/main_menu_action.test.jsx.snap
  plugins/test/main_menu_action.test.jsx
  utils/constants.jsx
  utils/policy_roles_adapter.js
  utils/policy_roles_adapter.test.jsx
Labels: 3: Ready to Merge, Awaiting PR

#2437 [MM-14283] Added E2E test for compact message display
  components/post_view/post_message_view/__snapshots__/post_message_view.test.jsx.snap
  components/post_view/post_message_view/post_message_view.jsx
  cypress/fixtures/users.json
  cypress/integration/account_settings/display/message_display_mode_spec.js
  cypress/support/commands.js
Labels: 3: Ready to Merge

#2453 Fix for wrong click handler.
  components/admin_console/group_settings/group_details/group_details.jsx
Labels: 3: Ready to Merge

#2419 MM-13952: Small style and text changes.
  components/admin_console/group_settings/group_details/__snapshots__/group_details.test.jsx.snap
  components/admin_console/group_settings/group_details/group_details.jsx
  components/admin_console/group_settings/groups_list/__snapshots__/groups_list.test.jsx.snap
  components/admin_console/group_settings/groups_list/groups_list.jsx
  i18n/en.json
  sass/components/_groups.scss
Labels: 2: Dev Review, Setup Test Server

#2363 Enable to highlight CJK mention key
  utils/text_formatting.jsx
  utils/text_formatting_mention_highlighting.test.jsx
Labels: 3: Ready to Merge, Hackfest

#2334 MM-13099 Use size_aware_image component for when loading images in posts
  components/post_view/message_attachments/message_attachment/__snapshots__/message_attachment.test.jsx.snap
  components/post_view/message_attachments/message_attachment/message_attachment.jsx
  components/post_view/post_attachment_opengraph/__snapshots__/post_attachment_opengraph.test.js.snap
  components/post_view/post_attachment_opengraph/post_attachment_opengraph.jsx
  components/post_view/post_attachment_opengraph/post_attachment_opengraph.test.js
  components/post_view/post_image/post_image.jsx
  components/post_view/post_message_view/__snapshots__/post_message_view.test.jsx.snap
  components/post_view/post_message_view/post_message_view.jsx
  components/single_image_view/__snapshots__/single_image_view.test.jsx.snap
  components/single_image_view/single_image_view.jsx
  components/single_image_view/single_image_view.test.jsx
  components/size_aware_image.jsx
  components/size_aware_image.test.jsx
  plugins/test/__snapshots__/post_type.test.jsx.snap
  sass/components/_files.scss
  utils/file_utils.jsx
  utils/file_utils.test.jsx
Labels: 2: Dev Review

#2411 MM-13958/MM-13959 Make postsInChannel into a sparse array
  actions/post_actions.jsx
  actions/post_actions.test.js
  actions/post_utils.js
  actions/post_utils.test.js
  actions/status_actions.jsx
  actions/status_actions.test.js
  actions/views/channel.js
  actions/views/channel.test.js
  actions/views/create_comment.jsx
  actions/views/create_comment.test.jsx
  components/create_post/create_post.jsx
  components/create_post/index.js
  components/post_view/index.js
  components/post_view/post_list.jsx
  package-lock.json
  package.json
Labels: 3: Ready to Merge

#2450 [MM-14321] Add e2e test for show more/less on long post
  components/post_view/show_more/__snapshots__/show_more.test.jsx.snap
  components/post_view/show_more/show_more.jsx
  cypress/fixtures/longMarkdownPost.html
  cypress/fixtures/longMarkdownPost.md
  cypress/integration/channel/collapsed_message_spec.js
Labels: 3: Ready to Merge

#2467 MM-14334 Allow plugin setting help text to contain Markdown
  components/admin_console/__snapshots__/help_text.test.jsx.snap
  components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
  components/admin_console/custom_plugin_settings/__snapshots__/custom_plugin_settings.test.jsx.snap
  components/admin_console/help_text.jsx
  components/admin_console/help_text.test.jsx
  components/admin_console/schema_admin_settings.jsx
Labels: 3: Ready to Merge

#2475 MM-14485 - Updating z-index for expand icon
  sass/layout/_post.scss
Labels: 3: Ready to Merge, CherryPickApproved

#2462 MM-14481: Do not show edit or delete in archived channels
  components/dot_menu/dot_menu.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2428 Fixing group channels header on narrow browser window
  sass/layout/_headers.scss
Labels: 3: Ready to Merge

#2477 Fix desktop-app dots menu openUp
  components/dot_menu/dot_menu.jsx
Labels: 3: Ready to Merge

#2470 MM-14440: localize on render, not in default props
  components/__snapshots__/save_button.test.jsx.snap
  components/__snapshots__/setting_item_max.test.jsx.snap
  components/admin_console/__snapshots__/message_export_settings.test.jsx.snap
  components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
  components/admin_console/custom_plugin_settings/__snapshots__/custom_plugin_settings.test.jsx.snap
  components/admin_console/custom_terms_of_service_settings/__snapshots__/custom_terms_of_service_settings.test.jsx.snap
  components/admin_console/permission_schemes_settings/permission_system_scheme_settings/__snapshots__/permission_system_scheme_settings.test.jsx.snap
  components/admin_console/permission_schemes_settings/permission_team_scheme_settings/__snapshots__/permission_team_scheme_settings.test.jsx.snap
  components/admin_console/plugin_management/__snapshots__/plugin_management.test.jsx.snap
  components/multiselect/__snapshots__/multiselect.test.jsx.snap
  components/save_button.jsx
  components/save_button.test.jsx
  components/user_settings/notifications/__snapshots__/manage_auto_responder.test.jsx.snap
  components/user_settings/notifications/email_notification_setting/__snapshots__/email_notification_setting.test.jsx.snap
Labels: 3: Ready to Merge, CherryPickApproved

#2480 [MM-14142] Add recent emoji to local storage every time a user adds emoji or reaction
  actions/emoji_actions.jsx
  actions/global_actions.jsx
  actions/local_storage.jsx
  components/logged_in/logged_in.jsx
  package.json
  selectors/emojis.js
  selectors/emojis.test.js
  stores/local_storage_store.jsx
  stores/local_storage_store.test.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2473 MM-14457 - Updating search “x” icon on mobile
  sass/responsive/_mobile.scss
Labels: 3: Ready to Merge, CherryPickApproved

#2476 [MM-14191] Render emojis in Interactive Message Buttons
  components/post_view/message_attachments/__snapshots__/action_button.test.jsx.snap
  components/post_view/message_attachments/action_button.jsx
  components/post_view/message_attachments/action_button.test.jsx
Labels: 3: Ready to Merge

#2464 MM-13741 Load user after setting up MFA on login or sign up
  actions/global_actions.jsx
  components/mfa/confirm.jsx
  components/mfa/confirm.test.jsx
Labels: 2: Dev Review

#2429 MM-13186: Adds a confirmation modal when removing team or channel association from group.
  components/admin_console/group_settings/group_details/__snapshots__/group_teams_and_channels_row.test.jsx.snap
  components/admin_console/group_settings/group_details/group_teams_and_channels_row.jsx
  components/admin_console/group_settings/group_details/group_teams_and_channels_row.test.jsx
  components/admin_console/permission_schemes_settings/permission_system_scheme_settings/__snapshots__/permission_system_scheme_settings.test.jsx.snap
  components/admin_console/permission_schemes_settings/permission_system_scheme_settings/permission_system_scheme_settings.jsx
  components/admin_console/permission_schemes_settings/permission_system_scheme_settings/permission_system_scheme_settings.test.jsx
  components/confirm_modal.jsx
  i18n/en.json
Labels: 3: Ready to Merge, Setup Test Server

#2468 MM-14415: Removes 'can_leave' field.
  components/admin_console/group_settings/group_details/group_details.jsx
  components/admin_console/group_settings/group_details/group_details.test.jsx
Labels: 3: Ready to Merge

#2471 MM-1447: check post?.metadata?.files, not just metadata
  components/file_attachment_list/index.js
  package-lock.json
  package.json
Labels: 3: Ready to Merge, Awaiting PR, CherryPickApproved

#2488 [MM-14354] Fixes multi_select component for removing items
  components/multiselect/multiselect.jsx
Labels: 2: Dev Review

#2474 MM-14343 - Updating settings nav on mobile
  sass/responsive/_mobile.scss
Labels: 3: Ready to Merge, CherryPickApproved

#2498 MM-14486 - Updating image/link previews size
  sass/components/_files.scss
  sass/components/_videos.scss
  sass/responsive/_mobile.scss
Labels: 3: Ready to Merge

#2487 [MM-13950] Prevents loading the URL of data images
  components/view_image/view_image.jsx
Labels: 3: Ready to Merge

#2491 [MM-13326] Added e2e test for checking message bullet text sizes
  cypress/integration/channel/message_bullets_spec.js
Labels: 2: Dev Review

#2489 [MM-14527] Fix default behavior when enabling/disabling email batching
  components/user_settings/notifications/email_notification_setting/email_notification_setting.jsx
  components/user_settings/notifications/email_notification_setting/email_notification_setting.test.jsx
  components/user_settings/notifications/email_notification_setting/index.js
  package-lock.json
  package.json
Labels: 2: Dev Review, Awaiting PR, CherryPickApproved

#2492 [MM-14298] Render message preview with single line break similar to when it gets posted
  components/textbox/textbox.jsx
  sass/layout/_post.scss
Labels: 2: Dev Review

#2479 [MM-14432] add E2E show autocomplete in each channel
  cypress/integration/channel/autocomplete_shown_each_channel_spec.js
  cypress/support/commands.js
Labels: 3: Ready to Merge

#2481 [MM-14319] E2E Code Theme Settings
  components/user_settings/display/user_settings_theme/__snapshots__/custom_theme_chooser.test.jsx.snap
  components/user_settings/display/user_settings_theme/custom_theme_chooser.jsx
  components/user_settings/display/user_settings_theme/premade_theme_chooser/premade_theme_chooser.jsx
  cypress/integration/account_settings/display/code_theme_colors_spec.js
Labels: 2: Dev Review

#2454 MM-4138_sidebarStyles
  components/user_settings/display/user_settings_theme/__snapshots__/custom_theme_chooser.test.jsx.snap
  components/user_settings/display/user_settings_theme/custom_theme_chooser.jsx
  cypress/integration/account_settings/theme_color/custom_colors_sidebarStyles_spec.js
  cypress/support/commands.js
Labels: 2: Dev Review

#2463 MM-14320: Adds e2e test to check @-mentions highlight with dots (#10368)
  components/confirm_modal.jsx
  cypress/integration/channel/message_spec.js
Labels: 3: Ready to Merge

#2399 [MM-13877] Update `User Status` filter name to "All Users"
  components/admin_console/system_users/system_users.jsx
Labels: 3: Ready to Merge

#2493 MM-14334 Fix translation of system console help text
  components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
  components/admin_console/help_text.jsx
Labels: 3: Ready to Merge

#2482 MM-14198 Close RHS when viewing thread or pinned posts for a channel user was removed from
  actions/websocket_actions.jsx
  actions/websocket_actions.test.jsx
Labels: 3: Ready to Merge

#2439 [MM-14529] Show channel name in post input placeholder
  components/create_post/__snapshots__/create_post.test.jsx.snap
  components/create_post/create_post.jsx
  i18n/en.json
Labels: 3: Ready to Merge, Setup Test Server

#2496 MM-14504 - Updating dropdown issue in sys con
  sass/responsive/_tablet.scss
Labels: 3: Ready to Merge, CherryPickApproved

#2499 MM-14478 Update documentation on AllowUntrustedInternalConnections
  components/admin_console/admin_definition.jsx
  i18n/en.json
Labels: 3: Ready to Merge, CherryPickApproved

#2503 translations PR 20190314
  i18n/de.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 3: Ready to Merge

#2501 [MM-14548] Added e2e test for RHS search result comments
  cypress/integration/search/results_post_comment_spec.js
Labels: 2: Dev Review

#2483 MM-8647/MM-14334 Make all plugin setting help text support Markdown
  components/admin_console/custom_plugin_settings/index.js
Labels: 3: Ready to Merge

#2500 Removing unnused InviteSalt config
  components/admin_console/admin_definition.jsx
  i18n/en.json
Labels: 3: Ready to Merge

#2438 [MM-14192] Render hyperlinks in Message Attachment title
  components/admin_console/custom_plugin_settings/__snapshots__/custom_plugin_settings.test.jsx.snap
  components/markdown/__snapshots__/markdown.test.jsx.snap
  components/post_view/message_attachments/message_attachment/__snapshots__/message_attachment.test.jsx.snap
  components/post_view/message_attachments/message_attachment/message_attachment.jsx
  components/post_view/message_attachments/message_attachment/message_attachment.test.jsx
  utils/__snapshots__/message_html_to_component.test.jsx.snap
  utils/markdown/index.js
  utils/markdown/link_only_renderer.jsx
  utils/markdown/link_only_renderer.test.jsx
  utils/text_formatting.jsx
  utils/text_formatting.test.jsx
Labels: 3: Ready to Merge

#2349 [MM-4819] Add and use MinimumHashtagLength setting
  components/admin_console/admin_settings.jsx
  components/admin_console/database_settings.jsx
  components/markdown/index.js
  components/markdown/markdown.jsx
  components/markdown/markdown.test.jsx
  i18n/en.json
  utils/constants.jsx
  utils/text_formatting.jsx
  utils/text_formatting_hashtags.test.jsx
Labels: 3: Ready to Merge

#2403 Adds a flag to autocomplete users and channels using elasticsearch in the config
  components/admin_console/elasticsearch_settings.jsx
  i18n/en.json
Labels: 3: Ready to Merge

#2510 MM-14302 Make combined user activity message timestamp unclickable
  components/post_view/post_info/post_info.jsx
Labels: 3: Ready to Merge

#2508 MM-14554: Updates LDAP sync job display text.
  components/admin_console/admin_definition.jsx
  i18n/en.json
Labels: 3: Ready to Merge

#2459 Admin console search
  NOTICE.txt
  components/admin_console/__snapshots__/admin_console.test.jsx.snap
  components/admin_console/admin_console.jsx
  components/admin_console/admin_definition.jsx
  components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.jsx.snap
  components/admin_console/admin_sidebar/admin_sidebar.jsx
  components/admin_console/admin_sidebar/admin_sidebar.test.jsx
  components/admin_console/admin_sidebar/index.js
  components/admin_console/highlight.jsx
  components/admin_console/schema_admin_settings.jsx
  components/admin_console/server_logs/log_list.jsx
  i18n/en.json
  package-lock.json
  package.json
  sass/components/_inputs.scss
  sass/routes/_admin-console.scss
  sass/utils/_variables.scss
  utils/admin_console_index.jsx
  utils/admin_console_index.test.jsx
Labels: 3: Ready to Merge

#2465 MM-13960 Re-add support for combined user activity posts
  actions/post_actions.jsx
  components/post_view/combined_user_activity_post/index.js
  components/post_view/date_separator/date_separator.jsx
  components/post_view/floating_timestamp/floating_timestamp.jsx
  components/post_view/floating_timestamp/index.js
  components/post_view/index.js
  components/post_view/new_messages_below/index.js
  components/post_view/new_messages_below/index.test.js
  components/post_view/new_messages_below/new_messages_below.jsx
  components/post_view/post/index.js
  components/post_view/post/index.test.js
  components/post_view/post_list.jsx
  components/post_view/post_list.test.jsx
  components/rhs_thread/rhs_thread.jsx
  package-lock.json
  package.json
Labels: 3: Ready to Merge

#2393 Added join/list public/private teams permissions
  actions/team_actions.jsx
  actions/team_actions.test.js
  components/needs_team/index.js
  components/needs_team/needs_team.jsx
  components/needs_team/needs_team.test.jsx
  components/select_team/__snapshots__/select_team.test.jsx.snap
  components/select_team/components/__snapshots__/select_team_item.test.jsx.snap
  components/select_team/components/select_team_item.jsx
  components/select_team/components/select_team_item.test.jsx
  components/select_team/index.js
  components/select_team/select_team.jsx
  components/select_team/select_team.test.jsx
  i18n/en.json
  package-lock.json
  package.json
  sass/routes/_signup.scss
Labels: 3: Ready to Merge

#2461 MM-12488: Adds groups search and filters.
  components/admin_console/group_settings/groups_list/__snapshots__/groups_list.test.jsx.snap
  components/admin_console/group_settings/groups_list/groups_list.jsx
  components/admin_console/group_settings/groups_list/groups_list.test.jsx
  i18n/en.json
  sass/components/_groups.scss
Labels: 3: Ready to Merge

#2518 Remove period from OAuth apps description in Main Menu > Integrations
  components/integrations/integrations.jsx
  i18n/en.json
Labels: 3: Ready to Merge

#2486 [MM-14253] Modify Elasticsearch admin console messages to reference users and channels
  components/admin_console/elasticsearch_settings.jsx
  i18n/en.json
Labels: 3: Ready to Merge

#2449 MM-13634 Fix error message when drag and dropping folders
  actions/file_actions.jsx
  components/file_upload/file_upload.jsx
  i18n/en.json
Labels: 2: Dev Review

#2484 [MM-14356] Some strings in Channel Settings aren't localizable
  components/channel_notifications_modal/components/__snapshots__/describe.test.jsx.snap
  components/channel_notifications_modal/components/describe.jsx
  i18n/en.json
  i18n/es.json
  i18n/ko.json
  i18n/pl.json
Labels: 3: Ready to Merge

#2507 [MM-14571] Add e2e to test @mentions notifications
  components/channel_header/__snapshots__/channel_header.test.jsx.snap
  components/channel_header/channel_header.js
  components/sidebar/sidebar_channel_button_or_link/__snapshots__/sidebar_channel_button_or_link.test.jsx.snap
  components/sidebar/sidebar_channel_button_or_link/sidebar_channel_button_or_link.jsx
  cypress.json
  cypress/integration/at_mentions/at_mentions_spec.js
  cypress/plugins/index.js
  cypress/plugins/post_message_as.js
  cypress/support/commands.js
  package-lock.json
  package.json
Labels: 2: Dev Review

#2497 MM-14533 - Removing width for channel title
  sass/layout/_headers.scss
Labels: 3: Ready to Merge

#2513 Adds e2e tests to check timestamp on edited post
  components/local_date_time/local_date_time.jsx
  cypress/integration/channel/edit_message_spec.js
  package-lock.json
Labels: 2: Dev Review

#2421 [MM-14270] UI Automation: Write an automated test using cypress for Delete a par…
  components/search_bar/search_bar.jsx
  cypress/integration/channel/mobile_message_deletion_spec.js
Labels: 2: Dev Review

#2511 MM-14350: Fixes relative link under custom subpath.
  components/admin_console/group_settings/__snapshots__/group_settings.test.jsx.snap
  components/admin_console/group_settings/group_settings.jsx
  components/widgets/admin_console/admin_panel.jsx
  components/widgets/admin_console/admin_panel.test.jsx
  i18n/en.json
Labels: 2: Dev Review

#2517 translations PR 20190318
  i18n/de.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 3: Ready to Merge

#2472 [MM-14491] avoid hiding the popover when the cursor is moved away fro…
  components/link_tooltip/link_tooltip.jsx
Labels: 3: Ready to Merge

#2506 [MM-14591] Add hide prop to profile popover from the at_mention component
  components/at_mention/__snapshots__/at_mention.test.jsx.snap
  components/at_mention/at_mention.jsx
Labels: 3: Ready to Merge

#2516 [MM-14382] Added marked commit that fixes formatted embedded link to italicize when surrounded by asterisks
  package-lock.json
  package.json
Labels: 3: Ready to Merge

#2490 MM-14358 - E2E Test for "Message Draft Pencil Icon visible in channel switcher"
  components/suggestion/switch_channel_provider.jsx
  cypress/integration/channel/message_draft_then_switch_channel_spec.js
Labels: 3: Ready to Merge

#2502 Add (SAML|LDAP|Email) Login Button Color Configurations
  components/admin_console/admin_definition.jsx
  i18n/en.json
  utils/admin_console_index.test.jsx
Labels: 3: Ready to Merge, Docs: Needed

#2527 [MM-14375] Fix flaky test on collapsed specs and separated markdown specs
  cypress/fixtures/longMarkdownPost.html
  cypress/fixtures/longMarkdownPost.md
  cypress/fixtures/long_text_post.txt
  cypress/fixtures/markdown/markdown_basic.html
  cypress/fixtures/markdown/markdown_basic.md
  cypress/fixtures/markdown/markdown_block_quotes_1.html
  cypress/fixtures/markdown/markdown_block_quotes_1.md
  cypress/fixtures/markdown/markdown_block_quotes_2.html
  cypress/fixtures/markdown/markdown_block_quotes_2.md
  cypress/fixtures/markdown/markdown_carriage_return.html
  cypress/fixtures/markdown/markdown_carriage_return.md
  cypress/fixtures/markdown/markdown_carriage_return_two_lines.html
  cypress/fixtures/markdown/markdown_carriage_return_two_lines.md
  cypress/fixtures/markdown/markdown_code_block.html
  cypress/fixtures/markdown/markdown_code_block.md
  cypress/fixtures/markdown/markdown_escape_characters.html
  cypress/fixtures/markdown/markdown_escape_characters.md
  cypress/fixtures/markdown/markdown_headings.html
  cypress/fixtures/markdown/markdown_headings.md
  cypress/fixtures/markdown/markdown_inline_code.html
  cypress/fixtures/markdown/markdown_inline_code.md
  cypress/fixtures/markdown/markdown_inline_images_1.html
  cypress/fixtures/markdown/markdown_inline_images_1.md
  cypress/fixtures/markdown/markdown_inline_images_2.html
  cypress/fixtures/markdown/markdown_inline_images_2.md
  cypress/fixtures/markdown/markdown_inline_images_3.html
  cypress/fixtures/markdown/markdown_inline_images_3.md
  cypress/fixtures/markdown/markdown_inline_images_4.html
  cypress/fixtures/markdown/markdown_inline_images_4.md
  cypress/fixtures/markdown/markdown_inline_images_5.html
  cypress/fixtures/markdown/markdown_inline_images_5.md
  cypress/fixtures/markdown/markdown_lines.html
  cypress/fixtures/markdown/markdown_lines.md
  cypress/fixtures/markdown/markdown_not_autolink.html
  cypress/fixtures/markdown/markdown_not_autolink.md
  cypress/fixtures/markdown/markdown_not_in_code_block.html
  cypress/fixtures/markdown/markdown_not_in_code_block.md
  cypress/fixtures/markdown/markdown_text_style.html
  cypress/fixtures/markdown/markdown_text_style.md
  cypress/integration/channel/collapsed_message_spec.js
  cypress/integration/markdown/markdown_spec.js
  cypress/support/commands.js
Labels: 3: Ready to Merge

#2530 [MM-14375] Fix flaky tests on some account settings specs
  cypress/fixtures/theme.json
  cypress/integration/account_settings/display/channel_display_mode_spec.js
  cypress/integration/account_settings/display/message_display_mode_spec.js
  cypress/integration/account_settings/theme_color/custom_colors_sidebarStyles_spec.js
  cypress/integration/account_settings/theme_color/custom_colors_sidebar_styles_spec.js
  cypress/support/commands.js
Labels: 2: Dev Review

#2309 custom URL scheme upper case letters not working
  package-lock.json
  package.json
  utils/markdown/renderer.jsx
Labels: 3: Ready to Merge

#2535 MM-14297 Match GM sidebar and channel switcher visibility check
  components/suggestion/switch_channel_provider.jsx
Labels: 2: Dev Review

#2526 MM-14341 Add client-side messageWillBePosted hook
  actions/hooks.js
  actions/hooks.test.js
  actions/views/create_comment.jsx
  actions/views/create_comment.test.jsx
  components/create_post/create_post.jsx
  components/create_post/create_post.test.jsx
  components/create_post/index.js
  plugins/registry.js
Labels: 3: Ready to Merge

#2447 MM-14196 Add virtualised list for posts
  actions/global_actions.jsx
  components/create_post/create_post.test.jsx
  components/create_post/index.js
  components/permalink_view/__snapshots__/permalink_view.test.jsx.snap
  components/post_view/floating_timestamp.jsx
  components/post_view/index.js
  components/post_view/message_attachments/message_attachment/message_attachment.jsx
  components/post_view/message_attachments/message_attachment/message_attachment.test.jsx
  components/post_view/new_message_separator/__snapshots__/new_message_separator.test.jsx.snap
  components/post_view/new_message_separator/new_message_separator.jsx
  components/post_view/new_message_separator/new_message_separator.test.jsx
  components/post_view/post/index.js
  components/post_view/post/post.jsx
  components/post_view/post_attachment_opengraph/post_attachment_opengraph.jsx
  components/post_view/post_header/post_header.jsx
  components/post_view/post_image/post_image.jsx
  components/post_view/post_info/post_info.jsx
  components/post_view/post_info/post_info.test.jsx
  components/post_view/post_list.jsx
  components/post_view/post_list_row/__snapshots__/post_list_row.test.jsx.snap
  components/post_view/post_list_row/index.js
  components/post_view/post_list_row/post_list_row.jsx
  components/post_view/post_list_row/post_list_row.test.jsx
  components/post_view/post_message_view/post_message_view.jsx
  components/post_view/post_message_view/post_message_view.test.jsx
  components/post_view/reaction_list/reaction_list.jsx
  components/sidebar_right/sidebar_right.jsx
  components/textbox/textbox.jsx
  package-lock.json
  package.json
  sass/components/_videos.scss
  sass/layout/_post.scss
  selectors/posts.js
  utils/constants.jsx
  utils/event_types.jsx
  utils/global_event_emitter.jsx
  utils/post_utils.jsx
Labels: 3: Ready to Merge, QA Review, Setup Test Server

#2532 Restoring ellipsis LHS header username and team name
  sass/layout/_headers.scss
Labels: 3: Ready to Merge

#2536 MM-14586 - Updating badge css
  sass/components/_badge.scss
Labels: 3: Ready to Merge

#2525 [MM-14570] Added e2e test for at-mention setting
  cypress/integration/at_mentions/at_mentions_spec.js
Labels: 3: Ready to Merge

#2504 iOS (Mobile Safari) - Keyboard covers up messages after orientation c…
  components/create_post/create_post.jsx
Labels: 2: Dev Review

#2540 update redux deps
  package-lock.json
  package.json
Labels: 2: Dev Review

#2541 MM-14748: Allow to invalidate email invites
  actions/admin_actions.jsx
  components/admin_console/admin_definition.jsx
  i18n/en.json
  package-lock.json
  package.json
Labels: 3: Ready to Merge, CherryPickApproved

#2528 Update pull request template
  .github/PULL_REQUEST_TEMPLATE.md
  PULL_REQUEST_TEMPLATE.md
Labels: 3: Ready to Merge

#2529 MM-13689 Fix leaving top team on sidebar from non-default channel
  components/sidebar/sidebar.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2519 Create a plugin component to override file previews
  components/file_attachment_list/__snapshots__/file_attachment_list.test.jsx.snap
  components/file_attachment_list/file_attachment_list.jsx
  components/post_view/post_body_additional_content/post_body_additional_content.jsx
  components/single_image_view/__snapshots__/single_image_view.test.jsx.snap
  components/single_image_view/single_image_view.jsx
  components/view_image/__snapshots__/view_image.test.jsx.snap
  components/view_image/index.js
  components/view_image/view_image.jsx
  components/view_image/view_image.test.jsx
  plugins/export.js
  plugins/registry.js
Labels: 2: Dev Review, CherryPickApproved

#2534 MM-14636 E2E test for system message wrap validation
  cypress/integration/channel/system_message_spec.js
  cypress/support/commands.js
Labels: 3: Ready to Merge

#2538 MM-14731 Prevent getRedirectLocation calls when metadata is present
  components/post_view/post_body_additional_content/post_body_additional_content.jsx
  components/post_view/post_body_additional_content/post_body_additional_content.test.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2549 fix the replyToAddress not being added in the system console screen
  components/admin_console/email_settings.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2546 MM-14668 - Updating header elipsis
  components/channel_header/__snapshots__/channel_header.test.jsx.snap
  components/channel_header/channel_header.js
  sass/layout/_headers.scss
Labels: 3: Ready to Merge, CherryPickApproved

#2543 MM-14520: restore pretext changed event on composition
  components/suggestion/suggestion_box.jsx
  components/suggestion/suggestion_box.test.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2545 MM-13566 - Throw an error when accessing Set.length or Map.length in dev mode
  actions/diagnostics_actions.jsx
  components/root/root.jsx
  components/root/root.test.jsx
  root.jsx
  utils/utils.jsx
  utils/utils.test.jsx
Labels: 3: Ready to Merge

#2551 MM-14970 Fix for Posts ovelapping with each other
  package-lock.json
  package.json
Labels: 3: Ready to Merge, CherryPickApproved

#2554 Revert "MM-14970 Fix for Posts ovelapping with each other"
  package-lock.json
  package.json
Labels: 3: Ready to Merge

#2553 MM-14713 - Updating email general settings
  components/user_settings/general/user_settings_general.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2531 MM-14579 Correctly size AutosizeTextarea on mount
  components/autosize_textarea.jsx
  components/create_comment/__snapshots__/create_comment.test.jsx.snap
  components/create_comment/create_comment.jsx
  components/create_post/__snapshots__/create_post.test.jsx.snap
  components/create_post/create_post.jsx
  components/textbox/textbox.jsx
Labels: 3: Ready to Merge

#2556 MM-14791 Safari and FF scroll correction issue when loading more posts
  components/post_view/post_list.jsx
  package-lock.json
  package.json
Labels: 3: Ready to Merge, CherryPickApproved

#2557 Fix a bad usage of length on a set in the channel switcher
  components/suggestion/switch_channel_provider.jsx
Labels: 3: Ready to Merge

#2555 MM-14794 Fixing unessisary API call in non-bot DM channels.
  components/channel_header/channel_header.js
Labels: 2: Dev Review

#2560 Revert "MM-14791 Safari and FF scroll correction issue when loading more posts"
  components/post_view/post_list.jsx
  package-lock.json
  package.json
Labels: 2: Dev Review

#2544 [MM-14375] Fix flaky E2E tests
  .gitignore
  components/dot_menu/__snapshots__/dot_menu.test.jsx.snap
  components/dot_menu/dot_menu.jsx
  cypress/integration/account_settings/display/channel_display_mode_spec.js
  cypress/integration/account_settings/display/code_theme_colors_spec.js
  cypress/integration/account_settings/display/message_display_mode_spec.js
  cypress/integration/at_mentions/at_mentions_spec.js
  cypress/integration/channel/edit_message_spec.js
  cypress/integration/channel/message_bullets_spec.js
  cypress/integration/channel/message_deletion_spec.js
  cypress/integration/channel/message_draft_spec.js
  cypress/integration/channel/message_edit_post_with_attachment_spec.js
  cypress/integration/channel/message_spec.js
  cypress/integration/channel/mobile_message_deletion_spec.js
  cypress/integration/post_header/post_header_spec.js
  cypress/integration/search/results_post_comment_spec.js
  cypress/support/commands.js
Labels: CherryPickApproved

#2552 MM-14708 - Updating PAC position
  components/admin_console/system_users/system_users_dropdown/system_users_dropdown.jsx
Labels: 2: Dev Review

#2562 MM-14800 Fix missing messages when switching to a team not previously loaded
  components/post_view/index.js
  components/post_view/post_list.jsx
Labels: 2: Dev Review, CherryPickApproved

#2548 MM-14692 - Updating textarea placeholder structure
  components/__snapshots__/autosize_textarea.test.jsx.snap
  components/autosize_textarea.jsx
  components/user_settings/notifications/__snapshots__/manage_auto_responder.test.jsx.snap
  sass/components/_modal.scss
  sass/responsive/_mobile.scss
Labels: 3: Ready to Merge, CherryPickApproved

#2558 MM-14799 Fixing DM loading.
  components/channel_header/channel_header.js
Labels: 3: Ready to Merge, CherryPickApproved

#2571 MM-14762 Fix hover effect causing post jiggle when zoomed
  components/post_view/post_list.jsx
  package-lock.json
  package.json
Labels: CherryPickApproved

#2572 MM-14810 Fix for infinite loop caused by loading channels with content less than screen height
  components/post_view/post_list.jsx
  package-lock.json
  package.json
Labels: 3: Ready to Merge, CherryPickApproved

#2573 Fix postlist connector when channel is undefined
  components/post_view/index.js
Labels: 2: Dev Review, CherryPickApproved

#2574 Update react-window to fix long posts
  package-lock.json
  package.json
Labels: 3: Ready to Merge, CherryPickApproved

#2575 Update React Window build
  package-lock.json
  package.json
Labels: 3: Ready to Merge, CherryPickApproved

#2569 Expose virtualised list variable to window
  components/post_view/post_list.jsx
Labels: 3: Ready to Merge, CherryPickApproved

#2559 Revert "MM-14489 Making SuggestionList component render at bottom of input on dialogs (#2235)"
  components/interactive_dialog/dialog_element.jsx
  components/interactive_dialog/interactive_dialog.jsx
  components/suggestion/suggestion_box.jsx
  components/suggestion/suggestion_list.jsx
  components/widgets/settings/autocomplete_selector.jsx
  sass/components/_select.scss
  sass/components/_suggestion-list.scss
  sass/layout/_webhooks.scss
  sass/routes/_about-modal.scss
Labels: 2: Dev Review, CherryPickApproved
