Repository mattermost/mattermost-webapp, pull requests merged in 2020-01, with the labels that each got.

#4550 [GH10573] Write an automated test using Cypress for "Main Menu stays open"
  e2e/cypress/integration/account_settings/general/main_menu_stays_open_spec.js
Labels: 3: Reviews Complete, QA Review Done

#4578 Fixes #13341 : UI Automation: Write an automated test using Cypress for Change selection in RHS / Message Thread
  e2e/cypress/integration/interactive_menu/basic_options_spec.js
Labels: 3: Reviews Complete, QA Review Done

#4602 Fixes #13520 : Many UI automation tests are failing in interactive_menu/basic_options_spec.js
  e2e/cypress/integration/interactive_menu/basic_options_spec.js
Labels: 3: Reviews Complete, QA Review Done

#4580 MM-21148 - `make i18n-extract` throws an error if mobile repo is not checked out
  package-lock.json
  package.json
Labels: 3: Reviews Complete, Tests/Not Needed

#4479 MM-18778 Remove deprecated lifecycle methods from root components
  components/authorize/authorize.jsx
  components/channel_layout/center_channel/center_channel.jsx
  components/channel_layout/center_channel/center_channel.test.jsx
  components/channel_layout/channel_identifier_router/channel_identifier_router.jsx
  components/channel_layout/channel_identifier_router/channel_identifier_router.test.jsx
  components/needs_team/needs_team.jsx
  components/root/root.jsx
  components/root/root.test.jsx
Labels: 3: Reviews Complete, QA Review Done

#4562 MM-21360 Fix date separator for timezone not supported by react-intl
  components/post_view/date_separator/__snapshots__/date_separator.test.jsx.snap
  components/post_view/date_separator/date_separator.test.jsx
  components/recent_date.test.tsx
  components/recent_date.tsx
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#4612 Automated cherry pick of #4562
  components/post_view/date_separator/__snapshots__/date_separator.test.jsx.snap
  components/post_view/date_separator/date_separator.test.jsx
  components/recent_date.test.tsx
  components/recent_date.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4327 Enable default select element in interactive dialogs
  components/interactive_dialog/dialog_element/dialog_element.jsx
  components/interactive_dialog/interactive_dialog.test.jsx
Labels: 3: Reviews Complete, AutoMerge, QA Review Done

#4613 Fix failing E2E
  e2e/cypress/integration/account_settings/sidebar/channel_switcher_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/guest_identification_ui_spec.js
  e2e/cypress/integration/interactive_menu/basic_options_spec.js
  e2e/cypress/integration/messaging/channel_read_after_permalink_spec.js
  e2e/cypress/integration/messaging/message_by_aeroplane_icon_spec.js
  e2e/cypress/integration/messaging/message_pinning_unpinning_spec.js
  e2e/cypress/integration/multi_team/system_message_spec.js
  e2e/cypress/integration/plugins/marketplace/marketplace_spec.js
  e2e/cypress/integration/search/date_filter_spec.js
  e2e/cypress/integration/search/post_search_display_spec.js
Labels: 2: Dev Review, 3: Reviews Complete

#4460 MM-17448 UI Automation for "Draw plugin does not post text in input box"
  components/admin_console/admin_settings.tsx
  components/admin_console/plugin_management/__snapshots__/plugin_management.test.jsx.snap
  components/admin_console/plugin_management/plugin_management.jsx
  components/file_upload/file_upload.jsx
  components/widgets/admin_console/admin_header.test.tsx
  e2e/cypress/integration/messaging/message_channel_draw_spec.js
  e2e/cypress/integration/system_console/plugin_upload_spec.js
  e2e/cypress/support/api_commands.js
  e2e/cypress/support/ui_commands.js
Labels: 3: Reviews Complete, QA Review Done

#4543 Fix incorrect link handling of inline MD images
  utils/__snapshots__/message_html_to_component.test.jsx.snap
  utils/message_html_to_component.jsx
  utils/message_html_to_component.test.jsx
Labels: 3: Reviews Complete, QA Review Done

#4572 MM-18759 add test "Floating timestamp in mobile view"
  components/post_view/floating_timestamp/floating_timestamp.jsx
  e2e/cypress/integration/channel/scroll_channel_messages_spec.js
Labels: 3: Reviews Complete, AutoMerge, QA Review Done

#4434 [GH-12271] UI Automation: Write an automated test using Cypress for "RHS fetches messages on socket reconnect when a different channel is in center"
  e2e/cypress/integration/messaging/receive_message_on_socket_reconnect_spec.js
  e2e/cypress/support/fetch_commands.js
  e2e/cypress/support/ui_commands.js
Labels: 3: Reviews Complete, QA Review Done

#4577 MM-12511 - add Mute option in Direct Message channel menus
  components/channel_header_dropdown/menu_items/toggle_mute_channel/__snapshots__/toggle_mute_channel.test.js.snap
  components/channel_header_dropdown/menu_items/toggle_mute_channel/toggle_mute_channel.js
  components/channel_header_dropdown/menu_items/toggle_mute_channel/toggle_mute_channel.test.js
Labels: 3: Reviews Complete, QA Review Done

#4417 [GH-11754] UI Automation: Write an automated test using Cypress for "System message limited options"
  e2e/cypress/integration/messaging/system_message_limited_options_spec.js
Labels: 3: Reviews Complete, QA Review Done

#4583 [MM-20274] fix axe rule violations (list, listitem) in account settings
  components/__snapshots__/setting_item_max.test.jsx.snap
  components/__snapshots__/setting_picture.test.jsx.snap
  components/setting_item_max.jsx
  components/setting_item_max.test.jsx
  components/setting_item_min/__snapshots__/setting_item_min.test.jsx.snap
  components/setting_item_min/setting_item_min.jsx
  components/setting_picture.jsx
  components/user_settings/notifications/__snapshots__/manage_auto_responder.test.jsx.snap
  components/user_settings/notifications/email_notification_setting/__snapshots__/email_notification_setting.test.jsx.snap
  sass/routes/_settings.scss
Labels: 3: Reviews Complete, QA Review Done

#4566 Fixes #12472 : Migrate 'components/common' module and associated tests to TypeScript
  components/claim/claim_controller.jsx
  components/common/__snapshots__/site_name_and_description.test.tsx.snap
  components/common/back_button.tsx
  components/common/comment_icon.tsx
  components/common/site_name_and_description.test.tsx
  components/common/site_name_and_description.tsx
  components/create_team/create_team.jsx
  components/create_team/create_team.test.jsx
  components/do_verify_email/do_verify_email.jsx
  components/login/login_controller/login_controller.jsx
  components/mfa/mfa_controller/mfa_controller.jsx
  components/post_view/post_info/post_info.jsx
  components/search_results_item/search_results_item.jsx
  components/select_team/select_team.jsx
  components/should_verify_email/should_verify_email.js
  components/signup/signup_controller/signup_controller.jsx
  components/signup/signup_email/signup_email.jsx
  types/react-bootstrap.d.ts
Labels: 3: Reviews Complete, QA Review Done

#4589 Fixes #13485 : Migrate 'components/tutorial/tutorial_tip' module and associated tests to TypeScript
  components/tutorial/tutorial_tip/__snapshots__/tutorial_tip.test.tsx.snap
  components/tutorial/tutorial_tip/index.js
  components/tutorial/tutorial_tip/tutorial_tip.test.tsx
  components/tutorial/tutorial_tip/tutorial_tip.tsx
  types/images.d.ts
Labels: 3: Reviews Complete, QA Review Done

#4591 MM-20672 - Updating sidebar unread text color
  sass/layout/_sidebar-left.scss
  utils/utils.jsx
Labels: 3: Reviews Complete, QA Review Done

#4590 MM-19855 - Updating markdown in view info modal
  sass/components/_modal.scss
Labels: 3: Reviews Complete, QA Review Done

#4540 Fixing how the accesibility labels for MenuItemToggleModalRedux are built
  components/toggle_modal_button_redux/__snapshots__/toggle_modal_button_redux.test.jsx.snap
  components/toggle_modal_button_redux/toggle_modal_button_redux.jsx
  i18n/en.json
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#4601 MM-20560 Migrate 'components/admin_console/blockable_link' module and associated tests to TypeScript
  components/admin_console/blockable_link/blockable_link.tsx
  components/admin_console/blockable_link/index.js
  components/admin_console/blockable_link/index.ts
Labels: 3: Reviews Complete, QA Review Done

#4553 [MM-20881] Moved out old sidebar and added setting to activate new one
  components/admin_console/admin_definition.jsx
  components/channel_layout/channel_controller.jsx
  components/channel_layout/channel_controller.test.jsx
  components/legacy_sidebar/__snapshots__/sidebar.test.jsx.snap
  components/legacy_sidebar/__snapshots__/sidebar_tutorial_tip.test.jsx.snap
  components/legacy_sidebar/channel_create.jsx
  components/legacy_sidebar/channel_more.jsx
  components/legacy_sidebar/channel_name.jsx
  components/legacy_sidebar/header/dropdown/index.js
  components/legacy_sidebar/header/dropdown/sidebar_header_dropdown.jsx
  components/legacy_sidebar/header/index.js
  components/legacy_sidebar/header/sidebar_header.jsx
  components/legacy_sidebar/header/sidebar_header_dropdown_button.jsx
  components/legacy_sidebar/index.js
  components/legacy_sidebar/more_public_direct_channels.jsx
  components/legacy_sidebar/sidebar.jsx
  components/legacy_sidebar/sidebar.test.jsx
  components/legacy_sidebar/sidebar_channel/__snapshots__/sidebar_channel.test.jsx.snap
  components/legacy_sidebar/sidebar_channel/index.js
  components/legacy_sidebar/sidebar_channel/sidebar_channel.jsx
  components/legacy_sidebar/sidebar_channel/sidebar_channel.test.jsx
  components/legacy_sidebar/sidebar_channel_button_or_link/__snapshots__/sidebar_channel_button_or_link.test.jsx.snap
  components/legacy_sidebar/sidebar_channel_button_or_link/__snapshots__/sidebar_channel_button_or_link_close_button.test.jsx.snap
  components/legacy_sidebar/sidebar_channel_button_or_link/__snapshots__/sidebar_channel_button_or_link_icon.test.jsx.snap
  components/legacy_sidebar/sidebar_channel_button_or_link/sidebar_channel_button_or_link.jsx
  components/legacy_sidebar/sidebar_channel_button_or_link/sidebar_channel_button_or_link.test.jsx
  components/legacy_sidebar/sidebar_channel_button_or_link/sidebar_channel_button_or_link_close_button.jsx
  components/legacy_sidebar/sidebar_channel_button_or_link/sidebar_channel_button_or_link_close_button.test.jsx
  components/legacy_sidebar/sidebar_channel_button_or_link/sidebar_channel_button_or_link_icon.jsx
  components/legacy_sidebar/sidebar_channel_button_or_link/sidebar_channel_button_or_link_icon.test.jsx
  components/legacy_sidebar/sidebar_tutorial_tip.jsx
  components/legacy_sidebar/sidebar_tutorial_tip.test.jsx
  components/legacy_team_sidebar/components/team_button.jsx
  components/legacy_team_sidebar/index.js
  components/legacy_team_sidebar/legacy_team_sidebar_controller.jsx
  components/needs_team/index.js
  components/needs_team/needs_team.jsx
  components/needs_team/needs_team.test.jsx
  components/sidebar/index.ts
  components/sidebar/sidebar.tsx
  components/sidebar/sidebar_channel_button_or_link/__snapshots__/sidebar_channel_button_or_link_icon.test.jsx.snap
  components/team_sidebar/index.ts
  components/team_sidebar/team_sidebar.tsx
  components/user_settings/sidebar/__snapshots__/user_settings_sidebar.test.jsx.snap
  components/user_settings/sidebar/index.js
  components/user_settings/sidebar/user_settings_sidebar.jsx
  components/user_settings/sidebar/user_settings_sidebar.test.jsx
  i18n/en.json
Labels: 2: Dev Review

#4219 [GH-12292] UI Automation: Write an automated test using Cypress for "Input box on main thread can expand with RHS closed"
  e2e/cypress/integration/messaging/input_box_expands_spec.js
Labels: 3: Reviews Complete, QA Review Done

#4587 MM-20331: Add E2E for SC20331 Can change Report a Problem Link setting
  e2e/cypress/integration/system_console/ui_and_api/customization_spec.js
Labels: 3: Reviews Complete, QA Review Done

#4555 Edits to in-product text (menus and action buttons)
  i18n/en.json
Labels: 3: Reviews Complete

#4568 Respecting the manual timezone in the date selector for searches
  components/search_bar/__snapshots__/search_bar.test.jsx.snap
  components/search_bar/search_bar.jsx
  components/suggestion/search_date_provider.jsx
  components/suggestion/search_date_suggestion/index.js
  components/suggestion/search_date_suggestion/search_date_suggestion.jsx
  utils/timezone.jsx
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#4621 Automated cherry pick of #4540
  components/toggle_modal_button_redux/__snapshots__/toggle_modal_button_redux.test.jsx.snap
  components/toggle_modal_button_redux/toggle_modal_button_redux.jsx
  i18n/en.json
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4623 MM-21421: Fix height and width parameters for inline image.
  components/markdown_image.jsx
  components/markdown_image.test.jsx
Labels: 3: Reviews Complete, AutoMerge, CherryPick/Approved, QA Review Done

#4546 MM-21043 Using up/down arrow keys to make selection
  e2e/cypress/integration/interactive_menu/basic_options_spec.js
Labels: 3: Reviews Complete, QA Review Done

#4609 MM-21414 - Updating textbox position in RHS
  components/create_comment/__snapshots__/create_comment.test.jsx.snap
  components/create_comment/create_comment.jsx
  components/create_comment/create_comment.test.jsx
  components/suggestion/suggestion_list.jsx
  components/textbox/textbox.jsx
  sass/components/_suggestion-list.scss
  utils/constants.jsx
Labels: CherryPick/Approved, QA Review Done

#4620 MM-20627: Create SECURITY.md
  SECURITY.md
Labels: 3: Reviews Complete

#4622 translations PR 20200106
  i18n/de.json
  i18n/zh-CN.json
Labels: 3: Reviews Complete, Tests/Not Needed

#4627 Automated cherry pick of #4609
  components/create_comment/__snapshots__/create_comment.test.jsx.snap
  components/create_comment/create_comment.jsx
  components/create_comment/create_comment.test.jsx
  components/suggestion/suggestion_list.jsx
  components/textbox/textbox.jsx
  sass/components/_suggestion-list.scss
  utils/constants.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4614 [MM-21483] Fix error thrown on team reload when icon not available
  components/widgets/team_icon/team_icon.tsx
Labels: 3: Reviews Complete, QA Review Done

#4611 automated MM-14632 Integration test for removing team icon #4066
  components/__snapshots__/setting_picture.test.jsx.snap
  components/setting_picture.jsx
  components/widgets/team_icon/__snapshots__/team_icon.test.tsx.snap
  components/widgets/team_icon/team_icon.tsx
  e2e/cypress/integration/team/remove_team_icon_spec.js
Labels: 3: Reviews Complete, QA Review Done

#4581 [MM-19146] Add max length to user first name, last name and email fields
  components/user_settings/general/user_settings_general.jsx
  utils/constants.jsx
Labels: 3: Reviews Complete, AutoMerge, QA Review Done

#4634 MM-20863 Fix for permalink to DM failing to load on daily
  components/sidebar/sidebar.jsx
Labels: 3: Reviews Complete, QA Review Done

#4630 MM-21607 - Updating suggestion list in Switcher
  components/widgets/menu/menu_items/menu_item.scss
  sass/components/_modal.scss
Labels: CherryPick/Approved, QA Review Done, Setup Cloud Test Server

#4579 Fixes #13366 : Remove call to `openLhs` from SidebarChannel render method
  components/sidebar/sidebar_channel/__snapshots__/sidebar_channel.test.jsx.snap
  components/sidebar/sidebar_channel/sidebar_channel.jsx
  components/sidebar/sidebar_channel/sidebar_channel.test.jsx
  components/sidebar/sidebar_tutorial_tip.jsx
  components/sidebar/sidebar_tutorial_tip.test.jsx
Labels: 3: Reviews Complete, QA Review Done

#4558 [GH-13334] UI Automation: Write an automated test using Cypress for "Boolean element check"
  e2e/cypress/integration/interactive_dialog/boolean_spec.js
  e2e/utils/webhook_utils.js
  e2e/webhook_serve.js
Labels: 3: Reviews Complete, QA Review Done

#4636 Automated cherry pick of #4630
  components/widgets/menu/menu_items/menu_item.scss
  sass/components/_modal.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4632 Enabled Plugin Marketplace signature E2E tests
  e2e/cypress/integration/plugins/marketplace/marketplace_spec.js
Labels: 3: Reviews Complete, QA Review Done

#4640 MM-21201 - Updating scrollbar bg in sys console
  sass/components/_scrollbar.scss
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#4643 Automated cherry pick of #4640
  sass/components/_scrollbar.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4575 [GH-13452] "onTouchEnd got false" console error
  components/file_upload/__snapshots__/file_upload.test.jsx.snap
  components/file_upload/file_upload.jsx
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#4637 MM-17555 Only use shallowWithIntl and dive when necessary
  components/__snapshots__/save_button.test.tsx.snap
  components/admin_console/admin_sidebar/admin_sidebar.test.jsx
  components/admin_console/jobs/table.test.jsx
  components/admin_console/system_users/list/system_users_list.test.jsx
  components/audit_table/audit_table.test.jsx
  components/backstage/components/backstage_header.test.jsx
  components/channel_header/channel_header.test.jsx
  components/channel_header_dropdown/channel_header_dropdown.test.jsx
  components/create_comment/create_comment.test.jsx
  components/create_post/create_post.test.jsx
  components/create_team/create_team.test.jsx
  components/dot_menu/dot_menu_empty.test.jsx
  components/dot_menu/dot_menu_mobile.test.jsx
  components/edit_channel_header_modal/__snapshots__/edit_channel_header_modal.test.jsx.snap
  components/edit_channel_header_modal/edit_channel_header_modal.test.jsx
  components/edit_post_modal/edit_post_modal.test.jsx
  components/file_upload/file_upload.test.jsx
  components/get_link_modal.test.tsx
  components/invitation_modal/__snapshots__/invitation_modal.test.jsx.snap
  components/invitation_modal/invitation_modal.jsx
  components/invitation_modal/invitation_modal_members_step.test.jsx
  components/login/login_controller/login_controller.test.jsx
  components/main_menu/main_menu.test.jsx
  components/password_reset_form/password_reset_form.test.js
  components/password_reset_send_link/password_reset_send_link.test.js
  components/permalink_redirector/permalink_redirector.test.jsx
  components/permalink_view/permalink_view.test.jsx
  components/plugin_marketplace/__snapshots__/marketplace_modal.test.js.snap
  components/post_view/combined_system_message/combined_system_message.test.jsx
  components/post_view/combined_system_message/last_users.test.jsx
  components/post_view/new_message_separator/new_message_separator.test.jsx
  components/post_view/post_list/post_list_virtualized.test.jsx
  components/post_view/post_list_row/post_list_row.test.jsx
  components/profile_popover/profile_popover.test.jsx
  components/recent_date.test.tsx
  components/rename_channel_modal/rename_channel_modal.test.jsx
  components/rhs_comment/rhs_comment.test.jsx
  components/rhs_root_post/rhs_root_post.test.jsx
  components/save_button.test.tsx
  components/search_results_item/search_results_item.test.jsx
  components/should_verify_email/should_verify_email.test.js
  components/sidebar/sidebar.test.jsx
  components/sidebar/sidebar_channel/sidebar_channel.test.jsx
  components/signup/signup_controller/signup_controller.test.jsx
  components/system_notice/system_notice.test.jsx
  components/team_settings_modal/team_settings_modal.test.jsx
  components/tutorial/tutorial_intro_screens/tutorial_intro_screen.test.jsx
  components/user_settings/display/user_settings_theme/custom_theme_chooser.test.jsx
  components/user_settings/display/user_settings_theme/user_settings_theme.test.jsx
  components/user_settings/general/user_settings_general.test.js
  components/user_settings/security/mfa_section/mfa_section.test.jsx
  components/user_settings/sidebar/user_settings_sidebar.test.jsx
  components/widgets/inputs/channels_input.test.jsx
  components/widgets/inputs/users_emails_input.test.jsx
  components/widgets/loading/loading_spinner.test.tsx
  components/widgets/modals/full_screen_modal.tsx
  plugins/test/main_menu_action.test.jsx
  tests/helpers/intl-test-helper.jsx
Labels: 3: Reviews Complete, QA Review Done

#4644 Automated cherry pick of #4575
  components/file_upload/__snapshots__/file_upload.test.jsx.snap
  components/file_upload/file_upload.jsx
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4639 MM-17555 Add dummy OverlayTrigger component
  components/admin_console/brand_image_setting/brand_image_setting.jsx
  components/admin_console/permission_schemes_settings/permissions_scheme_summary/permissions_scheme_summary.jsx
  components/admin_console/team_channel_settings/group/group_users_row.jsx
  components/analytics/table_chart.tsx
  components/announcement_bar/announcement_bar.jsx
  components/change_url_modal/change_url_modal.jsx
  components/channel_header/channel_header.js
  components/channel_header/components/header_icon_wrapper.js
  components/channel_header_mobile/channel_info_button/channel_info_button.js
  components/common/comment_icon.tsx
  components/copy_text.tsx
  components/create_team/components/team_url/team_url.jsx
  components/dot_menu/dot_menu.jsx
  components/file_attachment/filename_overlay.jsx
  components/integrations/bots/add_bot/add_bot.jsx
  components/overlay_trigger.tsx
  components/plugin_marketplace/marketplace_item/marketplace_item.js
  components/popover_list_members/popover_list_members.jsx
  components/post_view/post_flag_icon/post_flag_icon.js
  components/post_view/post_info/post_info.jsx
  components/post_view/post_reaction/post_reaction.jsx
  components/post_view/reaction/reaction.jsx
  components/post_view/reaction_list/reaction_list.jsx
  components/profile_picture.tsx
  components/profile_popover/profile_popover.jsx
  components/quick_input.jsx
  components/rename_channel_modal/rename_channel_modal.jsx
  components/rhs_card_header/rhs_card_header.jsx
  components/rhs_comment/rhs_comment.jsx
  components/rhs_header_post/rhs_header_post.jsx
  components/rhs_root_post/rhs_root_post.jsx
  components/search_results_header/search_results_header.jsx
  components/search_results_item/search_results_item.jsx
  components/select_team/components/select_team_item.jsx
  components/setting_picture.jsx
  components/sidebar/channel_create.jsx
  components/sidebar/channel_name.jsx
  components/sidebar/header/sidebar_header_dropdown_button.jsx
  components/sidebar/sidebar_channel_button_or_link/sidebar_channel_button_or_link.jsx
  components/sidebar/sidebar_channel_button_or_link/sidebar_channel_button_or_link.test.jsx
  components/sidebar/sidebar_channel_button_or_link/sidebar_channel_button_or_link_close_button.jsx
  components/team_sidebar/components/team_button.jsx
  components/user_profile/user_profile.jsx
  components/user_settings/display/user_settings_theme/custom_theme_chooser.jsx
  components/widgets/popover/popover.stories.js
Labels: 3: Reviews Complete, QA Review Done

#4570 [MM-19756] Remove role='presentation' for post timestamps
  components/post_view/post_time/post_time.jsx
Labels: 3: Reviews Complete, QA Review Done

#4638 MM-17555 Update tests that use string refs
  components/change_url_modal/change_url_modal.test.jsx
  components/channel_header_mobile/channel_info_button/channel_info_button.test.js
Labels: 3: Reviews Complete, QA Review Done

#4461 MM-18903 Removal of redux requests states for integrations object
  components/integrations/add_incoming_webhook/add_incoming_webhook.jsx
  components/integrations/add_incoming_webhook/add_incoming_webhook.test.jsx
  components/integrations/add_incoming_webhook/index.js
  components/integrations/add_oauth_app/add_oauth_app.jsx
  components/integrations/add_oauth_app/index.js
  components/integrations/add_outgoing_webhook/add_outgoing_webhook.jsx
  components/integrations/add_outgoing_webhook/add_outgoing_webhook.test.jsx
  components/integrations/add_outgoing_webhook/index.js
  components/integrations/edit_incoming_webhook/__snapshots__/edit_incoming_webhook.test.jsx.snap
  components/integrations/edit_incoming_webhook/edit_incoming_webhook.jsx
  components/integrations/edit_incoming_webhook/edit_incoming_webhook.test.jsx
  components/integrations/edit_incoming_webhook/index.js
  components/integrations/edit_outgoing_webhook/edit_outgoing_webhook.jsx
  components/integrations/edit_outgoing_webhook/edit_outgoing_webhook.test.jsx
  components/integrations/edit_outgoing_webhook/index.js
  components/integrations/installed_oauth_app/installed_oauth_app.jsx
  components/integrations/installed_oauth_apps/__snapshots__/installed_oauth_apps.test.jsx.snap
  components/integrations/installed_oauth_apps/index.js
  components/integrations/installed_oauth_apps/installed_oauth_apps.jsx
  components/integrations/installed_oauth_apps/installed_oauth_apps.test.jsx
Labels: 3: Reviews Complete, QA Review Done

#4427 MM-20697: Update System Console for SAML metadata support
  actions/admin_actions.jsx
  components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
  components/admin_console/admin_definition.jsx
  components/admin_console/admin_definition.test.jsx
  components/admin_console/schema_admin_settings.jsx
  e2e/cypress/integration/enterprise/system_console/saml_metadata_spec.js
  i18n/en.json
  utils/constants.jsx
Labels: 1: UX Review, 2: QA Review, Setup Cloud Test Server

#4608 MM-21394 - Updating menu item css on mobile
  components/widgets/menu/menu_items/menu_item.scss
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#4645 MM-21315 Don't mark manually unread channel as read on team switch
  actions/team_actions.jsx
  actions/team_actions.test.js
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#4652 Automated cherry pick of #4608
  components/widgets/menu/menu_items/menu_item.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4653 Automated cherry pick of #4645
  actions/team_actions.jsx
  actions/team_actions.test.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4642 MM-21603 - Updating sidebar text 80 var
  utils/utils.jsx
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#4576 [GH-13453] Fix "wrapperHeight prop not a prop from component" console error
  components/suggestion/suggestion_box.jsx
Labels: 3: Reviews Complete, QA Review Done, Tests/Not Needed

#4654 Automated cherry pick of #4642
  utils/utils.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4650 MM-21482 Use react-intl by default or moment-timezone for (react-intl) unsupported timezone
  components/post_view/date_separator/__snapshots__/date_separator.test.jsx.snap
  components/recent_date.test.tsx
  components/recent_date.tsx
  components/widgets/separator/__snapshots__/separator.test.tsx.snap
  components/widgets/separator/basic-separator.tsx
  e2e/cypress/integration/messaging/date_separator_spec.js
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done, Setup Cloud Test Server

#4664 MM-20349 Fix perf regressions when typing
  components/create_post/create_post.jsx
  components/post_view/post/post.jsx
  components/textbox/textbox.jsx
  components/textbox/textbox_links.jsx
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#4368 eslint --cache
  .gitignore
  package.json
Labels: 3: Reviews Complete, AutoMerge, QA Review Done

#4646 MM-20622 Only wrap code without a language tag
  utils/markdown/index.test.js
  utils/markdown/renderer.jsx
Labels: 3: Reviews Complete, QA Review Done

#4617 [MM-20559] Migrate 'components/admin_console/reset_password_modal' mo…
  components/admin_console/reset_password_modal/__snapshots__/reset_password_modal.test.tsx.snap
  components/admin_console/reset_password_modal/index.js
  components/admin_console/reset_password_modal/index.ts
  components/admin_console/reset_password_modal/reset_password_modal.test.tsx
  components/admin_console/reset_password_modal/reset_password_modal.tsx
Labels: 3: Reviews Complete, QA Review Done

#4656 Automated cherry pick of #4650
  components/post_view/date_separator/__snapshots__/date_separator.test.jsx.snap
  components/recent_date.tsx
  components/widgets/separator/__snapshots__/separator.test.tsx.snap
  components/widgets/separator/basic-separator.tsx
  e2e/cypress/integration/messaging/date_separator_spec.js
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4598 MM:20579 - Migrate 'components/admin_console/team_channel_settings/group' module and associated tests to TypeScript #13493
  components/admin_console/team_channel_settings/group/__snapshots__/group_list.test.tsx.snap
  components/admin_console/team_channel_settings/group/__snapshots__/group_row.test.tsx.snap
  components/admin_console/team_channel_settings/group/__snapshots__/group_users.test.tsx.snap
  components/admin_console/team_channel_settings/group/__snapshots__/group_users_row.test.tsx.snap
  components/admin_console/team_channel_settings/group/group_list.test.tsx
  components/admin_console/team_channel_settings/group/group_list.tsx
  components/admin_console/team_channel_settings/group/group_row.test.tsx
  components/admin_console/team_channel_settings/group/group_row.tsx
  components/admin_console/team_channel_settings/group/group_users.test.tsx
  components/admin_console/team_channel_settings/group/group_users.tsx
  components/admin_console/team_channel_settings/group/group_users_row.test.tsx
  components/admin_console/team_channel_settings/group/group_users_row.tsx
  components/admin_console/team_channel_settings/group/index.js
  components/admin_console/team_channel_settings/users_to_be_removed_modal.jsx
Labels: QA Review Done

#4603 Migrate leave_private_channel_modal to typescript
  components/leave_private_channel_modal/__snapshots__/leave_private_channel_modal.test.tsx.snap
  components/leave_private_channel_modal/index.ts
  components/leave_private_channel_modal/leave_private_channel_modal.test.tsx
  components/leave_private_channel_modal/leave_private_channel_modal.tsx
Labels: 3: Reviews Complete, QA Review Done

#4661 MM-21342 Fix leading zero on post by using react-intl by default and fallback to moment-timezone for unsupported locale
  components/local_date_time/local_date_time.test.tsx
  components/local_date_time/local_date_time.tsx
  e2e/cypress/integration/messaging/local_date_time_spec.js
Labels: 2: Dev Review, CherryPick/Approved, QA Review Done, Setup Cloud Test Server

#4471 [MM-20058] Team and Channel roles in group configuration screen
  components/admin_console/group_settings/__snapshots__/group_row.test.jsx.snap
  components/admin_console/group_settings/group_details/__snapshots__/group_details.test.jsx.snap
  components/admin_console/group_settings/group_details/__snapshots__/group_teams_and_channels.test.jsx.snap
  components/admin_console/group_settings/group_details/__snapshots__/group_teams_and_channels_row.test.jsx.snap
  components/admin_console/group_settings/group_details/group_details.jsx
  components/admin_console/group_settings/group_details/group_details.test.jsx
  components/admin_console/group_settings/group_details/group_teams_and_channels.jsx
  components/admin_console/group_settings/group_details/group_teams_and_channels.test.jsx
  components/admin_console/group_settings/group_details/group_teams_and_channels_row.jsx
  components/admin_console/group_settings/group_details/group_teams_and_channels_row.test.jsx
  components/admin_console/group_settings/group_details/index.jsx
  components/admin_console/group_settings/group_row.jsx
  components/widgets/admin_console/admin_panel.scss
  components/widgets/admin_console/admin_panel.test.tsx
  components/widgets/admin_console/admin_panel.tsx
  components/widgets/menu/menu_items/menu_item_action.tsx
  e2e/cypress/integration/enterprise/system_console/groups_assign_roles_spec.js
  i18n/en.json
  package-lock.json
  package.json
  sass/components/_groups.scss
Labels: 3: Reviews Complete, QA Review Done

#4535 [MM-21076] Improve dropdown menu wrapping behavior
  components/widgets/menu/menu.scss
  components/widgets/menu/menu_items/__snapshots__/menu_item_toggle_modal_redux.test.tsx.snap
  components/widgets/menu/menu_items/menu_item.scss
  components/widgets/menu/menu_items/menu_item_action.test.tsx
  components/widgets/menu/menu_items/menu_item_action.tsx
  components/widgets/menu/menu_items/menu_item_toggle_modal_redux.test.tsx
  components/widgets/menu/menu_items/menu_item_toggle_modal_redux.tsx
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#4551 MM-21635 fix: not closing channel header modal
  components/edit_channel_header_modal/__snapshots__/edit_channel_header_modal.test.jsx.snap
  components/edit_channel_header_modal/edit_channel_header_modal.jsx
  components/edit_channel_header_modal/edit_channel_header_modal.test.jsx
  components/edit_channel_header_modal/index.js
  components/post_view/channel_intro_message/channel_intro_message.jsx
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#4667 Automated cherry pick of #4551
  components/edit_channel_header_modal/__snapshots__/edit_channel_header_modal.test.jsx.snap
  components/edit_channel_header_modal/edit_channel_header_modal.jsx
  components/edit_channel_header_modal/edit_channel_header_modal.test.jsx
  components/edit_channel_header_modal/index.js
  components/post_view/channel_intro_message/channel_intro_message.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4455 [MM-17155] Deep Linking Landing Page
  components/get_android_app/__snapshots__/get_android_app.test.tsx.snap
  components/get_android_app/get_android_app.test.tsx
  components/get_android_app/get_android_app.tsx
  components/get_android_app/index.ts
  components/get_ios_app/__snapshots__/get_ios_app.test.tsx.snap
  components/get_ios_app/get_ios_app.test.tsx
  components/get_ios_app/get_ios_app.tsx
  components/get_ios_app/index.ts
  components/linking_landing_page/index.tsx
  components/linking_landing_page/linking_landing_page.tsx
  components/root/root.jsx
  i18n/en.json
  images/deep-linking/deeplinking-desktop-img.png
  images/deep-linking/deeplinking-mobile-img.png
  images/logo.svg
  package-lock.json
  package.json
  sass/routes/_get-app.scss
  stores/browser_store.jsx
  types/custom-protocol-detection.d.ts
  utils/constants.jsx
Labels: 3: Reviews Complete, QA Review Done, Setup Cloud Test Server

#4447 [MM-20646][MM-20059]: System Admin can map roles to groups from Channel Configuration screen and Team Configuration screen
  components/admin_console/group_settings/groups_list/__snapshots__/groups_list.test.jsx.snap
  components/admin_console/group_settings/groups_list/groups_list.jsx
  components/admin_console/team_channel_settings/abstract_list.jsx
  components/admin_console/team_channel_settings/channel/details/__snapshots__/channel_details.test.jsx.snap
  components/admin_console/team_channel_settings/channel/details/__snapshots__/channel_groups.test.jsx.snap
  components/admin_console/team_channel_settings/channel/details/channel_details.jsx
  components/admin_console/team_channel_settings/channel/details/channel_details.test.jsx
  components/admin_console/team_channel_settings/channel/details/channel_groups.jsx
  components/admin_console/team_channel_settings/channel/details/channel_groups.test.jsx
  components/admin_console/team_channel_settings/channel/details/index.js
  components/admin_console/team_channel_settings/channel/list/__snapshots__/channel_row.test.jsx.snap
  components/admin_console/team_channel_settings/channel/list/channel_row.jsx
  components/admin_console/team_channel_settings/group/__snapshots__/group_list.test.tsx.snap
  components/admin_console/team_channel_settings/group/__snapshots__/group_row.test.tsx.snap
  components/admin_console/team_channel_settings/group/group_list.test.tsx
  components/admin_console/team_channel_settings/group/group_list.tsx
  components/admin_console/team_channel_settings/group/group_row.test.tsx
  components/admin_console/team_channel_settings/group/group_row.tsx
  components/admin_console/team_channel_settings/group/index.js
  components/admin_console/team_channel_settings/team/details/__snapshots__/team_details.test.jsx.snap
  components/admin_console/team_channel_settings/team/details/__snapshots__/team_groups.test.jsx.snap
  components/admin_console/team_channel_settings/team/details/index.js
  components/admin_console/team_channel_settings/team/details/team_details.jsx
  components/admin_console/team_channel_settings/team/details/team_details.test.jsx
  components/admin_console/team_channel_settings/team/details/team_groups.jsx
  components/admin_console/team_channel_settings/team/details/team_groups.test.jsx
  components/admin_console/team_channel_settings/team/list/__snapshots__/team_row.test.jsx.snap
  components/admin_console/team_channel_settings/team/list/team_row.jsx
  components/toggle_modal_button.jsx
  e2e/cypress/integration/enterprise/system_console/team_and_channel_asign_roles_spec.js
  i18n/en.json
  sass/components/_groups.scss
Labels: 3: Reviews Complete, QA Review Done

#4666 Automated cherry pick of #4661
  components/local_date_time/local_date_time.test.tsx
  components/local_date_time/local_date_time.tsx
  e2e/cypress/integration/messaging/local_date_time_spec.js
Labels: 3: Reviews Complete, AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4655 MM-14322 Created E2E test for a long post with multiple attachments
  components/file_attachment_list/file_attachment_list.jsx
  components/view_image/__snapshots__/image_preview.test.jsx.snap
  components/view_image/image_preview.jsx
  components/view_image/popover_bar/__snapshots__/popover_bar.test.jsx.snap
  components/view_image/popover_bar/popover_bar.jsx
  e2e/cypress/integration/channel/long_post_attachments_spec.js
Labels: 3: Reviews Complete, QA Review Done

#4669 translations PR 20200113
  i18n/de.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 3: Reviews Complete, AutoMerge

#4541 [MM-20613] Treat code pasted from GitHub as a code block
  components/create_comment/create_comment.jsx
  components/create_comment/create_comment.test.jsx
  components/create_post/create_post.jsx
  components/create_post/create_post.test.jsx
  utils/paste.tsx
Labels: 1: UX Review, QA Review Done

#4504 MM-19761 - User autocomplete should match on spaces
  components/suggestion/at_mention_provider/at_mention_provider.jsx
  components/suggestion/at_mention_provider/at_mention_provider.test.jsx
  e2e/cypress/integration/at_mentions/at_mentions_user_spec.js
Labels: 3: Reviews Complete, QA Review Done

#4670 MM-21320 - Updating typing css in RHS
  sass/layout/_sidebar-right.scss
Labels: 3: Reviews Complete, QA Review Done

#4586 MM-17937 - add tests for executeCommand action /leave, /settings, /collapse
  actions/command.js
  actions/command.test.js
Labels: 3: Reviews Complete, AutoMerge, QA Review Done

#4647 MM-21651: Add additional reserved team names
  utils/constants.jsx
Labels: 3: Reviews Complete, Docs/Needed, QA Review Done

#4599 [MM-20061] Add System Admin filter to both LDAP and SAML settings in Admin Console
  components/admin_console/admin_definition.jsx
  i18n/en.json
Labels: 3: Reviews Complete, AutoMerge, QA Review Done

#4547 [MM-21128] Show Show Marketplace labels fetched from server
  components/plugin_marketplace/marketplace_item/__snapshots__/marketplace_item.test.js.snap
  components/plugin_marketplace/marketplace_item/marketplace_item.js
  components/plugin_marketplace/marketplace_item/marketplace_item.test.js
  components/plugin_marketplace/marketplace_modal.js
  e2e/cypress/integration/plugins/marketplace/marketplace_spec.js
  i18n/en.json
Labels: 3: Reviews Complete

#4665 Thread fetching revert
  actions/views/channel.js
  actions/views/channel.test.js
  actions/websocket_actions.jsx
  actions/websocket_actions.test.jsx
  components/permalink_view/actions.js
  components/permalink_view/permalink_view.test.jsx
  components/post_view/post/index.js
  components/post_view/post/index.test.js
  components/rhs_thread/rhs_thread.jsx
  components/rhs_thread/rhs_thread.test.jsx
  package-lock.json
  package.json
Labels: 2: Dev Review, 2: QA Review

#4676 MM-21636 - Updating more modal row css
  sass/components/_modal.scss
Labels: 3: Reviews Complete, QA Review Done

#4628 [MM-19533] Add toasts feature
  actions/global_actions.jsx
  components/post_view/floating_timestamp/floating_timestamp.jsx
  components/post_view/new_messages_below/index.js
  components/post_view/new_messages_below/index.test.js
  components/post_view/new_messages_below/new_messages_below.jsx
  components/post_view/post_list/__snapshots__/post_list.test.jsx.snap
  components/post_view/post_list/index.js
  components/post_view/post_list/post_list.jsx
  components/post_view/post_list/post_list.test.jsx
  components/post_view/post_list_virtualized/post_list_virtualized.jsx
  components/post_view/post_list_virtualized/post_list_virtualized.test.jsx
  components/toast/__snapshots__/toast.test.jsx.snap
  components/toast/toast.jsx
  components/toast/toast.scss
  components/toast/toast.test.jsx
  components/toast_wrapper/index.jsx
  components/toast_wrapper/toast_wrapper.jsx
  components/toast_wrapper/toast_wrapper.test.jsx
  components/widgets/icons/close_icon.jsx
  components/widgets/icons/unread_below_icon.jsx
  e2e/cypress/integration/channel/toast_spec.js
  i18n/en.json
  package-lock.json
  package.json
  reducers/views/channel.js
  utils/constants.jsx
  utils/post_utils.jsx
Labels: 3: Reviews Complete, QA Review Done

#3845 Migrate to typescript 12481
  components/announcement_bar/text_dismissable_bar.jsx
  components/login/login_controller/login_controller.jsx
  components/markdown/markdown.jsx
  components/terms_of_service/terms_of_service.jsx
  package-lock.json
  package.json
  patches/@types+marked+0.6.5.patch
  plugins/export.js
  utils/markdown/index.ts
  utils/markdown/link_only_renderer.test.tsx
  utils/markdown/link_only_renderer.tsx
  utils/markdown/mentionable_renderer.tsx
  utils/markdown/remove_markdown.test.tsx
  utils/markdown/remove_markdown.ts
  utils/markdown/renderer.tsx
  utils/syntax_highlighting.tsx
  utils/text_formatting.test.jsx
  utils/text_formatting.tsx
  utils/text_formatting_at_mentions.test.jsx
  utils/text_formatting_channel_links.test.jsx
  utils/text_formatting_email.test.jsx
  utils/text_formatting_hashtags.test.jsx
  utils/text_formatting_imgs.test.jsx
  utils/text_formatting_links.test.jsx
  utils/text_formatting_mention_highlighting.test.jsx
  utils/text_formatting_search_highlighting.test.jsx
Labels: 3: Reviews Complete, Hacktoberfest, QA Review Done

#4564 MM-19606 - Rework prepackaged plugins
  actions/marketplace.js
  components/admin_console/plugin_management/__snapshots__/plugin_management.test.jsx.snap
  components/admin_console/plugin_management/plugin_management.jsx
  components/admin_console/plugin_management/plugin_management.test.jsx
  components/plugin_marketplace/__snapshots__/marketplace_modal.test.js.snap
  components/plugin_marketplace/marketplace_item/__snapshots__/marketplace_item.test.js.snap
  components/plugin_marketplace/marketplace_item/marketplace_item.js
  components/plugin_marketplace/marketplace_modal.js
  e2e/cypress/integration/plugins/marketplace/marketplace_spec.js
  i18n/en.json
  package-lock.json
  package.json
Labels: 1: PM Review, 3: Reviews Complete

#4633 MM-20627: Update wording in SECURITY.md
  SECURITY.md
Labels: 3: Reviews Complete

#4678 MM-21667 fix redirection on leave channel with subpath
  stores/local_storage_store.jsx
  stores/local_storage_store.test.jsx
Labels: QA Review Done, Setup Cloud Test Server

#4672 MM-21344 - Updating emoji reactions css
  components/post_view/reaction/__snapshots__/reaction.test.jsx.snap
  components/post_view/reaction/reaction.jsx
  sass/layout/_post.scss
Labels: 3: Reviews Complete, QA Review Done

#4604 [Build, Compiler, Refactor] Upgrade typescript and add optional-chaining and nullish-coalescing
  .gitignore
  babel.config.js
  package-lock.json
  package.json
  utils/youtube.js
  utils/youtube.test.js
Labels: 3: Reviews Complete, QA Review Done

#4559 [GH-9502] Add a red dot to browser favicon when there are unread mentions
  components/sidebar/sidebar.jsx
  components/sidebar/sidebar.test.jsx
  images/favicon/favicon-reddot-16x16.png
  images/favicon/favicon-reddot-32x32.png
  images/favicon/favicon-reddot-96x96.png
  images/favicon/redfavicon-16x16.png
  utils/user_agent.tsx
Labels: 3: Reviews Complete, QA Review Done

#4605 MM-18571: Include current user in suggestions
  components/suggestion/at_mention_provider/at_mention_provider.jsx
  components/suggestion/at_mention_provider/at_mention_provider.test.jsx
  components/suggestion/at_mention_provider/at_mention_suggestion.jsx
  components/suggestion/suggestion_box.test.jsx
  i18n/en.json
  sass/components/_mentions.scss
Labels: 3: Reviews Complete, QA Review Done

#4413 MM-16425 Fixes #12614 : Show single image thumbnails in compact view
  components/file_attachment_list/file_attachment_list.jsx
  components/single_image_view/single_image_view.jsx
  e2e/cypress/fixtures/huge-image.jpg
  e2e/cypress/integration/messaging/file_upload_in_center_channel_spec.js
  e2e/cypress/support/ui_commands.js
  sass/components/_files.scss
Labels: 3: Reviews Complete, QA Review Done

#4674 [MM-21277] Update Google Apps Oauth 2 Steps
  components/admin_console/admin_definition.jsx
  i18n/en.json
Labels: 3: Reviews Complete, QA Review Done

#4688 Changed mobile protocol over to mattermost-mobile and removed unused protocol detection
  components/linking_landing_page/linking_landing_page.tsx
  i18n/en.json
Labels: QA Review Done, Setup Cloud Test Server

#4593 MM-20580: Migrate 'components/admin_console/team_channel_settings/channel/list' module and associated tests to TypeScript
  components/admin_console/team_channel_settings/channel/list/__snapshots__/channel_list.test.tsx.snap
  components/admin_console/team_channel_settings/channel/list/__snapshots__/channel_row.test.tsx.snap
  components/admin_console/team_channel_settings/channel/list/channel_list.test.tsx
  components/admin_console/team_channel_settings/channel/list/channel_list.tsx
  components/admin_console/team_channel_settings/channel/list/channel_row.test.tsx
  components/admin_console/team_channel_settings/channel/list/channel_row.tsx
  components/admin_console/team_channel_settings/channel/list/index.ts
Labels: QA Review Done

#4683 [MM-21514] Update package.json Mattermost-Redux incorporate latest changes
  package-lock.json
  package.json
Labels: 3: Reviews Complete, QA Review Done

#4561 MM-12515 - Refactor actions/views/root.js::loadTranslations to have a single point of return
  actions/views/root.js
Labels: 3: Reviews Complete, QA Review Done

#4641 MM-21322 - Show page not found when navigating to missing plugin config page
  components/admin_console/schema_admin_settings.jsx
  components/admin_console/schema_admin_settings.test.jsx
  i18n/en.json
Labels: 3: Reviews Complete, QA Review Done

#3672 MM-13537 Improve the UX of the custom theme text box and color selectors
  components/__snapshots__/color_input.test.tsx.snap
  components/color_input.test.tsx
  components/color_input.tsx
  components/setting_item_max.jsx
  components/user_settings/display/user_settings_theme/__snapshots__/custom_theme_chooser.test.jsx.snap
  components/user_settings/display/user_settings_theme/custom_theme_chooser.jsx
  components/user_settings/display/user_settings_theme/user_settings_theme.jsx
  i18n/en.json
  sass/components/_color-input.scss
  sass/routes/_settings.scss
Labels: 2: Dev Review, QA Review Done

#4692 MM-20349 Improve typing performance
  components/create_post/create_post.jsx
  components/create_post/create_post.test.jsx
  components/rhs_comment/rhs_comment.jsx
  components/rhs_root_post/rhs_root_post.jsx
  components/suggestion/suggestion_box.jsx
  components/suggestion/suggestion_box.test.jsx
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#4673 MM-21392 - Updating tutorial css
  sass/components/_tutorial.scss
Labels: CherryPick/Approved, QA Review Done

#4619 [MM-18787] Remove deprecated lifecycle methods from team settings
  components/member_list_team/member_list_team.jsx
  components/team_general_tab/team_general_tab.jsx
Labels: 3: Reviews Complete, QA Review Done

#4681 Add missing bracket to i18n/en.json that was creating errors on javascript console
  components/toast_wrapper/toast_wrapper.jsx
  i18n/en.json
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#4686 [MM-21484] Set label and value in add groups modal before sending props to multiselect
  components/add_groups_to_channel_modal/add_groups_to_channel_modal.jsx
  components/add_groups_to_team_modal/add_groups_to_team_modal.jsx
  components/more_direct_channels/more_direct_channels.jsx
Labels: 3: Reviews Complete, AutoMerge, CherryPick/Approved, QA Review Done

#4490 MM-20653: Add role drop-down to to chat-facing team groups
  components/channel_groups_manage_modal/channel_groups_manage_modal.jsx
  components/channel_groups_manage_modal/index.js
  components/team_groups_manage_modal/index.js
  components/team_groups_manage_modal/team_groups_manage_modal.jsx
  i18n/en.json
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#4689 [MM-21682] Remove the link between the verification and the notification settings
  components/admin_console/admin_definition.jsx
  i18n/en.json
Labels: 3: Reviews Complete, QA Review Done

#4677 [MM-21081] Stop auto focus of the search bar when opening a reply
  components/channel_header/channel_header.js
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#4695 Automated cherry pick of #4677
  components/channel_header/channel_header.js
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4328 MM-18541 Size list padding dynamically
  package-lock.json
  package.json
  sass/layout/_markdown.scss
  sass/layout/_post.scss
  utils/markdown/index.test.js
  utils/markdown/renderer.tsx
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#4691 MM-20181 - Updating scrollbar on IE RHS
  sass/components/_scrollbar.scss
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#4671 MM-21467 - Updating overflow for dialogs
  sass/layout/_webhooks.scss
Labels: AutoMerge, CherryPick/Approved, QA Review Done

#4631 Fixes #12466 : Migrate 'components/help' module and associated tests to TypeScript
  components/help/components/attaching.tsx
  components/help/components/commands.tsx
  components/help/components/composing.tsx
  components/help/components/formatting.tsx
  components/help/components/mentioning.tsx
  components/help/components/messaging.tsx
  components/help/help_controller.tsx
  components/markdown/markdown.jsx
Labels: 3: Reviews Complete, AutoMerge, QA Review Done

#4694 Automated cherry pick of #4673
  sass/components/_tutorial.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4697 Automated cherry pick of #4671
  sass/layout/_webhooks.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4696 Automated cherry pick of #4691
  sass/components/_scrollbar.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4625 Mm 20561: Updating admin manage roles modal to typescript
  components/admin_console/manage_roles_modal/index.ts
  components/admin_console/manage_roles_modal/manage_roles_modal.tsx
Labels: 3: Reviews Complete, QA Review Done

#4618 [MM-18785] Remove deprecated lifecycle methods from user settings
  components/user_settings/display/user_settings_theme/user_settings_theme.jsx
  components/user_settings/security/user_access_token_section/user_access_token_section.jsx
Labels: 3: Reviews Complete, QA Review Done

#4685 Mattermost allows me to Create or Rename a channel containing a user ID that cannot be opened
  components/channel_layout/channel_identifier_router/actions.js
  components/channel_layout/channel_identifier_router/actions.test.js
  components/channel_layout/channel_identifier_router/index.js
  e2e/cypress/integration/channel/channel_routing_spec.js
Labels: 3: Reviews Complete, AutoMerge, CherryPick/Approved, QA Review Done

#4698 Automated cherry pick of #4685
  components/channel_layout/channel_identifier_router/actions.js
  components/channel_layout/channel_identifier_router/actions.test.js
  components/channel_layout/channel_identifier_router/index.js
  e2e/cypress/integration/channel/channel_routing_spec.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4610 [GH-13515] Migrate 'components/team_members_modal' module and associated tests to TypeScript
  actions/status_actions.jsx
  actions/views/modals.js
  components/member_list_team/index.ts
  components/member_list_team/member_list_team.tsx
  components/permissions_gates/team_permission_gate/__snapshots__/team_permission_gate.test.tsx.snap
  components/permissions_gates/team_permission_gate/index.ts
  components/permissions_gates/team_permission_gate/team_permission_gate.jsx
  components/permissions_gates/team_permission_gate/team_permission_gate.test.tsx
  components/permissions_gates/team_permission_gate/team_permission_gate.tsx
  components/team_members_modal/__snapshots__/team_members_modal.test.tsx.snap
  components/team_members_modal/index.ts
  components/team_members_modal/team_members_modal.test.tsx
  components/team_members_modal/team_members_modal.tsx
  package-lock.json
  package.json
Labels: 3: Reviews Complete, QA Review Done

#4679 Mm 20576: : Migrate 'components/admin_console' module and associated tests to TypeScript
  components/admin_console/__snapshots__/admin_console.test.tsx.snap
  components/admin_console/admin_console.test.tsx
  components/admin_console/admin_console.tsx
  components/admin_console/index.ts
Labels: 3: Reviews Complete, QA Review Done

#4658 Mm 21610 - Uninstall all plugins to make sure test run correctly
  e2e/cypress/integration/plugins/marketplace/marketplace_spec.js
  e2e/cypress/support/api_commands.js
Labels: 3: Reviews Complete, QA Review Done

#4668 MM-21863: fix bool defaults for interactive dialog
  components/interactive_dialog/interactive_dialog.jsx
  components/interactive_dialog/interactive_dialog.test.jsx
Labels: CherryPick/Approved, QA Review Done, Setup Cloud Test Server

#4600 MM-21224: System console shows wrong authentication method
  components/admin_console/system_user_detail/__snapshots__/system_user_detail.test.jsx.snap
  components/admin_console/system_user_detail/index.js
  components/admin_console/system_user_detail/system_user_detail.jsx
  components/admin_console/system_user_detail/system_user_detail.test.jsx
  i18n/en.json
Labels: 1: UX Review, 3: Reviews Complete, AutoMerge, QA Review Done

#4253 MM-19588 WCAG issues related to the Channel Header and its subsections
  components/admin_console/system_users/list/__snapshots__/system_users_list.test.jsx.snap
  components/edit_channel_purpose_modal/__snapshots__/edit_channel_purpose_modal.test.jsx.snap
  components/edit_channel_purpose_modal/edit_channel_purpose_modal.jsx
  components/edit_channel_purpose_modal/edit_channel_purpose_modal.test.jsx
  components/rename_channel_modal/__snapshots__/rename_channel_modal.test.jsx.snap
  components/rename_channel_modal/rename_channel_modal.jsx
  components/search_bar/__snapshots__/search_bar.test.jsx.snap
  components/search_bar/search_bar.jsx
  components/searchable_user_list/searchable_user_list.jsx
  components/textbox/textbox_links.jsx
  components/widgets/icons/message_icon.jsx
Labels: 3: Reviews Complete, QA Review Done

#4700 MM-21007 Don't allow Mark as Unread in archived channels and search
  components/dot_menu/dot_menu.jsx
  components/dot_menu/dot_menu.test.jsx
  components/dot_menu/dot_menu_empty.test.jsx
  components/dot_menu/dot_menu_mobile.test.jsx
  components/dot_menu/index.js
  components/post_view/post/index.js
  components/post_view/post/post.jsx
  components/post_view/post/post.test.js
  components/rhs_comment/index.js
  components/rhs_comment/rhs_comment.jsx
  components/rhs_comment/rhs_comment.test.jsx
  components/rhs_root_post/index.js
  components/rhs_root_post/rhs_root_post.jsx
  components/rhs_root_post/rhs_root_post.test.jsx
  utils/channel_utils.jsx
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#4711 Automated cherry pick of #4700
  components/dot_menu/dot_menu.jsx
  components/dot_menu/dot_menu.test.jsx
  components/dot_menu/dot_menu_empty.test.jsx
  components/dot_menu/dot_menu_mobile.test.jsx
  components/dot_menu/index.js
  components/post_view/post/index.js
  components/post_view/post/post.jsx
  components/post_view/post/post.test.js
  components/rhs_comment/index.js
  components/rhs_comment/rhs_comment.jsx
  components/rhs_comment/rhs_comment.test.jsx
  components/rhs_root_post/index.js
  components/rhs_root_post/rhs_root_post.jsx
  components/rhs_root_post/rhs_root_post.test.jsx
  utils/channel_utils.jsx
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4708 Fix failing test on custom themes
  e2e/cypress/integration/account_settings/display/theme/custom_theme_color_picker_spec.js
  e2e/cypress/integration/account_settings/display/theme/custom_theme_sidebar_styles_spec.js
Labels: 3: Reviews Complete, QA Review Done

#4648 MM-21558: Add Invite More button
  components/invitation_modal/__snapshots__/invitation_modal_confirm_step.test.jsx.snap
  components/invitation_modal/invitation_modal.jsx
  components/invitation_modal/invitation_modal_confirm_step.jsx
  components/invitation_modal/invitation_modal_confirm_step.scss
  components/invitation_modal/invitation_modal_confirm_step.test.jsx
  e2e/cypress/integration/team/invite_members_spec.js
  e2e/cypress/support/api_commands.js
  i18n/en.json
Labels: 3: Reviews Complete, QA Review Done

#4720 MM-21213 - Updating max height for search popoever
  sass/components/_popover.scss
Labels: 3: Reviews Complete, QA Review Done

#4707 Automated cherry pick of #4668
  components/interactive_dialog/interactive_dialog.jsx
  components/interactive_dialog/interactive_dialog.test.jsx
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4712 [MM-21979] Fix incorrect placeholder prop for searchable user list
  components/searchable_user_list/searchable_user_list.jsx
Labels: 3: Reviews Complete, QA Review Done

#4709 Fix message bullets and email notification tests
  e2e/cypress/integration/channel/message_bullets_spec.js
  e2e/cypress/integration/email/mention_email_notification_spec.js
Labels: 3: Reviews Complete

#4659 MM-20581 Migrate 'components/admin_console/team_channel_settings/channel/details' module and associated tests to TypeScript
  components/admin_console/blockable_link/blockable_link.tsx
  components/admin_console/team_channel_settings/channel/details/__snapshots__/channel_details.test.tsx.snap
  components/admin_console/team_channel_settings/channel/details/__snapshots__/channel_groups.test.tsx.snap
  components/admin_console/team_channel_settings/channel/details/__snapshots__/channel_modes.test.tsx.snap
  components/admin_console/team_channel_settings/channel/details/__snapshots__/channel_profile.test.tsx.snap
  components/admin_console/team_channel_settings/channel/details/channel_details.test.tsx
  components/admin_console/team_channel_settings/channel/details/channel_details.tsx
  components/admin_console/team_channel_settings/channel/details/channel_groups.jsx
  components/admin_console/team_channel_settings/channel/details/channel_groups.test.tsx
  components/admin_console/team_channel_settings/channel/details/channel_groups.tsx
  components/admin_console/team_channel_settings/channel/details/channel_modes.jsx
  components/admin_console/team_channel_settings/channel/details/channel_modes.test.tsx
  components/admin_console/team_channel_settings/channel/details/channel_modes.tsx
  components/admin_console/team_channel_settings/channel/details/channel_profile.jsx
  components/admin_console/team_channel_settings/channel/details/channel_profile.test.tsx
  components/admin_console/team_channel_settings/channel/details/channel_profile.tsx
  components/admin_console/team_channel_settings/group/group_list.tsx
  components/widgets/admin_console/admin_panel.tsx
Labels: 3: Reviews Complete, QA Review Done

#4657 MM-16734 UI Automation Replying to older bot post with attachment pretext
  e2e/cypress/integration/channel/message_reply_pretext_spec.js
  e2e/cypress/plugins/index.js
  e2e/cypress/plugins/post_bot_message.js
  e2e/cypress/support/api_commands.js
  e2e/cypress/support/task_commands.js
Labels: QA Review Done

#4710 MM-21933 Fix toast banner delays
  components/post_view/post_list_virtualized/post_list_virtualized.jsx
  components/post_view/post_list_virtualized/post_list_virtualized.test.jsx
  components/toast/toast.jsx
  components/toast/toast.scss
  components/toast/toast.test.jsx
  components/toast_wrapper/toast_wrapper.jsx
  components/toast_wrapper/toast_wrapper.test.jsx
  e2e/cypress/integration/channel/toast_spec.js
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done, Setup Cloud Test Server

#4730 Automated cherry pick of #4710
  components/post_view/post_list_virtualized/post_list_virtualized.jsx
  components/post_view/post_list_virtualized/post_list_virtualized.test.jsx
  components/toast/toast.jsx
  components/toast/toast.scss
  components/toast/toast.test.jsx
  components/toast_wrapper/toast_wrapper.jsx
  components/toast_wrapper/toast_wrapper.test.jsx
  e2e/cypress/integration/channel/toast_spec.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4702 MM-21721 Fix FullScreenModal not supporting refs
  components/widgets/modals/full_screen_modal.tsx
Labels: CherryPick/Approved, QA Review Done

#4684 [MM-21789] Update role on initial add of group to a team or channel
  components/admin_console/team_channel_settings/channel/details/channel_details.tsx
  components/admin_console/team_channel_settings/team/details/team_details.jsx
  e2e/cypress/integration/enterprise/system_console/team_and_channel_asign_roles_spec.js
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#4740 Automated cherry pick of #4684
  components/admin_console/team_channel_settings/channel/details/channel_details.jsx
  components/admin_console/team_channel_settings/team/details/team_details.jsx
  e2e/cypress/integration/enterprise/system_console/team_and_channel_asign_roles_spec.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4687 MM-19606 - Improved AutomaticPrepackagedPlugins setting help text
  components/admin_console/plugin_management/__snapshots__/plugin_management.test.jsx.snap
  components/admin_console/plugin_management/plugin_management.jsx
  i18n/en.json
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#4735 Automated cherry pick of #4702
  components/widgets/modals/full_screen_modal.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4480 [MM-18531] Added Feature to Close Channel via Direct Message
  components/channel_header_dropdown/__snapshots__/channel_header_dropdown.test.jsx.snap
  components/channel_header_dropdown/channel_header_dropdown_items.js
  components/channel_header_dropdown/menu_items/close_direct_channel/__snapshots__/close_direct_channel.test.js.snap
  components/channel_header_dropdown/menu_items/close_direct_channel/close_direct_channel.js
  components/channel_header_dropdown/menu_items/close_direct_channel/close_direct_channel.test.js
  components/channel_header_dropdown/menu_items/close_direct_channel/index.js
  i18n/en.json
Labels: 3: Reviews Complete, QA Review Done

#4741 Fix e2e for tutorial navigation and interactive menu
  e2e/cypress/integration/interactive_menu/basic_options_spec.js
  e2e/cypress/integration/login/tutorial_navigation_and_links_spec.js
  e2e/cypress/support/task_commands.js
Labels: 3: Reviews Complete

#4729 Revert to mattermost:// protocol for mobile and to store app if that fails
  components/linking_landing_page/linking_landing_page.tsx
Labels: 3: Reviews Complete, CherryPick/Approved
