Repository mattermost/mattermost-webapp, pull requests merged in 2020-07, with the labels that each got.

#5811 Cypress/E2E: Fix failing tests in Okta login flow
  e2e/cypress/support/api_commands.js
Labels: 4: Reviews Complete

#5824 MM-26069 Cypress test for MM-T2029 - Setup for incoming webhook
  e2e/cypress/integration/integrations/incoming_webhook/disallow_username_profile_override_spec.js
  e2e/cypress/integration/integrations/incoming_webhook/helpers.js
  e2e/cypress/integration/integrations/incoming_webhook/setup_incoming_webhook_spec.js
Labels: 2: Dev Review, 3: QA Review

#5816 MM-26339 - Add context and CommandArgs to dynamic autocomplete calls
  components/create_comment/__snapshots__/create_comment.test.jsx.snap
  components/create_comment/create_comment.jsx
  components/suggestion/command_provider.jsx
  components/textbox/textbox.tsx
  package-lock.json
  package.json
Labels: 2: Dev Review

#5826 MM-26074 Cypress test for MM-T270 and MM-T269 - No Matches for Autocomplete
  e2e/cypress/integration/account_settings/display/channel_display_mode_spec.js
  e2e/cypress/integration/messaging/no_matches_for_autocomplete_spec.js
Labels: 4: Reviews Complete

#5829 MM-26074 Cypress Test for MM-T305 - Account Settings are not autosaved
  e2e/cypress/integration/account_settings/sidebar/channel_switcher_spec.js
Labels: 4: Reviews Complete

#5830 MM-26074 Cypress test for MM-T2098 and MM-T2096 - Clock Display Settings
  e2e/cypress/integration/account_settings/display/clock_display_mode_spec.js
Labels: 4: Reviews Complete

#5831 MM-26075 Standardized Cypress API commands - apiGetTeamsForUser, apiAddUserToTeam and apiGetUsersNotInTeam
  e2e/cypress/integration/enterprise/ldap_group/search_channels_spec.js
  e2e/cypress/integration/system_console/group_configuration_spec.js
  e2e/cypress/integration/team_settings/teammates_pagination_spec.js
  e2e/cypress/integration/team_settings/teams_spec.js
  e2e/cypress/support/api/team.d.ts
  e2e/cypress/support/api/team.js
  e2e/cypress/support/api/user.d.ts
  e2e/cypress/support/api/user.js
  e2e/cypress/support/index.js
Labels: 4: Reviews Complete

#5822 MM-26512 Fix type of SettingItemMin describe props
  components/setting_item_min/setting_item_min.tsx
  components/user_settings/sidebar/__snapshots__/user_settings_sidebar.test.tsx.snap
  components/user_settings/sidebar/user_settings_sidebar.test.tsx
  components/user_settings/sidebar/user_settings_sidebar.tsx
Labels: 4: Reviews Complete

#5835 MM-26597/MM-26672/MM-26616/MM-26605 Properly forward ref to Textbox
  components/edit_post_modal/edit_post_modal.jsx
  components/rhs_comment/index.js
  components/rhs_root_post/index.js
  components/textbox/index.ts
Labels: 4: Reviews Complete, AutoMerge

#5779 Get trial directly from feature discovery
  actions/admin_actions.jsx
  components/admin_console/__snapshots__/admin_console.test.tsx.snap
  components/admin_console/admin_definition.jsx
  components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.jsx.snap
  components/admin_console/feature_discovery/__snapshots__/feature_discovery.test.tsx.snap
  components/admin_console/feature_discovery/feature_discovery.scss
  components/admin_console/feature_discovery/feature_discovery.test.tsx
  components/admin_console/feature_discovery/feature_discovery.tsx
  components/admin_console/feature_discovery/index.tsx
  components/admin_console/feature_discovery/ldap.tsx
  components/admin_console/feature_discovery/saml.tsx
  components/admin_console/license_settings/license_settings.jsx
  components/invitation_modal/invitation_modal_members_step.scss
  i18n/en.json
  sass/routes/_admin-console.scss
  utils/admin_console_index.jsx
  utils/admin_console_index.test.jsx
Labels: 4: Reviews Complete, CherryPick/Approved

#5796 changing license renewal link to point to new renewal webpage
  components/announcement_bar/configuration_bar/__snapshots__/configuration_bar.test.jsx.snap
  components/announcement_bar/configuration_bar/configuration_bar.jsx
Labels: 2: Dev Review, 3: QA Review

#5804 Update NOTICE.txt
  NOTICE.txt
Labels: AutoMerge, CherryPick/Approved

#5837 Added Cypress test MM-T1414 and MM-T1417
  e2e/cypress/integration/enterprise/guest_accounts/guest_experience_ui_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/guest_invitation_ui_spec.js
  e2e/cypress/support/external_commands.d.ts
  e2e/cypress/support/external_commands.js
  e2e/cypress/support/index.js
  e2e/cypress/support/task_commands.js
Labels: 4: Reviews Complete

#5853 MM-26627 Add channels to sidebar when the user is invited to them
  actions/websocket_actions.jsx
  utils/constants.jsx
Labels: 4: Reviews Complete

#5838 Fix random dev mode warnings
  components/create_comment/__snapshots__/create_comment.test.jsx.snap
  components/create_comment/create_comment.jsx
  components/favicon_title_handler/favicon_title_handler.tsx
  components/status_dropdown/status_dropdown.jsx
  components/toggle_modal_button_redux/toggle_modal_button_redux.jsx
Labels: 4: Reviews Complete

#5812 [MM-21993] Fixed center channel flicker with light theme when loading
  utils/utils.jsx
Labels: 4: Reviews Complete

#5832 Cypress/E2E: Fix group config and search channels
  e2e/cypress/integration/enterprise/ldap_group/search_channels_spec.js
  e2e/cypress/integration/system_console/group_configuration_spec.js
Labels: 4: Reviews Complete

#5836 MM-25069 Cypress/E2E for MM-T619 Webhook with @-mention, username and profile pic and basic formatting
  e2e/cypress/integration/integrations/incoming_webhook/basic_formatting_spec.js
  e2e/cypress/integration/interactive_menu/basic_options_spec.js
  e2e/cypress/integration/interactive_menu/select_with_keys_spec.js
  e2e/cypress/integration/interactive_menu/slack_parsing_message_button_spec.js
  e2e/cypress/support/task_commands.js
Labels: 4: Reviews Complete

#5840 MM-20537 Migrate 'components/header_footer_template' module to Typescript.
  components/header_footer_template/__snapshots__/header_footer_template.test.tsx.snap
  components/header_footer_template/header_footer_template.test.tsx
  components/header_footer_template/header_footer_template.tsx
  components/header_footer_template/index.ts
Labels: 4: Reviews Complete

#5818 MM-26573 Support variations for one-byte emojis
  utils/text_formatting.test.jsx
  utils/text_formatting.tsx
Labels: 4: Reviews Complete, CherryPick/Approved

#5864 Automated cherry pick of #5818
  utils/text_formatting.test.jsx
  utils/text_formatting.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5852 MM-26669 Cypress/E2E: Update clock display tests to include nth post
  e2e/cypress/integration/account_settings/display/clock_display_mode_spec.js
Labels: 4: Reviews Complete

#5857 [MM-23358] Cypress test for "CTRL/CMD+K - Open private channel using arrow keys and Enter"
  e2e/cypress/integration/messaging/private_channel_open_spec.js
Labels: 4: Reviews Complete

#5845 [MM-26605] Forward references into SearchChannelSuggestion and SwitchChannelSuggestion to allow scrolling during arrow navigation
  components/suggestion/search_channel_suggestion/index.js
  components/suggestion/suggestion_box.jsx
  components/suggestion/switch_channel_provider.jsx
Labels: 4: Reviews Complete

#5844 [MM-26610] Fix the crash when switching teams
  components/rhs_thread/index.ts
  components/rhs_thread/rhs_thread.tsx
Labels: 4: Reviews Complete

#5642 MM-22706 Don't set user online when responding to push notification
  actions/websocket_actions.jsx
  actions/websocket_actions.test.jsx
Labels: 4: Reviews Complete

#5850 Added Cypress tests MM-T1410, MM-T1415 and MM-T1419
  e2e/cypress/integration/enterprise/guest_accounts/guest_identification_ui_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/guest_invitation_ui_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/system_console_guest_access_ui_spec.js
Labels: 4: Reviews Complete

#5862 Cypress/E2E: Promote and demote tests
  e2e/cypress/integration/account_settings/display/theme/custom_theme_color_picker_spec.js
  e2e/cypress/integration/account_settings/display/theme/custom_theme_sidebar_styles_spec.js
  e2e/cypress/integration/commands/leave_channel_spec.js
  e2e/cypress/integration/enterprise/extend_session/email_login_activity_spec.js
  e2e/cypress/integration/enterprise/ldap_group/group_mentions_spec.js
  e2e/cypress/integration/enterprise/ldap_group/groups_assign_roles_spec.js
  e2e/cypress/integration/enterprise/ldap_group/search_channels_spec.js
  e2e/cypress/integration/enterprise/system_console/team_members_spec.js
  e2e/cypress/integration/integrations/incoming_webhook/setup_incoming_webhook_spec.js
  e2e/cypress/integration/messaging/at_mentions_spec.js
  e2e/cypress/integration/messaging/channel_read_after_permalink_spec.js
  e2e/cypress/integration/messaging/date_separator_spec.js
  e2e/cypress/integration/messaging/focus_move_spec.js
  e2e/cypress/integration/messaging/header_spec.js
  e2e/cypress/integration/messaging/input_box_expands_spec.js
  e2e/cypress/integration/messaging/local_date_time_spec.js
  e2e/cypress/integration/messaging/message_permalink_spec.js
  e2e/cypress/integration/messaging/permalink_loading_indicator_spec.js
  e2e/cypress/integration/messaging/permalink_message_edit_spec.js
  e2e/cypress/integration/messaging/send_message_via_profile_popover_spec.js
  e2e/cypress/integration/multi_team_and_dm/existing_channel_name_spec.js
  e2e/cypress/integration/search/post_search_display_spec.js
  e2e/cypress/integration/system_console/cluster_spec.js
  e2e/cypress/integration/visual_regression/system_console/about_section_spec.js
  e2e/cypress/integration/visual_regression/system_console/authentication_section_spec.js
  e2e/cypress/integration/visual_regression/system_console/compliance_section_spec.js
  e2e/cypress/integration/visual_regression/system_console/environment_section_spec.js
Labels: 4: Reviews Complete

#5867 Cypress/E2E: fix failing tests due to search-input test ID change
  e2e/cypress/integration/enterprise/ldap_group/team_and_channel_assign_roles_spec.js
  e2e/cypress/integration/enterprise/system_console/archived_channels_spec.js
  e2e/cypress/integration/enterprise/system_console/channel_moderation/helpers.js
  e2e/cypress/integration/enterprise/system_console/channel_moderation/system_config_spec.js
  e2e/cypress/integration/enterprise/teams/search_teams_spec.js
Labels: 4: Reviews Complete

#5866 [MM-24301] Added translation strings for new Direct Messages and Channels category headers
  components/sidebar/sidebar_category/sidebar_category.tsx
  i18n/de.json
  i18n/en.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 4: Reviews Complete

#5856 MM-26512 Update Jest to fix unexpected outcome on unit tests
  actions/post_actions.test.js
  actions/user_actions.test.js
  actions/views/create_comment.test.jsx
  actions/views/root.test.js
  components/__snapshots__/profile_picture.test.tsx.snap
  components/admin_console/admin_sidebar/admin_sidebar.test.jsx
  components/admin_console/permission_schemes_settings/guest_permissions_tree/__snapshots__/guest_permissions_tree.test.jsx.snap
  components/admin_console/permission_schemes_settings/permissions_tree/__snapshots__/permissions_tree.test.jsx.snap
  components/admin_console/team_channel_settings/channel/list/__snapshots__/channel_list.test.tsx.snap
  components/admin_console/team_channel_settings/team/list/__snapshots__/team_list.test.jsx.snap
  components/analytics/doughnut_chart.test.tsx
  components/announcement_bar/__snapshots__/text_dismissable_bar.test.jsx.snap
  components/channel_header_mobile/channel_info_button/__snapshots__/channel_info_button.test.js.snap
  components/dot_menu/dot_menu.test.jsx
  components/dot_menu/dot_menu_empty.test.jsx
  components/dot_menu/dot_menu_mobile.test.jsx
  components/favicon_title_handler/favicon_title_handler.test.jsx
  components/file_attachment/file_attachment.test.tsx
  components/file_upload/file_upload.test.jsx
  components/legacy_sidebar/sidebar.test.jsx
  components/legacy_sidebar/sidebar_channel/sidebar_channel.test.jsx
  components/legacy_sidebar/sidebar_channel_button_or_link/sidebar_channel_button_or_link.test.jsx
  components/more_channels/__snapshots__/more_channels.test.jsx.snap
  components/more_channels/more_channels.test.jsx
  components/popover_list_members/popover_list_members.test.jsx
  components/post_markdown/__snapshots__/post_markdown.test.jsx.snap
  components/post_view/message_attachments/message_attachment/__snapshots__/message_attachment.test.jsx.snap
  components/rhs_card/__snapshots__/rhs_card.test.jsx.snap
  components/search_bar/search_bar.test.jsx
  components/select_team/components/__snapshots__/select_team_item.test.jsx.snap
  components/sidebar/sidebar_channel/sidebar_channel_link/sidebar_channel_link.test.tsx
  components/suggestion/suggestion_box.test.jsx
  components/user_profile/__snapshots__/user_profile.test.jsx.snap
  components/user_settings/notifications/desktop_notification_settings.test.jsx
  components/widgets/admin_console/admin_panel_with_link.test.tsx
  components/widgets/loading/loading_wrapper.test.tsx
  components/widgets/menu/menu.test.tsx
  package-lock.json
  package.json
  utils/__snapshots__/message_html_to_component.test.jsx.snap
Labels: 4: Reviews Complete

#5848 [MM-26411] - Show copy link for private channels
  components/sidebar/sidebar_channel/sidebar_channel_menu/__snapshots__/sidebar_channel_menu.test.tsx.snap
  components/sidebar/sidebar_channel/sidebar_channel_menu/sidebar_channel_menu.test.tsx
  components/sidebar/sidebar_channel/sidebar_channel_menu/sidebar_channel_menu.tsx
Labels: 4: Reviews Complete, QA Review Done

#5859 [MM-26450] - Pass correct permissions to channel member
  components/sidebar/sidebar_channel/sidebar_channel_menu/index.ts
Labels: 4: Reviews Complete, QA Review Done

#5872 Fix i18n merge conflicts
  i18n/ko.json
  i18n/nl.json
  i18n/ro.json
  i18n/tr.json
Labels: 4: Reviews Complete

#5871 MM-26074 Cypress Test for MM-T301 - Timezone Display mode
  e2e/cypress/integration/account_settings/display/clock_display_mode_spec.js
  e2e/cypress/integration/account_settings/display/timezone_display_mode_spec.js
  e2e/package-lock.json
  e2e/package.json
Labels: 4: Reviews Complete

#5858 MM-26685 enable redux setting to emit rudder events when url and key is set
  components/root/root.jsx
  components/root/root.test.jsx
  package-lock.json
  package.json
Labels: 4: Reviews Complete

#5819 Add S3 prefix configuration to the admin console
  components/admin_console/admin_definition.jsx
  i18n/en.json
Labels: 4: Reviews Complete

#5886 MM-26069 Cypress test: Incoming webhook - Payload username and profile picture override in-app settings
  e2e/cypress/integration/integrations/incoming_webhook/inapp_username_profile_override_spec.js
Labels: 4: Reviews Complete

#5847 Updated the message shown for deactivated account
  components/channel_view/channel_view.jsx
  components/rhs_thread/rhs_thread.tsx
  i18n/en.json
Labels: 4: Reviews Complete, QA Review Done

#5875 [MM-26594] - Don't delete channel category when there are no channels…
  components/sidebar/sidebar_category/sidebar_category.tsx
Labels: 4: Reviews Complete

#5881 MM-26072: Added few cypress tests for Guest Account feature
  e2e/cypress/integration/enterprise/guest_accounts/guest_experience_ui_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/member_invitation_ui_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/system_console_guest_access_ui_spec.js
Labels: 4: Reviews Complete

#5827 [MM-20504] Migrate channel_identifier_router to ts
  components/channel_layout/channel_identifier_router/actions.test.ts
  components/channel_layout/channel_identifier_router/actions.ts
  components/channel_layout/channel_identifier_router/channel_identifier_router.test.tsx
  components/channel_layout/channel_identifier_router/channel_identifier_router.tsx
  components/channel_layout/channel_identifier_router/index.ts
Labels: 4: Reviews Complete

#5891 MM-26069 Cypress test for MM-T623 Lock to this channel on webhook configuration works
  e2e/cypress/integration/integrations/incoming_webhook/setting_spec.js
Labels: 4: Reviews Complete

#5896 MM-26885 Fix for client4 import
  components/root/root.jsx
  components/root/root.test.jsx
Labels: 4: Reviews Complete

#5865 [MM-26468][MM-26483] Progress Bar Common Component/Sidebar Next Steps Component
  components/progress_bar.scss
  components/progress_bar.test.tsx
  components/progress_bar.tsx
  components/sidebar/__snapshots__/sidebar.test.tsx.snap
  components/sidebar/sidebar.tsx
  components/sidebar/sidebar_next_steps/sidebar_next_steps.scss
  components/sidebar/sidebar_next_steps/sidebar_next_steps.tsx
  i18n/en.json
Labels: 4: Reviews Complete, Setup Cloud Test Server

#5892 MM-26069 Cypress test for MM-T621 Override username and profile picture - remove overrides from payload
  e2e/cypress/integration/integrations/incoming_webhook/inapp_username_profile_override_spec.js
Labels: 4: Reviews Complete, AutoMerge

#5823 [MM-26465] Background and general layout for cloud onboarding
  components/channel_view/channel_view.jsx
  components/channel_view/channel_view.test.jsx
  components/channel_view/index.js
  components/next_steps_view/__snapshots__/next_steps_view.test.tsx.snap
  components/next_steps_view/index.ts
  components/next_steps_view/next_steps_view.scss
  components/next_steps_view/next_steps_view.test.tsx
  components/next_steps_view/next_steps_view.tsx
  i18n/en.json
  images/cloud-logos/professional.svg
  images/getting-started.svg
  images/onboarding-bg.svg
  utils/constants.jsx
Labels: 4: Reviews Complete, Setup Cloud Test Server

#5878 [MM-26349][MM-26408] - Fix menu z-index issues
  sass/layout/_sidebar-left.scss
Labels: 4: Reviews Complete, AutoMerge

#5895 [MM-26782] Webapp/Admin console: Next page of Teams does not respect search results
  components/admin_console/team_channel_settings/team/list/team_list.jsx
Labels: 4: Reviews Complete

#5885 MM-26074 Cypress Test for MM-T713 - Correct time format for clock mode
  e2e/cypress/fixtures/date_time_format.js
  e2e/cypress/integration/account_settings/display/clock_display_mode_spec.js
  e2e/cypress/integration/account_settings/display/timezone_display_mode_spec.js
  e2e/cypress/integration/messaging/local_date_time_spec.js
  e2e/cypress/support/api/index.js
  e2e/cypress/support/api/preference.d.ts
  e2e/cypress/support/api/preference.js
  e2e/cypress/support/api_commands.js
  e2e/cypress/support/index.d.ts
Labels: 4: Reviews Complete

#5843 MM-26609 Create a new single entry point to get help, with a new "Ask Mattermost Community" menu item
  components/channel_header/__snapshots__/channel_header.test.jsx.snap
  components/channel_header/channel_header.js
  components/channel_header/components/user_guide_dropdown/__snapshots__/user_guide_dropdown.test.jsx.snap
  components/channel_header/components/user_guide_dropdown/index.ts
  components/channel_header/components/user_guide_dropdown/user_guide_dropdown.test.jsx
  components/channel_header/components/user_guide_dropdown/user_guide_dropdown.tsx
  components/search_bar/search_bar.jsx
  components/widgets/icons/user_guide_icon.jsx
  e2e/cypress/integration/menus/user_guide_help_spec.js
  i18n/en.json
  sass/components/_channel-header__icon.scss
  sass/components/_search.scss
  sass/responsive/_desktop.scss
  sass/responsive/_tablet.scss
Labels: QA Review Done

#5877 MM-26620 Add system console setting to disable ask the community link
  components/admin_console/admin_definition.jsx
  components/channel_header/components/user_guide_dropdown/__snapshots__/user_guide_dropdown.test.jsx.snap
  components/channel_header/components/user_guide_dropdown/index.ts
  components/channel_header/components/user_guide_dropdown/user_guide_dropdown.test.jsx
  components/channel_header/components/user_guide_dropdown/user_guide_dropdown.tsx
  e2e/cypress/integration/menus/user_guide_help_spec.js
  i18n/en.json
  package-lock.json
  package.json
Labels: 4: Reviews Complete, QA Review Done

#5909 Cypress/E2E: fix failing specs
  e2e/cypress/integration/channel/channel_mention_autocomplete_spec.js
  e2e/cypress/integration/commands/leave_channel_spec.js
  e2e/cypress/integration/emoji/react_to_last_message_shortcut_spec.js
  e2e/cypress/integration/emoji/recently_used_emoji_spec.js
Labels: 4: Reviews Complete

#5906 Cypress/E2E: fix sidebar channel collapsing
  e2e/cypress/integration/channel_sidebar/category_collapsing_unread_filter_spec.js
Labels: 4: Reviews Complete

#5905 Cypress/E2E: fix failing tests on drag and drop, and user guide menu
  e2e/cypress/fixtures/partial_default_config.json
  e2e/cypress/integration/channel_sidebar/drag_and_drop_spec.js
  e2e/cypress/integration/menus/user_guide_help_spec.js
Labels: 4: Reviews Complete

#5870 [MM-26762] Archived Channels are not shown in the System Console > Channels page
  components/admin_console/team_channel_settings/channel/list/channel_list.tsx
  components/admin_console/team_channel_settings/channel/list/index.ts
Labels: 4: Reviews Complete

#5672 [MM-24323] Fixing alignment issues on the mobile new channel sidebar
  sass/responsive/_mobile.scss
Labels: 4: Reviews Complete

#5897 MM-26628 Fix for empty space for new category in mobile view
  sass/layout/_sidebar-left.scss
Labels: 4: Reviews Complete

#5861 [MM-26480] Card/Accordion Common Component
  components/accordion.scss
  components/accordion.tsx
  components/card/__snapshots__/card.test.tsx.snap
  components/card/card.scss
  components/card/card.test.tsx
  components/card/card.tsx
  components/card/card_body.tsx
  components/card/card_header.tsx
  components/next_steps_view/__snapshots__/next_steps_view.test.tsx.snap
  components/next_steps_view/next_steps_view.scss
  components/next_steps_view/next_steps_view.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server

#5882 [MM-25264] [MM-25265] Create and apply filter component to user grids
  actions/views/search.js
  components/add_users_to_team_modal/index.ts
  components/admin_console/data_grid/data_grid.scss
  components/admin_console/data_grid/data_grid.tsx
  components/admin_console/data_grid/data_grid_search.tsx
  components/admin_console/filter/filter.scss
  components/admin_console/filter/filter.tsx
  components/admin_console/filter/filter_checkbox.tsx
  components/admin_console/filter/filter_list.tsx
  components/admin_console/team_channel_settings/channel/details/channel_members/__snapshots__/channel_members.test.tsx.snap
  components/admin_console/team_channel_settings/channel/details/channel_members/channel_members.test.tsx
  components/admin_console/team_channel_settings/channel/details/channel_members/channel_members.tsx
  components/admin_console/team_channel_settings/channel/details/channel_members/index.ts
  components/admin_console/team_channel_settings/team/details/team_members/__snapshots__/team_members.test.tsx.snap
  components/admin_console/team_channel_settings/team/details/team_members/index.ts
  components/admin_console/team_channel_settings/team/details/team_members/team_members.test.tsx
  components/admin_console/team_channel_settings/team/details/team_members/team_members.tsx
  components/admin_console/user_grid/__snapshots__/user_grid.test.tsx.snap
  components/admin_console/user_grid/user_grid.test.tsx
  components/admin_console/user_grid/user_grid.tsx
  components/textbox/index.ts
  components/widgets/admin_console/admin_panel.scss
  components/widgets/admin_console/admin_panel.test.tsx
  components/widgets/admin_console/admin_panel.tsx
  i18n/en.json
  package-lock.json
  package.json
  reducers/views/search.js
  reducers/views/search.test.js
  sass/admin_console_base/_module.scss
  sass/admin_console_base/_sys_css_variables.scss
  sass/styles.scss
  types/store/index.ts
  utils/constants.jsx
Labels: 4: Reviews Complete

#5921 Lock CI
  .circleci/config.yml
Labels: AutoMerge

#5498 [MM-22853] Add flag icon to post hover menu, update pinned & flagged post styling
  components/channel_header/components/__snapshots__/header_icon_wrapper.test.js.snap
  components/channel_header/components/header_icon_wrapper.js
  components/common/comment_icon.tsx
  components/dot_menu/__snapshots__/dot_menu.test.jsx.snap
  components/dot_menu/dot_menu.jsx
  components/main_menu/__snapshots__/main_menu.test.jsx.snap
  components/main_menu/main_menu.jsx
  components/post_view/post/__snapshots__/post.test.js.snap
  components/post_view/post/index.js
  components/post_view/post/post.jsx
  components/post_view/post/post.test.js
  components/post_view/post_flag_icon/__snapshots__/post_flag_icon.test.js.snap
  components/post_view/post_flag_icon/post_flag_icon.js
  components/post_view/post_flag_icon/post_flag_icon.test.js
  components/post_view/post_info/__snapshots__/post_info.test.jsx.snap
  components/post_view/post_info/post_info.jsx
  components/post_view/post_info/post_info.test.jsx
  components/post_view/post_pre_header/__snapshots__/post_pre_header.test.tsx.snap
  components/post_view/post_pre_header/index.js
  components/post_view/post_pre_header/post_pre_header.test.tsx
  components/post_view/post_pre_header/post_pre_header.tsx
  components/rhs_card_header/rhs_card_header.jsx
  components/rhs_comment/__snapshots__/rhs_comment.test.jsx.snap
  components/rhs_comment/rhs_comment.jsx
  components/rhs_comment/rhs_comment.test.jsx
  components/rhs_header_post/rhs_header_post.jsx
  components/rhs_root_post/__snapshots__/rhs_root_post.test.jsx.snap
  components/rhs_root_post/rhs_root_post.jsx
  components/rhs_root_post/rhs_root_post.test.jsx
  components/search_results/search_results.jsx
  components/search_results_item/__snapshots__/search_results_item.test.jsx.snap
  components/search_results_item/search_results_item.jsx
  components/search_results_item/search_results_item.test.jsx
  components/widgets/icons/flag_icon.jsx
  components/widgets/icons/flag_icon_filled.jsx
  e2e/cypress/integration/accessibility/accessibility_buttons_spec.js
  e2e/cypress/integration/accessibility/accessibility_post_spec.js
  e2e/cypress/integration/emoji/react_to_last_message_shortcut_spec.js
  e2e/cypress/integration/messaging/post_header_spec.js
  e2e/cypress/integration/messaging/post_pre_header_spec.js
  i18n/en.json
  plugins/test/__snapshots__/main_menu_action.test.jsx.snap
  sass/components/_channel-header__icon.scss
  sass/components/_icons.scss
  sass/components/_post-menu.scss
  sass/components/_post-right.scss
  sass/components/_post.scss
  sass/components/_search.scss
  sass/layout/_headers.scss
  sass/layout/_sidebar-right.scss
  sass/responsive/_mobile.scss
  sass/responsive/_tablet.scss
  utils/post_utils.jsx
  utils/post_utils.test.jsx
  utils/utils.jsx
Labels: 4: Reviews Complete, CherryPick/Approved

#5860 MM-26718 Fix the perf of animation on DM modal
  components/more_direct_channels/__snapshots__/more_direct_channels.test.jsx.snap
  components/more_direct_channels/more_direct_channels.test.jsx
  components/more_direct_channels/more_direct_channels.tsx
Labels: 4: Reviews Complete, CherryPick/Approved

#5930 [E2E] Fix test M18679 - Mobile view: Post options menu (3-dots) is present on a reply post in RHS
  e2e/cypress/integration/messaging/post_options_menu_spec.js
Labels: 4: Reviews Complete

#5929 Automated cherry pick of #5860
  components/more_direct_channels/__snapshots__/more_direct_channels.test.jsx.snap
  components/more_direct_channels/more_direct_channels.test.jsx
  components/more_direct_channels/more_direct_channels.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5889 [MM-26691] Store correct password settings values in local state
  components/admin_console/password_settings.jsx
Labels: 4: Reviews Complete, CherryPick/Approved

#5915 MM-26621 Add analytic event for ask community link
  components/channel_header/components/user_guide_dropdown/__snapshots__/user_guide_dropdown.test.jsx.snap
  components/channel_header/components/user_guide_dropdown/user_guide_dropdown.test.jsx
  components/channel_header/components/user_guide_dropdown/user_guide_dropdown.tsx
Labels: 4: Reviews Complete, CherryPick/Approved

#5908 MM-26751: Fix highlighting of at-mentions of self
  components/post_markdown/__snapshots__/post_markdown.test.jsx.snap
  components/post_markdown/post_markdown.jsx
  e2e/cypress/integration/messaging/at_mentions_user_spec.js
Labels: CherryPick/Approved, QA Review Done

#5923 [MM-26848] - Fix mention badge opacity for muted channels
  sass/layout/_sidebar-left.scss
Labels: 4: Reviews Complete, CherryPick/Approved, QA Review Done

#5934 Automated cherry pick of #5923
  sass/layout/_sidebar-left.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5932 Automated cherry pick of #5915
  components/channel_header/components/user_guide_dropdown/__snapshots__/user_guide_dropdown.test.jsx.snap
  components/channel_header/components/user_guide_dropdown/user_guide_dropdown.test.jsx
  components/channel_header/components/user_guide_dropdown/user_guide_dropdown.tsx
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5933 Automated cherry pick of #5908
  components/post_markdown/__snapshots__/post_markdown.test.jsx.snap
  components/post_markdown/post_markdown.jsx
  e2e/cypress/integration/messaging/at_mentions_user_spec.js
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5914 Cypress/E2E: promote/demote specs for v5.26
  e2e/cypress/integration/account_settings/display/clock_display_mode_spec.js
  e2e/cypress/integration/account_settings/display/message_display_mode_spec.js
  e2e/cypress/integration/account_settings/display/timezone_display_mode_spec.js
  e2e/cypress/integration/account_settings/sidebar/channel_switcher_ui_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/guest_experience_ui_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/guest_identification_ui_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/member_invitation_ui_spec.js
  e2e/cypress/integration/enterprise/ldap_group/group_mentions_spec.js
  e2e/cypress/integration/enterprise/ldap_group/search_channels_spec.js
  e2e/cypress/integration/enterprise/system_console/channel_moderation/create_posts_spec.js
  e2e/cypress/integration/enterprise/system_console/channel_moderation/manage_members_spec.js
  e2e/cypress/integration/enterprise/system_console/channel_moderation/system_config_spec.js
  e2e/cypress/integration/integrations/incoming_webhook/basic_formatting_spec.js
  e2e/cypress/integration/integrations/incoming_webhook/disallow_username_profile_override_spec.js
  e2e/cypress/integration/integrations/incoming_webhook/inapp_username_profile_override_spec.js
  e2e/cypress/integration/integrations/incoming_webhook/setting_spec.js
  e2e/cypress/integration/messaging/channel_read_after_permalink_spec.js
  e2e/cypress/integration/messaging/channel_users_interactions_spec.js
  e2e/cypress/integration/messaging/date_separator_spec.js
  e2e/cypress/integration/messaging/mention_autocomplete_overlap_spec.js
  e2e/cypress/integration/messaging/message_permalink_spec.js
  e2e/cypress/integration/messaging/post_header_spec.js
  e2e/cypress/integration/messaging/post_textbox_height_spec.js
  e2e/cypress/integration/messaging/private_channel_open_spec.js
  e2e/cypress/integration/search/search_user_post_spec.js
  e2e/cypress/integration/signin_authentication/forgot_password_spec.js
  e2e/cypress/integration/system_console/plugin_upload_spec.js
Labels: 4: Reviews Complete, AutomatedCherryPick, CherryPick/Approved

#5876 [MM-26622] - Change permissions for guest users to create and join channels
  components/sidebar/index.ts
Labels: 2: Dev Review, CherryPick/Approved, QA Review Done

#5938 Automated cherry pick of #5914
  e2e/cypress/integration/account_settings/display/clock_display_mode_spec.js
  e2e/cypress/integration/account_settings/display/message_display_mode_spec.js
  e2e/cypress/integration/account_settings/display/timezone_display_mode_spec.js
  e2e/cypress/integration/account_settings/sidebar/channel_switcher_ui_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/guest_experience_ui_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/guest_identification_ui_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/member_invitation_ui_spec.js
  e2e/cypress/integration/enterprise/ldap_group/group_mentions_spec.js
  e2e/cypress/integration/enterprise/ldap_group/search_channels_spec.js
  e2e/cypress/integration/enterprise/system_console/channel_moderation/create_posts_spec.js
  e2e/cypress/integration/enterprise/system_console/channel_moderation/manage_members_spec.js
  e2e/cypress/integration/enterprise/system_console/channel_moderation/system_config_spec.js
  e2e/cypress/integration/integrations/incoming_webhook/basic_formatting_spec.js
  e2e/cypress/integration/integrations/incoming_webhook/disallow_username_profile_override_spec.js
  e2e/cypress/integration/integrations/incoming_webhook/inapp_username_profile_override_spec.js
  e2e/cypress/integration/integrations/incoming_webhook/setting_spec.js
  e2e/cypress/integration/messaging/channel_read_after_permalink_spec.js
  e2e/cypress/integration/messaging/channel_users_interactions_spec.js
  e2e/cypress/integration/messaging/date_separator_spec.js
  e2e/cypress/integration/messaging/mention_autocomplete_overlap_spec.js
  e2e/cypress/integration/messaging/message_permalink_spec.js
  e2e/cypress/integration/messaging/post_header_spec.js
  e2e/cypress/integration/messaging/post_textbox_height_spec.js
  e2e/cypress/integration/messaging/private_channel_open_spec.js
  e2e/cypress/integration/search/search_user_post_spec.js
  e2e/cypress/integration/signin_authentication/forgot_password_spec.js
  e2e/cypress/integration/system_console/plugin_upload_spec.js
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5939 Automated cherry pick of #5876
  components/sidebar/index.ts
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5890 MM-26321 Add telemetry for create category from sidebar menu
  components/sidebar/sidebar.tsx
  components/sidebar/sidebar_channel/sidebar_channel_menu/sidebar_channel_menu.tsx
Labels: 4: Reviews Complete, CherryPick/Approved

#5943 Automated cherry pick of #5890
  components/sidebar/sidebar.tsx
  components/sidebar/sidebar_channel/sidebar_channel_menu/sidebar_channel_menu.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5942 Cypress/E2E: fix tests on timezone display
  e2e/cypress/integration/account_settings/display/timezone_display_mode_spec.js
  e2e/cypress/support/ui_commands.js
Labels: 3: QA Review, CherryPick/Approved

#5944 Automated cherry pick of #5942
  e2e/cypress/integration/account_settings/display/timezone_display_mode_spec.js
  e2e/cypress/support/ui_commands.js
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5874 [MM-26813] autocomplete UX rework
  components/create_post/create_post.jsx
  components/suggestion/command_provider.jsx
  components/suggestion/suggestion_box.jsx
Labels: 4: Reviews Complete, CherryPick/Approved

#5947 Cypress/E2E: Fix existing channel name spec
  e2e/cypress/integration/multi_team_and_dm/existing_channel_name_spec.js
Labels: 4: Reviews Complete, CherryPick/Approved

#5949 Automated cherry pick of #5947
  e2e/cypress/integration/multi_team_and_dm/existing_channel_name_spec.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5912 MM-26075 Add type definitions and standard return to several user api commands
  e2e/cypress/integration/enterprise/elasticsearch_autocomplete/helpers/index.js
  e2e/cypress/integration/enterprise/elasticsearch_autocomplete/users_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/guest_experience_ui_spec.js
  e2e/cypress/integration/enterprise/ldap/ldap_login_spec.js
  e2e/cypress/integration/enterprise/ldap_group/group_mentions_spec.js
  e2e/cypress/integration/search_autocomplete/users_spec.js
  e2e/cypress/support/api/user.d.ts
  e2e/cypress/support/api/user.js
  e2e/cypress/support/api_commands.js
Labels: 4: Reviews Complete, AutoMerge

#5948 Cypress/E2E: Fix accessibility post spec
  e2e/cypress/integration/accessibility/accessibility_post_spec.js
Labels: 4: Reviews Complete

#5945 Cypress/E2E: Fix team members spec
  e2e/cypress/integration/enterprise/system_console/team_members_spec.js
Labels: 4: Reviews Complete, CherryPick/Approved

#5954 Automated cherry pick of #5945
  e2e/cypress/integration/enterprise/system_console/team_members_spec.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5957 Cypress/E2E: Try to fix timezone display mode flakiness
  e2e/cypress/integration/account_settings/display/timezone_display_mode_spec.js
Labels: 4: Reviews Complete, CherryPick/Approved

#5794 MM-25525 Sidebar: Event for tracking number of visible GMs and DMs in LHS
  actions/user_actions.jsx
  actions/user_actions.test.js
  components/data_prefetch/data_prefetch.test.tsx
  components/data_prefetch/data_prefetch.tsx
  components/data_prefetch/index.ts
Labels: 4: Reviews Complete, CherryPick/Approved

#5960 Cypress/E2E: Fix channel routing spec
  e2e/cypress/integration/channel/channel_routing_spec.js
Labels: 3: QA Review, CherryPick/Approved

#5959 Automated cherry pick of #5957
  e2e/cypress/integration/account_settings/display/timezone_display_mode_spec.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5961 Cypress/E2E: Fix accessibility input fields
  e2e/cypress/integration/accessibility/accessibility_input_fields_spec.js
Labels: 4: Reviews Complete

#5955 Cypress/E2E: Fix apiAdminLogin return object
  e2e/cypress/integration/enterprise/system_console/channel_members_spec.js
  e2e/cypress/integration/enterprise/system_console/team_members_spec.js
Labels: 4: Reviews Complete

#5953 MM-26075 Add type definitions and standard return to user/status/external api commands
  e2e/cypress/integration/enterprise/guest_accounts/guest_identification_ui_spec.js
  e2e/cypress/support/api/index.js
  e2e/cypress/support/api/status.d.ts
  e2e/cypress/support/api/status.js
  e2e/cypress/support/api/user.d.ts
  e2e/cypress/support/api/user.js
  e2e/cypress/support/api_commands.js
  e2e/cypress/support/external_commands.d.ts
  e2e/cypress/support/external_commands.js
  e2e/cypress/support/index.d.ts
Labels: 4: Reviews Complete

#5900 Fix MM-26677 : setState called from render method of CreateComment
  components/create_comment/create_comment.jsx
  e2e/cypress/integration/messaging/mention_autocomplete_overlap_spec.js
Labels: 4: Reviews Complete

#5833 Select Team list container should scale in width based on browser window width #14197
  components/select_team/__snapshots__/select_team.test.jsx.snap
  components/select_team/select_team.jsx
  sass/responsive/_mobile.scss
  sass/routes/_signup.scss
Labels: 4: Reviews Complete, QA Review Done

#5913 [MM-26868] Fix reselection of dropdowns on Interactive Dialogs
  components/suggestion/suggestion_box.jsx
Labels: 4: Reviews Complete, CherryPick/Approved

#5917 MM-26410/MM-26825 Switch to new isFavoriteChannel selector
  actions/command.js
  actions/command.test.js
  actions/views/channel.js
  components/legacy_sidebar/sidebar_channel/index.js
  components/sidebar/sidebar_channel/sidebar_channel_menu/index.ts
  package-lock.json
  package.json
Labels: 4: Reviews Complete, CherryPick/Approved

#5883 [MM-24708] Added What's New modal for Channel Sidebar Phase 2 changes
  components/__snapshots__/generic_modal.test.tsx.snap
  components/category_modal.scss
  components/delete_category_modal/delete_category_modal.tsx
  components/edit_category_modal/edit_category_modal.tsx
  components/generic_modal.scss
  components/generic_modal.test.tsx
  components/generic_modal.tsx
  components/sidebar/index.ts
  components/sidebar/sidebar.test.tsx
  components/sidebar/sidebar.tsx
  components/sidebar/sidebar_whats_new_modal/index.ts
  components/sidebar/sidebar_whats_new_modal/sidebar_whats_new_modal.scss
  components/sidebar/sidebar_whats_new_modal/sidebar_whats_new_modal.tsx
  i18n/en.json
  images/whats-new-1.5.gif
  utils/constants.jsx
Labels: 4: Reviews Complete, CherryPick/Approved

#5965 Automated cherry pick of #5917
  actions/command.js
  actions/command.test.js
  actions/views/channel.js
  components/legacy_sidebar/sidebar_channel/index.js
  components/sidebar/sidebar_channel/sidebar_channel_menu/index.ts
  package-lock.json
  package.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5972 Cypress/E2E: Fix plugin upload spec
  e2e/cypress/integration/system_console/plugin_upload_spec.js
Labels: 4: Reviews Complete, AutoMerge

#5971 Cypress/E2E: Fix hotkeys spec
  e2e/cypress/integration/account_settings/display/timezone_display_mode_spec.js
  e2e/cypress/integration/account_settings/sidebar/channel_switcher_ui_spec.js
  e2e/cypress/integration/channel_sidebar/hotkeys_spec.js
Labels: 4: Reviews Complete

#5894 MM-26733 - Export Textbox so plugins can use it
  components/quick_input.jsx
  components/suggestion/suggestion_box.jsx
  components/textbox/index.ts
  components/textbox/textbox.tsx
  package-lock.json
  plugins/export.js
Labels: 2: Dev Review

#5447 Add metric warning support (announcement bar and DM)
  actions/websocket_actions.jsx
  components/announcement_bar/__snapshots__/announcement_bar.test.jsx.snap
  components/announcement_bar/announcement_bar_controller.jsx
  components/announcement_bar/configuration_bar/configuration_bar.jsx
  components/announcement_bar/configuration_bar/index.js
  components/announcement_bar/default_announcement_bar/announcement_bar.jsx
  components/announcement_bar/index.js
  components/post_view/message_attachments/action_button/__snapshots__/action_button.test.jsx.snap
  components/post_view/message_attachments/action_button/action_button.jsx
  components/post_view/message_attachments/message_attachment/__snapshots__/message_attachment.test.jsx.snap
  components/post_view/message_attachments/message_attachment/message_attachment.jsx
  components/post_view/message_attachments/message_attachment/message_attachment.test.jsx
  components/root/index.js
  components/root/root.jsx
  components/root/root.test.jsx
  components/warn_metric_ack_modal/__snapshots__/warn_metric_ack_modal.test.tsx.snap
  components/warn_metric_ack_modal/index.ts
  components/warn_metric_ack_modal/warn_metric_ack_modal.test.tsx
  components/warn_metric_ack_modal/warn_metric_ack_modal.tsx
  i18n/en.json
  images/error-icon.png
  images/icons/check-circle-outline.svg
  images/icons/error-icon.svg
  images/icons/round-error-icon.svg
  images/icons/round-info-icon.svg
  images/icons/round-white-info-icon.svg
  package-lock.json
  package.json
  reducers/views/notice.js
  sass/base/_typography.scss
  sass/components/_announcement-bar.scss
  utils/constants.jsx
Labels: 4: Reviews Complete, CherryPick/Approved

#5952 Replacing blacklist with blocklist
  build/emoji/make-emojis
  components/suggestion/emoticon_provider.jsx
  components/suggestion/emoticon_provider.test.jsx
Labels: 4: Reviews Complete

#5927 [MM-26533] convey redirect link through verification
  components/do_verify_email/do_verify_email.tsx
Labels: 4: Reviews Complete, CherryPick/Approved

#5975 Automated cherry pick of #5927
  components/do_verify_email/do_verify_email.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5976 Switch mattermost-redux back to master
  package-lock.json
  package.json
Labels: 4: Reviews Complete

#5899 [MM-26824] Apply filter component to channels listing and add ability to filter by team
  components/admin_console/filter/filter.scss
  components/admin_console/filter/filter.tsx
  components/admin_console/filter/team_filter_dropdown/index.tsx
  components/admin_console/filter/team_filter_dropdown/team_filter_checkbox.tsx
  components/admin_console/filter/team_filter_dropdown/team_filter_dropdown.scss
  components/admin_console/filter/team_filter_dropdown/team_filter_dropdown.tsx
  components/admin_console/team_channel_settings/channel/list/__snapshots__/channel_list.test.tsx.snap
  components/admin_console/team_channel_settings/channel/list/channel_list.tsx
  components/admin_console/team_channel_settings/channel/list/index.ts
  components/channel_selector_modal/channel_selector_modal.jsx
  i18n/en.json
  package-lock.json
  package.json
  sass/routes/_admin-console.scss
Labels: 4: Reviews Complete, CherryPick/Approved

#5979 Automated cherry pick of #5913
  components/suggestion/suggestion_box.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5966 Translations update from Weblate
  i18n/de.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: AutoMerge

#5893 [MM-26470] Base Next Step Wizard Controller and Styling
  components/card/card.scss
  components/card/card.tsx
  components/card/card_body.tsx
  components/channel_view/channel_view.jsx
  components/channel_view/index.js
  components/next_steps_view/__snapshots__/next_steps_view.test.tsx.snap
  components/next_steps_view/index.ts
  components/next_steps_view/next_steps_view.scss
  components/next_steps_view/next_steps_view.test.tsx
  components/next_steps_view/next_steps_view.tsx
  components/next_steps_view/steps.ts
  components/next_steps_view/steps/complete_profile_step.tsx
  i18n/en.json
Labels: 4: Reviews Complete, Setup Cloud Test Server

#5985 Merge conflicts with weblate
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
Labels: AutoMerge

#5951 MM-27135: Deactivated users show in channel members dropdown
  components/popover_list_members/__snapshots__/popover_list_members.test.jsx.snap
  components/popover_list_members/popover_list_members.jsx
  components/popover_list_members/popover_list_members.test.jsx
  utils/filter_users.js
  utils/filter_users.test.js
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server

#5984 Cypress/E2E: Fix channel sidebar specs
  e2e/cypress/integration/channel_sidebar/category_collapsing_unread_filter_spec.js
  e2e/cypress/integration/channel_sidebar/channel_sidebar_spec.js
  e2e/cypress/integration/channel_sidebar/drag_and_drop_spec.js
  e2e/cypress/integration/channel_sidebar/history_channel_switcher_spec.js
  e2e/cypress/integration/channel_sidebar/new_channel_dropdown_spec.js
  e2e/cypress/integration/websocket/handle_removed_user/new_sidebar_spec.js
  e2e/cypress/support/ui/index.js
  e2e/cypress/support/ui/modal.d.ts
  e2e/cypress/support/ui/modal.js
Labels: 4: Reviews Complete, CherryPick/Approved

#5987 MM-27135: Deactivated users show in channel members dropdown (#5951)
  components/popover_list_members/__snapshots__/popover_list_members.test.jsx.snap
  components/popover_list_members/popover_list_members.jsx
  components/popover_list_members/popover_list_members.test.jsx
  utils/filter_users.js
  utils/filter_users.test.js
Labels: AutoMerge

#5925 MM-26833: Lowercase login ID before submitting in LoginMFA
  components/login/login_mfa.jsx
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, Setup Old Test Server

#5970 Cypress/E2E: Fix message display mode spec
  e2e/cypress/integration/account_settings/display/message_display_mode_spec.js
Labels: 4: Reviews Complete

#5967 Cypress/E2E: Fix accessibility modals dialogs
  e2e/cypress/integration/accessibility/accessibility_modals_dialogs_spec.js
Labels: 4: Reviews Complete

#5903 Added Direct Channels in the channels list of goToLastViewedChannel
  actions/views/channel.js
Labels: 4: Reviews Complete, CherryPick/Approved

#5910 [MM-26219] Fix member count on add groups to channel / team modal
  components/add_groups_to_channel_modal/add_groups_to_channel_modal.jsx
  components/add_groups_to_team_modal/add_groups_to_team_modal.jsx
  package-lock.json
  package.json
Labels: 4: Reviews Complete, CherryPick/Approved

#5990 MM-27167: Add undefined check
  components/data_prefetch/index.ts
Labels: 4: Reviews Complete, CherryPick/Approved

#5946 Fixes MM-25783 : Selecting an emoji shows hidden text
  sass/components/_emoticons.scss
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server

#5962 MM-25322 - Updating compass icon fonts
  components/quick_switch_modal/__snapshots__/quick_switch_modal.test.jsx.snap
  components/quick_switch_modal/quick_switch_modal.jsx
  components/search_bar/__snapshots__/search_bar.test.jsx.snap
  components/search_bar/search_bar.jsx
  fonts/compass-icons/compass-icons.eot
  fonts/compass-icons/compass-icons.svg
  fonts/compass-icons/compass-icons.ttf
  fonts/compass-icons/compass-icons.woff
  fonts/compass-icons/compass-icons.woff2
  fonts/mattermosticons/mattermosticons.eot
  fonts/mattermosticons/mattermosticons.svg
  fonts/mattermosticons/mattermosticons.ttf
  fonts/mattermosticons/mattermosticons.woff
  fonts/mattermosticons/mattermosticons.woff2
  sass/base/_compass-icons.scss
  sass/base/_module.scss
  sass/components/_channel-switcher.scss
  sass/components/_icons.scss
  sass/components/_search.scss
  sass/components/_suggestion-list.scss
  sass/layout/_sidebar-left.scss
  sass/layout/_sidebar-right.scss
Labels: 4: Reviews Complete

#5992 MM-26731 Sidebar text updates
  components/delete_category_modal/delete_category_modal.tsx
  components/edit_category_modal/edit_category_modal.tsx
  components/sidebar/add_channel_dropdown.tsx
  components/sidebar/sidebar_category/__snapshots__/sidebar_category.test.tsx.snap
  components/sidebar/sidebar_category/sidebar_category.tsx
  components/sidebar/sidebar_category/sidebar_category_menu/__snapshots__/sidebar_category_menu.test.tsx.snap
  components/sidebar/sidebar_category/sidebar_category_menu/sidebar_category_menu.tsx
  components/sidebar/sidebar_channel/sidebar_channel_menu/__snapshots__/sidebar_channel_menu.test.tsx.snap
  components/sidebar/sidebar_channel/sidebar_channel_menu/sidebar_channel_menu.tsx
  i18n/en.json
Labels: 4: Reviews Complete, CherryPick/Approved

#5898 [MM-19640] - Add download link for job results
  components/admin_console/jobs/index.jsx
  components/admin_console/jobs/table.jsx
  i18n/en.json
  package-lock.json
  package.json
Labels: 4: Reviews Complete

#5941 [MM-26969] Add team filter to team list in sys console
  components/admin_console/team_channel_settings/team/list/__snapshots__/team_list.test.jsx.snap
  components/admin_console/team_channel_settings/team/list/team_list.jsx
  package-lock.json
  package.json
Labels: 4: Reviews Complete

#5998 Cypress/E2E: Fix Cypress tests for admin-console search in User Management > Channel
  e2e/cypress/integration/enterprise/ldap_group/search_channels_spec.js
  e2e/cypress/integration/enterprise/system_console/channel_moderation/helpers.js
  e2e/cypress/integration/enterprise/system_console/channel_moderation/system_config_spec.js
Labels: 4: Reviews Complete, CherryPick/Approved

#5467 [MM-24052] Add animation to emoji reaction
  components/post_view/reaction/__snapshots__/reaction.test.jsx.snap
  components/post_view/reaction/reaction.jsx
  components/post_view/reaction/reaction.scss
  components/post_view/reaction/reaction.test.jsx
  components/post_view/reaction_list/__snapshots__/reactions_list.test.jsx.snap
  components/post_view/reaction_list/reaction_list.jsx
  e2e/cypress/integration/messaging/message_reaction_spec.js
  sass/components/_post.scss
  sass/utils/_mixins.scss
Labels: 4: Reviews Complete

#5964 [MM-27255] Change default theme system console setting to a dropdown
  components/admin_console/admin_definition.jsx
Labels: 4: Reviews Complete

#5924 [MM-26023] - Add Category related websocket actions
  actions/websocket_actions.jsx
  package-lock.json
  package.json
  utils/constants.jsx
Labels: 4: Reviews Complete, CherryPick/Approved

#6000 Cypress/E2E: Fix marketplace and plugin_upload specs
  e2e/cypress/integration/plugins/marketplace/marketplace_spec.js
  e2e/cypress/integration/system_console/plugin_upload_spec.js
Labels: 4: Reviews Complete

#5926 [MM-26960] Fix Archive Icon not showing up for archived channels on system console > Channels page
  components/admin_console/team_channel_settings/channel/list/__snapshots__/channel_list.test.tsx.snap
  components/admin_console/team_channel_settings/channel/list/channel_list.scss
  components/admin_console/team_channel_settings/channel/list/channel_list.tsx
Labels: 4: Reviews Complete, QA Review Done

#5884 MM-23699: Remove backbutton for when invalid callback url
  components/error_page/__snapshots__/error_message.test.tsx.snap
  components/error_page/__snapshots__/error_title.test.tsx.snap
  components/error_page/error_message.test.tsx
  components/error_page/error_message.tsx
  components/error_page/error_page.tsx
  components/error_page/error_title.test.tsx
  components/error_page/error_title.tsx
  utils/constants.jsx
Labels: 4: Reviews Complete

#5821 [MM-26493] Allow incoming webhooks owned by bot to override username
  components/post_view/post_header/post_header.jsx
Labels: 4: Reviews Complete

#6003 Cypress/E2E: Fix date separator spec
  e2e/cypress/integration/messaging/date_separator_spec.js
Labels: 4: Reviews Complete

#6001 Cypress/E2E: Fix forgot password spec
  e2e/cypress/support/api/user.js
Labels: 4: Reviews Complete

#6004 Cypress/E2E: Fix specs failing due to dropdown menu
  e2e/cypress/support/ui/post_dropdown_menu.js
  e2e/cypress/support/ui_commands.js
Labels: 4: Reviews Complete

#5869 [MM-26673] Attach emoji picker to the `Post Edit Modal`
  components/edit_post_modal/__snapshots__/edit_post_modal.test.jsx.snap
  components/edit_post_modal/edit_post_modal.jsx
  components/emoji_picker/emoji_picker_overlay.jsx
Labels: 4: Reviews Complete

#5919 [MM-26958] fix sort order of channel suggestion list
  components/suggestion/search_channel_provider.jsx
  components/suggestion/search_suggestion_list.jsx
  package.json
Labels: 4: Reviews Complete

#6007 MM-27346 Fix for excessive analytic events on scroll of LHS
  components/sidebar/sidebar_menu/sidebar_menu.test.tsx
  components/sidebar/sidebar_menu/sidebar_menu.tsx
Labels: 4: Reviews Complete, CherryPick/Approved

#6006 MM-T1437 Try to create a new team using restricted words
  e2e/cypress/integration/team_settings/create_a_team_spec.js
Labels: 4: Reviews Complete, Hackfest

#6008 MM-T1535 Team setting / Invite code text
  e2e/cypress/integration/team_settings/teams_spec.js
Labels: 4: Reviews Complete, Hackfest

#6002 MM-26866/MM-26869 Fix a couple sidebar CSS colours
  sass/layout/_legacy-sidebar-left.scss
  sass/layout/_sidebar-left.scss
  utils/utils.jsx
Labels: 4: Reviews Complete, CherryPick/Approved, QA Review Done

#5675 [MM-24518] Webapp: update 'More unreads' banner in sidebar to match new mobile UI
  components/__snapshots__/unread_channel_indicator.test.tsx.snap
  components/legacy_sidebar/__snapshots__/sidebar.test.jsx.snap
  components/legacy_sidebar/sidebar.jsx
  components/sidebar/sidebar_category_list/__snapshots__/sidebar_category_list.test.tsx.snap
  components/sidebar/sidebar_category_list/sidebar_category_list.tsx
  components/unread_channel_indicator.tsx
  components/widgets/icons/unread_below_icon.jsx
  i18n/en.json
  sass/layout/_legacy-sidebar-left.scss
Labels: 4: Reviews Complete

#5999 MM-26971 Fix GM duplicates when created and already exists in a category
  package-lock.json
  package.json
Labels: 4: Reviews Complete, CherryPick/Approved, QA Review Done

#6010 [MM-27168] Set -webkit-fill-available when on iOS Safari and 100vh otherwise
  sass/routes/_admin-console.scss
Labels: 4: Reviews Complete, CherryPick/Approved

#6022 Automated cherry pick of #6010
  sass/routes/_admin-console.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5937 [MM-20533] Migrate "RhsHeaderPost" component to TypeScript
  components/rhs_header_post/index.ts
  components/rhs_header_post/rhs_header_post.tsx
Labels: 4: Reviews Complete

#5996 MM-26598: channel name truncated too early on hover
  sass/layout/_sidebar-left.scss
Labels: 4: Reviews Complete, CherryPick/Approved
