Repository mattermost/mattermost-webapp, pull requests merged in 2020-10, with the labels that each got.

#6589 Cypress/E2E: Fix MM-T1462 accessibility for incoming message
  e2e/cypress/integration/accessibility/accessibility_post_spec.js
  e2e/cypress/integration/channel_sidebar/custom_categories_spec.js
Labels: 4: Reviews Complete

#6519 MM-28263: Cypress/E2E: Automate backlogs - Messaging > Pinned Posts part 2
  e2e/cypress/integration/messaging/pinned_posts_part2_spec.js
Labels: 4: Reviews Complete

#6570 MM-24811 Archive channels should not have options to manage users
  e2e/cypress/integration/archived_channel/archive_channel_member_spec.js
Labels: 4: Reviews Complete

#6560 [MM-28783] migrate string refs in edit post modal
  components/edit_post_modal/edit_post_modal.jsx
Labels: 4: Reviews Complete

#6278 [Mm-27817] e2e add user to gm
  e2e/cypress/integration/multi_team_and_dm/gm_add_user_spec.js
Labels: 4: Reviews Complete

#6455 MM-23345 - MM-T187 Inline markdown images open preview window
  e2e/cypress/integration/messaging/inline_images_open_preview_window_spec.js
Labels: 4: Reviews Complete

#6588 Cypress/E2E: Fix MM-T1467 for more modal dialog accessibility
  e2e/cypress/integration/accessibility/accessibility_modals_dialogs_spec.js
Labels: 4: Reviews Complete

#6571 MM-24813 Add e2e tests for archive post menu options
  e2e/cypress/integration/archived_channel/post_menu_spec.js
Labels: 4: Reviews Complete

#6511 [MM-27207] e2e archived channels I (4)
  e2e/cypress/integration/archived_channel/archived_leave_channel_spec.js
Labels: 4: Reviews Complete

#6429 [MM-28260] Automate backlogs - Integrations > Slash Commands
  e2e/cypress/integration/integrations/slash_commands_spec.js
Labels: 4: Reviews Complete

#6606 Cypress/E2E: Fix intermittent failing tests at common commands
  e2e/cypress/integration/integrations/builtin_commands/common_commands_spec.js
  e2e/cypress/integration/integrations/builtin_commands/groupmsg_command_spec.js
  e2e/cypress/integration/integrations/builtin_commands/helper.js
  e2e/cypress/integration/integrations/builtin_commands/invite_command_spec.js
Labels: 4: Reviews Complete

#6431 [MM-25553] favicon added for unread messages without mention
  components/favicon_title_handler/favicon_title_handler.test.jsx
  components/favicon_title_handler/favicon_title_handler.tsx
  images/favicon/favicon-default-16x16.png
  images/favicon/favicon-default-24x24.png
  images/favicon/favicon-default-32x32.png
  images/favicon/favicon-default-64x64.png
  images/favicon/favicon-default-96x96.png
  images/favicon/favicon-mentions-16x16.png
  images/favicon/favicon-mentions-24x24.png
  images/favicon/favicon-mentions-32x32.png
  images/favicon/favicon-mentions-64x64.png
  images/favicon/favicon-mentions-96x96.png
  images/favicon/favicon-reddot-16x16.png
  images/favicon/favicon-reddot-32x32.png
  images/favicon/favicon-reddot-96x96.png
  images/favicon/favicon-unread-16x16.png
  images/favicon/favicon-unread-24x24.png
  images/favicon/favicon-unread-32x32.png
  images/favicon/favicon-unread-64x64.png
  images/favicon/favicon-unread-96x96.png
  package-lock.json
  root.html
Labels: 4: Reviews Complete, QA Review Done, Setup Cloud Test Server

#6602 [GH-15620] Migrated string refs in signup_email
  components/signup/signup_email/signup_email.jsx
Labels: 4: Reviews Complete, Hacktoberfest

#6612 Cypress/E2E: Stabilize profile popover spec
  e2e/cypress/integration/add_user_to_channel_from_profile_popover/profile_popover_spec.js
Labels: 4: Reviews Complete

#6614 Cypress/E2E: Fix managing bot accounts spec
  e2e/cypress/integration/bot_accounts/managing_bot_accounts_spec.js
Labels: 4: Reviews Complete

#6593 Migrate post_list_row component to typescript
  components/post_view/post_list_row/__snapshots__/post_list_row.test.tsx.snap
  components/post_view/post_list_row/index.ts
  components/post_view/post_list_row/post_list_row.test.tsx
  components/post_view/post_list_row/post_list_row.tsx
Labels: 4: Reviews Complete, Hacktoberfest

#6627 GH-15766 Fixed cypress env for PostgreSQL connection
  e2e/cypress.json
Labels: 4: Reviews Complete, Hacktoberfest

#6617 Cypress/E2E: Fix archived channel specs
  e2e/cypress/integration/archived_channel/archived_leave_channel_spec.js
  e2e/cypress/integration/channel/archived_channels_2_spec.js
  e2e/cypress/support/ui/channel.d.ts
  e2e/cypress/support/ui/channel.js
  e2e/cypress/support/ui/channel_sidebar.js
Labels: 4: Reviews Complete

#6592 MM-28780 Migrate dotMenu string refs to functional ones
  components/rhs_comment/rhs_comment.jsx
Labels: 4: Reviews Complete, Hacktoberfest

#6546 [MM-28965] - Prevent link overlap in channel header
  sass/layout/_headers.scss
Labels: 4: Reviews Complete

#6562 MM-24810 Add e2e for reactions for archived channel posts
  e2e/cypress/integration/archived_channel/archive_channel_reaction_spec.js
Labels: 4: Reviews Complete

#6632 [MM-20490] Migrate 'components/post_view/combined_user_activity_post' module and associated tests to TypeScript
  components/post_view/combined_user_activity_post/index.ts
Labels: 2: Dev Review, Hacktoberfest

#6579 MM-24812 Add e2e tests for adding reactions to existing reactions in archived channel posts
  e2e/cypress/integration/archived_channel/archive_channel_addReaction_spec.js
Labels: 4: Reviews Complete

#6604 MM T134 visual verification of tooltips
  e2e/cypress/integration/messaging/visual_verification_of_tooltips_on_top_nav_channel_icons_posts_spec.js
Labels: 4: Reviews Complete, Hacktoberfest

#6616 /files should target=_blank
  utils/markdown/index.test.js
  utils/markdown/renderer.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server

#6651 Automated cherry pick of #6616
  utils/markdown/index.test.js
  utils/markdown/renderer.tsx
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#6639 [MM-29302] Billing Summary Card - No Billing History case
  components/admin_console/billing/billing_subscriptions.tsx
  components/admin_console/billing/billing_summary.scss
  components/admin_console/billing/billing_summary.tsx
  i18n/en.json
  images/no_billing_history_graphic.svg
Labels: 4: Reviews Complete, QA Review Done, Setup Cloud Test Server

#6621 [GH-15724] Remove usage of findDOMNode from Create Team screens
  components/create_team/components/__snapshots__/display_name.test.jsx.snap
  components/create_team/components/display_name.jsx
  components/create_team/components/display_name.test.jsx
  components/create_team/components/team_url/__snapshots__/team_url.test.tsx.snap
  components/create_team/components/team_url/team_url.test.tsx
  components/create_team/components/team_url/team_url.tsx
Labels: 4: Reviews Complete, Hacktoberfest

#6601 [MM-20460] Migrate 'components/permissions_gates/channel_permission_gate' module and associated tests to TypeScript
  components/permissions_gates/channel_permission_gate/__snapshots__/channel_permission_gate.test.tsx.snap
  components/permissions_gates/channel_permission_gate/channel_permission_gate.jsx
  components/permissions_gates/channel_permission_gate/channel_permission_gate.test.tsx
  components/permissions_gates/channel_permission_gate/channel_permission_gate.tsx
  components/permissions_gates/channel_permission_gate/index.ts
Labels: 4: Reviews Complete, AutoMerge, Hacktoberfest, hacktoberfest-accepted

#6199 [MM-22161] - Improve accessibility of channel switcher
  components/quick_switch_modal/__snapshots__/quick_switch_modal.test.jsx.snap
  components/quick_switch_modal/quick_switch_modal.jsx
  components/suggestion/suggestion_list.jsx
  components/suggestion/switch_channel_provider.jsx
  i18n/en.json
Labels: 2: Dev Review, QA Review Done, Setup Cloud Test Server

#6650 Cypress/E2E: Promote cypress test to production
  e2e/cypress/integration/add_user_to_channel_from_profile_popover/profile_popover_spec_user_a_b_spec.js
  e2e/cypress/integration/archived_channel/archive_channel_header_spec.js
  e2e/cypress/integration/archived_channel/archive_channel_post_spec.js
  e2e/cypress/integration/archived_channel/join_archived_channel_spec.js
  e2e/cypress/integration/archived_channel/leave_archived_channel_spec.js
  e2e/cypress/integration/bot_accounts/edit_bot_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/guest_experience_ui_spec.js
  e2e/cypress/integration/enterprise/ldap/ldap_group_sync_spec.js
  e2e/cypress/integration/enterprise/system_console/channel_moderation/create_posts_spec.js
  e2e/cypress/integration/enterprise/system_console/channel_moderation/manage_members_spec.js
  e2e/cypress/integration/enterprise/system_console/channel_moderation/system_config_spec.js
  e2e/cypress/integration/enterprise/system_console/system_scheme_permission_spec.js
  e2e/cypress/integration/enterprise/system_console/team_guest_channel_spec.js
  e2e/cypress/integration/enterprise/system_console/team_scheme_permission_spec.js
  e2e/cypress/integration/integrations/builtin_commands/user_status_spec.js
  e2e/cypress/integration/mark_as_unread/bot_post_mark_as_unread_spec.js
  e2e/cypress/integration/mark_as_unread/mark_as_unread_using_shortcuts_spec.js
  e2e/cypress/integration/mark_as_unread/mark_mentions_as_unread_spec.js
  e2e/cypress/integration/messaging/autocomplete_with_space_spec.js
  e2e/cypress/integration/messaging/message_reaction_gm_spec.js
  e2e/cypress/integration/messaging/pinned_posts_spec.js
  e2e/cypress/integration/messaging/reactions_spec.js
  e2e/cypress/integration/messaging/system_message_limited_options_spec.js
  e2e/cypress/integration/multi_team_and_dm/gm_header_spec.js
  e2e/cypress/integration/notifications/message_bar_spec.js
  e2e/cypress/integration/notifications/own_user_posts_reply_while_scrolled_up_spec.js
  e2e/cypress/integration/notifications/unread_on_public_channel_spec.js
  e2e/cypress/integration/plugins/upgrade_spec.js
  e2e/cypress/integration/scroll/fixed_width_spec.js
  e2e/cypress/integration/search/search_user_post_spec.js
  e2e/cypress/integration/system_console/feature_discovery_spec.js
  e2e/cypress/integration/system_console/main_menu_spec.js
  e2e/cypress/integration/system_console/reporting/server_logs_spec.js
  e2e/cypress/integration/system_console/reporting/site_statistics_spec.js
  e2e/cypress/integration/system_console/reporting/team_statistics_spec.js
  e2e/cypress/integration/system_console/site_configuration/customization_spec.js
  e2e/cypress/integration/system_console/user_management/users_spec.js
Labels: 4: Reviews Complete

#6630 MM-29278 Make database error message easier to understand on Cypress test
  e2e/cypress/integration/enterprise/extend_session/email_login_activity_spec.js
  e2e/cypress/plugins/db_request.js
  e2e/cypress/support/db_commands.d.ts
  e2e/cypress/support/db_commands.js
  e2e/cypress/support/index.d.ts
  e2e/cypress/support/index.js
Labels: 4: Reviews Complete

#6657 Cypress/E2E: Stabilize emoji specs
  e2e/cypress/integration/emoji/recently_used_emoji_spec.js
  e2e/cypress/integration/messaging/emoji_to_markdown_spec.js
Labels: 4: Reviews Complete, CherryPick/Approved

#6660 Automated cherry pick of #6657
  e2e/cypress/integration/emoji/recently_used_emoji_spec.js
  e2e/cypress/integration/messaging/emoji_to_markdown_spec.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#6658 Cypress/E2E: Fix invite command spec; demote group mentions spec
  e2e/cypress/integration/enterprise/ldap_group/group_mentions_spec.js
  e2e/cypress/integration/integrations/builtin_commands/invite_command_spec.js
Labels: 4: Reviews Complete

#6547 [MM-20462] migrate any_team_permission_gate to typescript
  components/permissions_gates/any_team_permission_gate/__snapshots__/any_team_permission_gate.test.tsx.snap
  components/permissions_gates/any_team_permission_gate/any_team_permission_gate.jsx
  components/permissions_gates/any_team_permission_gate/any_team_permission_gate.test.tsx
  components/permissions_gates/any_team_permission_gate/any_team_permission_gate.tsx
  components/permissions_gates/any_team_permission_gate/index.ts
Labels: 4: Reviews Complete

#6674 Translations update from Weblate
  i18n/de.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: Hacktoberfest

#6634 [MM-29034] Remove usage of sidebar-text-## CSS variables
  components/sidebar/sidebar_next_steps/sidebar_next_steps.scss
  sass/base/_css_variables.scss
  sass/layout/_legacy-sidebar-left.scss
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#6633 MM-29038 Removed usage of centre-channel-color from post comments
  sass/components/_files.scss
  sass/components/_mentions.scss
  sass/components/_post-menu.scss
  sass/components/_post-right.scss
  sass/components/_post.scss
  sass/layout/_markdown.scss
  sass/responsive/_mobile.scss
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#6641 [GH-15776]Switch center-channel-color-## with center-channel-color-rgb variables
  sass/components/_buttons.scss
  sass/components/_emoticons.scss
  sass/components/_popover.scss
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#6643 [GH-15777] Replace center-channel-color-## with center-channel-color-rgb variables
  sass/components/_no-results-indicator.scss
  sass/components/_react-select.scss
  sass/components/_search.scss
  sass/components/_suggestion-list.scss
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#6607 [MM-28781] migrate string refs in channelView
  components/channel_view/channel_view.jsx
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#6662 Cypress/E2E: Fix channel switcher spec
  e2e/cypress/integration/channel/channel_switcher_spec.js
Labels: 4: Reviews Complete

#6167 [MM-24507] - Pin comment box on bottom of RHS thread
  components/create_comment/create_comment.jsx
  components/rhs_thread/__snapshots__/rhs_thread.test.tsx.snap
  components/rhs_thread/rhs_thread.tsx
Labels: 4: Reviews Complete

#6659 Added final set of cypress tests part of MM-29347
  e2e/cypress/integration/enterprise/group_mentions/group_mentions_permissions_spec.js
Labels: 4: Reviews Complete

#6624 migrate user_list_row_with_error to ts
  components/user_list_row_with_error/index.ts
  components/user_list_row_with_error/user_list_row_with_error.tsx
Labels: 4: Reviews Complete, Hacktoberfest, QA Review Done, hacktoberfest-accepted

#6583 [MM-27142] In-Web-App purchase of Mattermost Cloud
  actions/cloud.tsx
  components/announcement_bar/cloud_announcement_bar/index.ts
  components/announcement_bar/cloud_announcement_bar/user_limit_announcement_bar.tsx
  components/dropdown_input.scss
  components/dropdown_input.tsx
  components/next_steps_view/next_steps_view.scss
  components/payment_form/card_image.css
  components/payment_form/card_image.tsx
  components/payment_form/card_input.css
  components/payment_form/card_input.tsx
  components/payment_form/payment_form.scss
  components/payment_form/payment_form.tsx
  components/payment_form/state_selector.tsx
  components/payment_form/stripe.ts
  components/purchase_modal/icon_message.scss
  components/purchase_modal/icon_message.tsx
  components/purchase_modal/index.ts
  components/purchase_modal/process_payment.css
  components/purchase_modal/process_payment_setup.tsx
  components/purchase_modal/purchase.scss
  components/purchase_modal/purchase_modal.tsx
  components/user_limit_modal/user_limit_modal.test.tsx
  components/user_limit_modal/user_limit_modal.tsx
  i18n/en.json
  images/cloud-logos/professional.svg
  images/cloud/blue-lower.svg
  images/cloud/blue.svg
  images/cloud/cards/amex.png
  images/cloud/cards/dinersclub.png
  images/cloud/cards/discover.jpg
  images/cloud/cards/jcb.png
  images/cloud/cards/mastercard.png
  images/cloud/cards/visa.jpg
  images/cloud/mattermost-cloud.svg
  images/cloud/payment_fail.svg
  images/cloud/payment_success.svg
  images/cloud/processing_payment.svg
  images/cloud/upgrade.svg
  images/cloud/waves.svg
  images/getting-started.svg
  images/onboarding-bg.svg
  images/onboarding-success.svg
  package-lock.json
  package.json
  sass/components/_announcement-bar.scss
  types/cloud/sku.ts
  utils/constants.jsx
  utils/countries.ts
  utils/states.ts
  utils/utils.jsx
  webpack.config.js
Labels: QA Review Done, Setup Cloud Test Server

#6635 [GH-15775] Replaced button-bg-## to use button-bg-rgb variables
  sass/components/_buttons.scss
  sass/components/_channel-header__icon.scss
  sass/components/_channel-switcher.scss
  sass/components/_files.scss
  sass/components/_popover.scss
  sass/components/_post-menu.scss
  sass/components/_post.scss
  sass/components/_react-select.scss
  sass/layout/_sidebar-right.scss
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#6642 MM-T581 Regen token
  e2e/cypress/integration/integrations/regen_token_spec.js
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#6671 migrate string-refs in search_results.jsx
  components/search_results/search_results.jsx
Labels: 4: Reviews Complete, Hacktoberfest, Setup Cloud Test Server, hacktoberfest-accepted

#6690 Automated cherry pick of #6583
  actions/cloud.tsx
  components/announcement_bar/cloud_announcement_bar/index.ts
  components/announcement_bar/cloud_announcement_bar/user_limit_announcement_bar.tsx
  components/dropdown_input.scss
  components/dropdown_input.tsx
  components/next_steps_view/next_steps_view.scss
  components/payment_form/card_image.css
  components/payment_form/card_image.tsx
  components/payment_form/card_input.css
  components/payment_form/card_input.tsx
  components/payment_form/payment_form.scss
  components/payment_form/payment_form.tsx
  components/payment_form/state_selector.tsx
  components/payment_form/stripe.ts
  components/purchase_modal/icon_message.scss
  components/purchase_modal/icon_message.tsx
  components/purchase_modal/index.ts
  components/purchase_modal/process_payment.css
  components/purchase_modal/process_payment_setup.tsx
  components/purchase_modal/purchase.scss
  components/purchase_modal/purchase_modal.tsx
  components/user_limit_modal/user_limit_modal.test.tsx
  components/user_limit_modal/user_limit_modal.tsx
  i18n/en.json
  images/cloud-logos/professional.svg
  images/cloud/blue-lower.svg
  images/cloud/blue.svg
  images/cloud/cards/amex.png
  images/cloud/cards/dinersclub.png
  images/cloud/cards/discover.jpg
  images/cloud/cards/jcb.png
  images/cloud/cards/mastercard.png
  images/cloud/cards/visa.jpg
  images/cloud/mattermost-cloud.svg
  images/cloud/payment_fail.svg
  images/cloud/payment_success.svg
  images/cloud/processing_payment.svg
  images/cloud/upgrade.svg
  images/cloud/waves.svg
  images/getting-started.svg
  images/onboarding-bg.svg
  images/onboarding-success.svg
  package-lock.json
  package.json
  sass/components/_announcement-bar.scss
  types/cloud/sku.ts
  utils/constants.jsx
  utils/countries.ts
  utils/states.ts
  utils/utils.jsx
  webpack.config.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#6691 Cypress/E2E: Update quick switch hint
  e2e/cypress/integration/account_settings/sidebar/channel_switcher_spec.js
  e2e/cypress/integration/enterprise/ldap/ldap_group_sync_spec.js
Labels: 4: Reviews Complete

#6578 Fix bot icon heigth
  components/legacy_sidebar/sidebar_channel_button_or_link/sidebar_channel_button_or_link_icon.jsx
Labels: 4: Reviews Complete

#6711 Remove Cloud billing flag from System Console
  components/admin_console/admin_definition.jsx
  i18n/en.json
Labels: 2: Dev Review

#6680 [MM-29399] Remove an unused changeCSS() style
  utils/utils.jsx
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#6700 [GH-15867] Migrate changeCSS() to CSS variable in utils/utils.jsx, ln. 546
  sass/components/_modal.scss
  utils/utils.jsx
Labels: 4: Reviews Complete, Hacktoberfest, Setup Cloud Test Server, hacktoberfest-accepted

#6695 [MM-29392] Migrate changeCSS() to CSS variable in utils/utils.jsx, ln 516 (#15831)
  sass/layout/_legacy-sidebar-left.scss
  utils/utils.jsx
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#6665 MM-T640 Cancel out of edit
  e2e/cypress/integration/integrations/incoming_webhook/cancel_out_of_edit_spec.js
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#6608 [MM-20474] Migrate 'components/post_view/commented_on' module and associated tests to TypeScript
  components/post_view/commented_on/__snapshots__/commented_on.test.tsx.snap
  components/post_view/commented_on/commented_on.test.tsx
  components/post_view/commented_on/commented_on.tsx
  components/post_view/commented_on/index.ts
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#6679 [MM-28213] Free Tier Overage Warning Panel
  .circleci/config.yml
  components/admin_console/admin_definition.jsx
  components/admin_console/billing/billing_subscriptions.tsx
  i18n/en.json
  utils/constants.jsx
Labels: 4: Reviews Complete, QA Review Done, Setup Cloud Test Server

#6706 Cypress/E2E: Fix main menu spec
  e2e/cypress/integration/system_console/main_menu_spec.js
Labels: 4: Reviews Complete

#6744 Automated cherry pick of #6679
  .circleci/config.yml
  components/admin_console/admin_definition.jsx
  components/admin_console/billing/billing_subscriptions.tsx
  i18n/en.json
  utils/constants.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#6638 [MM-28257] Cypress/E2E: Automate backlogs - Integrations > Slash Commands (10 test cases)
  e2e/cypress/integration/integrations/builtin_commands/common_commands_spec.js
  e2e/cypress/integration/integrations/builtin_commands/groupmsg_command_spec.js
  e2e/cypress/integration/integrations/builtin_commands/helper.js
Labels: 4: Reviews Complete

#6705 [MM-28714] Check if subscription is paid before showing any upgrade warnings
  components/announcement_bar/cloud_announcement_bar/index.ts
  components/announcement_bar/cloud_announcement_bar/user_limit_announcement_bar.tsx
  components/main_menu/index.jsx
  components/main_menu/main_menu.jsx
Labels: 3: QA Review, Setup Cloud Test Server

#6751 Automated cherry pick of #6705
  components/announcement_bar/cloud_announcement_bar/index.ts
  components/announcement_bar/cloud_announcement_bar/user_limit_announcement_bar.tsx
  components/main_menu/index.jsx
  components/main_menu/main_menu.jsx
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#6745 [GH-15875] Migrate changeCSS() to CSS variable in utils/utils.jsx, ln. 564
  sass/layout/_navigation.scss
  utils/utils.jsx
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#6735 [GH-15890] Migrate changeCSS() to CSS variable in utils/utils.jsx, ln. 627
  sass/components/_popover.scss
  utils/utils.jsx
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#6702 Migrate changeCSS() to CSS variable in utils/utils.jsx, ln. 566
  sass/layout/_team-sidebar.scss
  utils/utils.jsx
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#6640 [MM-29035] Remove usage of mention-highlight-bg-## CSS variables
  sass/components/_post.scss
  utils/utils.jsx
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#6686 [MM-29397] Migrate changeCSS() to CSS variable in utils/utils.jsx, ln 525 (#15836)
  utils/utils.jsx
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#6644 MM-29040 Switch center-channel-color-## to -rgb variables
  sass/components/_channel-switcher.scss
  sass/components/_color-input.scss
  sass/components/_forms.scss
  sass/components/_modal.scss
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#6636 [MM-20480] Migrate new_message_separator and its tests to typescript
  components/post_view/new_message_separator/__snapshots__/new_message_separator.test.tsx.snap
  components/post_view/new_message_separator/new_message_separator.test.tsx
  components/post_view/new_message_separator/new_message_separator.tsx
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#6596 [MM-20455] Migrate 'components/integrations/edit_incoming_webhook' module and associated tests to TypeScript
  components/integrations/edit_incoming_webhook/__snapshots__/edit_incoming_webhook.test.tsx.snap
  components/integrations/edit_incoming_webhook/edit_incoming_webhook.test.tsx
  components/integrations/edit_incoming_webhook/edit_incoming_webhook.tsx
  components/integrations/edit_incoming_webhook/index.ts
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#6749 Translations update from Weblate
  i18n/es.json
  i18n/ja.json
  i18n/ko.json
  i18n/pt-BR.json
  i18n/uk.json
  i18n/zh-CN.json
Labels: 2: Dev Review

#6748 Translations update from Weblate
  i18n/de.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 2: Dev Review

#6682 MM-T636 Description field for incoming and outgoing webhooks can hold 500 characters
  e2e/cypress/integration/integrations/incoming_webhook/description_length_check_spec.js
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#6733 [GH-15892] Migrate changeCSS() to CSS variable in utils/utils.jsx, ln. 631
  sass/components/_popover.scss
  utils/utils.jsx
Labels: Hacktoberfest, hacktoberfest-accepted

#6740 Cloud Billing polish Soft GA
  components/admin_console/billing/billing_history.tsx
  components/admin_console/billing/company_info.tsx
  components/admin_console/billing/company_info_display.tsx
Labels: 4: Reviews Complete

#6584 [MM-20514] Migrates components/password reset send link to typescript
  components/password_reset_send_link/__snapshots__/password_reset_send_link.test.tsx.snap
  components/password_reset_send_link/index.js
  components/password_reset_send_link/index.ts
  components/password_reset_send_link/password_reset_send_link.test.tsx
  components/password_reset_send_link/password_reset_send_link.tsx
Labels: 4: Reviews Complete

#6758 Automated cherry pick of #6740
  components/admin_console/billing/billing_history.tsx
  components/admin_console/billing/company_info.tsx
  components/admin_console/billing/company_info_display.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#6731 MM-27454 - Contact Us and Billing Documentation Links
  .circleci/config.yml
  components/admin_console/billing/billing_history.tsx
  components/admin_console/billing/billing_subscriptions.tsx
  components/admin_console/billing/billing_summary.tsx
  components/admin_console/billing/plan_details.tsx
  components/purchase_modal/index.ts
  components/purchase_modal/purchase_modal.tsx
  i18n/en.json
  package-lock.json
  package.json
  selectors/cloud.ts
  utils/constants.jsx
Labels: 3: QA Review

#6760 [MM-28062] Add telemetry for in-app purchase flow
  components/purchase_modal/process_payment_setup.tsx
  components/purchase_modal/purchase_modal.tsx
  components/user_limit_modal/user_limit_modal.tsx
  utils/constants.jsx
Labels: 4: Reviews Complete

#6725 [GH-15896] Migrate changeCSS() to CSS variable in utils/utils.jsx, ln. 636
  sass/components/_scrollbar.scss
  utils/utils.jsx
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#6676 [MM-27231]: cypress test for MM-T1837
  e2e/cypress/integration/messaging/header_spec.js
Labels: 4: Reviews Complete

#6743 [GH-15889] Migrate changeCSS() to CSS variable in utils/utils.jsx, ln. 622
  sass/responsive/_mobile.scss
  utils/utils.jsx
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#6692 [MM-29396] Migrate changeCSS() to CSS variable in utils/utils.jsx, ln. 523 (#15835)
  utils/utils.jsx
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#6698 [MM-29388] Migrate changeCSS() to CSS variable in utils/utils.jsx, ln 505 (#15827)
  utils/utils.jsx
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#6696 [MM-29391] Migrate changeCSS() to CSS variable in utils/utils.jsx, ln 513 (#15830)
  sass/routes/_settings.scss
  utils/utils.jsx
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#6763 [MM-28064] Add telemetry in various places around cloud message banners
  components/admin_console/billing/billing_subscriptions.tsx
  components/announcement_bar/cloud_announcement_bar/user_limit_announcement_bar.tsx
  utils/constants.jsx
Labels: 4: Reviews Complete

#6694 [MM-29393] Migrate changeCSS() to CSS variable in utils/utils.jsx, ln 519 (#15832)
  sass/layout/_legacy-sidebar-left.scss
  utils/utils.jsx
Labels: 2: Dev Review, Hacktoberfest, hacktoberfest-accepted

#6765 [MM-29557] [MM-29590] Update subscription when purchase modal closes
  components/purchase_modal/index.ts
  components/purchase_modal/purchase_modal.tsx
Labels: 4: Reviews Complete

#6693 [MM-29394] Migrate changeCSS() to CSS variable in utils/utils.jsx, ln 520 (#15833)
  sass/layout/_team-sidebar.scss
  utils/utils.jsx
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#6712 [MM-29453] Migrate changeCSS() to CSS variable in utils/utils.jsx, ln. 533
  sass/layout/_team-sidebar.scss
  utils/utils.jsx
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#6764 [MM-29559][MM-29558] Company Info Fixes
  components/admin_console/billing/company_info_display.tsx
Labels: 2: Dev Review

#6699 Migrate changeCSS() use of sidebarTextActiveBorder to CSS variable in utils/utils.jsx
  sass/layout/_team-sidebar.scss
  utils/utils.jsx
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#6767 Automated cherry pick of #6764
  components/admin_console/billing/company_info_display.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#6762 [MM-28063] Cloud Telemetry - Admin Console
  components/admin_console/billing/billing_history.tsx
  components/admin_console/billing/billing_subscriptions.scss
  components/admin_console/billing/billing_subscriptions.tsx
  components/admin_console/billing/billing_summary.tsx
  components/admin_console/billing/company_info.tsx
  components/admin_console/billing/company_info_display.tsx
  components/admin_console/billing/payment_info.tsx
  components/admin_console/billing/payment_info_display.tsx
  components/admin_console/billing/payment_info_edit.tsx
  components/admin_console/billing/plan_details.tsx
  i18n/en.json
Labels: 4: Reviews Complete

#6761 Automated cherry pick of #6731
  .circleci/config.yml
  components/admin_console/billing/billing_history.tsx
  components/admin_console/billing/billing_subscriptions.tsx
  components/admin_console/billing/billing_summary.tsx
  components/admin_console/billing/plan_details.tsx
  components/purchase_modal/index.ts
  components/purchase_modal/purchase_modal.tsx
  i18n/en.json
  package-lock.json
  package.json
  selectors/cloud.ts
  utils/constants.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#6770 Automated cherry pick of #6762
  components/admin_console/billing/billing_history.tsx
  components/admin_console/billing/billing_subscriptions.scss
  components/admin_console/billing/billing_subscriptions.tsx
  components/admin_console/billing/billing_summary.tsx
  components/admin_console/billing/company_info.tsx
  components/admin_console/billing/company_info_display.tsx
  components/admin_console/billing/payment_info.tsx
  components/admin_console/billing/payment_info_display.tsx
  components/admin_console/billing/payment_info_edit.tsx
  components/admin_console/billing/plan_details.tsx
  i18n/en.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#6769 Automated cherry pick of #6766
  components/admin_console/billing/billing_subscriptions.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#6720 [MM-29461] Migrate changeCSS() to CSS variable in utils/utils.jsx in 560.
  sass/layout/_navigation.scss
  utils/utils.jsx
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#6717 [MM-20489] Migrate failed_post_options and its tests to typescript
  components/post_view/failed_post_options/__snapshots__/failed_post_options.test.tsx.snap
  components/post_view/failed_post_options/failed_post_options.test.tsx
  components/post_view/failed_post_options/failed_post_options.tsx
  components/post_view/failed_post_options/index.ts
  components/rhs_thread/rhs_thread.test.tsx
  utils/test_helper.ts
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#5828 [MM-24436]- Add a threshold from bottom for new messages toast
  components/toast_wrapper/toast_wrapper.jsx
  components/toast_wrapper/toast_wrapper.test.jsx
Labels: 4: Reviews Complete, QA Review Done, Setup Cloud Test Server

#6656 MM-20554 Migrate 'components/delete_post_modal' module and associated tests to TypeScript
  components/delete_post_modal/__snapshots__/delete_post_modal.test.tsx.snap
  components/delete_post_modal/delete_post_modal.test.tsx
  components/delete_post_modal/delete_post_modal.tsx
  components/delete_post_modal/index.js
  components/delete_post_modal/index.ts
Labels: 4: Reviews Complete, Hacktoberfest, Setup Cloud Test Server, hacktoberfest-accepted

#6574 [MM-20599] Migrated select_team component to Typescript
  components/select_team/__snapshots__/select_team.test.tsx.snap
  components/select_team/components/__snapshots__/select_team_item.test.tsx.snap
  components/select_team/components/select_team_item.test.tsx
  components/select_team/components/select_team_item.tsx
  components/select_team/index.ts
  components/select_team/select_team.test.tsx
  components/select_team/select_team.tsx
  utils/utils.jsx
Labels: 4: Reviews Complete

#6631 [MM-20478] Migrate post_header module to TypeScript
  components/post_view/post_header/index.ts
  components/post_view/post_header/post_header.tsx
  components/post_view/post_info/post_info.jsx
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#6724 [GH-15894] Migrate changeCSS() to CSS variable in utils/utils.jsx, ln. 635
  sass/components/_scrollbar.scss
  utils/utils.jsx
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#6752 MM-T644 Integrations display on team where they were created
  e2e/cypress/integration/integrations/incoming_webhook/integrations_display_on_team_where_created_spec.js
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#6708 Cypress/E2E: Fix tutorial header verification
  e2e/cypress/integration/onboarding/finish_tutorial_spec.js
  e2e/cypress/integration/onboarding/login_page_link_account_creation_spec.js
  e2e/cypress/integration/onboarding/use_team_invite_link_to_sign_up_spec.js
  e2e/cypress/integration/team_settings/closed_team_invite_by_email_spec.js
Labels: 4: Reviews Complete

#6567 [MM-28680] rm usage of jQuery from theme settings
  components/user_settings/display/user_settings_theme/__snapshots__/custom_theme_chooser.test.jsx.snap
  components/user_settings/display/user_settings_theme/custom_theme_chooser.jsx
  components/user_settings/display/user_settings_theme/custom_theme_chooser.test.jsx
  components/user_settings/display/user_settings_theme/premade_theme_chooser/premade_theme_chooser.jsx
  sass/routes/_settings.scss
  utils/utils.jsx
Labels: 4: Reviews Complete

#6713 [MM-29459] Migrate changeCSS() to CSS variable in utils/utils.jsx in 550.
  sass/components/_emoticons.scss
  utils/utils.jsx
Labels: 2: Dev Review, Hacktoberfest, hacktoberfest-accepted

#6652 MM-29347: E2E Cypress Tests - System Console > Enterprise > Group Mentions (Part 1)
  e2e/cypress/integration/enterprise/group_mentions/group_mentions_system_messages_spec.js
Labels: 4: Reviews Complete, AutoMerge

#6697 Migrate changeCSS(sideText) to CSS variable --sidebartext in utils/utils.jsx
  components/user_settings/display/user_settings_theme/user_settings_theme.jsx
  sass/components/_multi-select.scss
  sass/components/_scrollbar.scss
  utils/utils.jsx
Labels: 2: Dev Review, Hacktoberfest, hacktoberfest-accepted

#6777 [MM-29632] Added extra null checking for company address
  components/admin_console/billing/company_info_display.tsx
Labels: 4: Reviews Complete

#6778 [MM-29646] Down't show picker error if paid tier
  components/invitation_modal/invitation_modal_members_step/index.ts
  components/invitation_modal/invitation_modal_members_step/invitation_modal_members_step.jsx
  components/invitation_modal/invitation_modal_members_step/invitation_modal_members_step.test.jsx
Labels: 4: Reviews Complete

#6780 [MM-29651] Wait for async calls to finish before rendering anything for a couple billing screens
  components/admin_console/billing/billing_subscriptions.tsx
  components/admin_console/billing/payment_info_display.tsx
Labels: 4: Reviews Complete

#6781 Automated cherry pick of #6777
  components/admin_console/billing/company_info_display.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#6779 [MM-29635] Don't show panel in subscription section if at user limit
  components/admin_console/billing/billing_subscriptions.tsx
Labels: 2: Dev Review

#6782 Automated cherry pick of #6780
  components/admin_console/billing/billing_subscriptions.tsx
  components/admin_console/billing/payment_info_display.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#6785 Automated cherry pick of #6778
  components/invitation_modal/invitation_modal_members_step/index.ts
  components/invitation_modal/invitation_modal_members_step/invitation_modal_members_step.jsx
  components/invitation_modal/invitation_modal_members_step/invitation_modal_members_step.test.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#6783 [MM-29630] Add error states to cloud guest invites when going over limit
  components/invitation_modal/__snapshots__/invitation_modal.test.jsx.snap
  components/invitation_modal/invitation_modal.jsx
  components/invitation_modal/invitation_modal_guest_step/__snapshots__/invitation_modal_guests_step.test.jsx.snap
  components/invitation_modal/invitation_modal_guest_step/index.ts
  components/invitation_modal/invitation_modal_guest_step/invitation_modal_guests_step.jsx
  components/invitation_modal/invitation_modal_guest_step/invitation_modal_guests_step.scss
  components/invitation_modal/invitation_modal_guest_step/invitation_modal_guests_step.test.jsx
Labels: 4: Reviews Complete

#6787 [MM-29671] Stopped error message from showing until form has been edited
  components/admin_console/billing/payment_info_edit.tsx
Labels: 2: Dev Review

#6784 Automated cherry pick of #6779
  components/admin_console/billing/billing_subscriptions.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#6788 Automated cherry pick of #6783
  components/invitation_modal/__snapshots__/invitation_modal.test.jsx.snap
  components/invitation_modal/invitation_modal.jsx
  components/invitation_modal/invitation_modal_guest_step/__snapshots__/invitation_modal_guests_step.test.jsx.snap
  components/invitation_modal/invitation_modal_guest_step/index.ts
  components/invitation_modal/invitation_modal_guest_step/invitation_modal_guests_step.jsx
  components/invitation_modal/invitation_modal_guest_step/invitation_modal_guests_step.scss
  components/invitation_modal/invitation_modal_guest_step/invitation_modal_guests_step.test.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#6790 Automated cherry pick of #6787
  components/admin_console/billing/payment_info_edit.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#6610 [MM-27188] E2E Tests Automated - Cypress/E2E: Automate backlogs - System Console (11 test cases)
  components/admin_console/license_settings/__snapshots__/license_settings.test.jsx.snap
  components/admin_console/license_settings/license_settings.jsx
  components/analytics/__snapshots__/line_chart.test.tsx.snap
  components/analytics/__snapshots__/statistic_count.test.tsx.snap
  components/analytics/line_chart.test.tsx
  components/analytics/line_chart.tsx
  components/analytics/statistic_count.tsx
  components/analytics/system_analytics/system_analytics.jsx
  components/analytics/team_analytics/team_analytics.jsx
  e2e/cypress/integration/system_console/about/edition_and_license_spec.js
  e2e/cypress/integration/system_console/main_menu_spec.js
  e2e/cypress/integration/system_console/reporting/site_statistics_spec.js
  e2e/cypress/integration/system_console/reporting/team_statistics_spec.js
  e2e/cypress/integration/system_console/search_box_spec.js
Labels: 4: Reviews Complete

#6789 [MM-29672] Include message in paid subscription card
  components/admin_console/billing/plan_details.scss
  components/admin_console/billing/plan_details.tsx
  i18n/en.json
Labels: 4: Reviews Complete

#6791 Automated cherry pick of #6789
  components/admin_console/billing/plan_details.scss
  components/admin_console/billing/plan_details.tsx
  i18n/en.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#6797 MM-29670 - Hide payment screen in system Console if in free tier
  components/admin_console/admin_console.test.tsx
  components/admin_console/admin_console.tsx
  components/admin_console/admin_definition.jsx
  components/admin_console/admin_sidebar/admin_sidebar.jsx
  components/admin_console/admin_sidebar/index.js
  components/admin_console/index.ts
Labels: 4: Reviews Complete

#6798 Automated cherry pick of #6797
  components/admin_console/admin_console.test.tsx
  components/admin_console/admin_console.tsx
  components/admin_console/admin_definition.jsx
  components/admin_console/admin_sidebar/admin_sidebar.jsx
  components/admin_console/admin_sidebar/index.js
  components/admin_console/index.ts
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#6771 [MM-29501] Migrate changeCSS() to CSS variable in utils/utils.jsx, ln 621 (#15888)
  utils/utils.jsx
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#6714 [GH-15899] migrated changeCss() to CSS variable
  sass/components/_post.scss
  utils/utils.jsx
Labels: 4: Reviews Complete

#6795 Cypress/E2E: Add missing TM4J IDs
  e2e/cypress/integration/account_settings/display/timezone_display_mode_spec.js
  e2e/cypress/integration/menus/main_menu_spec.js
  e2e/cypress/integration/messaging/local_date_time_spec.js
Labels: 4: Reviews Complete

#6703 [GH-15873] Migrate changeCSS() to CSS variable in utils/utils.jsx, ln. 562
  sass/layout/_team-button.scss
  utils/utils.jsx
Labels: 2: Dev Review, Hacktoberfest, hacktoberfest-accepted

#6736 [GH-15885] Migrate changeCSS() to CSS variable in utils/utils.jsx, ln. 613
  sass/layout/_legacy-sidebar-left.scss
  utils/utils.jsx
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#6741 [GH-15898] Migrate changeCSS() to CSS variable in utils/utils.jsx, ln. 668
  sass/components/_post.scss
  utils/utils.jsx
Labels: 2: Dev Review, Hacktoberfest, hacktoberfest-accepted

#6727 [MM-20486] 🏷 migrated 'post_add_channel_member' module to TypeScript
  components/post_view/post_add_channel_member/__snapshots__/post_add_channel_member.test.tsx.snap
  components/post_view/post_add_channel_member/index.ts
  components/post_view/post_add_channel_member/post_add_channel_member.test.tsx
  components/post_view/post_add_channel_member/post_add_channel_member.tsx
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#6591 Migrate team_settings_modal to typescript
  components/team_settings/team_settings.jsx
  components/team_settings_modal/__snapshots__/team_settings_modal.test.tsx.snap
  components/team_settings_modal/index.ts
  components/team_settings_modal/team_settings_modal.test.tsx
  components/team_settings_modal/team_settings_modal.tsx
Labels: 4: Reviews Complete, Hacktoberfest, Setup Cloud Test Server, hacktoberfest-accepted

#6746 [MM-20502] Migrate 'components/post_view/date_separator' module and a…
  components/post_view/date_separator/index.ts
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#6802 Cypress/E2E: Fix require license on some system console specs
  e2e/cypress/integration/system_console/about/edition_and_license_spec.js
  e2e/cypress/integration/system_console/main_menu_spec.js
  e2e/cypress/integration/system_console/reporting/site_statistics_spec.js
  e2e/cypress/integration/system_console/search_box_spec.js
Labels: 4: Reviews Complete

#6768 Campaign/applytheme sidebar text active border
  sass/layout/_team-sidebar.scss
  utils/utils.jsx
Labels: 4: Reviews Complete

#6786 MM-T2835 Slash command help stays visible for plugin
  e2e/cypress/integration/integrations/plugin_slash_command_stays_visible_spec.js
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#6623 [MM-20468] Migrate 'components/emoji/add_emoji' module and associated tests to TypeScript
  components/__snapshots__/spinner_button.test.tsx.snap
  components/emoji/add_emoji/__snapshots__/add_emoji.test.tsx.snap
  components/emoji/add_emoji/add_emoji.test.js
  components/emoji/add_emoji/add_emoji.test.tsx
  components/emoji/add_emoji/add_emoji.tsx
  components/emoji/add_emoji/index.js
  components/emoji/add_emoji/index.ts
  components/spinner_button.test.tsx
  components/spinner_button.tsx
  i18n/en.json
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#6775 Campaign/applytheme sidebar text
  components/user_settings/display/user_settings_theme/user_settings_theme.jsx
  sass/components/_multi-select.scss
  sass/components/_scrollbar.scss
  sass/layout/_legacy-sidebar-left.scss
  sass/layout/_team-sidebar.scss
  sass/routes/_settings.scss
  utils/utils.jsx
Labels: 4: Reviews Complete

#6618 Cypress/E2E: Automate backlogs - Messaging > Custom Emoji (9 test cases)
  e2e/cypress/fixtures/animated-gif-image-file.gif
  e2e/cypress/fixtures/gif-image-file-resized.gif
  e2e/cypress/integration/emoji/custom_emoji_spec.js
Labels: 4: Reviews Complete

#6575 MM-28261: Cypress/E2E: Automate backlogs - Integrations > Outgoing Webhooks (7 test cases)
  e2e/cypress/fixtures/webhook_icon.jpg
  e2e/cypress/fixtures/webhook_override_icon.png
  e2e/cypress/integration/integrations/incoming_webhook/helpers.js
  e2e/cypress/integration/integrations/outgoing_webhook/disable_override_username_profile_spec.js
  e2e/webhook_serve.js
Labels: 4: Reviews Complete

#6776 MM-T569 Integrations Page resize and check links
  e2e/cypress/integration/integrations/integrations_page_spec.js
Labels: Hacktoberfest, hacktoberfest-accepted

#6311 [MM-27816] Add tests for Ignore channel mentions
  e2e/cypress/integration/notifications/ignore_channel_mentions_spec.js
Labels: 4: Reviews Complete

#6647 Migrate string-refs to functional ones: this.refs.addReactionButton
  components/post_view/reaction_list/reaction_list.jsx
Labels: 4: Reviews Complete, AutoMerge, Hacktoberfest, hacktoberfest-accepted

#6683 [MM-29407]-Migrate-string-refs
  components/edit_channel_header_modal/edit_channel_header_modal.jsx
Labels: 4: Reviews Complete, AutoMerge, Hacktoberfest, hacktoberfest-accepted
