Repository mattermost/mattermost-webapp, pull requests merged in 2020-12, with the labels that each got.

#7109 [MM-20498] components/post_view/combined_system_message' to TypeScript
  components/post_view/combined_system_message/__snapshots__/combined_system_message.test.tsx.snap
  components/post_view/combined_system_message/__snapshots__/last_users.test.tsx.snap
  components/post_view/combined_system_message/combined_system_message.test.tsx
  components/post_view/combined_system_message/combined_system_message.tsx
  components/post_view/combined_system_message/index.ts
  components/post_view/combined_system_message/last_users.test.tsx
  components/post_view/combined_system_message/last_users.tsx
Labels: 4: Reviews Complete

#6962 Migrate 'components/sidebar_right_menu' module to TypeScript
  components/sidebar_right_menu/index.js
  components/sidebar_right_menu/sidebar_right_menu.tsx
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#7115 Converted 'leave_channel' to typescript.
  components/channel_header_dropdown/menu_items/leave_channel/__snapshots__/leave_channel.test.tsx.snap
  components/channel_header_dropdown/menu_items/leave_channel/index.ts
  components/channel_header_dropdown/menu_items/leave_channel/leave_channel.test.tsx
  components/channel_header_dropdown/menu_items/leave_channel/leave_channel.tsx
Labels: 4: Reviews Complete

#6924 [MM-20581] Migrate index to TS in 'components/admin_console/team_channel_settings/channel/details' module
  components/admin_console/team_channel_settings/channel/details/channel_details.tsx
  components/admin_console/team_channel_settings/channel/details/channel_groups.tsx
  components/admin_console/team_channel_settings/channel/details/channel_modes.tsx
  components/admin_console/team_channel_settings/channel/details/index.ts
Labels: Hacktoberfest, hacktoberfest-accepted

#6988 [MM-30176] Migrate changeCSS() to CSS variable in utils/utils.jsx, ln. 710
  sass/components/_popover.scss
  utils/utils.jsx
Labels: 4: Reviews Complete, Hacktoberfest, Setup Cloud Test Server, hacktoberfest-accepted

#7050 [MM-30339] mark browser.focused as false if starting in the background
  components/logged_in/logged_in.jsx
  components/logged_in/logged_in.test.jsx
Labels: 4: Reviews Complete

#7094 MM-27989 Remove experimental setting for data prefetch
  components/admin_console/admin_definition.jsx
  components/legacy_sidebar/__snapshots__/sidebar.test.jsx.snap
  components/legacy_sidebar/index.js
  components/legacy_sidebar/sidebar.jsx
  components/legacy_sidebar/sidebar.test.jsx
  components/sidebar/__snapshots__/sidebar.test.tsx.snap
  components/sidebar/index.ts
  components/sidebar/sidebar.test.tsx
  components/sidebar/sidebar.tsx
  i18n/en.json
Labels: 4: Reviews Complete

#7117 [MM-27207] e2e leave archived channels I - last
  e2e/cypress/integration/archived_channel/archived_leave_channel_spec.js
Labels: 4: Reviews Complete, AutoMerge

#7113 MM-30370: Cypress/E2E: Automate backlogs - Keyboard Shortcuts (10 test cases)
  e2e/cypress/integration/keyboard_shortcuts/keyboard_shortcuts_one_spec.js
Labels: 4: Reviews Complete, AutoMerge

#7112 MM-30371: Cypress/E2E: Automate backlogs - Keyboard Shortcuts part 2 (10 test cases)
  e2e/cypress/integration/keyboard_shortcuts/keyboard_shortcuts_two_spec.js
Labels: 4: Reviews Complete

#7153 [MM-29853] Migrate string-refs to functional ones: this.refs.fileInput
  components/admin_console/license_settings/license_settings.jsx
Labels: 4: Reviews Complete

#7156 MM-30740 Fix display of boolean feature flags in system console.
  components/admin_console/feature_flags.tsx
Labels: 2: Dev Review

#7140 MM-30992 Add the capability to run part by part for Cypress parallel testing (part 1)
  e2e/run_tests.js
  e2e/save_report.js
  e2e/utils/report.js
  e2e/utils/test_cases.js
Labels: 4: Reviews Complete

#7142 Cypress/E2E: Fix email verification that works both with current, Cloud and parallel testing (part 2)
  e2e/cypress/integration/email/mention_email_notification_spec.js
  e2e/cypress/integration/enterprise/cloud/onboarding/login_page_link_account_creation_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/guest_identification_spec.js
  e2e/cypress/integration/notifications/channel_links_show_as_links_spec.js
  e2e/cypress/integration/onboarding/use_team_invite_link_to_sign_up_spec.js
  e2e/cypress/integration/signin_authentication/forgot_password_spec.js
  e2e/cypress/integration/team_settings/closed_team_invite_by_email_spec.js
  e2e/cypress/integration/team_settings/helpers.js
  e2e/cypress/utils/constants.js
  e2e/cypress/utils/index.js
Labels: 4: Reviews Complete

#7143 Cypress/E2E: Fix for several flaky tests (part 3)
  e2e/cypress/integration/accessibility/accessibility_dropdowns_spec.js
  e2e/cypress/integration/bot_accounts/edit_bot_username_spec.js
  e2e/cypress/integration/channel_sidebar/hotkeys_spec.js
  e2e/cypress/integration/enterprise/channel/channel_groups_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/system_console_guest_access_ui_spec.js
  e2e/cypress/integration/integrations/builtin_commands/common_commands_spec.js
  e2e/cypress/integration/integrations/custom_slash_commands/slash_commands_spec.js
  e2e/cypress/integration/integrations/outgoing_webhook/prompt_set_status_spec.js
  e2e/cypress/integration/messaging/message_spec.js
  e2e/cypress/integration/messaging/single_image_thumbnail_spec.js
  e2e/cypress/integration/system_console/reporting/server_logs_spec.js
  e2e/cypress/integration/system_console/reporting/team_statistics_spec.js
  e2e/cypress/integration/system_console/user_management/users_spec.js
  e2e/cypress/utils/index.js
Labels: 4: Reviews Complete

#7159 Cypress/E2E: Fix return of Cypress custom commands
  e2e/cypress/support/api/team.js
  e2e/cypress/support/api/user.js
  e2e/cypress/support/api/webhooks.js
  e2e/cypress/support/api_commands.js
  e2e/cypress/support/client.js
  e2e/cypress/support/db_commands.js
  e2e/cypress/support/okta_commands.js
  e2e/cypress/support/task_commands.js
Labels: 4: Reviews Complete

#7165 Automated cherry pick of #7103
  components/admin_console/admin_definition.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7126 [MM-30354] e2e fullname
  components/profile_popover/profile_popover.jsx
  e2e/cypress/integration/account_settings/general/fullname_spec.js
  e2e/cypress/integration/account_settings/general/fullname_truncate_spec.js
Labels: 4: Reviews Complete, AutoMerge

#6804 Embedded forms
  actions/apps.ts
  components/apps_modal/apps_modal.tsx
  components/apps_modal/dialog_element/dialog_element.tsx
  components/apps_modal/index.ts
  components/apps_modal/interactive_dialog.test.tsx
  components/apps_modal/interactive_dialog.tsx
  components/button_selector.tsx
  components/post_view/post_body_additional_content/__snapshots__/post_body_additional_content.test.jsx.snap
  components/post_view/post_body_additional_content/post_body_additional_content.jsx
  components/post_view/post_body_additional_content/post_body_additional_content.test.jsx
Labels: 2: Dev Review

#7155 MM-30972 Add proper padding to code preview line numbers
  sass/components/_modal.scss
Labels: 4: Reviews Complete, AutoMerge, CherryPick/Approved

#7171 MM-28412: Add tm4j key
  e2e/cypress/integration/archived_channel/archive_channel_addReaction_spec.js
Labels: 4: Reviews Complete

#7167 Automated cherry pick of #7155
  sass/components/_modal.scss
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7120 [MM-26593] Disable pointer events on LHS scrollbar when scrolling isn't required
  components/sidebar/sidebar_channel_list/sidebar_channel_list.tsx
  sass/layout/_sidebar-left.scss
Labels: 4: Reviews Complete

#7102 Update NOTICE.txt
  NOTICE.txt
Labels: 4: Reviews Complete, CherryPick/Approved

#7141 MM-30376 Cypress/E2E: Automate backlogs - Messaging (8 test cases)
  e2e/cypress/integration/enterprise/profile_popover/profile_popover_spec_user_a_b_spec.js
  e2e/cypress/integration/messaging/group_message_spec.js
  e2e/cypress/integration/messaging/message_edit_post_clear_text_spec.js
  e2e/cypress/integration/messaging/message_ephemeral_spec.js
  e2e/cypress/integration/messaging/message_with_gif_spec.js
Labels: 3: QA Review

#7174 Automated cherry pick of #7102
  NOTICE.txt
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7133 [MM-30969] Drop aria-label from Marketplace item description
  components/plugin_marketplace/marketplace_item/__snapshots__/marketplace_item.test.js.snap
  components/plugin_marketplace/marketplace_item/marketplace_item.js
  components/plugin_marketplace/marketplace_item/marketplace_item.test.js
Labels: 4: Reviews Complete

#7177 Automated cherry pick of #7133
  components/plugin_marketplace/marketplace_item/__snapshots__/marketplace_item.test.js.snap
  components/plugin_marketplace/marketplace_item/marketplace_item.js
  components/plugin_marketplace/marketplace_item/marketplace_item.test.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7178 Automated cherry pick of #7133
  components/plugin_marketplace/marketplace_item/__snapshots__/marketplace_item.test.js.snap
  components/plugin_marketplace/marketplace_item/marketplace_item.js
  components/plugin_marketplace/marketplace_item/marketplace_item.test.js
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7179 Automated cherry pick of #7102
  NOTICE.txt
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7183 MM-31115 - Fixed "how billing works" cloud link
  utils/constants.jsx
Labels: 4: Reviews Complete, CherryPick/Approved

#7184 Automated cherry pick of #7183
  utils/constants.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7149 [MM-30372] Cypress/E2E: Automate backlogs - Messaging > Reply
  e2e/cypress/integration/messaging/message_reply_part2_spec.js
Labels: 4: Reviews Complete

#7146 MM-30374: Cypress/E2E: Messaging > Markdown
  e2e/cypress/fixtures/markdown/markdown_code_syntax.html
  e2e/cypress/fixtures/markdown/markdown_latex.html
  e2e/cypress/fixtures/markdown/markdown_latex.md
  e2e/cypress/fixtures/markdown/markdown_list.html
  e2e/cypress/fixtures/markdown/markdown_postgres.html
  e2e/cypress/fixtures/markdown/markdown_postgres.md
  e2e/cypress/fixtures/markdown/markdown_python.html
  e2e/cypress/fixtures/markdown/markdown_python.md
  e2e/cypress/fixtures/markdown/markdown_shell.html
  e2e/cypress/fixtures/markdown/markdown_shell.md
  e2e/cypress/fixtures/markdown/markdown_tables.html
  e2e/cypress/fixtures/markdown/markdown_test_basic.html
  e2e/cypress/fixtures/markdown/markdown_typescript.html
  e2e/cypress/fixtures/markdown/markdown_typescript.md
  e2e/cypress/integration/messaging/markdown_spec.js
Labels: 4: Reviews Complete

#7163 MM-30810 Remove special props from /me post
  components/post_markdown/system_message_helpers.jsx
Labels: 4: Reviews Complete

#7151 [MM-30449] - Hide create category option when unread filter is enabled
  components/sidebar/__snapshots__/sidebar.test.tsx.snap
  components/sidebar/add_channel_dropdown.tsx
  components/sidebar/index.ts
  components/sidebar/sidebar.test.tsx
  components/sidebar/sidebar.tsx
Labels: 4: Reviews Complete, QA Review Done

#7127 Add Billing Permissions
  components/admin_console/admin_definition.jsx
  components/admin_console/system_roles/system_role/index.tsx
  components/admin_console/system_roles/system_role/system_role.tsx
  components/admin_console/system_roles/system_role/system_role_permissions.tsx
  i18n/en.json
Labels: 3: QA Review

#7118 [MM-29036]Remove usage of center-channel-color-## CSS variables from header components
  sass/components/_channel-header__icon.scss
  sass/layout/_headers.scss
  sass/layout/_sidebar-right.scss
Labels: 4: Reviews Complete

#7181 Mm 30380/cypress dms and gms coverage
  e2e/cypress/integration/messaging/direct_message_spec.js
  e2e/cypress/integration/messaging/group_message_spec.js
Labels: 2: Dev Review, 3: QA Review, 4: Reviews Complete

#7105 [MM-30390] - Add specs for team settings
  e2e/cypress/integration/team_settings/teams_spec.js
Labels: 3: QA Review

#7108 [MM-30358] - Add account position spec
  e2e/cypress/integration/account_settings/display/account_settings_position_spec.js
Labels: 4: Reviews Complete

#6625 [MM-20487] Migrate 'components/post_view/post_time' module and associated tests to TypeScript
  components/post_view/post_time/index.ts
  components/post_view/post_time/post_time.tsx
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#7128 [MM-29418] Apply the same sorting function (#15920)
  components/admin_console/plugin_management/plugin_management.tsx
  package-lock.json
Labels: 4: Reviews Complete

#6989 [MM-20432] Migrate components/channel_view module and associated tests to TypeScript
  components/channel_view/__snapshots__/channel_view.test.jsx.snap
  components/channel_view/__snapshots__/channel_view.test.tsx.snap
  components/channel_view/channel_view.test.tsx
  components/channel_view/channel_view.tsx
  components/channel_view/index.ts
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#7196 [MM-27927] - Revert mattermost-redux
  package-lock.json
  package.json
Labels: 4: Reviews Complete

#7111 [MM-30364] - Add spec for channel settings
  e2e/cypress/integration/channel/add_users_to_channel_spec.js
  e2e/cypress/integration/channel/channel_settings_spec.js
  e2e/cypress/integration/notifications/desktop_notifications_spec.js
Labels: 4: Reviews Complete, AutoMerge

#6949 [MM-29949] Add extra space for team name and user name on new sidebar
  sass/layout/_sidebar-left.scss
Labels: 4: Reviews Complete, QA Review Done, Setup Cloud Test Server

#6860 [MM-27213] Cypress/E2E: Automate backlogs - Auth - Part 01 (10 test cases)
  actions/invite_actions.jsx
  components/should_verify_email/__snapshots__/should_verify_email.test.js.snap
  components/should_verify_email/should_verify_email.js
  e2e/cypress/integration/enterprise/system_console/authentication/authentication_spec.js
  e2e/cypress/integration/system_console/authentication/authentication_spec.js
Labels: 4: Reviews Complete

#7152 [MM-30447] - Add create direct message option to category menu
  components/sidebar/__snapshots__/sidebar.test.tsx.snap
  components/sidebar/add_channel_dropdown.tsx
  components/sidebar/sidebar.tsx
  i18n/en.json
Labels: 4: Reviews Complete, QA Review Done

#7107 [GH-16162] Migrate 'components/quick_switch_modal' module and associated tests to TypeScript
  components/quick_switch_modal/__snapshots__/quick_switch_modal.test.tsx.snap
  components/quick_switch_modal/index.tsx
  components/quick_switch_modal/quick_switch_modal.test.tsx
  components/quick_switch_modal/quick_switch_modal.tsx
Labels: 4: Reviews Complete

#7078 [MM-28150] add remaining test cases
  e2e/cypress/integration/system_console/user_management_spec.js
  e2e/cypress/support/api/user.d.ts
  e2e/cypress/support/api/user.js
Labels: 4: Reviews Complete

#6996 Fix tooltip text for copying incoming webhook url
  components/integrations/confirm_integration/__snapshots__/confirm_integration.test.jsx.snap
  components/integrations/confirm_integration/confirm_integration.jsx
Labels: 4: Reviews Complete

#7170 [MM-31045] Fix Error when adding group on channel configuration screen
  components/admin_console/team_channel_settings/channel/details/channel_groups.tsx
  components/admin_console/team_channel_settings/channel/details/index.ts
Labels: 3: QA Review

#7066 MM-30373 - Cypress/E2E: Automate backlogs - Messaging > @ autocomplete (9 test cases)
  e2e/cypress/integration/messaging/autocomplete_spec.js
Labels: 4: Reviews Complete

#7158 MM-30381/cypress notifications teammate name MM-T490
  e2e/cypress/integration/notifications/desktop_notifications_spec.js
Labels: 4: Reviews Complete

#7157 MM-30381/cypress notifications teammate name MM-T489
  e2e/cypress/integration/notifications/desktop_notifications_spec.js
  e2e/cypress/integration/notifications/users_with_same_firstname_channel_mentions_spec.js
Labels: 4: Reviews Complete

#7154 MM-30381/cypress notifications teammate name MM-T488
  e2e/cypress/integration/notifications/desktop_notifications_spec.js
  e2e/cypress/integration/notifications/users_with_same_firstname_channel_mentions_spec.js
Labels: 4: Reviews Complete

#7162 [MM-30367] Automate E2E admin roles tests
  components/admin_console/license_settings/__snapshots__/license_settings.test.jsx.snap
  components/admin_console/license_settings/license_settings.jsx
  e2e/cypress/fixtures/console-example-inputs.json
  e2e/cypress/fixtures/system-roles-console-access.json
  e2e/cypress/integration/enterprise/system_console/limited_console_access_spec.js
  e2e/cypress/integration/system_console/limited_console_access_spec.js
Labels: 4: Reviews Complete, AutoMerge

#7187 Cypress/E2E: Automate backlogs - System Console > Compliance Export Downloads
  e2e/cypress.json
  e2e/cypress/integration/enterprise/system_console/compliance/download_compliance_export_file_spec.js
Labels: 4: Reviews Complete

#7192 [MM-31209] Take into account the OFF setting for OPEN ID
  components/admin_console/admin_definition.jsx
Labels: 4: Reviews Complete

#7110 [MM-16139] Migrate 'components/channel_header_dropdown/menu_items/toggle_favorite_channel' module and associated tests to TypeScript
  components/channel_header_dropdown/menu_items/toggle_favorite_channel/__snapshots__/toggle_favorite_channel.test.tsx.snap
  components/channel_header_dropdown/menu_items/toggle_favorite_channel/index.ts
  components/channel_header_dropdown/menu_items/toggle_favorite_channel/toggle_favorite_channel.test.tsx
  components/channel_header_dropdown/menu_items/toggle_favorite_channel/toggle_favorite_channel.tsx
Labels: 4: Reviews Complete, Lifecycle/1:stale

#7207 MM-31275 New sidebar performance improvements
  actions/views/channel_sidebar.ts
  components/legacy_sidebar/sidebar.jsx
  components/sidebar/index.ts
  components/sidebar/sidebar_channel_list/sidebar_channel_list.tsx
  components/sidebar/sidebar_menu/sidebar_menu.tsx
  reducers/views/channel_sidebar.test.ts
  reducers/views/channel_sidebar.ts
Labels: 4: Reviews Complete, AutoMerge, CherryPick/Approved

#7221 MM-31275 New sidebar performance improvements (#7207)
  components/legacy_sidebar/sidebar.jsx
  components/sidebar/sidebar_channel_list/sidebar_channel_list.tsx
  components/sidebar/sidebar_menu/sidebar_menu.tsx
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed

#7193 [MM-27214] Cypress Automation Auth Numero Dos 2
  e2e/cypress/integration/enterprise/system_console/authentication/authentication2_spec.js
Labels: 4: Reviews Complete

#6978 MM-20405: Migrate configuration_bar module and tests to TypeScript
  components/announcement_bar/configuration_bar/__snapshots__/configuration_bar.test.tsx.snap
  components/announcement_bar/configuration_bar/configuration_bar.test.tsx
  components/announcement_bar/configuration_bar/configuration_bar.tsx
  components/announcement_bar/configuration_bar/index.ts
  components/announcement_bar/default_announcement_bar/announcement_bar.tsx
  components/channel_header_dropdown/menu_items/toggle_favorite_channel/toggle_favorite_channel.tsx
  types/store/views.ts
Labels: 4: Reviews Complete, Hacktoberfest, QA Review Done, hacktoberfest-accepted

#7161 MM-30394: Cypress/E2E - System Console > Settings
  e2e/cypress/integration/enterprise/system_console/authentication_method_spec.js
  e2e/cypress/integration/enterprise/system_console/settings_spec.js
  e2e/cypress/integration/system_console/mobile_settings_spec.js
  e2e/cypress/support/api/user.d.ts
  e2e/cypress/support/api/user.js
Labels: 4: Reviews Complete

#7121 Converted 'commands_container' to typescript.
  components/integrations/commands_container/commands_container.tsx
  components/integrations/commands_container/index.ts
Labels: 4: Reviews Complete

#7150 Add text subtypes
  components/apps_modal/apps_modal.tsx
Labels: 2: Dev Review

#7191 [MM-27210] Archived channels 4 part I
  e2e/cypress/integration/archived_channel/archive_channel_operations_spec.js
  e2e/cypress/support/ui/channel.js
Labels: 4: Reviews Complete, AutoMerge

#7229 [MM-31329] Enable @typescript-eslint/array-type
  components/admin_console/member_list_group/member_list_group.tsx
  components/admin_console/plugin_management/plugin_management.tsx
  components/admin_console/radio_setting.tsx
  components/admin_console/reset_password_modal/reset_password_modal.test.tsx
  components/admin_console/system_roles/system_role/system_role.tsx
  components/admin_console/system_user_detail/team_list/abstract_list.tsx
  components/admin_console/system_user_detail/team_list/team_list.tsx
  components/admin_console/system_users/list/system_users_list.tsx
  components/admin_console/team_channel_settings/channel/details/channel_details.tsx
  components/admin_console/team_channel_settings/channel/details/channel_groups.test.tsx
  components/admin_console/team_channel_settings/channel/details/channel_groups.tsx
  components/admin_console/team_channel_settings/channel/details/channel_moderation.tsx
  components/admin_console/team_channel_settings/group/group_list.test.tsx
  components/admin_console/team_channel_settings/group/group_list.tsx
  components/admin_console/team_channel_settings/group/group_users/users_to_remove_groups.tsx
  components/admin_console/team_channel_settings/group/group_users/users_to_remove_role.tsx
  components/channel_invite_modal/channel_invite_modal.tsx
  components/channel_invite_modal/index.ts
  components/legacy_team_sidebar/legacy_team_sidebar_controller.tsx
  components/markdown/markdown.tsx
  components/member_list_channel/index.ts
  components/member_list_channel/member_list_channel.tsx
  components/member_list_team/index.ts
  components/member_list_team/member_list_team.tsx
  components/more_direct_channels/index.ts
  components/more_direct_channels/more_direct_channels.tsx
  components/next_steps_view/steps.ts
  components/permissions_gates/system_permission_gate/index.ts
  components/permissions_gates/system_permission_gate/system_permission_gate.tsx
  components/permissions_gates/team_permission_gate/index.ts
  components/permissions_gates/team_permission_gate/team_permission_gate.tsx
  components/post_view/channel_intro_message/channel_intro_message.tsx
  components/post_view/combined_system_message/combined_system_message.test.tsx
  components/post_view/combined_system_message/combined_system_message.tsx
  components/post_view/combined_system_message/last_users.tsx
  components/rename_channel_modal/rename_channel_modal.test.tsx
  components/rhs_thread/rhs_thread.tsx
  components/select_team/select_team.tsx
  components/system_notice/system_notice.tsx
  components/team_selector_modal/team_selector_modal.tsx
  components/textbox/textbox.tsx
  components/timestamp/timestamp.stories.tsx
  components/timestamp/timestamp.tsx
  components/tutorial/tutorial_tip/tutorial_tip.tsx
  components/user_list_row_with_error/user_list_row_with_error.tsx
  components/user_settings/display/user_settings_display.tsx
  components/user_settings/notifications/email_notification_setting/email_notification_setting.tsx
  components/user_settings/notifications/email_notification_setting/index.ts
  components/widgets/menu/menu_modals/submenu_modal/submenu_modal.tsx
  components/widgets/settings/radio_setting.tsx
  components/widgets/users/avatars/avatars.tsx
  components/widgets/users/users.stories.tsx
  e2e/cypress/support/api/channel.d.ts
  e2e/cypress/support/index.d.ts
  package-lock.json
  package.json
  types/store/rhs.ts
Labels: 4: Reviews Complete

#7190 Mm 30361
  e2e/cypress/integration/enterprise/ldap/ldap_login_spec.js
  e2e/cypress/integration/enterprise/ldap/ldap_setting_spec.js
  e2e/cypress/support/ldap_commands.js
Labels: 4: Reviews Complete

#7123 [MM-30159] Move multiselected channel to other categories via the 3-dot menu
  actions/views/channel_sidebar.ts
  components/sidebar/sidebar_channel/sidebar_channel_link/index.ts
  components/sidebar/sidebar_channel/sidebar_channel_link/sidebar_channel_link.test.tsx
  components/sidebar/sidebar_channel/sidebar_channel_link/sidebar_channel_link.tsx
  components/sidebar/sidebar_channel/sidebar_channel_menu/__snapshots__/sidebar_channel_menu.test.tsx.snap
  components/sidebar/sidebar_channel/sidebar_channel_menu/index.ts
  components/sidebar/sidebar_channel/sidebar_channel_menu/sidebar_channel_menu.test.tsx
  components/sidebar/sidebar_channel/sidebar_channel_menu/sidebar_channel_menu.tsx
  utils/test_helper.ts
Labels: 4: Reviews Complete

#7185 [MM-30360] Cypress/E2E: Account settings
  components/user_settings/security/user_settings_security.tsx
  e2e/cypress/integration/account_settings/display/theme/save_theme_spec.js
  e2e/cypress/integration/account_settings/general/profile_picture_spec.js
  e2e/cypress/integration/account_settings/security/active_sessions_spec.js
  e2e/cypress/integration/menus/status_dropdown_spec.js
Labels: 4: Reviews Complete, AutoMerge

#7160 MM-27312 Allow uploading 10 files per post
  components/file_upload/file_upload.test.jsx
  utils/constants.jsx
Labels: 4: Reviews Complete

#7203 Cypress/E2E: Automate backlogs - System Console > User Mgmt Deactivation (6 test cases)
  e2e/cypress/integration/system_console/user_management/users_spec.js
  e2e/cypress/support/ui_commands.js
Labels: 4: Reviews Complete, AutoMerge

#7145 [MM-31018] Update email address for admin advisor contact requests to support-advisor@mattermost.com
  components/warn_metric_ack_modal/__snapshots__/warn_metric_ack_modal.test.tsx.snap
  components/warn_metric_ack_modal/warn_metric_ack_modal.tsx
Labels: AutoMerge

#7240 Automated cherry pick of #7207
  actions/views/channel_sidebar.ts
  components/legacy_sidebar/sidebar.jsx
  components/sidebar/index.ts
  components/sidebar/sidebar_channel_list/sidebar_channel_list.tsx
  components/sidebar/sidebar_menu/sidebar_menu.tsx
  reducers/views/channel_sidebar.test.ts
  reducers/views/channel_sidebar.ts
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7199 [MM-30383] - Desktop notifications spec
  e2e/cypress/integration/notifications/desktop_notifications_spec.js
Labels: 4: Reviews Complete

#7186 Cypress/E2E: Update MM-T131 to include additional step/verification from archived MM-T2154
  components/quick_switch_modal/__snapshots__/quick_switch_modal.test.tsx.snap
  components/quick_switch_modal/quick_switch_modal.tsx
  e2e/cypress/integration/account_settings/sidebar/channel_switcher_spec.js
  e2e/cypress/integration/archived_channel/archived_leave_channel_spec.js
  e2e/cypress/integration/channel/channel_switcher_spec.js
  e2e/cypress/integration/enterprise/elasticsearch_autocomplete/helpers/index.js
  e2e/cypress/integration/enterprise/elasticsearch_autocomplete/users_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/guest_identification_ui_spec.js
  e2e/cypress/integration/enterprise/ldap/ldap_group_sync_spec.js
  e2e/cypress/integration/keyboard_shortcuts/keyboard_shortcuts_one_spec.js
  e2e/cypress/integration/messaging/ctrl_cmd_k_open_dm_with_mouse_spec.js
  e2e/cypress/integration/messaging/focus_move_spec.js
  e2e/cypress/integration/messaging/message_draft_then_switch_channel_spec.js
  e2e/cypress/integration/messaging/private_channel_open_spec.js
  e2e/cypress/integration/search_autocomplete/renaming_spec.js
  e2e/cypress/integration/search_autocomplete/users_spec.js
  i18n/en.json
Labels: 4: Reviews Complete

#7099 MM-T643 Incoming web-hook: Long URL for embedded image
  e2e/cypress/integration/integrations/incoming_webhook/long_url_embedded_image_spec.js
Labels: 4: Reviews Complete, AutoMerge

#7242 MM-31466 Performance investigation part two
  actions/views/channel_sidebar.ts
  components/create_comment/create_comment.jsx
  components/create_comment/create_comment.test.jsx
  components/sidebar/sidebar_channel/sidebar_channel_menu/index.ts
  components/sidebar/sidebar_channel_list/index.ts
  components/textbox/index.ts
  selectors/views/channel_sidebar.ts
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server

#7244 MM-31466 Performance investigation part two (release-5.30)
  components/create_comment/create_comment.jsx
  components/create_comment/create_comment.test.jsx
  components/sidebar/sidebar_channel/sidebar_channel_menu/index.ts
  components/sidebar/sidebar_channel_list/index.ts
  components/textbox/index.ts
  selectors/views/channel_sidebar.ts
Labels: 2: Dev Review, Changelog/Not Needed, Docs/Not Needed

#7245 MM-31466 Performance investigation part two (cloud)
  actions/views/channel_sidebar.ts
  components/create_comment/create_comment.jsx
  components/create_comment/create_comment.test.jsx
  components/sidebar/sidebar_channel/sidebar_channel_menu/index.ts
  components/sidebar/sidebar_channel_list/index.ts
  components/textbox/index.ts
  selectors/views/channel_sidebar.ts
Labels: 4: Reviews Complete, AutoMerge, Changelog/Not Needed, Docs/Not Needed

#7135 MM-30366: Test group mention synced channel.
  e2e/cypress/integration/enterprise/group_mentions/group_mentions_posts_spec.js
  e2e/cypress/support/api/channel.js
Labels: 4: Reviews Complete, AutoMerge

#7198 [MM-30379] add MM-T433, MM-T437 and MM-T438
  e2e/cypress/integration/multi_team_and_dm/multi_team_spec.js
Labels: 4: Reviews Complete

#6755 [MM-27834] Collapse on more than 5 plugin buttons cypress tests
  e2e/cypress/integration/plugins/plugin_buttons_spec.js
Labels: 4: Reviews Complete

#7233 [MM-31403] Ensure other permissions except billing getting deleted
  components/admin_console/system_roles/system_role/system_role_permissions.tsx
Labels: 4: Reviews Complete

#7129 [MM-28259] custom slash commands e2e tests
  e2e/cypress/integration/integrations/custom_slash_commands/custom_slash_commands_spec.js
  e2e/cypress/integration/integrations/custom_slash_commands/slash_commands_spec.js
Labels: 4: Reviews Complete

#7216 [MM-30357] - Add nickname spec
  e2e/cypress/integration/account_settings/general/nickname_spec.js
Labels: 4: Reviews Complete

#7218 Cypress/E2E: Add custom commands for main menu, channel menu and account settings modal
  e2e/cypress/integration/account_settings/display/account_settings_position_spec.js
  e2e/cypress/integration/emoji/react_to_last_message_shortcut_spec.js
  e2e/cypress/integration/enterprise/cloud/onboarding/cloud_sysadmin_onboarding_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/guest_experience_ui_spec.js
  e2e/cypress/integration/enterprise/ldap_group/invite_bot_spec.js
  e2e/cypress/integration/integrations/incoming_webhook/delete_incoming_webhook_spec.js
  e2e/cypress/integration/integrations/incoming_webhook/incoming_webhook_is_image_only_spec.js
  e2e/cypress/integration/integrations/incoming_webhook/setup_incoming_webhook_spec.js
  e2e/cypress/integration/integrations/integrations_spec.js
  e2e/cypress/integration/integrations/outgoing_webhook/disable_override_username_profile_spec.js
  e2e/cypress/integration/keyboard_shortcuts/keyboard_shortcuts_two_spec.js
  e2e/cypress/integration/menus/main_menu_spec.js
  e2e/cypress/integration/messaging/center_channel_rhs_overlap_spec.js
  e2e/cypress/integration/messaging/inline_images_open_preview_window_spec.js
  e2e/cypress/integration/multi_team_and_dm/town_square_not_marked_as_unread_spec.js
  e2e/cypress/integration/notifications/at_icon_still_shows_mentions_list_with_deactivated_triggers_spec.js
  e2e/cypress/integration/notifications/channel_links_show_as_links_spec.js
  e2e/cypress/support/ui/account_settings_modal.d.ts
  e2e/cypress/support/ui/account_settings_modal.js
  e2e/cypress/support/ui/common.d.ts
  e2e/cypress/support/ui/common.js
  e2e/cypress/support/ui/extend_testing_library.d.ts
  e2e/cypress/support/ui/extend_testing_library.js
  e2e/cypress/support/ui/index.js
  e2e/cypress/support/ui/menu.d.ts
  e2e/cypress/support/ui/menu.js
  e2e/cypress/support/ui_commands.js
  e2e/cypress/utils/index.js
Labels: 4: Reviews Complete

#7134 [MM-30369] Upload files tests
  e2e/cypress/fixtures/mm_file_testing/Audio/AAC.aac
  e2e/cypress/fixtures/mm_file_testing/Audio/FLAC.flac
  e2e/cypress/fixtures/mm_file_testing/Audio/M4A.m4a
  e2e/cypress/fixtures/mm_file_testing/Audio/M4R.m4r
  e2e/cypress/fixtures/mm_file_testing/Audio/MP3.mp3
  e2e/cypress/fixtures/mm_file_testing/Audio/OGG.ogg
  e2e/cypress/fixtures/mm_file_testing/Audio/WAV.wav
  e2e/cypress/fixtures/mm_file_testing/Audio/WMA.wma
  e2e/cypress/fixtures/mm_file_testing/Code/JSON
  e2e/cypress/fixtures/mm_file_testing/Code/Patch.diff
  e2e/cypress/fixtures/mm_file_testing/Code/Python
  e2e/cypress/fixtures/mm_file_testing/Documents/Excel.xlsx
  e2e/cypress/fixtures/mm_file_testing/Documents/PDF.pdf
  e2e/cypress/fixtures/mm_file_testing/Documents/PPT.pptx
  e2e/cypress/fixtures/mm_file_testing/Documents/Text.txt
  e2e/cypress/fixtures/mm_file_testing/Documents/Word.docx
  e2e/cypress/fixtures/mm_file_testing/Images/BMP.bmp
  e2e/cypress/fixtures/mm_file_testing/Images/GIF.gif
  e2e/cypress/fixtures/mm_file_testing/Images/JPG.jpg
  e2e/cypress/fixtures/mm_file_testing/Images/PNG.png
  e2e/cypress/fixtures/mm_file_testing/Images/PSD.psd
  e2e/cypress/fixtures/mm_file_testing/Images/TIFF.tif
  e2e/cypress/fixtures/mm_file_testing/Video/AVI.avi
  e2e/cypress/fixtures/mm_file_testing/Video/MKV.mkv
  e2e/cypress/fixtures/mm_file_testing/Video/MOV.mov
  e2e/cypress/fixtures/mm_file_testing/Video/MP4.mp4
  e2e/cypress/fixtures/mm_file_testing/Video/MPG.mpg
  e2e/cypress/fixtures/mm_file_testing/Video/WEBM.webm
  e2e/cypress/fixtures/mm_file_testing/Video/WMV.wmv
  e2e/cypress/fixtures/svg.svg
  e2e/cypress/integration/files_and_attachments/edit_message_with_attachment_spec.js
  e2e/cypress/integration/files_and_attachments/file_previews_1_spec.js
  e2e/cypress/integration/files_and_attachments/file_previews_2_spec.js
  e2e/cypress/integration/files_and_attachments/paste_image_spec.js
  e2e/cypress/integration/files_and_attachments/upload_files_spec.js
  e2e/cypress/integration/files_and_attachments/youtube_video_spec.js
Labels: 4: Reviews Complete

#7173 [Cypress/E2E, MM-27222] Add test cases, fix makeClient, add/correct types
  e2e/cypress/integration/bot_accounts/display_name_spec.js
  e2e/cypress/integration/bot_accounts/in_teams_and_channels_spec.js
  e2e/cypress/integration/bot_accounts/post_message_spec.js
  e2e/cypress/integration/bot_accounts/promote_demote_spec.js
  e2e/cypress/support/api/bots.d.ts
  e2e/cypress/support/api/bots.js
  e2e/cypress/support/api/channel.d.ts
  e2e/cypress/support/api/channel.js
  e2e/cypress/support/api/setup.d.ts
  e2e/cypress/support/api/team.js
  e2e/cypress/support/client-impl.js
  e2e/cypress/support/client.d.ts
  e2e/cypress/support/client.js
  e2e/cypress/support/index.d.ts
  e2e/cypress/support/ui/index.js
  e2e/cypress/support/ui/team.js
Labels: 4: Reviews Complete

#7259 Lock CI from cloud/release-5.31
  .circleci/config.yml
  .gitlab-ci.yml
Labels: AutoMerge

#7114 Fix: Removed explicitly UTC-based timezone
  utils/datetime.ts
Labels: 4: Reviews Complete

#7204 [MM-27215] Cypress Authentication Part 3 Tests
  components/admin_console/password_settings.jsx
  e2e/cypress.json
  e2e/cypress/integration/enterprise/system_console/authentication/authentication3_spec.js
  e2e/cypress/support/api/user.js
  e2e/cypress/support/env.js
  utils/constants.jsx
Labels: 4: Reviews Complete, AutoMerge

#7255 [Cypress/E2E, MM-27224] Add Test Cases
  e2e/cypress/fixtures/bot-default-avatar.png
  e2e/cypress/integration/bot_accounts/bot_channel_intro_spec.js
  e2e/cypress/integration/bot_accounts/edit_bot_username_spec.js
  e2e/cypress/integration/bot_accounts/in_lists_spec.js
  e2e/cypress/integration/bot_accounts/tags_spec.js
  e2e/cypress/integration/messaging/header_not_cloud_spec.js
  e2e/cypress/support/api/plugin.d.ts
  e2e/cypress/support/api/plugin.js
  e2e/package-lock.json
  e2e/package.json
Labels: 4: Reviews Complete

#7137 [MM-20469] Transformed emoji_list_item to ts
  components/emoji/emoji_list_item/emoji_list_item.tsx
  components/emoji/emoji_list_item/index.ts
Labels: 4: Reviews Complete, Lifecycle/1:stale

#7236 [MM-29927] Add discard when changing page after adding or removing user in system roles
  components/admin_console/system_roles/system_role/system_role.tsx
Labels: 4: Reviews Complete

#7087 MM-T444 DM More... show user count
  e2e/cypress/integration/multi_team_and_dm/dm_more_show_user_count_spec.js
Labels: 4: Reviews Complete

#7040 MM-27230 Cypress/E2E: Automate backlogs - BOT Accounts - Part 07 (10 test cases)
  e2e/cypress/integration/bot_accounts/bot_api_spec.js
  e2e/cypress/support/task_commands.js
Labels: 4: Reviews Complete

#7082 MM-24072-Position the autocomplete popover relative to the @,~,/ trigger in the post draft
  components/__snapshots__/textbox.test.tsx.snap
  components/suggestion/at_mention_provider/at_mention_provider.jsx
  components/suggestion/channel_mention_provider.jsx
  components/suggestion/emoticon_provider.jsx
  components/suggestion/suggestion_box.jsx
  components/suggestion/suggestion_list.jsx
  sass/components/_modal.scss
  sass/components/_suggestion-list.scss
  tests/setup.js
  utils/constants.jsx
  utils/utils.jsx
  utils/utils.test.jsx
Labels: 4: Reviews Complete, AutoMerge
