Repository mattermost/mattermost-webapp, pull requests merged in 2020-05, with the labels that each got.

#5408 Migrate 'components/user_settings/sidebar' module and associated tests to TypeScript:
  components/user_settings/sidebar/__snapshots__/user_settings_sidebar.test.tsx.snap
  components/user_settings/sidebar/index.ts
  components/user_settings/sidebar/user_settings_sidebar.test.tsx
  components/user_settings/sidebar/user_settings_sidebar.tsx
Labels: 3: Reviews Complete, QA Review Done

#5419 add new-separator class to NewMessageSeparator component
  components/post_view/new_message_separator/__snapshots__/new_message_separator.test.jsx.snap
  components/post_view/new_message_separator/new_message_separator.jsx
Labels: 3: Reviews Complete, QA Review Done

#5345 MM-24278 Fixes emoji picker keyboard navigation and highlight style
  components/emoji_picker/emoji_picker.jsx
  e2e/cypress/integration/messaging/emoji_picker_keyboard_usability_spec.js
  sass/components/_emoticons.scss
Labels: 3: Reviews Complete, QA Review Done

#5217 Experimental Sidebar Drag 'n Drop - Proof of Concept with react-beautiful-dnd
  actions/views/channel_sidebar.ts
  components/sidebar/__snapshots__/sidebar.test.tsx.snap
  components/sidebar/sidebar.tsx
  components/sidebar/sidebar_category/__snapshots__/sidebar_category.test.tsx.snap
  components/sidebar/sidebar_category/index.ts
  components/sidebar/sidebar_category/sidebar_category.test.tsx
  components/sidebar/sidebar_category/sidebar_category.tsx
  components/sidebar/sidebar_category_list/__snapshots__/sidebar_category_list.test.tsx.snap
  components/sidebar/sidebar_category_list/index.ts
  components/sidebar/sidebar_category_list/sidebar_category_list.test.tsx
  components/sidebar/sidebar_category_list/sidebar_category_list.tsx
  components/sidebar/sidebar_channel/__snapshots__/sidebar_channel.test.tsx.snap
  components/sidebar/sidebar_channel/index.ts
  components/sidebar/sidebar_channel/sidebar_channel.test.tsx
  components/sidebar/sidebar_channel/sidebar_channel.tsx
  components/sidebar/sidebar_channel/sidebar_channel_link/sidebar_channel_link.tsx
  e2e/cypress/integration/channel_sidebar/drag_and_drop_spec.js
  package-lock.json
  package.json
  reducers/views/channel_sidebar.ts
  sass/layout/_sidebar-left.scss
  selectors/views/channel_sidebar.ts
  types/store/index.ts
  utils/a11y_controller.js
  utils/constants.jsx
  utils/utils.jsx
Labels: 4: Reviews Complete, Setup Cloud Test Server

#5412 [MM-24514] Show groups before non channel members in autocomplete provider
  components/suggestion/at_mention_provider/at_mention_provider.jsx
  components/suggestion/at_mention_provider/at_mention_provider.test.jsx
Labels: 4: Reviews Complete

#5358 MM-24379: Adds create post permission to UI.
  components/admin_console/permission_schemes_settings/guest_permissions_tree/__snapshots__/guest_permissions_tree.test.jsx.snap
  components/admin_console/permission_schemes_settings/guest_permissions_tree/guest_permissions_tree.jsx
  components/admin_console/permission_schemes_settings/guest_permissions_tree/index.jsx
  components/admin_console/permission_schemes_settings/permission_schemes_settings.jsx
  components/admin_console/permission_schemes_settings/permissions_tree/__snapshots__/permissions_tree.test.jsx.snap
  components/admin_console/permission_schemes_settings/permissions_tree/permissions_tree.jsx
  e2e/cypress/integration/enterprise/system_console/system_scheme_permission_spec.js
  e2e/cypress/integration/enterprise/system_console/team_scheme_permission_spec.js
  e2e/cypress/integration/enterprise/system_console/use_channel_mentions_team_scheme_spec.js
  i18n/en.json
Labels: 4: Reviews Complete

#4189 MM-15719 Change to use util func in mm-redux
  components/post_view/post_body_additional_content/post_body_additional_content.jsx
  components/post_view/post_body_additional_content/post_body_additional_content.test.jsx
Labels: QA Review Done

#5393 [MM-24150] [MM-24357] Update special mentions regex to better match server notification behaviour
  utils/constants.jsx
  utils/post_utils.jsx
  utils/text_formatting.test.jsx
  utils/text_formatting.tsx
Labels: 4: Reviews Complete

#5352 [MM-20529] Migrate 'components/file_attachment' module to TypeScript
  components/file_attachment/__snapshots__/file_attachment.test.tsx.snap
  components/file_attachment/__snapshots__/filename_overlay.test.tsx.snap
  components/file_attachment/file_attachment.test.tsx
  components/file_attachment/file_attachment.tsx
  components/file_attachment/filename_overlay.test.tsx
  components/file_attachment/filename_overlay.tsx
  components/file_attachment/index.ts
  components/file_preview/__snapshots__/file_preview.test.tsx.snap
  components/file_preview/__snapshots__/file_progress_preview.test.tsx.snap
  components/file_preview/file_preview.test.tsx
  components/file_preview/file_preview.tsx
  components/file_preview/file_progress_preview.test.tsx
  components/file_preview/file_progress_preview.tsx
  components/file_preview/index.ts
Labels: 4: Reviews Complete, QA Review Done

#5382 MM-24214: Add check for license for group mention API calls
  components/needs_team/index.ts
  components/needs_team/needs_team.test.tsx
  components/needs_team/needs_team.tsx
Labels: 4: Reviews Complete

#5389 MM-24330 - remove table headers if not items exist in table
  components/admin_console/group_settings/groups_list/__snapshots__/groups_list.test.jsx.snap
  components/admin_console/group_settings/groups_list/groups_list.jsx
  components/admin_console/system_user_detail/team_list/__snapshots__/abstract_list.test.tsx.snap
  components/admin_console/system_user_detail/team_list/abstract_list.tsx
  components/admin_console/team_channel_settings/__snapshots__/abstract_list.test.jsx.snap
  components/admin_console/team_channel_settings/abstract_list.jsx
  components/admin_console/team_channel_settings/abstract_list.test.jsx
Labels: 4: Reviews Complete, AutoMerge

#5422 MM-24506: Fix closing DM/GM from header dropdown menu
  components/channel_header_dropdown/menu_items/close_message/close_message.js
  components/channel_header_dropdown/menu_items/close_message/close_message.test.js
  components/channel_header_dropdown/menu_items/close_message/index.js
  e2e/cypress/integration/channel/close_direct_group_spec.js
  e2e/cypress/support/ui_commands.js
Labels: 4: Reviews Complete, CherryPick/Approved

#5435 Automated cherry pick of #5422
  components/channel_header_dropdown/menu_items/close_message/close_message.js
  components/channel_header_dropdown/menu_items/close_message/close_message.test.js
  components/channel_header_dropdown/menu_items/close_message/index.js
  e2e/cypress/integration/channel/close_direct_group_spec.js
  e2e/cypress/support/ui_commands.js
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5378 MM-20895 Experimental Sidebar Features - Custom Category Look n Feel
  components/category_modal.scss
  components/delete_category_modal.tsx
  components/edit_category_modal.tsx
  components/sidebar/__snapshots__/sidebar.test.tsx.snap
  components/sidebar/add_channel_dropdown.tsx
  components/sidebar/index.ts
  components/sidebar/sidebar.test.tsx
  components/sidebar/sidebar.tsx
  components/sidebar/sidebar_category/__snapshots__/sidebar_category.test.tsx.snap
  components/sidebar/sidebar_category/sidebar_category.test.tsx
  components/sidebar/sidebar_category/sidebar_category.tsx
  components/sidebar/sidebar_category_list/sidebar_category_list.test.tsx
  components/sidebar/sidebar_category_list/sidebar_category_list.tsx
  i18n/en.json
  sass/layout/_sidebar-left.scss
Labels: 4: Reviews Complete

#5372 [MM-24177] Don't highlight group mention if doesn't have required permission
  components/create_comment/create_comment.jsx
  components/create_post/create_post.jsx
  components/markdown/index.ts
  components/post_markdown/__snapshots__/post_markdown.test.jsx.snap
  components/post_markdown/index.js
  components/post_markdown/index.test.js
  components/post_markdown/post_markdown.jsx
  components/post_markdown/post_markdown.test.jsx
Labels: 4: Reviews Complete

#5379 MM-24378 MM-24430 Inteactive dialog improvments
  components/interactive_dialog/dialog_element/dialog_element.jsx
  components/interactive_dialog/interactive_dialog.jsx
  components/widgets/settings/bool_setting.tsx
  components/widgets/settings/text_setting.tsx
Labels: 4: Reviews Complete

#5426 migrated do_verify_email component to typescript
  components/do_verify_email/__snapshots__/do_verify_email.test.tsx.snap
  components/do_verify_email/do_verify_email.test.tsx
  components/do_verify_email/do_verify_email.tsx
  components/do_verify_email/index.ts
Labels: 4: Reviews Complete

#4663 MM-15336 - Improve profile popover for posts with overwritten usernam…
  components/post_profile_picture/index.jsx
  components/post_profile_picture/post_profile_picture.jsx
  components/post_view/post_header/index.js
  components/post_view/post_header/post_header.jsx
  components/profile_picture.tsx
  components/profile_popover/profile_popover.jsx
  components/user_profile/__snapshots__/user_profile.test.jsx.snap
  components/user_profile/user_profile.jsx
  i18n/en.json
Labels: 4: Reviews Complete, QA Review Done

#5411 [MM-24521] Restrict group mentions permission to license with LDAP
  components/admin_console/permission_schemes_settings/guest_permissions_tree/__snapshots__/guest_permissions_tree.test.jsx.snap
  components/admin_console/permission_schemes_settings/guest_permissions_tree/guest_permissions_tree.jsx
  components/admin_console/permission_schemes_settings/guest_permissions_tree/guest_permissions_tree.test.jsx
  components/admin_console/permission_schemes_settings/guest_permissions_tree/index.jsx
  components/admin_console/permission_schemes_settings/permissions_tree/__snapshots__/permissions_tree.test.jsx.snap
  components/admin_console/permission_schemes_settings/permissions_tree/index.jsx
  components/admin_console/permission_schemes_settings/permissions_tree/permissions_tree.jsx
  components/admin_console/permission_schemes_settings/permissions_tree/permissions_tree.test.jsx
Labels: 4: Reviews Complete

#5443 E2E: Fix for failing tests on nickname spec
  e2e/cypress/integration/account_settings/general/nickname_spec.js
Labels: 4: Reviews Complete

#5437 translations PR 20200504
  i18n/fr.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/zh-TW.json
Labels: 4: Reviews Complete, AutoMerge, Tests/Not Needed

#5376 Experimental Sidebar Features - Quick Menus look and feel
  actions/channel_actions.jsx
  components/sidebar/__snapshots__/sidebar_menu.test.tsx.snap
  components/sidebar/sidebar_category/sidebar_category.tsx
  components/sidebar/sidebar_category/sidebar_category_menu/__snapshots__/sidebar_category_menu.test.tsx.snap
  components/sidebar/sidebar_category/sidebar_category_menu/index.ts
  components/sidebar/sidebar_category/sidebar_category_menu/sidebar_category_menu.test.tsx
  components/sidebar/sidebar_category/sidebar_category_menu/sidebar_category_menu.tsx
  components/sidebar/sidebar_channel/sidebar_channel_close.tsx
  components/sidebar/sidebar_channel/sidebar_channel_link/__snapshots__/sidebar_channel_link.test.tsx.snap
  components/sidebar/sidebar_channel/sidebar_channel_link/sidebar_channel_link.tsx
  components/sidebar/sidebar_channel/sidebar_channel_menu/__snapshots__/sidebar_channel_menu.test.tsx.snap
  components/sidebar/sidebar_channel/sidebar_channel_menu/index.ts
  components/sidebar/sidebar_channel/sidebar_channel_menu/sidebar_channel_menu.test.tsx
  components/sidebar/sidebar_channel/sidebar_channel_menu/sidebar_channel_menu.tsx
  components/sidebar/sidebar_menu.test.tsx
  components/sidebar/sidebar_menu.tsx
  components/widgets/menu/menu_items/menu_item.scss
  components/widgets/menu/menu_items/submenu_item.test.tsx
  components/widgets/menu/menu_items/submenu_item.tsx
  components/widgets/menu/menu_modals/submenu_modal/__snapshots__/submenu_modal.test.tsx.snap
  components/widgets/menu/menu_modals/submenu_modal/submenu_modal.test.tsx
  components/widgets/menu/menu_wrapper.test.tsx
  components/widgets/menu/menu_wrapper.tsx
  fonts/mattermosticons/mattermosticons.eot
  fonts/mattermosticons/mattermosticons.ttf
  i18n/en.json
  package-lock.json
  package.json
  sass/layout/_sidebar-left.scss
  sass/responsive/_mobile.scss
Labels: 4: Reviews Complete, Setup Cloud Test Server

#5418 Check license expiration, disable license and notify administrator
  utils/license_utils.jsx
Labels: 4: Reviews Complete

#5444 E2E: Fix tests failing on URL check
  e2e/cypress/integration/channel_sidebar/channel_sidebar_spec.js
  e2e/cypress/integration/channel_sidebar/new_channel_dropdown_spec.js
Labels: 4: Reviews Complete

#5429 MM-24757 E2E: upload test artifacts to S3
  e2e/cypress/plugins/index.js
  e2e/cypress/support/index.js
  e2e/cypress/support/task_commands.js
  e2e/package-lock.json
  e2e/package.json
  e2e/run_tests.js
  e2e/utils/save_artifacts.js
Labels: 4: Reviews Complete, AutoMerge

#5432 MM-24032: Make settings' textarea only vertically resizable
  sass/routes/_settings.scss
Labels: 4: Reviews Complete, QA Review Done, Setup Cloud Test Server

#5414 [MM-24632] Show valid group mentions as blue
  components/at_mention/__snapshots__/at_mention.test.jsx.snap
  components/at_mention/at_mention.jsx
  components/at_mention/at_mention.test.jsx
  components/at_mention/index.jsx
  components/markdown/markdown.tsx
  components/post_markdown/__snapshots__/post_markdown.test.jsx.snap
  components/post_markdown/post_markdown.jsx
  components/post_markdown/post_markdown.test.jsx
  package-lock.json
  package.json
  sass/components/_mentions.scss
  utils/__snapshots__/message_html_to_component.test.jsx.snap
  utils/message_html_to_component.jsx
  utils/message_html_to_component.test.jsx
  utils/text_formatting.tsx
  utils/utils.jsx
Labels: 4: Reviews Complete

#5441 fix missing dash between tos/pp
  components/about_build_modal/__snapshots__/about_build_modal.test.jsx.snap
  components/about_build_modal/about_build_modal.jsx
Labels: 4: Reviews Complete, Setup Cloud Test Server

#5450 [MM-24767] autocomplete icons
  components/suggestion/command_provider.jsx
  components/suggestion/command_provider.test.js
Labels: 1: UX Review

#5401 MM-24490 - Updating UI for link previews name
  sass/components/_post.scss
Labels: 4: Reviews Complete

#5280 MM-23038: Compliance report fixes
  components/admin_console/jobs/table.jsx
  components/admin_console/jobs/table.test.jsx
  components/admin_console/message_export_settings.jsx
  components/admin_console/message_export_settings.test.jsx
  i18n/en.json
  utils/constants.jsx
Labels: 4: Reviews Complete

#5271 [MM-5881] Add support for searching by position in user lists
  components/more_direct_channels/__snapshots__/more_direct_channels.test.jsx.snap
  utils/utils.jsx
Labels: AutoMerge, QA Review Done

#5431 E2E: Add invalidate cache API command
  e2e/cypress/support/api_commands.js
  e2e/cypress/support/index.js
Labels: 4: Reviews Complete

#5440 E2E: fix tests for sidebar link in system console
  e2e/cypress/integration/enterprise/system_console/sidebar_link_navigation_spec.js
  e2e/cypress/integration/system_console/sidebar_link_navigation_spec.js
Labels: 4: Reviews Complete

#5456 MM-24942 Clean up setting AllowedUntrustedInternalConnections on test specs
  e2e/cypress/integration/interactive_dialog/boolean_spec.js
  e2e/cypress/integration/interactive_dialog/full_dialog_spec.js
  e2e/cypress/integration/interactive_dialog/scrollable_spec.js
  e2e/cypress/integration/interactive_dialog/simple_dialog_spec.js
  e2e/cypress/integration/interactive_menu/basic_options_spec.js
  e2e/cypress/integration/interactive_menu/select_with_keys_spec.js
  e2e/cypress/integration/interactive_menu/slack_parsing_message_button_spec.js
Labels: 4: Reviews Complete

#5448 [MM-24521] Restrict group mentions permission fix typo during merge
  components/admin_console/permission_schemes_settings/permissions_tree/__snapshots__/permissions_tree.test.jsx.snap
  components/admin_console/permission_schemes_settings/permissions_tree/permissions_tree.jsx
Labels: 4: Reviews Complete

#5459 MM-24966 Update group mention toggle to include (Beta)
  components/admin_console/group_settings/group_details/group_profile_and_settings.jsx
  i18n/en.json
Labels: 4: Reviews Complete

#5462 MM-24715: fix getstate refactor
  actions/channel_actions.jsx
  actions/post_actions.jsx
  actions/user_actions.jsx
  components/permalink_view/actions.js
Labels: 4: Reviews Complete, CherryPick/Approved

#5452 MM-24033: Compute suggestion list width
  components/add_user_to_channel_modal/__snapshots__/add_user_to_channel_modal.test.jsx.snap
  components/add_user_to_channel_modal/add_user_to_channel_modal.jsx
  sass/components/_modal.scss
  sass/components/_suggestion-list.scss
  sass/utils/_modifiers.scss
Labels: 4: Reviews Complete, QA Review Done

#5460 E2E: Fix failing tests on mark as unread and toast specs
  e2e/cypress/integration/mark_as_unread/mark_as_unread_spec.js
  e2e/cypress/integration/toast/toast_spec.js
Labels: 3: QA Review

#5463 MM-24918: Make sure flagged posts and recent mentions from old channel are excluded in RHS
  actions/websocket_actions.jsx
  e2e/cypress/integration/websocket/handle_removed_user_spec.js
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server

#5464 Fixed accessibility dropdowns spec and added file path to report
  e2e/cypress/integration/accessibility/accessibility_dropdowns_spec.js
  e2e/cypress/support/index.js
Labels: 4: Reviews Complete

#5438 [MM-24764] [MM-24673] Dont call member counts by group when no license or permission
  actions/websocket_actions.jsx
  components/create_comment/create_comment.jsx
  components/create_comment/create_comment.test.jsx
  components/create_comment/index.js
  components/create_post/create_post.jsx
  components/create_post/create_post.test.jsx
  components/create_post/index.js
Labels: 4: Reviews Complete

#5405 MM-24054: Do not populate channels list after user clears the search
  components/add_user_to_channel_modal/__snapshots__/add_user_to_channel_modal.test.jsx.snap
  components/add_user_to_channel_modal/add_user_to_channel_modal.jsx
Labels: QA Review Done

#5362 MM-23816: Group Mentions: Add ability to rename group names
  components/admin_console/group_settings/group_details/__snapshots__/group_details.test.jsx.snap
  components/admin_console/group_settings/group_details/__snapshots__/group_profile.test.jsx.snap
  components/admin_console/group_settings/group_details/__snapshots__/group_profile_and_settings.test.jsx.snap
  components/admin_console/group_settings/group_details/group_details.jsx
  components/admin_console/group_settings/group_details/group_details.test.jsx
  components/admin_console/group_settings/group_details/group_details_errors.jsx
  components/admin_console/group_settings/group_details/group_profile.jsx
  components/admin_console/group_settings/group_details/group_profile.test.jsx
  components/admin_console/group_settings/group_details/group_profile_and_settings.jsx
  components/admin_console/group_settings/group_details/group_profile_and_settings.test.jsx
  components/admin_console/group_settings/group_details/index.jsx
  i18n/en.json
  sass/components/_groups.scss
Labels: 4: Reviews Complete

#5474 MM-25019 E2E: Fix failing tests due to disabled post textbox
  e2e/cypress/integration/enterprise/system_console/team_scheme_permission_spec.js
  e2e/cypress/integration/keyboard_shortcuts/alt_option_plus_up_down_spec.js
Labels: 4: Reviews Complete

#5453 [MM-23694] - Improve channel switcher feedback when there are no results
  components/no_results_indicator/no_results_indicator.tsx
  components/no_results_indicator/types.ts
  components/quick_switch_modal/__snapshots__/quick_switch_modal.test.jsx.snap
  components/quick_switch_modal/quick_switch_modal.jsx
  components/suggestion/suggestion_box.jsx
  components/suggestion/suggestion_list.jsx
  i18n/en.json
  images/search.svg
  sass/components/_module.scss
  sass/components/_no-results-indicator.scss
Labels: 1: UX Review, 2: Dev Review, AutoMerge, CherryPick/Approved, QA Review Done

#5262 [MM-22171] Move `loadedPlugins` into redux-store
  actions/websocket_actions.test.jsx
  plugins/index.js
  reducers/plugins/index.js
  utils/constants.jsx
Labels: 4: Reviews Complete, QA Review Done

#5341 [MM-22806] Make search hints interactive
  components/search_bar/__snapshots__/search_bar.test.jsx.snap
  components/search_bar/search_bar.jsx
  components/search_hint/__snapshots__/search_hint.test.tsx.snap
  components/search_hint/search_hint.test.tsx
  components/search_hint/search_hint.tsx
  components/search_results/search_results.jsx
  components/sidebar_right/index.js
  components/sidebar_right/sidebar_right.jsx
  components/suggestion/suggestion_box.jsx
  i18n/de.json
  i18n/en.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
  sass/components/_popover.scss
  sass/components/_search.scss
  utils/constants.jsx
Labels: QA Review Done

#5478 E2E: fix failing tests on image attachment and markdown
  e2e/cypress/integration/markdown/markdown_image_spec.js
  e2e/cypress/integration/messaging/image_attachment_spec.js
Labels: 4: Reviews Complete

#5477 MM-25097 Update Cypress default config
  e2e/cypress/fixtures/partial_default_config.json
Labels: 4: Reviews Complete

#5289 [MM-21494] autocomplete suggestions
  components/__snapshots__/textbox.test.jsx.snap
  components/suggestion/at_mention_provider/at_mention_provider.jsx
  components/suggestion/command_provider.jsx
  components/suggestion/command_provider.test.js
  components/suggestion/suggestion_box.jsx
  package-lock.json
Labels: 4: Reviews Complete

#5326 [MM-23535] Adds disable database search config flag to the admin console
  components/admin_console/admin_definition.jsx
  components/admin_console/database_settings.jsx
  i18n/en.json
Labels: 4: Reviews Complete

#5488 Revert "[MM-22171] Move `loadedPlugins` into redux-store (#5262)"
  actions/websocket_actions.test.jsx
  plugins/index.js
  reducers/plugins/index.js
  utils/constants.jsx
Labels: 4: Reviews Complete, AutoMerge

#5473 [MM-24695] Small code refactor + Only groups you are apart of get highlighted yellow
  components/at_mention/at_mention.jsx
  components/needs_team/index.ts
  components/needs_team/needs_team.test.tsx
  components/needs_team/needs_team.tsx
  components/post_markdown/index.test.js
  package-lock.json
  package.json
Labels: 4: Reviews Complete

#5484 E2E: Add apiEmailTest to check SMTP setup before proceeding to actual test
  e2e/cypress/integration/email/mention_email_notification_spec.js
  e2e/cypress/integration/signin_authentication/forgot_password_spec.js
  e2e/cypress/support/api_commands.js
Labels: 4: Reviews Complete

#5476 MM-24956 Add saving data to automation dashboard
  .gitignore
  e2e/cypress/fixtures/partial_default_config.json
  e2e/package-lock.json
  e2e/package.json
  e2e/run_tests.js
  e2e/utils/dashboard.js
  e2e/utils/file.js
  e2e/utils/report.js
  e2e/utils/save_artifacts.js
Labels: 4: Reviews Complete

#5367 MM-24126 Supporing plugin full page routes.
  components/needs_team/index.ts
  components/needs_team/needs_team.tsx
  components/root/index.js
  components/root/root.jsx
  plugins/registry.js
Labels: 4: Reviews Complete

#5436 MM-24781 Make GM profiles API calls to be concurrent
  actions/user_actions.jsx
  actions/user_actions.test.js
  package-lock.json
  package.json
Labels: 4: Reviews Complete

#5457 MM-24082: Add profile picture attribute to admin console settings
  components/admin_console/admin_definition.jsx
  i18n/en.json
Labels: 4: Reviews Complete

#4907 Mm 20517 Migrate 'components/rhs_thread' module and associated tests to TypeScript
  components/post_view/floating_timestamp/__snapshots__/floating_timestamp.test.tsx.snap
  components/post_view/floating_timestamp/floating_timestamp.test.tsx
  components/post_view/floating_timestamp/floating_timestamp.tsx
  components/post_view/floating_timestamp/index.ts
  components/rhs_thread/__snapshots__/rhs_thread.test.tsx.snap
  components/rhs_thread/index.ts
  components/rhs_thread/rhs_thread.test.tsx
  components/rhs_thread/rhs_thread.tsx
  package.json
Labels: 4: Reviews Complete

#5501 MM-25245 Fix failing tests related to LDAP when running on CI
  e2e/cypress.json
  e2e/cypress/integration/enterprise/ldap_group/channel_modes_spec.js
  e2e/cypress/integration/enterprise/ldap_group/groups_assign_roles_spec.js
  e2e/cypress/integration/enterprise/ldap_group/team_and_channel_assign_roles_spec.js
Labels: 4: Reviews Complete

#5421 MM-25177 Update latex_block.jsx to left-align math
  components/latex_block/latex_block.jsx
Labels: 4: Reviews Complete

#5494 MM-25000: In-Product Discovery
  components/admin_console/__snapshots__/admin_console.test.tsx.snap
  components/admin_console/admin_definition.jsx
  components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.jsx.snap
  components/admin_console/feature_discovery/__snapshots__/feature_discovery.test.tsx.snap
  components/admin_console/feature_discovery/feature_discovery.scss
  components/admin_console/feature_discovery/feature_discovery.test.tsx
  components/admin_console/feature_discovery/feature_discovery.tsx
  components/admin_console/feature_discovery/ldap.tsx
  components/admin_console/feature_discovery/saml.tsx
  components/invitation_modal/invitation_modal_members_step.scss
  e2e/cypress/integration/system_console/feature_discovery_spec.js
  i18n/en.json
  images/feature-discovery/ldap.png
  images/feature-discovery/saml.png
  utils/admin_console_index.test.jsx
Labels: 4: Reviews Complete

#4922 [MM-20565] Fix: #13507 - Migrate grouplist to TS
  components/admin_console/group_settings/groups_list/__snapshots__/groups_list.test.tsx.snap
  components/admin_console/group_settings/groups_list/groups_list.test.tsx
  components/admin_console/group_settings/groups_list/groups_list.tsx
  components/admin_console/group_settings/groups_list/index.ts
Labels: 4: Reviews Complete, QA Review Done

#5503 Revert "Updating compass icons to replace mattermost icons"
  fonts/compass-icons.eot
  fonts/compass-icons.svg
  fonts/compass-icons.ttf
  fonts/compass-icons.woff
  fonts/compass-icons.woff2
  fonts/mattermosticons/mattermosticons.eot
  fonts/mattermosticons/mattermosticons.svg
  fonts/mattermosticons/mattermosticons.ttf
  fonts/mattermosticons/mattermosticons.woff
  fonts/mattermosticons/mattermosticons.woff2
  sass/base/_mattermost-icons.scss
Labels: 2: Dev Review, 3: QA Review

#5510 Fix image
  .circleci/config.yml
Labels: AutoMerge

#5245 MM-23395: Add websockets support for update group
  actions/websocket_actions.jsx
  utils/constants.jsx
Labels: 4: Reviews Complete

#5398 MM-24549 Fix for skipping user info calls for hidden GM's
  actions/user_actions.jsx
  actions/user_actions.test.js
Labels: 4: Reviews Complete

#4993 [MM-22734] Support different interactive message button styles
  components/post_view/message_attachments/action_button.jsx
  components/post_view/message_attachments/action_button.test.jsx
  components/post_view/message_attachments/action_button/__snapshots__/action_button.test.jsx.snap
  components/post_view/message_attachments/action_button/action_button.jsx
  components/post_view/message_attachments/action_button/action_button.test.jsx
  components/post_view/message_attachments/action_button/index.js
  components/post_view/message_attachments/message_attachment/__snapshots__/message_attachment.test.jsx.snap
Labels: 4: Reviews Complete

#5466 MM-25095: Compress JS and CSS files with Brotli.
  package-lock.json
  package.json
  webpack.config.js
Labels: 4: Reviews Complete

#5500 MM-25184: Update ldap filters examples.
  components/admin_console/admin_definition.jsx
  i18n/en.json
Labels: 4: Reviews Complete

#5483 MM-24965: Re-evaluate transitions on RHS state change
  components/sidebar_right/sidebar_right.jsx
  e2e/cypress/integration/search/mobile_search_spec.js
Labels: 4: Reviews Complete

#5475 MM-24176: Regenerate invite code when making team private.
  components/team_general_tab/team_general_tab.jsx
  i18n/en.json
Labels: 4: Reviews Complete

#5449 [MM-24154] - Prevent copying of certain elements in posts
  components/widgets/users/avatar.scss
  sass/components/_post-menu.scss
  sass/components/_post.scss
Labels: 2: Dev Review, CherryPick/Approved, QA Review Done, Setup Cloud Test Server

#5469 [MM-14906] Add TeamMembers block which builds off of UserGrid and DataGrid
  actions/user_actions.jsx
  actions/user_actions.test.js
  components/add_users_to_team_modal/__snapshots__/add_users_to_team_modal.test.tsx.snap
  components/add_users_to_team_modal/add_users_to_team_modal.test.tsx
  components/add_users_to_team_modal/add_users_to_team_modal.tsx
  components/add_users_to_team_modal/index.ts
  components/admin_console/data_grid/__snapshots__/data_grid.test.tsx.snap
  components/admin_console/data_grid/data_grid.scss
  components/admin_console/data_grid/data_grid.test.tsx
  components/admin_console/data_grid/data_grid.tsx
  components/admin_console/data_grid/data_grid_header.tsx
  components/admin_console/data_grid/data_grid_row.tsx
  components/admin_console/data_grid/data_grid_search.tsx
  components/admin_console/team_channel_settings/remove_confirm_modal.jsx
  components/admin_console/team_channel_settings/team/details/__snapshots__/team_details.test.jsx.snap
  components/admin_console/team_channel_settings/team/details/index.js
  components/admin_console/team_channel_settings/team/details/team_details.jsx
  components/admin_console/team_channel_settings/team/details/team_details.test.jsx
  components/admin_console/team_channel_settings/team/details/team_members/__snapshots__/team_members.test.tsx.snap
  components/admin_console/team_channel_settings/team/details/team_members/index.ts
  components/admin_console/team_channel_settings/team/details/team_members/team_members.test.tsx
  components/admin_console/team_channel_settings/team/details/team_members/team_members.tsx
  components/admin_console/user_grid/__snapshots__/user_grid.test.tsx.snap
  components/admin_console/user_grid/user_grid.scss
  components/admin_console/user_grid/user_grid.test.tsx
  components/admin_console/user_grid/user_grid.tsx
  components/admin_console/user_grid/user_grid_name.tsx
  components/admin_console/user_grid/user_grid_remove.tsx
  components/admin_console/user_grid/user_grid_role_dropdown.tsx
  components/widgets/admin_console/admin_panel.scss
  i18n/en.json
  package-lock.json
  package.json
  utils/test_helper.ts
Labels: 4: Reviews Complete

#5455 [MM-24332] Add ‘extend session length’ setting
  components/admin_console/admin_definition.jsx
  components/admin_console/admin_settings.tsx
  components/admin_console/session_length_settings.jsx
  e2e/cypress/integration/enterprise/system_console/session_length_spec.js
  e2e/cypress/integration/system_console/session_length_spec.js
  i18n/en.json
  utils/admin_console_index.test.jsx
Labels: 4: Reviews Complete, CherryPick/Approved

#5480 [MM-14912] Add channel members block to channel details page
  actions/user_actions.jsx
  actions/user_actions.test.js
  components/admin_console/team_channel_settings/channel/details/__snapshots__/channel_details.test.tsx.snap
  components/admin_console/team_channel_settings/channel/details/channel_details.test.tsx
  components/admin_console/team_channel_settings/channel/details/channel_details.tsx
  components/admin_console/team_channel_settings/channel/details/channel_members/__snapshots__/channel_members.test.tsx.snap
  components/admin_console/team_channel_settings/channel/details/channel_members/channel_members.test.tsx
  components/admin_console/team_channel_settings/channel/details/channel_members/channel_members.tsx
  components/admin_console/team_channel_settings/channel/details/channel_members/index.ts
  components/admin_console/team_channel_settings/channel/details/index.js
  components/channel_invite_modal/__snapshots__/channel_invite_modal.test.jsx.snap
  components/channel_invite_modal/channel_invite_modal.jsx
  components/channel_invite_modal/channel_invite_modal.test.jsx
  components/channel_invite_modal/index.js
  components/channel_members_modal/channel_members_modal.tsx
  i18n/en.json
  utils/test_helper.ts
Labels: 4: Reviews Complete, CherryPick/Approved

#5522 MM-25305 Fix E2E tests due to duplicate team/channel/user
  e2e/cypress/integration/account_settings/general/fullname_spec.js
  e2e/cypress/integration/channel_sidebar/category_collapsing_unread_filter_spec.js
  e2e/cypress/integration/channel_sidebar/channel_sidebar_spec.js
  e2e/cypress/integration/channel_sidebar/history_channel_switcher_spec.js
  e2e/cypress/integration/channel_sidebar/hotkeys_spec.js
  e2e/cypress/integration/channel_sidebar/new_channel_dropdown_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/guest_invitation_ui_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/member_invitation_ui_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/system_console_manage_guest_spec.js
  e2e/cypress/integration/enterprise/ldap/ldap_login_spec.js
  e2e/cypress/integration/enterprise/system_console/channel_moderation_spec.js
  e2e/cypress/integration/enterprise/system_console/team_guest_channel_spec.js
  e2e/cypress/integration/integrations/integrations_spec.js
  e2e/cypress/integration/messaging/mobile_message_deletion_spec.js
  e2e/cypress/integration/onboarding/existing_email_adress_spec.js
  e2e/cypress/integration/team_settings/create_a_team_spec.js
  e2e/cypress/integration/team_settings/teams_spec.js
  e2e/cypress/integration/websocket/handle_removed_user_spec.js
  e2e/cypress/support/api_commands.js
  e2e/cypress/utils/index.js
  e2e/package-lock.json
  e2e/package.json
Labels: 4: Reviews Complete

#5120 Adding bleve to the admin console
  actions/admin_actions.jsx
  components/admin_console/__snapshots__/admin_console.test.tsx.snap
  components/admin_console/__snapshots__/bleve_settings.test.jsx.snap
  components/admin_console/admin_definition.jsx
  components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.jsx.snap
  components/admin_console/bleve_settings.jsx
  components/admin_console/bleve_settings.test.jsx
  i18n/en.json
  i18n/es.json
  utils/constants.jsx
Labels: CherryPick/Approved

#5470 [MM-24507] Affix comment input to bottom in right-hand side (RHS)
  components/create_comment/create_comment.jsx
  components/favicon_title_handler/favicon_title_handler.tsx
  components/post_view/floating_timestamp/floating_timestamp.tsx
  components/rhs_thread/__snapshots__/rhs_thread.test.tsx.snap
  components/rhs_thread/index.ts
  components/rhs_thread/rhs_thread.scss
  components/rhs_thread/rhs_thread.test.tsx
  components/rhs_thread/rhs_thread.tsx
  sass/components/_post-right.scss
  sass/layout/_sidebar-right.scss
Labels: 4: Reviews Complete

#5427 [MM-24376] Show channel (and team) as unread if system message is adding current user to channel
  actions/post_utils.js
  actions/post_utils.test.js
Labels: 4: Reviews Complete

#5505 MM-24380 - Add ability to add components to the left and right of the RHS
  actions/views/rhs.js
  components/search_results_header/index.jsx
  components/search_results_header/search_results_header.jsx
  plugins/registry.js
  plugins/rhs_plugin/index.js
  plugins/rhs_plugin/rhs_plugin.jsx
  reducers/plugins/index.js
  utils/constants.jsx
Labels: 4: Reviews Complete, CherryPick/Approved

#5465 MM-24086:Disable changing picture if LDAP sync'ed
  components/__snapshots__/setting_picture.test.jsx.snap
  components/setting_picture.jsx
  components/setting_picture.test.jsx
  components/team_general_tab/__snapshots__/team_general_tab.test.jsx.snap
  components/team_general_tab/team_general_tab.jsx
  components/team_general_tab/team_general_tab.test.jsx
  components/user_settings/general/index.js
  components/user_settings/general/user_settings_general.jsx
  components/user_settings/general/user_settings_general.test.js
Labels: 4: Reviews Complete

#5542 Automated cherry pick of #5505
  actions/views/rhs.js
  components/search_results_header/index.jsx
  components/search_results_header/search_results_header.jsx
  plugins/registry.js
  plugins/rhs_plugin/index.js
  plugins/rhs_plugin/rhs_plugin.jsx
  reducers/plugins/index.js
  utils/constants.jsx
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5543 Automated cherry pick of #5465
  components/__snapshots__/setting_picture.test.jsx.snap
  components/setting_picture.jsx
  components/setting_picture.test.jsx
  components/team_general_tab/__snapshots__/team_general_tab.test.jsx.snap
  components/team_general_tab/team_general_tab.jsx
  components/team_general_tab/team_general_tab.test.jsx
  components/user_settings/general/index.js
  components/user_settings/general/user_settings_general.jsx
  components/user_settings/general/user_settings_general.test.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5502 [MM-25165] Fix search bar disappearing
  components/admin_console/team_channel_settings/abstract_list.jsx
  components/admin_console/team_channel_settings/channel/list/__snapshots__/channel_list.test.tsx.snap
  components/admin_console/team_channel_settings/channel/list/channel_list.tsx
  components/admin_console/team_channel_settings/group/__snapshots__/group_list.test.tsx.snap
  components/admin_console/team_channel_settings/team/list/__snapshots__/team_list.test.jsx.snap
  components/admin_console/team_channel_settings/team/list/team_list.jsx
  sass/components/_team-channel-settings.scss
Labels: 4: Reviews Complete

#5549 Automated cherry pick of #5502
  components/admin_console/team_channel_settings/abstract_list.jsx
  components/admin_console/team_channel_settings/channel/list/__snapshots__/channel_list.test.tsx.snap
  components/admin_console/team_channel_settings/channel/list/channel_list.tsx
  components/admin_console/team_channel_settings/group/__snapshots__/group_list.test.tsx.snap
  components/admin_console/team_channel_settings/team/list/__snapshots__/team_list.test.jsx.snap
  components/admin_console/team_channel_settings/team/list/team_list.jsx
  sass/components/_team-channel-settings.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5541 MM-25369: Disable Brotli in 'dev' mode.
  webpack.config.js
Labels: 2: Dev Review

#5508 MM-22304 Enable SAML OKTA test in CircleCI/Cypress
  .gitignore
  e2e/cypress.json
  e2e/cypress.okta.json
  e2e/cypress/fixtures/partial_default_config.json
  e2e/cypress/integration/enterprise/saml/okta_login_spec.js
  e2e/cypress/integration/enterprise/saml/saml_metadata_spec.js
  e2e/cypress/plugins/index.js
  e2e/cypress/support/api_commands.js
  e2e/cypress/support/common_login_commands.js
  e2e/cypress/support/saml_commands.js
Labels: 4: Reviews Complete

#5468 MM-25386 Add support for PostgreSQL & PL/pgSQL syntax highlighting
  types/external/highlightjs.d.ts
  utils/constants.jsx
  utils/syntax_highlighting.tsx
Labels: 4: Reviews Complete

#5499 [MM-21494] Slash Command Autocomplete
  components/__snapshots__/textbox.test.jsx.snap
  components/suggestion/at_mention_provider/at_mention_provider.jsx
  components/suggestion/command_provider.jsx
  components/suggestion/command_provider.test.js
  components/suggestion/suggestion_box.jsx
  package-lock.json
Labels: CherryPick/Approved, QA Review Done

#5551 Automated cherry pick of #5499
  components/__snapshots__/textbox.test.jsx.snap
  components/suggestion/at_mention_provider/at_mention_provider.jsx
  components/suggestion/command_provider.jsx
  components/suggestion/command_provider.test.js
  components/suggestion/suggestion_box.jsx
  package-lock.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5534 MM-25345 Fix plugin file upload
  e2e/cypress/fixtures/partial_default_config.json
  e2e/cypress/integration/messaging/message_channel_draw_spec.js
  e2e/cypress/integration/plugins/marketplace/marketplace_spec.js
  e2e/cypress/integration/system_console/plugin_upload_spec.js
  e2e/cypress/support/api_commands.js
Labels: 4: Reviews Complete

#5491 MM-22064: Update verbage for domain restrictions
  components/admin_console/admin_definition.jsx
  i18n/en.json
Labels: 4: Reviews Complete

#5548 Fix "rending > rendering" typo in Latex help text
  components/admin_console/admin_definition.jsx
  i18n/en.json
Labels: 4: Reviews Complete

#5530 [MM-23937] Add e2e tests for group mentions
  components/admin_console/group_settings/group_details/__snapshots__/group_profile.test.jsx.snap
  components/admin_console/group_settings/group_details/__snapshots__/group_profile_and_settings.test.jsx.snap
  components/admin_console/group_settings/group_details/group_profile.jsx
  components/admin_console/group_settings/group_details/group_profile_and_settings.jsx
  e2e/cypress/integration/enterprise/ldap_group/group_mentions_spec.js
  e2e/cypress/support/api_commands.js
  sass/components/_groups.scss
Labels: 2: Dev Review, 3: QA Review, CherryPick/Approved

#5550 [MM-23690] Not showing updated / correct roles when searching for user in the team members modal after their role has been updated
  components/member_list_team/index.ts
  components/member_list_team/member_list_team.tsx
Labels: 4: Reviews Complete

#5495 MM-24423 Don't close the sidebar when clicking global permalink.
  components/needs_team/index.ts
  components/needs_team/needs_team.test.tsx
  components/needs_team/needs_team.tsx
  components/permalink_redirector/actions.js
  components/permalink_redirector/index.js
  components/permalink_redirector/permalink_redirector.jsx
  components/permalink_redirector/permalink_redirector.test.jsx
  components/root/index.js
  components/root/root.jsx
  reducers/views/rhs.js
  reducers/views/rhs.test.js
  selectors/local_storage.js
Labels: 4: Reviews Complete, CherryPick/Approved

#5562 Automated cherry pick of #5495
  components/needs_team/index.ts
  components/needs_team/needs_team.test.tsx
  components/needs_team/needs_team.tsx
  components/permalink_redirector/actions.js
  components/permalink_redirector/index.js
  components/permalink_redirector/permalink_redirector.jsx
  components/permalink_redirector/permalink_redirector.test.jsx
  components/root/index.js
  components/root/root.jsx
  reducers/views/rhs.js
  reducers/views/rhs.test.js
  selectors/local_storage.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5540 MM-25363 Separate logic between running Cypress specs and saving/publishing test reports
  e2e/run_tests.js
  e2e/save_report.js
  e2e/utils/artifacts.js
  e2e/utils/constants.js
  e2e/utils/report.js
Labels: 4: Reviews Complete

#5546 [MM-23938] [MM-25361] Team and Channel pages e2e tests
  actions/user_actions.jsx
  components/admin_console/team_channel_settings/channel/details/__snapshots__/channel_groups.test.tsx.snap
  components/admin_console/team_channel_settings/channel/details/channel_groups.tsx
  components/admin_console/team_channel_settings/channel/details/channel_members/__snapshots__/channel_members.test.tsx.snap
  components/admin_console/team_channel_settings/channel/details/channel_members/channel_members.tsx
  components/admin_console/team_channel_settings/channel/details/channel_modes.tsx
  components/admin_console/team_channel_settings/team/details/__snapshots__/team_groups.test.jsx.snap
  components/admin_console/team_channel_settings/team/details/team_groups.jsx
  components/admin_console/team_channel_settings/team/details/team_members/__snapshots__/team_members.test.tsx.snap
  components/admin_console/team_channel_settings/team/details/team_members/team_members.tsx
  components/admin_console/team_channel_settings/team/details/team_modes.jsx
  components/admin_console/user_grid/user_grid.tsx
  components/admin_console/user_grid/user_grid_role_dropdown.tsx
  components/toggle_modal_button.jsx
  e2e/cypress/integration/enterprise/ldap_group/team_and_channel_assign_roles_spec.js
  e2e/cypress/integration/enterprise/system_console/channel_members_spec.js
  e2e/cypress/integration/enterprise/system_console/channel_moderation_spec.js
  e2e/cypress/integration/enterprise/system_console/session_length_spec.js
  e2e/cypress/integration/enterprise/system_console/team_members_spec.js
  e2e/cypress/integration/system_console/session_length_spec.js
Labels: 4: Reviews Complete, CherryPick/Approved

#5574 Automated cherry pick of #5546
  actions/user_actions.jsx
  components/admin_console/team_channel_settings/channel/details/__snapshots__/channel_groups.test.tsx.snap
  components/admin_console/team_channel_settings/channel/details/channel_groups.tsx
  components/admin_console/team_channel_settings/channel/details/channel_members/__snapshots__/channel_members.test.tsx.snap
  components/admin_console/team_channel_settings/channel/details/channel_members/channel_members.tsx
  components/admin_console/team_channel_settings/channel/details/channel_modes.tsx
  components/admin_console/team_channel_settings/team/details/__snapshots__/team_groups.test.jsx.snap
  components/admin_console/team_channel_settings/team/details/team_groups.jsx
  components/admin_console/team_channel_settings/team/details/team_members/__snapshots__/team_members.test.tsx.snap
  components/admin_console/team_channel_settings/team/details/team_members/team_members.tsx
  components/admin_console/team_channel_settings/team/details/team_modes.jsx
  components/admin_console/user_grid/user_grid.tsx
  components/admin_console/user_grid/user_grid_role_dropdown.tsx
  components/toggle_modal_button.jsx
  e2e/cypress/integration/enterprise/ldap_group/team_and_channel_assign_roles_spec.js
  e2e/cypress/integration/enterprise/system_console/channel_members_spec.js
  e2e/cypress/integration/enterprise/system_console/channel_moderation_spec.js
  e2e/cypress/integration/enterprise/system_console/session_length_spec.js
  e2e/cypress/integration/enterprise/system_console/team_members_spec.js
  e2e/cypress/integration/system_console/session_length_spec.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5544 MM-22155 ESLint configuration updates part 1
  .eslintrc.json
  components/admin_console/audits/audits.tsx
  components/admin_console/data_grid/data_grid_search.tsx
  components/admin_console/system_user_detail/team_list/abstract_list.tsx
  components/admin_console/team_channel_settings/channel/list/channel_list.tsx
  components/admin_console/text_setting.tsx
  components/admin_console/user_grid/user_grid.tsx
  components/analytics/format.tsx
  components/channel_groups_manage_modal/channel_groups_manage_modal.tsx
  components/channel_groups_manage_modal/index.ts
  components/common/infinite_scroll.jsx
  components/do_verify_email/do_verify_email.tsx
  components/do_verify_email/index.ts
  components/file_attachment/filename_overlay.test.tsx
  components/link_tooltip/link_tooltip.tsx
  components/multiselect/multiselect.test.tsx
  components/popover_list_members/popover_list_members.jsx
  components/post_emoji/post_emoji.tsx
  components/rhs_thread/rhs_thread.tsx
  components/searchable_user_list/searchable_user_list.jsx
  components/sidebar/channel_navigator/index.ts
  components/sidebar/sidebar_category_list/sidebar_category_list.tsx
  components/sidebar/sidebar_channel/sidebar_base_channel/sidebar_base_channel.tsx
  components/sidebar/sidebar_channel/sidebar_channel_icon/sidebar_channel_icon.tsx
  components/team_groups_manage_modal/team_groups_manage_modal.jsx
  components/team_sidebar/team_button/index.ts
  components/user_list_row/user_list_row.jsx
  components/widgets/menu/menu_items/submenu_item.tsx
  components/widgets/menu/menu_wrapper_animation.tsx
  e2e/cypress/integration/accessibility/accessibility_popovers_spec.js
  e2e/cypress/integration/emoji/react_to_last_message_shortcut_spec.js
  selectors/i18n.test.js
  utils/constants.jsx
  utils/markdown/renderer.tsx
  utils/paste.test.tsx
Labels: 4: Reviews Complete

#5375 MM-23524: Integrate Dependency-Check to CircleCI
  .circleci/config.yml
Labels: AutoMerge

#5577 translations PR 20200525
  i18n/de.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 4: Reviews Complete, AutoMerge

#5385 MM-23665: Read channel right before leaving it
  components/channel_view/__snapshots__/channel_view.test.jsx.snap
  components/channel_view/channel_view.jsx
  components/channel_view/channel_view.test.jsx
  components/post_view/post_list/index.js
  components/post_view/post_list/post_list.jsx
  components/post_view/post_list/post_list.test.jsx
  components/post_view/post_view.jsx
  components/post_view/post_view.test.js
Labels: 4: Reviews Complete, CherryPick/Approved

#5570 Rename Error type to ServerError
  components/admin_console/system_users/system_users_dropdown/index.ts
  components/admin_console/system_users/system_users_dropdown/system_users_dropdown.tsx
  components/do_verify_email/do_verify_email.tsx
  components/new_channel_flow/index.ts
  components/new_channel_flow/new_channel_flow.tsx
  package-lock.json
  package.json
Labels: 4: Reviews Complete

#5533 [MM-25128] Fixed keyboard shortcut on new channel sidebar
  components/sidebar/sidebar_category_list/sidebar_category_list.tsx
Labels: 4: Reviews Complete, CherryPick/Approved

#5579 MM-25527 Improve Cypress reporting to accommodate master/release/PR in partial/full view
  e2e/save_report.js
  e2e/utils/report.js
Labels: 4: Reviews Complete

#5558 MM-24211 - Updating emoji list css
  sass/components/_suggestion-list.scss
Labels: 3: QA Review, AutomatedCherryPick, CherryPick/Approved, Setup Cloud Test Server

#5583 Automated cherry pick of #5558
  sass/components/_suggestion-list.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5557 MM-25032 - Fixing margins of channels name
  sass/components/_team-channel-settings.scss
Labels: 4: Reviews Complete, AutomatedCherryPick, CherryPick/Approved, QA Review Done

#5584 Automated cherry pick of #5557
  sass/components/_team-channel-settings.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5573 [MM-20775] Fix: Highlighting is not updated correctly when Group Mention is modified/enabled/disabled until user reloads the page
  actions/websocket_actions.jsx
Labels: 4: Reviews Complete, CherryPick/Approved

#5582 Automated cherry pick of #5533
  components/sidebar/sidebar_category_list/sidebar_category_list.tsx
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5564 Remove event listener when modal is closed
  components/view_image/view_image.jsx
Labels: 4: Reviews Complete

#5585 Automated cherry pick of #5573
  actions/websocket_actions.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5560 [MM-24929] Force red background on mobile view header mention badge
  sass/layout/_navigation.scss
Labels: 4: Reviews Complete, CherryPick/Approved, QA Review Done

#5586 Manual cherry pick of #5385
  components/channel_view/__snapshots__/channel_view.test.jsx.snap
  components/channel_view/channel_view.jsx
  components/channel_view/channel_view.test.jsx
  components/post_view/post_list/index.js
  components/post_view/post_list/post_list.jsx
  components/post_view/post_list/post_list.test.jsx
  components/post_view/post_view.jsx
  components/post_view/post_view.test.js
Labels: 4: Reviews Complete, AutoMerge, Changelog/Not Needed, Docs/Not Needed

#5588 Automated cherry pick of #5560
  sass/layout/_navigation.scss
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5568 Update en.json
  i18n/en.json
Labels: 4: Reviews Complete, CherryPick/Approved

#5590 Automated cherry pick of #5568
  i18n/en.json
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5559 MM-25357 Fix tests for formatGithubCodePaste
  utils/paste.test.tsx
Labels: CherryPick/Approved

#5595 Automated cherry pick of #5559
  utils/paste.test.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5580 MM-25531 Filter E2E production tests
  e2e/cypress/integration/accessibility/accessibility_image_spec.js
  e2e/cypress/integration/accessibility/accessibility_keyboard_usability_spec.js
  e2e/cypress/integration/accessibility/accessibility_nav_diff_regions_spec.js
  e2e/cypress/integration/accessibility/accessibility_popovers_spec.js
  e2e/cypress/integration/channel/close_direct_group_spec.js
  e2e/cypress/integration/channel_sidebar/category_collapsing_unread_filter_spec.js
  e2e/cypress/integration/channel_sidebar/history_channel_switcher_spec.js
  e2e/cypress/integration/channel_sidebar/hotkeys_spec.js
  e2e/cypress/integration/channel_sidebar/new_channel_dropdown_spec.js
  e2e/cypress/integration/enterprise/elasticsearch_autocomplete/channels_spec.js
  e2e/cypress/integration/enterprise/elasticsearch_autocomplete/renaming_spec.js
  e2e/cypress/integration/enterprise/elasticsearch_autocomplete/system_console_spec.js
  e2e/cypress/integration/enterprise/elasticsearch_autocomplete/users_spec.js
  e2e/cypress/integration/enterprise/ldap_group/groups_assign_roles_spec.js
  e2e/cypress/integration/enterprise/system_console/system_scheme_permission_spec.js
  e2e/cypress/integration/enterprise/system_console/team_guest_channel_spec.js
  e2e/cypress/integration/integrations/builtin_commands/common_commands_spec.js
  e2e/cypress/integration/integrations/builtin_commands/user_status_commands_spec.js
  e2e/cypress/integration/integrations/message_to_channel_via_slash_command_spec.js
  e2e/cypress/integration/keyboard_shortcuts/alt_option_plus_up_down_spec.js
  e2e/cypress/integration/messaging/channel_read_after_permalink_spec.js
  e2e/cypress/integration/messaging/date_separator_spec.js
  e2e/cypress/integration/messaging/emoji_followed_by_punctuation_spec.js
  e2e/cypress/integration/messaging/emoji_insert_position_spec.js
  e2e/cypress/integration/messaging/emoji_keyboard_entry_spec.js
  e2e/cypress/integration/messaging/focus_move_spec.js
  e2e/cypress/integration/messaging/header_spec.js
  e2e/cypress/integration/messaging/input_box_expands_spec.js
  e2e/cypress/integration/messaging/long_draft_spec.js
  e2e/cypress/integration/messaging/message_draft_then_switch_channel_spec.js
  e2e/cypress/integration/messaging/message_permalink_spec.js
  e2e/cypress/integration/messaging/message_reaction_spec.js
  e2e/cypress/integration/messaging/message_reply_spec.js
  e2e/cypress/integration/messaging/permalink_loading_indicator_spec.js
  e2e/cypress/integration/messaging/permalink_message_edit_spec.js
  e2e/cypress/integration/messaging/send_message_via_profile_popover_spec.js
  e2e/cypress/integration/messaging/system_message_limited_options_spec.js
  e2e/cypress/integration/multi_team_and_dm/existing_channel_name_spec.js
  e2e/cypress/integration/plugins/marketplace/marketplace_spec.js
  e2e/cypress/integration/search/post_search_display_spec.js
  e2e/cypress/integration/signin_authentication/subpath_login_spec.js
Labels: 3: QA Review

#5578 MM-25479 Fix failing test on emoji picker item
  e2e/cypress/integration/messaging/message_reaction_spec.js
Labels: 4: Reviews Complete

#5581 E2E: Quick fix on failing tests in LDAP
  e2e/cypress/integration/enterprise/ldap_group/search_channels_spec.js
  e2e/cypress/integration/enterprise/teams/search_teams_spec.js
Labels: 4: Reviews Complete

#5569 MM-25014: Set GroupMention Name if null when toggled
  components/admin_console/group_settings/group_details/group_details.jsx
  components/admin_console/group_settings/group_details/group_details.test.jsx
  components/admin_console/group_settings/group_details/group_profile.jsx
  components/admin_console/group_settings/group_details/group_profile_and_settings.jsx
Labels: 4: Reviews Complete, CherryPick/Approved

#5592 [MM-25409] Switch to css variable for search options hover state
  sass/components/_search.scss
Labels: 4: Reviews Complete, CherryPick/Approved, QA Review Done

#5604 Automated cherry pick of #5592
  sass/components/_search.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5593 MM-25492, MM-25485, MM-25483 - Autocomplete ui fixes
  components/suggestion/channel_mention_provider.jsx
  components/suggestion/search_channel_with_permissions_provider.jsx
  sass/components/_suggestion-list.scss
Labels: 4: Reviews Complete, AutomatedCherryPick, CherryPick/Approved, QA Review Done

#5605 Automated cherry pick of #5593
  components/suggestion/channel_mention_provider.jsx
  components/suggestion/search_channel_with_permissions_provider.jsx
  sass/components/_suggestion-list.scss
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5600 Revert "[MM-24507] Affix comment input to bottom in right-hand side (RHS) (#5470)"
  components/create_comment/create_comment.jsx
  components/favicon_title_handler/favicon_title_handler.tsx
  components/post_view/floating_timestamp/floating_timestamp.tsx
  components/rhs_thread/__snapshots__/rhs_thread.test.tsx.snap
  components/rhs_thread/index.ts
  components/rhs_thread/rhs_thread.scss
  components/rhs_thread/rhs_thread.test.tsx
  components/rhs_thread/rhs_thread.tsx
  sass/components/_post-right.scss
  sass/layout/_sidebar-right.scss
Labels: CherryPick/Approved

#5601 Automated cherry pick of #5569
  components/admin_console/group_settings/group_details/group_details.jsx
  components/admin_console/group_settings/group_details/group_details.test.jsx
  components/admin_console/group_settings/group_details/group_profile.jsx
  components/admin_console/group_settings/group_details/group_profile_and_settings.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5589 MM-25449 Update regex used for trimming strings
  package-lock.json
  package.json
Labels: 4: Reviews Complete, CherryPick/Approved

#5492 [MM-24999] fix css on Copy Theme Colors button
  sass/routes/_settings.scss
Labels: 4: Reviews Complete, Setup Cloud Test Server

#5594 [MM-25533] Restored scrolling to autocomplete popover in search bar
  sass/components/_popover.scss
Labels: 4: Reviews Complete, CherryPick/Approved

#5612 Automated cherry pick of #5594
  sass/components/_popover.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5572 [MM-24705] Add telemetry for Experimental Sidebar Phase 2
  components/edit_category_modal/edit_category_modal.tsx
  components/sidebar/sidebar.tsx
  components/sidebar/sidebar_category/sidebar_category.tsx
  components/sidebar/sidebar_category/sidebar_category_menu/__snapshots__/sidebar_category_menu.test.tsx.snap
  components/sidebar/sidebar_category/sidebar_category_menu/sidebar_category_menu.tsx
  components/sidebar/sidebar_category_list/sidebar_category_list.tsx
  components/sidebar/sidebar_channel/sidebar_channel_menu/__snapshots__/sidebar_channel_menu.test.tsx.snap
  components/sidebar/sidebar_channel/sidebar_channel_menu/sidebar_channel_menu.tsx
Labels: 4: Reviews Complete

#5615 Revert "MM-24380 - Add ability to add components to the left and right of the RHS (#5505)"
  actions/views/rhs.js
  components/search_results_header/index.jsx
  components/search_results_header/search_results_header.jsx
  plugins/registry.js
  plugins/rhs_plugin/index.js
  plugins/rhs_plugin/rhs_plugin.jsx
  reducers/plugins/index.js
  utils/constants.jsx
Labels: 4: Reviews Complete, CherryPick/Approved

#5507 MM-24761 Fix hashtag click has no affect when plugin LinkTooltip is registered
  components/link_tooltip/__snapshots__/link_tooltip.test.tsx.snap
  components/link_tooltip/link_tooltip.test.tsx
  components/link_tooltip/link_tooltip.tsx
  utils/__snapshots__/message_html_to_component.test.jsx.snap
  utils/message_html_to_component.jsx
Labels: 4: Reviews Complete, CherryPick/Approved

#5617 Automated cherry pick of #5507
  components/link_tooltip/__snapshots__/link_tooltip.test.tsx.snap
  components/link_tooltip/link_tooltip.test.tsx
  components/link_tooltip/link_tooltip.tsx
  utils/__snapshots__/message_html_to_component.test.jsx.snap
  utils/message_html_to_component.jsx
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5611 MM-24677: Stage group configuration changes.
  components/admin_console/group_settings/group_details/__snapshots__/group_details.test.jsx.snap
  components/admin_console/group_settings/group_details/__snapshots__/group_teams_and_channels_row.test.jsx.snap
  components/admin_console/group_settings/group_details/group_details.jsx
  components/admin_console/group_settings/group_details/group_details.test.jsx
  components/admin_console/group_settings/group_details/group_teams_and_channels.jsx
  components/admin_console/group_settings/group_details/group_teams_and_channels.test.jsx
  components/admin_console/group_settings/group_details/group_teams_and_channels_row.jsx
  components/channel_selector_modal/channel_selector_modal.jsx
  components/widgets/icons/mentions_icon.jsx
  e2e/cypress/integration/system_console/group_configuration_spec.js
  e2e/cypress/support/api_commands.js
  sass/components/_groups.scss
Labels: 2: Dev Review, 3: QA Review, CherryPick/Approved

#5620 Fix common commands
  e2e/cypress/integration/integrations/builtin_commands/common_commands_spec.js
Labels: 4: Reviews Complete

#5619 Fix accessibility buttons
  e2e/cypress/integration/accessibility/accessibility_buttons_spec.js
Labels: 4: Reviews Complete

#5623 Quick fix: minor update on Cypress report
  e2e/utils/report.js
Labels: 3: QA Review

#5561 MM-25468 Fix not being able to change sidebar settings
  components/user_settings/sidebar/user_settings_sidebar.tsx
Labels: 4: Reviews Complete

#5618 Fix input specs
  e2e/cypress/integration/accessibility/accessibility_input_fields_spec.js
  e2e/cypress/integration/messaging/message_reply_input_box_expand_spec.js
Labels: 4: Reviews Complete

#5518 MM-24818: Fix leaving archived channels
  actions/views/channel.js
  e2e/cypress/integration/channel/archived_channels_spec.js
  e2e/cypress/support/ui_commands.js
Labels: 4: Reviews Complete, CherryPick/Approved
