Repository mattermost/mattermost-webapp, pull requests merged in 2020-06, with the labels that each got.

#5599 Update NOTICE.txt
  NOTICE.txt
Labels: 4: Reviews Complete, CherryPick/Approved

#5631 Automated cherry pick of #5599
  NOTICE.txt
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5598 MM-24751 - Upgrading the plugin from 0.2 to 0.3 changes the incident list to a blank RHS
  actions/views/rhs.js
  actions/views/rhs.test.js
  actions/websocket_actions.test.jsx
  plugins/actions.js
  plugins/index.js
  plugins/pluggable/__snapshots__/pluggable.test.jsx.snap
  plugins/pluggable/pluggable.test.jsx
  plugins/rhs_plugin/index.js
  plugins/rhs_plugin/rhs_plugin.jsx
  reducers/views/rhs.js
  reducers/views/rhs.test.js
  selectors/rhs.ts
  types/store/rhs.ts
Labels: 4: Reviews Complete, AutomatedCherryPick, CherryPick/Approved

#5566 MM-24180 Make emojis in posts selectable
  components/post_emoji/post_emoji.test.tsx
  components/post_emoji/post_emoji.tsx
  e2e/cypress/integration/messaging/message_spec.js
  sass/components/_emoticons.scss
  sass/components/_post.scss
Labels: 4: Reviews Complete, QA Review Done

#5627 Update mattermost-redux to re-add missing Client4 method
  package-lock.json
  package.json
Labels: 4: Reviews Complete

#5610 [MM-25373] [MM-25374] [MM-25106] - Fix functionality bugs in search hint popover
  components/search_bar/__snapshots__/search_bar.test.jsx.snap
  components/search_bar/search_bar.jsx
  components/search_hint/__snapshots__/search_hint.test.tsx.snap
  components/search_hint/search_hint.tsx
  utils/constants.jsx
Labels: 2: Dev Review, 4: Reviews Complete, CherryPick/Approved

#5639 Automated cherry pick of #5610
  components/search_bar/__snapshots__/search_bar.test.jsx.snap
  components/search_bar/search_bar.jsx
  components/search_hint/__snapshots__/search_hint.test.tsx.snap
  components/search_hint/search_hint.tsx
  utils/constants.jsx
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5637 [MM-25685] Change out of channel msg to show X others when >3 users
  components/post_view/post_add_channel_member/__snapshots__/post_add_channel_member.test.jsx.snap
  components/post_view/post_add_channel_member/post_add_channel_member.jsx
  components/post_view/post_add_channel_member/post_add_channel_member.test.jsx
  i18n/en.json
Labels: 4: Reviews Complete, CherryPick/Approved

#5640 Automated cherry pick of #5637
  components/post_view/post_add_channel_member/__snapshots__/post_add_channel_member.test.jsx.snap
  components/post_view/post_add_channel_member/post_add_channel_member.jsx
  components/post_view/post_add_channel_member/post_add_channel_member.test.jsx
  i18n/en.json
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5629 [MM-25561] Added extra padding on admin console sidebar when announcement bar is visible
  sass/routes/_admin-console.scss
Labels: 4: Reviews Complete, CherryPick/Approved

#5641 Automated cherry pick of #5629
  sass/routes/_admin-console.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5485 [MM-22815][MM-23693][MM-23735] - Improve empty states on RHS search variants
  actions/views/rhs.js
  components/emoji_picker/emoji_picker.jsx
  components/no_results_indicator/no_results_indicator.tsx
  components/quick_switch_modal/quick_switch_modal.jsx
  components/search_bar/index.jsx
  components/search_bar/search_bar.jsx
  components/search_hint/__snapshots__/flag_post_search_hint.test.jsx.snap
  components/search_hint/__snapshots__/no_result_search_hint.test.jsx.snap
  components/search_hint/__snapshots__/pin_post_search_hint.test.jsx.snap
  components/search_hint/flag_post_search_hint.jsx
  components/search_hint/flag_post_search_hint.test.jsx
  components/search_hint/no_result_search_hint.jsx
  components/search_hint/no_result_search_hint.test.jsx
  components/search_hint/pin_post_search_hint.jsx
  components/search_hint/pin_post_search_hint.test.jsx
  components/search_results/index.jsx
  components/search_results/search_results.jsx
  components/sidebar_right/sidebar_right.jsx
  i18n/en.json
  images/search.svg
  sass/components/_no-results-indicator.scss
  sass/components/_search.scss
  sass/layout/_sidebar-right.scss
Labels: 2: Dev Review, 4: Reviews Complete, CherryPick/Approved

#5613 E2E: Fix failing tests on team and channel role assignment
  e2e/cypress/integration/enterprise/ldap_group/team_and_channel_assign_roles_spec.js
  e2e/cypress/support/api_commands.js
Labels: 4: Reviews Complete

#5614 E2E: Fix LDAP tests for CircleCI
  e2e/cypress/fixtures/partial_default_config.json
  e2e/cypress/integration/enterprise/ldap/ldap_login_spec.js
  e2e/cypress/support/api_commands.js
Labels: 4: Reviews Complete, AutoMerge

#5487 [MM-22858] Include invalid value in username validation message
  utils/utils.jsx
Labels: 4: Reviews Complete

#5532 Adding request trial interface
  actions/admin_actions.jsx
  components/admin_console/license_settings/index.js
  components/admin_console/license_settings/license_settings.jsx
  i18n/en.json
  sass/routes/_admin-console.scss
Labels: 4: Reviews Complete

#5624 MM-25604 Add help text check to session length settings
  e2e/cypress/integration/enterprise/system_console/session_length_spec.js
  e2e/cypress/integration/system_console/session_length_spec.js
Labels: 4: Reviews Complete

#5563 MM-25050: Enable cluster encryption
  components/admin_console/__snapshots__/cluster_settings.test.jsx.snap
  components/admin_console/admin_definition.jsx
  components/admin_console/cluster_settings.jsx
  components/admin_console/cluster_settings.test.jsx
  e2e/cypress/integration/system_console/cluster_spec.js
  i18n/en.json
Labels: 4: Reviews Complete

#5645 Automated cherry pick of #5644
  sass/layout/_legacy-sidebar-left.scss
  sass/layout/_sidebar-left.scss
  sass/layout/_team-sidebar.scss
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5621 Fix focus move
  e2e/cypress/integration/messaging/focus_move_spec.js
Labels: 4: Reviews Complete

#5651 Fix hotkeys, user status commands, leave channel specs
  e2e/cypress/integration/channel_sidebar/hotkeys_spec.js
  e2e/cypress/integration/integrations/builtin_commands/user_status_commands_spec.js
  e2e/cypress/support/ui_commands.js
Labels: 3: QA Review

#5646 Fix accessibility account settings
  e2e/cypress/integration/accessibility/accessibility_account_settings_spec.js
Labels: 4: Reviews Complete

#5648 Fix emoji html text
  e2e/cypress/integration/markdown/markdown_text_spec.js
  e2e/cypress/integration/messaging/emoji_followed_by_punctuation_spec.js
  e2e/cypress/integration/messaging/emoji_insert_position_spec.js
  e2e/cypress/integration/messaging/message_parse_spec.js
Labels: 4: Reviews Complete

#5650 Fix no results message
  e2e/cypress/integration/search_date_filter/date_filter_spec.js
  e2e/cypress/integration/search_date_filter/negative_filter_spec.js
Labels: 4: Reviews Complete

#5655 MM-25768 Add typings to Cypress custom commands for quick reference via IDE intellisense
  e2e/cypress/support/api_commands.d.ts
  e2e/cypress/support/api_commands.js
  e2e/package-lock.json
  e2e/package.json
Labels: 2: Dev Review, 3: QA Review

#5656 Automated cherry pick of #5654
  root.html
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5660 Fix accessibility dropdowns
  e2e/cypress/integration/accessibility/accessibility_dropdowns_spec.js
Labels: 4: Reviews Complete

#5657 Fix channel name
  e2e/cypress/integration/enterprise/system_console/channel_moderation_spec.js
Labels: 4: Reviews Complete

#5554 [MM-22776] Implement auto scroll to permission that is disabled from channel moderation widget
  components/admin_console/permission_schemes_settings/__snapshots__/permission_group.test.jsx.snap
  components/admin_console/permission_schemes_settings/guest_permissions_tree/__snapshots__/guest_permissions_tree.test.jsx.snap
  components/admin_console/permission_schemes_settings/guest_permissions_tree/guest_permissions_tree.jsx
  components/admin_console/permission_schemes_settings/permission_group.jsx
  components/admin_console/permission_schemes_settings/permission_schemes_settings.jsx
  components/admin_console/permission_schemes_settings/permission_system_scheme_settings/__snapshots__/permission_system_scheme_settings.test.jsx.snap
  components/admin_console/permission_schemes_settings/permission_system_scheme_settings/permission_system_scheme_settings.jsx
  components/admin_console/permission_schemes_settings/permission_team_scheme_settings/__snapshots__/permission_team_scheme_settings.test.jsx.snap
  components/admin_console/permission_schemes_settings/permission_team_scheme_settings/permission_team_scheme_settings.jsx
  components/admin_console/team_channel_settings/channel/details/__snapshots__/channel_details.test.tsx.snap
  components/admin_console/team_channel_settings/channel/details/__snapshots__/channel_moderation.test.tsx.snap
  components/admin_console/team_channel_settings/channel/details/channel_details.tsx
  components/admin_console/team_channel_settings/channel/details/channel_moderation.test.tsx
  components/admin_console/team_channel_settings/channel/details/channel_moderation.tsx
  i18n/en.json
Labels: 4: Reviews Complete

#5658 Fix test: Invite Member via Email containing upper case letters
  e2e/cypress/integration/enterprise/guest_accounts/member_invitation_ui_spec.js
Labels: 4: Reviews Complete

#5446 Show emoji aliases
  components/emoji_picker/components/emoji_picker_preview.jsx
  sass/components/_emoticons.scss
Labels: 4: Reviews Complete

#5667 [MM-25828] Fix incorrect globe / lock icon for private and public channels
  components/channel_selector_modal/channel_selector_modal.jsx
Labels: CherryPick/Approved

#5661 Fix unstable messaging specs
  e2e/cypress/integration/messaging/at_mentions_spec.js
  e2e/cypress/integration/messaging/date_separator_spec.js
  e2e/cypress/integration/messaging/header_spec.js
  e2e/cypress/integration/messaging/message_draft_then_switch_channel_spec.js
  e2e/cypress/integration/search/post_search_display_spec.js
Labels: 4: Reviews Complete

#5643 MM-25557 Fix &nbsp; appearing in the View Members modal
  components/user_list_row/user_list_row.jsx
Labels: 4: Reviews Complete

#5653 [MM-24154] - Fix firefox select issue
  sass/components/_post.scss
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server

#5630 MM-25604 E2E for extending session with web/email login
  e2e/cypress.json
  e2e/cypress/integration/enterprise/extend_session/email_login_activity_spec.js
  e2e/cypress/integration/enterprise/extend_session/session_length_spec.js
  e2e/cypress/plugins/db_request.js
  e2e/cypress/plugins/index.js
  e2e/cypress/support/api_commands.js
  e2e/cypress/support/db_commands.js
  e2e/cypress/support/index.js
  e2e/cypress/utils/index.js
  e2e/package-lock.json
  e2e/package.json
Labels: 4: Reviews Complete

#5663 E2E: Fix failing test on system message by waiting for a message if posted before continuing test
  e2e/cypress/integration/multi_team_and_dm/system_message_spec.js
  e2e/cypress/support/api_commands.d.ts
  e2e/cypress/support/ui_commands.d.ts
  e2e/cypress/support/ui_commands.js
Labels: 4: Reviews Complete

#5647 [MM-25757] - Add latest UI requirements to search hint popover
  components/__snapshots__/quick_input.test.jsx.snap
  components/quick_input.jsx
  components/quick_input.test.jsx
  components/search_bar/__snapshots__/search_bar.test.jsx.snap
  components/search_bar/search_bar.jsx
  components/search_hint/__snapshots__/search_hint.test.tsx.snap
  components/search_hint/search_hint.tsx
Labels: 4: Reviews Complete, CherryPick/Approved

#5244 [GH-13731] Migrates 'components/textbox' module and associated tests to TypeScript
  .eslintrc.json
  components/__snapshots__/textbox.test.tsx.snap
  components/textbox.test.tsx
  components/textbox/index.ts
  components/textbox/textbox.tsx
  components/textbox/textbox_links/index.ts
  components/textbox/textbox_links/textbox_links.tsx
  package-lock.json
  package.json
Labels: 4: Reviews Complete

#5682 [MM-25757] - Add latest UI requirements to search hint popover (#5647)
  components/__snapshots__/quick_input.test.jsx.snap
  components/quick_input.jsx
  components/quick_input.test.jsx
  components/search_bar/__snapshots__/search_bar.test.jsx.snap
  components/search_bar/search_bar.jsx
  components/search_hint/__snapshots__/search_hint.test.tsx.snap
  components/search_hint/search_hint.tsx
Labels: AutoMerge, CherryPick/Done

#5670 Automated cherry pick of #5653
  sass/components/_post.scss
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5666 [MM-24205] Remove tabability from collapsed channel menus
  components/sidebar/sidebar_channel/sidebar_channel_link/__snapshots__/sidebar_channel_link.test.tsx.snap
  components/sidebar/sidebar_channel/sidebar_channel_link/sidebar_channel_link.tsx
  components/sidebar/sidebar_channel/sidebar_channel_menu/__snapshots__/sidebar_channel_menu.test.tsx.snap
  components/sidebar/sidebar_channel/sidebar_channel_menu/sidebar_channel_menu.test.tsx
  components/sidebar/sidebar_channel/sidebar_channel_menu/sidebar_channel_menu.tsx
  components/sidebar/sidebar_menu/sidebar_menu.tsx
Labels: 4: Reviews Complete, QA Review Done

#5686 [ MM-25860] Ensure calls to load page are only made once
  components/admin_console/user_grid/user_grid.tsx
Labels: 4: Reviews Complete, CherryPick/Approved

#5692 Automated cherry pick of #5686
  components/admin_console/user_grid/user_grid.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5664 MM-25791: Fixes bugs saving group details.
  components/admin_console/group_settings/group_details/group_details.jsx
  components/admin_console/group_settings/group_details/group_details_errors.jsx
  e2e/cypress/integration/system_console/group_configuration_spec.js
Labels: 4: Reviews Complete, CherryPick/Approved

#5687 MM-25687 - Updating mentions icon fill
  components/widgets/icons/mentions_icon.jsx
Labels: 4: Reviews Complete, AutoMerge, AutomatedCherryPick, CherryPick/Approved, QA Review Done

#5693 Automated cherry pick of #5664
  components/admin_console/group_settings/group_details/group_details.jsx
  components/admin_console/group_settings/group_details/group_details_errors.jsx
  e2e/cypress/integration/system_console/group_configuration_spec.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5659 MM-24361 - Updating system console save button
  components/admin_console/team_channel_settings/team/details/__snapshots__/team_profile.test.jsx.snap
  components/admin_console/team_channel_settings/team/details/team_profile.jsx
  sass/routes/_admin-console.scss
Labels: 4: Reviews Complete

#5694 Automated cherry pick of #5687
  components/widgets/icons/mentions_icon.jsx
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5695 [MM-25921] Modify admin console index tests to ignore order check in spanish
  utils/admin_console_index.test.jsx
Labels: 2: Dev Review, CherryPick/Approved

#5696 Automated cherry pick of #5695
  utils/admin_console_index.test.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5688 translations PR 20200608
  i18n/de.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 4: Reviews Complete

#5679 Add .npmrc file to enforce save-exact
  .npmrc
Labels: 4: Reviews Complete

#5673 [MM-24968] Fixed add channel dropdown on mobile to pop out correctly
  sass/responsive/_mobile.scss
Labels: 4: Reviews Complete, QA Review Done

#5698 Removes server references from Bleve system console section
  components/admin_console/__snapshots__/bleve_settings.test.jsx.snap
  components/admin_console/bleve_settings.jsx
  i18n/en.json
Labels: AutoMerge, CherryPick/Approved, QA Review Done

#5704 Automated cherry pick of #5698
  components/admin_console/__snapshots__/bleve_settings.test.jsx.snap
  components/admin_console/bleve_settings.jsx
  i18n/en.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5439 Do not allow to navigate to deleted teams
  actions/global_actions.jsx
  components/needs_team/needs_team.test.tsx
  components/needs_team/needs_team.tsx
Labels: 4: Reviews Complete

#5701 [MM-25771] Ensure users displayed in add users to team modal are not inactive
  components/add_users_to_team_modal/index.ts
Labels: 4: Reviews Complete, CherryPick/Approved

#5708 Automated cherry pick of #5701
  components/add_users_to_team_modal/index.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5399 MM-24351 Update react virt list to be based on new library
  components/post_view/post_list_virtualized/post_list_virtualized.jsx
  package-lock.json
  package.json
Labels: 4: Reviews Complete

#5702 MM-25841 Retain search results even when quick switcher is out of focus
  components/__snapshots__/textbox.test.tsx.snap
  components/add_user_to_channel_modal/__snapshots__/add_user_to_channel_modal.test.jsx.snap
  components/autocomplete_selector.test.jsx
  components/quick_switch_modal/__snapshots__/quick_switch_modal.test.jsx.snap
  components/quick_switch_modal/quick_switch_modal.jsx
  components/search_bar/__snapshots__/search_bar.test.jsx.snap
  components/suggestion/suggestion_box.jsx
  components/suggestion/suggestion_box.test.jsx
Labels: 4: Reviews Complete

#5705 Updated few cypress tests based on failures
  e2e/cypress/integration/accessibility/accessibility_modals_dialogs_spec.js
  e2e/cypress/integration/enterprise/ldap/ldap_login_spec.js
  e2e/cypress/integration/enterprise/ldap_group/groups_assign_roles_spec.js
  e2e/cypress/integration/enterprise/system_console/channel_moderation_spec.js
Labels: 4: Reviews Complete

#5602 Update en.json (delete channel question)
  i18n/en.json
Labels: 4: Reviews Complete

#5565 MM-18788 Remove deprecated lifecycle methods from file previews
  components/code_preview.jsx
  components/pdf_preview.jsx
  components/pdf_preview.test.jsx
  components/view_image/view_image.jsx
Labels: 4: Reviews Complete

#5603 Update delete_channel_modal.tsx
  components/delete_channel_modal/__snapshots__/delete_channel_modal.test.tsx.snap
  components/delete_channel_modal/delete_channel_modal.tsx
Labels: 4: Reviews Complete

#5716 Promoting consistently passing unstable tests to prod stage
  e2e/cypress/integration/accessibility/accessibility_account_settings_spec.js
  e2e/cypress/integration/account_settings/general/nickname_spec.js
  e2e/cypress/integration/account_settings/sidebar/channel_switcher_spec.js
  e2e/cypress/integration/channel/channel_groups_spec.js
  e2e/cypress/integration/channel_sidebar/history_channel_switcher_spec.js
  e2e/cypress/integration/integrations/builtin_commands/common_commands_spec.js
  e2e/cypress/integration/integrations/builtin_commands/user_status_commands_spec.js
  e2e/cypress/integration/menus/main_menu_spec.js
  e2e/cypress/integration/menus/status_dropdown_spec.js
  e2e/cypress/integration/messaging/message_draft_then_switch_channel_spec.js
  e2e/cypress/integration/messaging/system_message_limited_options_spec.js
Labels: 4: Reviews Complete

#5717 E2E: Fix strikethrough spec
  e2e/cypress/integration/messaging/strikethrough_spec.js
Labels: 4: Reviews Complete

#5718 E2E: Fix main menu spec
  e2e/cypress/integration/menus/main_menu_spec.js
Labels: 4: Reviews Complete

#5719 E2E: Fix status dropdown spec
  e2e/cypress/integration/menus/status_dropdown_spec.js
Labels: 4: Reviews Complete

#5714 [MM25816] invitation_modal: revert to existing behavior for inviting existing ones
  components/invitation_modal/invitation_modal_members_step.jsx
  components/invitation_modal/invitation_modal_members_step.test.jsx
Labels: 4: Reviews Complete

#5710 [MM-25952] Fix license banner hiding revoke sessions
  sass/routes/_admin-console.scss
Labels: 4: Reviews Complete

#5722 [MM23361] Focus remains in the RHS text box
  e2e/cypress/integration/messaging/message_spec.js
Labels: 4: Reviews Complete

#5727 MM-26065: Revert pr 5654.
  root.html
Labels: 2: Dev Review

#5430 [MM-24763] Add onModalDismissed prop to file preview override component's props
  components/view_image/__snapshots__/view_image.test.jsx.snap
  components/view_image/view_image.jsx
Labels: 4: Reviews Complete

#5699 [MM-25947] Removed font-weight: 300 for muted channels
  sass/layout/_sidebar-left.scss
Labels: 4: Reviews Complete

#5706 MM-25889 - Restored announcement type for email verification
  components/do_verify_email/do_verify_email.tsx
Labels: 4: Reviews Complete

#5734 MM-26065: Reverts Brotli support.
  package-lock.json
  package.json
  webpack.config.js
Labels: 2: Dev Review, CherryPick/Approved

#5725 MM-26071 Cypress/E2E: Upgrade Cypress to 4.8.0 and other dependencies to latest
  e2e/cypress/integration/accessibility/accessibility_account_settings_spec.js
  e2e/cypress/integration/accessibility/accessibility_image_spec.js
  e2e/cypress/integration/emoji/sorted_emojis_spec.js
  e2e/cypress/integration/enterprise/elasticsearch_autocomplete/channels_spec.js
  e2e/cypress/integration/interactive_menu/basic_options_spec.js
  e2e/cypress/integration/messaging/file_upload_in_center_channel_spec.js
  e2e/cypress/integration/messaging/image_attachment_spec.js
  e2e/cypress/integration/messaging/long_post_attachments_spec.js
  e2e/cypress/integration/messaging/mention_autocomplete_overlap_spec.js
  e2e/cypress/integration/messaging/message_draft_with_attachment_then_switch_channel_spec.js
  e2e/cypress/integration/messaging/message_edit_post_with_attachment_spec.js
  e2e/cypress/integration/messaging/message_reply_bot_post_spec.js
  e2e/cypress/integration/messaging/message_reply_spec.js
  e2e/cypress/integration/messaging/receive_message_on_socket_reconnect_spec.js
  e2e/cypress/integration/search/results_post_spec.js
  e2e/cypress/integration/search_autocomplete/channels_spec.js
  e2e/cypress/integration/search_date_filter/date_filter_spec.js
  e2e/cypress/integration/search_date_filter/negative_filter_spec.js
  e2e/cypress/integration/system_console/plugin_upload_spec.js
  e2e/cypress/integration/system_console/ui_and_api/customization_spec.js
  e2e/cypress/integration/team_settings/remove_team_icon_spec.js
  e2e/cypress/support/storybook_commands.js
  e2e/cypress/support/ui_commands.js
  e2e/package-lock.json
  e2e/package.json
Labels: 4: Reviews Complete

#5712 MM-25904 - Updating link tooltips z-index for plugins
  components/link_tooltip/__snapshots__/link_tooltip.test.tsx.snap
  components/link_tooltip/link_tooltip.tsx
Labels: 4: Reviews Complete, AutomatedCherryPick, CherryPick/Approved, QA Review Done

#5634 [MM-25263] Add view group members modal
  actions/views/search.js
  components/add_users_to_team_modal/__snapshots__/add_users_to_team_modal.test.tsx.snap
  components/add_users_to_team_modal/add_users_to_team_modal.test.tsx
  components/admin_console/data_grid/data_grid.scss
  components/admin_console/data_grid/data_grid.tsx
  components/admin_console/data_grid/data_grid_search.tsx
  components/admin_console/group_settings/group_details/__snapshots__/group_users.test.jsx.snap
  components/admin_console/group_settings/group_details/group_details.jsx
  components/admin_console/group_settings/group_details/group_details.test.jsx
  components/admin_console/group_settings/group_details/group_users.jsx
  components/admin_console/group_settings/group_details/group_users.test.jsx
  components/admin_console/group_settings/group_details/index.jsx
  components/admin_console/member_list_group/__snapshots__/member_list_group.test.tsx.snap
  components/admin_console/member_list_group/index.ts
  components/admin_console/member_list_group/member_list_group.scss
  components/admin_console/member_list_group/member_list_group.test.tsx
  components/admin_console/member_list_group/member_list_group.tsx
  components/admin_console/reset_password_modal/reset_password_modal.test.tsx
  components/admin_console/team_channel_settings/channel/details/channel_members/__snapshots__/channel_members.test.tsx.snap
  components/admin_console/team_channel_settings/channel/details/channel_members/channel_members.test.tsx
  components/admin_console/team_channel_settings/channel/details/channel_members/channel_members.tsx
  components/admin_console/team_channel_settings/channel/details/channel_members/index.ts
  components/admin_console/team_channel_settings/group/__snapshots__/group_members_modal.test.tsx.snap
  components/admin_console/team_channel_settings/group/__snapshots__/group_row.test.tsx.snap
  components/admin_console/team_channel_settings/group/group_members_modal.test.tsx
  components/admin_console/team_channel_settings/group/group_members_modal.tsx
  components/admin_console/team_channel_settings/group/group_row.tsx
  components/admin_console/team_channel_settings/team/details/team_members/__snapshots__/team_members.test.tsx.snap
  components/admin_console/team_channel_settings/team/details/team_members/index.ts
  components/admin_console/team_channel_settings/team/details/team_members/team_members.test.tsx
  components/admin_console/team_channel_settings/team/details/team_members/team_members.tsx
  components/admin_console/user_grid/__snapshots__/user_grid.test.tsx.snap
  components/admin_console/user_grid/user_grid.test.tsx
  components/rhs_thread/rhs_thread.test.tsx
  components/sidebar/sidebar_channel/sidebar_direct_channel/__snapshots__/sidebar_direct_channel.test.tsx.snap
  components/sidebar/sidebar_channel/sidebar_direct_channel/sidebar_direct_channel.test.tsx
  i18n/en.json
  package-lock.json
  package.json
  utils/constants.jsx
  utils/test_helper.ts
Labels: Setup Cloud Test Server

#5724 MM-26008 Fix for suggestions not appearing when opening quick switcher
  components/suggestion/suggestion_box.jsx
  components/suggestion/suggestion_box.test.jsx
Labels: 4: Reviews Complete

#5750 MM-25889 - Restored announcement type for email verification (#5706)
  components/do_verify_email/do_verify_email.tsx
Labels: 2: Dev Review, AutoMerge

#5751 Automated cherry pick of #5712
  components/link_tooltip/__snapshots__/link_tooltip.test.tsx.snap
  components/link_tooltip/link_tooltip.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5744 Fix LinkTooltip with uncommon link format
  components/link_tooltip/__snapshots__/link_tooltip.test.tsx.snap
  components/link_tooltip/link_tooltip.test.tsx
  components/link_tooltip/link_tooltip.tsx
  utils/__snapshots__/message_html_to_component.test.jsx.snap
  utils/message_html_to_component.jsx
Labels: 4: Reviews Complete, CherryPick/Approved

#5697 MM-25933: Do not exclude default channels from channel search on grou…
  components/channel_selector_modal/channel_selector_modal.jsx
  e2e/cypress/integration/system_console/group_configuration_spec.js
Labels: 4: Reviews Complete, CherryPick/Approved

#5756 Automated cherry pick of #5697
  components/channel_selector_modal/channel_selector_modal.jsx
  e2e/cypress/integration/system_console/group_configuration_spec.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5690 [MM-25805] Fix mobile web view hashtags and channel links not working
  components/channel_header_mobile/channel_header_mobile.js
  components/channel_header_mobile/channel_info_button/__snapshots__/channel_info_button.test.js.snap
  components/channel_header_mobile/channel_info_button/channel_info_button.js
  components/channel_header_mobile/channel_info_button/channel_info_button.test.js
  components/channel_header_mobile/index.js
  components/channel_info_modal/__snapshots__/channel_info_modal.test.jsx.snap
  components/channel_info_modal/channel_info_modal.jsx
  components/channel_info_modal/channel_info_modal.test.jsx
  components/channel_info_modal/index.js
Labels: 4: Reviews Complete, CherryPick/Approved

#5745 MM-26035 Migrate to new cy.apiInitSetup and fix permalink issues when expecting from clipboard
  components/link_tooltip/__snapshots__/link_tooltip.test.tsx.snap
  e2e/cypress/integration/accessibility/accessibility_dropdowns_spec.js
  e2e/cypress/integration/accessibility/accessibility_modals_dialogs_spec.js
  e2e/cypress/integration/messaging/channel_read_after_permalink_spec.js
  e2e/cypress/integration/messaging/message_permalink_spec.js
  e2e/cypress/integration/messaging/permalink_loading_indicator_spec.js
  e2e/cypress/integration/messaging/permalink_message_edit_spec.js
  e2e/cypress/integration/search_date_filter/date_filter_spec.js
  e2e/cypress/integration/search_date_filter/negative_filter_spec.js
  e2e/cypress/integration/toast/toast_spec.js
  e2e/cypress/plugins/index.js
  e2e/cypress/support/index.js
  e2e/cypress/support/ui/index.js
  e2e/cypress/support/ui/post_dropdown_menu.d.ts
  e2e/cypress/support/ui/post_dropdown_menu.js
  e2e/cypress/support/ui_commands.js
  e2e/cypress/utils/index.js
  e2e/package-lock.json
  e2e/package.json
  package-lock.json
Labels: 4: Reviews Complete, AutoMerge

#5737 MM-26035 Remove "cy.apiCreateNewUser" in favor new "cy.apiInitSetup"
  e2e/cypress/integration/enterprise/elasticsearch_autocomplete/channels_spec.js
  e2e/cypress/integration/enterprise/elasticsearch_autocomplete/helpers/index.js
  e2e/cypress/integration/enterprise/elasticsearch_autocomplete/renaming_spec.js
  e2e/cypress/integration/enterprise/elasticsearch_autocomplete/users_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/guest_invitation_ui_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/member_invitation_ui_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/system_console_guest_access_ui_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/system_console_manage_guest_spec.js
  e2e/cypress/integration/messaging/header_spec.js
  e2e/cypress/integration/messaging/remove_last_post_in_channel_spec.js
  e2e/cypress/integration/messaging/send_message_via_profile_popover_spec.js
  e2e/cypress/integration/messaging/tooltip_visual_verification_spec.js
  e2e/cypress/integration/search_autocomplete/renaming_spec.js
  e2e/cypress/integration/search_autocomplete/users_spec.js
  e2e/cypress/integration/search_date_filter/date_filter_spec.js
  e2e/cypress/integration/search_filter/after_spec.js
  e2e/cypress/integration/search_filter/before_spec.js
  e2e/cypress/integration/search_filter/edit_spec.js
  e2e/cypress/integration/search_filter/helpers.js
  e2e/cypress/integration/search_filter/input_spec.js
  e2e/cypress/integration/search_filter/invalid_spec.js
  e2e/cypress/integration/search_filter/mixed_spec.js
  e2e/cypress/integration/search_filter/negative_spec.js
  e2e/cypress/integration/search_filter/on_spec.js
  e2e/cypress/support/api/setup.d.ts
  e2e/cypress/support/api/setup.js
  e2e/cypress/support/api/user.d.ts
  e2e/cypress/support/api/user.js
  e2e/cypress/support/index.js
  e2e/cypress/support/task_commands.js
Labels: 4: Reviews Complete

#5738 MM-26035 Migrate use of "user-1", update "cy.apiCreateGuestUser" and remove split spec
  e2e/cypress/integration/enterprise/system_console/channel_moderation/channel_mentions_spec.js
  e2e/cypress/integration/enterprise/system_console/channel_moderation/create_posts_spec.js
  e2e/cypress/integration/enterprise/system_console/channel_moderation/higher_scoped_scheme_spec.js
  e2e/cypress/integration/enterprise/system_console/channel_moderation/manage_members_spec.js
  e2e/cypress/integration/enterprise/system_console/channel_moderation/post_reactions_spec.js
  e2e/cypress/integration/enterprise/system_console/channel_moderation/system_config_spec.js
  e2e/cypress/integration/enterprise/system_console/channel_moderation_spec.js
  e2e/cypress/integration/menus/main_menu_spec.js
  e2e/cypress/integration/messaging/at_mentions_spec.js
  e2e/cypress/integration/messaging/at_mentions_user_spec.js
  e2e/cypress/integration/messaging/autocomplete_shown_each_channel_spec.js
  e2e/cypress/integration/messaging/center_channel_rhs_overlap_spec.js
  e2e/cypress/integration/messaging/message_deletion_spec.js
  e2e/cypress/integration/messaging/message_reply_input_box_expand_spec.js
  e2e/cypress/integration/messaging/message_reply_too_long_spec.js
  e2e/cypress/integration/messaging/mobile_message_deletion_spec.js
  e2e/cypress/integration/messaging/mobile_profile_popover_spec.js
  e2e/cypress/integration/messaging/post_header_spec.js
  e2e/cypress/integration/messaging/post_options_menu_spec.js
  e2e/cypress/integration/messaging/post_textbox_height_spec.js
  e2e/cypress/integration/websocket/handle_removed_user_spec.js
  e2e/cypress/support/api/user.d.ts
  e2e/cypress/support/api/user.js
  e2e/cypress/support/ui_commands.js
Labels: 4: Reviews Complete

#5632 MM-23573: Remove Segment.
  components/root/root.jsx
  package-lock.json
  utils/constants.jsx
Labels: 4: Reviews Complete

#5506 MM-25126 Add default sorting method
  components/sidebar/sidebar_category/__snapshots__/sidebar_category.test.tsx.snap
  components/sidebar/sidebar_category/sidebar_category.test.tsx
Labels: 2: Dev Review

#5733 MM-25138: CircleCI caching improvements
  .circleci/config.yml
Labels: 4: Reviews Complete

#5764 Automated cherry pick of #5492
  sass/routes/_settings.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5761 Manual cherrypick of #5744 - Fix LinkTooltip with uncommon link format
  components/link_tooltip/__snapshots__/link_tooltip.test.tsx.snap
  components/link_tooltip/link_tooltip.test.tsx
  components/link_tooltip/link_tooltip.tsx
  utils/__snapshots__/message_html_to_component.test.jsx.snap
  utils/message_html_to_component.jsx
Labels: 4: Reviews Complete

#5762 Manual cherrypick of #5744 - Fix LinkTooltip with uncommon link format
  components/link_tooltip/__snapshots__/link_tooltip.test.tsx.snap
  components/link_tooltip/link_tooltip.test.tsx
  components/link_tooltip/link_tooltip.tsx
  utils/__snapshots__/message_html_to_component.test.jsx.snap
  utils/message_html_to_component.jsx
Labels: 4: Reviews Complete

#5760 Manual cherrypick of #5744 - Fix LinkTooltip with uncommon link format
  components/link_tooltip/__snapshots__/link_tooltip.test.tsx.snap
  components/link_tooltip/link_tooltip.test.tsx
  components/link_tooltip/link_tooltip.tsx
  utils/__snapshots__/message_html_to_component.test.jsx.snap
  utils/message_html_to_component.jsx
Labels: 4: Reviews Complete

#5772 Automated cherry pick of #5659
  components/admin_console/team_channel_settings/team/details/__snapshots__/team_profile.test.jsx.snap
  components/admin_console/team_channel_settings/team/details/team_profile.jsx
  sass/routes/_admin-console.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5767 MM-25951: Fix license id in link
  components/announcement_bar/configuration_bar/__snapshots__/configuration_bar.test.jsx.snap
  components/announcement_bar/configuration_bar/configuration_bar.jsx
  components/announcement_bar/configuration_bar/configuration_bar.test.jsx
Labels: 4: Reviews Complete, CherryPick/Approved

#5683 MM-24467 Add SAML ServiceProviderIdentifier
  components/admin_console/admin_definition.jsx
  e2e/cypress/integration/enterprise/saml/okta_login_spec.js
  e2e/cypress/integration/enterprise/saml/saml_metadata_spec.js
  i18n/en.json
Labels: 4: Reviews Complete, CherryPick/Approved

#5773 Automated cherry pick of #5767
  components/announcement_bar/configuration_bar/__snapshots__/configuration_bar.test.jsx.snap
  components/announcement_bar/configuration_bar/configuration_bar.jsx
  components/announcement_bar/configuration_bar/configuration_bar.test.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5774 Cypress/E2E: Fix failing tests due to read-only config after HA cluster is enabled
  e2e/cypress/fixtures/partial_default_config.json
Labels: 4: Reviews Complete

#5713 MM-22788 - Updating suggestion list max height
  components/suggestion/suggestion_list.jsx
  utils/constants.jsx
Labels: 4: Reviews Complete

#5743 Update dependencies
  components/create_team/__snapshots__/create_team.test.tsx.snap
  components/create_team/create_team.jsx
  components/create_team/create_team.test.tsx
  components/create_team/index.js
  components/linking_landing_page/linking_landing_page.tsx
  components/multiselect/multiselect.tsx
  components/suggestion/provider.jsx
  components/widgets/admin_console/admin_panel_with_link.test.tsx
  package-lock.json
  package.json
  patches/@types+marked+0.6.5.patch
  selectors/views/channel_sidebar.test.ts
  tests/setup.js
  utils/syntax_highlighting.tsx
  utils/text_formatting.tsx
  webpack.config.js
Labels: 4: Reviews Complete

#5752 MM-26063 Fix for center channel auto scroll to bottom
  package-lock.json
  package.json
Labels: 4: Reviews Complete

#5747 [MM-25804] fix removing dm from localstorage
  actions/views/channel.js
  components/sidebar/sidebar_channel/sidebar_direct_channel/index.ts
  components/sidebar/sidebar_channel/sidebar_direct_channel/sidebar_direct_channel.test.tsx
  components/sidebar/sidebar_channel/sidebar_direct_channel/sidebar_direct_channel.tsx
  stores/local_storage_store.jsx
  stores/local_storage_store.test.jsx
Labels: 4: Reviews Complete

#5771 MM-24791: Fix invisible border in interactive dialog's dropdown
  sass/components/_select.scss
Labels: 4: Reviews Complete, CherryPick/Approved

#5781 Automated cherry pick of #5771
  sass/components/_select.scss
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5778 [MM-26426] - Fix translations broken by the webpack require call
  i18n/i18n.jsx
Labels: 4: Reviews Complete

#5783 MM-23788 Setup for visual regression testing
  e2e/applitools.config.js
  e2e/cypress.json
  e2e/cypress/integration/visual_regression/helpers.js
  e2e/cypress/integration/visual_regression/system_console/about_section_spec.js
  e2e/cypress/integration/visual_regression/system_console/authentication_section_spec.js
  e2e/cypress/integration/visual_regression/system_console/compliance_section_spec.js
  e2e/cypress/integration/visual_regression/system_console/environment_section_spec.js
  e2e/cypress/plugins/index.js
  e2e/cypress/support/index.js
  e2e/cypress/support/visual_commands.d.ts
  e2e/cypress/support/visual_commands.js
  e2e/cypress/tsconfig.json
  e2e/package-lock.json
  e2e/package.json
  e2e/run_tests.js
Labels: 4: Reviews Complete

#5777 [MM-25818] - Fix styling for archived icons
  components/channel_info_modal/__snapshots__/channel_info_modal.test.jsx.snap
  components/channel_info_modal/channel_info_modal.jsx
Labels: 4: Reviews Complete, CherryPick/Approved, QA Review Done

#5753 [MM-26305] migrate refs example
  components/admin_console/password_settings.jsx
Labels: 4: Reviews Complete

#5788 Automated cherry pick of #5777
  components/channel_info_modal/__snapshots__/channel_info_modal.test.jsx.snap
  components/channel_info_modal/channel_info_modal.jsx
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5780 [MM-26407] Remove beta flag from ldap groups
  components/admin_console/admin_definition.jsx
  components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.jsx.snap
  components/admin_console/group_settings/__snapshots__/group_settings.test.jsx.snap
  components/admin_console/group_settings/group_settings.jsx
  e2e/cypress/integration/enterprise/system_console/sidebar_link_navigation_spec.js
  i18n/en.json
Labels: 4: Reviews Complete, CherryPick/Approved

#5792 Automated cherry pick of #5780
  components/admin_console/admin_definition.jsx
  components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.jsx.snap
  components/admin_console/group_settings/__snapshots__/group_settings.test.jsx.snap
  components/admin_console/group_settings/group_settings.jsx
  e2e/cypress/integration/enterprise/system_console/sidebar_link_navigation_spec.js
  i18n/en.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5786 E2E: Fix accessibility dropdowns
  e2e/cypress/integration/accessibility/accessibility_dropdowns_spec.js
Labels: 4: Reviews Complete

#5793 Fix failing tests on handle removed user
  e2e/cypress/integration/websocket/handle_removed_user/helpers.js
Labels: 4: Reviews Complete

#5755 MM-25640 - Leaving archived channel does not return user to the last viewed channel
  actions/views/channel.js
  actions/views/channel.test.js
Labels: 4: Reviews Complete

#5746 MM-16457: Increase width of the system console logs
  components/admin_console/server_logs/logs.jsx
  sass/routes/_admin-console.scss
Labels: 4: Reviews Complete

#5790 E2E/Cypress: Fix remnants of old timeouts
  e2e/cypress/integration/messaging/edit_message_spec.js
  e2e/cypress/integration/messaging/message_permalink_spec.js
  e2e/cypress/integration/search_filter/helpers.js
  e2e/cypress/integration/toast/toast_spec.js
Labels: 4: Reviews Complete

#5789 Unset width for invitation modal button
  components/invitation_modal/invitation_modal_members_step.scss
Labels: 4: Reviews Complete, CherryPick/Approved

#5799 Automated cherry pick of #5789
  components/invitation_modal/invitation_modal_members_step.scss
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5571 [MM-24760] Fix post card icon CSS
  components/post_view/post_info/post_info.jsx
  components/rhs_comment/rhs_comment.jsx
  components/rhs_root_post/rhs_root_post.jsx
  components/search_results_item/search_results_item.jsx
Labels: 4: Reviews Complete, CherryPick/Approved

#5784 MM-26388 - Update error handling from server
  components/admin_console/group_settings/group_details/group_details.jsx
  i18n/en.json
Labels: 4: Reviews Complete, CherryPick/Approved

#5802 Cherry pick of #5336
  components/legacy_sidebar/header/dropdown/sidebar_header_dropdown.jsx
  components/legacy_sidebar/header/sidebar_header_dropdown_button.jsx
  components/status_dropdown/status_dropdown.jsx
  i18n/en.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
  sass/layout/_headers.scss
Labels: Changelog/Not Needed, Docs/Not Needed

#5801 Automated cherry pick of #5571
  components/post_view/post_info/post_info.jsx
  components/rhs_comment/rhs_comment.jsx
  components/rhs_root_post/rhs_root_post.jsx
  components/search_results_item/search_results_item.jsx
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5800 Fix element check.
  plugins/registry.js
Labels: 4: Reviews Complete

#5803 Automated cherry pick of #5784
  components/admin_console/group_settings/group_details/group_details.jsx
  i18n/en.json
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5805 Consitering strings in resolve element.
  plugins/registry.js
Labels: 2: Dev Review

#5742 [MM-24861] Enabled plugins without any configs to be displayed in admin sidebar
  components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.jsx.snap
  components/admin_console/admin_sidebar/admin_sidebar.jsx
  components/admin_console/admin_sidebar/admin_sidebar.test.jsx
Labels: 4: Reviews Complete

#5731 MM-26066 Move rudder to use CDN instead of npm
  actions/hooks.test.js
  components/admin_console/system_users/system_users.test.jsx
  components/channel_layout/channel_identifier_router/channel_identifier_router.test.jsx
  components/create_post/create_post.test.jsx
  components/edit_post_modal/edit_post_modal.test.jsx
  components/emoji_picker/emoji_picker.test.jsx
  components/more_channels/more_channels.test.jsx
  components/post_view/post/post.test.js
  components/root/root.jsx
  components/suggestion/at_mention_provider/at_mention_provider.test.jsx
  package-lock.json
  package.json
Labels: 4: Reviews Complete

#5791 [MM-25903] fix avatar for dms in search
  components/suggestion/search_channel_suggestion/index.js
  components/suggestion/search_channel_suggestion/search_channel_suggestion.jsx
Labels: 4: Reviews Complete, CherryPick/Approved

#5782 [MM-25785] allow pasting tables into edit post, keep caret position
  components/create_comment/create_comment.jsx
  components/create_comment/create_comment.test.jsx
  components/create_post/create_post.jsx
  components/create_post/create_post.test.jsx
  components/edit_post_modal/edit_post_modal.jsx
  utils/paste.tsx
Labels: 4: Reviews Complete, CherryPick/Approved

#5807 Automated cherry pick of #5791
  components/suggestion/search_channel_suggestion/index.js
  components/suggestion/search_channel_suggestion/search_channel_suggestion.jsx
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5795 E2E: Fix invite members spec
  e2e/cypress/integration/team_settings/invite_members_spec.js
Labels: 4: Reviews Complete

#5808 Automated cherry pick of #5782
  components/create_comment/create_comment.jsx
  components/create_comment/create_comment.test.jsx
  components/create_post/create_post.jsx
  components/create_post/create_post.test.jsx
  components/edit_post_modal/edit_post_modal.jsx
  utils/paste.tsx
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5810 MM-26035 Cypress/E2E: Removed users.json
  e2e/cypress/fixtures/users.json
Labels: 4: Reviews Complete

#5709 MM-14774 Use default 'pointer' cursor for non-clickable menu items
  components/status_dropdown/__snapshots__/status_dropdown.test.tsx.snap
  components/status_dropdown/status_dropdown.jsx
  components/widgets/menu/menu_wrapper.scss
  i18n/en.json
Labels: 4: Reviews Complete

#5547 [MM-24917] Prefecthing of posts
  actions/global_actions.jsx
  actions/user_actions.jsx
  actions/views/channel.js
  actions/views/channel.test.js
  components/admin_console/admin_definition.jsx
  components/data_prefetch/data_prefetch.test.tsx
  components/data_prefetch/data_prefetch.tsx
  components/data_prefetch/index.ts
  components/legacy_sidebar/__snapshots__/sidebar.test.jsx.snap
  components/legacy_sidebar/index.js
  components/legacy_sidebar/sidebar.jsx
  components/legacy_sidebar/sidebar.test.jsx
  components/post_view/post_list/index.js
  components/post_view/post_list/post_list.jsx
  components/post_view/post_list/post_list.test.jsx
  components/sidebar/__snapshots__/sidebar.test.tsx.snap
  components/sidebar/index.ts
  components/sidebar/sidebar.test.tsx
  components/sidebar/sidebar.tsx
  i18n/en.json
  reducers/views/channel.js
  reducers/views/channel.test.js
  types/store/index.ts
  utils/constants.jsx
Labels: 2: Dev Review, QA Review Done

#5817 Update package.json and package-lock.json
  package-lock.json
  package.json
Labels: 4: Reviews Complete

#5797 MM-25143 Update react redux
  components/__snapshots__/profile_picture.test.tsx.snap
  components/admin_console/permission_schemes_settings/guest_permissions_tree/__snapshots__/guest_permissions_tree.test.jsx.snap
  components/admin_console/permission_schemes_settings/permissions_tree/__snapshots__/permissions_tree.test.jsx.snap
  components/admin_console/system_users/list/__snapshots__/system_users_list.test.jsx.snap
  components/admin_console/team_channel_settings/channel/details/__snapshots__/channel_groups.test.tsx.snap
  components/admin_console/team_channel_settings/channel/details/channel_members/__snapshots__/channel_members.test.tsx.snap
  components/admin_console/team_channel_settings/team/details/__snapshots__/team_groups.test.jsx.snap
  components/admin_console/team_channel_settings/team/details/team_members/__snapshots__/team_members.test.tsx.snap
  components/announcement_bar/__snapshots__/text_dismissable_bar.test.jsx.snap
  components/channel_header_dropdown/__snapshots__/channel_header_dropdown.test.jsx.snap
  components/channel_header_mobile/channel_header_mobile.js
  components/channel_header_mobile/channel_info_button/__snapshots__/channel_info_button.test.js.snap
  components/channel_notifications_modal/components/__snapshots__/collapse_view.test.jsx.snap
  components/create_comment/create_comment.jsx
  components/create_comment/create_comment.test.jsx
  components/create_comment/index.js
  components/create_post/create_post.jsx
  components/create_post/create_post.test.jsx
  components/edit_channel_header_modal/edit_channel_header_modal.jsx
  components/edit_post_modal/edit_post_modal.jsx
  components/file_upload/index.js
  components/legacy_sidebar/sidebar_channel/index.js
  components/main_menu/__snapshots__/main_menu.test.jsx.snap
  components/more_channels/__snapshots__/more_channels.test.jsx.snap
  components/overlay_trigger.tsx
  components/post_markdown/__snapshots__/post_markdown.test.jsx.snap
  components/post_view/message_attachments/message_attachment/__snapshots__/message_attachment.test.jsx.snap
  components/profile_popover/__snapshots__/profile_popover.test.jsx.snap
  components/rhs_card/__snapshots__/rhs_card.test.jsx.snap
  components/setting_item_min/index.ts
  components/setting_item_min/setting_item_min.tsx
  components/team_general_tab/__snapshots__/team_general_tab.test.jsx.snap
  components/textbox/index.ts
  components/toggle_modal_button.jsx
  components/user_profile/__snapshots__/user_profile.test.jsx.snap
  components/user_settings/advanced/join_leave_section/__snapshots__/join_leave_section.test.jsx.snap
  components/user_settings/display/__snapshots__/user_settings_display.test.jsx.snap
  components/user_settings/display/user_settings_theme/__snapshots__/user_settings_theme.test.jsx.snap
  components/user_settings/modal/user_settings_modal.tsx
  components/user_settings/notifications/__snapshots__/desktop_notification_settings.test.jsx.snap
  components/user_settings/notifications/email_notification_setting/__snapshots__/email_notification_setting.test.jsx.snap
  components/user_settings/security/mfa_section/__snapshots__/mfa_section.test.tsx.snap
  components/user_settings/sidebar/__snapshots__/user_settings_sidebar.test.tsx.snap
  components/user_settings/sidebar/user_settings_sidebar.test.tsx
  package-lock.json
  package.json
  plugins/test/__snapshots__/main_menu_action.test.jsx.snap
  utils/__snapshots__/message_html_to_component.test.jsx.snap
Labels: 4: Reviews Complete

#5814 MM-26069 Cypress test for MM-T622 which disallow override of username and profile picture
  e2e/cypress/integration/integrations/incoming/disallow_username_profile_override_spec.js
  e2e/cypress/support/index.js
  e2e/cypress/support/task_commands.js
  e2e/cypress/support/ui_commands.d.ts
  e2e/cypress/support/ui_commands.js
  e2e/cypress/utils/index.js
Labels: 4: Reviews Complete

#5820 Quick fix on failing unit tests
  components/create_comment/create_comment.test.jsx
  components/create_post/create_post.test.jsx
Labels: 4: Reviews Complete

#5707 [MM-25658] Replace Data Grid on Channel and Teams page in System console with Common Component
  components/admin_console/data_grid/__snapshots__/data_grid.test.tsx.snap
  components/admin_console/data_grid/data_grid.scss
  components/admin_console/data_grid/data_grid.test.tsx
  components/admin_console/data_grid/data_grid.tsx
  components/admin_console/data_grid/data_grid_row.tsx
  components/admin_console/data_grid/data_grid_search.tsx
  components/admin_console/member_list_group/__snapshots__/member_list_group.test.tsx.snap
  components/admin_console/member_list_group/member_list_group.tsx
  components/admin_console/team_channel_settings/channel/list/__snapshots__/channel_list.test.tsx.snap
  components/admin_console/team_channel_settings/channel/list/channel_list.scss
  components/admin_console/team_channel_settings/channel/list/channel_list.test.tsx
  components/admin_console/team_channel_settings/channel/list/channel_list.tsx
  components/admin_console/team_channel_settings/channel/list/index.ts
  components/admin_console/team_channel_settings/team/list/__snapshots__/team_list.test.jsx.snap
  components/admin_console/team_channel_settings/team/list/index.js
  components/admin_console/team_channel_settings/team/list/team_list.jsx
  components/admin_console/team_channel_settings/team/list/team_list.scss
  components/admin_console/user_grid/__snapshots__/user_grid.test.tsx.snap
  components/admin_console/user_grid/user_grid.tsx
  components/widgets/team_icon/team_icon.scss
  i18n/en.json
  sass/layout/_channel-icon.scss
Labels: 4: Reviews Complete

#5798 [MM-26532] Fix team members modal user count issues
  components/member_list_team/member_list_team.tsx
  components/searchable_user_list/searchable_user_list.jsx
Labels: 4: Reviews Complete, CherryPick/Approved

#5806 MM-26075 Cypress/E2E: Standardize apiCreateTeam, apiDeleteTeam, apiGetTeamByName and apiGetAllTeams
  e2e/cypress/integration/enterprise/elasticsearch_autocomplete/renaming_spec.js
  e2e/cypress/integration/enterprise/elasticsearch_autocomplete/users_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/guest_removal_ui_spec.js
  e2e/cypress/integration/enterprise/ldap/ldap_login_spec.js
  e2e/cypress/integration/enterprise/ldap_group/invite_bot_spec.js
  e2e/cypress/integration/enterprise/teams/search_teams_spec.js
  e2e/cypress/integration/integrations/message_to_channel_via_slash_command_spec.js
  e2e/cypress/integration/interactive_dialog/boolean_spec.js
  e2e/cypress/integration/interactive_dialog/full_dialog_spec.js
  e2e/cypress/integration/interactive_dialog/scrollable_spec.js
  e2e/cypress/integration/interactive_dialog/simple_dialog_spec.js
  e2e/cypress/integration/search_autocomplete/renaming_spec.js
  e2e/cypress/integration/search_autocomplete/users_spec.js
  e2e/cypress/support/api/setup.js
  e2e/cypress/support/api/team.d.ts
  e2e/cypress/support/api/team.js
  e2e/cypress/support/index.d.ts
Labels: 4: Reviews Complete

#5776 [MM-25957] Fixed up types in `admin_console`
  components/add_users_to_team_modal/add_users_to_team_modal.test.tsx
  components/admin_console/admin_console.test.tsx
  components/admin_console/admin_console.tsx
  components/admin_console/admin_settings.tsx
  components/admin_console/admin_sidebar_header/admin_sidebar_header.tsx
  components/admin_console/audits/audits.tsx
  components/admin_console/audits/index.ts
  components/admin_console/blockable_link/index.ts
  components/admin_console/group_settings/groups_list/__snapshots__/groups_list.test.tsx.snap
  components/admin_console/group_settings/groups_list/groups_list.test.tsx
  components/admin_console/group_settings/groups_list/groups_list.tsx
  components/admin_console/group_settings/groups_list/index.ts
  components/admin_console/manage_roles_modal/index.ts
  components/admin_console/manage_roles_modal/manage_roles_modal.tsx
  components/admin_console/reset_password_modal/reset_password_modal.test.tsx
  components/admin_console/reset_password_modal/reset_password_modal.tsx
  components/admin_console/system_users/system_users_dropdown/system_users_dropdown.test.tsx
  components/admin_console/system_users/system_users_dropdown/system_users_dropdown.tsx
  components/admin_console/team_channel_settings/channel/details/channel_details.tsx
  components/admin_console/team_channel_settings/channel/details/channel_moderation.tsx
  components/admin_console/team_channel_settings/channel/list/channel_list.test.tsx
  components/admin_console/team_channel_settings/channel/list/channel_list.tsx
  components/admin_console/team_channel_settings/group/group_users.tsx
  components/admin_console/user_grid/user_grid.test.tsx
  components/rhs_thread/rhs_thread.test.tsx
  components/sidebar/sidebar_channel/sidebar_direct_channel/sidebar_direct_channel.test.tsx
  types/utils.d.ts
  utils/test_helper.ts
Labels: 4: Reviews Complete

#5813 MM-26560 Add test environment details to reports
  e2e/run_tests.js
  e2e/save_report.js
  e2e/utils/constants.js
  e2e/utils/report.js
Labels: 4: Reviews Complete
