Repository mattermost/mattermost-webapp, pull requests merged in 2020-04, with the labels that each got.

#5235 translations PR 20200330
  i18n/de.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 3: Reviews Complete

#5220 [MM-23638] Prevent Safari from handling team number keyboard shortcuts
  components/legacy_team_sidebar/legacy_team_sidebar_controller.jsx
Labels: CherryPick/Approved, QA Review Done

#4803 Review and refine tooltips text
  components/channel_header/components/__snapshots__/header_icon_wrapper.test.js.snap
  components/channel_header/components/header_icon_wrapper.js
  components/create_post/__snapshots__/create_post.test.jsx.snap
  components/create_post/create_post.jsx
  components/legacy_sidebar/__snapshots__/sidebar.test.jsx.snap
  components/legacy_sidebar/channel_create.jsx
  components/legacy_sidebar/channel_more.jsx
  components/legacy_sidebar/channel_name.jsx
  components/legacy_sidebar/sidebar.jsx
  components/legacy_sidebar/sidebar_channel_button_or_link/__snapshots__/sidebar_channel_button_or_link_close_button.test.jsx.snap
  components/legacy_sidebar/sidebar_channel_button_or_link/sidebar_channel_button_or_link_close_button.jsx
  components/legacy_team_sidebar/components/team_button.jsx
  components/legacy_team_sidebar/legacy_team_sidebar_controller.jsx
  components/post_view/reaction_list/__snapshots__/reactions_list.test.jsx.snap
  components/post_view/reaction_list/reaction_list.jsx
  components/select_team/__snapshots__/select_team.test.jsx.snap
  components/select_team/select_team.jsx
  components/sidebar/sidebar_category_list/__snapshots__/sidebar_category_list.test.tsx.snap
  components/sidebar/sidebar_category_list/sidebar_category_list.tsx
  e2e/cypress/integration/onboarding/existing_email_adress_spec.js
  i18n/en.json
Labels: 3: Reviews Complete, QA Review Done

#5247 Automated cherry pick of #5220
  components/legacy_team_sidebar/legacy_team_sidebar_controller.jsx
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4984 MM-22963 - Updating post spacing and highlight
  sass/layout/_post-right.scss
  sass/layout/_post.scss
  sass/responsive/_tablet.scss
  utils/utils.jsx
Labels: 2: Dev Review, QA Review Done

#5103 [MM-20530] Migrate 'components/markdown' module and associated tests to TypeScript
  components/markdown/__snapshots__/markdown.test.tsx.snap
  components/markdown/index.ts
  components/markdown/markdown.jsx
  components/markdown/markdown.test.tsx
  components/markdown/markdown.tsx
  utils/text_formatting.tsx
Labels: 3: Reviews Complete, QA Review Done

#5230 MM-23660 - Updating emoji popup on desktop and mobile
  sass/components/_emojisprite.scss
  sass/components/_emoticons.scss
  sass/responsive/_mobile.scss
Labels: 2: Dev Review, AutomatedCherryPick, CherryPick/Approved, QA Review Done, Setup Cloud Test Server

#5254 Automated cherry pick of #5230
  sass/components/_emojisprite.scss
  sass/components/_emoticons.scss
  sass/responsive/_mobile.scss
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5250 Added step to activate guest user if Guest Access was disabled in any of previous tests
  e2e/cypress/integration/enterprise/system_console/channel_moderation_spec.js
  e2e/cypress/support/api_commands.js
Labels: 3: Reviews Complete, QA Review Done

#5246 MM-23767 Add webhook integration between Cypress test and server analytics validation
  e2e/run_tests.js
Labels: 3: Reviews Complete, QA Review Done

#5242 [MM-23715] Modify all calls to imageURLForUser to pass a user id and default last_picture_update to 0
  components/integrations/bots/add_bot/add_bot.jsx
  components/integrations/bots/bot.jsx
  components/integrations/bots/bot.test.jsx
  components/integrations/bots/bots.jsx
  components/integrations/bots/bots.test.jsx
  components/integrations/bots/index.js
  components/invitation_modal/invitation_modal_confirm_step_row.jsx
  components/post_profile_picture/post_profile_picture.jsx
  components/post_view/channel_intro_message/channel_intro_message.jsx
  components/suggestion/at_mention_provider/at_mention_suggestion.jsx
  components/suggestion/search_user_provider.jsx
  components/suggestion/switch_channel_provider.jsx
  components/user_profile/user_profile.jsx
  components/user_settings/general/user_settings_general.jsx
  components/widgets/inputs/users_emails_input.jsx
  utils/utils.jsx
  utils/utils.test.jsx
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#5255 Automated cherry pick of #5242
  components/integrations/bots/add_bot/add_bot.jsx
  components/integrations/bots/bot.jsx
  components/integrations/bots/bot.test.jsx
  components/integrations/bots/bots.jsx
  components/integrations/bots/bots.test.jsx
  components/integrations/bots/index.js
  components/invitation_modal/invitation_modal_confirm_step_row.jsx
  components/post_profile_picture/post_profile_picture.jsx
  components/post_view/channel_intro_message/channel_intro_message.jsx
  components/suggestion/at_mention_provider/at_mention_suggestion.jsx
  components/suggestion/search_user_provider.jsx
  components/suggestion/switch_channel_provider.jsx
  components/user_profile/user_profile.jsx
  components/user_settings/general/user_settings_general.jsx
  components/widgets/inputs/users_emails_input.jsx
  utils/utils.jsx
  utils/utils.test.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5248 update text
  components/admin_console/team_channel_settings/errors.jsx
  i18n/en.json
Labels: QA Review Done

#5257 Fixed few failures related to toast_spec & System Scheme
  e2e/cypress.json
  e2e/cypress/integration/messaging/create_post_permission_spec.js
  e2e/cypress/integration/toast/toast_spec.js
Labels: QA Review Done

#5249 Updated Accessibility tests based on the latest label changes on the App
  e2e/cypress/integration/accessibility/accessibility_modals_dialogs_spec.js
  e2e/cypress/integration/accessibility/accessibility_post_spec.js
  e2e/cypress/integration/accessibility/accessibility_sidebar_spec.js
Labels: QA Review Done

#5260 [MM-23808] Fixed the experimental sidebar header to use the correct themeing, also fixed the border.
  sass/layout/_sidebar-left.scss
  utils/utils.jsx
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#5261 Automated cherry pick of #5260
  sass/layout/_sidebar-left.scss
  utils/utils.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5265 Reverting timeout in Cypress.json file.
  e2e/cypress.json
Labels: 3: Reviews Complete

#5266 [MM-23833] Fix missing labels in Marketplace modal
  components/plugin_marketplace/marketplace_list/marketplace_list.jsx
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#5267 Automated cherry pick of #5266
  components/plugin_marketplace/marketplace_list/marketplace_list.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5105 [MM-18953] Migrate 'components/change_url_modal' to TypeScript
  components/change_url_modal/__snapshots__/change_url_modal.test.tsx.snap
  components/change_url_modal/change_url_modal.test.tsx
  components/change_url_modal/change_url_modal.tsx
  components/change_url_modal/index.ts
Labels: 3: Reviews Complete, QA Review Done

#5270 [MM-23841] Allow confirm modal to update when state.checked is modified
  components/confirm_modal.test.tsx
  components/confirm_modal.tsx
Labels: 3: Reviews Complete, CherryPick/Approved, Docs/Not Needed, QA Review Done

#5274 Automated cherry pick of #5270
  components/confirm_modal.test.tsx
  components/confirm_modal.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5258 MM-23772/MM-23696 Fix channel header popover for existing channels
  components/channel_header/__snapshots__/channel_header.test.jsx.snap
  components/channel_header/channel_header.js
  sass/components/_popover.scss
  utils/markdown/index.ts
Labels: CherryPick/Approved, QA Review Done

#5277 Automated cherry pick of #5258
  components/channel_header/__snapshots__/channel_header.test.jsx.snap
  components/channel_header/channel_header.js
  sass/components/_popover.scss
  utils/markdown/index.ts
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5218 [MM-23626] Add 2 skipped E2E for Channel Moderation
  e2e/cypress/integration/enterprise/system_console/channel_moderation_spec.js
Labels: 3: Reviews Complete, QA Review Done

#5272 MM-21542 Test Automation: send Cypress test data to Test automation dashboard
  e2e/run_tests.js
Labels: 3: Reviews Complete, QA Review Done

#5275 Fixing javascript errors in the invitation process
  components/invitation_modal/__snapshots__/invitation_modal_initial_step.test.jsx.snap
  components/invitation_modal/invitation_modal.jsx
  components/invitation_modal/invitation_modal.test.jsx
  components/invitation_modal/invitation_modal_initial_step.jsx
  components/root_portal.jsx
  components/widgets/modals/full_screen_modal.tsx
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done, Tests/Not Needed

#5251 Remove unneeded duplicated requests for statuses
  actions/websocket_actions.jsx
  actions/websocket_actions.test.jsx
Labels: 3: Reviews Complete, QA Review Done

#5285 Automated cherry pick of #5275
  components/invitation_modal/__snapshots__/invitation_modal_initial_step.test.jsx.snap
  components/invitation_modal/invitation_modal.jsx
  components/invitation_modal/invitation_modal.test.jsx
  components/invitation_modal/invitation_modal_initial_step.jsx
  components/root_portal.jsx
  components/widgets/modals/full_screen_modal.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5283 E2E: Fix failing tests on permalink and post header
  e2e/cypress/integration/messaging/permalink_message_edit_spec.js
  e2e/cypress/integration/messaging/post_header_spec.js
  e2e/cypress/support/ui_commands.js
Labels: QA Review Done

#5278 [MM-23899] Revert "Remove extra line break in reaction overlay"
  components/post_view/reaction/__snapshots__/reaction.test.jsx.snap
  components/post_view/reaction/reaction.jsx
Labels: 3: Reviews Complete, CherryPick/Approved, Docs/Not Needed, QA Review Done

#5288 Automated cherry pick of #5278
  components/post_view/reaction/__snapshots__/reaction.test.jsx.snap
  components/post_view/reaction/reaction.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5259 [MM-23716] Re-add create_post write translations
  i18n/de.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: QA Review Done

#5279 translations PR 20200406
  i18n/de.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 3: Reviews Complete

#5264 Updating autocomplete popovers
  components/channel_header/channel_header.js
  components/channel_selector_modal/channel_selector_modal.jsx
  components/quick_switch_modal/__snapshots__/quick_switch_modal.test.jsx.snap
  components/quick_switch_modal/quick_switch_modal.jsx
  components/suggestion/__snapshots__/command_provider.test.js.snap
  components/suggestion/at_mention_provider/at_mention_suggestion.jsx
  components/suggestion/channel_mention_provider.jsx
  components/suggestion/command_provider.jsx
  components/suggestion/command_provider.test.js
  components/suggestion/search_channel_suggestion/search_channel_suggestion.jsx
  components/suggestion/search_user_provider.jsx
  components/suggestion/switch_channel_provider.jsx
  components/widgets/icons/globe_icon.jsx
  i18n/en.json
  sass/base/_mattermost-icons.scss
  sass/base/_typography.scss
  sass/components/_channel-switcher.scss
  sass/components/_forms.scss
  sass/components/_mentions.scss
  sass/components/_modal.scss
  sass/components/_module.scss
  sass/components/_popover.scss
  sass/components/_search.scss
  sass/components/_status-icon.scss
  sass/components/_suggestion-list.scss
  sass/layout/_headers.scss
  sass/layout/_legacy-sidebar-left.scss
  sass/responsive/_desktop.scss
  sass/responsive/_mobile.scss
  sass/responsive/_tablet.scss
  sass/styles.scss
  utils/utils.jsx
Labels: 2: Dev Review, QA Review Done

#5252 [MM-21405] Show warning first when Sync group members is turned on without members and then show error if save without groups added
  components/admin_console/team_channel_settings/channel/details/channel_details.tsx
  components/admin_console/team_channel_settings/errors.jsx
  i18n/en.json
Labels: 3: Reviews Complete, QA Review Done

#5286 Added E2E test to Verify Quick Navigation support across different regions in the app
  e2e/cypress/integration/accessibility/accessibility_nav_diff_regions_spec.js
Labels: QA Review Done

#5253 MM-23756 Always show unread DMs and GMs in new sidebar
  package-lock.json
  package.json
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done, Setup Cloud Test Server

#5224 [MM-23065] - Return to a DM/channel when you reload or go to root url
  actions/global_actions.jsx
  actions/global_actions.test.js
  actions/views/channel.js
  components/legacy_sidebar/sidebar_channel/index.js
  components/legacy_sidebar/sidebar_channel/sidebar_channel.jsx
  components/legacy_sidebar/sidebar_channel/sidebar_channel.test.jsx
Labels: QA Review Done

#5243 MM-15416: Change Group summary description text
  components/admin_console/group_settings/__snapshots__/group_settings.test.jsx.snap
  components/admin_console/group_settings/group_settings.jsx
  i18n/en.json
Labels: 1: UX Review, 3: Reviews Complete, QA Review Done

#5293 Fix handle removed user and misc timeouts imports
  e2e/cypress/integration/interactive_menu/slack_parsing_message_button_spec.js
  e2e/cypress/integration/mark_as_unread/mark_as_unread_spec.js
  e2e/cypress/integration/messaging/send_message_via_profile_popover_spec.js
  e2e/cypress/integration/search/clear_input_spec.js
  e2e/cypress/integration/search_date_filter/date_filter_spec.js
  e2e/cypress/integration/toast/toast_spec.js
  e2e/cypress/integration/websocket/handle_removed_user_spec.js
Labels: 3: Reviews Complete, QA Review Done

#5301 [MM-24035] Fix getDeactivatedChannel selector for DM channel
  components/channel_view/index.js
Labels: CherryPick/Approved, Docs/Not Needed, QA Review Done, Setup Cloud Test Server

#5305 Automated cherry pick of #5301
  components/channel_view/index.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5299 Fix emoji, guest accounts
  e2e/cypress/integration/emoji/react_to_last_message_shortcut_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/guest_invitation_ui_spec.js
Labels: QA Review Done

#5295 Fix messaging, plugins, team settings
  e2e/cypress/fixtures/long_text_post.txt
  e2e/cypress/integration/messaging/channel_read_after_permalink_spec.js
  e2e/cypress/integration/messaging/collapse_link_spec.js
  e2e/cypress/integration/messaging/collapsed_message_spec.js
  e2e/cypress/integration/messaging/emoji_picker_keyboard_usability_spec.js
  e2e/cypress/integration/messaging/focus_move_spec.js
  e2e/cypress/integration/messaging/header_spec.js
  e2e/cypress/integration/messaging/long_post_attachments_spec.js
  e2e/cypress/integration/messaging/message_permalink_spec.js
  e2e/cypress/integration/messaging/permalink_loading_indicator_spec.js
  e2e/cypress/integration/messaging/post_header_spec.js
  e2e/cypress/integration/messaging/remove_last_post_in_channel_spec.js
  e2e/cypress/integration/messaging/send_message_via_profile_popover_spec.js
  e2e/cypress/integration/messaging/system_message_limited_options_spec.js
  e2e/cypress/integration/messaging/tooltip_visual_verification_spec.js
  e2e/cypress/integration/plugins/marketplace/marketplace_spec.js
  e2e/cypress/integration/team_settings/invite_members_spec.js
Labels: 2: QA Review

#5307 Revert "MM-21707: enable backstage link for only bots (#4883)"
  components/backstage/backstage_controller.jsx
  components/backstage/components/backstage_sidebar.jsx
  components/backstage/components/backstage_sidebar.test.jsx
  components/backstage/index.js
  components/main_menu/__snapshots__/main_menu.test.jsx.snap
  components/main_menu/index.jsx
  components/main_menu/main_menu.jsx
  components/main_menu/main_menu.test.jsx
  plugins/test/__snapshots__/main_menu_action.test.jsx.snap
  plugins/test/main_menu_action.test.jsx
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#5296 [MM-23997] Ensure channel mentions permission is set on edit post
  components/edit_post_modal/__snapshots__/edit_post_modal.test.jsx.snap
  components/edit_post_modal/edit_post_modal.jsx
  components/edit_post_modal/edit_post_modal.test.jsx
  components/edit_post_modal/index.js
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#5291 [MM-24016] - Fix channel header when there is an announcement bar in …
  actions/views/announcement_bar.js
  components/announcement_bar/__snapshots__/text_dismissable_bar.test.jsx.snap
  components/announcement_bar/announcement_bar.test.jsx
  components/announcement_bar/announcement_bar_controller.jsx
  components/announcement_bar/configuration_bar/configuration_bar.jsx
  components/announcement_bar/default_announcement_bar/announcement_bar.jsx
  components/announcement_bar/default_announcement_bar/index.js
  components/announcement_bar/text_dismissable_bar.jsx
  components/announcement_bar/version_bar/__snapshots__/version_bar.test.jsx.snap
  components/announcement_bar/version_bar/version_bar.jsx
  components/announcement_bar/version_bar/version_bar.test.jsx
  components/channel_header/__snapshots__/channel_header.test.jsx.snap
  components/channel_header/channel_header.js
  components/channel_header/index.js
  reducers/views/announcement_bar.js
  reducers/views/index.js
  selectors/views/announcement_bar.js
  utils/constants.jsx
Labels: 2: Dev Review, CherryPick/Approved, QA Review Done, Setup Cloud Test Server

#5308 Automated cherry pick of #5291
  actions/views/announcement_bar.js
  components/announcement_bar/__snapshots__/text_dismissable_bar.test.jsx.snap
  components/announcement_bar/announcement_bar.test.jsx
  components/announcement_bar/announcement_bar_controller.jsx
  components/announcement_bar/configuration_bar/configuration_bar.jsx
  components/announcement_bar/default_announcement_bar/announcement_bar.jsx
  components/announcement_bar/default_announcement_bar/index.js
  components/announcement_bar/text_dismissable_bar.jsx
  components/announcement_bar/version_bar/__snapshots__/version_bar.test.jsx.snap
  components/announcement_bar/version_bar/version_bar.jsx
  components/announcement_bar/version_bar/version_bar.test.jsx
  components/channel_header/__snapshots__/channel_header.test.jsx.snap
  components/channel_header/channel_header.js
  components/channel_header/index.js
  reducers/views/announcement_bar.js
  reducers/views/index.js
  selectors/views/announcement_bar.js
  utils/constants.jsx
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5268 MM-23849: Removes unsupported example.
  components/admin_console/admin_definition.jsx
  i18n/en.json
Labels: 3: Reviews Complete, QA Review Done

#5297 [MM-23977] Ensure users not in team when searching for users
  components/invitation_modal/__snapshots__/invitation_modal.test.jsx.snap
  components/invitation_modal/invitation_modal.jsx
  components/invitation_modal/invitation_modal_members_step.jsx
  components/invitation_modal/invitation_modal_members_step.test.jsx
Labels: CherryPick/Approved, Docs/Not Needed, QA Review Done

#5311 Automated cherry pick of #5297
  components/invitation_modal/__snapshots__/invitation_modal.test.jsx.snap
  components/invitation_modal/invitation_modal.jsx
  components/invitation_modal/invitation_modal_members_step.jsx
  components/invitation_modal/invitation_modal_members_step.test.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5312 Fix module error in existing email spec
  e2e/cypress/integration/onboarding/existing_email_adress_spec.js
Labels: QA Review Done

#5315 Quick fix: use superagent when sending Cypress test report
  e2e/package-lock.json
  e2e/package.json
  e2e/run_tests.js
Labels: QA Review Done

#5294 [MM-23995] [MM-23996] Fix improper rendering of bot profile picture and bot roles
  components/integrations/bots/add_bot/add_bot.jsx
  components/integrations/bots/add_bot/index.js
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#5263 [MM-23727] Fix validation for channel url when renaming channel
  components/change_url_modal/__snapshots__/change_url_modal.test.tsx.snap
  components/change_url_modal/change_url_modal.test.tsx
  components/change_url_modal/change_url_modal.tsx
  components/rename_channel_modal/rename_channel_modal.jsx
  components/rename_channel_modal/rename_channel_modal.test.jsx
  utils/url.test.tsx
  utils/url.tsx
Labels: QA Review Done

#5316 Automated cherry pick of #5294
  components/integrations/bots/add_bot/add_bot.jsx
  components/integrations/bots/add_bot/index.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5241 MM-23252 Show parent post link when deleting first reply
  components/post_view/post_body/post_body.jsx
Labels: QA Review Done

#5292 [MM-23427] Update redux and manually add selected changes for MM-23427
  components/channel_layout/channel_identifier_router/actions.js
  package-lock.json
  package.json
Labels: 3: Reviews Complete, QA Review Done

#5306 Added E2E Cypress test to verify accessibility support in Emoji Popover
  e2e/cypress/integration/accessibility/accessibility_popovers_spec.js
Labels: 3: Reviews Complete, QA Review Done

#5322 translations PR 20200413
  i18n/es.json
  i18n/it.json
  i18n/ko.json
  i18n/nl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/tr.json
  i18n/zh-CN.json
Labels: 3: Reviews Complete, AutoMerge

#5314 MM-24051 Added E2E Cypress test to verify Accessibility keyboard usability across different regions in the app
  e2e/cypress/integration/accessibility/accessibility_keyboard_usability_spec.js
Labels: 3: Reviews Complete, QA Review Done

#5313 MM-18457 E2E for sending message to other channel via custom slash command
  e2e/cypress/integration/integrations/message_to_channel_via_slash_command_spec.js
  e2e/package.json
  e2e/webhook_serve.js
Labels: 3: Reviews Complete, QA Review Done

#5309 Fix accessibility input fields
  e2e/cypress/integration/accessibility/accessibility_input_fields_spec.js
Labels: 3: Reviews Complete, QA Review Done

#5290 Fixing discard changes confirm modal accesibility for invitation process
  components/confirm_modal.tsx
Labels: 3: Reviews Complete, QA Review Done

#5321 MM-21401: Minor adjustments to Team Pages
  components/admin_console/team_channel_settings/team/details/__snapshots__/team_profile.test.jsx.snap
  components/admin_console/team_channel_settings/team/details/team_profile.jsx
  sass/components/_groups.scss
  sass/components/_team-channel-settings.scss
Labels: 3: Reviews Complete, QA Review Done

#5329 Fixed tests based on Channel switcher changes
  e2e/cypress/integration/account_settings/sidebar/channel_switcher_spec.js
  e2e/cypress/integration/channel_sidebar/history_channel_switcher_spec.js
Labels: QA Review Done

#5178 MM-14177 listen for alt/option + enter/return and insert a line break
  components/create_comment/create_comment.jsx
  components/create_comment/create_comment.test.jsx
  components/create_post/create_post.jsx
  components/create_post/create_post.test.jsx
  components/edit_channel_header_modal/edit_channel_header_modal.jsx
  components/edit_channel_header_modal/edit_channel_header_modal.test.jsx
  components/edit_channel_purpose_modal/edit_channel_purpose_modal.jsx
  components/edit_channel_purpose_modal/edit_channel_purpose_modal.test.jsx
  components/edit_post_modal/edit_post_modal.jsx
  components/edit_post_modal/edit_post_modal.test.jsx
  tests/helpers/line_break_helpers.js
  tests/helpers/user_agent_mocks.js
  utils/user_agent.tsx
  utils/utils.jsx
  utils/utils.test.jsx
Labels: 3: Reviews Complete, QA Review Done

#5332 Fix username, fullname, nickname
  e2e/cypress/integration/account_settings/general/fullname_spec.js
  e2e/cypress/integration/enterprise/elasticsearch_autocomplete/renaming_spec.js
  e2e/cypress/integration/enterprise/elasticsearch_autocomplete/users_spec.js
Labels: QA Review Done

#5335 translations PR 20200414
  i18n/de.json
  i18n/fr.json
  i18n/ro.json
Labels: 3: Reviews Complete, AutoMerge

#4977 MM-23015: Enable or disable group mentions
  actions/views/group.js
  components/__snapshots__/textbox.test.jsx.snap
  components/admin_console/group_settings/group_details/__snapshots__/group_details.test.jsx.snap
  components/admin_console/group_settings/group_details/__snapshots__/group_profile_and_settings.test.jsx.snap
  components/admin_console/group_settings/group_details/group_details.jsx
  components/admin_console/group_settings/group_details/group_details.test.jsx
  components/admin_console/group_settings/group_details/group_profile.jsx
  components/admin_console/group_settings/group_details/group_profile.test.jsx
  components/admin_console/group_settings/group_details/group_profile_and_settings.jsx
  components/admin_console/group_settings/group_details/group_profile_and_settings.test.jsx
  components/admin_console/group_settings/group_details/index.jsx
  components/admin_console/team_channel_settings/channel/details/__snapshots__/channel_details.test.tsx.snap
  components/admin_console/team_channel_settings/channel/details/channel_details.test.tsx
  components/needs_team/index.ts
  components/needs_team/needs_team.test.tsx
  components/needs_team/needs_team.tsx
  components/suggestion/at_mention_provider/at_mention_provider.jsx
  components/suggestion/at_mention_provider/at_mention_provider.test.jsx
  components/suggestion/at_mention_provider/at_mention_suggestion.jsx
  components/suggestion/suggestion_box.test.jsx
  components/textbox.test.jsx
  components/textbox/index.js
  components/textbox/textbox.jsx
  i18n/en.json
  package-lock.json
  package.json
  sass/components/_groups.scss
  utils/constants.jsx
Labels: 3: Reviews Complete, QA Review Done

#5284 MM-23879 - Minor UI Fixes
  sass/components/_channel-switcher.scss
  sass/components/_modal.scss
  sass/components/_search.scss
  sass/responsive/_mobile.scss
Labels: QA Review Done

#5328 MM-24147 - Updating autocomplete UI issues
  components/widgets/badges/badge.scss
  components/widgets/menu/menu_group.scss
  sass/components/_suggestion-list.scss
Labels: 3: Reviews Complete, QA Review Done

#5180 migrating lhs and rhs selectors to typescript
  components/post_view/post_info/index.js
  components/rhs_card/index.js
  components/rhs_thread/index.js
  components/sidebar/index.ts
  components/sidebar/sidebar_channel/sidebar_channel_icon/index.ts
  selectors/lhs.ts
  selectors/rhs.test.js
  selectors/rhs.ts
  types/store/rhs.ts
Labels: 3: Reviews Complete, QA Review Done

#5304 Added E2E Cypress test to verify Accessibility Support in different Buttons
  e2e/cypress/integration/accessibility/accessibility_buttons_spec.js
Labels: 3: Reviews Complete, QA Review Done

#5303 Quick wins bucket 4
  components/post_view/reaction_list/__snapshots__/reactions_list.test.jsx.snap
  components/post_view/reaction_list/reaction_list.jsx
  components/widgets/icons/add_reaction_icon.jsx
  i18n/en.json
  sass/components/_mentions.scss
  sass/components/_post.scss
  utils/utils.jsx
Labels: QA Review Done

#5330 [MM-23159] Highlight Group Names
  components/markdown/index.ts
  package-lock.json
  package.json
Labels: 3: Reviews Complete, QA Review Done

#5298 [MM23348] Selecting an emoji from emoji picker should insert it at the cursor position
  e2e/cypress/integration/messaging/emoji_insert_position_spec.js
Labels: 3: Reviews Complete, QA Review Done

#5282 Bucket 3: Posts
  components/file_attachment/__snapshots__/file_attachment.test.jsx.snap
  components/file_attachment/__snapshots__/filename_overlay.test.jsx.snap
  components/file_attachment/file_attachment.jsx
  components/file_attachment/filename_overlay.jsx
  components/file_preview/__snapshots__/file_preview.test.tsx.snap
  components/file_preview/__snapshots__/file_progress_preview.test.tsx.snap
  components/file_preview/file_preview.tsx
  components/file_preview/file_progress_preview.tsx
  components/single_image_view/__snapshots__/single_image_view.test.jsx.snap
  components/single_image_view/single_image_view.jsx
  images/icons/audio.png
  images/icons/audio.svg
  images/icons/code.png
  images/icons/code.svg
  images/icons/excel.png
  images/icons/excel.svg
  images/icons/generic.png
  images/icons/generic.svg
  images/icons/image.png
  images/icons/image.svg
  images/icons/patch.png
  images/icons/patch.svg
  images/icons/pdf.png
  images/icons/pdf.svg
  images/icons/powerpoint.svg
  images/icons/ppt.png
  images/icons/ppt.svg
  images/icons/text.svg
  images/icons/video.png
  images/icons/video.svg
  images/icons/word.png
  images/icons/word.svg
  images/icons/zip.svg
  sass/components/_channel-header__icon.scss
  sass/components/_files.scss
  sass/components/_post-menu.scss
  sass/components/_post.scss
  sass/components/_search.scss
  sass/responsive/_desktop.scss
  sass/utils/_mixins.scss
  utils/constants.jsx
  utils/utils.jsx
Labels: 3: Reviews Complete, QA Review Done

#5338 Shortcuts modal and Emoji picker UI Fixes
  sass/components/_emoticons.scss
  sass/routes/_shortcuts-modal.scss
  utils/utils.jsx
Labels: 2: QA Review, Setup Cloud Test Server

#5327 Update en.json
  i18n/en.json
Labels: 3: Reviews Complete

#5281 [MM-23019] Add use_group_mentions to system console
  components/admin_console/permission_schemes_settings/guest_permissions_tree/__snapshots__/guest_permissions_tree.test.jsx.snap
  components/admin_console/permission_schemes_settings/guest_permissions_tree/guest_permissions_tree.jsx
  components/admin_console/permission_schemes_settings/guest_permissions_tree/index.jsx
  components/admin_console/permission_schemes_settings/permission_schemes_settings.jsx
  components/admin_console/permission_schemes_settings/permissions_tree/__snapshots__/permissions_tree.test.jsx.snap
  components/admin_console/permission_schemes_settings/permissions_tree/permissions_tree.jsx
  e2e/cypress/integration/enterprise/system_console/team_guest_channel_spec.js
  i18n/en.json
  sass/components/_permissions.scss
  utils/constants.jsx
Labels: 3: Reviews Complete, QA Review Done

#5287 [MM-23872] Fix signup callback sending user to undefined team name on error
  components/signup/signup_email/__snapshots__/signup_email.test.jsx.snap
  components/signup/signup_email/signup_email.jsx
  components/signup/signup_email/signup_email.test.jsx
Labels: QA Review Done

#5349 [MM-23716] Re-add create_post write translations (#5259) (cherry-pick)
  i18n/uk.json
Labels: 3: Reviews Complete

#5355 Automated cherry pick of #5241
  components/post_view/post_body/post_body.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5212 MM-23569: Add Rudder for diagnostics in addition to Segment.
  components/root/root.jsx
  package-lock.json
  package.json
  utils/constants.jsx
  webpack.config.js
Labels: CherryPick/Candidate, QA Review Done

#5363 Automated cherry pick of #5073
  components/channel_header/__snapshots__/channel_header.test.jsx.snap
  components/channel_header/channel_header.js
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5364 Automated cherry pick of #5225
  components/rhs_comment/rhs_comment.jsx
  components/rhs_root_post/rhs_root_post.jsx
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5365 Automated cherry pick of #5224
  actions/global_actions.jsx
  actions/global_actions.test.js
  actions/views/channel.js
  components/legacy_sidebar/sidebar_channel/index.js
  components/legacy_sidebar/sidebar_channel/sidebar_channel.jsx
  components/legacy_sidebar/sidebar_channel/sidebar_channel.test.jsx
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5368 MM-24421 Upgrade Cypress version
  e2e/package-lock.json
  e2e/package.json
Labels: QA Review Done

#5356 MM-22917 Allow up to 5 plugin header buttons to be displayed before a menu appears.
  components/channel_header/__snapshots__/channel_header.test.jsx.snap
  components/channel_header/channel_header.js
  plugins/channel_header_plug/__snapshots__/channel_header_plug.test.jsx.snap
  plugins/channel_header_plug/channel_header_plug.jsx
  plugins/channel_header_plug/channel_header_plug.test.jsx
  sass/layout/_headers.scss
Labels: QA Review Done, Setup Cloud Test Server

#5343 [MM-23639] Muted channels on another team appear as unread in team sidebar and browser tab
  actions/post_actions.jsx
  actions/post_actions.test.js
Labels: CherryPick/Approved, QA Review Done

#5269 [GH-14152] Retain emoji search gif picker
  components/emoji_picker/emoji_picker.jsx
  components/emoji_picker/emoji_picker.test.jsx
  components/emoji_picker/emoji_picker_tabs.jsx
  components/gif_picker/components/App/index.jsx
  components/gif_picker/components/Header/index.jsx
  components/gif_picker/components/SearchBar/index.jsx
  components/gif_picker/gif_picker.jsx
Labels: QA Review Done

#5346 [MM-24222] - Set mentions to true in header change message
  components/post_markdown/__snapshots__/post_markdown.test.jsx.snap
  components/post_markdown/system_message_helpers.jsx
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done, Setup Cloud Test Server

#5374 Automated cherry pick of #5343
  actions/post_actions.jsx
  actions/post_actions.test.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5381 Automated cherry pick of #5197
  components/create_post/create_post.jsx
  components/create_post/create_post.test.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5324 MM-24128: Remove extra space from 'React to last message' shortcut help text
  components/shortcuts_modal.jsx
  i18n/en.json
Labels: 3: Reviews Complete, QA Review Done

#5380 Automated cherry pick of #5346
  components/post_markdown/__snapshots__/post_markdown.test.jsx.snap
  components/post_markdown/system_message_helpers.jsx
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5377 MM-24445 - Updating channel header icon css
  components/channel_header/__snapshots__/channel_header.test.jsx.snap
  components/channel_header/channel_header.js
  sass/components/_channel-header__icon.scss
  sass/layout/_headers.scss
  utils/utils.jsx
Labels: 3: Reviews Complete, QA Review Done

#5334 MM-24066: Showing guest badge on channel header for GMs
  components/channel_header/channel_header.js
  components/channel_header/channel_header.test.jsx
Labels: CherryPick/Approved, QA Review Done, Tests/Done

#5366 Added Cypress tests to verify accessibility support in images & incoming messages
  e2e/cypress/integration/accessibility/accessibility_account_settings_spec.js
  e2e/cypress/integration/accessibility/accessibility_image_spec.js
  e2e/cypress/integration/accessibility/accessibility_modals_dialogs_spec.js
  e2e/cypress/integration/accessibility/accessibility_post_spec.js
Labels: 3: Reviews Complete, QA Review Done

#5239 MM23360 - Emoji characters followed by punctuation
  e2e/cypress/integration/messaging/emoji_followed_by_punctuation_spec.js
Labels: 3: Reviews Complete

#5320 MM-23994 Fix slash command /leave causing webapp stuck trying to load left channel
  actions/websocket_actions.jsx
  e2e/cypress/integration/commands/leave_channel_spec.js
Labels: CherryPick/Approved, QA Review Done

#5337 [MM-22802] [MM-22801] Dont show createPost until channel roles are loaded
  components/channel_view/__snapshots__/channel_view.test.jsx.snap
  components/channel_view/channel_view.jsx
  components/channel_view/channel_view.test.jsx
  components/channel_view/index.js
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#5395 Automated cherry pick of #5337
  components/channel_view/__snapshots__/channel_view.test.jsx.snap
  components/channel_view/channel_view.jsx
  components/channel_view/channel_view.test.jsx
  components/channel_view/index.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5347 Adds support for TypeScript syntax highlighting
  types/external/highlightjs.d.ts
  utils/constants.jsx
  utils/syntax_highlighting.tsx
Labels: 3: Reviews Complete, QA Review Done

#5331 [MM 23264] Show Confirmation Modal for group mentions
  actions/websocket_actions.jsx
  components/admin_console/admin_definition.jsx
  components/create_comment/__snapshots__/create_comment.test.jsx.snap
  components/create_comment/create_comment.jsx
  components/create_comment/create_comment.test.jsx
  components/create_comment/index.js
  components/create_post/__snapshots__/create_post.test.jsx.snap
  components/create_post/create_post.jsx
  components/create_post/create_post.test.jsx
  components/create_post/index.js
  i18n/en.json
  package-lock.json
  package.json
  utils/post_utils.jsx
  utils/text_formatting.tsx
Labels: 3: Reviews Complete, QA Review Done

#5369 MM-24392 - Updating modal css
  sass/components/_modal.scss
Labels: 3: Reviews Complete

#5342 [MM-23727] Proposal to remove unnecessarily strict channel url validation
  components/change_url_modal/__snapshots__/change_url_modal.test.tsx.snap
  components/change_url_modal/change_url_modal.tsx
  components/new_channel_modal/__snapshots__/new_channel_modal.test.jsx.snap
  components/new_channel_modal/new_channel_modal.jsx
  components/rename_channel_modal/__snapshots__/rename_channel_modal.test.jsx.snap
  components/rename_channel_modal/rename_channel_modal.jsx
  components/rename_channel_modal/rename_channel_modal.test.jsx
  i18n/en.json
  sass/components/_forms.scss
  utils/url.test.tsx
  utils/url.tsx
  utils/utils.jsx
Labels: 3: Reviews Complete, QA Review Done

#5344 [MM-23605] Reload team memberships when team scheme is updated
  actions/websocket_actions.jsx
  utils/constants.jsx
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#5404 Automated cherry pick of #5344
  actions/websocket_actions.jsx
  utils/constants.jsx
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5302 [MM-24027] Add profile pop-over when clicking a user in the View/Manage members modals
  components/channel_members_modal/channel_members_modal.tsx
  components/popover_list_members/__snapshots__/popover_list_members.test.jsx.snap
  components/popover_list_members/popover_list_members.jsx
  components/popover_list_members/popover_list_members.test.jsx
  components/profile_popover/__snapshots__/profile_popover.test.jsx.snap
  components/profile_popover/index.js
  components/profile_popover/profile_popover.jsx
  components/profile_popover/profile_popover.test.jsx
  components/team_members_modal/team_members_modal.tsx
  components/user_list_row/user_list_row.jsx
  components/user_profile/__snapshots__/user_profile.test.jsx.snap
  components/user_profile/user_profile.jsx
  components/user_profile/user_profile.test.jsx
  utils/utils.jsx
Labels: 3: Reviews Complete, QA Review Done, Setup Cloud Test Server

#5333 MM-23933 Fix for post text box overriding content on paste of github codeblock
  components/create_comment/create_comment.jsx
  components/create_comment/create_comment.test.jsx
  components/create_post/create_post.jsx
  components/create_post/create_post.test.jsx
  utils/paste.test.tsx
  utils/paste.tsx
Labels: QA Review Done

#5339 Update multiselect string in en.json
  i18n/en.json
Labels: 3: Reviews Complete

#5319 MM-24108 Hide next/prev team shortcuts on Linux
  components/shortcuts_modal.jsx
  utils/utils.jsx
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#5407 Automated cherry pick of #5319
  components/shortcuts_modal.jsx
  utils/utils.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5392 Refactor: move @types/* to devDeps and update stale package-lock
  package-lock.json
  package.json
Labels: 3: Reviews Complete, QA Review Done

#5384 [MM-24338] - Render plugins section only when components are present in state
  components/dot_menu/dot_menu.jsx
  components/dot_menu/dot_menu.test.jsx
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#5386 [MM-23384] Readded div to wrap around contents of OverlayTrigger
  components/sidebar/sidebar_channel/sidebar_channel_link/__snapshots__/sidebar_channel_link.test.tsx.snap
  components/sidebar/sidebar_channel/sidebar_channel_link/sidebar_channel_link.tsx
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#5403 Highlight hovered items when searching with "in:"
  components/suggestion/search_channel_suggestion/search_channel_suggestion.jsx
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#5415 Automated cherry pick of #5403
  components/suggestion/search_channel_suggestion/search_channel_suggestion.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5323 MM-24057: team integration permissions
  components/main_menu/index.jsx
  e2e/cypress/integration/menus/main_menu_spec.js
Labels: QA Review Done

#5360 translations PR 20200420
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/ro.json
  i18n/ru.json
  i18n/uk.json
Labels: 3: Reviews Complete, AutoMerge

#5416 Automated cherry pick of #5384
  components/dot_menu/dot_menu.jsx
  components/dot_menu/dot_menu.test.jsx
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5357 [MM-24356] Dispatch getChannelMemberCountsByGroup if timezones are enabled when user is updated
  actions/websocket_actions.jsx
Labels: 3: Reviews Complete

#5400 MM-24311 - Updating min height for preview textarea
  sass/components/_post.scss
Labels: 3: Reviews Complete

#5397 ID21032 UI Automation: automated test using Cypress for "Password element check"
  e2e/cypress/integration/interactive_dialog/full_dialog_spec.js
Labels: 3: Reviews Complete

#5340 MM-24050: Added Cypress E2E test to verify accessibility support in Invite People Flow.
  e2e/cypress/integration/accessibility/accessibility_modals_dialogs_spec.js
Labels: 3: Reviews Complete, QA Review Done

#5325 [MM-20598] Migrate components/delete_channel_modal to TypeScript
  components/delete_channel_modal/__snapshots__/delete_channel_modal.test.tsx.snap
  components/delete_channel_modal/delete_channel_modal.test.tsx
  components/delete_channel_modal/delete_channel_modal.tsx
  components/delete_channel_modal/index.ts
Labels: 3: Reviews Complete, QA Review Done

#5394 MM-24487 - Updating icons in invite modal dropdown
  components/suggestion/search_channel_with_permissions_provider.jsx
  sass/components/_suggestion-list.scss
Labels: QA Review Done

#5383 MM-21404 - Channel Page UI Tweeks
  components/admin_console/team_channel_settings/channel/details/__snapshots__/channel_profile.test.tsx.snap
  components/admin_console/team_channel_settings/channel/details/channel_profile.tsx
  components/admin_console/team_channel_settings/group/group_list.tsx
  i18n/en.json
  sass/components/_team-channel-settings.scss
Labels: 3: Reviews Complete

#5417 MM-24590: fix roles check on leave
  components/channel_view/index.js
  e2e/cypress/integration/messaging/channel_menu_spec.js
Labels: 3: Reviews Complete, CherryPick/Approved

#5424 Automated cherry pick of #5417
  components/channel_view/index.js
  e2e/cypress/integration/channel/channel_menu_spec.js
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5425 Bumping mattermost-redux to the last release-5.23 branch HEAD
  package-lock.json
  package.json
Labels: 3: Reviews Complete, Tests/Not Needed
