Repository mattermost/mattermost-webapp, pull requests merged in 2020-03, with the labels that each got.

#4910 Add types for webapp-specific state
  components/access_history_modal/index.ts
  components/admin_console/admin_navbar_dropdown/index.ts
  components/admin_console/admin_sidebar_header/index.ts
  components/admin_console/audits/index.ts
  components/admin_console/index.ts
  components/admin_console/reset_password_modal/index.ts
  components/admin_console/system_users/system_users_dropdown/index.ts
  components/admin_console/team_channel_settings/channel/list/index.ts
  components/channel_layout/center_channel/index.ts
  components/channel_members_modal/index.ts
  components/error_page/index.tsx
  components/file_attachment/file_thumbnail/index.ts
  components/file_info_preview/index.ts
  components/leave_team_modal/index.ts
  components/linking_landing_page/index.tsx
  components/local_date_time/index.ts
  components/member_list_channel/index.ts
  components/member_list_team/index.ts
  components/msg_typing/index.ts
  components/notify_counts/index.ts
  components/permissions_gates/team_permission_gate/index.ts
  components/post_emoji/index.tsx
  components/setting_item_min/index.ts
  components/team_members_modal/index.ts
  package-lock.json
  tsconfig.json
  types/external/custom-protocol-detection.d.ts
  types/external/highlightjs.d.ts
  types/external/images.d.ts
  types/external/key-mirror.d.ts
  types/external/react-bootstrap.d.ts
  types/external/svg.d.ts
  types/store/i18n.ts
  types/store/index.ts
  types/store/plugins.ts
  types/store/rhs.ts
Labels: 3: Reviews Complete

#4928 Update Redux commit hash
  package-lock.json
  package.json
Labels: 3: Reviews Complete, CherryPick/Approved

#4956 Fix mention autocomplete overlap spec
  e2e/cypress/integration/messaging/mention_autocomplete_overlap_spec.js
Labels: 3: Reviews Complete, QA Review Done

#4944 Added test to verify Accessibility Support in Account Settings
  e2e/cypress/fixtures/account_setting_sections.json
  e2e/cypress/integration/accessibility/accessibility_account_settings_spec.js
Labels: 2: Dev Review, QA Review Done

#4937 Added Cypress test to verify Accessibility Support in Modals & Dialogs
  components/team_settings_modal/__snapshots__/team_settings_modal.test.jsx.snap
  components/team_settings_modal/team_settings_modal.jsx
  e2e/cypress/integration/accessibility/accessibility_modals_dialogs_spec.js
Labels: QA Review Done

#4951 Added Cypress test to verify Accessibility Support in Dropdown Menus
  components/status_dropdown/status_dropdown.jsx
  e2e/cypress/integration/accessibility/accessibility_dropdowns_spec.js
  e2e/cypress/integration/messaging/local_date_time_spec.js
  e2e/cypress/support/api_commands.js
  e2e/run_tests.js
Labels: QA Review Done

#4966 MM-22420 - Remove invalid/outdated instruction and link
  components/admin_console/admin_definition.jsx
  i18n/en.json
Labels: 3: Reviews Complete, QA Review Done

#4916 [MM-22622] Add mentionHighlightDisabled props on create post and create comment
  actions/views/create_comment.jsx
  components/create_comment/create_comment.jsx
  components/create_comment/create_comment.test.jsx
  components/create_post/create_post.jsx
  components/create_post/create_post.test.jsx
  components/post_markdown/__snapshots__/post_markdown.test.jsx.snap
  components/post_markdown/post_markdown.jsx
  components/post_markdown/system_message_helpers.jsx
  utils/post_utils.jsx
  utils/post_utils.test.jsx
  utils/text_formatting.tsx
Labels: QA Review Done

#4938 [MM-22370] Fix channel modal not showing updated roles
  components/member_list_channel/index.ts
  components/member_list_channel/member_list_channel.tsx
Labels: 3: Reviews Complete, QA Review Done

#4900 [MM-20518] - Convert channel_groups_manage_modal to TypeScript
  actions/views/modals.js
  components/channel_groups_manage_modal/channel_groups_manage_modal.tsx
  components/channel_groups_manage_modal/index.js
  components/channel_groups_manage_modal/index.ts
Labels: 2: Dev Review, QA Review Done

#4981 MM-22969 - Updating paragraph styling in list item
  sass/layout/_post.scss
Labels: 3: Reviews Complete, AutomatedCherryPick, CherryPick/Approved, QA Review Done, Setup Cloud Test Server

#4968 translations PR 20200302
  i18n/es.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pt-BR.json
  i18n/ru.json
  i18n/tr.json
  i18n/zh-CN.json
Labels: 3: Reviews Complete

#4965 Use webapp-specific GlobalState everywhere
  components/admin_console/system_user_detail/team_list/index.ts
  components/more_direct_channels/index.ts
  components/removed_from_channel_modal/index.ts
Labels: 3: Reviews Complete

#4986 Automated cherry pick of #4981
  sass/layout/_post.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4914 MM-22114 Add view state for collapsed categories and unread filter
  actions/views/channel_sidebar.test.ts
  actions/views/channel_sidebar.ts
  reducers/views/channel_sidebar.ts
  reducers/views/index.js
  selectors/storage.js
  selectors/views/channel_sidebar.test.ts
  selectors/views/channel_sidebar.ts
  utils/constants.jsx
Labels: 3: Reviews Complete

#4982 MM-23012 - Hiding scrollbars in IE from LHS/RHS
  sass/components/_scrollbar.scss
Labels: AutomatedCherryPick, CherryPick/Approved, QA Review Done

#4990 Automated cherry pick of #4982
  sass/components/_scrollbar.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4954 Upgrade to cypress 4.0
  e2e/cypress/plugins/index.js
  e2e/package-lock.json
  e2e/package.json
  e2e/run_tests.js
Labels: QA Review Done

#4988 MM-22754 Fix for missing closing bracket
  i18n/en.json
Labels: 2: QA Review, 3: Reviews Complete

#4979 MM-22760 - Updating position logic for post menu
  components/dot_menu/dot_menu.jsx
  utils/constants.jsx
Labels: 3: Reviews Complete, AutomatedCherryPick, CherryPick/Approved, QA Review Done, Setup Cloud Test Server

#4825 MM-11505 Update permalink view
  components/channel_layout/center_channel/center_channel.tsx
  components/channel_layout/channel_identifier_router/channel_identifier_router.jsx
  components/channel_layout/channel_identifier_router/channel_identifier_router.test.jsx
  components/channel_view/channel_view.jsx
  components/channel_view/channel_view.test.jsx
  components/delete_post_modal/delete_post_modal.jsx
  components/delete_post_modal/delete_post_modal.test.jsx
  components/delete_post_modal/index.js
  components/permalink_view/__snapshots__/permalink_view.test.jsx.snap
  components/permalink_view/actions.js
  components/permalink_view/index.js
  components/permalink_view/permalink_view.jsx
  components/permalink_view/permalink_view.test.jsx
  components/post_view/index.js
  components/post_view/post/__snapshots__/post.test.js.snap
  components/post_view/post/post.jsx
  components/post_view/post/post.test.js
  components/post_view/post_list/index.js
  components/post_view/post_list_virtualized/post_list_virtualized.jsx
  components/post_view/post_view.jsx
  components/sidebar_right/index.js
  components/toast/__snapshots__/toast.test.jsx.snap
  components/toast/toast.jsx
  components/toast/toast.scss
  components/toast/toast.test.jsx
  components/toast_wrapper/toast_wrapper.jsx
  components/toast_wrapper/toast_wrapper.test.jsx
  e2e/cypress.json
  e2e/cypress/integration/channel/toast_spec.js
  e2e/cypress/integration/messaging/message_permalink_spec.js
  i18n/en.json
  reducers/views/channel.js
  sass/layout/_post.scss
  utils/constants.jsx
Labels: 3: Reviews Complete, QA Review Done, Setup Cloud Test Server

#4994 MM-22970: Fix highlighting of at mentions of self
  components/post_markdown/__snapshots__/post_markdown.test.jsx.snap
  components/post_markdown/post_markdown.jsx
  components/post_markdown/post_markdown.test.jsx
Labels: 3: Reviews Complete, QA Review Done

#4959 GH-13807 Enable notification sounds in FF, update i18n strings with same
  components/user_settings/notifications/__snapshots__/desktop_notification_settings.test.jsx.snap
  components/user_settings/notifications/desktop_notification_settings.jsx
  i18n/en.json
  utils/utils.jsx
Labels: 2: Dev Review, QA Review Done

#4980 MM-22929 - Updating back button in Account modal
  components/user_settings/sidebar/__snapshots__/user_settings_sidebar.test.jsx.snap
  components/user_settings/sidebar/user_settings_sidebar.jsx
Labels: 3: Reviews Complete, AutomatedCherryPick, CherryPick/Approved, QA Review Done

#5002 MM-22698 Fix for unread channel getting stuck at Loading indicator
  package-lock.json
  package.json
Labels: 3: Reviews Complete, QA Review Done

#5003 MM-21584 Replace removeItem call with setItem
  actions/views/channel_sidebar.ts
Labels: 2: Dev Review

#4996 Automated cherry pick of #4979
  components/dot_menu/dot_menu.jsx
  utils/constants.jsx
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4839 Migrate 'components/needs_team' module and associated tests to TS
  components/needs_team/__snapshots__/needs_team.test.tsx.snap
  components/needs_team/index.ts
  components/needs_team/needs_team.test.tsx
  components/needs_team/needs_team.tsx
  types/inobounce.d.ts
Labels: 3: Reviews Complete, QA Review Done

#4989 Fixed issue in Cypress test while selecting a group in Add New Groups Dialog
  e2e/cypress/integration/enterprise/system_console/team_and_channel_asign_roles_spec.js
Labels: QA Review Done

#4983 Fixed Accessibility related Cypress tests based on run on Cypress test instance
  e2e/cypress/fixtures/account_setting_sections.json
  e2e/cypress/integration/accessibility/accessibility_account_settings_spec.js
  e2e/cypress/integration/accessibility/accessibility_dropdowns_spec.js
  e2e/cypress/integration/accessibility/accessibility_modals_dialogs_spec.js
Labels: QA Review Done

#5000 Automated cherry pick of #4980
  components/user_settings/sidebar/__snapshots__/user_settings_sidebar.test.jsx.snap
  components/user_settings/sidebar/user_settings_sidebar.jsx
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4995 Revert "[MM-21000] Fix using local storage to return to a DM/GM (#4791)"
  actions/global_actions.jsx
  actions/global_actions.test.js
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#5007 Automated cherry pick of #4995
  actions/global_actions.jsx
  actions/global_actions.test.js
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5006 Added Cypress test to verify Accessibility support in different input fields
  e2e/cypress/integration/accessibility/accessibility_input_fields_spec.js
Labels: QA Review Done

#4974 MM-22857 Fix lists being unable to start with 0
  utils/markdown/index.test.js
  utils/markdown/renderer.tsx
Labels: 3: Reviews Complete, QA Review Done

#4881 [MM-22276] Create Channel Moderation Widget
  components/admin_console/permission_schemes_settings/permission_system_scheme_settings/__snapshots__/permission_system_scheme_settings.test.jsx.snap
  components/admin_console/permission_schemes_settings/permission_system_scheme_settings/permission_system_scheme_settings.jsx
  components/admin_console/team_channel_settings/channel/details/__snapshots__/channel_details.test.tsx.snap
  components/admin_console/team_channel_settings/channel/details/channel_details.test.tsx
  components/admin_console/team_channel_settings/channel/details/channel_details.tsx
  components/admin_console/team_channel_settings/channel/details/channel_moderation.tsx
  components/admin_console/team_channel_settings/channel/details/index.js
  e2e/cypress/integration/enterprise/system_console/channel_moderation_spec.js
  i18n/en.json
  package-lock.json
  package.json
  sass/components/_groups.scss
  utils/constants.jsx
Labels: 3: Reviews Complete, QA Review Done

#4992 Define handleFormattedTextClick as an arrow function
  components/channel_header/channel_header.js
  components/post_view/message_attachments/message_attachment/message_attachment.jsx
  components/post_view/post_message_view/post_message_view.jsx
Labels: QA Review Done

#5014 Fix failing test on at-mention
  e2e/cypress/integration/at_mentions/at_mentions_spec.js
Labels: QA Review Done

#4883 MM-21707: enable backstage link for only bots
  components/backstage/backstage_controller.jsx
  components/backstage/components/backstage_sidebar.jsx
  components/backstage/components/backstage_sidebar.test.jsx
  components/backstage/index.js
  components/main_menu/__snapshots__/main_menu.test.jsx.snap
  components/main_menu/index.jsx
  components/main_menu/main_menu.jsx
  components/main_menu/main_menu.test.jsx
  plugins/test/__snapshots__/main_menu_action.test.jsx.snap
  plugins/test/main_menu_action.test.jsx
Labels: 3: Reviews Complete, QA Review Done

#4998 Merging of CSS styles into new sidebar code
  components/sidebar/channel_filter/channel_filter.tsx
  components/sidebar/sidebar.tsx
  components/sidebar/sidebar_category/sidebar_category.tsx
  components/sidebar/sidebar_category_list/sidebar_category_list.tsx
  components/sidebar/sidebar_channel/sidebar_base_channel/sidebar_base_channel.tsx
  components/sidebar/sidebar_channel/sidebar_channel.tsx
  components/sidebar/sidebar_channel/sidebar_channel_link/sidebar_channel_link.tsx
  components/sidebar/sidebar_channel/sidebar_direct_channel/sidebar_direct_channel.tsx
  components/status_icon_new.tsx
  components/team_sidebar/team_sidebar.tsx
  fonts/mattermosticons.eot
  fonts/mattermosticons.svg
  fonts/mattermosticons.ttf
  fonts/mattermosticons.woff
  fonts/mattermosticons.woff2
  sass/base/_mattermost-icons.scss
  sass/base/_module.scss
  sass/layout/_sidebar-left.scss
  utils/utils.jsx
Labels: 2: Dev Review

#5005 [MM-22478] Unread Filtering and Create New Channel Menu
  components/sidebar/add_channel_dropdown/add_channel_dropdown.tsx
  components/sidebar/channel_filter/channel_filter.tsx
  components/sidebar/channel_filter/index.ts
  components/sidebar/sidebar.tsx
  components/sidebar/sidebar_category/index.ts
  components/sidebar/sidebar_category/sidebar_category.tsx
  components/sidebar/sidebar_category_list/index.ts
  components/sidebar/sidebar_category_list/sidebar_category_list.tsx
  i18n/en.json
  sass/layout/_sidebar-left.scss
  types/store/index.ts
Labels: 2: Dev Review

#4596 [MM14489] Fix: In interactive dialogs, render autocomplete lists below the input field by default
  components/autocomplete_selector.jsx
  components/autocomplete_selector.test.jsx
  components/interactive_dialog/dialog_element/dialog_element.jsx
  components/suggestion/modal_suggestion_list.jsx
  components/suggestion/suggestion_box.jsx
  sass/components/_modal.scss
  utils/utils.jsx
Labels: 3: Reviews Complete

#5016 Mobile/Desktop Sidebar View + Restored Team Sidebar and Header
  components/channel_layout/channel_controller.jsx
  components/sidebar/index.ts
  components/sidebar/sidebar.tsx
  components/sidebar/sidebar_channel/sidebar_channel_link/sidebar_channel_link.tsx
  components/sidebar/sidebar_header/index.ts
  components/sidebar/sidebar_header/sidebar_header.tsx
  sass/layout/_headers.scss
  sass/layout/_sidebar-left.scss
  sass/responsive/_mobile.scss
Labels: 3: Reviews Complete

#5023 Channel Switcher + History Button Style
  components/sidebar/channel_navigator/channel_navigator.tsx
  components/sidebar/channel_navigator/index.ts
  i18n/en.json
  sass/layout/_sidebar-left.scss
Labels: 3: Reviews Complete

#5012 Add URL check for service required by a Cypress test
  components/widgets/badges/badges_spec.js
  components/widgets/popover/popover_spec.js
  e2e/cypress/integration/interactive_dialog/boolean_spec.js
  e2e/cypress/integration/interactive_dialog/full_dialog_spec.js
  e2e/cypress/integration/interactive_dialog/simple_dialog_spec.js
  e2e/cypress/integration/interactive_menu/basic_options_spec.js
  e2e/cypress/integration/interactive_menu/select_with_keys_spec.js
  e2e/cypress/plugins/index.js
  e2e/cypress/plugins/url_health_check.js
  e2e/cypress/support/task_commands.js
Labels: QA Review Done

#4973 MM-22423 Update landing page translation strings
  components/linking_landing_page/linking_landing_page.tsx
  i18n/en.json
Labels: 3: Reviews Complete, QA Review Done

#4969 [MM-20520] Migrate 'components/new_channel_flow' module and associated tests to TypeScript
  components/new_channel_flow/__snapshots__/new_channel_flow.test.tsx.snap
  components/new_channel_flow/index.js
  components/new_channel_flow/index.ts
  components/new_channel_flow/new_channel_flow.test.tsx
  components/new_channel_flow/new_channel_flow.tsx
Labels: 3: Reviews Complete, AutoMerge, QA Review Done

#4903 MM-18775: Remove some deprecated/unsafe lifecycles
  components/add_groups_to_channel_modal/add_groups_to_channel_modal.jsx
  components/add_groups_to_team_modal/add_groups_to_team_modal.jsx
  components/admin_console/permission_schemes_settings/permission_group.jsx
  components/admin_console/permission_schemes_settings/permission_schemes_settings.jsx
  components/team_selector_modal/team_selector_modal.jsx
Labels: QA Review Done

#3678 [MM-11387] Add team switch shortcuts
  components/shortcuts_modal.jsx
  components/sidebar/sidebar.jsx
  components/team_sidebar/components/team_button.jsx
  components/team_sidebar/team_sidebar_controller.jsx
  i18n/en.json
  sass/components/_tooltip.scss
  sass/layout/_team-sidebar.scss
Labels: QA Review Done

#5038 Fix accessibility support specs
  e2e/cypress/integration/accessibility/accessibility_account_settings_spec.js
  e2e/cypress/integration/accessibility/accessibility_input_fields_spec.js
  e2e/cypress/integration/accessibility/accessibility_modals_dialogs_spec.js
Labels: QA Review Done

#4976 Add custom ESLint rule to prevent passing getState into dispatch
  .eslintrc.json
  actions/storage.js
  package-lock.json
  package.json
Labels: 3: Reviews Complete

#5029 MM-22986 - Updating channel header interaction
  components/channel_header/__snapshots__/channel_header.test.jsx.snap
  components/channel_header/channel_header.js
  i18n/en.json
  sass/layout/_headers.scss
Labels: QA Review Done

#5013 MM-22874 - Updating user popover css
  sass/components/_popover.scss
  utils/utils.jsx
Labels: 2: Dev Review, QA Review Done

#5011 MM-22873 - Updating input UI in DM modal
  components/multiselect/__snapshots__/multiselect.test.tsx.snap
  components/multiselect/multiselect.tsx
Labels: 3: Reviews Complete, QA Review Done, Setup Cloud Test Server

#5008 MM-22869 - Updating team button active state
  sass/layout/_team-button.scss
Labels: QA Review Done

#5015 Fix failing tests by setting known teammate name display preference
  e2e/cypress/integration/channel/channel_routing_spec.js
  e2e/cypress/integration/channel/message_reply_bot_post_spec.js
  e2e/cypress/integration/channel/message_reply_spec.js
  e2e/cypress/integration/email/mention_email_notification_spec.js
  e2e/cypress/integration/enterprise/elasticsearch/renaming_spec.js
  e2e/cypress/integration/enterprise/elasticsearch/users_spec.js
  e2e/cypress/integration/integrations/builtin_commands/common_commands_spec.js
Labels: QA Review Done

#5009 MM-22871 - Updating emoji css
  sass/components/_emoticons.scss
  sass/layout/_post.scss
  utils/utils.jsx
Labels: 2: Dev Review, QA Review Done

#4985 MM-22843 - Updating RHS size on wider screens
  sass/layout/_sidebar-right.scss
  sass/responsive/_desktop.scss
  sass/responsive/_module.scss
  sass/responsive/_tablet.scss
Labels: 2: QA Review, Setup Cloud Test Server

#5021 MM-23112: Mark channel moderation as 'Beta'.
  components/admin_console/team_channel_settings/channel/details/channel_moderation.tsx
  i18n/en.json
Labels: QA Review Done

#5031 MM-22989 - Adding reply count to root posts in RHS (Search, Flags, Pinned)
  components/post_view/post/index.js
  components/post_view/post/index.test.js
  components/search_results_item/index.js
  components/search_results_item/search_results_item.jsx
  utils/post_utils.jsx
  utils/post_utils.test.jsx
Labels: 3: Reviews Complete, QA Review Done

#5044 Fix misc failing specs
  e2e/cypress/integration/accessibility/accessibility_input_fields_spec.js
  e2e/cypress/integration/channel/add_users_to_channel_spec.js
  e2e/cypress/integration/emoji/react_to_last_message_shortcut_spec.js
  e2e/cypress/integration/interactive_dialog/full_dialog_spec.js
  e2e/cypress/integration/interactive_menu/basic_options_spec.js
Labels: 3: Reviews Complete, QA Review Done

#5052 Fix messaging specs
  e2e/cypress/integration/at_mentions/at_mentions_spec.js
  e2e/cypress/integration/enterprise/elasticsearch/renaming_spec.js
  e2e/cypress/integration/interactive_dialog/simple_dialog_spec.js
  e2e/cypress/integration/messaging/channel_read_after_permalink_spec.js
  e2e/cypress/integration/messaging/focus_move_spec.js
  e2e/cypress/integration/messaging/message_permalink_spec.js
  e2e/cypress/integration/messaging/permalink_loading_indicator_spec.js
  e2e/cypress/integration/messaging/permalink_message_edit_spec.js
  e2e/cypress/integration/messaging/post_options_menu_spec.js
  e2e/cypress/integration/post_header/post_header_spec.js
  e2e/cypress/plugins/getClipboard.js
  e2e/cypress/plugins/index.js
  e2e/package-lock.json
  e2e/package.json
Labels: QA Review Done

#4597 [GH-13333] UI Automation: Write an automated test using Cypress for "Individual "User" and "Channel" screens are scrollable
  e2e/cypress/integration/interactive_dialog/scrollable_spec.js
  e2e/utils/webhook_utils.js
  e2e/webhook_serve.js
Labels: 3: Reviews Complete, QA Review Done

#5032 MM-22987 - Making searchbar fixed in console
  components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.jsx.snap
  components/admin_console/admin_sidebar/admin_sidebar.jsx
  sass/routes/_admin-console.scss
Labels: 2: Dev Review, QA Review Done

#5022 MM-22984 - Adding hover state for channel name
  sass/layout/_headers.scss
Labels: 3: Reviews Complete, QA Review Done

#5020 MM-22903 - Updating send message UI in popover
  sass/components/_popover.scss
Labels: 2: Dev Review, QA Review Done

#5047 MM-23091 - Implement Server Setup telemetry - account and team setup flow
  components/announcement_bar/text_dismissable_bar.jsx
  components/create_team/__snapshots__/create_team.test.jsx.snap
  components/create_team/components/display_name.jsx
  components/create_team/components/team_url/team_url.jsx
  components/create_team/create_team.jsx
  components/select_team/__snapshots__/select_team.test.jsx.snap
  components/select_team/select_team.jsx
  components/signup/signup_email/signup_email.jsx
Labels: QA Review Done

#5010 Add check for Cypress tests that require license
  e2e/cypress/integration/enterprise/channels/search_channels_spec.js
  e2e/cypress/integration/enterprise/elasticsearch/channels_spec.js
  e2e/cypress/integration/enterprise/elasticsearch/renaming_spec.js
  e2e/cypress/integration/enterprise/elasticsearch/system_console_spec.js
  e2e/cypress/integration/enterprise/elasticsearch/users_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/guest_experience_ui_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/guest_identification_ui_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/guest_invitation_ui_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/guest_removal_ui_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/member_invitation_ui_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/system_console_guest_access_ui_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/system_console_manage_guest_spec.js
  e2e/cypress/integration/enterprise/saml/okta_login_spec.js
  e2e/cypress/integration/enterprise/system_console/channel_moderation_spec.js
  e2e/cypress/integration/enterprise/system_console/channel_modes_spec.js
  e2e/cypress/integration/enterprise/system_console/groups_assign_roles_spec.js
  e2e/cypress/integration/enterprise/system_console/saml_metadata_spec.js
  e2e/cypress/integration/enterprise/system_console/sidebar_link_navigation_spec.js
  e2e/cypress/integration/enterprise/system_console/team_and_channel_asign_roles_spec.js
  e2e/cypress/integration/enterprise/system_console/ui_and_api/notifications_spec.js
  e2e/cypress/integration/enterprise/teams/invite_bot_spec.js
  e2e/cypress/integration/enterprise/teams/search_teams_spec.js
  e2e/cypress/support/api_commands.js
Labels: QA Review Done

#5025 [MM-22360] - Handle closing of editPostModal when user has unsaved changes
  components/edit_post_modal/__snapshots__/edit_post_modal.test.jsx.snap
  components/edit_post_modal/edit_post_modal.jsx
Labels: QA Review Done

#4931 [MM-22498] Refactor channel header popover to match requirements
  components/channel_header/__snapshots__/channel_header.test.jsx.snap
  components/channel_header/channel_header.js
  components/channel_header/index.js
  sass/components/_popover.scss
  sass/layout/_headers.scss
Labels: 3: Reviews Complete, QA Review Done

#5053 Fixed E2E Cypress test toast_spec
  e2e/cypress/integration/channel/toast_spec.js
  e2e/cypress/support/ui_commands.js
Labels: 3: Reviews Complete, QA Review Done

#4567 [MM-17546] Support plugin pagination in the Plugin Marketplace
  components/plugin_marketplace/__snapshots__/marketplace_modal.test.js.snap
  components/plugin_marketplace/marketplace_list/__snapshots__/marketplace_list.test.jsx.snap
  components/plugin_marketplace/marketplace_list/marketplace_list.jsx
  components/plugin_marketplace/marketplace_list/marketplace_list.test.jsx
  components/plugin_marketplace/marketplace_list/navigation_row/__snapshots__/navigation_row.test.jsx.snap
  components/plugin_marketplace/marketplace_list/navigation_row/index.js
  components/plugin_marketplace/marketplace_list/navigation_row/navigation_button.jsx
  components/plugin_marketplace/marketplace_list/navigation_row/navigation_row.jsx
  components/plugin_marketplace/marketplace_list/navigation_row/navigation_row.test.jsx
  components/plugin_marketplace/marketplace_modal.js
  components/plugin_marketplace/marketplace_modal.scss
  components/plugin_marketplace/marketplace_modal.test.js
  i18n/en.json
Labels: 3: Reviews Complete, AutoMerge, QA Review Done

#5059 Fix header and image attachment specs
  e2e/cypress/integration/channel/header_spec.js
  e2e/cypress/support/ui_commands.js
Labels: QA Review Done

#5058 Fix e2e tests for channel at-mentions and tooltips
  e2e/cypress/integration/at_mentions/at_mentions_spec.js
  e2e/cypress/integration/channel/channel_name_tooltips_spec.js
Labels: QA Review Done

#5050 [MM-22556] Remove email reference from help text when email invitations are disabled
  components/invitation_modal/__snapshots__/invitation_modal.test.jsx.snap
  components/invitation_modal/__snapshots__/invitation_modal_initial_step.test.jsx.snap
  components/invitation_modal/invitation_modal.jsx
  components/invitation_modal/invitation_modal_initial_step.jsx
  components/invitation_modal/invitation_modal_initial_step.test.jsx
  i18n/en.json
Labels: 3: Reviews Complete, QA Review Done

#4967 MM-21983-add padding to bottom of admin_sidebar
  sass/routes/_admin-console.scss
Labels: 2: Dev Review, QA Review Done

#4042 MM 18527 - sort teams in LHS
  actions/team_actions.jsx
  components/team_sidebar/components/team_button.jsx
  components/team_sidebar/index.js
  components/team_sidebar/team_sidebar_controller.jsx
  package-lock.json
  package.json
  sass/layout/_team-sidebar.scss
  utils/constants.jsx
  utils/team_utils.jsx
  utils/team_utils.test.jsx
  utils/utils.jsx
Labels: Hacktoberfest, QA Review Done

#5037 [MM-22674] Clicking Hashtag in the Popover of channel header now searches for term
  components/channel_header/__snapshots__/channel_header.test.jsx.snap
  components/channel_header/channel_header.js
Labels: 3: Reviews Complete, QA Review Done

#5024 [MM-21408] make name display consistent for DM and align it with mobiles
  components/post_view/channel_intro_message/channel_intro_message.jsx
  components/post_view/channel_intro_message/index.js
  package-lock.json
  package.json
Labels: 3: Reviews Complete, QA Review Done

#5071 [MM-22962] Expose group mentions in the system console UI
  components/admin_console/permission_schemes_settings/guest_permissions_tree/__snapshots__/guest_permissions_tree.test.jsx.snap
  components/admin_console/permission_schemes_settings/guest_permissions_tree/guest_permissions_tree.jsx
  components/admin_console/permission_schemes_settings/permission_schemes_settings.jsx
  components/admin_console/permission_schemes_settings/permission_system_scheme_settings/permission_system_scheme_settings.jsx
  components/admin_console/permission_schemes_settings/permissions_tree/permissions_tree.jsx
  i18n/en.json
  utils/constants.jsx
Labels: 2: Dev Review

#5019 [MM-23103] Fix redirection after editing the channel you were just viewing
  components/admin_console/admin_console.test.tsx
  components/admin_console/admin_console.tsx
  components/admin_console/index.ts
  package-lock.json
  package.json
Labels: 3: Reviews Complete, QA Review Done

#5062 [MM-22670] - Hide tooltips in header when the dropdowns are open
  components/channel_header/components/header_icon_wrapper.js
  components/popover_list_members/popover_list_members.jsx
  components/search_bar/index.jsx
  components/search_bar/search_bar.jsx
  plugins/channel_header_plug/channel_header_plug.jsx
Labels: 3: Reviews Complete, QA Review Done

#5069 Improve E2E test duration of interactive menu by using waitUntil instead of explicit wait when posting an incoming webhook
  e2e/cypress/integration/interactive_menu/basic_options_spec.js
  e2e/cypress/support/task_commands.js
  e2e/cypress/utils/index.js
Labels: QA Review Done

#5063 [MM-22715] - Fix line-height for emojis on Catalina OS
  sass/components/_emoticons.scss
Labels: 3: Reviews Complete, QA Review Done, Setup Cloud Test Server

#5041 MM-23042: Fix select teams when there are no teams
  components/common/__snapshots__/infinite_scroll.test.js.snap
  components/common/infinite_scroll.jsx
  components/common/infinite_scroll.test.js
  components/select_team/__snapshots__/select_team.test.jsx.snap
  components/select_team/select_team.jsx
Labels: 3: Reviews Complete, QA Review Done

#5067 Fix failing tests on at mentions, keyboard shortcuts and LDAP group
  e2e/cypress/integration/at_mentions/at_mentions_spec.js
  e2e/cypress/integration/emoji/react_to_last_message_shortcut_spec.js
  e2e/cypress/integration/enterprise/system_console/groups_assign_roles_spec.js
Labels: 2: QA Review

#5055 [MM-22212] Add channel scheme websocket event
  actions/websocket_actions.jsx
  package-lock.json
  package.json
  utils/constants.jsx
Labels: 3: Reviews Complete, QA Review Done

#4690 MM-20345: Adding changes for cleanup not longer visible users to the websockets event handlers
  actions/websocket_actions.jsx
  package-lock.json
  package.json
Labels: CherryPick/Approved, QA Review Done

#5054 MM-20900 Add basic E2E tests for new sidebar
  e2e/cypress/integration/channel_sidebar/channel_sidebar_spec.js
  e2e/cypress/integration/channel_sidebar/hotkeys_spec.js
  e2e/cypress/support/api_commands.js
  e2e/cypress/support/hooks.js
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#4975 [MM-20546] Migrate mfa_section' module and associated tests to TypeScript
  components/user_settings/security/mfa_section/__snapshots__/mfa_section.test.tsx.snap
  components/user_settings/security/mfa_section/index.ts
  components/user_settings/security/mfa_section/mfa_section.test.tsx
  components/user_settings/security/mfa_section/mfa_section.tsx
Labels: 3: Reviews Complete, QA Review Done

#4292 MM-13064 Improving the keyboard usability of the emoji picker.
  components/emoji_picker/emoji_picker.jsx
  e2e/cypress/integration/messaging/emoji_picker_keyboard_usability_spec.js
Labels: 3: Reviews Complete, QA Review Done

#5074 [MM-22212] Update manage_members from server after switching channel privacy
  components/admin_console/team_channel_settings/channel/details/channel_details.tsx
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#5081 Automated cherry pick of #5074
  components/admin_console/team_channel_settings/channel/details/channel_details.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5082 [MM-23429] Fixed an issue where the new sidebar will not load with a DM with a bot
  components/sidebar/sidebar_channel/sidebar_direct_channel/sidebar_direct_channel.tsx
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#5084 Automated cherry pick of #5082
  components/sidebar/sidebar_channel/sidebar_direct_channel/sidebar_direct_channel.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5076 Automated cherry pick of #5054
  e2e/cypress/integration/channel_sidebar/channel_sidebar_spec.js
  e2e/cypress/integration/channel_sidebar/hotkeys_spec.js
  e2e/cypress/support/api_commands.js
  e2e/cypress/support/hooks.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5088 Fix failing E2E tests on channel header, profile popover and toast
  e2e/cypress/integration/channel/header_spec.js
  e2e/cypress/integration/channel/send_message_via_profile_popover_spec.js
  e2e/cypress/integration/channel/toast_spec.js
Labels: 2: QA Review

#5079 MM-23364 - Updating react select UI
  components/multiselect/__snapshots__/multiselect.test.tsx.snap
  components/multiselect/multiselect.tsx
  sass/components/_react-select.scss
Labels: 2: Dev Review, CherryPick/Approved, QA Review Done

#5035 [MM-22703] Fix channel switcher duplicate bug
  components/suggestion/switch_channel_provider.jsx
  components/suggestion/switch_channel_provider.test.jsx
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#5091 Automated cherry pick of #5079
  components/multiselect/__snapshots__/multiselect.test.tsx.snap
  components/multiselect/multiselect.tsx
  sass/components/_react-select.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5092 Automated cherry pick of #5035
  components/suggestion/switch_channel_provider.jsx
  components/suggestion/switch_channel_provider.test.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5042 [MM-23095] - Fix console error when marking system post as unread
  components/post_view/post/post.jsx
  package.json
Labels: CherryPick/Approved, QA Review Done

#5060 Added E2E Cypress test to Verify Accessibility Support in Channel Sidebar Navigation
  e2e/cypress/integration/accessibility/accessibility_sidebar_spec.js
Labels: 3: Reviews Complete, QA Review Done

#5085 Added E2E Cypress test to verify Accessibility support in Post
  e2e/cypress/integration/accessibility/accessibility_post_spec.js
Labels: 3: Reviews Complete, QA Review Done

#5080 E2E: add partial default config which aimed to not require reverting config changes
  e2e/cypress/fixtures/partial_default_config.json
  e2e/cypress/integration/accessibility/accessibility_account_settings_spec.js
  e2e/cypress/integration/emoji/react_to_last_message_shortcut_spec.js
  e2e/cypress/integration/enterprise/channels/search_channels_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/system_console_guest_access_ui_spec.js
  e2e/cypress/integration/enterprise/system_console/groups_assign_roles_spec.js
  e2e/cypress/integration/enterprise/system_console/team_and_channel_assign_roles_spec.js
  e2e/cypress/integration/enterprise/teams/invite_bot_spec.js
  e2e/cypress/integration/plugins/marketplace/marketplace_spec.js
  e2e/cypress/integration/system_console/ui_and_api/customization_spec.js
  e2e/cypress/support/api_commands.js
Labels: 2: QA Review

#5089 translations PR 20200319
  i18n/de.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 3: Reviews Complete, Tests/Not Needed

#5096 Update mattermost-redux to latest version
  package.json
Labels: 3: Reviews Complete

#5078 [MM-23447] Fixes swith teams shortcut after reorder teams feature was added
  components/legacy_team_sidebar/components/team_button.jsx
  components/legacy_team_sidebar/legacy_team_sidebar_controller.jsx
Labels: CherryPick/Approved, QA Review Done

#5083 MM-23269 - Updating bullets in header css
  sass/layout/_headers.scss
Labels: 2: Dev Review, QA Review Done

#4991 [MM-22667] - Add autocomplete="off" to emoji picker input
  components/emoji_picker/emoji_picker.jsx
Labels: QA Review Done

#5072 MM-23094: allow full screen modals to self focus
  components/widgets/modals/full_screen_modal.tsx
  e2e/cypress/integration/plugins/marketplace/marketplace_spec.js
Labels: 2: QA Review, CherryPick/Approved

#5073 MM-23366-Fix favourite channel tooltip position
  components/channel_header/__snapshots__/channel_header.test.jsx.snap
  components/channel_header/channel_header.js
Labels: QA Review Done

#5108 Automated cherry pick of #5072
  components/widgets/modals/full_screen_modal.tsx
  e2e/cypress/integration/plugins/marketplace/marketplace_spec.js
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5100 E2E: Fix daily tests on several spec files
  e2e/cypress/fixtures/partial_default_config.json
  e2e/cypress/integration/accessibility/accessibility_input_fields_spec.js
  e2e/cypress/integration/channel/channel_name_tooltips_spec.js
  e2e/cypress/integration/channel/message_reaction_spec.js
  e2e/cypress/integration/channel/send_message_via_profile_popover_spec.js
  e2e/cypress/integration/channel_sidebar/channel_sidebar_spec.js
  e2e/cypress/integration/email/mention_email_notification_spec.js
  e2e/cypress/integration/enterprise/elasticsearch/channels_spec.js
  e2e/cypress/integration/enterprise/elasticsearch/renaming_spec.js
  e2e/cypress/integration/enterprise/elasticsearch/users_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/guest_identification_ui_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/guest_invitation_ui_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/member_invitation_ui_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/system_console_guest_access_ui_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/system_console_manage_guest_spec.js
  e2e/cypress/integration/enterprise/system_console/saml_metadata_spec.js
  e2e/cypress/integration/integrations/builtin_commands/common_commands_spec.js
  e2e/cypress/integration/interactive_menu/basic_options_spec.js
  e2e/cypress/integration/messaging/permalink_message_edit_spec.js
  e2e/cypress/integration/messaging/remove_last_post_in_channel_spec.js
  e2e/cypress/integration/messaging/tooltip_visual_verification_spec.js
  e2e/cypress/integration/search/date_filter_spec.js
  e2e/cypress/integration/team/invite_members_spec.js
  e2e/cypress/support/api_commands.js
  e2e/cypress/support/hooks.js
Labels: 2: QA Review

#5104 [MM-22777] - Fix dot menu highlight on desktop app
  components/dot_menu/dot_menu.jsx
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#5097 Automated cherry pick of #5078
  components/legacy_team_sidebar/components/team_button.jsx
  components/legacy_team_sidebar/legacy_team_sidebar_controller.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5094 [MM-23428] - Check for single new lines in channel header popover
  components/channel_header/__snapshots__/channel_header.test.jsx.snap
  components/channel_header/channel_header.js
Labels: 2: Dev Review, CherryPick/Approved, QA Review Done

#5128 [MM-23538] Update redux hash to fix builds
  package-lock.json
  package.json
Labels: 3: Reviews Complete, AutoMerge, CherryPick/Approved, QA Review Done

#5130 Automated cherry pick of #5128
  package-lock.json
  package.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4978 [MM-23018] Add use_channel_mentions to system and team permission schemes
  components/admin_console/permission_schemes_settings/__snapshots__/permission_checkbox.test.jsx.snap
  components/admin_console/permission_schemes_settings/__snapshots__/permission_group.test.jsx.snap
  components/admin_console/permission_schemes_settings/__snapshots__/permission_row.test.jsx.snap
  components/admin_console/permission_schemes_settings/guest_permissions_tree/__snapshots__/guest_permissions_tree.test.jsx.snap
  components/admin_console/permission_schemes_settings/guest_permissions_tree/guest_permissions_tree.jsx
  components/admin_console/permission_schemes_settings/permission_checkbox.jsx
  components/admin_console/permission_schemes_settings/permission_checkbox.test.jsx
  components/admin_console/permission_schemes_settings/permission_group.jsx
  components/admin_console/permission_schemes_settings/permission_row.jsx
  components/admin_console/permission_schemes_settings/permission_schemes_settings.jsx
  components/admin_console/permission_schemes_settings/permission_system_scheme_settings/permission_system_scheme_settings.jsx
  components/admin_console/permission_schemes_settings/permissions_scheme_summary/__snapshots__/permissions_scheme_summary.test.jsx.snap
  components/admin_console/permission_schemes_settings/permissions_scheme_summary/permissions_scheme_summary.jsx
  components/admin_console/permission_schemes_settings/permissions_tree/__snapshots__/permissions_tree.test.jsx.snap
  components/admin_console/permission_schemes_settings/permissions_tree/permissions_tree.jsx
  components/create_comment/index.js
  components/create_post/index.js
  components/widgets/admin_console/admin_panel_with_button.test.tsx
  components/widgets/admin_console/admin_panel_with_button.tsx
  components/widgets/admin_console/admin_panel_with_link.test.tsx
  components/widgets/admin_console/admin_panel_with_link.tsx
  e2e/cypress/integration/enterprise/system_console/use_channel_mentions_system_scheme_spec.js
  e2e/cypress/integration/enterprise/system_console/use_channel_mentions_team_scheme_spec.js
  e2e/cypress/support/api_commands.js
  i18n/en.json
Labels: CherryPick/Approved, QA Review Done

#5077 [MM-22937] Fix Edge case by using includes instead of contains
  utils/utils.jsx
Labels: 3: Reviews Complete, AutoMerge, CherryPick/Approved, QA Review Done

#5133 Automated cherry pick of #5077
  utils/utils.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5131 Automated cherry pick of #4978
  components/admin_console/permission_schemes_settings/__snapshots__/permission_checkbox.test.jsx.snap
  components/admin_console/permission_schemes_settings/__snapshots__/permission_group.test.jsx.snap
  components/admin_console/permission_schemes_settings/__snapshots__/permission_row.test.jsx.snap
  components/admin_console/permission_schemes_settings/guest_permissions_tree/__snapshots__/guest_permissions_tree.test.jsx.snap
  components/admin_console/permission_schemes_settings/guest_permissions_tree/guest_permissions_tree.jsx
  components/admin_console/permission_schemes_settings/permission_checkbox.jsx
  components/admin_console/permission_schemes_settings/permission_checkbox.test.jsx
  components/admin_console/permission_schemes_settings/permission_group.jsx
  components/admin_console/permission_schemes_settings/permission_row.jsx
  components/admin_console/permission_schemes_settings/permission_schemes_settings.jsx
  components/admin_console/permission_schemes_settings/permission_system_scheme_settings/permission_system_scheme_settings.jsx
  components/admin_console/permission_schemes_settings/permissions_scheme_summary/__snapshots__/permissions_scheme_summary.test.jsx.snap
  components/admin_console/permission_schemes_settings/permissions_scheme_summary/permissions_scheme_summary.jsx
  components/admin_console/permission_schemes_settings/permissions_tree/__snapshots__/permissions_tree.test.jsx.snap
  components/admin_console/permission_schemes_settings/permissions_tree/permissions_tree.jsx
  components/create_comment/index.js
  components/create_post/index.js
  components/widgets/admin_console/admin_panel_with_button.test.tsx
  components/widgets/admin_console/admin_panel_with_button.tsx
  components/widgets/admin_console/admin_panel_with_link.test.tsx
  components/widgets/admin_console/admin_panel_with_link.tsx
  e2e/cypress/integration/enterprise/system_console/use_channel_mentions_system_scheme_spec.js
  e2e/cypress/integration/enterprise/system_console/use_channel_mentions_team_scheme_spec.js
  e2e/cypress/support/api_commands.js
  i18n/en.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5111 [MM-22877] - Fix download image button tooltip
  components/file_attachment/__snapshots__/filename_overlay.test.jsx.snap
  components/file_attachment/filename_overlay.jsx
  sass/components/_files.scss
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done, Setup Cloud Test Server

#5102 [MM-23448] - Fix drag and drop in desktop app
  components/legacy_team_sidebar/components/team_button.jsx
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done, Setup Cloud Test Server

#5086 [MM-23101] - Fix error in RHS posts with emoji
  components/rhs_comment/index.js
  components/rhs_comment/rhs_comment.jsx
  components/rhs_comment/rhs_comment.test.jsx
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#5125 Automated cherry pick of #5094
  components/channel_header/__snapshots__/channel_header.test.jsx.snap
  components/channel_header/channel_header.js
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5135 Automated cherry pick of #5111
  components/file_attachment/__snapshots__/filename_overlay.test.jsx.snap
  components/file_attachment/filename_overlay.jsx
  sass/components/_files.scss
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5118 Automated cherry pick of #5104
  components/dot_menu/dot_menu.jsx
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5106 [MM-23102] Add E2E tests + Unit tests for Channel Moderation Widget
  components/__snapshots__/autosize_textarea.test.jsx.snap
  components/admin_console/permission_schemes_settings/__snapshots__/permission_schemes_settings.test.jsx.snap
  components/admin_console/permission_schemes_settings/permission_schemes_settings.jsx
  components/admin_console/permission_schemes_settings/permissions_scheme_summary/__snapshots__/permissions_scheme_summary.test.jsx.snap
  components/admin_console/permission_schemes_settings/permissions_scheme_summary/permissions_scheme_summary.jsx
  components/admin_console/team_channel_settings/channel/details/__snapshots__/channel_moderation.test.tsx.snap
  components/admin_console/team_channel_settings/channel/details/channel_moderation.test.tsx
  components/admin_console/team_channel_settings/channel/details/channel_moderation.tsx
  components/admin_console/team_channel_settings/channel/details/channel_modes.tsx
  components/admin_console/team_channel_settings/line_switch.jsx
  components/autosize_textarea.tsx
  components/channel_members_dropdown/__snapshots__/channel_members_dropdown.test.jsx.snap
  components/channel_members_dropdown/channel_members_dropdown.jsx
  components/post_view/post_info/__snapshots__/post_info.test.jsx.snap
  components/post_view/post_info/post_info.jsx
  components/post_view/post_reaction/__snapshots__/post_reaction.test.jsx.snap
  components/post_view/post_reaction/post_reaction.jsx
  components/user_settings/notifications/__snapshots__/manage_auto_responder.test.jsx.snap
  components/widgets/admin_console/admin_panel_with_link.test.tsx
  components/widgets/admin_console/admin_panel_with_link.tsx
  components/widgets/menu/menu_items/menu_item_action.tsx
  e2e/cypress/fixtures/users.json
  e2e/cypress/integration/enterprise/system_console/channel_moderation_spec.js
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#5137 Automated cherry pick of #5106
  components/__snapshots__/autosize_textarea.test.jsx.snap
  components/admin_console/permission_schemes_settings/__snapshots__/permission_schemes_settings.test.jsx.snap
  components/admin_console/permission_schemes_settings/permission_schemes_settings.jsx
  components/admin_console/permission_schemes_settings/permissions_scheme_summary/__snapshots__/permissions_scheme_summary.test.jsx.snap
  components/admin_console/permission_schemes_settings/permissions_scheme_summary/permissions_scheme_summary.jsx
  components/admin_console/team_channel_settings/channel/details/__snapshots__/channel_moderation.test.tsx.snap
  components/admin_console/team_channel_settings/channel/details/channel_moderation.test.tsx
  components/admin_console/team_channel_settings/channel/details/channel_moderation.tsx
  components/admin_console/team_channel_settings/channel/details/channel_modes.tsx
  components/admin_console/team_channel_settings/line_switch.jsx
  components/autosize_textarea.tsx
  components/channel_members_dropdown/__snapshots__/channel_members_dropdown.test.jsx.snap
  components/channel_members_dropdown/channel_members_dropdown.jsx
  components/post_view/post_info/__snapshots__/post_info.test.jsx.snap
  components/post_view/post_info/post_info.jsx
  components/post_view/post_reaction/__snapshots__/post_reaction.test.jsx.snap
  components/post_view/post_reaction/post_reaction.jsx
  components/user_settings/notifications/__snapshots__/manage_auto_responder.test.jsx.snap
  components/widgets/admin_console/admin_panel_with_link.test.tsx
  components/widgets/admin_console/admin_panel_with_link.tsx
  components/widgets/menu/menu_items/menu_item_action.tsx
  e2e/cypress/fixtures/users.json
  e2e/cypress/integration/enterprise/system_console/channel_moderation_spec.js
  e2e/cypress/support/api_commands.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5109 MM-23458 Fix missing toast for unreads
  components/post_view/post_list_virtualized/post_list_virtualized.jsx
  components/toast_wrapper/toast_wrapper.jsx
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#5141 Automated cherry pick of #5109
  components/post_view/post_list_virtualized/post_list_virtualized.jsx
  components/toast_wrapper/toast_wrapper.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5127 [MM-23412] - Align mention and close icon horizontally
  sass/layout/_sidebar-left.scss
Labels: CherryPick/Approved, QA Review Done

#5139 Automated cherry pick of #5086
  components/rhs_comment/index.js
  components/rhs_comment/rhs_comment.jsx
  components/rhs_comment/rhs_comment.test.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5134 [MM-23445] - Fix chevron icon on Firefox
  sass/layout/_sidebar-left.scss
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#5144 Automated cherry pick of #5127
  sass/layout/_sidebar-left.scss
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5124 [No-Ticket] Update MakeFile to include make fix-style
  Makefile
Labels: 3: Reviews Complete

#5145 Automated cherry pick of #5134
  sass/layout/_sidebar-left.scss
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5110 [MM-20901] E2E tests for history arrows, channel switcher and new channel dropdown
  e2e/cypress/integration/channel_sidebar/history_channel_switcher_spec.js
  e2e/cypress/integration/channel_sidebar/new_channel_dropdown_spec.js
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#5126 [MM-23515] Unit Tests for new Experimental Sidebar
  components/sidebar/__snapshots__/sidebar.test.tsx.snap
  components/sidebar/channel_filter/__snapshots__/channel_filter.test.tsx.snap
  components/sidebar/channel_filter/channel_filter.test.tsx
  components/sidebar/sidebar.test.tsx
  components/sidebar/sidebar_category/__snapshots__/sidebar_category.test.tsx.snap
  components/sidebar/sidebar_category/sidebar_category.test.tsx
  components/sidebar/sidebar_category/sidebar_category.tsx
  components/sidebar/sidebar_category_list/__snapshots__/sidebar_category_list.test.tsx.snap
  components/sidebar/sidebar_category_list/sidebar_category_list.test.tsx
  components/sidebar/sidebar_category_list/sidebar_category_list.tsx
  components/sidebar/sidebar_channel/__snapshots__/sidebar_channel.test.tsx.snap
  components/sidebar/sidebar_channel/sidebar_base_channel/__snapshots__/sidebar_base_channel.test.tsx.snap
  components/sidebar/sidebar_channel/sidebar_base_channel/sidebar_base_channel.test.tsx
  components/sidebar/sidebar_channel/sidebar_channel.test.tsx
  components/sidebar/sidebar_channel/sidebar_channel_close.tsx
  components/sidebar/sidebar_channel/sidebar_channel_link/__snapshots__/sidebar_channel_link.test.tsx.snap
  components/sidebar/sidebar_channel/sidebar_channel_link/sidebar_channel_link.test.tsx
  components/sidebar/sidebar_channel/sidebar_direct_channel/__snapshots__/sidebar_direct_channel.test.tsx.snap
  components/sidebar/sidebar_channel/sidebar_direct_channel/sidebar_direct_channel.test.tsx
Labels: 3: Reviews Complete, CherryPick/Approved

#5146 Automated cherry pick of #5102
  components/legacy_team_sidebar/components/team_button.jsx
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5148 Automated cherry pick of #5110
  e2e/cypress/integration/channel_sidebar/history_channel_switcher_spec.js
  e2e/cypress/integration/channel_sidebar/new_channel_dropdown_spec.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5149 Automated cherry pick of #5126
  components/sidebar/__snapshots__/sidebar.test.tsx.snap
  components/sidebar/channel_filter/__snapshots__/channel_filter.test.tsx.snap
  components/sidebar/channel_filter/channel_filter.test.tsx
  components/sidebar/sidebar.test.tsx
  components/sidebar/sidebar_category/__snapshots__/sidebar_category.test.tsx.snap
  components/sidebar/sidebar_category/sidebar_category.test.tsx
  components/sidebar/sidebar_category/sidebar_category.tsx
  components/sidebar/sidebar_category_list/__snapshots__/sidebar_category_list.test.tsx.snap
  components/sidebar/sidebar_category_list/sidebar_category_list.test.tsx
  components/sidebar/sidebar_category_list/sidebar_category_list.tsx
  components/sidebar/sidebar_channel/__snapshots__/sidebar_channel.test.tsx.snap
  components/sidebar/sidebar_channel/sidebar_base_channel/__snapshots__/sidebar_base_channel.test.tsx.snap
  components/sidebar/sidebar_channel/sidebar_base_channel/sidebar_base_channel.test.tsx
  components/sidebar/sidebar_channel/sidebar_channel.test.tsx
  components/sidebar/sidebar_channel/sidebar_channel_close.tsx
  components/sidebar/sidebar_channel/sidebar_channel_link/__snapshots__/sidebar_channel_link.test.tsx.snap
  components/sidebar/sidebar_channel/sidebar_channel_link/sidebar_channel_link.test.tsx
  components/sidebar/sidebar_channel/sidebar_direct_channel/__snapshots__/sidebar_direct_channel.test.tsx.snap
  components/sidebar/sidebar_channel/sidebar_direct_channel/sidebar_direct_channel.test.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4917 MM-10272: Add count for pinned posts header icon.
  actions/websocket_actions.jsx
  components/channel_header/__snapshots__/channel_header.test.jsx.snap
  components/channel_header/channel_header.js
  components/channel_header/channel_header.test.jsx
  components/channel_header/index.js
Labels: 3: Reviews Complete, Docs/Not Needed, QA Review Done

#5132 [MM-23481] - Turn down opacity for muted channels
  components/sidebar/sidebar_channel/sidebar_channel_link/index.ts
  components/sidebar/sidebar_channel/sidebar_channel_link/sidebar_channel_link.tsx
  sass/layout/_sidebar-left.scss
Labels: CherryPick/Approved, QA Review Done

#5070 [MM-20903] Category collapsing and unread filter tests
  e2e/cypress/integration/channel_sidebar/category_collapsing_unread_filter_spec.js
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#5154 Automated cherry pick of #5070
  e2e/cypress/integration/channel_sidebar/category_collapsing_unread_filter_spec.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#5087 [MM-23414] Fix up multiselect styling
  components/multiselect/multiselect.tsx
  sass/components/_react-select.scss
Labels: AutoMerge, CherryPick/Approved, QA Review Done

#5121 MM-23492 Remove automatic scrolling to channel from new sidebar
  components/legacy_sidebar/sidebar.jsx
  components/sidebar/sidebar_category_list/sidebar_category_list.tsx
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done
