Repository mattermost/mattermost-webapp, pull requests merged in 2020-02, with the labels that each got.

#4758 MM-22075 Fix date separator
  components/recent_date.tsx
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#4814 Automated cherry pick of #4758
  components/recent_date.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4778 Export browserHistory
  plugins/export.js
Labels: 3: Reviews Complete, QA Review Done

#4802 edits to defaultMessage in components
  components/activity_log_modal/components/__snapshots__/activity_log.test.jsx.snap
  components/activity_log_modal/components/activity_log.jsx
  components/admin_console/admin_navbar_dropdown/admin_navbar_dropdown.jsx
  components/admin_console/system_user_detail/team_list/team_list_dropdown.jsx
  components/channel_members_dropdown/__snapshots__/channel_members_dropdown.test.jsx.snap
  components/channel_members_dropdown/channel_members_dropdown.jsx
  components/channel_members_modal/__snapshots__/channel_members_modal.test.jsx.snap
  components/channel_members_modal/channel_members_modal.jsx
  components/claim/components/email_to_ldap.jsx
  components/claim/components/email_to_oauth.jsx
  components/claim/components/oauth_to_email.jsx
  components/error_page/error_page.tsx
  components/help/components/attaching.tsx
  components/help/components/commands.tsx
  components/help/components/composing.tsx
  components/help/components/mentioning.tsx
  components/help/components/messaging.tsx
  components/integrations/__snapshots__/abstract_command.test.jsx.snap
  components/integrations/abstract_command.jsx
  components/integrations/bots/add_bot/add_bot.jsx
  components/integrations/installed_commands/installed_commands.jsx
  components/integrations/installed_incoming_webhooks/installed_incoming_webhooks.jsx
  components/login/login_controller/login_controller.jsx
  components/main_menu/__snapshots__/main_menu.test.jsx.snap
  components/main_menu/main_menu.jsx
  components/more_channels/__snapshots__/more_channels.test.jsx.snap
  components/more_channels/more_channels.jsx
  components/new_channel_modal/__snapshots__/new_channel_modal.test.jsx.snap
  components/new_channel_modal/new_channel_modal.jsx
  components/post_view/post_list_row/__snapshots__/post_list_row.test.jsx.snap
  components/post_view/post_list_row/post_list_row.jsx
  components/system_notice/__snapshots__/system_notice.test.jsx.snap
  components/system_notice/system_notice.jsx
  components/team_sidebar/team_sidebar_controller.jsx
  components/tutorial/tutorial_intro_screens/__snapshots__/tutorial_intro_screen.test.jsx.snap
  components/tutorial/tutorial_intro_screens/tutorial_intro_screens.jsx
  components/user_settings/security/mfa_section/__snapshots__/mfa_section.test.jsx.snap
  components/user_settings/security/mfa_section/mfa_section.jsx
  components/user_settings/security/user_access_token_section/user_access_token_section.jsx
  components/user_settings/security/user_settings_security.jsx
  plugins/test/__snapshots__/main_menu_action.test.jsx.snap
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#4817 Automated cherry pick of #4802
  components/activity_log_modal/components/__snapshots__/activity_log.test.jsx.snap
  components/activity_log_modal/components/activity_log.jsx
  components/admin_console/admin_navbar_dropdown/admin_navbar_dropdown.jsx
  components/admin_console/system_user_detail/team_list/team_list_dropdown.jsx
  components/channel_members_dropdown/__snapshots__/channel_members_dropdown.test.jsx.snap
  components/channel_members_dropdown/channel_members_dropdown.jsx
  components/channel_members_modal/__snapshots__/channel_members_modal.test.jsx.snap
  components/channel_members_modal/channel_members_modal.jsx
  components/claim/components/email_to_ldap.jsx
  components/claim/components/email_to_oauth.jsx
  components/claim/components/oauth_to_email.jsx
  components/error_page/error_page.tsx
  components/help/components/attaching.jsx
  components/help/components/commands.jsx
  components/help/components/composing.jsx
  components/help/components/mentioning.jsx
  components/help/components/messaging.jsx
  components/integrations/__snapshots__/abstract_command.test.jsx.snap
  components/integrations/abstract_command.jsx
  components/integrations/bots/add_bot/add_bot.jsx
  components/integrations/installed_commands/installed_commands.jsx
  components/integrations/installed_incoming_webhooks/installed_incoming_webhooks.jsx
  components/login/login_controller/login_controller.jsx
  components/main_menu/__snapshots__/main_menu.test.jsx.snap
  components/main_menu/main_menu.jsx
  components/more_channels/__snapshots__/more_channels.test.jsx.snap
  components/more_channels/more_channels.jsx
  components/new_channel_modal/__snapshots__/new_channel_modal.test.jsx.snap
  components/new_channel_modal/new_channel_modal.jsx
  components/post_view/post_list_row/__snapshots__/post_list_row.test.jsx.snap
  components/post_view/post_list_row/post_list_row.jsx
  components/system_notice/__snapshots__/system_notice.test.jsx.snap
  components/system_notice/system_notice.jsx
  components/team_sidebar/team_sidebar_controller.jsx
  components/tutorial/tutorial_intro_screens/__snapshots__/tutorial_intro_screen.test.jsx.snap
  components/tutorial/tutorial_intro_screens/tutorial_intro_screens.jsx
  components/user_settings/security/mfa_section/__snapshots__/mfa_section.test.jsx.snap
  components/user_settings/security/mfa_section/mfa_section.jsx
  components/user_settings/security/user_access_token_section/user_access_token_section.jsx
  components/user_settings/security/user_settings_security.jsx
  plugins/test/__snapshots__/main_menu_action.test.jsx.snap
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4774 [MM-21739] Improve UX and modify wording for guest access change
  components/admin_console/__snapshots__/custom_enable_disable_guest_accounts_setting.test.tsx.snap
  components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
  components/admin_console/custom_enable_disable_guest_accounts_setting.test.tsx
  components/admin_console/custom_enable_disable_guest_accounts_setting.tsx
  components/admin_console/custom_plugin_settings/__snapshots__/custom_plugin_settings.test.jsx.snap
  components/admin_console/schema_admin_settings.jsx
  i18n/en.json
  sass/routes/_admin-console.scss
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#4771 MM-22042 Only scroll RHS to bottom when current user posts
  components/rhs_thread/rhs_thread.jsx
  components/rhs_thread/rhs_thread.test.jsx
Labels: 3: Reviews Complete, QA Review Done

#4794 Added testcase for Manage Guest Users & Guest access screen
  e2e/cypress/integration/enterprise/guest_accounts/system_console_guest_access_ui_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/system_console_manage_guest_spec.js
Labels: QA Review Done

#4800 Fix member invitation ui spec
  e2e/cypress/integration/enterprise/guest_accounts/member_invitation_ui_spec.js
Labels: 3: Reviews Complete, QA Review Done

#4798 Fix guest invitation ui spec
  e2e/cypress/integration/enterprise/guest_accounts/guest_invitation_ui_spec.js
Labels: 3: Reviews Complete, AutoMerge, QA Review Done

#4719 [MM-20531] Migrate 'components/notify_counts' module to TypeScript
  components/notify_counts/index.ts
  components/notify_counts/notify_counts.tsx
Labels: 3: Reviews Complete, QA Review Done

#4809 MM-20169 Fix incorrect escaping of translation strings
  components/help/components/formatting.tsx
  components/message_submit_error.tsx
  i18n/en.json
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#4810 Migrate leave_team_modal to typescript
  components/leave_team_modal/__snapshots__/leave_team_modal.test.tsx.snap
  components/leave_team_modal/index.ts
  components/leave_team_modal/leave_team_modal.test.tsx
  components/leave_team_modal/leave_team_modal.tsx
Labels: 3: Reviews Complete, QA Review Done

#4824 Automated cherry pick of #4809
  components/help/components/formatting.jsx
  components/message_submit_error.tsx
  i18n/en.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4732 [MM-18975] Migrate 'components/confirm_modal.jsx' to TypeScript
  components/admin_console/custom_enable_disable_guest_accounts_setting.tsx
  components/admin_console/data_retention_settings.jsx
  components/admin_console/group_settings/group_details/group_teams_and_channels_row.jsx
  components/admin_console/permission_schemes_settings/permission_system_scheme_settings/permission_system_scheme_settings.jsx
  components/admin_console/permission_schemes_settings/permissions_scheme_summary/permissions_scheme_summary.jsx
  components/admin_console/permission_schemes_settings/permissions_scheme_summary/permissions_scheme_summary.test.jsx
  components/admin_console/plugin_management/plugin_management.jsx
  components/admin_console/system_user_detail/system_user_detail.jsx
  components/admin_console/system_users/system_users.jsx
  components/admin_console/system_users/system_users_dropdown/system_users_dropdown.jsx
  components/admin_console/team_channel_settings/convert_and_remove_confirm_modal.jsx
  components/admin_console/team_channel_settings/convert_confirm_modal.jsx
  components/admin_console/team_channel_settings/remove_confirm_modal.jsx
  components/confirm_modal.test.tsx
  components/confirm_modal.tsx
  components/create_comment/create_comment.jsx
  components/create_post/create_post.jsx
  components/delete_modal_trigger.jsx
  components/delete_modal_trigger.test.jsx
  components/discard_changes_modal.tsx
  components/integrations/bots/bot.jsx
  components/integrations/edit_command/edit_command.jsx
  components/integrations/edit_oauth_app/edit_oauth_app.jsx
  components/integrations/edit_outgoing_webhook/edit_outgoing_webhook.jsx
  components/invitation_modal/invitation_modal.jsx
  components/leave_private_channel_modal/leave_private_channel_modal.tsx
  components/plugin_marketplace/marketplace_item/marketplace_item.js
  components/plugin_marketplace/marketplace_item/marketplace_item.test.js
  components/reset_status_modal/reset_status_modal.jsx
  components/team_groups_manage_modal/team_groups_manage_modal.jsx
  components/team_members_dropdown/team_members_dropdown.jsx
  components/team_selector_modal/team_selector_modal.jsx
  components/user_settings/advanced/user_settings_advanced.jsx
  components/user_settings/modal/user_settings_modal.jsx
  components/user_settings/security/user_access_token_section/user_access_token_section.jsx
Labels: 3: Reviews Complete, QA Review Done, Setup Cloud Test Server

#4777 MM-22024: Allow to disable link generate while using FormattedMarkdonwText
  components/__snapshots__/formatted_markdown_message.test.jsx.snap
  components/formatted_markdown_message.jsx
  components/formatted_markdown_message.test.jsx
  components/widgets/inputs/users_emails_input.jsx
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#4828 Automated cherry pick of #4777
  components/__snapshots__/formatted_markdown_message.test.jsx.snap
  components/formatted_markdown_message.jsx
  components/formatted_markdown_message.test.jsx
  components/widgets/inputs/users_emails_input.jsx
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4813 Fix basic options spec
  e2e/cypress/integration/interactive_menu/basic_options_spec.js
  e2e/cypress/support/task_commands.js
Labels: 3: Reviews Complete, QA Review Done

#4818 MM-21247 - Adding tooltip for plugins button
  plugins/channel_header_plug/__snapshots__/channel_header_plug.test.jsx.snap
  plugins/channel_header_plug/channel_header_plug.jsx
Labels: 2: QA Review, 3: Reviews Complete

#4745 Migrate 'file_attachment/file_thumbnail' module and tests to TypeScript
  components/file_attachment/file_thumbnail/__snapshots__/file_thumbnail.test.tsx.snap
  components/file_attachment/file_thumbnail/file_thumbnail.test.tsx
  components/file_attachment/file_thumbnail/file_thumbnail.tsx
  components/file_attachment/file_thumbnail/index.ts
Labels: 3: Reviews Complete, QA Review Done

#4811 [MM-21911] Moved favicon and titlebar update to its own component
  components/channel_layout/channel_controller.jsx
  components/favicon_title_handler/favicon_title_handler.test.jsx
  components/favicon_title_handler/favicon_title_handler.tsx
  components/favicon_title_handler/index.ts
  components/legacy_sidebar/sidebar.jsx
  components/legacy_sidebar/sidebar.test.jsx
Labels: 2: Dev Review

#4760 [MM-21870] Default help text for "Invite People” should not wrap to another line
  components/widgets/menu/menu_items/menu_item.scss
  components/widgets/menu/menu_items/menu_item_link.test.tsx
  components/widgets/menu/menu_items/menu_item_link.tsx
  sass/layout/_headers.scss
Labels: CherryPick/Approved, QA Review Done, Setup Cloud Test Server

#4835 Fix scroll channel messages spec
  e2e/cypress/integration/channel/scroll_channel_messages_spec.js
Labels: 3: Reviews Complete, QA Review Done

#4748 MM-21948 Add test to RootPortal and open up possibility to test other components that render as children of it
  components/__snapshots__/root_portal.test.jsx.snap
  components/root_portal.test.jsx
Labels: 3: Reviews Complete, AutoMerge, QA Review Done

#4836 Automated cherry pick of #4760
  components/widgets/menu/menu_items/menu_item.scss
  components/widgets/menu/menu_items/menu_item_link.test.tsx
  components/widgets/menu/menu_items/menu_item_link.tsx
  sass/layout/_headers.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4789 Add 'Close Group Message' option to Group Message menu
  components/channel_header_dropdown/__snapshots__/channel_header_dropdown.test.jsx.snap
  components/channel_header_dropdown/channel_header_dropdown_items.js
  components/channel_header_dropdown/menu_items/close_direct_channel/__snapshots__/close_direct_channel.test.js.snap
  components/channel_header_dropdown/menu_items/close_direct_channel/close_direct_channel.test.js
  components/channel_header_dropdown/menu_items/close_message/__snapshots__/close_message.test.js.snap
  components/channel_header_dropdown/menu_items/close_message/close_message.js
  components/channel_header_dropdown/menu_items/close_message/close_message.test.js
  components/channel_header_dropdown/menu_items/close_message/index.js
  i18n/en.json
Labels: 3: Reviews Complete, QA Review Done

#4841 MM-22233 Fix 2 byte character drafts not being cleared
  components/create_post/create_post.jsx
Labels: CherryPick/Approved, QA Review Done

#4840 MM-22311 Fix JS crash when leaving all teams
  components/sidebar/sidebar.jsx
Labels: CherryPick/Approved, QA Review Done

#4842 Automated cherry pick of #4841
  components/create_post/create_post.jsx
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4845 Automated cherry pick of #4840
  components/sidebar/sidebar.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4827 MM-21933 Do not show toast when a channel is marked as unread and at bottom
  components/toast_wrapper/toast_wrapper.jsx
  components/toast_wrapper/toast_wrapper.test.jsx
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done, Setup Cloud Test Server

#4660 MM 20562 -Migrate 'components/admin_console/admin_navbar_dropdown' module and associated tests to TypeScript
  components/admin_console/admin_navbar_dropdown/admin_navbar_dropdown.tsx
  components/admin_console/admin_navbar_dropdown/index.ts
  components/admin_console/admin_navbar_dropdown/menu_item_blockable_link.test.tsx
  components/admin_console/admin_navbar_dropdown/menu_item_blockable_link.tsx
  components/admin_console/blockable_link/blockable_link.tsx
Labels: 3: Reviews Complete, QA Review Done

#4849 Automated cherry pick of #4827
  components/toast_wrapper/toast_wrapper.jsx
  components/toast_wrapper/toast_wrapper.test.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4820 [MM-21517] Team manage members modal update role after it changes for users other than yourself
  components/member_list_team/index.ts
  components/member_list_team/member_list_team.tsx
Labels: 3: Reviews Complete, QA Review Done

#4822 [MM-22147] Fix code block copying line numbers
  sass/layout/_markdown.scss
  utils/syntax_highlighting.tsx
Labels: 3: Reviews Complete, QA Review Done, Setup Cloud Test Server

#4848 MM-22199 Disable scrolling to channel on switch
  components/sidebar/sidebar.jsx
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#4862 Fix marketplace spec
  e2e/cypress/integration/plugins/marketplace/marketplace_spec.js
Labels: 3: Reviews Complete, QA Review Done

#4861 Fix post header spec
  e2e/cypress/integration/post_header/post_header_spec.js
  e2e/cypress/support/ui_commands.js
Labels: 3: Reviews Complete, QA Review Done

#4858 Fix forgot password spec
  e2e/cypress/integration/signin_authentication/forgot_password_spec.js
Labels: 3: Reviews Complete, QA Review Done

#4857 Fix teams spec
  e2e/cypress/integration/team/teams_spec.js
Labels: 3: Reviews Complete, QA Review Done

#4854 Fix timeout issues
  e2e/cypress/integration/channel/send_message_via_profile_popover_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/guest_invitation_ui_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/member_invitation_ui_spec.js
Labels: 3: Reviews Complete, QA Review Done

#4831 Showing the demote-to-guest action only when you have a license
  components/admin_console/system_users/system_users_dropdown/__snapshots__/system_users_dropdown.test.js.snap
  components/admin_console/system_users/system_users_dropdown/index.js
  components/admin_console/system_users/system_users_dropdown/system_users_dropdown.jsx
  components/admin_console/system_users/system_users_dropdown/system_users_dropdown.test.js
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#4855 MM-22351: Fix users/emails autocompletion when user emails is not available
  components/widgets/inputs/channels_input.jsx
  components/widgets/inputs/users_emails_input.jsx
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#4853 MM-22346: Fix open new added team
  components/needs_team/needs_team.jsx
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#4866 Automated cherry pick of #4855
  components/widgets/inputs/channels_input.jsx
  components/widgets/inputs/users_emails_input.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4867 Automated cherry pick of #4853
  components/needs_team/needs_team.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4865 Automated cherry pick of #4831
  components/admin_console/system_users/system_users_dropdown/__snapshots__/system_users_dropdown.test.js.snap
  components/admin_console/system_users/system_users_dropdown/index.js
  components/admin_console/system_users/system_users_dropdown/system_users_dropdown.jsx
  components/admin_console/system_users/system_users_dropdown/system_users_dropdown.test.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4776 Update dependencies.
  Makefile
  package-lock.json
  package.json
Labels: 3: Reviews Complete, Setup Cloud Test Server

#4850 MM-22326 Fix non-DM/GM autocomplete in search box
  components/suggestion/search_channel_provider.jsx
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#4869 Automated cherry pick of #4850
  components/suggestion/search_channel_provider.jsx
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4856 Automated cherry pick of #4848
  components/sidebar/sidebar.jsx
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4728 MM-21924: Enforces the 'create_post' permission to make channels act …
  components/create_comment/__snapshots__/create_comment.test.jsx.snap
  components/create_comment/create_comment.jsx
  components/create_comment/create_comment.test.jsx
  components/create_comment/index.js
  components/create_post/__snapshots__/create_post.test.jsx.snap
  components/create_post/create_post.jsx
  components/create_post/create_post.test.jsx
  components/create_post/index.js
  e2e/cypress/integration/channel/create_post_permission_spec.js
  e2e/cypress/support/api_commands.js
  package-lock.json
Labels: 3: Reviews Complete, QA Review Done

#4868 [MM-21542] Fix Cypress test report
  e2e/run_tests.js
Labels: 3: Reviews Complete, QA Review Done

#4844 MM-22191: Fix the mentions that get attached in a list
  utils/markdown/index.test.js
  utils/markdown/renderer.tsx
Labels: 2: QA Review, CherryPick/Approved, Tests/Not Needed

#4872 Automated cherry pick of #4844
  utils/markdown/index.test.js
  utils/markdown/renderer.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4870 Changes to handle a recent change done for toast not to appear when the bottom is in view
  e2e/cypress/integration/channel/toast_spec.js
Labels: 3: Reviews Complete, QA Review Done

#4871 Fix plugin upload spec
  e2e/cypress/integration/system_console/plugin_upload_spec.js
Labels: 3: Reviews Complete, QA Review Done

#4874 MM-21542 Add New Commits to Cypress Test Report
  e2e/run_tests.js
Labels: 3: Reviews Complete, QA Review Done

#4833 MM-22289 Fix for toast appearing when scrolled up
  components/post_view/post_list_virtualized/post_list_virtualized.jsx
  components/post_view/post_list_virtualized/post_list_virtualized.test.jsx
  components/post_view/scroll_to_bottom_arrows.jsx
  components/toast_wrapper/toast_wrapper.jsx
  components/toast_wrapper/toast_wrapper.test.jsx
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done, Setup Cloud Test Server

#4882 Automated cherry pick of #4833
  components/post_view/post_list_virtualized/post_list_virtualized.jsx
  components/post_view/post_list_virtualized/post_list_virtualized.test.jsx
  components/post_view/scroll_to_bottom_arrows.jsx
  components/toast_wrapper/toast_wrapper.jsx
  components/toast_wrapper/toast_wrapper.test.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4876 MM-22327 Fix search autocomplete not closing after typing selection
  components/suggestion/search_user_provider.jsx
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#4884 Automated cherry pick of #4876
  components/suggestion/search_user_provider.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4821 [MM-21909] Keyboard shortcuts and a11y-controller classes
  components/sidebar/sidebar_category/sidebar_category.tsx
  components/sidebar/sidebar_category_list/index.ts
  components/sidebar/sidebar_category_list/sidebar_category_list.tsx
  components/sidebar/sidebar_header/sidebar_header.tsx
Labels: 3: Reviews Complete

#4819 MM-22017 Fix Markdown component not respecting mentionHighlight flag
  components/at_mention/at_mention.jsx
  components/markdown/markdown.jsx
  utils/__snapshots__/message_html_to_component.test.jsx.snap
  utils/message_html_to_component.jsx
  utils/message_html_to_component.test.jsx
Labels: 3: Reviews Complete, QA Review Done

#4834 [MM-22108] Don't redirect to landing page when already on a landing link for mobile
  components/linking_landing_page/linking_landing_page.tsx
  components/root/root.jsx
Labels: 3: Reviews Complete, QA Review Done, Setup Cloud Test Server

#4879 translations PR 20200211
  i18n/de.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 3: Reviews Complete, QA Review Done

#4787 [MM-21920] Enforce use_channel_mentions permissions
  components/__snapshots__/textbox.test.jsx.snap
  components/admin_console/reset_password_modal/reset_password_modal.test.tsx
  components/create_comment/__snapshots__/create_comment.test.jsx.snap
  components/create_comment/create_comment.jsx
  components/create_comment/create_comment.test.jsx
  components/create_comment/index.js
  components/create_post/__snapshots__/create_post.test.jsx.snap
  components/create_post/create_post.jsx
  components/create_post/create_post.test.jsx
  components/create_post/index.js
  components/suggestion/at_mention_provider/at_mention_provider.jsx
  components/suggestion/at_mention_provider/at_mention_provider.test.jsx
  components/textbox.test.jsx
  components/textbox/textbox.jsx
  package-lock.json
  package.json
Labels: QA Review Done

#4888 Fix failing tests on channel mention and profile popover
  e2e/cypress/integration/channel/channel_mention_autocomplete_spec.js
  e2e/cypress/integration/channel/send_message_via_profile_popover_spec.js
Labels: 3: Reviews Complete

#4886 Mm 22430 - Regression &nbsp should not display
  components/admin_console/team_channel_settings/group/__snapshots__/group_users_row.test.tsx.snap
  components/admin_console/team_channel_settings/group/group_users_row.tsx
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#4889 Automated cherry pick of #4886
  components/admin_console/team_channel_settings/group/__snapshots__/group_users_row.test.tsx.snap
  components/admin_console/team_channel_settings/group/group_users_row.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4738 Migrating SystemUsersDropdown to typescript
  components/admin_console/system_users/system_users_dropdown/__snapshots__/system_users_dropdown.test.tsx.snap
  components/admin_console/system_users/system_users_dropdown/index.ts
  components/admin_console/system_users/system_users_dropdown/system_users_dropdown.test.tsx
  components/admin_console/system_users/system_users_dropdown/system_users_dropdown.tsx
  components/permissions_gates/system_permission_gate/system_permission_gate.jsx
  utils/test_helper.ts
Labels: 2: Dev Review, 2: QA Review

#4887 Fix failing test on channel switcher
  e2e/cypress/integration/account_settings/sidebar/channel_switcher_spec.js
  e2e/cypress/integration/account_settings/sidebar/channel_switcher_ui_spec.js
Labels: QA Review Done

#4899 HotFix : Added missing types to test_helper
  utils/test_helper.ts
Labels: 3: Reviews Complete, QA Review Done

#4616 MM:20563 migrate audits to typescript
  components/admin_console/audits/audits.jsx
  components/admin_console/audits/audits.tsx
  components/admin_console/audits/index.js
  components/admin_console/audits/index.ts
Labels: 3: Reviews Complete, QA Review Done

#4894 Fix message reply input box expand spec
  e2e/cypress/integration/messaging/message_reply_input_box_expand_spec.js
Labels: 3: Reviews Complete, QA Review Done

#4895 Fix ephemeral verification
  e2e/cypress/integration/interactive_menu/basic_options_spec.js
Labels: 3: Reviews Complete, QA Review Done

#4892 Fix customization spec
  e2e/cypress/integration/system_console/ui_and_api/customization_spec.js
Labels: 3: Reviews Complete, QA Review Done

#4837 [GH-13729] Migrate 'components/channel_members_modal' module and associated tests to TypeScript
  components/channel_members_modal/__snapshots__/channel_members_modal.test.tsx.snap
  components/channel_members_modal/channel_members_modal.test.tsx
  components/channel_members_modal/channel_members_modal.tsx
  components/channel_members_modal/index.js
  components/channel_members_modal/index.ts
  components/member_list_channel/index.ts
  components/member_list_channel/member_list_channel.tsx
Labels: 3: Reviews Complete, QA Review Done

#4863 [GH-13346] Write an automated test using Cypress for "Using up/down keys to make a selection from SEARCH results"
  e2e/cypress/integration/interactive_menu/select_with_keys_spec.js
Labels: 3: Reviews Complete, QA Review Done

#4904 E2E: Ensure user is on suggestion list before doing verification
  e2e/cypress/integration/account_settings/general/fullname_spec.js
Labels: 3: Reviews Complete, QA Review Done

#4896 Fix file upload in center channel spec
  e2e/cypress/integration/messaging/file_upload_in_center_channel_spec.js
Labels: 3: Reviews Complete, QA Review Done

#4864 MM-22027: Removes 'on the next AD/LDAP synchronization' from the mess…
  components/admin_console/team_channel_settings/channel/details/__snapshots__/channel_groups.test.tsx.snap
  components/admin_console/team_channel_settings/channel/details/channel_groups.tsx
  components/admin_console/team_channel_settings/convert_and_remove_confirm_modal.jsx
  components/admin_console/team_channel_settings/remove_confirm_modal.jsx
  components/team_groups_manage_modal/team_groups_manage_modal.jsx
  i18n/en.json
Labels: 1: PM Review, 3: Reviews Complete, QA Review Done

#4829 MM-21857: Add Cypress test support for SAML auth(Okta)
  e2e/cypress.json
  e2e/cypress.okta.json
  e2e/cypress/extensions/Ignore-X-Frame-headers/background.js
  e2e/cypress/extensions/Ignore-X-Frame-headers/manifest.json
  e2e/cypress/fixtures/saml_users.json
  e2e/cypress/integration/enterprise/saml/okta_login_spec.js
  e2e/cypress/plugins/index.js
  e2e/cypress/plugins/okta_request.js
  e2e/cypress/support/index.js
  e2e/cypress/support/okta_commands.js
  e2e/cypress/support/saml_commands.js
Labels: 3: Reviews Complete, QA Review Done

#4717 MM-18062 - add support for Office365Settings Directory (tenant) Id
  components/admin_console/admin_definition.jsx
  i18n/en.json
Labels: 3: Reviews Complete, QA Review Done

#4905 E2E: Fix channel switcher and draw plugin
  e2e/cypress/integration/account_settings/sidebar/channel_switcher_spec.js
  e2e/cypress/integration/messaging/message_channel_draw_spec.js
  e2e/cypress/integration/system_console/plugin_upload_spec.js
  e2e/cypress/support/api_commands.js
  e2e/cypress/support/ui_commands.js
Labels: 3: Reviews Complete, QA Review Done

#4909 Added step to run LDAP Sync before running tests related to Groups
  components/admin_console/jobs/table.jsx
  e2e/cypress/integration/enterprise/system_console/channel_modes_spec.js
  e2e/cypress/integration/enterprise/system_console/groups_assign_roles_spec.js
  e2e/cypress/integration/enterprise/system_console/team_and_channel_asign_roles_spec.js
  e2e/cypress/support/api_commands.js
  e2e/cypress/support/ui_commands.js
Labels: 3: Reviews Complete, QA Review Done

#4885 MM-22081: fix various PropTypes issues
  components/channel_header/channel_header.js
  components/channel_header/components/header_icon_wrapper.js
  components/search_results_header/search_results_header.jsx
  components/widgets/menu/menu_items/menu_item.tsx
Labels: 3: Reviews Complete, QA Review Done

#4843 MM-22038: removing deactivate users from open private channels without private messages with me
  components/more_direct_channels/__snapshots__/more_direct_channels.test.jsx.snap
  components/more_direct_channels/index.js
  components/more_direct_channels/more_direct_channels.jsx
  components/more_direct_channels/more_direct_channels.test.jsx
Labels: CherryPick/Approved, QA Review Done

#4747 MM-20577 - Migrate 'components/admin_console/system_user_detail/team_list' module and associated tests to TypeScript
  components/admin_console/system_user_detail/team_list/__snapshots__/abstract_list.test.tsx.snap
  components/admin_console/system_user_detail/team_list/__snapshots__/team_list.test.tsx.snap
  components/admin_console/system_user_detail/team_list/abstract_list.test.tsx
  components/admin_console/system_user_detail/team_list/abstract_list.tsx
  components/admin_console/system_user_detail/team_list/index.ts
  components/admin_console/system_user_detail/team_list/team_image.tsx
  components/admin_console/system_user_detail/team_list/team_list.test.tsx
  components/admin_console/system_user_detail/team_list/team_list.tsx
  components/admin_console/system_user_detail/team_list/team_list_dropdown.tsx
  components/admin_console/system_user_detail/team_list/team_row.tsx
Labels: 3: Reviews Complete, QA Review Done

#3165 [MM-13160] Add infinite scroll to Select Teams screen
  components/common/__snapshots__/infinite_scroll.test.js.snap
  components/common/infinite_scroll.jsx
  components/common/infinite_scroll.test.js
  components/select_team/__snapshots__/select_team.test.jsx.snap
  components/select_team/index.js
  components/select_team/select_team.jsx
  components/select_team/select_team.test.jsx
  sass/components/_infinite-scroll.scss
  sass/components/_module.scss
  sass/responsive/_mobile.scss
  sass/routes/_signup.scss
Labels: 3: Reviews Complete, QA Review Done

#4921 Cherry pick of #4820
  components/admin_console/team_channel_settings/group/group_list.tsx
  components/member_list_team/index.js
  components/member_list_team/member_list_team.jsx
  components/widgets/admin_console/admin_panel.tsx
Labels: Changelog/Not Needed, Docs/Not Needed

#4919 Automated cherry pick of #4720
  sass/components/_popover.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4815 M16735 Replying to an older bot post that has no post content and no attachment pretext
  e2e/cypress/integration/channel/message_reply_bot_post_spec.js
Labels: 3: Reviews Complete, QA Review Done

#4770 MM-19954 Always open external images in a new tab
  components/view_image/__snapshots__/view_image.test.jsx.snap
  components/view_image/image_preview.jsx
  components/view_image/image_preview.test.jsx
  components/view_image/popover_bar/__snapshots__/popover_bar.test.jsx.snap
  components/view_image/popover_bar/index.js
  components/view_image/popover_bar/popover_bar.jsx
  components/view_image/popover_bar/popover_bar.test.jsx
  components/view_image/view_image.test.jsx
Labels: CherryPick/Approved, QA Review Done

#4925 Automated cherry pick of #4770
  components/view_image/__snapshots__/view_image.test.jsx.snap
  components/view_image/image_preview.jsx
  components/view_image/image_preview.test.jsx
  components/view_image/popover_bar/__snapshots__/popover_bar.test.jsx.snap
  components/view_image/popover_bar/index.js
  components/view_image/popover_bar/popover_bar.jsx
  components/view_image/popover_bar/popover_bar.test.jsx
  components/view_image/view_image.test.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4918 Fixing margin typo
  sass/utils/_modifiers.scss
Labels: 2: Dev Review, 2: QA Review

#4826 Migrate removed_from_channel_modal to typescript
  components/removed_from_channel_modal/__snapshots__/removed_from_channel_modal.test.tsx.snap
  components/removed_from_channel_modal/index.ts
  components/removed_from_channel_modal/removed_from_channel_modal.test.tsx
  components/removed_from_channel_modal/removed_from_channel_modal.tsx
Labels: 3: Reviews Complete, QA Review Done

#4791 [MM-21000] Fix using local storage to return to a DM/GM
  actions/global_actions.jsx
  actions/global_actions.test.js
Labels: 2: Dev Review, AutoMerge, CherryPick/Approved, QA Review Done

#4901 [MM-22137] - Make RHS comment dropdown open down by default
  components/dot_menu/dot_menu.jsx
Labels: CherryPick/Approved, QA Review Done, Setup Cloud Test Server

#4891 [MM-22389] Refactor adminResetPassword action to adhere to redux thun…
  actions/admin_actions.jsx
  components/admin_console/reset_password_modal/index.ts
  components/admin_console/reset_password_modal/reset_password_modal.test.tsx
  components/admin_console/reset_password_modal/reset_password_modal.tsx
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#4932 Automated cherry pick of #4834
  components/linking_landing_page/linking_landing_page.tsx
  components/root/root.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4933 Automated cherry pick of #4822
  sass/layout/_markdown.scss
  utils/syntax_highlighting.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4935 Automated cherry pick of #4819
  components/at_mention/at_mention.jsx
  components/markdown/markdown.jsx
  utils/__snapshots__/message_html_to_component.test.jsx.snap
  utils/message_html_to_component.jsx
  utils/message_html_to_component.test.jsx
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4945 MM-21224: System console shows wrong authentication method (#4600)
  components/admin_console/system_user_detail/__snapshots__/system_user_detail.test.jsx.snap
  components/admin_console/system_user_detail/index.js
  components/admin_console/system_user_detail/system_user_detail.jsx
  components/admin_console/system_user_detail/system_user_detail.test.jsx
  i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed

#4936 Automated cherry pick of #4771
  components/rhs_thread/rhs_thread.jsx
  components/rhs_thread/rhs_thread.test.jsx
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4823 Added Cypress test to verify Invite via Email containing upper case letters
  e2e/cypress/integration/enterprise/guest_accounts/guest_invitation_ui_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/member_invitation_ui_spec.js
Labels: 3: Reviews Complete, QA Review Done

#4912 [MM-22204] - Add target="_blank" to terms and policy links
  components/signup/signup_email/signup_email.jsx
Labels: 2: Dev Review, 2: QA Review, CherryPick/Approved

#4942 Automated cherry pick of #4901
  components/dot_menu/dot_menu.jsx
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4943 Automated cherry pick of #4891
  actions/admin_actions.jsx
  components/admin_console/reset_password_modal/index.ts
  components/admin_console/reset_password_modal/reset_password_modal.test.tsx
  components/admin_console/reset_password_modal/reset_password_modal.tsx
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4948 Automated cherry pick of #4912
  components/signup/signup_email/signup_email.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4930 [MM-22129] - Remove post link modal and copy permalink directly
  actions/global_actions.jsx
  components/channel_layout/channel_controller.jsx
  components/dot_menu/__snapshots__/dot_menu.test.jsx.snap
  components/dot_menu/dot_menu.jsx
  components/dot_menu/dot_menu.test.jsx
  components/dot_menu/dot_menu_empty.test.jsx
  components/dot_menu/dot_menu_mobile.test.jsx
  components/dot_menu/index.js
  components/get_post_link_modal/__snapshots__/get_post_link_modal.test.tsx.snap
  components/get_post_link_modal/get_post_link_modal.test.tsx
  components/get_post_link_modal/get_post_link_modal.tsx
  components/get_post_link_modal/index.ts
  i18n/de.json
  i18n/en.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
  stores/modal_store.jsx
  utils/constants.jsx
Labels: 1: UX Review, 2: Dev Review, 2: QA Review, Setup Cloud Test Server

#4947 Add latest mattermost-redux version
  package-lock.json
  package.json
Labels: 2: Dev Review, QA Review Done

#4873 [MM-22290] Collapsible Category Logic
  components/sidebar/sidebar_category/index.ts
  components/sidebar/sidebar_category/sidebar_category.tsx
  components/sidebar/sidebar_category_list/sidebar_category_list.tsx
  components/sidebar/sidebar_channel/index.ts
  components/sidebar/sidebar_channel/sidebar_channel.tsx
  sass/layout/_legacy-sidebar-left.scss
  sass/layout/_module.scss
  sass/layout/_sidebar-left.scss
Labels: 3: Reviews Complete

#4859 MM-22079 Properly capture emoji sequences
  utils/text_formatting.test.jsx
  utils/text_formatting.tsx
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#4953 Automated cherry pick of #4859
  utils/text_formatting.test.jsx
  utils/text_formatting.tsx
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4838 MM-22590 Fix messages
  components/admin_console/system_user_detail/system_user_detail.jsx
  components/integrations/bots/add_bot/add_bot.jsx
  components/user_settings/notifications/__snapshots__/desktop_notification_settings.test.jsx.snap
  components/user_settings/notifications/desktop_notification_settings.jsx
  i18n/en.json
Labels: 2: Dev Review, QA Review Done

#4877 Update en.json
  i18n/en.json
Labels: 3: Reviews Complete, AutoMerge

#4955 translations PR 20200225
  i18n/de.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 3: Reviews Complete

#4478 Fixes #9506 : Keyboard shortcut for adding reactions to last message in channel or thread
  actions/post_actions.jsx
  components/create_comment/create_comment.jsx
  components/create_comment/index.js
  components/create_post/create_post.jsx
  components/create_post/index.js
  components/post_view/post/post.jsx
  components/post_view/post_header/post_header.jsx
  components/post_view/post_info/index.js
  components/post_view/post_info/post_info.jsx
  components/post_view/post_info/post_info.test.jsx
  components/post_view/post_list/post_list.jsx
  components/post_view/post_list_row/index.js
  components/post_view/post_list_row/post_list_row.jsx
  components/post_view/post_list_virtualized/post_list_virtualized.jsx
  components/rhs_comment/index.js
  components/rhs_comment/rhs_comment.jsx
  components/rhs_comment/rhs_comment.test.jsx
  components/rhs_root_post/index.js
  components/rhs_root_post/rhs_root_post.jsx
  components/rhs_root_post/rhs_root_post.test.jsx
  components/rhs_thread/__snapshots__/rhs_thread.test.jsx.snap
  components/rhs_thread/rhs_thread.jsx
  components/shortcuts_modal.jsx
  e2e/cypress/fixtures/messages.js
  e2e/cypress/integration/emoji/react_to_last_message_shortcut_spec.js
  e2e/cypress/utils/index.js
  i18n/en.json
  package-lock.json
  reducers/views/emoji.js
  selectors/emojis.js
  utils/constants.jsx
Labels: 3: Reviews Complete, QA Review Done

#4934 Automated cherry pick of #4843
  components/more_direct_channels/__snapshots__/more_direct_channels.test.jsx.snap
  components/more_direct_channels/index.js
  components/more_direct_channels/more_direct_channels.jsx
  components/more_direct_channels/more_direct_channels.test.jsx
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4941 Automated cherry pick of #4791
  actions/global_actions.jsx
  actions/global_actions.test.js
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4908 MM-22309 - Updating marketplace modal css
  components/plugin_marketplace/__snapshots__/marketplace_modal.test.js.snap
  components/plugin_marketplace/marketplace_modal.js
  components/plugin_marketplace/marketplace_modal.scss
  components/widgets/modals/full_screen_modal.scss
  utils/utils.jsx
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#4960 Automated cherry pick of #4908
  components/plugin_marketplace/__snapshots__/marketplace_modal.test.js.snap
  components/plugin_marketplace/marketplace_modal.js
  components/plugin_marketplace/marketplace_modal.scss
  components/widgets/modals/full_screen_modal.scss
  utils/utils.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4957 Promote Dutch and Russian to Beta, v5.22
  components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
  i18n/i18n.jsx
Labels: 3: Reviews Complete

#4458 [MM-12330] Add "Unarchive Channel" option to archived channels menu
  actions/websocket_actions.jsx
  components/channel_header_dropdown/__snapshots__/channel_header_dropdown.test.jsx.snap
  components/channel_header_dropdown/channel_header_dropdown_items.js
  components/post_markdown/system_message_helpers.jsx
  components/unarchive_channel_modal/__snapshots__/unarchive_channel_modal.test.jsx.snap
  components/unarchive_channel_modal/index.js
  components/unarchive_channel_modal/unarchive_channel_modal.jsx
  components/unarchive_channel_modal/unarchive_channel_modal.test.jsx
  i18n/en.json
  package-lock.json
  utils/constants.jsx
Labels: 3: Reviews Complete, AutoMerge, QA Review Done

#4875 [MM-22294] Fixed the use of handleUploadError on create_comment
  components/create_comment/create_comment.jsx
  components/create_comment/create_comment.test.jsx
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#4961 Automated cherry pick of #4875
  components/create_comment/create_comment.jsx
  components/create_comment/create_comment.test.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4522 MM-19755 Add landmark roles
  components/channel_header/__snapshots__/channel_header.test.jsx.snap
  components/channel_header/channel_header.js
  components/create_comment/__snapshots__/create_comment.test.jsx.snap
  components/create_comment/create_comment.jsx
  components/create_post/__snapshots__/create_post.test.jsx.snap
  components/create_post/create_post.jsx
  components/post_view/post_view.jsx
  components/sidebar/__snapshots__/sidebar.test.jsx.snap
  components/sidebar/sidebar.jsx
  components/sidebar_right/sidebar_right.jsx
  components/team_sidebar/team_sidebar_controller.jsx
Labels: 3: Reviews Complete, QA Review Done

#4962 MM-22634: Add Team Name back to team list
  components/admin_console/permission_schemes_settings/permission_team_scheme_settings/team_in_list/__snapshots__/team_in_list.test.jsx.snap
  components/admin_console/permission_schemes_settings/permission_team_scheme_settings/team_in_list/team_in_list.jsx
  components/admin_console/permission_schemes_settings/permission_team_scheme_settings/team_in_list/team_in_list.test.jsx
Labels: 3: Reviews Complete, CherryPick/Approved, QA Review Done

#4964 Automated cherry pick of #4962
  components/admin_console/permission_schemes_settings/permission_team_scheme_settings/team_in_list/__snapshots__/team_in_list.test.jsx.snap
  components/admin_console/permission_schemes_settings/permission_team_scheme_settings/team_in_list/team_in_list.jsx
  components/admin_console/permission_schemes_settings/permission_team_scheme_settings/team_in_list/team_in_list.test.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#4940 Change message for invite code in team settings
  components/team_general_tab/team_general_tab.jsx
  i18n/en.json
Labels: 2: Dev Review, QA Review Done

#4846 [MM-20594] Migrate components/more_direct_channels to TypeScript
  actions/user_actions.jsx
  components/admin_console/reset_password_modal/reset_password_modal.test.tsx
  components/more_direct_channels/__snapshots__/more_direct_channels.test.jsx.snap
  components/more_direct_channels/group_message_option.tsx
  components/more_direct_channels/index.ts
  components/more_direct_channels/more_direct_channels.test.jsx
  components/more_direct_channels/more_direct_channels.tsx
  components/multiselect/multiselect.test.tsx
  components/multiselect/multiselect.tsx
  components/multiselect/multiselect_list.tsx
Labels: QA Review Done

#4847 [MM-21910] Modal Handling for new Sidebar
  components/sidebar/add_channel_dropdown/add_channel_dropdown.tsx
  components/sidebar/add_channel_dropdown/index.ts
  components/sidebar/index.ts
  components/sidebar/sidebar.tsx
  components/sidebar/sidebar_category/sidebar_category.tsx
  components/sidebar/sidebar_category_list/sidebar_category_list.tsx
  i18n/en.json
Labels: 3: Reviews Complete

#4946 [MM-22310] Remove back button when user has no accounts
  components/signup/signup_email/index.js
  components/signup/signup_email/signup_email.jsx
Labels: 2: Dev Review, QA Review Done
