Repository mattermost/mattermost-webapp, pull requests merged in 2020-11, with the labels that each got.

#6831 [MM-T662] Add e2e test for /join command
  e2e/cypress/integration/integrations/slash_commands_spec.js
Labels: 4: Reviews Complete, AutoMerge, Hacktoberfest, hacktoberfest-accepted

#6827 [GH-13486] Migrate 'components/admin_console/manage_tokens_modal' module and associated tests to TypeScript
  components/admin_console/manage_tokens_modal/__snapshots__/manage_tokens_modal.test.tsx.snap
  components/admin_console/manage_tokens_modal/index.js
  components/admin_console/manage_tokens_modal/index.ts
  components/admin_console/manage_tokens_modal/manage_tokens_modal.test.tsx
  components/admin_console/manage_tokens_modal/manage_tokens_modal.tsx
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#6935 [MM-30193] change file attachment info to show fractions below 10
  utils/utils.jsx
Labels: 4: Reviews Complete

#7000 [MM-20196] Use UTC timezone for formattedDate so it doesn't change the date
  components/admin_console/billing/billing_history.tsx
  components/admin_console/billing/billing_summary.tsx
Labels: 4: Reviews Complete

#7001 [MM-30127] Make invoice.tax a boolean so a rogue 0 isn't rendered
  components/admin_console/billing/billing_summary.tsx
Labels: 2: Dev Review

#7003 Automated cherry pick of #7001
  components/admin_console/billing/billing_summary.tsx
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#6986 Campaign/applytheme center channel color
  sass/responsive/_desktop.scss
  utils/utils.jsx
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#7004 Automated cherry pick of #7000
  components/admin_console/billing/billing_history.tsx
  components/admin_console/billing/billing_summary.tsx
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#6985 MM-30177: Migrate changeCSS() to CSS variable '.app__body .input-grou…
  sass/routes/_settings.scss
  utils/utils.jsx
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#6955 [MM-30066] Allow sidebar category button width to grow and shrink as needed
  sass/layout/_sidebar-left.scss
Labels: 4: Reviews Complete

#6914 Migrate team_list and team_row to typescript
  components/admin_console/team_channel_settings/team/list/__snapshots__/team_list.test.tsx.snap
  components/admin_console/team_channel_settings/team/list/__snapshots__/team_row.test.tsx.snap
  components/admin_console/team_channel_settings/team/list/index.ts
  components/admin_console/team_channel_settings/team/list/team_list.test.tsx
  components/admin_console/team_channel_settings/team/list/team_list.tsx
  components/admin_console/team_channel_settings/team/list/team_row.test.tsx
  components/admin_console/team_channel_settings/team/list/team_row.tsx
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#6729 [MM-20482] Migrate 'components/post_view/channel_intro_message' module …
  components/post_view/channel_intro_message/channel_intro_message.tsx
  components/post_view/channel_intro_message/index.ts
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#6933 [MM-29836] Migrate changeCSS() to CSS variable in utils/utils.jsx, ln. 693
  utils/utils.jsx
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#6905 MM-28843 Adding feature flags to system console for easy diagnosis.
  components/admin_console/admin_definition.jsx
  components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.jsx.snap
  components/admin_console/feature_flags.tsx
  i18n/en.json
Labels: 4: Reviews Complete

#6881 [MM-29850] Migrate string-refs to functional ones: this.refs.errorMessage
  components/admin_console/system_user_detail/system_user_detail.jsx
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#7012 [MM-30190] Show spinner when loading invoices instead of 'no invoices found'
  components/admin_console/billing/billing_history.scss
  components/admin_console/billing/billing_history.tsx
Labels: 4: Reviews Complete

#7013 Automated cherry pick of #7012
  components/admin_console/billing/billing_history.scss
  components/admin_console/billing/billing_history.tsx
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#6884 [MM-T560] Add test for notifications
  e2e/cypress/fixtures/favicon-16x16.png
  e2e/cypress/fixtures/favicon-default-16x16.png
  e2e/cypress/fixtures/favicon-mentions-16x16.png
  e2e/cypress/fixtures/favicon-unread-16x16.png
  e2e/cypress/integration/notifications/browser_tab_notification_spec.js
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#6738 MM-20492 Migrate 'components/post_view/post_message_view' module and …
  components/post_view/post_message_view/__snapshots__/post_message_view.test.tsx.snap
  components/post_view/post_message_view/index.ts
  components/post_view/post_message_view/post_message_view.test.tsx
  components/post_view/post_message_view/post_message_view.tsx
  plugins/test/__snapshots__/post_type.test.jsx.snap
  plugins/test/post_type.test.jsx
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#7011 Cypress/E2E: Fix custom categories spec
  e2e/cypress/integration/channel_sidebar/custom_categories_spec.js
Labels: 4: Reviews Complete

#6774 [MM-20465] migrate single_image_view to typescript
  components/single_image_view/__snapshots__/single_image_view.test.tsx.snap
  components/single_image_view/index.ts
  components/single_image_view/single_image_view.test.tsx
  components/single_image_view/single_image_view.tsx
  components/view_image/view_image.jsx
  utils/test_helper.ts
Labels: 2: Dev Review, 3: QA Review, Hacktoberfest, hacktoberfest-accepted

#6920 [MM-29903] - Check if current user is on last post when scrolling in rhs
  components/rhs_thread/__snapshots__/rhs_thread.test.tsx.snap
  components/rhs_thread/rhs_thread.tsx
Labels: 2: Dev Review, 3: QA Review, CherryPick/Approved, Setup Cloud Test Server

#6993 [MM-30173] Migrate changeCSS() to CSS variable in utils/utils.jsx, ln. 707
  sass/components/_popover.scss
  utils/utils.jsx
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#6992 [MM-30174] Migrate changeCSS() to CSS variable in utils/utils.jsx, ln. 708
  sass/components/_popover.scss
  utils/utils.jsx
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#6873 MM-T614 Search on Outgoing Webhooks page
  e2e/cypress/integration/integrations/outgoing_webhook/search_on_outgoing_webhooks_spec.js
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#7010 Cypress/E2E: Move cluster spec to enterprise
  e2e/cypress/integration/enterprise/system_console/cluster_spec.js
Labels: 4: Reviews Complete

#6801 MM-20578 Migrate 'components/admin_console/system_user_detail' module…
  components/admin_console/system_user_detail/__snapshots__/system_user_detail.test.tsx.snap
  components/admin_console/system_user_detail/index.js
  components/admin_console/system_user_detail/index.ts
  components/admin_console/system_user_detail/system_user_detail.test.tsx
  components/admin_console/system_user_detail/system_user_detail.tsx
  components/admin_console/system_user_detail/team_list/team_list.tsx
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#6829 [MM-20568] Migrate 'components/admin_console/system_users' module to ts
  components/admin_console/system_users/__snapshots__/system_users.test.tsx.snap
  components/admin_console/system_users/index.ts
  components/admin_console/system_users/list/system_users_list.tsx
  components/admin_console/system_users/system_users.test.tsx
  components/admin_console/system_users/system_users.tsx
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#7023 MM-30258 Fixing title text in select team icon.
  components/admin_console/admin_navbar_dropdown/admin_navbar_dropdown.tsx
Labels: 4: Reviews Complete, CherryPick/Approved

#7026 Automated cherry pick of #7023
  components/admin_console/admin_navbar_dropdown/admin_navbar_dropdown.tsx
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7024 MM-30090 Open managed resource links in a new tab
  components/admin_console/admin_definition.jsx
  components/markdown/index.ts
  components/markdown/markdown.tsx
  i18n/en.json
  package-lock.json
  package.json
  utils/markdown/index.test.js
  utils/markdown/renderer.tsx
  utils/text_formatting.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, Docs/Done

#6704 migrate string-refs in user_list.jsx
  components/__snapshots__/user_list.test.jsx.snap
  components/user_list.jsx
  components/user_list.test.jsx
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#6991 [MM-30172] Migrate changeCSS() to CSS variable in utils/utils.jsx, ln. 706
  sass/components/_buttons.scss
  utils/utils.jsx
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#7016 [MM-T556] Add e2e test for MM-T556
  e2e/cypress/fixtures/favicon-mentions-16x16.png
  e2e/cypress/integration/notifications/browser_tab_notification_spec.js
Labels: 4: Reviews Complete

#6572 MM-24505-Update-help-text-leave-team-modal
  components/leave_team_modal/__snapshots__/leave_team_modal.test.tsx.snap
  components/leave_team_modal/index.ts
  components/leave_team_modal/leave_team_modal.test.tsx
  components/leave_team_modal/leave_team_modal.tsx
  i18n/en.json
Labels: 4: Reviews Complete, QA Review Done

#7028 MM-29929 Fix for unread messages toast on marking channel as unread
  components/toast_wrapper/toast_wrapper.jsx
  components/toast_wrapper/toast_wrapper.test.jsx
Labels: 4: Reviews Complete, CherryPick/Approved

#7032 Automated cherry pick of #7028
  components/toast_wrapper/toast_wrapper.jsx
  components/toast_wrapper/toast_wrapper.test.jsx
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#6904 [MM-26386] - Respect user locale when searching for channels
  components/suggestion/search_channel_provider.jsx
Labels: 4: Reviews Complete, QA Review Done

#6629 [MM-25186] Bot username validation i8n support
  components/integrations/bots/add_bot/add_bot.jsx
  components/signup/signup_email/signup_email.jsx
  components/user_settings/general/user_settings_general.tsx
  i18n/en.json
  utils/constants.jsx
  utils/utils.jsx
  utils/utils.test.jsx
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#6865 Migrate String Refs to Functional ones - MM 16039
  components/admin_console/remove_file_setting.jsx
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#7008 MM-29849/MM-29942/MM-29982 Fix code theme not being applied
  utils/utils.jsx
Labels: 4: Reviews Complete

#6619 Convert 'components/post_view/post_info' module and associated tests to TypeScript
  .eslintrc.json
  actions/command.js
  actions/new_post.test.js
  actions/new_post.ts
  actions/post_actions.test.js
  actions/views/channel.js
  actions/views/profile_popover.js
  components/add_users_to_team_modal/add_users_to_team_modal.test.tsx
  components/data_prefetch/data_prefetch.test.tsx
  components/data_prefetch/data_prefetch.tsx
  components/data_prefetch/index.ts
  components/dot_menu/dot_menu.jsx
  components/markdown/markdown.test.tsx
  components/needs_team/index.ts
  components/needs_team/needs_team.test.tsx
  components/needs_team/needs_team.tsx
  components/new_channel_flow/index.ts
  components/permalink_view/index.js
  components/post_view/channel_intro_message/index.ts
  components/post_view/post_body/index.js
  components/post_view/post_info/__snapshots__/post_info.test.tsx.snap
  components/post_view/post_info/index.ts
  components/post_view/post_info/post_info.test.tsx
  components/post_view/post_info/post_info.tsx
  components/post_view/post_reaction/post_reaction.test.tsx
  components/post_view/post_reaction/post_reaction.tsx
  components/profile_popover/index.js
  components/select_team/__snapshots__/select_team.test.tsx.snap
  components/select_team/components/__snapshots__/select_team_item.test.tsx.snap
  components/sidebar/index.ts
  components/sidebar/sidebar_channel/index.ts
  components/sidebar/sidebar_channel/sidebar_channel_icon/index.ts
  components/sidebar/sidebar_channel/sidebar_direct_channel/index.ts
  components/sidebar/sidebar_channel/sidebar_group_channel/index.ts
  components/sidebar/sidebar_channel_list/index.ts
  components/sidebar/sidebar_channel_list/sidebar_channel_list.test.tsx
  components/sidebar/sidebar_channel_list/sidebar_channel_list.tsx
  components/team_members_dropdown/index.ts
  selectors/views/channel_sidebar.test.js
  selectors/views/channel_sidebar.ts
Labels: 4: Reviews Complete, Hacktoberfest, QA Review Done, hacktoberfest-accepted

#7020 [MM-30183] - No more text decoration on hover and focus
  components/post_view/post_time/post_time.jsx
  sass/components/_post.scss
Labels: 4: Reviews Complete

#6645 [MM-20470] Migrate emoji page and any team permission gate to typescript #15470
  components/emoji/delete_emoji_modal.test.tsx
  components/emoji/delete_emoji_modal.tsx
  components/emoji/emoji_list_item/emoji_list_item.jsx
  components/emoji/emoji_page.tsx
  components/emoji/index.ts
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#7031 [MM-30226][MM-39255] Allow a post to be sent when you do CMD + ENTER on Mac with 'Allow all messages' to be sent via CMD + ENTER
  components/edit_post_modal/edit_post_modal.jsx
  components/edit_post_modal/edit_post_modal.test.jsx
Labels: 4: Reviews Complete

#7039 [MM-30340] Update post height when comment box height change occurs
  components/create_comment/create_comment.jsx
  components/rhs_thread/__snapshots__/rhs_thread.test.tsx.snap
  components/rhs_thread/rhs_thread.tsx
Labels: 4: Reviews Complete, AutoMerge, CherryPick/Approved, QA Review Done, Setup Cloud Test Server

#7044 Automated cherry pick of #7039
  components/create_comment/create_comment.jsx
  components/rhs_thread/__snapshots__/rhs_thread.test.tsx.snap
  components/rhs_thread/rhs_thread.tsx
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7009 [MM-28181] e2e: add system_console/unsaved_changes_spec
  e2e/cypress/integration/system_console/unsaved_changes_spec.js
Labels: 4: Reviews Complete

#6824 15474 convert team selector modal to ts
  components/post_view/commented_on/commented_on.test.tsx
  components/rhs_thread/rhs_thread.test.tsx
  components/team_selector_modal/__snapshots__/team_selector_modal.test.tsx.snap
  components/team_selector_modal/index.ts
  components/team_selector_modal/team_selector_modal.test.tsx
  components/team_selector_modal/team_selector_modal.tsx
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#7002 MM-19509 Prioritize autocomplete results based on interactions and threads
  actions/views/channel.js
  components/__snapshots__/textbox.test.tsx.snap
  components/suggestion/at_mention_provider/at_mention_provider.jsx
  components/suggestion/at_mention_provider/at_mention_provider.test.jsx
  components/textbox.test.tsx
  components/textbox/index.ts
  components/textbox/textbox.tsx
  package-lock.json
  package.json
Labels: 4: Reviews Complete

#6799 Add E2E test for desktop notifications for empty strings
  e2e/cypress/integration/notifications/desktop_notifications_spec.js
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#6938 Apply Theme center-channel-color to .shadow--2
  components/system_notice/__snapshots__/system_notice.test.jsx.snap
  components/system_notice/system_notice.jsx
  sass/components/_system-notice.scss
  utils/utils.jsx
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#7034 MM-20433 - convert view_pinned_posts to typescript
  components/channel_header_dropdown/menu_items/view_pinned_posts/__snapshots__/view_pinned_posts.test.tsx.snap
  components/channel_header_dropdown/menu_items/view_pinned_posts/index.ts
  components/channel_header_dropdown/menu_items/view_pinned_posts/view_pinned_posts.test.tsx
  components/channel_header_dropdown/menu_items/view_pinned_posts/view_pinned_posts.tsx
Labels: 4: Reviews Complete

#7052 Cypress/E2E: fix test
  e2e/cypress.json
  e2e/cypress/integration/enterprise/cloud/onboarding/cloud_sysadmin_onboarding_spec.js
  e2e/cypress/integration/enterprise/cloud/onboarding/finish_tutorial_spec.js
  e2e/cypress/support/api/system.d.ts
  e2e/cypress/support/api/system.js
Labels: 4: Reviews Complete

#6867 [MM-29855] Migrate string-refs to functional ones: this.refs.content
  components/admin_console/permission_schemes_settings/permission_description.jsx
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#6901 [MM-27231]: e2e for T1880 - deleted token cannot be used to post
  e2e/cypress/integration/bot_accounts/token_spec.js
  e2e/cypress/integration/enterprise/system_console/reporting/site_statistics_spec.js
  e2e/cypress/integration/mark_as_unread/bot_post_mark_as_unread_spec.js
  e2e/cypress/integration/messaging/message_reply_bot_post_spec.js
  e2e/cypress/support/api/user.d.ts
  e2e/cypress/support/api/user.js
  e2e/cypress/support/api_commands.js
  e2e/cypress/support/index.d.ts
Labels: 4: Reviews Complete

#7061 MM-29933 Fix menu rendering behind input box in RHS.
  components/rhs_thread/__snapshots__/rhs_thread.test.tsx.snap
  components/rhs_thread/rhs_thread.tsx
Labels: 3: QA Review, CherryPick/Approved, Setup Cloud Test Server

#7065 Automated cherry pick of #7061
  components/rhs_thread/__snapshots__/rhs_thread.test.tsx.snap
  components/rhs_thread/rhs_thread.tsx
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#6518 [MM-27708] Disable Plugin on Removal
  e2e/cypress/integration/plugins/upgrade_spec.js
Labels: 4: Reviews Complete

#7063 [MM-30104][MM-30105] Fix up banners in payment_info and billing_subscription pages
  components/admin_console/billing/billing_subscriptions.tsx
  components/admin_console/billing/payment_info.tsx
  utils/cloud_utils.ts
Labels: 2: Dev Review

#6529 [MM-27556] UI For new system roles
  components/admin_console/admin_definition.jsx
  components/admin_console/data_grid/data_grid.test.tsx
  components/admin_console/data_grid/data_grid.tsx
  components/admin_console/data_grid/data_grid_search.tsx
  components/admin_console/member_list_group/__snapshots__/member_list_group.test.tsx.snap
  components/admin_console/member_list_group/member_list_group.tsx
  components/admin_console/system_roles/index.tsx
  components/admin_console/system_roles/system_role/add_users_to_role_modal/add_users_to_role_modal.tsx
  components/admin_console/system_roles/system_role/add_users_to_role_modal/index.tsx
  components/admin_console/system_roles/system_role/index.tsx
  components/admin_console/system_roles/system_role/system_role.tsx
  components/admin_console/system_roles/system_role/system_role_permission.tsx
  components/admin_console/system_roles/system_role/system_role_permission_dropdown.tsx
  components/admin_console/system_roles/system_role/system_role_permissions.scss
  components/admin_console/system_roles/system_role/system_role_permissions.tsx
  components/admin_console/system_roles/system_role/system_role_users/index.tsx
  components/admin_console/system_roles/system_role/system_role_users/system_role_users.tsx
  components/admin_console/system_roles/system_role/types.ts
  components/admin_console/system_roles/system_roles.scss
  components/admin_console/system_roles/system_roles.tsx
  components/admin_console/team_channel_settings/channel/details/channel_members/__snapshots__/channel_members.test.tsx.snap
  components/admin_console/team_channel_settings/channel/details/channel_members/channel_members.tsx
  components/admin_console/team_channel_settings/channel/list/__snapshots__/channel_list.test.tsx.snap
  components/admin_console/team_channel_settings/channel/list/channel_list.tsx
  components/admin_console/team_channel_settings/group/group_users/__snapshots__/users_to_remove.test.tsx.snap
  components/admin_console/team_channel_settings/group/group_users/users_to_remove.tsx
  components/admin_console/team_channel_settings/team/details/team_members/__snapshots__/team_members.test.tsx.snap
  components/admin_console/team_channel_settings/team/details/team_members/team_members.tsx
  components/admin_console/team_channel_settings/team/list/__snapshots__/team_list.test.tsx.snap
  components/admin_console/team_channel_settings/team/list/team_list.tsx
  components/admin_console/user_grid/__snapshots__/user_grid.test.tsx.snap
  components/admin_console/user_grid/user_grid.test.tsx
  components/admin_console/user_grid/user_grid.tsx
  i18n/en.json
  package-lock.json
  package.json
  selectors/admin_console.jsx
  utils/constants.jsx
Labels: 4: Reviews Complete

#6965 [MM-20428] Migrate terms of service to Typescript
  components/terms_of_service/__snapshots__/terms_of_service.test.tsx.snap
  components/terms_of_service/index.js
  components/terms_of_service/index.ts
  components/terms_of_service/terms_of_service.test.tsx
  components/terms_of_service/terms_of_service.tsx
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#7067 [MM-29621] Only load the stripe library when cloud components are actually rendered
  components/admin_console/billing/payment_info_edit.tsx
  components/purchase_modal/purchase_modal.tsx
Labels: 4: Reviews Complete, QA Review Done

#6969 MM-20412: Migrate 'components/channel_header_mobile/show_search_button' module to TypeScript
  components/channel_header_mobile/show_search_button/index.ts
  components/channel_header_mobile/show_search_button/show_search_button.tsx
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#6976 MM 20404 Migrate 'components/announcement_bar/version_bar' module and associated tests to TypeScript
  components/announcement_bar/version_bar/__snapshots__/version_bar.test.tsx.snap
  components/announcement_bar/version_bar/index.ts
  components/announcement_bar/version_bar/version_bar.test.tsx
  components/announcement_bar/version_bar/version_bar.tsx
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#7018 Migrate changeCSS() to CSS variable in utils/utils.jsx, ln. 702 #16173
  sass/layout/_headers.scss
  utils/utils.jsx
Labels: 4: Reviews Complete

#6990 [MM-30175] Migrate changeCSS() to CSS variable in utils/utils.jsx, ln. 709
  sass/components/_popover.scss
  utils/utils.jsx
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#6994 [MM-30171] Migrate changeCSS() to CSS variable in utils/utils.jsx, ln. 705
  sass/components/_popover.scss
  utils/utils.jsx
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#6772 MM-27229 - Cypress/E2E: Automate backlogs - BOT Accounts - Part 06 (10 test cases)
  e2e/cypress/integration/bot_accounts/bot_api_spec.js
  e2e/cypress/integration/bot_accounts/managing_bot_accounts_spec.js
  e2e/cypress/support/api/user.d.ts
  e2e/cypress/support/api/user.js
  e2e/cypress/support/api_commands.js
Labels: 4: Reviews Complete

#6754 migrate refs icon_url. #15801
  components/integrations/abstract_oauth_app.jsx
Labels: 4: Reviews Complete, AutoMerge, Hacktoberfest, hacktoberfest-accepted

#6866 [GH-16035] Migrating refs plugin_management.tsx
  components/admin_console/plugin_management/plugin_management.tsx
Labels: 4: Reviews Complete, AutoMerge, Hacktoberfest, hacktoberfest-accepted

#7069 [MM-29515] Hide imports tab when in cloud installation
  components/team_settings_modal/index.ts
  components/team_settings_modal/team_settings_modal.test.tsx
  components/team_settings_modal/team_settings_modal.tsx
Labels: 2: Dev Review, QA Review Done

#7054 MM-T446 DM More... searching from page 2 of user list
  e2e/cypress/integration/multi_team_and_dm/dm_more_searching_from_page_2_spec.js
Labels: 4: Reviews Complete

#7084 [No Ticket] Update to latest redux hash and fixing test cases with missing types
  components/admin_console/team_channel_settings/channel/details/channel_moderation.test.tsx
  components/sidebar/sidebar_category/__snapshots__/sidebar_category.test.tsx.snap
  components/sidebar/sidebar_category/sidebar_category.test.tsx
  components/sidebar/sidebar_category/sidebar_category_menu/sidebar_category_menu.test.tsx
  components/sidebar/sidebar_channel/sidebar_channel_menu/sidebar_channel_menu.test.tsx
  components/sidebar/sidebar_channel_list/__snapshots__/sidebar_channel_list.test.tsx.snap
  components/sidebar/sidebar_channel_list/sidebar_channel_list.test.tsx
  package-lock.json
  package.json
Labels: 4: Reviews Complete, AutoMerge

#6977 [MM-27154] Cypress tests: Incoming Webhooks
  e2e/cypress/integration/enterprise/integrations/incoming_webhook_spec.js
  e2e/cypress/integration/integrations/incoming_webhook/slack_formatting_spec.js
Labels: 4: Reviews Complete

#7077 Cypress/E2E: Fix failing tests due to announcement bar
  e2e/cypress/integration/integrations/integrations_spec.js
  e2e/cypress/integration/plugins/marketplace/marketplace_spec.js
  e2e/cypress/support/ui/announcement_bar.d.ts
  e2e/cypress/support/ui/announcement_bar.js
  e2e/cypress/support/ui/index.js
Labels: 4: Reviews Complete

#6909 MM-27315 Cypress tests for Integrations > Slash command auto-complete (7 test cases)
  e2e/cypress/integration/slash_commands/autocomplete_spec.js
Labels: 4: Reviews Complete

#7051 MM-30359: Cypress/E2E: Account Settings > Email
  e2e/cypress/integration/account_settings/general/email_spec.js
Labels: 4: Reviews Complete

#7015 [MM-T561] Add e2e test for MM-T561
  e2e/cypress/integration/notifications/direct_messages_do_not_add_indicator_spec.js
Labels: 4: Reviews Complete

#7071 Fix alignment when no icon is provided in post actions
  components/dot_menu/dot_menu.tsx
Labels: 4: Reviews Complete

#6558 [MM-28255] Add tests for OAuth Apps
  e2e/cypress/integration/enterprise/oauth/oauth_spec.js
  e2e/cypress/integration/enterprise/system_console/channel_moderation/constants.js
  e2e/package-lock.json
  e2e/package.json
  e2e/webhook_serve.js
Labels: 4: Reviews Complete

#6885 MM-29858: Migrate string refs to functional ones in autosize textarea component
  components/autosize_textarea.tsx
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#6882 Migrate errorMessage string ref
  components/admin_console/__snapshots__/bleve_settings.test.jsx.snap
  components/admin_console/__snapshots__/cluster_settings.test.jsx.snap
  components/admin_console/__snapshots__/elasticsearch_settings.test.jsx.snap
  components/admin_console/__snapshots__/message_export_settings.test.jsx.snap
  components/admin_console/admin_settings.tsx
  components/admin_console/custom_terms_of_service_settings/__snapshots__/custom_terms_of_service_settings.test.tsx.snap
  components/admin_console/plugin_management/__snapshots__/plugin_management.test.tsx.snap
Labels: AutoMerge, Hacktoberfest, hacktoberfest-accepted

#7005 MM-T329 Image link preview
  e2e/cypress/integration/files_and_attachments/image_link_preview_new_window_spec.js
Labels: 4: Reviews Complete

#7045 [MM-28150] e2e: add MM-T924, MM-T928, MM-T929, MM-T930
  e2e/cypress/integration/system_console/user_management_spec.js
Labels: 4: Reviews Complete, AutoMerge

#7073 MM-30363: Cypress/E2E: Automate backlogs - Edit Bot Username (1 test case)
  e2e/cypress/integration/bot_accounts/edit_bot_username_spec.js
Labels: 4: Reviews Complete, AutoMerge

#7080 Cypress/E2E: Promote and demote tests to/from prod
  e2e/cypress/integration/archived_channel/archive_channel_member_spec.js
  e2e/cypress/integration/archived_channel/archive_channel_post_spec.js
  e2e/cypress/integration/archived_channel/archive_channel_reaction_spec.js
  e2e/cypress/integration/archived_channel/post_menu_spec.js
  e2e/cypress/integration/bot_accounts/bot_api_spec.js
  e2e/cypress/integration/bot_accounts/crud_spec.js
  e2e/cypress/integration/bot_accounts/managing_bot_accounts_spec.js
  e2e/cypress/integration/channel_sidebar/unread_filter_spec.js
  e2e/cypress/integration/emoji/custom_emoji_spec.js
  e2e/cypress/integration/enterprise/bot_accounts/managing_bot_accounts_spec.js
  e2e/cypress/integration/enterprise/group_mentions/group_mentions_system_messages_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/guest_feature_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/guest_identification_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/system_console_guest_access_ui_spec.js
  e2e/cypress/integration/enterprise/profile_popover/profile_popover_spec.js
  e2e/cypress/integration/enterprise/system_console/about/edition_and_license_spec.js
  e2e/cypress/integration/enterprise/system_console/channel_members_spec.js
  e2e/cypress/integration/enterprise/system_console/cluster_spec.js
  e2e/cypress/integration/enterprise/system_console/main_menu_spec.js
  e2e/cypress/integration/enterprise/system_console/reporting/site_statistics_spec.js
  e2e/cypress/integration/enterprise/system_console/search_box_spec.js
  e2e/cypress/integration/files_and_attachments/upload_files_spec.js
  e2e/cypress/integration/integrations/builtin_commands/common_commands_spec.js
  e2e/cypress/integration/integrations/incoming_webhook/cancel_out_of_edit_spec.js
  e2e/cypress/integration/integrations/incoming_webhook/description_length_check_spec.js
  e2e/cypress/integration/integrations/incoming_webhook/disallow_username_profile_override_spec.js
  e2e/cypress/integration/integrations/incoming_webhook/integrations_display_on_team_where_created_spec.js
  e2e/cypress/integration/integrations/integrations_page_spec.js
  e2e/cypress/integration/integrations/integrations_search_gives_feedback_spec.js
  e2e/cypress/integration/integrations/outgoing_webhook/delete_outgoing_webhook_spec.js
  e2e/cypress/integration/integrations/outgoing_webhook/disable_outgoing_webhook_spec.js
  e2e/cypress/integration/integrations/outgoing_webhook/disable_override_username_profile_spec.js
  e2e/cypress/integration/integrations/outgoing_webhook/search_on_outgoing_webhooks_spec.js
  e2e/cypress/integration/integrations/outgoing_webhook/token_copy_icon_spec.js
  e2e/cypress/integration/integrations/plugin_slash_command_stays_visible_spec.js
  e2e/cypress/integration/markdown/markdown_image_spec.js
  e2e/cypress/integration/messaging/inline_images_open_preview_window_spec.js
  e2e/cypress/integration/messaging/inline_markdown_image_link_open_link_spec.js
  e2e/cypress/integration/messaging/pinned_posts_part2_spec.js
  e2e/cypress/integration/messaging/visual_verification_of_tooltips_on_top_nav_channel_icons_posts_spec.js
  e2e/cypress/integration/modals/quick_switcher_spec.js
  e2e/cypress/integration/notifications/desktop_notifications_spec.js
  e2e/cypress/integration/onboarding/invalidate_pending_email_invitations_spec.js
  e2e/cypress/integration/system_console/main_menu_spec.js
  e2e/cypress/integration/system_console/plugin_upload_spec.js
  e2e/cypress/integration/system_console/reporting/site_statistics_spec.js
  e2e/cypress/integration/system_console/reporting/team_statistics_spec.js
  e2e/cypress/integration/system_console/search_box_spec.js
  e2e/cypress/integration/system_console/unsaved_changes_spec.js
  e2e/cypress/integration/team_settings/closed_team_invite_with_non_mattermost_domain_spec.js
  e2e/cypress/integration/team_settings/closed_team_invite_with_specific_domain_spec.js
Labels: 4: Reviews Complete

#7081 Cypress/E2E: Fix toast appears unread spec
  e2e/cypress/integration/mark_as_unread/toast_appears_unread_spec.js
Labels: 4: Reviews Complete, CherryPick/Approved

#7076 [MM-30586] Change super to system
  i18n/en.json
Labels: 4: Reviews Complete

#7086 Automated cherry pick of #7081
  e2e/cypress/integration/mark_as_unread/toast_appears_unread_spec.js
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#6981 MM-29458: Migrate changeCSS() to CSS variable in utils/utils.jsx
  sass/layout/_webhooks.scss
  utils/utils.jsx
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#6975 MM-20418: Migrate 'components/channel_selector_modal' module and associated tests to TypeScript
  components/channel_selector_modal/__snapshots__/channel_selector_modal.test.tsx.snap
  components/channel_selector_modal/channel_selector_modal.test.tsx
  components/channel_selector_modal/channel_selector_modal.tsx
  components/channel_selector_modal/index.js
  components/channel_selector_modal/index.ts
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#7088 Automated cherry pick of #7076
  i18n/en.json
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7053 MM-T439 Town Square is not marked as unread for existing users when a new user is added to the team
  e2e/cypress/integration/multi_team_and_dm/town_square_not_marked_as_unread_spec.js
Labels: 4: Reviews Complete, AutoMerge

#6840 [MM-20582] Migrate 'components/admin_console/team_channel_settings/ch…
  components/admin_console/team_channel_settings/channel/__snapshots__/channel_settings.test.tsx.snap
  components/admin_console/team_channel_settings/channel/channel_settings.test.tsx
  components/admin_console/team_channel_settings/channel/channel_settings.tsx
  components/admin_console/team_channel_settings/channel/index.ts
  components/admin_console/team_channel_settings/channel/list/channel_list.tsx
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#7085 [MM-20465][MM-30590] Fix for collapse/expand of image preview
  components/single_image_view/__snapshots__/single_image_view.test.tsx.snap
  components/single_image_view/single_image_view.test.tsx
  components/single_image_view/single_image_view.tsx
  components/view_image/view_image.jsx
Labels: 4: Reviews Complete, CherryPick/Approved

#7064 MM-20465 Revert usage of getCurrentChannel to getCurrentChannelId where possible
  actions/new_post.ts
  components/data_prefetch/data_prefetch.test.tsx
  components/data_prefetch/data_prefetch.tsx
  components/data_prefetch/index.ts
  components/needs_team/index.ts
  components/needs_team/needs_team.tsx
  components/new_channel_flow/index.ts
  components/sidebar/index.ts
  components/sidebar/sidebar_channel/index.ts
  components/sidebar/sidebar_channel/sidebar_channel_icon/index.ts
  components/sidebar/sidebar_channel/sidebar_direct_channel/index.ts
  components/sidebar/sidebar_channel/sidebar_group_channel/index.ts
  components/sidebar/sidebar_channel_list/index.ts
  components/sidebar/sidebar_channel_list/sidebar_channel_list.test.tsx
  components/sidebar/sidebar_channel_list/sidebar_channel_list.tsx
  components/team_members_dropdown/index.ts
  selectors/views/channel_sidebar.ts
Labels: 4: Reviews Complete, CherryPick/Approved

#7092 Automated cherry pick of #7064
  actions/new_post.ts
  components/data_prefetch/data_prefetch.test.tsx
  components/data_prefetch/data_prefetch.tsx
  components/data_prefetch/index.ts
  components/needs_team/index.ts
  components/needs_team/needs_team.tsx
  components/new_channel_flow/index.ts
  components/sidebar/index.ts
  components/sidebar/sidebar_channel/index.ts
  components/sidebar/sidebar_channel/sidebar_channel_icon/index.ts
  components/sidebar/sidebar_channel/sidebar_direct_channel/index.ts
  components/sidebar/sidebar_channel/sidebar_group_channel/index.ts
  components/sidebar/sidebar_channel_list/index.ts
  components/sidebar/sidebar_channel_list/sidebar_channel_list.test.tsx
  components/sidebar/sidebar_channel_list/sidebar_channel_list.tsx
  components/team_members_dropdown/index.ts
  selectors/views/channel_sidebar.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7090 [MM-29821] Prefer TypeScript files over JavaScript in webpack
  webpack.config.js
Labels: 4: Reviews Complete

#7060 [MM-30317] add MANAGE_REMOTE_CLUSTERS permission
  components/admin_console/permission_schemes_settings/permission_schemes_settings.jsx
  components/admin_console/permission_schemes_settings/permissions_tree/permissions_tree.jsx
  i18n/en.json
  package-lock.json
  utils/constants.jsx
Labels: 2: Dev Review, 3: QA Review

#6971 MM-20416: Migrate 'components/channel_header_mobile/collapse_lhs_button' module to TypeScript
  components/channel_header_mobile/collapse_lhs_button/collapse_lhs_button.tsx
  components/channel_header_mobile/collapse_lhs_button/index.ts
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#7096 Remove Cloud billing flag from System Console
  components/admin_console/admin_definition.jsx
  i18n/en.json
Labels: 4: Reviews Complete, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, Setup Cloud Test Server

#7097 Automated cherry pick of #7096
  components/admin_console/admin_definition.jsx
  i18n/en.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7070 Some fixes to sync with lev-cleanup branch on apps
  components/dot_menu/dot_menu.test.tsx
  components/dot_menu/dot_menu.tsx
  components/dot_menu/dot_menu_empty.test.tsx
  components/dot_menu/dot_menu_mobile.test.tsx
  components/dot_menu/index.ts
  package.json
  plugins/channel_header_plug/channel_header_plug.test.tsx
  plugins/channel_header_plug/channel_header_plug.tsx
Labels: 4: Reviews Complete

#6963 Migrate 'components/announcement_bar/default_announcement_bar' module and associated tests to TypeScript
  components/announcement_bar/__snapshots__/announcement_bar.test.jsx.snap
  components/announcement_bar/announcement_bar.test.jsx
  components/announcement_bar/default_announcement_bar/announcement_bar.tsx
  components/announcement_bar/default_announcement_bar/index.ts
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#6957 Migrate this.ref.dotMenu to functional
  components/rhs_root_post/rhs_root_post.jsx
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#7033 MM-20897 Add category muting
  components/sidebar/sidebar_category/__snapshots__/sidebar_category.test.tsx.snap
  components/sidebar/sidebar_category/sidebar_category.test.tsx
  components/sidebar/sidebar_category/sidebar_category.tsx
  components/sidebar/sidebar_category/sidebar_category_menu/__snapshots__/sidebar_category_menu.test.tsx.snap
  components/sidebar/sidebar_category/sidebar_category_menu/index.ts
  components/sidebar/sidebar_category/sidebar_category_menu/sidebar_category_menu.test.tsx
  components/sidebar/sidebar_category/sidebar_category_menu/sidebar_category_menu.tsx
  components/sidebar/sidebar_category_header.tsx
  components/sidebar/sidebar_channel/sidebar_channel_menu/sidebar_channel_menu.test.tsx
  components/sidebar/sidebar_channel_list/__snapshots__/sidebar_channel_list.test.tsx.snap
  components/sidebar/sidebar_channel_list/sidebar_channel_list.test.tsx
  e2e/cypress/integration/channel_sidebar/category_muting_spec.js
  e2e/cypress/integration/channel_sidebar/custom_categories_spec.js
  e2e/cypress/integration/channel_sidebar/helpers.js
  e2e/cypress/plugins/client_request.js
  e2e/cypress/plugins/index.js
  e2e/cypress/support/client.js
  e2e/cypress/support/index.js
  e2e/cypress/support/ui/channel_sidebar.js
  i18n/en.json
  sass/layout/_sidebar-left.scss
Labels: 4: Reviews Complete

#7059 MM-24293 Fix to have group channels return in quick switcher with space
  components/suggestion/switch_channel_provider.jsx
  components/suggestion/switch_channel_provider.test.jsx
  e2e/cypress/integration/modals/quick_switcher_spec.js
Labels: 4: Reviews Complete

#7101 If card year is 0 return false for isExpired
  components/admin_console/billing/payment_info.tsx
  utils/cloud_utils.ts
Labels: 4: Reviews Complete, CherryPick/Approved

#7104 Automated cherry pick of #7101
  components/admin_console/billing/payment_info.tsx
  utils/cloud_utils.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#6825 Converted 'dot_menu' to typescript.
  components/dot_menu/__snapshots__/dot_menu.test.tsx.snap
  components/dot_menu/__snapshots__/dot_menu_empty.test.tsx.snap
  components/dot_menu/__snapshots__/dot_menu_mobile.test.tsx.snap
  components/dot_menu/dot_menu.test.tsx
  components/dot_menu/dot_menu.tsx
  components/dot_menu/dot_menu_empty.test.tsx
  components/dot_menu/dot_menu_mobile.test.tsx
  components/dot_menu/index.ts
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#7038 Migrate string refs of reset password modal
  components/admin_console/reset_password_modal/reset_password_modal.tsx
Labels: 4: Reviews Complete, AutoMerge

#7093 MM-30477 Fix for autocomplete not closing
  actions/views/channel.js
  actions/views/channel.test.js
Labels: 4: Reviews Complete, AutoMerge, CherryPick/Approved

#7106 MM-20897 Cleanup a couple missed issues
  e2e/cypress/integration/channel_sidebar/category_muting_spec.js
  e2e/cypress/plugins/client_request.js
Labels: 4: Reviews Complete

#7091 MM-T638 Webhook posts when webhook creator is not a member of the channel
  e2e/cypress/integration/integrations/incoming_webhook/webhook_posts_when_creator_not_in_channel_spec.js
Labels: 4: Reviews Complete

#6668 [MM-20481] Migrate 'components/post_view/post_body_additional_content' module and associated tests to TypeScript
  components/post_view/post_attachment_opengraph/index.ts
  components/post_view/post_attachment_opengraph/post_attachment_opengraph.tsx
  components/post_view/post_body_additional_content/__snapshots__/post_body_additional_content.test.tsx.snap
  components/post_view/post_body_additional_content/index.js
  components/post_view/post_body_additional_content/index.ts
  components/post_view/post_body_additional_content/post_body_additional_content.test.tsx
  components/post_view/post_body_additional_content/post_body_additional_content.tsx
  components/youtube_video/youtube_video.jsx
  components/youtube_video/youtube_video.test.jsx
  types/store/plugins.ts
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#7103 [MM-30509] set isDisabled prop for site > notices
  components/admin_console/admin_definition.jsx
Labels: 4: Reviews Complete, AutoMerge, CherryPick/Approved, QA Review Done

#6979 [MM-27931][MM-30158] Multi-selection and dragging of channels
  actions/views/channel_sidebar.test.ts
  actions/views/channel_sidebar.ts
  components/sidebar/index.ts
  components/sidebar/sidebar.test.tsx
  components/sidebar/sidebar.tsx
  components/sidebar/sidebar_channel/index.ts
  components/sidebar/sidebar_channel/sidebar_channel.test.tsx
  components/sidebar/sidebar_channel/sidebar_channel.tsx
  components/sidebar/sidebar_channel/sidebar_channel_link/index.ts
  components/sidebar/sidebar_channel/sidebar_channel_link/sidebar_channel_link.test.tsx
  components/sidebar/sidebar_channel/sidebar_channel_link/sidebar_channel_link.tsx
  components/sidebar/sidebar_channel_list/index.ts
  components/sidebar/sidebar_channel_list/sidebar_channel_list.test.tsx
  components/sidebar/sidebar_channel_list/sidebar_channel_list.tsx
  i18n/en.json
  reducers/views/channel_sidebar.test.ts
  reducers/views/channel_sidebar.ts
  sass/layout/_sidebar-left.scss
  selectors/views/channel_sidebar.ts
  types/store/index.ts
  utils/constants.jsx
Labels: 4: Reviews Complete, Setup Cloud Test Server

#7036 [MM-20572] Migrate 'components/admin_console/compliance_reports' to TypeScript
  components/admin_console/compliance_reports/compliance_reports.tsx
  components/admin_console/compliance_reports/index.ts
Labels: 4: Reviews Complete, AutoMerge

#7056 MM-30087 Remove direct dependency between Client4 and Rudder
  components/post_view/post_attachment_opengraph/post_attachment_opengraph.test.tsx
  components/root/root.jsx
  components/root/root.test.jsx
  package-lock.json
  package.json
Labels: 4: Reviews Complete

#7025 [MM_20423] 'external_image'module to ts (#16151)
  components/external_image/external_image.test.tsx
  components/external_image/external_image.tsx
  components/external_image/index.ts
Labels: 4: Reviews Complete

#7043 Migrate 'components/claim' module and associated tests to TypeScript
  components/claim/claim_controller.tsx
  components/claim/index.ts
Labels: 4: Reviews Complete, AutoMerge

#6912 Cloud Apps: Commands
  actions/apps.ts
  actions/command.js
  actions/command.test.js
  components/apps_modal/apps_modal.tsx
  components/dot_menu/dot_menu.tsx
  components/dot_menu/index.ts
  components/suggestion/command_provider.test.js
  components/suggestion/command_provider/__snapshots__/command_provider.test.tsx.snap
  components/suggestion/command_provider/app_command_parser.test.ts
  components/suggestion/command_provider/app_command_parser.ts
  components/suggestion/command_provider/command_provider.test.tsx
  components/suggestion/command_provider/command_provider.tsx
  components/suggestion/suggestion_box.jsx
  components/textbox/textbox.tsx
  package-lock.json
  package.json
  plugins/channel_header_plug/__snapshots__/channel_header_plug.test.tsx.snap
  plugins/channel_header_plug/channel_header_plug.tsx
  plugins/channel_header_plug/index.ts
  utils/constants.jsx
Labels: 4: Reviews Complete

#6959 [MM-29500] Migrate changeCSS() to CSS variable in utils/utils.jsx
  sass/base/_structure.scss
  utils/utils.jsx
Labels: 2: Dev Review, Hacktoberfest, hacktoberfest-accepted

#7074 MM-T2056 e2e to test, Username change reflecting for other users
  e2e/cypress/integration/account_settings/general/username_spec.js
Labels: 4: Reviews Complete

#7130 [MM-20400] Migrate 'components/plugin_marketplace/marketplace_item' module and associated tests to TypeScript
  components/plugin_marketplace/marketplace_item/__snapshots__/marketplace_item.test.tsx.snap
  components/plugin_marketplace/marketplace_item/index.ts
  components/plugin_marketplace/marketplace_item/marketplace_item.test.tsx
  components/plugin_marketplace/marketplace_item/marketplace_item.tsx
  components/plugin_marketplace/marketplace_list/__snapshots__/marketplace_list.test.jsx.snap
  components/plugin_marketplace/marketplace_list/marketplace_list.jsx
  package-lock.json
  package.json
Labels: 4: Reviews Complete

#7131 [MM-30919] Migrate 'components/plugin_marketplace/marketplace_list/navigation_row' module and associated tests to TypeScript
  components/plugin_marketplace/marketplace_list/navigation_row/__snapshots__/navigation_row.test.tsx.snap
  components/plugin_marketplace/marketplace_list/navigation_row/index.ts
  components/plugin_marketplace/marketplace_list/navigation_row/navigation_button.tsx
  components/plugin_marketplace/marketplace_list/navigation_row/navigation_row.test.tsx
  components/plugin_marketplace/marketplace_list/navigation_row/navigation_row.tsx
Labels: 2: Dev Review

#6813 [MM-26334] Fixes direct messages loading screen misalignment
  components/__snapshots__/searchable_channel_list.test.jsx.snap
  components/searchable_channel_list.jsx
  sass/components/_modal.scss
Labels: 2: Dev Review, Hacktoberfest, hacktoberfest-accepted

#7049 MM-28153: Cypress/E2E: Automate backlogs - System Console > Environment (8 test cases)
  e2e/cypress/fixtures/mattermost-icon_128x128.png
  e2e/cypress/integration/enterprise/system_console/environment_spec.js
  e2e/cypress/integration/system_console/environment_spec.js
Labels: 3: QA Review

#7072 MM-30377: Cypress/E2E: Automate backlogs - Messaging > Channel and Post Links (6 test cases)
  e2e/cypress/integration/messaging/channel_and_posts_links_spec.js
Labels: 4: Reviews Complete

#7062 MM-30355: Cypress/E2E: Automate backlogs - Account Settings > Username (6 test cases)
  e2e/cypress/integration/account_settings/general/username_spec.js
Labels: 4: Reviews Complete

#7124 MM-27208 Add tests for MM-T1684, MM-T1687, and MM-T1688
  e2e/cypress/integration/channel/archived_channels_2_spec.js
  e2e/cypress/integration/channel_sidebar/channel_sidebar_spec.js
  e2e/cypress/support/client.js
Labels: 4: Reviews Complete
