Repository mattermost/mattermost-webapp, pull requests merged in 2021-04, with the labels that each got.

#7798 chore : Fixed typo in babel plugin for object, rest, spread
  babel.config.js
Labels: 4: Reviews Complete

#7814 Cypress/E2E: Update test case name
  e2e/cypress/integration/system_console/user_management/users_deactivation_spec.js
Labels: 4: Reviews Complete

#7801 Cypress/E2E: Fix test key extraction
  e2e/cypress/integration/enterprise/system_console/authentication_method_spec.js
  e2e/cypress/integration/messaging/markdown_spec.js
  e2e/cypress/integration/system_console/mobile_settings_spec.js
  e2e/utils/test_cases.js
Labels: 4: Reviews Complete

#7793 MM-34387 Cypress/E2E: Fix tests with SAML/Keycloak
  e2e/cypress.json
  e2e/cypress/integration/ad_ldap/saml_ldap_sync_id_attrib_spec.js
  e2e/cypress/integration/ad_ldap/saml_ldap_sync_remove_spec.js
  e2e/cypress/integration/ad_ldap/saml_ldap_sync_spec.js
  e2e/cypress/plugins/keycloak_request.js
  e2e/cypress/support/api/index.js
  e2e/cypress/support/api/keycloak.d.ts
  e2e/cypress/support/api/keycloak.js
  e2e/cypress/support/api/keycloak_realm.json
  e2e/cypress/support/api/system.d.ts
  e2e/cypress/support/api/system.js
  e2e/cypress/support/api/user.js
  e2e/cypress/support/ldap_commands.js
  e2e/run_tests.js
  e2e/utils/file.js
Labels: 4: Reviews Complete, AutoMerge

#7802 MM-34026 Cypress/E2E: fix markdown tests
  e2e/cypress/fixtures/markdown/markdown_code_syntax.html
  e2e/cypress/fixtures/markdown/markdown_latex.html
  e2e/cypress/integration/messaging/markdown_spec.js
Labels: 4: Reviews Complete

#7729 [MM-32933] Custom Statuses: Implement max length validation on the status modal
  components/custom_status/custom_status.scss
  components/custom_status/custom_status_modal.tsx
Labels: 4: Reviews Complete, AutoMerge

#7818 Translations update from Weblate
  i18n/de.json
  i18n/fr.json
  i18n/ja.json
  i18n/nl.json
  i18n/ru.json
  i18n/tr.json
  i18n/zh-CN.json
Labels: 2: Dev Review, 3: QA Review

#7765 MM-33926 Cypress/E2E: Separate failed tests due to valid bug and stabilize other tests on archived channel
  e2e/cypress/integration/archived_channel/archived_channel_spec.js
  e2e/cypress/integration/archived_channel/archived_leave_channel_spec.js
  e2e/cypress/support/api/channel.d.ts
  e2e/cypress/support/api/channel.js
  e2e/cypress/support/api/setup.d.ts
  e2e/cypress/support/api/setup.js
  e2e/cypress/support/ui/channel.js
Labels: 4: Reviews Complete

#7518 All Sections to SubSections
  components/admin_console/admin_definition.jsx
  components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.jsx.snap
  components/admin_console/admin_sidebar/admin_sidebar.test.jsx
  components/admin_console/data_retention_settings.jsx
  components/admin_console/system_roles/system_role/__snapshots__/system_role_permissions.test.tsx.snap
  components/admin_console/system_roles/system_role/system_role.tsx
  components/admin_console/system_roles/system_role/system_role_permissions.tsx
  e2e/cypress/fixtures/console-example-inputs.json
  e2e/cypress/fixtures/system-roles-console-access.json
  e2e/cypress/support/api/role.js
  i18n/en.json
  packages/mattermost-redux/src/constants/permissions.ts
  packages/mattermost-redux/src/constants/permissions_sysconsole.ts
  plugins/test/__snapshots__/main_menu_action.test.jsx.snap
  selectors/admin_console.jsx
Labels: 4: Reviews Complete, Docs/Needed

#7819 Memorize marketplace selectors
  selectors/views/marketplace.ts
Labels: 4: Reviews Complete

#7811 MM-34553: profile popover, fix channel admin badge in channel header mentions
  components/profile_popover/index.js
Labels: 4: Reviews Complete, CherryPick/Approved

#7824 Automated cherry pick of #7811
  components/profile_popover/index.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7822 Fix emoticons not being case indepent
  components/suggestion/emoticon_provider.jsx
Labels: 4: Reviews Complete

#7821 [MM-344156] - Fix regression for channel members modal
  sass/components/_modal.scss
Labels: 4: Reviews Complete

#7823 [MM-34491] Respect slash command root label
  components/suggestion/command_provider/app_command_parser/app_command_parser.ts
Labels: 4: Reviews Complete

#7785 Re-enable snapshotting of node_modules
  webpack.config.js
Labels: 4: Reviews Complete, AutoMerge

#7810 Cypress/E2E: Promote and Update
  e2e/cypress/integration/emoji/custom_emoji_1_spec.js
  e2e/cypress/integration/emoji/custom_emoji_2_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/system_console_manage_guest_spec.js
Labels: 4: Reviews Complete

#7835 Cypress/E2E: Fix MM-T1635 Channel listing is displayed correctly with proper team name
  e2e/cypress/integration/enterprise/system_console/settings_spec.js
Labels: 4: Reviews Complete

#7829 [MM-34580] - Truncate image name when text is too long
  components/single_image_view/__snapshots__/single_image_view.test.tsx.snap
  components/single_image_view/single_image_view.tsx
  sass/components/_files.scss
Labels: 4: Reviews Complete

#7828 [MM-34575] - Fix regressions for set a header button in DM
  components/post_view/channel_intro_message/add_members_button.scss
  sass/layout/_headers.scss
Labels: 4: Reviews Complete, CherryPick/Approved

#7771 MM-27380 Move collapsed categories to server and make sidebar more optimistic
  actions/views/channel_sidebar.test.ts
  actions/views/channel_sidebar.ts
  components/sidebar/sidebar_category/__snapshots__/sidebar_category.test.tsx.snap
  components/sidebar/sidebar_category/index.ts
  components/sidebar/sidebar_category/sidebar_category.test.tsx
  components/sidebar/sidebar_category/sidebar_category.tsx
  components/sidebar/sidebar_category/sidebar_category_menu/sidebar_category_menu.test.tsx
  components/sidebar/sidebar_channel_list/__snapshots__/sidebar_channel_list.test.tsx.snap
  components/sidebar/sidebar_channel_list/index.ts
  components/sidebar/sidebar_channel_list/sidebar_channel_list.test.tsx
  components/sidebar/sidebar_channel_list/sidebar_channel_list.tsx
  packages/mattermost-redux/src/actions/channel_categories.test.js
  packages/mattermost-redux/src/actions/channel_categories.ts
  packages/mattermost-redux/src/types/channel_categories.ts
  selectors/views/channel_sidebar.test.js
  selectors/views/channel_sidebar.ts
  utils/test_helper.ts
Labels: 4: Reviews Complete

#7755 [MM-20426] Migrate 'components/post_markdown' module and associated tests to TypeScript
  components/markdown/index.ts
  components/post_markdown/__snapshots__/post_markdown.test.tsx.snap
  components/post_markdown/index.ts
  components/post_markdown/post_markdown.test.tsx
  components/post_markdown/post_markdown.tsx
  components/post_markdown/system_message_helpers.tsx
  components/post_view/combined_system_message/index.ts
  components/post_view/post_add_channel_member/index.ts
  components/textbox/textbox.tsx
Labels: 4: Reviews Complete

#7841 Automated cherry pick of #7828
  components/post_view/channel_intro_message/add_members_button.scss
  sass/layout/_headers.scss
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7842 Automated cherry pick of #7829
  components/single_image_view/__snapshots__/single_image_view.test.tsx.snap
  components/single_image_view/single_image_view.tsx
  sass/components/_files.scss
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7352 [MM-12290] inline image collapse
  actions/command.js
  actions/post_actions.jsx
  components/__snapshots__/markdown_image.test.jsx.snap
  components/markdown_image.jsx
  components/markdown_image.test.jsx
  components/markdown_image_expand/__snapshots__/markdown_image_expand.test.tsx.snap
  components/markdown_image_expand/index.ts
  components/markdown_image_expand/markdown_image_expand.scss
  components/markdown_image_expand/markdown_image_expand.test.tsx
  components/markdown_image_expand/markdown_image_expand.tsx
  components/post_view/post_message_view/__snapshots__/post_message_view.test.tsx.snap
  components/post_view/post_message_view/post_message_view.tsx
  package-lock.json
  plugins/test/__snapshots__/post_type.test.jsx.snap
  sass/utils/_variables.scss
  selectors/posts.js
  selectors/preferences.ts
  utils/constants.jsx
Labels: 4: Reviews Complete

#7831 [MM-34563] - Fix hover in category sorting menu for all theme
  components/widgets/menu/menu_items/submenu_item.test.tsx
  components/widgets/menu/menu_items/submenu_item.tsx
  sass/layout/_sidebar-left.scss
  utils/utils.jsx
Labels: 4: Reviews Complete

#7809 Cypress/E2E: Add @noncloud to support_packet_generation_spec
  e2e/cypress/integration/enterprise/system_console/support_packet_generation_spec.js
Labels: 4: Reviews Complete

#7844 MM-34502 Fix help text being invisible for empty gif picker
  components/gif_picker/components/SearchGrid/SearchGrid.scss
Labels: 4: Reviews Complete, AutoMerge, CherryPick/Approved

#7848 Automated cherry pick of #7844
  components/gif_picker/components/SearchGrid/SearchGrid.scss
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7758 [MM-33714] Prevent user from clicking upgrade button with no credit card input
  components/payment_form/card_input.tsx
  components/payment_form/payment_form.tsx
  components/purchase_modal/purchase_modal.tsx
  package-lock.json
Labels: 4: Reviews Complete, QA Review Done

#7833 Cypress/E2E: Fix case Verify Guest Badge in DM header and GM header
  e2e/cypress/integration/enterprise/guest_accounts/guest_identification_ui_spec.js
Labels: 3: QA Review

#7705 Making the scrollbar on pdfs previews always visible
  sass/components/_modal.scss
Labels: QA Review Done

#7791 Handle modal double submit
  components/apps_form/apps_form.tsx
Labels: 4: Reviews Complete

#7807 [MM-34414] Add trial_end_at to cloud redux Subscription type
  packages/mattermost-redux/src/types/cloud.ts
Labels: 4: Reviews Complete

#7825 Bump plugin channel header button limit
  plugins/channel_header_plug/__snapshots__/channel_header_plug.test.tsx.snap
  plugins/channel_header_plug/channel_header_plug.test.tsx
  plugins/channel_header_plug/channel_header_plug.tsx
Labels: 4: Reviews Complete

#7778 [MM-33859] - Transition animation smoothly on long post permalinks
  components/post_view/post/__snapshots__/post.test.js.snap
  components/post_view/post/post.jsx
  sass/components/_post.scss
  utils/constants.jsx
  utils/utils.jsx
Labels: 2: Dev Review, 3: QA Review, Setup Cloud Test Server

#7789 Create app call response posts as bot
  actions/command.ts
  actions/global_actions.tsx
  components/apps_form/apps_form_container.tsx
  components/dot_menu/dot_menu.tsx
  components/post_view/embedded_bindings/button_binding/button_binding.test.tsx
  components/post_view/embedded_bindings/button_binding/button_binding.tsx
  components/post_view/embedded_bindings/select_binding/select_binding.test.tsx
  components/post_view/embedded_bindings/select_binding/select_binding.tsx
  components/suggestion/command_provider/app_command_parser/app_command_parser.ts
  components/suggestion/command_provider/app_command_parser/app_command_parser_dependencies.ts
  packages/mattermost-redux/src/types/apps.ts
  plugins/channel_header_plug/channel_header_plug.tsx
Labels: 4: Reviews Complete

#7830 [MM-34501] - Bring back margin: auto for the no results indicator
  components/no_results_indicator/no_results_indicator.scss
Labels: 4: Reviews Complete

#7748 [MM-32188] Fix Apps modal styling issues
  components/apps_form/apps_form_field/apps_form_select_field.tsx
Labels: 4: Reviews Complete, QA Review Done

#7847 MM-34699-fix oauth check in admin_definition
  components/admin_console/admin_definition.jsx
  components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.jsx.snap
Labels: 4: Reviews Complete

#7836 Cypress/E2E: Fix MM-T1665_1 Deactivated user is not shown in Direct Messages modal when no previous conversation
  e2e/cypress/integration/messaging/dm_list_of_users_spec.js
Labels: 4: Reviews Complete

#7845 Cypress/E2E: Improve handling of specs to properly distribute in parallel
  e2e/generate_test_cycle.js
  e2e/package.json
  e2e/run_test_cycle.js
  e2e/run_tests.js
  e2e/utils/file.js
Labels: 4: Reviews Complete, AutoMerge

#7852 Fix failing tests on master
  components/channel_header/__snapshots__/channel_header.test.jsx.snap
Labels: 2: Dev Review

#7858 Automated cherry pick of #7518
  components/admin_console/admin_definition.jsx
  components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.jsx.snap
  components/admin_console/admin_sidebar/admin_sidebar.test.jsx
  components/admin_console/data_retention_settings.jsx
  components/admin_console/system_roles/system_role/__snapshots__/system_role_permissions.test.tsx.snap
  components/admin_console/system_roles/system_role/system_role.tsx
  components/admin_console/system_roles/system_role/system_role_permissions.tsx
  e2e/cypress/fixtures/console-example-inputs.json
  e2e/cypress/fixtures/system-roles-console-access.json
  e2e/cypress/support/api/role.js
  i18n/en.json
  packages/mattermost-redux/src/constants/permissions.ts
  packages/mattermost-redux/src/constants/permissions_sysconsole.ts
  plugins/test/__snapshots__/main_menu_action.test.jsx.snap
  selectors/admin_console.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7859 Automated cherry pick of #7789
  actions/command.ts
  actions/global_actions.tsx
  components/apps_form/apps_form_container.tsx
  components/dot_menu/dot_menu.tsx
  components/post_view/embedded_bindings/button_binding/button_binding.test.tsx
  components/post_view/embedded_bindings/button_binding/button_binding.tsx
  components/post_view/embedded_bindings/select_binding/select_binding.test.tsx
  components/post_view/embedded_bindings/select_binding/select_binding.tsx
  components/suggestion/command_provider/app_command_parser/app_command_parser.ts
  components/suggestion/command_provider/app_command_parser/app_command_parser_dependencies.ts
  packages/mattermost-redux/src/types/apps.ts
  plugins/channel_header_plug/channel_header_plug.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7860 Automated cherry pick of #7791
  components/apps_form/apps_form.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7862 Automated cherry pick of #7847
  components/admin_console/admin_definition.jsx
  components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.jsx.snap
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7863 Automated cherry pick of #7748
  components/apps_form/apps_form_field/apps_form_select_field.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7864 Automated cherry pick of #7755
  components/markdown/index.ts
  components/post_markdown/__snapshots__/post_markdown.test.tsx.snap
  components/post_markdown/index.ts
  components/post_markdown/post_markdown.test.tsx
  components/post_markdown/post_markdown.tsx
  components/post_markdown/system_message_helpers.tsx
  components/post_view/combined_system_message/index.ts
  components/post_view/post_add_channel_member/index.ts
  components/textbox/textbox.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7865 Automated cherry pick of #7828
  components/post_view/channel_intro_message/add_members_button.scss
  sass/layout/_headers.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7866 Automated cherry pick of #7799
  components/post_view/channel_intro_message/add_members_button.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7867 Automated cherry pick of #7765
  e2e/cypress/integration/archived_channel/archived_channel_spec.js
  e2e/cypress/integration/archived_channel/archived_leave_channel_spec.js
  e2e/cypress/support/api/channel.d.ts
  e2e/cypress/support/api/channel.js
  e2e/cypress/support/api/setup.d.ts
  e2e/cypress/support/api/setup.js
  e2e/cypress/support/ui/channel.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7868 Automated cherry pick of #7780
  e2e/cypress/integration/custom_status/custom_status_1_spec.js
  e2e/cypress/integration/custom_status/custom_status_2_spec.js
  e2e/cypress/integration/custom_status/custom_status_3_spec.js
  e2e/cypress/integration/custom_status/custom_status_4_spec.js
  e2e/cypress/integration/custom_status/custom_status_6_spec.js
  e2e/cypress/integration/enterprise/integrations/incoming_webhook_spec.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7869 Automated cherry pick of #7809
  e2e/cypress/integration/enterprise/system_console/support_packet_generation_spec.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7870 Automated cherry pick of #7852
  components/channel_header/__snapshots__/channel_header.test.jsx.snap
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7871 Automated cherry pick of #7602
  components/channel_info_modal/__snapshots__/channel_info_modal.test.tsx.snap
  components/channel_info_modal/channel_info_modal.test.tsx
  components/channel_info_modal/channel_info_modal.tsx
  components/channel_info_modal/index.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7872 Automated cherry pick of #7771
  actions/views/channel_sidebar.test.ts
  actions/views/channel_sidebar.ts
  components/sidebar/sidebar_category/__snapshots__/sidebar_category.test.tsx.snap
  components/sidebar/sidebar_category/index.ts
  components/sidebar/sidebar_category/sidebar_category.test.tsx
  components/sidebar/sidebar_category/sidebar_category.tsx
  components/sidebar/sidebar_category/sidebar_category_menu/sidebar_category_menu.test.tsx
  components/sidebar/sidebar_channel_list/__snapshots__/sidebar_channel_list.test.tsx.snap
  components/sidebar/sidebar_channel_list/index.ts
  components/sidebar/sidebar_channel_list/sidebar_channel_list.test.tsx
  components/sidebar/sidebar_channel_list/sidebar_channel_list.tsx
  packages/mattermost-redux/src/actions/channel_categories.test.js
  packages/mattermost-redux/src/actions/channel_categories.ts
  packages/mattermost-redux/src/types/channel_categories.ts
  selectors/views/channel_sidebar.test.js
  selectors/views/channel_sidebar.ts
  utils/test_helper.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7873 Automated cherry pick of #7705
  sass/components/_modal.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7874 Automated cherry pick of #7821
  sass/components/_modal.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7875 Automated cherry pick of #7778
  components/post_view/post/__snapshots__/post.test.js.snap
  components/post_view/post/post.jsx
  sass/components/_post.scss
  utils/constants.jsx
  utils/utils.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7876 Automated cherry pick of #7830
  components/no_results_indicator/no_results_indicator.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7877 Automated cherry pick of #7831
  components/widgets/menu/menu_items/submenu_item.test.tsx
  components/widgets/menu/menu_items/submenu_item.tsx
  sass/layout/_sidebar-left.scss
  utils/utils.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7878 Automated cherry pick of #7836
  e2e/cypress/integration/messaging/dm_list_of_users_spec.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7879 Automated cherry pick of #7814
  e2e/cypress/integration/system_console/user_management/users_deactivation_spec.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7880 Automated cherry pick of #7825
  plugins/channel_header_plug/__snapshots__/channel_header_plug.test.tsx.snap
  plugins/channel_header_plug/channel_header_plug.test.tsx
  plugins/channel_header_plug/channel_header_plug.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7881 Automated cherry pick of #7812
  sass/components/_react-select.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7882 Automated cherry pick of #7352
  actions/command.ts
  actions/post_actions.jsx
  components/__snapshots__/markdown_image.test.jsx.snap
  components/markdown_image.jsx
  components/markdown_image.test.jsx
  components/markdown_image_expand/__snapshots__/markdown_image_expand.test.tsx.snap
  components/markdown_image_expand/index.ts
  components/markdown_image_expand/markdown_image_expand.scss
  components/markdown_image_expand/markdown_image_expand.test.tsx
  components/markdown_image_expand/markdown_image_expand.tsx
  components/post_view/post_message_view/__snapshots__/post_message_view.test.tsx.snap
  components/post_view/post_message_view/post_message_view.tsx
  package-lock.json
  plugins/test/__snapshots__/post_type.test.jsx.snap
  sass/utils/_variables.scss
  selectors/posts.js
  selectors/preferences.ts
  utils/constants.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7783 Sync parser with latest mobile improvements
  actions/command.ts
  components/suggestion/command_provider/app_command_parser/app_command_parser.test.ts
  components/suggestion/command_provider/app_command_parser/app_command_parser.ts
  components/suggestion/command_provider/app_command_parser/app_command_parser_dependencies.ts
  components/suggestion/command_provider/command_provider.tsx
  i18n/en.json
  packages/mattermost-redux/src/types/actions.ts
  utils/constants.jsx
Labels: 4: Reviews Complete

#7884 Translations update from Weblate
  i18n/bg.json
  i18n/de.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 2: Dev Review

#7749 [MM-34094] Hide bindings for system messages
  components/dot_menu/index.ts
Labels: 4: Reviews Complete, QA Review Done

#7854 Update en.json
  i18n/en.json
Labels: 4: Reviews Complete, AutoMerge

#7887 Cherry-pick Translations update from Weblate (#7884)
  i18n/bg.json
  i18n/de.json
  i18n/es.json
  i18n/fr.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 4: Reviews Complete

#7855 MM-34005 Cypress/E2E: Fix for OAuth
  e2e/Dockerfile.webhook
  e2e/cypress/integration/enterprise/oauth/oauth_spec.js
  e2e/cypress/support/task_commands.d.ts
  e2e/cypress/support/task_commands.js
  e2e/webhook_serve.js
Labels: 4: Reviews Complete

#7726 [MM-32430] New hybrid input
  components/widgets/inputs/__snapshots__/dropdown_input_hybrid.test.tsx.snap
  components/widgets/inputs/dropdown_input_hybrid.scss
  components/widgets/inputs/dropdown_input_hybrid.test.tsx
  components/widgets/inputs/dropdown_input_hybrid.tsx
  components/widgets/inputs/inputs.stories.js
Labels: 3: QA Review

#7890 [MM-34663] System Console > Guest Access (Beta) - System User Manager role now sees Integrations > CORS
  components/admin_console/admin_definition.jsx
  components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.jsx.snap
Labels: 4: Reviews Complete

#7899 Automated cherry pick of #7749
  components/dot_menu/index.ts
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7757 [MM-33897][MM-33910] Revert to using original display name logic for DMs on channel switcher, removing username
  components/suggestion/switch_channel_provider.jsx
  components/suggestion/switch_channel_provider.test.jsx
  sass/components/_post.scss
Labels: 4: Reviews Complete

#7900 Automated cherry pick of #7783
  actions/command.ts
  components/suggestion/command_provider/app_command_parser/app_command_parser.test.ts
  components/suggestion/command_provider/app_command_parser/app_command_parser.ts
  components/suggestion/command_provider/app_command_parser/app_command_parser_dependencies.ts
  components/suggestion/command_provider/command_provider.tsx
  i18n/en.json
  packages/mattermost-redux/src/types/actions.ts
  utils/constants.jsx
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7901 Automated cherry pick of #7890
  components/admin_console/admin_definition.jsx
  components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.jsx.snap
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7903 Automated cherry pick of #7757
  components/suggestion/switch_channel_provider.jsx
  components/suggestion/switch_channel_provider.test.jsx
  sass/components/_post.scss
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7839 MM-34506 - add banners when trial product
  components/admin_console/billing/billing_subscriptions/index.tsx
  components/announcement_bar/announcement_bar_controller.jsx
  components/announcement_bar/cloud_trial_announcement_bar/cloud_trial_announcement_bar.tsx
  components/announcement_bar/cloud_trial_announcement_bar/index.ts
  components/announcement_bar/default_announcement_bar/announcement_bar.tsx
  components/purchase_modal/index.ts
  components/purchase_modal/purchase_modal.tsx
  i18n/en.json
  sass/base/_compass-icons.scss
  sass/components/_announcement-bar.scss
  utils/constants.jsx
Labels: 1: UX Review, Setup Cloud + CWS Test Server

#7905 Automated cherry pick of #7840
  images/add_payment_method.png
  images/logo_email_gray.png
  webpack.config.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7837 [MM-34535][MM-34536][MM-34558] Update Trial License Banner Text
  components/announcement_bar/configuration_bar/configuration_bar.tsx
  components/announcement_bar/configuration_bar/index.ts
  components/announcement_bar/purchase_link/purchase_link.tsx
  i18n/en.json
  utils/constants.jsx
  utils/license_utils.jsx
Labels: 3: QA Review

#7795 MM-27493 shared channels (MVP)
  components/admin_console/admin_definition.jsx
  components/admin_console/data_grid/data_grid.scss
  components/admin_console/team_channel_settings/channel/details/__snapshots__/channel_profile.test.tsx.snap
  components/admin_console/team_channel_settings/channel/details/channel_profile.scss
  components/admin_console/team_channel_settings/channel/details/channel_profile.test.tsx
  components/admin_console/team_channel_settings/channel/details/channel_profile.tsx
  components/admin_console/team_channel_settings/channel/list/__snapshots__/channel_list.test.tsx.snap
  components/admin_console/team_channel_settings/channel/list/channel_list.scss
  components/admin_console/team_channel_settings/channel/list/channel_list.test.tsx
  components/admin_console/team_channel_settings/channel/list/channel_list.tsx
  components/admin_console/user_grid/user_grid_role_dropdown.tsx
  components/channel_header/__snapshots__/channel_header.test.jsx.snap
  components/channel_header/channel_header.js
  components/channel_header/channel_header.test.jsx
  components/channel_info_modal/channel_info_modal.tsx
  components/channel_members_dropdown/__snapshots__/channel_members_dropdown.test.jsx.snap
  components/channel_members_dropdown/channel_members_dropdown.jsx
  components/channel_members_dropdown/channel_members_dropdown.test.jsx
  components/legacy_sidebar/sidebar_channel/__snapshots__/sidebar_channel.test.jsx.snap
  components/legacy_sidebar/sidebar_channel/index.js
  components/legacy_sidebar/sidebar_channel/sidebar_channel.jsx
  components/legacy_sidebar/sidebar_channel/sidebar_channel.test.jsx
  components/legacy_sidebar/sidebar_channel_button_or_link/__snapshots__/sidebar_channel_button_or_link.test.jsx.snap
  components/legacy_sidebar/sidebar_channel_button_or_link/__snapshots__/sidebar_channel_button_or_link_icon.test.jsx.snap
  components/legacy_sidebar/sidebar_channel_button_or_link/sidebar_channel_button_or_link.jsx
  components/legacy_sidebar/sidebar_channel_button_or_link/sidebar_channel_button_or_link.test.jsx
  components/legacy_sidebar/sidebar_channel_button_or_link/sidebar_channel_button_or_link_icon.jsx
  components/legacy_sidebar/sidebar_channel_button_or_link/sidebar_channel_button_or_link_icon.test.jsx
  components/popover_list_members/popover_list_members_item/popover_list_members_item.jsx
  components/post_view/post_header/post_header.tsx
  components/post_view/post_list_row/post_list_row.tsx
  components/profile_popover/__snapshots__/profile_popover.test.jsx.snap
  components/profile_popover/profile_popover.jsx
  components/profile_popover/profile_popover.test.jsx
  components/rhs_root_post/rhs_root_post.jsx
  components/searchable_channel_list.jsx
  components/shared_channel_indicator.tsx
  components/shared_user_indicator.tsx
  components/sidebar/sidebar_channel/sidebar_base_channel/__snapshots__/sidebar_base_channel.test.tsx.snap
  components/sidebar/sidebar_channel/sidebar_base_channel/sidebar_base_channel.test.tsx
  components/sidebar/sidebar_channel/sidebar_base_channel/sidebar_base_channel.tsx
  components/suggestion/at_mention_provider/at_mention_suggestion.jsx
  components/suggestion/search_user_provider.jsx
  components/suggestion/switch_channel_provider.jsx
  components/user_profile/__snapshots__/user_profile.test.tsx.snap
  components/user_profile/index.ts
  components/user_profile/user_profile.test.tsx
  components/user_profile/user_profile.tsx
  i18n/en.json
  packages/mattermost-redux/src/types/channels.ts
  packages/mattermost-redux/src/types/users.ts
  sass/components/_mentions.scss
  sass/components/_modal.scss
  sass/components/_popover.scss
  sass/components/_post.scss
  sass/components/_suggestion-list.scss
  sass/layout/_headers.scss
  sass/layout/_legacy-sidebar-left.scss
Labels: 4: Reviews Complete, CherryPick/Approved, QA Review Done

#7909 Automated cherry pick of #7795
  components/admin_console/admin_definition.jsx
  components/admin_console/data_grid/data_grid.scss
  components/admin_console/team_channel_settings/channel/details/__snapshots__/channel_profile.test.tsx.snap
  components/admin_console/team_channel_settings/channel/details/channel_profile.scss
  components/admin_console/team_channel_settings/channel/details/channel_profile.test.tsx
  components/admin_console/team_channel_settings/channel/details/channel_profile.tsx
  components/admin_console/team_channel_settings/channel/list/__snapshots__/channel_list.test.tsx.snap
  components/admin_console/team_channel_settings/channel/list/channel_list.scss
  components/admin_console/team_channel_settings/channel/list/channel_list.test.tsx
  components/admin_console/team_channel_settings/channel/list/channel_list.tsx
  components/admin_console/user_grid/user_grid_role_dropdown.tsx
  components/channel_header/__snapshots__/channel_header.test.jsx.snap
  components/channel_header/channel_header.js
  components/channel_header/channel_header.test.jsx
  components/channel_info_modal/channel_info_modal.tsx
  components/channel_members_dropdown/__snapshots__/channel_members_dropdown.test.jsx.snap
  components/channel_members_dropdown/channel_members_dropdown.jsx
  components/channel_members_dropdown/channel_members_dropdown.test.jsx
  components/legacy_sidebar/sidebar_channel/__snapshots__/sidebar_channel.test.jsx.snap
  components/legacy_sidebar/sidebar_channel/index.js
  components/legacy_sidebar/sidebar_channel/sidebar_channel.jsx
  components/legacy_sidebar/sidebar_channel/sidebar_channel.test.jsx
  components/legacy_sidebar/sidebar_channel_button_or_link/__snapshots__/sidebar_channel_button_or_link.test.jsx.snap
  components/legacy_sidebar/sidebar_channel_button_or_link/__snapshots__/sidebar_channel_button_or_link_icon.test.jsx.snap
  components/legacy_sidebar/sidebar_channel_button_or_link/sidebar_channel_button_or_link.jsx
  components/legacy_sidebar/sidebar_channel_button_or_link/sidebar_channel_button_or_link.test.jsx
  components/legacy_sidebar/sidebar_channel_button_or_link/sidebar_channel_button_or_link_icon.jsx
  components/legacy_sidebar/sidebar_channel_button_or_link/sidebar_channel_button_or_link_icon.test.jsx
  components/popover_list_members/popover_list_members_item/popover_list_members_item.jsx
  components/post_view/post_header/post_header.tsx
  components/post_view/post_list_row/post_list_row.tsx
  components/profile_popover/__snapshots__/profile_popover.test.jsx.snap
  components/profile_popover/profile_popover.jsx
  components/profile_popover/profile_popover.test.jsx
  components/rhs_root_post/rhs_root_post.jsx
  components/searchable_channel_list.jsx
  components/shared_channel_indicator.tsx
  components/shared_user_indicator.tsx
  components/sidebar/sidebar_channel/sidebar_base_channel/__snapshots__/sidebar_base_channel.test.tsx.snap
  components/sidebar/sidebar_channel/sidebar_base_channel/sidebar_base_channel.test.tsx
  components/sidebar/sidebar_channel/sidebar_base_channel/sidebar_base_channel.tsx
  components/suggestion/at_mention_provider/at_mention_suggestion.jsx
  components/suggestion/search_user_provider.jsx
  components/suggestion/switch_channel_provider.jsx
  components/user_profile/__snapshots__/user_profile.test.tsx.snap
  components/user_profile/index.ts
  components/user_profile/user_profile.test.tsx
  components/user_profile/user_profile.tsx
  i18n/en.json
  packages/mattermost-redux/src/types/channels.ts
  packages/mattermost-redux/src/types/users.ts
  sass/components/_mentions.scss
  sass/components/_modal.scss
  sass/components/_popover.scss
  sass/components/_post.scss
  sass/components/_suggestion-list.scss
  sass/layout/_headers.scss
  sass/layout/_legacy-sidebar-left.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7910 Automated cherry pick of #7837
  components/announcement_bar/configuration_bar/configuration_bar.tsx
  components/announcement_bar/configuration_bar/index.ts
  components/announcement_bar/purchase_link/purchase_link.tsx
  i18n/en.json
  utils/constants.jsx
  utils/license_utils.jsx
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7888 Cypress/E2E: Fix reporting and save environment details to dashboard
  e2e/generate_test_cycle.js
  e2e/package-lock.json
  e2e/package.json
  e2e/run_test_cycle.js
  e2e/run_tests.js
  e2e/save_report.js
  e2e/utils/dashboard.js
  e2e/utils/report.js
Labels: 4: Reviews Complete

#7885 Fixing file search results styles and text on channels without files
  components/no_results_indicator/no_results_indicator.scss
  i18n/en.json
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server

#7768 Fix Marketplace aria-label in MM-T1476 e2e test
  e2e/cypress/integration/accessibility/accessibility_dropdowns_spec.js
Labels: 4: Reviews Complete, AutoMerge

#7912 Automated cherry pick of #7885
  components/no_results_indicator/no_results_indicator.scss
  i18n/en.json
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7743 [MM-32201] Job table changes for data retention
  components/admin_console/jobs/table.jsx
  components/admin_console/jobs/table.scss
  components/admin_console/jobs/table.test.jsx
Labels: 3: QA Review, Setup Cloud Test Server

#7908 use the new server value is_free_trial
  components/admin_console/billing/billing_subscriptions/index.tsx
  components/announcement_bar/cloud_trial_announcement_bar/index.ts
  components/purchase_modal/index.ts
  packages/mattermost-redux/src/types/cloud.ts
Labels: 2: Dev Review

#7820 Mm 29656
  components/product_notices_modal/product_notices.test.tsx
  components/product_notices_modal/product_notices_modal.scss
Labels: 4: Reviews Complete

#7826 [MM-34523] New trial card for license page
  components/admin_console/license_settings/__snapshots__/license_settings.test.jsx.snap
  components/admin_console/license_settings/license_settings.jsx
  components/admin_console/license_settings/license_settings.test.jsx
  components/admin_console/license_settings/renew_license_card/renew_license_card.scss
  components/admin_console/license_settings/trial_license_card/trial_license_card.scss
  components/admin_console/license_settings/trial_license_card/trial_license_card.tsx
  i18n/en.json
Labels: 3: QA Review, Setup Cloud Test Server

#7914 Automated cherry pick of #7826
  components/admin_console/license_settings/__snapshots__/license_settings.test.jsx.snap
  components/admin_console/license_settings/license_settings.jsx
  components/admin_console/license_settings/license_settings.test.jsx
  components/admin_console/license_settings/renew_license_card/renew_license_card.scss
  components/admin_console/license_settings/trial_license_card/trial_license_card.scss
  components/admin_console/license_settings/trial_license_card/trial_license_card.tsx
  i18n/en.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7770 Migrating a few stragglers from the TS migration
  components/access_history_modal/access_history_modal.test.tsx
  components/activity_log_modal/activity_log_modal.jsx
  components/activity_log_modal/components/__snapshots__/activity_log.test.tsx.snap
  components/activity_log_modal/components/activity_log.test.tsx
  components/activity_log_modal/components/activity_log.tsx
  components/activity_log_modal/components/more_info.test.tsx
  components/activity_log_modal/components/more_info.tsx
  components/admin_console/system_users/system_users.test.tsx
  components/channel_header/components/__snapshots__/header_icon_wrapper.test.tsx.snap
  components/channel_header/components/header_icon_wrapper.test.tsx
  components/channel_header/components/header_icon_wrapper.tsx
  components/channel_header_dropdown/menu_items/close_message/__snapshots__/close_message.test.tsx.snap
  components/channel_header_dropdown/menu_items/close_message/close_message.test.tsx
  components/channel_header_dropdown/menu_items/close_message/close_message.tsx
  components/channel_header_dropdown/menu_items/close_message/index.ts
  components/channel_header_dropdown/menu_items/leave_channel/leave_channel.test.tsx
  components/channel_header_dropdown/menu_items/view_pinned_posts/view_pinned_posts.test.tsx
  components/channel_header_mobile/unmute_channel_button/unmute_channel_button.test.tsx
  components/common/__snapshots__/infinite_scroll.test.tsx.snap
  components/common/infinite_scroll.test.tsx
  components/common/infinite_scroll.tsx
  components/create_team/components/__snapshots__/display_name.test.tsx.snap
  components/create_team/components/display_name.test.tsx
  components/create_team/components/display_name.tsx
  components/create_team/components/team_url/team_url.tsx
  components/create_team/create_team.tsx
  components/dot_menu/__snapshots__/dot_menu.test.tsx.snap
  components/dot_menu/dot_menu.test.tsx
  components/dot_menu/dot_menu.tsx
  components/external_image/external_image.test.tsx
  components/favicon_title_handler/favicon_title_handler.test.tsx
  components/favicon_title_handler/favicon_title_handler.tsx
  components/get_public_link_modal/get_public_link_modal.test.tsx
  components/integrations/edit_incoming_webhook/edit_incoming_webhook.test.tsx
  components/integrations/edit_outgoing_webhook/edit_outgoing_webhook.test.tsx
  components/integrations/installed_incoming_webhook.test.tsx
  components/more_channels/more_channels.test.tsx
  components/needs_team/needs_team.test.tsx
  components/new_channel_flow/new_channel_flow.test.tsx
  components/next_steps_view/next_steps_view.test.tsx
  components/next_steps_view/steps/complete_profile_step/complete_profile_step.test.tsx
  components/next_steps_view/steps/team_profile_step/team_profile_step.test.tsx
  components/post_view/post_info/__snapshots__/post_info.test.tsx.snap
  components/post_view/post_info/post_info.test.tsx
  components/rhs_comment/__snapshots__/rhs_comment.test.jsx.snap
  components/rhs_root_post/__snapshots__/rhs_root_post.test.jsx.snap
  components/rhs_search_nav/components/user_guide_dropdown/__snapshots__/user_guide_dropdown.test.tsx.snap
  components/rhs_search_nav/components/user_guide_dropdown/user_guide_dropdown.test.tsx
  components/rhs_search_nav/rhs_search_nav.tsx
  components/search/search.tsx
  components/search_hint/__snapshots__/data_retention_hint.test.tsx.snap
  components/search_hint/data_retention_hint.test.tsx
  components/search_hint/data_retention_hint.tsx
  components/search_results/search_results.test.jsx
  components/search_results/search_results.test.tsx
  components/search_results_item/__snapshots__/search_results_item.test.jsx.snap
  components/select_team/select_team.tsx
  components/tutorial/tutorial_tip/tutorial_tip.test.tsx
  components/user_settings/security/user_settings_security.test.tsx
  utils/test_helper.ts
Labels: 4: Reviews Complete

#7769 Fix autocomplete static option case insensitive compare
  components/suggestion/menu_action_provider.jsx
Labels: 4: Reviews Complete, CherryPick/Approved

#7913 Cypress/E2E: Fix CI run of Cypress and add flag to sort specs to test first
  e2e/run_test_cycle.js
  e2e/utils/file.js
Labels: 4: Reviews Complete

#7892 MM-34782 Cypress/E2E: Fix test for forgot password based on new email template
  e2e/cypress/integration/signin_authentication/forgot_password_spec.js
Labels: 4: Reviews Complete

#7896 Cypress/E2E: Add @mfa metadata to specs accordingly
  e2e/cypress/integration/accessibility/accessibility_account_settings_spec.js
  e2e/cypress/integration/auth_sso/authentication_2_spec.js
  e2e/cypress/integration/bot_accounts/bot_api_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/guest_identification_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/system_console_guest_access_ui_spec.js
  e2e/cypress/integration/signin_authentication/authentication_spec.js
Labels: 3: QA Review

#7838 MM-34569 - remove step 3 to guests
  components/next_steps_view/step_helpers.ts
  components/next_steps_view/steps.test.tsx
  components/next_steps_view/steps.ts
Labels: 2: Dev Review, QA Review Done, Setup Cloud + CWS Test Server

#7916 Automated cherry pick of #7769
  components/suggestion/menu_action_provider.jsx
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7699 [MM_20388/ GH_16718] Migrate 'components/signup/signup_email' module and associated tests to TypeScript
  components/signup/signup_email/__snapshots__/signup_email.test.tsx.snap
  components/signup/signup_email/index.ts
  components/signup/signup_email/signup_email.test.tsx
  components/signup/signup_email/signup_email.tsx
Labels: 4: Reviews Complete

#7787 [MM-9695] Added statuses to channel invite modal
  components/channel_invite_modal/__snapshots__/channel_invite_modal.test.tsx.snap
  components/channel_invite_modal/channel_invite_modal.test.tsx
  components/channel_invite_modal/channel_invite_modal.tsx
  components/channel_invite_modal/index.ts
Labels: 4: Reviews Complete

#7918 Prod test fixes
  e2e/cypress/integration/integrations/incoming_webhook/inapp_username_profile_override_spec.js
  e2e/cypress/integration/integrations/incoming_webhook/setting_spec.js
  e2e/cypress/integration/integrations/incoming_webhook/slack_formatting_spec.js
  e2e/cypress/integration/messaging/message_reply_gm_spec.js
Labels: 4: Reviews Complete

#7920 Adding missing Zephyr keys to existing E2E tests
  e2e/cypress/integration/account_settings/display/message_display_mode_spec.js
  e2e/cypress/integration/messaging/long_post_attachments_spec.js
  e2e/cypress/integration/messaging/message_edit_post_with_attachment_spec.js
Labels: 4: Reviews Complete

#7923 Cypress/E2E: Upgrade cypress to v7.1.0 and other dependencies
  e2e/applitools.config.js
  e2e/cypress.json
  e2e/cypress/integration/accessibility/accessibility_post_spec.js
  e2e/cypress/integration/archived_channel/archive_channel_operations_spec.js
  e2e/cypress/integration/archived_channel/archived_channel_spec.js
  e2e/cypress/integration/archived_channel/helpers.js
  e2e/cypress/integration/enterprise/guest_accounts/guest_identification_ui_spec.js
  e2e/cypress/integration/enterprise/visual_regression/helpers.js
  e2e/cypress/integration/enterprise/visual_regression/system_console/about_section_spec.js
  e2e/cypress/integration/enterprise/visual_regression/system_console/authentication_section_spec.js
  e2e/cypress/integration/enterprise/visual_regression/system_console/compliance_section_spec.js
  e2e/cypress/integration/messaging/date_separator_spec.js
  e2e/cypress/integration/messaging/message_reply_bot_post_spec.js
  e2e/cypress/integration/messaging/message_reply_spec.js
  e2e/cypress/integration/messaging/scroll_channel_messages_spec.js
  e2e/cypress/integration/search_filter/input_spec.js
  e2e/cypress/integration/search_filter/mixed_spec.js
  e2e/cypress/integration/search_filter/negative_spec.js
  e2e/cypress/integration/search_filter/on_spec.js
  e2e/cypress/plugins/index.js
  e2e/cypress/support/index.js
  e2e/cypress/support/ui_commands.js
  e2e/cypress/support/visual_commands.d.ts
  e2e/cypress/support/visual_commands.js
  e2e/cypress/tsconfig.json
  e2e/package-lock.json
  e2e/package.json
  e2e/run_tests.js
Labels: 4: Reviews Complete

#7919 Cypress/E2E: Fix test on LDAP groups, code theme and incoming webhook
  e2e/cypress/integration/account_settings/display/code_theme_colors_spec.js
  e2e/cypress/integration/enterprise/integrations/incoming_webhook_spec.js
  e2e/cypress/integration/enterprise/ldap_group/channel_modes_spec.js
  e2e/cypress/integration/enterprise/ldap_group/groups_assign_roles_spec.js
Labels: 3: QA Review

#7931 Fixing keys in Cypress
  e2e/cypress/integration/messaging/header_spec.js
  e2e/cypress/integration/onboarding/existing_email_adress_spec.js
  e2e/cypress/integration/onboarding/tutorial_navigation_and_links_spec.js
  e2e/cypress/integration/search/cleared_search_term_spec.js
  e2e/cypress/integration/search/post_search_display_spec.js
  e2e/cypress/integration/search/results_post_comment_spec.js
Labels: 4: Reviews Complete

#7930 fix subcription typo in the code
  components/announcement_bar/cloud_announcement_bar/user_limit_announcement_bar.tsx
  components/announcement_bar/cloud_trial_announcement_bar/cloud_trial_announcement_bar.tsx
  components/announcement_bar/payment_announcement_bar/payment_announcement_bar.tsx
  components/common/hocs/cloud/with_get_cloud_subscription.test.tsx
  components/common/hocs/cloud/with_get_cloud_subscription.tsx
  components/invitation_modal/invitation_modal_guest_step/invitation_modal_guests_step.jsx
  components/invitation_modal/invitation_modal_members_step/invitation_modal_members_step.jsx
  components/main_menu/main_menu.jsx
Labels: 2: Dev Review

#7894 Mm 34578 add subscribe now button
  components/main_menu/index.jsx
  components/main_menu/main_menu.jsx
  components/main_menu/main_menu.test.jsx
  components/purchase_modal/index.ts
  components/widgets/links/link.scss
  components/widgets/links/upgrade_link.tsx
  components/widgets/menu/menu.tsx
  components/widgets/menu/menu_items/menu_item.scss
  components/widgets/menu/menu_items/menu_top_notification.tsx
  i18n/en.json
Labels: 1: UX Review, 2: Dev Review, Setup Cloud + CWS Test Server

#7718 [MM-19327] Add keyboard shortcut to focus search bar and search in current channel
  components/channel_header/channel_header.js
  components/channel_header/index.js
  components/rhs_search_nav/__snapshots__/rhs_search_nav.test.tsx.snap
  components/rhs_search_nav/rhs_search_nav.tsx
  components/search/index.tsx
  components/search/search.tsx
  components/search/types.ts
Labels: 4: Reviews Complete

#7936 Upgrading tests to prod
  e2e/cypress/integration/archived_channel/archived_leave_channel_spec.js
  e2e/cypress/integration/channel_sidebar/dm_gm_filtering_sorting_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/guest_add_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/guest_popover_ui_spec.js
  e2e/cypress/integration/enterprise/oauth/oauth_spec.js
  e2e/cypress/integration/files_and_attachments/file_preview_audio_spec.js
  e2e/cypress/integration/files_and_attachments/file_preview_generic_spec.js
  e2e/cypress/integration/files_and_attachments/file_preview_image_spec.js
  e2e/cypress/integration/files_and_attachments/file_preview_video_spec.js
  e2e/cypress/integration/integrations/incoming_webhook/webhook_posts_when_creator_not_in_channel_spec.js
  e2e/cypress/integration/interactive_dialog/simple_dialog_spec.js
Labels: 4: Reviews Complete

#7940 MM-34978 - fix contact support link in the error payment screen
  components/purchase_modal/icon_message.scss
  components/purchase_modal/process_payment_setup.tsx
  components/purchase_modal/purchase.scss
  components/purchase_modal/purchase_modal.tsx
Labels: 2: Dev Review, QA Review Done, Setup Cloud + CWS Test Server

#7904 [MM-34551] Make button disabled for Read Only Admin
  components/admin_console/license_settings/__snapshots__/license_settings.test.jsx.snap
  components/admin_console/license_settings/license_settings.jsx
  components/admin_console/license_settings/license_settings.test.jsx
  components/admin_console/license_settings/renew_license_card/renew_license_card.tsx
  components/announcement_bar/renewal_link/renewal_link.tsx
Labels: 4: Reviews Complete, CherryPick/Approved

#7927 [MM-34288] Fix BaseDN typo
  components/admin_console/admin_definition.jsx
  i18n/en.json
Labels: 4: Reviews Complete

#7943 Translations update from Weblate
  i18n/bg.json
  i18n/es.json
  i18n/fr.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
  i18n/zh-CN.json
Labels: 2: Dev Review, 3: QA Review

#7947 Automated cherry pick of #7904
  components/admin_console/license_settings/__snapshots__/license_settings.test.jsx.snap
  components/admin_console/license_settings/license_settings.jsx
  components/admin_console/license_settings/license_settings.test.jsx
  components/admin_console/license_settings/renew_license_card/renew_license_card.tsx
  components/announcement_bar/renewal_link/renewal_link.tsx
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7948 Automated cherry pick of #7927
  components/admin_console/admin_definition.jsx
  i18n/en.json
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7950 MM-34975 - hide payment information to free trial customers
  components/admin_console/admin_definition.jsx
Labels: 4: Reviews Complete, CherryPick/Approved, QA Review Done

#7952 Automated cherry pick of #7950
  components/admin_console/admin_definition.jsx
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7953 MM-35016 - Update payment screen info text
  components/admin_console/billing/payment_info_edit.tsx
  i18n/en.json
Labels: 3: QA Review, CherryPick/Candidate, Setup Cloud + CWS Test Server

#7954 Automated cherry pick of #7953
  components/admin_console/billing/payment_info_edit.tsx
  i18n/en.json
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7949 Cypress/E2E: Fix clock, timezone, local date time specs
  e2e/cypress/integration/account_settings/display/clock_display_mode_spec.js
  e2e/cypress/integration/account_settings/display/timezone_display_mode_spec.js
  e2e/cypress/integration/messaging/local_date_time_spec.js
Labels: 4: Reviews Complete

#7932 Feature/mm 34670
  components/suggestion/switch_channel_provider.jsx
  package-lock.json
  sass/components/_channel-switcher.scss
Labels: 4: Reviews Complete

#7934 [MM-34763][MM-34744][MM-34767] - Fix UX issues with channel navigator and navbar
  sass/components/_popover.scss
  sass/layout/_headers.scss
  sass/layout/_sidebar-left.scss
Labels: 4: Reviews Complete

#7926 [MM-34742][MM-34743][MM-34745] - Hard coded values fixes
  sass/layout/_sidebar-left.scss
  sass/layout/_team-sidebar.scss
Labels: 2: Dev Review, QA Review Done, Setup Cloud Test Server

#7843 MM-23120 Custom status issues
  components/channel_header/__snapshots__/channel_header.test.jsx.snap
  components/channel_header/channel_header.js
  components/custom_status/custom_status.scss
  components/custom_status/custom_status_emoji.tsx
  components/custom_status/custom_status_modal.tsx
  components/legacy_sidebar/header/sidebar_header_dropdown_button.jsx
  components/legacy_sidebar/sidebar_channel_button_or_link/__snapshots__/sidebar_channel_button_or_link.test.jsx.snap
  components/legacy_sidebar/sidebar_channel_button_or_link/sidebar_channel_button_or_link.jsx
  components/post_view/post_header/post_header_custom_status.tsx
  components/profile_popover/profile_popover.jsx
  components/sidebar/sidebar_channel/sidebar_channel_link/sidebar_channel_link.tsx
  components/suggestion/switch_channel_provider.jsx
  components/user_settings/notifications/user_settings_notifications.jsx
  i18n/en.json
  sass/components/_suggestion-list.scss
  sass/layout/_headers.scss
Labels: 4: Reviews Complete, AutoMerge, CherryPick/Approved

#7925 Fix accesibility problems in files/message selectors in hint and RHS
  components/file_search_results/__snapshots__/file_search_result_item.test.tsx.snap
  components/file_search_results/file_search_result_item.scss
  components/file_search_results/file_search_result_item.tsx
  components/search/search.tsx
  components/search_hint/__snapshots__/search_hint.test.tsx.snap
  components/search_hint/search_hint.tsx
  components/search_results/__snapshots__/messages_or_files_selector.test.tsx.snap
  components/search_results/messages_or_files_selector.scss
  components/search_results/messages_or_files_selector.tsx
  sass/components/_search.scss
Labels: 4: Reviews Complete, CherryPick/Approved

#7792 [MM-33900] Take into account menu permissions
  components/channel_members_dropdown/__snapshots__/channel_members_dropdown.test.jsx.snap
  components/channel_members_dropdown/channel_members_dropdown.jsx
  components/team_members_dropdown/__snapshots__/team_members_dropdown.test.tsx.snap
  components/team_members_dropdown/team_members_dropdown.tsx
Labels: 4: Reviews Complete, AutoMerge, Setup Cloud Test Server

#7956 Automated cherry pick of #7925
  components/file_search_results/__snapshots__/file_search_result_item.test.tsx.snap
  components/file_search_results/file_search_result_item.scss
  components/file_search_results/file_search_result_item.tsx
  components/search/search.tsx
  components/search_hint/__snapshots__/search_hint.test.tsx.snap
  components/search_hint/search_hint.tsx
  components/search_results/__snapshots__/messages_or_files_selector.test.tsx.snap
  components/search_results/messages_or_files_selector.scss
  components/search_results/messages_or_files_selector.tsx
  sass/components/_search.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7958 Mm 23120/picking conflicting changes
  components/channel_header/__snapshots__/channel_header.test.jsx.snap
  components/channel_header/channel_header.js
  components/custom_status/custom_status.scss
  components/custom_status/custom_status_emoji.tsx
  components/custom_status/custom_status_modal.tsx
  components/legacy_sidebar/header/sidebar_header_dropdown_button.jsx
  components/legacy_sidebar/sidebar_channel_button_or_link/__snapshots__/sidebar_channel_button_or_link.test.jsx.snap
  components/legacy_sidebar/sidebar_channel_button_or_link/sidebar_channel_button_or_link.jsx
  components/post_view/post_header/post_header_custom_status.tsx
  components/profile_popover/profile_popover.jsx
  components/sidebar/sidebar_channel/sidebar_channel_link/sidebar_channel_link.tsx
  components/suggestion/switch_channel_provider.jsx
  components/user_settings/notifications/user_settings_notifications.jsx
  i18n/en.json
  sass/components/_channel-switcher.scss
  sass/components/_suggestion-list.scss
  sass/layout/_headers.scss
Labels: 4: Reviews Complete, AutoMerge

#7929 MM-32962/MM-32930 Dependency updates
  .storybook/addons.js
  .storybook/config.js
  .storybook/main.js
  .storybook/preview.js
  .storybook/theme.js
  .storybook/webpack.config.js
  components/admin_console/highlight.tsx
  components/admin_console/team_channel_settings/channel/list/channel_list.tsx
  components/admin_console/team_channel_settings/channel/list/channel_row.tsx
  components/admin_console/team_channel_settings/channel/list/index.ts
  components/timestamp/timestamp.tsx
  package-lock.json
  package.json
  storybook/decorator.jsx
  webpack.config.js
Labels: 4: Reviews Complete, Setup Cloud Test Server

#7945 Cypress/E2E: Save code body, error details and screenshots to dashboard when test failed
  e2e/run_test_cycle.js
  e2e/utils/dashboard.js
Labels: 4: Reviews Complete, AutoMerge

#7957 Cypress/E2E: Fix E2E from recent Cloud test run
  e2e/cypress/integration/archived_channel/archive_channel_add_reaction_spec.js
  e2e/cypress/integration/auth_sso/authentication_1_spec.js
  e2e/cypress/integration/auth_sso/authentication_not_cloud_spec.js
  e2e/cypress/integration/enterprise/system_console/limited_console_access_not_cloud_spec.js
  e2e/cypress/integration/enterprise/system_console/limited_console_access_spec.js
  e2e/cypress/integration/enterprise/system_console/openid/openid_spec.js
  e2e/cypress/integration/integrations/slash_commands_spec.js
  e2e/cypress/integration/messaging/autocomplete_spec.js
  e2e/cypress/integration/modals/quick_switcher_spec.js
  e2e/cypress/integration/search/cleared_search_term_spec.js
  e2e/cypress/integration/system_console/main_menu_spec.js
  e2e/cypress/integration/team_settings/join_closed_team_with_not_allowed_email_spec.js
  e2e/cypress/support/ui/menu.d.ts
  e2e/cypress/support/ui/menu.js
  e2e/cypress/support/ui_commands.js
Labels: 4: Reviews Complete

#7955 MM-35021: Only display overflow names in Avatars tooltip
  components/threading/channel_threads/thread_footer/__snapshots__/thread_footer.test.tsx.snap
  components/widgets/users/avatars/__snapshots__/avatars.test.tsx.snap
  components/widgets/users/avatars/avatars.test.tsx
  components/widgets/users/avatars/avatars.tsx
Labels: 4: Reviews Complete

#7924 MM-31717: Remove HTTP clustering
  components/admin_console/__snapshots__/cluster_settings.test.jsx.snap
  components/admin_console/admin_definition.jsx
  components/admin_console/cluster_settings.jsx
  components/admin_console/cluster_settings.test.jsx
  e2e/cypress/integration/enterprise/system_console/cluster_spec.js
  i18n/en.json
  packages/mattermost-redux/src/types/config.ts
Labels: 4: Reviews Complete

#7911 release: add release note section
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 2: Dev Review, release-note-none

#7959 [MM-34838] Remove Ancillary Permissions That Are Purposefully Being Remove
  components/admin_console/system_roles/system_role/system_role.tsx
  packages/mattermost-redux/src/client/client4.ts
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#4924 Fixes GH-13865 : Added a11y popover to memebers list
  components/popover_list_members/__snapshots__/popover_list_members.test.jsx.snap
  components/popover_list_members/popover_list_members.jsx
Labels: 2: Dev Review

#7937 MM - 34503 - new contact sales form option for cloud trial
  components/admin_console/billing/billing_subscriptions/billing_subscriptions.tsx
  components/admin_console/billing/billing_subscriptions/index.tsx
  selectors/cloud.ts
Labels: QA Review Done, Setup Cloud + CWS Test Server, do-not-merge/release-note-label-needed

#7939 MM-34977 - add the correct text to the purchase modal button when trialing
  components/admin_console/billing/billing_summary/billing_summary.tsx
  components/announcement_bar/cloud_trial_announcement_bar/cloud_trial_announcement_bar.tsx
  components/purchase_modal/purchase_modal.tsx
  i18n/en.json
Labels: QA Review Done, Setup Cloud + CWS Test Server, do-not-merge/release-note-label-needed

#7891 MM-34286: Adds missing authz checks.
  components/admin_console/admin_definition.jsx
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#7962 Cypress/E2E: Fix test related to channel switcher and bot display name
  e2e/cypress/integration/bot_accounts/display_name_spec.js
  e2e/cypress/integration/enterprise/elasticsearch_autocomplete/helpers/index.js
  e2e/cypress/integration/keyboard_shortcuts/ctrl_cmd_k_unreads_spec.js
Labels: 4: Reviews Complete, release-note-none

#7964 Cypress/E2E: Fix compliance export test
  e2e/cypress.json
  e2e/cypress/integration/enterprise/system_console/compliance/compliance_export_multiple_post_spec.js
  e2e/cypress/integration/enterprise/system_console/compliance/compliance_export_ui_spec.js
  e2e/cypress/integration/enterprise/system_console/compliance/download_bot_compliance_export_file_spec.js
  e2e/cypress/integration/enterprise/system_console/compliance/download_compliance_export_file_spec.js
  e2e/cypress/integration/enterprise/system_console/compliance/helpers.js
  e2e/cypress/integration/enterprise/system_console/compliance/s3_bucket_storage_spec.js
Labels: 3: QA Review, release-note-none

#7938 MM-31339: add e2e test for only one auto response per day
  e2e/cypress/integration/messaging/message_auto_response_spec.js
Labels: 4: Reviews Complete, release-note-none

#7946 MM-34910 New messages toast should only count root posts
  components/toast_wrapper/index.jsx
  components/toast_wrapper/toast_wrapper.jsx
  packages/mattermost-redux/src/selectors/entities/channels.ts
Labels: 4: Reviews Complete, release-note-none

#7972 Lock CI from /release-5.35
  .circleci/config.yml
  .gitlab-ci.yml
Labels: release-note-none

#7973 Automated cherry pick of #7959
  components/admin_console/system_roles/system_role/system_role.tsx
  packages/mattermost-redux/src/client/client4.ts
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#7969 MM-35074: short circuit slash command hooks
  actions/hooks.js
  actions/hooks.test.js
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, release-note
