Repository mattermost/mattermost-webapp, pull requests merged in 2021-08, with the labels that each got.

#8513 Translations update from Weblate
  i18n/bg.json
  i18n/de.json
  i18n/en_AU.json
  i18n/es.json
  i18n/fr.json
  i18n/hu.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 2: Dev Review, 3: QA Review, release-note-none

#8512 WIP: Global Header UI updates/additions
  components/global/at_mentions_button/at_mentions_button.tsx
  components/global/at_mentions_button/index.ts
  components/global/global_header.scss
  components/global/global_header.tsx
  components/global/global_search_nav/global_search_nav.tsx
  components/global/history_buttons/history_buttons.tsx
  components/global/history_buttons/index.ts
  components/global/product_switcher/index.ts
  components/global/product_switcher/product_switcher.tsx
  components/global/product_switcher_menu/index.ts
  components/global/saved_posts_button/index.ts
  components/global/saved_posts_button/saved_posts_button.tsx
  components/global/settings_button/index.ts
  components/global/settings_button/settings_button.tsx
  components/global/user_guide_dropdown/user_guide_dropdown.tsx
  components/root/root.jsx
  package.json
Labels: Work in Progress, do-not-merge/release-note-label-needed

#8492 [MM-37497] Rename view image modal to file preview modal and change imports
  components/__snapshots__/markdown_image.test.jsx.snap
  components/file_attachment_list/file_attachment_list.tsx
  components/file_preview_modal/__snapshots__/file_preview_modal.test.jsx.snap
  components/file_preview_modal/__snapshots__/image_preview.test.jsx.snap
  components/file_preview_modal/file_preview_modal.jsx
  components/file_preview_modal/file_preview_modal.test.jsx
  components/file_preview_modal/image_preview.jsx
  components/file_preview_modal/image_preview.test.jsx
  components/file_preview_modal/index.js
  components/file_preview_modal/popover_bar/__snapshots__/popover_bar.test.tsx.snap
  components/file_preview_modal/popover_bar/index.ts
  components/file_preview_modal/popover_bar/popover_bar.test.tsx
  components/file_preview_modal/popover_bar/popover_bar.tsx
  components/file_search_results/__snapshots__/file_search_result_item.test.tsx.snap
  components/file_search_results/file_search_result_item.tsx
  components/markdown_image.jsx
  components/markdown_image.test.jsx
  components/post_view/post_image/post_image.jsx
  components/single_image_view/__snapshots__/single_image_view.test.tsx.snap
  components/single_image_view/single_image_view.tsx
Labels: 4: Reviews Complete, release-note-none

#8263 [MM-18945] Migrate 'components/activity_log_modal' and associated tests to TypeScript
  components/activity_log_modal/__snapshots__/activity_log_modal.test.tsx.snap
  components/activity_log_modal/activity_log_modal.test.tsx
  components/activity_log_modal/activity_log_modal.tsx
  components/activity_log_modal/index.ts
Labels: 4: Reviews Complete, release-note-none

#8453 MM-37451 integration of compass-components
  components/global/global_header.tsx
  components/global/product_switcher.tsx
  package-lock.json
  package.json
Labels: 2: Dev Review, Setup Cloud Test Server, release-note-none

#8510 Make rootId prop optional for Textbox
  components/rhs_thread/index.ts
  components/textbox/index.ts
  components/textbox/textbox.tsx
  components/threading/global_threads/thread_item/index.ts
  components/threading/global_threads/thread_pane/thread_pane.tsx
  components/threading/thread_viewer/index.ts
  packages/mattermost-redux/src/selectors/entities/posts.test.js
  packages/mattermost-redux/src/selectors/entities/posts.ts
Labels: 4: Reviews Complete, release-note-none

#8518 ESLint overlay trigger error help message
  .eslintrc.json
  components/channel_header_mobile/channel_info_button/channel_info_button.test.js
  components/overlay_trigger.test.tsx
  components/overlay_trigger.tsx
Labels: 4: Reviews Complete, release-note-none

#8495 MM-36646: reverts post paddings when CRT enabled
  components/channel_layout/center_channel/center_channel.tsx
  sass/components/_post.scss
Labels: 4: Reviews Complete, release-note-none

#8524 Cypress/E2E: Add flag disabling limit to Docker resource when launching chrome, add "@timeout_error" metadata and only remove plugin by ID
  e2e/cypress/integration/emoji/recently_used_emoji_spec.js
  e2e/cypress/integration/plugins/plugin_install_spec.js
  e2e/cypress/integration/plugins/plugin_startup_fail_spec.js
  e2e/cypress/plugins/index.js
Labels: 4: Reviews Complete, release-note-none

#8523 [MM-37460] - Add tip for downloading desktop app to the Getting Started page
  components/next_steps_view/__snapshots__/next_steps_view.test.tsx.snap
  components/next_steps_view/download_section.tsx
  components/next_steps_view/next_steps_tips.tsx
  components/next_steps_view/next_steps_view.tsx
Labels: QA Review Done, Setup Cloud Test Server, release-note-none

#8520 Cypress/E2E: Fix failed tests in prod
  e2e/cypress/fixtures/favicon-mentions-16x16.png
  e2e/cypress/integration/integrations/builtin_commands/common_commands_spec.js
  e2e/cypress/integration/integrations/outgoing_webhook/disable_outgoing_webhook_spec.js
  e2e/cypress/integration/messaging/quick_send_spec.js
  e2e/cypress/integration/notifications/browser_tab_notification_spec.js
Labels: 4: Reviews Complete, release-note-none

#8501 Switch to using @mattermost/compass-icons package
  components/global/product_switcher.tsx
  components/main_menu/main_menu.jsx
  fonts/compass-icons/compass-icons.eot
  fonts/compass-icons/compass-icons.svg
  fonts/compass-icons/compass-icons.ttf
  fonts/compass-icons/compass-icons.woff
  fonts/compass-icons/compass-icons.woff2
  package-lock.json
  package.json
  plugins/test/__snapshots__/main_menu_action.test.jsx.snap
  root.jsx
  sass/base/_compass-icons.scss
  sass/base/_module.scss
  sass/responsive/_mobile.scss
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none

#8525 [MM-37065] - No way to complete onboarding in mobile view
  components/next_steps_view/next_steps_view.scss
Labels: CherryPick/Approved, Setup Cloud Test Server, QA Review Done, release-note-none

#8531 Automated cherry pick of #8525
  components/next_steps_view/next_steps_view.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#8530 Automated cherry pick of #8525
  components/next_steps_view/next_steps_view.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#8521 [MM-37468] Update tutorial dot
  components/create_post/__snapshots__/create_post.test.jsx.snap
  components/create_post/create_post.jsx
  components/main_menu/index.jsx
  components/main_menu/main_menu.jsx
  components/sidebar/__snapshots__/channel_tutorial_tip.test.tsx.snap
  components/sidebar/add_channel_dropdown.tsx
  components/sidebar/add_channel_tutorial_tip.tsx
  components/sidebar/channel_navigator/channel_navigator.tsx
  components/sidebar/channel_navigator/index.ts
  components/sidebar/channel_tutorial_tip.test.tsx
  components/sidebar/channel_tutorial_tip.tsx
  components/sidebar/index.ts
  components/sidebar/sidebar_channel/sidebar_channel_link/sidebar_channel_link.tsx
  components/sidebar/sidebar_header/dropdown/index.ts
  components/sidebar/sidebar_header/dropdown/sidebar_header_dropdown.tsx
  components/sidebar/sidebar_header/dropdown/sidebar_header_dropdown_button.tsx
  components/sidebar/sidebar_header/sidebar_header.tsx
  components/status_dropdown/__snapshots__/status_dropdown.test.tsx.snap
  components/status_dropdown/status_dropdown.scss
  components/status_dropdown/status_dropdown.tsx
  components/tutorial/menu_tutorial_tip.tsx
  components/tutorial/tutorial_tip/__snapshots__/tutorial_tip.test.tsx.snap
  components/tutorial/tutorial_tip/tutorial_tip.tsx
  components/widgets/pulsating_dot/index.tsx
  components/widgets/pulsating_dot/pulsating_dot.scss
  i18n/en.json
  images/tutorialTip.gif
  images/tutorialTipWhite.gif
  plugins/test/__snapshots__/main_menu_action.test.jsx.snap
  sass/components/_tutorial.scss
  utils/constants.jsx
Labels: 2: Dev Review, Setup Cloud Test Server, QA Review Done, release-note

#8399 ApplyTheme Updates – convert older changeCSS JS to CSS variables part 1
  components/admin_console/feature_discovery/feature_discovery.scss
  components/category_modal.scss
  components/collapsed_reply_threads_modal/collapsed_reply_threads_modal.scss
  components/confirm_notify_admin_modal/confirm_notify_admin_modal.scss
  components/hint-toast/hint_toast.scss
  components/invitation_modal/invitation_modal_confirm_step.scss
  components/invitation_modal/invitation_modal_guest_step/invitation_modal_guests_step.scss
  components/invitation_modal/invitation_modal_initial_step.scss
  components/invitation_modal/invitation_modal_members_step/invitation_modal_members_step.scss
  components/next_steps_view/next_steps_view.scss
  components/plugin_marketplace/marketplace_modal.scss
  components/post_view/reaction/reaction.scss
  components/product_notices_modal/product_notices_modal.scss
  components/shortcut_key/shortcut_key.scss
  components/user_limit_modal/user_limit_modal.scss
  components/widgets/badges/badge.scss
  components/widgets/inputs/channels_input.scss
  components/widgets/inputs/users_emails_input.scss
  components/widgets/menu/menu_group.scss
  components/widgets/menu/menu_items/menu_item.scss
  components/widgets/menu/menu_modals/submenu_modal/submenu_modal.scss
  components/widgets/modals/full_screen_modal.scss
  sass/components/_badge.scss
  sass/components/_buttons.scss
  sass/components/_dropdown.scss
  sass/components/_emoji-picker-tabs.scss
  sass/components/_emoticons.scss
  sass/components/_modal.scss
  sass/components/_popover.scss
  sass/components/_post.scss
  sass/components/_react-select.scss
  sass/components/_search.scss
  sass/components/_sidebar-header.scss
  sass/components/_status-icon.scss
  sass/components/_suggestion-list.scss
  sass/layout/_headers.scss
  sass/layout/_legacy-sidebar-left.scss
  sass/layout/_navigation.scss
  sass/layout/_sidebar-left.scss
  sass/layout/_sidebar-menu.scss
  sass/layout/_sidebar-right.scss
  sass/layout/_team-sidebar.scss
  sass/responsive/_mobile.scss
  sass/routes/_settings.scss
  sass/utils/_modifiers.scss
  utils/utils.jsx
Labels: 1: PM Review, Setup Cloud Test Server, QA Review Done, 1: UX Review, release-note-none

#8479 [MM-24733] Removing slack importer from UI
  components/setting_upload.jsx
  components/team_import_tab.jsx
  components/team_settings/team_settings.tsx
  components/team_settings_modal/__snapshots__/team_settings_modal.test.tsx.snap
  components/team_settings_modal/team_settings_modal.tsx
  i18n/en.json
  packages/mattermost-redux/src/client/client4.ts
  utils/utils.jsx
Labels: 4: Reviews Complete, release-note

#8517 Upgrading german to official language
  components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
  i18n/i18n.jsx
Labels: 4: Reviews Complete, release-note

#8529 MM 37062 Add new default branded theme "Denim"
  components/admin_console/admin_definition.jsx
  components/post_view/message_attachments/action_button/action_button.test.tsx
  components/user_settings/display/user_settings_theme/__snapshots__/custom_theme_chooser.test.jsx.snap
  components/user_settings/display/user_settings_theme/custom_theme_chooser.test.jsx
  packages/mattermost-redux/src/constants/preferences.ts
  packages/mattermost-redux/src/selectors/entities/preferences.test.js
  packages/mattermost-redux/src/selectors/entities/preferences.ts
  packages/mattermost-redux/src/types/themes.ts
  packages/mattermost-redux/src/utils/theme_utils.test.js
  packages/mattermost-redux/src/utils/theme_utils.ts
  utils/utils.jsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, QA Review Done, release-note

#8435 [MM-36710] System Console "Data Retention Policies" is not supposed to be team themed
  components/admin_console/data_retention_settings/custom_policy_form/custom_policy_form.scss
  components/admin_console/data_retention_settings/data_retention_settings.scss
  components/admin_console/data_retention_settings/global_policy_form/global_policy_form.scss
  components/admin_console/jobs/table.scss
  components/card/card.scss
  components/payment_form/payment_form.scss
  sass/routes/_admin-console.scss
  sass/routes/_backstage.scss
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, release-note-none

#8536 Automated cherry pick of #8435
  components/admin_console/data_retention_settings/custom_policy_form/custom_policy_form.scss
  components/admin_console/data_retention_settings/data_retention_settings.scss
  components/admin_console/data_retention_settings/global_policy_form/global_policy_form.scss
  components/admin_console/jobs/table.scss
  components/card/card.scss
  components/payment_form/payment_form.scss
  sass/routes/_admin-console.scss
  sass/routes/_backstage.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#8535 Automated cherry pick of #8435
  components/admin_console/data_retention_settings/custom_policy_form/custom_policy_form.scss
  components/admin_console/data_retention_settings/data_retention_settings.scss
  components/admin_console/data_retention_settings/global_policy_form/global_policy_form.scss
  components/admin_console/jobs/table.scss
  components/card/card.scss
  components/payment_form/payment_form.scss
  sass/routes/_admin-console.scss
  sass/routes/_backstage.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#8480 MM-36977 Add PostAriaLabelDiv to reduce Post re-rendering
  components/create_comment/create_comment.jsx
  components/create_post/create_post.jsx
  components/dot_menu/dot_menu.tsx
  components/dot_menu/index.ts
  components/edit_post_modal/edit_post_modal.test.tsx
  components/edit_post_modal/edit_post_modal.tsx
  components/external_image/external_image.tsx
  components/gif_picker/components/Categories/index.jsx
  components/gif_picker/components/SearchItem/index.jsx
  components/message_submit_error.tsx
  components/post_view/combined_user_activity_post/index.ts
  components/post_view/post/__snapshots__/post.test.js.snap
  components/post_view/post/index.ts
  components/post_view/post/post.jsx
  components/post_view/post/post.test.js
  components/post_view/post_aria_label_div.test.jsx
  components/post_view/post_aria_label_div.tsx
  components/post_view/post_attachment_opengraph/post_attachment_opengraph.tsx
  components/post_view/post_body/post_body.jsx
  components/post_view/post_header/post_header.tsx
  components/post_view/post_info/index.ts
  components/post_view/post_info/post_info.tsx
  components/post_view/post_list/__snapshots__/post_list.test.jsx.snap
  components/post_view/post_list/index.js
  components/post_view/post_list/post_list.jsx
  components/post_view/post_list_row/__snapshots__/post_list_row.test.tsx.snap
  components/post_view/post_list_virtualized/latest_post_reader.test.jsx
  components/post_view/post_list_virtualized/latest_post_reader.tsx
  components/post_view/post_list_virtualized/post_list_virtualized.jsx
  components/post_view/post_list_virtualized/post_list_virtualized.test.jsx
  components/rhs_comment/__snapshots__/rhs_comment.test.jsx.snap
  components/rhs_comment/index.ts
  components/rhs_comment/rhs_comment.jsx
  components/rhs_comment/rhs_comment.test.jsx
  components/rhs_root_post/__snapshots__/rhs_root_post.test.jsx.snap
  components/rhs_root_post/index.ts
  components/rhs_root_post/rhs_root_post.jsx
  components/rhs_root_post/rhs_root_post.test.jsx
  components/search_results/search_results.tsx
  components/search_results_item/__snapshots__/search_results_item.test.jsx.snap
  components/search_results_item/index.ts
  components/search_results_item/search_results_item.jsx
  components/search_results_item/search_results_item.test.jsx
  components/threading/thread_viewer/__snapshots__/thread_viewer.test.tsx.snap
  components/threading/thread_viewer/thread_viewer.tsx
  components/toast_wrapper/toast_wrapper.jsx
  packages/mattermost-redux/src/constants/posts.ts
  packages/mattermost-redux/src/selectors/entities/users.ts
  packages/mattermost-redux/src/types/posts.ts
  packages/mattermost-redux/src/utils/post_list.test.js
  packages/mattermost-redux/src/utils/post_list.ts
  utils/paste.tsx
  utils/post_utils.test.jsx
  utils/post_utils.ts
Labels: 4: Reviews Complete, release-note

#8385 Migrate Create Post and Create Comment to typescript
  actions/post_actions.jsx
  actions/views/create_comment.tsx
  components/create_comment/__snapshots__/create_comment.test.jsx.snap
  components/create_comment/create_comment.test.jsx
  components/create_comment/create_comment.tsx
  components/create_comment/index.ts
  components/create_post/__snapshots__/create_post.test.jsx.snap
  components/create_post/create_post.test.jsx
  components/create_post/create_post.tsx
  components/create_post/index.ts
  components/file_upload/file_upload.jsx
  components/textbox.test.tsx
  packages/mattermost-redux/src/actions/posts.ts
  packages/mattermost-redux/src/types/config.ts
  types/actions.ts
  types/store/rhs.ts
  utils/post_utils.ts
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none

#8304 [MM-36175] Permalink previews
  components/admin_console/admin_definition.jsx
  components/post_view/embedded_bindings/embedded_binding/__snapshots__/embedded_binding.test.tsx.snap
  components/post_view/embedded_bindings/embedded_binding/embedded_binding.tsx
  components/post_view/message_attachments/message_attachment/__snapshots__/message_attachment.test.tsx.snap
  components/post_view/message_attachments/message_attachment/message_attachment.tsx
  components/post_view/post_attachment_container/__snapshots__/post_attachment_container.test.tsx.snap
  components/post_view/post_attachment_container/post_attachment_container.test.tsx
  components/post_view/post_attachment_container/post_attachment_container.tsx
  components/post_view/post_body_additional_content/__snapshots__/post_body_additional_content.test.tsx.snap
  components/post_view/post_body_additional_content/post_body_additional_content.test.tsx
  components/post_view/post_body_additional_content/post_body_additional_content.tsx
  components/post_view/post_message_preview/__snapshots__/post_message_preview.test.tsx.snap
  components/post_view/post_message_preview/index.ts
  components/post_view/post_message_preview/post_message_preview.test.tsx
  components/post_view/post_message_preview/post_message_preview.tsx
  components/post_view/post_message_view/post_message_view.tsx
  components/post_view/show_more/__snapshots__/show_more.test.tsx.snap
  components/post_view/show_more/show_more.tsx
  i18n/en.json
  packages/mattermost-redux/src/actions/posts.ts
  packages/mattermost-redux/src/reducers/entities/posts.ts
  packages/mattermost-redux/src/types/posts.ts
  sass/components/_post.scss
  sass/layout/_webhooks.scss
  sass/responsive/_tablet.scss
  utils/utils.jsx
Labels: 4: Reviews Complete

#8546 Translations update from Weblate
  i18n/bg.json
  i18n/de.json
  i18n/en_AU.json
  i18n/es.json
  i18n/fr.json
  i18n/hu.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 2: Dev Review, 3: QA Review, release-note-none

#8547 Upgrading german to official language (#8517)
  components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
  i18n/i18n.jsx
Labels: AutoMerge, release-note-none

#8548 Upgrading german to official language (#8517)
  components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
  i18n/i18n.jsx
Labels: AutoMerge, release-note-none

#8540 [MM-37715] - Hide global header preference when the feature flag is d…
  components/user_settings/display/index.ts
  components/user_settings/display/user_settings_display.test.tsx
  components/user_settings/display/user_settings_display.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#8549 Automated cherry pick of #8540
  components/user_settings/display/index.ts
  components/user_settings/display/user_settings_display.test.tsx
  components/user_settings/display/user_settings_display.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, do-not-merge/release-note-label-needed

#8170 MM-35932: changes strings due to re-packaging
  components/admin_console/feature_discovery/feature_discovery.scss
  components/admin_console/feature_discovery/features/announcement_banner.tsx
  components/admin_console/feature_discovery/features/channels.tsx
  components/admin_console/feature_discovery/features/compliance_export.tsx
  components/admin_console/feature_discovery/features/custom_terms_of_service.tsx
  components/admin_console/feature_discovery/features/data_retention.tsx
  components/admin_console/feature_discovery/features/groups.tsx
  components/admin_console/feature_discovery/features/guest_access.tsx
  components/admin_console/feature_discovery/features/ldap.tsx
  components/admin_console/feature_discovery/features/openid.tsx
  components/admin_console/feature_discovery/features/saml.tsx
  components/admin_console/feature_discovery/features/system_roles.tsx
  components/admin_console/license_settings/__snapshots__/license_settings.test.jsx.snap
  components/admin_console/license_settings/license_settings.jsx
  components/admin_console/license_settings/license_settings.test.jsx
  components/admin_console/license_settings/trial_license_card/trial_license_card.tsx
  components/announcement_bar/configuration_bar/configuration_bar.tsx
  components/system_notice/notices.tsx
  i18n/en.json
Labels: 4: Reviews Complete, release-note-none

#8550 Automated cherry pick of #8406
  components/admin_console/license_settings/license_settings.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#8542 Cypress/E2E Maintenance: Fix broken tests
  e2e/cypress/integration/accessibility/accessibility_image_spec.js
  e2e/cypress/integration/account_settings/general/nickname_spec.js
  e2e/cypress/integration/enterprise/ldap/ldap_guest_spec.js
  e2e/cypress/integration/enterprise/system_console/sidebar_link_navigation_spec.js
  e2e/cypress/integration/enterprise/visual_regression/system_console/authentication_section_spec.js
  e2e/cypress/integration/enterprise/visual_regression/system_console/compliance_section_spec.js
  e2e/cypress/integration/interactive_dialog/full_dialog_spec.js
  e2e/cypress/integration/messaging/message_reaction_spec.js
  e2e/cypress/integration/messaging/strikethrough_spec.js
  e2e/cypress/integration/team_settings/invite_members_spec.js
Labels: 3: QA Review, release-note-none

#8539 MM-37333 - fix info banner colors
  components/alert_banner.scss
Labels: 2: Dev Review, release-note-none, QA Deferred

#8559 Automated cherry pick of #8311
  components/root/root.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#8562 MM-35972 Pull unread thread counts for other teams on websocket reconnect
  actions/websocket_actions.jsx
Labels: 4: Reviews Complete, release-note

#8552 MM-36977 Prevent unnecessary changes to emoji state
  packages/mattermost-redux/src/reducers/entities/emojis.test.js
  packages/mattermost-redux/src/reducers/entities/emojis.ts
  packages/mattermost-redux/src/selectors/entities/emojis.ts
Labels: 4: Reviews Complete, release-note-none

#8544 Mm 37472 product switcher tip
  components/global/hooks.tsx
  components/global/product_switcher.test.tsx
  components/global/product_switcher.tsx
  components/global/product_switcher_tip.tsx
  e2e/cypress/integration/onboarding/tutorial_guided_tour_spec.js
  i18n/en.json
  sass/components/_tutorial.scss
  utils/constants.jsx
Labels: 2: Dev Review, Run E2E Testing, release-note, QA Deferred

#8555 [MM-37614] Webapp threads screen illustration updates
  components/threading/common/balloon_illustration.tsx
  components/threading/common/chat_illustration.tsx
Labels: 4: Reviews Complete, release-note-none

#8563 Mm 37504 - add new invite people button to sidebar channel dropdown
  components/sidebar/__snapshots__/sidebar.test.tsx.snap
  components/sidebar/add_channel_dropdown.tsx
  components/sidebar/channel_navigator/channel_navigator.tsx
  components/sidebar/sidebar.tsx
  components/widgets/menu/menu_items/menu_item.scss
  i18n/en.json
Labels: 2: Dev Review, 3: QA Review, Setup Cloud Test Server, 1: UX Review, release-note-none

#8538 [MM-37716] Drop support for LHS specific bot icons
  components/legacy_sidebar/sidebar_channel/index.js
  components/legacy_sidebar/sidebar_channel/sidebar_channel.jsx
  components/legacy_sidebar/sidebar_channel_button_or_link/sidebar_channel_button_or_link.jsx
  components/legacy_sidebar/sidebar_channel_button_or_link/sidebar_channel_button_or_link_icon.jsx
  components/sidebar/sidebar_channel/sidebar_direct_channel/index.ts
  components/sidebar/sidebar_channel/sidebar_direct_channel/sidebar_direct_channel.test.tsx
  components/sidebar/sidebar_channel/sidebar_direct_channel/sidebar_direct_channel.tsx
  package-lock.json
  package.json
  sass/layout/_legacy-sidebar-left.scss
Labels: 4: Reviews Complete, release-note-none

#8509 [MM-36274] Catch all updates on Global Header with Compass
  components/channel_header/channel_header.js
  components/channel_header/index.js
  components/compass_theme_provider/compass_theme_provider.tsx
  components/custom_status/custom_status.scss
  components/global/at_mentions_button/at_mentions_button.tsx
  components/global/global_header.scss
  components/global/global_header.tsx
  components/global/global_search_nav/global_search_nav.tsx
  components/global/history_buttons/history_buttons.tsx
  components/global/history_buttons/index.ts
  components/global/hooks.tsx
  components/global/product_branding/index.ts
  components/global/product_branding/product_branding.tsx
  components/global/product_switcher.tsx
  components/global/product_switcher_menu/index.ts
  components/global/product_switcher_menu/product_switcher_menu.tsx
  components/global/saved_posts_button/saved_posts_button.tsx
  components/global/settings_button/index.ts
  components/global/settings_button/settings_button.tsx
  components/global/user_guide_dropdown/__snapshots__/user_guide_dropdown.test.tsx.snap
  components/global/user_guide_dropdown/index.ts
  components/global/user_guide_dropdown/user_guide_dropdown.test.tsx
  components/global/user_guide_dropdown/user_guide_dropdown.tsx
  components/main_menu/index.jsx
  components/main_menu/main_menu.jsx
  components/root/root.jsx
  components/search/index.tsx
  components/search/search.tsx
  components/search/types.ts
  components/search_bar/search_bar.tsx
  components/sidebar/channel_navigator/channel_navigator.tsx
  components/sidebar/channel_navigator/index.ts
  components/status_dropdown/__snapshots__/status_dropdown.test.tsx.snap
  components/status_dropdown/index.ts
  components/status_dropdown/status_dropdown.scss
  components/status_dropdown/status_dropdown.test.tsx
  components/status_dropdown/status_dropdown.tsx
  components/threading/global_threads/global_threads.tsx
  components/widgets/users/avatar/avatar.tsx
  i18n/en.json
  sass/components/_search.scss
  types/store/plugins.ts
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none

#8533 [MM-37616] Self-managed: Update email template to new branding - Welcome and Verification email
  images/logo_email_dark.png
  images/welcome_illustration.png
  images/welcome_illustration_new.png
  webpack.config.js
Labels: 2: Dev Review, Setup Cloud Test Server, release-note-none

#8572 improve `ProductSwitcher` product icon rendering
  components/global/product_switcher.tsx
Labels: 2: Dev Review, release-note-none, kind/bug

#8570 Close products menu on switch
  components/global/product_switcher.tsx
  components/global/product_switcher_menu/product_switcher_menu.tsx
Labels: 4: Reviews Complete, release-note-none

#8560 MM-37647 - modify branding svg images for cloud system console
  components/admin_console/billing/billing_history.tsx
  components/admin_console/billing/billing_subscriptions/billing_subscriptions.tsx
  components/admin_console/billing/billing_summary/billing_summary.scss
  components/admin_console/billing/billing_summary/billing_summary.tsx
  components/admin_console/billing/company_info_display.tsx
  components/admin_console/billing/payment_info_display.tsx
  components/common/svg_images_components/cloud_trial.svg.tsx
  components/common/svg_images_components/company.svg.tsx
  components/common/svg_images_components/credit_card.svg.tsx
  components/common/svg_images_components/empty_billing_history.svg.tsx
  components/common/svg_images_components/private_cloud.svg.tsx
  components/common/svg_images_components/upgrade.svg.tsx
  images/free-trial-private-cloud-image.svg
  images/no_billing_history_graphic.svg
  images/no_company_info_graphic.svg
  images/no_payment_info_graphic.svg
Labels: 2: Dev Review, Setup Cloud Test Server, release-note

#8565 Update compass-icon `icon-file-document-outline` to match icon font rename
  components/channel_header/__snapshots__/channel_header.test.jsx.snap
  components/channel_header/channel_header.js
  components/no_results_indicator/no_results_indicator.tsx
  components/search_hint/__snapshots__/search_hint.test.tsx.snap
  components/search_hint/search_hint.tsx
Labels: Setup Cloud Test Server, QA Review Done, 1: UX Review, release-note-none

#8153 Add rest field support
  components/suggestion/command_provider/app_command_parser/app_command_parser.test.ts
  components/suggestion/command_provider/app_command_parser/app_command_parser.ts
  components/suggestion/command_provider/app_command_parser/tests/app_command_parser_test_data.ts
Labels: 4: Reviews Complete, release-note

#8431 Fix help page images
  components/help/components/attaching.tsx
  components/help/components/commands.tsx
  components/help/components/composing.tsx
  components/help/components/formatting.tsx
  components/help/components/mentioning.tsx
  components/help/components/messaging.tsx
  i18n/en.json
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note

#8557 [MM-36842] - Send email invites when clicking Next button in Onboarding
  components/next_steps_view/steps/invite_members_step/invite_members_step.tsx
  e2e/cypress/integration/enterprise/cloud/onboarding/invite_member_by_email_spec.js
Labels: 4: Reviews Complete, Setup Cloud Test Server, QA Review Done, release-note-none

#8556 [MM-37788] - Remove support email step in admin onboarding
  components/next_steps_view/steps.test.tsx
  components/next_steps_view/steps.ts
  components/next_steps_view/steps/enter_support_email/enter_support_email.scss
  components/next_steps_view/steps/enter_support_email/enter_support_email.tsx
  components/next_steps_view/steps/invite_members_step/invite_members_step.tsx
  e2e/cypress/integration/enterprise/cloud/onboarding/cloud_sysadmin_onboarding_spec.js
  e2e/cypress/integration/enterprise/cloud/onboarding/enter_support_email_spec.js
  i18n/en.json
  packages/mattermost-redux/src/action_types/admin.ts
  packages/mattermost-redux/src/actions/admin.ts
  packages/mattermost-redux/src/client/client4.ts
  utils/constants.jsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, QA Review Done, release-note-none

#8528 [MM-37578] - Add setting for onboarding
  components/admin_console/admin_definition.jsx
  components/channel_layout/center_channel/index.ts
  components/channel_view/index.ts
  components/sidebar/sidebar_next_steps/index.ts
  components/sidebar/sidebar_next_steps/sidebar_next_steps.tsx
  components/threading/global_threads/global_threads.tsx
  e2e/cypress/support/api/cloud_default_config.json
  e2e/cypress/support/api/on_prem_default_config.json
  i18n/en.json
  packages/mattermost-redux/src/types/config.ts
Labels: Setup Cloud Test Server, QA Review Done, release-note

#8574 feature: unify channel navigator in web and desktop app
  components/global/global_header.scss
  components/sidebar/channel_navigator/channel_navigator.tsx
Labels: 2: Dev Review, QA Review Done, Setup Cloud + CWS Test Server, release-note

#8452 [MM-36758] Fix App filter and locations
  actions/command.test.js
  components/suggestion/command_provider/app_command_parser/app_command_parser.test.ts
  components/suggestion/command_provider/app_command_parser/app_command_parser.ts
  components/suggestion/command_provider/app_command_parser/tests/app_command_parser_test_data.ts
  packages/mattermost-redux/src/reducers/entities/__snapshots__/apps.test.ts.snap
  packages/mattermost-redux/src/reducers/entities/apps.test.ts
  packages/mattermost-redux/src/utils/apps.ts
Labels: 4: Reviews Complete, release-note

#8553 Mm 37049 cta cloud
  components/admin_console/feature_discovery/feature_discovery.test.tsx
  components/admin_console/feature_discovery/feature_discovery.tsx
  components/admin_console/feature_discovery/index.tsx
  e2e/cypress/integration/system_console/feature_discovery_not_cloud_spec.js
  i18n/en.json
  packages/mattermost-redux/src/selectors/entities/general.ts
  utils/license_utils.jsx
Labels: Setup Cloud Test Server, QA Review Done, release-note

#8578 Mm 37473 settings tip
  components/global/global_header.tsx
  components/global/settings_tip.tsx
  i18n/en.json
  sass/components/_tutorial.scss
  utils/constants.jsx
Labels: 2: Dev Review, QA Review Done, Setup Cloud + CWS Test Server, release-note

#8418 Virtualized Thread Viewer
  components/create_comment/create_comment.tsx
  components/rhs_comment/index.ts
  components/rhs_comment/rhs_comment.jsx
  components/rhs_comment/rhs_comment.test.jsx
  components/sidebar_right/sidebar_right.jsx
  components/threading/thread_viewer/__snapshots__/thread_viewer.test.tsx.snap
  components/threading/thread_viewer/index.ts
  components/threading/thread_viewer/thread_viewer.scss
  components/threading/thread_viewer/thread_viewer.test.tsx
  components/threading/thread_viewer/thread_viewer.tsx
  components/threading/virtualized_thread_viewer/create_comment.tsx
  components/threading/virtualized_thread_viewer/index.ts
  components/threading/virtualized_thread_viewer/reply/index.ts
  components/threading/virtualized_thread_viewer/reply/reply.tsx
  components/threading/virtualized_thread_viewer/root_post/index.ts
  components/threading/virtualized_thread_viewer/root_post/root_post.tsx
  components/threading/virtualized_thread_viewer/thread_viewer_row.tsx
  components/threading/virtualized_thread_viewer/virtualized_thread_viewer.tsx
  e2e/cypress/integration/accessibility/accessibility_keyboard_usability_spec.js
  e2e/cypress/integration/messaging/message_reply_scrollable_spec.js
  packages/mattermost-redux/src/selectors/entities/posts.ts
  packages/mattermost-redux/src/utils/post_list.ts
  selectors/views/threads.ts
  types/external/dynamic-virtualized-list.d.ts
Labels: 4: Reviews Complete, release-note-none

#8249 Filter forms and embedded bindings
  actions/apps.ts
  components/apps_form/apps_form_component.tsx
  components/post_view/embedded_bindings/button_binding/button_binding.tsx
  components/post_view/embedded_bindings/embedded_binding/embedded_binding.tsx
  components/post_view/embedded_bindings/select_binding/select_binding.tsx
  components/suggestion/command_provider/app_command_parser/app_command_parser.ts
  components/suggestion/command_provider/app_command_parser/app_command_parser_dependencies.ts
  packages/mattermost-redux/src/reducers/entities/__snapshots__/apps.test.ts.snap
  packages/mattermost-redux/src/reducers/entities/apps.test.ts
  packages/mattermost-redux/src/reducers/entities/apps.ts
  packages/mattermost-redux/src/utils/apps.test.ts
  packages/mattermost-redux/src/utils/apps.ts
  utils/apps.test.ts
  utils/apps.ts
Labels: 4: Reviews Complete, release-note-none

#8490 [MM-31004] Highlight whole category bounds when holding a channel above a category name
  components/sidebar/sidebar_category/__snapshots__/sidebar_category.test.tsx.snap
  components/sidebar/sidebar_category/sidebar_category.tsx
  e2e/cypress/integration/channel_sidebar/dm_category_spec.js
  sass/layout/_sidebar-left.scss
Labels: 4: Reviews Complete, release-note

#8580 Cypress/E2E: Add CWS option to connect with cloud test server
  e2e/cypress.json
  e2e/cypress/integration/modals/product_notice_spec.js
  e2e/cypress/support/api/cloud_default_config.json
  e2e/cypress/support/api/system.js
  e2e/cypress/support/index.js
Labels: 4: Reviews Complete, release-note-none

#8592 Translations update from Weblate
  i18n/bg.json
  i18n/de.json
  i18n/en_AU.json
  i18n/es.json
  i18n/fr.json
  i18n/hu.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 2: Dev Review, 3: QA Review, release-note-none

#8576 fix product switcher tip position
  components/global/hooks.tsx
  components/global/product_switcher.test.tsx
  components/global/product_switcher.tsx
  components/global/product_switcher_tip.tsx
  components/global/product_switcher_tip/index.tsx
  components/global/product_switcher_tip/product_switcher_tip.test.tsx
  components/global/product_switcher_tip/product_switcher_tip.tsx
  sass/components/_tutorial.scss
Labels: Setup Cloud + CWS Test Server, release-note-none, QA Deferred

#8484 [MM-18391] Removing convert channel endpoint
  components/convert_channel_modal/convert_channel_modal.jsx
  components/convert_channel_modal/index.js
  packages/mattermost-redux/src/actions/channels.test.js
  packages/mattermost-redux/src/actions/channels.ts
  packages/mattermost-redux/src/client/client4.ts
Labels: 4: Reviews Complete, release-note

#8596 Cypress/E2E: Disable onboarding flow by default in Cypress
  e2e/cypress/integration/onboarding/invalidate_pending_email_invitations_spec.js
  e2e/cypress/integration/onboarding/use_team_invite_link_to_sign_up_spec.js
  e2e/cypress/integration/team_settings/closed_team_invite_with_non_mattermost_domain_spec.js
  e2e/cypress/integration/team_settings/closed_team_invite_with_specific_domain_spec.js
  e2e/cypress/integration/team_settings/helpers.js
  e2e/cypress/support/api/cloud_default_config.json
  e2e/cypress/support/api/on_prem_default_config.json
Labels: 2: Dev Review, 3: QA Review, release-note-none

#8526 [MM-12104] Create file preview modal header and footer and new ui changes
  components/code_preview.jsx
  components/file_preview_modal/__snapshots__/file_preview_modal.test.jsx.snap
  components/file_preview_modal/__snapshots__/image_preview.test.jsx.snap
  components/file_preview_modal/file_preview_modal.jsx
  components/file_preview_modal/file_preview_modal.scss
  components/file_preview_modal/file_preview_modal.test.jsx
  components/file_preview_modal/file_preview_modal_footer/__snapshots__/file_preview_modal_footer.test.tsx.snap
  components/file_preview_modal/file_preview_modal_footer/file_preview_modal_footer.scss
  components/file_preview_modal/file_preview_modal_footer/file_preview_modal_footer.test.tsx
  components/file_preview_modal/file_preview_modal_footer/file_preview_modal_footer.tsx
  components/file_preview_modal/file_preview_modal_header/__snapshots__/file_preview_modal_header.test.tsx.snap
  components/file_preview_modal/file_preview_modal_header/file_preview_modal_header.scss
  components/file_preview_modal/file_preview_modal_header/file_preview_modal_header.test.tsx
  components/file_preview_modal/file_preview_modal_header/file_preview_modal_header.tsx
  components/file_preview_modal/file_preview_modal_info/__snapshots__/file_preview_modal_info.test.tsx.snap
  components/file_preview_modal/file_preview_modal_info/file_preview_modal_info.scss
  components/file_preview_modal/file_preview_modal_info/file_preview_modal_info.test.tsx
  components/file_preview_modal/file_preview_modal_info/file_preview_modal_info.tsx
  components/file_preview_modal/file_preview_modal_main_actions/__snapshots__/file_preview_modal_main_actions.test.tsx.snap
  components/file_preview_modal/file_preview_modal_main_actions/file_preview_modal_main_actions.scss
  components/file_preview_modal/file_preview_modal_main_actions/file_preview_modal_main_actions.test.tsx
  components/file_preview_modal/file_preview_modal_main_actions/file_preview_modal_main_actions.tsx
  components/file_preview_modal/file_preview_modal_main_nav/__snapshots__/file_preview_modal_main_nav.test.tsx.snap
  components/file_preview_modal/file_preview_modal_main_nav/file_preview_modal_main_nav.scss
  components/file_preview_modal/file_preview_modal_main_nav/file_preview_modal_main_nav.test.tsx
  components/file_preview_modal/file_preview_modal_main_nav/file_preview_modal_main_nav.tsx
  components/file_preview_modal/image_preview.jsx
  components/file_preview_modal/image_preview.scss
  components/file_preview_modal/image_preview.test.jsx
  components/file_preview_modal/popover_bar/__snapshots__/popover_bar.test.tsx.snap
  components/file_preview_modal/popover_bar/popover_bar.test.tsx
  components/file_preview_modal/popover_bar/popover_bar.tsx
  components/pdf_preview.jsx
  components/pdf_preview.test.jsx
  i18n/en.json
  sass/components/_modal.scss
  sass/responsive/_tablet.scss
  utils/constants.jsx
Labels: 4: Reviews Complete, release-note

#8003 [MM-35167] Display error text under submit buttons
  components/apps_form/__snapshots__/apps_form_component.test.tsx.snap
  components/apps_form/apps_form_component.test.tsx
  components/apps_form/apps_form_component.tsx
  sass/components/_apps-modal.scss
  sass/components/_module.scss
Labels: 4: Reviews Complete, release-note-none

#8593 MM-37455: fix misplaced channel header info popover
  components/channel_header/channel_header.js
Labels: 4: Reviews Complete, release-note-none, kind/bug

#8604 Clean up some unused channel-related code
  actions/global_actions.tsx
  actions/views/channel.js
  actions/views/channel.test.js
  components/admin_console/team_channel_settings/channel/details/__snapshots__/channel_details.test.tsx.snap
  components/admin_console/team_channel_settings/channel/details/channel_details.test.tsx
  components/admin_console/team_channel_settings/channel/details/channel_members/__snapshots__/channel_members.test.tsx.snap
  components/admin_console/team_channel_settings/channel/list/channel_row.test.tsx
  components/channel_header_dropdown/menu_items/toggle_favorite_channel/toggle_favorite_channel.test.tsx
  components/channel_info_modal/channel_info_modal.tsx
  components/channel_invite_modal/channel_invite_modal.test.tsx
  components/channel_members_dropdown/channel_members_dropdown.test.jsx
  components/channel_members_modal/__snapshots__/channel_members_modal.test.tsx.snap
  components/channel_members_modal/channel_members_modal.test.tsx
  components/channel_selector_modal/__snapshots__/channel_selector_modal.test.tsx.snap
  components/data_prefetch/data_prefetch.test.tsx
  components/delete_channel_modal/delete_channel_modal.test.tsx
  components/leave_private_channel_modal/leave_private_channel_modal.test.tsx
  components/more_channels/__snapshots__/more_channels.test.tsx.snap
  components/new_channel_flow/new_channel_flow.tsx
  components/post_view/post_list_row/post_list_row.test.tsx
  components/rhs_thread/__snapshots__/rhs_thread.test.tsx.snap
  components/rhs_thread/rhs_thread.test.tsx
  components/sidebar/sidebar_channel/__snapshots__/sidebar_channel.test.tsx.snap
  components/sidebar/sidebar_channel/sidebar_base_channel/__snapshots__/sidebar_base_channel.test.tsx.snap
  components/sidebar/sidebar_channel/sidebar_base_channel/sidebar_base_channel.test.tsx
  components/sidebar/sidebar_channel/sidebar_channel.test.tsx
  components/sidebar/sidebar_channel/sidebar_channel_link/__snapshots__/sidebar_channel_link.test.tsx.snap
  components/sidebar/sidebar_channel/sidebar_channel_link/sidebar_channel_link.test.tsx
  components/sidebar/sidebar_channel/sidebar_direct_channel/__snapshots__/sidebar_direct_channel.test.tsx.snap
  components/sidebar/sidebar_channel/sidebar_direct_channel/sidebar_direct_channel.test.tsx
  components/sidebar/sidebar_channel_list/sidebar_channel_list.test.tsx
  components/threading/thread_viewer/__snapshots__/thread_viewer.test.tsx.snap
  components/threading/thread_viewer/thread_viewer.test.tsx
  components/unarchive_channel_modal/unarchive_channel_modal.test.tsx
  packages/mattermost-redux/src/action_types/channels.ts
  packages/mattermost-redux/src/reducers/entities/channels.ts
  packages/mattermost-redux/src/types/channels.ts
  utils/test_helper.ts
Labels: 4: Reviews Complete, release-note-none

#8532 [MM-32804] Use npm package for timezones
  components/user_settings/display/index.ts
  components/user_settings/display/manage_timezones/index.ts
  components/user_settings/display/manage_timezones/manage_timezones.test.tsx
  components/user_settings/display/manage_timezones/manage_timezones.tsx
  components/user_settings/display/user_settings_display.test.tsx
  components/user_settings/display/user_settings_display.tsx
  package-lock.json
  package.json
  packages/mattermost-redux/src/actions/general.test.js
  packages/mattermost-redux/src/actions/general.ts
  packages/mattermost-redux/src/actions/timezone.ts
  packages/mattermost-redux/src/client/client4.ts
  packages/mattermost-redux/src/reducers/entities/general.ts
  packages/mattermost-redux/src/selectors/entities/general.ts
  packages/mattermost-redux/src/selectors/entities/timezone.ts
  packages/mattermost-redux/src/store/initial_state.ts
  packages/mattermost-redux/src/types/general.ts
  packages/mattermost-redux/src/utils/timezone_utils.ts
  utils/timezone.jsx
Labels: 4: Reviews Complete, release-note

#8579 Mm 37816
  components/admin_console/feature_discovery/features/images/announcement_banner_svg.tsx
  components/admin_console/feature_discovery/features/images/channels_svg.tsx
  components/admin_console/feature_discovery/features/images/compliance_export_svg.tsx
  components/admin_console/feature_discovery/features/images/custom_terms_of_service_svg.tsx
  components/admin_console/feature_discovery/features/images/data_retention_svg.tsx
  components/admin_console/feature_discovery/features/images/groups_svg.tsx
  components/admin_console/feature_discovery/features/images/guest_access_svg.tsx
  components/admin_console/feature_discovery/features/images/ldap_svg.tsx
  components/admin_console/feature_discovery/features/images/permissions_svg.tsx
  components/admin_console/feature_discovery/features/images/saml_svg.tsx
  components/admin_console/feature_discovery/features/images/system_roles_svg.tsx
Labels: 2: Dev Review, CherryPick/Approved, Setup Cloud + CWS Test Server, release-note, QA Deferred

#8602 update tip placement
  sass/components/_tutorial.scss
Labels: 2: Dev Review, CherryPick/Approved, Setup Cloud Test Server, QA Review Done, release-note-none

#8599 [MM-37932] - Onboarding flow in center channel comes back for existing users
  components/channel_layout/center_channel/index.ts
Labels: CherryPick/Approved, Setup Cloud Test Server, QA Review Done, release-note-none

#8564 Add e2e test update
  e2e/cypress/integration/onboarding/tutorial_guided_tour_spec.js
Labels: 2: Dev Review, release-note-none

#8581 MM-37862: Update product registration
  components/global/global_header.scss
  components/global/global_header.tsx
  components/global/product_switcher_tip/product_switcher_tip.test.tsx
  plugins/registry.js
  types/store/plugins.ts
Labels: 4: Reviews Complete, release-note-none

#8594 MM-37916: close product switcher on item click
  components/global/product_switcher.tsx
  components/global/product_switcher_menu/product_switcher_menu.tsx
  components/widgets/menu/menu_items/menu_item.tsx
  components/widgets/menu/menu_items/menu_item_action.test.tsx
  components/widgets/menu/menu_items/menu_item_action.tsx
Labels: 4: Reviews Complete, release-note-none, kind/bug

#8571 bugfix: Hide HistoryButtons in browser
  components/global/global_header.tsx
  components/global/history_buttons/history_buttons.tsx
Labels: 4: Reviews Complete, release-note-none, kind/bug

#8554 MM-36084 - Certificate Auth: Remove SAML dependency in license check
  components/admin_console/admin_definition.jsx
  packages/mattermost-redux/src/types/general.ts
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, release-note-none

#8614 Automated cherry pick of #8554
  components/admin_console/admin_definition.jsx
  packages/mattermost-redux/src/types/general.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note

#8612 Automated cherry pick of #8599
  components/channel_layout/center_channel/index.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note

#8620 Automated cherry pick of #8532
  components/user_settings/display/index.ts
  components/user_settings/display/manage_timezones/index.ts
  components/user_settings/display/manage_timezones/manage_timezones.test.tsx
  components/user_settings/display/manage_timezones/manage_timezones.tsx
  components/user_settings/display/user_settings_display.test.tsx
  components/user_settings/display/user_settings_display.tsx
  package-lock.json
  package.json
  packages/mattermost-redux/src/actions/general.test.js
  packages/mattermost-redux/src/actions/general.ts
  packages/mattermost-redux/src/actions/timezone.ts
  packages/mattermost-redux/src/client/client4.ts
  packages/mattermost-redux/src/reducers/entities/general.ts
  packages/mattermost-redux/src/selectors/entities/general.ts
  packages/mattermost-redux/src/selectors/entities/timezone.ts
  packages/mattermost-redux/src/store/initial_state.ts
  packages/mattermost-redux/src/types/general.ts
  packages/mattermost-redux/src/utils/timezone_utils.ts
  utils/timezone.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note

#8619 Automated cherry pick of #8484
  components/convert_channel_modal/convert_channel_modal.jsx
  components/convert_channel_modal/index.js
  packages/mattermost-redux/src/actions/channels.test.js
  packages/mattermost-redux/src/actions/channels.ts
  packages/mattermost-redux/src/client/client4.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note

#8613 Automated cherry pick of #8602
  sass/components/_tutorial.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, do-not-merge/release-note-label-needed

#8595 MM-37784: make integrations (backstage) take up the entire viewport
  components/global/global_header.scss
Labels: Setup Cloud Test Server, QA Review Done, release-note-none, kind/bug

#8618 Automated cherry pick of #8526
  components/code_preview.jsx
  components/file_preview_modal/__snapshots__/file_preview_modal.test.jsx.snap
  components/file_preview_modal/__snapshots__/image_preview.test.jsx.snap
  components/file_preview_modal/file_preview_modal.jsx
  components/file_preview_modal/file_preview_modal.scss
  components/file_preview_modal/file_preview_modal.test.jsx
  components/file_preview_modal/file_preview_modal_footer/__snapshots__/file_preview_modal_footer.test.tsx.snap
  components/file_preview_modal/file_preview_modal_footer/file_preview_modal_footer.scss
  components/file_preview_modal/file_preview_modal_footer/file_preview_modal_footer.test.tsx
  components/file_preview_modal/file_preview_modal_footer/file_preview_modal_footer.tsx
  components/file_preview_modal/file_preview_modal_header/__snapshots__/file_preview_modal_header.test.tsx.snap
  components/file_preview_modal/file_preview_modal_header/file_preview_modal_header.scss
  components/file_preview_modal/file_preview_modal_header/file_preview_modal_header.test.tsx
  components/file_preview_modal/file_preview_modal_header/file_preview_modal_header.tsx
  components/file_preview_modal/file_preview_modal_info/__snapshots__/file_preview_modal_info.test.tsx.snap
  components/file_preview_modal/file_preview_modal_info/file_preview_modal_info.scss
  components/file_preview_modal/file_preview_modal_info/file_preview_modal_info.test.tsx
  components/file_preview_modal/file_preview_modal_info/file_preview_modal_info.tsx
  components/file_preview_modal/file_preview_modal_main_actions/__snapshots__/file_preview_modal_main_actions.test.tsx.snap
  components/file_preview_modal/file_preview_modal_main_actions/file_preview_modal_main_actions.scss
  components/file_preview_modal/file_preview_modal_main_actions/file_preview_modal_main_actions.test.tsx
  components/file_preview_modal/file_preview_modal_main_actions/file_preview_modal_main_actions.tsx
  components/file_preview_modal/file_preview_modal_main_nav/__snapshots__/file_preview_modal_main_nav.test.tsx.snap
  components/file_preview_modal/file_preview_modal_main_nav/file_preview_modal_main_nav.scss
  components/file_preview_modal/file_preview_modal_main_nav/file_preview_modal_main_nav.test.tsx
  components/file_preview_modal/file_preview_modal_main_nav/file_preview_modal_main_nav.tsx
  components/file_preview_modal/image_preview.jsx
  components/file_preview_modal/image_preview.scss
  components/file_preview_modal/image_preview.test.jsx
  components/file_preview_modal/popover_bar/__snapshots__/popover_bar.test.tsx.snap
  components/file_preview_modal/popover_bar/popover_bar.test.tsx
  components/file_preview_modal/popover_bar/popover_bar.tsx
  components/pdf_preview.jsx
  components/pdf_preview.test.jsx
  i18n/en.json
  sass/components/_modal.scss
  sass/responsive/_tablet.scss
  utils/constants.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, do-not-merge/release-note-label-needed

#8616 Automated cherry pick of #8577
  components/sidebar/add_channel_dropdown.tsx
  components/widgets/menu/menu_items/menu_item.scss
  i18n/en.json
  sass/layout/_sidebar-left.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, do-not-merge/release-note-label-needed

#8615 Automated cherry pick of #8593
  components/channel_header/channel_header.js
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, do-not-merge/release-note-label-needed

#8611 Automated cherry pick of #8594
  components/global/product_switcher.tsx
  components/global/product_switcher_menu/product_switcher_menu.tsx
  components/widgets/menu/menu_items/menu_item.tsx
  components/widgets/menu/menu_items/menu_item_action.test.tsx
  components/widgets/menu/menu_items/menu_item_action.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, do-not-merge/release-note-label-needed

#8610 Automated cherry pick of #8571
  components/global/global_header.tsx
  components/global/history_buttons/history_buttons.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, do-not-merge/release-note-label-needed

#8588 [MM 37561] Fix dropdown menu theming in System Console
  components/admin_console/data_retention_settings/data_retention_settings.scss
  sass/routes/_admin-console.scss
Labels: 4: Reviews Complete, release-note

#8587 [MM-37669] System console hamburger menu theming issue
  sass/routes/_admin-console.scss
Labels: 4: Reviews Complete, release-note

#8586 [MM-37670] System console about modal missing header border
  sass/routes/_about-modal.scss
Labels: 4: Reviews Complete, release-note

#8626 Automated cherry pick of #8586
  sass/routes/_about-modal.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, do-not-merge/release-note-label-needed

#8625 Automated cherry pick of #8587
  sass/routes/_admin-console.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, do-not-merge/release-note-label-needed

#8624 Automated cherry pick of #8588
  components/admin_console/data_retention_settings/data_retention_settings.scss
  sass/routes/_admin-console.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, do-not-merge/release-note-label-needed

#8623 Automated cherry pick of #8595
  components/global/global_header.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, do-not-merge/release-note-label-needed

#8627 Automated cherry pick of #8581
  components/global/global_header.scss
  components/global/global_header.tsx
  components/global/product_switcher_tip/product_switcher_tip.test.tsx
  plugins/registry.js
  types/store/plugins.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, do-not-merge/release-note-label-needed

#8617 MM-37542: support tooltip react components
  plugins/registry.js
Labels: release-note

#8609 Add timezones.json to the package-lock
  package-lock.json
Labels: 4: Reviews Complete, release-note-none

#8419 [MM-27312] Allow uploading 10 files per post
  .circleci/config.yml
  .gitlab-ci.yml
  components/file_upload/file_upload.test.jsx
  utils/constants.jsx
Labels: 4: Reviews Complete, release-note

#8608 Adds websockets to products
  components/root/root.jsx
Labels: CherryPick/Approved, release-note

#8633 Automated cherry pick of #8608
  components/root/root.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, do-not-merge/release-note-label-needed

#8634 Automated cherry pick of #8419
  components/file_upload/file_upload.test.jsx
  utils/constants.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#8584 [MM-37726] - Self-managed: Update email template to new branding - Invitation email
  images/invite_illustration.png
Labels: 1: PM Review, Setup Cloud + CWS Test Server, release-note-none

#8582 [MM-37725] - Self-managed: Update email template to new branding - Password Reset
  images/forgot_password_illustration.png
Labels: 1: PM Review, Setup Cloud + CWS Test Server, release-note-none

#8607 Update en.json
  components/help/components/messaging.tsx
  i18n/en.json
Labels: 4: Reviews Complete, release-note-none

#8636 Automated cherry pick of #8584
  images/invite_illustration.png
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#8635 Automated cherry pick of #8582
  images/forgot_password_illustration.png
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#8637 Automated cherry pick of #8617
  plugins/registry.js
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#8605 [MM-37157, MM-37159] Add new branding graphics welcome to MM, tips & next steps and shared background
  components/next_steps_view/download_section.tsx
  components/next_steps_view/images/download-apps.svg.tsx
  components/next_steps_view/images/getting-started-svg.tsx
  components/next_steps_view/images/onboarding-bg-svg.tsx
  components/next_steps_view/next_steps_view.scss
  components/widgets/background_pill_symbol/background_pill_symbol.tsx
  components/widgets/background_pill_symbol/index.ts
  images/download-app.svg
Labels: 3: QA Review, Setup Cloud Test Server, release-note-none

#8640 Automated cherry pick of #8609
  package-lock.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#8638 Automated cherry pick of #8605
  components/next_steps_view/download_section.tsx
  components/next_steps_view/images/download-apps.svg.tsx
  components/next_steps_view/images/getting-started-svg.tsx
  components/next_steps_view/images/onboarding-bg-svg.tsx
  components/next_steps_view/next_steps_view.scss
  components/widgets/background_pill_symbol/background_pill_symbol.tsx
  components/widgets/background_pill_symbol/index.ts
  images/download-app.svg
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#8628 Cypress/E2E: Add ability to include or exclude test files
  e2e/generate_test_cycle.js
  e2e/run_tests.js
  e2e/utils/file.js
Labels: 4: Reviews Complete, release-note-none

#8575 only show "integration" and "marketplace" in messaging
  components/global/product_switcher.tsx
  components/global/product_switcher_menu/product_switcher_menu.tsx
Labels: 2: Dev Review, 3: QA Review, Setup Cloud Test Server, 1: UX Review, release-note-none

#8647 Automated cherry pick of #8575
  components/global/product_switcher.tsx
  components/global/product_switcher_menu/product_switcher_menu.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#8573 Mm 37657 migrate cloud purchase screens to new branding
  components/admin_console/billing/billing_subscriptions/billing_subscriptions.scss
  components/admin_console/billing/billing_subscriptions/billing_subscriptions.tsx
  components/common/svg_images_components/credit_card.svg.tsx
  components/common/svg_images_components/payment_failed.svg.tsx
  components/common/svg_images_components/payment_sucess_standard.svg.tsx
  components/error_page/workspace_user_limit_reached.tsx
  components/purchase_modal/icon_message.tsx
  components/purchase_modal/process_payment_setup.tsx
  components/purchase_modal/purchase.scss
  components/purchase_modal/purchase_modal.tsx
  images/cloud/background.svg
  images/cloud/mattermost-cloud.svg
  images/cloud/payment_fail.svg
  images/cloud/payment_success.svg
  images/cloud/processing_payment.svg
  images/upgrade-mattermost-cloud-image.svg
Labels: 4: Reviews Complete, QA Review Done, Setup Cloud + CWS Test Server, release-note

#8561 MM-37600 - disable global header in mobile web views (small viewports)
  components/global/global_header.scss
  components/user_settings/display/index.ts
  selectors/global_header.ts
Labels: 4: Reviews Complete, QA Review Done, Setup Cloud + CWS Test Server, release-note

#8515 MM-36234,MM-37030,MM-37031: CRT, desktop notification settings
  actions/notification_actions.jsx
  actions/notification_actions.test.js
  components/logged_in/index.js
  components/logged_in/logged_in.jsx
  components/user_settings/notifications/desktop_notification_settings.jsx
  components/user_settings/notifications/desktop_notification_settings.test.jsx
  components/user_settings/notifications/email_notification_setting/__snapshots__/email_notification_setting.test.tsx.snap
  components/user_settings/notifications/email_notification_setting/email_notification_setting.test.tsx
  components/user_settings/notifications/email_notification_setting/email_notification_setting.tsx
  components/user_settings/notifications/user_settings_notifications.jsx
  i18n/en.json
  utils/url.test.tsx
  utils/url.tsx
  utils/utils.jsx
Labels: 4: Reviews Complete, release-note-none

#8653 Automated cherry pick of #8621
  components/channel_layout/channel_controller.jsx
  components/root/root.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#8654 Automated cherry pick of #8561
  components/global/global_header.scss
  components/user_settings/display/index.ts
  selectors/global_header.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#8657 Automated cherry pick of #8515
  actions/notification_actions.jsx
  actions/notification_actions.test.js
  components/logged_in/index.js
  components/logged_in/logged_in.jsx
  components/user_settings/notifications/desktop_notification_settings.jsx
  components/user_settings/notifications/desktop_notification_settings.test.jsx
  components/user_settings/notifications/email_notification_setting/__snapshots__/email_notification_setting.test.tsx.snap
  components/user_settings/notifications/email_notification_setting/email_notification_setting.test.tsx
  components/user_settings/notifications/email_notification_setting/email_notification_setting.tsx
  components/user_settings/notifications/user_settings_notifications.jsx
  i18n/en.json
  utils/url.test.tsx
  utils/url.tsx
  utils/utils.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#8650 Cypress/E2E: Follow up fix to finding spec files
  e2e/generate_test_cycle.js
  e2e/run_tests.js
  e2e/utils/file.js
Labels: 4: Reviews Complete, release-note-none

#8642 MM-38011 - select enterprise for first subscribe
  .circleci/config.yml
  .gitlab-ci.yml
  components/purchase_modal/purchase_modal.tsx
Labels: QA Review Done, Setup Cloud + CWS Test Server, release-note-none

#8660 MM-37697 - Updating favicons
  images/favicon/android-chrome-192x192.png
  images/favicon/apple-touch-icon-120x120.png
  images/favicon/apple-touch-icon-144x144.png
  images/favicon/apple-touch-icon-152x152.png
  images/favicon/apple-touch-icon-57x57.png
  images/favicon/apple-touch-icon-60x60.png
  images/favicon/apple-touch-icon-72x72.png
  images/favicon/apple-touch-icon-76x76.png
  images/favicon/favicon-16x16.png
  images/favicon/favicon-32x32.png
  images/favicon/favicon-96x96.png
  images/favicon/favicon-default-16x16.png
  images/favicon/favicon-default-24x24.png
  images/favicon/favicon-default-32x32.png
  images/favicon/favicon-default-64x64.png
  images/favicon/favicon-default-96x96.png
  images/favicon/favicon-mentions-16x16.png
  images/favicon/favicon-mentions-24x24.png
  images/favicon/favicon-mentions-32x32.png
  images/favicon/favicon-mentions-64x64.png
  images/favicon/favicon-mentions-96x96.png
  images/favicon/favicon-unread-16x16.png
  images/favicon/favicon-unread-24x24.png
  images/favicon/favicon-unread-32x32.png
  images/favicon/favicon-unread-64x64.png
  images/favicon/favicon-unread-96x96.png
Labels: 4: Reviews Complete, CherryPick/Approved, AutoMerge, release-note-none

#8661 Automated cherry pick of #8660
  images/favicon/android-chrome-192x192.png
  images/favicon/apple-touch-icon-120x120.png
  images/favicon/apple-touch-icon-144x144.png
  images/favicon/apple-touch-icon-152x152.png
  images/favicon/apple-touch-icon-57x57.png
  images/favicon/apple-touch-icon-60x60.png
  images/favicon/apple-touch-icon-72x72.png
  images/favicon/apple-touch-icon-76x76.png
  images/favicon/favicon-16x16.png
  images/favicon/favicon-32x32.png
  images/favicon/favicon-96x96.png
  images/favicon/favicon-default-16x16.png
  images/favicon/favicon-default-24x24.png
  images/favicon/favicon-default-32x32.png
  images/favicon/favicon-default-64x64.png
  images/favicon/favicon-default-96x96.png
  images/favicon/favicon-mentions-16x16.png
  images/favicon/favicon-mentions-24x24.png
  images/favicon/favicon-mentions-32x32.png
  images/favicon/favicon-mentions-64x64.png
  images/favicon/favicon-mentions-96x96.png
  images/favicon/favicon-unread-16x16.png
  images/favicon/favicon-unread-24x24.png
  images/favicon/favicon-unread-32x32.png
  images/favicon/favicon-unread-64x64.png
  images/favicon/favicon-unread-96x96.png
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#8433 [MM-37051] Company Information test script for system console
  e2e/cypress.json
  e2e/cypress/integration/enterprise/cloud/billing/company_information_free_trial_spec.js
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#8494 First batch of collapsed reply threads e2e tests
  components/rhs_comment/__snapshots__/rhs_comment.test.jsx.snap
  components/rhs_comment/rhs_comment.jsx
  components/threading/global_threads_link/global_threads_link.tsx
  e2e/cypress/integration/collapsed_reply_threads/crt_settings_spec.js
  e2e/cypress/integration/collapsed_reply_threads/following_spec.js
  e2e/cypress/integration/collapsed_reply_threads/replies_spec.js
  e2e/cypress/integration/collapsed_reply_threads/unread_spec.js
  e2e/cypress/support/api/cloud_default_config.json
  e2e/cypress/support/api/on_prem_default_config.json
  e2e/cypress/support/api/preference.d.ts
  e2e/cypress/support/api/preference.js
  e2e/cypress/support/ui/account_settings_modal.d.ts
  e2e/cypress/support/ui/account_settings_modal.js
  e2e/cypress/support/ui/sidebar_left.d.ts
  e2e/cypress/support/ui/sidebar_left.js
  e2e/cypress/support/ui_commands.js
  selectors/views/threads.ts
Labels: release-note-none

#8534 [MM-36943] Fix message attachment fields alignment
  sass/layout/_webhooks.scss
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#8537 [MM-37452] Add query parameter to translate in-product help pages
  components/help/components/attaching.tsx
  components/help/components/commands.tsx
  components/help/components/composing.tsx
  components/help/components/formatting.tsx
  components/help/components/help_links.tsx
  components/help/components/mentioning.tsx
  components/help/components/messaging.tsx
  components/help/types.ts
  components/textbox/textbox_links/index.ts
  components/textbox/textbox_links/textbox_links.tsx
  selectors/i18n.test.js
  selectors/i18n.ts
Labels: 4: Reviews Complete, release-note

#8665 Automated cherry pick of #8534
  sass/layout/_webhooks.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#8666 Automated cherry pick of #8494
  components/rhs_comment/__snapshots__/rhs_comment.test.jsx.snap
  components/rhs_comment/rhs_comment.jsx
  components/threading/global_threads_link/global_threads_link.tsx
  e2e/cypress/integration/collapsed_reply_threads/crt_settings_spec.js
  e2e/cypress/integration/collapsed_reply_threads/following_spec.js
  e2e/cypress/integration/collapsed_reply_threads/replies_spec.js
  e2e/cypress/integration/collapsed_reply_threads/unread_spec.js
  e2e/cypress/support/api/cloud_default_config.json
  e2e/cypress/support/api/on_prem_default_config.json
  e2e/cypress/support/api/preference.d.ts
  e2e/cypress/support/api/preference.js
  e2e/cypress/support/ui/account_settings_modal.d.ts
  e2e/cypress/support/ui/account_settings_modal.js
  e2e/cypress/support/ui/sidebar_left.d.ts
  e2e/cypress/support/ui/sidebar_left.js
  e2e/cypress/support/ui_commands.js
  selectors/views/threads.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#8585 [MM-37785] - Polish global header
  components/custom_status/custom_status.scss
  components/global/global_header.scss
  components/global/global_header.tsx
  components/global/global_search_nav/global_search_nav.tsx
  components/global/history_buttons/history_buttons.tsx
  components/global/product_branding/product_branding.tsx
  components/global/product_switcher.tsx
  components/global/user_guide_dropdown/__snapshots__/user_guide_dropdown.test.tsx.snap
  components/global/user_guide_dropdown/user_guide_dropdown.tsx
  components/main_menu/main_menu.jsx
  components/sidebar/legacy_sidebar_header/dropdown/sidebar_header_dropdown.tsx
  components/status_dropdown/__snapshots__/status_dropdown.test.tsx.snap
  components/status_dropdown/status_dropdown.tsx
  components/widgets/menu/menu_group.scss
  components/widgets/menu/menu_items/menu_item.scss
  components/widgets/menu/menu_items/submenu_item.test.tsx
  components/widgets/menu/menu_items/submenu_item.tsx
  package-lock.json
  package.json
  sass/components/_search.scss
  sass/components/_status-icon.scss
  sass/responsive/_desktop.scss
Labels: 2: Dev Review, 3: QA Review, CherryPick/Approved, 1: UX Review, Setup Cloud + CWS Test Server, release-note-none

#8668 Automated cherry pick of #8585
  components/custom_status/custom_status.scss
  components/global/global_header.scss
  components/global/global_header.tsx
  components/global/global_search_nav/global_search_nav.tsx
  components/global/history_buttons/history_buttons.tsx
  components/global/product_branding/product_branding.tsx
  components/global/product_switcher.tsx
  components/global/user_guide_dropdown/__snapshots__/user_guide_dropdown.test.tsx.snap
  components/global/user_guide_dropdown/user_guide_dropdown.tsx
  components/main_menu/main_menu.jsx
  components/sidebar/legacy_sidebar_header/dropdown/sidebar_header_dropdown.tsx
  components/status_dropdown/__snapshots__/status_dropdown.test.tsx.snap
  components/status_dropdown/status_dropdown.tsx
  components/widgets/menu/menu_group.scss
  components/widgets/menu/menu_items/menu_item.scss
  components/widgets/menu/menu_items/submenu_item.test.tsx
  components/widgets/menu/menu_items/submenu_item.tsx
  package-lock.json
  package.json
  sass/components/_search.scss
  sass/components/_status-icon.scss
  sass/responsive/_desktop.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#8649 [MM-37233] CRT:fix two scrollbar issue in threads view
  components/threading/global_threads/thread_list/thread_list.scss
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#8670 Automated cherry pick of #8649
  components/threading/global_threads/thread_list/thread_list.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#8663 Cypress/E2E: Fixed failed tests on timezone, theme sidebar and navigation
  e2e/cypress/integration/accessibility/accessibility_nav_diff_regions_spec.js
  e2e/cypress/integration/account_settings/display/theme/custom_theme_sidebar_styles_spec.js
  e2e/cypress/integration/account_settings/display/timezone_display_mode_spec.js
  e2e/cypress/utils/timezone.js
  e2e/package-lock.json
  e2e/package.json
Labels: 2: Dev Review, 3: QA Review, release-note-none

#8622 MM-37429 Fix detection of manually sized collapsible images
  components/__snapshots__/markdown_image.test.jsx.snap
  components/markdown_image.jsx
  components/markdown_image.test.jsx
  utils/markdown/helpers.test.js
  utils/markdown/helpers.ts
  utils/markdown/renderer.tsx
  utils/text_formatting_imgs.test.jsx
Labels: 4: Reviews Complete, release-note

#8672 Cypress:e2e/fixed category muting test case
  e2e/cypress/integration/channel_sidebar/helpers.js
  e2e/cypress/support/ui/channel_sidebar.js
Labels: 4: Reviews Complete, release-note-none

#8676 Translations update from Weblate
  i18n/bg.json
  i18n/de.json
  i18n/en_AU.json
  i18n/es.json
  i18n/fr.json
  i18n/hu.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 2: Dev Review, 3: QA Review, release-note-none

#8630 Fix attachment images
  components/markdown_image_expand/markdown_image_expand.tsx
  components/post_view/embedded_bindings/embedded_binding/__snapshots__/embedded_binding.test.tsx.snap
  components/post_view/embedded_bindings/embedded_binding/embedded_binding.tsx
  components/post_view/message_attachments/message_attachment/__snapshots__/message_attachment.test.tsx.snap
  components/post_view/message_attachments/message_attachment/message_attachment.tsx
Labels: 4: Reviews Complete, release-note

#8589 [MM-37351] Split settings modal
  actions/command.test.js
  actions/command.ts
  components/global/settings_button/index.ts
  components/global/settings_button/settings_button.tsx
  components/main_menu/main_menu.jsx
  components/next_steps_view/steps/setup_preferences_step/setup_preferences_step.tsx
  components/profile_popover/__snapshots__/profile_popover.test.tsx.snap
  components/profile_popover/profile_popover.tsx
  components/sidebar/legacy_sidebar_header/dropdown/sidebar_header_dropdown.tsx
  components/sidebar/sidebar_header/dropdown/sidebar_header_dropdown.jsx
  components/status_dropdown/__snapshots__/status_dropdown.test.tsx.snap
  components/status_dropdown/status_dropdown.tsx
  components/user_settings/general/user_settings_general.tsx
  components/user_settings/modal/index.ts
  components/user_settings/modal/user_settings_modal.tsx
  components/user_settings/user_settings.tsx
  i18n/en.json
  plugins/test/__snapshots__/main_menu_action.test.jsx.snap
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#8683 Automated cherry pick of #8589
  actions/command.test.js
  actions/command.ts
  components/global/settings_button/index.ts
  components/global/settings_button/settings_button.tsx
  components/main_menu/main_menu.jsx
  components/next_steps_view/steps/setup_preferences_step/setup_preferences_step.tsx
  components/profile_popover/__snapshots__/profile_popover.test.tsx.snap
  components/profile_popover/profile_popover.tsx
  components/sidebar/legacy_sidebar_header/dropdown/sidebar_header_dropdown.tsx
  components/sidebar/sidebar_header/dropdown/sidebar_header_dropdown.jsx
  components/status_dropdown/__snapshots__/status_dropdown.test.tsx.snap
  components/status_dropdown/status_dropdown.tsx
  components/user_settings/general/user_settings_general.tsx
  components/user_settings/modal/index.ts
  components/user_settings/modal/user_settings_modal.tsx
  components/user_settings/user_settings.tsx
  i18n/en.json
  plugins/test/__snapshots__/main_menu_action.test.jsx.snap
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#8682 added a guard to check for the currentUser in `status_dropdown.tsx`
  components/status_dropdown/status_dropdown.tsx
Labels: 2: Dev Review, CherryPick/Approved, Setup Cloud Test Server, QA Review Done, release-note-none, kind/bug

#8686 Automated cherry pick of #8682
  components/status_dropdown/status_dropdown.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#8606 MM-37961 - update invite members image to new branding
  components/common/svg_images_components/empty_state_themeable.svg.tsx
  components/post_view/channel_intro_message/add_members_button.tsx
  components/post_view/channel_intro_message/channel_intro_message.tsx
  components/post_view/channel_intro_message/index.ts
  components/post_view/channel_intro_message/members_illustration.svg.tsx
Labels: 4: Reviews Complete, CherryPick/Candidate, CherryPick/Approved, QA Review Done, Setup Cloud + CWS Test Server, release-note-none

#8679 fixes color inheritance on highlighted hashtags in RHS
  utils/utils.jsx
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, release-note-none, kind/bug

#8651 active state for iconbuttons in global header
  components/sidebar/sidebar_header/sidebar_header.tsx
  selectors/global_header.ts
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#8694 Automated cherry pick of #8679
  utils/utils.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, do-not-merge/release-note-label-needed

#8696 Automated cherry pick of #8651
  components/sidebar/sidebar_header/sidebar_header.tsx
  selectors/global_header.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#8697 Automated cherry pick of #8687
  components/custom_status/custom_status_suggestion.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none
