Repository mattermost/mattermost-webapp, pull requests merged in 2021-03, with the labels that each got.

#7603 Update links in README.md
  README.md
Labels: 4: Reviews Complete

#7608 Automated cherry pick of #7594
  webpack.config.js
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7610 Automated cherry pick of #7579
  components/invitation_modal/__snapshots__/invitation_modal.test.jsx.snap
  components/invitation_modal/index.js
  components/invitation_modal/invitation_modal.jsx
  components/invitation_modal/invitation_modal.test.jsx
  components/main_menu/index.jsx
  components/main_menu/main_menu.jsx
  components/user_limit_modal/__snapshots__/user_limit_modal.test.tsx.snap
  components/user_limit_modal/index.ts
  components/user_limit_modal/user_limit_modal.test.tsx
  components/user_limit_modal/user_limit_modal.tsx
  components/widgets/links/notify_link.tsx
  i18n/en.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7600 Fix zoom on pdf previews
  components/pdf_preview.jsx
Labels: 4: Reviews Complete, CherryPick/Approved

#7575 MM 32772 - migration import home screen
  components/admin_console/admin_definition.jsx
  components/admin_console/cloud_import/components/import_list.tsx
  components/admin_console/cloud_import/import.svg.tsx
  components/admin_console/cloud_import/import_workspace.scss
  components/admin_console/cloud_import/import_workspace.tsx
  components/admin_console/cloud_import/widgets/__snapshots__/cloud_table.test.tsx.snap
  components/admin_console/cloud_import/widgets/__snapshots__/progress_bar.test.tsx.snap
  components/admin_console/cloud_import/widgets/__snapshots__/status_legend.test.tsx.snap
  components/admin_console/cloud_import/widgets/cloud_table.scss
  components/admin_console/cloud_import/widgets/cloud_table.test.tsx
  components/admin_console/cloud_import/widgets/cloud_table.tsx
  components/admin_console/cloud_import/widgets/progress_bar.scss
  components/admin_console/cloud_import/widgets/progress_bar.test.tsx
  components/admin_console/cloud_import/widgets/progress_bar.tsx
  components/admin_console/cloud_import/widgets/status_legend.scss
  components/admin_console/cloud_import/widgets/status_legend.test.tsx
  components/admin_console/cloud_import/widgets/status_legend.tsx
  components/common/card_container.scss
  components/common/card_container.tsx
  components/common/hooks/set_interval.tsx
  components/widgets/admin_console/admin_header.test.tsx
  components/widgets/admin_console/admin_header.tsx
  i18n/en.json
  images/cloud_spinner.gif
  utils/constants.jsx
Labels: 2: Dev Review, Setup Cloud Test Server

#7613 Automated cherry pick of #7600
  components/pdf_preview.jsx
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7614 Automated cherry pick of #7600
  components/pdf_preview.jsx
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7591 Cypress/E2E: Reorganize and add keys for Elasticsearch autocomplete - users
  e2e/cypress/integration/enterprise/elasticsearch_autocomplete/helpers/index.js
  e2e/cypress/integration/enterprise/elasticsearch_autocomplete/users_in_channel_switcher_spec.js
  e2e/cypress/integration/enterprise/elasticsearch_autocomplete/users_in_message_input_box_spec.js
  e2e/cypress/integration/enterprise/elasticsearch_autocomplete/users_spec.js
Labels: 4: Reviews Complete, AutoMerge

#7556 Handle errors on binding locations
  actions/apps.ts
  actions/command.test.js
  actions/command.ts
  actions/global_actions.tsx
  actions/post_actions.jsx
  components/apps_form/__snapshots__/apps_form_container.test.jsx.snap
  components/apps_form/apps_form.test.jsx
  components/apps_form/apps_form.tsx
  components/apps_form/apps_form_container.test.jsx
  components/apps_form/apps_form_container.tsx
  components/channel_header/__snapshots__/channel_header.test.jsx.snap
  components/dot_menu/__snapshots__/dot_menu.test.jsx.snap
  components/dot_menu/__snapshots__/dot_menu_empty.test.tsx.snap
  components/dot_menu/__snapshots__/dot_menu_mobile.test.tsx.snap
  components/dot_menu/dot_menu.test.jsx
  components/dot_menu/dot_menu.tsx
  components/dot_menu/dot_menu_empty.test.tsx
  components/dot_menu/dot_menu_mobile.test.tsx
  components/dot_menu/index.ts
  components/post_view/embedded_bindings/button_binding/button_binding.test.tsx
  components/post_view/embedded_bindings/button_binding/button_binding.tsx
  components/post_view/embedded_bindings/select_binding/select_binding.test.tsx
  components/post_view/embedded_bindings/select_binding/select_binding.tsx
  components/post_view/post_info/__snapshots__/post_info.test.tsx.snap
  components/rhs_comment/__snapshots__/rhs_comment.test.jsx.snap
  components/rhs_root_post/__snapshots__/rhs_root_post.test.jsx.snap
  components/search_results_item/__snapshots__/search_results_item.test.jsx.snap
  components/suggestion/command_provider/app_command_parser.test.ts
  components/suggestion/command_provider/app_command_parser.ts
  components/suggestion/command_provider/command_provider.tsx
  i18n/en.json
  plugins/channel_header_plug/__snapshots__/channel_header_plug.test.tsx.snap
  plugins/channel_header_plug/channel_header_plug.test.tsx
  plugins/channel_header_plug/channel_header_plug.tsx
  plugins/channel_header_plug/index.ts
  utils/apps.ts
  utils/utils.jsx
Labels: 4: Reviews Complete

#7595 [MM-33132] - Subscription stats are not updated when a user is deactivated/activated
  actions/websocket_actions.jsx
Labels: 4: Reviews Complete, QA Review Done, Setup Cloud + CWS Test Server

#7599 Add refresh websocket event
  actions/websocket_actions.jsx
  utils/constants.jsx
Labels: 2: Dev Review

#7581 [MM-33107][MM-33312] fix rhs over textbox
  sass/layout/_sidebar-right.scss
  sass/responsive/_tablet.scss
Labels: 4: Reviews Complete, CherryPick/Approved

#7616 Automated cherry pick of #7581
  sass/layout/_sidebar-right.scss
  sass/responsive/_tablet.scss
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7525 Updating font size for add people to channel modal
  sass/components/_modal.scss
Labels: 4: Reviews Complete

#7618 Automated cherry pick of #7581
  sass/layout/_sidebar-right.scss
  sass/responsive/_tablet.scss
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7283 support auto rtl detection in browsers
  components/__snapshots__/autosize_textarea.test.jsx.snap
  components/__snapshots__/get_link_modal.test.tsx.snap
  components/autosize_textarea.tsx
  components/channel_header/__snapshots__/channel_header.test.jsx.snap
  components/channel_header/channel_header.js
  components/get_link_modal.tsx
  components/post_view/post_message_view/__snapshots__/post_message_view.test.tsx.snap
  components/post_view/post_message_view/post_message_view.tsx
  components/user_settings/notifications/__snapshots__/manage_auto_responder.test.jsx.snap
  components/widgets/settings/text_setting.test.tsx
  components/widgets/settings/text_setting.tsx
  plugins/test/__snapshots__/post_type.test.jsx.snap
  sass/components/_inputs.scss
  sass/components/_post.scss
Labels: 4: Reviews Complete

#7514 MM-32655 Collapsed threads socket event handling
  actions/websocket_actions.jsx
  components/channel_header/__snapshots__/channel_header.test.jsx.snap
  components/rhs_comment/rhs_comment.jsx
  components/rhs_search_nav/__snapshots__/rhs_search_nav.test.jsx.snap
  components/rhs_search_nav/__snapshots__/rhs_search_nav.test.tsx.snap
  components/rhs_search_nav/rhs_search_nav.test.jsx
  components/rhs_search_nav/rhs_search_nav.test.tsx
  components/rhs_search_nav/rhs_search_nav.tsx
  components/rhs_thread/__snapshots__/rhs_thread.test.tsx.snap
  components/rhs_thread/rhs_thread.tsx
  components/search/search.tsx
  components/sidebar/sidebar_channel/sidebar_channel_link/index.ts
  components/sidebar_right/index.js
  components/sidebar_right/sidebar_right.jsx
  components/threading/global_threads/global_threads.tsx
  components/threading/global_threads/thread_item/thread_item.test.tsx
  components/threading/global_threads/thread_item/thread_item.tsx
  components/threading/global_threads/thread_list/thread_list.tsx
  components/threading/global_threads/thread_pane/thread_pane.test.tsx
  components/threading/global_threads_link/global_threads_link.tsx
  components/threading/thread_viewer/index.ts
  components/threading/thread_viewer/thread_viewer.scss
  components/threading/thread_viewer/thread_viewer.test.tsx
  components/threading/thread_viewer/thread_viewer.tsx
  components/timestamp/timestamp.tsx
  components/user_profile/index.ts
  package-lock.json
  package.json
  utils/constants.jsx
Labels: 2: Dev Review

#7559 update compass font icon
  fonts/compass-icons/compass-icons.eot
  fonts/compass-icons/compass-icons.svg
  fonts/compass-icons/compass-icons.ttf
  fonts/compass-icons/compass-icons.woff
  fonts/compass-icons/compass-icons.woff2
  sass/base/_compass-icons.scss
Labels: 4: Reviews Complete

#7611 Update NOTICE.txt
  NOTICE.txt
Labels: 4: Reviews Complete, AutoMerge, CherryPick/Approved

#7619 Automated cherry pick of #7611
  NOTICE.txt
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7383 Campaign/applytheme sidebar header bg
  sass/components/_emoticons.scss
  sass/components/_modal.scss
  sass/layout/_webhooks.scss
  sass/responsive/_mobile.scss
  utils/utils.jsx
Labels: 4: Reviews Complete, QA Review Done

#7617 [MM-33397] revert lhs ID for backward compatibility
  components/sidebar/sidebar_channel_list/__snapshots__/sidebar_channel_list.test.tsx.snap
  components/sidebar/sidebar_channel_list/sidebar_channel_list.tsx
  e2e/cypress/integration/accessibility/accessibility_keyboard_usability_spec.js
  e2e/cypress/integration/accessibility/accessibility_nav_diff_regions_spec.js
  e2e/cypress/integration/channel/more_channels_spec.js
  e2e/cypress/integration/integrations/builtin_commands/common_commands_spec.js
  e2e/cypress/integration/keyboard_shortcuts/alt_option_plus_up_down_spec.js
  e2e/cypress/integration/notifications/browser_tab_notification_spec.js
  e2e/cypress/integration/notifications/unread_on_public_channel_spec.js
Labels: 4: Reviews Complete, CherryPick/Approved

#7623 Automated cherry pick of #7617
  components/sidebar/sidebar_channel_list/__snapshots__/sidebar_channel_list.test.tsx.snap
  components/sidebar/sidebar_channel_list/sidebar_channel_list.tsx
  e2e/cypress/integration/accessibility/accessibility_keyboard_usability_spec.js
  e2e/cypress/integration/accessibility/accessibility_nav_diff_regions_spec.js
  e2e/cypress/integration/channel/more_channels_spec.js
  e2e/cypress/integration/integrations/builtin_commands/common_commands_spec.js
  e2e/cypress/integration/keyboard_shortcuts/alt_option_plus_up_down_spec.js
  e2e/cypress/integration/notifications/browser_tab_notification_spec.js
  e2e/cypress/integration/notifications/unread_on_public_channel_spec.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7592 Fix issues in Custom Status
  components/channel_header/__snapshots__/channel_header.test.jsx.snap
  components/channel_header/channel_header.js
  components/custom_status/__snapshots__/custom_status_emoji.test.tsx.snap
  components/custom_status/custom_status_emoji.test.tsx
  components/custom_status/custom_status_emoji.tsx
  components/custom_status/custom_status_modal.tsx
  components/emoji/render_emoji.tsx
  components/legacy_sidebar/sidebar_channel_button_or_link/__snapshots__/sidebar_channel_button_or_link.test.jsx.snap
  components/more_direct_channels/__snapshots__/more_direct_channels.test.jsx.snap
  components/post_view/post_header/__snapshots__/post_header.test.tsx.snap
  components/post_view/post_header/post_header.scss
  components/post_view/post_header/post_header.tsx
  components/post_view/post_header/post_header_custom_status.tsx
  components/profile_popover/profile_popover.jsx
  components/rhs_comment/__snapshots__/rhs_comment.test.jsx.snap
  components/rhs_root_post/__snapshots__/rhs_root_post.test.jsx.snap
  components/sidebar/sidebar_channel/sidebar_channel_link/sidebar_channel_link.tsx
  package-lock.json
  selectors/emojis.js
  selectors/views/custom_status.ts
Labels: 4: Reviews Complete, CherryPick/Approved

#7625 Automated cherry pick of #7592
  components/channel_header/__snapshots__/channel_header.test.jsx.snap
  components/channel_header/channel_header.js
  components/custom_status/__snapshots__/custom_status_emoji.test.tsx.snap
  components/custom_status/custom_status_emoji.test.tsx
  components/custom_status/custom_status_emoji.tsx
  components/custom_status/custom_status_modal.tsx
  components/emoji/render_emoji.tsx
  components/legacy_sidebar/sidebar_channel_button_or_link/__snapshots__/sidebar_channel_button_or_link.test.jsx.snap
  components/more_direct_channels/__snapshots__/more_direct_channels.test.jsx.snap
  components/post_view/post_header/__snapshots__/post_header.test.tsx.snap
  components/post_view/post_header/post_header.scss
  components/post_view/post_header/post_header.tsx
  components/post_view/post_header/post_header_custom_status.tsx
  components/profile_popover/profile_popover.jsx
  components/rhs_comment/__snapshots__/rhs_comment.test.jsx.snap
  components/rhs_root_post/__snapshots__/rhs_root_post.test.jsx.snap
  components/sidebar/sidebar_channel/sidebar_channel_link/sidebar_channel_link.tsx
  package-lock.json
  selectors/emojis.js
  selectors/views/custom_status.ts
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7626 Automated cherry pick of #7592
  components/channel_header/__snapshots__/channel_header.test.jsx.snap
  components/channel_header/channel_header.js
  components/custom_status/__snapshots__/custom_status_emoji.test.tsx.snap
  components/custom_status/custom_status_emoji.test.tsx
  components/custom_status/custom_status_emoji.tsx
  components/custom_status/custom_status_modal.tsx
  components/emoji/render_emoji.tsx
  components/legacy_sidebar/sidebar_channel_button_or_link/__snapshots__/sidebar_channel_button_or_link.test.jsx.snap
  components/more_direct_channels/__snapshots__/more_direct_channels.test.jsx.snap
  components/post_view/post_header/__snapshots__/post_header.test.tsx.snap
  components/post_view/post_header/post_header.scss
  components/post_view/post_header/post_header.tsx
  components/post_view/post_header/post_header_custom_status.tsx
  components/profile_popover/profile_popover.jsx
  components/rhs_comment/__snapshots__/rhs_comment.test.jsx.snap
  components/rhs_root_post/__snapshots__/rhs_root_post.test.jsx.snap
  components/sidebar/sidebar_channel/sidebar_channel_link/sidebar_channel_link.tsx
  selectors/emojis.js
  selectors/views/custom_status.ts
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7620 Cypress/E2E: Promote and demote E2E tests
  e2e/cypress/integration/archived_channel/archive_channel_search_spec.js
  e2e/cypress/integration/enterprise/ldap/ldap_login_spec.js
  e2e/cypress/integration/enterprise/system_console/compliance/compliance_export_multiple_post_spec.js
  e2e/cypress/integration/enterprise/system_console/compliance/compliance_export_ui_spec.js
  e2e/cypress/integration/mark_as_unread/mark_gm_as_unread_spec.js
  e2e/cypress/integration/messaging/long_draft_spec.js
  e2e/cypress/integration/messaging/message_edit_post_clear_text_spec.js
  e2e/cypress/integration/messaging/receive_message_on_socket_reconnect_spec.js
  e2e/cypress/integration/messaging/visual_verification_of_tooltips_on_top_nav_channel_icons_posts_spec.js
  e2e/cypress/integration/plugins/upgrade_spec.js
  e2e/cypress/integration/system_console/user_management_spec.js
Labels: 4: Reviews Complete

#7632 Cypress/E2E: Fix timezone display mode spec
  e2e/cypress/integration/account_settings/display/timezone_display_mode_spec.js
Labels: 4: Reviews Complete

#7624 Cypress/E2E: Organize and add keys of Elasticsearch autocomplete for channel
  e2e/cypress/integration/enterprise/elasticsearch_autocomplete/channels_spec.js
  e2e/cypress/integration/enterprise/elasticsearch_autocomplete/channels_with_special_characters_spec.js
  e2e/cypress/integration/enterprise/elasticsearch_autocomplete/helpers/index.js
Labels: 4: Reviews Complete

#7633 Cypress/E2E: Fix channel name tooltips
  e2e/cypress/integration/channel/channel_name_tooltips_spec.js
Labels: 4: Reviews Complete

#7631 Use App id to install App from Marketplace
  actions/marketplace.ts
  components/plugin_marketplace/marketplace_item/marketplace_item_app/__snapshots__/marketplace_item_app.test.tsx.snap
  components/plugin_marketplace/marketplace_item/marketplace_item_app/marketplace_item_app.test.tsx
  components/plugin_marketplace/marketplace_item/marketplace_item_app/marketplace_item_app.tsx
  components/plugin_marketplace/marketplace_list/marketplace_list.tsx
  package-lock.json
  package.json
Labels: 4: Reviews Complete

#7612 All select use AppSelectOption
  components/apps_form/apps_form.test.jsx
  components/apps_form/apps_form_field/apps_form_field.tsx
  components/apps_form/apps_form_field/index.ts
Labels: 4: Reviews Complete

#7639 [No Ticket] Update MMJS Tool
  package-lock.json
  package.json
Labels: 4: Reviews Complete

#7552 MM-32881 : Onboarding flow - Add images to the ‘Tips & Next Steps’ section for admins.
  components/next_steps_view/next_steps_tips.tsx
  components/next_steps_view/next_steps_view.scss
  i18n/en.json
  images/tips_next_steps1.svg
  images/tips_next_steps2.svg
  images/tips_next_steps3.svg
Labels: 2: Dev Review, QA Review Done

#7640 Cypress/E2E: Stabilize file previews specs
  e2e/cypress/integration/files_and_attachments/helpers.js
Labels: 4: Reviews Complete

#7630 MM-24009: remove redux-action-buffer
  package-lock.json
  package.json
  store/index.js
Labels: 4: Reviews Complete, AutoMerge

#7627 [MM-33033] Use box-shadow for create post border instead of border
  sass/components/_post.scss
Labels: 4: Reviews Complete

#7513 fix group modal tests
  components/add_groups_to_channel_modal/add_groups_to_channel_modal.test.tsx
  components/add_groups_to_team_modal/add_groups_to_team_modal.test.tsx
  components/add_groups_to_team_modal/add_groups_to_team_modal.tsx
Labels: 4: Reviews Complete

#7642 Fix channel header dropdown icon size and count
  plugins/channel_header_plug/channel_header_plug.tsx
Labels: 4: Reviews Complete

#7644 Fix multiword select options and keep quotes on complete values
  components/suggestion/command_provider/app_command_parser.test.ts
  components/suggestion/command_provider/app_command_parser.ts
Labels: 4: Reviews Complete

#7628 [MM-35501] Remove Determining Ancillary Permissions from Frontend to Backend
  components/admin_console/system_roles/system_role/system_role.tsx
Labels: 3: QA Review

#7657 Disable check-deps ci step
  .circleci/config.yml
Labels: 4: Reviews Complete

#7646 MM-3295 - remove no longer necessary validation
  components/main_menu/main_menu.jsx
Labels: 2: Dev Review

#7668 Automated cherry pick of #7657
  .circleci/config.yml
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7650 Command send options (user, channel, dynamic and static) as options and not only values.
  actions/command.test.js
  components/suggestion/command_provider/app_command_parser.ts
  i18n/en.json
Labels: 2: Dev Review

#7664 Fix command errors
  actions/command.ts
Labels: 2: Dev Review

#7667 Remove autocomplete of ~ and @ for user and channel suggestions
  components/suggestion/command_provider/app_command_parser.ts
Labels: 2: Dev Review

#7649 only apply theme variable in context of main app
  sass/components/_modal.scss
Labels: 4: Reviews Complete

#7593 [MM-32799] Add About SubSections
  components/admin_console/admin_definition.jsx
  components/admin_console/system_roles/system_role/__snapshots__/system_role_permissions.test.tsx.snap
  components/admin_console/system_roles/system_role/system_role_permissions.tsx
  e2e/cypress/fixtures/console-example-inputs.json
  e2e/cypress/fixtures/system-roles-console-access.json
  e2e/cypress/support/api/role.js
  i18n/en.json
  package-lock.json
  package.json
  plugins/test/__snapshots__/main_menu_action.test.jsx.snap
Labels: 4: Reviews Complete

#7675 Automated cherry pick of #7657
  .circleci/config.yml
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7647 MM-33581 Fix off-by-one error in wrapEmojis
  utils/emoji_utils.test.jsx
  utils/emoji_utils.tsx
Labels: 4: Reviews Complete

#7669 Fixing group to channel modal
  components/add_groups_to_channel_modal/add_groups_to_channel_modal.tsx
Labels: AutoMerge, CherryPick/Approved, QA Review Done, Setup Cloud Test Server

#7682 Automated cherry pick of #7669
  components/add_groups_to_channel_modal/add_groups_to_channel_modal.tsx
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7681 Automated cherry pick of #7669
  components/add_groups_to_channel_modal/add_groups_to_channel_modal.tsx
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7665 [MM-33374] - Adding cloud license to dev environment causes sidebar menu to break
  components/common/hocs/cloud/with_get_cloud_subcription.test.tsx
  components/common/hocs/cloud/with_get_cloud_subcription.tsx
  components/invitation_modal/__snapshots__/invitation_modal.test.jsx.snap
  components/invitation_modal/invitation_modal_guest_step/__snapshots__/invitation_modal_guests_step.test.jsx.snap
  components/invitation_modal/invitation_modal_guest_step/index.ts
  components/invitation_modal/invitation_modal_guest_step/invitation_modal_guests_step.jsx
  components/invitation_modal/invitation_modal_members_step/__snapshots__/invitation_modal_members_step.test.jsx.snap
  components/invitation_modal/invitation_modal_members_step/index.ts
  components/invitation_modal/invitation_modal_members_step/invitation_modal_members_step.jsx
  components/main_menu/__snapshots__/main_menu.test.jsx.snap
  components/main_menu/index.jsx
  components/main_menu/main_menu.jsx
  components/main_menu/main_menu.test.jsx
  plugins/test/main_menu_action.test.jsx
Labels: 4: Reviews Complete

#7436 [MM-20397] Migrated the ChannelSelect component to TypeScript
  components/channel_select/__snapshots__/channel_select.test.tsx.snap
  components/channel_select/channel_select.test.tsx
  components/channel_select/channel_select.tsx
  components/channel_select/index.ts
Labels: 4: Reviews Complete

#7677 Added Guest account test cases
  e2e/cypress/integration/enterprise/guest_accounts/guest_add_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/guest_popover_ui_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/guest_removal_ui_spec.js
Labels: 4: Reviews Complete

#7659 [MM-31132] components/admin_console: enable metrics settings for TE
  components/admin_console/admin_definition.jsx
  components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.jsx.snap
  components/admin_console/admin_sidebar/admin_sidebar.test.jsx
  e2e/cypress/integration/enterprise/system_console/sidebar_link_navigation_spec.js
  e2e/cypress/integration/system_console/sidebar_link_navigation_spec.js
Labels: 4: Reviews Complete

#6609 Feature/MM 25430 show online status in channel switcher
  components/suggestion/switch_channel_provider.jsx
  sass/components/_mentions.scss
  sass/components/_suggestion-list.scss
Labels: 4: Reviews Complete, Setup Cloud Test Server

#7694 NO TICKET Fix broken test on Master
  components/delete_channel_modal/delete_channel_modal.test.tsx
Labels: 4: Reviews Complete

#7635 The pdf zoom level is store independently per file preview
  components/view_image/view_image.jsx
Labels: 4: Reviews Complete

#7676 Fixed prod test cases
  components/status_dropdown/__snapshots__/status_dropdown.test.tsx.snap
  components/status_dropdown/status_dropdown.jsx
  components/widgets/menu/menu_items/menu_item_toggle_modal_redux.tsx
  e2e/cypress/integration/accessibility/accessibility_dropdowns_spec.js
  e2e/cypress/integration/account_settings/display/theme/custom_theme_sidebar_styles_spec.js
  e2e/cypress/integration/channel/more_channels_spec.js
  e2e/cypress/integration/enterprise/profile_popover/profile_popover_spec.js
  e2e/cypress/integration/menus/status_dropdown_spec.js
  e2e/cypress/integration/signin_authentication/forgot_password_spec.js
  e2e/cypress/support/ui/menu.d.ts
  e2e/cypress/support/ui/menu.js
Labels: 4: Reviews Complete, AutoMerge

#7684 use theme variable for disabled select background
  sass/components/_react-select.scss
Labels: 4: Reviews Complete

#7693 MM-33791 - add openId to check for account types
  components/user_settings/security/__snapshots__/user_settings_security.test.tsx.snap
  components/user_settings/security/user_settings_security.test.tsx
  components/user_settings/security/user_settings_security.tsx
  i18n/en.json
Labels: 4: Reviews Complete, AutoMerge

#7564 Custom Status E2E tests
  components/custom_status/custom_status_modal.tsx
  components/post_view/post_header/post_header.scss
  components/profile_popover/profile_popover.jsx
  e2e/cypress/integration/custom_status/custom_status_1_spec.js
  e2e/cypress/integration/custom_status/custom_status_2_spec.js
  e2e/cypress/integration/custom_status/custom_status_3_spec.js
  e2e/cypress/integration/custom_status/custom_status_4_spec.js
  e2e/cypress/integration/custom_status/custom_status_5_spec.js
  e2e/cypress/integration/custom_status/custom_status_6_spec.js
  e2e/cypress/integration/custom_status/helper.js
  e2e/cypress/integration/menus/status_dropdown_spec.js
  e2e/cypress/support/api/status.d.ts
  e2e/cypress/support/api/status.js
  e2e/cypress/support/index.d.ts
Labels: 4: Reviews Complete

#7704 Automated cherry pick of #7693
  components/user_settings/security/__snapshots__/user_settings_security.test.tsx.snap
  components/user_settings/security/user_settings_security.test.tsx
  components/user_settings/security/user_settings_security.tsx
  i18n/en.json
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7520 MM-19925-remove role from user card
  components/admin_console/system_user_detail/__snapshots__/system_user_detail.test.tsx.snap
  components/admin_console/system_user_detail/system_user_detail.tsx
  i18n/en.json
Labels: 3: QA Review

#7645 MM32642 - increase invite others visibility
  components/post_view/channel_intro_message/add_members_button.scss
  components/post_view/channel_intro_message/add_members_button.tsx
  components/post_view/channel_intro_message/channel_intro_message.tsx
  components/post_view/channel_intro_message/index.ts
  components/post_view/channel_intro_message/members_illustration.svg.tsx
  components/widgets/icons/fa_edit_icon.jsx
  i18n/en.json
  package-lock.json
  package.json
  sass/layout/_headers.scss
Labels: 1: UX Review, 2: Dev Review, QA Review Done, Setup Cloud + CWS Test Server

#7680 MM-33330 - fixed SidebarLink background-color on hover
  sass/layout/_sidebar-left.scss
Labels: 4: Reviews Complete

#7622 [MM-32343] Environment SubSection
  components/admin_console/admin_definition.jsx
  components/admin_console/system_roles/system_role/__snapshots__/system_role_permissions.test.tsx.snap
  components/admin_console/system_roles/system_role/system_role_permissions.tsx
  e2e/cypress/fixtures/console-example-inputs.json
  e2e/cypress/fixtures/system-roles-console-access.json
  e2e/cypress/support/api/role.js
  i18n/en.json
  package-lock.json
  package.json
  plugins/test/__snapshots__/main_menu_action.test.jsx.snap
Labels: 3: QA Review

#7709 Promoting regularly passing tests from 03/08 to 03/15
  e2e/cypress/integration/enterprise/elasticsearch_autocomplete/channels_spec.js
  e2e/cypress/integration/enterprise/elasticsearch_autocomplete/channels_with_special_characters_spec.js
  e2e/cypress/integration/enterprise/elasticsearch_autocomplete/renaming_spec.js
  e2e/cypress/integration/enterprise/elasticsearch_autocomplete/renaming_team_spec.js
  e2e/cypress/integration/enterprise/elasticsearch_autocomplete/system_console_spec.js
  e2e/cypress/integration/enterprise/elasticsearch_autocomplete/users_spec.js
  e2e/cypress/integration/enterprise/system_console/search_box_spec.js
  e2e/cypress/integration/enterprise/system_console/support_packet_generation_spec.js
  e2e/cypress/integration/messaging/long_draft_spec.js
  e2e/cypress/integration/messaging/message_edit_post_clear_text_spec.js
  e2e/cypress/integration/messaging/permalink_click_spec.js
Labels: 4: Reviews Complete

#7544 Clarify that System & Team admins can delete posts
  components/admin_console/admin_definition.jsx
  i18n/en.json
Labels: 2: Dev Review, 3: QA Review

#7469 [MM-32429] Content Cards
  components/card/__snapshots__/card.test.tsx.snap
  components/card/card.scss
  components/card/card.stories.tsx
  components/card/card.test.tsx
  components/card/title_and_button_card_header/title_and_button_card_header.tsx
  i18n/en.json
Labels: 1: UX Review, 3: QA Review

#7696 [MM-33796][MM-33780] Updating channel switcher css system console
  sass/components/_channel-switcher.scss
  sass/components/_modal.scss
  sass/components/_react-select.scss
  sass/utils/_variables.scss
Labels: 4: Reviews Complete, AutoMerge, CherryPick/Approved, QA Review Done, Setup Cloud Test Server

#7596 MM-32351: Add Compliance Subsections
  components/admin_console/admin_definition.jsx
  components/admin_console/system_roles/system_role/__snapshots__/system_role_permissions.test.tsx.snap
  components/admin_console/system_roles/system_role/system_role_permissions.tsx
  e2e/cypress/fixtures/console-example-inputs.json
  e2e/cypress/fixtures/system-roles-console-access.json
  e2e/cypress/support/api/role.js
  i18n/en.json
Labels: 3: QA Review

#7686 MM32771 - improve tips and next steps cards
  components/admin_console/admin_console.test.tsx
  components/admin_console/admin_console.tsx
  components/admin_console/index.ts
  components/backstage/components/backstage_navbar.jsx
  components/next_steps_view/__snapshots__/next_steps_view.test.tsx.snap
  components/next_steps_view/images/documents.svg.tsx
  components/next_steps_view/images/incidents.svg.tsx
  components/next_steps_view/images/plugins.svg.tsx
  components/next_steps_view/index.ts
  components/next_steps_view/next_steps_tips.tsx
  components/next_steps_view/next_steps_view.test.tsx
  components/next_steps_view/next_steps_view.tsx
  i18n/en.json
  sass/routes/_admin-console.scss
  sass/routes/_backstage.scss
  sass/utils/_variables.scss
Labels: 1: UX Review, 3: QA Review, Setup Cloud + CWS Test Server

#7714 Only use fake timers for tests that need them
  components/admin_console/system_users/system_users.test.tsx
  components/channel_layout/channel_identifier_router/channel_identifier_router.test.tsx
  components/edit_post_modal/edit_post_modal.test.jsx
  components/suggestion/at_mention_provider/at_mention_provider.test.jsx
  tests/setup.js
Labels: 4: Reviews Complete

#7710 Cypress/E2E: Fix tests for cloud
  e2e/cypress/integration/enterprise/elasticsearch_autocomplete/channels_spec.js
  e2e/cypress/integration/enterprise/elasticsearch_autocomplete/channels_with_special_characters_spec.js
  e2e/cypress/integration/enterprise/elasticsearch_autocomplete/renaming_spec.js
  e2e/cypress/integration/enterprise/elasticsearch_autocomplete/renaming_team_spec.js
  e2e/cypress/integration/enterprise/elasticsearch_autocomplete/system_console_spec.js
  e2e/cypress/integration/enterprise/elasticsearch_autocomplete/users_in_channel_switcher_spec.js
  e2e/cypress/integration/enterprise/elasticsearch_autocomplete/users_in_message_input_box_spec.js
  e2e/cypress/integration/enterprise/elasticsearch_autocomplete/users_spec.js
  e2e/cypress/integration/enterprise/integrations/incoming_webhook_spec.js
  e2e/cypress/integration/enterprise/system_console/compliance/compliance_export_ui_spec.js
  e2e/cypress/integration/enterprise/system_console/compliance/s3_bucket_storage_spec.js
  e2e/cypress/integration/enterprise/system_console/support_packet_generation_spec.js
  e2e/cypress/integration/enterprise/visual_regression/system_console/about_section_spec.js
  e2e/cypress/integration/enterprise/visual_regression/system_console/authentication_section_spec.js
  e2e/cypress/integration/enterprise/visual_regression/system_console/compliance_section_spec.js
  e2e/cypress/integration/system_console/support_packet_generation_spec.js
  e2e/cypress/support/task_commands.js
Labels: 4: Reviews Complete, CherryPick/Approved

#7666 MM-32347 Site Subsections
  components/admin_console/admin_definition.jsx
  components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.jsx.snap
  components/admin_console/system_roles/system_role/__snapshots__/system_role_permissions.test.tsx.snap
  components/admin_console/system_roles/system_role/system_role_permissions.tsx
  e2e/cypress/fixtures/console-example-inputs.json
  e2e/cypress/fixtures/system-roles-console-access.json
  e2e/cypress/support/api/role.js
  i18n/en.json
  package-lock.json
  package.json
  plugins/test/__snapshots__/main_menu_action.test.jsx.snap
Labels: 3: QA Review

#7679 Use type on call path, and minor refactoring
  actions/apps.ts
  actions/command.test.js
  actions/command.ts
  components/apps_form/__snapshots__/apps_form_container.test.jsx.snap
  components/apps_form/apps_form.tsx
  components/apps_form/apps_form_container.test.jsx
  components/apps_form/apps_form_container.tsx
  components/apps_form/index.ts
  components/dot_menu/dot_menu.tsx
  components/dot_menu/index.ts
  components/post_view/embedded_bindings/button_binding/__snapshots__/button_binding.test.tsx.snap
  components/post_view/embedded_bindings/button_binding/button_binding.test.tsx
  components/post_view/embedded_bindings/button_binding/button_binding.tsx
  components/post_view/embedded_bindings/button_binding/index.ts
  components/post_view/embedded_bindings/select_binding/index.ts
  components/post_view/embedded_bindings/select_binding/select_binding.test.tsx
  components/post_view/embedded_bindings/select_binding/select_binding.tsx
  components/suggestion/command_provider/app_command_parser.test.ts
  components/suggestion/command_provider/app_command_parser.ts
  components/suggestion/command_provider/command_provider.test.tsx
  components/suggestion/command_provider/command_provider.tsx
  i18n/en.json
  package-lock.json
  package.json
  plugins/channel_header_plug/channel_header_plug.tsx
  plugins/channel_header_plug/index.ts
  utils/apps.ts
Labels: 2: Dev Review

#7715 MM-33907 - fix admin console heigh and show save buttons
  sass/routes/_admin-console.scss
Labels: 2: Dev Review, QA Review Done, Setup Cloud Test Server

#7636 [MM-32831] Change show-more background to be highlighted on permanlink views
  sass/components/_post.scss
  utils/constants.jsx
  utils/utils.jsx
Labels: 4: Reviews Complete, AutoMerge

#7706 Synchronize app command parser with mobile app
  actions/apps.ts
  actions/command.test.js
  actions/command.ts
  components/apps_form/__snapshots__/apps_form_container.test.jsx.snap
  components/apps_form/apps_form_container.test.jsx
  components/apps_form/apps_form_container.tsx
  components/dot_menu/dot_menu.tsx
  components/post_view/embedded_bindings/button_binding/__snapshots__/button_binding.test.tsx.snap
  components/post_view/embedded_bindings/button_binding/button_binding.test.tsx
  components/post_view/embedded_bindings/button_binding/button_binding.tsx
  components/post_view/embedded_bindings/button_binding/index.ts
  components/post_view/embedded_bindings/select_binding/index.ts
  components/post_view/embedded_bindings/select_binding/select_binding.test.tsx
  components/post_view/embedded_bindings/select_binding/select_binding.tsx
  components/suggestion/command_provider/app_command_parser/app_command_parser.test.ts
  components/suggestion/command_provider/app_command_parser/app_command_parser.ts
  components/suggestion/command_provider/app_command_parser/app_command_parser_dependencies.ts
  components/suggestion/command_provider/app_command_parser/tests/app_command_parser_test_data.ts
  components/suggestion/command_provider/app_command_parser/tests/app_command_parser_test_dependencies.ts
  components/suggestion/command_provider/command_provider.test.tsx
  components/suggestion/command_provider/command_provider.tsx
  i18n/en.json
  plugins/channel_header_plug/channel_header_plug.tsx
  utils/apps.ts
Labels: 4: Reviews Complete

#7671 MM-32350 - Integrations
  components/admin_console/admin_definition.jsx
  components/admin_console/system_roles/system_role/__snapshots__/system_role_permissions.test.tsx.snap
  components/admin_console/system_roles/system_role/system_role_permissions.tsx
  e2e/cypress/fixtures/console-example-inputs.json
  e2e/cypress/fixtures/system-roles-console-access.json
  e2e/cypress/support/api/role.js
  i18n/en.json
  package-lock.json
Labels: 4: Reviews Complete, AutoMerge

#7648 MM-24009: remove redux-offline
  actions/channel_actions.test.js
  components/delete_channel_modal/delete_channel_modal.test.tsx
  components/delete_channel_modal/delete_channel_modal.tsx
  package-lock.json
  package.json
  store/index.js
  utils/network.js
Labels: 4: Reviews Complete

#7716 Fixing site_statistics_spec
  e2e/cypress/integration/system_console/reporting/site_statistics_spec.js
Labels: 4: Reviews Complete

#7711 [MM-33648] - Remove possible confusion point after a member notifies the admin about inviting more users the "Not right now" button remains
  components/confirm_notify_admin_modal/confirm_notify_admin.svg.tsx
  components/confirm_notify_admin_modal/confirm_notify_admin_modal.scss
  components/confirm_notify_admin_modal/confirm_notify_admin_modal.tsx
  components/confirm_notify_admin_modal/index.tsx
  components/user_limit_modal/__snapshots__/user_limit_modal.test.tsx.snap
  components/user_limit_modal/index.ts
  components/user_limit_modal/user_limit_modal.tsx
  components/widgets/links/notify_link.test.tsx
  components/widgets/links/notify_link.tsx
  i18n/en.json
  utils/constants.jsx
Labels: 2: Dev Review, 4: Reviews Complete

#7479 MM-29726 Allow disabling link previews from certain domains
  components/admin_console/admin_definition.jsx
  i18n/en.json
Labels: 4: Reviews Complete

#7719 Scrolling the logout button into view so that it is visible
  e2e/cypress/integration/signin_authentication/login_spec.js
Labels: 4: Reviews Complete

#7653 [MM-20603] Migrate components/team_settings to TypeScript
  components/team_general_tab/team_general_tab.jsx
  components/team_settings/index.ts
  components/team_settings/team_settings.tsx
Labels: 4: Reviews Complete

#7685 MM-30407: improve slow typing
  components/dot_menu/dot_menu.tsx
  components/sidebar/sidebar_category/sidebar_category_menu/__snapshots__/sidebar_category_menu.test.tsx.snap
  components/sidebar/sidebar_category/sidebar_category_menu/sidebar_category_menu.tsx
  components/sidebar/sidebar_category/sidebar_category_sorting_menu/sidebar_category_sorting_menu.tsx
  components/sidebar/sidebar_channel/sidebar_channel_menu/__snapshots__/sidebar_channel_menu.test.tsx.snap
  components/sidebar/sidebar_channel/sidebar_channel_menu/sidebar_channel_menu.test.tsx
  components/sidebar/sidebar_channel/sidebar_channel_menu/sidebar_channel_menu.tsx
  components/widgets/menu/menu_items/submenu_item.test.tsx
  components/widgets/menu/menu_items/submenu_item.tsx
  components/widgets/menu/menu_modals/submenu_modal/__snapshots__/submenu_modal.test.tsx.snap
  components/widgets/menu/menu_modals/submenu_modal/submenu_modal.tsx
  package-lock.json
  package.json
Labels: QA Review Done, Setup Cloud Test Server

#7707 [GH-15906][MM-22844] Add channel_icon for email notification redesign.
  images/channel_icon.png
  webpack.config.js
Labels: 4: Reviews Complete

#7725 Fix status dropdown
  e2e/cypress/integration/menus/status_dropdown_spec.js
  e2e/cypress/integration/system_console/environment_spec.js
Labels: 3: QA Review

#7660 Adding subsection permissions for Authentication
  components/admin_console/admin_definition.jsx
  components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.jsx.snap
  components/admin_console/system_roles/system_role/__snapshots__/system_role_permissions.test.tsx.snap
  components/admin_console/system_roles/system_role/system_role_permissions.tsx
  e2e/cypress/fixtures/console-example-inputs.json
  e2e/cypress/fixtures/system-roles-console-access.json
  e2e/cypress/support/api/role.js
  i18n/en.json
Labels: 2: Dev Review, 3: QA Review

#7728 Demoting consistently failing tests from prod to unstable
  e2e/cypress/integration/emoji/custom_emoji_2_spec.js
  e2e/cypress/integration/emoji/custom_emoji_3_spec.js
  e2e/cypress/integration/enterprise/system_console/compliance/s3_bucket_storage_spec.js
  e2e/cypress/integration/integrations/incoming_webhook/webhook_posts_when_creator_not_in_channel_spec.js
  e2e/cypress/integration/messaging/pinned_posts_spec.js
  e2e/cypress/integration/search_autocomplete/users_spec.js
  e2e/cypress/integration/signin_authentication/forgot_password_spec.js
  e2e/cypress/integration/toast/permalink_jump_to_spec.js
  e2e/cypress/integration/toast/permalink_post_spec.js
Labels: 4: Reviews Complete

#7730 Automated cherry pick of #7686
  components/admin_console/admin_console.test.tsx
  components/admin_console/admin_console.tsx
  components/admin_console/index.ts
  components/backstage/components/backstage_navbar.jsx
  components/next_steps_view/__snapshots__/next_steps_view.test.tsx.snap
  components/next_steps_view/images/documents.svg.tsx
  components/next_steps_view/images/incidents.svg.tsx
  components/next_steps_view/images/plugins.svg.tsx
  components/next_steps_view/index.ts
  components/next_steps_view/next_steps_tips.tsx
  components/next_steps_view/next_steps_view.test.tsx
  components/next_steps_view/next_steps_view.tsx
  i18n/en.json
  sass/routes/_admin-console.scss
  sass/routes/_backstage.scss
  sass/utils/_variables.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7731 Automated cherry pick of #7645
  components/post_view/channel_intro_message/add_members_button.scss
  components/post_view/channel_intro_message/add_members_button.tsx
  components/post_view/channel_intro_message/channel_intro_message.tsx
  components/post_view/channel_intro_message/index.ts
  components/post_view/channel_intro_message/members_illustration.svg.tsx
  components/widgets/icons/fa_edit_icon.jsx
  i18n/en.json
  package-lock.json
  package.json
  sass/layout/_headers.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7516 [MM-31411][MM-32164] - Add profile picture to Direct Channels link
  components/profile_picture/__snapshots__/profile_picture.test.tsx.snap
  components/profile_picture/profile_picture.tsx
  components/sidebar/sidebar_channel/sidebar_direct_channel/__snapshots__/sidebar_direct_channel.test.tsx.snap
  components/sidebar/sidebar_channel/sidebar_direct_channel/sidebar_direct_channel.test.tsx
  components/sidebar/sidebar_channel/sidebar_direct_channel/sidebar_direct_channel.tsx
  sass/components/_badge.scss
  sass/layout/_sidebar-left.scss
Labels: 4: Reviews Complete, Setup Cloud Test Server

#7740 MM-33907 - fix admin console heigh and show save buttons
  sass/routes/_admin-console.scss
Labels: 4: Reviews Complete, AutoMerge, Changelog/Not Needed, Docs/Not Needed

#7742 MM-25140 Update build Docker image to Node 14
  build/Dockerfile
Labels: 4: Reviews Complete

#7734 [MM-33609] - Fix team icon coverage on firefox
  components/widgets/team_icon/team_icon.scss
Labels: 2: Dev Review, QA Review Done, Setup Cloud Test Server

#7727 Updating status_dropdown_spec with missing test cases
  e2e/cypress/fixtures/theme.json
  e2e/cypress/integration/menus/status_dropdown_spec.js
  e2e/cypress/support/api/cloud_default_config.json
  e2e/cypress/support/api/on_prem_default_config.json
Labels: 2: Dev Review, 3: QA Review

#7643 Use Feature flag
  actions/command.test.js
  utils/apps.ts
Labels: 2: Dev Review

#7722 Case independency fixes
  components/suggestion/command_provider/app_command_parser/app_command_parser.ts
Labels: 4: Reviews Complete

#7651 Remove Enable/Disable and Remove from System Console for cloud apps
  components/admin_console/custom_plugin_settings/index.js
  components/admin_console/plugin_management/__snapshots__/plugin_management.test.tsx.snap
  components/admin_console/plugin_management/index.ts
  components/admin_console/plugin_management/plugin_management.test.tsx
  components/admin_console/plugin_management/plugin_management.tsx
  utils/apps.ts
Labels: 2: Dev Review, 3: QA Review

#7752 [MM-33171] Admin guide link should be different for cloud or on-premise instances
  components/admin_console/admin_navbar_dropdown/admin_navbar_dropdown.tsx
  components/admin_console/admin_navbar_dropdown/index.ts
Labels: 2: Dev Review, QA Review Done, Setup Cloud + CWS Test Server

#6913 [MM-22840/GH-14198] DMs (More dialog): show recent 20 with relative timestamp
  babel.config.js
  components/admin_console/group_settings/group_details/group_users.test.jsx
  components/more_direct_channels/__snapshots__/group_message_option.test.jsx.snap
  components/more_direct_channels/__snapshots__/more_direct_channels.test.jsx.snap
  components/more_direct_channels/group_message_option.test.jsx
  components/more_direct_channels/group_message_option.tsx
  components/more_direct_channels/index.ts
  components/more_direct_channels/more_direct_channels.test.jsx
  components/more_direct_channels/more_direct_channels.tsx
  components/multiselect/multiselect.tsx
  components/multiselect/multiselect_list.tsx
  package-lock.json
  package.json
  sass/components/_modal.scss
Labels: 4: Reviews Complete

#7745 [MM-34183] - Getting Started Step 3 (Invite members to team) for new users on paid Workspace above 10 users are unable to invite members via email
  components/next_steps_view/steps/invite_members_step/invite_members_step.test.tsx
  components/next_steps_view/steps/invite_members_step/invite_members_step.tsx
Labels: 4: Reviews Complete, QA Review Done

#7695 [MM-29959] restrict 'Manage Roles' button to system admins
  components/admin_console/system_users/system_users_dropdown/__snapshots__/system_users_dropdown.test.tsx.snap
  components/admin_console/system_users/system_users_dropdown/system_users_dropdown.test.tsx
  components/admin_console/system_users/system_users_dropdown/system_users_dropdown.tsx
Labels: AutoMerge, Setup Cloud Test Server

#7641 Remove Custom statuses feature flag
  components/admin_console/admin_definition.jsx
Labels: 4: Reviews Complete

#7754 MM-34017 Fix E2E for file previews
  e2e/cypress/integration/files_and_attachments/file_preview_audio_spec.js
  e2e/cypress/integration/files_and_attachments/file_preview_generic_spec.js
  e2e/cypress/integration/files_and_attachments/file_preview_image_spec.js
  e2e/cypress/integration/files_and_attachments/file_preview_video_spec.js
  e2e/cypress/integration/files_and_attachments/file_previews_1_spec.js
  e2e/cypress/integration/files_and_attachments/file_previews_2_spec.js
  e2e/cypress/integration/files_and_attachments/file_previews_3_spec.js
  e2e/cypress/integration/files_and_attachments/file_previews_4_spec.js
  e2e/cypress/integration/files_and_attachments/file_previews_5_spec.js
  e2e/cypress/integration/files_and_attachments/helpers.js
Labels: 4: Reviews Complete

#7760 MM-34235 - remove trailing slash causing nav bar to hide
  components/next_steps_view/next_steps_tips.tsx
Labels: 2: Dev Review, 3: QA Review, Setup Cloud + CWS Test Server

#7762 [GH-15906][MM-22844] Change channel_icon for email notification redesign.
  images/channel_icon.png
Labels: 4: Reviews Complete

#7756 [MM-33102] Don't show warning and Fix support Link on Cloud
  components/commercial_support_modal/__snapshots__/commercial_support_modal.test.tsx.snap
  components/commercial_support_modal/commercial_support_modal.test.tsx
  components/commercial_support_modal/commercial_support_modal.tsx
  components/commercial_support_modal/index.ts
  i18n/en.json
Labels: 3: QA Review, Setup Cloud + CWS Test Server

#7741 MM-25140 Fix unit tests which are broken on Node 14
  components/add_groups_to_channel_modal/add_groups_to_channel_modal.tsx
  components/add_groups_to_team_modal/add_groups_to_team_modal.tsx
  components/data_prefetch/data_prefetch.test.tsx
Labels: 4: Reviews Complete

#7766 MM-34114 - grab users stats on demand to fix invite buttons logic
  components/post_view/channel_intro_message/add_members_button.tsx
  components/post_view/channel_intro_message/channel_intro_message.tsx
  components/post_view/channel_intro_message/index.ts
Labels: 2: Dev Review, QA Review Done, Setup Cloud + CWS Test Server

#7744 MM-18107: Precursory refactoring and supporting code
  actions/views/profile_popover.js
  components/async_load.jsx
  components/at_mention/at_mention.jsx
  components/channel_header/__snapshots__/channel_header.test.jsx.snap
  components/channel_header/channel_header.js
  components/create_comment/__snapshots__/create_comment.test.jsx.snap
  components/create_comment/create_comment.jsx
  components/create_post/__snapshots__/create_post.test.jsx.snap
  components/create_post/create_post.jsx
  components/file_upload/file_upload.jsx
  components/file_upload/file_upload.test.jsx
  components/file_upload/index.js
  components/markdown/index.ts
  components/markdown/markdown.tsx
  components/no_results_indicator/index.ts
  components/no_results_indicator/no_results_indicator.scss
  components/no_results_indicator/no_results_indicator.tsx
  components/post_profile_picture/post_profile_picture.jsx
  components/post_view/post_add_channel_member/__snapshots__/post_add_channel_member.test.tsx.snap
  components/post_view/post_add_channel_member/post_add_channel_member.tsx
  components/profile_picture/profile_picture.tsx
  components/profile_popover/index.js
  components/profile_popover/profile_popover.jsx
  components/rhs_comment/__snapshots__/rhs_comment.test.jsx.snap
  components/rhs_comment/rhs_comment.jsx
  components/rhs_root_post/__snapshots__/rhs_root_post.test.jsx.snap
  components/rhs_root_post/rhs_root_post.jsx
  components/rhs_search_nav/__snapshots__/rhs_search_nav.test.tsx.snap
  components/rhs_search_nav/components/user_guide_dropdown/__snapshots__/user_guide_dropdown.test.jsx.snap
  components/rhs_search_nav/components/user_guide_dropdown/index.ts
  components/rhs_search_nav/components/user_guide_dropdown/user_guide_dropdown.test.jsx
  components/rhs_search_nav/components/user_guide_dropdown/user_guide_dropdown.tsx
  components/rhs_search_nav/index.ts
  components/rhs_search_nav/rhs_search_nav.test.tsx
  components/rhs_search_nav/rhs_search_nav.tsx
  components/search/search.tsx
  components/sidebar/sidebar_channel/channel_mention_badge.tsx
  components/sidebar/sidebar_channel/sidebar_channel_link/__snapshots__/sidebar_channel_link.test.tsx.snap
  components/sidebar/sidebar_channel/sidebar_channel_link/sidebar_channel_link.tsx
  components/user_profile/user_profile.tsx
  sass/components/_module.scss
  utils/message_html_to_component.jsx
Labels: 4: Reviews Complete

#7764 Removing Beta from sv and bg
  components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
  i18n/i18n.jsx
Labels: 3: QA Review, CherryPick/Approved

#7747 MM-34055 Re-add border to Markdown preview
  sass/components/_post.scss
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server

#7563 MM-32882: Add an unread badge/marker to the Main Menu icon and the ‘Plugin Marketplace’ Menu Item
  actions/websocket_actions.jsx
  components/legacy_sidebar/header/dropdown/index.js
  components/legacy_sidebar/header/dropdown/sidebar_header_dropdown.jsx
  components/legacy_sidebar/header/index.js
  components/legacy_sidebar/header/sidebar_header_dropdown_button.jsx
  components/main_menu/index.jsx
  components/main_menu/main_menu.jsx
  components/plugin_marketplace/index.ts
  components/plugin_marketplace/marketplace_modal.test.tsx
  components/plugin_marketplace/marketplace_modal.tsx
  components/toggle_modal_button_redux/toggle_modal_button_redux.jsx
  components/widgets/menu/menu_items/menu_item_toggle_modal_redux.tsx
  packages/mattermost-redux/src/action_types/general.ts
  packages/mattermost-redux/src/actions/general.test.js
  packages/mattermost-redux/src/actions/general.ts
  packages/mattermost-redux/src/client/client4.ts
  packages/mattermost-redux/src/constants/websocket.ts
  packages/mattermost-redux/src/reducers/entities/general.test.js
  packages/mattermost-redux/src/reducers/entities/general.ts
  packages/mattermost-redux/src/selectors/entities/general.test.js
  packages/mattermost-redux/src/selectors/entities/general.ts
  packages/mattermost-redux/src/store/initial_state.ts
  packages/mattermost-redux/src/types/general.ts
  plugins/test/__snapshots__/main_menu_action.test.jsx.snap
  sass/components/_buttons.scss
  sass/components/_sidebar-header-dropdown-button.scss
  utils/constants.jsx
Labels: 4: Reviews Complete, QA Review Done, Setup Cloud Test Server

#7777 [MM-34163][MM-34165] - UI fixes to direct channel profile pics
  components/sidebar/sidebar_channel/sidebar_direct_channel/__snapshots__/sidebar_direct_channel.test.tsx.snap
  components/sidebar/sidebar_channel/sidebar_direct_channel/sidebar_direct_channel.tsx
  sass/layout/_sidebar-left.scss
Labels: 2: Dev Review, CherryPick/Approved, QA Review Done, Setup Cloud Test Server

#7772 websocket_client: rename variables
  client/websocket_client.tsx
Labels: 4: Reviews Complete

#7780 Cypress/E2E: Promote tests to prod
  e2e/cypress/integration/custom_status/custom_status_1_spec.js
  e2e/cypress/integration/custom_status/custom_status_2_spec.js
  e2e/cypress/integration/custom_status/custom_status_3_spec.js
  e2e/cypress/integration/custom_status/custom_status_4_spec.js
  e2e/cypress/integration/custom_status/custom_status_6_spec.js
  e2e/cypress/integration/enterprise/integrations/incoming_webhook_spec.js
Labels: 4: Reviews Complete

#7763 MM-34001 Cypress/E2E: Fix for members with bots
  e2e/cypress/integration/bot_accounts/in_lists_2_spec.js
  e2e/package.json
Labels: 4: Reviews Complete

#7799 make totalUsers optional
  components/post_view/channel_intro_message/add_members_button.tsx
Labels: 4: Reviews Complete

#7602 [GH-16739, MM-18954] Converted channel info modal and associated tests to typescript
  components/channel_info_modal/__snapshots__/channel_info_modal.test.tsx.snap
  components/channel_info_modal/channel_info_modal.test.tsx
  components/channel_info_modal/channel_info_modal.tsx
  components/channel_info_modal/index.js
Labels: 4: Reviews Complete

#7797 MM-34371: handle undefined status in switcher
  sass/components/_mentions.scss
Labels: 4: Reviews Complete, CherryPick/Approved

#7803 Automated cherry pick of #7797
  sass/components/_mentions.scss
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7804 Automated cherry pick of #7797
  sass/components/_mentions.scss
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7800 make actorId optional
  components/post_view/combined_system_message/combined_system_message.tsx
Labels: 4: Reviews Complete
