Repository mattermost/mattermost-webapp, pull requests merged in 2021-11, with the labels that each got.

#9171 Updated tutorial text for Global Header
  components/global_header/right_controls/settings_tip.tsx
  components/next_steps_view/steps/setup_preferences_step/setup_preferences_step.tsx
  i18n/en.json
Labels: 4: Reviews Complete, release-note-none

#9293 MM-39580 Switch admin-related modals to onExited
  components/add_groups_to_channel_modal/__snapshots__/add_groups_to_channel_modal.test.tsx.snap
  components/add_groups_to_channel_modal/add_groups_to_channel_modal.test.tsx
  components/add_groups_to_channel_modal/add_groups_to_channel_modal.tsx
  components/admin_console/system_roles/system_role/add_users_to_role_modal/add_users_to_role_modal.test.tsx
  components/admin_console/system_roles/system_role/add_users_to_role_modal/add_users_to_role_modal.tsx
  components/admin_console/team_channel_settings/group/group_members_modal.test.tsx
  components/admin_console/team_channel_settings/group/group_members_modal.tsx
  components/admin_console/team_channel_settings/users_to_be_removed_modal.jsx
  components/commercial_support_modal/__snapshots__/commercial_support_modal.test.tsx.snap
  components/commercial_support_modal/commercial_support_modal.test.tsx
  components/commercial_support_modal/commercial_support_modal.tsx
  components/commercial_support_modal/index.ts
  components/delete_post_modal/delete_post_modal.test.tsx
  components/delete_post_modal/delete_post_modal.tsx
  components/join_private_channel_modal.tsx
Labels: 4: Reviews Complete, release-note-none, QA Deferred

#9294 MM-39580 Switch misc modals to onExited
  components/about_build_modal/__snapshots__/about_build_modal.test.tsx.snap
  components/about_build_modal/about_build_modal.test.tsx
  components/about_build_modal/about_build_modal.tsx
  components/about_build_modal/about_build_modal_cloud/about_build_modal_cloud.tsx
  components/about_build_modal/index.ts
  components/apps_form/__snapshots__/apps_form_container.test.jsx.snap
  components/apps_form/apps_form_component.test.tsx
  components/apps_form/apps_form_component.tsx
  components/apps_form/apps_form_container.test.jsx
  components/apps_form/apps_form_container.tsx
  components/confirm_modal_redux/confirm_modal_redux.test.tsx
  components/confirm_modal_redux/confirm_modal_redux.tsx
  components/create_comment/create_comment.tsx
  components/create_comment/index.ts
  components/create_post/create_post.test.jsx
  components/create_post/create_post.tsx
  components/create_post/index.ts
  components/integrations/delete_integration_link/delete_integration_link.tsx
  components/integrations/delete_integration_link/index.ts
  components/interactive_dialog/interactive_dialog.jsx
  components/interactive_dialog/interactive_dialog.test.jsx
  components/more_direct_channels/more_direct_channels.test.jsx
  components/more_direct_channels/more_direct_channels.tsx
  components/next_steps_view/steps/setup_preferences_step/setup_preferences_step.tsx
  components/notify_confirm_modal.tsx
  components/quick_switch_modal/quick_switch_modal.test.tsx
  components/quick_switch_modal/quick_switch_modal.tsx
  components/removed_from_channel_modal/removed_from_channel_modal.test.tsx
  components/removed_from_channel_modal/removed_from_channel_modal.tsx
  components/reset_status_modal/reset_status_modal.jsx
  components/user_settings/modal/user_settings_modal.tsx
  components/widgets/menu/menu_modals/submenu_modal/submenu_modal.test.tsx
  components/widgets/menu/menu_modals/submenu_modal/submenu_modal.tsx
Labels: 4: Reviews Complete, release-note-none, QA Deferred

#9298 Lock CI from /release-6.1
  .circleci/config.yml
  .gitlab-ci.yml
Labels: release-note-none

#9300 Automated cherry pick of #9171
  components/global_header/right_controls/settings_tip.tsx
  components/next_steps_view/steps/setup_preferences_step/setup_preferences_step.tsx
  i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#9301 Automated cherry pick of #9211
  packages/mattermost-redux/src/constants/general.ts
  packages/mattermost-redux/src/selectors/entities/channels.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#9302 Automated cherry pick of #9190
  components/widgets/icons/status_offline_avatar_icon.tsx
  sass/base/_css_variables.scss
  sass/components/_status-icon.scss
  sass/layout/_sidebar-left.scss
  utils/utils.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#9297 [GH-18821] Added E2E test new email not visible to other users until it has been confirmed
  e2e/cypress/integration/account_settings/account_settings_spec.js
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted, release-note-none, Contributor

#9174 Update permalink preview subtext
  components/post_view/post_message_preview/__snapshots__/post_message_preview.test.tsx.snap
  components/post_view/post_message_preview/post_message_preview.tsx
  i18n/en.json
Labels: 4: Reviews Complete, release-note-none

#9308 Automated cherry pick of #9174
  components/post_view/post_message_preview/__snapshots__/post_message_preview.test.tsx.snap
  components/post_view/post_message_preview/post_message_preview.tsx
  i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#9249 MM-39059 - AB test for the add members to channel btn
  components/popover_list_members/__snapshots__/popover_list_members.test.jsx.snap
  components/popover_list_members/index.js
  components/popover_list_members/popover_list_members.jsx
  components/popover_list_members/popover_list_members.test.jsx
  i18n/en.json
  packages/mattermost-redux/src/constants/config.ts
  packages/mattermost-redux/src/selectors/entities/preferences.ts
  sass/components/_popover.scss
Labels: Setup Cloud Test Server, QA Review Done, release-note-none

#8779 [MM-37038] CRT:Fake following for root post with zero reply counts with mentions
  components/dot_menu/dot_menu.tsx
  components/dot_menu/index.ts
  components/rhs_header_post/index.ts
  components/rhs_header_post/rhs_header_post.tsx
  packages/mattermost-redux/src/selectors/entities/threads.ts
  utils/post_utils.ts
Labels: 4: Reviews Complete, Setup Cloud Test Server, QA Review Done, release-note

#9304 Update NOTICE.txt
  NOTICE.txt
Labels: 4: Reviews Complete, CherryPick/Approved, AutoMerge, release-note-none

#9311 Automated cherry pick of #9304
  NOTICE.txt
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#9314 Automated cherry pick of #8779
  components/dot_menu/dot_menu.tsx
  components/dot_menu/index.ts
  components/rhs_header_post/index.ts
  components/rhs_header_post/rhs_header_post.tsx
  packages/mattermost-redux/src/selectors/entities/threads.ts
  utils/post_utils.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#9313 MM-39773 Re-add default value in getChannelsWithUserProfiles
  packages/mattermost-redux/src/selectors/entities/channels.test.js
  packages/mattermost-redux/src/selectors/entities/channels.ts
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none, QA Deferred

#9315 Automated cherry pick of #9313
  packages/mattermost-redux/src/selectors/entities/channels.test.js
  packages/mattermost-redux/src/selectors/entities/channels.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#9264 [MM-39429]: show edited indicator on empty/deleted messages with attachment
  components/markdown/markdown.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, QA Review Done, AutoMerge, release-note, kind/bug

#9316 Automated cherry pick of #9264
  components/markdown/markdown.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#9317 Automated cherry pick of #9264
  components/markdown/markdown.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#9222 MM-T1271 UP - Removing all text in edit deletes post
  e2e/cypress/integration/keyboard_shortcuts/up_arrow_edit_message_spec.js
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted, release-note-none, Contributor

#8316 Add .gitlab-ci.yml-compatible continuous integration configuration
  build/contrib/gitlab/.gitlab-ci.yml
  build/contrib/gitlab/README.md
Labels: 4: Reviews Complete, release-note-none

#9229 [MM-20431] Migrate 'components/reset_status_modal' module and associated tests to TypeScript
  components/reset_status_modal/__snapshots__/reset_status_modal.test.tsx.snap
  components/reset_status_modal/index.ts
  components/reset_status_modal/reset_status_modal.test.tsx
  components/reset_status_modal/reset_status_modal.tsx
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted, release-note-none, Contributor

#9254 MM-36765: fixes crash on LEAVE_CHANNEL
  components/threading/channel_threads/thread_footer/__snapshots__/thread_footer.test.tsx.snap
  components/threading/channel_threads/thread_footer/thread_footer.tsx
  components/threading/global_threads/thread_item/thread_item.tsx
  components/threading/global_threads/thread_pane/thread_pane.tsx
  components/threading/thread_viewer/thread_viewer.tsx
  packages/mattermost-redux/src/selectors/entities/threads.test.js
  packages/mattermost-redux/src/selectors/entities/threads.ts
Labels: 4: Reviews Complete, release-note-none

#9322 Automated cherry pick of #9299 on release-6.1
  i18n/bg.json
  i18n/de.json
  i18n/en_AU.json
  i18n/es.json
  i18n/fr.json
  i18n/hu.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
  i18n/zh-CN.json
Labels: CherryPick/Done, release-note-none

#9291 MM-39680 Switch Channel modals to onExited
  components/channel_info_modal/channel_info_modal.test.tsx
  components/channel_info_modal/channel_info_modal.tsx
  components/channel_invite_modal/channel_invite_modal.test.tsx
  components/channel_invite_modal/channel_invite_modal.tsx
  components/channel_members_modal/__snapshots__/channel_members_modal.test.tsx.snap
  components/channel_members_modal/channel_members_modal.test.tsx
  components/channel_members_modal/channel_members_modal.tsx
  components/channel_notifications_modal/channel_notifications_modal.jsx
  components/channel_notifications_modal/channel_notifications_modal.test.jsx
  components/delete_channel_modal/delete_channel_modal.test.tsx
  components/delete_channel_modal/delete_channel_modal.tsx
  components/edit_channel_purpose_modal/edit_channel_purpose_modal.test.tsx
  components/edit_channel_purpose_modal/edit_channel_purpose_modal.tsx
  components/rename_channel_modal/rename_channel_modal.test.tsx
  components/rename_channel_modal/rename_channel_modal.tsx
  components/unarchive_channel_modal/unarchive_channel_modal.test.tsx
  components/unarchive_channel_modal/unarchive_channel_modal.tsx
Labels: Setup Cloud Test Server, release-note-none, QA Deferred

#9283 MM-39580 Switch EditChannelHeaderModal to onExited
  components/edit_channel_header_modal/__snapshots__/edit_channel_header_modal.test.tsx.snap
  components/edit_channel_header_modal/edit_channel_header_modal.test.tsx
  components/edit_channel_header_modal/edit_channel_header_modal.tsx
  components/edit_channel_header_modal/index.ts
Labels: Setup Cloud Test Server, release-note-none, QA Deferred

#9309 [MM-39503] - Remove DownloadApps Feature Flag
  components/next_steps_view/__snapshots__/next_steps_view.test.tsx.snap
  components/next_steps_view/index.ts
  components/next_steps_view/next_steps_view.test.tsx
  components/next_steps_view/next_steps_view.tsx
  components/next_steps_view/steps.test.tsx
  components/next_steps_view/steps.ts
  components/next_steps_view/steps/invite_members_step/index.ts
  components/next_steps_view/steps/invite_members_step/invite_members_step.tsx
  i18n/en.json
  packages/mattermost-redux/src/constants/config.ts
  packages/mattermost-redux/src/selectors/entities/preferences.ts
Labels: 2: Dev Review, Setup Cloud Test Server, QA Review Done, release-note

#9281 MM-39580 Migrate ConvertChannelModal to TypeScript and to use onExited
  components/convert_channel_modal/convert_channel_modal.tsx
  components/convert_channel_modal/index.js
  components/convert_channel_modal/index.ts
Labels: 4: Reviews Complete, release-note-none, QA Deferred

#9305 MM-39581 Update openModal type definitions
  components/admin_console/feature_discovery/feature_discovery.tsx
  components/announcement_bar/cloud_announcement_bar/user_limit_announcement_bar.tsx
  components/announcement_bar/cloud_trial_announcement_bar/cloud_trial_announcement_bar.tsx
  components/announcement_bar/renewal_link/renewal_link.tsx
  components/dot_menu/dot_menu.tsx
  components/dot_menu/index.ts
  components/edit_post_modal/edit_post_modal.tsx
  components/global_header/right_controls/settings_button/settings_button.tsx
  components/invitation_modal/index.js
  components/main_menu/main_menu.tsx
  components/sidebar/index.ts
  components/sidebar/legacy_sidebar_header/dropdown/sidebar_header_dropdown.tsx
  components/sidebar/legacy_sidebar_header/dropdown/sidebar_header_dropdown_button.tsx
  components/sidebar/legacy_sidebar_header/legacy_sidebar_header.tsx
  components/sidebar/sidebar.tsx
  components/sidebar/sidebar_channel/sidebar_channel_menu/index.ts
  components/sidebar/sidebar_channel/sidebar_channel_menu/sidebar_channel_menu.tsx
  components/sidebar/sidebar_next_steps/sidebar_next_steps.tsx
  components/status_dropdown/status_dropdown.tsx
  components/user_limit_modal/index.ts
  components/user_limit_modal/user_limit_modal.tsx
Labels: 4: Reviews Complete, release-note-none, QA Deferred

#9325 Automated cherry pick of #9318
  components/admin_console/license_settings/__snapshots__/license_settings.test.jsx.snap
  components/admin_console/license_settings/license_settings.test.jsx
  utils/license_utils.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#9260 [MM-38937] Remove the cursor pointer when hovering at "Disable notifications until:"
  components/status_dropdown/status_dropdown.scss
  components/widgets/menu/menu_items/menu_item.scss
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted, release-note-none, Contributor

#9188 [MM-38643] - Improve Onboarding steps consistency
  components/global_header/left_controls/product_menu/product_menu_tip/product_menu_tip.tsx
  components/next_steps_view/next_steps_view.test.tsx
  components/next_steps_view/next_steps_view.tsx
  components/next_steps_view/steps.ts
  components/next_steps_view/steps/complete_profile_step/__snapshots__/complete_profile_step.test.tsx.snap
  components/next_steps_view/steps/complete_profile_step/complete_profile_step.test.tsx
  components/next_steps_view/steps/complete_profile_step/complete_profile_step.tsx
  components/next_steps_view/steps/download_apps_step/download_apps_step.tsx
  components/next_steps_view/steps/enable_notifications_step/enable_notifications_step.test.tsx
  components/next_steps_view/steps/enable_notifications_step/enable_notifications_step.tsx
  components/next_steps_view/steps/invite_members_step/invite_members_step.test.tsx
  components/next_steps_view/steps/invite_members_step/invite_members_step.tsx
  components/next_steps_view/steps/setup_preferences_step/__snapshots__/setup_preferences_step.test.tsx.snap
  components/next_steps_view/steps/setup_preferences_step/setup_preferences_step.test.tsx
  components/next_steps_view/steps/setup_preferences_step/setup_preferences_step.tsx
  components/next_steps_view/steps/team_profile_step/__snapshots__/team_profile_step.test.tsx.snap
  components/next_steps_view/steps/team_profile_step/team_profile_step.test.tsx
  components/next_steps_view/steps/team_profile_step/team_profile_step.tsx
  e2e/cypress/integration/enterprise/cloud/onboarding/cloud_sysadmin_onboarding_spec.js
  e2e/cypress/integration/enterprise/cloud/onboarding/invite_member_by_email_spec.js
  e2e/cypress/integration/enterprise/cloud/onboarding/set_profile_and_team_spec.js
  i18n/en.json
Labels: 4: Reviews Complete, QA Review Done, release-note-none

#9326 Automated cherry pick of #9260
  components/status_dropdown/status_dropdown.scss
  components/widgets/menu/menu_items/menu_item.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#9327 Automated cherry pick of #9260
  components/status_dropdown/status_dropdown.scss
  components/widgets/menu/menu_items/menu_item.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#9290 [MM-34916] Update Stripe dependencies
  package-lock.json
  package.json
Labels: 4: Reviews Complete, release-note, QA Deferred

#9312 [MM-39057] - Remove Tips & Next Steps page
  components/channel_layout/center_channel/center_channel.test.tsx
  components/channel_layout/center_channel/center_channel.tsx
  components/channel_layout/center_channel/index.ts
  components/channel_view/__snapshots__/channel_view.test.tsx.snap
  components/channel_view/channel_view.test.tsx
  components/channel_view/index.ts
  components/global_header/center_controls/user_guide_dropdown/index.ts
  components/global_header/center_controls/user_guide_dropdown/user_guide_dropdown.test.tsx
  components/global_header/center_controls/user_guide_dropdown/user_guide_dropdown.tsx
  components/main_menu/index.tsx
  components/main_menu/main_menu.tsx
  components/next_steps_view/__snapshots__/next_steps_view.test.tsx.snap
  components/next_steps_view/images/documents.svg.tsx
  components/next_steps_view/images/incidents.svg.tsx
  components/next_steps_view/images/plugins.svg.tsx
  components/next_steps_view/next_steps_tips.tsx
  components/next_steps_view/next_steps_view.scss
  components/next_steps_view/next_steps_view.test.tsx
  components/next_steps_view/next_steps_view.tsx
  components/next_steps_view/steps.ts
  components/sidebar/sidebar_next_steps/index.ts
  components/sidebar/sidebar_next_steps/sidebar_next_steps.scss
  components/sidebar/sidebar_next_steps/sidebar_next_steps.tsx
  components/threading/global_threads/global_threads.tsx
  e2e/cypress/integration/enterprise/cloud/onboarding/cloud_sysadmin_onboarding_spec.js
  i18n/en.json
Labels: 4: Reviews Complete, CherryPick/Candidate, QA Review Done, release-note-none

#9328 Manual cherry pick of #9312
  components/channel_layout/center_channel/center_channel.test.tsx
  components/channel_layout/center_channel/center_channel.tsx
  components/channel_layout/center_channel/index.ts
  components/channel_view/__snapshots__/channel_view.test.tsx.snap
  components/channel_view/channel_view.test.tsx
  components/channel_view/index.ts
  components/global_header/center_controls/user_guide_dropdown/index.ts
  components/global_header/center_controls/user_guide_dropdown/user_guide_dropdown.test.tsx
  components/global_header/center_controls/user_guide_dropdown/user_guide_dropdown.tsx
  components/main_menu/index.tsx
  components/main_menu/main_menu.tsx
  components/next_steps_view/__snapshots__/next_steps_view.test.tsx.snap
  components/next_steps_view/images/documents.svg.tsx
  components/next_steps_view/images/incidents.svg.tsx
  components/next_steps_view/images/plugins.svg.tsx
  components/next_steps_view/next_steps_tips.tsx
  components/next_steps_view/next_steps_view.scss
  components/next_steps_view/next_steps_view.test.tsx
  components/next_steps_view/next_steps_view.tsx
  components/next_steps_view/steps.ts
  components/sidebar/sidebar_next_steps/index.ts
  components/sidebar/sidebar_next_steps/sidebar_next_steps.scss
  components/sidebar/sidebar_next_steps/sidebar_next_steps.tsx
  components/threading/global_threads/global_threads.tsx
  e2e/cypress/integration/enterprise/cloud/onboarding/cloud_sysadmin_onboarding_spec.js
  i18n/en.json
Labels: release-note-none

#9329 Cypress/E2E: Fixed cypress tests
  e2e/cypress/integration/keyboard_shortcuts/ctrl_cmd_shift_slash/react_to_center_spec.js
  e2e/cypress/integration/messaging/header_spec.js
  e2e/cypress/integration/messaging/system_message_spec.js
  e2e/cypress/integration/system_console/lock_teammate_name_display_spec.js
Labels: 4: Reviews Complete, release-note-none

#9172 [MM-39200] Fixing manual timezone issue
  components/user_settings/display/manage_timezones/manage_timezones.tsx
Labels: 4: Reviews Complete, release-note-none

#9332 Cypress E2E: Moved from unstable to prod
  e2e/cypress/integration/account_settings/security/password_spec.js
  e2e/cypress/integration/enterprise/system_console/compliance/data_retention_policies_2_spec.js
  e2e/cypress/integration/enterprise/system_console/compliance/data_retention_policies_3_spec.js
  e2e/cypress/integration/enterprise/system_console/compliance/data_retention_policies_4_spec.js
  e2e/cypress/integration/keyboard_shortcuts/ctrl_cmd_up_down_in_rhs_spec.js
Labels: release-note-none

#9330 [MM-39770] Make thread mention badge visible in all themes
  components/threading/global_threads/thread_item/thread_item.scss
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, AutoMerge, release-note, QA Deferred

#9337 Automated cherry pick of #9330
  components/threading/global_threads/thread_item/thread_item.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#9338 Automated cherry pick of #9330
  components/threading/global_threads/thread_item/thread_item.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#9295 Fix tomorrow option in DND expiry and add options translations
  components/status_dropdown/__snapshots__/status_dropdown.test.tsx.snap
  components/status_dropdown/index.ts
  components/status_dropdown/status_dropdown.scss
  components/status_dropdown/status_dropdown.test.tsx
  components/status_dropdown/status_dropdown.tsx
  components/widgets/menu/menu_items/submenu_item.tsx
  e2e/cypress/integration/menus/status_dropdown_spec.js
  e2e/cypress/integration/settings/display/theme/custom_theme_sidebar_styles_spec.js
  e2e/cypress/integration/status/status_dnd_1_spec.js
  i18n/en.json
  i18n/fr.json
Labels: Hacktoberfest, 3: QA Review, Setup Cloud Test Server, hacktoberfest-accepted, release-note, Contributor

#9341 Automated cherry pick of #9340 on cloud
  i18n/bg.json
  i18n/de.json
  i18n/en_AU.json
  i18n/es.json
  i18n/fr.json
  i18n/hu.json
  i18n/ja.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: release-note-none

#9342 Automated cherry pick of #9340 on release-6.1
  i18n/bg.json
  i18n/de.json
  i18n/en_AU.json
  i18n/es.json
  i18n/fr.json
  i18n/hu.json
  i18n/ja.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: release-note-none

#9319 MM-39850: fixes follow in thread footer
  components/threading/common/follow_button/follow_button.tsx
Labels: 4: Reviews Complete, release-note-none

#9343 Cypress/E2E: fixed flaky tests as verified for Cloud release
  e2e/cypress/integration/bot_accounts/post_message_spec.js
  e2e/cypress/integration/emoji/custom_emoji_1_spec.js
Labels: 4: Reviews Complete, release-note-none

#9307 MM-39199 Fix permissions for reactions buttons
  components/post_view/post_body/index.js
  components/post_view/post_body/post_body.jsx
  components/post_view/reaction/__snapshots__/reaction.test.jsx.snap
  components/post_view/reaction/index.ts
  components/post_view/reaction/reaction.test.jsx
  components/post_view/reaction/reaction.tsx
  components/post_view/reaction/reaction_tooltip/reaction_tooltip.tsx
  components/post_view/reaction_list/index.ts
  components/post_view/reaction_list/reaction_list.tsx
  components/post_view/reaction_list/reactions_list.test.jsx
  packages/mattermost-redux/src/selectors/entities/reactions.ts
Labels: 4: Reviews Complete, release-note

#9257 Terminology changes: Account Settings to Profile
  components/global_header/right_controls/settings_tip.tsx
  components/keyboard_shortcuts/keyboard_shortcuts_sequence/keyboard_shortcuts.ts
  components/main_menu/__snapshots__/main_menu.test.tsx.snap
  components/main_menu/main_menu.tsx
  components/next_steps_view/steps/setup_preferences_step/setup_preferences_step.tsx
  components/status_dropdown/__snapshots__/status_dropdown.test.tsx.snap
  components/status_dropdown/status_dropdown.tsx
  components/user_settings/modal/user_settings_modal.tsx
  e2e/cypress/integration/accessibility/accessibility_account_settings_spec.js
  e2e/cypress/integration/accessibility/accessibility_image_spec.js
  e2e/cypress/integration/account_settings/main_menu_stays_open_spec.js
  e2e/cypress/integration/account_settings/profile/account_settings_position_spec.js
  e2e/cypress/integration/account_settings/profile/email_spec.js
  e2e/cypress/integration/account_settings/profile/fullname_edit_spec.js
  e2e/cypress/integration/account_settings/profile/fullname_truncate_spec.js
  e2e/cypress/integration/account_settings/profile/nickname_spec.js
  e2e/cypress/integration/account_settings/profile/profile_picture_spec.js
  e2e/cypress/integration/account_settings/profile/username_spec.js
  e2e/cypress/integration/account_settings/security/access_history_spec.js
  e2e/cypress/integration/account_settings/security/active_sessions_spec.js
  e2e/cypress/integration/account_settings/security/password_spec.js
  e2e/cypress/integration/auth_sso/authentication_1_spec.js
  e2e/cypress/integration/auth_sso/authentication_2_spec.js
  e2e/cypress/integration/enterprise/accessibility/accessibility_modals_dialogs_spec.js
  e2e/cypress/integration/enterprise/group_mentions/group_mentions_permissions_spec.js
  e2e/cypress/integration/enterprise/group_mentions/group_mentions_posts_spec.js
  e2e/cypress/integration/enterprise/group_mentions/group_mentions_system_messages_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/guest_add_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/guest_experience_ui_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/guest_identification_ui_not_cloud_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/guest_identification_ui_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/guest_popover_ui_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/member_invitation_ui_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/system_console_guest_access_ui_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/system_console_manage_guest_not_cloud_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/system_console_manage_guest_spec.js
  e2e/cypress/integration/enterprise/saml/saml_automated_spec.js
  e2e/cypress/integration/keyboard_shortcuts/ctrl_cmd_shift_slash/not_open_emoji_picker_spec.js
  e2e/cypress/integration/keyboard_shortcuts/keyboard_shortcuts_1_spec.js
  e2e/cypress/integration/menus/main_menu_spec.js
  e2e/cypress/integration/settings/display/timezone_display_mode_spec.js
  e2e/cypress/integration/settings/sidebar/fullname_spec.js
  e2e/cypress/integration/signin_authentication/desktop_session_expire_spec.js
  e2e/cypress/integration/signin_authentication/mfa_authentication_spec.js
  e2e/cypress/integration/system_console/user_management_spec.js
  e2e/cypress/support/ui/account_settings_modal.d.ts
  e2e/cypress/support/ui/account_settings_modal.js
  e2e/cypress/support/ui/global_header.d.ts
  i18n/en.json
  plugins/test/__snapshots__/main_menu_action.test.jsx.snap
Labels: 4: Reviews Complete, release-note

#9324 [MM-39596] Fix menu width
  components/widgets/menu/menu_items/menu_item.scss
Labels: 4: Reviews Complete, CherryPick/Approved, release-note, QA Deferred

#9335 Add .nvmrc
  .nvmrc
Labels: 4: Reviews Complete, release-note-none

#9348 Automated cherry pick of #9324
  components/widgets/menu/menu_items/menu_item.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#9320 MM-T3293 Entire thread appears and scrollable in the RHS
  e2e/cypress/integration/messaging/thread_appears_and_scrollable_in_the_rhs_spec.js
  e2e/cypress/plugins/index.js
  e2e/cypress/plugins/post_list_of_messages.js
  e2e/cypress/support/task_commands.js
  e2e/cypress/support/ui/sidebar_right.d.ts
Labels: 4: Reviews Complete, release-note, Contributor

#9336 [MM-36984] - Update Cypress test for onboarding flow
  e2e/cypress/integration/enterprise/cloud/onboarding/cloud_legacy_invite_member_by_email_spec.js
  e2e/cypress/integration/onboarding/cloud_sysadmin_onboarding_spec.js
  e2e/cypress/integration/onboarding/finish_tutorial_spec.js
  e2e/cypress/integration/onboarding/invite_member_by_email_spec.js
  e2e/cypress/integration/onboarding/login_page_link_account_creation_spec.js
  e2e/cypress/integration/onboarding/set_profile_and_team_spec.js
Labels: 2: Dev Review, release-note-none

#9310 Fix several bugs on saved posts and mentions
  components/dot_menu/__snapshots__/dot_menu.test.tsx.snap
  components/dot_menu/dot_menu.test.tsx
  components/dot_menu/dot_menu.tsx
  components/dot_menu/dot_menu_empty.test.tsx
  components/dot_menu/dot_menu_mobile.test.tsx
  components/dot_menu/index.ts
  components/post_view/post_time/index.ts
  components/search_results/search_results.tsx
  components/search_results_item/__snapshots__/search_results_item.test.jsx.snap
  components/search_results_item/index.test.js
  components/search_results_item/index.ts
  components/search_results_item/search_results_item.jsx
  components/search_results_item/search_results_item.test.jsx
  packages/mattermost-redux/src/actions/search.ts
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, QA Review Done, release-note-none

#9351 Fix several bugs on saved posts and mentions (#9310)
  components/dot_menu/__snapshots__/dot_menu.test.tsx.snap
  components/dot_menu/dot_menu.test.tsx
  components/dot_menu/dot_menu.tsx
  components/dot_menu/dot_menu_empty.test.tsx
  components/dot_menu/dot_menu_mobile.test.tsx
  components/dot_menu/index.ts
  components/post_view/post_time/index.ts
  components/search_results/search_results.tsx
  components/search_results_item/__snapshots__/search_results_item.test.jsx.snap
  components/search_results_item/index.test.js
  components/search_results_item/index.ts
  components/search_results_item/search_results_item.jsx
  components/search_results_item/search_results_item.test.jsx
  packages/mattermost-redux/src/actions/search.ts
Labels: release-note-none

#9355 Automated cherry pick of #9347
  components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
  i18n/i18n.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#9045 [MM-32213] Inline image collapse
  components/single_image_view/__snapshots__/single_image_view.test.tsx.snap
  components/single_image_view/single_image_view.test.tsx
  components/single_image_view/single_image_view.tsx
  e2e/cypress/integration/messaging/file_upload_in_center_channel_spec.js
  e2e/cypress/integration/messaging/single_image_thumbnail_spec.js
  sass/components/_module.scss
  sass/components/_single_image_view.scss
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted, release-note, Contributor

#9268 Remove string-refs usage in ThemeSetting component as it isn't needed anymore
  components/user_settings/display/user_settings_theme/user_settings_theme.jsx
  sass/routes/_settings.scss
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted, release-note-none, Contributor

#9284 MM-37746 Fix premature truncation of names in emoji picker
  build/emoji/emoji_gen.mjs
  sass/components/_emojisprite.scss
  sass/components/_emoticons.scss
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted, release-note-none, Contributor

#9286 [MM-37990] Update recent emojis based on default selected skin tone
  components/emoji_picker/emoji_picker.jsx
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted, release-note, Contributor

#9356 Automated cherry pick of #8431
  components/help/components/attaching.tsx
  components/help/components/commands.tsx
  components/help/components/composing.tsx
  components/help/components/formatting.tsx
  components/help/components/mentioning.tsx
  components/help/components/messaging.tsx
  i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#9354 [MM-39374] Remove references to DesktopMinVersion and DesktopLatestVersion
  e2e/cypress/support/api/on_prem_default_config.json
  packages/mattermost-redux/src/types/config.ts
Labels: 4: Reviews Complete, release-note-none

#9292 MM-39580 Switch Team modals to onExited
  components/add_groups_to_team_modal/add_groups_to_team_modal.test.tsx
  components/add_groups_to_team_modal/add_groups_to_team_modal.tsx
  components/add_users_to_team_modal/add_users_to_team_modal.test.tsx
  components/add_users_to_team_modal/add_users_to_team_modal.tsx
  components/admin_console/system_roles/system_role/system_role_users/__snapshots__/system_role_users.test.tsx.snap
  components/admin_console/system_roles/system_role/system_role_users/system_role_users.tsx
  components/admin_console/team_channel_settings/channel/details/__snapshots__/channel_groups.test.tsx.snap
  components/admin_console/team_channel_settings/channel/details/channel_groups.tsx
  components/admin_console/team_channel_settings/channel/details/channel_members/__snapshots__/channel_members.test.tsx.snap
  components/admin_console/team_channel_settings/channel/details/channel_members/channel_members.tsx
  components/admin_console/team_channel_settings/errors.jsx
  components/admin_console/team_channel_settings/group/__snapshots__/group_row.test.tsx.snap
  components/admin_console/team_channel_settings/group/group_row.tsx
  components/admin_console/team_channel_settings/team/details/__snapshots__/team_groups.test.jsx.snap
  components/admin_console/team_channel_settings/team/details/team_groups.jsx
  components/admin_console/team_channel_settings/team/details/team_members/__snapshots__/team_members.test.tsx.snap
  components/admin_console/team_channel_settings/team/details/team_members/team_members.tsx
  components/leave_team_modal/__snapshots__/leave_team_modal.test.tsx.snap
  components/leave_team_modal/index.ts
  components/leave_team_modal/leave_team_modal.test.tsx
  components/leave_team_modal/leave_team_modal.tsx
  components/post_view/channel_intro_message/add_members_button.tsx
  components/post_view/channel_intro_message/channel_intro_message.tsx
  components/sidebar/__snapshots__/invite_members_button.test.tsx.snap
  components/team_members_modal/__snapshots__/team_members_modal.test.tsx.snap
  components/team_members_modal/team_members_modal.test.tsx
  components/team_members_modal/team_members_modal.tsx
  components/team_settings_modal/team_settings_modal.test.tsx
  components/team_settings_modal/team_settings_modal.tsx
  components/toggle_modal_button_redux/__snapshots__/toggle_modal_button_redux.test.jsx.snap
  components/toggle_modal_button_redux/toggle_modal_button_redux.jsx
  e2e/cypress/integration/enterprise/ldap/ldap_group_sync_spec.js
  e2e/cypress/integration/enterprise/ldap/ldap_guest_spec.js
  e2e/cypress/integration/enterprise/ldap_group/team_and_channel_assign_roles_spec.js
  e2e/cypress/integration/enterprise/system_console/channel_members_spec.js
  e2e/cypress/integration/enterprise/system_console/team_members_spec.js
  utils/constants.jsx
Labels: 4: Reviews Complete, release-note-none

#9350 MM-T1277 Create Spec for SHIFT+UP Shortcut
  e2e/cypress/integration/keyboard_shortcuts/shift_up_focuses_on_rhs_spec.js
Labels: 4: Reviews Complete, release-note-none, Contributor

#9274 Fixes threads list inconsistencies
  components/threading/global_threads/global_threads.tsx
  components/threading/global_threads/thread_list/thread_list.tsx
  packages/mattermost-redux/src/reducers/entities/threads/index.ts
  packages/mattermost-redux/src/reducers/entities/threads/threads.test.js
  packages/mattermost-redux/src/reducers/entities/threads/threadsInTeam.test.ts
  packages/mattermost-redux/src/reducers/entities/threads/threadsInTeam.ts
  packages/mattermost-redux/src/reducers/entities/threads/types.ts
Labels: 4: Reviews Complete, release-note-none

#9357 Update package-lock.json
  package-lock.json
Labels: 4: Reviews Complete, release-note-none

#9275 Update switch to navigate
  components/keyboard_shortcuts/keyboard_shortcuts_sequence/keyboard_shortcuts.ts
  components/quick_switch_modal/__snapshots__/quick_switch_modal.test.tsx.snap
  components/quick_switch_modal/quick_switch_modal.tsx
  e2e/cypress/integration/accessibility/accessibility_sidebar_spec.js
  e2e/cypress/integration/keyboard_shortcuts/esc_close_modal_spec.js
  e2e/cypress/integration/messaging/message_draft_then_switch_channel_spec.js
  e2e/cypress/support/ui/sidebar_left.js
  i18n/en.json
Labels: 4: Reviews Complete, release-note

#9265 chore/MM-39425 : Migrate ModalStore modals to use ModalController and remove ModalStore
  actions/command.test.js
  actions/command.ts
  actions/global_actions.tsx
  components/__snapshots__/get_link_modal.test.tsx.snap
  components/channel_header_dropdown/menu_items/leave_channel/index.ts
  components/channel_header_dropdown/menu_items/leave_channel/leave_channel.test.tsx
  components/channel_header_dropdown/menu_items/leave_channel/leave_channel.tsx
  components/channel_layout/channel_controller.tsx
  components/create_post/create_post.test.jsx
  components/create_post/create_post.tsx
  components/file_attachment/file_attachment.test.tsx
  components/file_attachment/file_attachment.tsx
  components/file_attachment/index.ts
  components/get_link_modal.test.tsx
  components/get_link_modal.tsx
  components/get_public_link_modal/__snapshots__/get_public_link_modal.test.tsx.snap
  components/get_public_link_modal/get_public_link_modal.test.tsx
  components/get_public_link_modal/get_public_link_modal.tsx
  components/get_public_link_modal/index.ts
  components/global_header/center_controls/user_guide_dropdown/index.ts
  components/global_header/center_controls/user_guide_dropdown/user_guide_dropdown.test.tsx
  components/global_header/center_controls/user_guide_dropdown/user_guide_dropdown.tsx
  components/invitation_modal/invitation_modal_guest_step/invitation_modal_guests_step.tsx
  components/keyboard_shortcuts/keyboard_shortcuts_modal/__snapshots__/keyboard_shortcuts_modal.test.tsx.snap
  components/keyboard_shortcuts/keyboard_shortcuts_modal/keyboard_shortcuts_modal.test.tsx
  components/keyboard_shortcuts/keyboard_shortcuts_modal/keyboard_shortcuts_modal.tsx
  components/leave_private_channel_modal/__snapshots__/leave_private_channel_modal.test.tsx.snap
  components/leave_private_channel_modal/leave_private_channel_modal.test.tsx
  components/leave_private_channel_modal/leave_private_channel_modal.tsx
  components/main_menu/main_menu.tsx
  components/rhs_search_nav/components/user_guide_dropdown/index.ts
  components/rhs_search_nav/components/user_guide_dropdown/user_guide_dropdown.test.tsx
  components/rhs_search_nav/components/user_guide_dropdown/user_guide_dropdown.tsx
  components/sidebar/legacy_sidebar_header/dropdown/sidebar_header_dropdown.tsx
  components/sidebar/sidebar_channel/sidebar_base_channel/index.ts
  components/sidebar/sidebar_channel/sidebar_base_channel/sidebar_base_channel.test.tsx
  components/sidebar/sidebar_channel/sidebar_base_channel/sidebar_base_channel.tsx
  components/user_settings/__snapshots__/import_theme_modal.test.tsx.snap
  components/user_settings/display/user_settings_theme/index.js
  components/user_settings/display/user_settings_theme/user_settings_theme.jsx
  components/user_settings/display/user_settings_theme/user_settings_theme.test.jsx
  components/user_settings/import_theme_modal.test.tsx
  components/user_settings/import_theme_modal.tsx
  stores/modal_store.jsx
  utils/constants.jsx
Labels: 4: Reviews Complete, QA Review Done, release-note-none

#8566 Update in-product conversation strings
  components/create_comment/__snapshots__/create_comment.test.jsx.snap
  components/create_comment/create_comment.tsx
  i18n/en.json
Labels: 4: Reviews Complete, release-note

#9362 [MM-39060] - A/B Test: Reminder to Join Workspace email
  components/signup/signup_email/signup_email.tsx
Labels: 2: Dev Review, release-note-none

#9344 [MM-39504] - Remove Prewritten Messages Feature Flag
  components/create_post/create_post.tsx
  components/create_post/create_post_tip.tsx
  components/create_post/index.ts
  components/create_post/prewritten_chips.tsx
  i18n/en.json
  packages/mattermost-redux/src/constants/config.ts
  packages/mattermost-redux/src/selectors/entities/preferences.ts
  packages/mattermost-redux/src/types/config.ts
  sass/components/_post.scss
Labels: 2: Dev Review, Setup Cloud Test Server, QA Review Done, release-note-none

#9375 Translations update from Mattermost Weblate
  i18n/de.json
  i18n/en_AU.json
  i18n/fr.json
  i18n/hu.json
  i18n/ja.json
  i18n/nl.json
  i18n/sv.json
  i18n/tr.json
  i18n/zh-CN.json
Labels: release-note-none

#9374 [MM-36009] fixes keyboard shortcut with global threads
  components/create_post/create_post.test.jsx
  components/create_post/create_post.tsx
  components/sidebar/sidebar.test.tsx
  components/sidebar/sidebar.tsx
Labels: 4: Reviews Complete, release-note, QA Deferred

#9386 Automated cherry pick of #9344
  components/create_post/create_post.tsx
  components/create_post/create_post_tip.tsx
  components/create_post/index.ts
  components/create_post/prewritten_chips.tsx
  i18n/en.json
  packages/mattermost-redux/src/constants/config.ts
  packages/mattermost-redux/src/selectors/entities/preferences.ts
  packages/mattermost-redux/src/types/config.ts
  sass/components/_post.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#9387 Automated cherry pick of #9374
  components/create_post/create_post.test.jsx
  components/create_post/create_post.tsx
  components/sidebar/sidebar.test.tsx
  components/sidebar/sidebar.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#9379 Cypress/E2E: Cleanup find channels
  e2e/cypress/integration/custom_status/custom_status_5_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/guest_identification_ui_spec.js
  e2e/cypress/integration/enterprise/ldap/ldap_group_sync_spec.js
  e2e/cypress/integration/system_console/user_management/users_deactivation_spec.js
  e2e/cypress/support/ui/sidebar_left.d.ts
  e2e/cypress/support/ui/sidebar_left.js
Labels: 4: Reviews Complete, release-note-none

#9377 Cypress/E2E: Fix unstable profile e2e
  e2e/cypress/integration/account_settings/account_settings_spec.js
  e2e/cypress/integration/account_settings/profile/help_text_link_spec.js
Labels: 4: Reviews Complete, release-note-none

#9392 Automated cherry pick of #9375 on cloud
  i18n/de.json
  i18n/en_AU.json
  i18n/fr.json
  i18n/hu.json
  i18n/ja.json
  i18n/nl.json
  i18n/sv.json
  i18n/tr.json
  i18n/zh-CN.json
Labels: release-note-none

#9372 Mm 39952 new ux license page design
  components/admin_console/license_settings/__snapshots__/license_settings.test.jsx.snap
  components/admin_console/license_settings/ee_license_modal/ee_license_modal.scss
  components/admin_console/license_settings/ee_license_modal/ee_license_modal.tsx
  components/admin_console/license_settings/enterprise_edition/enterprise_edition.scss
  components/admin_console/license_settings/enterprise_edition/enterprise_edition_left_panel.tsx
  components/admin_console/license_settings/enterprise_edition/enterprise_edition_right_panel.tsx
  components/admin_console/license_settings/index.js
  components/admin_console/license_settings/index.ts
  components/admin_console/license_settings/license_settings.jsx
  components/admin_console/license_settings/license_settings.scss
  components/admin_console/license_settings/license_settings.test.jsx
  components/admin_console/license_settings/license_settings.tsx
  components/admin_console/license_settings/license_utils/license_utils.tsx
  components/admin_console/license_settings/renew_license_card/renew_license_card.scss
  components/admin_console/license_settings/renew_license_card/renew_license_card.tsx
  components/admin_console/license_settings/starter_edition/starter_edition.scss
  components/admin_console/license_settings/starter_edition/starter_left_panel.tsx
  components/admin_console/license_settings/starter_edition/starter_right_panel.tsx
  components/admin_console/license_settings/team_edition/team_edition.scss
  components/admin_console/license_settings/team_edition/team_edition_left_panel.tsx
  components/admin_console/license_settings/team_edition/team_edition_right_panel.tsx
  components/admin_console/license_settings/trial_license_card/trial_license_card.scss
  components/admin_console/license_settings/trial_license_card/trial_license_card.tsx
  components/announcement_bar/contact_sales/contact_us.tsx
  components/announcement_bar/renewal_link/renewal_link.tsx
  components/common/svg_images_components/hands_svg.tsx
  components/common/svg_images_components/two_people_chatting_svg.tsx
  components/common/svg_images_components/woman_up_arrows_and_clouds_svg.tsx
  components/common/svg_images_components/woman_with_card_svg.tsx
  i18n/en.json
  packages/mattermost-redux/src/types/config.ts
  sass/admin_console_base/_sys_css_variables.scss
  sass/base/_css_variables.scss
  sass/routes/_admin-console.scss
  utils/constants.jsx
  utils/markdown/index.ts
Labels: CherryPick/Candidate, Setup Cloud Test Server, QA Review Done, 1: UX Review, release-note-none

#9394 Automated cherry pick of #9372
  components/admin_console/license_settings/__snapshots__/license_settings.test.jsx.snap
  components/admin_console/license_settings/ee_license_modal/ee_license_modal.scss
  components/admin_console/license_settings/ee_license_modal/ee_license_modal.tsx
  components/admin_console/license_settings/enterprise_edition/enterprise_edition.scss
  components/admin_console/license_settings/enterprise_edition/enterprise_edition_left_panel.tsx
  components/admin_console/license_settings/enterprise_edition/enterprise_edition_right_panel.tsx
  components/admin_console/license_settings/index.js
  components/admin_console/license_settings/index.ts
  components/admin_console/license_settings/license_settings.jsx
  components/admin_console/license_settings/license_settings.scss
  components/admin_console/license_settings/license_settings.test.jsx
  components/admin_console/license_settings/license_settings.tsx
  components/admin_console/license_settings/license_utils/license_utils.tsx
  components/admin_console/license_settings/renew_license_card/renew_license_card.scss
  components/admin_console/license_settings/renew_license_card/renew_license_card.tsx
  components/admin_console/license_settings/starter_edition/starter_edition.scss
  components/admin_console/license_settings/starter_edition/starter_left_panel.tsx
  components/admin_console/license_settings/starter_edition/starter_right_panel.tsx
  components/admin_console/license_settings/team_edition/team_edition.scss
  components/admin_console/license_settings/team_edition/team_edition_left_panel.tsx
  components/admin_console/license_settings/team_edition/team_edition_right_panel.tsx
  components/admin_console/license_settings/trial_license_card/trial_license_card.scss
  components/admin_console/license_settings/trial_license_card/trial_license_card.tsx
  components/announcement_bar/contact_sales/contact_us.tsx
  components/announcement_bar/renewal_link/renewal_link.tsx
  components/common/svg_images_components/hands_svg.tsx
  components/common/svg_images_components/two_people_chatting_svg.tsx
  components/common/svg_images_components/woman_up_arrows_and_clouds_svg.tsx
  components/common/svg_images_components/woman_with_card_svg.tsx
  i18n/en.json
  packages/mattermost-redux/src/types/config.ts
  sass/admin_console_base/_sys_css_variables.scss
  sass/base/_css_variables.scss
  sass/routes/_admin-console.scss
  utils/constants.jsx
  utils/markdown/index.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#9390 Cypress/E2E: Fix unstable autocomplete
  e2e/cypress/integration/autocomplete/common_test.js
  e2e/cypress/integration/channel/channel_mention_autocomplete_spec.js
  e2e/cypress/integration/messaging/mention_autocomplete_overlap_spec.js
  e2e/cypress/integration/settings/sidebar/fullname_spec.js
  e2e/cypress/support/ui/suggestion_list.d.ts
  e2e/cypress/support/ui/suggestion_list.js
Labels: 4: Reviews Complete, release-note-none

#9388 [MM-40038] Track crt events
  components/post_view/post/post.jsx
  components/threading/channel_threads/thread_footer/thread_footer.tsx
  components/threading/global_threads/thread_list/thread_list.tsx
  components/threading/global_threads_link/global_threads_link.tsx
Labels: 4: Reviews Complete, release-note, QA Deferred

#9393 add missing i18 variable for unread threads
  components/threading/global_threads/global_threads.tsx
  i18n/en.json
Labels: 4: Reviews Complete, release-note

#9399 Automated cherry pick of #9393
  components/threading/global_threads/global_threads.tsx
  i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#9345 chore/MM-39787 : Migrate PostDeletedModal to be controlled by the ModalController
  components/__snapshots__/post_deleted_modal.test.tsx.snap
  components/create_comment/__snapshots__/create_comment.test.jsx.snap
  components/create_comment/create_comment.test.jsx
  components/create_comment/create_comment.tsx
  components/create_post/__snapshots__/create_post.test.jsx.snap
  components/create_post/create_post.test.jsx
  components/create_post/create_post.tsx
  components/post_deleted_modal.test.tsx
  components/post_deleted_modal.tsx
  utils/constants.jsx
Labels: 4: Reviews Complete, QA Review Done, release-note-none

#9381 [MM-38376]fix-app-crash-on-root-post-delete-from-global-threads
  components/delete_post_modal/delete_post_modal.tsx
  components/delete_post_modal/index.ts
  components/threading/global_threads/thread_item/index.ts
  reducers/views/rhs.js
  reducers/views/threads.ts
Labels: 4: Reviews Complete, release-note

#8787 MM-35718: new replies banner for thread viewer
  actions/views/threads.ts
  components/new_replies_banner/index.ts
  components/new_replies_banner/new_replies_banner.scss
  components/new_replies_banner/new_replies_banner.tsx
  components/post_view/floating_timestamp/index.ts
  components/threading/virtualized_thread_viewer/create_comment.tsx
  components/threading/virtualized_thread_viewer/virtualized_thread_viewer.tsx
  components/toast/toast.tsx
  e2e/cypress/integration/mark_as_unread/unread_toast_count_spec.js
  i18n/en.json
  reducers/views/threads.ts
  sass/components/_post.scss
  selectors/views/threads.ts
  types/external/dynamic-virtualized-list.d.ts
  types/store/views.ts
  utils/constants.jsx
Labels: 4: Reviews Complete, release-note-none

#9282 MM-39580 Switch GenericModal and related modals to use onExited
  components/__snapshots__/generic_modal.test.tsx.snap
  components/announcement_bar/no_internet_connection/no_internet_connection.tsx
  components/collapsed_reply_threads_modal/collapsed_reply_threads_modal.tsx
  components/custom_status/__snapshots__/custom_status_modal.test.tsx.snap
  components/custom_status/custom_status_modal.test.tsx
  components/custom_status/custom_status_modal.tsx
  components/delete_category_modal/delete_category_modal.tsx
  components/dnd_custom_time_picker_modal/dnd_custom_time_picker_modal.tsx
  components/edit_category_modal/edit_category_modal.test.tsx
  components/edit_category_modal/edit_category_modal.tsx
  components/generic_modal.test.tsx
  components/generic_modal.tsx
  components/product_notices_modal/__snapshots__/product_notices.test.tsx.snap
  components/product_notices_modal/product_notices.test.tsx
  components/product_notices_modal/product_notices_modal.tsx
  components/sidebar/sidebar_next_steps/remove_next_steps_modal.tsx
  components/trial_benefits_modal/__snapshots__/trial_benefits_modal.test.tsx.snap
  components/trial_benefits_modal/trial_benefits_modal.test.tsx
  components/trial_benefits_modal/trial_benefits_modal.tsx
Labels: 4: Reviews Complete, release-note-none

#9395 MM-40165 - remaining ux improvements for licensing page
  components/admin_console/license_settings/__snapshots__/license_settings.test.jsx.snap
  components/admin_console/license_settings/enterprise_edition/enterprise_edition.scss
  components/admin_console/license_settings/enterprise_edition/enterprise_edition_left_panel.tsx
  components/admin_console/license_settings/enterprise_edition/enterprise_edition_right_panel.tsx
  components/admin_console/license_settings/license_settings.scss
  components/admin_console/license_settings/license_settings.tsx
  components/admin_console/license_settings/license_utils/license_utils.tsx
  components/admin_console/license_settings/starter_edition/starter_edition.scss
  components/admin_console/license_settings/starter_edition/starter_left_panel.tsx
  components/admin_console/license_settings/starter_edition/starter_right_panel.tsx
  components/admin_console/license_settings/team_edition/team_edition.scss
  components/admin_console/license_settings/team_edition/team_edition_right_panel.tsx
  i18n/en.json
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, release-note-none, QA Deferred

#9402 Automated cherry pick of #9395
  components/admin_console/license_settings/__snapshots__/license_settings.test.jsx.snap
  components/admin_console/license_settings/enterprise_edition/enterprise_edition.scss
  components/admin_console/license_settings/enterprise_edition/enterprise_edition_left_panel.tsx
  components/admin_console/license_settings/enterprise_edition/enterprise_edition_right_panel.tsx
  components/admin_console/license_settings/license_settings.scss
  components/admin_console/license_settings/license_settings.tsx
  components/admin_console/license_settings/license_utils/license_utils.tsx
  components/admin_console/license_settings/starter_edition/starter_edition.scss
  components/admin_console/license_settings/starter_edition/starter_left_panel.tsx
  components/admin_console/license_settings/starter_edition/starter_right_panel.tsx
  components/admin_console/license_settings/team_edition/team_edition.scss
  components/admin_console/license_settings/team_edition/team_edition_right_panel.tsx
  i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#9403 Automated cherry pick of #9381
  components/delete_post_modal/delete_post_modal.tsx
  components/delete_post_modal/index.ts
  components/threading/global_threads/thread_item/index.ts
  reducers/views/rhs.js
  reducers/views/threads.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#9407 fix : Typscript failing prop for GenericModal in EE_Licence_Modal, changed from onHide to onExited
  components/admin_console/license_settings/ee_license_modal/ee_license_modal.tsx
Labels: 4: Reviews Complete, release-note-none, QA Deferred

#9401 MM-40013 : Mock useIntl in all test cases
  components/global_header/left_controls/product_menu/product_menu_list/product_menu_list.test.tsx
  components/keyboard_shortcuts/keyboard_shortcuts_modal/keyboard_shortcuts_modal.test.tsx
  components/threading/global_threads/thread_item/thread_item.test.tsx
  components/threading/global_threads/thread_list/thread_list.test.tsx
  components/threading/global_threads/thread_menu/thread_menu.test.tsx
  components/threading/global_threads/thread_pane/thread_pane.test.tsx
  tests/react-intl_mock.js
  tests/setup.js
Labels: 4: Reviews Complete, release-note-none, QA Deferred

#9370 MM-39292 Remove unused component DataRetentionSettingsOld
  components/admin_console/admin_definition.jsx
  components/admin_console/data_retention_settings.jsx
  i18n/en.json
Labels: 4: Reviews Complete, release-note-none

#9384 fix/MM-39845 : System console help text for Custom Emoji setting is out of date
  components/admin_console/admin_definition.jsx
  i18n/en.json
Labels: 4: Reviews Complete, release-note-none, QA Deferred

#9396 fixing e2e tests
  components/common/radio_group.tsx
  components/invitation_modal/add_to_channels.test.tsx
  components/invitation_modal/add_to_channels.tsx
  components/invitation_modal/index.tsx
  components/invitation_modal/invitation_modal.test.tsx
  components/invitation_modal/invitation_modal.tsx
  components/invitation_modal/invite_as.tsx
  components/invitation_modal/invite_view.test.tsx
  components/invitation_modal/invite_view.tsx
  components/invitation_modal/result_view.tsx
  components/toggle.tsx
  e2e/cypress/integration/auth_sso/authentication_4_spec.js
  e2e/cypress/integration/enterprise/accessibility/accessibility_input_fields_spec.js
  e2e/cypress/integration/enterprise/accessibility/accessibility_modals_dialogs_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/guest_identification_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/guest_invitation_ui_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/helpers.js
  e2e/cypress/integration/enterprise/guest_accounts/member_invitation_ui_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/system_console_guest_access_ui_spec.js
  e2e/cypress/integration/keyboard_shortcuts/ctrl_cmd_shift_l_does_not_change_focus_to_msgbox_spec.js
  e2e/cypress/integration/team_settings/closed_team_invite_by_email_spec.js
  e2e/cypress/integration/team_settings/join_closed_team_with_not_allowed_email_spec.js
  e2e/cypress/integration/team_settings/teams_spec.js
  e2e/cypress/support/common_login_commands.js
  e2e/cypress/support/saml_commands.js
  e2e/cypress/support/ui/team.js
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, QA Review Done, release-note-none

#9413 Automated cherry pick of #9396
  components/common/radio_group.tsx
  components/invitation_modal/add_to_channels.test.tsx
  components/invitation_modal/add_to_channels.tsx
  components/invitation_modal/index.tsx
  components/invitation_modal/invitation_modal.test.tsx
  components/invitation_modal/invitation_modal.tsx
  components/invitation_modal/invite_as.tsx
  components/invitation_modal/invite_view.test.tsx
  components/invitation_modal/invite_view.tsx
  components/invitation_modal/result_view.tsx
  components/toggle.tsx
  e2e/cypress/integration/auth_sso/authentication_4_spec.js
  e2e/cypress/integration/enterprise/accessibility/accessibility_input_fields_spec.js
  e2e/cypress/integration/enterprise/accessibility/accessibility_modals_dialogs_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/guest_identification_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/guest_invitation_ui_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/helpers.js
  e2e/cypress/integration/enterprise/guest_accounts/member_invitation_ui_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/system_console_guest_access_ui_spec.js
  e2e/cypress/integration/keyboard_shortcuts/ctrl_cmd_shift_l_does_not_change_focus_to_msgbox_spec.js
  e2e/cypress/integration/team_settings/closed_team_invite_by_email_spec.js
  e2e/cypress/integration/team_settings/join_closed_team_with_not_allowed_email_spec.js
  e2e/cypress/integration/team_settings/teams_spec.js
  e2e/cypress/support/common_login_commands.js
  e2e/cypress/support/saml_commands.js
  e2e/cypress/support/ui/team.js
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#9306 [MM-38537] File-extension outside border fix
  components/file_attachment/__snapshots__/file_attachment.test.tsx.snap
  components/file_attachment/file_attachment.test.tsx
  components/file_attachment/file_attachment.tsx
  sass/components/_files.scss
Labels: 2: Dev Review, 3: QA Review, Setup Cloud Test Server, release-note

#9411 Automated cherry pick of #9410 on cloud
  i18n/bg.json
  i18n/de.json
  i18n/en_AU.json
  i18n/es.json
  i18n/fr.json
  i18n/hu.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 2: Dev Review, release-note-none

#9389 [MM-39816] Fix mentions permalink
  components/dot_menu/index.ts
Labels: 4: Reviews Complete, Setup Cloud Test Server, QA Review Done, release-note-none

#9414 Automated cherry pick of #9389
  components/dot_menu/index.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#9400 MM-39619: E2E CRT channel channel notification override
  e2e/cypress/integration/collapsed_reply_threads/channel_notifications_spec.js
Labels: 4: Reviews Complete, release-note-none

#9415 Automated cherry pick of #9384
  components/admin_console/admin_definition.jsx
  i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#9416 Automated cherry pick of #9306
  components/file_attachment/__snapshots__/file_attachment.test.tsx.snap
  components/file_attachment/file_attachment.test.tsx
  components/file_attachment/file_attachment.tsx
  sass/components/_files.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#9398 [MM-35926] CRT: Thread viewer long post Show More/Less background is broken
  utils/utils.jsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, QA Review Done, release-note-none

#9383 [MM-39792] - Add tab focus to global header heading and user avatar
  components/global_header/left_controls/product_menu/product_branding/__snapshots__/product_branding.test.tsx.snap
  components/global_header/left_controls/product_menu/product_branding/product_branding.tsx
  components/suggestion/at_mention_provider/__snapshots__/at_mention_suggestion.test.tsx.snap
  components/widgets/users/avatar/__snapshots__/avatar.test.tsx.snap
  components/widgets/users/avatar/avatar.tsx
Labels: 4: Reviews Complete, release-note-none

#9382 [MM-39287] - Fix alignment of clear button in message deleted indicator
  sass/components/_post.scss
Labels: 4: Reviews Complete, release-note-none

#9373 bug/MM-39875 : Fix warning printed after closing any ModalController modal
  reducers/views/modals.test.tsx
  reducers/views/modals.ts
Labels: 4: Reviews Complete, release-note-none

#9380 Cypress/E2E: Fix for downloading export
  .gitignore
  e2e/cypress/integration/enterprise/system_console/compliance/download_bot_compliance_export_file_spec.js
  e2e/cypress/integration/enterprise/system_console/compliance/download_compliance_export_file_spec.js
  e2e/cypress/integration/enterprise/system_console/compliance/helpers.js
  e2e/cypress/plugins/index.js
  e2e/cypress/plugins/shell.js
  e2e/cypress/support/index.js
  e2e/cypress/support/shell.d.ts
  e2e/cypress/support/shell.js
  e2e/package-lock.json
  e2e/package.json
Labels: 4: Reviews Complete, release-note-none

#9417 Cypress/E2E: Fix channel files search and default max file size
  e2e/cypress/integration/files_and_attachments/channel_files_spec.js
  e2e/cypress/integration/system_console/unsaved_changes_spec.js
  e2e/cypress/support/ui/sidebar_right.d.ts
  e2e/cypress/support/ui/sidebar_right.js
Labels: 4: Reviews Complete, release-note-none

#9418 Remove unused getYoutubeVideoInfo function
  actions/integration_actions.jsx
Labels: 4: Reviews Complete, release-note-none

#9409 Removing remaining jquery imports
  components/activity_log_modal/activity_log_modal.tsx
  components/admin_console/brand_image_setting/brand_image_setting.tsx
  components/admin_console/file_upload_setting.jsx
  components/admin_console/remove_file_setting.jsx
  components/audio_video_preview.jsx
  components/code_preview.jsx
  components/post_view/scroll_to_bottom_arrows.jsx
  components/searchable_channel_list.jsx
  components/searchable_user_list/searchable_user_list.jsx
  components/settings_sidebar.tsx
  components/team_general_tab/team_general_tab.jsx
  components/team_settings_modal/team_settings_modal.tsx
  package-lock.json
  package.json
  tests/helpers/client-test-helper.jsx
Labels: 4: Reviews Complete, release-note-none

#9420 chore/MM-37187 : Updated only definetlyTyped packages; no parent package updates - Nov 21
  package-lock.json
  package.json
Labels: 4: Reviews Complete, release-note-none, QA Deferred

#9406 Command Shift F search in global threads without prefilled term
  components/search/search.tsx
Labels: Setup Cloud Test Server, 1: UX Review, release-note

#9366 Changing "One-click" to "Quick" reactions on messages
  components/user_settings/display/__snapshots__/user_settings_display.test.tsx.snap
  components/user_settings/display/user_settings_display.tsx
  e2e/cypress/integration/accessibility/accessibility_account_settings_spec.js
  i18n/en.json
Labels: Setup Cloud Test Server, QA Review Done, release-note

#9368 Latex Rendering Updates
  components/admin_console/admin_definition.jsx
  i18n/en.json
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note

#9428 Cypress/E2E: Fix flaky tests on MFA
  e2e/cypress/integration/enterprise/auth_sso/mfa_authentication_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/guest_identification_spec.js
  e2e/cypress/integration/signin_authentication/mfa_authentication_spec.js
  e2e/cypress/support/ui/index.js
  e2e/cypress/support/ui/mfa.d.ts
  e2e/cypress/support/ui/mfa.js
Labels: 4: Reviews Complete, release-note-none

#9429 Cypress/E2E: Fix user profile focus and menu option aria-label
  components/status_dropdown/__snapshots__/status_dropdown.test.tsx.snap
  components/status_dropdown/status_dropdown.tsx
  e2e/cypress/integration/accessibility/accessibility_dropdowns_spec.js
  e2e/cypress/integration/accessibility/accessibility_post_spec.js
  e2e/cypress/integration/enterprise/accessibility/accessibility_modals_dialogs_spec.js
Labels: 4: Reviews Complete, release-note-none

#9431 Cypress/E2E: Fix public links and channel mode
  e2e/cypress/integration/enterprise/ldap_group/channel_modes_spec.js
  e2e/cypress/integration/enterprise/system_console/about/edition_and_license_spec.js
  e2e/cypress/integration/enterprise/system_console/edition_and_license_link_spec.js
  e2e/cypress/integration/system_console/site_configuration/link_customization_e20_2_spec.js
  e2e/cypress/utils/constants.js
Labels: 4: Reviews Complete, release-note-none

#9437 Cypress/E2E: Set @cypress/request to 2.88.7 to avoid error when installing deprecated "har-validator"
  e2e/package-lock.json
  e2e/package.json
Labels: release-note-none

#9438 Lock CI from /release-6.2
  .circleci/config.yml
  .gitlab-ci.yml
Labels: release-note-none

#9221 [MM-20590] Migrate 'components/interactive_dialog/dialog_element' module and associated tests to TypeScript
  components/interactive_dialog/dialog_element/dialog_element.test.tsx
  components/interactive_dialog/dialog_element/dialog_element.tsx
  components/interactive_dialog/dialog_element/index.js
  components/interactive_dialog/dialog_element/index.ts
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted, release-note-none, Contributor

#9439 Fixing attachments code preview
  components/code_preview.jsx
Labels: 4: Reviews Complete, release-note-none, QA Deferred

#9442 Automated cherry pick of #9368
  components/admin_console/admin_definition.jsx
  i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#9441 Automated cherry pick of #9366
  components/user_settings/display/__snapshots__/user_settings_display.test.tsx.snap
  components/user_settings/display/user_settings_display.tsx
  e2e/cypress/integration/accessibility/accessibility_account_settings_spec.js
  i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#9440 Automated cherry pick of #9439
  components/code_preview.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#9443 Automated cherry pick of #9382
  sass/components/_post.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#9444 MM-27450 Remove remaining references to jQuery 🎉
  .eslintrc.json
  NOTICE.txt
  components/admin_console/admin_console.tsx
  components/channel_header/channel_header.js
  package-lock.json
  package.json
  tests/setup.js
  webpack.config.js
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none

#9435 [MM-40340] Uninitialize webapp plugin when a new version gets deployed
  plugins/index.js
Labels: 4: Reviews Complete, release-note-none

#9323 [MM-38239 & MM-39788] Recent files causing crash
  actions/views/rhs.ts
  components/file_preview_modal/file_preview_modal_info/__snapshots__/file_preview_modal_info.test.tsx.snap
  components/file_preview_modal/file_preview_modal_info/file_preview_modal_info.test.tsx
  components/file_preview_modal/file_preview_modal_info/file_preview_modal_info.tsx
  packages/mattermost-redux/src/actions/posts.ts
  packages/mattermost-redux/src/client/client4.ts
Labels: 4: Reviews Complete, release-note-none

#9412 Updated Terms of Service to Terms of Use
  components/about_build_modal/__snapshots__/about_build_modal.test.tsx.snap
  components/about_build_modal/about_build_modal.tsx
  components/admin_console/admin_definition.jsx
  components/admin_console/license_settings/__snapshots__/license_settings.test.jsx.snap
  components/admin_console/license_settings/license_settings.tsx
  components/login/login_controller/login_controller.jsx
  components/signup/signup_email/__snapshots__/signup_email.test.tsx.snap
  components/signup/signup_email/signup_email.tsx
  e2e/cypress/integration/enterprise/system_console/edition_and_license_link_spec.js
  e2e/cypress/integration/signin_authentication/signup_spec.js
  e2e/cypress/integration/system_console/site_configuration/link_customization_e20_2_spec.js
  e2e/cypress/integration/system_console/ui_and_api/customization_not_cloud_spec.js
  e2e/cypress/support/api/on_prem_default_config.json
  e2e/cypress/utils/constants.js
  i18n/en.json
Labels: 4: Reviews Complete, release-note

#9419 Removing some unused files and components
  components/admin_console/connection_security_dropdown_setting.jsx
  components/button_selector.tsx
  components/confirm_notify_admin_modal/confirm_notify_admin.svg.tsx
  components/confirm_notify_admin_modal/confirm_notify_admin_modal.scss
  components/confirm_notify_admin_modal/confirm_notify_admin_modal.tsx
  components/confirm_notify_admin_modal/index.tsx
  components/file_attachment/__snapshots__/filename_overlay.test.tsx.snap
  components/file_attachment/filename_overlay.test.tsx
  components/size_aware_image.test.jsx
  components/user_limit_modal/__snapshots__/user_limit_modal.test.tsx.snap
  components/user_limit_modal/index.ts
  components/user_limit_modal/user_limit_modal.scss
  components/user_limit_modal/user_limit_modal.test.tsx
  components/user_limit_modal/user_limit_modal.tsx
  components/user_limit_modal/user_limit_upgrade_svg.tsx
  components/widgets/icons/arrow_right_icon.tsx
  components/widgets/icons/bot_icon.tsx
  components/widgets/icons/download_icon.tsx
  components/widgets/icons/draft_icon.tsx
  components/widgets/icons/fa_remove_icon.tsx
  components/widgets/icons/fa_select_icon.tsx
  components/widgets/icons/icons.stories.js
  components/widgets/icons/invite_icon.tsx
  components/widgets/icons/invite_members_icon.tsx
  components/widgets/icons/link_icon.tsx
  components/widgets/icons/member_icon.tsx
  i18n/en.json
  utils/image_utils.jsx
Labels: 4: Reviews Complete, release-note-none

#9363 Don't close statusmenu on header click
  components/status_dropdown/__snapshots__/status_dropdown.test.tsx.snap
  components/status_dropdown/status_dropdown.tsx
  components/widgets/menu/menu_items/__snapshots__/submenu_item.test.tsx.snap
  components/widgets/menu/menu_items/submenu_item.tsx
  e2e/cypress/integration/menus/status_dropdown_spec.js
Labels: 4: Reviews Complete, AutoMerge, release-note-none, Contributor

#9447 Automated cherry pick of #9323
  actions/views/rhs.ts
  components/file_preview_modal/file_preview_modal_info/__snapshots__/file_preview_modal_info.test.tsx.snap
  components/file_preview_modal/file_preview_modal_info/file_preview_modal_info.test.tsx
  components/file_preview_modal/file_preview_modal_info/file_preview_modal_info.tsx
  packages/mattermost-redux/src/actions/posts.ts
  packages/mattermost-redux/src/client/client4.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#9371 Lazy loading pdf.js library
  components/pdf_preview.jsx
  plugins/export.js
  root.jsx
Labels: 3: QA Review, Setup Cloud Test Server, release-note-none

#9421 chore/MM-37187 : Update minor or patch version of the packages - Nov 21
  package-lock.json
  package.json
Labels: 4: Reviews Complete, release-note-none

#9220 MM-32783: header & footer for threads in search
  components/search_results_item/__snapshots__/search_results_item.test.jsx.snap
  components/search_results_item/index.ts
  components/search_results_item/search_results_item.jsx
  components/search_results_item/search_results_item.test.jsx
  components/threading/channel_threads/thread_footer/thread_footer.tsx
  i18n/en.json
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted, release-note, Contributor

#9453 Automated cherry pick of #9450 on cloud
  i18n/bg.json
  i18n/de.json
  i18n/en_AU.json
  i18n/es.json
  i18n/fr.json
  i18n/hu.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: release-note-none
