Repository mattermost/mattermost-webapp, pull requests merged in 2021-09, with the labels that each got.

#8760 [MM-38241] Use DOMParser to parse tables from clipboard
  e2e/cypress/integration/messaging/post_html_table_spec.js
  utils/paste.tsx
Labels: 4: Reviews Complete, release-note-none

#8772 Automated cherry pick of #8760
  e2e/cypress/integration/messaging/post_html_table_spec.js
  utils/paste.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, do-not-merge/release-note-label-needed

#8771 Automated cherry pick of #8760
  e2e/cypress/integration/messaging/post_html_table_spec.js
  utils/paste.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, do-not-merge/release-note-label-needed

#8770 Automated cherry pick of #8754
  components/post_view/post/post.jsx
  sass/layout/_markdown.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, do-not-merge/release-note-label-needed

#8769 Automated cherry pick of #8754
  components/post_view/post/post.jsx
  sass/layout/_markdown.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, do-not-merge/release-note-label-needed

#8443 ApplyTheme Updates – convert older changeCSS JS to CSS variables part 2
  components/shortcut_key/shortcut_key.scss
  sass/components/_alerts.scss
  sass/components/_dropdown.scss
  sass/components/_emoticons.scss
  sass/components/_modal.scss
  sass/components/_popover.scss
  sass/components/_post.scss
  sass/components/_sidebar-card.scss
  sass/components/_status-icon.scss
  sass/components/_system-notice.scss
  sass/components/_tutorial.scss
  sass/layout/_content.scss
  sass/layout/_markdown.scss
  sass/layout/_navigation.scss
  sass/layout/_webhooks.scss
  sass/utils/_modifiers.scss
  utils/utils.jsx
Labels: Setup Cloud Test Server, QA Review Done, release-note-none

#8648 make `ProductBranding` component clickable
  components/global/global_header.tsx
  components/global/product_switcher.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, QA Review Done, release-note-none

#8773 Automated cherry pick of #8648
  components/global/global_header.tsx
  components/global/product_switcher.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, do-not-merge/release-note-label-needed

#8759 [MM-38209] - removed propagation stop on handler function
  components/post_view/post/post.jsx
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none, kind/bug

#8775 Automated cherry pick of #8759
  components/post_view/post/post.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, do-not-merge/release-note-label-needed

#8756 [MM-37708] - changed font-family to Open Sans on popover title
  sass/components/_popover.scss
Labels: 4: Reviews Complete, release-note-none

#8678 Feature/mm 37916 close product switcher on item click
  components/global/product_switcher.tsx
  components/global/product_switcher_menu/product_switcher_menu.tsx
  components/widgets/menu/menu_group.tsx
Labels: 2: Dev Review, CherryPick/Approved, Setup Cloud Test Server, QA Review Done, release-note-none

#8777 Automated cherry pick of #8678
  components/global/product_switcher.tsx
  components/global/product_switcher_menu/product_switcher_menu.tsx
  components/widgets/menu/menu_group.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, do-not-merge/release-note-label-needed

#8590 chore/MM-17293 : Migrate 'components/invitation_modal/invitation_modal_guest_step' and associated tests to TypeScript
  components/invitation_modal/invitation_modal_guest_step/__snapshots__/invitation_modal_guests_step.test.tsx.snap
  components/invitation_modal/invitation_modal_guest_step/index.ts
  components/invitation_modal/invitation_modal_guest_step/invitation_modal_guests_step.test.tsx
  components/invitation_modal/invitation_modal_guest_step/invitation_modal_guests_step.tsx
  packages/mattermost-redux/src/actions/helpers.ts
Labels: 4: Reviews Complete, release-note-none

#8755 MM-37957: fixes overlapping separators in thread
  sass/components/_post-right.scss
Labels: 4: Reviews Complete, release-note-none

#8757 MM-38147 - validate guest users cannot invite
  components/post_view/channel_intro_message/add_members_button.tsx
  components/sidebar/__snapshots__/invite_members.test.tsx.snap
  components/sidebar/__snapshots__/invite_members_button.test.tsx.snap
  components/sidebar/invite_members_button.test.tsx
  components/sidebar/invite_members_button.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, QA Review Done, release-note-none

#8749 [MM-37814] - Handle quick switch shortcut in channel navigator
  components/global/global_search_nav/global_search_nav.tsx
  components/rhs_search_nav/index.ts
  components/rhs_search_nav/rhs_search_nav.tsx
  components/sidebar/channel_navigator/channel_navigator.test.tsx
  components/sidebar/channel_navigator/channel_navigator.tsx
  components/sidebar/channel_navigator/index.ts
Labels: 4: Reviews Complete, release-note-none

#8386 Distinguish between RHS and main channel for Apps Commands.
  actions/command.test.js
  actions/global_actions.tsx
  actions/views/create_comment.tsx
  actions/websocket_actions.jsx
  components/create_comment/create_comment.tsx
  components/suggestion/command_provider/app_command_parser/app_command_parser.test.ts
  components/suggestion/command_provider/app_command_parser/app_command_parser.ts
  components/suggestion/command_provider/app_command_parser/app_command_parser_dependencies.ts
  components/suggestion/command_provider/command_provider.tsx
  components/textbox/textbox.tsx
  components/threading/thread_viewer/index.ts
  components/threading/thread_viewer/thread_viewer.test.tsx
  components/threading/thread_viewer/thread_viewer.tsx
  packages/mattermost-redux/src/action_types/apps.ts
  packages/mattermost-redux/src/actions/apps.ts
  packages/mattermost-redux/src/client/client4.ts
  packages/mattermost-redux/src/reducers/entities/apps.test.ts
  packages/mattermost-redux/src/reducers/entities/apps.ts
  packages/mattermost-redux/src/selectors/entities/apps.test.ts
  packages/mattermost-redux/src/selectors/entities/apps.ts
  packages/mattermost-redux/src/store/initial_state.ts
  packages/mattermost-redux/src/types/apps.ts
Labels: 4: Reviews Complete, release-note

#8786 Translations update from Weblate
  i18n/bg.json
  i18n/de.json
  i18n/en_AU.json
  i18n/es.json
  i18n/fr.json
  i18n/hu.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 2: Dev Review, 3: QA Review, release-note-none

#8781 [MM-37897] - added fading to the "new channel category dropzone box"
  components/next_steps_view/steps.ts
  sass/layout/_sidebar-left.scss
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none, kind/bug

#8791 Fixes "property.roles" of undefined
  components/global/user_guide_dropdown/index.ts
Labels: 4: Reviews Complete, release-note-none, kind/bug

#8774 WIP: [MM-38237] - fixing misaligned download-outline icon
  package.json
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none, kind/bug

#8795 security: add dependency track configuration (#8741)
  .gobom.json
Labels: 4: Reviews Complete, release-note-none

#8794 Automated cherry pick of #8774
  package.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, do-not-merge/release-note-label-needed

#8783 Automated cherry pick of #8664
  components/threading/channel_threads/thread_footer/__snapshots__/thread_footer.test.tsx.snap
  components/threading/channel_threads/thread_footer/thread_footer.test.tsx
  components/threading/channel_threads/thread_footer/thread_footer.tsx
  components/threading/global_threads/thread_item/__snapshots__/thread_item.test.tsx.snap
  components/threading/global_threads/thread_item/thread_item.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, do-not-merge/release-note-label-needed

#8684 [MM-37978] - Start Trial CTA in Main Menu
  components/global/product_switcher_menu/product_switcher_menu.tsx
  components/main_menu/main_menu.jsx
  components/main_menu/main_menu.test.jsx
  components/start_trial_modal/index.tsx
  components/start_trial_modal/start_trial_modal.scss
  components/start_trial_modal/start_trial_modal_svg.tsx
  components/widgets/menu/menu.tsx
  components/widgets/menu/menu_items/menu_item.scss
  components/widgets/menu/menu_items/menu_start_trial.test.tsx
  components/widgets/menu/menu_items/menu_start_trial.tsx
  i18n/en.json
  plugins/test/__snapshots__/main_menu_action.test.jsx.snap
  utils/constants.jsx
Labels: Setup Cloud Test Server, QA Review Done, 1: UX Review, release-note-none

#8798 Automated cherry pick of #8684
  components/global/product_switcher_menu/product_switcher_menu.tsx
  components/main_menu/main_menu.jsx
  components/main_menu/main_menu.test.jsx
  components/start_trial_modal/index.tsx
  components/start_trial_modal/start_trial_modal.scss
  components/start_trial_modal/start_trial_modal_svg.tsx
  components/widgets/menu/menu.tsx
  components/widgets/menu/menu_items/menu_item.scss
  components/widgets/menu/menu_items/menu_start_trial.test.tsx
  components/widgets/menu/menu_items/menu_start_trial.tsx
  i18n/en.json
  plugins/test/__snapshots__/main_menu_action.test.jsx.snap
  utils/constants.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, do-not-merge/release-note-label-needed

#8788 Updates .editorconfig to handle typescript files
  .editorconfig
Labels: 4: Reviews Complete, release-note-none

#8790 Automated cherry pick of #8781
  components/next_steps_view/steps.ts
  sass/layout/_sidebar-left.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, do-not-merge/release-note-label-needed

#8799 Automated cherry pick of #8757
  components/post_view/channel_intro_message/add_members_button.tsx
  components/sidebar/__snapshots__/invite_members.test.tsx.snap
  components/sidebar/__snapshots__/invite_members_button.test.tsx.snap
  components/sidebar/invite_members_button.test.tsx
  components/sidebar/invite_members_button.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#8708 [MM-36789] Thread Root Post
  components/threading/global_threads/thread_item/thread_item.test.tsx
  components/threading/global_threads/thread_item/thread_item.tsx
Labels: 4: Reviews Complete, release-note

#8768 MM-38159 - Fix license checks in System Console for Starter License
  components/admin_console/admin_definition.jsx
  components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.jsx.snap
  components/admin_console/admin_sidebar/admin_sidebar.test.jsx
Labels: 4: Reviews Complete, QA Review Done, Setup Cloud + CWS Test Server, release-note-none

#8667 [MM-37814] - Adjust status dropdown according to design
  components/compass_theme_provider/compass_theme_provider.tsx
  components/global/global_header.scss
  components/status_dropdown/__snapshots__/status_dropdown.test.tsx.snap
  components/status_dropdown/status_dropdown.tsx
  components/widgets/menu/menu_items/menu_item_action.tsx
  components/widgets/menu/menu_items/submenu_item.test.tsx
  components/widgets/menu/menu_items/submenu_item.tsx
  package-lock.json
  sass/components/_status-icon.scss
Labels: 3: QA Review, Setup Cloud Test Server, release-note-none

#8789 Cypress/E2E: Fix failed tests on header info due to global header
  e2e/cypress/integration/accessibility/accessibility_dropdowns_spec.js
  e2e/cypress/integration/accessibility/accessibility_nav_diff_regions_spec.js
  e2e/cypress/integration/accessibility/accessibility_sidebar_spec.js
  e2e/cypress/integration/account_settings/general/email_spec.js
  e2e/cypress/integration/account_settings/general/fullname_truncate_spec.js
  e2e/cypress/integration/account_settings/general/main_menu_stays_open_spec.js
  e2e/cypress/integration/auth_sso/authentication_4_spec.js
  e2e/cypress/integration/bot_accounts/bot_api_spec.js
  e2e/cypress/integration/bot_accounts/create_bot_spec.js
  e2e/cypress/integration/bot_accounts/edit_bot_spec.js
  e2e/cypress/integration/bot_accounts/promote_demote_spec.js
  e2e/cypress/integration/channel_sidebar/dm_gm_filtering_sorting_spec.js
  e2e/cypress/integration/channel_sidebar/group_unreads_separately_spec.js
  e2e/cypress/integration/enterprise/accessibility/accessibility_input_fields_spec.js
  e2e/cypress/integration/enterprise/accessibility/accessibility_modals_dialogs_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/guest_experience_ui_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/guest_identification_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/guest_identification_ui_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/guest_invitation_ui_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/helpers.js
  e2e/cypress/integration/enterprise/guest_accounts/member_invitation_ui_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/system_console_guest_access_ui_spec.js
  e2e/cypress/integration/enterprise/ldap/ldap_guest_spec.js
  e2e/cypress/integration/enterprise/oauth/oauth_spec.js
  e2e/cypress/integration/enterprise/permissions/team_permissions_spec.js
  e2e/cypress/integration/integrations/slash_commands_spec.js
  e2e/cypress/integration/system_console/user_management_not_cloud_spec.js
  e2e/cypress/integration/team_settings/create_a_team_spec.js
  e2e/cypress/integration/team_settings/teammates_pagination_spec.js
  e2e/cypress/integration/team_settings/teams_spec.js
  e2e/cypress/support/ui/account_settings_modal.js
  e2e/cypress/support/ui/common.js
  e2e/cypress/support/ui/global_header.d.ts
  e2e/cypress/support/ui/global_header.js
  e2e/cypress/support/ui/index.js
  e2e/cypress/support/ui/sidebar_left.d.ts
  e2e/cypress/support/ui/sidebar_left.js
  e2e/cypress/support/ui_commands.js
  e2e/package-lock.json
Labels: 4: Reviews Complete, release-note-none

#8803 [MM-38420] Fix root message being equal
  packages/mattermost-redux/src/reducers/entities/channels/message_counts.test.js
  packages/mattermost-redux/src/reducers/entities/channels/message_counts.ts
Labels: Setup Cloud Test Server, release-note-none, QA Deferred

#8800 Make invite members button always show as lhs button and remove featu…
  components/sidebar/__snapshots__/invite_members_button.test.tsx.snap
  components/sidebar/channel_navigator/channel_navigator.tsx
  components/sidebar/invite_members_button.test.tsx
  components/sidebar/invite_members_button.tsx
  components/sidebar/sidebar_category/__snapshots__/sidebar_category.test.tsx.snap
  components/sidebar/sidebar_category/sidebar_category.tsx
  components/sidebar/sidebar_channel_list/__snapshots__/sidebar_channel_list.test.tsx.snap
  components/sidebar/sidebar_channel_list/sidebar_channel_list.tsx
  package-lock.json
  packages/mattermost-redux/src/constants/config.ts
  packages/mattermost-redux/src/selectors/entities/preferences.ts
  packages/mattermost-redux/src/types/config.ts
Labels: 3: QA Review, Setup Cloud + CWS Test Server, release-note

#8808 Automated cherry pick of #8667
  components/compass_theme_provider/compass_theme_provider.tsx
  components/global/global_header.scss
  components/status_dropdown/__snapshots__/status_dropdown.test.tsx.snap
  components/status_dropdown/status_dropdown.tsx
  components/widgets/menu/menu_items/menu_item_action.tsx
  components/widgets/menu/menu_items/submenu_item.test.tsx
  components/widgets/menu/menu_items/submenu_item.tsx
  package-lock.json
  sass/components/_status-icon.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, do-not-merge/release-note-label-needed

#8809 Automated cherry pick of #8749
  components/global/global_search_nav/global_search_nav.tsx
  components/rhs_search_nav/index.ts
  components/rhs_search_nav/rhs_search_nav.tsx
  components/sidebar/channel_navigator/channel_navigator.test.tsx
  components/sidebar/channel_navigator/channel_navigator.tsx
  components/sidebar/channel_navigator/index.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, do-not-merge/release-note-label-needed

#8780 MM-38060 - Fix license check for Themes and others in System Console
  components/admin_console/admin_definition.jsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, QA Review Done, release-note-none

#8814 Automated cherry pick of #8755
  sass/components/_post-right.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, do-not-merge/release-note-label-needed

#8812 Automated cherry pick of #8708
  components/threading/global_threads/thread_item/thread_item.test.tsx
  components/threading/global_threads/thread_item/thread_item.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, do-not-merge/release-note-label-needed

#8796 Bugfix - roles error with global header enabled
  components/global/global_header.tsx
  components/global/hooks.tsx
  components/global/user_guide_dropdown/index.ts
  components/next_steps_view/steps.ts
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none, kind/bug

#8816 Automated cherry pick of #8796
  components/global/global_header.tsx
  components/global/hooks.tsx
  components/next_steps_view/steps.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, do-not-merge/release-note-label-needed

#8813 Automated cherry pick of #8755
  sass/components/_post-right.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, do-not-merge/release-note-label-needed

#8811 Automated cherry pick of #8708
  components/threading/global_threads/thread_item/thread_item.test.tsx
  components/threading/global_threads/thread_item/thread_item.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, do-not-merge/release-note-label-needed

#8656 Added support to exclude specific emoji by short name
  build/emoji/emoji_gen.mjs
Labels: 4: Reviews Complete, release-note

#8739 Fix JS error on joining missing channel as sysadmin
  components/channel_layout/channel_identifier_router/actions.ts
Labels: 4: Reviews Complete, release-note

#8817 [MM-38280] Fixing doc link for permalinks
  components/admin_console/admin_definition.jsx
  i18n/en.json
  i18n/en_AU.json
Labels: 3: QA Review, CherryPick/Approved, release-note-none

#8820 Automated cherry pick of #8817
  components/admin_console/admin_definition.jsx
  i18n/en.json
  i18n/en_AU.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#8819 Cypress/E2E: Fix tests related to global header
  e2e/cypress/integration/emoji/custom_emoji_1_spec.js
  e2e/cypress/integration/emoji/custom_emoji_2_spec.js
  e2e/cypress/integration/emoji/custom_emoji_3_spec.js
  e2e/cypress/integration/emoji/recently_used_emoji_spec.js
  e2e/cypress/integration/emoji/sorted_emojis_spec.js
  e2e/cypress/integration/integrations/integrations_spec.js
  e2e/cypress/integration/messaging/emoji_insert_position_spec.js
  e2e/cypress/integration/messaging/emoji_keyboard_entry_spec.js
  e2e/cypress/integration/messaging/emoji_picker_keyboard_usability_spec.js
  e2e/cypress/integration/messaging/reactions_spec.js
  e2e/cypress/integration/notifications/desktop_notifications_1_spec.js
  e2e/cypress/integration/notifications/desktop_notifications_2_spec.js
  e2e/cypress/integration/notifications/desktop_notifications_3_spec.js
  e2e/cypress/integration/notifications/desktop_notifications_spec.js
  e2e/cypress/integration/notifications/helper.js
  e2e/cypress/integration/onboarding/tutorial_guided_tour_spec.js
  e2e/cypress/integration/plugins/marketplace/disabled_remote_marketplace_spec.js
  e2e/cypress/integration/plugins/marketplace/helpers.js
  e2e/cypress/integration/plugins/marketplace/invalid_marketplace_url_spec.js
  e2e/cypress/integration/plugins/marketplace/ui_spec.js
  e2e/cypress/integration/signin_authentication/authentication_spec.js
  e2e/cypress/integration/signin_authentication/desktop_session_expire_spec.js
  e2e/cypress/integration/system_console/sidebar_link_navigation_not_cloud_spec.js
  e2e/cypress/integration/system_console/sidebar_link_navigation_spec.js
  e2e/cypress/integration/team_settings/invite_members_spec.js
  e2e/cypress/support/ui/common.js
  e2e/cypress/support/ui/emoji.d.ts
  e2e/cypress/support/ui/emoji.js
  e2e/cypress/support/ui/global_header.d.ts
  e2e/cypress/support/ui/global_header.js
  e2e/cypress/support/ui/index.js
  e2e/cypress/support/ui/sidebar_left.d.ts
  e2e/cypress/support/ui/sidebar_left.js
Labels: 4: Reviews Complete, release-note-none

#8818 downgrading Italian and Polish to Alpha
  components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
  i18n/i18n.jsx
Labels: 4: Reviews Complete, Changelog/Done, Docs/Done, CherryPick/Approved, release-note-none

#8823 Automated cherry pick of #8818
  components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
  i18n/i18n.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge

#8822 Automated cherry pick of #8818
  components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
  i18n/i18n.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note

#8797 [MM-34870] - fixing post-highlighting
  sass/components/_post.scss
  utils/utils.jsx
Labels: 4: Reviews Complete, release-note-none, kind/bug

#8765 MM-38193 Add missing i18n strings from MoreChannels modal
  components/searchable_channel_list.jsx
  i18n/en.json
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#8825 Automated cherry pick of #8765
  components/searchable_channel_list.jsx
  i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, do-not-merge/release-note-label-needed

#8807 extends the `Screenshots` section in the PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 2: Dev Review, release-note-none

#8778 MM-38093: updates notifications copy on CRT replies
  actions/notification_actions.jsx
  actions/notification_actions.test.js
  i18n/en.json
Labels: 4: Reviews Complete, release-note-none

#8833 Translations update from Weblate
  i18n/bg.json
  i18n/de.json
  i18n/en_AU.json
  i18n/hu.json
  i18n/ja.json
  i18n/sv.json
  i18n/tr.json
  i18n/zh-CN.json
Labels: 2: Dev Review, 3: QA Review, release-note-none

#8805 [MM-37694] - fixing getting started colors
  components/sidebar/sidebar_next_steps/sidebar_next_steps.scss
Labels: 2: Dev Review, Setup Cloud Test Server, QA Review Done, release-note-none, kind/bug

#8832 match invite members button space with other lhs spacing
  components/sidebar/invite_members_button.tsx
  components/sidebar/sidebar_category/__snapshots__/sidebar_category.test.tsx.snap
  components/sidebar/sidebar_category/sidebar_category.tsx
  sass/layout/_sidebar-left.scss
Labels: 2: Dev Review, CherryPick/Approved, QA Review Done, Setup Cloud + CWS Test Server, release-note

#8827 [MM-38427] - Start Trial option showing in Daily
  components/widgets/menu/menu_items/menu_start_trial.test.tsx
  components/widgets/menu/menu_items/menu_start_trial.tsx
Labels: 2: Dev Review, CherryPick/Approved, QA Review Done, release-note-none

#8837 Automated cherry pick of #8832
  components/sidebar/invite_members_button.tsx
  components/sidebar/sidebar_category/__snapshots__/sidebar_category.test.tsx.snap
  components/sidebar/sidebar_category/sidebar_category.tsx
  sass/layout/_sidebar-left.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, do-not-merge/release-note-label-needed

#8838 Automated cherry pick of #8827
  components/widgets/menu/menu_items/menu_start_trial.test.tsx
  components/widgets/menu/menu_items/menu_start_trial.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, do-not-merge/release-note-label-needed

#8836 remove bodyOnly prop
  components/more_channels/more_channels.tsx
  components/more_direct_channels/more_direct_channels.tsx
Labels: 4: Reviews Complete, release-note-none

#8842 Automated cherry pick of #8805
  components/sidebar/sidebar_next_steps/sidebar_next_steps.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, do-not-merge/release-note-label-needed

#8841 Automated cherry pick of #8778
  actions/notification_actions.jsx
  actions/notification_actions.test.js
  i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, do-not-merge/release-note-label-needed

#8843 Automated cherry pick of #8797
  sass/components/_post.scss
  utils/utils.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, do-not-merge/release-note-label-needed

#8830 Cypress/E2E: Fix failed tests related to Global header
  e2e/cypress/integration/accessibility/accessibility_image_spec.js
  e2e/cypress/integration/accessibility/accessibility_keyboard_usability_spec.js
  e2e/cypress/integration/account_settings/display/channel_display_mode_spec.js
  e2e/cypress/integration/account_settings/display/clock_display_mode_spec.js
  e2e/cypress/integration/account_settings/display/theme/custom_theme_color_picker_spec.js
  e2e/cypress/integration/account_settings/display/theme/custom_theme_sidebar_styles_spec.js
  e2e/cypress/integration/account_settings/display/theme/save_theme_spec.js
  e2e/cypress/integration/account_settings/general/fullname_spec.js
  e2e/cypress/integration/account_settings/general/profile_picture_spec.js
  e2e/cypress/integration/account_settings/general/username_spec.js
  e2e/cypress/integration/account_settings/security/access_history_spec.js
  e2e/cypress/integration/account_settings/security/active_sessions_spec.js
  e2e/cypress/integration/account_settings/security/password_spec.js
  e2e/cypress/integration/auth_sso/authentication_2_spec.js
  e2e/cypress/integration/enterprise/saml/saml_automated_spec.js
  e2e/cypress/integration/integrations/builtin_commands/user_status_commands_spec.js
  e2e/cypress/integration/notifications/at_mentions_spec.js
  e2e/cypress/integration/notifications/reply_notifications_spec.js
  e2e/cypress/integration/scroll/fixed_width_spec.js
  e2e/cypress/integration/signin_authentication/mfa_authentication_spec.js
  e2e/cypress/integration/system_console/lock_teammate_name_display_spec.js
  e2e/cypress/integration/system_console/site_configuration/helper.js
  e2e/cypress/integration/system_console/site_configuration/link_customization_not_cloud_spec.js
  e2e/cypress/integration/system_console/site_configuration/link_customization_spec.js
  e2e/cypress/integration/team_settings/join_closed_team_with_not_allowed_email_spec.js
  e2e/cypress/integration/team_settings/manage_members_spec.js
  e2e/cypress/integration/team_settings/remove_team_icon_spec.js
  e2e/cypress/support/common_login_commands.js
  e2e/cypress/support/ldap_commands.js
  e2e/cypress/support/saml_commands.js
  e2e/cypress/support/ui/global_header.d.ts
  e2e/cypress/support/ui/global_header.js
  e2e/cypress/support/ui/index.js
  e2e/cypress/support/ui/login.d.ts
  e2e/cypress/support/ui/login.js
  e2e/cypress/support/ui_commands.js
  e2e/cypress/utils/index.js
Labels: 4: Reviews Complete, release-note-none

#8847 Cypress/E2E: fix tests related to global header changes
  e2e/cypress/fixtures/account_setting_sections.json
  e2e/cypress/fixtures/console-example-inputs.json
  e2e/cypress/fixtures/favicon-default-16x16.png
  e2e/cypress/fixtures/favicon-mentions-16x16.png
  e2e/cypress/fixtures/system-roles-console-access.json
  e2e/cypress/integration/accessibility/accessibility_account_settings_spec.js
  e2e/cypress/integration/channel/archived_channels_1_spec.js
  e2e/cypress/integration/channel_sidebar/category_collapsing_spec.js
  e2e/cypress/integration/channel_sidebar/channel_sidebar_spec.js
  e2e/cypress/integration/channel_sidebar/dm_gm_behaviour_spec.js
  e2e/cypress/integration/channel_sidebar/drag_and_drop_spec.js
  e2e/cypress/integration/channel_sidebar/history_channel_switcher_spec.js
  e2e/cypress/integration/channel_sidebar/hotkeys_spec.js
  e2e/cypress/integration/channel_sidebar/new_channel_dropdown_spec.js
  e2e/cypress/integration/enterprise/cloud/onboarding/finish_tutorial_spec.js
  e2e/cypress/integration/enterprise/cloud/onboarding/login_page_link_account_creation_spec.js
  e2e/cypress/integration/enterprise/ldap/ldap_login_spec.js
  e2e/cypress/integration/integrations/builtin_commands/common_commands_2_spec.js
  e2e/cypress/integration/interactive_menu/basic_options_spec.js
  e2e/cypress/integration/keyboard_shortcuts/keyboard_shortcuts_1_spec.js
  e2e/cypress/integration/keyboard_shortcuts/keyboard_shortcuts_2_spec.js
  e2e/cypress/integration/keyboard_shortcuts/keyboard_shortcuts_3_spec.js
  e2e/cypress/integration/messaging/permalink_click_spec.js
  e2e/cypress/integration/multi_team_and_dm/join_open_team_from_dm_spec.js
  e2e/cypress/integration/multi_team_and_dm/multi_team_spec.js
  e2e/cypress/integration/multi_team_and_dm/send_dm_user_no_team_spec.js
  e2e/cypress/integration/notifications/browser_tab_notification_spec.js
  e2e/cypress/integration/onboarding/use_team_invite_link_to_sign_up_spec.js
  e2e/cypress/integration/team_settings/closed_team_invite_by_email_spec.js
  e2e/cypress/integration/team_settings/helpers.js
  e2e/cypress/integration/websocket/channel_created/new_sidebar_spec.js
  e2e/cypress/integration/websocket/channel_created/old_sidebar_spec.js
  e2e/cypress/integration/websocket/handle_removed_user/helpers.js
  e2e/cypress/support/ui_commands.js
Labels: 4: Reviews Complete, release-note-none

#8541 [MM-36444] Manage 6.0 deprecations
  components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
  components/admin_console/admin_definition.jsx
  components/admin_console/schema_admin_settings.test.jsx
  components/channel_header/index.js
  components/channel_header_dropdown/index.js
  components/channel_header_mobile/index.js
  components/create_comment/index.ts
  components/create_post/index.ts
  components/post_view/channel_intro_message/index.ts
  components/post_view/post_body/index.js
  components/post_view/post_info/index.ts
  components/post_view/reaction/index.ts
  components/rhs_comment/index.ts
  components/rhs_root_post/index.ts
  e2e/cypress/support/api/cloud_default_config.json
  e2e/cypress/support/api/on_prem_default_config.json
  i18n/en.json
  packages/mattermost-redux/src/actions/roles.test.js
  packages/mattermost-redux/src/actions/roles.ts
  packages/mattermost-redux/src/selectors/entities/channels.test.js
  packages/mattermost-redux/src/selectors/entities/channels.ts
  packages/mattermost-redux/src/selectors/entities/general.test.js
  packages/mattermost-redux/src/selectors/entities/general.ts
  packages/mattermost-redux/src/types/config.ts
  packages/mattermost-redux/src/utils/channel_utils.test.js
  packages/mattermost-redux/src/utils/channel_utils.ts
  packages/mattermost-redux/src/utils/post_utils.test.js
  packages/mattermost-redux/src/utils/post_utils.ts
  utils/policy_roles_adapter.test.jsx
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#8855 Automated cherry pick of #8739
  components/channel_layout/channel_identifier_router/actions.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, do-not-merge/release-note-label-needed

#8792 [MM-37052] Payment information test scripts for system console
  e2e/cypress.json
  e2e/cypress/fixtures/client_billing.json
  e2e/cypress/integration/enterprise/cloud/billing/payment_information_after_subscription_spec.js
  e2e/cypress/support/ui/cloud_billing.d.ts
  e2e/cypress/support/ui/cloud_billing.js
  e2e/cypress/support/ui/index.js
Labels: 4: Reviews Complete, QA Review Done, release-note-none

#8815 Fixes bot username override issue with incoming webhooks
  components/threading/global_threads/thread_item/thread_item.tsx
Labels: 4: Reviews Complete, release-note

#8859 Automated cherry pick of #8815
  components/threading/global_threads/thread_item/thread_item.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, do-not-merge/release-note-label-needed

#8850 Cypress/E2E: More test fixes
  e2e/cypress/integration/accessibility/accessibility_buttons_spec.js
  e2e/cypress/integration/account_settings/display/theme/custom_theme_sidebar_styles_spec.js
  e2e/cypress/integration/account_settings/general/username_spec.js
  e2e/cypress/integration/archived_channel/archive_channel_post_spec.js
  e2e/cypress/integration/archived_channel/join_archived_channel_spec.js
  e2e/cypress/integration/bot_accounts/tags_spec.js
  e2e/cypress/integration/custom_status/custom_status_3_spec.js
  e2e/cypress/integration/custom_status/custom_status_4_spec.js
  e2e/cypress/integration/custom_status/custom_status_5_spec.js
  e2e/cypress/integration/custom_status/helper.js
  e2e/cypress/integration/enterprise/cloud/onboarding/finish_tutorial_spec.js
  e2e/cypress/integration/enterprise/cloud/onboarding/login_page_link_account_creation_spec.js
  e2e/cypress/integration/enterprise/system_console/reporting/site_statistics_spec.js
  e2e/cypress/integration/menus/status_dropdown_spec.js
  e2e/cypress/integration/menus/user_guide_help_spec.js
  e2e/cypress/integration/messaging/focus_move_spec.js
  e2e/cypress/integration/messaging/inline_markdown_image_link_open_link_spec.js
  e2e/cypress/integration/messaging/pinned_posts_1_spec.js
  e2e/cypress/integration/messaging/pinned_posts_2_spec.js
  e2e/cypress/integration/messaging/post_header_spec.js
  e2e/cypress/integration/notifications/at_icon_still_shows_mentions_list_with_deactivated_triggers_spec.js
  e2e/cypress/integration/notifications/users_with_same_firstname_channel_ mentions_spec.js
  e2e/cypress/integration/notifications/users_with_same_firstname_channel_mentions_spec.js
  e2e/cypress/integration/onboarding/invalidate_pending_email_invitations_spec.js
  e2e/cypress/integration/status/status_dnd_1_spec.js
  e2e/cypress/integration/system_console/environment_spec.js
  e2e/cypress/integration/team_settings/helpers.js
  e2e/cypress/integration/team_settings/invite_user_to_closed_team_spec.js
  e2e/cypress/integration/websocket/handle_removed_user/helpers.js
  e2e/cypress/support/api/system.d.ts
  e2e/cypress/support/api/system.js
  e2e/cypress/support/ui/channel_header.d.ts
  e2e/cypress/support/ui/channel_header.js
  e2e/cypress/support/ui/global_header.d.ts
  e2e/cypress/support/ui/global_header.js
  e2e/cypress/support/ui/index.js
  e2e/cypress/support/ui/menu.d.ts
  e2e/cypress/support/ui/menu.js
Labels: 4: Reviews Complete, release-note-none

#8776 fixing show more button for message previews
  components/post_view/post_message_preview/__snapshots__/post_message_preview.test.tsx.snap
  components/post_view/post_message_preview/post_message_preview.tsx
  sass/components/_post.scss
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, AutoMerge, release-note-none

#8863 Automated cherry pick of #8776
  components/post_view/post_message_preview/__snapshots__/post_message_preview.test.tsx.snap
  components/post_view/post_message_preview/post_message_preview.tsx
  sass/components/_post.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, do-not-merge/release-note-label-needed

#8864 Cypress/e2e/Fixed main menu test case
  e2e/cypress/integration/menus/main_menu_spec.js
  e2e/cypress/integration/messaging/post_header_spec.js
Labels: 4: Reviews Complete, release-note-none

#8840 Mm 38361 pre written messages
  components/create_post/__snapshots__/create_post.test.jsx.snap
  components/create_post/chip.tsx
  components/create_post/create_post.test.jsx
  components/create_post/create_post.tsx
  components/create_post/create_post_tip.tsx
  components/create_post/index.ts
  components/create_post/prewritten_chips.tsx
  components/tutorial/tutorial_tip/tutorial_tip.tsx
  i18n/en.json
  packages/mattermost-redux/src/constants/config.ts
  packages/mattermost-redux/src/selectors/entities/preferences.ts
  packages/mattermost-redux/src/types/channels.ts
  packages/mattermost-redux/src/types/config.ts
  sass/base/_css_variables.scss
  sass/components/_post.scss
  sass/utils/_variables.scss
Labels: 4: Reviews Complete, QA Review Done, release-note

#8860 MM-37187 Update react-intl and update localized icons to support that
  components/__snapshots__/file_upload_overlay.test.jsx.snap
  components/admin_console/admin_navbar_dropdown/admin_navbar_dropdown.tsx
  components/admin_console/server_logs/log_list.tsx
  components/common/back_button.tsx
  components/file_upload_overlay.test.jsx
  components/file_upload_overlay.tsx
  components/localized_icon.tsx
  components/multiselect/multiselect.tsx
  components/post_view/channel_intro_message/add_members_button.tsx
  components/post_view/channel_intro_message/channel_intro_message.tsx
  components/rhs_card_header/rhs_card_header.tsx
  components/rhs_header_post/rhs_header_post.tsx
  components/search_results_header/search_results_header.tsx
  components/should_verify_email/should_verify_email.tsx
  components/status_dropdown/__snapshots__/status_dropdown.test.tsx.snap
  components/status_dropdown/status_dropdown.tsx
  components/user_settings/general/user_settings_general.tsx
  components/user_settings/security/__snapshots__/user_settings_security.test.tsx.snap
  components/user_settings/security/user_settings_security.tsx
  components/widgets/icons/admin_eye_icon.tsx
  components/widgets/icons/user_guide_icon.tsx
  package-lock.json
  package.json
Labels: 4: Reviews Complete, release-note-none

#8785 [MM-38158] Allowing username and profile pic overrides for bots
  components/post_view/post_message_preview/__snapshots__/post_message_preview.test.tsx.snap
  components/post_view/post_message_preview/index.ts
  components/post_view/post_message_preview/post_message_preview.test.tsx
  components/post_view/post_message_preview/post_message_preview.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, AutoMerge, release-note-none

#8875 fix snapshots
  components/post_view/post_message_preview/__snapshots__/post_message_preview.test.tsx.snap
Labels: 2: Dev Review, Changelog/Not Needed, Docs/Not Needed, CherryPick/Approved, release-note-none

#8802 [MM-22950] Add initial whitespace characters in /code rendering
  actions/command.ts
Labels: 4: Reviews Complete, release-note

#8880 Automated cherry pick of #8873
  components/admin_console/admin_definition.jsx
  components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.jsx.snap
  components/admin_console/team_channel_settings/team/details/__snapshots__/team_details.test.jsx.snap
  components/admin_console/team_channel_settings/team/details/__snapshots__/team_modes.test.jsx.snap
  components/admin_console/team_channel_settings/team/details/index.js
  components/admin_console/team_channel_settings/team/details/team_details.jsx
  components/admin_console/team_channel_settings/team/details/team_modes.jsx
  components/admin_console/team_channel_settings/team/list/__snapshots__/team_list.test.tsx.snap
  components/admin_console/team_channel_settings/team/list/index.ts
  components/admin_console/team_channel_settings/team/list/team_list.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, do-not-merge/release-note-label-needed

#8878 [MM-38630] Don't error if there is no pathName defined on the message
  utils/browser_history.jsx
Labels: CherryPick/Approved, Setup Cloud Test Server, release-note-none, QA Deferred

#8881 Automated cherry pick of #8878
  utils/browser_history.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, do-not-merge/release-note-label-needed

#8868 Cypress/E2E: fix for failed tests
  e2e/cypress/integration/archived_channel/archive_channel_operations_spec.js
  e2e/cypress/integration/archived_channel/archived_leave_channel_spec.js
  e2e/cypress/integration/channel/user_to_channel_admin_member_updates_manage_channel_members_modal_spec.js
  e2e/cypress/integration/channel_sidebar/drag_and_drop_spec.js
  e2e/cypress/integration/integrations/builtin_commands/groupmsg_command_spec.js
  e2e/cypress/integration/integrations/builtin_commands/helper.js
  e2e/cypress/integration/integrations/builtin_commands/invalid_commands_spec.js
  e2e/cypress/integration/integrations/builtin_commands/invite_command_spec.js
  e2e/cypress/integration/integrations/builtin_commands/user_status_commands_spec.js
  e2e/cypress/integration/integrations/builtin_commands/user_status_spec.js
  e2e/cypress/integration/integrations/slash_commands_spec.js
  e2e/cypress/integration/keyboard_shortcuts/ctrl_cmd_k_unreads_spec.js
  e2e/cypress/integration/keyboard_shortcuts/ctrl_cmd_shift_slash/not_open_emoji_picker_spec.js
  e2e/cypress/integration/keyboard_shortcuts/ctrl_cmd_shift_slash/react_to_center_spec.js
  e2e/cypress/integration/markdown/markdown_image_spec.js
  e2e/cypress/integration/markdown/markdown_text_spec.js
  e2e/cypress/integration/menus/status_dropdown_spec.js
  e2e/cypress/integration/messaging/at_mentions_user_spec.js
  e2e/cypress/integration/messaging/autocomplete_shown_each_channel_spec.js
  e2e/cypress/integration/messaging/center_channel_rhs_overlap_spec.js
  e2e/cypress/integration/messaging/channel_and_posts_links_spec.js
  e2e/cypress/integration/messaging/collapse_link_spec.js
  e2e/cypress/integration/messaging/collapsed_message_spec.js
  e2e/cypress/integration/messaging/ctrl_cmd_k_find_gm_by_matching_name_spec.js
  e2e/cypress/integration/messaging/ctrl_cmd_k_open_dm_with_mouse_spec.js
  e2e/cypress/integration/messaging/edit_message_spec.js
  e2e/cypress/integration/notifications/at_mentions_spec.js
  e2e/cypress/support/api/user.d.ts
  e2e/cypress/support/api/user.js
  e2e/cypress/support/ui/global_header.d.ts
Labels: 4: Reviews Complete, release-note-none

#8883 Translations update from Weblate
  i18n/bg.json
  i18n/de.json
  i18n/en_AU.json
  i18n/es.json
  i18n/fr.json
  i18n/hu.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 2: Dev Review, 3: QA Review, release-note-none

#8876 Mm 38364 download apps
  components/next_steps_view/download_section.tsx
  components/next_steps_view/index.ts
  components/next_steps_view/next_steps_view.scss
  components/next_steps_view/next_steps_view.test.tsx
  components/next_steps_view/next_steps_view.tsx
  components/next_steps_view/steps.test.tsx
  components/next_steps_view/steps.ts
  components/next_steps_view/steps/download_apps_step/download_apps_step.tsx
  components/next_steps_view/steps/enable_notifications_step/enable_notifications_step.tsx
  components/next_steps_view/steps/invite_members_step/index.ts
  components/next_steps_view/steps/invite_members_step/invite_members_step.test.tsx
  components/next_steps_view/steps/invite_members_step/invite_members_step.tsx
  components/next_steps_view/steps/setup_preferences_step/setup_preferences_step.tsx
  i18n/en.json
  packages/mattermost-redux/src/constants/config.ts
  packages/mattermost-redux/src/selectors/entities/preferences.ts
  utils/constants.jsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, QA Review Done, release-note

#8463 Last 4 credit card digits as a string
  packages/mattermost-redux/src/types/cloud.ts
Labels: Setup Cloud + CWS Test Server, release-note, QA Deferred

#8890 fixed messageing test cases
  e2e/cypress/integration/messaging/message_reaction_spec.js
  e2e/cypress/integration/messaging/message_spec.js
  e2e/cypress/integration/messaging/post_options_menu_spec.js
  e2e/cypress/integration/messaging/post_pre_header_spec.js
  e2e/cypress/integration/messaging/post_textbox_height_spec.js
  e2e/cypress/integration/messaging/private_channel_open_spec.js
  e2e/cypress/integration/messaging/quick_send_spec.js
  e2e/cypress/integration/messaging/typing_on_middle_spec.js
  e2e/cypress/integration/search/results_post_spec.js
Labels: 4: Reviews Complete, release-note-none

#8844 MM-24370 Remove manual focus change from cancel button
  components/new_channel_modal/__snapshots__/new_channel_modal.test.jsx.snap
  components/new_channel_modal/index.js
  components/new_channel_modal/new_channel_modal.jsx
  components/new_channel_modal/new_channel_modal.test.jsx
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#8897 Automated cherry pick of #8844
  components/new_channel_modal/__snapshots__/new_channel_modal.test.jsx.snap
  components/new_channel_modal/index.js
  components/new_channel_modal/new_channel_modal.jsx
  components/new_channel_modal/new_channel_modal.test.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, do-not-merge/release-note-label-needed

#8898 Automated cherry pick of #8844
  components/new_channel_modal/__snapshots__/new_channel_modal.test.jsx.snap
  components/new_channel_modal/index.js
  components/new_channel_modal/new_channel_modal.jsx
  components/new_channel_modal/new_channel_modal.test.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, do-not-merge/release-note-label-needed

#8867 fix input background
  sass/components/_post.scss
Labels: 2: Dev Review, Setup Cloud Test Server, QA Review Done, release-note-none

#8899 Improve memoization of makeCombineUserActivityPosts
  packages/mattermost-redux/src/utils/post_list.test.js
  packages/mattermost-redux/src/utils/post_list.ts
Labels: 4: Reviews Complete, release-note

#8892 [MM-38468] - Webapp/System Console: Check if help text about customized Support Email is still accurate with the removal of tutorial screen
  components/admin_console/admin_definition.jsx
  e2e/cypress/integration/system_console/ui_and_api/customization_spec.js
  i18n/en.json
Labels: 4: Reviews Complete, release-note-none

#8885 Translations update from Weblate (#8883)
  i18n/bg.json
  i18n/de.json
  i18n/en_AU.json
  i18n/es.json
  i18n/fr.json
  i18n/hu.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 2: Dev Review, 3: QA Review, release-note-none

#8902 Cypress/E2E: Fix tests for v6.0
  e2e/cypress/integration/integrations/poll_spec.js
  e2e/cypress/integration/messaging/tooltips_on_top_nav_channel_icons_posts_spec.js
  e2e/cypress/integration/plugins/demo_plugin/webhook_spec.js
  e2e/cypress/integration/search/clear_input_spec.js
  e2e/cypress/integration/search/cleared_search_term_spec.js
  e2e/cypress/integration/search/results_post_comment_spec.js
  e2e/cypress/integration/search_autocomplete/channels_spec.js
  e2e/cypress/integration/search_autocomplete/renaming_spec.js
  e2e/cypress/integration/search_autocomplete/scroll_spec.js
  e2e/cypress/integration/search_filter/after_spec.js
  e2e/cypress/integration/search_filter/before_spec.js
  e2e/cypress/integration/search_filter/edit_spec.js
  e2e/cypress/integration/search_filter/future_date_spec.js
  e2e/cypress/integration/search_filter/helpers.js
  e2e/cypress/integration/search_filter/input_spec.js
  e2e/cypress/integration/search_filter/invalid_spec.js
  e2e/cypress/integration/search_filter/mixed_spec.js
  e2e/cypress/integration/search_filter/negative_spec.js
  e2e/cypress/integration/search_filter/on_spec.js
  e2e/cypress/integration/signin_authentication/login_logout_smoke_spec.js
  e2e/cypress/integration/signin_authentication/login_spec.js
  e2e/cypress/integration/signin_authentication/mfa_authentication_spec.js
  e2e/cypress/integration/system_console/reporting/site_statistics_spec.js
  e2e/cypress/integration/system_console/site_configuration/customization_spec.js
  e2e/cypress/integration/system_console/user_management_not_cloud_spec.js
  e2e/cypress/integration/team_settings/create_a_team_spec.js
  e2e/cypress/integration/team_settings/teams_spec.js
  e2e/cypress/integration/toast/new_messages_toast_spec.js
  e2e/cypress/integration/toast/permalink_jump_to_spec.js
  e2e/cypress/integration/toast/permalink_post_spec.js
  e2e/cypress/integration/toast/permalink_post_with_new_message_spec.js
  e2e/cypress/integration/toast/toast_spec.js
  e2e/cypress/support/ui/channel_header.d.ts
  e2e/cypress/support/ui/channel_header.js
  e2e/cypress/support/ui/global_header.d.ts
  e2e/cypress/support/ui/global_header.js
  e2e/cypress/support/ui/sidebar_left.d.ts
  e2e/cypress/support/ui/sidebar_left.js
  e2e/cypress/support/ui/sidebar_right.d.ts
  e2e/cypress/support/ui/sidebar_right.js
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#8905 Automated cherry pick of #8902
  e2e/cypress/integration/integrations/poll_spec.js
  e2e/cypress/integration/messaging/tooltips_on_top_nav_channel_icons_posts_spec.js
  e2e/cypress/integration/plugins/demo_plugin/webhook_spec.js
  e2e/cypress/integration/search/clear_input_spec.js
  e2e/cypress/integration/search/cleared_search_term_spec.js
  e2e/cypress/integration/search/results_post_comment_spec.js
  e2e/cypress/integration/search_autocomplete/channels_spec.js
  e2e/cypress/integration/search_autocomplete/renaming_spec.js
  e2e/cypress/integration/search_autocomplete/scroll_spec.js
  e2e/cypress/integration/search_filter/after_spec.js
  e2e/cypress/integration/search_filter/before_spec.js
  e2e/cypress/integration/search_filter/edit_spec.js
  e2e/cypress/integration/search_filter/future_date_spec.js
  e2e/cypress/integration/search_filter/helpers.js
  e2e/cypress/integration/search_filter/input_spec.js
  e2e/cypress/integration/search_filter/invalid_spec.js
  e2e/cypress/integration/search_filter/mixed_spec.js
  e2e/cypress/integration/search_filter/negative_spec.js
  e2e/cypress/integration/search_filter/on_spec.js
  e2e/cypress/integration/signin_authentication/login_logout_smoke_spec.js
  e2e/cypress/integration/signin_authentication/login_spec.js
  e2e/cypress/integration/signin_authentication/mfa_authentication_spec.js
  e2e/cypress/integration/system_console/reporting/site_statistics_spec.js
  e2e/cypress/integration/system_console/site_configuration/customization_spec.js
  e2e/cypress/integration/system_console/user_management_not_cloud_spec.js
  e2e/cypress/integration/team_settings/create_a_team_spec.js
  e2e/cypress/integration/team_settings/teams_spec.js
  e2e/cypress/integration/toast/new_messages_toast_spec.js
  e2e/cypress/integration/toast/permalink_jump_to_spec.js
  e2e/cypress/integration/toast/permalink_post_spec.js
  e2e/cypress/integration/toast/permalink_post_with_new_message_spec.js
  e2e/cypress/integration/toast/toast_spec.js
  e2e/cypress/support/ui/channel_header.d.ts
  e2e/cypress/support/ui/channel_header.js
  e2e/cypress/support/ui/global_header.d.ts
  e2e/cypress/support/ui/global_header.js
  e2e/cypress/support/ui/sidebar_left.d.ts
  e2e/cypress/support/ui/sidebar_left.js
  e2e/cypress/support/ui/sidebar_right.d.ts
  e2e/cypress/support/ui/sidebar_right.js
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#8907 Automated cherry pick of #8867
  sass/components/_post.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#8908 Automated cherry pick of #8892
  components/admin_console/admin_definition.jsx
  e2e/cypress/integration/system_console/ui_and_api/customization_spec.js
  i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#8911 MM-38579 cherry pick to release-6.0
  components/create_comment/__snapshots__/create_comment.test.jsx.snap
  components/create_comment/create_comment.test.jsx
  components/create_comment/create_comment.tsx
  components/create_comment/index.ts
  components/create_post/__snapshots__/create_post.test.jsx.snap
  components/create_post/create_post.test.jsx
  components/create_post/create_post.tsx
  components/create_post/index.ts
Labels: 2: Dev Review, release-note-none

#8910 MM-38579 cherry pick to cloud
  components/create_comment/__snapshots__/create_comment.test.jsx.snap
  components/create_comment/create_comment.test.jsx
  components/create_comment/create_comment.tsx
  components/create_comment/index.ts
  components/create_post/__snapshots__/create_post.test.jsx.snap
  components/create_post/create_post.test.jsx
  components/create_post/create_post.tsx
  components/create_post/index.ts
Labels: 2: Dev Review, release-note-none

#8912 WIP do not merge
  components/actions_menu/actions_menu.tsx
  components/actions_menu/index.ts
  components/post_view/post_info/index.ts
  components/post_view/post_info/post_info.tsx
  packages/mattermost-redux/src/actions/preferences.ts
  packages/mattermost-redux/src/constants/preferences.ts
  selectors/actions_menu.ts
Labels: do-not-merge/release-note-label-needed

#8918 [MM-38414] fixes Unable to set custom status with Don't clear option
  components/custom_status/custom_status_modal.tsx
Labels: Setup Cloud Test Server, release-note, QA Deferred

#8914 fixed messaging test case
  e2e/cypress/integration/auth_sso/authentication_4_spec.js
  e2e/cypress/integration/messaging/message_edit_post_clear_text_spec.js
  e2e/cypress/integration/messaging/message_edit_post_with_attachment_spec.js
  e2e/cypress/integration/messaging/message_emoji_jumbo_spec.js
  e2e/cypress/integration/messaging/message_ephemeral_spec.js
  e2e/cypress/integration/messaging/message_in_another_language_spec.js
  e2e/cypress/integration/messaging/message_parse_spec.js
  e2e/cypress/integration/messaging/message_pinning_unpinning_spec.js
  e2e/cypress/integration/messaging/message_reply_input_box_expand_spec.js
  e2e/cypress/integration/messaging/message_reply_scrollable_spec.js
  e2e/cypress/integration/messaging/message_reply_too_long_spec.js
  e2e/cypress/integration/messaging/message_shortlinking_spec.js
  e2e/cypress/integration/messaging/message_with_gif_spec.js
  e2e/cypress/integration/messaging/mobile_message_deletion_spec.js
  e2e/cypress/integration/messaging/mobile_profile_popover_spec.js
  e2e/cypress/integration/messaging/strikethrough_spec.js
  e2e/cypress/integration/messaging/typing_should_show_up_when_editing_spec.js
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#8919 Automated cherry pick of #8914
  e2e/cypress/integration/auth_sso/authentication_4_spec.js
  e2e/cypress/integration/messaging/message_edit_post_clear_text_spec.js
  e2e/cypress/integration/messaging/message_edit_post_with_attachment_spec.js
  e2e/cypress/integration/messaging/message_emoji_jumbo_spec.js
  e2e/cypress/integration/messaging/message_ephemeral_spec.js
  e2e/cypress/integration/messaging/message_in_another_language_spec.js
  e2e/cypress/integration/messaging/message_parse_spec.js
  e2e/cypress/integration/messaging/message_pinning_unpinning_spec.js
  e2e/cypress/integration/messaging/message_reply_input_box_expand_spec.js
  e2e/cypress/integration/messaging/message_reply_scrollable_spec.js
  e2e/cypress/integration/messaging/message_reply_too_long_spec.js
  e2e/cypress/integration/messaging/message_shortlinking_spec.js
  e2e/cypress/integration/messaging/message_with_gif_spec.js
  e2e/cypress/integration/messaging/mobile_message_deletion_spec.js
  e2e/cypress/integration/messaging/mobile_profile_popover_spec.js
  e2e/cypress/integration/messaging/strikethrough_spec.js
  e2e/cypress/integration/messaging/typing_should_show_up_when_editing_spec.js
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#8906 Update NOTICE.txt
  NOTICE.txt
Labels: 4: Reviews Complete, Changelog/Done, Docs/Not Needed, CherryPick/Approved, AutoMerge, release-note

#8920 Automated cherry pick of #8906
  NOTICE.txt
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#8839 [MM-38263] - Add channel category menu to channel header
  components/category_menu_items/category_menu_items.tsx
  components/category_menu_items/index.ts
  components/channel_header_dropdown/__snapshots__/channel_header_dropdown.test.jsx.snap
  components/channel_header_dropdown/channel_header_dropdown_items.js
  components/sidebar/sidebar_category/sidebar_category_menu/__snapshots__/sidebar_category_menu.test.tsx.snap
  components/sidebar/sidebar_category/sidebar_category_sorting_menu/sidebar_category_sorting_menu.tsx
  components/sidebar/sidebar_channel/sidebar_channel_menu/__snapshots__/sidebar_channel_menu.test.tsx.snap
  components/sidebar/sidebar_channel/sidebar_channel_menu/sidebar_channel_menu.tsx
  components/widgets/menu/menu.scss
  components/widgets/menu/menu_items/submenu_item.tsx
  components/widgets/menu/menu_modals/submenu_modal/__snapshots__/submenu_modal.test.tsx.snap
  i18n/en.json
Labels: 4: Reviews Complete, release-note

#8923 Automated cherry pick of #8918
  components/custom_status/custom_status_modal.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#8922 Automated cherry pick of #8918
  components/custom_status/custom_status_modal.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#8821 MM-37971 Refactor MoreDirectChannels into smaller components
  components/more_direct_channels/__snapshots__/more_direct_channels.test.jsx.snap
  components/more_direct_channels/index.ts
  components/more_direct_channels/list/index.test.js
  components/more_direct_channels/list/index.ts
  components/more_direct_channels/list/list.tsx
  components/more_direct_channels/list_item/__snapshots__/list_item.test.jsx.snap
  components/more_direct_channels/list_item/index.ts
  components/more_direct_channels/list_item/list_item.test.jsx
  components/more_direct_channels/list_item/list_item.tsx
  components/more_direct_channels/list_item/user_details/index.ts
  components/more_direct_channels/list_item/user_details/user_details.tsx
  components/more_direct_channels/more_direct_channels.test.jsx
  components/more_direct_channels/more_direct_channels.tsx
  components/more_direct_channels/types.ts
  packages/mattermost-redux/src/selectors/entities/users.ts
  packages/mattermost-redux/src/utils/channel_utils.ts
Labels: 4: Reviews Complete, release-note-none

#8916 Cypress/E2E: Fix tests for v6.0
  e2e/cypress/integration/accessibility/accessibility_account_settings_spec.js
  e2e/cypress/integration/account_settings/general/nickname_spec.js
  e2e/cypress/integration/enterprise/cloud/onboarding/cloud_sysadmin_onboarding_spec.js
  e2e/cypress/integration/enterprise/ldap_group/invite_bot_spec.js
  e2e/cypress/integration/integrations/incoming_webhook/delete_incoming_webhook_spec.js
  e2e/cypress/integration/integrations/incoming_webhook/incoming_webhook_is_image_only_spec.js
  e2e/cypress/integration/integrations/incoming_webhook/setup_incoming_webhook_spec.js
  e2e/cypress/integration/integrations/integrations_spec.js
  e2e/cypress/integration/integrations/outgoing_webhook/disable_override_username_profile_spec.js
  e2e/cypress/integration/notifications/deselect_username_mention_trigger_spec.js
  e2e/cypress/integration/notifications/notification_preferences_do_not_save_spec.js
  e2e/cypress/integration/onboarding/invalidate_pending_email_invitations_spec.js
  e2e/cypress/integration/signin_authentication/desktop_session_expire_spec.js
  e2e/cypress/integration/system_console/lock_teammate_name_display_spec.js
  e2e/cypress/integration/system_console/sidebar_link_navigation_not_cloud_spec.js
  e2e/cypress/integration/system_console/sidebar_link_navigation_spec.js
  e2e/cypress/integration/system_console/site_configuration/link_customization_spec.js
  e2e/cypress/integration/team_settings/teams_spec.js
  e2e/cypress/support/ui/common.d.ts
  e2e/cypress/support/ui/extend_testing_library.d.ts
  e2e/cypress/support/ui/menu.d.ts
  e2e/cypress/support/ui/menu.js
  e2e/cypress/support/ui/post.d.ts
  e2e/cypress/support/ui/post.js
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#8925 Automated cherry pick of #8916
  e2e/cypress/integration/accessibility/accessibility_account_settings_spec.js
  e2e/cypress/integration/account_settings/general/nickname_spec.js
  e2e/cypress/integration/enterprise/cloud/onboarding/cloud_sysadmin_onboarding_spec.js
  e2e/cypress/integration/enterprise/ldap_group/invite_bot_spec.js
  e2e/cypress/integration/integrations/incoming_webhook/delete_incoming_webhook_spec.js
  e2e/cypress/integration/integrations/incoming_webhook/incoming_webhook_is_image_only_spec.js
  e2e/cypress/integration/integrations/incoming_webhook/setup_incoming_webhook_spec.js
  e2e/cypress/integration/integrations/integrations_spec.js
  e2e/cypress/integration/integrations/outgoing_webhook/disable_override_username_profile_spec.js
  e2e/cypress/integration/notifications/deselect_username_mention_trigger_spec.js
  e2e/cypress/integration/notifications/notification_preferences_do_not_save_spec.js
  e2e/cypress/integration/onboarding/invalidate_pending_email_invitations_spec.js
  e2e/cypress/integration/signin_authentication/desktop_session_expire_spec.js
  e2e/cypress/integration/system_console/lock_teammate_name_display_spec.js
  e2e/cypress/integration/system_console/sidebar_link_navigation_not_cloud_spec.js
  e2e/cypress/integration/system_console/sidebar_link_navigation_spec.js
  e2e/cypress/integration/system_console/site_configuration/link_customization_spec.js
  e2e/cypress/integration/team_settings/teams_spec.js
  e2e/cypress/support/ui/common.d.ts
  e2e/cypress/support/ui/extend_testing_library.d.ts
  e2e/cypress/support/ui/menu.d.ts
  e2e/cypress/support/ui/menu.js
  e2e/cypress/support/ui/post.d.ts
  e2e/cypress/support/ui/post.js
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#8870 Refactor isMobile to use redux and change name to isMobileView for better clarity (alternative)
  actions/views/browser.ts
  components/global/hooks.tsx
  components/root/index.js
  components/root/root.jsx
  components/root/root.test.jsx
  components/sidebar/index.ts
  components/sidebar/sidebar.test.tsx
  components/sidebar/sidebar.tsx
  reducers/views/browser.js
  reducers/views/browser.test.js
  reducers/views/browser.ts
  selectors/views/browser.ts
  types/store/views.ts
  utils/constants.jsx
Labels: 4: Reviews Complete, release-note-none

#8930 Cypress/e2e/fixed cypress test cases
  e2e/cypress/integration/bot_accounts/in_teams_and_channels_spec.js
  e2e/cypress/integration/enterprise/ldap_group/group_mentions_spec.js
  e2e/cypress/integration/keyboard_shortcuts/ctrl_cmd_shift_slash/react_to_rhs_spec.js
  e2e/cypress/support/ui/team.js
Labels: 4: Reviews Complete, CherryPick/Approved, AutoMerge, release-note-none

#8931 Automated cherry pick of #8930
  e2e/cypress/integration/bot_accounts/in_teams_and_channels_spec.js
  e2e/cypress/integration/enterprise/ldap_group/group_mentions_spec.js
  e2e/cypress/integration/keyboard_shortcuts/ctrl_cmd_shift_slash/react_to_rhs_spec.js
  e2e/cypress/support/ui/team.js
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#8896 [MM-22800]_add keyboard shortcuts to tooltips
  components/__snapshots__/shortcuts_modal.test.jsx.snap
  components/channel_header/components/__snapshots__/header_icon_wrapper.test.tsx.snap
  components/channel_header/components/header_icon_wrapper.tsx
  components/channel_layout/channel_controller.jsx
  components/file_upload/__snapshots__/file_upload.test.jsx.snap
  components/file_upload/file_upload.jsx
  components/global/at_mentions_button/at_mentions_button.tsx
  components/global/history_buttons/history_buttons.tsx
  components/keyboard_shortcuts/keyboard_shortcuts_modal/__snapshots__/keyboard_shortcuts_modal.test.tsx.snap
  components/keyboard_shortcuts/keyboard_shortcuts_modal/keyboard_shortcuts_modal.scss
  components/keyboard_shortcuts/keyboard_shortcuts_modal/keyboard_shortcuts_modal.test.tsx
  components/keyboard_shortcuts/keyboard_shortcuts_modal/keyboard_shortcuts_modal.tsx
  components/keyboard_shortcuts/keyboard_shortcuts_sequence/__snapshots__/keyboard_shortcuts_sequence.test.tsx.snap
  components/keyboard_shortcuts/keyboard_shortcuts_sequence/index.ts
  components/keyboard_shortcuts/keyboard_shortcuts_sequence/keyboard_shortcuts.ts
  components/keyboard_shortcuts/keyboard_shortcuts_sequence/keyboard_shortcuts_sequence.scss
  components/keyboard_shortcuts/keyboard_shortcuts_sequence/keyboard_shortcuts_sequence.test.tsx
  components/keyboard_shortcuts/keyboard_shortcuts_sequence/keyboard_shortcuts_sequence.tsx
  components/search_shortcut/search_shortcut.tsx
  components/shortcut_key/index.ts
  components/shortcut_key/shortcut_key.scss
  components/shortcut_key/shortcut_key.test.tsx
  components/shortcut_key/shortcut_key.tsx
  components/shortcuts_modal.jsx
  components/shortcuts_modal.test.jsx
  components/sidebar/channel_navigator/channel_navigator.tsx
  components/sidebar/sidebar_category/__snapshots__/sidebar_category.test.tsx.snap
  components/sidebar/sidebar_category/sidebar_category.tsx
  components/team_sidebar/components/team_button.tsx
  i18n/en.json
  sass/components/_tooltip.scss
  sass/routes/_module.scss
Labels: 4: Reviews Complete, release-note

#8903 always show playbooks card
  components/next_steps_view/__snapshots__/next_steps_view.test.tsx.snap
  components/next_steps_view/next_steps_tips.tsx
  components/next_steps_view/next_steps_view.tsx
  i18n/en.json
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, QA Review Done, release-note

#8904 fix notifications translations
  components/create_post/prewritten_chips.tsx
  components/next_steps_view/next_steps_view.test.tsx
  components/next_steps_view/next_steps_view.tsx
  components/next_steps_view/steps.ts
  i18n/en.json
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, QA Review Done, release-note

#8935 Automated cherry pick of #8903
  components/next_steps_view/__snapshots__/next_steps_view.test.tsx.snap
  components/next_steps_view/next_steps_tips.tsx
  components/next_steps_view/next_steps_view.tsx
  i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#8933 Cypress/E2E: fix tests for v6
  e2e/cypress/integration/accessibility/accessibility_dropdowns_spec.js
  e2e/cypress/integration/archived_channel/archived_channel_spec.js
  e2e/cypress/integration/archived_channel/archived_leave_channel_spec.js
  e2e/cypress/integration/channel_sidebar/dm_gm_behaviour_spec.js
  e2e/cypress/integration/collapsed_reply_threads/following_spec.js
  e2e/cypress/integration/collapsed_reply_threads/replies_spec.js
  e2e/cypress/integration/enterprise/cloud/onboarding/cloud_sysadmin_onboarding_spec.js
  e2e/cypress/integration/integrations/builtin_commands/invite_command_spec.js
  e2e/cypress/integration/messaging/center_channel_rhs_overlap_spec.js
  e2e/cypress/integration/messaging/direct_message_spec.js
  e2e/cypress/integration/messaging/group_message_spec.js
  e2e/cypress/integration/modals/quick_switcher_spec.js
  e2e/cypress/integration/multi_team_and_dm/close_current_dm_redirects_spec.js
  e2e/cypress/integration/multi_team_and_dm/gm_add_user_spec.js
  e2e/cypress/integration/multi_team_and_dm/gm_header_spec.js
  e2e/cypress/integration/notifications/channel_links_show_as_links_spec.js
  e2e/cypress/integration/notifications/desktop_notifications_2_spec.js
  e2e/cypress/integration/notifications/ignore_channel_mentions_spec.js
  e2e/cypress/integration/notifications/mention_email_notification_spec.js
  e2e/cypress/integration/notifications/message_posted_while_scrolled_up_spec.js
  e2e/cypress/integration/notifications/own_user_posts_reply_while_scrolled_up_spec.js
  e2e/cypress/integration/notifications/reply_notifications_spec.js
  e2e/cypress/integration/notifications/users_with_same_firstname_channel_mentions_spec.js
  e2e/cypress/integration/onboarding/tutorial_navigation_and_links_spec.js
  e2e/cypress/integration/scroll/default_images_collapsed_spec.js
  e2e/cypress/integration/scroll/editing_scroll_spec.js
  e2e/cypress/support/ui/channel_header.d.ts
  e2e/cypress/support/ui/channel_header.js
  e2e/cypress/support/ui/menu.d.ts
  e2e/cypress/support/ui/menu.js
  e2e/cypress/support/ui/post.d.ts
  e2e/cypress/support/ui/post.js
  e2e/cypress/support/ui/sidebar_left.d.ts
  e2e/cypress/support/ui/sidebar_left.js
  e2e/cypress/utils/email.js
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#8937 Automated cherry pick of #8903
  components/next_steps_view/__snapshots__/next_steps_view.test.tsx.snap
  components/next_steps_view/next_steps_tips.tsx
  components/next_steps_view/next_steps_view.tsx
  i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#8439 Get options for post options based on the post channel
  actions/apps.ts
  components/dot_menu/dot_menu.test.tsx
  components/dot_menu/dot_menu.tsx
  components/dot_menu/dot_menu_empty.test.tsx
  components/dot_menu/dot_menu_mobile.test.tsx
  components/dot_menu/index.ts
  packages/mattermost-redux/src/selectors/entities/apps.ts
Labels: 4: Reviews Complete, Docs/Done, release-note

#8793 MM-36697: global threads infinite scrolling
  components/threading/global_threads/global_threads.tsx
  components/threading/global_threads/thread_list/__snapshots__/thread_list.test.tsx.snap
  components/threading/global_threads/thread_list/thread_list.test.tsx
  components/threading/global_threads/thread_list/thread_list.tsx
  components/threading/global_threads/thread_list/virtualized_thread_list.tsx
  package-lock.json
  package.json
  packages/mattermost-redux/src/action_types/threads.ts
  packages/mattermost-redux/src/actions/threads.ts
  packages/mattermost-redux/src/reducers/entities/threads.test.js
  packages/mattermost-redux/src/reducers/entities/threads.ts
  packages/mattermost-redux/src/reducers/entities/threadsInTeam/threadsInTeam.ts
  packages/mattermost-redux/src/selectors/entities/threads.test.js
  packages/mattermost-redux/src/selectors/entities/threads.ts
  packages/mattermost-redux/src/store/initial_state.ts
  packages/mattermost-redux/src/types/threads.ts
  utils/constants.jsx
Labels: 4: Reviews Complete, release-note-none

#8928 MM-38678 - fix theme colour bug
  sass/components/_modal.scss
Labels: 4: Reviews Complete, release-note-none

#8921 [MM-38469] - fixed several console errors regarding propTypes
  components/widgets/menu/menu_items/__snapshots__/menu_item_toggle_modal_redux.test.tsx.snap
  components/widgets/menu/menu_items/menu_item.test.tsx
  components/widgets/menu/menu_items/menu_item.tsx
  components/widgets/menu/menu_items/menu_item_toggle_modal_redux.test.tsx
  components/widgets/menu/menu_items/menu_item_toggle_modal_redux.tsx
  selectors/views/modals.js
Labels: 4: Reviews Complete, release-note-none, kind/bug

#8917 [MM-38578] - fix for rhs bottom spacing issue
  sass/components/_post-right.scss
Labels: 4: Reviews Complete, release-note-none, kind/bug

#8828 MM-37951: follow thread on reply
  actions/websocket_actions.jsx
Labels: 4: Reviews Complete, release-note-none

#8851 [MM-36551] - improvements to post edit indicator
  components/markdown/__snapshots__/markdown.test.tsx.snap
  components/markdown/markdown.tsx
  components/post_markdown/__snapshots__/post_markdown.test.tsx.snap
  components/post_markdown/post_markdown.tsx
  components/post_view/post_edited_indicator/post_edited_indicator.tsx
  components/post_view/post_message_view/__snapshots__/post_message_view.test.tsx.snap
  components/post_view/post_message_view/post_message_view.test.tsx
  components/post_view/post_message_view/post_message_view.tsx
  i18n/en.json
  sass/components/_post.scss
  utils/datetime.ts
  utils/message_html_to_component.jsx
  utils/text_formatting.tsx
Labels: 4: Reviews Complete, QA Review Done, Setup Cloud + CWS Test Server, release-note

#8826 [MM-38442] - add product switcher menu unit tests
  components/global/product_switcher_menu/__snapshots__/product_switcher_menu.test.tsx.snap
  components/global/product_switcher_menu/product_switcher_menu.test.tsx
  components/global/product_switcher_menu/product_switcher_menu.tsx
Labels: release-note-none

#8806 [MM-38283] - fixed `SUGGESTION.UNDEFINED` in quick-switch modal
  components/quick_switch_modal/quick_switch_modal.tsx
  components/suggestion/suggestion_list.jsx
  components/suggestion/switch_channel_provider.jsx
  i18n/en.json
  package-lock.json
  utils/constants.jsx
Labels: 4: Reviews Complete, CherryPick/Approved, AutoMerge, release-note-none, kind/bug

#8945 Automated cherry pick of #8928
  sass/components/_modal.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#8946 Automated cherry pick of #8928
  sass/components/_modal.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#8947 Automated cherry pick of #8921
  components/widgets/menu/menu_items/__snapshots__/menu_item_toggle_modal_redux.test.tsx.snap
  components/widgets/menu/menu_items/menu_item.test.tsx
  components/widgets/menu/menu_items/menu_item.tsx
  components/widgets/menu/menu_items/menu_item_toggle_modal_redux.test.tsx
  components/widgets/menu/menu_items/menu_item_toggle_modal_redux.tsx
  selectors/views/modals.js
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#8948 Automated cherry pick of #8921
  components/widgets/menu/menu_items/__snapshots__/menu_item_toggle_modal_redux.test.tsx.snap
  components/widgets/menu/menu_items/menu_item.test.tsx
  components/widgets/menu/menu_items/menu_item.tsx
  components/widgets/menu/menu_items/menu_item_toggle_modal_redux.test.tsx
  components/widgets/menu/menu_items/menu_item_toggle_modal_redux.tsx
  selectors/views/modals.js
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#8949 Automated cherry pick of #8806
  components/quick_switch_modal/quick_switch_modal.tsx
  components/suggestion/suggestion_list.jsx
  components/suggestion/switch_channel_provider.jsx
  i18n/en.json
  package-lock.json
  utils/constants.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#8950 Automated cherry pick of #8917
  sass/components/_post-right.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#8952 Automated cherry pick of #8828
  actions/websocket_actions.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#8953 Automated cherry pick of #8828
  actions/websocket_actions.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#8954 Automated cherry pick of #8806
  components/quick_switch_modal/quick_switch_modal.tsx
  components/suggestion/suggestion_list.jsx
  components/suggestion/switch_channel_provider.jsx
  i18n/en.json
  package-lock.json
  utils/constants.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#8951 Automated cherry pick of #8917
  sass/components/_post-right.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#8939 Highlight invite_members_button until user interacts with it
  components/sidebar/__snapshots__/invite_members_button.test.tsx.snap
  components/sidebar/invite_members_button.test.tsx
  components/sidebar/invite_members_button.tsx
  components/sidebar/sidebar_category/__snapshots__/sidebar_category.test.tsx.snap
  components/sidebar/sidebar_category/index.ts
  components/sidebar/sidebar_category/sidebar_category.test.tsx
  components/sidebar/sidebar_category/sidebar_category.tsx
  sass/layout/_sidebar-left.scss
  utils/constants.jsx
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, QA Review Done, release-note-none

#8932 MM-38446 - theme color fix for tips next steps page plugins image
  components/next_steps_view/images/documents.svg.tsx
  components/next_steps_view/images/incidents.svg.tsx
  components/next_steps_view/images/plugins.svg.tsx
Labels: Setup Cloud Test Server, release-note-none

#8958 Automated cherry pick of #8932
  components/next_steps_view/images/documents.svg.tsx
  components/next_steps_view/images/incidents.svg.tsx
  components/next_steps_view/images/plugins.svg.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#8959 Automated cherry pick of #8932
  components/next_steps_view/images/documents.svg.tsx
  components/next_steps_view/images/incidents.svg.tsx
  components/next_steps_view/images/plugins.svg.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#8927 MM-38311 - invite people button to bottom of menu
  components/sidebar/add_channel_dropdown.tsx
Labels: 2: Dev Review, CherryPick/Approved, Setup Cloud Test Server, QA Review Done, release-note-none
