Repository mattermost/mattermost-webapp, pull requests merged in 2021-05, with the labels that each got.

#7897 [MM-34338] Migrate 'components/post_profile_picture' and associated tests to TypeScript
  components/post_profile_picture/__snapshots__/post_profile_picture.test.tsx.snap
  components/post_profile_picture/index.ts
  components/post_profile_picture/post_profile_picture.test.tsx
  components/post_profile_picture/post_profile_picture.tsx
Labels: 4: Reviews Complete, release-note

#7982 [MM-35138] Avoid autofill on apps forms
  components/apps_form/apps_form.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#8045 Automated cherry pick of #7982
  components/apps_form/apps_form.tsx
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8046 Automated cherry pick of #7982
  components/apps_form/apps_form.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#7774 MM-18818 Prompt admins to set the Support Email
  e2e/cypress/support/api/cloud_default_config.json
  e2e/cypress/support/api/on_prem_default_config.json
Labels: 4: Reviews Complete, release-note

#8048 Translations update from Weblate
  i18n/bg.json
  i18n/fr.json
  i18n/hu.json
  i18n/ko.json
  i18n/nl.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
Labels: 2: Dev Review, 3: QA Review, release-note-none

#7922 Apps commands invalidate form cache
  components/suggestion/command_provider/app_command_parser/app_command_parser.ts
  components/suggestion/command_provider/command_provider.test.tsx
  components/suggestion/command_provider/command_provider.tsx
  components/suggestion/suggestion_box.test.jsx
  components/textbox/textbox.tsx
Labels: 4: Reviews Complete, AutoMerge, CherryPick/Approved, release-note

#8049 Automated cherry pick of #7922
  components/suggestion/command_provider/app_command_parser/app_command_parser.ts
  components/suggestion/command_provider/command_provider.test.tsx
  components/suggestion/command_provider/command_provider.tsx
  components/suggestion/suggestion_box.test.jsx
  components/textbox/textbox.tsx
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8050 Automated cherry pick of #7922
  components/suggestion/command_provider/app_command_parser/app_command_parser.ts
  components/suggestion/command_provider/command_provider.test.tsx
  components/suggestion/command_provider/command_provider.tsx
  components/suggestion/suggestion_box.test.jsx
  components/textbox/textbox.tsx
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8008 [MM-35062] Increase specificity of GenericModal CSS to override existing styles
  components/generic_modal.scss
Labels: 4: Reviews Complete, release-note-none

#8001 MM-33540 Remove sticky headings from sidebar to fix nesting errors
  components/sidebar/sidebar_category_header.tsx
  components/sidebar/unread_channel_indicator/__snapshots__/unread_channel_indicator.test.tsx.snap
  components/sidebar/unread_channel_indicator/unread_channel_indicator.scss
  components/sidebar/unread_channel_indicator/unread_channel_indicator.tsx
  e2e/cypress/integration/channel_sidebar/category_sorting_spec.js
  sass/layout/_sidebar-left.scss
Labels: 4: Reviews Complete, release-note

#8019 MM-22678 Update Edit Channel Header modal error text
  components/channel_header_dropdown/__snapshots__/channel_header_dropdown.test.jsx.snap
  components/edit_channel_header_modal/__snapshots__/edit_channel_header_modal.test.jsx.snap
  components/edit_channel_header_modal/edit_channel_header_modal.jsx
  components/edit_channel_header_modal/edit_channel_header_modal.test.jsx
  components/edit_channel_purpose_modal/__snapshots__/edit_channel_purpose_modal.test.jsx.snap
  components/edit_channel_purpose_modal/edit_channel_purpose_modal.jsx
  components/edit_channel_purpose_modal/edit_channel_purpose_modal.test.jsx
  i18n/en.json
  tests/helpers/line_break_helpers.js
Labels: 4: Reviews Complete, release-note

#8060 [MM-35445] Fix Spelling Mistake for Custom Terms of Service
  packages/mattermost-redux/src/constants/permissions.ts
Labels: 4: Reviews Complete, QA Review Done, release-note

#7968 [MM-30815] add link to Plugins Marketplace
  components/main_menu/main_menu.jsx
  components/main_menu/main_menu.test.jsx
  plugins/test/__snapshots__/main_menu_action.test.jsx.snap
Labels: 3: QA Review, release-note-none

#8062 Automated cherry pick of #8060
  packages/mattermost-redux/src/constants/permissions.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8061 Automated cherry pick of #8060
  packages/mattermost-redux/src/constants/permissions.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8026 [MM-34340] Migrated RhsCardHeader component to TypeScript
  components/rhs_card_header/index.tsx
  components/rhs_card_header/rhs_card_header.tsx
Labels: 4: Reviews Complete, release-note

#8058 Adding class to indicate if the menu is open on the menu wrapper
  components/widgets/menu/menu_wrapper.test.tsx
  components/widgets/menu/menu_wrapper.tsx
Labels: 4: Reviews Complete

#8009 [MM-35184] Update apps install command for Marketplace
  actions/marketplace.ts
Labels: 4: Reviews Complete, Do Not Merge, release-note-none

#8066 Automated cherry pick of #8009
  actions/marketplace.ts
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8067 Automated cherry pick of #8009
  actions/marketplace.ts
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8069 Revert "Automated cherry pick of #8009"
  actions/marketplace.ts
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#8072 Cypress/E2E: Fixed accessibility test cases
  e2e/cypress/integration/accessibility/accessibility_buttons_spec.js
  e2e/cypress/integration/accessibility/accessibility_keyboard_usability_spec.js
Labels: 4: Reviews Complete, release-note-none

#8073 Cyperss/E2E:fixed emoji preview and keyboard accessibility
  e2e/cypress/integration/accessibility/accessibility_nav_diff_regions_spec.js
  e2e/cypress/integration/accessibility/accessibility_post_spec.js
Labels: 4: Reviews Complete, release-note-none

#8064 MM-34018 Cypress/E2E: Fix image link and previews
  e2e/cypress/integration/files_and_attachments/image_link_preview_new_window_spec.js
  e2e/cypress/integration/files_and_attachments/image_link_preview_spec.js
  e2e/cypress/integration/files_and_attachments/upload_files_not_cloud_spec.js
  e2e/cypress/integration/files_and_attachments/upload_files_spec.js
Labels: 4: Reviews Complete, release-note-none

#8065 Cypress/E2E: Improve excluding test files
  e2e/utils/file.js
Labels: 4: Reviews Complete, release-note-none

#8063 Cypress/E2E: Fix flaky prod tests
  e2e/cypress/integration/enterprise/group_mentions/group_mentions_permissions_spec.js
  e2e/cypress/integration/enterprise/group_mentions/group_mentions_posts_spec.js
  e2e/cypress/integration/enterprise/group_mentions/group_mentions_system_messages_spec.js
  e2e/cypress/integration/enterprise/group_mentions/helpers.js
  e2e/cypress/integration/integrations/outgoing_webhook/regenerate_token_spec.js
  e2e/cypress/integration/messaging/message_draft_then_switch_channel_spec.js
  e2e/cypress/support/ui/system.js
Labels: 4: Reviews Complete, release-note-none

#7037 [MM-8497] Ability to set Do Not Disturb for a specified period of time
  components/dnd_custom_time_picker_modal/dnd_custom_time_picker_modal.scss
  components/dnd_custom_time_picker_modal/dnd_custom_time_picker_modal.tsx
  components/dnd_custom_time_picker_modal/index.ts
  components/generic_modal.scss
  components/sidebar/sidebar_category/sidebar_category_menu/__snapshots__/sidebar_category_menu.test.tsx.snap
  components/sidebar/sidebar_channel/sidebar_channel_menu/__snapshots__/sidebar_channel_menu.test.tsx.snap
  components/status_dropdown/__snapshots__/status_dropdown.test.tsx.snap
  components/status_dropdown/index.jsx
  components/status_dropdown/status_dropdown.jsx
  components/status_dropdown/status_dropdown.scss
  components/widgets/menu/menu.scss
  components/widgets/menu/menu_header.scss
  components/widgets/menu/menu_items/menu_item.scss
  components/widgets/menu/menu_items/submenu_item.tsx
  components/widgets/menu/menu_modals/submenu_modal/__snapshots__/submenu_modal.test.tsx.snap
  e2e/cypress/integration/status/status_dnd_1_spec.js
  i18n/en.json
  package-lock.json
  packages/mattermost-redux/src/types/users.ts
  sass/components/_day-picker.scss
  sass/components/_dnd-pickers-dropdown-menu.scss
  sass/components/_react-day-picker.scss
  sass/layout/_headers.scss
  sass/utils/_modifiers.scss
  utils/constants.jsx
  utils/datetime.ts
  utils/timezone.jsx
  utils/utils.jsx
Labels: 4: Reviews Complete, Setup Cloud Test Server

#7995 [MM-34812] Add feature discoveries
  components/admin_console/admin_definition.jsx
  components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.jsx.snap
  components/admin_console/feature_discovery/__snapshots__/feature_discovery.test.tsx.snap
  components/admin_console/feature_discovery/feature_discovery.test.tsx
  components/admin_console/feature_discovery/feature_discovery.tsx
  components/admin_console/feature_discovery/features/announcement_banner.tsx
  components/admin_console/feature_discovery/features/channels.tsx
  components/admin_console/feature_discovery/features/compliance_export.tsx
  components/admin_console/feature_discovery/features/custom_terms_of_service.tsx
  components/admin_console/feature_discovery/features/data_retention.tsx
  components/admin_console/feature_discovery/features/groups.tsx
  components/admin_console/feature_discovery/features/guest_access.tsx
  components/admin_console/feature_discovery/features/images/announcement_banner_svg.tsx
  components/admin_console/feature_discovery/features/images/channels_svg.tsx
  components/admin_console/feature_discovery/features/images/compliance_export_svg.tsx
  components/admin_console/feature_discovery/features/images/custom_terms_of_service_svg.tsx
  components/admin_console/feature_discovery/features/images/data_retention_svg.tsx
  components/admin_console/feature_discovery/features/images/groups_svg.tsx
  components/admin_console/feature_discovery/features/images/guest_access_svg.tsx
  components/admin_console/feature_discovery/features/images/ldap_svg.tsx
  components/admin_console/feature_discovery/features/images/permissions_svg.tsx
  components/admin_console/feature_discovery/features/images/saml_svg.tsx
  components/admin_console/feature_discovery/features/images/system_roles_svg.tsx
  components/admin_console/feature_discovery/features/index.ts
  components/admin_console/feature_discovery/features/ldap.tsx
  components/admin_console/feature_discovery/features/openid.tsx
  components/admin_console/feature_discovery/features/permissions.tsx
  components/admin_console/feature_discovery/features/saml.tsx
  components/admin_console/feature_discovery/features/system_roles.tsx
  e2e/cypress/integration/system_console/feature_discovery_spec.js
  i18n/en.json
  images/feature-discovery/ldap.png
  images/feature-discovery/saml.png
Labels: 3: QA Review, Setup Cloud Test Server, release-note

#7750 MM-34128: Allow clearing custom status with only the emoji and no text
  components/custom_status/custom_status_modal.tsx
  components/quick_input/quick_input.jsx
Labels: 4: Reviews Complete, release-note

#8079 Cypress/e2e:fixed custom status test case
  e2e/cypress/integration/custom_status/custom_status_3_spec.js
Labels: release-note

#8089 Translations update from Weblate
  i18n/bg.json
  i18n/de.json
  i18n/es.json
  i18n/fr.json
  i18n/hu.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 2: Dev Review, 3: QA Review, release-note-none

#7851 Add bindings to mobile view channel header
  components/channel_header_mobile/__snapshots__/channel_header_mobile.test.js.snap
  packages/mattermost-redux/src/selectors/entities/channels.ts
  packages/mattermost-redux/src/selectors/entities/common.ts
  packages/mattermost-redux/src/utils/channel_utils.ts
  plugins/mobile_channel_header_plug/__snapshots__/mobile_channel_header_plug.test.jsx.snap
  plugins/mobile_channel_header_plug/index.js
  plugins/mobile_channel_header_plug/index.ts
  plugins/mobile_channel_header_plug/mobile_channel_header_plug.jsx
  plugins/mobile_channel_header_plug/mobile_channel_header_plug.test.jsx
  plugins/mobile_channel_header_plug/mobile_channel_header_plug.tsx
Labels: 4: Reviews Complete, AutoMerge, CherryPick/Approved, release-note-none

#8028 MM-34909: Marking as unread from the post menu should mark the thread as unread
  actions/post_actions.jsx
  components/dot_menu/dot_menu.tsx
  components/post_view/post/post.jsx
  components/post_view/post/post.test.js
  components/rhs_comment/rhs_comment.jsx
  components/rhs_comment/rhs_comment.test.jsx
  components/rhs_root_post/rhs_root_post.jsx
Labels: 4: Reviews Complete, release-note

#8093 Reverting package-lock.json
  package-lock.json
Labels: release-note-none

#8075 MM-35319 - last day message inconsistencies
  components/admin_console/billing/billing_summary/billing_summary.tsx
  components/announcement_bar/cloud_trial_announcement_bar/cloud_trial_announcement_bar.tsx
Labels: 2: Dev Review, QA Review Done, Setup Cloud + CWS Test Server, release-note-none

#8096 Cherry pick #7851 for 5.35
  components/admin_console/license_settings/license_settings.test.jsx
  components/channel_header_mobile/__snapshots__/channel_header_mobile.test.js.snap
  packages/mattermost-redux/src/selectors/entities/channels.ts
  packages/mattermost-redux/src/selectors/entities/common.ts
  packages/mattermost-redux/src/utils/channel_utils.ts
  plugins/mobile_channel_header_plug/__snapshots__/mobile_channel_header_plug.test.jsx.snap
  plugins/mobile_channel_header_plug/index.js
  plugins/mobile_channel_header_plug/index.ts
  plugins/mobile_channel_header_plug/mobile_channel_header_plug.jsx
  plugins/mobile_channel_header_plug/mobile_channel_header_plug.test.jsx
  plugins/mobile_channel_header_plug/mobile_channel_header_plug.tsx
Labels: release-note-none

#8092 MM-35509 Do not use getDerivedStateFromProps to determine picker placement and instead use memoization
  components/emoji_picker/emoji_picker_overlay.jsx
Labels: CherryPick/Approved, release-note

#8099 Automated cherry pick of #8092
  components/emoji_picker/emoji_picker_overlay.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8102 ci/gitlab: fix test running on gitlab ci
  .gitlab-ci.yml
  package.json
Labels: release-note-none

#8103 Automated cherry pick of #8093
  package-lock.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, do-not-merge/release-note-label-needed

#8104 Automated cherry pick of #8102
  .gitlab-ci.yml
  package.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, do-not-merge/release-note-label-needed

#7996 MM-32786: Root post thread footer
  actions/websocket_actions.jsx
  components/channel_layout/center_channel/center_channel.tsx
  components/post_view/post/index.js
  components/post_view/post/post.jsx
  components/post_view/post/post.test.js
  components/threading/channel_threads/thread_footer/__snapshots__/thread_footer.test.tsx.snap
  components/threading/channel_threads/thread_footer/thread_footer.scss
  components/threading/channel_threads/thread_footer/thread_footer.test.tsx
  components/threading/channel_threads/thread_footer/thread_footer.tsx
  components/threading/common/button/button.scss
  components/widgets/users/avatar/__snapshots__/avatar.test.tsx.snap
  components/widgets/users/avatar/avatar.scss
  components/widgets/users/avatar/avatar.test.tsx
  components/widgets/users/avatar/avatar.tsx
  components/widgets/users/avatars/__snapshots__/avatars.test.tsx.snap
  components/widgets/users/avatars/avatars.test.tsx
  components/widgets/users/avatars/avatars.tsx
  packages/mattermost-redux/src/actions/threads.ts
  packages/mattermost-redux/src/selectors/entities/threads.ts
  packages/mattermost-redux/src/selectors/entities/users.ts
  packages/mattermost-redux/src/types/posts.ts
  packages/mattermost-redux/src/types/threads.ts
  packages/mattermost-redux/src/utils/user_utils.ts
  sass/components/_post.scss
  utils/post_utils.jsx
  utils/post_utils.test.jsx
Labels: QA Review Done, release-note

#8086 Cypress/E2E: Fixed compliance compliance data retention
  e2e/cypress/fixtures/console-example-inputs.json
  e2e/cypress/fixtures/system-roles-console-access.json
Labels: 4: Reviews Complete, release-note-none

#8027 MM-32785: In CRT, Prevent incoming replies via WS and handle feature toggling without refresh.
  actions/new_post.test.js
  actions/new_post.ts
  actions/post_actions.test.js
  actions/websocket_actions.jsx
  actions/websocket_actions.test.jsx
  components/app.jsx
  components/threading/channel_threads/posts_channel_reset_watcher/index.ts
  components/threading/channel_threads/posts_channel_reset_watcher/posts_channel_reset_watcher.tsx
  packages/mattermost-redux/src/action_types/posts.ts
  packages/mattermost-redux/src/actions/posts.ts
  packages/mattermost-redux/src/reducers/entities/posts.test.js
  packages/mattermost-redux/src/reducers/entities/posts.ts
Labels: 4: Reviews Complete, release-note

#8106 Cypress/E2E: Fix failed tests related to emoji picker
  e2e/cypress/integration/archived_channel/archive_channel_add_reaction_spec.js
  e2e/cypress/integration/emoji/custom_emoji_1_spec.js
  e2e/cypress/integration/emoji/sorted_emojis_spec.js
  e2e/cypress/integration/messaging/emoji_insert_position_spec.js
  e2e/cypress/integration/messaging/message_reaction_gm_spec.js
  e2e/cypress/integration/messaging/message_reaction_spec.js
  e2e/cypress/integration/messaging/reactions_spec.js
Labels: 4: Reviews Complete, release-note-none

#8105 Cypress/E2E: Fix emoji reaction shortcut
  e2e/cypress/integration/emoji/react_to_last_message_shortcut_spec.js
  e2e/cypress/integration/keyboard_shortcuts/ctrl_cmd_shift_slash/helpers.js
  e2e/cypress/integration/keyboard_shortcuts/ctrl_cmd_shift_slash/not_open_emoji_picker_spec.js
  e2e/cypress/integration/keyboard_shortcuts/ctrl_cmd_shift_slash/react_to_center_spec.js
  e2e/cypress/integration/keyboard_shortcuts/ctrl_cmd_shift_slash/react_to_rhs_spec.js
Labels: 4: Reviews Complete, release-note-none

#8095 Cypress/E2E: Fix flaky test on MM-T1776
  e2e/cypress/integration/auth_sso/authentication_not_cloud_spec.js
Labels: 4: Reviews Complete, release-note-none

#8091 Cypress/E2e:moved unstable to prod
  e2e/cypress/integration/enterprise/system_console/authentication_method_spec.js
  e2e/cypress/integration/messaging/message_auto_response_spec.js
  e2e/cypress/integration/messaging/receive_message_on_socket_reconnect_spec.js
  e2e/cypress/integration/messaging/visual_verification_of_tooltips_on_top_nav_channel_icons_posts_spec.js
  e2e/cypress/integration/plugins/marketplace/not_render_in_main_menu_spec.js
  e2e/cypress/integration/plugins/marketplace/render_in_main_menu_spec.js
  e2e/cypress/integration/plugins/plugin_install_spec.js
Labels: 4: Reviews Complete, release-note

#8087 MM-35332 Cypress/E2E: Not extending session when setting is disabled
  e2e/cypress/integration/enterprise/extend_session/not_extended_when_disabled/helpers.js
  e2e/cypress/integration/enterprise/extend_session/not_extended_when_disabled/with_email_login_spec.js
  e2e/cypress/integration/enterprise/extend_session/not_extended_when_disabled/with_ldap_login_spec.js
  e2e/cypress/integration/enterprise/extend_session/not_extended_when_disabled/with_saml_login_spec.js
Labels: 4: Reviews Complete, release-note-none

#8088 MM-T3080 Add Cypress test for Sign in email/pwd account
  e2e/cypress/integration/signin_authentication/login_logout_smoke_spec.js
Labels: 4: Reviews Complete, AutoMerge, Hackfest, release-note-none

#8114 Translations update from Weblate
  i18n/bg.json
  i18n/de.json
  i18n/es.json
  i18n/fr.json
  i18n/hu.json
  i18n/pl.json
  i18n/sv.json
Labels: 2: Dev Review, 3: QA Review, release-note-none

#8082 MM-35431: fixes save post disabled when opened from threads
  components/edit_post_modal/index.js
Labels: 4: Reviews Complete, release-note-none

#8109 MM-35509 (part 1) Performance improvements when receiving new posts
  actions/views/channel_sidebar.ts
  components/post_markdown/post_markdown.tsx
  components/sidebar/sidebar_category/index.ts
  components/sidebar/sidebar_category/sidebar_category.test.tsx
  components/sidebar/sidebar_category/sidebar_category.tsx
  package-lock.json
  package.json
  packages/mattermost-redux/src/selectors/entities/channel_categories.test.js
  packages/mattermost-redux/src/selectors/entities/channel_categories.ts
  packages/mattermost-redux/src/selectors/entities/channels.ts
  selectors/views/channel_sidebar.test.js
  selectors/views/channel_sidebar.ts
Labels: 3: QA Review, Setup Cloud Test Server, release-note

#8117 [MM-35555] file overlay should cover center channel input box
  sass/components/_post.scss
Labels: 4: Reviews Complete, release-note

#8100 [MM-35310] Only show channels not in a team attached to the current policy
  components/admin_console/data_retention_settings/custom_policy_form/custom_policy_form.tsx
  components/admin_console/data_retention_settings/custom_policy_form/index.ts
  components/channel_selector_modal/__snapshots__/channel_selector_modal.test.tsx.snap
  components/channel_selector_modal/channel_selector_modal.test.tsx
  components/channel_selector_modal/channel_selector_modal.tsx
  utils/test_helper.ts
Labels: 4: Reviews Complete, AutoMerge, CherryPick/Approved, Setup Cloud Test Server, release-note-none

#8076 Update README to link to mattermost.com
  README.md
Labels: 4: Reviews Complete, release-note-none

#8056 MM-35407 Update to NPM 7 and prepare to support Node 16
  actions/post_actions.test.js
  components/add_users_to_team_modal/add_users_to_team_modal.test.tsx
  components/admin_console/brand_image_setting/brand_image_setting.test.jsx
  components/admin_console/team_channel_settings/channel/details/__snapshots__/channel_details.test.tsx.snap
  components/admin_console/team_channel_settings/channel/details/channel_details.test.tsx
  components/admin_console/team_channel_settings/channel/details/channel_details.tsx
  components/integrations/installed_oauth_app/installed_oauth_app.test.tsx
  components/intl_provider/__snapshots__/intl_provider.test.jsx.snap
  components/intl_provider/intl_provider.test.jsx
  components/pdf_preview.jsx
  components/permalink_view/permalink_view.test.jsx
  components/select_team/select_team.test.tsx
  components/suggestion/suggestion_box.test.jsx
  components/warn_metric_ack_modal/warn_metric_ack_modal.test.tsx
  package-lock.json
  package.json
  store/index.js
  store/utils.js
  tests/redux-persist_mock.js
  tests/setup.js
Labels: 4: Reviews Complete, release-note-none

#8112 migrate tutorial_intro_screens to typescript
  components/tutorial/tutorial_intro_screens/__snapshots__/tutorial_intro_screens.test.tsx.snap
  components/tutorial/tutorial_intro_screens/index.tsx
  components/tutorial/tutorial_intro_screens/tutorial_intro_screens.test.tsx
  components/tutorial/tutorial_intro_screens/tutorial_intro_screens.tsx
Labels: 4: Reviews Complete, release-note-none

#8113 migrate tutorial to typescript
  components/tutorial/index.tsx
  components/tutorial/menu_tutorial_tip.tsx
  components/tutorial/tutorial_tip/index.ts
  components/tutorial/tutorial_view.tsx
Labels: 4: Reviews Complete, release-note-none

#8068 [MM-35110] Change plugin header count from 5 to 15
  e2e/cypress/integration/plugins/plugin_buttons_spec.js
  e2e/cypress/utils/plugins.js
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#8130 ci/gitlab: add ssh keys to be able to fetch the repositories
  .gitlab-ci.yml
Labels: release-note-none

#7883 [MM-33462] Extend manifest type
  packages/mattermost-redux/src/types/apps.ts
  selectors/views/marketplace.test.ts
Labels: 4: Reviews Complete, release-note-none

#8131 update pr template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: release-note-none

#7963 [MM-34304] Migrate 'components/admin_console/admin_button_outline' and associated tests to TypeScript
  components/admin_console/admin_button_outline/__snapshots__/admin_button_outline.test.tsx.snap
  components/admin_console/admin_button_outline/admin_button_outline.jsx
  components/admin_console/admin_button_outline/admin_button_outline.scss
  components/admin_console/admin_button_outline/admin_button_outline.test.tsx
  components/admin_console/admin_button_outline/admin_button_outline.tsx
Labels: 3: QA Review, release-note

#8083 MM-35270, MM-35271: CRT dotmenu changes
  components/post_view/post_info/index.ts
  components/post_view/post_info/post_info.test.tsx
  components/post_view/post_info/post_info.tsx
  components/rhs_comment/__snapshots__/rhs_comment.test.jsx.snap
  components/rhs_comment/index.js
  components/rhs_comment/rhs_comment.jsx
  components/rhs_comment/rhs_comment.test.jsx
  components/rhs_root_post/__snapshots__/rhs_root_post.test.jsx.snap
  components/rhs_root_post/index.js
  components/rhs_root_post/rhs_root_post.jsx
  components/rhs_root_post/rhs_root_post.test.jsx
Labels: 4: Reviews Complete, release-note-none

#8043 [MM-34353] Migrate 'components/status_dropdown' and associated tests to TypeScript
  components/legacy_sidebar/header/sidebar_header.jsx
  components/sidebar/sidebar_header/sidebar_header.tsx
  components/status_dropdown/__snapshots__/status_dropdown.test.tsx.snap
  components/status_dropdown/index.ts
  components/status_dropdown/status_dropdown.test.tsx
  components/status_dropdown/status_dropdown.tsx
  packages/mattermost-redux/src/types/users.ts
Labels: 4: Reviews Complete, release-note

#8047 [MM-34344] Migrated search_date_suggestion component to TypeScript
  components/suggestion/search_date_suggestion/index.ts
  components/suggestion/search_date_suggestion/search_date_suggestion.tsx
Labels: 4: Reviews Complete, release-note-none

#8110 MM-35432: fixes bolding/mention count on "Threads" LHS link when toggling CRT on
  components/threading/global_threads_link/global_threads_link.tsx
Labels: 4: Reviews Complete, release-note-none

#8002 MM-32782: RHSThread Follow Button
  components/rhs_header_post/index.ts
  components/rhs_header_post/rhs_header_post.tsx
  sass/layout/_sidebar-right.scss
Labels: 4: Reviews Complete, release-note

#8132 Update CI to use Node 14
  .circleci/config.yml
  .eslintrc.json
  .gitlab-ci.yml
  components/threading/channel_threads/thread_footer/__snapshots__/thread_footer.test.tsx.snap
  package-lock.json
  package.json
  tests/setup.js
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none

#8111 Cypress/E2E: Fix test related to email and MFA
  e2e/cypress/integration/account_settings/general/email_spec.js
  e2e/cypress/integration/auth_sso/authentication_1_spec.js
  e2e/cypress/integration/auth_sso/authentication_4_spec.js
  e2e/cypress/integration/email/mention_email_notification_spec.js
  e2e/cypress/integration/enterprise/cloud/onboarding/login_page_link_account_creation_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/guest_identification_spec.js
  e2e/cypress/integration/notifications/channel_links_show_as_links_spec.js
  e2e/cypress/integration/notifications/desktop_notifications_spec.js
  e2e/cypress/integration/notifications/mention_email_notification_spec.js
  e2e/cypress/integration/onboarding/invalidate_pending_email_invitations_spec.js
  e2e/cypress/integration/onboarding/use_team_invite_link_to_sign_up_spec.js
  e2e/cypress/integration/signin_authentication/authentication_spec.js
  e2e/cypress/integration/signin_authentication/forgot_password_spec.js
  e2e/cypress/integration/signin_authentication/helpers.js
  e2e/cypress/integration/signin_authentication/mfa_authentication_spec.js
  e2e/cypress/integration/system_console/user_management_spec.js
  e2e/cypress/integration/team_settings/closed_team_invite_by_email_spec.js
  e2e/cypress/integration/team_settings/closed_team_invite_with_non_mattermost_domain_spec.js
  e2e/cypress/integration/team_settings/closed_team_invite_with_specific_domain_spec.js
  e2e/cypress/integration/team_settings/helpers.js
  e2e/cypress/support/api/user.d.ts
  e2e/cypress/support/api/user.js
  e2e/cypress/support/email.d.ts
  e2e/cypress/support/email.js
  e2e/cypress/support/index.js
  e2e/cypress/utils/email.js
  e2e/cypress/utils/index.js
Labels: 4: Reviews Complete, release-note-none

#8121 Cypress/E2E: Fix several tests from the recent cloud test run
  e2e/cypress/integration/accessibility/accessibility_dropdowns_spec.js
  e2e/cypress/integration/account_settings/display/theme/custom_theme_sidebar_styles_spec.js
  e2e/cypress/integration/mark_as_unread/toast_appears_unread_spec.js
  e2e/cypress/integration/menus/status_dropdown_spec.js
  e2e/cypress/integration/messaging/permalink_message_edit_spec.js
  e2e/cypress/integration/plugins/marketplace/not_render_in_main_menu_spec.js
  e2e/cypress/integration/plugins/marketplace/render_in_main_menu_spec.js
  e2e/cypress/support/ui/menu.d.ts
  e2e/cypress/support/ui/menu.js
Labels: 4: Reviews Complete, release-note-none

#8122 Cypress/E2E: Fix test of custom status and match with the test case
  e2e/cypress/integration/custom_status/custom_status_5_spec.js
Labels: 4: Reviews Complete, release-note-none

#8136 Revert "[MM-8497] Ability to set Do Not Disturb for a specified period of time (#7037)"
  components/dnd_custom_time_picker_modal/dnd_custom_time_picker_modal.scss
  components/dnd_custom_time_picker_modal/dnd_custom_time_picker_modal.tsx
  components/dnd_custom_time_picker_modal/index.ts
  components/generic_modal.scss
  components/sidebar/sidebar_category/sidebar_category_menu/__snapshots__/sidebar_category_menu.test.tsx.snap
  components/sidebar/sidebar_channel/sidebar_channel_menu/__snapshots__/sidebar_channel_menu.test.tsx.snap
  components/status_dropdown/__snapshots__/status_dropdown.test.tsx.snap
  components/status_dropdown/index.ts
  components/status_dropdown/status_dropdown.scss
  components/status_dropdown/status_dropdown.tsx
  components/widgets/menu/menu.scss
  components/widgets/menu/menu_header.scss
  components/widgets/menu/menu_items/menu_item.scss
  components/widgets/menu/menu_items/submenu_item.tsx
  components/widgets/menu/menu_modals/submenu_modal/__snapshots__/submenu_modal.test.tsx.snap
  e2e/cypress/integration/status/status_dnd_1_spec.js
  i18n/en.json
  package-lock.json
  packages/mattermost-redux/src/types/users.ts
  sass/components/_day-picker.scss
  sass/components/_dnd-pickers-dropdown-menu.scss
  sass/components/_react-day-picker.scss
  sass/layout/_headers.scss
  sass/utils/_modifiers.scss
  utils/constants.jsx
  utils/datetime.ts
  utils/timezone.jsx
  utils/utils.jsx
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#8140 Revert "[MM-8497] Ability to set Do Not Disturb for a specified period of time (#7037)"
  components/dnd_custom_time_picker_modal/dnd_custom_time_picker_modal.scss
  components/dnd_custom_time_picker_modal/dnd_custom_time_picker_modal.tsx
  components/dnd_custom_time_picker_modal/index.ts
  components/generic_modal.scss
  components/sidebar/sidebar_category/sidebar_category_menu/__snapshots__/sidebar_category_menu.test.tsx.snap
  components/sidebar/sidebar_channel/sidebar_channel_menu/__snapshots__/sidebar_channel_menu.test.tsx.snap
  components/status_dropdown/__snapshots__/status_dropdown.test.tsx.snap
  components/status_dropdown/index.jsx
  components/status_dropdown/status_dropdown.jsx
  components/status_dropdown/status_dropdown.scss
  components/widgets/menu/menu.scss
  components/widgets/menu/menu_header.scss
  components/widgets/menu/menu_items/menu_item.scss
  components/widgets/menu/menu_items/submenu_item.tsx
  components/widgets/menu/menu_modals/submenu_modal/__snapshots__/submenu_modal.test.tsx.snap
  e2e/cypress/integration/status/status_dnd_1_spec.js
  i18n/en.json
  packages/mattermost-redux/src/types/users.ts
  sass/components/_day-picker.scss
  sass/components/_dnd-pickers-dropdown-menu.scss
  sass/components/_react-day-picker.scss
  sass/layout/_headers.scss
  sass/utils/_modifiers.scss
  utils/constants.jsx
  utils/datetime.ts
  utils/timezone.jsx
  utils/utils.jsx
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#7431 [MM-20384] Migrated LatexBlock component to TypeScript
  components/latex_block/__snapshots__/latex_block.test.tsx.snap
  components/latex_block/index.ts
  components/latex_block/latex_block.test.tsx
  components/latex_block/latex_block.tsx
  package-lock.json
  package.json
Labels: 4: Reviews Complete, release-note-none

#8137 [MM-35595] Stop the search shortcut from triggering full screen view on Mac
  components/search/search.tsx
Labels: 4: Reviews Complete, QA Review Done, Setup Cloud Test Server, release-note

#8125 MM-35237: CRT, Keep Threads mention badge on hover
  components/threading/global_threads_link/global_threads_link.scss
Labels: 4: Reviews Complete, release-note-none

#8124 MM-35689 Fix error caused by trying to render non-string attachment field
  components/post_view/message_attachments/message_attachment/__snapshots__/message_attachment.test.tsx.snap
  components/post_view/message_attachments/message_attachment/message_attachment.test.tsx
  components/post_view/message_attachments/message_attachment/message_attachment.tsx
Labels: 4: Reviews Complete, release-note

#8116 [MM-35092][MM-35093] - Sidebar opacity fixes
  sass/layout/_sidebar-left.scss
Labels: 4: Reviews Complete, release-note-none

#8101 MM-T260 Mark as Unread New Messages line extra space moves with it
  e2e/cypress/integration/mark_as_unread/helpers.js
  e2e/cypress/integration/mark_as_unread/mark_as_unread_spec.js
Labels: 4: Reviews Complete, release-note-none

#8144 Translations update from Weblate
  i18n/fr.json
  i18n/hu.json
  i18n/ja.json
  i18n/nl.json
  i18n/pt-BR.json
  i18n/sv.json
  i18n/tr.json
Labels: 2: Dev Review, 3: QA Review, release-note-none

#8084 [MM-27447] Remove usage of jQuery from post components
  components/create_comment/create_comment.jsx
  components/create_comment/create_comment.test.jsx
  components/link_tooltip/__snapshots__/link_tooltip.test.tsx.snap
  components/link_tooltip/link_tooltip.scss
  components/link_tooltip/link_tooltip.tsx
  components/suggestion/search_suggestion_list.jsx
  components/suggestion/suggestion_list.jsx
  components/threading/thread_viewer/__snapshots__/thread_viewer.test.tsx.snap
  components/threading/thread_viewer/thread_viewer.tsx
  e2e/cypress/integration/messaging/message_reply_scrollable_spec.js
  e2e/cypress/integration/plugins/link_tooltip_spec.js
  e2e/cypress/integration/search_autocomplete/scroll_spec.js
Labels: 4: Reviews Complete, release-note-none

#8151 Cypress/E2E: Promote tests to prod
  e2e/cypress/integration/autocomplete/database/users_in_channel_switcher_spec.js
  e2e/cypress/integration/autocomplete/database/users_in_message_input_box_spec.js
  e2e/cypress/integration/enterprise/extend_session/not_extended_when_disabled/with_email_login_spec.js
  e2e/cypress/integration/enterprise/extend_session/not_extended_when_disabled/with_ldap_login_spec.js
  e2e/cypress/integration/files_and_attachments/channel_files_spec.js
  e2e/cypress/integration/files_and_attachments/image_link_preview_spec.js
  e2e/cypress/integration/notifications/browser_tab_notification_spec.js
  e2e/cypress/integration/plugins/plugin_buttons_spec.js
  e2e/cypress/integration/signin_authentication/login_logout_smoke_spec.js
  e2e/cypress/integration/signin_authentication/mfa_authentication_spec.js
Labels: 4: Reviews Complete, release-note-none

#8150 Cypress/E2E: Fix account setting sections json
  e2e/cypress/fixtures/account_setting_sections.json
Labels: 3: QA Review, release-note-none

#8094 MM-35591 - multiple sku options in billing subscription pages
  components/admin_console/billing/billing_subscriptions/billing_subscriptions.scss
  components/admin_console/billing/billing_subscriptions/billing_subscriptions.tsx
  components/admin_console/billing/billing_subscriptions/index.tsx
  components/admin_console/billing/billing_summary/index.tsx
  components/admin_console/billing/plan_details/index.tsx
  components/admin_console/billing/plan_details/plan_details.tsx
  i18n/en.json
  images/free-trial-private-cloud-image.svg
  packages/mattermost-redux/src/types/cloud.ts
  utils/constants.jsx
Labels: QA Deferred, Setup Cloud + CWS Test Server, release-note

#7638 Fix custom emojis for statuses not loaded on page refresh
  actions/emoji_actions.js
  actions/emoji_actions.jsx
  actions/emoji_actions.mock.test.js
  actions/emoji_actions.test.js
  actions/status_actions.jsx
  actions/status_actions.test.js
  actions/user_actions.jsx
  actions/views/channel.js
  actions/websocket_actions.jsx
  components/custom_status/custom_status_emoji.test.tsx
  components/custom_status/custom_status_emoji.tsx
  components/custom_status/custom_status_modal.tsx
  components/emoji_picker/index.js
  components/more_direct_channels/index.ts
  components/more_direct_channels/more_direct_channels.test.jsx
  components/more_direct_channels/more_direct_channels.tsx
  components/root/root.jsx
Labels: 4: Reviews Complete, release-note

#8128 Fixed custom status issues
  components/post_profile_picture/__snapshots__/post_profile_picture.test.tsx.snap
  components/post_profile_picture/post_profile_picture.tsx
  components/profile_picture/profile_picture.tsx
  components/profile_popover/profile_popover.jsx
  components/profile_popover/profile_popover.scss
  components/rhs_root_post/index.js
  components/rhs_root_post/rhs_root_post.jsx
Labels: 4: Reviews Complete, release-note

#8162 Reduce number of workers in CI tests
  package.json
Labels: 2: Dev Review, release-note-none

#8141 [MM-35796] Use same constant to validate permissions
  components/admin_console/admin_definition.jsx
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#8146 [MM-35780] - Update add users to channel modal test case
  e2e/cypress/integration/channel_settings/add_users_to_channel_spec.js
Labels: 4: Reviews Complete, release-note-none

#8164 [MM-35796] Use same constant to validate permissions (cherry-pick v5.35)
  components/admin_console/admin_definition.jsx
Labels: AutoMerge, release-note

#8039 [MM-34169] Data retention cypress tests
  components/admin_console/data_retention_settings/__snapshots__/data_retention_settings.test.tsx.snap
  components/admin_console/data_retention_settings/channel_list/__snapshots__/channel_list.test.tsx.snap
  components/admin_console/data_retention_settings/channel_list/channel_list.tsx
  components/admin_console/data_retention_settings/custom_policy_form/__snapshots__/custom_policy_form.test.tsx.snap
  components/admin_console/data_retention_settings/custom_policy_form/custom_policy_form.tsx
  components/admin_console/data_retention_settings/data_retention_settings.tsx
  components/admin_console/data_retention_settings/dropdown_options/dropdown_options.tsx
  components/admin_console/data_retention_settings/global_policy_form/__snapshots__/global_policy_form.test.tsx.snap
  components/admin_console/data_retention_settings/global_policy_form/global_policy_form.tsx
  components/admin_console/data_retention_settings/team_list/__snapshots__/team_list.test.tsx.snap
  components/admin_console/data_retention_settings/team_list/team_list.tsx
  components/channel_selector_modal/channel_selector_modal.tsx
  components/widgets/inputs/__snapshots__/dropdown_input_hybrid.test.tsx.snap
  components/widgets/inputs/dropdown_input_hybrid.tsx
  e2e/cypress/integration/enterprise/system_console/compliance/data_retention_policies_spec.js
  e2e/cypress/integration/enterprise/system_console/compliance/helpers.js
  e2e/cypress/support/api/data_retention.js
  e2e/cypress/support/api/index.js
  e2e/cypress/support/api_commands.js
  e2e/cypress/support/ui/data_retention.d.ts
  e2e/cypress/support/ui/data_retention.js
  e2e/cypress/support/ui/index.js
Labels: 3: QA Review, release-note-none

#8163 WIP ci/test: add NODE_OPTIONS max_old_space_size=500
  .gitlab-ci.yml
  package.json
Labels: release-note-none

#8071 [MM-34303] Add team ID to response when linking a channel to a group
  packages/mattermost-redux/src/actions/groups.test.js
  packages/mattermost-redux/src/reducers/entities/groups.test.ts
  packages/mattermost-redux/src/reducers/entities/groups.ts
Labels: 3: QA Review, Setup Cloud Test Server, release-note

#8154 Use Node 16 for CI
  .circleci/config.yml
  .gitlab-ci.yml
  package-lock.json
  package.json
  tests/setup.js
Labels: 4: Reviews Complete, release-note-none

#7933 MM-34758 Collapsed Reply Threads without mobile support
  actions/websocket_actions.jsx
  packages/mattermost-redux/src/actions/channels.test.js
  packages/mattermost-redux/src/actions/threads.ts
  packages/mattermost-redux/src/client/client4.ts
  packages/mattermost-redux/src/selectors/entities/threads.test.js
  packages/mattermost-redux/src/selectors/entities/threads.ts
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note

#8119 MM-35435 - add multiple SKU options to purchase modal
  actions/cloud.tsx
  components/common/__snapshots__/radio_group.test.tsx.snap
  components/common/radio_group.test.tsx
  components/common/radio_group.tsx
  components/purchase_modal/index.ts
  components/purchase_modal/process_payment_setup.tsx
  components/purchase_modal/purchase.scss
  components/purchase_modal/purchase_modal.tsx
  i18n/en.json
  packages/mattermost-redux/src/client/client4.ts
  utils/constants.jsx
Labels: QA Deferred, release-note-none

#8143 MM-35838/MM-35923 Fix memoization of selectors
  .eslintrc.json
  components/markdown/index.ts
  packages/mattermost-redux/src/selectors/entities/channel_categories.test.js
  packages/mattermost-redux/src/selectors/entities/channel_categories.ts
  packages/mattermost-redux/src/selectors/entities/channels.test.js
  packages/mattermost-redux/src/selectors/entities/channels.ts
  utils/text_formatting.tsx
  utils/text_formatting_channel_links.test.jsx
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#7984 MM-32801 : Webapp: In mention autocomplete, remove (Nickname) when (you) is present
  components/suggestion/at_mention_provider/__snapshots__/at_mention_suggestion.test.tsx.snap
  components/suggestion/at_mention_provider/at_mention_suggestion.jsx
  components/suggestion/at_mention_provider/at_mention_suggestion.test.tsx
Labels: 4: Reviews Complete, release-note

#8077 String update: Clarify Add Member to Channel hint text
  components/multiselect/multiselect.tsx
  i18n/en.json
Labels: 4: Reviews Complete, release-note

#8134 MM-35715: CRT removes comment count
  components/post_view/post_info/post_info.tsx
Labels: 4: Reviews Complete, release-note-none

#8158 Cypress/E2E: Apply temp fix to dnd e2e
  e2e/cypress/integration/accessibility/accessibility_dropdowns_spec.js
  e2e/cypress/integration/account_settings/display/theme/custom_theme_sidebar_styles_spec.js
  e2e/cypress/integration/menus/status_dropdown_spec.js
  e2e/cypress/support/ui/menu.js
Labels: 4: Reviews Complete, release-note-none
