Repository mattermost/mattermost-webapp, pull requests merged in 2021-01, with the labels that each got.

#7226 [MM-30337] - Fix mobile menus and remove redundant styles
  components/widgets/menu/menu_items/menu_item.scss
  sass/layout/_sidebar-left.scss
  sass/responsive/_mobile.scss
Labels: 4: Reviews Complete

#7200 [MM-31149] don't allow change of roles if user can't manage members
  components/channel_members_dropdown/index.js
Labels: 4: Reviews Complete, AutoMerge

#7230 [MM-30391] E2E tests - Team Settings pt. 2
  e2e/cypress/integration/team_settings/join_closed_team_with_not_allowed_email_spec.js
  e2e/cypress/integration/team_settings/manage_members_spec.js
Labels: 4: Reviews Complete

#7205 [MM-27210] archived channels 4 II
  e2e/cypress/integration/archived_channel/archive_channel_search_spec.js
  e2e/cypress/integration/archived_channel/archived_leave_channel_spec.js
  e2e/cypress/integration/archived_channel/helpers.js
  e2e/cypress/support/ui/channel.js
Labels: 4: Reviews Complete

#6997 Migrate components/analytics/system_analytics module to TypeScript
  components/analytics/system_analytics/index.ts
  components/analytics/system_analytics/system_analytics.tsx
Labels: 4: Reviews Complete, AutoMerge, Lifecycle/1:stale

#7232 MM-20449 Migrate 'components/integrations/installed_incoming_webhooks' module and associated tests to TypeScript
  components/integrations/__snapshots__/installed_incoming_webhook.test.tsx.snap
  components/integrations/installed_incoming_webhook.test.tsx
  components/integrations/installed_incoming_webhooks/index.ts
  components/integrations/installed_incoming_webhooks/installed_incoming_webhooks.tsx
Labels: 4: Reviews Complete, AutoMerge

#7235 [MM-31358] Clicking 'Jump to recent' in an archived channel shouldn't redirect to town square
  actions/global_actions.tsx
Labels: 4: Reviews Complete

#7212 MM-20422 Migrate 'components/user_profile' module and associated tests to TypeScript
  components/overlay_trigger.tsx
  components/post_view/commented_on/__snapshots__/commented_on.test.tsx.snap
  components/post_view/commented_on/commented_on.tsx
  components/post_view/post_header/post_header.tsx
  components/user_profile/__snapshots__/user_profile.test.tsx.snap
  components/user_profile/index.ts
  components/user_profile/user_profile.test.tsx
  components/user_profile/user_profile.tsx
Labels: 4: Reviews Complete

#7271 Revert "MM-24072-Position the autocomplete popover relative to the @,~,/ trigger in the post draft"
  components/__snapshots__/textbox.test.tsx.snap
  components/suggestion/at_mention_provider/at_mention_provider.jsx
  components/suggestion/channel_mention_provider.jsx
  components/suggestion/emoticon_provider.jsx
  components/suggestion/suggestion_box.jsx
  components/suggestion/suggestion_list.jsx
  sass/components/_modal.scss
  sass/components/_suggestion-list.scss
  tests/setup.js
  utils/constants.jsx
  utils/utils.jsx
  utils/utils.test.jsx
Labels: 2: Dev Review

#7148 [MM-28155] Add link customization e2e tests
  e2e/cypress/integration/system_console/site_configuration/link_customization_spec.js
Labels: 2: Dev Review

#7238 [MM-30368] E2E Testing - Channel Sidebar
  e2e/cypress/integration/channel_sidebar/channel_sidebar_spec.js
  e2e/cypress/integration/channel_sidebar/dm_gm_behaviour_spec.js
  e2e/cypress/integration/channel_sidebar/sidebar_category_menu_spec.js
  e2e/cypress/integration/channel_sidebar/sidebar_channel_menu_spec.js
Labels: 4: Reviews Complete

#7270 Cypress/E2E: Ignore uncaught exception by cypress
  e2e/cypress/integration/messaging/at_mentions_spec.js
  e2e/cypress/integration/messaging/message_permalink_spec.js
  e2e/cypress/integration/notifications/desktop_notifications_spec.js
  e2e/cypress/integration/team_settings/teams_spec.js
  e2e/cypress/support/api/system.js
  e2e/cypress/support/index.js
  e2e/cypress/support/notification.js
Labels: 4: Reviews Complete

#7269 Cypress/E2E: Demote unstable tests, add flag when not to run on cloud and fix saving test report
  e2e/cypress/integration/archived_channel/archived_leave_channel_spec.js
  e2e/cypress/integration/channel/channel_routing_spec.js
  e2e/cypress/integration/channel_settings/more_unreads_position_with_scroll_spec.js
  e2e/cypress/integration/enterprise/group_mentions/group_mentions_system_messages_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/guest_identification_spec.js
  e2e/cypress/integration/enterprise/ldap/ldap_group_sync_spec.js
  e2e/cypress/integration/enterprise/ldap_group/channel_modes_spec.js
  e2e/cypress/integration/enterprise/system_console/archived_channels_spec.js
  e2e/cypress/integration/enterprise/system_console/channel_members_spec.js
  e2e/cypress/integration/enterprise/system_console/channel_moderation/create_posts_spec.js
  e2e/cypress/integration/enterprise/system_console/channel_moderation/manage_members_spec.js
  e2e/cypress/integration/enterprise/system_console/channel_moderation/system_config_spec.js
  e2e/cypress/integration/files_and_attachments/upload_files_not_cloud_spec.js
  e2e/cypress/integration/interactive_dialog/simple_dialog_spec.js
  e2e/cypress/integration/messaging/header_not_cloud_spec.js
  e2e/cypress/integration/messaging/markdown_spec.js
  e2e/cypress/integration/modals/quick_switcher_spec.js
  e2e/cypress/integration/multi_team_and_dm/gm_header_spec.js
  e2e/cypress/integration/plugins/upgrade_spec.js
  e2e/save_report.js
Labels: 4: Reviews Complete

#7211 MM-20452 Migrate installed OAuth apps component to TypeScript
  components/integrations/installed_oauth_app/__snapshots__/installed_oauth_app.test.tsx.snap
  components/integrations/installed_oauth_app/index.ts
  components/integrations/installed_oauth_app/installed_oauth_app.test.tsx
  components/integrations/installed_oauth_app/installed_oauth_app.tsx
Labels: 4: Reviews Complete

#7277 [MM-4644] Upgrade Rate Limiting help text
  components/admin_console/admin_definition.jsx
  i18n/en.json
Labels: 1: PM Review, 2: Dev Review, 3: QA Review

#7125 [GH-16211][MM-30274] Implement hotkeys for link markdown
  components/create_comment/create_comment.jsx
  components/create_post/create_post.jsx
  components/edit_post_modal/edit_post_modal.jsx
  tests/helpers/markdown_hotkey_helpers.js
  utils/utils.jsx
Labels: 4: Reviews Complete

#6742 Migrate 'components/emoji/emoji_list' module and associated tests to TypeScript
  components/emoji/emoji_list/emoji_list.tsx
  components/emoji/emoji_list/index.js
  components/emoji/emoji_list/index.ts
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted

#7241 MM-31361: Fix missing error text when team name is empty
  components/create_team/components/display_name.jsx
  components/create_team/components/display_name.test.jsx
Labels: 4: Reviews Complete, Setup Cloud Test Server

#7278 MM-31697- Remove OpenId from System Console
  components/admin_console/admin_definition.jsx
  components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.jsx.snap
  e2e/cypress/integration/enterprise/system_console/openid/openid_spec.js
Labels: 2: Dev Review, CherryPick/Approved, QA Review Done

#7265 [MM-30384] Implement Cypress test cases
  components/admin_console/permission_schemes_settings/__snapshots__/permission_schemes_settings.test.jsx.snap
  components/admin_console/permission_schemes_settings/permission_schemes_settings.jsx
  e2e/cypress/integration/enterprise/permissions/team_permissions_spec.js
  e2e/cypress/integration/enterprise/system_console/system_scheme_permission_part2_spec.js
  e2e/cypress/integration/enterprise/system_console/team_scheme_permission_part2_spec.js
Labels: 4: Reviews Complete

#7197 [MM-30349] Demo plugin - Webhook events
  e2e/cypress/integration/plugins/demo_plugin/helper.js
  e2e/cypress/integration/plugins/demo_plugin/webhook_spec.js
Labels: 4: Reviews Complete

#7294 Automated cherry pick of #7278
  components/admin_console/admin_definition.jsx
  components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.jsx.snap
  e2e/cypress/integration/enterprise/system_console/openid/openid_spec.js
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7292 MM-31189 Revert New Messages toast PRs
  components/toast_wrapper/toast_wrapper.jsx
  components/toast_wrapper/toast_wrapper.test.jsx
Labels: 4: Reviews Complete, AutoMerge, CherryPick/Approved, Setup Cloud Test Server

#7284 [MM-31580] Fix call to getChannel to use new parameter format
  actions/notification_actions.jsx
Labels: 4: Reviews Complete, CherryPick/Approved, QA Review Done, Setup Cloud Test Server

#7298 Automated cherry pick of #7292
  components/toast_wrapper/toast_wrapper.jsx
  components/toast_wrapper/toast_wrapper.test.jsx
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7299 Automated cherry pick of #7284
  actions/notification_actions.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7300 Automated cherry pick of #7284
  actions/notification_actions.jsx
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7290 [MM-31708][MM-31726][MM-31739][MM-31727] - Fix regressions in RHS and Status menu
  components/search/search.tsx
  components/search_bar/__snapshots__/search_bar.test.jsx.snap
  components/search_bar/search_bar.test.jsx
  components/search_bar/search_bar.tsx
  components/search_results/search_results.tsx
  components/sidebar_right/sidebar_right.jsx
  components/widgets/menu/menu_items/menu_item.scss
  components/widgets/separator/separator.scss
Labels: CherryPick/Approved

#7301 Automated cherry pick of #7292
  components/toast_wrapper/toast_wrapper.jsx
  components/toast_wrapper/toast_wrapper.test.jsx
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7302 Automated cherry pick of #7290
  components/search/search.tsx
  components/search_bar/__snapshots__/search_bar.test.jsx.snap
  components/search_bar/search_bar.test.jsx
  components/search_bar/search_bar.tsx
  components/search_results/search_results.tsx
  components/sidebar_right/sidebar_right.jsx
  components/widgets/menu/menu_items/menu_item.scss
  components/widgets/separator/separator.scss
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7303 MM-31858 - Include build hash in cloud about modal
  components/about_build_modal/__snapshots__/about_build_modal.test.jsx.snap
  components/about_build_modal/about_build_modal_cloud/about_build_modal_cloud.scss
  components/about_build_modal/about_build_modal_cloud/about_build_modal_cloud.tsx
Labels: 4: Reviews Complete, AutoMerge, QA Review Done, Setup Cloud Test Server

#7287 MM-31716: Remove the word experimental from gossip setting
  components/admin_console/__snapshots__/cluster_settings.test.jsx.snap
  components/admin_console/cluster_settings.jsx
  i18n/en.json
Labels: 4: Reviews Complete

#7280 Cypress/E2E: Add explicit wait with cy.postMessage
  e2e/cypress/support/ui_commands.js
Labels: 4: Reviews Complete

#7268 [MM-30352] Cypress/E2E: Plugin Management
  e2e/cypress/integration/plugins/plugin_install_spec.js
  e2e/cypress/integration/plugins/plugin_startup_fail_spec.js
Labels: 4: Reviews Complete, AutoMerge

#7223 Convert 'components/about_build_modal/about_build_modal' to typescript
  components/about_build_modal/__snapshots__/about_build_modal.test.tsx.snap
  components/about_build_modal/about_build_modal.test.tsx
  components/about_build_modal/about_build_modal.tsx
  components/about_build_modal/index.ts
  components/html_entities/nbsp.tsx
  types/global.d.ts
Labels: 3: QA Review

#7289 adding Swedish and Bulgarian translations
  components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
  i18n/bg.json
  i18n/i18n.jsx
  i18n/sv.json
Labels: 4: Reviews Complete

#7305 Fix limit banner show modal for cloud in-app purchases
  components/announcement_bar/cloud_announcement_bar/user_limit_announcement_bar.tsx
  components/announcement_bar/default_announcement_bar/announcement_bar.tsx
  components/announcement_bar/payment_announcement_bar/payment_announcement_bar.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, QA Review Done

#7307 Automated cherry pick of #7305
  components/announcement_bar/cloud_announcement_bar/user_limit_announcement_bar.tsx
  components/announcement_bar/default_announcement_bar/announcement_bar.tsx
  components/announcement_bar/payment_announcement_bar/payment_announcement_bar.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#6926 Remove background color for post action buttons
  components/post_view/message_attachments/action_button/action_button.jsx
  components/post_view/message_attachments/action_button/action_button.test.jsx
Labels: 4: Reviews Complete

#7251 [GH-16126] - Migrate 'components/integrations/edit_command' module and associated tests to TypeScript
  components/integrations/edit_command/__snapshots__/edit_command.test.tsx.snap
  components/integrations/edit_command/edit_command.test.tsx
  components/integrations/edit_command/edit_command.tsx
  components/integrations/edit_command/index.ts
  utils/test_helper.ts
Labels: 4: Reviews Complete

#7266 Some messages mark as traslatable
  components/next_steps_view/next_steps_tips.tsx
  components/purchase_modal/purchase_modal.tsx
  i18n/en.json
Labels: QA Review Done

#7252 [GH-16128] - Migrate 'components/integrations/bots' module and associated tests to TypeScript
  components/integrations/bots/bot.test.tsx
  components/integrations/bots/bot.tsx
  components/integrations/bots/bots.test.tsx
  components/integrations/bots/bots.tsx
  components/integrations/bots/index.ts
  utils/test_helper.ts
Labels: 4: Reviews Complete

#7309 Cypress/E2E: fix and update tests
  e2e/cypress.json
  e2e/cypress/integration/bot_accounts/tags_spec.js
  e2e/cypress/integration/emoji/react_to_last_message_shortcut_spec.js
  e2e/cypress/integration/messaging/header_spec.js
  e2e/cypress/integration/messaging/message_reply_too_long_spec.js
  e2e/cypress/integration/messaging/pinned_posts_spec.js
  e2e/cypress/integration/messaging/post_pre_header_spec.js
  e2e/cypress/integration/messaging/visual_verification_of_tooltips_on_top_nav_channel_icons_posts_spec.js
  e2e/cypress/integration/search/clear_input_spec.js
  e2e/cypress/integration/system_console/site_configuration/link_customization_spec.js
  e2e/cypress/integration/system_console/user_management/users_deactivation_spec.js
  e2e/cypress/integration/system_console/user_management/users_reactivation_spec.js
  e2e/cypress/integration/system_console/user_management/users_spec.js
  e2e/cypress/support/api/system.js
  e2e/cypress/support/api/user.js
Labels: 4: Reviews Complete, CherryPick/Approved

#7312 Cypress/E2E: Fix user guide help spec
  e2e/cypress/integration/menus/user_guide_help_spec.js
Labels: 4: Reviews Complete

#7295 MM-29636 - add the cancel subscription section in subscription screen
  components/admin_console/billing/billing_subscriptions.scss
  components/admin_console/billing/billing_subscriptions.tsx
  i18n/en.json
Labels: 4: Reviews Complete, QA Review Done, Setup Cloud Test Server

#7264 MM-30362: Cypress/E2E: LDAP-SAML Sync
  e2e/cypress.json
  e2e/cypress/fixtures/ldap-add-user.ldif
  e2e/cypress/fixtures/ldap-reset-data.ldif
  e2e/cypress/fixtures/saml_ldap_users.json
  e2e/cypress/integration/ad_ldap/saml_ldap_sync_id_attrib_spec.js
  e2e/cypress/integration/ad_ldap/saml_ldap_sync_remove_spec.js
  e2e/cypress/integration/ad_ldap/saml_ldap_sync_spec.js
  e2e/cypress/plugins/index.js
  e2e/cypress/plugins/keycloak_request.js
  e2e/cypress/support/api/user.js
  e2e/cypress/support/common_login_commands.d.ts
  e2e/cypress/support/common_login_commands.js
  e2e/cypress/support/index.js
  e2e/cypress/support/keycloak_commands.d.ts
  e2e/cypress/support/keycloak_commands.js
  e2e/cypress/support/ldap_commands.d.ts
  e2e/cypress/support/ldap_commands.js
  e2e/cypress/support/ldap_server_commands.d.ts
  e2e/cypress/support/ldap_server_commands.js
  e2e/cypress/support/saml_commands.js
  e2e/cypress/support/ui/account_settings_modal.d.ts
  e2e/cypress/support/ui/account_settings_modal.js
Labels: 3: QA Review

#7209 [MM-27209] - Add spec for archived channels part 03
  e2e/cypress/integration/channel/archived_channels_spec.js
Labels: 4: Reviews Complete, AutoMerge

#7319 MM-31960 Fix custom emoji list and make related tests more stable
  components/emoji/emoji_list/emoji_list.tsx
  e2e/cypress/integration/emoji/custom_emoji_spec.js
Labels: 4: Reviews Complete

#7285 MM-31616 - fix js errors shown for switch channel&incident plugin suggestion m…
  components/suggestion/suggestion_box.jsx
  components/suggestion/suggestion_list.jsx
Labels: 4: Reviews Complete

#7315 Cypress/E2E: Fix link customization spec
  e2e/cypress/integration/system_console/site_configuration/link_customization_spec.js
Labels: 4: Reviews Complete

#7318 Cypress/E2E: Fix plugin upload spec
  e2e/cypress/integration/system_console/plugin_upload_spec.js
Labels: 4: Reviews Complete

#7313 Cypress/E2E: Fix search filter edit spec
  e2e/cypress/integration/search_filter/edit_spec.js
  e2e/cypress/integration/search_filter/helpers.js
Labels: 4: Reviews Complete

#7215 [MM-20401] Migrate 'components/plugin_marketplace' module and associated tests to TypeScript
  actions/marketplace.ts
  components/plugin_marketplace/__snapshots__/marketplace_modal.test.tsx.snap
  components/plugin_marketplace/index.ts
  components/plugin_marketplace/marketplace_item/index.ts
  components/plugin_marketplace/marketplace_list/__snapshots__/marketplace_list.test.tsx.snap
  components/plugin_marketplace/marketplace_list/marketplace_list.test.tsx
  components/plugin_marketplace/marketplace_list/marketplace_list.tsx
  components/plugin_marketplace/marketplace_modal.test.tsx
  components/plugin_marketplace/marketplace_modal.tsx
Labels: 4: Reviews Complete

#7293 MM-30443 Add separate Group unread channels separately setting for new sidebar
  components/sidebar/sidebar_category/index.ts
  components/sidebar/sidebar_channel_list/index.ts
  components/sidebar/sidebar_channel_list/sidebar_channel_list.test.tsx
  components/sidebar/sidebar_channel_list/sidebar_channel_list.tsx
  components/sidebar/unread_channels/unread_channels.tsx
  components/user_settings/sidebar/show_unreads_category/index.ts
  components/user_settings/sidebar/show_unreads_category/show_unreads_category.tsx
  components/user_settings/sidebar/user_settings_sidebar.tsx
  e2e/cypress/integration/channel_sidebar/group_unreads_seperately_spec.js
  e2e/cypress/integration/channel_sidebar/unread_filter_spec.js
  i18n/en.json
  package-lock.json
  package.json
  sass/layout/_sidebar-left.scss
  selectors/views/channel_sidebar.test.js
  selectors/views/channel_sidebar.ts
Labels: 4: Reviews Complete

#7263 MM-29089: Disable Admin Filter
  components/admin_console/admin_console.tsx
  components/admin_console/admin_definition.jsx
  components/admin_console/schema_admin_settings.jsx
Labels: 4: Reviews Complete

#7068 [MM-27927] - Add limit for visible DMs and DM sorting menu
  actions/user_actions.jsx
  actions/user_actions.test.js
  components/sidebar/sidebar_category/__snapshots__/sidebar_category.test.tsx.snap
  components/sidebar/sidebar_category/sidebar_category.test.tsx
  components/sidebar/sidebar_category/sidebar_category.tsx
  components/sidebar/sidebar_category/sidebar_category_sorting_menu/index.ts
  components/sidebar/sidebar_category/sidebar_category_sorting_menu/sidebar_category_sorting_menu.tsx
  components/sidebar/sidebar_channel_list/sidebar_channel_list.tsx
  components/sidebar/sidebar_menu/sidebar_menu.tsx
  components/user_settings/sidebar/user_settings_sidebar.tsx
  components/widgets/menu/menu_items/menu_item.scss
  components/widgets/menu/menu_items/submenu_item.test.tsx
  components/widgets/menu/menu_items/submenu_item.tsx
  i18n/en.json
  package-lock.json
  package.json
  sass/layout/_sidebar-left.scss
Labels: 4: Reviews Complete

#7333 Cypress/E2E: Fixed at mention notifications TM4J keys
  e2e/cypress/integration/messaging/at_mentions_spec.js
Labels: 4: Reviews Complete

#7296 [MM-29675] - Add sorting for channels in categories
  components/sidebar/sidebar_category/sidebar_category_menu/__snapshots__/sidebar_category_menu.test.tsx.snap
  components/sidebar/sidebar_category/sidebar_category_menu/index.ts
  components/sidebar/sidebar_category/sidebar_category_menu/sidebar_category_menu.test.tsx
  components/sidebar/sidebar_category/sidebar_category_menu/sidebar_category_menu.tsx
  i18n/en.json
  package-lock.json
  sass/layout/_sidebar-left.scss
Labels: 4: Reviews Complete, AutoMerge

#7247 [MM-31364] - Remove whats new modal
  components/sidebar/sidebar.tsx
  components/sidebar/sidebar_whats_new_modal/index.ts
  components/sidebar/sidebar_whats_new_modal/sidebar_whats_new_modal.scss
  components/sidebar/sidebar_whats_new_modal/sidebar_whats_new_modal.tsx
  e2e/cypress/support/api/preference.d.ts
  e2e/cypress/support/api/preference.js
  e2e/cypress/support/api/user.d.ts
  e2e/cypress/support/api/user.js
  e2e/cypress/support/index.js
  e2e/cypress/support/ui/modal.d.ts
  e2e/cypress/support/ui/modal.js
  i18n/en.json
  i18n/es.json
  i18n/ja.json
  i18n/nl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/tr.json
  i18n/zh-CN.json
  i18n/zh-TW.json
  images/whats-new-1.5.gif
Labels: 4: Reviews Complete, AutoMerge

#7267 [MM-28188] e2e cypress tests for subpath
  e2e/README-Subpath.md
  e2e/cypress.json
  e2e/cypress/integration/subpath/subpath_channel_routing_spec.js
  e2e/cypress/integration/subpath/subpath_dm_search_spec.js
  e2e/cypress/support/api/system.d.ts
  e2e/cypress/support/api/system.js
Labels: 4: Reviews Complete, AutoMerge

#7304 [MM-31515] - Call /cloud/subscription endpoint only when cloud is enabled
  components/announcement_bar/cloud_announcement_bar/user_limit_announcement_bar.tsx
  components/announcement_bar/payment_announcement_bar/payment_announcement_bar.tsx
  components/common/hocs/cloud/with_get_cloud_subcription.test.tsx
  components/common/hocs/cloud/with_get_cloud_subcription.tsx
  components/invitation_modal/__snapshots__/invitation_modal.test.jsx.snap
  components/invitation_modal/invitation_modal_guest_step/__snapshots__/invitation_modal_guests_step.test.jsx.snap
  components/invitation_modal/invitation_modal_guest_step/invitation_modal_guests_step.jsx
  components/invitation_modal/invitation_modal_members_step/__snapshots__/invitation_modal_members_step.test.jsx.snap
  components/invitation_modal/invitation_modal_members_step/invitation_modal_members_step.jsx
  components/main_menu/__snapshots__/main_menu.test.jsx.snap
  components/main_menu/main_menu.jsx
  components/main_menu/main_menu.test.jsx
  plugins/test/main_menu_action.test.jsx
Labels: 4: Reviews Complete, QA Review Done

#7195 [MM-30851/MM-31405] Replace ExperimentalChannelSidebarOrganization with EnableLegacySidebar
  actions/command.test.js
  actions/user_actions.jsx
  actions/views/channel.test.js
  components/admin_console/admin_definition.jsx
  components/channel_header/__snapshots__/channel_header.test.jsx.snap
  components/channel_header/channel_header.js
  components/channel_header/index.js
  components/needs_team/index.ts
  components/user_settings/sidebar/__snapshots__/user_settings_sidebar.test.tsx.snap
  components/user_settings/sidebar/index.ts
  components/user_settings/sidebar/user_settings_sidebar.test.tsx
  components/user_settings/sidebar/user_settings_sidebar.tsx
  e2e/cypress/integration/account_settings/sidebar/channel_switcher_ui_spec.js
  e2e/cypress/integration/channel/archived_channels_spec.js
  e2e/cypress/integration/channel_sidebar/category_collapsing_spec.js
  e2e/cypress/integration/channel_sidebar/category_muting_spec.js
  e2e/cypress/integration/channel_sidebar/channel_sidebar_spec.js
  e2e/cypress/integration/channel_sidebar/custom_categories_spec.js
  e2e/cypress/integration/channel_sidebar/dm_category_spec.js
  e2e/cypress/integration/channel_sidebar/drag_and_drop_spec.js
  e2e/cypress/integration/channel_sidebar/history_channel_switcher_spec.js
  e2e/cypress/integration/channel_sidebar/hotkeys_spec.js
  e2e/cypress/integration/channel_sidebar/legacy_sidebar_settings_spec.js
  e2e/cypress/integration/channel_sidebar/new_category_badge_spec.js
  e2e/cypress/integration/channel_sidebar/new_channel_dropdown_spec.js
  e2e/cypress/integration/channel_sidebar/sidebar_channel_menu_spec.js
  e2e/cypress/integration/channel_sidebar/unread_filter_spec.js
  e2e/cypress/integration/enterprise/cloud/onboarding/cloud_sysadmin_onboarding_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/guest_identification_ui_spec.js
  e2e/cypress/integration/websocket/channel_created/new_sidebar_spec.js
  e2e/cypress/integration/websocket/handle_new_post_spec.js
  e2e/cypress/integration/websocket/handle_removed_user/new_sidebar_spec.js
  e2e/cypress/support/api/cloud_default_config.json
  e2e/cypress/support/api/on_prem_default_config.json
  i18n/en.json
  package-lock.json
  package.json
Labels: 4: Reviews Complete

#7169 [MM-30444][MM-23459][MM-31775] - Style sidebar navigator and team icons
  components/admin_console/permission_schemes_settings/permission_team_scheme_settings/team_in_list/__snapshots__/team_in_list.test.jsx.snap
  components/admin_console/permission_schemes_settings/permission_team_scheme_settings/team_in_list/team_in_list.jsx
  components/admin_console/system_user_detail/team_list/team_row.tsx
  components/admin_console/team_channel_settings/team/details/__snapshots__/team_profile.test.jsx.snap
  components/admin_console/team_channel_settings/team/details/team_profile.jsx
  components/admin_console/team_channel_settings/team/list/__snapshots__/team_list.test.tsx.snap
  components/admin_console/team_channel_settings/team/list/__snapshots__/team_row.test.tsx.snap
  components/admin_console/team_channel_settings/team/list/team_list.tsx
  components/admin_console/team_channel_settings/team/list/team_row.tsx
  components/legacy_team_sidebar/components/team_button.tsx
  components/legacy_team_sidebar/legacy_team_sidebar_controller.tsx
  components/sidebar/__snapshots__/sidebar.test.tsx.snap
  components/sidebar/channel_filter/__snapshots__/channel_filter.test.tsx.snap
  components/sidebar/channel_filter/channel_filter.tsx
  components/sidebar/channel_navigator/channel_navigator.tsx
  components/sidebar/channel_navigator/index.ts
  components/sidebar/sidebar.tsx
  components/team_selector_modal/team_selector_modal.tsx
  components/widgets/team_icon/__snapshots__/team_icon.test.tsx.snap
  components/widgets/team_icon/team_icon.scss
  components/widgets/team_icon/team_icon.stories.js
  components/widgets/team_icon/team_icon.test.tsx
  components/widgets/team_icon/team_icon.tsx
  i18n/de.json
  i18n/en.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/tr.json
  i18n/zh-CN.json
  i18n/zh-TW.json
  sass/components/_badge.scss
  sass/layout/_sidebar-left.scss
  sass/layout/_team-button.scss
  sass/layout/_team-sidebar.scss
Labels: 4: Reviews Complete

#7288 Cover with cypress tests server search display scenarios part 1
  e2e/cypress/integration/search/post_search_display_spec.js
Labels: 3: QA Review

#7342 MM-32099 Don't change category sorting method to manual when dragging and dropping
  package-lock.json
  package.json
Labels: 4: Reviews Complete, QA Review Done

#7030 Moving header icons to the left of the header aside the channel description
  components/channel_header/__snapshots__/channel_header.test.jsx.snap
  components/channel_header/channel_header.js
  components/channel_header/components/__snapshots__/header_icon_wrapper.test.js.snap
  components/channel_header/components/header_icon_wrapper.js
  components/popover_list_members/__snapshots__/popover_list_members.test.jsx.snap
  components/popover_list_members/popover_list_members.jsx
  i18n/en.json
  plugins/channel_header_plug/__snapshots__/channel_header_plug.test.tsx.snap
  sass/components/_channel-header__icon.scss
  sass/components/_popover.scss
  sass/layout/_headers.scss
Labels: 4: Reviews Complete

#7335 Cypress/E2E: Fixed plugin/marketplace TM4J keys
  e2e/cypress/integration/plugins/marketplace/marketplace_spec.js
Labels: 4: Reviews Complete

#7334 Cypress/E2E: Fixed channel moderation TM4J keys
  e2e/cypress/integration/enterprise/system_console/channel_moderation/channel_mentions_spec.js
  e2e/cypress/integration/enterprise/system_console/channel_moderation/create_posts_spec.js
  e2e/cypress/integration/enterprise/system_console/channel_moderation/higher_scoped_scheme_spec.js
  e2e/cypress/integration/enterprise/system_console/channel_moderation/manage_members_spec.js
  e2e/cypress/integration/enterprise/system_console/channel_moderation/post_reactions_spec.js
Labels: 4: Reviews Complete, AutoMerge

#7332 Cypress/E2E: Fixed some guest account specs TM4J keys
  e2e/cypress/integration/enterprise/guest_accounts/guest_experience_ui_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/guest_identification_ui_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/member_invitation_ui_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/system_console_manage_guest_spec.js
  e2e/cypress/integration/team_settings/invite_members_spec.js
Labels: 4: Reviews Complete, AutoMerge

#7343 [MM-30806] Account Settings - Setting to limit number of DMs/GMs shown in new sidebar
  components/user_settings/sidebar/limit_visible_gms_dms/index.ts
  components/user_settings/sidebar/limit_visible_gms_dms/limit_visible_gms_dms.tsx
  components/user_settings/sidebar/user_settings_sidebar.tsx
  i18n/en.json
Labels: 4: Reviews Complete, CherryPick/Approved

#7340 Update compass icon font
  fonts/compass-icons/compass-icons.eot
  fonts/compass-icons/compass-icons.svg
  fonts/compass-icons/compass-icons.ttf
  fonts/compass-icons/compass-icons.woff
  fonts/compass-icons/compass-icons.woff2
  sass/base/_compass-icons.scss
Labels: 4: Reviews Complete, QA Review Done, Setup Cloud Test Server

#7321 MM 31935 - fill issue detail in contact-us form
  components/admin_console/billing/billing_subscriptions.tsx
  selectors/cloud.ts
Labels: QA Review Done

#7276 MM-30053/GH-16204 Clear selection in channel switcher on backspace
  components/suggestion/suggestion_box.jsx
  components/suggestion/suggestion_box.test.jsx
Labels: 4: Reviews Complete, QA Review Done

#7210 MM-20440 edit oauth app typescript migration
  components/integrations/edit_oauth_app/__snapshots__/edit_oauth_app.test.tsx.snap
  components/integrations/edit_oauth_app/edit_oauth_app.test.tsx
  components/integrations/edit_oauth_app/edit_oauth_app.tsx
  components/integrations/edit_oauth_app/index.js
  components/integrations/edit_oauth_app/index.ts
Labels: 4: Reviews Complete

#7346 Cypress/E2E: Update remaining tests for the new config of sidebar organization
  e2e/cypress/integration/bot_accounts/in_lists_spec.js
  e2e/cypress/integration/channel/archived_channels_spec.js
  e2e/cypress/integration/channel_sidebar/dm_gm_behaviour_spec.js
  e2e/cypress/integration/channel_sidebar/group_unreads_seperately_spec.js
  e2e/cypress/integration/channel_sidebar/sidebar_category_menu_spec.js
  e2e/cypress/integration/team_settings/teams_spec.js
Labels: 4: Reviews Complete

#7249 [MM-20443/GH-16131] - Migrate 'components/integrations/installed_commands'  to TypeScript
  components/integrations/installed_commands/index.ts
  components/integrations/installed_commands/installed_commands.tsx
Labels: 4: Reviews Complete

#7297 Convert command_provider to typescript
  components/suggestion/command_provider.test.js
  components/suggestion/command_provider/__snapshots__/command_provider.test.tsx.snap
  components/suggestion/command_provider/command_provider.test.tsx
  components/suggestion/command_provider/command_provider.tsx
  components/suggestion/suggestion_box.jsx
  components/textbox/textbox.tsx
  utils/constants.jsx
Labels: 2: Dev Review

#7350 Fix for failing T2060
  e2e/cypress/integration/account_settings/general/nickname_spec.js
  e2e/cypress/integration/system_console/user_management_spec.js
Labels: 4: Reviews Complete

#7228 [GH-16537][MM-31148] Add Formatting Shortcut Keys to Shortcut modal
  components/shortcuts_modal.jsx
  i18n/en.json
Labels: 4: Reviews Complete

#7349 [MM-32173] Hide the experimental settings when the legacy sidebar is disabled
  components/admin_console/admin_definition.jsx
  i18n/en.json
Labels: 4: Reviews Complete, CherryPick/Approved, QA Review Done, Setup Cloud Test Server

#7358 Automated cherry pick of #7349
  components/admin_console/admin_definition.jsx
  i18n/en.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7359 Promoting tests to prod from unstable - part II
  e2e/cypress/integration/files_and_attachments/youtube_video_spec.js
  e2e/cypress/integration/integrations/builtin_commands/groupmsg_command_spec.js
  e2e/cypress/integration/integrations/custom_slash_commands/custom_slash_commands_spec.js
  e2e/cypress/integration/integrations/custom_slash_commands/slash_commands_spec.js
  e2e/cypress/integration/integrations/incoming_webhook/long_url_embedded_image_spec.js
  e2e/cypress/integration/integrations/incoming_webhook/slack_formatting_spec.js
  e2e/cypress/integration/integrations/incoming_webhook/webhook_posts_when_creator_not_in_channel_spec.js
  e2e/cypress/integration/keyboard_shortcuts/backspace_spec.js
  e2e/cypress/integration/markdown/markdown_image_spec.js
  e2e/cypress/integration/messaging/autocomplete_spec.js
  e2e/cypress/integration/messaging/center_channel_rhs_overlap_spec.js
  e2e/cypress/integration/messaging/channel_and_posts_links_spec.js
  e2e/cypress/integration/messaging/direct_message_spec.js
  e2e/cypress/integration/messaging/header_not_cloud_spec.js
  e2e/cypress/integration/messaging/inline_markdown_image_link_open_link_spec.js
  e2e/cypress/integration/messaging/message_edit_post_clear_text_spec.js
  e2e/cypress/integration/messaging/message_ephemeral_spec.js
  e2e/cypress/integration/messaging/message_reply_part2_spec.js
  e2e/cypress/integration/messaging/message_with_gif_spec.js
  e2e/cypress/integration/modals/quick_switcher_spec.js
  e2e/cypress/integration/multi_team_and_dm/dm_more_searching_from_page_spec.js
  e2e/cypress/integration/multi_team_and_dm/dm_more_show_user_count_spec.js
  e2e/cypress/integration/multi_team_and_dm/multi_team_spec.js
  e2e/cypress/integration/multi_team_and_dm/town_square_not_marked_as_unread_spec.js
  e2e/cypress/integration/notifications/desktop_notifications_spec.js
  e2e/cypress/integration/notifications/direct_messages_do_not_add_indicator_spec.js
  e2e/cypress/integration/onboarding/tutorial_navigation_and_links_spec.js
  e2e/cypress/integration/search_autocomplete/users_spec.js
  e2e/cypress/integration/system_console/authentication/authentication_spec.js
  e2e/cypress/integration/system_console/environment_spec.js
  e2e/cypress/integration/team_settings/manage_members_spec.js
  e2e/cypress/integration/team_settings/teams_spec.js
  e2e/cypress/integration/toast/new_messages_toast_spec.js
Labels: 4: Reviews Complete

#7320 MM-29935 - update pricing visibility and legends
  components/admin_console/billing/plan_details.scss
  components/admin_console/billing/plan_details.tsx
  i18n/en.json
Labels: 4: Reviews Complete, QA Review Done

#7356 [MM-32193][MM-32178] Move transform for team sidebar button to anchor
  sass/layout/_sidebar-left.scss
  sass/layout/_team-sidebar.scss
Labels: 4: Reviews Complete, CherryPick/Approved, QA Review Done, Setup Cloud Test Server

#7357 fix mention badge styling
  components/legacy_team_sidebar/components/team_button.tsx
  sass/components/_badge.scss
  sass/layout/_sidebar-left.scss
  sass/layout/_team-sidebar.scss
Labels: 4: Reviews Complete, CherryPick/Approved, QA Review Done, Setup Cloud Test Server

#7369 Automated cherry pick of #7357
  components/legacy_team_sidebar/components/team_button.tsx
  sass/components/_badge.scss
  sass/layout/_sidebar-left.scss
  sass/layout/_team-sidebar.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7364 Cypress/E2E: Fix MM-T924 by creating enough users to page through
  e2e/cypress/integration/system_console/user_management_spec.js
  e2e/cypress/support/api/helpers.js
  e2e/cypress/support/api/user.d.ts
  e2e/cypress/support/api/user.js
Labels: 4: Reviews Complete

#7344 MM-32107 Add saml guest member test
  e2e/cypress/integration/enterprise/saml/saml_guest_member_spec.js
Labels: 4: Reviews Complete

#7367 MM-32197 Use other timestamps when autohiding DMs/GMs
  package-lock.json
  package.json
Labels: 4: Reviews Complete, CherryPick/Approved

#7361 Cypress/E2E: Promote tests to production
  e2e/cypress/integration/channel_sidebar/legacy_sidebar_settings_spec.js
  e2e/cypress/integration/enterprise/group_mentions/group_mentions_permissions_spec.js
  e2e/cypress/integration/enterprise/group_mentions/group_mentions_system_messages_spec.js
  e2e/cypress/integration/enterprise/ldap/ldap_guest_spec.js
  e2e/cypress/integration/enterprise/system_console/authentication/authentication2_spec.js
  e2e/cypress/integration/enterprise/system_console/authentication/authentication3_spec.js
  e2e/cypress/integration/enterprise/system_console/channel_members_spec.js
  e2e/cypress/integration/enterprise/system_console/channel_moderation/create_posts_spec.js
  e2e/cypress/integration/enterprise/system_console/channel_moderation/manage_members_spec.js
  e2e/cypress/integration/enterprise/system_console/channel_moderation/system_config_spec.js
  e2e/cypress/integration/enterprise/system_console/cluster_spec.js
  e2e/cypress/integration/enterprise/system_console/environment_spec.js
  e2e/cypress/integration/enterprise/system_console/limited_console_access_spec.js
  e2e/cypress/integration/enterprise/system_console/settings_spec.js
  e2e/cypress/integration/enterprise/system_console/system_scheme_permission_part2_spec.js
  e2e/cypress/integration/enterprise/system_console/team_scheme_permission_part2_spec.js
  e2e/cypress/integration/files_and_attachments/edit_message_with_attachment_spec.js
  e2e/cypress/integration/files_and_attachments/file_previews_1_spec.js
  e2e/cypress/integration/files_and_attachments/image_link_preview_new_window_spec.js
  e2e/cypress/integration/files_and_attachments/paste_image_spec.js
  e2e/cypress/integration/files_and_attachments/upload_files_not_cloud_spec.js
  e2e/cypress/integration/integrations/outgoing_webhook/regenerate_token_spec.js
  e2e/cypress/integration/integrations/poll_spec.js
  e2e/cypress/integration/mark_as_unread/mark_gm_as_unread_spec.js
  e2e/cypress/integration/messaging/long_draft_spec.js
  e2e/cypress/integration/notifications/ignore_channel_mentions_spec.js
  e2e/cypress/integration/search/post_search_display_spec.js
  e2e/cypress/integration/system_console/compliance/custom_terms_of_service_spec.js
Labels: 4: Reviews Complete

#7371 Automated cherry pick of #7367
  package-lock.json
  package.json
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7362 Cypress/E2E: fix MM-T1877, MM-T1878 and MM-T1880
  e2e/cypress/integration/bot_accounts/bot_api_spec.js
Labels: 4: Reviews Complete

#7366 [MM-32138] - Fix margin of history arrows without unread filter button
  sass/layout/_sidebar-left.scss
Labels: 2: Dev Review, CherryPick/Approved, QA Review Done, Setup Cloud Test Server

#7382 Automated cherry pick of #7366
  sass/layout/_sidebar-left.scss
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7172 15642 - Updating Add to channel modal
  components/add_groups_to_channel_modal/__snapshots__/add_groups_to_channel_modal.test.jsx.snap
  components/add_groups_to_team_modal/__snapshots__/add_groups_to_team_modal.test.jsx.snap
  components/add_users_to_team_modal/__snapshots__/add_users_to_team_modal.test.tsx.snap
  components/channel_invite_modal/__snapshots__/channel_invite_modal.test.tsx.snap
  components/channel_invite_modal/channel_invite_modal.tsx
  components/channel_selector_modal/__snapshots__/channel_selector_modal.test.tsx.snap
  components/more_direct_channels/__snapshots__/more_direct_channels.test.jsx.snap
  components/multiselect/__snapshots__/multiselect.test.tsx.snap
  components/multiselect/multiselect.tsx
  components/multiselect/multiselect_list.tsx
  components/team_selector_modal/__snapshots__/team_selector_modal.test.tsx.snap
  e2e/cypress/integration/channel_sidebar/sidebar_channel_menu_spec.js
  e2e/cypress/integration/enterprise/accessibility/accessibility_modals_dialogs_spec.js
  e2e/cypress/integration/enterprise/ldap/ldap_group_sync_spec.js
  e2e/cypress/integration/enterprise/system_console/limited_console_access_spec.js
  e2e/cypress/integration/messaging/dm_list_of_users_spec.js
  e2e/cypress/integration/messaging/focus_move_spec.js
  e2e/cypress/integration/messaging/group_message_spec.js
  e2e/cypress/integration/multi_team_and_dm/dm_more_searching_from_page_spec.js
  e2e/cypress/integration/multi_team_and_dm/dm_more_show_user_count_spec.js
  i18n/en.json
  sass/components/_channel-switcher.scss
  sass/components/_multi-select.scss
  sass/components/_react-select.scss
  sass/utils/_modifiers.scss
Labels: 3: QA Review, Setup Cloud Test Server

#7387 Quick fix for failing snapshot
  components/admin_console/system_roles/system_role/add_users_to_role_modal/__snapshots__/add_users_to_role_modal.test.tsx.snap
Labels: 4: Reviews Complete

#7348 [MM-32167] Alphabetical and recency sorted categories will now have the same drop behaviour as DMs
  components/sidebar/sidebar_category/__snapshots__/sidebar_category.test.tsx.snap
  components/sidebar/sidebar_category/sidebar_category.tsx
  components/sidebar/sidebar_channel/index.ts
  components/sidebar/sidebar_channel/sidebar_channel.test.tsx
  components/sidebar/sidebar_channel/sidebar_channel.tsx
  components/sidebar/unread_channels/unread_channels.tsx
  e2e/cypress/integration/bot_accounts/in_lists_spec.js
  sass/layout/_sidebar-left.scss
  selectors/views/channel_sidebar.ts
Labels: 4: Reviews Complete, CherryPick/Approved, QA Review Done, Setup Cloud Test Server

#7388 [MM-32167] Alphabetical and recency sorted categories will now have the same drop behaviour as DMs (#7348)
  components/sidebar/sidebar_category/__snapshots__/sidebar_category.test.tsx.snap
  components/sidebar/sidebar_category/sidebar_category.tsx
  components/sidebar/sidebar_channel/index.ts
  components/sidebar/sidebar_channel/sidebar_channel.test.tsx
  components/sidebar/sidebar_channel/sidebar_channel.tsx
  components/sidebar/unread_channels/unread_channels.tsx
  e2e/cypress/integration/bot_accounts/in_lists_spec.js
  sass/layout/_sidebar-left.scss
  selectors/views/channel_sidebar.ts
Labels: 4: Reviews Complete, AutoMerge

#7385 Cypress/E2E: Fix time out error on initial Cypress run against remote server
  e2e/cypress/plugins/external_request.js
  e2e/cypress/support/api/system.js
  e2e/cypress/support/api/user.js
  e2e/cypress/support/index.js
  e2e/cypress/support/task_commands.d.ts
  e2e/cypress/support/task_commands.js
Labels: 4: Reviews Complete

#7380 MM-32156 Load GMs for new sidebar correctly
  actions/user_actions.jsx
  actions/user_actions.test.js
  components/data_prefetch/data_prefetch.test.tsx
  components/data_prefetch/data_prefetch.tsx
  components/data_prefetch/index.ts
Labels: 4: Reviews Complete, AutoMerge, Changelog/Not Needed, CherryPick/Approved, Docs/Not Needed

#7394 Automated cherry pick of #7380
  actions/user_actions.jsx
  actions/user_actions.test.js
  components/data_prefetch/data_prefetch.test.tsx
  components/data_prefetch/data_prefetch.tsx
  components/data_prefetch/index.ts
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7262 [MM-30389] add signin_authentication spec
  e2e/cypress/integration/signin_authentication/authentication_spec.js
Labels: 4: Reviews Complete

#7286 Revert "Revert "MM-24072 - Position the autocomplete popover relative…
  components/__snapshots__/textbox.test.tsx.snap
  components/suggestion/at_mention_provider/at_mention_provider.jsx
  components/suggestion/channel_mention_provider.jsx
  components/suggestion/emoticon_provider.jsx
  components/suggestion/suggestion_box.jsx
  components/suggestion/suggestion_list.jsx
  sass/components/_modal.scss
  sass/components/_suggestion-list.scss
  tests/setup.js
  utils/constants.jsx
  utils/utils.jsx
  utils/utils.test.jsx
Labels: 4: Reviews Complete, Setup Cloud Test Server

#7363 Mm 20374 migrate get public link modal to typescript
  components/get_public_link_modal/__snapshots__/get_public_link_modal.test.tsx.snap
  components/get_public_link_modal/get_public_link_modal.test.tsx
  components/get_public_link_modal/get_public_link_modal.tsx
  components/get_public_link_modal/index.js
  components/get_public_link_modal/index.ts
Labels: 4: Reviews Complete

#7306 [Server #15623]: Migrate string-refs to functional ones.
  components/create_comment/create_comment.jsx
  components/create_comment/create_comment.test.jsx
Labels: 4: Reviews Complete

#7261 MM-31185 Added localization to date picker used when searching for posts around a given date with momentjs
  components/suggestion/search_date_suggestion/index.js
  components/suggestion/search_date_suggestion/search_date_suggestion.jsx
Labels: 4: Reviews Complete

#7372 [MM-29496, MM-29497] Update changeCSS() call to CSS variable for away…
  sass/components/_status-icon.scss
  utils/utils.jsx
Labels: 4: Reviews Complete, QA Review Done

#7331 Fix Embedded forms after refactor
  components/post_view/post_body_additional_content/post_body_additional_content.tsx
Labels: 2: Dev Review

#7311 [MM-31509] Updating server log instructions
  components/admin_console/server_logs/logs.tsx
  i18n/en.json
Labels: 3: QA Review

#7392 MM-32255:Hide PublicLinks section if restricted admin
  components/admin_console/admin_definition.jsx
Labels: 4: Reviews Complete, CherryPick/Approved

#7399 Cypress/E2E: fix TM4J keys for MM-T1767 to MM-T1769, MM-T1181 and MM-T1635
  e2e/cypress/integration/enterprise/system_console/authentication/authentication3_spec.js
  e2e/cypress/integration/enterprise/system_console/settings_spec.js
Labels: 4: Reviews Complete, AutoMerge

#7400 Cypress/E2E: Separate TM4J keys for team and enterprise of site statistics
  e2e/cypress/integration/enterprise/system_console/reporting/site_statistics_spec.js
  e2e/cypress/integration/system_console/reporting/site_statistics_te_spec.js
Labels: 4: Reviews Complete

#7375 Cypress/E2E: Improve E2E report
  e2e/save_report.js
  e2e/utils/report.js
  e2e/utils/test_cases.js
Labels: 4: Reviews Complete, AutoMerge

#7378 [MM-32189] Apps Modal UX: bold the select field name
  components/apps_form/apps_form_field/apps_form_select_field.tsx
Labels: 4: Reviews Complete

#7379 Campaign/applytheme sidebar header text color
  sass/layout/_navigation.scss
  sass/layout/_team-button.scss
  sass/responsive/_mobile.scss
  utils/utils.jsx
Labels: 4: Reviews Complete

#7373 Campaign/applytheme center channel bg
  sass/base/_structure.scss
  sass/components/_forms.scss
  sass/components/_modal.scss
  sass/components/_popover.scss
  sass/components/_post.scss
  sass/components/_scrollbar.scss
  sass/layout/_sidebar-menu.scss
  utils/utils.jsx
Labels: 4: Reviews Complete

#7404 Cypress/E2E: Fix for failed e2e tests
  e2e/cypress/integration/archived_channel/archive_channel_operations_spec.js
  e2e/cypress/integration/archived_channel/post_menu_spec.js
  e2e/cypress/integration/enterprise/group_mentions/group_mentions_permissions_spec.js
  e2e/cypress/integration/messaging/reactions_spec.js
  e2e/cypress/integration/multi_team_and_dm/gm_header_spec.js
Labels: 4: Reviews Complete

#7396 MM-31391: Add max connection idle timeout to config
  components/admin_console/__snapshots__/database_settings.test.jsx.snap
  components/admin_console/admin_definition.jsx
  components/admin_console/database_settings.jsx
  components/admin_console/database_settings.test.jsx
  i18n/en.json
Labels: 4: Reviews Complete, Do Not Merge/Awaiting PR

#7374 [MM-29493, MM-29494] Migrate changeCSS() to CSS variable in utils/ut…
  sass/components/_status-icon.scss
  utils/utils.jsx
Labels: 4: Reviews Complete

#7329 MM-31993: Add flag to disable gossip compression
  components/admin_console/__snapshots__/cluster_settings.test.jsx.snap
  components/admin_console/admin_definition.jsx
  components/admin_console/cluster_settings.jsx
  components/admin_console/cluster_settings.test.jsx
  e2e/cypress/integration/enterprise/system_console/cluster_spec.js
  i18n/en.json
Labels: 4: Reviews Complete

#7330 Migrate Plugin Marketplace to TypeScript
  actions/marketplace.ts
  components/plugin_marketplace/__snapshots__/marketplace_modal.test.tsx.snap
  components/plugin_marketplace/index.ts
  components/plugin_marketplace/marketplace_item/__snapshots__/marketplace_item.test.tsx.snap
  components/plugin_marketplace/marketplace_item/index.ts
  components/plugin_marketplace/marketplace_item/marketplace_item.test.tsx
  components/plugin_marketplace/marketplace_item/marketplace_item.tsx
  components/plugin_marketplace/marketplace_list/__snapshots__/marketplace_list.test.tsx.snap
  components/plugin_marketplace/marketplace_list/marketplace_list.test.tsx
  components/plugin_marketplace/marketplace_list/marketplace_list.tsx
  components/plugin_marketplace/marketplace_list/navigation_row/__snapshots__/navigation_row.test.tsx.snap
  components/plugin_marketplace/marketplace_list/navigation_row/index.ts
  components/plugin_marketplace/marketplace_list/navigation_row/navigation_button.tsx
  components/plugin_marketplace/marketplace_list/navigation_row/navigation_row.test.tsx
  components/plugin_marketplace/marketplace_list/navigation_row/navigation_row.tsx
  components/plugin_marketplace/marketplace_modal.test.tsx
  components/plugin_marketplace/marketplace_modal.tsx
  package-lock.json
  package.json
Labels: 4: Reviews Complete

#7414 Automated cherry pick of #7392
  components/admin_console/admin_definition.jsx
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7355 MM-31914 , MM-31898 - hook up license renewal button; update banners
  components/announcement_bar/__snapshots__/text_dismissable_bar.test.jsx.snap
  components/announcement_bar/cloud_announcement_bar/user_limit_announcement_bar.tsx
  components/announcement_bar/configuration_bar/__snapshots__/configuration_bar.test.tsx.snap
  components/announcement_bar/configuration_bar/configuration_bar.tsx
  components/announcement_bar/default_announcement_bar/announcement_bar.tsx
  components/announcement_bar/no_internet_connection/no-internet-connection-svg.tsx
  components/announcement_bar/no_internet_connection/no_internet_connection.scss
  components/announcement_bar/no_internet_connection/no_internet_connection.tsx
  components/announcement_bar/payment_announcement_bar/payment_announcement_bar.tsx
  components/announcement_bar/renewal_link/index.ts
  components/announcement_bar/renewal_link/renewal_link.tsx
  components/announcement_bar/text_dismissable_bar.jsx
  i18n/en.json
  images/icons/success-icon.svg
  images/icons/warning-icon.svg
  package-lock.json
  package.json
  sass/base/_structure.scss
  sass/components/_announcement-bar.scss
  sass/layout/_legacy-sidebar-left.scss
  sass/layout/_sidebar-left.scss
  sass/layout/_sidebar-right.scss
  sass/layout/_team-sidebar.scss
  sass/responsive/_mobile.scss
  sass/routes/_admin-console.scss
  sass/routes/_signup.scss
  sass/utils/_variables.scss
  utils/constants.jsx
Labels: 4: Reviews Complete, CherryPick/Candidate, QA Review Done, Setup Cloud Test Server

#7406 MM-29694: Migrate changeCSS() to CSS variable in utils/utils.jsx, ln. 689
  sass/components/_post.scss
  utils/utils.jsx
Labels: 4: Reviews Complete

#7391 MM-30540 - display renewal panel in license screen
  components/admin_console/license_settings/__snapshots__/license_settings.test.jsx.snap
  components/admin_console/license_settings/license_settings.jsx
  components/admin_console/license_settings/license_settings.test.jsx
  components/admin_console/license_settings/renew_license_card/renew_license_card.scss
  components/admin_console/license_settings/renew_license_card/renew_license_card.tsx
  components/announcement_bar/renewal_link/renewal_link.tsx
  i18n/en.json
Labels: 4: Reviews Complete, CherryPick/Approved, QA Review Done, Setup Cloud Test Server

#7405 [MM-29388][MM-29387]Campaign/applytheme sidebar bg
  sass/responsive/_mobile.scss
  utils/utils.jsx
Labels: 4: Reviews Complete, QA Review Done

#7325 MM-31735 - ReDisplay OpenID Connect
  components/admin_console/admin_definition.jsx
  components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.jsx.snap
  components/admin_console/admin_sidebar/admin_sidebar.jsx
  components/admin_console/openid_convert/__snapshots__/openid_convert.test.tsx.snap
  components/admin_console/openid_convert/openid_convert.tsx
  e2e/cypress/integration/enterprise/system_console/openid/openid_spec.js
Labels: 2: Dev Review, 3: QA Review

#7390 Cypress/E2E: Remove duplicate MM-T3294, fix MM-T1253 and fix/reorganize other keyboard shortcuts tests
  e2e/cypress/integration/keyboard_shortcuts/ctrl_cmd_k_unreads_spec.js
  e2e/cypress/integration/keyboard_shortcuts/ctrl_cmd_shift_m_spec.js
  e2e/cypress/integration/keyboard_shortcuts/keyboard_shortcuts_one_spec.js
  e2e/cypress/integration/messaging/ctrl_cmd_k_open_dm_with_mouse_spec.js
Labels: 4: Reviews Complete, CherryPick/Approved

#7412 Cypress/E2E: Fix e2e for sidebar channels
  e2e/cypress/integration/channel_sidebar/category_collapsing_spec.js
  e2e/cypress/integration/channel_sidebar/dm_category_spec.js
  e2e/cypress/integration/channel_sidebar/unread_filter_spec.js
Labels: 4: Reviews Complete, CherryPick/Approved

#7418 Automated cherry pick of #7412
  e2e/cypress/integration/channel_sidebar/category_collapsing_spec.js
  e2e/cypress/integration/channel_sidebar/dm_category_spec.js
  e2e/cypress/integration/channel_sidebar/unread_filter_spec.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7416 Cypress/E2E: Fix for more channels and auth specs
  e2e/cypress/integration/channel/more_public_channels_spec.js
  e2e/cypress/integration/enterprise/system_console/authentication/authentication2_spec.js
  e2e/cypress/integration/enterprise/system_console/cluster_spec.js
Labels: 4: Reviews Complete, CherryPick/Approved

#7398 Cypress/E2E: Fix failed tests due to recent change in add users modal
  e2e/cypress/integration/account_settings/general/nickname_spec.js
  e2e/cypress/integration/channel_settings/add_users_to_channel_spec.js
  e2e/cypress/integration/channel_sidebar/sidebar_channel_menu_spec.js
  e2e/cypress/integration/enterprise/accessibility/accessibility_modals_dialogs_spec.js
  e2e/cypress/integration/enterprise/ldap/ldap_group_sync_spec.js
  e2e/cypress/integration/notifications/ignore_channel_mentions_spec.js
Labels: 4: Reviews Complete, CherryPick/Approved

#7402 Cypress/E2E: Promote tests with 23 TM4J test cases
  e2e/cypress/integration/bot_accounts/bot_api_spec.js
  e2e/cypress/integration/enterprise/ldap_group/group_mentions_spec.js
  e2e/cypress/integration/system_console/user_management_spec.js
Labels: 4: Reviews Complete, CherryPick/Approved

#7415 Cypress/E2E: Fix and reorganize tests for custom emojis
  e2e/cypress/integration/emoji/custom_emoji_1_spec.js
  e2e/cypress/integration/emoji/custom_emoji_2_spec.js
  e2e/cypress/integration/emoji/custom_emoji_3_spec.js
  e2e/cypress/integration/emoji/custom_emoji_spec.js
  e2e/cypress/integration/emoji/helpers.js
Labels: 4: Reviews Complete, AutoMerge, CherryPick/Approved

#7419 Automated cherry pick of #7402
  e2e/cypress/integration/enterprise/ldap_group/group_mentions_spec.js
  e2e/cypress/integration/system_console/user_management_spec.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7413 MM 31192 - license renewal telemetry
  components/admin_console/license_settings/renew_license_card/renew_license_card.tsx
  components/announcement_bar/configuration_bar/__snapshots__/configuration_bar.test.tsx.snap
  components/announcement_bar/configuration_bar/configuration_bar.tsx
  components/announcement_bar/renewal_link/renewal_link.tsx
Labels: 2: Dev Review, CherryPick/Approved

#7422 Automated cherry pick of #7413
  components/admin_console/license_settings/renew_license_card/renew_license_card.tsx
  components/announcement_bar/configuration_bar/__snapshots__/configuration_bar.test.tsx.snap
  components/announcement_bar/configuration_bar/configuration_bar.tsx
  components/announcement_bar/renewal_link/renewal_link.tsx
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7324 [MM-22369] Filter out ldap group sync teams when adding a team to a user
  components/admin_console/system_user_detail/system_user_detail.tsx
  components/team_selector_modal/__snapshots__/team_selector_modal.test.tsx.snap
  components/team_selector_modal/team_selector_modal.test.tsx
  components/team_selector_modal/team_selector_modal.tsx
Labels: 4: Reviews Complete, AutoMerge

#7386 [MM-29108] Simplifies emoji reaction animation
  components/post_view/reaction/__snapshots__/reaction.test.jsx.snap
  components/post_view/reaction/index.ts
  components/post_view/reaction/reaction.test.jsx
  components/post_view/reaction/reaction.tsx
  components/post_view/reaction_list/index.ts
  components/post_view/reaction_list/reaction_list.tsx
  components/post_view/reaction_list/reactions_list.test.jsx
Labels: 4: Reviews Complete

#7421 Cypress/E2E: Fix tests for bots in list and in sidebar
  e2e/cypress/integration/bot_accounts/in_lists_spec.js
  e2e/cypress/integration/bot_accounts/sidebar_display_spec.js
Labels: 4: Reviews Complete

#7424 Cypress/E2E: Fix tests for archived channels
  e2e/cypress/integration/channel/archived_channels_1_spec.js
  e2e/cypress/integration/channel/archived_channels_2_spec.js
Labels: 4: Reviews Complete

#7326 MM-31646: Update Office instructions
  components/admin_console/admin_definition.jsx
  i18n/en.json
Labels: 4: Reviews Complete, AutoMerge
