Repository mattermost/mattermost-webapp, pull requests merged in 2021-06, with the labels that each got.

#8165 MM-T2369 : Aspect Ratio is preserved in RHS
  e2e/cypress/integration/scroll/image_aspect_ratio_spec.js
Labels: 4: Reviews Complete, release-note-none

#8184 Translations update from Weblate
  i18n/bg.json
  i18n/de.json
  i18n/es.json
  i18n/fr.json
  i18n/hu.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
  i18n/zh-CN.json
Labels: 2: Dev Review, 3: QA Review, release-note-none

#8173 Fixes: position of clear custom status icon
  components/custom_status/custom_status.scss
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#8133 ref: migrate announcement_bar to ts
  components/announcement_bar/__snapshots__/announcement_bar.test.tsx.snap
  components/announcement_bar/__snapshots__/text_dismissable_bar.test.tsx.snap
  components/announcement_bar/announcement_bar.test.tsx
  components/announcement_bar/announcement_bar_controller.tsx
  components/announcement_bar/configuration_bar/configuration_bar.tsx
  components/announcement_bar/default_announcement_bar/announcement_bar.tsx
  components/announcement_bar/index.ts
  components/announcement_bar/text_dismissable_bar.test.tsx
  components/announcement_bar/text_dismissable_bar.tsx
  components/warn_metric_ack_modal/warn_metric_ack_modal.test.tsx
  components/warn_metric_ack_modal/warn_metric_ack_modal.tsx
Labels: 4: Reviews Complete, release-note-none

#8138 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 4: Reviews Complete, release-note-none

#8157 [MM-35922] Fixed a couple style issues with the sidebar category headers on drag
  components/sidebar/sidebar_category_header.tsx
  sass/layout/_sidebar-left.scss
Labels: 4: Reviews Complete, AutoMerge, CherryPick/Approved, QA Review Done, Setup Cloud Test Server, release-note-none

#8177 Fixed custom status issues
  components/post_view/post/__snapshots__/post.test.js.snap
  components/post_view/post/post.jsx
  components/rhs_comment/__snapshots__/rhs_comment.test.jsx.snap
  components/rhs_comment/rhs_comment.jsx
  components/rhs_root_post/__snapshots__/rhs_root_post.test.jsx.snap
  components/rhs_root_post/rhs_root_post.jsx
Labels: 4: Reviews Complete, AutoMerge, CherryPick/Approved, Setup Cloud Test Server, release-note

#8155 MM - 35835 show cc info in purchase modal
  components/admin_console/billing/payment_details.tsx
  components/admin_console/billing/payment_info_display.tsx
  components/common/radio_group.tsx
  components/purchase_modal/index.ts
  components/purchase_modal/purchase.scss
  components/purchase_modal/purchase_modal.tsx
  i18n/en.json
  sass/base/_css_variables.scss
Labels: 2: Dev Review, QA Deferred

#8188 MM-36126 - prevent purchase modal Object.keys invocation with null value
  components/purchase_modal/purchase_modal.tsx
Labels: 2: Dev Review, 3: QA Review

#8194 Translations update from Weblate
  i18n/en_AU.json
  i18n/fr.json
  i18n/nl.json
  i18n/sv.json
  i18n/tr.json
Labels: 2: Dev Review, 3: QA Review, release-note-none

#7751 Changed the api call for the remove recent custom status API
  packages/mattermost-redux/src/client/client4.ts
Labels: 4: Reviews Complete, release-note-none

#8190 added `align-items: center` and increased `line-height` on the `span`
  sass/layout/_headers.scss
Labels: 2: Dev Review, 3: QA Review, Setup Cloud Test Server, release-note-none

#8196 Lock CI from /release-5.36
  .circleci/config.yml
  .gitlab-ci.yml
Labels: release-note-none

#8195 MM-36172 - purchase modal empty address issue
  components/purchase_modal/purchase_modal.tsx
Labels: 2: Dev Review, QA Deferred, Setup Cloud + CWS Test Server, release-note-none

#8156 Cleanup store initialization
  package-lock.json
  package.json
  packages/mattermost-redux/src/store/configureStore.dev.ts
  packages/mattermost-redux/src/store/configureStore.ts
  packages/mattermost-redux/src/store/helpers.ts
  packages/mattermost-redux/src/store/index.ts
  packages/mattermost-redux/src/store/middleware.ts
  packages/mattermost-redux/src/store/reducer_registry.ts
Labels: 4: Reviews Complete, release-note-none

#8176 MM-T2372 Deleting: Thread does not move when deleting post
  e2e/cypress/integration/scroll/deleting_scroll_spec.js
Labels: 3: QA Review, release-note-none

#8175 tests/MM-T947 : When deactivating users in the System Console, email address should not disappear
  e2e/cypress/integration/system_console/user_management/users_deactivation_spec.js
Labels: 4: Reviews Complete, release-note-none

#8178 tests/MM-T1321 : WebApp: Truncated Numbered List on Chat History Panel
  e2e/cypress/integration/messaging/message_bullets_spec.js
Labels: 4: Reviews Complete, release-note-none

#8202 Cypress/E2E : Fixed Category sortingTest Case
  e2e/cypress/integration/channel_sidebar/category_sorting_spec.js
Labels: 4: Reviews Complete, release-note-none

#8179 [MM-T1282] Add e2e test coverage for default behaviour when an empty site name is configured
  e2e/cypress/integration/system_console/site_configuration/customization_spec.js
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#8182 MM-36035 - Removing status from bot posts
  components/profile_popover/profile_popover.jsx
Labels: 4: Reviews Complete, AutoMerge, CherryPick/Approved, release-note-none

#8206 Automated cherry pick of #8182
  components/profile_popover/profile_popover.jsx
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8212 Automated cherry pick of #8092
  components/emoji_picker/emoji_picker_overlay.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8168 tests/MM-T1128 : Announcement Banner - Dismissible banner shows long text truncated
  e2e/cypress/integration/system_console/site_configuration/announcement_banner_spec.js
Labels: 4: Reviews Complete, release-note-none

#8181 tests/MM-T2374 : System Messages
  e2e/cypress/integration/scroll/channel_scroll_spec.js
Labels: 4: Reviews Complete, release-note-none

#8185 tests/CTRL+CMD+K : Unread Channels and input field focus
  e2e/cypress/integration/keyboard_shortcuts/ctrl_cmd_k_unreads_spec.js
Labels: 4: Reviews Complete, release-note-none

#8217 Translations update from Weblate
  i18n/bg.json
  i18n/ja.json
  i18n/nl.json
  i18n/tr.json
Labels: 2: Dev Review, 3: QA Review, release-note-none

#6667 [GH-15803] fix: migrate this.ref.dotMenu to React.createRef
  components/post_view/post_info/post_info.tsx
Labels: AutoMerge, Hacktoberfest, Lifecycle/1:stale, QA Review Done, hacktoberfest-accepted, release-note-none

#8145 [MM-35669] - Align channel globe icons with sidebar navigator icons
  sass/components/_badge.scss
  sass/layout/_headers.scss
  sass/layout/_sidebar-left.scss
Labels: 4: Reviews Complete, QA Review Done, Setup Cloud Test Server, release-note-none

#8174 tests/MM-T925 : Users - Profile image on User Configuration page is round
  e2e/cypress/integration/system_console/user_management/users_spec.js
Labels: 4: Reviews Complete, QA Review Done, release-note-none

#8149 MM-35717: CRT, new messages line
  actions/new_post.ts
  actions/post_actions.jsx
  actions/views/threads.ts
  actions/websocket_actions.jsx
  components/needs_team/index.ts
  components/needs_team/needs_team.test.tsx
  components/needs_team/needs_team.tsx
  components/threading/global_threads/global_threads.tsx
  components/threading/global_threads/thread_menu/thread_menu.test.tsx
  components/threading/global_threads/thread_menu/thread_menu.tsx
  components/threading/thread_viewer/index.ts
  components/threading/thread_viewer/thread_viewer.scss
  components/threading/thread_viewer/thread_viewer.test.tsx
  components/threading/thread_viewer/thread_viewer.tsx
  reducers/views/threads.ts
  selectors/views/threads.test.ts
  selectors/views/threads.ts
  types/store/views.ts
  utils/constants.jsx
Labels: 4: Reviews Complete, release-note-none

#8152 MM-35719: CRT, shows following when single message
  components/post_view/post/post.jsx
  components/post_view/post/post.test.js
  components/threading/channel_threads/thread_footer/__snapshots__/thread_footer.test.tsx.snap
  components/threading/channel_threads/thread_footer/thread_footer.test.tsx
  components/threading/channel_threads/thread_footer/thread_footer.tsx
Labels: 4: Reviews Complete, release-note-none

#8081 MM-32788: Permalink'ed replies open thread viewer and jump to in RHS
  actions/views/rhs.test.ts
  actions/views/rhs.ts
  components/permalink_view/actions.js
  components/permalink_view/permalink_view.jsx
  components/permalink_view/permalink_view.test.jsx
  components/rhs_comment/__snapshots__/rhs_comment.test.jsx.snap
  components/rhs_comment/rhs_comment.jsx
  components/rhs_comment/rhs_comment.test.jsx
  components/threading/global_threads/thread_item/__snapshots__/thread_item.test.tsx.snap
  components/threading/global_threads/thread_item/thread_item.test.tsx
  components/threading/global_threads/thread_item/thread_item.tsx
  components/threading/thread_viewer/index.ts
  components/threading/thread_viewer/thread_viewer.test.tsx
  components/threading/thread_viewer/thread_viewer.tsx
  reducers/views/rhs.js
  reducers/views/rhs.test.js
  selectors/rhs.test.js
  selectors/rhs.ts
  types/store/rhs.ts
  utils/constants.jsx
  utils/post_utils.jsx
  utils/post_utils.test.jsx
  utils/utils.jsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none

#8205 MM-35405: hides reply notifications user setting
  components/user_settings/notifications/index.js
  components/user_settings/notifications/user_settings_notifications.jsx
  components/user_settings/notifications/user_settings_notifications.test.js
Labels: 4: Reviews Complete, release-note-none

#8201 MM-36112 - hide upgrade references when only one product
  components/admin_console/billing/billing_subscriptions/billing_subscriptions.tsx
  components/admin_console/billing/billing_subscriptions/index.tsx
Labels: CherryPick/Approved, QA Review Done, Setup Cloud + CWS Test Server, release-note-none

#8200 Mm 36066 open cloud pricing link in new tab
  components/admin_console/billing/billing_subscriptions/billing_subscriptions.tsx
  i18n/en.json
  utils/constants.jsx
Labels: 2: Dev Review, QA Review Done, Setup Cloud + CWS Test Server, release-note-none

#8223 Automated cherry pick of #8201
  components/admin_console/billing/billing_subscriptions/billing_subscriptions.tsx
  components/admin_console/billing/billing_subscriptions/index.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8199 Update NOTICE.txt
  NOTICE.txt
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#8230 Automated cherry pick of #8199
  NOTICE.txt
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8225 MM-36095 Fix text overflow in announcement banner
  components/announcement_bar/__snapshots__/announcement_bar.test.tsx.snap
  components/announcement_bar/default_announcement_bar/announcement_bar.tsx
  e2e/cypress/integration/system_console/site_configuration/announcement_banner_spec.js
  sass/components/_announcement-bar.scss
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#8208 MM-36166 Force recalculate emoji picker position on open
  components/emoji_picker/emoji_picker_overlay.jsx
Labels: 4: Reviews Complete, CherryPick/Approved, QA Review Done, Setup Cloud Test Server, release-note-none

#8232 Automated cherry pick of #8208
  components/emoji_picker/emoji_picker_overlay.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note

#8233 Automated cherry pick of #8208
  components/emoji_picker/emoji_picker_overlay.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, do-not-merge/release-note-label-needed

#8118 [MM-35653] Data Retention redux tests
  packages/mattermost-redux/src/actions/admin.test.js
  packages/mattermost-redux/src/actions/admin.ts
  packages/mattermost-redux/src/client/client4.ts
  packages/mattermost-redux/src/reducers/entities/admin.test.js
  packages/mattermost-redux/src/reducers/entities/admin.ts
  packages/mattermost-redux/src/reducers/entities/channels.test.js
  packages/mattermost-redux/src/reducers/entities/teams.test.js
Labels: 3: QA Review, release-note

#8228 Export PurchaseModal component and related utils
  plugins/export.js
Labels: release-note-none

#8198 Fix plugin buttons on the LHS showing one below the other, instead of one after the other
  components/sidebar/__snapshots__/sidebar.test.tsx.snap
  components/sidebar/sidebar.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, QA Review Done, release-note

#8240 Automated cherry pick of #8198
  components/sidebar/__snapshots__/sidebar.test.tsx.snap
  components/sidebar/sidebar.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8235 [MM-36173] Fix spacing and opacity on descriptions for special mentions
  components/suggestion/at_mention_provider/at_mention_suggestion.jsx
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#8241 Automated cherry pick of #8235
  components/suggestion/at_mention_provider/at_mention_suggestion.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#8192 Adding English Australian to translated languages
  components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
  i18n/i18n.jsx
Labels: 2: Dev Review, QA Review Done, Setup Cloud Test Server, release-note

#8207 MM-36160 - Fix showing the red button in the sidebar hamburger menu when Enable Marketplace or Enable Plugins is disabled
  components/legacy_sidebar/header/dropdown/index.js
  components/legacy_sidebar/header/dropdown/sidebar_header_dropdown.jsx
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#8242 Automated cherry pick of #8207
  components/legacy_sidebar/header/dropdown/index.js
  components/legacy_sidebar/header/dropdown/sidebar_header_dropdown.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8209 MM-36068 Update avatars and reply count correctly for unfollowed threads
  packages/mattermost-redux/src/actions/posts.test.js
  packages/mattermost-redux/src/reducers/entities/posts.ts
  packages/mattermost-redux/src/reducers/entities/threads.ts
Labels: 4: Reviews Complete, QA Review Done, Setup Cloud Test Server, release-note-none

#8167 MM-36054, MM-35968: Fix following button and prevent no-op/server error
  actions/websocket_actions.jsx
  components/rhs_header_post/index.ts
  components/threading/thread_viewer/thread_viewer.tsx
Labels: 4: Reviews Complete, release-note-none

#8227 [MM-36270] Add overflow to emoji rendering
  components/emoji/render_emoji.tsx
  sass/components/_emoticons.scss
Labels: 4: Reviews Complete, release-note

#8224 Allow uploading `.jpeg` files on Linux
  components/__snapshots__/picture_selector.test.tsx.snap
  components/__snapshots__/setting_picture.test.jsx.snap
  components/admin_console/brand_image_setting/brand_image_setting.jsx
  components/emoji/add_emoji/__snapshots__/add_emoji.test.tsx.snap
  components/emoji/add_emoji/add_emoji.tsx
  components/integrations/bots/add_bot/add_bot.jsx
  components/picture_selector.tsx
  components/setting_picture.jsx
  utils/constants.jsx
Labels: 4: Reviews Complete, release-note

#8210 Cypress/e2e: Fixed Webhook and Tutorial navigation test cases
  e2e/cypress/integration/onboarding/tutorial_navigation_and_links_spec.js
  e2e/cypress/integration/plugins/demo_plugin/webhook_spec.js
Labels: 4: Reviews Complete, release-note-none

#8213 Cypress/E2E : Fixed link customization Test case
  e2e/cypress/integration/system_console/site_configuration/link_customization_spec.js
Labels: 4: Reviews Complete, release-note-none

#8186 tests/MM-T1808 : Hover effect exists to add a channel description / header (when not already present)
  e2e/cypress/integration/channel_settings/channel_header_spec.js
  e2e/cypress/support/api/channel.d.ts
Labels: 4: Reviews Complete, release-note-none

#8216 Migrate 'components/profile_popover' module and associated tests to T…
  components/profile_popover/__snapshots__/profile_popover.test.tsx.snap
  components/profile_popover/index.ts
  components/profile_popover/profile_popover.test.tsx
  components/profile_popover/profile_popover.tsx
  components/user_profile/user_profile.tsx
  packages/mattermost-redux/src/types/posts.ts
  utils/utils.jsx
Labels: QA Review Done, release-note

#8221 MM-35804: hide unread indicator when not following thread
  components/threading/channel_threads/thread_footer/thread_footer.test.tsx
  components/threading/channel_threads/thread_footer/thread_footer.tsx
Labels: 4: Reviews Complete, release-note-none

#8247 Fixes tests in thread viewer
  components/threading/thread_viewer/__snapshots__/thread_viewer.test.tsx.snap
  components/threading/thread_viewer/thread_viewer.test.tsx
Labels: release-note-none

#8222 MM-35837 Improve batching of channel-related actions on post receipt
  actions/new_post.test.js
  actions/new_post.ts
  actions/post_actions.test.js
  packages/mattermost-redux/src/actions/channels.ts
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#8246 Lock CI from master/release-6.0
  .circleci/config.yml
  .gitlab-ci.yml
  components/threading/thread_viewer/__snapshots__/thread_viewer.test.tsx.snap
  components/threading/thread_viewer/thread_viewer.test.tsx
Labels: AutoMerge, release-note-none

#8159 MM-35346, MM-35394: Fix unread selectors/indicators
  actions/user_actions.jsx
  components/data_prefetch/index.ts
  components/favicon_title_handler/favicon_title_handler.test.tsx
  components/favicon_title_handler/favicon_title_handler.tsx
  components/favicon_title_handler/index.ts
  components/legacy_sidebar/index.js
  components/legacy_sidebar/sidebar.jsx
  components/notify_counts/index.ts
  components/notify_counts/notify_counts.test.tsx
  components/notify_counts/notify_counts.tsx
  packages/mattermost-redux/src/actions/channels.ts
  packages/mattermost-redux/src/selectors/entities/channel_categories.test.js
  packages/mattermost-redux/src/selectors/entities/channel_categories.ts
  packages/mattermost-redux/src/selectors/entities/channels.test.js
  packages/mattermost-redux/src/selectors/entities/channels.ts
  packages/mattermost-redux/src/utils/channel_utils.ts
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none

#8248 Cherry-pick performance fixes to 5.35
  .eslintrc.json
  actions/views/channel_sidebar.ts
  components/markdown/index.ts
  components/post_markdown/post_markdown.tsx
  components/sidebar/sidebar_category/index.ts
  components/sidebar/sidebar_category/sidebar_category.test.tsx
  components/sidebar/sidebar_category/sidebar_category.tsx
  package-lock.json
  package.json
  packages/mattermost-redux/src/selectors/entities/channel_categories.test.js
  packages/mattermost-redux/src/selectors/entities/channel_categories.ts
  packages/mattermost-redux/src/selectors/entities/channels.test.js
  packages/mattermost-redux/src/selectors/entities/channels.ts
  selectors/views/channel_sidebar.test.js
  selectors/views/channel_sidebar.ts
  utils/text_formatting.tsx
  utils/text_formatting_channel_links.test.jsx
Labels: CherryPick/Approved, release-note

#8231 Fixes: crash at global threads on root post delete
  packages/mattermost-redux/src/reducers/entities/threads.test.js
  packages/mattermost-redux/src/reducers/entities/threads.ts
Labels: 4: Reviews Complete, release-note-none

#8250 MM-35837 Improve batching of channel-related actions on post receipt (release-5.35)
  actions/new_post.test.js
  actions/new_post.ts
  actions/post_actions.test.js
  packages/mattermost-redux/src/actions/channels.ts
Labels: 2: Dev Review, CherryPick/Done, release-note-none

#8251 Automated cherry pick of #8208
  components/emoji_picker/emoji_picker_overlay.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8252 Cypress/E2E: Update Zephyr Scale API URL
  e2e/utils/test_cases.js
Labels: 3: QA Review, release-note-none

#8183 [MM-34331] Migrate 'components/call_button' and associated tests to TypeScript
  components/call_button/call_button.tsx
  components/call_button/index.ts
Labels: 4: Reviews Complete, QA Review Done, release-note-none

#8254 Downgrading Polish, Italian and German to beta
  components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
  i18n/i18n.jsx
Labels: 2: Dev Review, release-note

#8244 [MM-36294] Update marketplace install command
  actions/marketplace.ts
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#8265 Translations update from Weblate
  i18n/bg.json
  i18n/de.json
  i18n/en_AU.json
  i18n/fr.json
  i18n/hu.json
  i18n/ja.json
  i18n/nl.json
  i18n/sv.json
  i18n/tr.json
Labels: 2: Dev Review, 3: QA Review, release-note-none

#8261 Set build image version as variable
  .gitlab-ci.yml
Labels: release-note-none

#8264 Automated cherry pick of #8244
  actions/marketplace.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8262 MM-36257 Handle is_following not being set for edited posts
  packages/mattermost-redux/src/reducers/entities/posts.ts
Labels: 4: Reviews Complete, release-note-none

#8259 MM-36389 Prevent unnecessary Post children components re-rendering due to comment count propagation
  actions/post_actions.jsx
  actions/post_actions.test.js
  actions/views/create_comment.jsx
  actions/views/create_comment.test.jsx
  components/create_post/create_post.jsx
  components/create_post/create_post.test.jsx
  components/create_post/index.js
  components/delete_post_modal/index.ts
  components/dot_menu/dot_menu.tsx
  components/dot_menu/index.ts
  components/edit_post_modal/edit_post_modal.jsx
  components/edit_post_modal/edit_post_modal.test.jsx
  components/post_view/comment_icon/index.ts
  components/post_view/post/__snapshots__/post.test.js.snap
  components/post_view/post/index.js
  components/post_view/post/post.jsx
  components/post_view/post/post.test.js
  components/post_view/post_header/post_header.tsx
  components/post_view/post_info/__snapshots__/post_info.test.tsx.snap
  components/post_view/post_info/index.ts
  components/post_view/post_info/post_info.tsx
  components/search_results_item/index.js
  components/search_results_item/search_results_item.jsx
  packages/mattermost-redux/src/selectors/entities/posts.ts
  utils/post_utils.jsx
  utils/post_utils.test.jsx
Labels: 4: Reviews Complete, release-note-none

#8271 Use reply count from post if thread not tracked in postsInThread reducer
  packages/mattermost-redux/src/selectors/entities/posts.ts
Labels: 2: Dev Review, release-note-none

#8237 [MM-36704] Add selector specifically for search channel name to handle its cases
  actions/views/rhs.ts
  components/search/index.tsx
  components/search/search.tsx
  components/search/types.ts
  packages/mattermost-redux/src/selectors/entities/channels.ts
  packages/mattermost-redux/src/utils/channel_utils.ts
Labels: 4: Reviews Complete, release-note-none

#8120 ref: migrate request_button to ts
  components/admin_console/__snapshots__/database_settings.test.jsx.snap
  components/admin_console/bleve_settings.jsx
  components/admin_console/database_settings.jsx
  components/admin_console/elasticsearch_settings.jsx
  components/admin_console/request_button/__snapshots__/request_button.test.tsx.snap
  components/admin_console/request_button/request_button.jsx
  components/admin_console/request_button/request_button.test.tsx
  components/admin_console/request_button/request_button.tsx
Labels: 4: Reviews Complete, release-note-none

#8270 decreased opacity on muted channels for bot-icons and avatars (with a…
  sass/layout/_sidebar-left.scss
Labels: 4: Reviews Complete, kind/bug, release-note-none

#8275 Fixes selector's name for tracking
  actions/views/create_comment.jsx
Labels: release-note-none

#8257 MM-35917: closes RHS upon navigating to threads
  actions/views/rhs.test.ts
  actions/views/rhs.ts
  components/sidebar_right/index.js
  components/sidebar_right/sidebar_right.jsx
  components/threading/global_threads/global_threads.tsx
  components/threading/global_threads_link/global_threads_link.tsx
  reducers/views/index.js
  reducers/views/rhs.js
  reducers/views/rhs.test.js
  reducers/views/rhs_suppressed.test.ts
  reducers/views/rhs_suppressed.ts
  selectors/rhs.ts
  types/store/views.ts
  utils/constants.jsx
Labels: 4: Reviews Complete, release-note-none

#8255 MM-35806: shows participants when turning CRT on
  packages/mattermost-redux/src/reducers/entities/posts.test.js
  packages/mattermost-redux/src/reducers/entities/posts.ts
  packages/mattermost-redux/src/utils/post_utils.test.js
  packages/mattermost-redux/src/utils/post_utils.ts
Labels: 4: Reviews Complete, release-note-none

#8272 MM-36218,MM-36219: CRT thread read flashes
  actions/new_post.ts
  actions/post_actions.jsx
  actions/views/threads.ts
  actions/websocket_actions.jsx
  components/threading/global_threads/thread_menu/thread_menu.test.tsx
  components/threading/global_threads/thread_menu/thread_menu.tsx
  reducers/views/threads.ts
  selectors/views/threads.ts
  types/store/views.ts
  utils/constants.jsx
Labels: 4: Reviews Complete, QA Review Done, Setup Cloud Test Server, release-note-none

#8267 MM-35769: CRT, shows unread indicator
  components/sidebar/sidebar_channel_list/sidebar_channel_list.tsx
Labels: 4: Reviews Complete, QA Review Done, Setup Cloud Test Server, release-note-none

#8226 MM-35720,MM-36293: land at new messages line
  components/post_view/new_message_separator/new_message_separator.tsx
  components/rhs_comment/rhs_comment.jsx
  components/rhs_comment/rhs_comment.test.jsx
  components/threading/global_threads/global_threads.tsx
  components/threading/thread_viewer/thread_viewer.test.tsx
  components/threading/thread_viewer/thread_viewer.tsx
  selectors/views/threads.ts
Labels: 4: Reviews Complete, release-note-none

#7944 MM-34437 Preventing infinite trial requests
  components/admin_console/feature_discovery/feature_discovery.test.tsx
  components/admin_console/feature_discovery/feature_discovery.tsx
  components/admin_console/feature_discovery/index.tsx
  components/admin_console/license_settings/__snapshots__/license_settings.test.jsx.snap
  components/admin_console/license_settings/index.js
  components/admin_console/license_settings/license_settings.jsx
  components/admin_console/license_settings/license_settings.scss
  components/admin_console/license_settings/license_settings.test.jsx
  components/admin_console/license_settings/renew_license_card/renew_license_card.scss
  components/admin_console/license_settings/trial_license_card/trial_license_card.scss
  components/admin_console/license_settings/trial_license_card/trial_license_card.tsx
  components/announcement_bar/contact_sales/contact_us.scss
  components/announcement_bar/contact_sales/contact_us.tsx
  components/announcement_bar/purchase_link/purchase_link.scss
  components/announcement_bar/purchase_link/purchase_link.tsx
  components/announcement_bar/renewal_link/renew_link.scss
  components/announcement_bar/renewal_link/renewal_link.tsx
  e2e/cypress/fixtures/markdown/markdown_basic.html
  packages/mattermost-redux/src/action_types/admin.ts
  packages/mattermost-redux/src/actions/admin.ts
  packages/mattermost-redux/src/client/client4.ts
  packages/mattermost-redux/src/reducers/entities/admin.ts
  packages/mattermost-redux/src/store/initial_state.ts
  packages/mattermost-redux/src/types/admin.ts
  utils/license_utils.jsx
  utils/utils.jsx
Labels: 4: Reviews Complete, release-note-none

#8280 MM-35837 Improve batching of channel-related actions on post receipt (release-5.36)
  actions/new_post.test.js
  actions/new_post.ts
  actions/post_actions.test.js
  packages/mattermost-redux/src/actions/channels.ts
Labels: 4: Reviews Complete, CherryPick/Done, release-note-none

#8197 Fix several autocomplete problems
  actions/views/create_comment.jsx
  components/create_comment/create_comment.jsx
  components/create_post/create_post.jsx
  components/suggestion/suggestion_box.jsx
Labels: 4: Reviews Complete, release-note-none

#8215 [MM-24335] Show recently viewed channels when channel switcher opens
  components/quick_switch_modal/__snapshots__/quick_switch_modal.test.tsx.snap
  components/quick_switch_modal/quick_switch_modal.tsx
  components/suggestion/switch_channel_provider.jsx
  i18n/en.json
  utils/constants.jsx
Labels: 4: Reviews Complete, release-note

#8276 Emoji makefile
  Makefile
  build/emoji/emoji_gen.mjs
Labels: 4: Reviews Complete, release-note-none

#8281 MM-36561: fixes loader shown on socket reconnect
  components/threading/thread_viewer/thread_viewer.tsx
Labels: 4: Reviews Complete, release-note-none

#8285 Cypress/E2E: Promote category sorting
  e2e/cypress/integration/channel_sidebar/category_sorting_spec.js
Labels: 4: Reviews Complete, release-note-none

#8283 MM-36430 Show thread as followed immediately on webapp when marking posts unread from the thread
  actions/post_actions.jsx
Labels: 4: Reviews Complete, QA Deferred, release-note-none

#8288 Translations update from Weblate
  i18n/bg.json
  i18n/de.json
  i18n/en_AU.json
  i18n/es.json
  i18n/fr.json
  i18n/hu.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 2: Dev Review, 3: QA Review, release-note-none

#8284 MM-30446: Fix toast dismiss hover console error
  components/toast/__snapshots__/toast.test.tsx.snap
  components/toast/toast.tsx
Labels: 4: Reviews Complete, QA Review Done, Setup Cloud Test Server, release-note-none

#8139 Implement FileDropdown Actions Plugin Method
  components/file_attachment/file_attachment.test.tsx
  components/file_attachment/file_attachment.tsx
  components/file_attachment/index.ts
  components/file_attachment_list/file_attachment_list.test.tsx
  components/file_attachment_list/file_attachment_list.tsx
  components/file_search_results/file_search_result_item.scss
  components/file_search_results/file_search_result_item.tsx
  components/post_view/post/__snapshots__/post.test.js.snap
  components/post_view/post/post.jsx
  components/post_view/post_body/post_body.jsx
  components/rhs_comment/rhs_comment.jsx
  components/rhs_root_post/rhs_root_post.jsx
  components/search_results/search_results.tsx
  components/search_results_item/__snapshots__/search_results_item.test.jsx.snap
  components/search_results_item/search_results_item.jsx
  plugins/registry.js
  sass/components/_files.scss
  sass/components/_post.scss
  sass/components/_search.scss
  selectors/plugins.ts
  types/store/plugins.ts
Labels: 4: Reviews Complete, release-note

#8287 MM-36590 Re-add old emoji aliases
  build/emoji/additional_shortnames.json
  build/emoji/emoji_gen.mjs
  components/suggestion/emoticon_provider.test.jsx
  utils/emoji.json
  utils/emoji.jsx
Labels: 2: Dev Review, CherryPick/Approved, QA Deferred, Setup Cloud Test Server, release-note-none

#8294 Automated cherry pick of #8287
  build/emoji/additional_shortnames.json
  build/emoji/emoji_gen.mjs
  components/suggestion/emoticon_provider.test.jsx
  utils/emoji.json
  utils/emoji.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8059 Custom status expiry
  actions/emoji_actions.js
  components/channel_header/__snapshots__/channel_header.test.jsx.snap
  components/channel_header/channel_header.js
  components/channel_header/channel_header.test.jsx
  components/channel_header/index.js
  components/custom_status/__snapshots__/custom_status_suggestion.test.tsx.snap
  components/custom_status/__snapshots__/date_time_input.test.tsx.snap
  components/custom_status/__snapshots__/expiry_menu.test.tsx.snap
  components/custom_status/custom_status.scss
  components/custom_status/custom_status_emoji.test.tsx
  components/custom_status/custom_status_emoji.tsx
  components/custom_status/custom_status_modal.tsx
  components/custom_status/custom_status_suggestion.test.tsx
  components/custom_status/custom_status_suggestion.tsx
  components/custom_status/date_time_input.test.tsx
  components/custom_status/date_time_input.tsx
  components/custom_status/expiry_menu.test.tsx
  components/custom_status/expiry_menu.tsx
  components/custom_status/expiry_time.tsx
  components/post_view/post_header/post_header_custom_status.tsx
  components/profile_popover/__snapshots__/profile_popover.test.tsx.snap
  components/profile_popover/index.ts
  components/profile_popover/profile_popover.test.tsx
  components/profile_popover/profile_popover.tsx
  components/status_dropdown/__snapshots__/status_dropdown.test.tsx.snap
  components/status_dropdown/index.ts
  components/status_dropdown/status_dropdown.scss
  components/status_dropdown/status_dropdown.test.tsx
  components/status_dropdown/status_dropdown.tsx
  components/timestamp/relative_ranges.tsx
  components/widgets/menu/menu_items/menu_item_toggle_modal_redux.tsx
  e2e/cypress/integration/custom_status/custom_status_3_spec.js
  e2e/cypress/integration/custom_status/custom_status_expiry/custom_status_expiry_1_spec.js
  e2e/cypress/integration/custom_status/custom_status_expiry/custom_status_expiry_2_spec.js
  e2e/cypress/integration/custom_status/custom_status_expiry/custom_status_expiry_3_spec.js
  e2e/cypress/integration/custom_status/custom_status_expiry/custom_status_expiry_4_spec.js
  e2e/cypress/utils/constants.js
  i18n/en.json
  packages/mattermost-redux/src/selectors/entities/timezone.ts
  packages/mattermost-redux/src/types/users.ts
  sass/components/_day-picker.scss
  selectors/general.js
  selectors/views/custom_status.test.ts
  selectors/views/custom_status.ts
  utils/constants.jsx
  utils/timezone.jsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note

#8296 fix reselect signature
  selectors/plugins.ts
Labels: 2: Dev Review, release-note-none

#8299 Automated cherry pick of #8059
  actions/emoji_actions.js
  components/channel_header/__snapshots__/channel_header.test.jsx.snap
  components/channel_header/channel_header.js
  components/channel_header/channel_header.test.jsx
  components/channel_header/index.js
  components/custom_status/__snapshots__/custom_status_suggestion.test.tsx.snap
  components/custom_status/__snapshots__/date_time_input.test.tsx.snap
  components/custom_status/__snapshots__/expiry_menu.test.tsx.snap
  components/custom_status/custom_status.scss
  components/custom_status/custom_status_emoji.test.tsx
  components/custom_status/custom_status_emoji.tsx
  components/custom_status/custom_status_modal.tsx
  components/custom_status/custom_status_suggestion.test.tsx
  components/custom_status/custom_status_suggestion.tsx
  components/custom_status/date_time_input.test.tsx
  components/custom_status/date_time_input.tsx
  components/custom_status/expiry_menu.test.tsx
  components/custom_status/expiry_menu.tsx
  components/custom_status/expiry_time.tsx
  components/post_view/post_header/post_header_custom_status.tsx
  components/profile_popover/__snapshots__/profile_popover.test.tsx.snap
  components/profile_popover/index.ts
  components/profile_popover/profile_popover.test.tsx
  components/profile_popover/profile_popover.tsx
  components/status_dropdown/__snapshots__/status_dropdown.test.tsx.snap
  components/status_dropdown/index.ts
  components/status_dropdown/status_dropdown.scss
  components/status_dropdown/status_dropdown.test.tsx
  components/status_dropdown/status_dropdown.tsx
  components/timestamp/relative_ranges.tsx
  components/widgets/menu/menu_items/menu_item_toggle_modal_redux.tsx
  e2e/cypress/integration/custom_status/custom_status_3_spec.js
  e2e/cypress/integration/custom_status/custom_status_expiry/custom_status_expiry_1_spec.js
  e2e/cypress/integration/custom_status/custom_status_expiry/custom_status_expiry_2_spec.js
  e2e/cypress/integration/custom_status/custom_status_expiry/custom_status_expiry_3_spec.js
  e2e/cypress/integration/custom_status/custom_status_expiry/custom_status_expiry_4_spec.js
  e2e/cypress/utils/constants.js
  i18n/en.json
  packages/mattermost-redux/src/selectors/entities/timezone.ts
  packages/mattermost-redux/src/types/users.ts
  sass/components/_day-picker.scss
  selectors/general.js
  selectors/views/custom_status.test.ts
  selectors/views/custom_status.ts
  utils/constants.jsx
  utils/timezone.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8298 fix import errors
  selectors/views/custom_status.ts
Labels: release-note-none

#8282 [MM-25435] Emoji picker + skin tones
  actions/emoji_actions.js
  actions/local_storage.jsx
  build/emoji/emoji_gen.mjs
  components/emoji_picker/components/emoji_picker_category.jsx
  components/emoji_picker/components/emoji_picker_preview.jsx
  components/emoji_picker/components/emoji_picker_skin.jsx
  components/emoji_picker/emoji_picker.jsx
  components/emoji_picker/emoji_picker.test.jsx
  components/emoji_picker/emoji_picker_tabs.jsx
  components/emoji_picker/index.js
  i18n/en.json
  images/emoji/emoji-custom.png
  reducers/views/emoji.js
  sass/components/_emoji-picker-tabs.scss
  sass/components/_emoticons.scss
  sass/components/_module.scss
  selectors/emojis.js
  stores/local_storage_store.jsx
  utils/constants.jsx
  utils/emoji.jsx
  utils/utils.jsx
Labels: 4: Reviews Complete, CherryPick/Approved, QA Review Done, release-note

#8301 Automated cherry pick of #8298
  selectors/views/custom_status.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8300 Automated cherry pick of #8282
  actions/emoji_actions.js
  actions/local_storage.jsx
  build/emoji/emoji_gen.mjs
  components/emoji_picker/components/emoji_picker_category.jsx
  components/emoji_picker/components/emoji_picker_preview.jsx
  components/emoji_picker/components/emoji_picker_skin.jsx
  components/emoji_picker/emoji_picker.jsx
  components/emoji_picker/emoji_picker.test.jsx
  components/emoji_picker/emoji_picker_tabs.jsx
  components/emoji_picker/index.js
  i18n/en.json
  images/emoji/emoji-custom.png
  reducers/views/emoji.js
  sass/components/_emoji-picker-tabs.scss
  sass/components/_emoticons.scss
  sass/components/_module.scss
  selectors/emojis.js
  stores/local_storage_store.jsx
  utils/constants.jsx
  utils/emoji.jsx
  utils/utils.jsx
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8187 Add app icon to Marketplace
  components/plugin_marketplace/marketplace_item/marketplace_item.tsx
  components/plugin_marketplace/marketplace_item/marketplace_item_app/__snapshots__/marketplace_item_app.test.tsx.snap
  components/plugin_marketplace/marketplace_item/marketplace_item_app/marketplace_item_app.test.tsx
  components/plugin_marketplace/marketplace_item/marketplace_item_app/marketplace_item_app.tsx
  components/plugin_marketplace/marketplace_item/marketplace_item_plugin/__snapshots__/marketplace_item_plugin.test.tsx.snap
  components/plugin_marketplace/marketplace_item/marketplace_item_plugin/marketplace_item_plugin.tsx
  components/plugin_marketplace/marketplace_list/marketplace_list.tsx
  packages/mattermost-redux/src/types/apps.ts
  packages/mattermost-redux/src/types/marketplace.ts
Labels: 4: Reviews Complete, QA Review Done, release-note

#8253 MM-36341 - order plan lists
  components/purchase_modal/purchase_modal.tsx
Labels: 2: Dev Review, release-note-none

#8286 [MM-18496] Private channels should appear in channel link autocomplete
  components/suggestion/channel_mention_provider.jsx
Labels: release-note

#8279 MM-36542: getOpenThreadId should consider suppressed RHS
  components/sidebar_right/sidebar_right.jsx
  selectors/views/threads.test.ts
  selectors/views/threads.ts
Labels: 4: Reviews Complete, release-note-none

#8305 Automated cherry pick of #8279
  components/sidebar_right/sidebar_right.jsx
  selectors/views/threads.test.ts
  selectors/views/threads.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8303 [MM-36626] fix emoji picker colors
  components/emoji_picker/emoji_picker_tabs.jsx
  sass/components/_emoji-picker-tabs.scss
  sass/components/_emoticons.scss
Labels: 2: Dev Review, QA Review Done, Setup Cloud Test Server, release-note-none

#8306 Automated cherry pick of #8303
  components/emoji_picker/emoji_picker_tabs.jsx
  sass/components/_emoji-picker-tabs.scss
  sass/components/_emoticons.scss
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8243 MM-35191 - show banner in user timezone
  components/admin_console/billing/billing_summary/billing_summary.tsx
  components/announcement_bar/cloud_trial_announcement_bar/cloud_trial_announcement_bar.tsx
  i18n/en.json
  i18n/en_AU.json
  utils/utils.jsx
Labels: QA Review Done, Setup Cloud + CWS Test Server, release-note-none

#8309 MM-36654 Re-add Mattermost emoji
  build/emoji/emoji_gen.mjs
  components/emoji_picker/components/emoji_picker_preview.jsx
  components/emoji_picker/emoji_picker.jsx
  images/emoji/mattermost.png
  sass/components/_emoticons.scss
  utils/emoji.json
  utils/emoji.jsx
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#8310 Automated cherry pick of #8309
  build/emoji/emoji_gen.mjs
  components/emoji_picker/components/emoji_picker_preview.jsx
  components/emoji_picker/emoji_picker.jsx
  images/emoji/mattermost.png
  sass/components/_emoticons.scss
  utils/emoji.json
  utils/emoji.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, do-not-merge/release-note-label-needed

#8292 MM-36593 RHS performance improvements
  components/file_search_results/index.tsx
  components/search_results/index.tsx
  components/search_results/search_results.tsx
  components/search_results/types.ts
  packages/mattermost-redux/src/selectors/entities/posts.ts
Labels: 4: Reviews Complete, release-note

#8314 Translations update from Weblate
  i18n/bg.json
  i18n/de.json
  i18n/en_AU.json
  i18n/es.json
  i18n/fr.json
  i18n/hu.json
  i18n/nl.json
  i18n/tr.json
  i18n/zh-CN.json
Labels: 2: Dev Review, 3: QA Review, release-note-none

#8160 [MM-8497] Ability to set Do Not Disturb for a specified period of time
  components/dnd_custom_time_picker_modal/dnd_custom_time_picker_modal.scss
  components/dnd_custom_time_picker_modal/dnd_custom_time_picker_modal.tsx
  components/dnd_custom_time_picker_modal/index.ts
  components/generic_modal.scss
  components/sidebar/sidebar_category/sidebar_category_menu/__snapshots__/sidebar_category_menu.test.tsx.snap
  components/sidebar/sidebar_channel/sidebar_channel_menu/__snapshots__/sidebar_channel_menu.test.tsx.snap
  components/status_dropdown/__snapshots__/status_dropdown.test.tsx.snap
  components/status_dropdown/index.ts
  components/status_dropdown/status_dropdown.scss
  components/status_dropdown/status_dropdown.test.tsx
  components/status_dropdown/status_dropdown.tsx
  components/widgets/menu/menu.scss
  components/widgets/menu/menu_header.scss
  components/widgets/menu/menu_items/menu_item.scss
  components/widgets/menu/menu_items/submenu_item.tsx
  components/widgets/menu/menu_modals/submenu_modal/__snapshots__/submenu_modal.test.tsx.snap
  e2e/cypress/integration/status/status_dnd_1_spec.js
  i18n/en.json
  packages/mattermost-redux/src/selectors/entities/preferences.ts
  packages/mattermost-redux/src/types/config.ts
  packages/mattermost-redux/src/types/users.ts
  sass/components/_day-picker.scss
  sass/components/_dnd-pickers-dropdown-menu.scss
  sass/layout/_headers.scss
  sass/utils/_modifiers.scss
  utils/constants.jsx
  utils/datetime.ts
  utils/timezone.jsx
  utils/utils.jsx
Labels: 4: Reviews Complete, QA Review Done, release-note

#8308 MM-35897 - make sure to show max 14 days in the UI of remaining trial
  components/admin_console/billing/billing_subscriptions/index.tsx
  components/admin_console/billing/billing_summary/billing_summary.tsx
  components/announcement_bar/cloud_trial_announcement_bar/cloud_trial_announcement_bar.tsx
  components/announcement_bar/cloud_trial_announcement_bar/index.ts
  components/main_menu/index.jsx
  utils/constants.jsx
Labels: 2: Dev Review, QA Review Done, Setup Cloud + CWS Test Server, release-note-none

#8318 [MM-36481] Fix thumbsup emoji parsing to support skin tones
  i18n/en.json
  utils/emoticons.test.tsx
  utils/emoticons.tsx
Labels: 4: Reviews Complete, QA Review Done, Setup Cloud Test Server, release-note-none

#8328 Automated cherry pick of #8318
  i18n/en.json
  utils/emoticons.test.tsx
  utils/emoticons.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8323 MM-36730: permalinks to replies sometimes throw
  components/rhs_comment/rhs_comment.jsx
  components/threading/thread_viewer/thread_viewer.tsx
Labels: 4: Reviews Complete, QA Review Done, Setup Cloud Test Server, release-note-none

#8291 MM-36592 Fix memoization of getDirectTeammate
  components/audit_table/index.ts
  components/channel_view/index.ts
  components/post_view/channel_intro_message/channel_intro_message.tsx
  components/post_view/channel_intro_message/index.ts
  components/rhs_thread/index.ts
  components/search_results_item/index.js
  components/search_results_item/search_results_item.jsx
  components/suggestion/search_channel_suggestion/index.ts
  components/suggestion/switch_channel_provider.jsx
  components/threading/thread_viewer/index.ts
  components/threading/thread_viewer/thread_viewer.tsx
  packages/mattermost-redux/src/selectors/entities/channels.ts
  utils/utils.jsx
Labels: 4: Reviews Complete, release-note

#8329 Automated cherry pick of #8323
  components/rhs_comment/rhs_comment.jsx
  components/threading/thread_viewer/thread_viewer.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8293 MM-36595 Reduced re-rendering of Reaction components
  .eslintrc.json
  components/post_view/reaction/__snapshots__/reaction.test.jsx.snap
  components/post_view/reaction/index.ts
  components/post_view/reaction/reaction.test.jsx
  components/post_view/reaction/reaction.tsx
  components/post_view/reaction/reaction_tooltip/index.test.js
  components/post_view/reaction/reaction_tooltip/index.ts
  components/post_view/reaction/reaction_tooltip/reaction_tooltip.tsx
  utils/utils.jsx
  utils/utils.test.jsx
Labels: 4: Reviews Complete, release-note

#8324 MM-36612: opening channel switcher while in threads throws
  components/suggestion/switch_channel_provider.jsx
Labels: 4: Reviews Complete, QA Review Done, Setup Cloud Test Server, release-note-none

#8322 [MM-36618] Save skin tone to preferences
  actions/emoji_actions.js
  actions/local_storage.jsx
  components/emoji_picker/components/emoji_picker_skin.jsx
  components/emoji_picker/emoji_picker.jsx
  components/emoji_picker/emoji_picker.test.jsx
  components/emoji_picker/index.js
  reducers/views/emoji.js
  selectors/emojis.js
  stores/local_storage_store.jsx
  utils/constants.jsx
Labels: 4: Reviews Complete, QA Review Done, Setup Cloud Test Server, release-note-none

#8331 Automated cherry pick of #8322
  actions/emoji_actions.js
  actions/local_storage.jsx
  components/emoji_picker/components/emoji_picker_skin.jsx
  components/emoji_picker/emoji_picker.jsx
  components/emoji_picker/emoji_picker.test.jsx
  components/emoji_picker/index.js
  reducers/views/emoji.js
  selectors/emojis.js
  stores/local_storage_store.jsx
  utils/constants.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8330 Automated cherry pick of #8324
  components/suggestion/switch_channel_provider.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8321 [MM-36714] - Renew Now button in announcement bar lost its styling
  sass/components/_announcement-bar.scss
Labels: 3: QA Review, CherryPick/Approved, Setup Cloud + CWS Test Server, release-note-none

#8332 Manual cherry pick of #8321
  sass/components/_announcement-bar.scss
Labels: Changelog/Not Needed, Docs/Not Needed, release-note-none

#8312 MM-36683 - align announcement bar close button to the right
  sass/components/_announcement-bar.scss
Labels: 4: Reviews Complete, QA Review Done, Setup Cloud + CWS Test Server, release-note-none

#8336 Prevent trackedSelectors from holding a reference to old selectors
  packages/reselect/src/index.js
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#8278 MM-36391: navigates to threads on shortcut ALT+ARROW
  actions/views/threads.ts
  components/sidebar/sidebar_channel_list/index.ts
  components/sidebar/sidebar_channel_list/sidebar_channel_list.test.tsx
  components/sidebar/sidebar_channel_list/sidebar_channel_list.tsx
  components/threading/global_threads/global_threads.tsx
  components/threading/global_threads_link/global_threads_link.tsx
Labels: 4: Reviews Complete, QA Review Done, release-note-none

#8338 Automated cherry pick of #8336
  packages/reselect/src/index.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8171 Add Markdown fields to app forms
  components/apps_form/apps_form_field/apps_form_field.tsx
  components/suggestion/command_provider/app_command_parser/app_command_parser.ts
  components/suggestion/command_provider/app_command_parser/app_command_parser_dependencies.ts
  packages/mattermost-redux/src/constants/apps.ts
Labels: 4: Reviews Complete, release-note

#8333 MM-35439: CRT, clicking x unread threads
  components/threading/global_threads/global_threads.tsx
Labels: 4: Reviews Complete, release-note-none

#8326 Cypress/E2E: Promote tests to prod
  e2e/cypress/integration/enterprise/elasticsearch_autocomplete/users_in_channel_switcher_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/guest_identification_spec.js
  e2e/cypress/integration/integrations/message_to_channel_via_slash_command_spec.js
  e2e/cypress/integration/messaging/message_reply_scrollable_spec.js
  e2e/cypress/integration/plugins/link_tooltip_spec.js
  e2e/cypress/integration/scroll/deleting_scroll_spec.js
  e2e/cypress/integration/scroll/editing_scroll_spec.js
  e2e/cypress/integration/scroll/image_aspect_ratio_spec.js
  e2e/cypress/integration/search_autocomplete/scroll_spec.js
  e2e/cypress/integration/search_filter/edit_spec.js
Labels: 4: Reviews Complete, release-note-none

#8325 Cypress/E2E: Fix failed tests
  e2e/cypress/integration/accessibility/accessibility_account_settings_spec.js
  e2e/cypress/integration/accessibility/accessibility_popovers_spec.js
  e2e/cypress/integration/accessibility/accessibility_post_spec.js
  e2e/cypress/integration/archived_channel/archived_leave_channel_spec.js
  e2e/cypress/integration/archived_channel/post_menu_spec.js
  e2e/cypress/integration/emoji/custom_emoji_1_spec.js
  e2e/cypress/integration/emoji/sorted_emojis_spec.js
  e2e/cypress/integration/enterprise/accessibility/accessibility_input_fields_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/guest_identification_ui_not_cloud_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/guest_identification_ui_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/guest_invitation_ui_more_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/helpers.js
  e2e/cypress/integration/enterprise/guest_accounts/system_console_manage_guest_not_cloud_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/system_console_manage_guest_spec.js
  e2e/cypress/integration/interactive_dialog/full_dialog_spec.js
  e2e/cypress/integration/keyboard_shortcuts/ctrl_cmd_k_unreads_spec.js
  e2e/cypress/integration/messaging/dm_list_of_users_spec.js
  e2e/cypress/integration/messaging/emoji_keyboard_entry_spec.js
  e2e/cypress/integration/messaging/emoji_picker_keyboard_usability_spec.js
  e2e/cypress/integration/messaging/emoji_size_spec.js
  e2e/cypress/integration/notifications/desktop_notifications_spec.js
  e2e/cypress/integration/system_console/reporting/site_statistics_spec.js
  e2e/cypress/integration/system_console/user_management/users_deactivation_not_cloud_spec.js
  e2e/cypress/integration/system_console/user_management/users_deactivation_spec.js
  e2e/cypress/integration/system_console/user_management_not_cloud_spec.js
  e2e/cypress/integration/system_console/user_management_spec.js
  e2e/cypress/support/api/user.d.ts
  e2e/cypress/support/api/user.js
Labels: 4: Reviews Complete, release-note-none
