Repository mattermost/mattermost-webapp, pull requests merged in 2021-10, with the labels that each got.

#9005 MM-38540 - set consistent hover state for invite members button
  sass/layout/_sidebar-left.scss
Labels: Setup Cloud Test Server, release-note-none

#9007 CypressE2E: Fixed Test Cases
  e2e/cypress/integration/accessibility/accessibility_sidebar_spec.js
  e2e/cypress/integration/account_settings/display/message_display_mode_spec.js
Labels: 3: QA Review, release-note-none

#9008 Automated cherry pick of #9007
  e2e/cypress/integration/accessibility/accessibility_sidebar_spec.js
  e2e/cypress/integration/account_settings/display/message_display_mode_spec.js
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#8986 [MM-38836] - Try Enterprise for free option missing spacing in mobile webview
  components/widgets/menu/menu_items/menu_item.scss
Labels: 2: Dev Review, Setup Cloud Test Server, 1: UX Review, release-note-none

#8983 [MM-38833] - Font within CC field is not consistent with other fields in payment form
  components/payment_form/card_input.tsx
Labels: 2: Dev Review, QA Review Done, Setup Cloud + CWS Test Server, release-note-none

#9006 Cypress/E2E: Update tests related to edit indicator
  e2e/cypress/integration/account_settings/display/message_display_mode_spec.js
  e2e/cypress/integration/keyboard_shortcuts/keyboard_shortcuts_2_spec.js
  e2e/cypress/integration/messaging/center_channel_rhs_overlap_spec.js
  e2e/cypress/integration/messaging/direct_message_spec.js
  e2e/cypress/integration/messaging/permalink_message_edit_spec.js
  e2e/cypress/integration/messaging/strikethrough_spec.js
  e2e/cypress/integration/messaging/typing_should_show_up_when_editing_spec.js
Labels: 4: Reviews Complete, QA Review Done, release-note-none

#9010 Automated cherry pick of #9006
  e2e/cypress/integration/account_settings/display/message_display_mode_spec.js
  e2e/cypress/integration/keyboard_shortcuts/keyboard_shortcuts_2_spec.js
  e2e/cypress/integration/messaging/center_channel_rhs_overlap_spec.js
  e2e/cypress/integration/messaging/direct_message_spec.js
  e2e/cypress/integration/messaging/permalink_message_edit_spec.js
  e2e/cypress/integration/messaging/strikethrough_spec.js
  e2e/cypress/integration/messaging/typing_should_show_up_when_editing_spec.js
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#9013 Automated cherry pick of #9005
  sass/layout/_sidebar-left.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#9012 MM-38908: Handle /:team/_playbooks/:playbookId/run
  components/channel_layout/center_channel/center_channel.tsx
  components/channel_layout/playbook_runner.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#9015 Automated cherry pick of #9012
  components/channel_layout/center_channel/center_channel.tsx
  components/channel_layout/playbook_runner.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#8981 [MM-38536] Stop needs_team from trying to join a team with a reserved name
  components/needs_team/needs_team.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#9017 Automated cherry pick of #8981
  components/needs_team/needs_team.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#9011 Cypress/E2E: fixed tests and demoted other tests
  e2e/cypress/integration/accessibility/accessibility_sidebar_dm_spec.js
  e2e/cypress/integration/accessibility/accessibility_sidebar_spec.js
  e2e/cypress/integration/account_settings/general/fullname_edit_spec.js
  e2e/cypress/integration/account_settings/general/fullname_spec.js
  e2e/cypress/integration/archived_channel/archived_leave_channel_spec.js
  e2e/cypress/integration/channel/channel_mention_autocomplete_spec.js
  e2e/cypress/integration/channel/user_to_channel_admin_member_updates_manage_channel_members_modal_spec.js
  e2e/cypress/integration/channel_sidebar/dm_gm_filtering_sorting_spec.js
  e2e/cypress/integration/channel_sidebar/dm_sidebar_not_remove_spec.js
  e2e/cypress/integration/enterprise/elasticsearch_autocomplete/users_spec.js
  e2e/cypress/integration/enterprise/group_mentions/group_mentions_permissions_spec.js
  e2e/cypress/integration/enterprise/group_mentions/group_mentions_posts_spec.js
  e2e/cypress/integration/enterprise/group_mentions/group_mentions_system_messages_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/guest_experience_ui_spec.js
  e2e/cypress/integration/enterprise/ldap_group/group_mentions_spec.js
  e2e/cypress/integration/enterprise/permissions/team_permissions_spec.js
  e2e/cypress/integration/integrations/builtin_commands/common_commands_1_spec.js
  e2e/cypress/integration/integrations/outgoing_webhook/prompt_set_status_spec.js
  e2e/cypress/integration/messaging/channel_and_posts_links_spec.js
  e2e/cypress/integration/messaging/channel_menu_spec.js
  e2e/cypress/integration/messaging/edit_message_spec.js
  e2e/cypress/integration/messaging/mention_autocomplete_overlap_spec.js
  e2e/cypress/integration/messaging/message_edit_post_with_attachment_spec.js
  e2e/cypress/integration/messaging/permalink_click_spec.js
  e2e/cypress/integration/messaging/receive_message_on_socket_reconnect_spec.js
  e2e/cypress/integration/multi_team_and_dm/close_gm_via_menu_spec.js
  e2e/cypress/integration/multi_team_and_dm/dm_more_searching_from_page_spec.js
  e2e/cypress/integration/multi_team_and_dm/max_gm_members_spec.js
  e2e/cypress/integration/notifications/browser_tab_notification_1_spec.js
  e2e/cypress/integration/notifications/browser_tab_notification_2_spec.js
  e2e/cypress/integration/system_console/user_management/users_reactivation_spec.js
  e2e/cypress/support/ui/post_dropdown_menu.js
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#9018 Automated cherry pick of #9011
  e2e/cypress/integration/accessibility/accessibility_sidebar_dm_spec.js
  e2e/cypress/integration/accessibility/accessibility_sidebar_spec.js
  e2e/cypress/integration/account_settings/general/fullname_edit_spec.js
  e2e/cypress/integration/account_settings/general/fullname_spec.js
  e2e/cypress/integration/archived_channel/archived_leave_channel_spec.js
  e2e/cypress/integration/channel/channel_mention_autocomplete_spec.js
  e2e/cypress/integration/channel/user_to_channel_admin_member_updates_manage_channel_members_modal_spec.js
  e2e/cypress/integration/channel_sidebar/dm_gm_filtering_sorting_spec.js
  e2e/cypress/integration/channel_sidebar/dm_sidebar_not_remove_spec.js
  e2e/cypress/integration/enterprise/elasticsearch_autocomplete/users_spec.js
  e2e/cypress/integration/enterprise/group_mentions/group_mentions_permissions_spec.js
  e2e/cypress/integration/enterprise/group_mentions/group_mentions_posts_spec.js
  e2e/cypress/integration/enterprise/group_mentions/group_mentions_system_messages_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/guest_experience_ui_spec.js
  e2e/cypress/integration/enterprise/ldap_group/group_mentions_spec.js
  e2e/cypress/integration/enterprise/permissions/team_permissions_spec.js
  e2e/cypress/integration/integrations/builtin_commands/common_commands_1_spec.js
  e2e/cypress/integration/integrations/outgoing_webhook/prompt_set_status_spec.js
  e2e/cypress/integration/messaging/channel_and_posts_links_spec.js
  e2e/cypress/integration/messaging/channel_menu_spec.js
  e2e/cypress/integration/messaging/edit_message_spec.js
  e2e/cypress/integration/messaging/mention_autocomplete_overlap_spec.js
  e2e/cypress/integration/messaging/message_edit_post_with_attachment_spec.js
  e2e/cypress/integration/messaging/permalink_click_spec.js
  e2e/cypress/integration/messaging/receive_message_on_socket_reconnect_spec.js
  e2e/cypress/integration/multi_team_and_dm/close_gm_via_menu_spec.js
  e2e/cypress/integration/multi_team_and_dm/dm_more_searching_from_page_spec.js
  e2e/cypress/integration/multi_team_and_dm/max_gm_members_spec.js
  e2e/cypress/integration/notifications/browser_tab_notification_1_spec.js
  e2e/cypress/integration/notifications/browser_tab_notification_2_spec.js
  e2e/cypress/integration/system_console/user_management/users_reactivation_spec.js
  e2e/cypress/support/ui/post_dropdown_menu.js
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#8829 MM-38212: remove read channel from unreads when navigating to threads
  actions/global_actions.tsx
  components/threading/global_threads/global_threads.tsx
Labels: 4: Reviews Complete, release-note-none

#8990 [MM-38430] - Onboarding invite shows limits that no longer apply-2
  components/next_steps_view/steps/invite_members_step/invite_members_step.test.tsx
  components/next_steps_view/steps/invite_members_step/invite_members_step.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, QA Review Done, Setup Cloud + CWS Test Server, release-note-none

#9020 [MM-38430] Cherrypick
  components/next_steps_view/steps/invite_members_step/invite_members_step.test.tsx
  components/next_steps_view/steps/invite_members_step/invite_members_step.tsx
  i18n/en.json
Labels: 2: Dev Review, release-note-none

#8801 [MM-37054] Refactored trial subscription test scripts for system console
  e2e/cypress/integration/enterprise/cloud/billing/subscriptions_free_trial_spec.js
Labels: 4: Reviews Complete, release-note-none

#8972 MM-38780 - Do not show Oauth 2.0 for Starter
  components/admin_console/admin_definition.jsx
Labels: 4: Reviews Complete, CherryPick/Approved, QA Review Done, Setup Cloud + CWS Test Server, release-note-none

#8996 [MM-38868] Fixes do not disturb submenu item not taking full width
  components/status_dropdown/status_dropdown.scss
Labels: 2: Dev Review, release-note, QA Deferred

#8866 [MM-26478] Add one click reactions
  components/post_view/post_info/index.ts
  components/post_view/post_info/post_info.test.tsx
  components/post_view/post_info/post_info.tsx
  components/post_view/post_recent_reactions/index.ts
  components/post_view/post_recent_reactions/post_recent_reactions.tsx
  components/post_view/post_recent_reactions/recent_reactions_emoji_item.jsx
  components/post_view/reaction/reaction.scss
  components/rhs_comment/index.ts
  components/rhs_comment/rhs_comment.jsx
  components/rhs_root_post/index.ts
  components/rhs_root_post/rhs_root_post.jsx
  components/user_settings/display/__snapshots__/user_settings_display.test.tsx.snap
  components/user_settings/display/index.ts
  components/user_settings/display/user_settings_display.test.tsx
  components/user_settings/display/user_settings_display.tsx
  components/widgets/icons/emoji_icon.tsx
  e2e/cypress/integration/accessibility/accessibility_account_settings_spec.js
  e2e/cypress/integration/accessibility/accessibility_post_spec.js
  i18n/en.json
  sass/responsive/_mobile.scss
  selectors/emojis.js
  utils/constants.jsx
Labels: 4: Reviews Complete, release-note

#9036 Automated cherry pick of #8972
  components/admin_console/admin_definition.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#9035 Automated cherry pick of #8990
  components/next_steps_view/steps/invite_members_step/invite_members_step.test.tsx
  components/next_steps_view/steps/invite_members_step/invite_members_step.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#9034 Automated cherry pick of #8981
  components/needs_team/needs_team.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#9037 Automated cherry pick of #8829
  actions/global_actions.tsx
  components/threading/global_threads/global_threads.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#9033 Cypress/E2E: Fix some prod messaging tests
  e2e/cypress/integration/messaging/channel_and_posts_links_spec.js
  e2e/cypress/integration/messaging/permalink_message_edit_spec.js
Labels: 4: Reviews Complete, release-note-none

#9041 Cypress/E2E: Fix some unstable messaging tests
  e2e/cypress/integration/messaging/permalink_click_spec.js
  e2e/cypress/integration/messaging/single_image_thumbnail_spec.js
Labels: 4: Reviews Complete, release-note-none

#8971 [MM-38502] Fixing image name in modal title
  components/file_preview_modal/file_preview_modal.jsx
  components/post_view/post_image/post_image.jsx
Labels: CherryPick/Approved, AutoMerge, release-note-none

#9043 Automated cherry pick of #8971
  components/file_preview_modal/file_preview_modal.jsx
  components/post_view/post_image/post_image.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#9042 Automated cherry pick of #8971
  components/file_preview_modal/file_preview_modal.jsx
  components/post_view/post_image/post_image.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#8987 docker/build: push image to the testing repository and refactor the fetches of the dockerfile
  .circleci/config.yml
Labels: 4: Reviews Complete, release-note-none

#8852 [MM-31389] Show confirm modal for `@here` mentions
  components/admin_console/admin_definition.jsx
  components/create_comment/__snapshots__/create_comment.test.jsx.snap
  components/create_comment/create_comment.test.jsx
  components/create_comment/create_comment.tsx
  components/create_comment/index.ts
  components/create_post/__snapshots__/create_post.test.jsx.snap
  components/create_post/create_post.test.jsx
  components/create_post/create_post.tsx
  components/create_post/index.ts
  components/notify_confirm_modal.tsx
  i18n/en.json
  utils/constants.jsx
  utils/post_utils.test.jsx
  utils/post_utils.ts
Labels: 4: Reviews Complete, release-note

#9050 Fixes fetching threads upon ws reconnection (#8985)
  actions/websocket_actions.jsx
Labels: release-note-none

#9023 test: MM-T963 Test for Purge Caches
  e2e/cypress/integration/system_console/environment_spec.js
Labels: Hacktoberfest, hacktoberfest-accepted, release-note-none, Contributor

#8893 Translations update from Weblate
  i18n/bg.json
  i18n/de.json
  i18n/en_AU.json
  i18n/es.json
  i18n/fr.json
  i18n/hu.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: release-note-none

#9029 MM-39033 Revert change to More DMs modal for new users
  components/more_direct_channels/list/index.test.js
  components/more_direct_channels/list/index.ts
Labels: 4: Reviews Complete, release-note-none, QA Deferred

#9053 Automated cherry pick of #9029
  components/more_direct_channels/list/index.test.js
  components/more_direct_channels/list/index.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#9030 MM-39034 Fix 'no results found' string in More DMs modal
  components/multiselect/__snapshots__/multiselect.test.tsx.snap
  components/multiselect/multiselect.tsx
Labels: 4: Reviews Complete, release-note, QA Deferred

#9039 MM-39046 Don't modify all drafts on page load
  actions/storage.js
  actions/storage.test.js
  actions/views/create_comment.tsx
  components/create_post/create_post.tsx
  components/create_post/index.ts
  reducers/storage.js
  reducers/storage.test.js
  utils/constants.jsx
Labels: 4: Reviews Complete, release-note, QA Deferred

#9025 [MM-36883] Show ephemeral message as centre post even if CRT is enabled
  packages/mattermost-redux/src/reducers/entities/posts.ts
Labels: 4: Reviews Complete, release-note

#9004 [MM-38287] - Add product switcher unit tests
  components/global/__snapshots__/product_switcher.test.tsx.snap
  components/global/product_switcher.test.tsx
  components/global/product_switcher.tsx
Labels: release-note-none

#9051 MM-39061 - change purchase modal lhs text and link
  components/purchase_modal/purchase_modal.tsx
  i18n/en.json
  utils/constants.jsx
Labels: 4: Reviews Complete, CherryPick/Approved, QA Review Done, AutoMerge, Setup Cloud + CWS Test Server, release-note-none

#9066 Automated cherry pick of #9051
  components/purchase_modal/purchase_modal.tsx
  i18n/en.json
  utils/constants.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#9056 Cypress/E2E: Update date filter format
  e2e/cypress/integration/custom_status/custom_status_expiry/custom_status_expiry_3_spec.js
Labels: 4: Reviews Complete, release-note-none

#9049 Cypress/E2E: Organize admin sidebar navigation
  e2e/cypress/integration/enterprise/system_console/search_box_spec.js
  e2e/cypress/integration/enterprise/system_console/sidebar_link_navigation_cloud_spec.js
  e2e/cypress/integration/enterprise/system_console/sidebar_link_navigation_e20_spec.js
  e2e/cypress/integration/enterprise/system_console/sidebar_link_navigation_not_cloud_spec.js
  e2e/cypress/integration/enterprise/system_console/sidebar_link_navigation_spec.js
  e2e/cypress/integration/enterprise/visual_regression/system_console/about_section_spec.js
  e2e/cypress/integration/enterprise/visual_regression/system_console/authentication_section_spec.js
  e2e/cypress/integration/enterprise/visual_regression/system_console/compliance_section_spec.js
  e2e/cypress/integration/enterprise/visual_regression/system_console/environment_section_spec.js
  e2e/cypress/integration/system_console/reporting/server_logs_spec.js
  e2e/cypress/integration/system_console/sidebar_link_navigation_not_cloud_spec.js
  e2e/cypress/integration/system_console/sidebar_link_navigation_spec.js
  e2e/cypress/integration/system_console/sidebar_link_navigation_team_spec.js
  e2e/cypress/support/api/system.js
  e2e/cypress/utils/admin_console.js
Labels: release-note-none

#9261 Fix type definition for state.entities.users.profilesInChannel
  packages/mattermost-redux/src/selectors/entities/channels.ts
  packages/mattermost-redux/src/selectors/entities/users.ts
  packages/mattermost-redux/src/types/users.ts
  packages/mattermost-redux/src/types/utilities.ts
  packages/mattermost-redux/src/utils/channel_utils.ts
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted, release-note-none, Contributor
