Repository mattermost/mattermost-webapp, pull requests merged in 2021-07, with the labels that each got.

#8302 MM-36609 Reduce recomputations of haveIChannelPermission and getMyChannelPermissions selectors during typing and other state changes
  actions/post_actions.test.js
  actions/views/group.js
  actions/websocket_actions.jsx
  components/backstage/index.js
  components/channel_members_dropdown/index.js
  components/create_comment/index.js
  components/create_post/index.js
  components/edit_post_modal/index.js
  components/integrations/installed_commands/index.ts
  components/integrations/installed_incoming_webhooks/index.ts
  components/integrations/installed_outgoing_webhooks/index.js
  components/invitation_modal/index.js
  components/legacy_sidebar/index.js
  components/main_menu/index.jsx
  components/member_list_team/index.ts
  components/new_channel_flow/index.ts
  components/permissions_gates/any_team_permission_gate/index.ts
  components/permissions_gates/channel_permission_gate/channel_permission_gate.test.tsx
  components/permissions_gates/channel_permission_gate/index.ts
  components/permissions_gates/team_permission_gate/index.ts
  components/post_view/reaction/index.ts
  components/sidebar/index.ts
  components/sidebar/sidebar_channel/sidebar_channel_menu/index.ts
  components/suggestion/search_channel_with_permissions_provider.jsx
  components/suggestion/search_channel_with_permissions_provider.test.jsx
  components/team_general_tab/index.js
  components/textbox/index.ts
  components/tutorial/index.tsx
  packages/mattermost-redux/src/reducers/entities/channels.test.js
  packages/mattermost-redux/src/reducers/entities/channels.ts
  packages/mattermost-redux/src/selectors/entities/channels.test.js
  packages/mattermost-redux/src/selectors/entities/channels.ts
  packages/mattermost-redux/src/selectors/entities/roles.test.js
  packages/mattermost-redux/src/selectors/entities/roles.ts
  packages/mattermost-redux/src/store/initial_state.ts
  packages/mattermost-redux/src/types/channels.ts
  packages/mattermost-redux/src/utils/channel_utils.ts
  packages/mattermost-redux/src/utils/post_utils.test.js
  packages/mattermost-redux/src/utils/post_utils.ts
  utils/channel_utils.jsx
  utils/post_utils.jsx
Labels: 4: Reviews Complete, QA Review Done, Setup Cloud Test Server, release-note

#8340 Automated cherry pick of #8302
  actions/post_actions.test.js
  actions/views/group.js
  actions/websocket_actions.jsx
  components/backstage/index.js
  components/channel_members_dropdown/index.js
  components/create_comment/index.js
  components/create_post/index.js
  components/edit_post_modal/index.js
  components/integrations/installed_commands/index.ts
  components/integrations/installed_incoming_webhooks/index.ts
  components/integrations/installed_outgoing_webhooks/index.js
  components/invitation_modal/index.js
  components/legacy_sidebar/index.js
  components/main_menu/index.jsx
  components/member_list_team/index.ts
  components/new_channel_flow/index.ts
  components/permissions_gates/any_team_permission_gate/index.ts
  components/permissions_gates/channel_permission_gate/channel_permission_gate.test.tsx
  components/permissions_gates/channel_permission_gate/index.ts
  components/permissions_gates/team_permission_gate/index.ts
  components/post_view/reaction/index.ts
  components/sidebar/index.ts
  components/sidebar/sidebar_channel/sidebar_channel_menu/index.ts
  components/suggestion/search_channel_with_permissions_provider.jsx
  components/suggestion/search_channel_with_permissions_provider.test.jsx
  components/team_general_tab/index.js
  components/textbox/index.ts
  components/tutorial/index.tsx
  packages/mattermost-redux/src/reducers/entities/channels.test.js
  packages/mattermost-redux/src/reducers/entities/channels.ts
  packages/mattermost-redux/src/selectors/entities/channels.test.js
  packages/mattermost-redux/src/selectors/entities/channels.ts
  packages/mattermost-redux/src/selectors/entities/roles.test.js
  packages/mattermost-redux/src/selectors/entities/roles.ts
  packages/mattermost-redux/src/store/initial_state.ts
  packages/mattermost-redux/src/types/channels.ts
  packages/mattermost-redux/src/utils/channel_utils.ts
  packages/mattermost-redux/src/utils/post_utils.test.js
  packages/mattermost-redux/src/utils/post_utils.ts
  utils/channel_utils.jsx
  utils/post_utils.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8346 Translations update from Weblate
  i18n/bg.json
  i18n/de.json
  i18n/en_AU.json
  i18n/es.json
  i18n/fr.json
  i18n/hu.json
  i18n/ja.json
  i18n/nl.json
  i18n/ro.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
  i18n/zh-CN.json
Labels: 2: Dev Review, 3: QA Review, release-note-none

#8274 Add ellipsis to channel suggestions and channel selector in forms and interactive dialogs
  components/add_user_to_channel_modal/add_user_to_channel_modal.jsx
  components/quick_switch_modal/__snapshots__/quick_switch_modal.test.tsx.snap
  components/quick_switch_modal/index.tsx
  components/quick_switch_modal/quick_switch_modal.tsx
  components/suggestion/at_mention_provider/__snapshots__/at_mention_suggestion.test.tsx.snap
  components/suggestion/at_mention_provider/at_mention_suggestion.jsx
  components/suggestion/at_mention_provider/at_mention_suggestion.test.tsx
  components/suggestion/channel_mention_provider.jsx
  components/suggestion/generic_channel_provider.jsx
  components/suggestion/generic_user_provider.jsx
  components/suggestion/menu_action_provider.jsx
  components/suggestion/search_channel_suggestion/__snapshots__/search_channel_suggestion.test.tsx.snap
  components/suggestion/search_channel_suggestion/search_channel_suggestion.tsx
  components/suggestion/search_channel_with_permissions_provider.jsx
  components/suggestion/search_user_provider.jsx
  components/suggestion/switch_channel_provider.jsx
  components/suggestion/switch_team_provider.jsx
  components/suggestion/timezone_provider.jsx
  e2e/cypress/integration/archived_channel/archived_leave_channel_spec.js
  e2e/cypress/integration/custom_status/custom_status_5_spec.js
  e2e/cypress/integration/enterprise/accessibility/accessibility_input_fields_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/guest_add_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/guest_identification_ui_spec.js
  e2e/cypress/integration/interactive_dialog/scrollable_spec.js
  e2e/cypress/integration/messaging/group_message_spec.js
  e2e/cypress/integration/search/post_search_display_spec.js
  e2e/cypress/integration/search/search_user_file_spec.js
  e2e/cypress/integration/search/search_user_post_spec.js
  e2e/cypress/integration/search_autocomplete/scroll_spec.js
  i18n/en.json
  sass/components/_channel-switcher.scss
  sass/components/_mentions.scss
  sass/components/_popover.scss
  sass/components/_status-icon.scss
  sass/components/_suggestion-list.scss
  utils/utils.jsx
Labels: 4: Reviews Complete, release-note-none

#8348 Fix Command parser
  components/suggestion/command_provider/app_command_parser/app_command_parser.ts
Labels: 4: Reviews Complete, release-note-none

#8219 Add markdown to apps field descriptions in forms and commands
  components/apps_form/apps_form.test.jsx
  components/apps_form/apps_form.tsx
  components/apps_form/apps_form_field/apps_form_field.test.tsx
  components/apps_form/apps_form_field/apps_form_field.tsx
  components/suggestion/command_provider/command_provider.test.tsx
Labels: 1: UX Review, 4: Reviews Complete, release-note

#8353 Lock CI from /release-5.37
  .circleci/config.yml
  .gitlab-ci.yml
Labels: release-note-none

#8355 Automated cherry pick of #8278
  actions/views/threads.ts
  components/sidebar/sidebar_channel_list/index.ts
  components/sidebar/sidebar_channel_list/sidebar_channel_list.test.tsx
  components/sidebar/sidebar_channel_list/sidebar_channel_list.tsx
  components/threading/global_threads/global_threads.tsx
  components/threading/global_threads_link/global_threads_link.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8354 Automated cherry pick of #8333
  components/threading/global_threads/global_threads.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8307 [MM-36128] Enable 'Set Status' button if the custom status hasn't changed from currently set status
  components/custom_status/custom_status.scss
  components/custom_status/custom_status_modal.tsx
Labels: 4: Reviews Complete, release-note-none

#8357 Update NOTICE.txt
  NOTICE.txt
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#8358 Automated cherry pick of #8357
  NOTICE.txt
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8236 [MM-34330] Migrate 'components/at_mention' and associated tests to TypeScript
  components/at_mention/__snapshots__/at_mention.test.tsx.snap
  components/at_mention/at_mention.test.tsx
  components/at_mention/at_mention.tsx
  components/at_mention/index.tsx
Labels: 4: Reviews Complete, release-note-none

#8356 [MM-35249] Ensure window size is at least 0 before checking for mobile
  utils/utils.jsx
Labels: 4: Reviews Complete, release-note-none

#8319 Fixed: overflowing text now truncates
  sass/layout/_sidebar-left.scss
Labels: 4: Reviews Complete, release-note-none

#8367 Automated cherry pick of #8219
  components/apps_form/apps_form.test.jsx
  components/apps_form/apps_form.tsx
  components/apps_form/apps_form_field/apps_form_field.test.tsx
  components/apps_form/apps_form_field/apps_form_field.tsx
  components/suggestion/command_provider/command_provider.test.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8360 Allow uploading .jpeg files on Linux
  components/user_settings/general/user_settings_general.tsx
  i18n/en.json
Labels: 4: Reviews Complete, AutoMerge, CherryPick/Approved, release-note-none

#8368 Automated cherry pick of #8360
  components/user_settings/general/user_settings_general.tsx
  i18n/en.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8369 Automated cherry pick of #8360
  components/user_settings/general/user_settings_general.tsx
  i18n/en.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8339 [MM-36809] Suggest only skintones along user skin tone selection
  components/suggestion/emoticon_provider.jsx
  packages/mattermost-redux/src/types/emojis.ts
  utils/emoticons.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, QA Review Done, Setup Cloud Test Server, release-note-none

#8337 [MM-36734] - Include Support Email step to Cloud Admin Onboarding
  components/next_steps_view/steps.test.tsx
  components/next_steps_view/steps.ts
  components/next_steps_view/steps/enter_support_email/enter_support_email.scss
  components/next_steps_view/steps/enter_support_email/enter_support_email.tsx
  components/next_steps_view/steps/invite_members_step/invite_members_step.tsx
  e2e/cypress/integration/enterprise/cloud/onboarding/enter_support_email_spec.js
  i18n/en.json
  i18n/en_AU.json
  packages/mattermost-redux/src/action_types/admin.ts
  packages/mattermost-redux/src/actions/admin.ts
  packages/mattermost-redux/src/client/client4.ts
  utils/constants.jsx
Labels: 2: Dev Review, 4: Reviews Complete, QA Review Done, Setup Cloud + CWS Test Server, release-note-none

#8371 Automated cherry pick of #8339
  components/suggestion/emoticon_provider.jsx
  packages/mattermost-redux/src/types/emojis.ts
  utils/emoticons.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8370 Automated cherry pick of #8339
  components/suggestion/emoticon_provider.jsx
  packages/mattermost-redux/src/types/emojis.ts
  utils/emoticons.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8335 MM-36692: tracks CRT display setting on/off
  components/user_settings/display/user_settings_display.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, release-note-none

#8374 Automated cherry pick of #8335
  components/user_settings/display/user_settings_display.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8375 Automated cherry pick of #8278
  components/threading/global_threads_link/global_threads_link.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8372 Cypress/e2e/Fixed emoji test case
  e2e/cypress/integration/emoji/custom_emoji_3_spec.js
  sass/layout/_sidebar-left.scss
Labels: 4: Reviews Complete, release-note-none

#8341 MM-36731 - ux changes to cloud starter flat fee
  components/admin_console/billing/billing_summary/billing_summary.tsx
  components/admin_console/billing/plan_details/plan_details.tsx
  components/common/radio_group.tsx
  components/purchase_modal/purchase.scss
  components/purchase_modal/purchase_modal.tsx
  i18n/en.json
  packages/mattermost-redux/src/types/cloud.ts
  utils/constants.jsx
Labels: 1: UX Review, 2: Dev Review, QA Review Done, Setup Cloud + CWS Test Server, release-note-none

#8349 [MM-36313] - Fix hardcoded value for about modal border
  sass/routes/_about-modal.scss
Labels: 4: Reviews Complete, QA Review Done, Setup Cloud Test Server, release-note-none

#8364 Add .stylelintignore
  .stylelintignore
  package.json
Labels: 4: Reviews Complete, release-note-none

#8377 Cypress/e2e: Fixed post menu test
  e2e/cypress/integration/archived_channel/post_menu_spec.js
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8148 Handle user and channels on the command provider
  actions/command.ts
  components/suggestion/channel_mention_provider.jsx
  components/suggestion/command_provider/app_command_parser/app_command_parser.test.ts
  components/suggestion/command_provider/app_command_parser/app_command_parser.ts
  components/suggestion/command_provider/app_command_parser/app_command_parser_dependencies.ts
  components/suggestion/command_provider/app_provider.tsx
  components/suggestion/command_provider/command_provider.tsx
  components/suggestion/command_provider/mentions/index.ts
  components/textbox/textbox.tsx
  utils/constants.jsx
Labels: QA Review Done, release-note

#8379 (chore) Cypress/E2E: fix e2e scripts instruction
  e2e/generate_test_cycle.js
  e2e/run_test_cycle.js
  e2e/save_report.js
Labels: 4: Reviews Complete, release-note-none

#8378 Cypress/E2E: Fix timeout error when running cypress against recently_used_emoji_spec
  e2e/cypress/integration/emoji/recently_used_emoji_spec.js
Labels: 4: Reviews Complete, release-note-none

#8380 Cypress/E2E: Upgrade Cypress to 7.7.0 and other dependencies
  e2e/package-lock.json
  e2e/package.json
Labels: 4: Reviews Complete, release-note-none

#8381 MM36936 - fix cloud subscribe api URI path
  packages/mattermost-redux/src/client/client4.ts
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud + CWS Test Server, release-note-none

#8382 Automated cherry pick of #8381
  packages/mattermost-redux/src/client/client4.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8383 Cypress/e2e/fixed markdown text and basic options test cases
  e2e/cypress/fixtures/markdown/markdown_basic.html
  e2e/cypress/integration/interactive_menu/basic_options_spec.js
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8384 Translations update from Weblate
  i18n/bg.json
  i18n/de.json
  i18n/en_AU.json
  i18n/es.json
  i18n/fr.json
  i18n/hu.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 2: Dev Review, 3: QA Review, release-note-none

#8193 Minor error fixes on command parser
  components/suggestion/command_provider/app_command_parser/app_command_parser.test.ts
  components/suggestion/command_provider/app_command_parser/app_command_parser.ts
  i18n/en.json
Labels: 4: Reviews Complete, release-note-none

#8376 [MM-36735] - Add current Cloud onboarding to self-managed
  components/channel_view/channel_view.tsx
  components/next_steps_view/__snapshots__/next_steps_view.test.tsx.snap
  components/next_steps_view/images/logo-svg.tsx
  components/next_steps_view/index.ts
  components/next_steps_view/next_steps_tips.tsx
  components/next_steps_view/next_steps_view.tsx
  components/next_steps_view/steps.test.tsx
  components/next_steps_view/steps.ts
  components/sidebar/__snapshots__/sidebar.test.tsx.snap
  components/sidebar/sidebar.tsx
  components/sidebar/sidebar_next_steps/remove_next_steps_modal.tsx
  i18n/en.json
  i18n/en_AU.json
Labels: QA Review Done, release-note-none

#8388 Automated cherry pick of #8348
  components/suggestion/command_provider/app_command_parser/app_command_parser.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8387 Check whether the list element is present or not before accessing the index
  components/suggestion/modal_suggestion_list.jsx
Labels: CherryPick/Approved, release-note-none

#8269 Handle missing field in error response
  components/apps_form/apps_form.tsx
  i18n/en.json
Labels: 4: Reviews Complete, release-note-none

#8395 Adjust feature flag language in System Console
  i18n/en.json
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#8268 [MM-36235] - Do not allow to downgrade cloud plans
  components/purchase_modal/purchase_modal.tsx
Labels: 1: UX Review, QA Deferred, release-note-none

#8260 [MM-34306] Migrate 'components/admin_console/brand_image_setting' and associated tests to TypeScript
  components/admin_console/admin_definition.jsx
  components/admin_console/brand_image_setting/__snapshots__/upload_button.test.tsx.snap
  components/admin_console/brand_image_setting/brand_image_setting.test.tsx
  components/admin_console/brand_image_setting/brand_image_setting.tsx
  components/admin_console/brand_image_setting/upload_button.test.tsx
  components/admin_console/brand_image_setting/upload_button.tsx
Labels: 4: Reviews Complete, release-note-none

#8390 Cypress/E2E: Fix failed tests from cloud run
  e2e/cypress/integration/enterprise/accessibility/accessibility_input_fields_spec.js
  e2e/cypress/integration/messaging/header_spec.js
  e2e/cypress/integration/messaging/receive_message_on_socket_reconnect_spec.js
  e2e/cypress/integration/team_settings/teams_spec.js
  e2e/cypress/integration/toast/permalink_post_with_new_message_spec.js
Labels: 3: QA Review, release-note-none

#8391 Fix dynamic and static select not being readonly
  components/apps_form/apps_form_field/apps_form_select_field.tsx
Labels: 4: Reviews Complete, release-note-none

#8362 [MM-37074] Encapsulate inserted GIFs in inline image markdown
  components/gif_picker/gif_picker.jsx
Labels: 4: Reviews Complete, release-note

#8313 MM-36547 Renamed 'Mute Channel' and 'Edit Channel Header' menus
  components/channel_header_dropdown/__snapshots__/channel_header_dropdown.test.jsx.snap
  components/channel_header_dropdown/channel_header_dropdown_items.js
  components/channel_header_dropdown/menu_items/toggle_mute_channel/toggle_mute_channel.test.tsx
  components/channel_header_dropdown/menu_items/toggle_mute_channel/toggle_mute_channel.tsx
  i18n/en.json
Labels: 4: Reviews Complete, release-note

#8404 [Re: MM-35696]: Expose Timestamp and ReactIntl for usage in plugins
  components/timestamp/timestamp.tsx
  plugins/export.js
Labels: 4: Reviews Complete, release-note

#8397 Add promise rejection handler for custom brand image retrieval
  components/admin_console/brand_image_setting/brand_image_setting.tsx
Labels: 4: Reviews Complete, release-note-none

#8410 [MM-34895] send timestamp after last_reply_at when viewing thread
  actions/websocket_actions.jsx
Labels: 4: Reviews Complete, release-note-none

#8129 Added functionality to archive/unarchive teams from system console
  actions/websocket_actions.jsx
  components/admin_console/team_channel_settings/team/details/__snapshots__/team_details.test.jsx.snap
  components/admin_console/team_channel_settings/team/details/__snapshots__/team_profile.test.jsx.snap
  components/admin_console/team_channel_settings/team/details/index.js
  components/admin_console/team_channel_settings/team/details/team_details.jsx
  components/admin_console/team_channel_settings/team/details/team_details.test.jsx
  components/admin_console/team_channel_settings/team/details/team_profile.jsx
  components/admin_console/team_channel_settings/team/details/team_profile.test.jsx
  components/admin_console/team_channel_settings/team/list/team_list.scss
  components/admin_console/team_channel_settings/team/list/team_list.tsx
  components/backstage/components/backstage_navbar.jsx
  i18n/en.json
  packages/mattermost-redux/src/action_types/teams.ts
  packages/mattermost-redux/src/actions/teams.test.js
  packages/mattermost-redux/src/actions/teams.ts
  packages/mattermost-redux/src/client/client4.ts
  packages/mattermost-redux/src/reducers/entities/teams.ts
Labels: 4: Reviews Complete, AutoMerge, Setup Cloud Test Server, release-note

#8416 Fix master lint issue.
  components/admin_console/team_channel_settings/team/details/__snapshots__/team_details.test.jsx.snap
  components/admin_console/team_channel_settings/team/details/__snapshots__/team_profile.test.jsx.snap
  components/admin_console/team_channel_settings/team/list/team_list.scss
  e2e/utils/artifacts.js
Labels: release-note-none

#8415 Translations update from Weblate
  i18n/bg.json
  i18n/de.json
  i18n/en_AU.json
  i18n/es.json
  i18n/fr.json
  i18n/hu.json
  i18n/ja.json
  i18n/nl.json
  i18n/tr.json
Labels: 2: Dev Review, 3: QA Review, release-note-none

#8398 Add balancing call to TestHelper.tearDown() in mattermost-redux test
  packages/mattermost-redux/src/selectors/entities/integrations.test.js
Labels: 4: Reviews Complete, release-note-none

#8350 MM-36696: global threads list now virtualized
  components/threading/global_threads/global_threads.tsx
  components/threading/global_threads/thread_item/__snapshots__/thread_item.test.tsx.snap
  components/threading/global_threads/thread_item/index.ts
  components/threading/global_threads/thread_item/thread_item.scss
  components/threading/global_threads/thread_item/thread_item.test.tsx
  components/threading/global_threads/thread_item/thread_item.tsx
  components/threading/global_threads/thread_list/__snapshots__/thread_list.test.tsx.snap
  components/threading/global_threads/thread_list/thread_list.test.tsx
  components/threading/global_threads/thread_list/thread_list.tsx
  components/threading/global_threads/thread_list/virtualized_thread_list.tsx
  components/threading/global_threads/thread_list/virtualized_thread_list_row.tsx
  components/threading/global_threads/thread_menu/thread_menu.tsx
  components/threading/hooks.ts
  components/threading/thread_viewer/thread_viewer.tsx
  package-lock.json
  package.json
  stores/hooks.ts
  types/external/dynamic-virtualized-list.d.ts
Labels: 4: Reviews Complete, release-note-none

#8411 MM-37048 Temporarily store drafts in localStorage and rehydrate manually to fix persistence issues
  actions/storage.js
  actions/views/create_comment.jsx
  components/create_comment/create_comment.jsx
  components/create_post/create_post.jsx
  components/create_post/index.js
Labels: 4: Reviews Complete, QA Deferred, release-note-none

#8417 Cypress/E2E: Fix issue when installing e2e packages
  e2e/package-lock.json
Labels: 4: Reviews Complete, release-note-none

#8426 Automated cherry pick of #8411
  actions/storage.js
  actions/views/create_comment.jsx
  components/create_comment/create_comment.jsx
  components/create_post/create_post.jsx
  components/create_post/index.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8427 Automated cherry pick of #8350
  components/threading/global_threads/global_threads.tsx
  components/threading/global_threads/thread_item/__snapshots__/thread_item.test.tsx.snap
  components/threading/global_threads/thread_item/index.ts
  components/threading/global_threads/thread_item/thread_item.scss
  components/threading/global_threads/thread_item/thread_item.test.tsx
  components/threading/global_threads/thread_item/thread_item.tsx
  components/threading/global_threads/thread_list/__snapshots__/thread_list.test.tsx.snap
  components/threading/global_threads/thread_list/thread_list.test.tsx
  components/threading/global_threads/thread_list/thread_list.tsx
  components/threading/global_threads/thread_list/virtualized_thread_list.tsx
  components/threading/global_threads/thread_list/virtualized_thread_list_row.tsx
  components/threading/global_threads/thread_menu/thread_menu.tsx
  components/threading/hooks.ts
  components/threading/thread_viewer/thread_viewer.tsx
  package-lock.json
  package.json
  stores/hooks.ts
  types/external/dynamic-virtualized-list.d.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8211 MM-36085: Split out System/Team Schemes from license feature checks.
  components/admin_console/admin_definition.jsx
  components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.jsx.snap
  components/admin_console/feature_discovery/features/index.ts
  components/admin_console/feature_discovery/features/permissions.tsx
  components/admin_console/permission_schemes_settings/permission_system_scheme_settings/permission_system_scheme_settings.jsx
  i18n/en.json
Labels: release-note

#8428 Fix draft removal on create_comment and unload in create_post
  actions/views/create_comment.jsx
  components/create_post/create_post.jsx
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#8429 Automated cherry pick of #8428
  actions/views/create_comment.jsx
  components/create_post/create_post.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8359 Update CRT docs link in notice
  components/collapsed_reply_threads_modal/collapsed_reply_threads_modal.tsx
  i18n/en.json
Labels: 4: Reviews Complete, release-note-none

#8432 Automated cherry pick of #8359
  components/collapsed_reply_threads_modal/collapsed_reply_threads_modal.tsx
  i18n/en.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8342 MM-35722: CRT, post click open thread
  components/needs_team/needs_team.test.tsx
  components/post_view/post/post.jsx
  components/post_view/post_header/post_header_custom_status.tsx
  components/post_view/post_info/post_info.tsx
  components/root/root.test.jsx
  components/threading/channel_threads/thread_footer/thread_footer.tsx
  sass/components/_post.scss
  sass/layout/_webhooks.scss
  utils/utils.jsx
Labels: 4: Reviews Complete, release-note-none

#8436 Automated cherry pick of #8342
  components/needs_team/needs_team.test.tsx
  components/post_view/post/post.jsx
  components/post_view/post_header/post_header_custom_status.tsx
  components/post_view/post_info/post_info.tsx
  components/root/root.test.jsx
  components/threading/channel_threads/thread_footer/thread_footer.tsx
  sass/components/_post.scss
  sass/layout/_webhooks.scss
  utils/utils.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8422 Cypress/E2E Maintenance: Fix failing tests
  e2e/cypress/integration/accessibility/accessibility_dropdowns_spec.js
  e2e/cypress/integration/account_settings/display/code_theme_colors_spec.js
  e2e/cypress/integration/enterprise/extend_session/not_extended_when_disabled/with_ldap_login_spec.js
  e2e/cypress/integration/enterprise/group_mentions/group_mentions_posts_spec.js
  e2e/cypress/integration/enterprise/ldap_group/group_mentions_spec.js
  e2e/cypress/integration/messaging/channel_menu_spec.js
  e2e/cypress/support/api/preference.d.ts
  e2e/cypress/support/api/preference.js
  e2e/cypress/support/api/user.d.ts
  e2e/cypress/support/api/user.js
  e2e/cypress/support/index.js
Labels: 4: Reviews Complete, release-note-none

#8423 MM-36739 Remove getNeededCustomEmojis
  packages/mattermost-redux/src/actions/posts.test.js
  packages/mattermost-redux/src/actions/posts.ts
Labels: 4: Reviews Complete, release-note-none

#8420 [MM-35552] Prevent opening of Search Tabs on Chrome when using Account Settings modal keyboard shortcut
  components/legacy_sidebar/header/dropdown/sidebar_header_dropdown.jsx
  components/main_menu/main_menu.jsx
  components/user_settings/modal/user_settings_modal.tsx
Labels: 4: Reviews Complete, QA Review Done, release-note-none

#8430 MM-36934 Disable unreads filter when unreads are grouped separately
  selectors/views/channel_sidebar.test.js
  selectors/views/channel_sidebar.ts
Labels: 4: Reviews Complete, release-note

#8407 MM-37130 Adding basic global header.
  babel.config.js
  components/custom_status/custom_status.scss
  components/global/assets.tsx
  components/global/global_header.test.tsx
  components/global/global_header.tsx
  components/global/hooks.tsx
  components/global/product_switcher.tsx
  components/legacy_sidebar/header/dropdown/index.js
  components/legacy_sidebar/header/dropdown/sidebar_header_dropdown.jsx
  components/legacy_sidebar/header/sidebar_header_dropdown_button.jsx
  components/needs_team/needs_team.tsx
  components/root/index.js
  components/root/root.jsx
  components/root/root.test.jsx
  components/sidebar/sidebar_header/index.ts
  components/sidebar/sidebar_header/sidebar_header.tsx
  components/status_dropdown/status_dropdown.tsx
  components/user_settings/display/__snapshots__/user_settings_display.test.tsx.snap
  components/user_settings/display/index.ts
  components/user_settings/display/user_settings_display.test.tsx
  components/user_settings/display/user_settings_display.tsx
  components/widgets/menu/menu.tsx
  i18n/en.json
  package-lock.json
  package.json
  plugins/pluggable/pluggable.jsx
  plugins/registry.js
  sass/base/_structure.scss
  sass/layout/_headers.scss
  sass/layout/_sidebar-right.scss
  selectors/global_header.ts
  types/store/plugins.ts
  utils/constants.jsx
  utils/url.tsx
  utils/utils.jsx
Labels: 4: Reviews Complete, release-note

#8424 MM-36854: Export ChannelInviteModal and ChannelMembersModal for plugins to use
  plugins/export.js
Labels: 4: Reviews Complete, release-note

#8425 [MM-37189] fix style issue in ProductNoticesModal
  components/generic_modal.scss
  components/product_notices_modal/product_notices_modal.scss
Labels: 4: Reviews Complete, Setup HA Cloud Test Server, release-note

#8446 Automated cherry pick of #8425
  components/generic_modal.scss
  components/product_notices_modal/product_notices_modal.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8445 Merge 6.0 back into master
  components/admin_console/admin_definition.jsx
  components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.jsx.snap
  components/admin_console/feature_discovery/features/index.ts
  components/admin_console/feature_discovery/features/permissions.tsx
  components/admin_console/permission_schemes_settings/permission_system_scheme_settings/permission_system_scheme_settings.jsx
  i18n/en.json
Labels: release-note-none

#8108 Set default value of bool form field to false
  components/apps_form/__snapshots__/apps_form_component.test.tsx.snap
  components/apps_form/apps_form_component.test.tsx
  components/apps_form/apps_form_component.tsx
  components/apps_form/apps_form_container.tsx
Labels: 4: Reviews Complete, release-note-none

#8451 fix: Subscription title in system console billing is singular
  components/admin_console/billing/billing_subscriptions/index.tsx
  i18n/en.json
Labels: 4: Reviews Complete, QA Review Done, Setup Cloud + CWS Test Server, release-note

#8455 Translations update from Weblate
  i18n/bg.json
  i18n/de.json
  i18n/en_AU.json
  i18n/es.json
  i18n/fr.json
  i18n/hu.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 2: Dev Review, 3: QA Review, release-note-none

#8450 MM-36573 Fix console error when viewing channel on an unsupported CRT client while webapp is open with CRT on
  packages/mattermost-redux/src/actions/threads.ts
Labels: 4: Reviews Complete, QA Deferred, release-note-none

#8456 Automated cherry pick of #8450
  packages/mattermost-redux/src/actions/threads.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8438 [MM-37106] - Can't return to Getting Started flow from Threads view
  components/threading/global_threads/global_threads.tsx
Labels: 4: Reviews Complete, CherryPick/Candidate, QA Review Done, Setup HA Cloud Test Server, release-note-none

#8448 Fixes Thread in thread viewer displayed vertically
  components/threading/global_threads/thread_pane/thread_pane.scss
Labels: 4: Reviews Complete, release-note-none

#8458 Automated cherry pick of #8448
  components/threading/global_threads/thread_pane/thread_pane.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8461 Cherry pick slow typing draft fixes to release-5.37
  actions/storage.js
  actions/views/create_comment.jsx
  actions/views/create_comment.test.jsx
  components/create_comment/create_comment.jsx
  components/create_comment/create_comment.test.jsx
  components/create_comment/index.js
  components/create_post/create_post.jsx
  components/create_post/index.js
  components/threading/thread_viewer/thread_viewer.tsx
Labels: release-note

#8460 Cherry pick slow typing draft fixes to release-5.31
  actions/storage.js
  actions/views/create_comment.jsx
  actions/views/create_comment.test.jsx
  components/create_comment/create_comment.jsx
  components/create_comment/create_comment.test.jsx
  components/create_comment/index.js
  components/create_post/create_post.jsx
  components/create_post/index.js
Labels: release-note

#8413 MM-35392 Load thread unreads for other teams on app load
  components/needs_team/index.ts
  components/needs_team/needs_team.test.tsx
  components/needs_team/needs_team.tsx
  components/sidebar/sidebar_channel_list/sidebar_channel_list.test.tsx
  components/team_members_dropdown/index.ts
  components/team_members_dropdown/team_members_dropdown.test.tsx
  components/team_members_dropdown/team_members_dropdown.tsx
  packages/mattermost-redux/src/actions/channels.test.js
  packages/mattermost-redux/src/actions/posts.test.js
  packages/mattermost-redux/src/actions/preferences.test.js
  packages/mattermost-redux/src/actions/teams.test.js
  packages/mattermost-redux/src/actions/teams.ts
  packages/mattermost-redux/src/actions/users.test.js
  packages/mattermost-redux/src/actions/users.ts
  packages/mattermost-redux/src/client/client4.ts
  packages/mattermost-redux/src/reducers/entities/threads.ts
  packages/mattermost-redux/src/types/teams.ts
  packages/mattermost-redux/test/test_helper.js
Labels: 4: Reviews Complete, release-note-none

#8408 MM-36756 Add new component for positioning SuggestionList in RHS
  components/apps_form/apps_form_field/apps_form_field.tsx
  components/create_comment/__snapshots__/create_comment.test.jsx.snap
  components/create_comment/create_comment.jsx
  components/suggestion/rhs_suggestion_list.tsx
  components/suggestion/suggestion_list.d.ts
  components/suggestion/suggestion_list.jsx
  components/textbox/textbox.tsx
  utils/utils.jsx
Labels: 4: Reviews Complete, release-note-none

#8440 [MM-36736] - Remove current self-managed initial product tour
  components/channel_view/channel_view.tsx
  components/channel_view/index.ts
  components/sidebar/sidebar_channel/sidebar_channel_link/index.ts
  components/sidebar/sidebar_channel/sidebar_channel_link/sidebar_channel_link.test.tsx
  components/sidebar/sidebar_channel/sidebar_channel_link/sidebar_channel_link.tsx
  components/tutorial/index.tsx
  components/tutorial/tutorial_intro_screens/__snapshots__/tutorial_intro_screens.test.tsx.snap
  components/tutorial/tutorial_intro_screens/index.tsx
  components/tutorial/tutorial_intro_screens/tutorial_intro_screens.test.tsx
  components/tutorial/tutorial_intro_screens/tutorial_intro_screens.tsx
  components/tutorial/tutorial_view.tsx
  i18n/en.json
  sass/components/_tutorial.scss
  utils/constants.jsx
Labels: CherryPick/Candidate, QA Review Done, release-note-none

#8465 Translations update from Weblate
  i18n/bg.json
  i18n/de.json
  i18n/en_AU.json
  i18n/es.json
  i18n/fr.json
  i18n/hu.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 2: Dev Review, 3: QA Review, release-note-none

#8462 Automated cherry pick of #8413
  components/needs_team/index.ts
  components/needs_team/needs_team.test.tsx
  components/needs_team/needs_team.tsx
  components/sidebar/sidebar_channel_list/sidebar_channel_list.test.tsx
  components/team_members_dropdown/index.ts
  components/team_members_dropdown/team_members_dropdown.test.tsx
  components/team_members_dropdown/team_members_dropdown.tsx
  packages/mattermost-redux/src/actions/channels.test.js
  packages/mattermost-redux/src/actions/posts.test.js
  packages/mattermost-redux/src/actions/preferences.test.js
  packages/mattermost-redux/src/actions/teams.test.js
  packages/mattermost-redux/src/actions/teams.ts
  packages/mattermost-redux/src/actions/users.test.js
  packages/mattermost-redux/src/actions/users.ts
  packages/mattermost-redux/src/client/client4.ts
  packages/mattermost-redux/src/reducers/entities/threads.ts
  packages/mattermost-redux/src/types/teams.ts
  packages/mattermost-redux/test/test_helper.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8449 MM-377220 Fix theming and stying of Add Users to Channel modals
  components/channel_invite_modal/__snapshots__/channel_invite_modal.test.tsx.snap
  components/channel_invite_modal/channel_invite_modal.tsx
  components/multiselect/multiselect.tsx
  e2e/cypress/integration/enterprise/accessibility/accessibility_modals_dialogs_spec.js
  e2e/cypress/integration/messaging/focus_move_spec.js
  e2e/cypress/integration/notifications/browser_tab_notification_spec.js
  sass/components/_channel-invite-modal.scss
  sass/components/_channel-switcher.scss
  sass/components/_module.scss
Labels: 4: Reviews Complete, QA Review Done, Setup Cloud Test Server, release-note

#8464 Automated cherry pick of #8440
  components/channel_view/channel_view.tsx
  components/channel_view/index.ts
  components/sidebar/sidebar_channel/sidebar_channel_link/index.ts
  components/sidebar/sidebar_channel/sidebar_channel_link/sidebar_channel_link.test.tsx
  components/sidebar/sidebar_channel/sidebar_channel_link/sidebar_channel_link.tsx
  components/tutorial/index.tsx
  components/tutorial/tutorial_intro_screens/__snapshots__/tutorial_intro_screens.test.tsx.snap
  components/tutorial/tutorial_intro_screens/index.tsx
  components/tutorial/tutorial_intro_screens/tutorial_intro_screens.test.tsx
  components/tutorial/tutorial_intro_screens/tutorial_intro_screens.tsx
  components/tutorial/tutorial_view.tsx
  i18n/en.json
  sass/components/_tutorial.scss
  utils/constants.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8468 Automated cherry pick of #8449
  components/channel_invite_modal/__snapshots__/channel_invite_modal.test.tsx.snap
  components/channel_invite_modal/channel_invite_modal.tsx
  components/multiselect/multiselect.tsx
  e2e/cypress/integration/enterprise/accessibility/accessibility_modals_dialogs_spec.js
  e2e/cypress/integration/messaging/focus_move_spec.js
  e2e/cypress/integration/notifications/browser_tab_notification_spec.js
  sass/components/_channel-invite-modal.scss
  sass/components/_channel-switcher.scss
  sass/components/_module.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8437 [MM-37105] - Onboarding comes back after team or thread view switch
  components/channel_layout/center_channel/center_channel.test.tsx
  components/channel_layout/center_channel/center_channel.tsx
  components/channel_layout/center_channel/index.ts
  components/channel_view/__snapshots__/channel_view.test.tsx.snap
  components/channel_view/channel_view.tsx
  components/channel_view/index.ts
Labels: 4: Reviews Complete, CherryPick/Approved, QA Review Done, release-note-none

#8442 [MM-37064] - Onboarding flow is showing for existing users
  components/next_steps_view/steps.ts
  components/sidebar/sidebar_next_steps/remove_next_steps_modal.tsx
  components/sidebar/sidebar_next_steps/sidebar_next_steps.tsx
  i18n/en.json
  i18n/en_AU.json
Labels: 3: QA Review, CherryPick/Approved, Setup HA Cloud Test Server, release-note-none

#8469 Automated cherry pick of #8437
  components/channel_layout/center_channel/center_channel.test.tsx
  components/channel_layout/center_channel/center_channel.tsx
  components/channel_layout/center_channel/index.ts
  components/channel_view/__snapshots__/channel_view.test.tsx.snap
  components/channel_view/channel_view.tsx
  components/channel_view/index.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8470 Automated cherry pick of #8442
  components/next_steps_view/steps.ts
  components/sidebar/sidebar_next_steps/remove_next_steps_modal.tsx
  components/sidebar/sidebar_next_steps/sidebar_next_steps.tsx
  i18n/en.json
  i18n/en_AU.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8472 Automated cherry pick of #8438
  components/threading/global_threads/global_threads.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8434 fix: drop manual capitalization in global threads
  components/threading/global_threads/thread_item/__snapshots__/thread_item.test.tsx.snap
  components/threading/global_threads/thread_item/thread_item.tsx
Labels: 4: Reviews Complete, release-note-none

#8474 Automated cherry pick of #8434
  components/threading/global_threads/thread_item/__snapshots__/thread_item.test.tsx.snap
  components/threading/global_threads/thread_item/thread_item.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8447 Fixes global threads crash on md images
  components/threading/global_threads/thread_item/__snapshots__/thread_item.test.tsx.snap
  components/threading/global_threads/thread_item/thread_item.tsx
Labels: 4: Reviews Complete, release-note-none

#8476 Automated cherry pick of #8447
  components/threading/global_threads/thread_item/__snapshots__/thread_item.test.tsx.snap
  components/threading/global_threads/thread_item/thread_item.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8406 [MM-37108] Only make request if server is enterprise ready
  components/admin_console/license_settings/license_settings.jsx
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#8477 Automated cherry pick of #8406
  components/admin_console/license_settings/license_settings.jsx
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8441 MM-36765: fixes threads crashing when LEAVE_CHANNEL
  components/rhs_header_post/index.ts
  components/threading/thread_viewer/thread_viewer.tsx
  packages/mattermost-redux/src/reducers/entities/threads.test.js
  packages/mattermost-redux/src/reducers/entities/threads.ts
Labels: 4: Reviews Complete, release-note-none

#8471 MM-37422: Fix Safari overflow scrolling issue
  components/sidebar_right/sidebar_right.jsx
  components/threading/thread_viewer/thread_viewer.tsx
Labels: 4: Reviews Complete, release-note

#8409 Standardize name of suggestionListPosition
  components/__snapshots__/textbox.test.tsx.snap
  components/add_user_to_channel_modal/__snapshots__/add_user_to_channel_modal.test.jsx.snap
  components/add_user_to_channel_modal/add_user_to_channel_modal.jsx
  components/admin_console/user_autocomplete_setting/user_autocomplete_setting.jsx
  components/autocomplete_selector.jsx
  components/autocomplete_selector.test.jsx
  components/edit_channel_header_modal/__snapshots__/edit_channel_header_modal.test.jsx.snap
  components/edit_channel_header_modal/edit_channel_header_modal.jsx
  components/edit_post_modal/__snapshots__/edit_post_modal.test.tsx.snap
  components/edit_post_modal/edit_post_modal.tsx
  components/interactive_dialog/dialog_element/dialog_element.jsx
  components/quick_switch_modal/__snapshots__/quick_switch_modal.test.tsx.snap
  components/quick_switch_modal/quick_switch_modal.tsx
  components/suggestion/modal_suggestion_list.jsx
  components/suggestion/rhs_suggestion_list.tsx
  components/suggestion/suggestion_box.jsx
  components/suggestion/suggestion_list.d.ts
  components/suggestion/suggestion_list.jsx
  components/textbox.test.tsx
  components/textbox/textbox.tsx
  plugins/export.js
  plugins/textbox/index.test.tsx
  plugins/textbox/index.tsx
Labels: 4: Reviews Complete, release-note-none

#8481 Automated cherry pick of #8471
  components/sidebar_right/sidebar_right.jsx
  components/threading/thread_viewer/thread_viewer.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note

#8482 Automated cherry pick of #8441
  components/rhs_header_post/index.ts
  components/threading/thread_viewer/thread_viewer.tsx
  packages/mattermost-redux/src/reducers/entities/threads.test.js
  packages/mattermost-redux/src/reducers/entities/threads.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8320 MM-36248 Fix GitLab Button Color and Text not reflecting in UI
  components/login/login_controller/__snapshots__/login_controller.test.jsx.snap
  components/login/login_controller/index.js
  components/login/login_controller/login_controller.jsx
  components/login/login_controller/login_controller.test.jsx
  packages/mattermost-redux/src/types/config.ts
Labels: 4: Reviews Complete, release-note

#8483 MM-37042 Add "playbooks" and "boards" to restricted team URLs list
  utils/constants.jsx
Labels: 4: Reviews Complete, release-note-none

#8400 [MM-36463] Promoting beta features to GA
  components/admin_console/__snapshots__/message_export_settings.test.jsx.snap
  components/admin_console/admin_definition.jsx
  components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.jsx.snap
  components/admin_console/custom_terms_of_service_settings/__snapshots__/custom_terms_of_service_settings.test.tsx.snap
  components/admin_console/custom_terms_of_service_settings/custom_terms_of_service_settings.tsx
  components/admin_console/message_export_settings.jsx
  components/admin_console/system_roles/__snapshots__/system_roles.test.tsx.snap
  components/admin_console/system_roles/system_roles.tsx
  i18n/en.json
Labels: 2: Dev Review, release-note

#8454 [MM-37278] Removing data retention feature flag
  components/admin_console/admin_definition.jsx
  components/admin_console/admin_sidebar/admin_sidebar.test.jsx
  e2e/cypress/integration/enterprise/system_console/compliance/data_retention_policies_spec.js
Labels: 4: Reviews Complete, CherryPick/Approved, QA Review Done, Setup Cloud Test Server, release-note

#8489 [MM-37118] Don't mark channel as read for reply posts with CRT on
  actions/new_post.ts
Labels: 4: Reviews Complete, release-note-none

#8488 [MM-32187]fix deleted message timestamp position issue
  components/post_view/post_time/post_time.tsx
Labels: 4: Reviews Complete, release-note

#8394 MM36866 - mid month proration UX changes to purchase modal
  components/admin_console/billing/billing_subscriptions/billing_subscriptions.tsx
  components/admin_console/billing/billing_subscriptions/index.tsx
  components/admin_console/billing/plan_details/index.tsx
  components/admin_console/billing/plan_details/plan_details.tsx
  components/purchase_modal/icon_message.tsx
  components/purchase_modal/index.ts
  components/purchase_modal/process_payment_setup.tsx
  components/purchase_modal/purchase.scss
  components/purchase_modal/purchase_modal.tsx
  i18n/bg.json
  i18n/de.json
  i18n/en.json
  i18n/en_AU.json
  i18n/es.json
  i18n/fr.json
  i18n/hu.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
  i18n/zh-CN.json
  utils/constants.jsx
Labels: UX deferred, release-note-none

#8311 Block only file drops, not all the kind of drops (from drag and drops)
  components/root/root.jsx
Labels: 4: Reviews Complete, release-note-none

#8487 MM-37457 Remove target blank and change routes to match new plan.
  components/global/product_switcher.tsx
Labels: 2: Dev Review, release-note-none

#8457 Fix console errors
  components/textbox/textbox.tsx
  components/user_settings/display/user_settings_theme/__snapshots__/user_settings_theme.test.jsx.snap
  components/user_settings/display/user_settings_theme/user_settings_theme.jsx
Labels: 2: Dev Review, QA Review Done, Setup Cloud Test Server, release-note-none

#8444 Cypress/E2E Maintenance: Remove old Data Retention Policy
  e2e/cypress/integration/enterprise/system_console/settings_spec.js
  e2e/cypress/integration/enterprise/system_console/sidebar_link_navigation_spec.js
  e2e/cypress/integration/enterprise/visual_regression/system_console/compliance_section_spec.js
  e2e/cypress/integration/system_console/feature_discovery_spec.js
Labels: 4: Reviews Complete, release-note-none

#8402 Add Metropolis font and apply to headings
  components/about_build_modal/__snapshots__/about_build_modal.test.tsx.snap
  components/about_build_modal/about_build_modal.tsx
  components/about_build_modal/about_build_modal_cloud/about_build_modal_cloud.tsx
  components/common/__snapshots__/infinite_scroll.test.tsx.snap
  components/common/__snapshots__/site_name_and_description.test.tsx.snap
  components/common/site_name_and_description.test.tsx
  components/common/site_name_and_description.tsx
  components/create_team/components/__snapshots__/display_name.test.tsx.snap
  components/create_team/components/display_name.tsx
  components/create_team/components/team_url/__snapshots__/team_url.test.tsx.snap
  components/create_team/components/team_url/team_url.tsx
  components/invitation_modal/invitation_modal.scss
  components/invitation_modal/invitation_modal_guest_step/invitation_modal_guests_step.jsx
  components/invitation_modal/invitation_modal_guest_step/invitation_modal_guests_step.scss
  components/invitation_modal/invitation_modal_initial_step.scss
  components/invitation_modal/invitation_modal_members_step/invitation_modal_members_step.jsx
  components/invitation_modal/invitation_modal_members_step/invitation_modal_members_step.scss
  components/legacy_sidebar/header/sidebar_header_dropdown_button.jsx
  components/linking_landing_page/linking_landing_page.tsx
  components/loading_screen.tsx
  components/next_steps_view/__snapshots__/next_steps_view.test.tsx.snap
  components/next_steps_view/next_steps_tips.tsx
  components/next_steps_view/next_steps_view.scss
  components/next_steps_view/next_steps_view.tsx
  components/next_steps_view/steps/complete_profile_step/__snapshots__/complete_profile_step.test.tsx.snap
  components/next_steps_view/steps/complete_profile_step/complete_profile_step.scss
  components/next_steps_view/steps/complete_profile_step/complete_profile_step.tsx
  components/next_steps_view/steps/invite_members_step/invite_members_step.scss
  components/next_steps_view/steps/invite_members_step/invite_members_step.tsx
  components/no_results_indicator/no_results_indicator.scss
  components/no_results_indicator/no_results_indicator.tsx
  components/password_reset_form/__snapshots__/password_reset_form.test.js.snap
  components/password_reset_form/password_reset_form.js
  components/password_reset_send_link/__snapshots__/password_reset_send_link.test.tsx.snap
  components/password_reset_send_link/password_reset_send_link.tsx
  components/plugin_marketplace/marketplace_modal.scss
  components/search_results/search_results.tsx
  components/searchable_channel_list.jsx
  components/shortcut_key/shortcut_key.scss
  components/shortcuts_modal.jsx
  components/threading/global_threads/thread_item/thread_item.scss
  fonts/Metropolis-Light.woff2
  fonts/Metropolis-LightItalic.woff2
  fonts/Metropolis-Regular.woff2
  fonts/Metropolis-RegularItalic.woff2
  fonts/Metropolis-SemiBold.woff2
  fonts/Metropolis-SemiBoldItalic.woff2
  sass/base/_typography.scss
  sass/components/_modal.scss
  sass/components/_tutorial.scss
  sass/layout/_headers.scss
  sass/layout/_markdown.scss
  sass/layout/_sidebar-left.scss
  sass/layout/_sidebar-right.scss
  sass/routes/_get-app.scss
  sass/routes/_loading.scss
  sass/routes/_settings.scss
  sass/routes/_shortcuts-modal.scss
Labels: 4: Reviews Complete, release-note

#8401 [MM-29217] Remove Posts.ParentId
  .circleci/config.yml
  .gitlab-ci.yml
  actions/command.test.js
  actions/command.ts
  actions/global_actions.tsx
  actions/views/create_comment.jsx
  actions/views/create_comment.test.jsx
  components/create_post/create_post.jsx
  components/delete_post_modal/delete_post_modal.test.tsx
  components/permalink_view/actions.js
  components/post_view/commented_on/commented_on.test.tsx
  components/post_view/post_header/__snapshots__/post_header.test.tsx.snap
  components/post_view/post_info/__snapshots__/post_info.test.tsx.snap
  components/rhs_comment/__snapshots__/rhs_comment.test.jsx.snap
  components/rhs_comment/rhs_comment.test.jsx
  components/rhs_root_post/__snapshots__/rhs_root_post.test.jsx.snap
  components/rhs_root_post/rhs_root_post.test.jsx
  components/search_results_item/__snapshots__/search_results_item.test.jsx.snap
  components/search_results_item/search_results_item.test.jsx
  components/threading/thread_viewer/__snapshots__/thread_viewer.test.tsx.snap
  e2e/cypress/plugins/post_bot_message.js
  e2e/cypress/plugins/post_message_as.js
  e2e/webhook_serve.js
  packages/mattermost-redux/src/actions/threads.test.js
  packages/mattermost-redux/src/types/integrations.ts
  packages/mattermost-redux/src/types/posts.ts
  plugins/registry.js
  utils/test_helper.ts
Labels: 4: Reviews Complete, release-note

#8493 MM-37495: CRT, always enable mark all as unread
  components/threading/global_threads/thread_list/__snapshots__/thread_list.test.tsx.snap
  components/threading/global_threads/thread_list/thread_list.tsx
Labels: 4: Reviews Complete, release-note-none

#8496 Lock CI from /release-5.38
  .circleci/config.yml
  .gitlab-ci.yml
Labels: release-note-none

#8497 Automated cherry pick of #8454
  components/admin_console/admin_definition.jsx
  components/admin_console/admin_sidebar/admin_sidebar.test.jsx
  e2e/cypress/integration/enterprise/system_console/compliance/data_retention_policies_spec.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, do-not-merge/release-note-label-needed

#8498 Automated cherry pick of #8493
  components/threading/global_threads/thread_list/__snapshots__/thread_list.test.tsx.snap
  components/threading/global_threads/thread_list/thread_list.tsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8499 Automated cherry pick of #8489
  actions/new_post.ts
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#8500 Fixes type issue
  components/edit_post_modal/edit_post_modal.test.tsx
Labels: release-note-none

#8486 fix whitespace in refresh bar
  components/announcement_bar/version_bar/__snapshots__/version_bar.test.tsx.snap
  components/announcement_bar/version_bar/version_bar.tsx
Labels: QA Deferred, Setup Cloud Test Server, release-note

#8502 Update NOTICE.txt
  NOTICE.txt
Labels: CherryPick/Approved, release-note-none

#8507 Automated cherry pick of #8502
  NOTICE.txt
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8478 [MM-37377] - LHS does not update after Getting Started steps are complete
  components/next_steps_view/steps.test.tsx
  components/next_steps_view/steps.ts
  components/sidebar/sidebar_next_steps/remove_next_steps_modal.tsx
  e2e/cypress/integration/enterprise/cloud/onboarding/cloud_sysadmin_onboarding_spec.js
  i18n/en.json
  i18n/en_AU.json
Labels: CherryPick/Approved, QA Review Done, Setup Cloud Test Server, release-note-none

#8508 Automated cherry pick of #8478
  components/next_steps_view/steps.test.tsx
  components/next_steps_view/steps.ts
  components/sidebar/sidebar_next_steps/remove_next_steps_modal.tsx
  e2e/cypress/integration/enterprise/cloud/onboarding/cloud_sysadmin_onboarding_spec.js
  i18n/en.json
  i18n/en_AU.json
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed, release-note-none

#8511 Fix builds pointing at the wrong version
  .circleci/config.yml
  .gitlab-ci.yml
Labels: release-note-none

#8504 Cypress E2E: fixed Guest and Member invitation test cases
  e2e/cypress/integration/enterprise/guest_accounts/guest_invitation_ui_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/member_invitation_ui_spec.js
Labels: 3: QA Review, release-note-none

#8491 MM-37299 - invite members ab testing
  components/sidebar/__snapshots__/invite_members.test.tsx.snap
  components/sidebar/channel_navigator/channel_navigator.tsx
  components/sidebar/invite_members.test.tsx
  components/sidebar/invite_members_button.tsx
  components/sidebar/sidebar_category/__snapshots__/sidebar_category.test.tsx.snap
  components/sidebar/sidebar_category/sidebar_category.tsx
  components/sidebar/sidebar_channel_list/__snapshots__/sidebar_channel_list.test.tsx.snap
  components/sidebar/sidebar_channel_list/sidebar_channel_list.tsx
  i18n/en.json
  packages/mattermost-redux/src/constants/config.ts
  packages/mattermost-redux/src/selectors/entities/preferences.ts
  packages/mattermost-redux/src/types/config.ts
  sass/layout/_sidebar-left.scss
Labels: QA Review Done, Setup Cloud Test Server, release-note-none
