Repository mattermost/mattermost-webapp, pull requests merged in 2021-02, with the labels that each got.

#7397 Cypress/E2E: Remove duplicate test executions and fix TM4J key
  e2e/cypress/integration/integrations/custom_slash_commands/custom_slash_commands_spec.js
  e2e/cypress/integration/integrations/custom_slash_commands/helpers.js
  e2e/cypress/integration/integrations/custom_slash_commands/slash_commands_spec.js
Labels: 4: Reviews Complete, AutoMerge, CherryPick/Approved

#7438 Automated cherry pick of #7397
  e2e/cypress/integration/integrations/custom_slash_commands/custom_slash_commands_spec.js
  e2e/cypress/integration/integrations/custom_slash_commands/helpers.js
  e2e/cypress/integration/integrations/custom_slash_commands/slash_commands_spec.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7327 MM-31654: Update steps for google openid
  components/admin_console/admin_definition.jsx
  i18n/en.json
Labels: 4: Reviews Complete, AutoMerge

#7395 [MM-32269] System Console: TeamIcon edge cases
  components/admin_console/permission_schemes_settings/permission_team_scheme_settings/team_in_list/__snapshots__/team_in_list.test.jsx.snap
  components/admin_console/team_channel_settings/team/list/team_list.scss
  components/widgets/team_icon/__snapshots__/team_icon.test.tsx.snap
  components/widgets/team_icon/team_icon.scss
  components/widgets/team_icon/team_icon.stories.js
  components/widgets/team_icon/team_icon.tsx
  sass/components/_permissions.scss
  sass/components/_team-channel-settings.scss
Labels: 4: Reviews Complete, CherryPick/Approved

#7442 Automated cherry pick of #7395
  components/admin_console/permission_schemes_settings/permission_team_scheme_settings/team_in_list/__snapshots__/team_in_list.test.jsx.snap
  components/admin_console/team_channel_settings/team/list/team_list.scss
  components/widgets/team_icon/__snapshots__/team_icon.test.tsx.snap
  components/widgets/team_icon/team_icon.scss
  components/widgets/team_icon/team_icon.stories.js
  components/widgets/team_icon/team_icon.tsx
  sass/components/_permissions.scss
  sass/components/_team-channel-settings.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7314 [MM-31791] Support Packet Generation FRONTEND
  components/admin_console/admin_navbar_dropdown/admin_navbar_dropdown.tsx
  components/admin_console/admin_navbar_dropdown/index.ts
  components/alert_banner.tsx
  components/commercial_support_modal/__snapshots__/commercial_support_modal.test.tsx.snap
  components/commercial_support_modal/commercial_support_modal.scss
  components/commercial_support_modal/commercial_support_modal.test.tsx
  components/commercial_support_modal/commercial_support_modal.tsx
  components/commercial_support_modal/index.ts
  i18n/en.json
  package-lock.json
  package.json
  utils/constants.jsx
Labels: 4: Reviews Complete

#7444 Automated cherry pick of #7327
  components/admin_console/admin_definition.jsx
  i18n/en.json
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7443 Automated cherry pick of #7395
  components/admin_console/permission_schemes_settings/permission_team_scheme_settings/team_in_list/__snapshots__/team_in_list.test.jsx.snap
  components/admin_console/team_channel_settings/team/list/team_list.scss
  components/widgets/team_icon/__snapshots__/team_icon.test.tsx.snap
  components/widgets/team_icon/team_icon.scss
  components/widgets/team_icon/team_icon.stories.js
  components/widgets/team_icon/team_icon.tsx
  sass/components/_permissions.scss
  sass/components/_team-channel-settings.scss
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7430 Cypress/E2E: Fix MM-T2069 and OAuth, and update MM-T368
  e2e/cypress/integration/account_settings/general/email_spec.js
  e2e/cypress/integration/enterprise/system_console/sidebar_link_navigation_spec.js
  e2e/cypress/integration/enterprise/visual_regression/system_console/authentication_section_spec.js
  e2e/cypress/integration/search/clear_input_spec.js
Labels: 4: Reviews Complete

#7401 [MM-31996] Add shared user and channel indicators
  components/admin_console/team_channel_settings/channel/details/__snapshots__/channel_profile.test.tsx.snap
  components/admin_console/team_channel_settings/channel/details/channel_profile.scss
  components/admin_console/team_channel_settings/channel/details/channel_profile.test.tsx
  components/admin_console/team_channel_settings/channel/details/channel_profile.tsx
  components/admin_console/team_channel_settings/channel/list/__snapshots__/channel_list.test.tsx.snap
  components/admin_console/team_channel_settings/channel/list/channel_list.scss
  components/admin_console/team_channel_settings/channel/list/channel_list.test.tsx
  components/admin_console/team_channel_settings/channel/list/channel_list.tsx
  components/channel_header/__snapshots__/channel_header.test.jsx.snap
  components/channel_header/channel_header.js
  components/channel_header/channel_header.test.jsx
  components/channel_info_modal/channel_info_modal.jsx
  components/legacy_sidebar/sidebar_channel/__snapshots__/sidebar_channel.test.jsx.snap
  components/legacy_sidebar/sidebar_channel/index.js
  components/legacy_sidebar/sidebar_channel/sidebar_channel.jsx
  components/legacy_sidebar/sidebar_channel/sidebar_channel.test.jsx
  components/legacy_sidebar/sidebar_channel_button_or_link/__snapshots__/sidebar_channel_button_or_link.test.jsx.snap
  components/legacy_sidebar/sidebar_channel_button_or_link/__snapshots__/sidebar_channel_button_or_link_icon.test.jsx.snap
  components/legacy_sidebar/sidebar_channel_button_or_link/sidebar_channel_button_or_link.jsx
  components/legacy_sidebar/sidebar_channel_button_or_link/sidebar_channel_button_or_link.test.jsx
  components/legacy_sidebar/sidebar_channel_button_or_link/sidebar_channel_button_or_link_icon.jsx
  components/legacy_sidebar/sidebar_channel_button_or_link/sidebar_channel_button_or_link_icon.test.jsx
  components/post_view/post_header/post_header.tsx
  components/post_view/post_list_row/post_list_row.tsx
  components/rhs_root_post/rhs_root_post.jsx
  components/searchable_channel_list.jsx
  components/shared_channel_indicator.tsx
  components/shared_user_indicator.tsx
  components/sidebar/sidebar_channel/sidebar_base_channel/__snapshots__/sidebar_base_channel.test.tsx.snap
  components/sidebar/sidebar_channel/sidebar_base_channel/sidebar_base_channel.test.tsx
  components/sidebar/sidebar_channel/sidebar_base_channel/sidebar_base_channel.tsx
  components/suggestion/switch_channel_provider.jsx
  components/user_profile/__snapshots__/user_profile.test.tsx.snap
  components/user_profile/index.ts
  components/user_profile/user_profile.test.tsx
  components/user_profile/user_profile.tsx
  i18n/en.json
  package-lock.json
  package.json
  sass/components/_modal.scss
  sass/components/_post.scss
  sass/components/_suggestion-list.scss
  sass/layout/_headers.scss
  sass/layout/_legacy-sidebar-left.scss
Labels: 1: UX Review, Setup Cloud Test Server

#7429 Cypress/E2E: Fix MM-T1752 enable account creation
  components/login/login_controller/login_controller.jsx
  e2e/cypress/integration/auth_sso/authentication_1_spec.js
  e2e/cypress/integration/auth_sso/authentication_2_spec.js
  e2e/cypress/integration/auth_sso/authentication_3_spec.js
  e2e/cypress/integration/auth_sso/authentication_4_spec.js
  e2e/cypress/integration/auth_sso/hide_create_account_spec.js
  e2e/cypress/integration/enterprise/auth_sso/authentication_spec.js
  e2e/cypress/integration/enterprise/auth_sso/mfa_authentication_spec.js
  e2e/cypress/integration/enterprise/system_console/authentication_method_spec.js
  e2e/cypress/support/api/on_prem_default_config.json
Labels: 4: Reviews Complete

#7450 [MM-32499] Fix console warning
  components/profile_popover/profile_popover.jsx
Labels: 4: Reviews Complete

#7281 [MM-24635] adds an Input component with max length validation and visual feedback
  components/edit_category_modal/edit_category_modal.test.tsx
  components/edit_category_modal/edit_category_modal.tsx
  components/generic_modal.scss
  components/quick_input/__snapshots__/max_length_input.test.tsx.snap
  components/quick_input/__snapshots__/quick_input.test.jsx.snap
  components/quick_input/index.js
  components/quick_input/max_length_input.test.tsx
  components/quick_input/max_length_input.tsx
  components/quick_input/quick_input.jsx
  components/quick_input/quick_input.test.jsx
  components/suggestion/suggestion_box.jsx
Labels: 4: Reviews Complete, Setup Cloud Test Server

#7323 MM- 18893: Change text User to Member
  components/admin_console/system_users/system_users_dropdown/__snapshots__/system_users_dropdown.test.tsx.snap
  components/admin_console/system_users/system_users_dropdown/system_users_dropdown.tsx
  e2e/cypress/integration/enterprise/guest_accounts/system_console_manage_guest_spec.js
  i18n/en.json
Labels: 3: QA Review

#7452 Cypress/E2E: Fix misc failing tests
  e2e/cypress/integration/files_and_attachments/upload_files_spec.js
  e2e/cypress/integration/integrations/builtin_commands/common_commands_spec.js
  e2e/cypress/integration/integrations/outgoing_webhook/disable_override_username_profile_spec.js
  e2e/cypress/integration/interactive_menu/basic_options_spec.js
  e2e/cypress/integration/mark_as_unread/bot_post_mark_as_unread_spec.js
  e2e/cypress/integration/mark_as_unread/mark_mentions_as_unread_spec.js
  e2e/cypress/integration/messaging/long_draft_spec.js
  e2e/cypress/integration/system_console/main_menu_spec.js
Labels: 3: QA Review, 4: Reviews Complete, CherryPick/Approved

#7456 Automated cherry pick of #7452
  e2e/cypress/integration/files_and_attachments/upload_files_spec.js
  e2e/cypress/integration/integrations/builtin_commands/common_commands_spec.js
  e2e/cypress/integration/integrations/outgoing_webhook/disable_override_username_profile_spec.js
  e2e/cypress/integration/interactive_menu/basic_options_spec.js
  e2e/cypress/integration/mark_as_unread/bot_post_mark_as_unread_spec.js
  e2e/cypress/integration/mark_as_unread/mark_mentions_as_unread_spec.js
  e2e/cypress/integration/messaging/long_draft_spec.js
  e2e/cypress/integration/system_console/main_menu_spec.js
Labels: 4: Reviews Complete, AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7449 [MM-32121] Fix neverending load on one-paged search results
  components/search_results/search_results.tsx
Labels: 4: Reviews Complete, QA Review Done

#7460 Automated cherry pick of #7449
  components/search_results/search_results.tsx
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7461 Automated cherry pick of #7449
  components/search_results/search_results.tsx
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7463 Cypress/E2E: Fix dm indicator in title spec
  e2e/cypress/integration/notifications/direct_messages_do_not_add_indicator_spec.js
Labels: 4: Reviews Complete

#7464 Cypress/E2E: Potential fix for user management
  e2e/cypress/integration/system_console/user_management_spec.js
Labels: 4: Reviews Complete, AutoMerge

#7465 Cypress/E2E: Move subpath login under subpath folder
  e2e/cypress/integration/subpath/subpath_login_spec.js
Labels: 4: Reviews Complete, AutoMerge

#7466 Cypress/E2E: Added linux platform to active sessions spec
  e2e/cypress/integration/account_settings/security/active_sessions_spec.js
Labels: 4: Reviews Complete

#7472 Cypress/E2E: Fix channel switch spec
  e2e/cypress/integration/channel/channel_switcher_spec.js
Labels: 4: Reviews Complete

#7345 Removing the preview limit for PDF files
  components/pdf_preview.jsx
  components/pdf_preview.test.jsx
  i18n/en.json
Labels: 4: Reviews Complete

#7470 Cypress/E2E: Split bot accounts in lists spec
  e2e/cypress/integration/bot_accounts/in_lists_1_spec.js
  e2e/cypress/integration/bot_accounts/in_lists_2_spec.js
Labels: 4: Reviews Complete

#7471 Cypress/E2E: Fix channel settings spec
  e2e/cypress/integration/channel/channel_settings_spec.js
Labels: 4: Reviews Complete, AutoMerge

#7459 MM-32558: changed SidebarHeader class to span full-width
  sass/layout/_sidebar-left.scss
Labels: 4: Reviews Complete

#7476 added `channel.name` to the concatenated searchString
  components/suggestion/switch_channel_provider.jsx
Labels: 4: Reviews Complete, QA Review Done, Setup Cloud Test Server

#7451 [MM-32401][MM-32450] Some style fixes for the sidebar
  sass/layout/_sidebar-left.scss
  sass/responsive/_mobile.scss
Labels: 4: Reviews Complete

#7481 Automated cherry pick of #7459
  sass/layout/_sidebar-left.scss
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7483 Automated cherry pick of #7459
  sass/layout/_sidebar-left.scss
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7482 Automated cherry pick of #7451
  sass/layout/_sidebar-left.scss
  sass/responsive/_mobile.scss
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7484 Automated cherry pick of #7451
  sass/layout/_sidebar-left.scss
  sass/responsive/_mobile.scss
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7353 MM-20403 Migrate mfa/setup to typescript
  components/mfa/setup/index.ts
  components/mfa/setup/setup.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server

#7477 Cypress/E2E: Fix search box focus related failures
  e2e/cypress/integration/archived_channel/archive_channel_search_spec.js
  e2e/cypress/integration/archived_channel/archived_leave_channel_spec.js
  e2e/cypress/integration/keyboard_shortcuts/keyboard_shortcuts_one_spec.js
  e2e/cypress/integration/search_filter/edit_spec.js
  e2e/cypress/support/ui_commands.js
Labels: 4: Reviews Complete

#7486 Cypress/E2E: Fix team permissions spec
  e2e/cypress/integration/enterprise/permissions/team_permissions_spec.js
Labels: 4: Reviews Complete

#7480 [MM-32581][MM-32582] - Fix popover regressions
  components/channel_header/channel_header.js
  components/post_view/reaction/__snapshots__/reaction.test.jsx.snap
  components/post_view/reaction/reaction.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server

#7492 Automated cherry pick of #7480
  components/channel_header/channel_header.js
  components/post_view/reaction/__snapshots__/reaction.test.jsx.snap
  components/post_view/reaction/reaction.tsx
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7381 MM-32131: Fix header alignment when channel has guests
  sass/components/_popover.scss
  sass/layout/_headers.scss
Labels: 4: Reviews Complete, CherryPick/Approved

#7494 Automated cherry pick of #7381
  sass/components/_popover.scss
  sass/layout/_headers.scss
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7495 Automated cherry pick of #7381
  sass/components/_popover.scss
  sass/layout/_headers.scss
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7485 Cypress/E2E: Fix more unreads position with scroll spec
  e2e/cypress/integration/channel_settings/more_unreads_position_with_scroll_spec.js
Labels: 3: QA Review

#7493 MM-31916: channel mention for specific keywords breaks application
  utils/text_formatting.tsx
  utils/text_formatting_imgs.test.jsx
Labels: 4: Reviews Complete

#7427 [MM-18952/GH-16740] - Migrate 'components/authorize' module and associated tests to TypeScript
  components/authorize/authorize.test.tsx
  components/authorize/authorize.tsx
  components/authorize/index.js
  components/authorize/index.ts
Labels: 4: Reviews Complete

#7425 [MM-32441] Fix group icon in channel switcher
  sass/components/_channel-switcher.scss
Labels: 4: Reviews Complete

#7458 MM-32226: adjustted "more unreads"-indicator positioning
  components/sidebar/unread_channel_indicator/__snapshots__/unread_channel_indicator.test.tsx.snap
  components/sidebar/unread_channel_indicator/unread_channel_indicator.scss
  components/sidebar/unread_channel_indicator/unread_channel_indicator.tsx
Labels: 4: Reviews Complete, QA Review Done, Setup Cloud Test Server

#7462 MM-31888: adjusted padding on menu items in sidebar
  sass/layout/_legacy-sidebar-left.scss
Labels: QA Review Done, Setup Cloud Test Server

#7474 [MM-32476] Apps in the Marketplace
  actions/command.ts
  actions/global_actions.tsx
  actions/marketplace.ts
  components/main_menu/main_menu.jsx
  components/plugin_marketplace/__snapshots__/marketplace_modal.test.tsx.snap
  components/plugin_marketplace/index.ts
  components/plugin_marketplace/marketplace_item/__snapshots__/marketplace_item.test.tsx.snap
  components/plugin_marketplace/marketplace_item/marketplace_item.tsx
  components/plugin_marketplace/marketplace_item/marketplace_item_app/__snapshots__/marketplace_item_app.test.tsx.snap
  components/plugin_marketplace/marketplace_item/marketplace_item_app/index.ts
  components/plugin_marketplace/marketplace_item/marketplace_item_app/marketplace_item_app.test.tsx
  components/plugin_marketplace/marketplace_item/marketplace_item_app/marketplace_item_app.tsx
  components/plugin_marketplace/marketplace_item/marketplace_item_plugin/__snapshots__/marketplace_item_plugin.test.tsx.snap
  components/plugin_marketplace/marketplace_item/marketplace_item_plugin/index.ts
  components/plugin_marketplace/marketplace_item/marketplace_item_plugin/marketplace_item_plugin.test.tsx
  components/plugin_marketplace/marketplace_item/marketplace_item_plugin/marketplace_item_plugin.tsx
  components/plugin_marketplace/marketplace_list/__snapshots__/marketplace_list.test.tsx.snap
  components/plugin_marketplace/marketplace_list/marketplace_list.test.tsx
  components/plugin_marketplace/marketplace_list/marketplace_list.tsx
  components/plugin_marketplace/marketplace_modal.test.tsx
  components/plugin_marketplace/marketplace_modal.tsx
  i18n/en.json
  package-lock.json
  package.json
  plugins/test/__snapshots__/main_menu_action.test.jsx.snap
  reducers/views/marketplace.test.ts
  reducers/views/marketplace.ts
  selectors/views/marketplace.js
  selectors/views/marketplace.test.ts
  selectors/views/marketplace.ts
  types/store/views.ts
  utils/constants.jsx
  utils/utils.jsx
Labels: 4: Reviews Complete

#7490 MM-31961: fixed color in search field for dark-theme
  components/search_bar/search_bar.tsx
  sass/components/_search.scss
  sass/responsive/_mobile.scss
Labels: QA Review Done, Setup Cloud Test Server

#7408 [MM-31497] - Prevent end users from inviting people and exceeding the free tier limits
  components/invitation_modal/__snapshots__/invitation_modal.test.jsx.snap
  components/invitation_modal/invitation_modal_guest_step/__snapshots__/invitation_modal_guests_step.test.jsx.snap
  components/invitation_modal/invitation_modal_guest_step/index.ts
  components/invitation_modal/invitation_modal_guest_step/invitation_modal_guests_step.jsx
  components/invitation_modal/invitation_modal_guest_step/invitation_modal_guests_step.test.jsx
  components/invitation_modal/invitation_modal_members_step/__snapshots__/invitation_modal_members_step.test.jsx.snap
  components/invitation_modal/invitation_modal_members_step/index.ts
  components/invitation_modal/invitation_modal_members_step/invitation_modal_members_step.jsx
  components/invitation_modal/invitation_modal_members_step/invitation_modal_members_step.test.jsx
  package-lock.json
  package.json
Labels: 4: Reviews Complete, QA Review Done, Setup Cloud + CWS Test Server

#7497 Cypress/E2E: Promote/Demote e2e tests
  e2e/cypress/integration/account_settings/security/active_sessions_spec.js
  e2e/cypress/integration/bot_accounts/in_lists_1_spec.js
  e2e/cypress/integration/bot_accounts/sidebar_display_spec.js
  e2e/cypress/integration/channel/archived_channels_1_spec.js
  e2e/cypress/integration/channel/archived_channels_2_spec.js
  e2e/cypress/integration/channel/channel_settings_spec.js
  e2e/cypress/integration/channel/channel_switcher_spec.js
  e2e/cypress/integration/channel_settings/more_unreads_position_with_scroll_spec.js
  e2e/cypress/integration/channel_sidebar/category_muting_spec.js
  e2e/cypress/integration/enterprise/group_mentions/group_mentions_posts_spec.js
  e2e/cypress/integration/enterprise/ldap/ldap_login_spec.js
  e2e/cypress/integration/enterprise/permissions/team_permissions_spec.js
  e2e/cypress/integration/enterprise/system_console/channel_moderation/channel_mentions_spec.js
  e2e/cypress/integration/enterprise/system_console/openid/openid_spec.js
  e2e/cypress/integration/enterprise/system_console/search_box_spec.js
  e2e/cypress/integration/integrations/outgoing_webhook/regenerate_token_spec.js
  e2e/cypress/integration/keyboard_shortcuts/ctrl_cmd_k_unreads_spec.js
  e2e/cypress/integration/keyboard_shortcuts/ctrl_cmd_shift_m_spec.js
  e2e/cypress/integration/keyboard_shortcuts/keyboard_shortcuts_one_spec.js
  e2e/cypress/integration/messaging/ctrl_cmd_k_open_dm_with_mouse_spec.js
  e2e/cypress/integration/multi_team_and_dm/gm_header_spec.js
  e2e/cypress/integration/plugins/plugin_startup_fail_spec.js
  e2e/cypress/integration/search/search_group_message_spec.js
  e2e/cypress/integration/system_console/compliance/custom_terms_of_service_spec.js
Labels: 4: Reviews Complete

#7500 MM-26497: markdown table word breaking
  sass/layout/_markdown.scss
Labels: 4: Reviews Complete

#7376 Isolate Apps to disable them whenever needed
  actions/apps.ts
  actions/command.test.js
  actions/command.ts
  actions/global_actions.tsx
  actions/marketplace.ts
  components/dot_menu/dot_menu.test.tsx
  components/dot_menu/dot_menu.tsx
  components/dot_menu/dot_menu_empty.test.tsx
  components/dot_menu/dot_menu_mobile.test.tsx
  components/dot_menu/index.ts
  components/post_view/post_body_additional_content/index.ts
  components/post_view/post_body_additional_content/post_body_additional_content.test.tsx
  components/post_view/post_body_additional_content/post_body_additional_content.tsx
  components/suggestion/command_provider/command_provider.tsx
  package-lock.json
  plugins/channel_header_plug/__snapshots__/channel_header_plug.test.tsx.snap
  plugins/channel_header_plug/channel_header_plug.test.tsx
  plugins/channel_header_plug/channel_header_plug.tsx
  plugins/channel_header_plug/index.ts
  utils/utils.jsx
Labels: 4: Reviews Complete

#7473 [MM-31088] Set submit buttons to the bottom of the form
  components/apps_form/apps_form.tsx
  components/apps_form/apps_form_field/apps_form_field.test.tsx
  components/apps_form/apps_form_field/apps_form_field.tsx
Labels: 4: Reviews Complete

#7510 Revert "Allow uploading 10 files per post (#7160)"
  components/file_upload/file_upload.test.jsx
  utils/constants.jsx
Labels: 4: Reviews Complete, CherryPick/Approved, QA Review Done

#7511 Automated cherry pick of #7510
  components/file_upload/file_upload.test.jsx
  utils/constants.jsx
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7507 Cypress/E2E: Fix for test that requires untrusted internal connection
  e2e/cypress.json
  e2e/cypress/support/api/system.js
Labels: 4: Reviews Complete

#7491 MM-32354 - do not show renew now text in announcement bar tooltip
  components/announcement_bar/configuration_bar/__snapshots__/configuration_bar.test.tsx.snap
  components/announcement_bar/configuration_bar/configuration_bar.tsx
  components/announcement_bar/default_announcement_bar/announcement_bar.tsx
  sass/components/_announcement-bar.scss
Labels: 1: UX Review, 2: Dev Review, QA Review Done

#7136 Add shared channels on admin console
  components/admin_console/admin_definition.jsx
  i18n/en.json
Labels: 3: QA Review, Setup Cloud Test Server

#7506 Cypress/E2E: Use MinIO for S3 storage testing
  e2e/cypress.json
  e2e/cypress/integration/enterprise/system_console/compliance/download_compliance_export_file_spec.js
Labels: 4: Reviews Complete

#7508 Cypress/E2E: Distribute tests evenly when testing in parallel
  e2e/run_tests.js
  e2e/utils/even_distribution.js
  e2e/utils/even_distribution.test.js
Labels: 4: Reviews Complete

#7417 [GH-15906][MM-22844] Add images for email notification redesign
  images/forgot_password_illustration.svg
  images/invite_illustration.svg
  images/logo_email_blue.svg
  images/welcome_illustration.svg
  webpack.config.js
Labels: 4: Reviews Complete

#7505 MM-32738 - Fix typo in OpenID
  components/admin_console/openid_convert/__snapshots__/openid_convert.test.tsx.snap
  components/admin_console/openid_convert/openid_convert.tsx
  i18n/en.json
Labels: 3: QA Review

#7439 [MM-30042]: CWS - Step 3 of Getting Started shows error when trying to send 10 email addresses
  components/next_steps_view/steps/invite_members_step/__snapshots__/invite_members_step.test.tsx.snap
  components/next_steps_view/steps/invite_members_step/index.ts
  components/next_steps_view/steps/invite_members_step/invite_members_step.test.tsx
  components/next_steps_view/steps/invite_members_step/invite_members_step.tsx
  i18n/en.json
  i18n/es.json
Labels: 4: Reviews Complete, QA Review Done, Setup Cloud + CWS Test Server

#7457 [MM-32301] Post Aria Label
  components/post_view/post/post.jsx
  components/rhs_comment/rhs_comment.jsx
  e2e/cypress/integration/messaging/message_deleted_on_reply_spec.js
  utils/post_utils.jsx
Labels: 4: Reviews Complete

#7434 [MM-20377] Convert persist_gate to TypeScript
  components/persist_gate/index.ts
  components/persist_gate/persist_gate.js
  components/persist_gate/persist_gate.ts
  types/store/index.ts
Labels: 4: Reviews Complete

#7488 [MM-20378] Convert file_attachment_list and tests to TypeScript
  components/file_attachment_list/file_attachment_list.test.tsx
  components/file_attachment_list/file_attachment_list.tsx
  components/file_attachment_list/index.ts
Labels: 4: Reviews Complete

#7468 MM-31503 - screen to restrict access because workspace capacity"
  actions/views/root.js
  components/error_page/error_page.tsx
  components/error_page/workspace_user_limit_reached.tsx
  components/purchase_modal/purchase_modal.tsx
  components/signup/signup_controller/__snapshots__/signup_controller.test.jsx.snap
  components/signup/signup_controller/index.js
  components/signup/signup_controller/signup_controller.jsx
  components/signup/signup_controller/signup_controller.test.jsx
  i18n/en.json
  images/cloud/computer-with-alert.svg
  sass/routes/_error-page.scss
  utils/constants.jsx
Labels: 1: UX Review, 2: Dev Review, Setup Cloud + CWS Test Server

#7509 E2 e prod tests fixes
  e2e/cypress/integration/bot_accounts/in_lists_1_spec.js
  e2e/cypress/integration/files_and_attachments/file_previews_2_spec.js
Labels: 4: Reviews Complete

#7522 Cypress/E2E: Fix slash commands spec and some promotions
  e2e/cypress/integration/integrations/slash_commands_spec.js
  e2e/cypress/integration/messaging/dm_list_of_users_spec.js
  e2e/cypress/integration/plugins/upgrade_spec.js
Labels: 4: Reviews Complete

#7426 Refactored apps command parser
  actions/command.ts
  components/suggestion/command_provider/app_command_parser.test.ts
  components/suggestion/command_provider/app_command_parser.ts
  components/suggestion/command_provider/command_provider.tsx
Labels: 2: Dev Review

#7176 [MM-20420]Migrate 'components/add_groups_to_channel_modal' module and associated tests to TypeScript
  components/add_groups_to_channel_modal/__snapshots__/add_groups_to_channel_modal.test.tsx.snap
  components/add_groups_to_channel_modal/add_groups_to_channel_modal.test.tsx
  components/add_groups_to_channel_modal/add_groups_to_channel_modal.tsx
  components/add_groups_to_channel_modal/index.ts
Labels: 4: Reviews Complete

#7524 Cypress/E2E: Fix webhook spec zephyr keys
  e2e/cypress/integration/plugins/demo_plugin/webhook_spec.js
Labels: 4: Reviews Complete

#7502 MM-22267: line-breaks in inline images are now correctly rendered
  utils/text_formatting.tsx
Labels: 1: UX Review, 2: Dev Review, QA Review Done, Setup Cloud Test Server

#7487 [MM-20396] Convert copy_url_context_menu to TypeScript
  components/copy_url_context_menu/__snapshots__/copy_url_context_menu.test.tsx.snap
  components/copy_url_context_menu/copy_url_context_menu.test.tsx
  components/copy_url_context_menu/copy_url_context_menu.tsx
  components/copy_url_context_menu/index.ts
Labels: 4: Reviews Complete

#7423 Rework embedded forms
  actions/command.ts
  actions/global_actions.tsx
  actions/marketplace.ts
  components/dot_menu/index.ts
  components/post_view/embedded_bindings/button_binding/__snapshots__/button_binding.test.tsx.snap
  components/post_view/embedded_bindings/button_binding/button_binding.test.tsx
  components/post_view/embedded_bindings/button_binding/button_binding.tsx
  components/post_view/embedded_bindings/button_binding/index.ts
  components/post_view/embedded_bindings/embedded_binding/__snapshots__/embedded_binding.test.tsx.snap
  components/post_view/embedded_bindings/embedded_binding/embedded_binding.test.tsx
  components/post_view/embedded_bindings/embedded_binding/embedded_binding.tsx
  components/post_view/embedded_bindings/embedded_binding/index.ts
  components/post_view/embedded_bindings/embedded_bindings.tsx
  components/post_view/embedded_bindings/select_binding/index.ts
  components/post_view/embedded_bindings/select_binding/select_binding.test.tsx
  components/post_view/embedded_bindings/select_binding/select_binding.tsx
  components/post_view/post_body_additional_content/index.ts
  components/post_view/post_body_additional_content/post_body_additional_content.tsx
  components/suggestion/command_provider/command_provider.tsx
  package-lock.json
  package.json
  plugins/channel_header_plug/index.ts
  utils/apps.test.ts
  utils/apps.ts
  utils/utils.jsx
Labels: 2: Dev Review

#7446 MM-31501 - Add upgrade-now link for admins in invite users
  components/invitation_modal/invitation_modal_guest_step/__snapshots__/invitation_modal_guests_step.test.jsx.snap
  components/invitation_modal/invitation_modal_guest_step/index.ts
  components/invitation_modal/invitation_modal_guest_step/invitation_modal_guests_step.jsx
  components/invitation_modal/invitation_modal_members_step/__snapshots__/invitation_modal_members_step.test.jsx.snap
  components/invitation_modal/invitation_modal_members_step/index.ts
  components/invitation_modal/invitation_modal_members_step/invitation_modal_members_step.jsx
  components/next_steps_view/steps/invite_members_step/index.ts
  components/next_steps_view/steps/invite_members_step/invite_members_step.scss
  components/next_steps_view/steps/invite_members_step/invite_members_step.tsx
  components/widgets/inputs/users_emails_input.jsx
  components/widgets/inputs/users_emails_input.scss
  components/widgets/links/__snapshots__/upgrade_link.test.tsx.snap
  components/widgets/links/upgrade_link.test.tsx
  components/widgets/links/upgrade_link.tsx
  i18n/en.json
Labels: 3: QA Review, Setup Cloud + CWS Test Server

#7496 MM-3190 show user limit modal when cloud limit exceed
  components/invitation_modal/__snapshots__/invitation_modal.test.jsx.snap
  components/invitation_modal/index.js
  components/invitation_modal/index.test.jsx
  components/invitation_modal/invitation_modal.jsx
  components/invitation_modal/invitation_modal.test.jsx
Labels: 1: UX Review, 2: Dev Review, QA Review Done, Setup Cloud + CWS Test Server

#7531 Automated cherry pick of #7496
  components/invitation_modal/__snapshots__/invitation_modal.test.jsx.snap
  components/invitation_modal/index.js
  components/invitation_modal/index.test.jsx
  components/invitation_modal/invitation_modal.jsx
  components/invitation_modal/invitation_modal.test.jsx
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7504 [MM-32684] Fix RHS Autocomplete options cover the input box for some reply threads
  components/suggestion/command_provider/command_provider.tsx
  components/suggestion/suggestion_box.jsx
  components/suggestion/suggestion_box.test.jsx
Labels: 4: Reviews Complete, CherryPick/Approved

#7533 Automated cherry pick of #7504
  components/suggestion/command_provider/command_provider.tsx
  components/suggestion/suggestion_box.jsx
  components/suggestion/suggestion_box.test.jsx
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7523 MM-32825 - suggestion box hidden by rhs
  sass/components/_post.scss
Labels: 4: Reviews Complete, CherryPick/Approved

#7389 [MM-32087] - Add theme variable for sidebar team bar
  components/user_settings/display/user_settings_theme/__snapshots__/custom_theme_chooser.test.jsx.snap
  components/user_settings/display/user_settings_theme/custom_theme_chooser.jsx
  components/user_settings/import_theme_modal.test.tsx
  components/user_settings/import_theme_modal.tsx
  components/widgets/team_icon/team_icon.scss
  e2e/cypress/fixtures/theme.json
  i18n/en.json
  package-lock.json
  package.json
  sass/components/_badge.scss
  sass/layout/_team-sidebar.scss
  utils/constants.jsx
  utils/utils.jsx
Labels: 4: Reviews Complete, QA Review Done, Setup Cloud Test Server

#7535 Automated cherry pick of #7523
  sass/components/_post.scss
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7489 MM-27241 Private channel prompt for sysadmin
  components/channel_layout/channel_identifier_router/actions.ts
  components/join_private_channel_modal.tsx
  components/needs_team/needs_team.tsx
  components/permalink_view/actions.js
  e2e/cypress/integration/messaging/permalink_click_spec.js
  i18n/en.json
  stores/local_storage_store.jsx
  utils/channel_utils.jsx
  utils/constants.jsx
  utils/utils.jsx
Labels: 4: Reviews Complete

#7536 Remove output from pkill
  Makefile
Labels: 4: Reviews Complete

#7527 MM-27400: tooltip for long channel names
  components/sidebar/sidebar_channel/sidebar_channel_link/__snapshots__/sidebar_channel_link.test.tsx.snap
  components/sidebar/sidebar_channel/sidebar_channel_link/sidebar_channel_link.tsx
  sass/layout/_sidebar-left.scss
Labels: 4: Reviews Complete

#7475 [MM-32352] Add Experiment Sub Section FRONTEND
  components/admin_console/admin_definition.jsx
  components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.jsx.snap
  components/admin_console/admin_sidebar/admin_sidebar.test.jsx
  components/admin_console/system_roles/system_role/__snapshots__/system_role_permissions.test.tsx.snap
  components/admin_console/system_roles/system_role/system_role_permissions.tsx
  e2e/cypress/fixtures/console-example-inputs.json
  e2e/cypress/fixtures/system-roles-console-access.json
  e2e/cypress/support/api/role.js
  i18n/en.json
  package-lock.json
  package.json
  plugins/test/__snapshots__/main_menu_action.test.jsx.snap
  selectors/admin_console.jsx
Labels: 4: Reviews Complete, AutoMerge

#7540 Cypress/E2E: Add release date to appropriate report
  e2e/utils/report.js
Labels: 4: Reviews Complete, AutoMerge

#7310 MM-20437 - migrate close channels to typescript
  components/channel_header_dropdown/menu_items/close_channel/__snapshots__/close_channel.test.tsx.snap
  components/channel_header_dropdown/menu_items/close_channel/close_channel.test.tsx
  components/channel_header_dropdown/menu_items/close_channel/close_channel.tsx
  components/channel_header_dropdown/menu_items/close_channel/index.ts
Labels: 4: Reviews Complete

#7541 Automated cherry pick of #7536
  Makefile
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7542 Cypress/E2E: Several fixes for Cloud
  e2e/cypress/integration/account_settings/display/timezone_display_mode_spec.js
  e2e/cypress/integration/archived_channel/archive_channel_operations_spec.js
  e2e/cypress/integration/archived_channel/archive_channel_search_spec.js
  e2e/cypress/integration/archived_channel/helpers.js
  e2e/cypress/integration/onboarding/tutorial_navigation_and_links_spec.js
  e2e/cypress/integration/plugins/demo_plugin/webhook_spec.js
  e2e/cypress/integration/plugins/plugin_buttons_spec.js
Labels: 4: Reviews Complete

#7543 Cypress/E2E: Add request on first E2E test
  e2e/cypress.json
  e2e/cypress/support/index.js
  e2e/run_tests.js
Labels: 3: QA Review

#7537 Change SVG images to PNG
  images/forgot_password_illustration.png
  images/forgot_password_illustration.svg
  images/invite_illustration.png
  images/invite_illustration.svg
  images/logo_email_blue.png
  images/logo_email_blue.svg
  images/welcome_illustration.png
  images/welcome_illustration.svg
  webpack.config.js
Labels: 4: Reviews Complete

#7478 Cypress/E2E: Fix for importing Cypress support and plugin folders
  e2e/cypress/support/client-impl.js
  e2e/cypress/support/ui/team.js
Labels: 4: Reviews Complete

#7550 Downgrade @hot-loader/react-dom and fix make dev
  package-lock.json
  package.json
  webpack.config.js
Labels: 4: Reviews Complete, CherryPick/Approved

#7557 Automated cherry pick of #7550
  package-lock.json
  package.json
  webpack.config.js
Labels: AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7503 MM-30392 cypress e2e compliance export
  e2e/cypress/integration/enterprise/system_console/compliance/compliance_export_multiple_post_spec.js
  e2e/cypress/integration/enterprise/system_console/compliance/compliance_export_ui_spec.js
  e2e/cypress/integration/enterprise/system_console/compliance/download_bot_compliance_export_file_spec.js
  e2e/cypress/integration/enterprise/system_console/compliance/download_compliance_export_file_spec.js
  e2e/cypress/integration/enterprise/system_console/compliance/helpers.js
  e2e/cypress/support/api/common.d.ts
  e2e/cypress/support/api/common.js
  e2e/cypress/support/ui/compliance_export.d.ts
  e2e/cypress/support/ui/compliance_export.js
  e2e/cypress/support/ui/index.js
Labels: 4: Reviews Complete, AutoMerge

#7515 MM-30531: importing slack theme in new format
  components/user_settings/__snapshots__/import_theme_modal.test.tsx.snap
  components/user_settings/import_theme_modal.test.tsx
  components/user_settings/import_theme_modal.tsx
  package-lock.json
Labels: 4: Reviews Complete

#7554 Fix custom status possible race condition
  selectors/views/custom_status.ts
Labels: 4: Reviews Complete, AutoMerge, Changelog/Not Needed, Docs/Not Needed, Setup Cloud + CWS Test Server

#7561 Automated cherry pick of #7554
  selectors/views/custom_status.ts
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7517 updated package version of proprietary markedjs fork to fix [MM-32645…
  package-lock.json
  package.json
Labels: 4: Reviews Complete

#7546 [MM-31502] - Add Notify Admin link to invitation modal
  components/invitation_modal/invitation_modal_members_step/invitation_modal_members_step.jsx
  components/widgets/links/__snapshots__/notify_link.test.tsx.snap
  components/widgets/links/notify_link.test.tsx
  components/widgets/links/notify_link.tsx
  i18n/en.json
Labels: 4: Reviews Complete, QA Review Done, Setup Cloud + CWS Test Server

#7571 Automated cherry pick of #7546
  components/invitation_modal/invitation_modal_members_step/invitation_modal_members_step.jsx
  components/widgets/links/__snapshots__/notify_link.test.tsx.snap
  components/widgets/links/notify_link.test.tsx
  components/widgets/links/notify_link.tsx
  i18n/en.json
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7447 [MM-32146] Adds shared user indicators for memberships
  components/admin_console/data_grid/data_grid.scss
  components/admin_console/user_grid/user_grid_role_dropdown.tsx
  components/channel_members_dropdown/__snapshots__/channel_members_dropdown.test.jsx.snap
  components/channel_members_dropdown/channel_members_dropdown.jsx
  components/channel_members_dropdown/channel_members_dropdown.test.jsx
  components/popover_list_members/popover_list_members_item/popover_list_members_item.jsx
  components/profile_popover/__snapshots__/profile_popover.test.jsx.snap
  components/profile_popover/profile_popover.jsx
  components/profile_popover/profile_popover.test.jsx
  components/sidebar/sidebar_channel/sidebar_base_channel/__snapshots__/sidebar_base_channel.test.tsx.snap
  components/sidebar/sidebar_channel/sidebar_base_channel/sidebar_base_channel.tsx
  components/suggestion/at_mention_provider/at_mention_suggestion.jsx
  components/suggestion/search_user_provider.jsx
  i18n/en.json
  sass/components/_mentions.scss
  sass/components/_modal.scss
  sass/components/_popover.scss
  sass/components/_suggestion-list.scss
Labels: 4: Reviews Complete

#7545 Cypress/E2E: Fix MM-T1201 Permissions freeze after license removal
  e2e/cypress/integration/enterprise/system_console/about/edition_and_license_spec.js
Labels: 4: Reviews Complete

#7549 Switch make run to faster source maps
  package-lock.json
  webpack.config.js
Labels: 4: Reviews Complete

#7573 Cypress/E2E: Fix several failed tests
  e2e/cypress/integration/emoji/react_to_last_message_shortcut_spec.js
  e2e/cypress/integration/enterprise/group_mentions/group_mentions_posts_spec.js
  e2e/cypress/integration/multi_team_and_dm/gm_add_user_spec.js
  e2e/cypress/support/ui_commands.js
Labels: 4: Reviews Complete

#7560 update from OAuth to OpenID in cloud steps
  components/next_steps_view/next_steps_tips.tsx
  i18n/en.json
Labels: 4: Reviews Complete, AutoMerge, CherryPick/Approved

#7577 Automated cherry pick of #7560
  components/next_steps_view/next_steps_tips.tsx
  i18n/en.json
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7570 Cypress/E2E: Fix image attachment
  e2e/cypress/integration/mark_as_unread/mark_gm_as_unread_spec.js
  e2e/cypress/integration/markdown/markdown_image_spec.js
  e2e/cypress/integration/messaging/image_attachment_spec.js
Labels: 4: Reviews Complete

#7568 Cypress/E2E: Clean up several tests
  e2e/cypress/integration/bot_accounts/token_spec.js
  e2e/cypress/integration/channel_sidebar/group_unreads_seperately_spec.js
  e2e/cypress/integration/enterprise/system_console/search_box_spec.js
  e2e/cypress/integration/search_filter/edit_spec.js
  e2e/cypress/integration/system_console/search_box_spec.js
Labels: 4: Reviews Complete

#7243 [MM-20441] - Migrate 'components/integrations/installed_oauth_apps' to TypeScript
  components/integrations/installed_oauth_apps/__snapshots__/installed_oauth_apps.test.tsx.snap
  components/integrations/installed_oauth_apps/index.ts
  components/integrations/installed_oauth_apps/installed_oauth_apps.test.tsx
  components/integrations/installed_oauth_apps/installed_oauth_apps.tsx
Labels: 4: Reviews Complete

#7572 Cypress/E2E: Fix nickname tests and MM-T1462
  e2e/cypress/integration/accessibility/accessibility_post_spec.js
  e2e/cypress/integration/account_settings/general/nickname_spec.js
  e2e/cypress/support/ui/common.d.ts
  e2e/cypress/support/ui/common.js
Labels: 4: Reviews Complete

#7548 [MM-27663] Don't focus the post textbox if the user presses SPACE while focused on a button or anchor
  e2e/cypress/integration/channel_sidebar/drag_and_drop_spec.js
  utils/post_utils.jsx
Labels: 4: Reviews Complete

#7384 GH-10232 improved timezone selector
  components/user_settings/display/manage_timezones/index.ts
  components/user_settings/display/manage_timezones/manage_timezones.tsx
  components/user_settings/display/user_settings_display.tsx
  i18n/en.json
  sass/components/_react-select.scss
Labels: 4: Reviews Complete

#7578 [MM-33127] Fixing admin console search clear icon
  components/custom_status/custom_status.scss
  components/quick_input/__snapshots__/quick_input.test.jsx.snap
  components/quick_input/quick_input.jsx
  sass/routes/_admin-console.scss
Labels: 4: Reviews Complete, AutoMerge, CherryPick/Approved

#7574 Fixing MM-33118
  components/suggestion/at_mention_provider/at_mention_suggestion.jsx
Labels: 4: Reviews Complete, AutoMerge, CherryPick/Approved

#7584 Automated cherry pick of #7578
  components/custom_status/custom_status.scss
  components/quick_input/__snapshots__/quick_input.test.jsx.snap
  components/quick_input/quick_input.jsx
  sass/routes/_admin-console.scss
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7585 Automated cherry pick of #7574
  components/suggestion/at_mention_provider/at_mention_suggestion.jsx
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7586 MM-33209 Downgrade serialize-error
  package-lock.json
  package.json
Labels: 4: Reviews Complete, CherryPick/Approved, QA Review Done, Setup Cloud Test Server

#7582 Hiding custom statuses config when feature flag is disabled
  components/admin_console/admin_definition.jsx
Labels: 4: Reviews Complete, AutoMerge, CherryPick/Approved

#7587 MM-33209 Downgrade serialize-error
  package-lock.json
  package.json
Labels: 4: Reviews Complete, AutoMerge, CherryPick/Done

#7588 Automated cherry pick of #7582
  components/admin_console/admin_definition.jsx
Labels: AutoMerge, AutomatedCherryPick, Changelog/Not Needed, Docs/Not Needed

#7539 [MM-20386] migrate popover_bar to typescript
  components/view_image/popover_bar/__snapshots__/popover_bar.test.tsx.snap
  components/view_image/popover_bar/index.ts
  components/view_image/popover_bar/popover_bar.test.tsx
  components/view_image/popover_bar/popover_bar.tsx
Labels: 4: Reviews Complete

#7501 MM-31740 Gif picker empty when no results are displayed
  components/gif_picker/components/Categories/index.jsx
  components/gif_picker/components/SearchGrid/SearchGrid.jsx
Labels: 4: Reviews Complete, AutoMerge

#7519 [MM-32549] Fixes lost focus on server logs page for search bar in right hand side admin panel
  components/admin_console/server_logs/log_list.tsx
Labels: 4: Reviews Complete

#7553 [MM-32691] - Send email when the users are not able to join a workspace
  components/error_page/workspace_user_limit_reached.tsx
  package-lock.json
  package.json
Labels: 4: Reviews Complete

#7580 [MM-32641] - Add the 'Invite Members' module to the end-user onboarding flow
  components/next_steps_view/next_steps_view.test.tsx
  components/next_steps_view/steps.ts
  components/next_steps_view/steps/invite_members_step/invite_members_step.tsx
Labels: 4: Reviews Complete, QA Review Done

#7579 [MM-32690] - Add 'Notify Admin' button when end-users are presented with the user limit reached modal
  components/invitation_modal/__snapshots__/invitation_modal.test.jsx.snap
  components/invitation_modal/index.js
  components/invitation_modal/invitation_modal.jsx
  components/invitation_modal/invitation_modal.test.jsx
  components/main_menu/index.jsx
  components/main_menu/main_menu.jsx
  components/user_limit_modal/__snapshots__/user_limit_modal.test.tsx.snap
  components/user_limit_modal/index.ts
  components/user_limit_modal/user_limit_modal.test.tsx
  components/user_limit_modal/user_limit_modal.tsx
  components/widgets/links/notify_link.tsx
  i18n/en.json
Labels: 4: Reviews Complete, QA Review Done

#7590 MM-33237 Update webpack-livereload-plugin
  package-lock.json
  package.json
Labels: 4: Reviews Complete

#7583 Cypress/E2E: Fix several failed tests
  e2e/cypress/integration/channel/channel_switcher_spec.js
  e2e/cypress/integration/enterprise/ldap/ldap_group_sync_spec.js
  e2e/cypress/integration/enterprise/system_console/channel_members_spec.js
  e2e/cypress/integration/enterprise/system_console/team_members_spec.js
  e2e/cypress/integration/integrations/slash_commands_spec.js
  e2e/cypress/integration/messaging/long_draft_spec.js
  e2e/cypress/integration/messaging/receive_message_on_socket_reconnect_spec.js
  e2e/cypress/integration/multi_team_and_dm/close_current_dm_redirects_spec.js
  e2e/cypress/integration/multi_team_and_dm/existing_channel_name_spec.js
  e2e/cypress/support/ui/channel.js
Labels: 4: Reviews Complete

#7567 MM-20371 migrate add_groups_to_team_modal to ts
  components/add_groups_to_team_modal/__snapshots__/add_groups_to_team_modal.test.tsx.snap
  components/add_groups_to_team_modal/add_groups_to_team_modal.test.tsx
  components/add_groups_to_team_modal/add_groups_to_team_modal.tsx
  components/add_groups_to_team_modal/index.ts
Labels: 2: Dev Review, QA Review Done

#7558 [MM-32098] Add Cypress Test for Support Packet Generation
  components/admin_console/admin_sidebar_header/admin_sidebar_header.tsx
  e2e/cypress/integration/enterprise/system_console/support_packet_generation_spec.js
  e2e/cypress/integration/system_console/support_packet_generation_spec.js
Labels: 4: Reviews Complete, AutoMerge

#7565 Cypress/E2E: Fix E2E due to recent change in at-mention suggestion list
  e2e/cypress/integration/account_settings/general/fullname_spec.js
  e2e/cypress/integration/enterprise/accessibility/accessibility_input_fields_spec.js
  e2e/cypress/integration/enterprise/elasticsearch_autocomplete/helpers/index.js
  e2e/cypress/integration/enterprise/elasticsearch_autocomplete/users_spec.js
  e2e/cypress/integration/search_autocomplete/renaming_spec.js
  e2e/cypress/integration/search_autocomplete/users_spec.js
  e2e/cypress/support/ui/index.js
  e2e/cypress/support/ui/suggestion_list.d.ts
  e2e/cypress/support/ui/suggestion_list.js
Labels: 4: Reviews Complete, AutoMerge

#7589 Cypress/E2E: Fix failed tests on theme
  e2e/cypress/integration/account_settings/display/theme/custom_theme_sidebar_styles_spec.js
  e2e/cypress/integration/account_settings/display/theme/settings_view_spec.js
  e2e/cypress/support/ui/common.d.ts
  e2e/cypress/support/ui/common.js
Labels: 4: Reviews Complete

#7594 MM-33245 Fix casing on contenthash for CSS
  webpack.config.js
Labels: 4: Reviews Complete, CherryPick/Approved

#7562 Removed unused roles requests state objects
  components/admin_console/permission_schemes_settings/permission_system_scheme_settings/index.jsx
  components/admin_console/permission_schemes_settings/permission_team_scheme_settings/index.jsx
Labels: 4: Reviews Complete

#7566 [MM-31508] Rename URL to Path in Call
  actions/command.test.js
  components/apps_form/__snapshots__/apps_form_container.test.tsx.snap
  components/apps_form/apps_form.test.tsx
  components/apps_form/apps_form_container.test.tsx
  components/post_view/embedded_bindings/button_binding/button_binding.test.tsx
  components/suggestion/command_provider/app_command_parser.test.ts
  package-lock.json
  package.json
  plugins/channel_header_plug/channel_header_plug.tsx
  utils/apps.test.ts
  utils/apps.ts
Labels: 4: Reviews Complete

#7598 MM-33285 Turn off snapshotting of node_modules and minor webpack changes
  webpack.config.js
Labels: 4: Reviews Complete

#7555 Fix App parser
  components/suggestion/command_provider/app_command_parser.test.ts
  components/suggestion/command_provider/app_command_parser.ts
  components/suggestion/command_provider/command_provider.tsx
  components/suggestion/suggestion_box.jsx
Labels: 4: Reviews Complete
