Repository mattermost/mattermost-webapp, pull requests merged in 2021-12, with the labels that each got.

#9461 Fix for isMobile hitting window.innerWidth (#9365) (6.0)
  actions/views/browser.ts
  components/root/index.js
  components/root/root.jsx
  components/root/root.test.jsx
  components/sidebar/index.ts
  components/sidebar/sidebar.test.tsx
  components/sidebar/sidebar.tsx
  components/sidebar/sidebar_header/dropdown/index.js
  components/sidebar_right_menu/index.js
  reducers/views/browser.js
  reducers/views/browser.test.js
  reducers/views/browser.ts
  selectors/views/browser.ts
  types/store/views.ts
  utils/constants.jsx
  utils/post_utils.ts
  utils/utils.jsx
Labels: 4: Reviews Complete, CherryPick/Done, release-note-none, QA Deferred

#9462 Fix for isMobile hitting window.innerWidth (#9365) (6.1)
  components/sidebar_right_menu/index.js
  utils/post_utils.ts
  utils/utils.jsx
Labels: 4: Reviews Complete, CherryPick/Done, release-note-none, QA Deferred

#9460 Fix for isMobile hitting window.innerWidth (#9365) (5.37 ESR)
  actions/views/browser.ts
  components/legacy_sidebar/header/dropdown/index.js
  components/legacy_sidebar/header/index.js
  components/root/index.js
  components/root/root.jsx
  components/root/root.test.jsx
  components/sidebar/index.ts
  components/sidebar/sidebar.test.tsx
  components/sidebar/sidebar.tsx
  components/sidebar/sidebar_header/index.ts
  components/sidebar_right_menu/index.js
  reducers/views/browser.js
  reducers/views/browser.test.js
  reducers/views/browser.ts
  selectors/views/browser.ts
  types/store/views.ts
  utils/constants.jsx
  utils/post_utils.jsx
  utils/utils.jsx
Labels: 4: Reviews Complete, CherryPick/Done, release-note-none, QA Deferred

#9465 Automated cherry pick of #9462
  components/sidebar_right_menu/index.js
  utils/post_utils.ts
  utils/utils.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#9464 Automated cherry pick of #9462
  components/sidebar_right_menu/index.js
  utils/post_utils.ts
  utils/utils.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#9448 MM-40222 - show the gov references in license page when gov license
  components/admin_console/license_settings/enterprise_edition/enterprise_edition.scss
  components/admin_console/license_settings/enterprise_edition/enterprise_edition_left_panel.tsx
  components/admin_console/license_settings/enterprise_edition/enterprise_edition_right_panel.tsx
  components/admin_console/license_settings/starter_edition/starter_edition.scss
  i18n/en.json
Labels: 2: Dev Review, Setup Cloud Test Server, QA Review Done, 1: UX Review, release-note-none

#9458 Cypress/E2E: Promote tests to production
  e2e/cypress/integration/account_settings/profile/help_text_link_spec.js
  e2e/cypress/integration/autocomplete/database/users_spec.js
  e2e/cypress/integration/channel/channel_mention_autocomplete_spec.js
  e2e/cypress/integration/enterprise/elasticsearch_autocomplete/users_spec.js
  e2e/cypress/integration/enterprise/system_console/compliance/download_bot_compliance_export_file_spec.js
  e2e/cypress/integration/keyboard_shortcuts/shift_up_focuses_on_rhs_spec.js
  e2e/cypress/integration/messaging/mention_autocomplete_overlap_spec.js
  e2e/cypress/integration/messaging/thread_appears_and_scrollable_in_the_rhs_spec.js
  e2e/cypress/integration/onboarding/set_profile_and_team_spec.js
  e2e/cypress/integration/settings/sidebar/fullname_spec.js
Labels: 2: Dev Review, 3: QA Review, release-note-none

#9339 MM-38674 - AB first channel creation
  actions/views/channel_sidebar.ts
  components/next_steps_view/next_steps_view.scss
  components/next_steps_view/next_steps_view.test.tsx
  components/next_steps_view/next_steps_view.tsx
  components/next_steps_view/steps.test.tsx
  components/next_steps_view/steps.ts
  components/next_steps_view/steps/complete_profile_step/complete_profile_step.test.tsx
  components/next_steps_view/steps/complete_profile_step/complete_profile_step.tsx
  components/next_steps_view/steps/create_first_channel_step/__snapshots__/create_first_channel_step.test.tsx.snap
  components/next_steps_view/steps/create_first_channel_step/create_first_channel_step.test.tsx
  components/next_steps_view/steps/create_first_channel_step/create_first_channel_step.tsx
  components/next_steps_view/steps/download_apps_step/download_apps_step.tsx
  components/next_steps_view/steps/enable_notifications_step/enable_notifications_step.test.tsx
  components/next_steps_view/steps/enable_notifications_step/enable_notifications_step.tsx
  components/next_steps_view/steps/invite_members_step/invite_members_step.test.tsx
  components/next_steps_view/steps/invite_members_step/invite_members_step.tsx
  components/next_steps_view/steps/setup_preferences_step/__snapshots__/setup_preferences_step.test.tsx.snap
  components/next_steps_view/steps/setup_preferences_step/setup_preferences_step.test.tsx
  components/next_steps_view/steps/setup_preferences_step/setup_preferences_step.tsx
  components/next_steps_view/steps/team_profile_step/team_profile_step.test.tsx
  components/next_steps_view/steps/team_profile_step/team_profile_step.tsx
  components/sidebar/__snapshots__/channel_tutorial_tip.test.tsx.snap
  components/sidebar/channel_tutorial_tip.test.tsx
  components/sidebar/channel_tutorial_tip.tsx
  components/sidebar/sidebar_channel/sidebar_channel_link/index.ts
  components/sidebar/sidebar_channel/sidebar_channel_link/sidebar_channel_link.tsx
  components/tutorial/tutorial_tip/index.ts
  components/tutorial/tutorial_tip/tutorial_tip.test.tsx
  components/tutorial/tutorial_tip/tutorial_tip.tsx
  components/tutorial/tutorial_tip/tutorial_tip_backdrop.tsx
  components/widgets/pulsating_dot/index.tsx
  i18n/en.json
  packages/mattermost-redux/src/selectors/entities/preferences.ts
  reducers/views/channel_sidebar.ts
  sass/components/_tutorial.scss
  types/store/views.ts
  utils/constants.jsx
Labels: Setup Cloud Test Server, QA Review Done, release-note-none

#9331 [MM-34325] Migrate 'components/admin_console/permission_schemes_settings' and associated tests to TypeScript
  components/admin_console/permission_schemes_settings/__snapshots__/permission_schemes_settings.test.tsx.snap
  components/admin_console/permission_schemes_settings/index.tsx
  components/admin_console/permission_schemes_settings/permission_schemes_settings.test.tsx
  components/admin_console/permission_schemes_settings/permission_schemes_settings.tsx
  components/admin_console/permission_schemes_settings/permissions_scheme_summary/permissions_scheme_summary.tsx
Labels: 4: Reviews Complete, release-note, Contributor

#9469 MM-40176 - adjust hands svg size for trial benefits modal
  components/trial_benefits_modal/trial_benefits_modal.scss
  components/trial_benefits_modal/trial_benefits_modal.tsx
Labels: CherryPick/Candidate, Setup Cloud Test Server, 1: UX Review, release-note-none, QA Deferred

#9451 MM-40071 Only calculate suggestion list max height when first opened
  components/__snapshots__/autosize_textarea.test.jsx.snap
  components/__snapshots__/textbox.test.tsx.snap
  components/autosize_textarea.test.jsx
  components/autosize_textarea.tsx
  components/edit_post_modal/edit_post_modal.test.tsx
  components/edit_post_modal/edit_post_modal.tsx
  components/quick_input/quick_input.tsx
  components/suggestion/rhs_suggestion_list.tsx
  components/suggestion/suggestion_box/suggestion_box.jsx
  components/suggestion/suggestion_list.jsx
  components/textbox/textbox.tsx
  components/user_settings/notifications/__snapshots__/manage_auto_responder.test.jsx.snap
  components/user_settings/notifications/manage_auto_responder.jsx
  components/user_settings/notifications/manage_auto_responder.test.jsx
Labels: 4: Reviews Complete, CherryPick/Done, release-note

#9456 MM-40071 Only calculate suggestion list max height when first opened (5.39)
  components/__snapshots__/autosize_textarea.test.jsx.snap
  components/__snapshots__/textbox.test.tsx.snap
  components/autosize_textarea.test.jsx
  components/autosize_textarea.tsx
  components/edit_post_modal/edit_post_modal.jsx
  components/edit_post_modal/edit_post_modal.test.jsx
  components/suggestion/rhs_suggestion_list.tsx
  components/suggestion/suggestion_box.jsx
  components/suggestion/suggestion_list.jsx
  components/textbox/textbox.tsx
  components/user_settings/notifications/__snapshots__/manage_auto_responder.test.jsx.snap
  components/user_settings/notifications/manage_auto_responder.jsx
  components/user_settings/notifications/manage_auto_responder.test.jsx
Labels: 4: Reviews Complete, CherryPick/Done, release-note-none

#9473 Automated cherry pick of #9451
  components/__snapshots__/autosize_textarea.test.jsx.snap
  components/__snapshots__/textbox.test.tsx.snap
  components/autosize_textarea.test.jsx
  components/autosize_textarea.tsx
  components/edit_post_modal/edit_post_modal.test.tsx
  components/edit_post_modal/edit_post_modal.tsx
  components/quick_input/quick_input.tsx
  components/suggestion/rhs_suggestion_list.tsx
  components/suggestion/suggestion_box/suggestion_box.jsx
  components/suggestion/suggestion_list.jsx
  components/textbox/textbox.tsx
  components/user_settings/notifications/__snapshots__/manage_auto_responder.test.jsx.snap
  components/user_settings/notifications/manage_auto_responder.jsx
  components/user_settings/notifications/manage_auto_responder.test.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#9475 Automated cherry pick of #9451
  components/__snapshots__/autosize_textarea.test.jsx.snap
  components/__snapshots__/textbox.test.tsx.snap
  components/autosize_textarea.test.jsx
  components/autosize_textarea.tsx
  components/edit_post_modal/edit_post_modal.test.tsx
  components/edit_post_modal/edit_post_modal.tsx
  components/quick_input/quick_input.tsx
  components/suggestion/rhs_suggestion_list.tsx
  components/suggestion/suggestion_box.jsx
  components/suggestion/suggestion_list.jsx
  components/textbox/textbox.tsx
  components/user_settings/notifications/__snapshots__/manage_auto_responder.test.jsx.snap
  components/user_settings/notifications/manage_auto_responder.jsx
  components/user_settings/notifications/manage_auto_responder.test.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#9474 Automated cherry pick of #9451
  components/__snapshots__/autosize_textarea.test.jsx.snap
  components/__snapshots__/textbox.test.tsx.snap
  components/autosize_textarea.test.jsx
  components/autosize_textarea.tsx
  components/edit_post_modal/edit_post_modal.test.tsx
  components/edit_post_modal/edit_post_modal.tsx
  components/quick_input/quick_input.tsx
  components/suggestion/rhs_suggestion_list.tsx
  components/suggestion/suggestion_box/suggestion_box.jsx
  components/suggestion/suggestion_list.jsx
  components/textbox/textbox.tsx
  components/user_settings/notifications/__snapshots__/manage_auto_responder.test.jsx.snap
  components/user_settings/notifications/manage_auto_responder.jsx
  components/user_settings/notifications/manage_auto_responder.test.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#9477 Automated cherry pick of #9469
  components/trial_benefits_modal/trial_benefits_modal.scss
  components/trial_benefits_modal/trial_benefits_modal.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#9478 Automated cherry pick of #9469
  components/trial_benefits_modal/trial_benefits_modal.scss
  components/trial_benefits_modal/trial_benefits_modal.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#9479 Cypress/E2E: Fix group configuration spec
  components/admin_console/group_settings/group_details/__snapshots__/group_teams_and_channels_row.test.tsx.snap
  components/admin_console/group_settings/group_details/group_teams_and_channels_row.tsx
  e2e/cypress/integration/enterprise/system_console/group_configuration_spec.js
  sass/components/_groups.scss
Labels: 4: Reviews Complete, release-note-none

#9481 Automated cherry pick of #9370
  components/admin_console/admin_definition.jsx
  components/admin_console/data_retention_settings.jsx
  i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#9455 Automated cherry pick of #9450 on release-6.2
  i18n/bg.json
  i18n/de.json
  i18n/en_AU.json
  i18n/es.json
  i18n/fr.json
  i18n/hu.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 2: Dev Review, release-note-none

#9430 Remove reliable websockets configuration
  client/websocket_client.tsx
Labels: 4: Reviews Complete, release-note-none

#9476 MM-40417 - fix the wording for the starter plan
  components/admin_console/license_settings/enterprise_edition/enterprise_edition_left_panel.tsx
Labels: CherryPick/Approved, Setup Cloud Test Server, QA Review Done, release-note-none

#9484 Automated cherry pick of #9476
  components/admin_console/license_settings/enterprise_edition/enterprise_edition_left_panel.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#9472 GH-1878: Display Bot Badge in Auto Complete For Focalboard
  plugins/export.js
Labels: 4: Reviews Complete, release-note-none

#9466 MM-40071 Attempt to improve performance by reducing direct DOM usage
  components/dot_menu/__snapshots__/dot_menu.test.tsx.snap
  components/dot_menu/dot_menu.tsx
  components/file_attachment/file_attachment.tsx
  components/rhs_search_nav/rhs_search_nav.tsx
  components/sidebar/sidebar_category/sidebar_category_menu/__snapshots__/sidebar_category_menu.test.tsx.snap
  components/sidebar/sidebar_category/sidebar_category_menu/sidebar_category_menu.tsx
  components/sidebar/sidebar_category/sidebar_category_sorting_menu/sidebar_category_sorting_menu.tsx
  components/sidebar/sidebar_channel/sidebar_channel_menu/__snapshots__/sidebar_channel_menu.test.tsx.snap
  components/sidebar/sidebar_channel/sidebar_channel_menu/sidebar_channel_menu.test.tsx
  components/sidebar/sidebar_channel/sidebar_channel_menu/sidebar_channel_menu.tsx
  components/sidebar/sidebar_menu/sidebar_menu.test.tsx
  components/sidebar/sidebar_menu/sidebar_menu.tsx
  utils/utils.jsx
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#9457 MM-T2079 Can remove profile pic then choose different pic without saving in between
  e2e/cypress/integration/account_settings/profile/profile_picture_change_spec.js
Labels: 4: Reviews Complete, release-note-none, Contributor

#9485 Automated cherry pick of #9466
  components/dot_menu/__snapshots__/dot_menu.test.tsx.snap
  components/dot_menu/dot_menu.tsx
  components/file_attachment/file_attachment.tsx
  components/rhs_search_nav/rhs_search_nav.tsx
  components/sidebar/sidebar_category/sidebar_category_menu/__snapshots__/sidebar_category_menu.test.tsx.snap
  components/sidebar/sidebar_category/sidebar_category_menu/sidebar_category_menu.tsx
  components/sidebar/sidebar_category/sidebar_category_sorting_menu/sidebar_category_sorting_menu.tsx
  components/sidebar/sidebar_channel/sidebar_channel_menu/__snapshots__/sidebar_channel_menu.test.tsx.snap
  components/sidebar/sidebar_channel/sidebar_channel_menu/sidebar_channel_menu.test.tsx
  components/sidebar/sidebar_channel/sidebar_channel_menu/sidebar_channel_menu.tsx
  components/sidebar/sidebar_menu/sidebar_menu.test.tsx
  components/sidebar/sidebar_menu/sidebar_menu.tsx
  utils/utils.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#9486 Automated cherry pick of #9466
  components/dot_menu/__snapshots__/dot_menu.test.tsx.snap
  components/dot_menu/dot_menu.tsx
  components/file_attachment/file_attachment.tsx
  components/rhs_search_nav/rhs_search_nav.tsx
  components/sidebar/sidebar_category/sidebar_category_menu/__snapshots__/sidebar_category_menu.test.tsx.snap
  components/sidebar/sidebar_category/sidebar_category_menu/sidebar_category_menu.tsx
  components/sidebar/sidebar_category/sidebar_category_sorting_menu/sidebar_category_sorting_menu.tsx
  components/sidebar/sidebar_channel/sidebar_channel_menu/__snapshots__/sidebar_channel_menu.test.tsx.snap
  components/sidebar/sidebar_channel/sidebar_channel_menu/sidebar_channel_menu.test.tsx
  components/sidebar/sidebar_channel/sidebar_channel_menu/sidebar_channel_menu.tsx
  components/sidebar/sidebar_menu/sidebar_menu.test.tsx
  components/sidebar/sidebar_menu/sidebar_menu.tsx
  utils/utils.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#9487 Automated cherry pick of #9466
  components/dot_menu/__snapshots__/dot_menu.test.tsx.snap
  components/dot_menu/dot_menu.tsx
  components/file_attachment/file_attachment.tsx
  components/rhs_search_nav/rhs_search_nav.tsx
  components/sidebar/sidebar_category/sidebar_category_menu/__snapshots__/sidebar_category_menu.test.tsx.snap
  components/sidebar/sidebar_category/sidebar_category_menu/sidebar_category_menu.tsx
  components/sidebar/sidebar_category/sidebar_category_sorting_menu/sidebar_category_sorting_menu.tsx
  components/sidebar/sidebar_channel/sidebar_channel_menu/__snapshots__/sidebar_channel_menu.test.tsx.snap
  components/sidebar/sidebar_channel/sidebar_channel_menu/sidebar_channel_menu.test.tsx
  components/sidebar/sidebar_channel/sidebar_channel_menu/sidebar_channel_menu.tsx
  components/sidebar/sidebar_menu/sidebar_menu.test.tsx
  components/sidebar/sidebar_menu/sidebar_menu.tsx
  utils/utils.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#9405 chore/MM-37187 : Update all babel related dependencies to v7.16.0 - Nov 21
  package-lock.json
  package.json
Labels: 4: Reviews Complete, release-note-none

#9480 Updated About Mattermost TE modal's community URL
  components/about_build_modal/__snapshots__/about_build_modal.test.tsx.snap
  components/about_build_modal/about_build_modal.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, QA Review Done, release-note

#9445 Migrating some files to typescript
  actions/views/posts.js
  components/admin_console/license_settings/ee_license_modal/ee_license_modal.tsx
  components/announcement_bar/default_announcement_bar/index.ts
  components/announcement_bar/show_start_trial_modal/show_start_trial_modal.tsx
  components/invitation_modal/index.test.tsx
  components/invitation_modal/index.tsx
  components/markdown_image_expand/index.ts
  components/sidebar/sidebar_category/sidebar_category_menu/sidebar_category_menu.tsx
  components/sidebar/sidebar_category/sidebar_category_sorting_menu/sidebar_category_sorting_menu.tsx
  components/start_trial_modal/index.tsx
  components/trial_benefits_modal/trial_benefits_modal.tsx
  components/warn_metric_ack_modal/index.ts
  components/widgets/menu/menu_items/submenu_item.tsx
  reducers/index.ts
  reducers/plugins/index.ts
  reducers/storage.ts
  reducers/views/admin.ts
  reducers/views/announcement_bar.ts
  reducers/views/channel.ts
  reducers/views/channel_selector_modal.ts
  reducers/views/emoji.ts
  reducers/views/i18n.ts
  reducers/views/index.ts
  reducers/views/lhs.ts
  reducers/views/notice.ts
  reducers/views/posts.ts
  reducers/views/rhs.ts
  reducers/views/search.ts
  reducers/views/settings.ts
  reducers/views/system.ts
  reducers/views/textbox.ts
  selectors/emojis.ts
  selectors/general.ts
  selectors/local_storage.ts
  selectors/posts.ts
  selectors/storage.ts
  selectors/views/admin.ts
  selectors/views/announcement_bar.ts
  selectors/views/channel.js
  selectors/views/channel.ts
  selectors/views/channel_selector_modal.ts
  selectors/views/modals.ts
  selectors/views/settings.ts
  selectors/views/system.ts
  selectors/views/textbox.ts
  selectors/views/websocket.js
  selectors/views/websocket.ts
  types/store/plugins.ts
  types/store/views.ts
Labels: 4: Reviews Complete, release-note-none

#9426 MM-40050 Don't load channel-specific data on user update
  actions/websocket_actions.jsx
  actions/websocket_actions.test.jsx
  e2e/cypress/integration/enterprise/guest_accounts/guest_identification_ui_not_cloud_spec.js
Labels: 4: Reviews Complete, Docs/Needed, CherryPick/Approved, release-note

#9408 chore/MM-37187 : Upgrade webpack and its related dependencies Part 1 - Nov 21
  package-lock.json
  package.json
  webpack.config.js
Labels: 4: Reviews Complete, release-note-none

#9489 Automated cherry pick of #9426
  actions/websocket_actions.jsx
  actions/websocket_actions.test.jsx
  e2e/cypress/integration/enterprise/guest_accounts/guest_identification_ui_not_cloud_spec.js
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#9490 Automated cherry pick of #9426
  actions/websocket_actions.jsx
  actions/websocket_actions.test.jsx
  e2e/cypress/integration/enterprise/guest_accounts/guest_identification_ui_not_cloud_spec.js
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#9483 Automated cherry pick of #9476
  components/admin_console/license_settings/enterprise_edition/enterprise_edition_left_panel.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#8936 Billing scenarios after subscription
  e2e/cypress/integration/enterprise/cloud/billing/after_subscription_spec.js
  e2e/cypress/integration/enterprise/cloud/billing/payment_free_trial_spec.js
  e2e/cypress/integration/enterprise/cloud/billing/payment_information_after_subscription_spec.js
Labels: 4: Reviews Complete, 3: QA Review, release-note-none

#9446 MM-T248 Mark DM post as Unread
  e2e/cypress/integration/mark_as_unread/helpers.js
  e2e/cypress/integration/mark_as_unread/mark_dm_post_as_unread_spec.js
Labels: 4: Reviews Complete, release-note-none, Contributor

#9488 Cypress/E2E: Add missing meta data
  e2e/cypress/integration/account_settings/profile/profile_picture_change_spec.js
Labels: 4: Reviews Complete, release-note-none

#9424 [MM-39745] Disable channel header buttons temporarily when the RHS closes
  plugins/channel_header_plug/__snapshots__/channel_header_plug.test.tsx.snap
  plugins/channel_header_plug/channel_header_plug.test.tsx
  plugins/channel_header_plug/channel_header_plug.tsx
  plugins/channel_header_plug/index.ts
Labels: 4: Reviews Complete, release-note-none

#9492 MM-T2075 Profile Picture: Cancel out of adding/changing profile picture
  e2e/cypress/integration/account_settings/profile/profile_picture_change_spec.js
Labels: 4: Reviews Complete, release-note-none, Contributor

#9449 MM-38150 System console additions for playbook permissions
  components/admin_console/permission_schemes_settings/permission_schemes_settings.tsx
  components/admin_console/permission_schemes_settings/permission_system_scheme_settings/__snapshots__/permission_system_scheme_settings.test.tsx.snap
  components/admin_console/permission_schemes_settings/permission_system_scheme_settings/permission_system_scheme_settings.test.tsx
  components/admin_console/permission_schemes_settings/permission_system_scheme_settings/permission_system_scheme_settings.tsx
  components/admin_console/permission_schemes_settings/permission_team_scheme_settings/__snapshots__/permission_team_scheme_settings.test.tsx.snap
  components/admin_console/permission_schemes_settings/permission_team_scheme_settings/permission_team_scheme_settings.test.tsx
  components/admin_console/permission_schemes_settings/permission_team_scheme_settings/permission_team_scheme_settings.tsx
  components/admin_console/permission_schemes_settings/permissions_tree/__snapshots__/permissions_tree.test.tsx.snap
  components/admin_console/permission_schemes_settings/permissions_tree/index.tsx
  components/admin_console/permission_schemes_settings/permissions_tree/permissions_tree.tsx
  components/admin_console/permission_schemes_settings/permissions_tree_playbooks.tsx
  components/admin_console/permission_schemes_settings/permissions_tree_runs.tsx
  components/admin_console/team_channel_settings/channel/details/channel_details.test.tsx
  i18n/en.json
  packages/mattermost-redux/src/constants/general.ts
  packages/mattermost-redux/src/constants/permissions.ts
  packages/mattermost-redux/src/types/schemes.ts
  utils/constants.jsx
Labels: 2: Dev Review, release-note-none

#9499 Automated cherry pick of #9497 on cloud
  i18n/de.json
  i18n/en_AU.json
  i18n/fr.json
  i18n/hu.json
  i18n/ja.json
  i18n/nl.json
  i18n/pl.json
  i18n/sv.json
  i18n/tr.json
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#9498 Automated cherry pick of #9497 on release-6.2
  i18n/de.json
  i18n/en_AU.json
  i18n/fr.json
  i18n/hu.json
  i18n/ja.json
  i18n/nl.json
  i18n/pl.json
  i18n/sv.json
  i18n/tr.json
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#9505 MM-40528 Fix error caused by changes to QuickInput
  components/suggestion/suggestion_box/suggestion_box.jsx
Labels: 4: Reviews Complete, release-note-none, QA Deferred

#9262 Team sidebar in products
  actions/team_actions.jsx
  components/channel_layout/channel_controller.tsx
  components/global_header/global_header.tsx
  components/global_header/hooks.tsx
  components/root/root.jsx
  components/team_sidebar/index.ts
  components/team_sidebar/team_sidebar.tsx
  plugins/registry.js
  sass/layout/_team-sidebar.scss
  sass/routes/_backstage.scss
  selectors/products.ts
  types/store/plugins.ts
  utils/products.ts
  utils/test_helper.ts
Labels: 4: Reviews Complete, release-note

#9496 MM-40447: fixes minor styling issues in suggestions
  sass/components/_day-picker.scss
  sass/components/_suggestion-list.scss
  utils/utils.jsx
Labels: 2: Dev Review, CherryPick/Approved, Setup Cloud Test Server, QA Review Done, release-note-none

#9514 Automated cherry pick of #9496
  sass/components/_day-picker.scss
  sass/components/_suggestion-list.scss
  utils/utils.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#9495 MM-40418: fix leave/archive channel
  actions/views/channel.js
  actions/views/channel.test.js
  actions/websocket_actions.jsx
  components/delete_channel_modal/index.ts
  components/rhs_header_post/index.ts
  components/rhs_header_post/rhs_header_post.spec.tsx
  components/rhs_header_post/rhs_header_post.tsx
  e2e/cypress/integration/archived_channel/archive_channel_post_spec.js
  e2e/cypress/integration/channel/leave_channel_spec.js
  packages/mattermost-redux/src/reducers/entities/threads/counts.ts
  packages/mattermost-redux/src/reducers/entities/threads/index.ts
  packages/mattermost-redux/src/reducers/entities/threads/threadsInTeam.ts
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, QA Review Done, release-note

#9515 Automated cherry pick of #9495
  actions/views/channel.js
  actions/views/channel.test.js
  actions/websocket_actions.jsx
  components/delete_channel_modal/index.ts
  components/rhs_header_post/index.ts
  components/rhs_header_post/rhs_header_post.spec.tsx
  components/rhs_header_post/rhs_header_post.tsx
  e2e/cypress/integration/archived_channel/archive_channel_post_spec.js
  e2e/cypress/integration/channel/leave_channel_spec.js
  packages/mattermost-redux/src/reducers/entities/threads/counts.ts
  packages/mattermost-redux/src/reducers/entities/threads/index.ts
  packages/mattermost-redux/src/reducers/entities/threads/threadsInTeam.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#9504 MM-40493 Switch DND modal to rely more on GenericModal
  components/dnd_custom_time_picker_modal/dnd_custom_time_picker_modal.scss
  components/dnd_custom_time_picker_modal/dnd_custom_time_picker_modal.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#9502 Automated cherry pick of #9424
  plugins/channel_header_plug/__snapshots__/channel_header_plug.test.tsx.snap
  plugins/channel_header_plug/channel_header_plug.test.tsx
  plugins/channel_header_plug/channel_header_plug.tsx
  plugins/channel_header_plug/index.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#9500 fix/MM-40381, MM-40381, MM-40381 : Emoji picker issues with custom emojis
  components/emoji_picker/components/emoji_picker_preview.tsx
  components/emoji_picker/emoji_picker.jsx
  components/post_view/reaction_list/index.ts
  selectors/emojis.ts
  utils/emoticons.tsx
  utils/post_utils.ts
Labels: 4: Reviews Complete, CherryPick/Approved, AutoMerge, release-note-none

#9506 MM-40437 Remove unused RHSSearchNav component
  components/rhs_search_nav/__snapshots__/rhs_search_nav.test.tsx.snap
  components/rhs_search_nav/index.ts
  components/rhs_search_nav/rhs_search_nav.test.tsx
  components/rhs_search_nav/rhs_search_nav.tsx
  components/search/search.tsx
  components/search/user_guide_dropdown/__snapshots__/user_guide_dropdown.test.tsx.snap
  components/search/user_guide_dropdown/index.ts
  components/search/user_guide_dropdown/user_guide_dropdown.test.tsx
  components/search/user_guide_dropdown/user_guide_dropdown.tsx
  utils/utils.d.ts
  utils/utils.jsx
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#9516 Automated cherry pick of #9500
  components/emoji_picker/components/emoji_picker_preview.tsx
  components/emoji_picker/emoji_picker.jsx
  components/post_view/reaction_list/index.ts
  selectors/emojis.js
  utils/emoticons.tsx
  utils/post_utils.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#9519 fix : Emojis with default skin not changing color in recent when skin is changed
  components/emoji_picker/emoji_picker.jsx
Labels: CherryPick/Approved, QA Review Done, release-note-none

#9520 Automated cherry pick of #9519
  components/emoji_picker/emoji_picker.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#9427 [MM-40285] Make sure ownProps are used in Timestamp's mapStateToProps
  components/timestamp/index.test.tsx
  components/timestamp/index.ts
Labels: 4: Reviews Complete, release-note-none, Contributor

#9510 MM-40114 Migrate RHS and search components to use getIsMobileView
  components/rhs_card/index.js
  components/rhs_card/rhs_card.jsx
  components/rhs_card/rhs_card.test.jsx
  components/rhs_comment/__snapshots__/rhs_comment.test.jsx.snap
  components/rhs_comment/index.ts
  components/rhs_comment/rhs_comment.jsx
  components/rhs_comment/rhs_comment.test.jsx
  components/rhs_header_post/index.ts
  components/rhs_header_post/rhs_header_post.tsx
  components/rhs_root_post/index.ts
  components/rhs_root_post/rhs_root_post.jsx
  components/rhs_root_post/rhs_root_post.test.jsx
  components/search/index.tsx
  components/search/search.tsx
  components/search/types.ts
  components/search_results_item/index.test.js
  components/search_results_item/index.ts
  components/search_results_item/search_results_item.jsx
  components/search_results_item/search_results_item.test.jsx
Labels: 2: Dev Review, Setup Cloud Test Server, release-note-none, QA Deferred

#9526 Fixes tests on master
  components/rhs_header_post/rhs_header_post.spec.tsx
Labels: 2: Dev Review, release-note-none, QA Deferred

#9367 Add lazy loading to some components
  components/app.jsx
  components/async_load.jsx
  components/channel_layout/center_channel/center_channel.tsx
  components/dnd_custom_time_picker_modal/index.ts
  components/emoji_picker/emoji_picker_tabs.jsx
  components/file_preview_modal/index.js
  components/invitation_modal/index.tsx
  components/main_menu/__snapshots__/main_menu.test.tsx.snap
  components/needs_team/needs_team.tsx
  components/next_steps_view/index.ts
  components/plugin_marketplace/index.ts
  components/plugin_marketplace/marketplace_modal.test.tsx
  components/plugin_marketplace/marketplace_modal.tsx
  components/purchase_modal/index.ts
  components/root/root.jsx
  components/sidebar/__snapshots__/invite_members_button.test.tsx.snap
  components/start_trial_modal/index.tsx
  components/widgets/menu/menu_items/menu_start_trial.tsx
  plugins/test/__snapshots__/main_menu_action.test.jsx.snap
  sass/components/_modal.scss
Labels: 4: Reviews Complete, release-note-none

#9529 Automated cherry pick of #9528 on release-6.2
  i18n/de.json
  i18n/en_AU.json
  i18n/ja.json
  i18n/nl.json
  i18n/pl.json
  i18n/sv.json
  i18n/tr.json
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#9527 chore/MM-40271 : Remove fastclick library
  NOTICE.txt
  components/root/root.jsx
  components/root/root.test.jsx
  package-lock.json
  package.json
Labels: 4: Reviews Complete, release-note-none

#9333 fix: set token if not already set
  components/root/root.jsx
  packages/mattermost-redux/src/client/client4.ts
Labels: 4: Reviews Complete, Setup Cloud Test Server, QA Review Done, release-note-none, Contributor

#9531 fix : Fix custom emoji deleted puts emoji picker in search state
  components/emoji_picker/emoji_picker.jsx
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, QA Review Done, release-note-none

#9532 Automated cherry pick of #9531
  components/emoji_picker/emoji_picker.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#9530 Automated cherry pick of #9528 on cloud
  i18n/de.json
  i18n/en_AU.json
  i18n/ja.json
  i18n/nl.json
  i18n/pl.json
  i18n/sv.json
  i18n/tr.json
Labels: release-note-none

#9493 Fix typo s/fatures/features in en.json
  components/admin_console/license_settings/starter_edition/starter_left_panel.tsx
  i18n/en.json
Labels: 4: Reviews Complete, release-note-none, Contributor

#9542 MM-40630 Update mmjstools so i18n-extract supports TypeScript
  components/widgets/users/avatars/avatars.tsx
  i18n/en.json
  package-lock.json
  package.json
Labels: 4: Reviews Complete, release-note-none

#9470 MM-40220 - new modal for deletion confirmation
  components/admin_console/license_settings/license_settings.tsx
  components/admin_console/license_settings/modals/__snapshots__/confirm_license_removal_modal.test.tsx.snap
  components/admin_console/license_settings/modals/confirm_license_removal_modal.scss
  components/admin_console/license_settings/modals/confirm_license_removal_modal.test.tsx
  components/admin_console/license_settings/modals/confirm_license_removal_modal.tsx
  components/admin_console/license_settings/modals/ee_license_modal.scss
  components/admin_console/license_settings/modals/ee_license_modal.tsx
  components/common/svg_images_components/alert_svg.tsx
  i18n/en.json
  utils/constants.jsx
Labels: Setup Cloud Test Server, QA Review Done, 1: UX Review, release-note-none

#9537 focus user email input by default for invitation modal
  components/invitation_modal/invite_view.tsx
  components/widgets/inputs/users_emails_input.tsx
  e2e/cypress/integration/team_settings/invite_members_spec.js
Labels: 2: Dev Review, Setup Cloud Test Server, QA Review Done, release-note

#9543 MM-40633 Remove Storybook-related CI steps
  .circleci/config.yml
Labels: 4: Reviews Complete, release-note-none

#9535 MM-40599 - fix typo in features list
  components/admin_console/license_settings/team_edition/team_edition_right_panel.tsx
Labels: 2: Dev Review, QA Review Done, release-note-none

#9422 Removing more unused files
  actions/views/settings.js
  components/admin_console/brand_image_setting/__snapshots__/upload_button.test.tsx.snap
  components/admin_console/brand_image_setting/upload_button.test.tsx
  components/admin_console/brand_image_setting/upload_button.tsx
  components/admin_console/feature_discovery/features/images/permissions_svg.tsx
  components/admin_console/system_user_detail/team_list/team_image.tsx
  components/admin_console/system_users/list/index.js
  components/admin_console/team_channel_settings/__snapshots__/abstract_list.test.jsx.snap
  components/admin_console/team_channel_settings/abstract_list.test.jsx
  components/admin_console/team_channel_settings/channel/list/__snapshots__/channel_row.test.tsx.snap
  components/admin_console/team_channel_settings/channel/list/channel_row.test.tsx
  components/admin_console/team_channel_settings/channel/list/channel_row.tsx
  components/admin_console/team_channel_settings/group/group_row.tsx
  components/admin_console/team_channel_settings/team/list/__snapshots__/team_row.test.tsx.snap
  components/admin_console/team_channel_settings/team/list/team_row.test.tsx
  components/admin_console/team_channel_settings/team/list/team_row.tsx
  components/gif_picker/static/gif.worker.js
  components/gif_picker/utils/request.js
  components/global_header/assets.tsx
  components/persist_gate/index.ts
  components/persist_gate/persist_gate.ts
  components/search_hint/__snapshots__/data_retention_hint.test.tsx.snap
  components/search_hint/data_retention_hint.test.tsx
  components/search_hint/data_retention_hint.tsx
  components/sidebar/__snapshots__/sidebar_tutorial_tip.test.jsx.snap
  components/sidebar/sidebar_tutorial_tip.jsx
  components/sidebar/sidebar_tutorial_tip.test.jsx
  components/toast_wrapper/toast_wrapper.jsx
  i18n/en.json
  selectors/views/channel_selector_modal.ts
  selectors/views/settings.ts
Labels: 4: Reviews Complete, release-note-none

#9273 [MM-39547] Introduce App Bar
  actions/apps.ts
  actions/command.ts
  components/app_bar/__snapshots__/app_bar.test.tsx.snap
  components/app_bar/app_bar.scss
  components/app_bar/app_bar.test.tsx
  components/app_bar/app_bar.tsx
  components/app_bar/app_bar_binding.tsx
  components/app_bar/app_bar_plugin_component.tsx
  components/channel_layout/__snapshots__/channel_controller.test.tsx.snap
  components/channel_layout/channel_controller.test.tsx
  components/channel_layout/channel_controller.tsx
  components/dot_menu/dot_menu.tsx
  components/needs_team/index.ts
  components/needs_team/needs_team.test.tsx
  components/needs_team/needs_team.tsx
  components/post_view/embedded_bindings/button_binding/button_binding.tsx
  components/post_view/embedded_bindings/select_binding/select_binding.tsx
  packages/mattermost-redux/src/constants/apps.ts
  packages/mattermost-redux/src/selectors/entities/apps.ts
  plugins/channel_header_plug/channel_header_plug.tsx
  plugins/channel_header_plug/index.ts
  plugins/mobile_channel_header_plug/mobile_channel_header_plug.tsx
  plugins/registry.js
  reducers/plugins/index.ts
  selectors/plugins.ts
  selectors/rhs.ts
  types/store/plugins.ts
Labels: 1: PM Review, QA Review Done, release-note

#9494 Splitting the OpenInvite section of team_general_tab into another component
  components/team_general_tab/__snapshots__/open_invite.test.tsx.snap
  components/team_general_tab/__snapshots__/team_general_tab.test.jsx.snap
  components/team_general_tab/open_invite.test.tsx
  components/team_general_tab/open_invite.tsx
  components/team_general_tab/team_general_tab.jsx
  components/team_general_tab/team_general_tab.test.jsx
Labels: 4: Reviews Complete, release-note-none

#9549 Translations update from Mattermost Weblate
  i18n/bg.json
  i18n/de.json
  i18n/en_AU.json
  i18n/es.json
  i18n/fr.json
  i18n/hu.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: release-note-none

#9533 Proposed changes to "Contact sales" area title
  components/admin_console/license_settings/enterprise_edition/enterprise_edition_right_panel.tsx
  i18n/en.json
Labels: 4: Reviews Complete, QA Review Done, AutoMerge, release-note-none

#9551 Lock CI from /release-6.3
  .circleci/config.yml
  .gitlab-ci.yml
Labels: release-note-none

#9550 use state.show & top level onExited for invitation modal
  components/invitation_modal/index.tsx
  components/invitation_modal/invitation_modal.test.tsx
  components/invitation_modal/invitation_modal.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, QA Review Done, release-note

#9544 [MM-40407] - Do not show the Renew Now if the license id does not exist in the portal
  components/admin_console/license_settings/renew_license_card/renew_license_card.test.tsx
  components/admin_console/license_settings/renew_license_card/renew_license_card.tsx
  components/announcement_bar/contact_sales/contact_us.tsx
  components/announcement_bar/renewal_link/renewal_link.test.tsx
  components/announcement_bar/renewal_link/renewal_link.tsx
  i18n/en.json
Labels: release-note-none, QA Deferred

#9562 Automated cherry pick of #9500
  components/emoji_picker/components/emoji_picker_preview.tsx
  components/emoji_picker/emoji_picker.jsx
  components/post_view/reaction_list/index.ts
  selectors/emojis.js
  utils/emoticons.tsx
  utils/post_utils.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#9552 Automated cherry pick of #9430
  client/websocket_client.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#9568 Automated cherry pick of #9527
  NOTICE.txt
  components/root/root.jsx
  components/root/root.test.jsx
  package-lock.json
  package.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#9574 Automated cherry pick of #9408
  package-lock.json
  package.json
  webpack.config.js
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#9575 Automated cherry pick of #9405
  package-lock.json
  package.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#9588 Automated cherry pick of #9531
  components/emoji_picker/emoji_picker.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#9553 Automated cherry pick of #9472
  plugins/export.js
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#9546 MM-40600 - use custom type and set correct value to api response
  components/admin_console/license_settings/__snapshots__/license_settings.test.jsx.snap
  components/admin_console/license_settings/index.ts
  components/admin_console/license_settings/license_settings.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, QA Review Done, AutoMerge, release-note

#9564 Automated cherry pick of #9506
  components/rhs_search_nav/__snapshots__/rhs_search_nav.test.tsx.snap
  components/rhs_search_nav/index.ts
  components/rhs_search_nav/rhs_search_nav.test.tsx
  components/rhs_search_nav/rhs_search_nav.tsx
  components/search/search.tsx
  components/search/user_guide_dropdown/__snapshots__/user_guide_dropdown.test.tsx.snap
  components/search/user_guide_dropdown/index.ts
  components/search/user_guide_dropdown/user_guide_dropdown.test.tsx
  components/search/user_guide_dropdown/user_guide_dropdown.tsx
  utils/utils.d.ts
  utils/utils.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#9565 Automated cherry pick of #9427
  components/timestamp/index.test.tsx
  components/timestamp/index.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#9566 Automated cherry pick of #9510
  components/rhs_card/index.js
  components/rhs_card/rhs_card.jsx
  components/rhs_card/rhs_card.test.jsx
  components/rhs_comment/__snapshots__/rhs_comment.test.jsx.snap
  components/rhs_comment/index.ts
  components/rhs_comment/rhs_comment.jsx
  components/rhs_comment/rhs_comment.test.jsx
  components/rhs_header_post/index.ts
  components/rhs_header_post/rhs_header_post.tsx
  components/rhs_root_post/index.ts
  components/rhs_root_post/rhs_root_post.jsx
  components/rhs_root_post/rhs_root_post.test.jsx
  components/search/index.tsx
  components/search/search.tsx
  components/search/types.ts
  components/search_results_item/index.test.js
  components/search_results_item/index.ts
  components/search_results_item/search_results_item.jsx
  components/search_results_item/search_results_item.test.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#9578 Automated cherry pick of #9542
  i18n/en.json
  package-lock.json
  package.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#9580 Automated cherry pick of #9537
  components/invitation_modal/invite_view.tsx
  components/widgets/inputs/users_emails_input.tsx
  e2e/cypress/integration/team_settings/invite_members_spec.js
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#9582 Automated cherry pick of #9494
  components/team_general_tab/__snapshots__/open_invite.test.tsx.snap
  components/team_general_tab/__snapshots__/team_general_tab.test.jsx.snap
  components/team_general_tab/open_invite.test.tsx
  components/team_general_tab/open_invite.tsx
  components/team_general_tab/team_general_tab.jsx
  components/team_general_tab/team_general_tab.test.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#9583 Automated cherry pick of #9533
  components/admin_console/license_settings/enterprise_edition/enterprise_edition_right_panel.tsx
  i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#9557 Automated cherry pick of #9262
  actions/team_actions.jsx
  components/channel_layout/channel_controller.tsx
  components/global_header/global_header.tsx
  components/global_header/hooks.tsx
  components/root/root.jsx
  components/team_sidebar/index.ts
  components/team_sidebar/team_sidebar.tsx
  plugins/registry.js
  sass/layout/_team-sidebar.scss
  sass/routes/_backstage.scss
  selectors/products.ts
  types/store/plugins.ts
  utils/products.ts
  utils/test_helper.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#9559 Automated cherry pick of #9496
  sass/components/_day-picker.scss
  sass/components/_suggestion-list.scss
  utils/utils.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#9563 Automated cherry pick of #9504
  components/dnd_custom_time_picker_modal/dnd_custom_time_picker_modal.scss
  components/dnd_custom_time_picker_modal/dnd_custom_time_picker_modal.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#9567 Automated cherry pick of #9535
  components/admin_console/license_settings/team_edition/team_edition_right_panel.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#9555 Automated cherry pick of #9449
  components/admin_console/permission_schemes_settings/permission_schemes_settings.jsx
  components/admin_console/permission_schemes_settings/permission_system_scheme_settings/__snapshots__/permission_system_scheme_settings.test.tsx.snap
  components/admin_console/permission_schemes_settings/permission_system_scheme_settings/permission_system_scheme_settings.test.tsx
  components/admin_console/permission_schemes_settings/permission_system_scheme_settings/permission_system_scheme_settings.tsx
  components/admin_console/permission_schemes_settings/permission_team_scheme_settings/__snapshots__/permission_team_scheme_settings.test.tsx.snap
  components/admin_console/permission_schemes_settings/permission_team_scheme_settings/permission_team_scheme_settings.test.tsx
  components/admin_console/permission_schemes_settings/permission_team_scheme_settings/permission_team_scheme_settings.tsx
  components/admin_console/permission_schemes_settings/permissions_tree/__snapshots__/permissions_tree.test.tsx.snap
  components/admin_console/permission_schemes_settings/permissions_tree/index.tsx
  components/admin_console/permission_schemes_settings/permissions_tree/permissions_tree.tsx
  components/admin_console/permission_schemes_settings/permissions_tree_playbooks.tsx
  components/admin_console/permission_schemes_settings/permissions_tree_runs.tsx
  components/admin_console/team_channel_settings/channel/details/channel_details.test.tsx
  i18n/en.json
  packages/mattermost-redux/src/constants/general.ts
  packages/mattermost-redux/src/constants/permissions.ts
  packages/mattermost-redux/src/types/schemes.ts
  utils/constants.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#9579 Automated cherry pick of #9470
  components/admin_console/license_settings/license_settings.tsx
  components/admin_console/license_settings/modals/__snapshots__/confirm_license_removal_modal.test.tsx.snap
  components/admin_console/license_settings/modals/confirm_license_removal_modal.scss
  components/admin_console/license_settings/modals/confirm_license_removal_modal.test.tsx
  components/admin_console/license_settings/modals/confirm_license_removal_modal.tsx
  components/admin_console/license_settings/modals/ee_license_modal.scss
  components/admin_console/license_settings/modals/ee_license_modal.tsx
  components/common/svg_images_components/alert_svg.tsx
  i18n/en.json
  utils/constants.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#9556 Automated cherry pick of #9505
  components/suggestion/suggestion_box/suggestion_box.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#9560 Automated cherry pick of #9495
  actions/views/channel.js
  actions/views/channel.test.js
  actions/websocket_actions.jsx
  components/delete_channel_modal/index.ts
  components/rhs_header_post/index.ts
  components/rhs_header_post/rhs_header_post.spec.tsx
  components/rhs_header_post/rhs_header_post.tsx
  e2e/cypress/integration/archived_channel/archive_channel_post_spec.js
  e2e/cypress/integration/channel/leave_channel_spec.js
  packages/mattermost-redux/src/reducers/entities/threads/counts.ts
  packages/mattermost-redux/src/reducers/entities/threads/index.ts
  packages/mattermost-redux/src/reducers/entities/threads/threadsInTeam.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#9561 Automated cherry pick of #9424
  plugins/channel_header_plug/__snapshots__/channel_header_plug.test.tsx.snap
  plugins/channel_header_plug/channel_header_plug.test.tsx
  plugins/channel_header_plug/channel_header_plug.tsx
  plugins/channel_header_plug/index.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#9586 Automated cherry pick of #9544
  components/admin_console/license_settings/renew_license_card/renew_license_card.test.tsx
  components/admin_console/license_settings/renew_license_card/renew_license_card.tsx
  components/announcement_bar/contact_sales/contact_us.tsx
  components/announcement_bar/renewal_link/renewal_link.test.tsx
  components/announcement_bar/renewal_link/renewal_link.tsx
  i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#9569 Automated cherry pick of #9333
  components/root/root.jsx
  packages/mattermost-redux/src/client/client4.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#9570 Automated cherry pick of #9493
  components/admin_console/license_settings/starter_edition/starter_left_panel.tsx
  i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#9572 Automated cherry pick of #9452
  components/__snapshots__/searchable_channel_list.test.jsx.snap
  components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.jsx.snap
  components/plugin_marketplace/__snapshots__/marketplace_modal.test.tsx.snap
  components/plugin_marketplace/marketplace_modal.tsx
  components/quick_input/quick_input.test.tsx
  components/quick_input/quick_input.tsx
  components/suggestion/modal_suggestion_list.jsx
  components/suggestion/rhs_suggestion_list.tsx
  components/suggestion/suggestion_box/suggestion_box.jsx
  components/suggestion/suggestion_list.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#9591 Automated cherry pick of #9546
  components/admin_console/license_settings/__snapshots__/license_settings.test.jsx.snap
  components/admin_console/license_settings/index.ts
  components/admin_console/license_settings/license_settings.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#9581 Automated cherry pick of #9543
  .circleci/config.yml
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#9547 fix Dm name in file preview modal info bar
  components/file_preview_modal/file_preview_modal_info/__snapshots__/file_preview_modal_info.test.tsx.snap
  components/file_preview_modal/file_preview_modal_info/file_preview_modal_info.tsx
Labels: release-note, QA Deferred

#9512 MM-40114/MM-40545 Clean up MobileSidebarHeader and have it use getIsMobileView
  components/sidebar/legacy_sidebar_header/dropdown/index.ts
  components/sidebar/legacy_sidebar_header/dropdown/sidebar_header_dropdown.tsx
  components/sidebar/legacy_sidebar_header/legacy_sidebar_header.tsx
  components/sidebar/mobile_sidebar_header/contents/contents.tsx
  components/sidebar/mobile_sidebar_header/contents/index.ts
  components/sidebar/mobile_sidebar_header/index.ts
  components/sidebar/mobile_sidebar_header/mobile_sidebar_header.tsx
  components/sidebar/sidebar.tsx
  e2e/cypress/integration/keyboard_shortcuts/ctrl_cmd_a_account_settings_spec.js
  sass/layout/_headers.scss
  sass/responsive/_mobile.scss
Labels: 4: Reviews Complete, release-note

#9592 [MM-40481] fix post hover menu overlap
  sass/components/_post-menu.scss
Labels: Setup Cloud Test Server, release-note, QA Deferred
