Repository mattermost/mattermost-webapp, pull requests merged in 2022-09, with the labels that each got.

#11038 updated version for compass-icons package
  package-lock.json
  package.json
Labels: 2: Dev Review, release-note-none, kind/chore

#11045 Automated cherry pick of #10983
  components/activity_and_insights/insights/top_boards/top_boards.tsx
  components/activity_and_insights/insights/top_boards/top_boards_table/top_boards_table.tsx
  packages/types/src/insights.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#11046 Automated cherry pick of #10971
  components/suggestion/switch_channel_provider.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#11043 Weblate 220901
  i18n/de.json
  i18n/en_AU.json
  i18n/hu.json
  i18n/tr.json
Labels: 4: Reviews Complete, release-note-none

#10995 Fix URLs in translations string for personal access tokens
  components/user_settings/security/user_access_token_section/user_access_token_section.tsx
  i18n/en.json
Labels: 4: Reviews Complete, release-note, QA Deferred

#11049 MM-46842: Do not query channelMemberCounts without config knob
  actions/websocket_actions.jsx
  components/create_comment/create_comment.tsx
  components/create_post/create_post.tsx
Labels: 4: Reviews Complete, release-note

#11050 MM-46842: Do not query channelMemberCounts without config knob (#11049)
  actions/websocket_actions.jsx
  components/create_comment/create_comment.tsx
  components/create_post/create_post.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#11022 Upgrade pdfjs-dist to latest version
  components/pdf_preview.jsx
  package-lock.json
  package.json
Labels: 4: Reviews Complete, Setup Cloud Test Server, QA Review Done, release-note-none

#11013 Fix error in error handling
  packages/mattermost-redux/src/actions/errors.ts
  packages/types/src/errors.ts
  root.tsx
Labels: 4: Reviews Complete, release-note-none, QA Deferred

#10892 [MM-45564] - Notify Admin v2
  components/at_plan_mention/at_plan_mention.test.tsx
  components/at_plan_mention/index.tsx
  components/at_sum_members_mention/index.tsx
  components/at_sum_members_mention/notification_from_members_modal.scss
  components/at_sum_members_mention/notification_from_members_modal.tsx
  components/center_message_lock/index.tsx
  components/custom_open_pricing_modal_post_renderer/index.tsx
  components/feature_restricted_modal/feature_restricted_modal.tsx
  components/file_limit_sticky_banner/index.tsx
  components/global_header/left_controls/product_menu/product_menu.tsx
  components/global_header/left_controls/product_menu/product_menu_list/__snapshots__/product_menu_list.test.tsx.snap
  components/global_header/left_controls/product_menu/product_menu_list/product_menu_list.tsx
  components/invitation_modal/invite_as.tsx
  components/main_menu/__snapshots__/main_menu.test.tsx.snap
  components/main_menu/main_menu.tsx
  components/markdown/markdown.tsx
  components/notify_admin_cta/notify_admin_cta.tsx
  components/pricing_modal/content.tsx
  components/widgets/menu/menu_items/restricted_indicator.tsx
  components/widgets/menu/menu_items/useWords.tsx
  e2e/cypress/tests/integration/enterprise/cloud/billing/notify_admin_spec.js
  i18n/en.json
  packages/client/src/client4.ts
  packages/types/src/cloud.ts
  plugins/export.js
  utils/constants.tsx
  utils/message_html_to_component.jsx
  utils/notify_admin_utils.ts
  utils/text_formatting.tsx
Labels: 2: Dev Review, 3: QA Review, 1: UX Review, Setup Cloud + CWS Test Server, release-note-none

#11054 Weblate fix
  i18n/tr.json
Labels: release-note-none, Do Not Merge/Mattermod

#11051 Cherry-picking translations
  i18n/de.json
  i18n/en_AU.json
  i18n/hu.json
  i18n/tr.json
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none, Contributor

#11057 Update react-overlays and re-add rootClose for profile popover
  components/profile_picture/__snapshots__/profile_picture.test.tsx.snap
  components/profile_picture/profile_picture.tsx
  components/user_profile/__snapshots__/user_profile.test.tsx.snap
  components/user_profile/user_profile.tsx
  package-lock.json
  package.json
  packages/components/package.json
Labels: 2: Dev Review, release-note

#11024 [MM-46663] Only enable marketplace command execution when config allows it and user has permission
  actions/command.test.js
  actions/command.ts
  components/global_header/left_controls/product_menu/product_menu_list/index.ts
  i18n/en.json
  packages/mattermost-redux/src/selectors/entities/general.ts
Labels: release-note-none, QA Deferred

#11072 Automated cherry pick of #11024
  actions/command.test.js
  actions/command.ts
  components/global_header/left_controls/product_menu/product_menu_list/index.ts
  i18n/en.json
  packages/mattermost-redux/src/selectors/entities/general.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#11074 Automated cherry pick of #10995
  components/user_settings/security/user_access_token_section/user_access_token_section.tsx
  i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#11042 [MM-46808] Add Calls keyboard shortcuts to in product help modal
  components/keyboard_shortcuts/keyboard_shortcuts_modal/__snapshots__/keyboard_shortcuts_modal.test.tsx.snap
  components/keyboard_shortcuts/keyboard_shortcuts_modal/keyboard_shortcuts_modal.scss
  components/keyboard_shortcuts/keyboard_shortcuts_modal/keyboard_shortcuts_modal.test.tsx
  components/keyboard_shortcuts/keyboard_shortcuts_modal/keyboard_shortcuts_modal.tsx
  components/keyboard_shortcuts/keyboard_shortcuts_sequence/__snapshots__/keyboard_shortcuts_sequence.test.tsx.snap
  components/keyboard_shortcuts/keyboard_shortcuts_sequence/keyboard_shortcuts.ts
  components/keyboard_shortcuts/keyboard_shortcuts_sequence/keyboard_shortcuts_sequence.test.tsx
  components/keyboard_shortcuts/keyboard_shortcuts_sequence/keyboard_shortcuts_sequence.tsx
  i18n/en.json
  packages/client/src/client4.ts
Labels: CherryPick/Approved, Setup Cloud Test Server, release-note, Editor review

#11078 Automated cherry pick of #11042
  components/keyboard_shortcuts/keyboard_shortcuts_modal/__snapshots__/keyboard_shortcuts_modal.test.tsx.snap
  components/keyboard_shortcuts/keyboard_shortcuts_modal/keyboard_shortcuts_modal.scss
  components/keyboard_shortcuts/keyboard_shortcuts_modal/keyboard_shortcuts_modal.test.tsx
  components/keyboard_shortcuts/keyboard_shortcuts_modal/keyboard_shortcuts_modal.tsx
  components/keyboard_shortcuts/keyboard_shortcuts_sequence/__snapshots__/keyboard_shortcuts_sequence.test.tsx.snap
  components/keyboard_shortcuts/keyboard_shortcuts_sequence/keyboard_shortcuts.ts
  components/keyboard_shortcuts/keyboard_shortcuts_sequence/keyboard_shortcuts_sequence.test.tsx
  components/keyboard_shortcuts/keyboard_shortcuts_sequence/keyboard_shortcuts_sequence.tsx
  i18n/en.json
  packages/client/src/client4.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#11002 Playwright: Update dependencies, support HA server and fix tests
  .gitignore
  e2e/playwright/README.md
  e2e/playwright/global_setup.ts
  e2e/playwright/package-lock.json
  e2e/playwright/package.json
  e2e/playwright/playwright.config.ts
  e2e/playwright/support/server/default_config.ts
  e2e/playwright/support/ui/page/landing_login.ts
  e2e/playwright/support/utils/index.ts
  e2e/playwright/support/visual/applitools.ts
  e2e/playwright/support/visual/index.ts
  e2e/playwright/support/visual/percy.ts
  e2e/playwright/test.config.ts
  e2e/playwright/tests/visual/intro_channel.spec.ts
  e2e/playwright/tests/visual/intro_channel.spec.ts-snapshots/intro-to-channel-as-regular-user-chrome-linux.png
  e2e/playwright/tests/visual/intro_channel.spec.ts-snapshots/intro-to-channel-as-regular-user-firefox-linux.png
  e2e/playwright/tests/visual/intro_channel.spec.ts-snapshots/intro-to-channel-as-regular-user-ipad-linux.png
  e2e/playwright/tests/visual/intro_channel.spec.ts-snapshots/intro-to-channel-as-regular-user-iphone-linux.png
  e2e/playwright/tests/visual/landing_page.spec.ts
  e2e/playwright/tests/visual/landing_page.spec.ts-snapshots/landing-login-chrome-linux.png
  e2e/playwright/tests/visual/landing_page.spec.ts-snapshots/landing-login-firefox-linux.png
  e2e/playwright/tests/visual/login.spec.ts
  e2e/playwright/tests/visual/signup_email.spec.ts
Labels: 4: Reviews Complete, release-note-none

#11028 Convert mattermost-webapp/packages/mattermost-redux/src/selectors tests to Typescript
  packages/mattermost-redux/src/actions/roles.test.js
  packages/mattermost-redux/src/constants/general.ts
  packages/mattermost-redux/src/selectors/entities/channel_categories.test.ts
  packages/mattermost-redux/src/selectors/entities/channels.test.ts
  packages/mattermost-redux/src/selectors/entities/channels.ts
  packages/mattermost-redux/src/selectors/entities/emojis.test.ts
  packages/mattermost-redux/src/selectors/entities/general.test.ts
  packages/mattermost-redux/src/selectors/entities/groups.test.ts
  packages/mattermost-redux/src/selectors/entities/i18n.test.ts
  packages/mattermost-redux/src/selectors/entities/integrations.test.ts
  packages/mattermost-redux/src/selectors/entities/posts.test.ts
  packages/mattermost-redux/src/selectors/entities/posts.ts
  packages/mattermost-redux/src/selectors/entities/preferences.test.ts
  packages/mattermost-redux/src/selectors/entities/roles.test.ts
  packages/mattermost-redux/src/selectors/entities/schemes.test.ts
  packages/mattermost-redux/src/selectors/entities/search.test.ts
  packages/mattermost-redux/src/selectors/entities/teams.test.ts
  packages/mattermost-redux/src/selectors/entities/threads.test.ts
  packages/mattermost-redux/src/selectors/entities/users.test.ts
  packages/mattermost-redux/src/selectors/entities/utils.test.ts
  packages/mattermost-redux/src/utils/channel_utils.ts
  packages/mattermost-redux/test/merge_objects.ts
  packages/mattermost-redux/test/test_helper.ts
Labels: 4: Reviews Complete, release-note-none

#11073 MM-46805: Show Top Playbooks widget.
  components/activity_and_insights/activity_and_insights.scss
Labels: 2: Dev Review, CherryPick/Approved, release-note-none, QA Deferred

#11080 Automated cherry pick of #11073
  components/activity_and_insights/activity_and_insights.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#10994 [MM-46239] Remove target=_blank from support packet link
  components/commercial_support_modal/__snapshots__/commercial_support_modal.test.tsx.snap
  components/commercial_support_modal/commercial_support_modal.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none

#11053 Cypress/e2e:fixed Cloud
  e2e/cypress/tests/integration/accessibility/accessibility_popovers_spec.js
  e2e/cypress/tests/integration/autocomplete/database/users_in_channel_switcher_spec.js
  e2e/cypress/tests/integration/autocomplete/database/users_in_message_input_box_spec.js
  e2e/cypress/tests/integration/autocomplete/database/users_spec.js
  e2e/cypress/tests/integration/messaging/message_spec.js
  e2e/cypress/tests/integration/search_autocomplete/channels_spec.js
  e2e/cypress/tests/integration/search_autocomplete/renaming_spec.js
Labels: release-note-none

#10986 MM-34333: Migrate 'components/gif_picker', subfolders and associated tests to TypeScript
  components/emoji_picker/emoji_picker_tabs.jsx
  components/gif_picker/components/App/index.tsx
  components/gif_picker/components/Categories/index.tsx
  components/gif_picker/components/Header/index.tsx
  components/gif_picker/components/Search/index.tsx
  components/gif_picker/components/SearchBar/index.tsx
  components/gif_picker/components/SearchGrid/SearchGrid.jsx
  components/gif_picker/components/SearchItem/index.tsx
  components/gif_picker/components/Trending/index.tsx
  components/gif_picker/gif_picker.jsx
  components/gif_picker/gif_picker.tsx
  components/gif_picker/utils/constants.ts
  packages/mattermost-redux/src/actions/gifs.ts
  packages/mattermost-redux/src/store/initial_state.ts
  packages/types/src/gifs.ts
  packages/types/src/store.ts
Labels: 4: Reviews Complete, release-note-none, Contributor

#11048 GitHub Workflows security hardening
  .github/workflows/codeql-analysis.yml
Labels: 4: Reviews Complete, release-note-none, Contributor

#11047 [MM-46143]: align the SuggestionList with the Textbox
  components/forward_post_modal/forward_post_comment_input.tsx
  components/suggestion/suggestion_box/suggestion_box.jsx
  components/textbox/textbox.tsx
  utils/utils.tsx
Labels: 4: Reviews Complete, release-note-none, kind/bug

#11067 Temporarily disable bundle size analysis CI
  .github/workflows/bundle-size-analysis.yml
  webpack.config.js
Labels: 4: Reviews Complete, release-note-none

#11091 Downgrade Bulgarian/Български to Beta
  components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
  i18n/i18n.jsx
Labels: 4: Reviews Complete, Docs/Needed, CherryPick/Approved, AutoMerge, release-note

#11092 Automated cherry pick of #11091
  components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
  i18n/i18n.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#11062 MM-46865 : Improve return type of 'ActionFunc' of 'mattermost-redux/types/actions'
  packages/client/src/client4.ts
  packages/mattermost-redux/src/actions/groups.ts
  packages/mattermost-redux/src/actions/teams.ts
  packages/mattermost-redux/src/types/actions.ts
Labels: 2: Dev Review, release-note-none

#11063 MM-46864 : Migrate "actions/team_actions.js" and tests to typescript
  actions/team_actions.test.ts
  actions/team_actions.ts
  components/team_members_dropdown/index.ts
  components/team_sidebar/index.ts
  packages/mattermost-redux/src/types/actions.ts
Labels: 4: Reviews Complete, release-note-none

#11076 Fix plugin ChannelHeaderMenu component shouldRender function check
  selectors/plugins.ts
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#11105 Automated cherry pick of #11076
  selectors/plugins.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#11106 Automated cherry pick of #11076
  selectors/plugins.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#11060 invite member modal fits on screen for small screen
  components/invitation_modal/invitation_modal.scss
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none

#11064 MM-46866 : Migrate "components/channel_layout/channel_controller" to functional component
  components/channel_layout/__snapshots__/channel_controller.test.tsx.snap
  components/channel_layout/center_channel/index.ts
  components/channel_layout/channel_controller.test.tsx
  components/channel_layout/channel_controller.tsx
Labels: QA Review Done, release-note-none

#11084 [MM-46607] Style fixes for insights
  components/activity_and_insights/activity_and_insights.scss
  components/activity_and_insights/insights/insights_modal/insights_modal.scss
  components/activity_and_insights/insights/least_active_channels/least_active_channels_table/least_active_channels_table.tsx
  components/activity_and_insights/insights/top_dms_and_new_members/new_members_table/new_members_table.tsx
  sass/responsive/_desktop.scss
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, AutoMerge, release-note-none

#11111 Automated cherry pick of #11084
  components/activity_and_insights/activity_and_insights.scss
  components/activity_and_insights/insights/insights_modal/insights_modal.scss
  components/activity_and_insights/insights/least_active_channels/least_active_channels_table/least_active_channels_table.tsx
  components/activity_and_insights/insights/top_dms_and_new_members/new_members_table/new_members_table.tsx
  sass/responsive/_desktop.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#11030 [MM-45597]: made RhsSuggestionList default in ATE
  components/advanced_text_editor/advanced_text_editor.tsx
Labels: 4: Reviews Complete, release-note-none, kind/bug

#10951 MM-46408: adds priority in posts
  components/admin_console/admin_definition.jsx
  components/advanced_create_post/__snapshots__/advanced_create_post.test.jsx.snap
  components/advanced_create_post/advanced_create_post.test.jsx
  components/advanced_create_post/advanced_create_post.tsx
  components/advanced_create_post/index.ts
  components/advanced_text_editor/advanced_text_editor.scss
  components/advanced_text_editor/advanced_text_editor.tsx
  components/advanced_text_editor/formatting_bar/formatting_bar.tsx
  components/advanced_text_editor/formatting_bar/formatting_icon.tsx
  components/keyboard_shortcuts/keyboard_shortcuts_sequence/keyboard_shortcuts.ts
  components/post_priority/post_priority_label.tsx
  components/post_priority/post_priority_picker.tsx
  components/post_priority/post_priority_picker_item.tsx
  components/post_priority/post_priority_picker_overlay.tsx
  components/post_view/post/index.ts
  components/post_view/post_header/__snapshots__/post_header.test.tsx.snap
  components/post_view/post_header/post_header.tsx
  components/post_view/post_info/__snapshots__/post_info.test.tsx.snap
  components/post_view/post_info/index.ts
  components/post_view/post_info/post_info.test.tsx
  components/post_view/post_info/post_info.tsx
  components/post_view/post_message_preview/__snapshots__/post_message_preview.test.tsx.snap
  components/post_view/post_message_preview/index.ts
  components/post_view/post_message_preview/post_message_preview.test.tsx
  components/post_view/post_message_preview/post_message_preview.tsx
  components/rhs_root_post/__snapshots__/rhs_root_post.test.jsx.snap
  components/rhs_root_post/index.ts
  components/rhs_root_post/rhs_root_post.jsx
  components/rhs_root_post/rhs_root_post.test.jsx
  components/search_results_item/__snapshots__/search_results_item.test.jsx.snap
  components/search_results_item/index.ts
  components/search_results_item/search_results_item.jsx
  components/search_results_item/search_results_item.test.jsx
  components/textbox/textbox.tsx
  components/widgets/badges/__snapshots__/badge.test.tsx.snap
  components/widgets/badges/badge.scss
  components/widgets/badges/badge.test.tsx
  components/widgets/badges/badge.tsx
  i18n/en.json
  packages/mattermost-redux/src/selectors/entities/posts.ts
  packages/types/src/config.ts
  packages/types/src/posts.ts
  sass/base/_css_variables.scss
  sass/components/_post.scss
Labels: 4: Reviews Complete, release-note

#11090 [MM-43193]: Remove path fill for offline icon in post
  sass/components/_post.scss
Labels: release-note-none, Contributor

#11079 MM-44921_First admin signup in new server briefly flashes error screen
  components/signup/signup.tsx
Labels: 2: Dev Review, QA Review Done, release-note-none

#11117 Automated cherry pick of #11084
  components/activity_and_insights/activity_and_insights.scss
  components/activity_and_insights/insights/insights_modal/insights_modal.scss
  components/activity_and_insights/insights/least_active_channels/least_active_channels_table/least_active_channels_table.tsx
  components/activity_and_insights/insights/top_dms_and_new_members/new_members_table/new_members_table.tsx
  sass/responsive/_desktop.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#11102 Intro-link button fix
  sass/layout/_headers.scss
Labels: 2: Dev Review, release-note-none

#11001 MM-46004/MM-46274 Add Module Federation and Boards as a POC Product
  Makefile
  components/root/index.ts
  components/root/root.test.tsx
  components/root/root.tsx
  entry.js
  entry.tsx
  package-lock.json
  package.json
  packages/types/src/plugins.ts
  plugins/products.ts
  root.tsx
  types/products.d.ts
  webpack.config.js
Labels: 4: Reviews Complete, QA Review Done, release-note-none

#11125 MM-46977: fixes post priority menu
  components/post_priority/post_priority_picker_item.tsx
Labels: 4: Reviews Complete, release-note-none, QA Deferred

#11088 Update p-queue and jest
  package-lock.json
  package.json
Labels: 3: QA Review, Setup Cloud Test Server, release-note

#11129 Automated cherry pick of #11122
  components/activity_and_insights/activity_and_insights.scss
  components/activity_and_insights/insights/least_active_channels/least_active_channels.test.tsx
  components/activity_and_insights/insights/least_active_channels/least_active_channels_item/least_active_channels_item.tsx
  components/activity_and_insights/insights/least_active_channels/least_active_channels_table/least_active_channels_table.tsx
  i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#11128 Automated cherry pick of #11122
  components/activity_and_insights/activity_and_insights.scss
  components/activity_and_insights/insights/least_active_channels/least_active_channels.test.tsx
  components/activity_and_insights/insights/least_active_channels/least_active_channels_item/least_active_channels_item.tsx
  components/activity_and_insights/insights/least_active_channels/least_active_channels_table/least_active_channels_table.tsx
  i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#11086 Remove max-width on context menus
  components/sidebar/sidebar_header/sidebar_header.tsx
Labels: 4: Reviews Complete, release-note-none

#11085 Fix direct messages modal on mobile web view
  sass/responsive/_mobile.scss
Labels: 4: Reviews Complete, release-note-none

#10836 Upgrade React and relevant packages to v17
  .circleci/config.yml
  .npm-upgrade.json
  components/__snapshots__/searchable_channel_list.test.jsx.snap
  components/__snapshots__/textbox.test.tsx.snap
  components/admin_console/data_retention_settings/channel_list/__snapshots__/channel_list.test.tsx.snap
  components/admin_console/system_roles/system_role/system_role_users/__snapshots__/system_role_users.test.tsx.snap
  components/admin_console/system_users/list/__snapshots__/system_users_list.test.tsx.snap
  components/admin_console/team_channel_settings/channel/details/__snapshots__/channel_groups.test.tsx.snap
  components/admin_console/team_channel_settings/channel/details/channel_members/__snapshots__/channel_members.test.tsx.snap
  components/admin_console/team_channel_settings/channel/list/__snapshots__/channel_list.test.tsx.snap
  components/admin_console/team_channel_settings/team/details/__snapshots__/team_groups.test.tsx.snap
  components/admin_console/team_channel_settings/team/details/team_members/__snapshots__/team_members.test.tsx.snap
  components/advanced_create_comment/advanced_create_comment.tsx
  components/advanced_create_post/advanced_create_post.tsx
  components/at_mention/at_mention.test.tsx
  components/at_mention/at_mention.tsx
  components/channel_header_dropdown/__snapshots__/channel_header_dropdown.test.jsx.snap
  components/color_input.tsx
  components/create_comment/create_comment.tsx
  components/create_post/create_post.tsx
  components/custom_status/custom_status_modal.tsx
  components/edit_post/edit_post.tsx
  components/global_header/left_controls/product_menu/product_menu_list/__snapshots__/product_menu_list.test.tsx.snap
  components/main_menu/__snapshots__/main_menu.test.tsx.snap
  components/plugin_marketplace/__snapshots__/marketplace_modal.test.tsx.snap
  components/post_view/channel_intro_message/__snapshots__/channel_intro_message.test.tsx.snap
  components/post_view/post_info/post_info.tsx
  components/post_view/post_reaction/post_reaction.tsx
  components/post_view/reaction_list/reaction_list.tsx
  components/profile_picture/__snapshots__/profile_picture.test.tsx.snap
  components/profile_picture/profile_picture.tsx
  components/profile_popover/__snapshots__/profile_popover.test.tsx.snap
  components/rhs_comment/rhs_comment.tsx
  components/rhs_root_post/rhs_root_post.jsx
  components/select_team/components/__snapshots__/select_team_item.test.tsx.snap
  components/sidebar/__snapshots__/invite_members_button.test.tsx.snap
  components/status_dropdown/__snapshots__/status_dropdown.test.tsx.snap
  components/tutorial/tutorial_tip_legacy/tutorial_tip.tsx
  components/user_profile/__snapshots__/user_profile.test.tsx.snap
  components/user_profile/user_profile.tsx
  components/user_settings/security/__snapshots__/user_settings_security.test.tsx.snap
  e2e/cypress/package.json
  package-lock.json
  package.json
  packages/components/package.json
  packages/components/rollup.config.js
  plugins/test/__snapshots__/main_menu_action.test.jsx.snap
  tests/setup.js
Labels: 3: QA Review, Setup Cloud Test Server, release-note

#11032 [MM-46437]: removed submitting the forward on pressing enter
  components/forward_post_modal/forward_post_comment_input.tsx
  components/forward_post_modal/forward_post_modal.tsx
Labels: 2: Dev Review, Setup Cloud Test Server, QA Review Done, release-note-none, kind/bug

#11134 MM-46994 : Suffix REST to "fetchAllMyTeamsChannelsAndChannelMembers" & "fetchMyChannelsAndMembers"
  actions/channel_actions.jsx
  actions/channel_actions.test.js
  actions/global_actions.tsx
  components/channel_layout/channel_identifier_router/actions.ts
  components/needs_team/index.ts
  components/needs_team/needs_team.test.tsx
  components/needs_team/needs_team.tsx
  components/suggestion/switch_channel_provider.jsx
  packages/mattermost-redux/src/actions/channels.test.js
  packages/mattermost-redux/src/actions/channels.ts
  packages/mattermost-redux/src/actions/teams.ts
Labels: 4: Reviews Complete, release-note-none

#11133 MM-46992 : Migrate "actions/channel_actions" to ts
  actions/channel_actions.test.ts
  actions/channel_actions.ts
  actions/views/channel.ts
  actions/views/create_comment.test.jsx
  actions/websocket_actions.jsx
  components/advanced_create_post/advanced_create_post.test.jsx
  components/create_post/create_post.test.jsx
  components/more_channels/index.ts
  components/permalink_view/actions.ts
  components/permalink_view/permalink_view.test.tsx
  components/post_view/message_attachments/action_menu/action_menu.test.tsx
  components/post_view/message_attachments/action_menu/action_menu.tsx
  components/post_view/message_attachments/action_menu/index.ts
  components/profile_popover/index.ts
  packages/mattermost-redux/src/actions/channels.ts
Labels: 2: Dev Review, release-note-none

#10768 [MM-45670]: added saving a draft for post editing
  actions/views/channel.ts
  actions/views/rhs.test.ts
  actions/views/rhs.ts
  components/advanced_create_comment/advanced_create_comment.tsx
  components/advanced_create_post/advanced_create_post.tsx
  components/advanced_create_post/index.ts
  components/create_comment/create_comment.tsx
  components/create_post/create_post.tsx
  components/create_post/index.ts
  components/edit_post/edit_post.tsx
  components/edit_post/index.ts
  components/post_view/post/__snapshots__/post.test.tsx.snap
  components/post_view/post/post.tsx
  components/sidebar/sidebar_channel/sidebar_channel_link/sidebar_channel_link.tsx
  utils/constants.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note, kind/bug

#11031 [MM-44400]: remove feature flag references and legacy code
  components/advanced_create_post/prewritten_chips.tsx
  components/channel_view/__snapshots__/channel_view.test.tsx.snap
  components/channel_view/channel_view.test.tsx
  components/channel_view/channel_view.tsx
  components/channel_view/index.ts
  components/common/chip/chip.tsx
  components/create_comment/__snapshots__/create_comment.test.tsx.snap
  components/create_comment/create_comment.test.tsx
  components/create_comment/create_comment.tsx
  components/create_comment/index.ts
  components/create_post/__snapshots__/create_post.test.jsx.snap
  components/create_post/create_post.test.jsx
  components/create_post/create_post.tsx
  components/create_post/index.ts
  components/create_post/prewritten_chips.tsx
  components/edit_channel_header_modal/index.ts
  components/file_upload/file_upload.test.tsx
  components/file_upload/file_upload.tsx
  components/file_upload/index.ts
  components/onboarding_tour/send_message_tour_tip.tsx
  components/threading/virtualized_thread_viewer/create_comment.tsx
  components/user_settings/advanced/index.ts
  components/user_settings/advanced/user_settings_advanced.test.tsx
  components/user_settings/advanced/user_settings_advanced.tsx
  e2e/playwright/support/server/default_config.ts
  i18n/en.json
  packages/mattermost-redux/src/selectors/entities/preferences.ts
Labels: 3: QA Review, Setup Cloud Test Server, release-note-none

#11126 [MM-46886] Fix responsive issue for insights
  components/activity_and_insights/activity_and_insights.scss
  sass/responsive/_desktop.scss
Labels: release-note-none

#11036 [MM-45688]: forward messages to new dm
  components/__snapshots__/textbox.test.tsx.snap
  components/add_user_to_channel_modal/__snapshots__/add_user_to_channel_modal.test.tsx.snap
  components/forward_post_modal/forward_post_channel_select.tsx
  components/forward_post_modal/forward_post_channel_select_styles.tsx
  components/forward_post_modal/forward_post_modal.tsx
  components/forward_post_modal/index.ts
  components/quick_switch_modal/__snapshots__/quick_switch_modal.test.tsx.snap
  components/suggestion/provider.jsx
Labels: 2: Dev Review, Setup Cloud Test Server, QA Review Done, release-note-none

#11011 Extract SkeletonLoader to @mattermost/components
  components/activity_and_insights/activity_and_insights.scss
  components/activity_and_insights/insights/least_active_channels/least_active_channels.tsx
  components/activity_and_insights/insights/skeleton_loader/bar_chart_loader/bar_chart_loader.tsx
  components/activity_and_insights/insights/skeleton_loader/circle_loader/circle_loader.tsx
  components/activity_and_insights/insights/skeleton_loader/line_chart_loader/line_chart_loader.tsx
  components/activity_and_insights/insights/skeleton_loader/skeleton_loader.scss
  components/activity_and_insights/insights/skeleton_loader/title_loader/title_loader.tsx
  components/activity_and_insights/insights/top_boards/top_boards.tsx
  components/activity_and_insights/insights/top_channels/top_channels.tsx
  components/activity_and_insights/insights/top_dms_and_new_members/top_dms_and_new_members.tsx
  components/activity_and_insights/insights/top_playbooks/top_playbooks.tsx
  components/activity_and_insights/insights/top_reactions/top_reactions.tsx
  components/activity_and_insights/insights/top_threads/top_threads.tsx
  packages/components/src/generic_modal/generic_modal.tsx
  packages/components/src/index.tsx
  packages/components/src/skeleton_loader/index.tsx
Labels: 4: Reviews Complete, release-note

#11071 improved alternate link placement on login and signup page
  components/login/__snapshots__/login.test.tsx.snap
  components/login/login.scss
  components/login/login.tsx
  components/signup/__snapshots__/signup.test.tsx.snap
  components/signup/signup.scss
  components/signup/signup.tsx
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, Setup Cloud Test Server, release-note-none

#11135 MM-45895: fixes dev console errors
  components/announcement_bar/configuration_bar/configuration_bar.tsx
  components/announcement_bar/text_dismissable_bar.tsx
  components/category_menu_items/category_menu_items.tsx
  components/deferComponentRender.tsx
  components/more_direct_channels/list/list.tsx
  components/needs_team/needs_team.tsx
  components/post_priority/post_priority_picker_item.tsx
  components/quick_switch_modal/__snapshots__/quick_switch_modal.test.tsx.snap
  components/quick_switch_modal/quick_switch_modal.tsx
  components/root/root.tsx
  components/threading/thread_viewer/thread_viewer.tsx
  components/timestamp/timestamp.tsx
  components/widgets/menu/menu_items/menu_item.tsx
Labels: 4: Reviews Complete, release-note-none

#11163 Adding basic top menu
  components/people/directory/directory.scss
  components/people/directory/directory.tsx
  i18n/en.json
Labels: release-note-none

#11168 Adds redux action to move a thread
  packages/client/src/client4.ts
  packages/mattermost-redux/src/action_types/posts.ts
  packages/mattermost-redux/src/actions/posts.ts
Labels: release-note-none

#11176 People - Profile card
  components/people/profile_card/profile_card.scss
  components/people/profile_card/profile_card.tsx
  i18n/en.json
Labels: release-note-none

#11179 Add sidebar for People + Groups navigation
  components/people/groups/groups.tsx
  components/people/people.tsx
  components/people/sidebar/sidebar.scss
  components/people/sidebar/sidebar.tsx
  i18n/en.json
Labels: 2: Dev Review, release-note-none

#11185 [contributor / wysiwyg] Add Feature Flag
  components/user_settings/advanced/index.ts
  components/user_settings/advanced/user_settings_advanced.tsx
  components/user_settings/advanced/wysiwyg_section/index.tsx
  components/user_settings/advanced/wysiwyg_section/wysiwyg_section.tsx
  packages/mattermost-redux/src/selectors/entities/preferences.ts
Labels: 2: Dev Review, do-not-merge/release-note-label-needed

#11137 [MM-46884] Load custom emojis in top reactions components
  components/activity_and_insights/insights/top_reactions/top_reactions.tsx
  components/activity_and_insights/insights/top_reactions/top_reactions_table/top_reactions_table.test.tsx
  components/activity_and_insights/insights/top_reactions/top_reactions_table/top_reactions_table.tsx
Labels: 3: QA Review, Setup Cloud Test Server, release-note-none

#11180 Wrangler UI
  components/dot_menu/__snapshots__/dot_menu.test.tsx.snap
  components/dot_menu/dot_menu.tsx
  components/forward_post_modal/forward_post_modal.tsx
  components/move_thread_modal/index.ts
  components/move_thread_modal/move_thread_modal.tsx
  i18n/en.json
  utils/constants.tsx
Labels: do-not-merge/release-note-label-needed

#11182 People list infinite scrolling
  components/people/directory/directory.scss
  components/people/directory/directory.tsx
  components/people/directory/people_list/index.ts
  components/people/directory/people_list/people_list.tsx
  components/people/people.tsx
  components/people/profile_card/profile_card.scss
  components/people/sidebar/sidebar.scss
Labels: release-note-none

#11193 People product init profile view layout
  components/people/people.tsx
  components/people/profile/profile.scss
  components/people/profile/profile.tsx
  components/people/profile/send_message_button.tsx
  components/people/profile_card/profile_card.scss
  components/people/profile_card/profile_card.tsx
  components/people/timezone_map/assets/timezones.json
  components/people/timezone_map/constant.ts
  components/people/timezone_map/timezone_map.tsx
  components/people/timezone_map/util.ts
  components/people/timezone_map/world_map.tsx
  i18n/en.json
  package-lock.json
  package.json
Labels: release-note-none

#11192 People - Add search to people list
  components/people/directory/directory.tsx
  components/people/directory/people_list/people_list.tsx
  components/people/profile_card/profile_card.scss
  components/people/profile_card/profile_card.tsx
Labels: 2: Dev Review, release-note-none

#11171 Fix ESLint in VS Code
  webpack.config.js
Labels: 4: Reviews Complete, release-note-none

#11000 cypress addition to notify admin v2
  e2e/cypress/tests/integration/enterprise/cloud/billing/notify_admin_spec.js
Labels: release-note-none

#11199 Translations update from Mattermost Weblate
  i18n/ja.json
Labels: release-note-none, Do Not Merge/Mattermod

#11161 MM-47061: Migrate "components/search_bar/search_bar.test.jsx" to Typescript
  components/search_bar/__snapshots__/search_bar.test.tsx.snap
  components/search_bar/search_bar.test.tsx
Labels: release-note, Contributor

#11175 MM-47062 : Migrate "components/file_upload_overlay.test.jsx" to Typescript
  components/__snapshots__/file_upload_overlay.test.tsx.snap
  components/file_upload_overlay.test.tsx
Labels: 4: Reviews Complete, release-note, Contributor

#10987 MM-46539 : E2E | Webapp | Fix cypress tests | Self hosted pricing modal
  e2e/cypress/tests/integration/enterprise/cloud/billing/after_subscription_spec.js
  e2e/cypress/tests/integration/enterprise/cloud/billing/billing_history_free_trial_spec.js
  e2e/cypress/tests/integration/enterprise/cloud/billing/cloud_pricing_modal_spec.js
  e2e/cypress/tests/integration/enterprise/cloud/billing/company_information_free_trial_spec.js
  e2e/cypress/tests/integration/enterprise/cloud/billing/payment_free_trial_spec.js
  e2e/cypress/tests/integration/enterprise/cloud/billing/self_hosted_pricing_modal_spec.js
  e2e/cypress/tests/integration/enterprise/cloud/billing/subscriptions_free_trial_spec.js
  e2e/cypress/tests/integration/enterprise/system_console/about/starter_edition_spec.js
Labels: release-note-none

#11138 [MM-45488] Adding insights to the channel switcher
  actions/views/channel.ts
  components/suggestion/switch_channel_provider.jsx
  components/suggestion/switch_channel_provider.test.jsx
  utils/constants.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note

#11144 [MM-46988] Fixing channel info shortcut and closing rhs when opening insights
  components/activity_and_insights/insights/insights.tsx
  components/sidebar_right/sidebar_right.tsx
Labels: 3: QA Review, Setup Cloud Test Server, release-note-none

#11006 MM-46470: Add copy content button for text / code file preview
  components/code_block/__snapshots__/code_block.test.jsx.snap
  components/code_preview.jsx
  components/copy_button.tsx
  components/file_preview_modal/__snapshots__/file_preview_modal.test.tsx.snap
  components/file_preview_modal/file_preview_modal.tsx
  components/file_preview_modal/file_preview_modal_footer/__snapshots__/file_preview_modal_footer.test.tsx.snap
  components/file_preview_modal/file_preview_modal_footer/file_preview_modal_footer.test.tsx
  components/file_preview_modal/file_preview_modal_footer/file_preview_modal_footer.tsx
  components/file_preview_modal/file_preview_modal_header/__snapshots__/file_preview_modal_header.test.tsx.snap
  components/file_preview_modal/file_preview_modal_header/file_preview_modal_header.test.tsx
  components/file_preview_modal/file_preview_modal_header/file_preview_modal_header.tsx
  components/file_preview_modal/file_preview_modal_main_actions/__snapshots__/file_preview_modal_main_actions.test.tsx.snap
  components/file_preview_modal/file_preview_modal_main_actions/file_preview_modal_main_actions.test.tsx
  components/file_preview_modal/file_preview_modal_main_actions/file_preview_modal_main_actions.tsx
  i18n/en.json
Labels: 4: Reviews Complete, release-note, Contributor

#11021 [MM-44394]: changed hotkeys and description
  components/advanced_create_comment/advanced_create_comment.tsx
  components/advanced_create_post/advanced_create_post.test.jsx
  components/advanced_create_post/advanced_create_post.tsx
  i18n/en.json
Labels: 2: Dev Review, 3: QA Review, Setup Cloud Test Server, release-note-none, kind/bug

#11213 Automated cherry pick of #11144
  components/activity_and_insights/insights/insights.tsx
  components/sidebar_right/sidebar_right.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#11029 MM-46653: Decrease the height of horizontal rules
  sass/layout/_markdown.scss
Labels: 4: Reviews Complete, release-note-none, Contributor

#11058 MM-46858: Hide mention badge in the team icon for muted channels
  packages/mattermost-redux/src/selectors/entities/channels.test.ts
  packages/mattermost-redux/src/selectors/entities/channels.ts
Labels: 4: Reviews Complete, release-note, Contributor

#11061 [MM-46819] Fix post overlay menu blocking message in compact mode
  sass/responsive/_tablet.scss
Labels: 4: Reviews Complete, release-note, Contributor

#11165 MM-47117 : Migrate "components/analytics/table_chart.test.jsx" to Typescript
  components/analytics/__snapshots__/table_chart.test.tsx.snap
  components/analytics/table_chart.test.tsx
  components/analytics/table_chart.tsx
Labels: QA Review Done, release-note, Contributor

#11159 MM-47099 : Migrate "components/channel_notifications_modal/components/expand_view.jsx" to Typescript
  components/channel_notifications_modal/components/expand_view.test.jsx
  components/channel_notifications_modal/components/expand_view.tsx
  components/channel_notifications_modal/components/notification_section.jsx
Labels: 3: QA Review, release-note-none, Contributor

#11151 MM-47120 : Migrate "components/create_team/index.js" to Typescript
  components/create_team/create_team.tsx
  components/create_team/index.ts
Labels: QA Review Done, release-note-none, Contributor

#11093 [MM-46861] Migrate tour tip to common components package
  components/actions_menu/actions_menu_tutorial_tip.tsx
  components/activity_and_insights/activity_and_insights_link/insights_tour_tip/insights_tour_tip.tsx
  components/onboarding_explore_tools_tour/boards_tour_tip.tsx
  components/onboarding_explore_tools_tour/onboarding_explore_tools_tour_tip.tsx
  components/onboarding_explore_tools_tour/playbooks_tour_tip.tsx
  components/onboarding_tasks/complete_your_profile_tour_tip.tsx
  components/onboarding_tasks/start_trial_tour_tip.tsx
  components/onboarding_tasks/visit_system_console_tour_tip.tsx
  components/onboarding_tour/channels_and_direct_messages_tour_tip.tsx
  components/onboarding_tour/create_and_join_channels_tour_tip.tsx
  components/onboarding_tour/customize_your_experience_tour_tip.tsx
  components/onboarding_tour/invite_people_tour_tip.tsx
  components/onboarding_tour/onboarding_tour_tip.tsx
  components/onboarding_tour/send_message_tour_tip.tsx
  components/status_dropdown/status_dropdown.tsx
  components/threading/global_threads_link/global_threads_link.tsx
  components/tutorial/tutorial_tip_legacy/hooks.ts
  components/tutorial/tutorial_tip_legacy/tutorial_tip.tsx
  entry.tsx
  packages/components/package.json
  packages/components/src/common/hooks/useElementAvailable.ts
  packages/components/src/common/hooks/useMeasurePunchouts.ts
  packages/components/src/index.tsx
  packages/components/src/pulsating_dot/index.tsx
  packages/components/src/pulsating_dot/pulsating_dot.scss
  packages/components/src/tour_tip/index.ts
  packages/components/src/tour_tip/tour_tip.scss
  packages/components/src/tour_tip/tour_tip.tsx
  packages/components/src/tour_tip/tour_tip_backdrop.tsx
Labels: 2: Dev Review, Setup Cloud Test Server, QA Review Done, release-note

#11077 MM-46824 : Allows for messages from Bot and Webhook to be forwarded
  components/dot_menu/dot_menu.tsx
  components/post_view/post/post.tsx
  components/rhs_comment/rhs_comment.test.tsx
  components/rhs_comment/rhs_comment.tsx
  components/rhs_root_post/rhs_root_post.jsx
  components/rhs_root_post/rhs_root_post.test.jsx
  utils/post_utils.ts
Labels: 4: Reviews Complete, release-note, Contributor

#11166 MM-47092, MM-47106, MM-47116 : Migrate tests of "abstract_incoming_hook", "autosize_textarea" & "more_direct_channels" to typescript
  components/__snapshots__/autosize_textarea.test.tsx.snap
  components/autosize_textarea.test.tsx
  components/integrations/__snapshots__/abstract_incoming_hook.test.tsx.snap
  components/integrations/abstract_incoming_hook.test.tsx
  components/more_direct_channels/list/index.test.ts
Labels: 4: Reviews Complete, release-note-none, Contributor

#11215 Revert "MM-47099 : Migrate "components/channel_notifications_modal/components/expand_view.jsx" to Typescript"
  components/channel_notifications_modal/components/expand_view.jsx
  components/channel_notifications_modal/components/expand_view.test.jsx
  components/channel_notifications_modal/components/notification_section.jsx
Labels: release-note-none

#11225 Automated cherry pick of #11215
  components/channel_notifications_modal/components/expand_view.jsx
  components/channel_notifications_modal/components/expand_view.test.jsx
  components/channel_notifications_modal/components/notification_section.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#11040 add reached limit texts to menu
  components/widgets/menu/menu_items/useWords.test.tsx
  components/widgets/menu/menu_items/useWords.tsx
  i18n/en.json
  utils/limits.tsx
Labels: 4: Reviews Complete, QA Review Done, release-note

#8889 [MM-24461] Show last active time of users when not online
  components/admin_console/admin_definition.jsx
  components/channel_header/__snapshots__/channel_header.test.tsx.snap
  components/channel_header/channel_header.test.tsx
  components/channel_header/channel_header.tsx
  components/channel_header/index.ts
  components/profile_popover/__snapshots__/profile_popover.test.tsx.snap
  components/profile_popover/index.ts
  components/profile_popover/profile_popover.scss
  components/profile_popover/profile_popover.test.tsx
  components/profile_popover/profile_popover.tsx
  components/user_settings/display/__snapshots__/user_settings_display.test.tsx.snap
  components/user_settings/display/index.ts
  components/user_settings/display/user_settings_display.test.tsx
  components/user_settings/display/user_settings_display.tsx
  i18n/en.json
  packages/mattermost-redux/src/actions/timezone.ts
  packages/mattermost-redux/src/reducers/entities/users.ts
  packages/mattermost-redux/src/selectors/entities/users.ts
  packages/mattermost-redux/src/store/initial_state.ts
  packages/types/src/config.ts
  packages/types/src/users.ts
  sass/layout/_headers.scss
  tests/constants/users.ts
Labels: release-note

#11110 [MM-45540] Fix channel header not displaying inline images (markdown)
  components/size_aware_image.jsx
  components/size_aware_image.test.jsx
  e2e/cypress/tests/integration/markdown/markdown_image_spec.js
  sass/layout/_markdown.scss
  utils/markdown/renderer.tsx
Labels: 4: Reviews Complete, release-note

#11157 MM-22768 : Migrate 'components/more_direct_channels.test.jsx' to TypeScript
  components/more_direct_channels/__snapshots__/more_direct_channels.test.jsx.snap
  components/more_direct_channels/__snapshots__/more_direct_channels.test.tsx.snap
  components/more_direct_channels/more_direct_channels.test.tsx
Labels: 4: Reviews Complete, release-note, Contributor

#11155 [MM-47041] fix escape key not closing channel switcher issue
  components/suggestion/suggestion_box/suggestion_box.jsx
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, QA Review Done, AutoMerge, release-note

#11228 Automated cherry pick of #11155
  components/suggestion/suggestion_box/suggestion_box.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#11114 MM-36600 : Animate emoji skin tone selector
  components/emoji_picker/components/emoji_picker_skin.tsx
  sass/components/_emoticons.scss
Labels: 4: Reviews Complete, release-note, Contributor

#11207 MM-47085 : Migrate "components/code_block/code_block.test.jsx" to Typescript
  components/code_block/__snapshots__/code_block.test.tsx.snap
  components/code_block/code_block.test.tsx
Labels: 4: Reviews Complete, release-note-none, Contributor

#11227 Automated cherry pick of #11155
  components/suggestion/suggestion_box/suggestion_box.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#11107 [MM-42030] CRT Thread pane tutorial tour migration to new tour tip component
  components/crt_tour/crt_threads_pane_tutorial_tip/crt_threads_pane_tutorial_tip.tsx
  e2e/cypress/tests/integration/collapsed_reply_threads/crt_tour_spec.js
  e2e/cypress/tests/integration/collapsed_reply_threads/following_spec.js
  e2e/cypress/tests/support/ui/sidebar_left.ts
  packages/components/src/tour_tip/tour_tip.tsx
Labels: 2: Dev Review, 3: QA Review, Lifecycle/1:stale, Setup Cloud Test Server, release-note, Contributor

#11174 MM-47119 : Migrate "components/sidebar_right_menu/index.js" to Typescript
  components/sidebar_right_menu/index.ts
Labels: release-note-none, QA Deferred, Contributor

#11097 fix: break only when role match is found
  components/channel_view/index.ts
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none, Contributor
