Repository mattermost/mattermost-webapp, pull requests merged in 2022-01, with the labels that each got.

#9599 Missing Zephyr keys updated for guest_invitation_ui_spec.js
  e2e/cypress/integration/bot_accounts/sidebar_display_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/guest_invitation_ui_spec.js
Labels: 4: Reviews Complete, Run E2E Testing, release-note-none

#9609 [MM-39279] - Hide the Invite Members button when the DM category is collapsed
  components/sidebar/sidebar_category/sidebar_category.tsx
Labels: 2: Dev Review, Setup Cloud Test Server, QA Review Done, release-note-none

#9594 MM-40746 - make licensing page purchase buttons responsive
  components/admin_console/license_settings/license_settings.scss
  components/admin_console/license_settings/starter_edition/starter_edition.scss
  components/admin_console/license_settings/starter_edition/starter_right_panel.tsx
  components/announcement_bar/contact_sales/contact_us.tsx
Labels: Setup Cloud Test Server, QA Review Done, 1: UX Review, release-note-none

#9615 MM-40751 Properly set Content-Type on API requests
  packages/mattermost-redux/src/client/client4.ts
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#9601 [MM-39488] - ENTER does not select the CTA on tutorial tips
  components/tutorial/tutorial_tip/tutorial_tip.tsx
  e2e/cypress/integration/onboarding/tutorial_guided_tour_spec.js
Labels: 2: Dev Review, Setup Cloud Test Server, QA Review Done, release-note-none

#9593 MM-40759 - unify the translation string in parts that make sense and are easy to translate
  components/admin_console/license_settings/trial_banner/trial_banner.tsx
  i18n/en.json
Labels: 4: Reviews Complete, QA Review Done, release-note-none

#9613 MM-40545 Prevent ctrl+a from opening account settings modal without shift
  components/sidebar/sidebar.tsx
  e2e/cypress/integration/keyboard_shortcuts/ctrl_cmd_shift_a_account_settings_spec.js
Labels: release-note-none, QA Deferred

#9607 MM-40790 - Do not show license expired banner for Cloud
  components/announcement_bar/configuration_bar/__snapshots__/configuration_bar.test.tsx.snap
  components/announcement_bar/configuration_bar/configuration_bar.test.tsx
  utils/license_utils.jsx
  utils/license_utils.test.jsx
Labels: Setup Cloud Test Server, release-note-none, QA Deferred

#9619 Automated cherry pick of #9607
  components/announcement_bar/configuration_bar/__snapshots__/configuration_bar.test.tsx.snap
  components/announcement_bar/configuration_bar/configuration_bar.test.tsx
  utils/license_utils.jsx
  utils/license_utils.test.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#9539 MM-40607 Remove broken autofocus from mobile search box
  components/global_header/center_controls/global_search_nav/global_search_nav.tsx
  components/search/search.tsx
  components/search/types.ts
  components/search_bar/__snapshots__/search_bar.test.jsx.snap
  components/search_bar/search_bar.test.jsx
  components/search_bar/search_bar.tsx
  components/sidebar_right/index.js
  components/sidebar_right/sidebar_right.jsx
Labels: 4: Reviews Complete, release-note-none

#9621 [MM-40231] Update Admin Log File Description
  components/admin_console/admin_definition.jsx
  i18n/en.json
Labels: 4: Reviews Complete, release-note-none, Contributor

#9361 Reducing bundle size (related to languages from @formatjs) from 35.68MB to 31.14
  components/intl_provider/intl_provider.tsx
  components/timestamp/relative_ranges.tsx
  components/timestamp/timestamp.stories.tsx
  components/timestamp/timestamp.tsx
  i18n/i18n.jsx
  package-lock.json
  package.json
  tests/helpers/intl-test-helper.tsx
  utils/datetime.ts
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none

#9596 MM-40766 unregisterComponent now removes plugin components from all associated locations
  reducers/plugins/index.ts
  types/store/plugins.ts
Labels: 4: Reviews Complete, QA Review Done, release-note-none

#9517 [MM-38501] - observe showPublicLink prop when rendering file preview modal
  components/file_preview_modal/file_preview_modal_main_actions/__snapshots__/file_preview_modal_main_actions.test.tsx.snap
  components/file_preview_modal/file_preview_modal_main_actions/file_preview_modal_main_actions.test.tsx
  components/file_preview_modal/file_preview_modal_main_actions/file_preview_modal_main_actions.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note, Contributor

#9605 Cypress/E2E:fixed image preview test case
  e2e/cypress/integration/files_and_attachments/image_link_preview_new_window_spec.js
  e2e/cypress/integration/files_and_attachments/image_link_preview_spec.js
  e2e/cypress/support/ui/file_preview.d.ts
  e2e/cypress/support/ui/file_preview.js
Labels: 4: Reviews Complete, release-note-none

#9595 [MM-38758] loading spinner in channel switcher if no local data matches
  components/suggestion/switch_channel_provider.jsx
  sass/components/_suggestion-list.scss
Labels: Setup Cloud Test Server, release-note, QA Deferred

#9604 [MM-38154] - Webapp: Change Getting Started/Tips & Next Steps to be it's own view rather than overlay on active channel
  components/channel_layout/center_channel/center_channel.test.tsx
  components/channel_layout/center_channel/center_channel.tsx
  components/channel_layout/center_channel/index.ts
  components/channel_view/__snapshots__/channel_view.test.tsx.snap
  components/channel_view/channel_view.test.tsx
  components/channel_view/channel_view.tsx
  components/channel_view/index.ts
  components/global_header/center_controls/user_guide_dropdown/index.ts
  components/global_header/center_controls/user_guide_dropdown/user_guide_dropdown.test.tsx
  components/global_header/center_controls/user_guide_dropdown/user_guide_dropdown.tsx
  components/main_menu/index.tsx
  components/main_menu/main_menu.test.tsx
  components/main_menu/main_menu.tsx
  components/next_steps_view/index.ts
  components/next_steps_view/next_steps_view.test.tsx
  components/next_steps_view/next_steps_view.tsx
  components/sidebar/__snapshots__/sidebar.test.tsx.snap
  components/sidebar/sidebar_next_steps/index.ts
  components/sidebar/sidebar_next_steps/sidebar_next_steps.tsx
  components/threading/global_threads/global_threads.tsx
  e2e/cypress/integration/enterprise/cloud/onboarding/cloud_legacy_invite_member_by_email_spec.js
  e2e/cypress/integration/onboarding/cloud_sysadmin_onboarding_spec.js
  e2e/cypress/integration/onboarding/invite_member_by_email_spec.js
  e2e/cypress/integration/onboarding/set_profile_and_team_spec.js
  plugins/test/__snapshots__/main_menu_action.test.jsx.snap
  plugins/test/main_menu_action.test.jsx
Labels: 2: Dev Review, Setup Cloud Test Server, QA Review Done, release-note-none

#9624 Automated cherry pick of #9592
  sass/components/_post-menu.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#9627 Cherrypick "MM-40766 unregisterComponent now removes plugin components from all associated locations #9596"
  reducers/plugins/index.js
  types/store/plugins.ts
Labels: AutoMerge, release-note-none

#9625 Automated cherry pick of #9594
  components/admin_console/license_settings/license_settings.scss
  components/admin_console/license_settings/starter_edition/starter_edition.scss
  components/admin_console/license_settings/starter_edition/starter_right_panel.tsx
  components/announcement_bar/contact_sales/contact_us.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#9626 Automated cherry pick of #9593
  components/admin_console/license_settings/trial_banner/trial_banner.tsx
  i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#9628 Automated cherry pick of #9543
  .circleci/config.yml
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#9630 Cherry-pick translations 20220106 6.3
  i18n/bg.json
  i18n/de.json
  i18n/en_AU.json
  i18n/es.json
  i18n/hu.json
  i18n/it.json
  i18n/ja.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#9629 Cypress/E2E: Fix tests on keyboard shortcuts
  e2e/cypress/integration/keyboard_shortcuts/ctrl_cmd_k_channel_switch_spec.js
  e2e/cypress/integration/keyboard_shortcuts/ctrl_cmd_up_down_no_action_spec.js
  e2e/cypress/integration/keyboard_shortcuts/keyboard_shortcuts_1_spec.js
  e2e/cypress/integration/keyboard_shortcuts/keyboard_shortcuts_3_spec.js
  e2e/cypress/support/ui/global_header.d.ts
  e2e/cypress/support/ui/global_header.js
Labels: 4: Reviews Complete, release-note-none

#9540 remove black outline around copy test link on Microsoft browsers
  components/invitation_modal/invite_view.scss
  components/invitation_modal/invite_view.tsx
  sass/utils/_mixins.scss
Labels: 4: Reviews Complete, Setup Cloud Test Server, QA Review Done, release-note

#9513 MM-40378 Plugin is incorrectly displayed as enabled after re-install
  packages/mattermost-redux/src/actions/admin.ts
Labels: 4: Reviews Complete, release-note, Contributor

#9632 Let fetch api set the correct content-type to FormData requests
  packages/mattermost-redux/src/client/client4.ts
Labels: 4: Reviews Complete, CherryPick/Approved, QA Review Done, release-note-none

#9620 [MM-40484]Archived channels are showing the globe channel icon in channel autocomplete
  components/suggestion/channel_mention_provider.jsx
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, AutoMerge, release-note, QA Deferred

#9633 Automated cherry pick of #9632
  packages/mattermost-redux/src/client/client4.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#9634 Automated cherry pick of #9620
  components/suggestion/channel_mention_provider.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#9622 fix:MM-405552 : JavaScript error when browsing channels and clicking Next
  components/searchable_channel_list.jsx
Labels: 2: Dev Review, CherryPick/Approved, Setup Cloud Test Server, QA Review Done, release-note-none

#9635 Automated cherry pick of #9622
  components/searchable_channel_list.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#9603 [MM-39931] - Tutorial points: arrow doesn't get proper theme color
  sass/components/_tutorial.scss
Labels: 2: Dev Review, Setup Cloud Test Server, QA Review Done, release-note-none

#9617 Add workaround for mmjstool integrity check failing
  Makefile
  package-lock.json
  skip_integrity_check.js
Labels: 4: Reviews Complete, release-note-none

#9637 Dependencies: luxon 2.3
  package-lock.json
  package.json
Labels: 4: Reviews Complete, release-note-none

#9611 MM-40219 - new dialog for upload license
  components/admin_console/license_settings/__snapshots__/license_settings.test.jsx.snap
  components/admin_console/license_settings/enterprise_edition/enterprise_edition.scss
  components/admin_console/license_settings/enterprise_edition/enterprise_edition_left_panel.tsx
  components/admin_console/license_settings/index.ts
  components/admin_console/license_settings/license_settings.scss
  components/admin_console/license_settings/license_settings.tsx
  components/admin_console/license_settings/modals/__snapshots__/upload_license_modal.test.tsx.snap
  components/admin_console/license_settings/modals/confirm_license_removal_modal.scss
  components/admin_console/license_settings/modals/confirm_license_removal_modal.tsx
  components/admin_console/license_settings/modals/upload_license_modal.scss
  components/admin_console/license_settings/modals/upload_license_modal.test.tsx
  components/admin_console/license_settings/modals/upload_license_modal.tsx
  components/admin_console/license_settings/starter_edition/starter_edition.scss
  components/admin_console/license_settings/starter_edition/starter_left_panel.tsx
  components/admin_console/license_settings/team_edition/team_edition_right_panel.tsx
  components/admin_console/license_settings/trial_banner/trial_banner.tsx
  components/admin_console/license_settings/trial_license_card/trial_license_card.tsx
  components/common/svg_images_components/file_svg.tsx
  components/common/svg_images_components/woman_arm_on_table_svg.tsx
  i18n/en.json
  utils/constants.jsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, QA Review Done, release-note

#9638 [MM-40591]Admin console team override scheme page going into an infinite loading state
  components/admin_console/permission_schemes_settings/permission_team_scheme_settings/permission_team_scheme_settings.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#9640 Automated cherry pick of #9638
  components/admin_console/permission_schemes_settings/permission_team_scheme_settings/permission_team_scheme_settings.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#9509 MM-40114 Migrate modals, headers, and onboarding to use getIsMobileView
  components/channel_header_mobile/__snapshots__/channel_header_mobile.test.tsx.snap
  components/channel_header_mobile/channel_header_mobile.test.tsx
  components/channel_header_mobile/channel_header_mobile.tsx
  components/channel_header_mobile/index.ts
  components/channel_notifications_modal/components/__snapshots__/collapse_view.test.jsx.snap
  components/global_header/center_controls/global_search_nav/global_search_nav.tsx
  components/global_header/center_controls/user_guide_dropdown/index.ts
  components/global_header/center_controls/user_guide_dropdown/user_guide_dropdown.test.tsx
  components/global_header/center_controls/user_guide_dropdown/user_guide_dropdown.tsx
  components/more_direct_channels/list_item/index.ts
  components/more_direct_channels/list_item/list_item.test.jsx
  components/more_direct_channels/list_item/list_item.tsx
  components/next_steps_view/download_section.tsx
  components/next_steps_view/index.ts
  components/next_steps_view/next_steps_view.test.tsx
  components/next_steps_view/next_steps_view.tsx
  components/next_steps_view/steps.ts
  components/next_steps_view/steps/complete_profile_step/complete_profile_step.test.tsx
  components/next_steps_view/steps/create_first_channel_step/__snapshots__/create_first_channel_step.test.tsx.snap
  components/next_steps_view/steps/create_first_channel_step/create_first_channel_step.test.tsx
  components/next_steps_view/steps/download_apps_step/download_apps_step.tsx
  components/next_steps_view/steps/enable_notifications_step/enable_notifications_step.test.tsx
  components/next_steps_view/steps/invite_members_step/invite_members_step.test.tsx
  components/next_steps_view/steps/setup_preferences_step/__snapshots__/setup_preferences_step.test.tsx.snap
  components/next_steps_view/steps/setup_preferences_step/setup_preferences_step.test.tsx
  components/next_steps_view/steps/team_profile_step/team_profile_step.test.tsx
  components/quick_switch_modal/index.tsx
  components/quick_switch_modal/quick_switch_modal.test.tsx
  components/quick_switch_modal/quick_switch_modal.tsx
  components/setting_item_min/index.ts
  components/setting_item_min/setting_item_min.test.tsx
  components/setting_item_min/setting_item_min.tsx
  components/team_general_tab/__snapshots__/open_invite.test.tsx.snap
  components/team_general_tab/__snapshots__/team_general_tab.test.jsx.snap
  components/user_settings/advanced/join_leave_section/__snapshots__/join_leave_section.test.tsx.snap
  components/user_settings/display/__snapshots__/user_settings_display.test.tsx.snap
  components/user_settings/display/user_settings_display.test.tsx
  components/user_settings/display/user_settings_theme/__snapshots__/user_settings_theme.test.jsx.snap
  components/user_settings/general/user_settings_general.test.tsx
  components/user_settings/notifications/__snapshots__/desktop_notification_settings.test.jsx.snap
  components/user_settings/notifications/email_notification_setting/__snapshots__/email_notification_setting.test.tsx.snap
  components/user_settings/notifications/user_settings_notifications.test.js
  components/user_settings/security/__snapshots__/user_settings_security.test.tsx.snap
  components/user_settings/security/mfa_section/__snapshots__/mfa_section.test.tsx.snap
  utils/test_helper.ts
Labels: 4: Reviews Complete, release-note-none

#9643 Cp translations 2022 01 12 release 6.3
  i18n/bg.json
  i18n/de.json
  i18n/en_AU.json
  i18n/es.json
  i18n/fr.json
  i18n/hu.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#9644 Cp translations 2022 01 12 cloud
  i18n/bg.json
  i18n/de.json
  i18n/en_AU.json
  i18n/es.json
  i18n/fr.json
  i18n/hu.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, release-note-none

#9589 [MM-40681] : The "Leave Channel" button doesn't work from the 3-dot menu when clicking on it second time
  components/sidebar/sidebar_channel/sidebar_base_channel/sidebar_base_channel.test.tsx
  components/sidebar/sidebar_channel/sidebar_base_channel/sidebar_base_channel.tsx
Labels: 4: Reviews Complete, release-note-none, Contributor

#9623 fix/MM-40381 : unified is not defined bug when recent used emoji is deleted
  components/emoji_picker/emoji_picker.jsx
Labels: 4: Reviews Complete, release-note-none

#9647 [MM-40750] Remove 'Status' Menu Header on Status Dropdown
  components/status_dropdown/__snapshots__/status_dropdown.test.tsx.snap
  components/status_dropdown/status_dropdown.tsx
  i18n/en.json
Labels: 4: Reviews Complete, release-note-none

#9660 working dashboard page
  components/admin_console/admin_definition.jsx
  components/admin_console/workspace-optimization/dashboard.tsx
  i18n/en.json
Labels: 2: Dev Review, release-note-none

#9656 MM-40824 - Backport support of Professional sku for channel moderation
  components/admin_console/admin_definition.jsx
  components/admin_console/team_channel_settings/channel/details/__snapshots__/channel_details.test.tsx.snap
  components/admin_console/team_channel_settings/channel/details/__snapshots__/channel_modes.test.tsx.snap
  components/admin_console/team_channel_settings/channel/details/channel_details.test.tsx
  components/admin_console/team_channel_settings/channel/details/channel_details.tsx
  components/admin_console/team_channel_settings/channel/details/channel_modes.tsx
  components/admin_console/team_channel_settings/channel/details/index.ts
  packages/mattermost-redux/src/types/general.ts
Labels: 4: Reviews Complete, CherryPick/Approved, QA Review Done, AutoMerge, release-note

#9661 Automated cherry pick of #9543
  .circleci/config.yml
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#9545 MM-36932: reconnect websocket on wakeup
  components/needs_team/needs_team.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none

#9614 [MM-32371] Enable desktop app to tell webapp when Back/Forward should be enabled
  components/global_header/left_controls/history_buttons/history_buttons.tsx
Labels: 4: Reviews Complete, release-note-none

#9154 MM-36109: Hide markdown preview link when user cannot post.
  components/create_comment/__snapshots__/create_comment.test.jsx.snap
  components/create_comment/create_comment.tsx
  components/create_comment/index.ts
  components/create_post/__snapshots__/create_post.test.jsx.snap
  components/create_post/create_post.test.jsx
  components/create_post/create_post.tsx
  components/create_post/index.ts
  components/edit_channel_header_modal/__snapshots__/edit_channel_header_modal.test.tsx.snap
  components/edit_channel_header_modal/edit_channel_header_modal.test.tsx
  components/edit_channel_header_modal/edit_channel_header_modal.tsx
  components/edit_channel_header_modal/index.ts
  components/edit_post_modal/__snapshots__/edit_post_modal.test.tsx.snap
  components/edit_post_modal/edit_post_modal.test.tsx
  components/edit_post_modal/edit_post_modal.tsx
  components/edit_post_modal/index.js
  components/textbox/textbox_links/index.ts
Labels: 4: Reviews Complete, release-note

#9645 MM-40894 - not able to download license in desktop app
  components/admin_console/billing/billing_history.tsx
  components/admin_console/billing/billing_subscriptions/billing_subscriptions.tsx
  components/admin_console/billing/billing_summary/billing_summary.tsx
  components/admin_console/billing/payment_info_edit.tsx
  components/admin_console/billing/plan_details/plan_details.tsx
  components/purchase_modal/purchase_modal.tsx
Labels: Setup Cloud + CWS Test Server, release-note-none, QA Deferred

#9659 Translations update from Mattermost Weblate
  i18n/bg.json
  i18n/de.json
  i18n/en_AU.json
  i18n/es.json
  i18n/fr.json
  i18n/hu.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: release-note-none

#9658 Fixed a bug causing team sidebar to always show up in products when running in subpath
  utils/products.ts
Labels: 3: QA Review, CherryPick/Approved, release-note-none

#9671 Translations update from Mattermost Weblate
  i18n/hu.json
  i18n/ru.json
  i18n/sv.json
Labels: release-note-none

#9670 Translation cherry pick from #9659 and #9671
  i18n/bg.json
  i18n/de.json
  i18n/en_AU.json
  i18n/es.json
  i18n/fr.json
  i18n/hu.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: release-note-none

#9651 [MM-38054] Remove the channel file related buttons if file attachments are disabled on the server
  components/channel_header/channel_header.js
  components/channel_header/channel_header.test.jsx
  components/channel_header/index.js
  components/search_hint/search_hint.test.tsx
  components/search_hint/search_hint.tsx
  components/search_results/__snapshots__/messages_or_files_selector.test.tsx.snap
  components/search_results/messages_or_files_selector.test.tsx
  components/search_results/messages_or_files_selector.tsx
  components/search_results/search_results.tsx
  utils/file_utils.jsx
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, QA Review Done, AutoMerge, release-note

#9673 Automated cherry pick of #9658
  utils/products.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#9674 Automated cherry pick of #9651
  components/channel_header/channel_header.js
  components/channel_header/channel_header.test.jsx
  components/channel_header/index.js
  components/search_hint/search_hint.test.tsx
  components/search_hint/search_hint.tsx
  components/search_results/__snapshots__/messages_or_files_selector.test.tsx.snap
  components/search_results/messages_or_files_selector.test.tsx
  components/search_results/messages_or_files_selector.tsx
  components/search_results/search_results.tsx
  utils/file_utils.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#9669 fixing small typo: aN extension
  i18n/en.json
Labels: 4: Reviews Complete, release-note-none, Contributor

#9678 Cypress/E2E: Update tests
  e2e/cypress/integration/keyboard_shortcuts/alt_option_plus_up_down_spec.js
  e2e/cypress/integration/keyboard_shortcuts/esc_close_modal_spec.js
  e2e/cypress/integration/team_settings/closed_team_invite_by_email_spec.js
  e2e/cypress/support/api/preference.d.ts
  e2e/cypress/support/api/preference.js
  e2e/cypress/support/index.js
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#9602 Add boards to global data retention policy
  components/admin_console/data_retention_settings/__snapshots__/data_retention_settings.test.tsx.snap
  components/admin_console/data_retention_settings/data_retention_settings.test.tsx
  components/admin_console/data_retention_settings/data_retention_settings.tsx
  components/admin_console/data_retention_settings/global_policy_form/global_policy_form.tsx
  i18n/en.json
  packages/mattermost-redux/src/reducers/entities/admin.ts
  packages/mattermost-redux/src/types/config.ts
Labels: 4: Reviews Complete, release-note

#9653 chore/MM-40559 : Add memoization to getOneClickReactionEmojis
  actions/emoji_actions.js
  actions/emoji_actions.test.js
  actions/local_storage.jsx
  selectors/emojis.ts
  stores/local_storage_store.jsx
  stores/local_storage_store.test.jsx
Labels: 4: Reviews Complete, release-note-none

#9677 [MM-40590] Fix inviting a guest guest to a channel where he's a member.
  actions/invite_actions.test.ts
  actions/invite_actions.ts
  components/invitation_modal/add_to_channels.test.tsx
  components/invitation_modal/add_to_channels.tsx
  e2e/cypress/integration/enterprise/guest_accounts/guest_invitation_ui_more_spec.js
Labels: 4: Reviews Complete, QA Review Done, release-note-none

#9523 feat:40442 Added shortcut to expand the sidebar
  components/keyboard_shortcuts/keyboard_shortcuts_modal/__snapshots__/keyboard_shortcuts_modal.test.tsx.snap
  components/keyboard_shortcuts/keyboard_shortcuts_modal/keyboard_shortcuts_modal.tsx
  components/keyboard_shortcuts/keyboard_shortcuts_sequence/keyboard_shortcuts.ts
  components/rhs_card_header/rhs_card_header.tsx
  components/rhs_header_post/rhs_header_post.tsx
  components/search_results_header/search_results_header.tsx
  components/sidebar_right/sidebar_right.jsx
  e2e/cypress/integration/keyboard_shortcuts/keyboard_shortcuts_1_spec.js
  i18n/en.json
Labels: 4: Reviews Complete, release-note, Contributor

#9639 Fixed a bug that caused a gap to appear in products using team sidebar when user had only 1 team
  components/root/root.jsx
  sass/base/_structure.scss
  sass/layout/_sidebar-left.scss
  sass/layout/_team-sidebar.scss
  sass/routes/_backstage.scss
Labels: 4: Reviews Complete, release-note

#9650 MM-40636: Clearing deleted root post leaves rhs blank
  components/post_view/post_info/index.ts
  packages/mattermost-redux/src/actions/posts.ts
Labels: 4: Reviews Complete, release-note-none

#9666 Growth spike/add basic accordion
  components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.jsx.snap
  components/admin_console/workspace-optimization/dashboard.scss
  components/admin_console/workspace-optimization/dashboard.tsx
  components/common/accordion/__snapshots__/accordion.test.tsx.snap
  components/common/accordion/accordion.scss
  components/common/accordion/accordion.test.tsx
  components/common/accordion/accordion.tsx
  components/common/accordion/accordion_item.tsx
  components/common/accordion/message_item.tsx
  components/common/svg_images_components/configuration_svg.tsx
  components/common/svg_images_components/data_privacy_svg.tsx
  components/common/svg_images_components/easy_management_svg.tsx
  components/common/svg_images_components/performance_svg.tsx
  components/common/svg_images_components/security_svg.tsx
  components/common/svg_images_components/updates_and_errors_svg.tsx
  components/common/svg_images_components/workspace_access_svg.tsx
  i18n/en.json
  sass/base/_css_variables.scss
Labels: 2: Dev Review, release-note-none

#9681 Cypress/E2E:Fixed cypress test cases
  e2e/cypress/fixtures/markdown/markdown_inline_images_1.md
  e2e/cypress/fixtures/markdown/markdown_inline_images_6.md
  e2e/cypress/integration/interactive_menu/slack_parsing_message_button_spec.js
  e2e/cypress/integration/markdown/markdown_image_spec.js
  e2e/cypress/integration/messaging/inline_images_open_preview_window_spec.js
Labels: 4: Reviews Complete, release-note-none

#9687 Cypress/E2E:Fixed cypress test cases
  e2e/cypress/integration/integrations/slash_commands_spec.js
  e2e/cypress/integration/messaging/inline_markdown_image_link_open_link_spec.js
  e2e/cypress/integration/search/post_search_display_spec.js
Labels: release-note-none

#9664 tests/MM-40609 : E2Es for recent custom emoji fixes
  e2e/cypress/integration/emoji/custom_emoji_2_spec.js
  e2e/cypress/integration/emoji/custom_emoji_3_spec.js
  e2e/cypress/integration/emoji/recently_used_emoji_spec.js
  e2e/cypress/integration/keyboard_shortcuts/ctrl_cmd_shift_slash/helpers.js
Labels: release-note-none

#9689 MM-41159 - Remove free tier cloud final date to subscribe
  components/admin_console/billing/billing_summary/billing_summary.tsx
  components/admin_console/billing/plan_details/index.tsx
  components/admin_console/billing/plan_details/plan_details.tsx
  i18n/bg.json
  i18n/de.json
  i18n/en.json
  i18n/en_AU.json
  i18n/es.json
  i18n/fr.json
  i18n/hu.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
  i18n/zh-CN.json
Labels: 4: Reviews Complete, QA Review Done, Setup Cloud + CWS Test Server, release-note-none

#9665 chore/MM-40297 : Reduce size of emoji.json in bundle
  build/emoji/Gemfile
  build/emoji/Gemfile.lock
  build/emoji/apple_emoji_extractor.rb
  build/emoji/apple_emoji_extractor_test.rb
  build/emoji/emoji-sequences.txt
  build/emoji/emoji_gen.mjs
  build/emoji/make-emojis
  build/emoji/unicode_emoji_helper.rb
  build/emoji/unicode_emoji_helper_test.rb
  package-lock.json
  package.json
  utils/emoji.json
Labels: 4: Reviews Complete, release-note-none

#9688 [MM-37245] Format the number of users in enterprise license details
  components/admin_console/license_settings/enterprise_edition/enterprise_edition_left_panel.test.tsx
  components/admin_console/license_settings/enterprise_edition/enterprise_edition_left_panel.tsx
  components/admin_console/license_settings/modals/upload_license_modal.test.tsx
  components/admin_console/license_settings/modals/upload_license_modal.tsx
  i18n/de.json
  i18n/en.json
  i18n/en_AU.json
  i18n/pl.json
Labels: Setup Cloud Test Server, QA Review Done, release-note-none

#9289 [MM-29622] Collapsed reply threads tour
  components/collapsed_reply_threads_modal/collapsed_reply_threads_modal.tsx
  components/create_post/create_post_tip.tsx
  components/crt_tour/collapsed_reply_threads_modal/collapsed_reply_threads_modal.scss
  components/crt_tour/collapsed_reply_threads_modal/collapsed_reply_threads_modal.tsx
  components/crt_tour/collapsed_reply_threads_modal/index.ts
  components/crt_tour/crt_list_tutorial_tip/crt_list_tutorial_tip.tsx
  components/crt_tour/crt_threads_pane_tutorial_tip/crt_threads_pane_tutorial_tip.tsx
  components/crt_tour/crt_unread_tutorial_tip/crt_unread_tutorial_tip.tsx
  components/crt_tour/crt_welcome_tutorial_tip/crt_welcome_tutorial_tip.tsx
  components/global_header/left_controls/product_menu/product_menu_tip/__snapshots__/product_menu_tip.test.tsx.snap
  components/global_header/left_controls/product_menu/product_menu_tip/product_menu_tip.tsx
  components/global_header/right_controls/settings_tip.tsx
  components/rhs_header_post/index.ts
  components/rhs_header_post/rhs_header_post.spec.tsx
  components/rhs_header_post/rhs_header_post.tsx
  components/shortcut_key/shortcut_key.scss
  components/shortcut_key/shortcut_key.tsx
  components/sidebar/__snapshots__/channel_tutorial_tip.test.tsx.snap
  components/sidebar/add_channel_tutorial_tip.tsx
  components/sidebar/channel_tutorial_tip.test.tsx
  components/sidebar/channel_tutorial_tip.tsx
  components/sidebar/sidebar_channel/sidebar_channel_link/index.ts
  components/sidebar/sidebar_channel/sidebar_channel_link/sidebar_channel_link.test.tsx
  components/sidebar/sidebar_channel/sidebar_channel_link/sidebar_channel_link.tsx
  components/threading/global_threads/global_threads.scss
  components/threading/global_threads/thread_item/__snapshots__/thread_item.test.tsx.snap
  components/threading/global_threads/thread_item/thread_item.test.tsx
  components/threading/global_threads/thread_item/thread_item.tsx
  components/threading/global_threads/thread_list/__snapshots__/thread_list.test.tsx.snap
  components/threading/global_threads/thread_list/thread_list.scss
  components/threading/global_threads/thread_list/thread_list.test.tsx
  components/threading/global_threads/thread_list/thread_list.tsx
  components/threading/global_threads/thread_list/virtualized_thread_list_row.tsx
  components/threading/global_threads/thread_pane/__snapshots__/thread_pane.test.tsx.snap
  components/threading/global_threads/thread_pane/thread_pane.tsx
  components/threading/global_threads_link/global_threads_link.tsx
  components/tutorial/menu_tutorial_tip.tsx
  components/tutorial/tutorial_tip/__snapshots__/tutorial_tip.test.tsx.snap
  components/tutorial/tutorial_tip/index.ts
  components/tutorial/tutorial_tip/tutorial_tip.test.tsx
  components/tutorial/tutorial_tip/tutorial_tip.tsx
  components/user_settings/modal/index.ts
  components/user_settings/modal/user_settings_modal.tsx
  e2e/cypress/integration/channel/leave_channel_spec.js
  e2e/cypress/integration/collapsed_reply_threads/crt_settings_spec.js
  e2e/cypress/integration/onboarding/finish_tutorial_spec.js
  e2e/cypress/support/ui/account_settings_modal.js
  e2e/cypress/support/ui/sidebar_left.js
  i18n/en.json
  sass/components/_tutorial.scss
  sass/responsive/_desktop.scss
  sass/responsive/_mobile.scss
  selectors/views/modals.ts
  utils/constants.jsx
Labels: QA Review Done, release-note

#9616 Edit Post patches only message, leaves props unchanged
  components/edit_post_modal/edit_post_modal.test.tsx
  components/edit_post_modal/edit_post_modal.tsx
Labels: 4: Reviews Complete, release-note-none

#9652 Mm 39663
  components/admin_console/billing/billing_history.tsx
  components/admin_console/billing/invoice_user_count.test.tsx
  components/admin_console/billing/invoice_user_count.tsx
  i18n/en.json
  packages/mattermost-redux/src/types/cloud.ts
  utils/utils.d.ts
  utils/utils.jsx
  utils/utils.test.jsx
Labels: 2: Dev Review, release-note, QA Deferred

#9648 [MM-39398] set missingPages to true when previousPage button is clicked
  components/emoji/emoji_list/emoji_list.tsx
Labels: 4: Reviews Complete, release-note-none, Contributor

#9693 Growth spike/add information chips
  components/admin_console/workspace-optimization/dashboard.scss
  components/admin_console/workspace-optimization/dashboard.tsx
  components/common/accordion/accordion.tsx
  components/common/accordion/accordion_item.tsx
  components/common/chip/chip.tsx
  components/create_post/prewritten_chips.tsx
  sass/admin_console_base/_sys_css_variables.scss
Labels: release-note-none

#9667 [MM-40739] Make-width-fit-content
  sass/components/_popover.scss
Labels: 4: Reviews Complete, release-note, Contributor

#9642 MM-39750: decrements thread counts on root post delete
  actions/websocket_actions.jsx
  packages/mattermost-redux/src/action_types/threads.ts
  packages/mattermost-redux/src/actions/posts.ts
  packages/mattermost-redux/src/actions/threads.ts
  packages/mattermost-redux/src/reducers/entities/threads/counts.ts
Labels: 4: Reviews Complete, release-note-none

#9541 Fixing FullScreen modal styles usage from plugins
  plugins/index.js
Labels: 4: Reviews Complete, release-note-none, QA Deferred

#9703 Translations update from Mattermost Weblate
  i18n/bg.json
  i18n/de.json
  i18n/en_AU.json
  i18n/es.json
  i18n/fr.json
  i18n/hu.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
  i18n/zh-CN.json
Labels: release-note-none

#8888 [MM-26721] show channels across teams in channel switcher modal
  actions/views/channel.js
  components/needs_team/index.ts
  components/needs_team/needs_team.test.tsx
  components/needs_team/needs_team.tsx
  components/suggestion/switch_channel_provider.jsx
  components/suggestion/switch_channel_provider.test.jsx
  e2e/cypress/integration/channel_sidebar/history_channel_switcher_spec.js
  e2e/cypress/integration/keyboard_shortcuts/ctrl_cmd_k_unreads_spec.js
  e2e/cypress/integration/messaging/private_channel_open_spec.js
  packages/mattermost-redux/src/actions/channels.test.js
  packages/mattermost-redux/src/actions/channels.ts
  packages/mattermost-redux/src/client/client4.ts
  packages/mattermost-redux/src/reducers/entities/channels.ts
  packages/mattermost-redux/src/selectors/entities/channels.ts
  packages/mattermost-redux/src/types/channels.ts
  sass/components/_channel-switcher.scss
  sass/components/_suggestion-list.scss
Labels: 3: QA Review, Setup Cloud Test Server, QA Review Done, release-note

#9654 MM-31051 - unify cc expired sentence
  components/admin_console/billing/billing_subscriptions/billing_subscriptions.tsx
  i18n/en.json
Labels: 4: Reviews Complete, QA Review Done, Setup Cloud + CWS Test Server, release-note-none

#9676 MM-40527 Make reducers responsible for cleaning up on logout
  packages/mattermost-redux/src/constants/general.ts
  packages/mattermost-redux/src/reducers/entities/search.test.js
  packages/mattermost-redux/src/reducers/entities/search.ts
  packages/mattermost-redux/src/store/helpers.ts
  reducers/plugins/index.ts
  reducers/views/admin.ts
  reducers/views/announcement_bar.ts
  reducers/views/channel.ts
  reducers/views/channel_sidebar.ts
  reducers/views/emoji.ts
  reducers/views/lhs.ts
  reducers/views/marketplace.ts
  reducers/views/modals.ts
  reducers/views/next_steps.ts
  reducers/views/notice.ts
  reducers/views/posts.ts
  reducers/views/rhs.ts
  reducers/views/rhs_suppressed.ts
  reducers/views/search.ts
  reducers/views/settings.ts
  reducers/views/status_dropdown.ts
  reducers/views/system.ts
  reducers/views/textbox.ts
  reducers/views/threads.ts
  store/index.js
  store/index.test.js
Labels: 4: Reviews Complete, release-note-none

#9704 docs : Removed comment note related to deleting emojis from emoji_gen file
  build/emoji/emoji_gen.mjs
Labels: 4: Reviews Complete, release-note-none, QA Deferred, Editor review

#9491 Splitting the component in smaller functional components and typescript
  components/admin_console/__snapshots__/bleve_settings.test.jsx.snap
  components/admin_console/__snapshots__/elasticsearch_settings.test.jsx.snap
  components/admin_console/__snapshots__/message_export_settings.test.jsx.snap
  components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
  components/admin_console/data_retention_settings/__snapshots__/data_retention_settings.test.tsx.snap
  components/admin_console/data_retention_settings/data_retention_settings.tsx
  components/admin_console/jobs/index.jsx
  components/admin_console/jobs/index.tsx
  components/admin_console/jobs/job_cancel_button.scss
  components/admin_console/jobs/job_cancel_button.tsx
  components/admin_console/jobs/job_download_link.tsx
  components/admin_console/jobs/job_finish_at.tsx
  components/admin_console/jobs/job_run_length.tsx
  components/admin_console/jobs/job_status.tsx
  components/admin_console/jobs/table.jsx
  components/admin_console/jobs/table.scss
  components/admin_console/jobs/table.test.tsx
  components/admin_console/jobs/table.tsx
  packages/mattermost-redux/src/types/jobs.ts
  sass/routes/_admin-console.scss
Labels: 4: Reviews Complete, release-note-none

#9710 Automated cherry pick of #9541
  plugins/index.js
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#9700 [MM-41281] Change crt tour trigger condition and save onBoarding auto tour status in preferences
  components/threading/global_threads_link/global_threads_link.tsx
  components/tutorial/tutorial_tip/index.ts
  components/tutorial/tutorial_tip/tutorial_tip.test.tsx
  components/tutorial/tutorial_tip/tutorial_tip.tsx
  utils/constants.jsx
Labels: 4: Reviews Complete, release-note-none

#9646 MM-40317: fixes showing new replies banner
  components/threading/virtualized_thread_viewer/virtualized_thread_viewer.tsx
Labels: 4: Reviews Complete, release-note-none

#9720 Automated cherry pick of #9700
  components/threading/global_threads_link/global_threads_link.tsx
  components/tutorial/tutorial_tip/index.ts
  components/tutorial/tutorial_tip/tutorial_tip.test.tsx
  components/tutorial/tutorial_tip/tutorial_tip.tsx
  utils/constants.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#9717 Remove incorrect string text
  i18n/en.json
Labels: 4: Reviews Complete, release-note

#9716 Clarified in-product string
  components/invitation_modal/no_permissions_view.tsx
  i18n/en.json
Labels: 4: Reviews Complete, release-note

#9714 Add overall score header
  components/admin_console/workspace-optimization/__snapshots__/chip_list.test.tsx.snap
  components/admin_console/workspace-optimization/chip_list.test.tsx
  components/admin_console/workspace-optimization/chips_list.tsx
  components/admin_console/workspace-optimization/dashboard.scss
  components/admin_console/workspace-optimization/dashboard.tsx
  components/admin_console/workspace-optimization/overall-score.tsx
  components/common/chip/chip.tsx
  components/common/circular_chart/__snapshots__/circular_chart.test.tsx.snap
  components/common/circular_chart/circular_chart.scss
  components/common/circular_chart/circular_chart.test.tsx
  components/common/circular_chart/circular_chart.tsx
  i18n/en.json
Labels: 2: Dev Review, Setup Cloud Test Server, release-note-none

#9668 [MM-41114] Don't elide usernames in compact view
  components/post_view/post/post.jsx
Labels: 4: Reviews Complete, release-note, Contributor

#9649 MM-40056: fixes scrolling to selected thread
  components/threading/global_threads/thread_list/virtualized_thread_list.tsx
Labels: 4: Reviews Complete, release-note-none

#9706 Cypress/E2E: fixed tests (on custom emojis & integrations) failing due to not finding 'back to mattermost' button
  e2e/cypress/integration/emoji/custom_emoji_1_spec.js
  e2e/cypress/integration/emoji/custom_emoji_2_spec.js
  e2e/cypress/integration/emoji/custom_emoji_3_spec.js
  e2e/cypress/integration/emoji/recently_used_emoji_spec.js
  e2e/cypress/integration/integrations/integrations_spec.js
Labels: Changelog/Not Needed, Docs/Not Needed, release-note-none

#9715 e2e: fix 'handle new post' spec read/unread assertions
  e2e/cypress/integration/websocket/handle_new_post_spec.js
Labels: Docs/Not Needed, release-note-none

#9683 Growth channel intro
  components/common/svg_images_components/empty_state_themeable_svg.tsx
  components/post_view/channel_intro_message/__snapshots__/add_members_button.test.tsx.snap
  components/post_view/channel_intro_message/__snapshots__/channel_intro_message.test.tsx.snap
  components/post_view/channel_intro_message/add_members_button.scss
  components/post_view/channel_intro_message/add_members_button.test.tsx
  components/post_view/channel_intro_message/add_members_button.tsx
  components/post_view/channel_intro_message/channel_intro_message.test.tsx
  components/post_view/channel_intro_message/channel_intro_message.tsx
  components/post_view/channel_intro_message/index.ts
  i18n/en.json
  plugins/registry.js
  selectors/plugins.ts
Labels: 2: Dev Review, Setup Cloud Test Server, 1: UX Review, release-note-none

#9702 [MM-41188] Remove "Add Channel Button" feature flag
  components/sidebar/add_channel_dropdown.tsx
  components/sidebar/add_channel_tutorial_tip.tsx
  components/sidebar/channel_navigator/channel_navigator.test.tsx
  components/sidebar/channel_navigator/channel_navigator.tsx
  components/sidebar/channel_navigator/index.ts
  components/sidebar/sidebar_header/sidebar_header.test.tsx
  components/sidebar/sidebar_header/sidebar_header.tsx
  packages/mattermost-redux/src/constants/config.ts
  packages/mattermost-redux/src/selectors/entities/preferences.ts
  packages/mattermost-redux/src/types/config.ts
  sass/layout/_sidebar-left.scss
Labels: QA Review Done, release-note-none

#9726 Remove incorrect string text
  components/admin_console/admin_definition.jsx
Labels: 4: Reviews Complete, release-note
