Repository mattermost/mattermost-webapp, pull requests merged in 2022-03, with the labels that each got.

#9597 feat/MM-40296 : Virtualize and re-write of emoji picker
  build/emoji/emoji_gen.mjs
  components/emoji_picker/__snapshots__/emoji_picker.test.tsx.snap
  components/emoji_picker/components/emoji_picker_categories.tsx
  components/emoji_picker/components/emoji_picker_category.tsx
  components/emoji_picker/components/emoji_picker_category_or_emoji_row.tsx
  components/emoji_picker/components/emoji_picker_category_row.tsx
  components/emoji_picker/components/emoji_picker_current_results.tsx
  components/emoji_picker/components/emoji_picker_custom_emoji_button.tsx
  components/emoji_picker/components/emoji_picker_item.tsx
  components/emoji_picker/components/emoji_picker_preview.tsx
  components/emoji_picker/components/emoji_picker_search.tsx
  components/emoji_picker/components/emoji_picker_skin.tsx
  components/emoji_picker/constants/index.ts
  components/emoji_picker/emoji_picker.jsx
  components/emoji_picker/emoji_picker.test.jsx
  components/emoji_picker/emoji_picker.test.tsx
  components/emoji_picker/emoji_picker.tsx
  components/emoji_picker/emoji_picker_category_section.jsx
  components/emoji_picker/emoji_picker_tabs.jsx
  components/emoji_picker/index.js
  components/emoji_picker/index.ts
  components/emoji_picker/types/index.ts
  components/emoji_picker/utils/index.test.ts
  components/emoji_picker/utils/index.ts
  components/post_view/post_reaction/__snapshots__/post_reaction.test.tsx.snap
  components/post_view/post_reaction/post_reaction.tsx
  components/post_view/reaction_list/reaction_list.tsx
  e2e/cypress/fixtures/timeouts.js
  e2e/cypress/integration/archived_channel/archive_channel_add_reaction_spec.js
  e2e/cypress/integration/custom_status/custom_status_3_spec.js
  e2e/cypress/integration/custom_status/custom_status_4_spec.js
  e2e/cypress/integration/emoji/custom_emoji_1_spec.js
  e2e/cypress/integration/emoji/custom_emoji_2_spec.js
  e2e/cypress/integration/emoji/custom_emoji_3_spec.js
  e2e/cypress/integration/emoji/recently_used_emoji_1_spec.js
  e2e/cypress/integration/emoji/sorted_emojis_spec.js
  e2e/cypress/integration/keyboard_shortcuts/ctrl_cmd_shift_slash/helpers.js
  e2e/cypress/integration/keyboard_shortcuts/ctrl_cmd_shift_slash/not_open_emoji_picker_spec.js
  e2e/cypress/integration/keyboard_shortcuts/ctrl_cmd_shift_slash/react_to_center_spec.js
  e2e/cypress/integration/keyboard_shortcuts/ctrl_cmd_shift_slash/react_to_rhs_spec.js
  e2e/cypress/integration/messaging/emoji_insert_position_spec.js
  e2e/cypress/integration/messaging/message_reaction_gm_spec.js
  e2e/cypress/integration/messaging/message_reaction_spec.js
  e2e/cypress/integration/messaging/reactions_spec.js
  e2e/cypress/integration/plugins/demo_plugin/webhook_spec.js
  e2e/cypress/support/ui_commands.d.ts
  e2e/cypress/support/ui_commands.js
  packages/mattermost-redux/src/selectors/entities/emojis.ts
  packages/mattermost-redux/src/types/emojis.ts
  packages/mattermost-redux/src/utils/emoji_utils.test.js
  packages/mattermost-redux/src/utils/emoji_utils.ts
  sass/components/_emoticons.scss
  selectors/emojis.ts
  types/store/views.ts
  utils/emoji.json
Labels: 4: Reviews Complete, release-note

#9711 Add scorecard analysis
  .github/workflows/scorecards-analysis.yml
Labels: 2: Dev Review

#9881 [MM-42075] Add "(Beta)" to User Groups
  components/admin_console/admin_definition.jsx
  components/sidebar/sidebar_header/sidebar_header.tsx
  components/user_groups_modal/user_groups_modal.scss
  i18n/en.json
Labels: Setup Cloud Test Server, release-note-none, QA Deferred

#9904 [MM-42058] : fix onboarding tour e2e
  components/sidebar/sidebar_channel/sidebar_channel_link/index.ts
  e2e/cypress/integration/onboarding/finish_tutorial_spec.js
  e2e/cypress/integration/onboarding/tutorial_guided_tour_spec.js
Labels: 4: Reviews Complete, CherryPick/Candidate, release-note

#9890 [MM-42020] Fix Categorization of Permissions
  components/admin_console/permission_schemes_settings/permissions_tree/__snapshots__/permissions_tree.test.tsx.snap
  components/admin_console/permission_schemes_settings/permissions_tree/permissions_tree.test.tsx
  components/admin_console/permission_schemes_settings/permissions_tree/permissions_tree.tsx
Labels: 4: Reviews Complete, release-note-none

#9833 MM-41955 Reduce useless changes to user state
  components/root/root.jsx
  components/root/root.test.jsx
  packages/mattermost-redux/src/action_types/users.ts
  packages/mattermost-redux/src/actions/users.test.js
  packages/mattermost-redux/src/actions/users.ts
  packages/mattermost-redux/src/reducers/entities/users.ts
  utils/utils.d.ts
  utils/utils.jsx
  utils/utils.test.jsx
Labels: 4: Reviews Complete, release-note

#9701 [MM-36190] Permalink Nested Previews
  components/file_attachment_list/file_attachment_list.tsx
  components/file_attachment_list/index.ts
  components/post_view/post_attachment_container/post_attachment_container.tsx
  components/post_view/post_attachment_opengraph/__snapshots__/post_attachment_opengraph.test.tsx.snap
  components/post_view/post_attachment_opengraph/post_attachment_opengraph.test.tsx
  components/post_view/post_attachment_opengraph/post_attachment_opengraph.tsx
  components/post_view/post_body/post_body.jsx
  components/post_view/post_body_additional_content/__snapshots__/post_body_additional_content.test.tsx.snap
  components/post_view/post_body_additional_content/post_body_additional_content.test.tsx
  components/post_view/post_body_additional_content/post_body_additional_content.tsx
  components/post_view/post_message_preview/__snapshots__/post_message_preview.test.tsx.snap
  components/post_view/post_message_preview/index.ts
  components/post_view/post_message_preview/post_message_preview.test.tsx
  components/post_view/post_message_preview/post_message_preview.tsx
  components/single_image_view/__snapshots__/single_image_view.test.tsx.snap
  components/single_image_view/single_image_view.test.tsx
  components/single_image_view/single_image_view.tsx
  packages/mattermost-redux/src/reducers/entities/files.test.js
  packages/mattermost-redux/src/reducers/entities/files.ts
  packages/mattermost-redux/src/reducers/entities/posts.test.js
  packages/mattermost-redux/src/reducers/entities/posts.ts
  packages/mattermost-redux/src/utils/post_utils.test.js
  packages/mattermost-redux/src/utils/post_utils.ts
  sass/components/_files.scss
  sass/components/_post.scss
  sass/components/_single_image_view.scss
  sass/layout/_webhooks.scss
Labels: 4: Reviews Complete, release-note

#9808 MM-41805: Improve selectors performance of "getDisplayedChannels" called when typing in quick switcher
  actions/user_actions.test.js
  components/channel_header/channel_header.js
  components/channel_header/index.js
  components/custom_status/custom_status_emoji.test.tsx
  components/custom_status/custom_status_text.test.tsx
  components/sidebar/sidebar_channel_list/sidebar_channel_list.tsx
  components/threading/global_threads_link/global_threads_link.tsx
  packages/mattermost-redux/src/selectors/entities/channels.ts
  packages/mattermost-redux/src/selectors/entities/posts.ts
  selectors/views/channel_sidebar.ts
Labels: 4: Reviews Complete, release-note-none

#9917 MM-41892 Fix untranslatable text in search results
  components/search_results/search_results.tsx
  i18n/en.json
Labels: 4: Reviews Complete, release-note

#9918 MM-41952 : Unread channels names and sidebar item render on top of channel options menu
  sass/layout/_sidebar-left.scss
Labels: 4: Reviews Complete, release-note

#9805 MM-40306 : Investigate removing XRegExp
  components/suggestion/at_mention_provider/at_mention_provider.jsx
  package-lock.json
  package.json
  utils/text_formatting.tsx
Labels: 4: Reviews Complete, release-note

#9857 MM-39537: fixes delay on bolding channel in LHS
  packages/mattermost-redux/src/actions/posts.ts
Labels: 4: Reviews Complete, release-note-none

#9915 MM-41950 Add new playbooks permissions.
  components/admin_console/permission_schemes_settings/permission_schemes_settings.tsx
  components/admin_console/permission_schemes_settings/permissions_tree/__snapshots__/permissions_tree.test.tsx.snap
  components/admin_console/permission_schemes_settings/permissions_tree/permissions_tree.tsx
  components/admin_console/permission_schemes_settings/permissions_tree_playbooks.tsx
  i18n/en.json
  utils/constants.jsx
Labels: 2: Dev Review, release-note-none

#9916 MM-42131 Fix accidental change to PostList positioning
  components/post_view/post_list_virtualized/post_list_virtualized.jsx
Labels: 4: Reviews Complete, release-note, QA Deferred

#9887 MM-39768 Rename ToggleModalButtonRedux to ToggleModalButton
  components/admin_console/system_roles/system_role/system_role_users/__snapshots__/system_role_users.test.tsx.snap
  components/admin_console/system_roles/system_role/system_role_users/system_role_users.tsx
  components/admin_console/team_channel_settings/channel/details/__snapshots__/channel_groups.test.tsx.snap
  components/admin_console/team_channel_settings/channel/details/channel_groups.tsx
  components/admin_console/team_channel_settings/channel/details/channel_members/__snapshots__/channel_members.test.tsx.snap
  components/admin_console/team_channel_settings/channel/details/channel_members/channel_members.tsx
  components/admin_console/team_channel_settings/errors.jsx
  components/admin_console/team_channel_settings/group/__snapshots__/group_row.test.tsx.snap
  components/admin_console/team_channel_settings/group/group_row.tsx
  components/admin_console/team_channel_settings/team/details/__snapshots__/team_groups.test.jsx.snap
  components/admin_console/team_channel_settings/team/details/team_groups.jsx
  components/admin_console/team_channel_settings/team/details/team_members/__snapshots__/team_members.test.tsx.snap
  components/admin_console/team_channel_settings/team/details/team_members/team_members.tsx
  components/announcement_bar/default_announcement_bar/announcement_bar.tsx
  components/post_view/channel_intro_message/__snapshots__/channel_intro_message.test.tsx.snap
  components/post_view/channel_intro_message/add_members_button.tsx
  components/post_view/channel_intro_message/channel_intro_message.tsx
  components/profile_popover/__snapshots__/profile_popover.test.tsx.snap
  components/profile_popover/profile_popover.tsx
  components/sidebar/__snapshots__/invite_members_button.test.tsx.snap
  components/sidebar/invite_members_button.tsx
  components/toggle_modal_button.jsx
  components/toggle_modal_button/__snapshots__/toggle_modal_button.test.jsx.snap
  components/toggle_modal_button/index.js
  components/toggle_modal_button/toggle_modal_button.jsx
  components/toggle_modal_button/toggle_modal_button.test.jsx
  components/user_settings/security/__snapshots__/user_settings_security.test.tsx.snap
  components/user_settings/security/user_settings_security.tsx
  components/widgets/menu/menu_items/__snapshots__/menu_item_toggle_modal_redux.test.tsx.snap
  components/widgets/menu/menu_items/menu_item_toggle_modal_redux.test.tsx
  components/widgets/menu/menu_items/menu_item_toggle_modal_redux.tsx
Labels: 4: Reviews Complete, release-note-none, QA Deferred

#9928 MM-42274 : Remove event listener "resize" on unmount of DataGrid component
  components/admin_console/data_grid/data_grid.tsx
Labels: 4: Reviews Complete, release-note, QA Deferred

#9891 MM-42094 Rework handling of uncaught JS errors
  components/announcement_bar/default_announcement_bar/announcement_bar.tsx
  packages/mattermost-redux/src/actions/errors.ts
  packages/mattermost-redux/src/actions/general.ts
  packages/mattermost-redux/src/client/client4.ts
  packages/mattermost-redux/src/types/client4.ts
  root.jsx
Labels: 4: Reviews Complete, release-note-none

#9935 Lock CI from /release-6.5
  .circleci/config.yml
  .gitlab-ci.yml
Labels: release-note-none

#9936 Automated cherry pick of #9918
  sass/layout/_sidebar-left.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#9941 Automated cherry pick of #9873
  packages/mattermost-redux/src/selectors/entities/roles.test.js
  packages/mattermost-redux/src/selectors/entities/roles.ts
  packages/mattermost-redux/test/test_helper.js
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#9943 Automated cherry pick of #9883
  packages/mattermost-redux/src/actions/groups.ts
  packages/mattermost-redux/src/client/client4.ts
  packages/mattermost-redux/src/selectors/entities/groups.test.js
  packages/mattermost-redux/src/selectors/entities/groups.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#9937 Automated cherry pick of #9912
  components/onboarding_tour/onboarding_tour_manager.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#9939 Automated cherry pick of #9904
  components/sidebar/sidebar_channel/sidebar_channel_link/index.ts
  e2e/cypress/integration/onboarding/finish_tutorial_spec.js
  e2e/cypress/integration/onboarding/tutorial_guided_tour_spec.js
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#9940 Automated cherry pick of #9881
  components/admin_console/admin_definition.jsx
  components/sidebar/sidebar_header/sidebar_header.tsx
  components/user_groups_modal/user_groups_modal.scss
  i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#9938 Automated cherry pick of #9890
  components/admin_console/permission_schemes_settings/permissions_tree/__snapshots__/permissions_tree.test.tsx.snap
  components/admin_console/permission_schemes_settings/permissions_tree/permissions_tree.test.tsx
  components/admin_console/permission_schemes_settings/permissions_tree/permissions_tree.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#9809 [MM-41710] Implement pluggable Call button in channel header
  components/call_button/call_button.tsx
  components/channel_header/__snapshots__/channel_header.test.jsx.snap
  components/channel_header/channel_header.js
  components/create_post/__snapshots__/create_post.test.jsx.snap
  components/create_post/create_post.tsx
  components/post_view/post_body/post_body.jsx
  components/widgets/icons/camera_icon.tsx
  i18n/en.json
  plugins/call_button/call_button.scss
  plugins/call_button/call_button.tsx
  plugins/call_button/index.ts
  plugins/channel_header_plug/channel_header_plug.tsx
  plugins/registry.js
  sass/components/_dropdown.scss
  types/store/plugins.ts
  utils/constants.jsx
Labels: 4: Reviews Complete, release-note

#9942 Automated cherry pick of #9847
  e2e/cypress/integration/channel_sidebar/group_unreads_separately_spec.js
  packages/mattermost-redux/src/selectors/entities/channels.test.js
  packages/mattermost-redux/src/selectors/entities/channels.ts
  reducers/views/channel.test.js
  reducers/views/channel.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#9931 [MM-42207] Revert changes to wake up code where websocket is automatically reconnected
  components/needs_team/needs_team.tsx
Labels: 3: QA Review, Setup Cloud Test Server, release-note-none

#9922 [MM-41579] Remove FF guided channel creation
  components/next_steps_view/steps.test.tsx
  components/next_steps_view/steps.ts
  components/next_steps_view/steps/create_first_channel_step/__snapshots__/create_first_channel_step.test.tsx.snap
  components/next_steps_view/steps/create_first_channel_step/create_first_channel_step.test.tsx
  components/next_steps_view/steps/create_first_channel_step/create_first_channel_step.tsx
  i18n/en.json
  packages/mattermost-redux/src/selectors/entities/preferences.ts
Labels: 2: Dev Review, Setup Cloud Test Server, QA Review Done, release-note-none

#9932 [MM-42298] Fix bugs introduced with console validation
  components/admin_console/schema_admin_settings.jsx
  components/admin_console/schema_admin_settings.test.jsx
Labels: 4: Reviews Complete, CherryPick/Candidate, release-note

#9910 [MM-40486] CRT beta warning modal
  components/collapsed_reply_threads_beta_modal/collapsed_reply_threads_beta_modal.scss
  components/collapsed_reply_threads_beta_modal/collapsed_reply_threads_beta_modal.tsx
  components/collapsed_reply_threads_beta_modal/index.ts
  components/user_settings/modal/index.ts
  components/user_settings/modal/user_settings_modal.tsx
  i18n/en.json
  utils/constants.jsx
Labels: Setup Cloud Test Server, QA Review Done, release-note

#9802 MM-40853 : Pressing Ctrl/Cmd+/ on MacOS should toggle Keyboard Shortcuts modal
  components/sidebar/index.ts
  components/sidebar/sidebar.test.tsx
  components/sidebar/sidebar.tsx
Labels: 4: Reviews Complete, release-note, Contributor

#9954 Automated cherry pick of #9931
  components/needs_team/needs_team.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#9955 Automated cherry pick of #9931
  components/needs_team/needs_team.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#9699 MM-39379 - success modal svg not aligned with button
  components/purchase_modal/icon_message.scss
Labels: 2: Dev Review, release-note-none

#9951 [MM-42126] Fixes: opting out not marking channels tour complete in tasklist
  components/onboarding_tasks/onboarding_tasks_manager.tsx
  components/onboarding_tour/onboarding_tour_manager.tsx
Labels: 2: Dev Review, release-note, QA Deferred

#9956 Automated cherry pick of #9846
  components/create_post/create_post.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#9959 MM-41955 Reduce useless changes to user state (#9833) (release-6.3)
  components/root/root.jsx
  components/root/root.test.jsx
  packages/mattermost-redux/src/action_types/users.ts
  packages/mattermost-redux/src/actions/users.test.js
  packages/mattermost-redux/src/actions/users.ts
  packages/mattermost-redux/src/reducers/entities/users.ts
  utils/utils.d.ts
  utils/utils.jsx
  utils/utils.test.jsx
Labels: 4: Reviews Complete, CherryPick/Done, Setup Cloud Test Server, release-note-none

#9957 Automated cherry pick of #9732
  components/sidebar/sidebar_channel/__snapshots__/sidebar_channel.test.tsx.snap
  components/sidebar/sidebar_channel/sidebar_channel.tsx
  e2e/cypress/integration/channel_sidebar/category_collapsing_spec.js
  e2e/cypress/integration/channel_sidebar/dm_gm_filtering_sorting_spec.js
  sass/layout/_sidebar-left.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#9962 Automated cherry pick of #9918
  sass/layout/_sidebar-left.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#9851 MM-16068: Improve announcement banner tooltip
  components/announcement_bar/__snapshots__/announcement_bar.test.tsx.snap
  components/announcement_bar/configuration_bar/__snapshots__/configuration_bar.test.tsx.snap
  components/announcement_bar/configuration_bar/configuration_bar.tsx
  components/announcement_bar/default_announcement_bar/announcement_bar.tsx
  sass/components/_announcement-bar.scss
  sass/components/_tooltip.scss
  utils/url.tsx
Labels: 4: Reviews Complete, release-note, Contributor

#9911 [MM-40267] Fixes: Channel keyboard navigation breaks when in the Threads view
  components/threading/global_threads/thread_list/thread_list.tsx
Labels: 4: Reviews Complete, release-note

#9929 MM-42127_Search row should not appear in the unreads tab
  components/threading/global_threads/thread_list/__snapshots__/thread_list.test.tsx.snap
  components/threading/global_threads/thread_list/thread_list.tsx
  components/threading/global_threads/thread_list/virtualized_thread_list.test.tsx
  components/threading/global_threads/thread_list/virtualized_thread_list.tsx
  e2e/cypress/integration/collapsed_reply_threads/following_spec.js
Labels: Setup Cloud Test Server, QA Review Done, release-note-none

#9908 MM-41827 Count preloaded channels on first team load
  actions/telemetry_actions.jsx
  components/data_prefetch/actions.ts
  components/data_prefetch/data_prefetch.test.tsx
  components/data_prefetch/data_prefetch.tsx
  components/data_prefetch/index.ts
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note, QA Deferred

#9966 Automated cherry pick of #9910
  components/collapsed_reply_threads_beta_modal/collapsed_reply_threads_beta_modal.scss
  components/collapsed_reply_threads_beta_modal/collapsed_reply_threads_beta_modal.tsx
  components/collapsed_reply_threads_beta_modal/index.ts
  components/user_settings/modal/index.ts
  components/user_settings/modal/user_settings_modal.tsx
  i18n/en.json
  utils/constants.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#9946 MM-41745 refactor upload license flow
  components/admin_console/license_settings/__snapshots__/license_settings.test.jsx.snap
  components/admin_console/license_settings/license_settings.tsx
  components/admin_console/license_settings/modals/__snapshots__/upload_license_modal.test.tsx.snap
  components/admin_console/license_settings/modals/upload_license_modal.test.tsx
  components/admin_console/license_settings/modals/upload_license_modal.tsx
  components/admin_console/license_settings/starter_edition/starter_left_panel.tsx
  utils/constants.jsx
Labels: 2: Dev Review, Setup Cloud Test Server, QA Review Done, 1: UX Review, release-note-none

#9919 [MM-42201] Adding error for username conflict on groups
  components/create_user_groups_modal/create_user_groups_modal.test.tsx
  components/create_user_groups_modal/create_user_groups_modal.tsx
  components/update_user_group_modal/update_user_group_modal.tsx
  i18n/en.json
Labels: 3: QA Review, CherryPick/Approved, Setup Cloud Test Server, release-note-none

#9973 Automated cherry pick of #9919
  components/create_user_groups_modal/create_user_groups_modal.test.tsx
  components/create_user_groups_modal/create_user_groups_modal.tsx
  components/update_user_group_modal/update_user_group_modal.tsx
  i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#9854 adding Persian as a beta language
  components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
  i18n/i18n.jsx
Labels: 4: Reviews Complete, release-note, Contributor

#9976 Automated cherry pick of #9854
  components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
  i18n/i18n.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#9977 Automated cherry pick of #9854
  components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
  i18n/i18n.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#9923 MM-42258: Displays message about username-groupname conflict.
  components/user_settings/general/user_settings_general.test.tsx
  components/user_settings/general/user_settings_general.tsx
  i18n/en.json
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, release-note-none

#9920 [MM-42258] Checking for reserved words when creating/updating groups
  components/create_user_groups_modal/create_user_groups_modal.test.tsx
  components/create_user_groups_modal/create_user_groups_modal.tsx
  components/update_user_group_modal/update_user_group_modal.tsx
  i18n/en.json
Labels: 3: QA Review, CherryPick/Approved, Setup Cloud Test Server, release-note-none

#9981 Automated cherry pick of #9923
  components/user_settings/general/user_settings_general.test.tsx
  components/user_settings/general/user_settings_general.tsx
  i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#9982 Automated cherry pick of #9923
  components/user_settings/general/user_settings_general.test.tsx
  components/user_settings/general/user_settings_general.tsx
  i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#9983 Automated cherry pick of #9920
  components/create_user_groups_modal/create_user_groups_modal.test.tsx
  components/create_user_groups_modal/create_user_groups_modal.tsx
  components/update_user_group_modal/update_user_group_modal.tsx
  i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#9984 Automated cherry pick of #9920
  components/create_user_groups_modal/create_user_groups_modal.test.tsx
  components/create_user_groups_modal/create_user_groups_modal.tsx
  components/update_user_group_modal/update_user_group_modal.tsx
  i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#9863 [MM-T2086] Cypress test for changing password and checking email and timestamp
  e2e/cypress/integration/account_settings/security/password_spec.js
Labels: release-note-none, Contributor

#9967 MM-41830 Add metrics for plugin loading
  actions/telemetry_actions.jsx
  plugins/index.js
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note, QA Deferred

#9963 [MM-31752] - Fixed MM-31752
  components/admin_console/password_settings.jsx
  e2e/cypress/integration/system_console/authentication/password_settings_spec.js
Labels: 2: Dev Review, 3: QA Review, release-note-none

#9980 Growth spike/remove feature flag guard
  components/admin_console/admin_definition.jsx
  components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.jsx.snap
  components/admin_console/admin_sidebar/admin_sidebar.test.jsx
Labels: 2: Dev Review, release-note-none

#9989 adjust svg positioning for cloud case with no previous button
  components/preparing_workspace/use_case.tsx
Labels: 4: Reviews Complete, release-note

#9994 fix references in svg
  components/preparing_workspace/person-smile.svg.tsx
Labels: 4: Reviews Complete, release-note

#9988 use channel display name in onboarding tip. Remove toTitleCase calls …
  components/onboarding_tour/channels_and_direct_messages_tour_tip.tsx
  components/sidebar/sidebar_channel/sidebar_channel_link/sidebar_channel_link.tsx
Labels: 2: Dev Review, Setup Cloud Test Server, QA Review Done, release-note

#9952 [FIX] admin_console/licence_settings: fix of referencing to a button
  components/admin_console/license_settings/trial_banner/trial_banner.tsx
  i18n/en.json
Labels: 4: Reviews Complete, Setup Cloud Test Server, QA Review Done, release-note-none, Contributor

#9986 Cypress:E2E/fixed cypress test cases
  e2e/cypress/integration/account_settings/security/access_history_spec.js
  e2e/cypress/integration/account_settings/security/active_sessions_spec.js
  e2e/cypress/integration/auth_sso/authentication_4_spec.js
  e2e/cypress/integration/emoji/custom_emoji_3_spec.js
  e2e/cypress/integration/system_console/site_configuration/link_customization_e20_1_spec.js
  e2e/cypress/integration/system_console/site_configuration/link_customization_e20_2_spec.js
  e2e/cypress/support/ui/account_settings_modal.js
Labels: release-note-none

#9969 [MM-42322] add thread auto follow setting in system console
  components/admin_console/admin_definition.jsx
  i18n/en.json
  packages/mattermost-redux/src/types/config.ts
Labels: Setup Cloud + CWS Test Server, release-note, QA Deferred

#9997 hide plugins screen, and set plugins status to skipped if plugin conf…
  components/preparing_workspace/preparing_workspace.tsx
Labels: CherryPick/Approved, Setup Cloud Test Server, QA Review Done, release-note-none

#10001 Automated cherry pick of #9997
  components/preparing_workspace/preparing_workspace.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#9947 MM-34312: Migrate 'components/admin_console/permission_schemes_settings/edit_post_time_limit_button' to TypeScript
  components/admin_console/permission_schemes_settings/edit_post_time_limit_button/edit_post_time_limit_button.jsx
  components/admin_console/permission_schemes_settings/edit_post_time_limit_button/edit_post_time_limit_button.tsx
  components/admin_console/permission_schemes_settings/edit_post_time_limit_button/index.tsx
Labels: 4: Reviews Complete, release-note-none, Contributor

#9924 [MM-34342] Migrate 'components/searchable_user_list' to TypeScript
  components/admin_console/system_users/list/system_users_list.tsx
  components/member_list_channel/member_list_channel.tsx
  components/member_list_team/member_list_team.tsx
  components/quick_input/quick_input.tsx
  components/searchable_user_list/searchable_user_list.tsx
  components/searchable_user_list/searchable_user_list_container.jsx
  components/searchable_user_list/searchable_user_list_container.tsx
Labels: 4: Reviews Complete, release-note-none, Contributor

#9993 [MM-37838]: global header clean up
  components/global_header/global_header.tsx
  components/global_header/right_controls/right_controls.tsx
  components/status_dropdown/__snapshots__/status_dropdown.test.tsx.snap
  components/status_dropdown/status_dropdown.tsx
Labels: 4: Reviews Complete, release-note-none

#9999 Cypress:/E2E test cases fixed
  e2e/cypress/integration/enterprise/accessibility/accessibility_modals_dialogs_spec.js
  e2e/cypress/integration/messaging/center_channel_rhs_overlap_spec.js
Labels: release-note-none

#10002 MM-30805 : On websocket reconnect, plugins are reloaded before the rest of the app
  actions/websocket_actions.jsx
Labels: 4: Reviews Complete, release-note-none, QA Deferred

#10003 MM-42321 : Client crashed on typing text in the Gif picker search
  components/emoji_picker/utils/index.ts
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#9949 MM-41824 : Add telemetry to count the number of request on page load
  actions/telemetry_actions.jsx
  components/root/root.jsx
  components/root/root.test.jsx
Labels: 4: Reviews Complete, release-note, QA Deferred

#10005 Cypress:e2e/Fixed and demote test cases
  e2e/cypress/integration/enterprise/accessibility/accessibility_modals_dialogs_1_spec.js
  e2e/cypress/integration/enterprise/accessibility/accessibility_modals_dialogs_spec.js
  e2e/cypress/integration/enterprise/system_console/compliance/s3_bucket_storage_spec.js
  e2e/cypress/integration/files_and_attachments/image_link_preview_KNOWNISSUE_spec.js
  e2e/cypress/integration/files_and_attachments/image_link_preview_spec.js
  e2e/cypress/integration/files_and_attachments/upload_files_KNOWNISSUE_spec.js
  e2e/cypress/integration/files_and_attachments/upload_files_spec.js
  e2e/cypress/integration/mark_as_unread/mark_mentions_as_unread_spec.js
  e2e/cypress/integration/messaging/message_auto_response_spec.js
  e2e/cypress/integration/system_console/user_management/users_deactivation_KNOWNISSUE_spec.js
  e2e/cypress/integration/system_console/user_management/users_deactivation_spec.js
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#9853 [MM-41576] add applied migrations to admin console
  components/about_build_modal/__snapshots__/about_build_modal.test.tsx.snap
  components/about_build_modal/about_build_modal.test.tsx
  components/about_build_modal/about_build_modal.tsx
  components/admin_console/__snapshots__/database_settings.test.jsx.snap
  components/admin_console/database/index.tsx
  components/admin_console/database/migrations_table.scss
  components/admin_console/database/migrations_table.tsx
  components/admin_console/database_settings.jsx
  i18n/en.json
  packages/mattermost-redux/src/actions/admin.ts
  packages/mattermost-redux/src/client/client4.ts
  packages/mattermost-redux/src/types/admin.ts
  packages/mattermost-redux/src/types/config.ts
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note

#10009 [MM-42506]: fixed guest accounts post editing
  components/edit_post/index.ts
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none, kind/bug

#10011 Automated cherry pick of #10009
  components/edit_post/index.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#10012 Automated cherry pick of #10003
  components/emoji_picker/utils/index.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#9927 MM-23809 : Improve "canManageAnyChannelMembersInCurrentTeam" redux selector
  packages/mattermost-redux/src/selectors/entities/channels.ts
Labels: 4: Reviews Complete, release-note-none

#9948 Makefile: run the client in the foreground
  .gitignore
  Makefile
  config.mk
Labels: 4: Reviews Complete, release-note-none

#9655 [MM-38770] Show a copy button when hovering over code blocks
  components/code_block/__snapshots__/code_block.test.jsx.snap
  components/code_block/code_block.test.jsx
  components/code_block/code_block.tsx
  components/copy_button.tsx
  e2e/cypress/fixtures/markdown/markdown_carriage_return_two_lines.html
  e2e/cypress/fixtures/markdown/markdown_code_block.html
  e2e/cypress/fixtures/markdown/markdown_not_autolink.html
  e2e/cypress/fixtures/markdown/markdown_not_in_code_block.html
  i18n/en.json
  sass/layout/_markdown.scss
  sass/utils/_animations.scss
  utils/__snapshots__/message_html_to_component.test.jsx.snap
  utils/markdown/index.test.js
  utils/markdown/renderer.tsx
  utils/message_html_to_component.jsx
  utils/message_html_to_component.test.jsx
  utils/text_formatting_search_highlighting.test.jsx
Labels: 4: Reviews Complete, release-note, Contributor

#10018 [MM-42479] Reduce number of calls to get the subscription data
  actions/views/root.js
  components/announcement_bar/announcement_bar_controller.tsx
  components/announcement_bar/cloud_announcement_bar/user_limit_announcement_bar.tsx
  components/announcement_bar/cloud_trial_announcement_bar/cloud_trial_announcement_bar.tsx
  components/announcement_bar/index.ts
  components/announcement_bar/payment_announcement_bar/payment_announcement_bar.tsx
  components/channel_layout/__snapshots__/channel_controller.test.tsx.snap
  components/login/login_controller/__snapshots__/login_controller.test.jsx.snap
  components/select_team/__snapshots__/select_team.test.tsx.snap
  components/signup/signup_controller/__snapshots__/signup_controller.test.jsx.snap
Labels: 2: Dev Review, release-note-none

#9872 E2E Update text for opening keyboard shortcuts modal
  e2e/cypress/integration/keyboard_shortcuts/keyboard_shortcuts_2_spec.js
Labels: 4: Reviews Complete, release-note-none

#10024 MM-35594 Add post menu item to copy text
  components/dot_menu/__snapshots__/dot_menu.test.tsx.snap
  components/dot_menu/dot_menu.test.tsx
  components/dot_menu/dot_menu.tsx
  e2e/cypress/integration/messaging/copy_post_text_spec.js
  i18n/en.json
  utils/constants.jsx
Labels: 4: Reviews Complete, release-note

#9991 [MM-42402]: compact post editing alignment fix
  components/common/auto_height_switcher.scss
  components/common/auto_height_switcher.tsx
  components/edit_post/edit_post.tsx
  components/post_view/post/__snapshots__/post.test.js.snap
  components/post_view/post/post.jsx
  components/post_view/post_body/post_body.jsx
  components/rhs_comment/__snapshots__/rhs_comment.test.jsx.snap
  components/rhs_comment/rhs_comment.jsx
  components/rhs_root_post/__snapshots__/rhs_root_post.test.jsx.snap
  components/rhs_root_post/rhs_root_post.jsx
  components/search_results_item/__snapshots__/search_results_item.test.jsx.snap
  components/search_results_item/search_results_item.jsx
  package-lock.json
  package.json
  sass/components/_post.scss
  utils/constants.jsx
Labels: 2: Dev Review, Setup Cloud Test Server, QA Review Done, release-note-none, kind/bug

#10032 Fix/conflicts transl
  i18n/ru.json
Labels: Changelog/Not Needed, Docs/Not Needed, 3: Security Review, release-note-none, kind/bug

#10000 MM-41870/MM-41872 Add debug settings to disable "User is typing..." and telemetry events
  actions/global_actions.tsx
  actions/telemetry_actions.jsx
  actions/websocket_actions.jsx
  components/user_settings/advanced/performance_debugging_section/index.ts
  components/user_settings/advanced/performance_debugging_section/performance_debugging_section.tsx
  i18n/en.json
  packages/mattermost-redux/src/constants/preferences.ts
Labels: 4: Reviews Complete, release-note

#9985 [MM40208] fix usernames with periods sorting in channel switcher
  components/suggestion/switch_channel_provider.jsx
  components/suggestion/switch_channel_provider.test.jsx
Labels: 4: Reviews Complete, release-note

#10026 MM 42614 fix e2e broken tests
  components/__snapshots__/generic_modal.test.tsx.snap
  components/custom_status/custom_status_modal.tsx
  components/dnd_custom_time_picker_modal/dnd_custom_time_picker_modal.tsx
  components/edit_category_modal/edit_category_modal.tsx
  components/generic_modal.scss
  components/generic_modal.tsx
  components/product_notices_modal/__snapshots__/product_notices.test.tsx.snap
  components/product_notices_modal/product_notices_modal.tsx
  components/sidebar/sidebar_next_steps/remove_next_steps_modal.tsx
Labels: Setup Cloud Test Server, QA Review Done, release-note-none

#10031 Cypress:E2E/ Test Fixed
  e2e/cypress/tests/integration/accessibility/accessibility_post_spec.js
  e2e/cypress/tests/integration/channel_sidebar/category_sorting_1_spec.js
  e2e/cypress/tests/integration/channel_sidebar/category_sorting_spec.js
  e2e/cypress/tests/integration/channel_sidebar/custom_categories_spec.js
  e2e/cypress/tests/integration/channel_sidebar/group_unreads_separately_1_spec.js
  e2e/cypress/tests/integration/channel_sidebar/group_unreads_separately_spec.js
  e2e/cypress/tests/integration/enterprise/oauth/oauth_spec.js
  e2e/cypress/tests/integration/enterprise/system_console/limited_console_access_not_cloud_spec.js
  e2e/cypress/tests/integration/enterprise/system_console/system_scheme_permission_spec.js
  e2e/cypress/tests/integration/files_and_attachments/image_link_preview_1_spec.js
  e2e/cypress/tests/integration/files_and_attachments/upload_files_1_spec.js
  e2e/cypress/tests/integration/integrations/custom_slash_commands/custom_slash_commands_spec.js
  e2e/cypress/tests/integration/mark_as_unread/mark_as_unread_1_spec.js
  e2e/cypress/tests/integration/mark_as_unread/mark_as_unread_spec.js
  e2e/cypress/tests/integration/system_console/user_management/users_deactivation_1_spec.js
Labels: 4: Reviews Complete, release-note-none

#10037 moved file to e2e cypress test
  e2e/cypress/tests/integration/messaging/copy_post_text_spec.js
Labels: 4: Reviews Complete, release-note-none

#9926 [MM 42088] : Compact message view thread footer avatar click issue
  sass/components/_post.scss
Labels: 4: Reviews Complete, release-note, Contributor

#10039 Cypress/E2E: Fix MM-T4688 copy text menu and shortcut
  components/actions_menu/actions_menu.tsx
  e2e/cypress/tests/integration/messaging/copy_post_text_spec.js
  e2e/cypress/tests/support/api/preference.d.ts
  e2e/cypress/tests/support/api/preference.js
  e2e/cypress/tests/support/api/user.js
  e2e/cypress/tests/support/index.js
Labels: release-note-none

#10038 MM-42675 Update URLs in non-English i18n files
  components/learn_more_trial_modal/__snapshots__/learn_more_trial_modal_step.test.tsx.snap
  components/learn_more_trial_modal/learn_more_trial_modal_step.tsx
  components/onboarding_tasklist/onboarding_tasklist_completed.tsx
  i18n/bg.json
  i18n/de.json
  i18n/en.json
  i18n/en_AU.json
  i18n/es.json
  i18n/fa.json
  i18n/fr.json
  i18n/hu.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 4: Reviews Complete, release-note-none

#10042 Automated cherry pick of #10038
  components/learn_more_trial_modal/__snapshots__/learn_more_trial_modal_step.test.tsx.snap
  components/learn_more_trial_modal/learn_more_trial_modal_step.tsx
  components/onboarding_tasklist/onboarding_tasklist_completed.tsx
  i18n/bg.json
  i18n/de.json
  i18n/en.json
  i18n/en_AU.json
  i18n/es.json
  i18n/fa.json
  i18n/fr.json
  i18n/hu.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#9845 MM-41273 : Restore main menu items added by plugins
  components/main_menu/__snapshots__/main_menu.test.tsx.snap
  components/main_menu/main_menu.tsx
  plugins/test/__snapshots__/main_menu_action.test.jsx.snap
  plugins/test/main_menu_action.test.jsx
Labels: 4: Reviews Complete, release-note, Contributor

#10044 Merge Weblate into master
  i18n/bg.json
  i18n/de.json
  i18n/en_AU.json
  i18n/es.json
  i18n/fa.json
  i18n/fr.json
  i18n/hu.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 4: Reviews Complete, release-note-none

#9263 Separate calls for Apps
  actions/apps.ts
  actions/command.test.js
  actions/command.ts
  components/actions_menu/actions_menu.test.tsx
  components/actions_menu/actions_menu.tsx
  components/actions_menu/actions_menu_empty.test.tsx
  components/actions_menu/actions_menu_mobile.test.tsx
  components/actions_menu/index.ts
  components/app_bar/app_bar_binding.tsx
  components/apps_form/__snapshots__/apps_form_container.test.tsx.snap
  components/apps_form/apps_form_component.test.tsx
  components/apps_form/apps_form_component.tsx
  components/apps_form/apps_form_container.test.tsx
  components/apps_form/apps_form_container.tsx
  components/apps_form/index.ts
  components/dot_menu/dot_menu_empty.test.tsx
  components/dot_menu/dot_menu_mobile.test.tsx
  components/post_view/embedded_bindings/button_binding/button_binding.test.tsx
  components/post_view/embedded_bindings/button_binding/button_binding.tsx
  components/post_view/embedded_bindings/button_binding/index.ts
  components/post_view/embedded_bindings/embedded_binding/embedded_binding.tsx
  components/post_view/embedded_bindings/select_binding/index.ts
  components/post_view/embedded_bindings/select_binding/select_binding.test.tsx
  components/post_view/embedded_bindings/select_binding/select_binding.tsx
  components/suggestion/command_provider/app_command_parser/app_command_parser.test.ts
  components/suggestion/command_provider/app_command_parser/app_command_parser.ts
  components/suggestion/command_provider/app_command_parser/app_command_parser_dependencies.ts
  components/suggestion/command_provider/app_command_parser/tests/app_command_parser_test_data.ts
  components/suggestion/command_provider/app_provider.tsx
  components/suggestion/command_provider/mentions/index.ts
  i18n/en.json
  packages/mattermost-redux/src/client/client4.ts
  packages/mattermost-redux/src/constants/apps.ts
  packages/mattermost-redux/src/reducers/entities/__snapshots__/apps.test.ts.snap
  packages/mattermost-redux/src/reducers/entities/apps.test.ts
  packages/mattermost-redux/src/types/apps.ts
  packages/mattermost-redux/src/utils/apps.test.ts
  packages/mattermost-redux/src/utils/apps.ts
  plugins/channel_header_plug/__snapshots__/channel_header_plug.test.tsx.snap
  plugins/channel_header_plug/channel_header_plug.test.tsx
  plugins/channel_header_plug/channel_header_plug.tsx
  plugins/channel_header_plug/index.ts
  plugins/mobile_channel_header_plug/__snapshots__/mobile_channel_header_plug.test.tsx.snap
  plugins/mobile_channel_header_plug/index.ts
  plugins/mobile_channel_header_plug/mobile_channel_header_plug.test.tsx
  plugins/mobile_channel_header_plug/mobile_channel_header_plug.tsx
  selectors/views/marketplace.test.ts
  types/apps.ts
  utils/apps.ts
Labels: 3: QA Review, release-note

#10047 Automated cherry pick of #10044
  i18n/bg.json
  i18n/de.json
  i18n/en_AU.json
  i18n/es.json
  i18n/fa.json
  i18n/fr.json
  i18n/hu.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#10051 Automated cherry pick of #10034
  components/edit_post/edit_post.tsx
  components/textbox/textbox.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#9964 MM-40115 Add eslint-plugin-react-hooks
  .eslintrc.json
  components/admin_console/billing/company_info_edit.tsx
  components/category_menu_items/category_menu_items.tsx
  components/channel_info_rhs/components/editable_area.tsx
  components/channel_info_rhs/components/linelimiter.tsx
  components/edit_post/edit_post.tsx
  components/emoji/render_emoji.tsx
  components/global_header/hooks.tsx
  components/global_header/left_controls/product_menu/product_menu_list/product_menu_list.tsx
  components/learn_more_trial_modal/learn_more_trial_modal.test.tsx
  components/learn_more_trial_modal/learn_more_trial_modal.tsx
  components/localized_icon.tsx
  components/main_menu/main_menu.tsx
  components/post_view/channel_intro_message/add_members_button.tsx
  components/post_view/post_attachment_opengraph/post_attachment_opengraph.tsx
  components/post_view/post_edited_indicator/post_edited_indicator.tsx
  components/threading/channel_threads/thread_footer/thread_footer.tsx
  components/trial_benefits_modal/trial_benefits_modal.tsx
  package-lock.json
  package.json
  plugins/call_button/call_button.tsx
  stores/hooks.ts
  utils/url.tsx
Labels: 4: Reviews Complete, Major Change, release-note-none

#10008 Adds another 'Active' filter users and admins in AdminConsole/UserManagement/Users
  components/admin_console/system_users/system_users.tsx
  i18n/en.json
  utils/constants.jsx
  utils/filter_users.ts
Labels: 4: Reviews Complete, release-note, Contributor

#9975 MM-42303 Change modal-header CSS to use flexbox instead of floats
  sass/components/_modal.scss
  sass/responsive/_mobile.scss
Labels: 4: Reviews Complete, release-note

#10041 MM-42679 : Remove all occurence of `getAllCustomEmojis` action
  packages/mattermost-redux/src/actions/emojis.test.js
  packages/mattermost-redux/src/actions/emojis.ts
  packages/mattermost-redux/src/actions/users.ts
  packages/mattermost-redux/src/types/requests.ts
Labels: 3: QA Review, release-note-none

#9921 [MM-40072] Fix Groups Pagination in System Console
  components/admin_console/group_settings/groups_list/groups_list.test.tsx
  components/admin_console/group_settings/groups_list/groups_list.tsx
Labels: 4: Reviews Complete, release-note-none

#10017 MM-41820 Report least effective selectors as telemetry
  actions/telemetry_actions.jsx
  components/root/root.jsx
  components/root/root.test.jsx
  packages/reselect/src/index.js
Labels: 4: Reviews Complete, release-note, QA Deferred

#10016 MM-42527 : Clickable area in quick emoji reactions is too small
  components/post_view/post_recent_reactions/recent_reactions_emoji_item.jsx
  components/post_view/post_recent_reactions/recent_reactions_emoji_item.tsx
  sass/components/_post-menu.scss
Labels: 4: Reviews Complete, release-note-none, Contributor

#10053 [MM-42636] fix disabled dot menu clicking
  components/dot_menu/dot_menu.test.tsx
  components/dot_menu/dot_menu.tsx
  components/dot_menu/utils.tsx
Labels: 3: QA Review, CherryPick/Approved, Setup Cloud Test Server, release-note-none

#10057 Automated cherry pick of #10053
  components/dot_menu/dot_menu.test.tsx
  components/dot_menu/dot_menu.tsx
  components/dot_menu/utils.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#10033 [MM-41876]: fix for not-showing updates and indicators in threads
  actions/websocket_actions.jsx
  packages/mattermost-redux/src/actions/threads.ts
Labels: 1: PM Review, Setup Cloud Test Server, release-note, kind/bug

#10048 MM-42390 : Make a minimal GraphQL web client
  packages/mattermost-redux/src/client/client4.test.js
  packages/mattermost-redux/src/client/client4.ts
Labels: 4: Reviews Complete, release-note-none, QA Deferred

#10043 MM-41808: fixes negative unread counts for threads
  packages/mattermost-redux/src/reducers/entities/threads/counts.ts
Labels: Setup Cloud Test Server, release-note-none, QA Deferred

#10035 [MM-42443]: fix selectionRange updates in edit_post component
  components/edit_post/edit_post.tsx
  e2e/cypress/tests/integration/messaging/center_channel_rhs_overlap_spec.js
  utils/utils.jsx
Labels: 4: Reviews Complete, CherryPick/Approved, release-note, kind/bug

#10066 Automated cherry pick of #10035
  components/edit_post/edit_post.tsx
  e2e/cypress/tests/integration/messaging/center_channel_rhs_overlap_spec.js
  utils/utils.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#10045 [MM-41998] Add channel files menu in Channel Info RHS
  actions/global_actions.tsx
  actions/views/rhs.test.ts
  actions/views/rhs.ts
  components/admin_console/team_channel_settings/channel/details/channel_members/index.ts
  components/channel_header/index.js
  components/channel_info_rhs/channel_info_rhs.tsx
  components/channel_info_rhs/index.ts
  components/channel_info_rhs/menu.test.tsx
  components/channel_info_rhs/menu.tsx
  components/search_results_header/index.tsx
  components/search_results_header/search_results_header.test.tsx
  components/search_results_header/search_results_header.tsx
  e2e/cypress/tests/integration/channel/channel_info_rhs_spec.js
  i18n/en.json
  packages/mattermost-redux/src/action_types/channels.ts
  packages/mattermost-redux/src/actions/posts.ts
  packages/mattermost-redux/src/reducers/entities/channels.test.js
  packages/mattermost-redux/src/reducers/entities/channels.ts
  packages/mattermost-redux/src/types/channels.ts
  reducers/views/rhs.ts
  types/store/rhs.ts
Labels: 4: Reviews Complete, Setup Cloud Test Server, QA Review Done, release-note-none

#10062 [MM-42324]: improved rendering performance
  components/edit_post/edit_post.tsx
Labels: release-note-none

#10072 Changed spelling from looukp to lookup in translation
  i18n/en.json
Labels: 4: Reviews Complete, release-note-none, QA Deferred, Contributor

#10069 [MM-42778] Fix console warning introduced by Actions Menu
  components/actions_menu/actions_menu_tutorial_tip.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#10007 [MM-41971] Fix for when pressing enter
  components/create_user_groups_modal/__snapshots__/create_user_groups_modal.test.tsx.snap
  components/create_user_groups_modal/create_user_groups_modal.tsx
  components/update_user_group_modal/__snapshots__/update_user_group_modal.test.tsx.snap
  components/update_user_group_modal/update_user_group_modal.tsx
Labels: 3: QA Review, release-note-none

#10078 Automated cherry pick of #10069
  components/actions_menu/actions_menu_tutorial_tip.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#10056 [MM-42604] - Menu items are misaligned redo
  components/dot_menu/__snapshots__/dot_menu.test.tsx.snap
  components/dot_menu/dot_menu.tsx
  components/widgets/menu/menu_items/menu_item.scss
  components/widgets/menu/menu_items/menu_item_action.test.tsx
  components/widgets/menu/menu_items/menu_item_action.tsx
Labels: CherryPick/Approved, Setup Cloud Test Server, QA Review Done, 1: UX Review, release-note-none

#10079 Automated cherry pick of #10056
  components/dot_menu/__snapshots__/dot_menu.test.tsx.snap
  components/dot_menu/dot_menu.tsx
  components/widgets/menu/menu_items/menu_item.scss
  components/widgets/menu/menu_items/menu_item_action.test.tsx
  components/widgets/menu/menu_items/menu_item_action.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#10028 [MM-42584, MM-42604] post Actions Menu merge fixes
  components/actions_menu/actions_menu.tsx
  components/rhs_comment/rhs_comment.jsx
  components/rhs_root_post/__snapshots__/rhs_root_post.test.jsx.snap
  components/rhs_root_post/rhs_root_post.jsx
  e2e/cypress/tests/integration/accessibility/accessibility_post_spec.js
  e2e/cypress/tests/integration/messaging/tooltip_visual_verification_spec.js
  i18n/en.json
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#8545 [MM-34233] Only refresh App bindings if apps plugin is enabled
  actions/command.test.js
  actions/websocket_actions.jsx
  actions/websocket_actions.test.jsx
  components/admin_console/custom_plugin_settings/index.js
  components/admin_console/plugin_management/__snapshots__/plugin_management.test.tsx.snap
  components/admin_console/plugin_management/index.ts
  components/admin_console/plugin_management/plugin_management.test.tsx
  components/admin_console/plugin_management/plugin_management.tsx
  components/app_bar/app_bar.test.tsx
  components/suggestion/command_provider/app_command_parser/app_command_parser.test.ts
  packages/mattermost-redux/src/action_types/apps.ts
  packages/mattermost-redux/src/actions/apps.ts
  packages/mattermost-redux/src/reducers/entities/apps.test.ts
  packages/mattermost-redux/src/reducers/entities/apps.ts
  packages/mattermost-redux/src/selectors/entities/apps.test.ts
  packages/mattermost-redux/src/selectors/entities/apps.ts
  packages/mattermost-redux/src/store/initial_state.ts
  packages/mattermost-redux/src/types/apps.ts
  utils/constants.jsx
Labels: 2: Dev Review, CherryPick/Approved, release-note-none

#10088 Automated cherry pick of #10028
  components/actions_menu/actions_menu.tsx
  components/rhs_comment/rhs_comment.jsx
  components/rhs_root_post/__snapshots__/rhs_root_post.test.jsx.snap
  components/rhs_root_post/rhs_root_post.jsx
  e2e/cypress/tests/integration/accessibility/accessibility_post_spec.js
  e2e/cypress/tests/integration/messaging/tooltip_visual_verification_spec.js
  i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#10089 Automated cherry pick of #8545
  actions/command.test.js
  actions/websocket_actions.jsx
  actions/websocket_actions.test.jsx
  components/admin_console/custom_plugin_settings/index.js
  components/admin_console/plugin_management/__snapshots__/plugin_management.test.tsx.snap
  components/admin_console/plugin_management/index.ts
  components/admin_console/plugin_management/plugin_management.test.tsx
  components/admin_console/plugin_management/plugin_management.tsx
  components/app_bar/app_bar.test.tsx
  components/suggestion/command_provider/app_command_parser/app_command_parser.test.ts
  packages/mattermost-redux/src/action_types/apps.ts
  packages/mattermost-redux/src/actions/apps.ts
  packages/mattermost-redux/src/reducers/entities/apps.test.ts
  packages/mattermost-redux/src/reducers/entities/apps.ts
  packages/mattermost-redux/src/selectors/entities/apps.test.ts
  packages/mattermost-redux/src/selectors/entities/apps.ts
  packages/mattermost-redux/src/store/initial_state.ts
  packages/mattermost-redux/src/types/apps.ts
  utils/constants.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#9913 [MM-41917] Use feature flag when fetching thread bindings
  components/threading/thread_viewer/index.ts
  components/threading/thread_viewer/thread_viewer.test.tsx
  components/threading/thread_viewer/thread_viewer.tsx
Labels: 4: Reviews Complete, CherryPick/Candidate, release-note

#10090 Automated cherry pick of #9913
  components/threading/thread_viewer/index.ts
  components/threading/thread_viewer/thread_viewer.test.tsx
  components/threading/thread_viewer/thread_viewer.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#10080 [MM-42603] if mobile view, don't show pulsating dot. Always open the actions menu
  selectors/actions_menu.ts
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#10073 MM-42353 - add more padding bottom if task list is shown
  components/admin_console/admin_sidebar/admin_sidebar.jsx
  components/admin_console/admin_sidebar/index.js
  sass/routes/_admin-console.scss
Labels: Setup Cloud Test Server, QA Review Done, release-note-none

#10091 Automated cherry pick of #10080
  selectors/actions_menu.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#10054 MM-34329: Migrate 'components/admin_console/user_autocomplete_setting' and associated tests to TypeScript
  components/admin_console/user_autocomplete_setting/index.tsx
  components/admin_console/user_autocomplete_setting/user_autocomplete_setting.jsx
  components/admin_console/user_autocomplete_setting/user_autocomplete_setting.tsx
Labels: 4: Reviews Complete, release-note-none, Contributor

#9979 MM-34313 : Migrate 'components/admin_console/permission_schemes_settings/edit_post_time_limit_modal' to TypeScript and convert to Functional Component
  components/admin_console/permission_schemes_settings/edit_post_time_limit_modal/edit_post_time_limit_modal.jsx
  components/admin_console/permission_schemes_settings/edit_post_time_limit_modal/edit_post_time_limit_modal.tsx
  components/admin_console/permission_schemes_settings/edit_post_time_limit_modal/index.jsx
  components/admin_console/permission_schemes_settings/edit_post_time_limit_modal/index.tsx
Labels: 4: Reviews Complete, release-note-none, Contributor

#9965 [MM-42261] Fixing group mention highlighting on professional licenses
  components/needs_team/index.ts
  components/needs_team/needs_team.test.tsx
  components/needs_team/needs_team.tsx
Labels: 3: QA Review, Setup Cloud Test Server, release-note-none

#10085 e2e: fix accessiblity test issues
  e2e/cypress/tests/integration/accessibility/accessibility_buttons_spec.js
  e2e/cypress/tests/integration/accessibility/accessibility_dropdowns_spec.js
Labels: release-note-none

#10096 Automated cherry pick of #10085
  e2e/cypress/tests/integration/accessibility/accessibility_buttons_spec.js
  e2e/cypress/tests/integration/accessibility/accessibility_dropdowns_spec.js
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#10071 [MM-41997] Channel Info RHS: add Pinned Messages menu item + improvements
  actions/views/rhs.test.ts
  actions/views/rhs.ts
  components/channel_info_rhs/about_area.tsx
  components/channel_info_rhs/about_area_channel.tsx
  components/channel_info_rhs/about_area_dm.tsx
  components/channel_info_rhs/about_area_gm.tsx
  components/channel_info_rhs/channel_info_rhs.tsx
  components/channel_info_rhs/components/linelimiter.tsx
  components/channel_info_rhs/index.ts
  components/channel_info_rhs/menu.test.tsx
  components/channel_info_rhs/menu.tsx
  components/rhs_header_post/index.ts
  components/rhs_header_post/rhs_header_post.tsx
  components/search_results_header/index.tsx
  components/search_results_header/search_results_header.test.tsx
  components/search_results_header/search_results_header.tsx
  e2e/cypress/tests/integration/channel/channel_info_rhs_spec.js
  i18n/en.json
  reducers/views/rhs.test.js
  reducers/views/rhs.ts
  selectors/rhs.test.js
  selectors/rhs.ts
  types/store/rhs.ts
  utils/constants.jsx
Labels: 3: QA Review, Setup Cloud Test Server, QA Review Done, release-note-none

#10082 Translations update from Mattermost Weblate
  i18n/bg.json
  i18n/de.json
  i18n/en_AU.json
  i18n/es.json
  i18n/fa.json
  i18n/fr.json
  i18n/hu.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/ro.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
  i18n/zh-CN.json
Labels: 4: Reviews Complete, release-note-none

#10063 [MM-42715] Add icons and shortcuts to mobile webview
  components/dot_menu/__snapshots__/dot_menu.test.tsx.snap
  components/dot_menu/dot_menu.tsx
  utils/constants.jsx
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, release-note-none

#10004 MM-42344: Eliminate unnecessary tooltip divs added for links
  components/link_tooltip/__snapshots__/link_tooltip.test.tsx.snap
  components/link_tooltip/link_tooltip.scss
  components/link_tooltip/link_tooltip.tsx
  e2e/cypress/tests/integration/plugins/link_tooltip_spec.js
Labels: 3: QA Review, Setup Cloud Test Server, release-note-none, Contributor

#10087 MM-41607 Don't redeclare redux-batched-actions
  packages/mattermost-redux/src/actions/admin.ts
  packages/mattermost-redux/src/actions/channel_categories.ts
  packages/mattermost-redux/src/actions/channels.ts
  packages/mattermost-redux/src/actions/files.ts
  packages/mattermost-redux/src/actions/general.ts
  packages/mattermost-redux/src/actions/groups.ts
  packages/mattermost-redux/src/actions/helpers.ts
  packages/mattermost-redux/src/actions/integrations.ts
  packages/mattermost-redux/src/actions/posts.ts
  packages/mattermost-redux/src/actions/search.ts
  packages/mattermost-redux/src/actions/teams.ts
  packages/mattermost-redux/src/actions/threads.ts
  packages/mattermost-redux/src/actions/users.ts
  packages/mattermost-redux/src/actions/websocket.ts
  packages/mattermost-redux/src/types/actions.ts
Labels: 4: Reviews Complete, release-note-none

#10027 MM-20427 : Migrate 'components/password_reset_form' and its related files to typescript
  components/password_reset_form/__snapshots__/password_reset_form.test.tsx.snap
  components/password_reset_form/index.js
  components/password_reset_form/index.ts
  components/password_reset_form/password_reset_form.js
  components/password_reset_form/password_reset_form.test.tsx
  components/password_reset_form/password_reset_form.tsx
Labels: 4: Reviews Complete, release-note-none, Contributor

#10095 [MM-42884] Guard against malformed error when logging
  packages/mattermost-redux/src/actions/errors.ts
Labels: 4: Reviews Complete, release-note-none

#10084 MM-42838: hide private playbook permissions on non-ee
  components/admin_console/permission_schemes_settings/permission_system_scheme_settings/__snapshots__/permission_system_scheme_settings.test.tsx.snap
  components/admin_console/permission_schemes_settings/permission_system_scheme_settings/permission_system_scheme_settings.tsx
  components/admin_console/permission_schemes_settings/permission_team_scheme_settings/__snapshots__/permission_team_scheme_settings.test.tsx.snap
  components/admin_console/permission_schemes_settings/permission_team_scheme_settings/permission_team_scheme_settings.tsx
  components/admin_console/permission_schemes_settings/permissions_tree/__snapshots__/permissions_tree.test.tsx.snap
  components/admin_console/permission_schemes_settings/permissions_tree/permissions_tree.test.tsx
  components/admin_console/permission_schemes_settings/permissions_tree/permissions_tree.tsx
  components/admin_console/permission_schemes_settings/permissions_tree/types.ts
  components/admin_console/permission_schemes_settings/permissions_tree_playbooks.test.tsx
  components/admin_console/permission_schemes_settings/permissions_tree_playbooks.tsx
  packages/mattermost-redux/src/types/general.ts
Labels: 4: Reviews Complete, release-note

#10077 [MM-37693]: e2e - testing global threads view
  components/threading/global_threads/thread_list/__snapshots__/thread_list.test.tsx.snap
  components/threading/global_threads/thread_list/thread_list.tsx
  e2e/cypress/tests/integration/collapsed_reply_threads/global_threads_spec.js
  e2e/cypress/tests/support/api_commands.js
Labels: 4: Reviews Complete, release-note-none

#10075 MM-41260: Add new Elasticsearch config settings
  packages/mattermost-redux/src/types/config.ts
Labels: 4: Reviews Complete, release-note-none

#10061 [MM-42713] - Remove cloud user limit restrictions
  actions/websocket_actions.jsx
  components/admin_console/billing/billing_subscriptions/billing_subscriptions.tsx
  components/admin_console/billing/billing_subscriptions/index.tsx
  components/admin_console/billing/plan_details/index.tsx
  components/admin_console/billing/plan_details/plan_details.scss
  components/admin_console/billing/plan_details/plan_details.tsx
  components/announcement_bar/announcement_bar_controller.tsx
  components/announcement_bar/cloud_announcement_bar/index.ts
  components/announcement_bar/cloud_announcement_bar/user_limit_announcement_bar.tsx
  components/announcement_bar/index.ts
  components/common/hocs/cloud/with_get_cloud_subscription.test.tsx
  components/common/hocs/cloud/with_get_cloud_subscription.tsx
  components/error_page/error_page.tsx
  components/error_page/workspace_user_limit_reached.tsx
  components/invitation_modal/index.test.tsx
  components/invitation_modal/index.tsx
  components/invitation_modal/invitation_modal.test.tsx
  components/invitation_modal/invitation_modal.tsx
  components/invitation_modal/invite_view.test.tsx
  components/invitation_modal/invite_view.tsx
  components/main_menu/index.tsx
  components/main_menu/main_menu.test.tsx
  components/main_menu/main_menu.tsx
  components/next_steps_view/steps/invite_members_step/index.ts
  components/next_steps_view/steps/invite_members_step/invite_members_step.test.tsx
  components/next_steps_view/steps/invite_members_step/invite_members_step.tsx
  components/post_view/channel_intro_message/index.ts
  components/signup/signup_controller/__snapshots__/signup_controller.test.jsx.snap
  components/signup/signup_controller/index.js
  components/signup/signup_controller/signup_controller.jsx
  components/signup/signup_controller/signup_controller.test.jsx
  components/widgets/links/__snapshots__/notify_link.test.tsx.snap
  components/widgets/links/notify_link.test.tsx
  components/widgets/links/notify_link.tsx
  components/widgets/menu/menu_items/menu_cloud_trial.test.tsx
  e2e/cypress/tests/integration/accessibility/accessibility_buttons_spec.js
  e2e/cypress/tests/integration/enterprise/cloud/onboarding/cloud_legacy_invite_member_by_email_spec.js
  e2e/cypress/tests/support/api/cloud_default_config.json
  i18n/en.json
  packages/mattermost-redux/src/action_types/cloud.ts
  packages/mattermost-redux/src/actions/cloud.ts
  packages/mattermost-redux/src/client/client4.ts
  packages/mattermost-redux/src/reducers/entities/cloud.ts
  packages/mattermost-redux/src/selectors/entities/general.ts
  packages/mattermost-redux/src/types/cloud.ts
  packages/mattermost-redux/src/types/config.ts
  plugins/test/__snapshots__/main_menu_action.test.jsx.snap
  plugins/test/main_menu_action.test.jsx
  sass/routes/_error-page.scss
  utils/constants.jsx
Labels: 2: Dev Review, QA Review Done, Setup Cloud + CWS Test Server, release-note
