Repository mattermost/mattermost-webapp, pull requests merged in 2022-10, with the labels that each got.

#11170 Contribute Voice Message: Add initial config for voice messages
  components/admin_console/admin_definition.jsx
  e2e/playwright/support/server/default_config.ts
  i18n/en.json
  packages/mattermost-redux/src/constants/posts.ts
  packages/mattermost-redux/src/selectors/entities/general.test.ts
  packages/mattermost-redux/src/selectors/entities/general.ts
  packages/types/src/config.ts
  packages/types/src/posts.ts
  utils/constants.tsx
Labels: 2: Dev Review, release-note-none

#11241 Update compass-icons to 0.1.27
  package-lock.json
  package.json
Labels: 4: Reviews Complete, release-note

#11164 MM-47118 : Migrate "components/post_markdown/index.test.js" to Typescript
  components/post_markdown/index.test.ts
Labels: 4: Reviews Complete, release-note-none, Contributor

#11252 Automated cherry pick of #11067
  webpack.config.js
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#11247 MM-47193 : Migrate "utils/youtube.js" to typescript
  utils/youtube.ts
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted, release-note-none, Contributor

#11232 Revert to React 16
  components/__snapshots__/searchable_channel_list.test.jsx.snap
  components/__snapshots__/textbox.test.tsx.snap
  components/admin_console/data_retention_settings/channel_list/__snapshots__/channel_list.test.tsx.snap
  components/admin_console/system_roles/system_role/system_role_users/__snapshots__/system_role_users.test.tsx.snap
  components/admin_console/system_users/list/__snapshots__/system_users_list.test.tsx.snap
  components/admin_console/team_channel_settings/channel/details/__snapshots__/channel_groups.test.tsx.snap
  components/admin_console/team_channel_settings/channel/details/channel_members/__snapshots__/channel_members.test.tsx.snap
  components/admin_console/team_channel_settings/channel/list/__snapshots__/channel_list.test.tsx.snap
  components/admin_console/team_channel_settings/team/details/__snapshots__/team_groups.test.tsx.snap
  components/admin_console/team_channel_settings/team/details/team_members/__snapshots__/team_members.test.tsx.snap
  components/channel_header_dropdown/__snapshots__/channel_header_dropdown.test.jsx.snap
  components/global_header/left_controls/product_menu/product_menu_list/__snapshots__/product_menu_list.test.tsx.snap
  components/main_menu/__snapshots__/main_menu.test.tsx.snap
  components/plugin_marketplace/__snapshots__/marketplace_modal.test.tsx.snap
  components/post_view/channel_intro_message/__snapshots__/channel_intro_message.test.tsx.snap
  components/profile_popover/__snapshots__/profile_popover.test.tsx.snap
  components/select_team/components/__snapshots__/select_team_item.test.tsx.snap
  components/sidebar/__snapshots__/invite_members_button.test.tsx.snap
  components/status_dropdown/__snapshots__/status_dropdown.test.tsx.snap
  components/user_settings/security/__snapshots__/user_settings_security.test.tsx.snap
  package-lock.json
  package.json
  packages/components/package.json
  plugins/test/__snapshots__/main_menu_action.test.jsx.snap
  tests/setup.js
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#11216 Fix profile popovers closing action due to react update
  components/at_mention/at_mention.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#11256 Automated cherry pick of #11216
  components/at_mention/at_mention.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#11255 Automated cherry pick of #11216
  components/at_mention/at_mention.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#11148 MM-47044 Wrap Pluggable component in an error boundary
  i18n/en.json
  plugins/pluggable/__snapshots__/pluggable.test.jsx.snap
  plugins/pluggable/error_boundary.tsx
  plugins/pluggable/pluggable.test.jsx
  plugins/pluggable/pluggable.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#11259 Automated cherry pick of #11148
  i18n/en.json
  plugins/pluggable/__snapshots__/pluggable.test.jsx.snap
  plugins/pluggable/error_boundary.tsx
  plugins/pluggable/pluggable.test.jsx
  plugins/pluggable/pluggable.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#11258 Automated cherry pick of #11148
  i18n/en.json
  plugins/pluggable/__snapshots__/pluggable.test.jsx.snap
  plugins/pluggable/error_boundary.tsx
  plugins/pluggable/pluggable.test.jsx
  plugins/pluggable/pluggable.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#11263 Downgraded Brazilian Portuguese and Romanian language support to Alpha
  components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
  i18n/i18n.jsx
Labels: 4: Reviews Complete, Docs/Not Needed, CherryPick/Approved, AutoMerge, release-note

#11265 Automated cherry pick of #11263
  components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
  i18n/i18n.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#11248 MM-47194 : Migrate "utils/storage_utils.js" to typescript
  utils/storage_utils.ts
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted, release-note-none, Contributor

#11239 MM-47101 : Migrate "components/channel_notifications_modal/components/describe.jsx" to Typescript
  components/channel_notifications_modal/components/__snapshots__/describe.test.tsx.snap
  components/channel_notifications_modal/components/collapse_view.jsx
  components/channel_notifications_modal/components/describe.test.tsx
  components/channel_notifications_modal/components/describe.tsx
  components/channel_notifications_modal/components/expand_view.jsx
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted, release-note-none, Contributor

#11083 [MM-46596] Screen Reader Announces Login Successful
  components/advanced_text_editor/advanced_text_editor.tsx
  components/channel_view/channel_view.tsx
  i18n/en.json
Labels: 4: Reviews Complete, release-note, Contributor

#11257 Prevent clean from failing because of missing files
  Makefile
Labels: 4: Reviews Complete, release-note-none

#11235 MM-46316 Fix a few broken links in the System Console
  components/admin_console/admin_definition.jsx
  components/admin_console/group_settings/__snapshots__/group_settings.test.tsx.snap
  components/admin_console/group_settings/group_settings.tsx
  components/admin_console/team_channel_settings/team/details/__snapshots__/team_profile.test.tsx.snap
  components/widgets/admin_console/admin_panel.test.tsx
  components/widgets/admin_console/admin_panel.tsx
  components/widgets/admin_console/admin_panel_with_link.tsx
  i18n/en.json
  sass/routes/_admin-console.scss
Labels: 4: Reviews Complete, release-note, QA Deferred

#11220 e2e/Cypress:fixed spec files
  e2e/cypress/tests/integration/channel/channel_info_rhs_spec.js
  e2e/cypress/tests/integration/integrations/builtin_commands/common_commands_1_spec.js
  e2e/cypress/tests/integration/keyboard_shortcuts/ctrl_cmd_k_focuses_message_box_spec.js
  e2e/cypress/tests/integration/keyboard_shortcuts/ctrl_cmd_k_open_channel_from_global_threads_spec.js
  e2e/cypress/tests/integration/modals/quick_switcher_spec.js
  e2e/cypress/tests/integration/scroll/image_aspect_ratio_spec.js
Labels: release-note-none

#11275 Update subpackage versions to 7.3.0
  package-lock.json
  package.json
  packages/client/package.json
  packages/types/package.json
Labels: release-note-none

#11039 [MM-46236]: remove deactivated users from the select list
  components/forward_post_modal/forward_post_channel_select.tsx
Labels: Setup Cloud Test Server, QA Review Done, release-note-none, kind/bug

#11141 [MM-46566] - Invite Guest: Add upsell prompt in self-managed
  components/feature_restricted_modal/feature_restricted_modal.test.tsx
  components/feature_restricted_modal/feature_restricted_modal.tsx
  components/invitation_modal/index.test.tsx
  components/invitation_modal/index.tsx
  components/invitation_modal/invitation_modal.test.tsx
  components/invitation_modal/invite_as.test.tsx
  components/invitation_modal/invite_as.tsx
  components/invitation_modal/invite_view.test.tsx
  components/learn_more_trial_modal/learn_more_trial_modal.tsx
  components/onboarding_tasklist/onboarding_tasklist_completed.tsx
  i18n/de.json
  i18n/en.json
  i18n/en_AU.json
  i18n/hu.json
  i18n/ja.json
  i18n/nl.json
  i18n/pl.json
  i18n/sv.json
  i18n/tr.json
Labels: 2: Dev Review, 3: QA Review, Setup Cloud Test Server, QA Review Done, release-note

#11270 MM-46953 : Add "Threads" to the unread filter view even if there aren't unread threads
  components/threading/global_threads_link/global_threads_link.tsx
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted, release-note, Contributor

#11221 MM-47105 : Migrate "components/more_direct_channels/list_item/list_item.test.jsx" to Typescript
  components/more_direct_channels/list_item/__snapshots__/list_item.test.tsx.snap
  components/more_direct_channels/list_item/list_item.test.tsx
  components/more_direct_channels/list_item/list_item.tsx
Labels: 4: Reviews Complete, release-note-none, Contributor

#11233 MM-47089 : Migrate "components/integrations/integration_option.jsx" to Typescript
  components/integrations/integration_option.tsx
  components/integrations/integrations.jsx
Labels: 4: Reviews Complete, release-note-none, Contributor

#11130 [MM-40152] Add shortcut to toggle unread/all channels
  components/file_upload/file_upload.tsx
  components/keyboard_shortcuts/keyboard_shortcuts_modal/__snapshots__/keyboard_shortcuts_modal.test.tsx.snap
  components/keyboard_shortcuts/keyboard_shortcuts_modal/keyboard_shortcuts_modal.tsx
  components/keyboard_shortcuts/keyboard_shortcuts_sequence/keyboard_shortcuts.ts
  components/sidebar/channel_filter/__snapshots__/channel_filter.test.tsx.snap
  components/sidebar/channel_filter/channel_filter.test.tsx
  components/sidebar/channel_filter/channel_filter.tsx
  e2e/cypress/tests/integration/channel_sidebar/unread_filter_spec.js
  i18n/en.json
Labels: 1: PM Review, Setup Cloud Test Server, QA Review Done, release-note

#11285 Automated cherry pick of #11218
  components/integrations/bots/add_bot/add_bot.test.tsx
  components/integrations/bots/add_bot/add_bot.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#11143 MM-20472: Migrate 'components/team_general_tab' module and associated tests to TypeScript
  components/team_general_tab/__snapshots__/team_general_tab.test.tsx.snap
  components/team_general_tab/index.js
  components/team_general_tab/index.ts
  components/team_general_tab/open_invite.tsx
  components/team_general_tab/team_general_tab.test.tsx
  components/team_general_tab/team_general_tab.tsx
  components/team_settings/team_settings.tsx
Labels: 4: Reviews Complete, release-note-none, Contributor

#11273 MM-47102: Migrate "components/channel_notifications_modal/components/section_title.jsx" to Typescript
  components/channel_notifications_modal/components/__snapshots__/section_title.test.tsx.snap
  components/channel_notifications_modal/components/collapse_view.jsx
  components/channel_notifications_modal/components/expand_view.jsx
  components/channel_notifications_modal/components/section_title.test.tsx
  components/channel_notifications_modal/components/section_title.tsx
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted, release-note-none, Contributor

#11205 MM-47087 : Migrate "components/integrations/integrations.jsx"
  components/integrations/index.ts
  components/integrations/integrations.tsx
Labels: 4: Reviews Complete, release-note-none, Contributor

#11250 MM-47189: Migrate "utils/timezone.jsx" to Typescript
  actions/views/rhs.test.ts
  components/logged_in/logged_in.tsx
  components/user_settings/display/user_settings_display.tsx
  utils/timezone.ts
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted, release-note-none, Contributor

#11136 [MM-45686] Add display name to add members to channel modal
  components/channel_invite_modal/__snapshots__/channel_invite_modal.test.tsx.snap
  components/channel_invite_modal/channel_invite_modal.test.tsx
  components/channel_invite_modal/channel_invite_modal.tsx
  components/channel_invite_modal/index.ts
  components/channel_members_rhs/member.tsx
Labels: 4: Reviews Complete, release-note-none

#11142 MM-46286: Change default # of DMs shown in sidebar from 20 to 40
  actions/views/channel_sidebar.test.ts
  components/sidebar/sidebar_category/sidebar_category_sorting_menu/index.ts
  components/user_settings/sidebar/limit_visible_gms_dms/index.ts
  e2e/cypress/tests/integration/channel_sidebar/dm_gm_filtering_sorting_spec.js
  packages/mattermost-redux/src/selectors/entities/channel_categories.ts
  selectors/views/channel_sidebar.test.js
  utils/constants.tsx
Labels: 4: Reviews Complete, release-note, Contributor

#11237 MM-20382 : Migrate 'components/gif_picker/components/SearchGrid.jsx' to Typescript
  components/gif_picker/components/SearchGrid/SearchGrid.tsx
  components/gif_picker/components/SearchGrid/index.ts
  packages/types/src/gifs.ts
Labels: 4: Reviews Complete, release-note-none, Contributor

#11150 MM-20424: Migrate 'components/channel_notifications_modal/channel_notifications_modal.jsx' and associated tests to TypeScript
  components/channel_notifications_modal/__snapshots__/channel_notifications_modal.test.tsx.snap
  components/channel_notifications_modal/channel_notifications_modal.test.tsx
  components/channel_notifications_modal/channel_notifications_modal.tsx
  components/channel_notifications_modal/index.js
  components/channel_notifications_modal/index.ts
  utils/constants.tsx
Labels: 4: Reviews Complete, release-note-none, Contributor

#11211 [MM-46568] - AD-LDAP upsell banner
  components/cloud_start_trial/cloud_start_trial_btn.tsx
  components/learn_more_trial_modal/start_trial_btn.tsx
  components/user_groups_modal/__snapshots__/user_groups_modal.test.tsx.snap
  components/user_groups_modal/ad_ldap_upsell_banner.test.tsx
  components/user_groups_modal/ad_ldap_upsell_banner.tsx
  components/user_groups_modal/user_groups_modal.scss
  components/user_groups_modal/user_groups_modal.tsx
  i18n/en.json
Labels: 2: Dev Review, 3: QA Review, Setup Cloud Test Server, QA Review Done, 1: UX Review, release-note-none

#11279 [MM-47226]: fixed a bug with currentTeamId not being set on mount
  components/needs_team/needs_team.tsx
  components/search_results/index.tsx
  components/search_results/search_results.tsx
  packages/mattermost-redux/src/selectors/entities/teams.ts
Labels: 4: Reviews Complete, CherryPick/Approved, AutoMerge, release-note-none, kind/bug

#11291 Automated cherry pick of #11279
  components/needs_team/needs_team.tsx
  components/search_results/index.tsx
  components/search_results/search_results.tsx
  packages/mattermost-redux/src/selectors/entities/teams.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#11271 Fix warning printed by SizeAwareImage
  components/size_aware_image.jsx
Labels: 4: Reviews Complete, release-note-none

#8704 For select and input fields, if the label is empty, don't add the label element. This allows compacting the fields vertically
  components/apps_form/apps_form_component.tsx
  components/apps_form/apps_form_field/apps_form_field.test.tsx
  components/apps_form/apps_form_field/apps_form_field.tsx
  components/apps_form/apps_form_field/apps_form_select_field.tsx
  components/widgets/settings/setting.tsx
  i18n/en.json
Labels: 4: Reviews Complete, release-note

#11223 MM-20519 : Migrate 'components/emoji_picker/emoji_picker_overlay.jsx' module to TypeScript
  components/advanced_create_comment/__snapshots__/advanced_create_comment.test.jsx.snap
  components/advanced_create_comment/advanced_create_comment.tsx
  components/advanced_create_post/__snapshots__/advanced_create_post.test.jsx.snap
  components/advanced_create_post/advanced_create_post.tsx
  components/advanced_text_editor/advanced_text_editor.tsx
  components/custom_status/custom_status_modal.tsx
  components/emoji_picker/emoji_picker_overlay.tsx
  components/post_view/post_reaction/__snapshots__/post_reaction.test.tsx.snap
  components/post_view/post_reaction/post_reaction.tsx
  components/post_view/reaction_list/__snapshots__/reactions_list.test.tsx.snap
  components/post_view/reaction_list/reaction_list.tsx
Labels: 4: Reviews Complete, release-note-none, Contributor

#11169 MM-47112 : Migrate "components/interactive_dialog/dialog_introduction_text.jsx" to Typescript
  components/interactive_dialog/__snapshots__/dialog_introduction_text.test.tsx.snap
  components/interactive_dialog/dialog_introduction_text.jsx
  components/interactive_dialog/dialog_introduction_text.test.tsx
  components/interactive_dialog/dialog_introduction_text.tsx
Labels: 4: Reviews Complete, release-note-none, Contributor

#11282 [MM-45688]: fixed missing options due to wrong filtering
  components/forward_post_modal/forward_post_channel_select.tsx
  components/forward_post_modal/forward_post_modal.tsx
Labels: 2: Dev Review, Setup Cloud Test Server, QA Review Done, release-note-none, kind/bug

#11290 legacy mattermost cloud bar
  components/announcement_bar/announcement_bar_controller.tsx
  components/announcement_bar/legacy_mattermost_cloud_bar/index.test.tsx
  components/announcement_bar/legacy_mattermost_cloud_bar/index.tsx
  i18n/en.json
  utils/test_helper.ts
Labels: 3: QA Review, Setup Cloud + CWS Test Server, release-note

#11302 Automated cherry pick of #11290
  components/announcement_bar/announcement_bar_controller.tsx
  components/announcement_bar/legacy_mattermost_cloud_bar/index.test.tsx
  components/announcement_bar/legacy_mattermost_cloud_bar/index.tsx
  i18n/en.json
  utils/test_helper.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#11230 MM-47217 Reorder the leave channel menu item
  components/channel_header_dropdown/__snapshots__/channel_header_dropdown.test.jsx.snap
  components/channel_header_dropdown/channel_header_dropdown_items.js
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none, QA Deferred

#11294 MM-34347: Migrate 'components/toast_wrapper' and associated tests to TypeScript
  components/post_view/post_list_virtualized/post_list_virtualized.tsx
  components/toast_wrapper/index.ts
  components/toast_wrapper/toast_wrapper.test.tsx
  components/toast_wrapper/toast_wrapper.tsx
  packages/mattermost-redux/src/utils/post_list.ts
Labels: 2: Dev Review, Hacktoberfest, 3: QA Review, hacktoberfest-accepted, release-note-none, Contributor

#11268 [MM-46567] - Self-Hosted admin: Add User Group in Product Switcher with CTA to start a trial
  components/global_header/left_controls/product_menu/product_menu_list/index.ts
  components/global_header/left_controls/product_menu/product_menu_list/product_menu_list.test.tsx
  components/global_header/left_controls/product_menu/product_menu_list/product_menu_list.tsx
Labels: 2: Dev Review, 3: QA Review, QA Review Done, Setup Cloud + CWS Test Server, release-note-none

#11289 [MM-47162] - Fix cloud pricing modal copy
  components/pricing_modal/content.tsx
  i18n/en.json
Labels: 1: PM Review, 2: Dev Review, release-note-none

#11280 [MM-47185] - Enterprise features labelled "Professional Feature" in the sidebar tooltip
  components/admin_console/admin_definition.jsx
  components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.tsx.snap
  components/widgets/menu/menu_items/restricted_indicator.tsx
  i18n/en.json
Labels: 1: PM Review, 2: Dev Review, Setup Cloud Test Server, QA Review Done, release-note-none

#8601 [MM-33930] show loading indicator when the selecting an option.
  components/apps_form/__snapshots__/apps_form_component.test.tsx.snap
  components/apps_form/apps_form_component.scss
  components/apps_form/apps_form_component.tsx
  components/widgets/loading/loading_spinner.tsx
Labels: 4: Reviews Complete, release-note

#11315 Bump @mattermost/compass-icons to 0.1.28
  package.json
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted, release-note, Contributor

#11283 [MM-47054] Change button label if upgrade is executed from System Console
  components/purchase_modal/process_payment_setup.tsx
Labels: 4: Reviews Complete, QA Review Done, Setup Cloud + CWS Test Server, release-note-none

#11324 [MM-47412] Check if delinquency since is not null before to calculate…
  components/delinquency_modal/delinquency_modal_controller.test.tsx
  components/delinquency_modal/useDelinquencyModalController.tsx
Labels: 3: QA Review, CherryPick/Approved, Setup Cloud + CWS Test Server, release-note-none

#11330 Automated cherry pick of #11324
  components/delinquency_modal/delinquency_modal_controller.test.tsx
  components/delinquency_modal/useDelinquencyModalController.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#11307 [#21315]: migrated custom status tests to typescript
  e2e/cypress/package-lock.json
  e2e/cypress/package.json
  e2e/cypress/tests/integration/custom_status/custom_status_1_spec.ts
  e2e/cypress/tests/integration/custom_status/custom_status_2_spec.ts
  e2e/cypress/tests/integration/custom_status/custom_status_3_spec.ts
  e2e/cypress/tests/integration/custom_status/custom_status_4_spec.ts
  e2e/cypress/tests/integration/custom_status/custom_status_5_spec.ts
  e2e/cypress/tests/integration/custom_status/custom_status_6_spec.ts
  e2e/cypress/tests/support/api/system.d.ts
  e2e/cypress/tests/support/extended_commands.d.ts
  e2e/cypress/tests/support/extended_commands.js
  e2e/cypress/tests/support/ui/global_header.d.ts
Labels: release-note-none

#11140 [MM-44858] Screen reader fails in announcing no result found in dm modal
  components/multiselect/multiselect_list.tsx
  i18n/en.json
Labels: 4: Reviews Complete, release-note, Contributor

#11336 Translations update from Mattermost Weblate
  i18n/de.json
  i18n/en_AU.json
  i18n/fr.json
  i18n/hu.json
  i18n/ja.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/sv.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-TW.json
Labels: Hacktoberfest, hacktoberfest-accepted, release-note-none, Do Not Merge/Mattermod

#11104 [MM-42341] Reset password error message
  components/password_reset_form/password_reset_form.tsx
  i18n/en.json
Labels: 2: Dev Review, Setup Cloud Test Server, QA Review Done, 1: UX Review, release-note

#11337 MM-47400/MM-47410 Fix subpaths with module federation
  entry.tsx
  root.tsx
  webpack.config.js
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#11340 Automated cherry pick of #11337
  entry.tsx
  root.tsx
  webpack.config.js
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#11338 Automated cherry pick of #11337
  entry.tsx
  root.tsx
  webpack.config.js
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#11131 MM-46804 - stop flashing in feature discovery pages
  components/admin_console/feature_discovery/index.tsx
Labels: Setup Cloud + CWS Test Server, release-note-none

#11341 Update package-lock.json
  package-lock.json
Labels: 4: Reviews Complete, release-note-none

#11309 MM-47284: Migrate /autocomplete/ tests to TypeScript
  e2e/cypress/tests/integration/autocomplete/common_test.ts
  e2e/cypress/tests/integration/autocomplete/helpers.ts
  e2e/cypress/tests/support/api/team.d.ts
  e2e/cypress/tests/support/api/user.d.ts
  e2e/cypress/tests/support/ui/common.d.ts
  e2e/cypress/tests/support/ui/suggestion_list.d.ts
Labels: Hacktoberfest, hacktoberfest-accepted, release-note-none, Contributor

#11094 MM-45848: fix mention badge update
  packages/mattermost-redux/src/reducers/entities/channels.test.js
  packages/mattermost-redux/src/reducers/entities/channels.ts
Labels: 4: Reviews Complete, release-note, QA Deferred

#11347 [MM-46645] - UI Enhancement | Web App | To Disable notify button when we see 'Already Notified' text
  components/center_message_lock/index.tsx
  components/feature_restricted_modal/feature_restricted_modal.tsx
  components/notify_admin_cta/notify_admin_cta.tsx
  e2e/cypress/tests/integration/enterprise/cloud/billing/notify_admin_spec.js
Labels: 2: Dev Review, 3: QA Review, QA Review Done, release-note-none

#11254 Cypress e2e: Migrated profile tests to typescript
  e2e/cypress/tests/integration/account_settings/profile/account_settings_position_spec.ts
  e2e/cypress/tests/integration/account_settings/profile/email_spec.ts
  e2e/cypress/tests/integration/account_settings/profile/fullname_edit_spec.ts
  e2e/cypress/tests/integration/account_settings/profile/fullname_truncate_spec.ts
  e2e/cypress/tests/integration/account_settings/profile/help_text_link_spec.ts
  e2e/cypress/tests/integration/account_settings/profile/nickname_spec.ts
  e2e/cypress/tests/integration/account_settings/profile/profile_picture_change_spec.ts
  e2e/cypress/tests/integration/account_settings/profile/username_spec.ts
  e2e/cypress/tests/support/api/system.d.ts
  e2e/cypress/tests/support/api/user.d.ts
  e2e/cypress/tests/support/email.d.ts
  e2e/cypress/tests/support/email.ts
  e2e/cypress/tests/support/ui/channel_header.d.ts
  e2e/cypress/tests/support/ui/common.d.ts
Labels: release-note-none

#11041 [MM-46694] A/B Test: welcome post
  actions/command.ts
  components/channel_info_rhs/header.test.tsx
  components/root/root.tsx
  components/sidebar/invite_members_button.test.tsx
  components/toast_wrapper/toast_wrapper.test.tsx
  components/welcome_post_renderer/index.scss
  components/welcome_post_renderer/index.test.tsx
  components/welcome_post_renderer/index.tsx
  e2e/cypress/tests/integration/enterprise/ldap/ldap_group_sync_spec.js
  e2e/cypress/tests/integration/integrations/integrations_spec.js
  i18n/en.json
  packages/mattermost-redux/src/selectors/entities/channels.test.ts
Labels: 2: Dev Review, CherryPick/Candidate, release-note-none, QA Deferred

#11358 Automated cherry pick of #11041
  actions/command.ts
  components/channel_info_rhs/header.test.tsx
  components/root/root.tsx
  components/sidebar/invite_members_button.test.tsx
  components/toast_wrapper/toast_wrapper.test.tsx
  components/welcome_post_renderer/index.scss
  components/welcome_post_renderer/index.test.tsx
  components/welcome_post_renderer/index.tsx
  e2e/cypress/tests/integration/enterprise/ldap/ldap_group_sync_spec.js
  e2e/cypress/tests/integration/integrations/integrations_spec.js
  i18n/en.json
  packages/mattermost-redux/src/selectors/entities/channels.test.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#11231 MM-T642: Attachment does not collapse - Cypress Webapp E2E Test
  e2e/cypress/tests/integration/integrations/incoming_webhook/attachment_does_not_collapse_spec.ts
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#11312 MM-21300 : Migrate /benchmark e2e tests to TypeScript
  e2e/cypress/tests/integration/benchmark/message_spec.ts
  e2e/cypress/tests/support/win.d.ts
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted, release-note-none, Contributor

#11339 [MM-47499] Add UTM Tracking
  components/root/root.tsx
Labels: 2: Dev Review, Setup Cloud Test Server, release-note-none, QA Deferred

#11296 GH-13865 : Add missing a11y__modal dialogClassName to <Modal> components
  components/admin_console/billing/billing_history_modal.tsx
  components/cloud_invoice_preview/index.tsx
  components/start_trial_modal/index.tsx
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted, release-note-none, Contributor

#11318 [GH-21305] Migrate /commands tests to TypeScript
  e2e/cypress/tests/integration/commands/leave_channel_spec.ts
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted, release-note-none, Contributor

#11240 MM-47093 : Migrate "components/integrations/installed_command.jsx" to Typescript
  components/integrations/__snapshots__/installed_command.test.tsx.snap
  components/integrations/installed_command.test.tsx
  components/integrations/installed_command.tsx
  components/integrations/installed_commands/installed_commands.tsx
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted, release-note-none, Contributor

#11242 MM-47191 : Migrate "utils/emoji.jsx" to Typescript
  build/emoji/emoji_gen.mjs
  components/emoji_picker/components/emoji_picker_skin.tsx
  components/emoji_picker/constants/index.ts
  components/post_view/reaction/index.ts
  components/root/root.tsx
  utils/emoji.d.ts
  utils/emoji.ts
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted, release-note-none, Contributor

#11245 MM-20592: Migrate 'components/search_results_item' to TypeScript
  components/dot_menu/index.ts
  components/search_results_item/__snapshots__/search_results_item.test.tsx.snap
  components/search_results_item/index.test.ts
  components/search_results_item/index.ts
  components/search_results_item/search_results_item.test.tsx
  components/search_results_item/search_results_item.tsx
  packages/types/src/posts.ts
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted, release-note-none, Contributor

#11274 MM-47103 : Migrate components/channel_notifications_modal/components/collapse_view.jsx to Typescript
  components/channel_notifications_modal/components/__snapshots__/collapse_view.test.tsx.snap
  components/channel_notifications_modal/components/collapse_view.test.tsx
  components/channel_notifications_modal/components/collapse_view.tsx
  components/channel_notifications_modal/components/notification_section.jsx
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted, release-note-none, Contributor

#11288 MM-47043: Cursor pointer on youtube link previews
  sass/components/_videos.scss
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted, release-note-none, Contributor

#11246 MM-47192 : Migrate "utils/policy_roles_adapter.js" to typescript
  utils/policy_roles_adapter.ts
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted, release-note-none, Contributor

#11295 MM-18905 : Remove unused status flags in Jobs request state object
  packages/mattermost-redux/src/action_types/jobs.ts
  packages/mattermost-redux/src/actions/jobs.test.js
  packages/mattermost-redux/src/actions/jobs.ts
  packages/mattermost-redux/src/reducers/requests/index.ts
  packages/mattermost-redux/src/reducers/requests/jobs.ts
  packages/mattermost-redux/src/store/initial_state.ts
  packages/types/src/requests.ts
  packages/types/src/store.ts
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted, release-note-none, Contributor

#11272 MM-47068: Migrate components/suggestion/provider.jsx to typescript
  components/forward_post_modal/forward_post_channel_select.tsx
  components/suggestion/at_mention_provider/at_mention_provider.jsx
  components/suggestion/channel_mention_provider.jsx
  components/suggestion/emoticon_provider.jsx
  components/suggestion/generic_channel_provider.jsx
  components/suggestion/generic_user_provider.jsx
  components/suggestion/menu_action_provider.jsx
  components/suggestion/provider.tsx
  components/suggestion/search_channel_provider.tsx
  components/suggestion/search_channel_with_permissions_provider.jsx
  components/suggestion/search_date_provider.jsx
  components/suggestion/search_user_provider.jsx
  components/suggestion/switch_channel_provider.jsx
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted, release-note-none, Contributor

#11322 [MM-47299] Migrated enterprise/permissions tests to Typescript
  e2e/cypress/tests/integration/enterprise/channel/channel_groups_spec.ts
  e2e/cypress/tests/support/api/channel.d.ts
  e2e/cypress/tests/support/api/system.d.ts
  e2e/cypress/tests/support/api/team.d.ts
  e2e/cypress/tests/support/index.d.ts
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted, release-note-none, Contributor

#11345 [MM-45385]: fixing selection after applying styles
  utils/markdown/apply_markdown.ts
Labels: 2: Dev Review, QA Review Done, release-note-none, kind/bug

#11278 MM-47069 : Migrate "components/suggestion/genric_user_provider" To Typescript
  components/admin_console/user_autocomplete_setting/index.tsx
  components/admin_console/user_autocomplete_setting/user_autocomplete_setting.tsx
  components/apps_form/apps_form_field/apps_form_field.test.tsx
  components/apps_form/apps_form_field/apps_form_field.tsx
  components/apps_form/apps_form_field/index.ts
  components/interactive_dialog/dialog_element/dialog_element.tsx
  components/interactive_dialog/dialog_element/index.ts
  components/post_view/message_attachments/action_menu/action_menu.tsx
  components/suggestion/generic_user_provider.tsx
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted, release-note-none, Contributor

#11281 MM-T2044 added profile-settings test spec
  e2e/cypress/tests/integration/profile_settings/profile_settings_spec.js
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted, release-note-none, Contributor

#11361 Automated cherry pick of #11339
  components/root/root.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#11305 [MM-47309] Migrated OAuth e2e tests to typescript
  e2e/cypress/tests/integration/enterprise/oauth/oauth_spec.ts
  e2e/cypress/tests/support/task_commands.ts
Labels: 4: Reviews Complete, Hacktoberfest, AutoMerge, hacktoberfest-accepted, release-note-none, Contributor

#11306 MM-47310 : Migrated enterprise/permissions e2e tests to Typescript
  e2e/cypress/tests/integration/enterprise/permissions/team_permissions_spec.ts
  e2e/cypress/tests/support/api/scheme.d.ts
  e2e/cypress/tests/support/ui/sidebar_left.ts
Labels: Hacktoberfest, hacktoberfest-accepted, release-note-none, Contributor

#11308 MM-21319 : Migrate "/integration/enterprise/ldap_group" e2e tests to TypeScript
  e2e/cypress/tests/integration/enterprise/ldap_group/channel_modes_spec.ts
  e2e/cypress/tests/integration/enterprise/ldap_group/group_mentions_spec.ts
  e2e/cypress/tests/integration/enterprise/ldap_group/groups_assign_roles_spec.ts
  e2e/cypress/tests/integration/enterprise/ldap_group/invite_bot_spec.ts
  e2e/cypress/tests/integration/enterprise/ldap_group/search_channels_spec.ts
  e2e/cypress/tests/integration/enterprise/ldap_group/team_and_channel_assign_roles_spec.ts
  e2e/cypress/tests/support/api/preference.d.ts
  e2e/cypress/tests/support/api/team.d.ts
Labels: 4: Reviews Complete, Hacktoberfest, AutoMerge, hacktoberfest-accepted, release-note-none, Contributor

#10954 Add error page for archived posts
  components/error_page/error_message.tsx
  components/error_page/error_page.test.tsx
  components/error_page/error_page.tsx
  components/error_page/error_title.tsx
  components/error_page/messages/cloud_archived.tsx
  components/permalink_view/actions.ts
  components/threading/thread_viewer/index.ts
  components/threading/virtualized_thread_viewer/create_comment.tsx
  i18n/en.json
  packages/mattermost-redux/src/actions/posts.ts
  packages/mattermost-redux/src/selectors/entities/cloud.ts
  utils/constants.tsx
  utils/test_helper.ts
Labels: 3: QA Review, QA Review Done, Setup Cloud + CWS Test Server, release-note

#11371 MM-46549 add e2e test for gather intent feature
  components/payment_form/gather_intent/gather_intent.scss
  e2e/cypress/tests/integration/enterprise/cloud/billing/payment_free_trial_spec.js
  e2e/cypress/tests/integration/enterprise/cloud/billing/payment_free_trial_spec.ts
Labels: release-note-none

#11317 MM-47302 Migrate /enterprise/extend_session e2e tests to TypeScript
  e2e/cypress/tests/integration/enterprise/extend_session/email_login_activity_spec.ts
  e2e/cypress/tests/integration/enterprise/extend_session/session_length_spec.ts
  e2e/cypress/tests/support/db_commands.d.ts
  e2e/cypress/tests/support/db_commands.js
  e2e/cypress/tests/support/db_commands.ts
Labels: Hacktoberfest, hacktoberfest-accepted, release-note-none, Contributor

#11343 MM-47534 : Remove the 'channelRolesLoading' check in "channel_view"
  components/channel_view/__snapshots__/channel_view.test.tsx.snap
  components/channel_view/channel_view.test.tsx
  components/channel_view/channel_view.tsx
  components/channel_view/index.ts
Labels: 4: Reviews Complete, release-note-none

#11362 Cypress/E2E: Revert changes using lodash.set and mattermost types imports
  e2e/cypress/package-lock.json
  e2e/cypress/package.json
  e2e/cypress/tests/integration/custom_status/custom_status_1_spec.ts
  e2e/cypress/tests/integration/custom_status/custom_status_2_spec.ts
  e2e/cypress/tests/integration/custom_status/custom_status_3_spec.ts
  e2e/cypress/tests/integration/custom_status/custom_status_4_spec.ts
  e2e/cypress/tests/integration/custom_status/custom_status_5_spec.ts
  e2e/cypress/tests/integration/custom_status/custom_status_6_spec.ts
  e2e/cypress/tests/integration/enterprise/oauth/oauth_spec.ts
  e2e/cypress/tests/support/api/setup.ts
Labels: 4: Reviews Complete, release-note-none

#11382 Create remote entrypoint for webapp to be imported by desktop, add basic module registry
  registry.ts
  utils/browser_history.jsx
  webpack.config.js
Labels: do-not-merge/release-note-label-needed

#10723 [MM-35703] Maintain scroll position in channel when opening reply message permalinks
  actions/views/channel.ts
  components/activity_and_insights/insights/insights.tsx
  components/advanced_create_comment/advanced_create_comment.tsx
  components/advanced_create_post/advanced_create_post.test.jsx
  components/advanced_create_post/advanced_create_post.tsx
  components/code_block/__snapshots__/code_block.test.tsx.snap
  components/code_preview.jsx
  components/copy_button.tsx
  components/file_preview_modal/__snapshots__/file_preview_modal.test.tsx.snap
  components/file_preview_modal/file_preview_modal.tsx
  components/file_preview_modal/file_preview_modal_footer/__snapshots__/file_preview_modal_footer.test.tsx.snap
  components/file_preview_modal/file_preview_modal_footer/file_preview_modal_footer.test.tsx
  components/file_preview_modal/file_preview_modal_footer/file_preview_modal_footer.tsx
  components/file_preview_modal/file_preview_modal_header/__snapshots__/file_preview_modal_header.test.tsx.snap
  components/file_preview_modal/file_preview_modal_header/file_preview_modal_header.test.tsx
  components/file_preview_modal/file_preview_modal_header/file_preview_modal_header.tsx
  components/file_preview_modal/file_preview_modal_main_actions/__snapshots__/file_preview_modal_main_actions.test.tsx.snap
  components/file_preview_modal/file_preview_modal_main_actions/file_preview_modal_main_actions.test.tsx
  components/file_preview_modal/file_preview_modal_main_actions/file_preview_modal_main_actions.tsx
  components/permalink_view/actions.ts
  components/permalink_view/permalink_view.test.tsx
  components/post_view/post_attachment_container/__snapshots__/post_attachment_container.test.tsx.snap
  components/post_view/post_attachment_container/post_attachment_container.test.tsx
  components/post_view/post_attachment_container/post_attachment_container.tsx
  components/sidebar_right/sidebar_right.tsx
  components/suggestion/switch_channel_provider.jsx
  components/suggestion/switch_channel_provider.test.jsx
  i18n/en.json
  packages/mattermost-redux/src/selectors/entities/channels.test.ts
  packages/mattermost-redux/src/selectors/entities/channels.ts
  packages/mattermost-redux/src/selectors/entities/teams.ts
  sass/layout/_markdown.scss
  utils/constants.tsx
  utils/utils.tsx
Labels: 4: Reviews Complete, release-note, Contributor

#11121 MM-44114 : Announcing of channel interface language dropdown correctly
  components/user_settings/display/__snapshots__/user_settings_display.test.tsx.snap
  components/user_settings/display/manage_languages/manage_languages.test.tsx
  components/user_settings/display/manage_languages/manage_languages.tsx
  i18n/en.json
Labels: release-note, Contributor

#11119 Mm 45580 notify admin delinquency update billing
  components/announcement_bar/announcement_bar_controller.tsx
  components/announcement_bar/cloud_delinquency/index.tsx
  components/announcement_bar/default_announcement_bar/announcement_bar.tsx
  components/announcement_bar/notify_admin_downgrade_delinquency_bar/index.tsx
  components/announcement_bar/notify_admin_downgrade_delinquency_bar/notify_admin_downgrade_delinquency_bar.test.tsx
  components/center_message_lock/index.tsx
  components/common/hooks/useDelinquencySubscription.ts
  components/common/hooks/useGetNotifyAdmin.ts
  components/custom_open_pricing_modal_post_renderer/index.tsx
  components/feature_restricted_modal/feature_restricted_modal.tsx
  components/notify_admin_cta/notify_admin_cta.tsx
  i18n/en.json
  utils/constants.tsx
  utils/notify_admin_utils.ts
Labels: 1: PM Review, 2: Dev Review, 3: QA Review, QA Review Done, 1: UX Review, Setup Cloud + CWS Test Server, release-note

#11219 MM-47099 : Migrate "components/channel_notifications_modal/components/expand_view.jsx" to Typescript
  components/channel_notifications_modal/components/__snapshots__/expand_view.test.tsx.snap
  components/channel_notifications_modal/components/expand_view.test.tsx
  components/channel_notifications_modal/components/expand_view.tsx
  components/channel_notifications_modal/components/notification_section.jsx
Labels: 4: Reviews Complete, release-note-none, Contributor

#11342 e2e/cypress:fixed test cases
  e2e/cypress/tests/integration/accessibility/accessibility_account_settings_spec.js
  e2e/cypress/tests/integration/accessibility/accessibility_nav_diff_regions_spec.js
  e2e/cypress/tests/integration/keyboard_shortcuts/keyboard_shortcuts_2_spec.js
  e2e/cypress/tests/integration/settings/display/message_display_mode_colorize_username_spec.js
Labels: release-note-none

#11373 MM-47611 : Change tsconfig value of module to 'es2020'
  tsconfig.json
Labels: 4: Reviews Complete, release-note-none

#11385 Updated CodeQL to use latest version
  .github/codeql/codeql-config.yml
  .github/workflows/codeql-analysis.yml
Labels: 4: Reviews Complete, release-note-none

#11384 Playwright/E2E: update dependencies and screenshots
  e2e/playwright/.eslintrc.json
  e2e/playwright/.percy.yml
  e2e/playwright/README.md
  e2e/playwright/global_setup.ts
  e2e/playwright/package-lock.json
  e2e/playwright/package.json
  e2e/playwright/support/server/init.ts
  e2e/playwright/support/visual/applitools.ts
  e2e/playwright/support/visual/index.ts
  e2e/playwright/support/visual/percy.ts
  e2e/playwright/tests/visual/intro_channel.spec.ts
  e2e/playwright/tests/visual/intro_channel.spec.ts-snapshots/intro-to-channel-as-regular-user-chrome-linux.png
  e2e/playwright/tests/visual/intro_channel.spec.ts-snapshots/intro-to-channel-as-regular-user-firefox-linux.png
  e2e/playwright/tests/visual/intro_channel.spec.ts-snapshots/intro-to-channel-as-regular-user-ipad-linux.png
  e2e/playwright/tests/visual/intro_channel.spec.ts-snapshots/intro-to-channel-as-regular-user-iphone-linux.png
  e2e/playwright/tests/visual/landing_page.spec.ts
  e2e/playwright/tests/visual/login.spec.ts
  e2e/playwright/tests/visual/login.spec.ts-snapshots/login-chrome-linux.png
  e2e/playwright/tests/visual/login.spec.ts-snapshots/login-error-chrome-linux.png
  e2e/playwright/tests/visual/login.spec.ts-snapshots/login-error-firefox-linux.png
  e2e/playwright/tests/visual/login.spec.ts-snapshots/login-firefox-linux.png
  e2e/playwright/tests/visual/signup_email.spec.ts
  e2e/playwright/tests/visual/signup_email.spec.ts-snapshots/signup-email-chrome-linux.png
  e2e/playwright/tests/visual/signup_email.spec.ts-snapshots/signup-email-error-chrome-linux.png
  e2e/playwright/tests/visual/signup_email.spec.ts-snapshots/signup-email-error-firefox-linux.png
  e2e/playwright/tests/visual/signup_email.spec.ts-snapshots/signup-email-firefox-linux.png
Labels: 4: Reviews Complete, release-note-none

#11113 MM-43306 : Support graphQL for channels, channel members
  actions/channel_actions.ts
  actions/channel_queries.ts
  actions/local_storage.jsx
  components/channel_layout/channel_controller.test.tsx
  components/channel_layout/channel_controller.tsx
  components/needs_team/__snapshots__/needs_team.test.tsx.snap
  components/needs_team/index.ts
  components/needs_team/needs_team.test.tsx
  components/needs_team/needs_team.tsx
  components/root/root.tsx
  components/team_controller/actions/index.test.ts
  components/team_controller/actions/index.ts
  components/team_controller/index.ts
  components/team_controller/team_controller.tsx
  packages/mattermost-redux/src/action_types/channels.ts
  packages/mattermost-redux/src/actions/roles.ts
  packages/mattermost-redux/src/actions/users.ts
  packages/mattermost-redux/src/actions/users_queries.ts
  packages/mattermost-redux/src/reducers/requests/channels.ts
  packages/mattermost-redux/src/reducers/requests/helpers.ts
  packages/mattermost-redux/src/store/initial_state.ts
  packages/types/src/requests.ts
Labels: 4: Reviews Complete, release-note

#11222 MM-47065 : Migrate "components/suggestion/search_date_provider.jsx" to Typescript
  components/suggestion/search_date_provider.tsx
Labels: 4: Reviews Complete, release-note-none, Contributor

#11070 MM-46392 - create channels with a board
  actions/global_actions.tsx
  components/app_bar/__snapshots__/app_bar.test.tsx.snap
  components/app_bar/app_bar.scss
  components/app_bar/app_bar.tsx
  components/app_bar/app_bar_plugin_component.tsx
  components/app_bar/new_channel_with_board_tour_tip.scss
  components/app_bar/new_channel_with_board_tour_tip.tsx
  components/channel_header/components/__snapshots__/header_icon_wrapper.test.tsx.snap
  components/channel_header/components/header_icon_wrapper.tsx
  components/global_header/left_controls/product_menu/product_menu.tsx
  components/new_channel_modal/new_channel_modal.scss
  components/new_channel_modal/new_channel_modal.test.tsx
  components/new_channel_modal/new_channel_modal.tsx
  components/new_channel_modal/new_channel_modal_with_board.test.tsx
  components/post_view/channel_intro_message/index.ts
  components/widgets/inputs/input/input.tsx
  e2e/cypress/tests/integration/channel/new_channel_with_board_spec.js
  e2e/cypress/tests/support/ui/channel.js
  i18n/en.json
  packages/client/src/client4.ts
  packages/components/src/common/hooks/useClickOutsideRef.ts
  packages/components/src/tour_tip/tour_tip.tsx
  packages/mattermost-redux/src/actions/boards.ts
  packages/mattermost-redux/src/constants/preferences.ts
  packages/types/src/boards.ts
  packages/types/src/posts.ts
  plugins/channel_header_plug/__snapshots__/channel_header_plug.test.tsx.snap
  plugins/channel_header_plug/channel_header_plug.tsx
  selectors/plugins.ts
  utils/constants.tsx
Labels: Setup Cloud Test Server, QA Review Done, release-note

#11350 MM-47497 - remove invite task from guest users
  components/onboarding_tasks/onboarding_tasks_manager.test.tsx
  components/onboarding_tasks/onboarding_tasks_manager.tsx
  packages/mattermost-redux/src/selectors/entities/users.ts
Labels: Setup Cloud Test Server, QA Review Done, release-note-none

#11388 MM-47679 - add id to feature discovery cloud trial start telemetry id
  components/admin_console/feature_discovery/__snapshots__/feature_discovery.test.tsx.snap
  components/admin_console/feature_discovery/feature_discovery.tsx
Labels: 2: Dev Review, Setup Cloud + CWS Test Server, release-note-none

#11359 MM-47396 - trial ended banner not dismissable
  components/announcement_bar/configuration_bar/__snapshots__/configuration_bar.test.tsx.snap
  components/announcement_bar/configuration_bar/configuration_bar.test.tsx
  components/announcement_bar/configuration_bar/configuration_bar.tsx
  components/announcement_bar/configuration_bar/index.ts
  components/announcement_bar/renewal_link/renewal_link.tsx
  utils/constants.tsx
Labels: QA Review Done, Setup Cloud + CWS Test Server, release-note-none

#11323 MM-47250: Add a new section in system console for products
  components/admin_console/admin_definition.jsx
  components/admin_console/admin_sidebar/admin_sidebar.test.tsx
  components/global_header/left_controls/product_menu/product_menu_list/__snapshots__/product_menu_list.test.tsx.snap
  i18n/en.json
  packages/mattermost-redux/src/constants/permissions.ts
  packages/mattermost-redux/src/constants/permissions_sysconsole.ts
  utils/admin_console_index.tsx
Labels: 4: Reviews Complete, release-note-none

#11390 Migrate /enterprise/guest_accounts e2e tests to TypeScript
  e2e/cypress/tests/integration/enterprise/elasticsearch_autocomplete/helpers/index.js
  e2e/cypress/tests/integration/enterprise/guest_accounts/guest_add_spec.ts
  e2e/cypress/tests/integration/enterprise/guest_accounts/guest_experience_ui_spec.ts
  e2e/cypress/tests/integration/enterprise/guest_accounts/guest_feature_spec.ts
  e2e/cypress/tests/integration/enterprise/guest_accounts/guest_identification_spec.ts
  e2e/cypress/tests/integration/enterprise/guest_accounts/guest_identification_ui_not_cloud_spec.ts
  e2e/cypress/tests/integration/enterprise/guest_accounts/guest_identification_ui_spec.ts
  e2e/cypress/tests/integration/enterprise/guest_accounts/guest_invitation_ui_more_spec.ts
  e2e/cypress/tests/integration/enterprise/guest_accounts/guest_invitation_ui_spec.ts
  e2e/cypress/tests/integration/enterprise/guest_accounts/guest_popover_ui_spec.ts
  e2e/cypress/tests/integration/enterprise/guest_accounts/guest_removal_ui_spec.ts
  e2e/cypress/tests/integration/enterprise/guest_accounts/helpers.ts
  e2e/cypress/tests/integration/enterprise/guest_accounts/member_invitation_ui_spec.ts
  e2e/cypress/tests/integration/enterprise/guest_accounts/system_console_guest_access_ui_spec.ts
  e2e/cypress/tests/integration/enterprise/guest_accounts/system_console_manage_guest_not_cloud_spec.ts
  e2e/cypress/tests/integration/enterprise/guest_accounts/system_console_manage_guest_spec.ts
  e2e/cypress/tests/support/api/user.d.ts
  e2e/cypress/tests/support/ui/common.d.ts
  e2e/cypress/tests/support/ui_commands.ts
Labels: release-note-none

#11310 [MM-44031] add system console SMTP link to invitation error
  actions/invite_actions.test.ts
  actions/invite_actions.ts
  components/invitation_modal/result_table.scss
  components/invitation_modal/result_table.tsx
  i18n/en.json
  utils/constants.tsx
Labels: 2: Dev Review, Setup Cloud Test Server, QA Review Done, 1: UX Review, release-note-none

#11389 [MM-47168] removing redundant test file
  e2e/cypress/tests/integration/enterprise/cloud/billing/banner_trial_spec.js
Labels: 4: Reviews Complete, release-note-none

#11409 Automated cherry pick of #11407
  actions/views/channel.ts
  components/activity_and_insights/insights/insights.tsx
  components/advanced_create_comment/advanced_create_comment.tsx
  components/advanced_create_post/advanced_create_post.test.jsx
  components/advanced_create_post/advanced_create_post.tsx
  components/code_block/__snapshots__/code_block.test.tsx.snap
  components/code_preview.jsx
  components/copy_button.tsx
  components/file_preview_modal/__snapshots__/file_preview_modal.test.tsx.snap
  components/file_preview_modal/file_preview_modal.tsx
  components/file_preview_modal/file_preview_modal_footer/__snapshots__/file_preview_modal_footer.test.tsx.snap
  components/file_preview_modal/file_preview_modal_footer/file_preview_modal_footer.test.tsx
  components/file_preview_modal/file_preview_modal_footer/file_preview_modal_footer.tsx
  components/file_preview_modal/file_preview_modal_header/__snapshots__/file_preview_modal_header.test.tsx.snap
  components/file_preview_modal/file_preview_modal_header/file_preview_modal_header.test.tsx
  components/file_preview_modal/file_preview_modal_header/file_preview_modal_header.tsx
  components/file_preview_modal/file_preview_modal_main_actions/__snapshots__/file_preview_modal_main_actions.test.tsx.snap
  components/file_preview_modal/file_preview_modal_main_actions/file_preview_modal_main_actions.test.tsx
  components/file_preview_modal/file_preview_modal_main_actions/file_preview_modal_main_actions.tsx
  components/permalink_view/actions.ts
  components/permalink_view/permalink_view.test.tsx
  components/post_view/post_attachment_container/__snapshots__/post_attachment_container.test.tsx.snap
  components/post_view/post_attachment_container/post_attachment_container.test.tsx
  components/post_view/post_attachment_container/post_attachment_container.tsx
  components/sidebar_right/sidebar_right.tsx
  components/suggestion/switch_channel_provider.jsx
  components/suggestion/switch_channel_provider.test.jsx
  i18n/en.json
  packages/mattermost-redux/src/selectors/entities/channels.test.ts
  packages/mattermost-redux/src/selectors/entities/channels.ts
  packages/mattermost-redux/src/selectors/entities/teams.ts
  sass/layout/_markdown.scss
  utils/constants.tsx
  utils/utils.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#11406 [MM-475584]: fix channel name not showing up in search results
  components/search_results_item/index.ts
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, AutoMerge, release-note, QA Deferred

#11410 Automated cherry pick of #11406
  components/search_results_item/index.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#11154 [MM-45909] Fixing group permissions issue
  packages/mattermost-redux/src/selectors/entities/roles.test.ts
  packages/mattermost-redux/src/selectors/entities/roles.ts
Labels: 3: QA Review, Setup Cloud Test Server, release-note

#11414 Revert "MM-43306 : Support graphQL for channels, channel members"
  actions/channel_actions.ts
  actions/channel_queries.ts
  actions/local_storage.jsx
  components/channel_layout/channel_controller.test.tsx
  components/channel_layout/channel_controller.tsx
  components/needs_team/__snapshots__/needs_team.test.tsx.snap
  components/needs_team/index.ts
  components/needs_team/needs_team.test.tsx
  components/needs_team/needs_team.tsx
  components/root/root.tsx
  components/team_controller/actions/index.test.ts
  components/team_controller/actions/index.ts
  components/team_controller/index.ts
  components/team_controller/team_controller.tsx
  packages/mattermost-redux/src/action_types/channels.ts
  packages/mattermost-redux/src/actions/roles.ts
  packages/mattermost-redux/src/actions/users.ts
  packages/mattermost-redux/src/actions/users_queries.ts
  packages/mattermost-redux/src/reducers/requests/channels.ts
  packages/mattermost-redux/src/reducers/requests/helpers.ts
  packages/mattermost-redux/src/store/initial_state.ts
  packages/types/src/requests.ts
Labels: 4: Reviews Complete, release-note

#11398 [MM-47619] Upgrade redux to version 4.2.0
  package-lock.json
  package.json
  packages/mattermost-redux/src/store/configureStore.ts
Labels: 4: Reviews Complete, release-note-none

#11251 Adds UI permissions guard for wrangler movethread
  components/admin_console/admin_definition.jsx
  components/dot_menu/__snapshots__/dot_menu.test.tsx.snap
  components/dot_menu/dot_menu.test.tsx
  components/dot_menu/dot_menu.tsx
  components/dot_menu/dot_menu_empty.test.tsx
  components/dot_menu/dot_menu_mobile.test.tsx
  components/dot_menu/index.ts
  components/forward_post_modal/forward_post_modal.scss
  components/move_thread_modal/move_thread_modal.tsx
  i18n/en.json
  packages/mattermost-redux/src/selectors/entities/posts.ts
  packages/types/src/config.ts
Labels: 2: Dev Review, release-note-none

#11424 Automated cherry pick of #11414
  actions/channel_actions.ts
  actions/channel_queries.ts
  actions/local_storage.jsx
  components/channel_layout/channel_controller.test.tsx
  components/channel_layout/channel_controller.tsx
  components/needs_team/__snapshots__/needs_team.test.tsx.snap
  components/needs_team/index.ts
  components/needs_team/needs_team.test.tsx
  components/needs_team/needs_team.tsx
  components/root/root.tsx
  components/team_controller/actions/index.test.ts
  components/team_controller/actions/index.ts
  components/team_controller/index.ts
  components/team_controller/team_controller.tsx
  packages/mattermost-redux/src/action_types/channels.ts
  packages/mattermost-redux/src/actions/roles.ts
  packages/mattermost-redux/src/actions/users.ts
  packages/mattermost-redux/src/actions/users_queries.ts
  packages/mattermost-redux/src/reducers/requests/channels.ts
  packages/mattermost-redux/src/reducers/requests/helpers.ts
  packages/mattermost-redux/src/store/initial_state.ts
  packages/types/src/requests.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#11393 [MM-47621] Upgrade highlight.js to 11.6.0
  package-lock.json
  package.json
Labels: 4: Reviews Complete, release-note-none

#11425 Automated cherry pick of #11140
  components/multiselect/multiselect_list.tsx
  i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#11379 [MM-47560]: Add support for new fields (back-end and front-end)
  components/admin_console/billing/billing_subscriptions/limit_reached_banner.test.tsx
  components/pricing_modal/downgrade_team_removal_modal/downgrade_team_removal_modal.test.tsx
  packages/types/src/cloud.ts
Labels: 2: Dev Review, release-note-none

#11426 Automated cherry pick of #10792
  components/search/search.tsx
  components/search_hint/__snapshots__/search_hint.test.tsx.snap
  components/search_hint/search_hint.tsx
  e2e/cypress/tests/integration/search/search_bar_popup_focus_spec.js
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#11196 MM-47080 : Migrate "components/suggestion/at_mention_provider/at_mention_suggestion.jsx" to Typescript
  components/suggestion/at_mention_provider/__snapshots__/at_mention_suggestion.test.tsx.snap
  components/suggestion/at_mention_provider/at_mention_provider.jsx
  components/suggestion/at_mention_provider/at_mention_provider.test.jsx
  components/suggestion/at_mention_provider/at_mention_suggestion.test.tsx
  components/suggestion/at_mention_provider/at_mention_suggestion.tsx
Labels: 4: Reviews Complete, release-note, Contributor

#11427 Fix missing field from master
  utils/test_helper.ts
Labels: 4: Reviews Complete, release-note-none

#11335 MM-47242 - improve tasklist items texts
  components/onboarding_tasks/onboarding_tasks_manager.tsx
  i18n/en.json
Labels: CherryPick/Approved, Setup Cloud Test Server, release-note-none, QA Deferred

#11429 Automated cherry pick of #11335
  components/onboarding_tasks/onboarding_tasks_manager.tsx
  i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#11286 MM-46528_Verify Invitation Flow Tracking Telemetry
  actions/telemetry_actions.jsx
  components/do_verify_email/do_verify_email.tsx
  components/invitation_modal/invitation_modal.test.tsx
  components/invitation_modal/invitation_modal.tsx
  components/invitation_modal/invite_view.test.tsx
  components/invitation_modal/invite_view.tsx
  components/should_verify_email/should_verify_email.tsx
  components/signup/signup.tsx
  utils/constants.tsx
  utils/utils.tsx
Labels: 1: PM Review, 2: Dev Review, Setup Cloud Test Server, release-note-none, QA Deferred

#11197 MM-47084 : Migrate "components/code_preview.jsx" to Typescript
  components/code_preview.tsx
  components/file_preview_modal/file_preview_modal.tsx
Labels: 4: Reviews Complete, release-note-none, Contributor

#11208 Mm 47088 : Migrate "components/integrations/installed_outgoing_webhook.jsx" to Typescript
  components/integrations/installed_outgoing_webhook.test.jsx
  components/integrations/installed_outgoing_webhook.tsx
  components/integrations/installed_outgoing_webhooks/installed_outgoing_webhooks.tsx
Labels: 4: Reviews Complete, release-note-none, Contributor

#11374 [MM-47615] Minor dependency upgrades for stripe dependencies
  package-lock.json
  package.json
Labels: 4: Reviews Complete, QA Review Done, Setup Cloud + CWS Test Server, release-note-none

#11331 MM-47443 : Removed gobal state from 'status_actions.ts'
  actions/status_actions.ts
Labels: 2: Dev Review, Hacktoberfest, 3: QA Review, Setup Cloud Test Server, hacktoberfest-accepted, release-note-none, Contributor

#11200 [MM-37712] Bubble DragEvent to drag and drop text into input/textarea
  components/file_upload/file_upload.tsx
  components/root/root.tsx
  utils/dragster.ts
  utils/utils.tsx
Labels: 4: Reviews Complete, release-note, Contributor

#11431 MM-74316 Update client and types packages to 7.4.0 (master)
  package-lock.json
  package.json
  packages/client/package.json
  packages/types/package.json
Labels: 4: Reviews Complete, release-note-none

#11234 MM-47066 : Migrate "components/suggestion/suggestion_date.jsx" to Typescript
  components/search_bar/search_bar.tsx
  components/suggestion/suggestion_date.tsx
Labels: 4: Reviews Complete, release-note-none, Contributor

#11267 MM-47190: Migrate utils/browser_history.jsx To Typescript
  components/channel_layout/channel_identifier_router/channel_identifier_router.test.tsx
  utils/browser_history.tsx
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted, release-note-none, Contributor

#11381 MM-47238 Add MM_BOARDS_DEV_SERVER_URL environment variable for MPA
  webpack.config.js
Labels: 4: Reviews Complete, release-note-none

#11399 Migrate "components/suggestion/menu_action_provider.jsx" to Typescript
  components/suggestion/generic_user_provider.tsx
  components/suggestion/menu_action_provider.tsx
Labels: 2: Dev Review, Hacktoberfest, hacktoberfest-accepted, release-note-none, QA Deferred, Contributor

#11214 MM-47067 : Migrate "components/suggestion/channel_mention_provider.jsx" to Typescript
  components/suggestion/channel_mention_provider.tsx
  components/textbox/textbox.tsx
Labels: 4: Reviews Complete, release-note-none, Contributor

#11421 MM-47107 : Migrate 'components/formatted_markdown_message.test.jsx' to Typescript
  components/__snapshots__/formatted_markdown_message.test.tsx.snap
  components/formatted_markdown_message.test.tsx
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted, release-note-none, QA Deferred, Contributor

#11172 MM-47097 : Migrate "components/message_with_additional_content.jsx" to Typescript
  components/message_with_additional_content.tsx
  components/rhs_comment/__snapshots__/rhs_comment.test.tsx.snap
  components/rhs_comment/rhs_comment.test.tsx
  components/rhs_comment/rhs_comment.tsx
  components/threading/virtualized_thread_viewer/reply/reply.tsx
Labels: 4: Reviews Complete, release-note-none, Contributor

#11319 MM-47109 : Migrate components/list_modal.jsx to Typescript
  components/channel_groups_manage_modal/channel_groups_manage_modal.tsx
  components/list_modal.tsx
  components/team_groups_manage_modal/team_groups_manage_modal.tsx
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted, release-note-none, Contributor

#11402 MM-47096 : Migrate "components/integrations/installed_incoming_webhook.jsx" to Typescript
  components/integrations/__snapshots__/installed_incoming_webhook.test.tsx.snap
  components/integrations/installed_incoming_webhook.test.tsx
  components/integrations/installed_incoming_webhook.tsx
  components/integrations/installed_incoming_webhooks/installed_incoming_webhooks.tsx
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted, release-note-none, QA Deferred, Contributor

#11432 MM-44114 : Announcing of channel interface language dropdown correctly (#11121)
  components/user_settings/display/__snapshots__/user_settings_display.test.tsx.snap
  components/user_settings/display/manage_languages/manage_languages.test.tsx
  components/user_settings/display/manage_languages/manage_languages.tsx
  i18n/en.json
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#11269 [MM-46933] Force profile popover to dismiss from avatars widget
  components/threading/channel_threads/thread_footer/__snapshots__/thread_footer.test.tsx.snap
  components/widgets/users/avatars/__snapshots__/avatars.test.tsx.snap
  components/widgets/users/avatars/avatars.tsx
Labels: 4: Reviews Complete, release-note-none
