Repository mattermost/mattermost-webapp, pull requests merged in 2022-06, with the labels that each got.

#10411 MM-44130: Changed email button text
  e2e/cypress/tests/integration/notifications/mention_email_notification_spec.js
  e2e/cypress/tests/utils/email.js
Labels: 4: Reviews Complete, release-note-none

#9404 [MM-38992] : Remove beta label from CRT user settings text and move settings up
  components/collapsed_reply_threads_beta_modal/collapsed_reply_threads_beta_modal.scss
  components/collapsed_reply_threads_beta_modal/collapsed_reply_threads_beta_modal.tsx
  components/collapsed_reply_threads_beta_modal/index.ts
  components/user_settings/display/__snapshots__/user_settings_display.test.tsx.snap
  components/user_settings/display/user_settings_display.tsx
  components/user_settings/modal/index.ts
  components/user_settings/modal/user_settings_modal.tsx
  e2e/cypress/tests/integration/channel/leave_channel_spec.js
  e2e/cypress/tests/support/ui/account_settings_modal.js
  i18n/en.json
  utils/constants.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#10373 MM-43323 : White screen when leaving channel in webapp, with unread filter is on.
  selectors/views/channel_sidebar.ts
Labels: 4: Reviews Complete, release-note

#10391 E2E/Cypress/fixed spec files
  e2e/cypress/tests/integration/channel_settings/add_users_to_channel_spec.js
  e2e/cypress/tests/integration/keyboard_shortcuts/up_arrow_edit_message_spec.js
  e2e/cypress/tests/integration/messaging/private_channel_open_spec.js
Labels: release-note-none

#10323 MM-44198: clarify playbook permissions text
  i18n/en.json
Labels: CherryPick/Approved, release-note-none, Editor review

#10366 [MM-20070] Added rule for focused SubMenuItem
  utils/utils.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none, Contributor

#10440 MM-44429 - open view plans modal
  components/widgets/menu/menu_items/menu_cloud_trial.tsx
Labels: 3: QA Review, Setup Cloud + CWS Test Server, release-note-none

#10405 Mm 43666 request bussiness email
  actions/cloud.tsx
  components/admin_console/data_retention_settings/custom_policy_form/__snapshots__/custom_policy_form.test.tsx.snap
  components/admin_console/data_retention_settings/custom_policy_form/custom_policy_form.tsx
  components/cloud_start_trial/__snapshots__/input_business_email.test.tsx.snap
  components/cloud_start_trial/__snapshots__/request_business_email_modal.test.tsx.snap
  components/cloud_start_trial/cloud_start_trial_btn.test.tsx
  components/cloud_start_trial/cloud_start_trial_btn.tsx
  components/cloud_start_trial/input_business_email.test.tsx
  components/cloud_start_trial/input_business_email.tsx
  components/cloud_start_trial/request_business_email_modal.scss
  components/cloud_start_trial/request_business_email_modal.test.tsx
  components/cloud_start_trial/request_business_email_modal.tsx
  components/create_user_groups_modal/__snapshots__/create_user_groups_modal.test.tsx.snap
  components/create_user_groups_modal/create_user_groups_modal.tsx
  components/learn_more_trial_modal/learn_more_trial_modal_step.tsx
  components/new_channel_modal/__snapshots__/new_channel_modal.test.tsx.snap
  components/new_channel_modal/new_channel_modal.tsx
  components/signup/__snapshots__/signup.test.tsx.snap
  components/signup/signup.tsx
  components/update_user_group_modal/__snapshots__/update_user_group_modal.test.tsx.snap
  components/update_user_group_modal/update_user_group_modal.tsx
  components/widgets/inputs/input/input.scss
  components/widgets/inputs/input/input.tsx
  components/widgets/inputs/password_input/password_input.tsx
  components/widgets/menu/menu_items/menu_cloud_trial.tsx
  i18n/en.json
  packages/client/src/client4.ts
  sass/base/_css_variables.scss
  utils/constants.tsx
Labels: 1: PM Review, release-note-none, QA Deferred

#10444 Automated cherry pick of #10438
  components/channel_info_rhs/index.ts
  e2e/cypress/tests/integration/channel/channel_info_rhs_spec.js
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#10417 [MM-44643] - Support the ability to link directly into the pricing modal
  components/admin_console/billing/billing_subscriptions/index.tsx
  components/purchase_modal/purchase_modal.tsx
Labels: QA Review Done, Setup Cloud + CWS Test Server, release-note-none

#10255 MM-40908 Go to threads view when switching a team if that was the last view
  actions/global_actions.tsx
  actions/views/channel.js
  components/channel_layout/center_channel/index.ts
  components/threading/global_threads/global_threads.tsx
  e2e/cypress/tests/integration/collapsed_reply_threads/last_viewed_spec.js
  e2e/cypress/tests/support/ui/sidebar_left.js
  selectors/local_storage.ts
  stores/local_storage_store.jsx
  utils/constants.tsx
Labels: Lifecycle/1:stale, Setup Cloud Test Server, QA Review Done, release-note-none, Contributor

#10447 Remove beta label from CRT user settings text and delete beta warning modal
  components/collapsed_reply_threads_beta_modal/collapsed_reply_threads_beta_modal.scss
  components/collapsed_reply_threads_beta_modal/collapsed_reply_threads_beta_modal.tsx
  components/collapsed_reply_threads_beta_modal/index.ts
  components/user_settings/display/__snapshots__/user_settings_display.test.tsx.snap
  components/user_settings/display/user_settings_display.tsx
  components/user_settings/modal/index.ts
  components/user_settings/modal/user_settings_modal.tsx
  e2e/cypress/tests/integration/channel/leave_channel_spec.js
  e2e/cypress/tests/support/ui/account_settings_modal.js
  i18n/en.json
  utils/constants.tsx
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note

#10449 Automated cherry pick of #10255
  actions/global_actions.tsx
  actions/views/channel.js
  components/channel_layout/center_channel/index.ts
  components/threading/global_threads/global_threads.tsx
  e2e/cypress/tests/integration/collapsed_reply_threads/last_viewed_spec.js
  e2e/cypress/tests/support/ui/sidebar_left.js
  selectors/local_storage.ts
  stores/local_storage_store.jsx
  utils/constants.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#10416 [MM-44649] - Add CTA to contact sales in the enterprise card on the pricing modal
  components/pricing_modal/contact_sales_cta.tsx
  components/pricing_modal/content.tsx
  components/pricing_modal/pricing_modal.scss
  e2e/cypress/tests/integration/enterprise/cloud/billing/pricing_modal_spec.js
  i18n/en.json
Labels: 2: Dev Review, QA Review Done, 1: UX Review, Setup Cloud + CWS Test Server, release-note-none

#10441 default to 0 storage used until real storage data is available
  actions/cloud.tsx
Labels: 2: Dev Review, QA Review Done, release-note-none

#10455 Remove cloud-starter-legacy; we do not need it
  components/admin_console/billing/billing_subscriptions/limits.test.tsx
  components/admin_console/billing/billing_subscriptions/limits.tsx
  components/admin_console/billing/plan_details/feature_list.tsx
  components/admin_console/billing/plan_details/plan_details.tsx
  utils/constants.tsx
  utils/limits.tsx
Labels: 2: Dev Review, Setup Cloud + CWS Test Server, release-note-none

#10445 MM-44650_Turn off Use Case Based Onboarding for Self-Managed while A/B Test runs on Cloud
  packages/mattermost-redux/src/selectors/entities/preferences.ts
Labels: QA Review Done, Setup Cloud + CWS Test Server, release-note-none

#10460 close request business email modal after trial success request
  components/cloud_start_trial/request_business_email_modal.tsx
Labels: release-note-none, QA Deferred

#10446 [MM-44422] Open Members RHS from Channel dropdown
  actions/views/rhs.ts
  components/channel_header_dropdown/__snapshots__/channel_header_dropdown.test.jsx.snap
  components/channel_header_dropdown/channel_header_dropdown_items.js
  components/channel_header_dropdown/menu_items/open_members_rhs/index.ts
  components/channel_header_dropdown/menu_items/open_members_rhs/open_members_rhs.tsx
  components/channel_members_rhs/channel_members_rhs.tsx
  components/channel_members_rhs/index.ts
  components/channel_members_rhs/member.tsx
  components/channel_members_rhs/member_list.tsx
  e2e/cypress/tests/integration/archived_channel/archive_channel_member_spec.js
  e2e/cypress/tests/integration/channel/channel_members_rhs_spec.js
  e2e/cypress/tests/integration/enterprise/guest_accounts/guest_identification_ui_spec.js
  e2e/cypress/tests/integration/enterprise/permissions/team_permissions_spec.js
  reducers/views/rhs.test.js
  reducers/views/rhs.ts
  selectors/rhs.ts
  types/store/rhs.ts
  utils/constants.tsx
Labels: 2: Dev Review, Setup Cloud Test Server, QA Review Done, AutoMerge, release-note-none

#10462 Automated cherry pick of #10446
  actions/views/rhs.ts
  components/channel_header_dropdown/__snapshots__/channel_header_dropdown.test.jsx.snap
  components/channel_header_dropdown/channel_header_dropdown_items.js
  components/channel_header_dropdown/menu_items/open_members_rhs/index.ts
  components/channel_header_dropdown/menu_items/open_members_rhs/open_members_rhs.tsx
  components/channel_members_rhs/channel_members_rhs.tsx
  components/channel_members_rhs/index.ts
  components/channel_members_rhs/member.tsx
  components/channel_members_rhs/member_list.tsx
  e2e/cypress/tests/integration/archived_channel/archive_channel_member_spec.js
  e2e/cypress/tests/integration/channel/channel_members_rhs_spec.js
  e2e/cypress/tests/integration/enterprise/guest_accounts/guest_identification_ui_spec.js
  e2e/cypress/tests/integration/enterprise/permissions/team_permissions_spec.js
  reducers/views/rhs.test.js
  reducers/views/rhs.ts
  selectors/rhs.ts
  types/store/rhs.ts
  utils/constants.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#10459 E2E/Cypress:test cases demoted
  e2e/cypress/tests/integration/emoji/custom_emoji_1_1_spec.js
  e2e/cypress/tests/integration/emoji/custom_emoji_1_spec.js
  e2e/cypress/tests/integration/emoji/custom_emoji_2_1_spec.js
  e2e/cypress/tests/integration/emoji/custom_emoji_2_spec.js
Labels: 4: Reviews Complete, release-note-none

#10463 Automated cherry pick of #10445
  packages/mattermost-redux/src/selectors/entities/preferences.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#10304 MM-35069: Eliminate loading indicator when you delete a post from permalink view
  components/post_view/post_list/index.js
Labels: 4: Reviews Complete, release-note, Contributor

#10392 [MM-44572] - Open limits modal from 'This plan has data restrictions' in pricing modal
  components/cloud_usage_modal/index.scss
  components/cloud_usage_modal/index.tsx
  components/cloud_usage_modal/limit_line.scss
  components/cloud_usage_modal/mini_modal.scss
  components/common/usage_percent_bar/index.tsx
  components/generic_modal.tsx
  components/pricing_modal/content.tsx
  components/pricing_modal/pricing_modal.scss
  components/pricing_modal/starter_disclaimer_cta.tsx
  e2e/cypress/tests/integration/enterprise/cloud/billing/pricing_modal_spec.js
  i18n/en.json
Labels: 2: Dev Review, QA Review Done, 1: UX Review, Setup Cloud + CWS Test Server, release-note-none

#10307 MM-36598 : Fix emoji search with emoji skin tone
  components/emoji_picker/utils/index.test.ts
  components/emoji_picker/utils/index.ts
Labels: 4: Reviews Complete, release-note-none, Contributor

#10412 [MM-43964] - Fix adding emoji reaction without opening RHS
  components/post_view/post_recent_reactions/recent_reactions_emoji_item.tsx
Labels: 4: Reviews Complete, release-note-none

#10456 MM-44746_Not Open Server error when signing up with email invite
  components/__snapshots__/alert_banner.test.tsx.snap
  components/alert_banner.tsx
  components/signup/signup.tsx
  e2e/cypress/tests/integration/team_settings/closed_team_invite_by_email_spec.js
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, QA Review Done, release-note-none

#10472 MM-44746_Not Open Server error when signing up with email invite (#10…
  components/signup/signup.tsx
  e2e/cypress/tests/integration/team_settings/closed_team_invite_by_email_spec.js
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#10468 Mm 43665 - modify the learn more trial modal
  components/common/carousel/carousel.scss
  components/common/carousel/carousel.test.tsx
  components/common/carousel/carousel.tsx
  components/common/carousel/carousel_button.tsx
  components/common/svg_images_components/monitor_imaclike_svg.tsx
  components/learn_more_trial_modal/learn_more_trial_modal.scss
  components/learn_more_trial_modal/learn_more_trial_modal.test.tsx
  components/learn_more_trial_modal/learn_more_trial_modal.tsx
  components/learn_more_trial_modal/learn_more_trial_modal_step.test.tsx
  components/learn_more_trial_modal/learn_more_trial_modal_step.tsx
  components/trial_benefits_modal/trial_benefits_modal_step_more.tsx
  i18n/en.json
Labels: QA Review Done, Setup Cloud + CWS Test Server, release-note-none

#10475 E2E/Cypress:fixed cloud test cases
  e2e/cypress/tests/integration/auth_sso/authentication_4_spec.js
  e2e/cypress/tests/integration/system_console/main_menu_spec.js
  e2e/cypress/tests/integration/system_console/site_configuration/link_customization_cloud_spec.js
  e2e/cypress/tests/utils/admin_console.js
Labels: 4: Reviews Complete, release-note-none

#10476 removed cloud_restrictable config
  e2e/cypress/tests/integration/markdown/markdown_image_spec.js
  e2e/cypress/tests/integration/markdown/markdown_text_spec.js
  e2e/cypress/tests/support/api/cloud_default_config.json
Labels: 4: Reviews Complete, release-note-none

#10484 [MM-44701] Adjust trial end check in banner to June 15
  components/announcement_bar/cloud_trial_ended_announcement_bar/index.tsx
Labels: 2: Dev Review, release-note-none

#10322 MM-44334: export styled components
  plugins/export.js
Labels: 4: Reviews Complete, release-note-none

#10474 [MM-44793] fixes: Mobile browser Advanced text editor formatting icon size issue
  components/advanced_text_editor/formatting_bar/formatting_icon.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#10487 Automated cherry pick of #10474
  components/advanced_text_editor/formatting_bar/formatting_icon.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#10451 [MM-44761] Replace occurrences of 'Subscribe Now' with 'Upgrade Now'
  components/admin_console/billing/billing_subscriptions/index.tsx
  components/admin_console/billing/billing_summary/billing_summary.tsx
  components/admin_console/feature_discovery/feature_discovery.tsx
  components/announcement_bar/cloud_trial_announcement_bar/cloud_trial_announcement_bar.tsx
  components/pricing_modal/content.tsx
  i18n/en.json
Labels: 4: Reviews Complete, Setup Cloud + CWS Test Server, release-note-none

#10458 show contact sales card when not on a limited plan.
  components/admin_console/admin_definition.jsx
  components/admin_console/billing/billing_subscriptions/index.tsx
  components/admin_console/billing/billing_summary/index.tsx
  components/admin_console/billing/billing_summary/upsell_card.tsx
  components/admin_console/billing/plan_details/index.tsx
  components/admin_console/billing/plan_details/plan_pricing.tsx
  components/common/hooks/useOpenSalesLink.ts
  components/pricing_modal/content.tsx
  components/purchase_modal/index.ts
  i18n/en.json
  packages/client/src/client4.ts
  packages/mattermost-redux/src/reducers/entities/cloud.test.ts
  packages/mattermost-redux/src/reducers/entities/cloud.ts
  packages/types/src/cloud.ts
  selectors/cloud.ts
  utils/cloud_utils.ts
Labels: 4: Reviews Complete, QA Review Done, Setup Cloud + CWS Test Server, release-note-none

#10490 Automated cherry pick of #10458
  components/admin_console/admin_definition.jsx
  components/admin_console/billing/billing_subscriptions/index.tsx
  components/admin_console/billing/billing_summary/index.tsx
  components/admin_console/billing/billing_summary/upsell_card.tsx
  components/admin_console/billing/plan_details/index.tsx
  components/admin_console/billing/plan_details/plan_pricing.tsx
  components/common/hooks/useOpenSalesLink.ts
  components/pricing_modal/content.tsx
  components/purchase_modal/index.ts
  i18n/en.json
  packages/client/src/client4.ts
  packages/mattermost-redux/src/reducers/entities/cloud.test.ts
  packages/mattermost-redux/src/reducers/entities/cloud.ts
  packages/types/src/cloud.ts
  selectors/cloud.ts
  utils/cloud_utils.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#10363 [MM-44073] Add loop for all team channel members api (Max 600 items)
  packages/client/src/client4.ts
  packages/mattermost-redux/src/actions/channels.ts
Labels: CherryPick/Approved, Setup Cloud Test Server, QA Review Done, release-note

#10498 Automated cherry pick of #10363
  packages/client/src/client4.ts
  packages/mattermost-redux/src/actions/channels.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#10493 Automated cherry pick of #10363
  packages/client/src/client4.ts
  packages/mattermost-redux/src/actions/channels.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#10454 MM-44685: Render app bar icons on top of RHS background
  components/app_bar/app_bar.scss
  sass/layout/_sidebar-right.scss
Labels: 4: Reviews Complete, CherryPick/Approved, AutoMerge, release-note-none

#10499 Automated cherry pick of #10454
  components/app_bar/app_bar.scss
  sass/layout/_sidebar-right.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#10501 Automated cherry pick of #10492
  components/header_footer_route/header_footer_route.tsx
  components/login/login.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#10502 Automated cherry pick of #10492
  components/header_footer_route/header_footer_route.tsx
  components/login/login.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#10471 MM44687: Add divider between the core products and the rest of icons
  components/app_bar/__snapshots__/app_bar.test.tsx.snap
  components/app_bar/app_bar.scss
  components/app_bar/app_bar.tsx
Labels: 3: QA Review, CherryPick/Approved, Setup Cloud Test Server, release-note-none

#10507 Automated cherry pick of #10471
  components/app_bar/__snapshots__/app_bar.test.tsx.snap
  components/app_bar/app_bar.scss
  components/app_bar/app_bar.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#10479 MM-44602 - fix flakyness showing onboarding trial
  components/cloud_start_trial/request_business_email_modal.tsx
  components/onboarding_tasklist/onboarding_tasklist.tsx
  components/root/index.js
  components/root/root.jsx
Labels: 2: Dev Review, Setup Cloud Test Server, QA Review Done, release-note-none

#10510 Automated cherry pick of #10479
  components/cloud_start_trial/request_business_email_modal.tsx
  components/onboarding_tasklist/onboarding_tasklist.tsx
  components/root/index.js
  components/root/root.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#10467 MM-44686: Fix squared outline using box-shadow
  components/app_bar/app_bar.scss
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, QA Review Done, AutoMerge, release-note-none

#10515 Automated cherry pick of #10467
  components/app_bar/app_bar.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#10514 Automated cherry pick of #10467
  components/app_bar/app_bar.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#10466 [MM-44438]: fix Advanced Text editor Padding issue in RHS and Thread view
  components/advanced_text_editor/advanced_text_editor.scss
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#10517 Automated cherry pick of #10466
  components/advanced_text_editor/advanced_text_editor.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#10516 Automated cherry pick of #10466
  components/advanced_text_editor/advanced_text_editor.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#10486 Create configuration folder for notice.txt generation
  build/notice-file/README.md
  build/notice-file/config.yaml
Labels: release-note-none, kind/chore

#10495 [MM-44896] Advanced Text Editor Don't show the preview button if the input is empty
  components/advanced_text_editor/advanced_text_editor.tsx
Labels: CherryPick/Approved, Setup Cloud Test Server, release-note, QA Deferred

#10497 [MM-44898] Hide Markdown settings from pre release preview settings in user settings modal ( Advanced settings)
  components/advanced_create_comment/advanced_create_comment.tsx
  components/advanced_create_comment/index.ts
  components/advanced_create_post/advanced_create_post.tsx
  components/advanced_create_post/index.ts
  components/edit_channel_header_modal/index.ts
  components/user_settings/advanced/user_settings_advanced.jsx
Labels: 4: Reviews Complete, CherryPick/Approved, release-note, QA Deferred

#10525 [MM-44898] Hide Markdown settings from pre-release preview settings in the user settings modal (Advanced settings)
  components/advanced_create_comment/advanced_create_comment.tsx
  components/advanced_create_comment/index.ts
  components/advanced_create_post/advanced_create_post.tsx
  components/advanced_create_post/index.ts
  components/edit_channel_header_modal/index.ts
  components/user_settings/advanced/user_settings_advanced.jsx
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note

#10526 Automated cherry pick of #10497
  components/advanced_create_comment/advanced_create_comment.tsx
  components/advanced_create_comment/index.ts
  components/advanced_create_post/advanced_create_post.tsx
  components/advanced_create_post/index.ts
  components/edit_channel_header_modal/index.ts
  components/user_settings/advanced/user_settings_advanced.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#10527 Automated cherry pick of #10495
  components/advanced_text_editor/advanced_text_editor.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#10522 Automated cherry pick of #10503
  components/file_upload/file_upload.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#10489 MM-44100 Always open internal help pages in a new tab
  utils/url.tsx
Labels: 4: Reviews Complete, release-note, QA Deferred

#9691 MM-39510 : Quick reactions in the hover menu and emoji picker should be based on most frequently used emoji instead of recently used
  actions/emoji_actions.js
  actions/emoji_actions.mock.test.js
  actions/emoji_actions.test.js
  components/emoji_picker/index.ts
  components/root/index.js
  components/root/root.jsx
  components/root/root.test.jsx
  components/suggestion/emoticon_provider.jsx
  components/suggestion/emoticon_provider.test.jsx
  e2e/cypress/tests/integration/accessibility/accessibility_post_spec.js
  e2e/cypress/tests/support/ui_commands.js
  packages/mattermost-redux/src/actions/emojis.ts
  packages/mattermost-redux/src/constants/preferences.ts
  packages/types/src/emojis.ts
  selectors/emojis.test.js
  selectors/emojis.ts
  stores/local_storage_store.jsx
  stores/local_storage_store.test.jsx
  utils/constants.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, QA Review Done, release-note, Contributor

#10513 Downgrade Romanian translations to Beta
  components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
  i18n/i18n.jsx
Labels: 4: Reviews Complete, Docs/Not Needed, CherryPick/Approved, AutoMerge, release-note

#10533 Automated cherry pick of #10513
  components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
  i18n/i18n.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#10496 [MM-44648] - Card input not visible in darker modes
  components/admin_console/billing/payment_info_edit.tsx
  components/payment_form/card_input.tsx
  components/payment_form/payment_form.scss
  components/payment_form/payment_form.tsx
  components/pricing_modal/content.tsx
  components/purchase_modal/index.ts
  components/purchase_modal/purchase.scss
  components/purchase_modal/purchase_modal.tsx
  i18n/en.json
  utils/utils.tsx
Labels: 2: Dev Review, QA Review Done, Setup Cloud + CWS Test Server, release-note-none

#10494 [MM-42629] Show Unfollow button in dot menu of root post if the post has mentions
  components/dot_menu/dot_menu.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#10537 Automated cherry pick of #10494
  components/dot_menu/dot_menu.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#10465 [MM-44451]: Move the TAF and CRT config settings out of the experimental section of the system console.
  components/admin_console/admin_definition.jsx
  i18n/en.json
Labels: 4: Reviews Complete, Docs/Needed, CherryPick/Approved, release-note

#10539 Automated cherry pick of #10465
  components/admin_console/admin_definition.jsx
  i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#10536 Automated cherry pick of #10494
  components/dot_menu/dot_menu.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#10538 Automated cherry pick of #10465
  components/admin_console/admin_definition.jsx
  i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#10488 MM-20350 Add search shortcut to the 'Keyboard Shortcuts' modal
  components/keyboard_shortcuts/keyboard_shortcuts_modal/__snapshots__/keyboard_shortcuts_modal.test.tsx.snap
  components/keyboard_shortcuts/keyboard_shortcuts_modal/keyboard_shortcuts_modal.tsx
  components/keyboard_shortcuts/keyboard_shortcuts_sequence/keyboard_shortcuts.ts
  i18n/en.json
Labels: 4: Reviews Complete, release-note, QA Deferred, Contributor

#10531 [MM-44933] Advanced Text Editor: fixes forced refresh on message submit via button if message have special mentions all, channel etc
  components/advanced_text_editor/send_button/send_button.tsx
Labels: 2: Dev Review, Setup Cloud Test Server, release-note, QA Deferred

#10512 remove unused code around unimplemented ExperimentalSettings.EnableCl…
  e2e/cypress/tests/support/api/on_prem_default_config.json
  e2e/playwright/support/server/default_config.ts
  packages/types/src/config.ts
Labels: 4: Reviews Complete, release-note-none, Contributor

#9914 MM-41565: fixes bug in delete post crt
  actions/websocket_actions.jsx
  packages/mattermost-redux/src/actions/threads.ts
Labels: Setup Cloud Test Server, release-note-none, QA Deferred

#10511 MM-44883_Update the Create Team in trial tooltip text
  components/main_menu/__snapshots__/main_menu.test.tsx.snap
  components/main_menu/main_menu.tsx
  i18n/en.json
Labels: CherryPick/Approved, QA Review Done, Setup Cloud + CWS Test Server, release-note-none

#10506 MM-44634_When login credentials are auto-filled, log in button shows as disabled on hover
  components/login/__snapshots__/login.test.tsx.snap
  components/login/login.tsx
  e2e/cypress/tests/integration/signin_authentication/login_spec.js
  e2e/cypress/tests/support/common_login_commands.js
Labels: CherryPick/Approved, Setup Cloud Test Server, QA Review Done, release-note

#10551 Automated cherry pick of #10506
  components/login/__snapshots__/login.test.tsx.snap
  components/login/login.tsx
  e2e/cypress/tests/integration/signin_authentication/login_spec.js
  e2e/cypress/tests/support/common_login_commands.js
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#10550 Automated cherry pick of #10511
  components/main_menu/__snapshots__/main_menu.test.tsx.snap
  components/main_menu/main_menu.tsx
  i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#10549 Automated cherry pick of #10531
  components/advanced_text_editor/send_button/send_button.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#10521 MM-42581: desktop notification when user added to channel
  actions/notification_actions.jsx
  actions/notification_actions.test.js
  packages/mattermost-redux/src/utils/post_utils.ts
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, CherryPick/Approved, AutoMerge, release-note-none

#10545 Automated cherry pick of #10506
  components/login/__snapshots__/login.test.tsx.snap
  components/login/login.tsx
  e2e/cypress/tests/integration/signin_authentication/login_spec.js
  e2e/cypress/tests/support/common_login_commands.js
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#10553 Automated cherry pick of #10521
  actions/notification_actions.jsx
  actions/notification_actions.test.js
  packages/mattermost-redux/src/utils/post_utils.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#10555 Automated cherry pick of #10464
  components/advanced_create_comment/advanced_create_comment.tsx
  components/advanced_create_post/advanced_create_post.tsx
  components/keyboard_shortcuts/keyboard_shortcuts_sequence/keyboard_shortcuts.ts
  components/keyboard_shortcuts/keyboard_shortcuts_sequence/keyboard_shortcuts_sequence.tsx
  i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#10557 Automated cherry pick of #10480
  components/suggestion/suggestion_box/suggestion_box.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#10530 add file storage usage
  actions/cloud.tsx
  packages/client/src/client4.ts
  packages/types/src/posts.ts
  utils/limits.tsx
Labels: CherryPick/Approved, Setup Cloud + CWS Test Server, release-note-none, QA Deferred

#10296 MM-29029 : Remove findDOMNode from FileUpload component
  components/advanced_create_comment/advanced_create_comment.tsx
  components/advanced_create_post/advanced_create_post.tsx
  components/create_comment/create_comment.tsx
  components/create_post/create_post.tsx
  components/file_upload/file_upload.jsx
Labels: 4: Reviews Complete, release-note-none, Contributor

#10552 Automated cherry pick of #10521
  actions/notification_actions.jsx
  actions/notification_actions.test.js
  packages/mattermost-redux/src/utils/post_utils.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#10558 Automated cherry pick of #10530
  actions/cloud.tsx
  packages/client/src/client4.ts
  packages/types/src/posts.ts
  utils/limits.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#10554 Automated cherry pick of #10464
  components/advanced_create_comment/advanced_create_comment.tsx
  components/advanced_create_post/advanced_create_post.tsx
  components/keyboard_shortcuts/keyboard_shortcuts_sequence/keyboard_shortcuts.ts
  components/keyboard_shortcuts/keyboard_shortcuts_sequence/keyboard_shortcuts_sequence.tsx
  i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#10556 Automated cherry pick of #10480
  components/suggestion/suggestion_box/suggestion_box.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#10491 Mm 43603 Subscription limit reached upgrade banner
  components/admin_console/billing/billing_subscriptions/billing_subscriptions.tsx
  components/admin_console/billing/billing_subscriptions/index.tsx
  components/admin_console/billing/billing_subscriptions/limit_reached_banner.scss
  components/admin_console/billing/billing_subscriptions/limit_reached_banner.test.tsx
  components/admin_console/billing/billing_subscriptions/limit_reached_banner.tsx
  components/alert_banner.tsx
  components/common/hooks/useSavePreferences.ts
  i18n/en.json
  packages/mattermost-redux/src/constants/preferences.ts
  packages/mattermost-redux/src/selectors/entities/preferences.ts
Labels: 2: Dev Review, QA Review Done, Setup Cloud + CWS Test Server, release-note-none

#10469 [MM-44531] - Updates to buttons in final confirmation step after purchase
  components/purchase_modal/icon_message.scss
  components/purchase_modal/icon_message.tsx
  components/purchase_modal/index.ts
  components/purchase_modal/process_payment_setup.tsx
  components/purchase_modal/purchase_modal.tsx
  i18n/en.json
Labels: CherryPick/Approved, QA Review Done, Setup Cloud + CWS Test Server, release-note-none

#10565 Automated cherry pick of #10469
  components/purchase_modal/icon_message.scss
  components/purchase_modal/icon_message.tsx
  components/purchase_modal/index.ts
  components/purchase_modal/process_payment_setup.tsx
  components/purchase_modal/purchase_modal.tsx
  i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#10574 consistent fallback limit usage
  components/cloud_usage_modal/lhs_nearing_limit_modal.tsx
  components/pricing_modal/content.tsx
  components/pricing_modal/starter_disclaimer_cta.tsx
  e2e/cypress/tests/integration/enterprise/cloud/billing/pricing_modal_spec.js
  i18n/en.json
  utils/limits.tsx
Labels: CherryPick/Approved, QA Review Done, Setup Cloud + CWS Test Server, release-note-none

#10583 Automated cherry pick of #10574
  components/cloud_usage_modal/lhs_nearing_limit_modal.tsx
  components/pricing_modal/content.tsx
  components/pricing_modal/starter_disclaimer_cta.tsx
  e2e/cypress/tests/integration/enterprise/cloud/billing/pricing_modal_spec.js
  i18n/en.json
  utils/limits.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#10585 Translations update from Mattermost Weblate
  i18n/bg.json
  i18n/de.json
  i18n/en_AU.json
  i18n/es.json
  i18n/fa.json
  i18n/fr.json
  i18n/hu.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
  i18n/zh-CN.json
Labels: release-note-none, Do Not Merge/Mattermod

#10253 [MM-41881]: update link preview UI
  components/common/auto_height_switcher.tsx
  components/post_view/post_attachment_opengraph/__snapshots__/post_attachment_opengraph.test.tsx.snap
  components/post_view/post_attachment_opengraph/index.ts
  components/post_view/post_attachment_opengraph/post_attachment_opengraph.scss
  components/post_view/post_attachment_opengraph/post_attachment_opengraph.test.tsx
  components/post_view/post_attachment_opengraph/post_attachment_opengraph.tsx
  e2e/cypress/tests/integration/messaging/collapse_link_spec.js
  i18n/en.json
  packages/types/src/posts.ts
  sass/components/_post.scss
  sass/layout/_webhooks.scss
Labels: 4: Reviews Complete, QA Review Done, release-note

#10566 Fix category modal on mobile web view
  sass/responsive/_mobile.scss
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none, QA Deferred

#10567 Fix markdown image collapsed preview
  components/markdown_image_expand/markdown_image_expand.scss
Labels: 3: QA Review, Setup Cloud Test Server, release-note-none, QA Deferred

#10573 Show desktop app download prompt on first visit to a new server
  components/linking_landing_page/linking_landing_page.tsx
  components/root/root.jsx
Labels: 3: QA Review, release-note-none, QA Deferred

#10590 Revert "Show desktop app download prompt on first visit to a new server"
  components/linking_landing_page/linking_landing_page.tsx
  components/root/root.jsx
Labels: release-note-none

#10561 MM-44849 - feature discovery pages show start trial button after trial completed
  components/admin_console/feature_discovery/feature_discovery.tsx
  components/admin_console/feature_discovery/index.tsx
Labels: 2: Dev Review, QA Review Done, Setup Cloud + CWS Test Server, release-note-none

#10562 MM-44906 - add back playbooks and boards to task list when no using o…
  components/onboarding_tasks/onboarding_tasks_manager.tsx
Labels: 2: Dev Review, QA Review Done, Setup Cloud + CWS Test Server, release-note-none

#10587 Fix redirect_to dropping query parameters
  components/logged_in/logged_in.test.tsx
  components/logged_in/logged_in.tsx
Labels: 2: Dev Review, Setup Cloud + CWS Test Server, release-note-none

#10473 [MM-44657] Insights responsive
  components/activity_and_insights/activity_and_insights.scss
  components/activity_and_insights/insights/card/card.scss
  components/activity_and_insights/insights/insights_header/insights_header.scss
  sass/responsive/_desktop.scss
Labels: 3: QA Review, Setup Cloud Test Server, release-note-none

#10576 MM-44973_Add prompt to start trial in Custom Groups menu entry
  components/feature_restricted_modal/feature_restricted_modal.scss
  components/feature_restricted_modal/feature_restricted_modal.test.tsx
  components/feature_restricted_modal/feature_restricted_modal.tsx
  components/global_header/left_controls/product_menu/product_menu_list/__snapshots__/product_menu_list.test.tsx.snap
  components/global_header/left_controls/product_menu/product_menu_list/index.ts
  components/global_header/left_controls/product_menu/product_menu_list/product_menu_list.test.tsx
  components/global_header/left_controls/product_menu/product_menu_list/product_menu_list.tsx
  components/main_menu/__snapshots__/main_menu.test.tsx.snap
  components/main_menu/index.tsx
  components/main_menu/main_menu.test.tsx
  components/main_menu/main_menu.tsx
  components/widgets/menu/menu_items/menu_item.scss
  components/widgets/menu/menu_items/menu_item_link.tsx
  components/widgets/menu/menu_items/menu_item_toggle_modal_redux.tsx
  components/widgets/menu/menu_items/restricted_indicator.scss
  components/widgets/menu/menu_items/restricted_indicator.tsx
  i18n/en.json
  plugins/test/main_menu_action.test.jsx
  utils/constants.tsx
Labels: 2: Dev Review, QA Review Done, 1: UX Review, Setup Cloud + CWS Test Server, release-note-none

#10591 MM-45067: Reorder core products in the App Bar
  components/app_bar/app_bar.tsx
Labels: 4: Reviews Complete, release-note-none

#10367 [MM-44156] Channel ordering is different between web and mobile
  packages/mattermost-redux/src/selectors/entities/channel_categories.test.js
  packages/mattermost-redux/src/selectors/entities/channel_categories.ts
Labels: 4: Reviews Complete, release-note, Contributor

#10426 MM-34366: Migrate 'components/post_view/post_list_virtualized' and associated tests to TypeScript
  components/post_view/floating_timestamp/floating_timestamp.tsx
  components/post_view/floating_timestamp/index.ts
  components/post_view/post_list_row/index.ts
  components/post_view/post_list_row/post_list_row.tsx
  components/post_view/post_list_virtualized/latest_post_reader.test.tsx
  components/post_view/post_list_virtualized/post_list_virtualized.test.tsx
  components/post_view/post_list_virtualized/post_list_virtualized.tsx
  types/external/dynamic-virtualized-list.d.ts
Labels: 4: Reviews Complete, release-note-none, Contributor

#10267 MM-30230 : Fix scroll to caret when returning to post draft
  components/create_post/create_post.test.jsx
  components/textbox/textbox.tsx
  utils/utils.tsx
Labels: 4: Reviews Complete, release-note-none, Contributor

#10433 MM-44513: Non-square custom emoji overflow div when set as status
  components/emoji/render_emoji.tsx
Labels: 4: Reviews Complete, release-note-none, Contributor

#10571 Update test case id for file_upload_in_center_channel_spec.js
  e2e/cypress/tests/integration/messaging/file_upload_in_center_channel_spec.js
Labels: release-note-none

#10435 MM-43166 : Upgrade dependencies for Webapp (April 2022)
  package-lock.json
  package.json
Labels: 4: Reviews Complete, release-note

#10470 [MM-44657] Top boards for insights
  components/activity_and_insights/activity_and_insights.scss
  components/activity_and_insights/insights/insights.tsx
  components/activity_and_insights/insights/insights_modal/insights_modal.scss
  components/activity_and_insights/insights/insights_modal/insights_modal.tsx
  components/activity_and_insights/insights/top_boards/top_boards.test.tsx
  components/activity_and_insights/insights/top_boards/top_boards.tsx
  components/activity_and_insights/insights/top_boards/top_boards_table/top_boards_table.test.tsx
  components/activity_and_insights/insights/top_boards/top_boards_table/top_boards_table.tsx
  i18n/en.json
  packages/types/src/insights.ts
  plugins/registry.js
  reducers/plugins/index.ts
  types/store/plugins.ts
  utils/constants.tsx
Labels: release-note

#10598 [MM-44923] - Fix theming issues when in subscriptions under the admin console
  components/admin_console/billing/billing_summary/upsell_card.scss
  components/cloud_usage_modal/index.scss
Labels: 2: Dev Review, Setup Cloud + CWS Test Server, release-note-none

#10596 MM-45019_End user, post-trial: Create team restricted modal shows incorrect title/description
  components/feature_restricted_modal/feature_restricted_modal.test.tsx
  components/feature_restricted_modal/feature_restricted_modal.tsx
  components/generic_modal.scss
  components/global_header/left_controls/product_menu/product_menu_list/__snapshots__/product_menu_list.test.tsx.snap
  components/global_header/left_controls/product_menu/product_menu_list/product_menu_list.tsx
  components/main_menu/__snapshots__/main_menu.test.tsx.snap
  components/main_menu/main_menu.tsx
  components/widgets/menu/menu_items/restricted_indicator.tsx
  i18n/en.json
Labels: 2: Dev Review, QA Review Done, Setup Cloud + CWS Test Server, release-note-none

#10604 Automated cherry pick of #10596
  components/feature_restricted_modal/feature_restricted_modal.test.tsx
  components/feature_restricted_modal/feature_restricted_modal.tsx
  components/generic_modal.scss
  components/global_header/left_controls/product_menu/product_menu_list/__snapshots__/product_menu_list.test.tsx.snap
  components/global_header/left_controls/product_menu/product_menu_list/product_menu_list.tsx
  components/main_menu/__snapshots__/main_menu.test.tsx.snap
  components/main_menu/main_menu.tsx
  components/widgets/menu/menu_items/restricted_indicator.tsx
  i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#10169 MM-43079 : Remove superagent library
  NOTICE.txt
  actions/file_actions.jsx
  actions/file_actions.ts
  components/file_upload/file_upload.jsx
  components/file_upload/file_upload.test.jsx
  components/file_upload/index.js
  package-lock.json
  package.json
  webpack.config.js
Labels: 4: Reviews Complete, release-note

#10584 MM-44642: Hide insights if not Professional or Enterprise SKU or if guest
  packages/mattermost-redux/src/selectors/entities/preferences.ts
  packages/types/src/config.ts
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none

#10529 [M44917]: fixed misalignment of ... menu
  components/advanced_text_editor/formatting_bar/formatting_bar.tsx
  components/advanced_text_editor/formatting_bar/hooks.tsx
  package-lock.json
  package.json
Labels: 4: Reviews Complete, release-note-none, kind/bug

#10570 [MM-44887] Consistency in dates between the various payment modals
  components/purchase_modal/purchase_modal.tsx
  i18n/en.json
Labels: release-note-none

#10594 [MM-44772] Adjust copy for grandfather banner based on subscription payment status
  components/admin_console/billing/billing_subscriptions/billing_subscriptions.tsx
  i18n/en.json
Labels: 4: Reviews Complete, QA Review Done, Setup Cloud + CWS Test Server, release-note-none

#10564 Fixing a typo in translation from 0365 to O365
  components/learn_more_trial_modal/learn_more_trial_modal.tsx
  i18n/en.json
Labels: 4: Reviews Complete, release-note-none, Contributor

#10605 Automated cherry pick of #10570
  components/purchase_modal/purchase_modal.tsx
  i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#10603 MM-44131 Add debug logging for DynamicSizedList and for post-related websocket events
  actions/websocket_actions.jsx
  package-lock.json
  package.json
Labels: 4: Reviews Complete, release-note-none

#10601 Mm 45059
  actions/websocket_actions.jsx
  actions/websocket_actions.test.jsx
  components/admin_console/billing/billing_subscriptions/index.tsx
  components/admin_console/billing/billing_subscriptions/limit_reached_banner.test.tsx
  components/admin_console/billing/billing_subscriptions/limits.test.tsx
  components/admin_console/billing/billing_subscriptions/limits.tsx
  components/admin_console/billing/billing_summary/index.tsx
  components/admin_console/billing/plan_details/feature_list.test.tsx
  components/admin_console/billing/plan_details/index.tsx
  components/admin_console/billing/plan_details/plan_pricing.tsx
  components/admin_console/feature_discovery/feature_discovery.test.tsx
  components/admin_console/feature_discovery/feature_discovery.tsx
  components/admin_console/feature_discovery/index.tsx
  components/admin_console/team_channel_settings/team/details/team_profile.test.tsx
  components/announcement_bar/cloud_trial_announcement_bar/index.ts
  components/announcement_bar/cloud_trial_ended_announcement_bar/cloud_trial_ended_announcement_bar.test.tsx
  components/announcement_bar/payment_announcement_bar/index.ts
  components/cloud_usage_modal/index.test.tsx
  components/common/hooks/useGetLimits.ts
  components/common/hooks/useGetUsage.ts
  components/global_header/left_controls/product_menu/product_menu_list/__snapshots__/product_menu_list.test.tsx.snap
  components/global_header/left_controls/product_menu/product_menu_list/product_menu_list.test.tsx
  components/global_header/right_controls/cloud_upgrade_button/cloud_upgrade_button.test.tsx
  components/global_header/right_controls/cloud_upgrade_button/index.tsx
  components/learn_more_trial_modal/__snapshots__/learn_more_trial_modal_step.test.tsx.snap
  components/learn_more_trial_modal/learn_more_trial_modal.test.tsx
  components/learn_more_trial_modal/learn_more_trial_modal.tsx
  components/learn_more_trial_modal/learn_more_trial_modal_step.test.tsx
  components/main_menu/main_menu.test.tsx
  components/onboarding_tasklist/onboarding_tasklist_completed.tsx
  components/onboarding_tasks/onboarding_tasks_manager.tsx
  components/select_team/select_team.test.tsx
  components/sidebar/sidebar_header/sidebar_header.test.tsx
  components/widgets/menu/menu_items/menu_cloud_trial.test.tsx
  components/widgets/menu/menu_items/menu_cloud_trial.tsx
  e2e/cypress/tests/integration/enterprise/cloud/billing/pricing_modal_spec.js
  i18n/en.json
  packages/mattermost-redux/src/selectors/entities/preferences.ts
  plugins/test/main_menu_action.test.jsx
Labels: 2: Dev Review, Setup Cloud + CWS Test Server, release-note, QA Deferred

#10356 [MM-44429] Top threads widget
  components/activity_and_insights/activity_and_insights.scss
  components/activity_and_insights/insights/card/card.scss
  components/activity_and_insights/insights/insights.tsx
  components/activity_and_insights/insights/insights_modal/insights_modal.scss
  components/activity_and_insights/insights/insights_modal/insights_modal.tsx
  components/activity_and_insights/insights/top_threads/top_threads.scss
  components/activity_and_insights/insights/top_threads/top_threads.test.tsx
  components/activity_and_insights/insights/top_threads/top_threads.tsx
  components/activity_and_insights/insights/top_threads/top_threads_table/top_threads_table.test.tsx
  components/activity_and_insights/insights/top_threads/top_threads_table/top_threads_table.tsx
  components/threading/channel_threads/thread_footer/__snapshots__/thread_footer.test.tsx.snap
  components/widgets/users/avatars/__snapshots__/avatars.test.tsx.snap
  components/widgets/users/avatars/avatars.tsx
  i18n/en.json
  packages/client/src/client4.ts
  packages/mattermost-redux/src/action_types/insights.ts
  packages/mattermost-redux/src/actions/insights.ts
  packages/mattermost-redux/src/reducers/entities/files.ts
  packages/mattermost-redux/src/reducers/entities/posts.ts
  packages/types/src/insights.ts
  utils/constants.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none

#10595 MM-45113 - fix product limits banner in subscription page
  components/admin_console/billing/billing_subscriptions/index.tsx
Labels: QA Review Done, Setup Cloud + CWS Test Server, release-note-none

#10568 MM-44845 - inform user license changes are taking place
  components/admin_console/feature_discovery/__snapshots__/feature_discovery.test.tsx.snap
  components/admin_console/feature_discovery/feature_discovery.test.tsx
  components/admin_console/feature_discovery/feature_discovery.tsx
  components/admin_console/feature_discovery/index.tsx
  components/trial_benefits_modal/trial_benefits_modal.test.tsx
  components/trial_benefits_modal/trial_benefits_modal.tsx
  components/trial_benefits_modal/trial_benefits_modal_step.tsx
  i18n/en.json
Labels: 2: Dev Review, QA Review Done, 1: UX Review, Setup Cloud + CWS Test Server, release-note-none

#10599 MM-44735_Freemium: Restrict create team from mobile view menu
  components/create_team/__snapshots__/create_team.test.tsx.snap
  components/create_team/create_team.test.tsx
  components/create_team/create_team.tsx
  components/create_team/index.js
  components/main_menu/main_menu.tsx
  components/select_team/index.ts
  components/select_team/select_team.test.tsx
  components/select_team/select_team.tsx
  i18n/en.json
Labels: 2: Dev Review, QA Review Done, Setup Cloud + CWS Test Server, release-note-none

#10606 Handle image metadata being undefined in posts with opengraph attachments
  components/post_view/post_attachment_opengraph/post_attachment_opengraph.test.tsx
  components/post_view/post_attachment_opengraph/post_attachment_opengraph.tsx
Labels: 4: Reviews Complete, release-note-none, QA Deferred

#10607 Automated cherry pick of #10606
  components/post_view/post_attachment_opengraph/post_attachment_opengraph.test.tsx
  components/post_view/post_attachment_opengraph/post_attachment_opengraph.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#10509 fix name label tooltips in LHS
  components/sidebar/sidebar_channel/sidebar_channel_link/__snapshots__/sidebar_channel_link.test.tsx.snap
  components/sidebar/sidebar_channel/sidebar_channel_link/sidebar_channel_link.tsx
  sass/layout/_sidebar-left.scss
Labels: 4: Reviews Complete, release-note, Contributor

#10299 MM-42599 Replacing url by variables
  components/about_build_modal/__snapshots__/about_build_modal.test.tsx.snap
  components/about_build_modal/about_build_modal.tsx
  components/about_build_modal/about_build_modal_cloud/about_build_modal_cloud.tsx
  components/admin_console/__snapshots__/database_settings.test.jsx.snap
  components/admin_console/admin_definition.jsx
  components/admin_console/database_settings.jsx
  components/admin_console/group_settings/__snapshots__/group_settings.test.tsx.snap
  components/admin_console/group_settings/group_settings.tsx
  components/admin_console/permission_schemes_settings/__snapshots__/permission_schemes_settings.test.tsx.snap
  components/admin_console/permission_schemes_settings/permission_schemes_settings.tsx
  components/admin_console/plugin_management/__snapshots__/plugin_management.test.tsx.snap
  components/admin_console/plugin_management/plugin_management.tsx
  components/admin_console/push_settings.jsx
  components/admin_console/team_channel_settings/channel/details/channel_modes.tsx
  components/admin_console/team_channel_settings/team/details/team_modes.jsx
  components/help/components/commands.tsx
  components/help/components/formatting.tsx
  components/help/components/messaging.tsx
  components/integrations/confirm_integration/__snapshots__/confirm_integration.test.jsx.snap
  components/integrations/confirm_integration/confirm_integration.jsx
  i18n/bg.json
  i18n/de.json
  i18n/en.json
  i18n/en_AU.json
  i18n/es.json
  i18n/fa.json
  i18n/fr.json
  i18n/hu.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 4: Reviews Complete, release-note-none, Contributor

#10360 [#20261] Add support 1C:Enterpise syntax highlight
  types/external/highlightjs.d.ts
  utils/constants.tsx
Labels: 4: Reviews Complete, release-note, Contributor

#10608 Update subpackage docs
  packages/README.md
  packages/client/README.md
  packages/types/README.md
Labels: 4: Reviews Complete, release-note-none

#10615 [MM-44429] Top threads widget (#10356)
  components/activity_and_insights/activity_and_insights.scss
  components/activity_and_insights/insights/card/card.scss
  components/activity_and_insights/insights/insights.tsx
  components/activity_and_insights/insights/insights_modal/insights_modal.scss
  components/activity_and_insights/insights/insights_modal/insights_modal.tsx
  components/activity_and_insights/insights/top_threads/top_threads.scss
  components/activity_and_insights/insights/top_threads/top_threads.test.tsx
  components/activity_and_insights/insights/top_threads/top_threads.tsx
  components/activity_and_insights/insights/top_threads/top_threads_table/top_threads_table.test.tsx
  components/activity_and_insights/insights/top_threads/top_threads_table/top_threads_table.tsx
  components/threading/channel_threads/thread_footer/__snapshots__/thread_footer.test.tsx.snap
  components/widgets/users/avatars/__snapshots__/avatars.test.tsx.snap
  components/widgets/users/avatars/avatars.tsx
  i18n/en.json
  packages/client/src/client4.ts
  packages/mattermost-redux/src/action_types/insights.ts
  packages/mattermost-redux/src/actions/insights.ts
  packages/mattermost-redux/src/reducers/entities/files.ts
  packages/mattermost-redux/src/reducers/entities/posts.ts
  packages/types/src/insights.ts
  utils/constants.tsx
Labels: 3: QA Review, release-note-none

#10616 [MM-44657] Top boards for insights (#10470)
  components/activity_and_insights/activity_and_insights.scss
  components/activity_and_insights/insights/insights.tsx
  components/activity_and_insights/insights/insights_modal/insights_modal.scss
  components/activity_and_insights/insights/insights_modal/insights_modal.tsx
  components/activity_and_insights/insights/top_boards/top_boards.test.tsx
  components/activity_and_insights/insights/top_boards/top_boards.tsx
  components/activity_and_insights/insights/top_boards/top_boards_table/top_boards_table.test.tsx
  components/activity_and_insights/insights/top_boards/top_boards_table/top_boards_table.tsx
  i18n/en.json
  packages/types/src/insights.ts
  plugins/registry.js
  reducers/plugins/index.ts
  types/store/plugins.ts
  utils/constants.tsx
Labels: release-note-none

#10457 MM-44509 - subscription change not reflected after trial
  actions/cloud.tsx
  components/cloud_start_trial/cloud_start_trial_btn.test.tsx
  components/cloud_start_trial/cloud_start_trial_btn.tsx
  components/cloud_start_trial/request_business_email_modal.test.tsx
  components/cloud_start_trial/request_business_email_modal.tsx
  components/learn_more_trial_modal/learn_more_trial_modal.test.tsx
  components/learn_more_trial_modal/learn_more_trial_modal.tsx
  components/widgets/inputs/input/input.scss
  i18n/en.json
  packages/client/src/client4.ts
Labels: 2: Dev Review, release-note-none, QA Deferred

#10439 Mm-20223 Add webp emoji support
  components/emoji/add_emoji/__snapshots__/add_emoji.test.tsx.snap
  components/emoji/add_emoji/add_emoji.tsx
  i18n/en.json
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none, QA Deferred, Contributor

#10592 [MM-45097] Fix attachment menu overlap issue
  components/advanced_text_editor/formatting_bar/formatting_bar.tsx
  components/file_upload/__snapshots__/file_upload.test.jsx.snap
  components/file_upload/file_upload.jsx
Labels: 4: Reviews Complete, CherryPick/Approved, AutoMerge, release-note

#10622 Automated cherry pick of #10592
  components/advanced_text_editor/formatting_bar/formatting_bar.tsx
  components/file_upload/__snapshots__/file_upload.test.jsx.snap
  components/file_upload/file_upload.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#10618 Make window.store always available on community
  stores/redux_store.jsx
Labels: 4: Reviews Complete, release-note-none

#10610 Update Licences at Notice.txt to reflect dependency changes.
  NOTICE.txt
Labels: release-note-none, kind/chore

#10625 [MM-44657] Insights responsive (#10473)
  components/activity_and_insights/activity_and_insights.scss
  components/activity_and_insights/insights/card/card.scss
  components/activity_and_insights/insights/insights_header/insights_header.scss
  sass/responsive/_desktop.scss
Labels: release-note-none

#10626 [MM-44657] Insights telemetry (#10518)
  components/activity_and_insights/activity_and_insights_link/activity_and_insights_link.tsx
  components/activity_and_insights/insights/card/__snapshots__/card.test.tsx.snap
  components/activity_and_insights/insights/card/card.tsx
  components/activity_and_insights/insights/insights.tsx
  components/activity_and_insights/insights/time_frame_dropdown/time_frame_dropdown.tsx
  components/activity_and_insights/insights/top_boards/top_boards.tsx
  components/activity_and_insights/insights/top_boards/top_boards_table/top_boards_table.tsx
  components/activity_and_insights/insights/top_channels/top_channels.tsx
  components/activity_and_insights/insights/top_channels/top_channels_table/top_channels_table.tsx
  components/activity_and_insights/insights/top_threads/top_threads.tsx
  components/activity_and_insights/insights/top_threads/top_threads_table/top_threads_table.tsx
  components/activity_and_insights/insights/widget_hoc/widget_hoc.tsx
Labels: release-note-none

#10611 MM-18032 : Remove "jasny-bootstrap" library
  .npm-upgrade.json
  NOTICE.txt
  package-lock.json
  package.json
  sass/styles.scss
Labels: 3: QA Review, release-note
