Repository mattermost/mattermost-webapp, pull requests merged in 2022-05, with the labels that each got.

#10251 Update NOTICE.txt
  NOTICE.txt
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#10257 Automated cherry pick of #10251
  NOTICE.txt
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#10227 MM-40127 : Fix team sidebar buttons screen reader hover
  components/admin_console/data_retention_settings/team_list/__snapshots__/team_list.test.tsx.snap
  components/admin_console/permission_schemes_settings/permission_team_scheme_settings/team_in_list/__snapshots__/team_in_list.test.tsx.snap
  components/admin_console/team_channel_settings/team/details/__snapshots__/team_profile.test.jsx.snap
  components/admin_console/team_channel_settings/team/list/__snapshots__/team_list.test.tsx.snap
  components/team_sidebar/team_sidebar.tsx
  components/widgets/team_icon/__snapshots__/team_icon.test.tsx.snap
  components/widgets/team_icon/team_icon.test.tsx
  components/widgets/team_icon/team_icon.tsx
  i18n/en.json
Labels: 4: Reviews Complete, release-note-none, Contributor

#9996 MM-19664 : On entering large text in More DM modal, text overflows
  components/multiselect/multiselect.tsx
  sass/components/_multi-select.scss
  sass/components/_react-select.scss
Labels: 4: Reviews Complete, release-note-none, Contributor

#10244 MM-29798 Log in background tabs on focus
  components/root/root.jsx
  components/root/root.test.jsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none, QA Deferred

#10231 MM-43043: Fix misaligned follow button on root posts with no comments
  components/threading/channel_threads/thread_footer/__snapshots__/thread_footer.test.tsx.snap
  components/threading/channel_threads/thread_footer/thread_footer.tsx
Labels: 4: Reviews Complete, release-note-none, Contributor

#10013 [MM-37714] : Add an "Unread" section to the channel switcher and include "Threads" in results
  actions/views/channel.js
  components/quick_switch_modal/__snapshots__/quick_switch_modal.test.tsx.snap
  components/quick_switch_modal/quick_switch_modal.tsx
  components/suggestion/suggestion_list.jsx
  components/suggestion/switch_channel_provider.jsx
  components/suggestion/switch_channel_provider.test.jsx
  e2e/cypress/tests/integration/keyboard_shortcuts/ctrl_cmd_k_open_channel_from_global_threads_spec.js
  e2e/cypress/tests/integration/keyboard_shortcuts/ctrl_cmd_k_unreads_spec.js
  i18n/en.json
  packages/mattermost-redux/src/selectors/entities/channels.ts
  sass/components/_channel-switcher.scss
  sass/components/_suggestion-list.scss
  selectors/views/channel_sidebar.ts
  utils/constants.tsx
Labels: 4: Reviews Complete, release-note

#10076 [MM-41109] Make all links from plugin settings open in a different tab
  components/__snapshots__/formatted_markdown_message.test.jsx.snap
  components/admin_console/schema_text.test.jsx
  components/formatted_markdown_message.jsx
Labels: 4: Reviews Complete, release-note-none, Contributor

#10248 Fixes: invalid CRT preference state
  packages/mattermost-redux/src/actions/users.ts
Labels: 4: Reviews Complete, release-note-none, QA Deferred

#10256 [MM-42906] - License receives invalid date in the console when license expiration check runs
  components/admin_console/license_settings/__snapshots__/license_settings.test.tsx.snap
  components/admin_console/license_settings/enterprise_edition/enterprise_edition_left_panel.tsx
  components/admin_console/license_settings/license_settings.tsx
Labels: Setup Cloud Test Server, QA Review Done, release-note-none

#10239 MM-43084 update product limits through websocket
  actions/websocket_actions.jsx
  actions/websocket_actions.test.jsx
  components/admin_console/admin_console.test.tsx
  components/admin_console/billing/billing_subscriptions/limits.test.tsx
  components/admin_console/billing/billing_subscriptions/limits.tsx
  packages/mattermost-redux/src/reducers/entities/cloud.test.ts
  packages/mattermost-redux/src/reducers/entities/cloud.ts
  packages/mattermost-redux/src/selectors/entities/cloud.ts
  packages/mattermost-redux/src/store/initial_state.ts
  packages/types/src/cloud.ts
  utils/constants.tsx
Labels: 2: Dev Review, release-note-none, QA Deferred

#10261 [MM-43637] Change shortcut to open channel info RHS on mac
  components/keyboard_shortcuts/keyboard_shortcuts_modal/__snapshots__/keyboard_shortcuts_modal.test.tsx.snap
  components/keyboard_shortcuts/keyboard_shortcuts_sequence/keyboard_shortcuts.ts
  components/sidebar_right/sidebar_right.jsx
Labels: 4: Reviews Complete, CherryPick/Approved, QA Review Done, Setup Cloud + CWS Test Server, release-note-none

#10269 Automated cherry pick of #10261
  components/keyboard_shortcuts/keyboard_shortcuts_modal/__snapshots__/keyboard_shortcuts_modal.test.tsx.snap
  components/keyboard_shortcuts/keyboard_shortcuts_sequence/keyboard_shortcuts.ts
  components/sidebar_right/sidebar_right.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#10273 Automated cherry pick of #10264
  components/new_channel_modal/new_channel_modal.tsx
  e2e/cypress/tests/integration/multi_team_and_dm/existing_channel_name_spec.js
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#10272 Automated cherry pick of #10264
  components/new_channel_modal/new_channel_modal.tsx
  e2e/cypress/tests/integration/multi_team_and_dm/existing_channel_name_spec.js
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#10208 MM-42599 : Remove raw URLs from translation strings
  components/admin_console/__snapshots__/message_export_settings.test.jsx.snap
  components/admin_console/admin_definition.jsx
  components/admin_console/manage_roles_modal/manage_roles_modal.tsx
  components/admin_console/manage_tokens_modal/__snapshots__/manage_tokens_modal.test.tsx.snap
  components/admin_console/manage_tokens_modal/manage_tokens_modal.tsx
  components/admin_console/message_export_settings.jsx
  components/admin_console/permission_schemes_settings/permission_system_scheme_settings/__snapshots__/permission_system_scheme_settings.test.tsx.snap
  components/admin_console/permission_schemes_settings/permission_system_scheme_settings/permission_system_scheme_settings.tsx
  components/admin_console/permission_schemes_settings/permission_team_scheme_settings/__snapshots__/permission_team_scheme_settings.test.tsx.snap
  components/admin_console/permission_schemes_settings/permission_team_scheme_settings/permission_team_scheme_settings.tsx
  components/admin_console/plugin_management/__snapshots__/plugin_management.test.tsx.snap
  components/admin_console/plugin_management/plugin_management.tsx
  components/admin_console/push_settings.jsx
  components/collapsed_reply_threads_beta_modal/collapsed_reply_threads_beta_modal.tsx
  components/integrations/confirm_integration/__snapshots__/confirm_integration.test.jsx.snap
  components/integrations/confirm_integration/confirm_integration.jsx
  components/learn_more_trial_modal/__snapshots__/learn_more_trial_modal_step.test.tsx.snap
  components/learn_more_trial_modal/learn_more_trial_modal_step.tsx
  components/start_trial_modal/index.tsx
  components/user_settings/security/user_access_token_section/user_access_token_section.tsx
  i18n/bg.json
  i18n/de.json
  i18n/en.json
  i18n/en_AU.json
  i18n/es.json
  i18n/fa.json
  i18n/fr.json
  i18n/hu.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
  package.json
Labels: 4: Reviews Complete, release-note-none, Contributor

#10216 GH-20026 : Fix missing aria-label in CHR members button
  components/channel_header/__snapshots__/channel_header.test.jsx.snap
  components/channel_header/channel_header.js
  components/channel_header/components/header_icon_wrapper.tsx
Labels: 4: Reviews Complete, release-note-none, Contributor

#9482 [MM-24507]: sticky "reply to thread..." input
  components/create_comment/__snapshots__/create_comment.test.jsx.snap
  components/create_comment/create_comment.tsx
  components/create_post/__snapshots__/create_post.test.jsx.snap
  components/create_post/create_post.test.jsx
  components/create_post/create_post.tsx
  components/file_upload/__snapshots__/file_upload.test.jsx.snap
  components/file_upload/file_upload.jsx
  components/new_replies_banner/new_replies_banner.scss
  components/rhs_comment/rhs_comment.jsx
  components/rhs_root_post/rhs_root_post.jsx
  components/threading/virtualized_thread_viewer/virtualized_thread_viewer.tsx
  e2e/cypress/tests/integration/enterprise/accessibility/accessibility_input_fields_spec.js
  e2e/cypress/tests/integration/integrations/poll_spec.js
  e2e/cypress/tests/integration/keyboard_shortcuts/up_arrow_edit_message_spec.js
  e2e/cypress/tests/integration/messaging/center_channel_rhs_overlap_spec.js
  e2e/cypress/tests/integration/messaging/message_reply_input_box_expand_spec.js
  e2e/cypress/tests/integration/messaging/message_reply_part2_spec.js
  e2e/cypress/tests/integration/messaging/message_reply_scrollable_spec.js
  e2e/cypress/tests/integration/messaging/message_spec.js
  e2e/cypress/tests/integration/messaging/pinned_parent_post_spec.js
  e2e/cypress/tests/support/ui/sidebar_right.d.ts
  e2e/cypress/tests/support/ui/sidebar_right.js
  i18n/en.json
  i18n/en_AU.json
  packages/mattermost-redux/src/utils/post_list.ts
  reducers/views/posts.ts
  sass/components/_post-right.scss
  sass/components/_post.scss
  sass/layout/_sidebar-right.scss
  sass/responsive/_mobile.scss
  selectors/views/threads.ts
  utils/utils.tsx
Labels: 4: Reviews Complete, release-note

#10270 MM-43816_Unable to hit enter to create channel in new Create Channel modal
  components/new_channel_modal/__snapshots__/new_channel_modal.test.tsx.snap
  components/new_channel_modal/new_channel_modal.tsx
  e2e/cypress/tests/integration/multi_team_and_dm/existing_channel_name_spec.js
Labels: 2: Dev Review, Setup Cloud Test Server, QA Review Done, release-note-none

#10278 MM-43816_Unable to hit enter to create channel in new Create Channel modal
  e2e/cypress/tests/integration/multi_team_and_dm/existing_channel_name_spec.js
Labels: 4: Reviews Complete, release-note-none

#10280 Automated cherry pick of #10270
  components/new_channel_modal/__snapshots__/new_channel_modal.test.tsx.snap
  components/new_channel_modal/new_channel_modal.tsx
  e2e/cypress/tests/integration/multi_team_and_dm/existing_channel_name_spec.js
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#10279 Automated cherry pick of #10270
  components/new_channel_modal/__snapshots__/new_channel_modal.test.tsx.snap
  components/new_channel_modal/new_channel_modal.tsx
  e2e/cypress/tests/integration/multi_team_and_dm/existing_channel_name_spec.js
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#8913 Mm-38333 display users within a channel
  components/channel_invite_modal/__snapshots__/channel_invite_modal.test.tsx.snap
  components/channel_invite_modal/channel_invite_modal.test.tsx
  components/channel_invite_modal/channel_invite_modal.tsx
  components/channel_invite_modal/index.ts
Labels: 3: QA Review, release-note-none

#10207 [MM-43333] Hooking up top reactions endpoint
  actions/websocket_actions.jsx
  components/activity_and_insights/activity_and_insights.scss
  components/activity_and_insights/insights/card/card.tsx
  components/activity_and_insights/insights/insights.tsx
  components/activity_and_insights/insights/insights_modal/insights_modal.scss
  components/activity_and_insights/insights/insights_modal/insights_modal.tsx
  components/activity_and_insights/insights/time_frame_dropdown/time_frame_dropdown.tsx
  components/activity_and_insights/insights/top_reactions/top_reactions.tsx
  components/activity_and_insights/insights/top_reactions/top_reactions_bar_chart/top_reactions_bar_chart.tsx
  components/activity_and_insights/insights/top_reactions/top_reactions_table/top_reactions_table.tsx
  components/activity_and_insights/insights/widget_hoc/widget_hoc.tsx
  i18n/en.json
  packages/client/src/client4.ts
  packages/mattermost-redux/src/action_types/index.ts
  packages/mattermost-redux/src/action_types/insights.ts
  packages/mattermost-redux/src/actions/index.ts
  packages/mattermost-redux/src/actions/insights.ts
  packages/mattermost-redux/src/reducers/entities/index.ts
  packages/mattermost-redux/src/reducers/entities/insights.ts
  packages/mattermost-redux/src/selectors/entities/insights.ts
  packages/mattermost-redux/src/selectors/entities/users.ts
  packages/mattermost-redux/src/store/initial_state.ts
  packages/mattermost-redux/src/types/insights.ts
  packages/types/src/insights.ts
  packages/types/src/reactions.ts
  packages/types/src/store.ts
  utils/constants.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none

#10288 [MM-43349]: fixes posting edited code-blocks
  components/edit_post/edit_post.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none, kind/bug

#10289 Automated cherry pick of #10288
  components/edit_post/edit_post.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#10265 Fix plugin link tooltip flickering
  components/link_tooltip/__snapshots__/link_tooltip.test.tsx.snap
  components/link_tooltip/link_tooltip.scss
  components/link_tooltip/link_tooltip.tsx
  e2e/cypress/tests/integration/plugins/link_tooltip_spec.js
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#10291 Automated cherry pick of #10265
  components/link_tooltip/__snapshots__/link_tooltip.test.tsx.snap
  components/link_tooltip/link_tooltip.scss
  components/link_tooltip/link_tooltip.tsx
  e2e/cypress/tests/integration/plugins/link_tooltip_spec.js
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#10298 Cherry pick for MM-43328
  components/channel_members_rhs/index.ts
  e2e/cypress/tests/integration/channel/channel_members_rhs_spec.js
  packages/mattermost-redux/src/selectors/entities/users.ts
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#10286 [MM-44047] fix issue with tippy mock test and TourTipOverlayPunchOut export warning
  components/rhs_header_post/rhs_header_post.spec.tsx
  components/widgets/tour_tip/index.ts
  components/widgets/tour_tip/tour_tip.tsx
  components/widgets/tour_tip/tour_tip_backdrop.tsx
  tests/react-tippy_mock.js
Labels: release-note, QA Deferred

#10287 MM-41062: fixes file upload disabled, adds E2E tests
  components/file_upload/file_upload.jsx
  e2e/cypress/tests/integration/files_and_attachments/disabled_file_upload_spec.js
  package.json
Labels: 4: Reviews Complete, release-note

#10242 [MM-32692]: Feature: Add two more CRT options in System Console: default_on & always_on
  components/admin_console/admin_definition.jsx
  components/user_settings/display/index.ts
  i18n/en.json
  packages/mattermost-redux/src/selectors/entities/preferences.ts
  packages/types/src/config.ts
Labels: 4: Reviews Complete, release-note

#10181 add more unit tests for sysadmin vs end user
  components/actions_menu/__snapshots__/actions_menu.test.tsx.snap
  components/actions_menu/actions_menu.test.tsx
Labels: release-note-none

#10252 MM-42031 : Add e2e tests for CRT tour
  components/threading/global_threads/thread_list/__snapshots__/thread_list.test.tsx.snap
  components/threading/global_threads/thread_list/thread_list.tsx
  components/tutorial/tutorial_tip_legacy/__snapshots__/tutorial_tip.test.tsx.snap
  components/tutorial/tutorial_tip_legacy/tutorial_tip.tsx
  components/widgets/pulsating_dot/index.tsx
  e2e/cypress/tests/integration/collapsed_reply_threads/crt_tour_spec.js
Labels: 2: Dev Review, 3: QA Review, release-note-none, Contributor

#10189 MM-43348: fetches latest thread replies on open
  components/threading/thread_viewer/index.ts
  components/threading/thread_viewer/thread_viewer.test.tsx
  components/threading/thread_viewer/thread_viewer.tsx
  e2e/cypress/tests/integration/collapsed_reply_threads/global_threads_spec.js
  packages/client/src/client4.ts
  packages/client/src/helpers.test.ts
  packages/client/src/helpers.ts
  packages/mattermost-redux/src/actions/posts.ts
  packages/mattermost-redux/src/reducers/entities/posts.test.js
  packages/mattermost-redux/src/reducers/entities/posts.ts
Labels: release-note

#10305 Fixes snapshot tests
  components/actions_menu/__snapshots__/actions_menu.test.tsx.snap
Labels: 4: Reviews Complete, release-note-none

#10310 MM-42489_Revamp: Login screen webapp
  components/login/login.tsx
  packages/client/src/client4.ts
Labels: 2: Dev Review, Setup Cloud Test Server, release-note-none

#10238 [MM-43720] Unit tests for insight components
  components/activity_and_insights/insights/__snapshots__/insights.test.tsx.snap
  components/activity_and_insights/insights/card/__snapshots__/card.test.tsx.snap
  components/activity_and_insights/insights/card/card.scss
  components/activity_and_insights/insights/card/card.test.tsx
  components/activity_and_insights/insights/card/card.tsx
  components/activity_and_insights/insights/insights.test.tsx
  components/activity_and_insights/insights/insights_modal/__snapshots__/insights_modal.test.tsx.snap
  components/activity_and_insights/insights/insights_modal/insights_modal.test.tsx
  components/activity_and_insights/insights/insights_title/__snapshots__/insights_title.test.tsx.snap
  components/activity_and_insights/insights/insights_title/insights_title.test.tsx
  components/activity_and_insights/insights/time_frame_dropdown/__snapshots__/time_frame_dropdown.test.tsx.snap
  components/activity_and_insights/insights/time_frame_dropdown/time_frame_dropdown.test.tsx
  components/activity_and_insights/insights/top_reactions/top_reactions.test.tsx
  components/activity_and_insights/insights/top_reactions/top_reactions.tsx
  components/activity_and_insights/insights/top_reactions/top_reactions_bar_chart/__snapshots__/top_reactions_bar_chart.test.tsx.snap
  components/activity_and_insights/insights/top_reactions/top_reactions_bar_chart/top_reactions_bar_chart.test.tsx
  components/activity_and_insights/insights/top_reactions/top_reactions_table/top_reactions_table.test.tsx
  components/activity_and_insights/insights/widget_hoc/widget_hoc.test.tsx
Labels: 2: Dev Review, Setup Cloud Test Server, release-note-none

#10306 [MM-44172] Fix hotkey for channel info shows alt instead of shift in the shortcut [mac only]
  i18n/en.json
Labels: QA Review Done, release-note-none

#10313 Automated cherry pick of #10306
  i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge

#10312 fixed coloring in EmojiPicker button for edit_post component
  components/edit_post/edit_post.tsx
Labels: 4: Reviews Complete

#10327 Automated cherry pick of #10312
  components/edit_post/edit_post.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#10328 Automated cherry pick of #10222
  components/threading/thread_viewer/thread_viewer.scss
  components/threading/virtualized_thread_viewer/create_comment.tsx
  e2e/cypress/tests/integration/channel/archived_channels_1_spec.js
  i18n/en.json
  i18n/en_AU.json
  sass/layout/_sidebar-right.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#10315 E2E/Cypress:fixed add user to channel test case
  e2e/cypress/tests/integration/channel_settings/add_users_to_channel_spec.js
Labels: 4: Reviews Complete, release-note-none

#10262 [MM-43786] Insights top channels
  components/activity_and_insights/activity_and_insights.scss
  components/activity_and_insights/insights/insights_modal/insights_modal.scss
  components/activity_and_insights/insights/insights_modal/insights_modal.tsx
  components/activity_and_insights/insights/top_channels/top_channels.test.tsx
  components/activity_and_insights/insights/top_channels/top_channels.tsx
  components/activity_and_insights/insights/top_channels/top_channels_table/top_channels_table.test.tsx
  components/activity_and_insights/insights/top_channels/top_channels_table/top_channels_table.tsx
  components/activity_and_insights/insights/top_reactions/top_reactions.tsx
  components/activity_and_insights/insights/widget_empty_state/widget_empty_state.tsx
  i18n/en.json
  packages/client/src/client4.ts
  packages/mattermost-redux/src/actions/insights.ts
  packages/mattermost-redux/src/selectors/entities/insights.ts
  packages/types/src/insights.ts
Labels: 3: QA Review, Setup Cloud Test Server, release-note-none

#10332 Automated cherry pick of #10214
  components/post_view/reaction_list/reaction_list.tsx
  components/post_view/reaction_list/reactions_list.test.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#10333 Merge Weblate into master
  i18n/de.json
  i18n/ko.json
  i18n/nl.json
  i18n/tr.json
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, release-note-none

#10293 MM-43792 - fix invite modal email results
  components/invitation_modal/result_table.scss
Labels: Setup Cloud Test Server, release-note-none

#10334 Automated cherry pick of #10293
  components/invitation_modal/result_table.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#10302 Mm 43596 limits usage modal
  components/admin_console/admin_console.tsx
  components/admin_console/billing/billing_subscriptions/limits.test.tsx
  components/admin_console/billing/billing_subscriptions/limits.tsx
  components/cloud_usage_modal/index.scss
  components/cloud_usage_modal/index.test.tsx
  components/cloud_usage_modal/index.tsx
  components/cloud_usage_modal/limit_line.scss
  components/cloud_usage_modal/limit_line.tsx
  components/cloud_usage_modal/mini_modal.scss
  components/cloud_usage_modal/mini_modal.tsx
  components/cloud_usage_modal/workspace_limits_panel.tsx
  components/common/hooks/useGetLimits.ts
  components/common/hooks/useGetUsage.ts
  components/common/usage_percent_bar/index.tsx
  components/generic_modal.scss
  i18n/en.json
  packages/mattermost-redux/src/selectors/entities/cloud.ts
  packages/types/src/cloud.ts
  utils/constants.tsx
Labels: 2: Dev Review, QA Review Done, 1: UX Review, Setup Cloud + CWS Test Server, release-note-none

#10260 MM-40643 : Fix compact thread post not left align
  sass/components/_post-right.scss
Labels: 4: Reviews Complete, release-note-none, Contributor

#10295 Mm 42775 create client 4 method for fetching trial self hosted
  actions/admin_actions.jsx
  packages/client/src/client4.ts
  packages/types/src/config.ts
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none

#10326 [MM-44228]: fixed post hover-state on compact message display
  sass/components/_post.scss
Labels: 4: Reviews Complete, Setup Cloud Test Server, QA Review Done, AutoMerge, release-note-none, kind/bug

#10339 Automated cherry pick of #10326
  sass/components/_post.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#10325 Mm 43886 - AB test initial onboarding flow
  components/channel_view/__snapshots__/channel_view.test.tsx.snap
  components/channel_view/channel_view.test.tsx
  components/channel_view/channel_view.tsx
  components/channel_view/index.ts
  components/do_verify_email/do_verify_email.tsx
  components/login/login.tsx
  components/main_menu/index.tsx
  components/main_menu/main_menu.test.tsx
  components/main_menu/main_menu.tsx
  components/onboarding_tasks/onboarding_tasks_manager.tsx
  components/signup/signup_controller/signup_controller.jsx
  components/signup/signup_email/signup_email.tsx
  components/terms_of_service/terms_of_service.tsx
  plugins/test/main_menu_action.test.jsx
Labels: CherryPick/Approved, Setup Cloud Test Server, release-note-none, QA Deferred

#10344 [MM-44389] : fix show preview tooltip text for windows/linux
  components/keyboard_shortcuts/keyboard_shortcuts_sequence/keyboard_shortcuts.ts
  i18n/en.json
Labels: Setup Cloud Test Server, release-note, QA Deferred

#10346 Automated cherry pick of #10344
  components/keyboard_shortcuts/keyboard_shortcuts_sequence/keyboard_shortcuts.ts
  i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#10336 [MM-44428]: Advanced text editor image pasting and drag drop issue
  components/advanced_text_editor/advanced_text_editor.tsx
  components/advanced_text_editor/formatting_bar/formatting_bar.tsx
  components/advanced_text_editor/toggle_formatting_bar/toggle_formatting_bar.tsx
Labels: 4: Reviews Complete, release-note

#10349 Automated cherry pick of #10336
  components/advanced_text_editor/advanced_text_editor.tsx
  components/advanced_text_editor/formatting_bar/formatting_bar.tsx
  components/advanced_text_editor/toggle_formatting_bar/toggle_formatting_bar.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#10254 GH-20109 : Fix sass Slash as Division deprecated
  sass/utils/_functions.scss
Labels: 4: Reviews Complete, release-note-none, Contributor

#10271 [MM-43646] - For admin: Pricing page
  components/admin_console/license_settings/enterprise_edition/enterprise_edition_left_panel.tsx
  components/global_header/right_controls/cloud_upgrade_button/cloud_upgrade_button.test.tsx
  components/global_header/right_controls/cloud_upgrade_button/index.tsx
  components/global_header/right_controls/right_controls.tsx
  components/pricing_modal/content.scss
  components/pricing_modal/content.tsx
  components/pricing_modal/index.tsx
  components/pricing_modal/lady.svg.tsx
  components/pricing_modal/man.svg.tsx
  components/pricing_modal/pricing_modal.scss
  components/widgets/icons/check_mark_icon.tsx
  components/widgets/icons/star_mark_icon.tsx
  e2e/cypress/tests/integration/enterprise/cloud/billing/pricing_modal_spec.js
  i18n/en.json
  packages/mattermost-redux/src/selectors/entities/cloud.ts
  plugins/export.js
  utils/constants.tsx
Labels: QA Review Done, Setup Cloud + CWS Test Server, release-note-none

#10343 [MM-41296] : Add a condition to hide legacy Enable post formatting setting if Advanced Text editor is enabled
  components/channel_view/index.ts
  components/threading/virtualized_thread_viewer/create_comment.tsx
  components/user_settings/advanced/index.js
  components/user_settings/advanced/user_settings_advanced.jsx
  packages/mattermost-redux/src/selectors/entities/preferences.ts
Labels: 4: Reviews Complete, release-note

#10353 Automated cherry pick of #10343
  components/channel_view/index.ts
  components/threading/virtualized_thread_viewer/create_comment.tsx
  components/user_settings/advanced/index.js
  components/user_settings/advanced/user_settings_advanced.jsx
  packages/mattermost-redux/src/selectors/entities/preferences.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#10274 MM-35853 : Replace getUserTimezone with makeGetUserTimezone
  actions/views/rhs.ts
  components/post_view/post_edited_indicator/index.ts
  components/root/effects.ts
  components/suggestion/search_date_suggestion/index.ts
  components/timestamp/index.test.tsx
  components/timestamp/index.ts
  components/user_settings/display/index.ts
  components/user_settings/display/user_settings_display.tsx
  packages/mattermost-redux/src/actions/timezone.ts
  packages/mattermost-redux/src/selectors/entities/timezone.ts
Labels: 4: Reviews Complete, release-note-none, Contributor

#10335 Limits state management
  actions/cloud.tsx
  components/admin_console/billing/billing_subscriptions/limits.test.tsx
  components/cloud_usage_modal/index.test.tsx
  components/common/hooks/useGetUsage.ts
  packages/client/src/client4.ts
  packages/mattermost-redux/src/action_types/cloud.ts
  packages/mattermost-redux/src/reducers/entities/index.ts
  packages/mattermost-redux/src/reducers/entities/usage.ts
  packages/mattermost-redux/src/selectors/entities/usage.ts
  packages/mattermost-redux/src/store/initial_state.ts
  packages/types/src/boards.ts
  packages/types/src/cloud.ts
  packages/types/src/posts.ts
  packages/types/src/store.ts
Labels: 2: Dev Review, QA Review Done, Setup Cloud + CWS Test Server, release-note-none

#10317 Revert "[MM-24507]: sticky "reply to thread..." input"
  components/create_comment/__snapshots__/create_comment.test.jsx.snap
  components/create_comment/create_comment.tsx
  components/create_post/__snapshots__/create_post.test.jsx.snap
  components/create_post/create_post.test.jsx
  components/create_post/create_post.tsx
  components/file_upload/__snapshots__/file_upload.test.jsx.snap
  components/file_upload/file_upload.jsx
  components/new_replies_banner/new_replies_banner.scss
  components/rhs_comment/rhs_comment.jsx
  components/rhs_root_post/rhs_root_post.jsx
  components/threading/virtualized_thread_viewer/virtualized_thread_viewer.tsx
  e2e/cypress/tests/integration/enterprise/accessibility/accessibility_input_fields_spec.js
  e2e/cypress/tests/integration/integrations/poll_spec.js
  e2e/cypress/tests/integration/keyboard_shortcuts/up_arrow_edit_message_spec.js
  e2e/cypress/tests/integration/messaging/center_channel_rhs_overlap_spec.js
  e2e/cypress/tests/integration/messaging/message_reply_input_box_expand_spec.js
  e2e/cypress/tests/integration/messaging/message_reply_part2_spec.js
  e2e/cypress/tests/integration/messaging/message_reply_scrollable_spec.js
  e2e/cypress/tests/integration/messaging/message_spec.js
  e2e/cypress/tests/integration/messaging/pinned_parent_post_spec.js
  e2e/cypress/tests/support/ui/sidebar_right.d.ts
  e2e/cypress/tests/support/ui/sidebar_right.js
  i18n/en.json
  i18n/en_AU.json
  packages/mattermost-redux/src/utils/post_list.ts
  reducers/views/posts.ts
  sass/components/_post-right.scss
  sass/components/_post.scss
  sass/layout/_sidebar-right.scss
  sass/responsive/_mobile.scss
  selectors/views/threads.ts
  utils/utils.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#10369 Automated cherry pick of #10317
  components/create_comment/__snapshots__/create_comment.test.jsx.snap
  components/create_comment/create_comment.tsx
  components/create_post/__snapshots__/create_post.test.jsx.snap
  components/create_post/create_post.test.jsx
  components/create_post/create_post.tsx
  components/file_upload/__snapshots__/file_upload.test.jsx.snap
  components/file_upload/file_upload.jsx
  components/new_replies_banner/new_replies_banner.scss
  components/rhs_comment/rhs_comment.jsx
  components/rhs_root_post/rhs_root_post.jsx
  components/threading/virtualized_thread_viewer/virtualized_thread_viewer.tsx
  e2e/cypress/tests/integration/enterprise/accessibility/accessibility_input_fields_spec.js
  e2e/cypress/tests/integration/integrations/poll_spec.js
  e2e/cypress/tests/integration/keyboard_shortcuts/up_arrow_edit_message_spec.js
  e2e/cypress/tests/integration/messaging/center_channel_rhs_overlap_spec.js
  e2e/cypress/tests/integration/messaging/message_reply_input_box_expand_spec.js
  e2e/cypress/tests/integration/messaging/message_reply_part2_spec.js
  e2e/cypress/tests/integration/messaging/message_reply_scrollable_spec.js
  e2e/cypress/tests/integration/messaging/message_spec.js
  e2e/cypress/tests/integration/messaging/pinned_parent_post_spec.js
  e2e/cypress/tests/support/ui/sidebar_right.d.ts
  e2e/cypress/tests/support/ui/sidebar_right.js
  i18n/en.json
  i18n/en_AU.json
  packages/mattermost-redux/src/utils/post_list.ts
  reducers/views/posts.ts
  sass/components/_post-right.scss
  sass/components/_post.scss
  sass/layout/_sidebar-right.scss
  sass/responsive/_mobile.scss
  selectors/views/threads.ts
  utils/utils.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#10345 [MM-44519] Fixes missing replies in thread
  components/threading/thread_viewer/index.ts
  components/threading/thread_viewer/thread_viewer.test.tsx
  components/threading/thread_viewer/thread_viewer.tsx
  packages/mattermost-redux/src/reducers/entities/posts.test.js
  packages/mattermost-redux/src/reducers/entities/posts.ts
Labels: 2: Dev Review, QA Review Done, release-note, kind/bug

#10372 Automated cherry pick of #10345
  components/threading/thread_viewer/index.ts
  components/threading/thread_viewer/thread_viewer.test.tsx
  components/threading/thread_viewer/thread_viewer.tsx
  packages/mattermost-redux/src/reducers/entities/posts.test.js
  packages/mattermost-redux/src/reducers/entities/posts.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#9680 [MM-41158] Remove white circles from App Bar icons
  components/app_bar/app_bar.scss
Labels: 3: QA Review, Setup Cloud Test Server, release-note-none

#10350 MM-44460 - hide trial disclosure after start
  components/cloud_start_trial/cloud_start_trial_btn.tsx
  components/onboarding_tasklist/onboarding_tasklist_completed.tsx
Labels: QA Review Done, Setup Cloud + CWS Test Server, release-note-none

#10376 Automated cherry pick of #10350
  components/cloud_start_trial/cloud_start_trial_btn.tsx
  components/onboarding_tasklist/onboarding_tasklist_completed.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#10320 Fix warnings about React-Bootstrap triggers
  components/channel_header/components/__snapshots__/header_icon_wrapper.test.tsx.snap
  components/channel_header/components/header_icon_wrapper.tsx
  components/global_header/left_controls/history_buttons/history_buttons.tsx
  components/global_header/right_controls/at_mentions_button/__snapshots__/at_mentions_button.test.tsx.snap
  components/global_header/right_controls/at_mentions_button/at_mentions_button.tsx
  components/global_header/right_controls/saved_posts_button/__snapshots__/saved_posts_button.test.tsx.snap
  components/global_header/right_controls/saved_posts_button/saved_posts_button.tsx
  components/global_header/right_controls/settings_button/settings_button.tsx
  plugins/channel_header_plug/__snapshots__/channel_header_plug.test.tsx.snap
Labels: 4: Reviews Complete, release-note

#10377 MM-42490_Rename new footer and header containers' classnames
  components/header_footer_route/footer.scss
  components/header_footer_route/footer.tsx
  components/header_footer_route/header.scss
  components/header_footer_route/header.tsx
  e2e/cypress/tests/integration/signin_authentication/login_spec.js
  e2e/cypress/tests/integration/signin_authentication/signup_spec.js
  e2e/cypress/tests/integration/system_console/site_configuration/link_customization_e20_1_spec.js
  e2e/cypress/tests/integration/system_console/site_configuration/link_customization_e20_2_spec.js
Labels: 2: Dev Review, Setup Cloud Test Server, release-note-none

#9349 Updating favicon images
  images/favicon/android-chrome-192x192.png
  images/favicon/apple-touch-icon-120x120.png
  images/favicon/apple-touch-icon-144x144.png
  images/favicon/apple-touch-icon-152x152.png
  images/favicon/apple-touch-icon-57x57.png
  images/favicon/apple-touch-icon-60x60.png
  images/favicon/apple-touch-icon-72x72.png
  images/favicon/apple-touch-icon-76x76.png
  images/favicon/favicon-16x16.png
  images/favicon/favicon-32x32.png
  images/favicon/favicon-96x96.png
  images/favicon/favicon-default-16x16.png
  images/favicon/favicon-default-24x24.png
  images/favicon/favicon-default-32x32.png
  images/favicon/favicon-default-64x64.png
  images/favicon/favicon-default-96x96.png
  images/favicon/favicon-mentions-16x16.png
  images/favicon/favicon-mentions-24x24.png
  images/favicon/favicon-mentions-32x32.png
  images/favicon/favicon-mentions-64x64.png
  images/favicon/favicon-mentions-96x96.png
  images/favicon/favicon-unread-16x16.png
  images/favicon/favicon-unread-24x24.png
  images/favicon/favicon-unread-32x32.png
  images/favicon/favicon-unread-64x64.png
  images/favicon/favicon-unread-96x96.png
Labels: 2: Dev Review, release-note-none

#10383 MM-44545 - show onboarding task list opened by default
  components/root/root.jsx
  selectors/onboarding.ts
Labels: Setup Cloud Test Server, QA Review Done, release-note-none

#10318 MM-44221: Add admin console setting to enable/disable App Bar
  components/admin_console/admin_definition.jsx
  components/app_bar/__snapshots__/app_bar.test.tsx.snap
  components/app_bar/app_bar.test.tsx
  components/app_bar/app_bar.tsx
  i18n/en.json
  packages/mattermost-redux/src/selectors/entities/apps.ts
  packages/types/src/config.ts
Labels: 4: Reviews Complete, release-note

#10362 Cypress/E2E: Hide trial modal for first admin
  e2e/cypress/tests/integration/accessibility/accessibility_sidebar_dm_spec.js
  e2e/cypress/tests/integration/accessibility/accessibility_sidebar_spec.js
  e2e/cypress/tests/integration/channel_sidebar/dm_category_spec.js
  e2e/cypress/tests/integration/channel_sidebar/dm_gm_behaviour_spec.js
  e2e/cypress/tests/integration/channel_sidebar/dm_gm_filtering_sorting_spec.js
  e2e/cypress/tests/integration/collapsed_reply_threads/channel_notifications_spec.js
  e2e/cypress/tests/integration/collapsed_reply_threads/crt_tour_spec.js
  e2e/cypress/tests/integration/collapsed_reply_threads/files_spec.js
  e2e/cypress/tests/integration/collapsed_reply_threads/following_spec.js
  e2e/cypress/tests/integration/collapsed_reply_threads/global_threads_spec.js
  e2e/cypress/tests/integration/collapsed_reply_threads/replies_spec.js
  e2e/cypress/tests/integration/collapsed_reply_threads/unread_spec.js
  e2e/cypress/tests/support/api/preference.d.ts
  e2e/cypress/tests/support/api/preference.js
  e2e/cypress/tests/support/api/setup.d.ts
  e2e/cypress/tests/support/api/setup.js
  e2e/cypress/tests/support/api/user.d.ts
  e2e/cypress/tests/support/api/user.js
  e2e/cypress/tests/support/index.js
Labels: 4: Reviews Complete, release-note-none

#10381 [MM-44566] - 501 errors for non-cloud environment getting subscription info
  components/global_header/right_controls/cloud_upgrade_button/cloud_upgrade_button.test.tsx
  components/global_header/right_controls/cloud_upgrade_button/index.tsx
Labels: 2: Dev Review, release-note-none

#10290 MM-43889 Reduce unnecessary calls to viewChannel API
  actions/team_actions.jsx
  actions/team_actions.test.js
  components/post_view/post_list/index.js
  components/post_view/post_list/post_list.jsx
  components/post_view/post_list/post_list.test.jsx
  packages/mattermost-redux/src/actions/teams.test.js
  packages/mattermost-redux/src/actions/teams.ts
Labels: 4: Reviews Complete, release-note

#10311 MM-44216: Move channel header icons to App Bar
  components/admin_console/admin_definition.jsx
  components/app_bar/__snapshots__/app_bar.test.tsx.snap
  components/app_bar/app_bar.scss
  components/app_bar/app_bar.test.tsx
  components/app_bar/app_bar.tsx
  components/app_bar/app_bar_plugin_component.tsx
  i18n/en.json
  packages/mattermost-redux/src/selectors/entities/apps.ts
  packages/types/src/config.ts
  plugins/channel_header_plug/__snapshots__/channel_header_plug.test.tsx.snap
  plugins/channel_header_plug/channel_header_plug.test.tsx
  plugins/channel_header_plug/channel_header_plug.tsx
  plugins/channel_header_plug/index.ts
  selectors/plugins.ts
Labels: 4: Reviews Complete, release-note

#10314 [MM-43650] - Billing page design updates
  components/common/plan_label/index.tsx
  components/pricing_modal/content.tsx
  components/pricing_modal/index.tsx
  components/purchase_modal/index.ts
  components/purchase_modal/purchase.scss
  components/purchase_modal/purchase_modal.tsx
  i18n/en.json
Labels: 2: Dev Review, QA Review Done, 1: UX Review, Setup Cloud + CWS Test Server, release-note-none

#10338 [MM-44309] Post Trial - Archived data banner
  components/announcement_bar/announcement_bar_controller.tsx
  components/announcement_bar/cloud_trial_ended_announcement_bar/cloud_trial_ended_announcement_bar.test.tsx
  components/announcement_bar/cloud_trial_ended_announcement_bar/index.tsx
  components/common/hooks/useGetSubscription.ts
  components/common/hooks/useGetUsageDeltas.ts
  i18n/en.json
  packages/mattermost-redux/src/reducers/entities/usage.ts
  packages/mattermost-redux/src/store/initial_state.ts
  packages/types/src/cloud.ts
  utils/constants.tsx
  utils/limits.tsx
Labels: 4: Reviews Complete, release-note-none

#10268 [MM-43785] Insights feature intro
  components/activity_and_insights/activity_and_insights_link/activity_and_insights_link.scss
  components/activity_and_insights/activity_and_insights_link/activity_and_insights_link.tsx
  components/activity_and_insights/activity_and_insights_link/insights_tour_tip/insights_tour_tip.tsx
  components/widgets/tour_tip/tour_tip.tsx
  i18n/en.json
  images/Insights-Preview-Image.jpg
  packages/mattermost-redux/src/actions/preferences.ts
  packages/mattermost-redux/src/constants/preferences.ts
  selectors/insights.ts
Labels: 3: QA Review, Setup Cloud + CWS Test Server, release-note-none

#10388 MM-44631 - use the enable onboarding config to show/hide the onboarding
  components/root/index.js
Labels: 2: Dev Review, Setup Cloud Test Server, QA Review Done, release-note-none

#10395 Automated cherry pick of #10311
  components/admin_console/admin_definition.jsx
  components/app_bar/__snapshots__/app_bar.test.tsx.snap
  components/app_bar/app_bar.scss
  components/app_bar/app_bar.test.tsx
  components/app_bar/app_bar.tsx
  components/app_bar/app_bar_plugin_component.tsx
  i18n/en.json
  packages/mattermost-redux/src/selectors/entities/apps.ts
  packages/types/src/config.ts
  plugins/channel_header_plug/__snapshots__/channel_header_plug.test.tsx.snap
  plugins/channel_header_plug/channel_header_plug.test.tsx
  plugins/channel_header_plug/channel_header_plug.tsx
  plugins/channel_header_plug/index.ts
  selectors/plugins.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#10393 Automated cherry pick of #9680
  components/app_bar/app_bar.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#10396 Automated cherry pick of #10388
  components/root/index.js
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#10397 Automated cherry pick of #10295
  actions/admin_actions.jsx
  packages/client/src/client4.ts
  packages/types/src/config.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#10398 Automated cherry pick of #10377
  components/header_footer_route/footer.scss
  components/header_footer_route/footer.tsx
  components/header_footer_route/header.scss
  components/header_footer_route/header.tsx
  e2e/cypress/tests/integration/signin_authentication/login_spec.js
  e2e/cypress/tests/integration/signin_authentication/signup_spec.js
  e2e/cypress/tests/integration/system_console/site_configuration/link_customization_e20_1_spec.js
  e2e/cypress/tests/integration/system_console/site_configuration/link_customization_e20_2_spec.js
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#10212 Command palette : Search and Recent searches plugin hook
  actions/hooks.js
  actions/hooks.test.js
  plugins/registry.js
  reducers/plugins/index.ts
  types/store/plugins.ts
  utils/constants.jsx
Labels: release-note-none

#10355 System console workspace limits UI (mm-43085 & mm-43594)
  components/admin_console/billing/billing_subscriptions/billing_subscriptions.scss
  components/admin_console/billing/billing_subscriptions/index.tsx
  components/admin_console/billing/billing_subscriptions/limit_card.scss
  components/admin_console/billing/billing_subscriptions/limit_card.tsx
  components/admin_console/billing/billing_subscriptions/limits.scss
  components/admin_console/billing/billing_subscriptions/limits.test.tsx
  components/admin_console/billing/billing_subscriptions/limits.tsx
  components/admin_console/billing/billing_subscriptions/mixins.scss
  components/admin_console/billing/billing_subscriptions/single_inline_limit.scss
  components/admin_console/billing/billing_subscriptions/single_inline_limit.tsx
  components/admin_console/billing/billing_subscriptions/translations.ts
  components/common/hooks/useOpenSalesLink.ts
  components/common/usage_percent_bar/index.tsx
  components/global_header/right_controls/cloud_upgrade_button/index.tsx
  components/pricing_modal/content.tsx
  i18n/en.json
  packages/mattermost-redux/src/selectors/entities/cloud.ts
  utils/constants.tsx
  utils/limits.tsx
Labels: QA Review Done, 1: UX Review, Setup Cloud + CWS Test Server, release-note-none

#10382 [MM-44495] - Update text on pricing modal
  components/pricing_modal/content.scss
  components/pricing_modal/content.tsx
  components/pricing_modal/pricing_modal.scss
  i18n/en.json
Labels: 2: Dev Review, 1: UX Review, Setup Cloud + CWS Test Server, release-note-none

#10401 Fix broken release-7.0 pipeline
  .gitlab-ci.yml
Labels: release-note-none, kind/chore

#10399 add reused hooks. Refactor pricing modal opening to consistently use …
  components/admin_console/billing/billing_subscriptions/limits.tsx
  components/announcement_bar/cloud_trial_ended_announcement_bar/index.tsx
  components/common/hooks/useGetHighestThresholdCloudLimit.test.ts
  components/common/hooks/useGetHighestThresholdCloudLimit.ts
  components/common/hooks/useGetUsage.ts
  components/common/hooks/useOpenPricingModal.ts
  components/common/usage_percent_bar/index.tsx
  components/global_header/right_controls/cloud_upgrade_button/index.tsx
  utils/limits.tsx
Labels: 2: Dev Review, Setup Cloud + CWS Test Server, release-note-none

#10389 MM-44420 - remove 14 days hardcoded values
  components/admin_console/billing/billing_subscriptions/index.tsx
  components/announcement_bar/cloud_trial_announcement_bar/cloud_trial_announcement_bar.tsx
  components/announcement_bar/cloud_trial_announcement_bar/index.ts
  components/widgets/menu/menu_items/menu_cloud_trial.tsx
  e2e/cypress/tests/support/api/preference.d.ts
  e2e/cypress/tests/support/index.js
  utils/constants.tsx
Labels: 2: Dev Review, QA Review Done, Setup Cloud + CWS Test Server, release-note-none

#10258 [MM-41326]: paginate the getPostThread API
  packages/client/src/client4.ts
  packages/client/src/helpers.ts
  packages/mattermost-redux/src/actions/posts.test.js
  packages/mattermost-redux/src/actions/posts.ts
  packages/mattermost-redux/src/actions/search.ts
  packages/types/src/client4.ts
  packages/types/src/posts.ts
Labels: 4: Reviews Complete, release-note

#10364 [MM-44473] - Fix theming and text color for pricing modal
  components/global_header/right_controls/cloud_upgrade_button/index.tsx
  components/payment_form/card_input.tsx
  components/pricing_modal/content.tsx
  components/pricing_modal/pricing_modal.scss
Labels: 2: Dev Review, QA Review Done, 1: UX Review, Setup Cloud + CWS Test Server, release-note-none

#10354 cache stylelint
  .gitignore
  package.json
Labels: release-note-none

#10415 [MM 44588] fixes: Keyboard focus not put back to post textbox after hitting ctrl+shift+p twice
  components/advanced_create_post/advanced_create_post.tsx
Labels: release-note, QA Deferred

#10348 [MM-44437]: Advanced text editor: alignment to center when channel display is set to fixed width
  components/advanced_text_editor/advanced_text_editor.scss
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note, QA Deferred

#10421 Automated cherry pick of #10415
  components/advanced_create_post/advanced_create_post.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#10374 [MM-44430]: Add resize observer to observe change in size of Advanced text editor enclosing div
  components/advanced_text_editor/formatting_bar/hooks.tsx
Labels: release-note, QA Deferred

#10424 Automated cherry pick of #10374
  components/advanced_text_editor/formatting_bar/hooks.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#10404 Mm 43595
  actions/cloud.tsx
  components/admin_console/billing/billing_subscriptions/limit_card.tsx
  components/admin_console/compliance_reports/compliance_reports.tsx
  components/admin_console/custom_url_schemes_setting.jsx
  components/admin_console/team_channel_settings/convert_and_remove_confirm_modal.jsx
  components/admin_console/team_channel_settings/convert_confirm_modal.jsx
  components/admin_console/team_channel_settings/remove_confirm_modal.jsx
  components/claim/components/email_to_ldap.jsx
  components/claim/components/email_to_oauth.jsx
  components/claim/components/ldap_to_email.jsx
  components/claim/components/oauth_to_email.jsx
  components/cloud_usage_modal/index.tsx
  components/cloud_usage_modal/lhs_nearing_limit_modal.tsx
  components/cloud_usage_modal/mini_modal.tsx
  components/cloud_usage_modal/workspace_limits_panel.tsx
  components/create_post/prewritten_chips.tsx
  components/emoji/emoji_list/emoji_list.tsx
  components/emoji_picker/constants/index.ts
  components/gif_picker/components/SearchBar/index.jsx
  components/global_header/left_controls/product_menu/product_menu_list/__snapshots__/product_menu_list.test.tsx.snap
  components/global_header/left_controls/product_menu/product_menu_list/product_menu_list.tsx
  components/integrations/abstract_command.jsx
  components/invitation_modal/invite_view.tsx
  components/mfa/setup/setup.tsx
  components/password_reset_form/password_reset_form.tsx
  components/password_reset_send_link/password_reset_send_link.tsx
  components/post_view/channel_intro_message/channel_intro_message.tsx
  components/team_general_tab/team_general_tab.jsx
  components/user_settings/notifications/desktop_notification_settings.jsx
  components/widgets/inputs/channels_input.tsx
  components/widgets/inputs/users_emails_input.tsx
  components/widgets/menu/menu.tsx
  components/widgets/menu/menu_items/menu_cloud_trial.test.tsx
  components/widgets/menu/menu_items/menu_cloud_trial.tsx
  components/widgets/menu/menu_items/menu_item.scss
  components/widgets/menu/menu_items/menu_item_cloud_limit.test.tsx
  components/widgets/menu/menu_items/menu_item_cloud_limit.tsx
  components/widgets/menu/menu_items/useWords.test.tsx
  components/widgets/menu/menu_items/useWords.tsx
  i18n/en.json
  packages/mattermost-redux/src/selectors/entities/general.ts
  packages/types/src/boards.ts
  packages/types/src/cloud.ts
  utils/i18n.tsx
Labels: 2: Dev Review, QA Review Done, Setup Cloud + CWS Test Server, release-note-none

#10384 Advanced Text Editor UX changes
  components/advanced_create_comment/__snapshots__/advanced_create_comment.test.jsx.snap
  components/advanced_create_comment/advanced_create_comment.tsx
  components/advanced_create_post/__snapshots__/advanced_create_post.test.jsx.snap
  components/advanced_create_post/advanced_create_post.tsx
  components/advanced_text_editor/advanced_text_editor.scss
  components/advanced_text_editor/advanced_text_editor.tsx
  components/advanced_text_editor/formatting_bar/formatting_bar.tsx
  components/file_upload/__snapshots__/file_upload.test.jsx.snap
  components/file_upload/file_upload.jsx
  components/file_upload/index.js
  sass/components/_post.scss
Labels: 4: Reviews Complete, release-note

#10387 [MM-44475] Team Unarchive: Do not allow to unarchive if workspace has reached the limit of teams
  actions/cloud.tsx
  actions/websocket_actions.jsx
  components/admin_console/billing/billing_subscriptions/limits.test.tsx
  components/admin_console/team_channel_settings/team/details/__snapshots__/team_details.test.jsx.snap
  components/admin_console/team_channel_settings/team/details/__snapshots__/team_profile.test.jsx.snap
  components/admin_console/team_channel_settings/team/details/__snapshots__/team_profile.test.tsx.snap
  components/admin_console/team_channel_settings/team/details/index.js
  components/admin_console/team_channel_settings/team/details/team_details.jsx
  components/admin_console/team_channel_settings/team/details/team_profile.jsx
  components/admin_console/team_channel_settings/team/details/team_profile.scss
  components/admin_console/team_channel_settings/team/details/team_profile.test.jsx
  components/admin_console/team_channel_settings/team/details/team_profile.test.tsx
  components/announcement_bar/cloud_trial_ended_announcement_bar/cloud_trial_ended_announcement_bar.test.tsx
  components/announcement_bar/cloud_trial_ended_announcement_bar/index.tsx
  components/cloud_usage_modal/index.test.tsx
  components/common/hooks/useGetHighestThresholdCloudLimit.test.ts
  components/common/hooks/useGetUsage.ts
  components/common/hooks/useGetUsageDeltas.ts
  i18n/en.json
  packages/client/src/client4.ts
  packages/mattermost-redux/src/action_types/cloud.ts
  packages/mattermost-redux/src/reducers/entities/usage.ts
  packages/mattermost-redux/src/selectors/entities/teams.ts
  packages/mattermost-redux/src/store/initial_state.ts
  packages/types/src/cloud.ts
  packages/types/src/posts.ts
  utils/limits.tsx
  webpack.config.js
Labels: CherryPick/Approved, QA Review Done, 1: UX Review, Setup Cloud + CWS Test Server, release-note-none

#10410 [MM-44439] Add a banner to billing_subscriptions page for grandfathered instances
  components/__snapshots__/alert_banner.test.tsx.snap
  components/admin_console/billing/billing_subscriptions/billing_subscriptions.tsx
  components/admin_console/billing/billing_subscriptions/index.tsx
  components/alert_banner.scss
  components/alert_banner.test.tsx
  components/alert_banner.tsx
  i18n/en.json
Labels: QA Review Done, 1: UX Review, Setup Cloud + CWS Test Server, release-note-none

#10427 Fix master pipeline
  components/widgets/menu/menu_items/menu_cloud_trial.test.tsx
  components/widgets/menu/menu_items/menu_item_cloud_limit.test.tsx
Labels: release-note-none

#10430 Automated cherry pick of #10427
  components/widgets/menu/menu_items/menu_cloud_trial.test.tsx
  components/widgets/menu/menu_items/menu_item_cloud_limit.test.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#10429 Automated cherry pick of #10410
  components/__snapshots__/alert_banner.test.tsx.snap
  components/admin_console/billing/billing_subscriptions/billing_subscriptions.tsx
  components/admin_console/billing/billing_subscriptions/index.tsx
  components/alert_banner.scss
  components/alert_banner.test.tsx
  components/alert_banner.tsx
  i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#10432 Automated cherry pick of #10384
  components/advanced_create_comment/__snapshots__/advanced_create_comment.test.jsx.snap
  components/advanced_create_comment/advanced_create_comment.tsx
  components/advanced_create_post/__snapshots__/advanced_create_post.test.jsx.snap
  components/advanced_create_post/advanced_create_post.tsx
  components/advanced_text_editor/advanced_text_editor.scss
  components/advanced_text_editor/advanced_text_editor.tsx
  components/advanced_text_editor/formatting_bar/formatting_bar.tsx
  components/file_upload/__snapshots__/file_upload.test.jsx.snap
  components/file_upload/file_upload.jsx
  components/file_upload/index.js
  sass/components/_post.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#10434 Automated cherry pick of #10406
  components/create_team_restricted_modal/create_team_restricted_modal.scss
  components/create_team_restricted_modal/create_team_restricted_modal.tsx
  components/main_menu/__snapshots__/main_menu.test.tsx.snap
  components/main_menu/index.tsx
  components/main_menu/main_menu.test.tsx
  components/main_menu/main_menu.tsx
  components/sidebar/sidebar_header/sidebar_header.test.tsx
  components/sidebar/sidebar_header/sidebar_header.tsx
  components/widgets/menu/menu_items/menu_item.scss
  components/widgets/menu/menu_items/menu_item_link.test.tsx
  components/widgets/menu/menu_items/menu_item_link.tsx
  i18n/en.json
  plugins/test/__snapshots__/main_menu_action.test.jsx.snap
  plugins/test/main_menu_action.test.jsx
  utils/constants.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none
