Repository mattermost/mattermost-webapp, pull requests merged in 2022-12, with the labels that each got.

#11696 Upgrade Web app to React 17 (#11558)
  .circleci/config.yml
  .npmrc
  Makefile
  components/__snapshots__/searchable_channel_list.test.jsx.snap
  components/__snapshots__/textbox.test.tsx.snap
  components/admin_console/data_retention_settings/channel_list/__snapshots__/channel_list.test.tsx.snap
  components/admin_console/system_roles/system_role/system_role_users/__snapshots__/system_role_users.test.tsx.snap
  components/admin_console/system_users/list/__snapshots__/system_users_list.test.tsx.snap
  components/admin_console/team_channel_settings/channel/details/__snapshots__/channel_groups.test.tsx.snap
  components/admin_console/team_channel_settings/channel/details/channel_members/__snapshots__/channel_members.test.tsx.snap
  components/admin_console/team_channel_settings/channel/list/__snapshots__/channel_list.test.tsx.snap
  components/admin_console/team_channel_settings/team/details/__snapshots__/team_groups.test.tsx.snap
  components/admin_console/team_channel_settings/team/details/team_members/__snapshots__/team_members.test.tsx.snap
  components/channel_header_dropdown/__snapshots__/channel_header_dropdown.test.tsx.snap
  components/global_header/left_controls/product_menu/product_menu_list/__snapshots__/product_menu_list.test.tsx.snap
  components/main_menu/__snapshots__/main_menu.test.tsx.snap
  components/plugin_marketplace/__snapshots__/marketplace_modal.test.tsx.snap
  components/post_view/channel_intro_message/__snapshots__/channel_intro_message.test.tsx.snap
  components/profile_popover/__snapshots__/profile_popover.test.tsx.snap
  components/select_team/components/__snapshots__/select_team_item.test.tsx.snap
  components/sidebar/__snapshots__/invite_members_button.test.tsx.snap
  components/status_dropdown/__snapshots__/status_dropdown.test.tsx.snap
  components/user_group_popover/__snapshots__/user_group_popover.test.tsx.snap
  components/user_settings/security/__snapshots__/user_settings_security.test.tsx.snap
  e2e/cypress/utils/dashboard.js
  package-lock.json
  package.json
  packages/components/package.json
  plugins/test/__snapshots__/main_menu_action.test.jsx.snap
  tests/setup.js
  webpack.config.js
Labels: 2: Dev Review, release-note

#11688 MM-47860 - Air Gapped Modal (Cherry-Picking into self-hosted-accounts)
  components/air_gapped_self_hosted_purchase_modal/content.scss
  components/air_gapped_self_hosted_purchase_modal/index.tsx
  components/common/hooks/useOpenAirGappedSelfHostedPurchaseModal.ts
  components/pricing_modal/self_hosted_content.tsx
  e2e/cypress/tests/integration/enterprise/cloud/billing/self_hosted_pricing_modal_spec.js
  i18n/en.json
  utils/constants.tsx
Labels: release-note-none

#11698 Automated cherry pick of #11635
  components/__snapshots__/list_modal.test.jsx.snap
  components/__snapshots__/searchable_channel_list.test.jsx.snap
  components/access_history_modal/__snapshots__/access_history_modal.test.tsx.snap
  components/admin_console/custom_terms_of_service_settings/__snapshots__/custom_terms_of_service_settings.test.tsx.snap
  components/admin_console/manage_teams_modal/__snapshots__/manage_teams_modal.test.tsx.snap
  components/admin_console/manage_tokens_modal/__snapshots__/manage_tokens_modal.test.tsx.snap
  components/admin_console/permission_schemes_settings/__snapshots__/permission_schemes_settings.test.tsx.snap
  components/admin_console/permission_schemes_settings/permission_system_scheme_settings/__snapshots__/permission_system_scheme_settings.test.tsx.snap
  components/admin_console/permission_schemes_settings/permission_team_scheme_settings/__snapshots__/permission_team_scheme_settings.test.tsx.snap
  components/channel_header/channel_info_button.tsx
  components/channel_info_rhs/index.ts
  components/channel_layout/channel_controller.tsx
  components/common/__snapshots__/infinite_scroll.test.tsx.snap
  components/integrations/edit_command/__snapshots__/edit_command.test.tsx.snap
  components/integrations/edit_incoming_webhook/__snapshots__/edit_incoming_webhook.test.tsx.snap
  components/integrations/edit_outgoing_webhook/__snapshots__/edit_outgoing_webhook.test.tsx.snap
  components/loading_screen.tsx
  components/logged_in/logged_in.test.tsx
  components/login/login.test.tsx
  components/needs_team/needs_team.tsx
  components/plugin_marketplace/__snapshots__/marketplace_modal.test.tsx.snap
  components/post_view/__snapshots__/post_view.test.tsx.snap
  components/post_view/post_list/post_list.tsx
  components/post_view/post_view.tsx
  components/search_results/index.tsx
  components/search_results_item/index.ts
  components/select_team/__snapshots__/select_team.test.tsx.snap
  components/sidebar_right/index.ts
  components/sidebar_right/sidebar_right.tsx
  components/terms_of_service/__snapshots__/terms_of_service.test.tsx.snap
  components/threading/global_threads/thread_list/__snapshots__/virtualized_thread_list_row.test.tsx.snap
  components/view_user_group_modal/__snapshots__/view_user_group_modal.test.tsx.snap
  e2e/cypress/tests/integration/channel/channel_info_rhs_spec.js
  e2e/cypress/tests/integration/channel/open_rhs_coming_from_system_console_spec.ts
  e2e/cypress/tests/support/ui/global_header.d.ts
  e2e/cypress/tests/support/ui/global_header.js
  sass/components/_post.scss
  sass/layout/_sidebar-right.scss
  sass/routes/_loading.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#11699 Automated cherry pick of #11689
  components/sidebar_right/sidebar_right.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#11704 [MM-48772] Fix Drafts Save to Wrong Channel
  components/advanced_create_post/advanced_create_post.test.jsx
  components/advanced_create_post/advanced_create_post.tsx
  components/advanced_create_post/index.ts
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#11710 Automated cherry pick of #11704
  components/advanced_create_post/advanced_create_post.test.jsx
  components/advanced_create_post/advanced_create_post.tsx
  components/advanced_create_post/index.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#11708 Automated cherry pick of #11704
  components/advanced_create_post/advanced_create_post.test.jsx
  components/advanced_create_post/advanced_create_post.tsx
  components/advanced_create_post/index.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#11641 MM-46597: Unreads button in channel sidebar is missing alt text for screen readers
  components/sidebar/channel_filter/__snapshots__/channel_filter.test.tsx.snap
  components/sidebar/channel_filter/channel_filter.tsx
  i18n/en.json
Labels: 4: Reviews Complete, release-note, Contributor

#11249 [MM-46251] Change activeUsers type: string -> string[]
  components/activity_and_insights/insights/top_boards/top_boards.test.tsx
  components/activity_and_insights/insights/top_boards/top_boards.tsx
  components/activity_and_insights/insights/top_boards/top_boards_table/top_boards_table.test.tsx
  components/activity_and_insights/insights/top_boards/top_boards_table/top_boards_table.tsx
  packages/types/src/insights.ts
Labels: release-note-none

#11712 MM-48688 Add separate benchmark flow for master/release branches
  .github/workflows/performance-benchmarks.yml
Labels: 4: Reviews Complete, release-note-none

#11705 [MM-48798] - Typo in pricing modal
  components/pricing_modal/content.tsx
  i18n/en.json
Labels: 2: Dev Review, 3: QA Review, Setup Cloud + CWS Test Server, release-note-none

#11703 MM-48126 - Display an in progress indicator on downgrade
  components/common/hooks/useOpenDowngradeModal.ts
  components/common/svg_images_components/getting_started_svg.tsx
  components/downgrade_modal/index.scss
  components/downgrade_modal/index.tsx
  components/pricing_modal/content.tsx
  e2e/cypress/tests/integration/enterprise/cloud/billing/cloud_pricing_modal_spec.js
  utils/constants.tsx
Labels: Setup Cloud + CWS Test Server, release-note-none

#11624 [MM-42008] Fix getting data when checking if team exists
  components/create_team/components/team_url/index.ts
  components/create_team/components/team_url/team_url.test.tsx
  components/create_team/components/team_url/team_url.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none

#11645 [MM-48498] Fixes custom status modal not closing when adding custom emoji
  components/custom_status/custom_status_modal.tsx
Labels: release-note

#11611 [MM-46415] Code block copy bugfix
  components/code_block/code_block.tsx
Labels: 4: Reviews Complete, release-note

#11618 [MM-47760] Bugfix: filter out threads with deleted replies
  packages/mattermost-redux/src/selectors/entities/threads.ts
Labels: 4: Reviews Complete, release-note

#11657 chore: upgrade to cypress@11.2.0 and its dependencies
  e2e/cypress/package-lock.json
  e2e/cypress/package.json
Labels: 4: Reviews Complete, release-note-none

#11694 MM-48609 : channels/DM/GMs moveTo sub menu options revise
  components/category_menu_items/category_menu_items.tsx
  components/category_menu_items/index.ts
  components/channel_header_dropdown/__snapshots__/channel_header_dropdown.test.tsx.snap
  components/channel_header_dropdown/channel_header_dropdown_items.tsx
  components/channel_move_to_sub_menu/index.tsx
  components/sidebar/sidebar_channel/sidebar_channel_menu/__snapshots__/sidebar_channel_menu.test.tsx.snap
  components/sidebar/sidebar_channel/sidebar_channel_menu/sidebar_channel_menu.tsx
Labels: 4: Reviews Complete, release-note-none

#11725 [MM-48207] Upgrade concurrently - minor version upgrade
  package-lock.json
  package.json
Labels: 4: Reviews Complete, release-note-none, QA Deferred

#11728 Automated cherry pick of #11712
  .github/workflows/performance-benchmarks.yml
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#11709 Stop exposing components package as a shared module for now
  package-lock.json
  package.json
  webpack.config.js
Labels: 4: Reviews Complete, release-note-none

#11682 MM-48744 - enhance telemetry info when trial started from the learn more about trial modal
  components/cloud_start_trial/cloud_start_trial_btn.test.tsx
  components/cloud_start_trial/cloud_start_trial_btn.tsx
  components/custom_open_pricing_modal_post_renderer/index.tsx
  components/learn_more_trial_modal/learn_more_trial_modal.tsx
  components/learn_more_trial_modal/start_trial_btn.test.tsx
  components/learn_more_trial_modal/start_trial_btn.tsx
  components/onboarding_tasks/onboarding_tasks_manager.tsx
  components/widgets/menu/menu_items/menu_cloud_trial.tsx
Labels: 2: Dev Review, Setup Cloud Test Server, release-note-none

#11718 MM-48773: fixes position of ACK users popover
  components/post_view/acknowledgements/post_acknowledgements.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#11719 MM-48565: fixes delay in channel urgent mention
  actions/websocket_actions.jsx
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#11720 MM-48831: fixes displaying of first acknowledgement
  packages/mattermost-redux/src/reducers/entities/posts.ts
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#11744 Automated cherry pick of #11720
  packages/mattermost-redux/src/reducers/entities/posts.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#11672 MM-48120/MM-48623 Add ExperimentalSettings.PatchPluginsReactDOM to the System Console
  components/admin_console/admin_definition.jsx
  e2e/playwright/support/server/default_config.ts
  i18n/en.json
  packages/types/src/config.ts
Labels: 4: Reviews Complete, CherryPick/Approved, AutoMerge, release-note-none

#11746 Automated cherry pick of #11672
  components/admin_console/admin_definition.jsx
  e2e/playwright/support/server/default_config.ts
  i18n/en.json
  packages/types/src/config.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#11747 Automated cherry pick of #11701
  components/admin_console/license_settings/enterprise_edition/enterprise_edition_left_panel.tsx
  i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#11740 Automated cherry pick of #11719
  actions/websocket_actions.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#11748 Automated cherry pick of #11701
  components/admin_console/license_settings/enterprise_edition/enterprise_edition_left_panel.tsx
  i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#11713 MM-48778: Render strikethrough on at-mentions in posts.
  sass/components/_mentions.scss
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, AutoMerge, release-note

#11752 Automated cherry pick of #11713
  sass/components/_mentions.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#11751 Automated cherry pick of #11713
  sass/components/_mentions.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#11692 [MM-48727] Restore license checks for SSO in self-hosted deployments - admin console
  components/admin_console/admin_definition.jsx
  components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.tsx.snap
Labels: 3: QA Review, CherryPick/Approved, release-note-none

#11756 Automated cherry pick of #11692
  components/admin_console/admin_definition.jsx
  components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.tsx.snap
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#11755 Automated cherry pick of #11692
  components/admin_console/admin_definition.jsx
  components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.tsx.snap
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#11668 [MM-46463] Use last_picture_update in insights
  components/activity_and_insights/insights/top_dms_and_new_members/new_members_item/new_members_item.tsx
Labels: 4: Reviews Complete, release-note

#11632 [MM-48572] : Replace --center-channel-text css variable with --center-channel-color
  components/admin_console/billing/billing_subscriptions/limit_card.scss
  components/admin_console/billing/billing_subscriptions/single_inline_limit.scss
  components/admin_console/billing/billing_summary/upsell_card.scss
  components/archived_preview.tsx
  components/center_message_lock/index.scss
  components/center_message_lock/index.tsx
  components/channel_members_rhs/member.tsx
  components/cloud_start_trial/request_business_email_modal.scss
  components/common/accordion/accordion.scss
  components/common/carousel/carousel.scss
  components/custom_open_pricing_modal_post_renderer/index.tsx
  components/external_login_button/external_login_button.scss
  components/feature_restricted_modal/feature_restricted_modal.scss
  components/file_attachment/file_attachment.tsx
  components/header_footer_route/content_layouts/alternate_link.scss
  components/header_footer_route/content_layouts/column.scss
  components/header_footer_route/footer.scss
  components/header_footer_route/header.scss
  components/login/login.scss
  components/post_priority/post_priority_picker_item.tsx
  components/pricing_modal/pricing_modal.scss
  components/pricing_modal/start_trial_caution.tsx
  components/search_results/search_limits_banner.tsx
  components/signup/signup.scss
  components/three_days_left_trial_modal/three_days_left_trial_modal.scss
  components/user_groups_modal/user_groups_modal.scss
  components/widgets/menu/menu_items/menu_item.scss
  components/widgets/menu/menu_items/restricted_indicator.scss
  components/widgets/public-private-selector/public-private-selector.scss
  sass/base/_css_variables.scss
  sass/components/_files.scss
  sass/layout/_markdown.scss
  sass/utils/_mixins.scss
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note

#11758 Cherry-picking translations into cloud
  i18n/de.json
  i18n/en_AU.json
  i18n/ja.json
  i18n/nl.json
  i18n/pl.json
  i18n/ru.json
  i18n/sv.json
Labels: 2: Dev Review, 3: QA Review, release-note-none, Contributor

#11730 [MM-48096] Delinquency banner text change
  components/announcement_bar/cloud_delinquency/index.tsx
  i18n/en.json
Labels: 2: Dev Review, release-note-none

#11139 [Mm 44864] Too long time stamp announcement
  components/post_view/post_time/post_time.tsx
  components/threading/channel_threads/thread_footer/__snapshots__/thread_footer.test.tsx.snap
  components/timestamp/__snapshots__/semantic_time.test.tsx.snap
  components/timestamp/semantic_time.test.tsx
  components/timestamp/semantic_time.tsx
  components/timestamp/timestamp.test.tsx
  components/timestamp/timestamp.tsx
Labels: 4: Reviews Complete, release-note, Contributor

#11638 [MM-47566] Show upcoming invoice in subscription screen if present
  components/admin_console/billing/billing_summary/billing_summary.scss
  components/admin_console/billing/billing_summary/billing_summary.tsx
  components/admin_console/billing/billing_summary/index.tsx
  i18n/en.json
  packages/types/src/cloud.ts
Labels: 4: Reviews Complete, release-note-none, QA Deferred

#11750 [MM-48748] Close RHS when opening global drafts
  components/drafts/drafts.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#11762 Automated cherry pick of #11750
  components/drafts/drafts.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#11761 Automated cherry pick of #11750
  components/drafts/drafts.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#11749 [MM-48771] Mentions fixes
  components/at_mention/at_mention.test.tsx
  components/at_mention/at_mention.tsx
  sass/components/_mentions.scss
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, AutoMerge, release-note-none

#11765 Automated cherry pick of #11749
  components/at_mention/at_mention.test.tsx
  components/at_mention/at_mention.tsx
  sass/components/_mentions.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#11764 Automated cherry pick of #11749
  components/at_mention/at_mention.test.tsx
  components/at_mention/at_mention.tsx
  sass/components/_mentions.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#11681 [MM-46461] Get user information from store for insights
  components/activity_and_insights/insights/top_dms_and_new_members/new_members_item/new_members_item.tsx
Labels: release-note

#11738 [MM-48889] Catch error when attempting to delete draft
  actions/views/drafts.ts
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#11768 Automated cherry pick of #11738
  actions/views/drafts.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#11754 MM-48905 Add MM_DONT_INCLUDE_PRODUCTS to build web app for production without products included
  webpack.config.js
Labels: 4: Reviews Complete, release-note-none

#11771 Automated cherry pick of #11754
  webpack.config.js
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#11652 [MM-47966] Improve accessibility for user group popovers
  components/at_mention/at_mention_group.tsx
  components/user_group_popover/__snapshots__/user_group_popover.test.tsx.snap
  components/user_group_popover/group_member_list/__snapshots__/group_member_list.test.tsx.snap
  components/user_group_popover/group_member_list/group_member_list.tsx
  components/user_group_popover/user_group_popover.test.tsx
  components/user_group_popover/user_group_popover.tsx
  sass/components/_mentions.scss
Labels: 3: QA Review, Setup Cloud Test Server, release-note-none

#11772 Automated cherry pick of #11652
  components/at_mention/at_mention_group.tsx
  components/user_group_popover/__snapshots__/user_group_popover.test.tsx.snap
  components/user_group_popover/group_member_list/__snapshots__/group_member_list.test.tsx.snap
  components/user_group_popover/group_member_list/group_member_list.tsx
  components/user_group_popover/user_group_popover.test.tsx
  components/user_group_popover/user_group_popover.tsx
  sass/components/_mentions.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#11715 [MM-48818]: Fix bugs related to yearly subscriptions
  components/pricing_modal/content.tsx
  components/purchase_modal/purchase_modal.tsx
  e2e/cypress/tests/integration/enterprise/cloud/billing/cloud_pricing_modal_spec.js
  i18n/en.json
Labels: CherryPick/Approved, 1: UX Review, Setup Cloud + CWS Test Server, release-note-none

#11774 Automated cherry pick of #11715
  components/pricing_modal/content.tsx
  components/purchase_modal/purchase_modal.tsx
  e2e/cypress/tests/integration/enterprise/cloud/billing/cloud_pricing_modal_spec.js
  i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#11770 MM-48897: Reverts text change.
  components/analytics/activated_users_card/index.tsx
  e2e/cypress/tests/integration/enterprise/system_console/reporting/site_statistics_spec.js
  e2e/cypress/tests/integration/system_console/reporting/site_statistics_te_spec.js
  e2e/cypress/tests/integration/system_console/reporting/team_statistics_spec.js
  i18n/en.json
  i18n/en_AU.json
Labels: Docs/Needed, CherryPick/Approved, release-note-none, QA Deferred

#11737 MM-48824 - move onboarding tasklist to logged in component
  components/logged_in/index.ts
  components/logged_in/logged_in.test.tsx
  components/logged_in/logged_in.tsx
  components/root/root.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none

#11753 MM-48819 Increase timeout for benchmark tests
  .github/workflows/performance-benchmarks.yml
Labels: 2: Dev Review, release-note-none

#11475 [MM-47843] Work Template Modal (read-only)
  components/common/accordion/accordion.tsx
  components/global_header/left_controls/product_menu/product_menu_list/__snapshots__/product_menu_list.test.tsx.snap
  components/global_header/left_controls/product_menu/product_menu_list/index.ts
  components/global_header/left_controls/product_menu/product_menu_list/product_menu_list.tsx
  components/timestamp/timestamp.tsx
  components/work_templates/components/customize.tsx
  components/work_templates/components/menu.tsx
  components/work_templates/components/menu/use_case.tsx
  components/work_templates/components/modal.tsx
  components/work_templates/components/preview.tsx
  components/work_templates/components/preview/accordion.tsx
  components/work_templates/components/preview/chip.tsx
  components/work_templates/components/preview/section.tsx
  components/work_templates/dev_data.ts
  components/work_templates/index.tsx
  components/work_templates/utils.ts
  i18n/en.json
  packages/mattermost-redux/src/action_types/index.ts
  packages/mattermost-redux/src/action_types/work_templates.ts
  packages/mattermost-redux/src/actions/work_templates.ts
  packages/mattermost-redux/src/reducers/entities/index.ts
  packages/mattermost-redux/src/reducers/entities/work_templates.ts
  packages/mattermost-redux/src/store/initial_state.ts
  packages/types/src/store.ts
  packages/types/src/utilities.ts
  packages/types/src/work_templates.ts
  utils/conditional_types.ts
  utils/constants.tsx
Labels: 2: Dev Review, Setup Cloud Test Server, 1: UX Review, release-note-none

#11782 Cypress/E2E: Enable open server explicitly and remove unnecessary config change
  .github/workflows/performance-benchmarks.yml
  e2e/cypress/tests/integration/auth_sso/authentication_1_spec.ts
  e2e/cypress/tests/integration/auth_sso/authentication_4_spec.ts
  e2e/cypress/tests/integration/enterprise/auth_sso/authentication_spec.js
  e2e/cypress/tests/integration/onboarding/existing_email_adress_spec.js
  e2e/cypress/tests/integration/signin_authentication/login_open_server_spec.js
Labels: 4: Reviews Complete, release-note-none

#11775 Automated cherry pick of #11770
  components/analytics/activated_users_card/index.tsx
  e2e/cypress/tests/integration/enterprise/system_console/reporting/site_statistics_spec.js
  e2e/cypress/tests/integration/system_console/reporting/site_statistics_te_spec.js
  e2e/cypress/tests/integration/system_console/reporting/team_statistics_spec.js
  i18n/en.json
  i18n/en_AU.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#11656 MM-48838 : Introduce formatjs eslint plugin and add multiple spaces rules
  .eslintrc.json
  components/admin_console/__snapshots__/cluster_settings.test.jsx.snap
  components/admin_console/billing/billing_subscriptions/billing_subscriptions.tsx
  components/admin_console/billing/billing_subscriptions/limits.tsx
  components/admin_console/cluster_settings.jsx
  components/admin_console/system_users/system_users_dropdown/__snapshots__/system_users_dropdown.test.tsx.snap
  components/admin_console/system_users/system_users_dropdown/system_users_dropdown.tsx
  components/integrations/__snapshots__/abstract_incoming_hook.test.tsx.snap
  components/integrations/__snapshots__/abstract_outgoing_webhook.test.jsx.snap
  components/integrations/abstract_incoming_webhook.jsx
  components/integrations/abstract_outgoing_webhook.jsx
  components/team_general_tab/__snapshots__/open_invite.test.tsx.snap
  components/team_general_tab/open_invite.tsx
  components/user_settings/advanced/user_settings_advanced.tsx
  i18n/en.json
  package-lock.json
  package.json
Labels: 4: Reviews Complete, release-note, QA Deferred

#11778 [MM-48987] Removing team insights if no enterprise build available
  components/activity_and_insights/insights/hooks.ts
  components/activity_and_insights/insights/insights.tsx
  components/activity_and_insights/insights/insights_header/insights_header.scss
  components/activity_and_insights/insights/insights_title/insights_title.tsx
Labels: CherryPick/Approved, QA Review Done, release-note

#11787 Automated cherry pick of #11778
  components/activity_and_insights/insights/hooks.ts
  components/activity_and_insights/insights/insights.tsx
  components/activity_and_insights/insights/insights_header/insights_header.scss
  components/activity_and_insights/insights/insights_title/insights_title.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#11714 remove duplicate text
  components/pricing_modal/content.tsx
  components/pricing_modal/self_hosted_content.tsx
  i18n/en.json
Labels: 2: Dev Review, Setup Cloud Test Server, QA Review Done, release-note

#11722 MM-47967 : Migrate /support/notification.js e2e file to TypeScript
  e2e/cypress/tests/support/notification.ts
Labels: 4: Reviews Complete, release-note-none, Contributor

#11723 MM-48833 : Remove 'form-data' npm package
  NOTICE.txt
  package-lock.json
  package.json
  packages/client/package.json
  packages/client/src/client4.ts
  packages/mattermost-redux/src/actions/admin.test.js
  packages/mattermost-redux/src/actions/files.test.js
  packages/mattermost-redux/src/actions/files.ts
Labels: 4: Reviews Complete, release-note-none

#11793 Automated cherry pick of #11641
  components/sidebar/channel_filter/__snapshots__/channel_filter.test.tsx.snap
  components/sidebar/channel_filter/channel_filter.tsx
  i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#11401 MM-47111 : Migrate "components/emoji_picker/emoji_picker_tabs" to typescript
  components/emoji_picker/emoji_picker_overlay.tsx
  components/emoji_picker/emoji_picker_tabs.tsx
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted, release-note-none, Contributor

#11795 MM-49053 Fix backwards if statement around MPA initialization
  webpack.config.js
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#11779 [MM-48652] call backend api for work templates
  components/work_templates/components/menu.tsx
  components/work_templates/dev_data.ts
  components/work_templates/index.tsx
  packages/client/src/client4.ts
  packages/mattermost-redux/src/action_types/work_templates.ts
  packages/mattermost-redux/src/actions/work_templates.ts
  packages/mattermost-redux/src/reducers/entities/work_templates.test.js
  packages/mattermost-redux/src/reducers/entities/work_templates.ts
  packages/types/src/work_templates.ts
Labels: 2: Dev Review, Setup Cloud Test Server, release-note-none

#11659 MM-48661 : Sync the latest userId in analytics
  components/common/hooks/useTelemetryIdentifySync.tsx
  components/team_controller/team_controller.tsx
  packages/mattermost-redux/src/actions/users.test.js
  packages/mattermost-redux/src/actions/users.ts
Labels: 4: Reviews Complete, release-note-none, QA Deferred

#11781 MM-48824 - remove unnecessary theme prop from LoggedIn Component
  components/logged_in/index.ts
  components/logged_in/logged_in.test.tsx
  components/logged_in/logged_in.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none

#11797 Updated Cloud admin docs links in-product
  components/admin_console/admin_navbar_dropdown/admin_navbar_dropdown.tsx
  e2e/cypress/tests/integration/system_console/main_menu_spec.js
Labels: 4: Reviews Complete, release-note

#11801 MM-48567 Fix Boards button in app bar appearing below divider
  components/app_bar/app_bar.tsx
  utils/constants.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note

#11800 MM-48567 Fix Client4 and ability to create a board with a channel in MPA
  components/keyboard_shortcuts/keyboard_shortcuts_modal/keyboard_shortcuts_modal.test.tsx
  components/keyboard_shortcuts/keyboard_shortcuts_modal/keyboard_shortcuts_modal.tsx
  components/new_channel_modal/new_channel_modal.tsx
  components/new_channel_modal/selectors.ts
  e2e/cypress/tests/integration/channel/new_channel_with_board_spec.js
  packages/client/src/client4.ts
  plugins/products.test.ts
  plugins/products.ts
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note, QA Deferred

#11789 [MM-49023] Add backwards compatibility for board insights activeUsers type
  components/activity_and_insights/insights/top_boards/top_boards.test.tsx
  components/activity_and_insights/insights/top_boards/top_boards.tsx
  components/activity_and_insights/insights/top_boards/top_boards_table/top_boards_table.test.tsx
  components/activity_and_insights/insights/top_boards/top_boards_table/top_boards_table.tsx
  packages/types/src/insights.ts
Labels: 4: Reviews Complete, release-note-none

#11733 [MM-48745] Sync Existing Drafts
  actions/views/drafts.ts
  components/drafts/drafts_link.tsx
  reducers/storage.ts
  selectors/drafts.ts
  tests/redux-persist_mock.js
  types/store/draft.ts
  utils/storage_utils.ts
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, release-note-none

#11695 MM-47563 : Text inside Cancel Button is not aligned
  sass/components/_channel-invite-modal.scss
Labels: 4: Reviews Complete, release-note-none, Contributor

#11727 [MM-44348] Show number of group members in group autocomplete
  components/suggestion/at_mention_provider/at_mention_suggestion.tsx
  i18n/en.json
  sass/components/_suggestion-list.scss
Labels: Setup Cloud Test Server, release-note

#11786 feat(cypress) : Check empty billing screen test
  e2e/cypress/tests/integration/enterprise/cloud/billing/billing_history_free_trial_spec.js
  e2e/cypress/tests/integration/enterprise/cloud/billing/billing_history_free_trial_spec.ts
Labels: release-note-none

#11763 Find a way to store and compare artifacts from the performance tests
  .github/workflows/performance-benchmarks.yml
  .gitignore
  e2e/cypress/tests/integration/performance/channel_switch_spec.js
  e2e/cypress/tests/integration/performance/team_switch_spec.js
  e2e/cypress/tests/integration/performance/utils.js
Labels: 2: Dev Review, 3: QA Review, release-note-none

#11711 MM-48687 - Billing History is not showing empty state when no invoices are listed
  components/admin_console/billing/billing_history.tsx
  e2e/cypress/tests/integration/enterprise/cloud/billing/billing_history_free_trial_spec.js
  e2e/cypress/tests/integration/enterprise/cloud/billing/billing_history_free_trial_spec.ts
Labels: 2: Dev Review, 3: QA Review, Setup Cloud Test Server, release-note-none

#11616 [MM-47634] Changed slash command description text
  components/integrations/__snapshots__/abstract_command.test.jsx.snap
  components/integrations/abstract_command.jsx
  i18n/en.json
Labels: 4: Reviews Complete, release-note

#11806 [MM-45615]: Fix problem where "View plans" button pushes Search box to the left
  components/global_header/center_controls/center_controls.tsx
  components/global_header/left_controls/left_controls.tsx
  components/global_header/right_controls/right_controls.tsx
Labels: 2: Dev Review, Setup Cloud Test Server, QA Review Done, release-note-none

#11777 [MM-47846] Retrieve playbook templates
  packages/mattermost-redux/src/action_types/index.ts
  packages/mattermost-redux/src/action_types/playbooks.ts
  packages/mattermost-redux/src/reducers/entities/work_templates.ts
  packages/mattermost-redux/src/store/initial_state.ts
  packages/types/src/work_templates.ts
Labels: 2: Dev Review, release-note-none

#11794 MM-48895 : Remove tab index on collapsed channel link in sidebar
  components/sidebar/sidebar_channel/__snapshots__/sidebar_channel.test.tsx.snap
  components/sidebar/sidebar_channel/sidebar_base_channel/__snapshots__/sidebar_base_channel.test.tsx.snap
  components/sidebar/sidebar_channel/sidebar_base_channel/sidebar_base_channel.test.tsx
  components/sidebar/sidebar_channel/sidebar_base_channel/sidebar_base_channel.tsx
  components/sidebar/sidebar_channel/sidebar_channel.tsx
  components/sidebar/sidebar_channel/sidebar_channel_link/__snapshots__/sidebar_channel_link.test.tsx.snap
  components/sidebar/sidebar_channel/sidebar_channel_link/sidebar_channel_link.test.tsx
  components/sidebar/sidebar_channel/sidebar_channel_link/sidebar_channel_link.tsx
  components/sidebar/sidebar_channel/sidebar_channel_menu/index.ts
  components/sidebar/sidebar_channel/sidebar_channel_menu/sidebar_channel_menu.test.tsx
  components/sidebar/sidebar_channel/sidebar_channel_menu/sidebar_channel_menu.tsx
  components/sidebar/sidebar_channel/sidebar_direct_channel/__snapshots__/sidebar_direct_channel.test.tsx.snap
  components/sidebar/sidebar_channel/sidebar_direct_channel/sidebar_direct_channel.test.tsx
  components/sidebar/sidebar_channel/sidebar_direct_channel/sidebar_direct_channel.tsx
  components/sidebar/sidebar_channel/sidebar_group_channel/sidebar_group_channel.tsx
Labels: 4: Reviews Complete, release-note-none

#11606 MM-47561 : fix icons alignment in global threads
  components/threading/common/button/button.scss
  components/threading/common/button/button.tsx
  components/threading/global_threads/thread_item/__snapshots__/thread_item.test.tsx.snap
  components/threading/global_threads/thread_item/thread_item.tsx
  components/threading/global_threads/thread_list/__snapshots__/thread_list.test.tsx.snap
  components/threading/global_threads/thread_list/thread_list.tsx
  components/threading/global_threads/thread_pane/__snapshots__/thread_pane.test.tsx.snap
  components/threading/global_threads/thread_pane/thread_pane.tsx
Labels: 4: Reviews Complete, release-note-none, Contributor

#11690 [MM-44347] Use new display name parameter to fetch users in group
  components/user_group_popover/group_member_list/group_member_list.tsx
  components/user_group_popover/group_member_list/index.ts
  packages/client/src/client4.ts
  packages/mattermost-redux/src/actions/users.ts
  packages/mattermost-redux/src/selectors/entities/users.ts
Labels: 4: Reviews Complete, release-note-none

#11760 MM-44842: Add restore groups permission to admin console
  components/admin_console/permission_schemes_settings/permission_schemes_settings.tsx
  components/admin_console/permission_schemes_settings/permissions_tree/__snapshots__/permissions_tree.test.tsx.snap
  components/admin_console/permission_schemes_settings/permissions_tree/permissions_tree.tsx
  i18n/en.json
  packages/mattermost-redux/src/constants/permissions.ts
  utils/constants.tsx
Labels: Setup Cloud Test Server, release-note-none

#11146 [MM-44043]Screen reader (JAWS) announcing selected state of sidebar submenu items
  components/widgets/menu/menu_items/__snapshots__/submenu_item.test.tsx.snap
  components/widgets/menu/menu_items/submenu_item.tsx
  i18n/en.json
  utils/utils.tsx
Labels: 4: Reviews Complete, Lifecycle/1:stale, release-note, Contributor

#11015 [MM-45008]: adjusted behavior of formattingbar in advanced text editor
  components/__snapshots__/autosize_textarea.test.tsx.snap
  components/__snapshots__/textbox.test.tsx.snap
  components/advanced_create_comment/advanced_create_comment.tsx
  components/advanced_create_post/__snapshots__/advanced_create_post.test.jsx.snap
  components/advanced_create_post/advanced_create_post.tsx
  components/advanced_text_editor/advanced_text_editor.scss
  components/advanced_text_editor/advanced_text_editor.tsx
  components/advanced_text_editor/formatting_bar/formatting_bar.tsx
  components/advanced_text_editor/formatting_bar/formatting_icon.tsx
  components/advanced_text_editor/texteditor_actions/texteditor_actions.tsx
  components/advanced_text_editor/toggle_formatting_bar/toggle_formatting_bar.tsx
  components/autosize_textarea.tsx
  components/common/auto_height_switcher.tsx
  components/keyboard_shortcuts/keyboard_shortcuts_sequence/keyboard_shortcuts.ts
  components/post_view/post_attachment_opengraph/__snapshots__/post_attachment_opengraph.test.tsx.snap
  components/quick_input/quick_input.tsx
  components/textbox/textbox.tsx
  e2e/cypress/tests/integration/accessibility/accessibility_keyboard_usability_spec.js
  e2e/cypress/tests/integration/accessibility/accessibility_nav_diff_regions_spec.js
  e2e/cypress/tests/integration/accessibility/accessibility_post_spec.js
  e2e/cypress/tests/integration/enterprise/accessibility/accessibility_input_fields_spec.js
  e2e/cypress/tests/integration/messaging/input_box_expands_spec.js
  e2e/cypress/tests/integration/messaging/thread_appears_and_scrollable_in_the_rhs_spec.js
  i18n/en.json
  package-lock.json
  package.json
  sass/components/_post.scss
Labels: 4: Reviews Complete, release-note-none, kind/bug, kind/feature

#11817 do not show two screens at once
  components/self_hosted_purchase_modal/index.test.tsx
  components/self_hosted_purchase_modal/index.tsx
Labels: 2: Dev Review, CherryPick/Approved, release-note-none, QA Deferred

#11832 Automated cherry pick of #11817
  components/self_hosted_purchase_modal/index.test.tsx
  components/self_hosted_purchase_modal/index.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#11836 Cherry-picking translations
  i18n/de.json
  i18n/en_AU.json
  i18n/es.json
  i18n/fr.json
  i18n/hu.json
  i18n/ja.json
  i18n/nl.json
  i18n/pl.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none, Contributor

#11792 [MM-41722] Add the upgrade enterprise sales reason
  components/admin_console/billing/billing_subscriptions/cloud_trial_banner.tsx
  components/pricing_modal/contact_sales_cta.tsx
  components/pricing_modal/content.tsx
Labels: 2: Dev Review, QA Review Done, Setup Cloud + CWS Test Server, release-note

#11835 Fix Apps form loading background color
  components/apps_form/apps_form_component.scss
Labels: 3: QA Review, release-note-none

#11842 Automated cherry pick of #11146
  components/widgets/menu/menu_items/__snapshots__/submenu_item.test.tsx.snap
  components/widgets/menu/menu_items/submenu_item.tsx
  i18n/en.json
  utils/utils.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#11825 Skipped rendering attachment box if it has no content
  components/post_view/message_attachments/message_attachment/__snapshots__/message_attachment.test.tsx.snap
  components/post_view/message_attachments/message_attachment/message_attachment.test.tsx
  components/post_view/message_attachments/message_attachment/message_attachment.tsx
Labels: release-note

#11848 Automated cherry pick of #11825
  components/post_view/message_attachments/message_attachment/__snapshots__/message_attachment.test.tsx.snap
  components/post_view/message_attachments/message_attachment/message_attachment.test.tsx
  components/post_view/message_attachments/message_attachment/message_attachment.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#11735 MM-48456 - restrict analytics call to only admins
  components/announcement_bar/announcement_bar_controller.tsx
  components/announcement_bar/show_start_trial_modal/show_start_trial_modal.tsx
Labels: Setup Cloud Test Server, QA Review Done, release-note-none

#11845 close pricing modal when purchase modal is ready to open
  components/common/hooks/useControlSelfHostedPurchaseModal.ts
  components/pricing_modal/self_hosted_content.tsx
Labels: 2: Dev Review, CherryPick/Candidate, release-note-none, QA Deferred

#11850 Automated cherry pick of #11845
  components/common/hooks/useControlSelfHostedPurchaseModal.ts
  components/pricing_modal/self_hosted_content.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#11809 [MM-44873] Fix button inside of button in global header
  components/status_dropdown/__snapshots__/status_dropdown.test.tsx.snap
  components/status_dropdown/status_dropdown.test.tsx
  components/status_dropdown/status_dropdown.tsx
  i18n/en.json
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none

#11572 feat: add support for multiselect in users form field
  components/apps_form/apps_form_component.scss
  components/apps_form/apps_form_field/apps_form_field.test.tsx
  components/apps_form/apps_form_field/apps_form_field.tsx
  components/apps_form/apps_form_field/apps_form_select_field.tsx
  components/apps_form/apps_form_field/select_channel_option.tsx
  components/apps_form/apps_form_field/select_user_option.tsx
Labels: 4: Reviews Complete, release-note, Contributor, kind/chore

#11851 Automated cherry pick of #11809
  components/status_dropdown/__snapshots__/status_dropdown.test.tsx.snap
  components/status_dropdown/status_dropdown.test.tsx
  components/status_dropdown/status_dropdown.tsx
  i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#11828 [MM-46337] Add emoji tooltip to Top Reactions
  components/activity_and_insights/insights/top_reactions/top_reactions_bar_chart/__snapshots__/top_reactions_bar_chart.test.tsx.snap
  components/activity_and_insights/insights/top_reactions/top_reactions_bar_chart/top_reactions_bar_chart.tsx
  components/widgets/simple_tooltip/simple_tooltip.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none

#11824 Clarified string impact for the user
  components/notify_confirm_modal.tsx
  i18n/en.json
Labels: 3: QA Review, Setup Cloud Test Server, release-note

#11841 [MM-49232]: Prevent the "view Plans" tooltip from showing on the Purchases modal
  components/global_header/right_controls/plan_upgrade_button/index.tsx
  e2e/cypress/tests/integration/enterprise/cloud/billing/cloud_pricing_modal_spec.js
Labels: QA Review Done, Setup Cloud + CWS Test Server, release-note-none

#11852 [MM-49263]: Spacing Changes for the Purchases Modal
  components/apps_form/apps_form_field/select_channel_option.tsx
  components/purchase_modal/purchase.scss
  components/purchase_modal/purchase_modal.tsx
Labels: 2: Dev Review, QA Review Done, 1: UX Review, Setup Cloud + CWS Test Server, release-note-none

#11857 Automated cherry pick of #11856
  components/self_hosted_purchase_modal/consequences.tsx
  components/self_hosted_purchase_modal/index.test.tsx
  components/self_hosted_purchase_modal/self_hosted_purchase_modal.scss
  i18n/en.json
  utils/constants.tsx
  utils/utils.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#11858 Automated cherry pick of #11856
  components/self_hosted_purchase_modal/consequences.tsx
  components/self_hosted_purchase_modal/index.test.tsx
  components/self_hosted_purchase_modal/self_hosted_purchase_modal.scss
  i18n/en.json
  utils/constants.tsx
  utils/utils.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#11830 [MM-49209] Reset escape key in a11y controller
  utils/a11y_controller.js
Labels: 3: QA Review, release-note-none

#11831 [MM-49224] Change at mention button implementation back to anchors
  components/at_mention/__snapshots__/at_mention.test.tsx.snap
  components/at_mention/at_mention.test.tsx
  components/at_mention/at_mention.tsx
  components/at_mention/at_mention_group.tsx
  components/user_group_popover/__snapshots__/user_group_popover.test.tsx.snap
  components/user_group_popover/group_member_list/__snapshots__/group_member_list.test.tsx.snap
  components/user_group_popover/group_member_list/group_member_list.tsx
  components/user_group_popover/user_group_popover.tsx
  sass/components/_mentions.scss
Labels: 3: QA Review, Setup Cloud Test Server, release-note

#11680 Mm 47648 check license expandable
  components/announcement_bar/overage_users_banner/index.tsx
  components/announcement_bar/overage_users_banner/overage_users_banner.test.tsx
  e2e/cypress/tests/integration/enterprise/overage_users/error_overage_users_spec.ts
  i18n/en.json
  packages/client/src/client4.ts
  packages/mattermost-redux/src/action_types/cloud.ts
  packages/mattermost-redux/src/actions/cloud.ts
  packages/mattermost-redux/src/reducers/entities/cloud.ts
  packages/types/src/cloud.ts
  selectors/cloud.ts
Labels: 3: QA Review, release-note

#11805 [MM-48963] - /cloud/products fails on Self-Hosted (Community)
  components/delinquency_modal/delinquency_modal_controller.test.tsx
  components/delinquency_modal/useDelinquencyModalController.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none

#11623 MM-44872: Complete link read out on focusing copy invite link button
  components/invitation_modal/invite_view.tsx
  i18n/en.json
Labels: 4: Reviews Complete, release-note-none, Contributor

#11803 [MM-49061] Fix Thread Drafts not Updating on Team Switch
  components/advanced_create_comment/advanced_create_comment.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#11316 [MM-38335] Prioritize results of add members to channel based on recent DMs
  components/channel_invite_modal/__snapshots__/channel_invite_modal.test.tsx.snap
  components/channel_invite_modal/channel_invite_modal.test.tsx
  components/channel_invite_modal/channel_invite_modal.tsx
  components/channel_invite_modal/index.ts
  packages/mattermost-redux/src/selectors/entities/channels.test.ts
  packages/mattermost-redux/src/selectors/entities/channels.ts
  packages/mattermost-redux/test/test_helper.ts
Labels: 2: Dev Review, Hacktoberfest, Setup Cloud Test Server, QA Review Done, release-note, Contributor

#11807 [MM-48799] - Adjusted windows text notification length
  actions/notification_actions.jsx
Labels: 4: Reviews Complete, release-note

#11706 [MM-47805] Remove CRT feature flag
  actions/notification_actions.test.js
  components/admin_console/admin_definition.jsx
  components/permalink_view/permalink_view.test.tsx
  components/suggestion/switch_channel_provider.test.jsx
  packages/mattermost-redux/src/actions/channels.test.js
  packages/mattermost-redux/src/actions/posts.test.js
  packages/mattermost-redux/src/actions/preferences.test.js
  packages/mattermost-redux/src/actions/teams.test.js
  packages/mattermost-redux/src/actions/users.test.js
  packages/mattermost-redux/src/selectors/entities/channel_categories.test.ts
  packages/mattermost-redux/src/selectors/entities/channels.test.ts
  packages/mattermost-redux/src/selectors/entities/preferences.ts
  utils/post_utils.test.jsx
Labels: 4: Reviews Complete, CherryPick/Approved, release-note
