Repository mattermost/mattermost-webapp, pull requests merged in 2022-04, with the labels that each got.

#10058 MM-42655 Improve memoization of permission selectors
  actions/websocket_actions.test.jsx
  packages/mattermost-redux/src/selectors/entities/roles.test.js
  packages/mattermost-redux/src/selectors/entities/roles.ts
  packages/mattermost-redux/src/selectors/entities/roles_helpers.ts
Labels: 4: Reviews Complete, release-note

#10101 MM-42654 Improve memoization of makeGetProfilesInChannel
  components/admin_console/team_channel_settings/channel/details/channel_members/index.ts
  components/channel_header/index.js
  components/popover_list_members/index.ts
  packages/mattermost-redux/src/selectors/entities/users.test.js
  packages/mattermost-redux/src/selectors/entities/users.ts
Labels: 4: Reviews Complete, release-note-none, QA Deferred

#10052 MM-42682 : Replace "completeLogin" with "loadMe"
  actions/views/root.js
  actions/views/root.test.js
  components/root/index.js
  components/root/root.jsx
  components/root/root.test.jsx
  packages/mattermost-redux/src/actions/users.ts
  packages/mattermost-redux/test/test_helper.js
Labels: 4: Reviews Complete, release-note-none

#10064 MM-40148: decouples thread data from counts
  actions/websocket_actions.jsx
  components/threading/global_threads/global_threads.tsx
  components/threading/global_threads_link/global_threads_link.tsx
  packages/mattermost-redux/src/action_types/threads.ts
  packages/mattermost-redux/src/actions/threads.test.js
  packages/mattermost-redux/src/actions/threads.ts
  packages/mattermost-redux/src/client/client4.ts
  packages/mattermost-redux/src/reducers/entities/threads/counts.ts
  packages/mattermost-redux/src/reducers/entities/threads/threads.test.js
  packages/mattermost-redux/src/selectors/entities/threads.test.js
  packages/mattermost-redux/src/selectors/entities/threads.ts
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none

#10098 [MM-42822] UX for blocked trial requests
  actions/admin_actions.jsx
  components/admin_console/feature_discovery/feature_discovery.tsx
  components/admin_console/license_settings/__snapshots__/license_settings.test.jsx.snap
  components/admin_console/license_settings/license_settings.tsx
  components/admin_console/license_settings/trial_banner/trial_banner.tsx
  components/common/carousel/__snapshots__/carousel.test.tsx.snap
  components/common/carousel/carousel.tsx
  components/learn_more_trial_modal/learn_more_trial_modal.tsx
  components/learn_more_trial_modal/learn_more_trial_modal_step.tsx
  components/learn_more_trial_modal/start_trial_btn.scss
  components/learn_more_trial_modal/start_trial_btn.test.tsx
  components/learn_more_trial_modal/start_trial_btn.tsx
  i18n/en.json
Labels: 4: Reviews Complete, release-note-none

#9705 [MM-22841] Add copy URL, download source image icon buttons, to image thumbnail
  components/__snapshots__/size_aware_image.test.jsx.snap
  components/single_image_view/__snapshots__/single_image_view.test.tsx.snap
  components/single_image_view/index.ts
  components/single_image_view/single_image_view.test.tsx
  components/single_image_view/single_image_view.tsx
  components/size_aware_image.jsx
  components/size_aware_image.test.jsx
  i18n/en.json
  sass/components/_files.scss
  sass/components/_post.scss
  sass/layout/_markdown.scss
Labels: 4: Reviews Complete, Setup Cloud Test Server, QA Review Done, release-note, Contributor

#10118 Updated legacy link
  components/integrations/__snapshots__/abstract_command.test.jsx.snap
  components/integrations/abstract_command.jsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, QA Review Done, release-note-none

#10117 fix placement of track callback
  components/common/hooks/useCopyText.ts
Labels: 4: Reviews Complete, Setup Cloud Test Server, QA Review Done, release-note

#10124 Automated cherry pick of #10118
  components/integrations/__snapshots__/abstract_command.test.jsx.snap
  components/integrations/abstract_command.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#10123 Automated cherry pick of #10118
  components/integrations/__snapshots__/abstract_command.test.jsx.snap
  components/integrations/abstract_command.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#10120 [MM-42777] Fixes a bug where code blocks would not longer be scrollable
  sass/layout/_markdown.scss
Labels: 4: Reviews Complete, CherryPick/Approved, release-note, kind/bug, Contributor

#10126 Automated cherry pick of #10120
  sass/layout/_markdown.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#9070 Use fromWebhook prop from the profile picture in the profile popover
  components/profile_picture/profile_picture.tsx
  components/profile_popover/profile_popover.tsx
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted, release-note, Contributor

#10068 [MM-42592] resolve flakiness when actions menu is open
  components/post_view/post_info/post_info.tsx
  components/rhs_root_post/__snapshots__/rhs_root_post.test.jsx.snap
  components/rhs_root_post/rhs_root_post.jsx
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#10131 Automated cherry pick of #10068
  components/post_view/post_info/post_info.tsx
  components/rhs_root_post/__snapshots__/rhs_root_post.test.jsx.snap
  components/rhs_root_post/rhs_root_post.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#10130 Automated cherry pick of #10068
  components/post_view/post_info/post_info.tsx
  components/rhs_root_post/__snapshots__/rhs_root_post.test.jsx.snap
  components/rhs_root_post/rhs_root_post.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#10103 [MM-42928]: fixes public links are being generated by the server even if public links are disabled in the config
  components/file_preview_modal/file_preview_modal_main_actions/file_preview_modal_main_actions.test.tsx
  components/file_preview_modal/file_preview_modal_main_actions/file_preview_modal_main_actions.tsx
Labels: 4: Reviews Complete, release-note

#10015 MM-42401 : Channels and Favorites are not localized on the "move to" channel options menu
  components/category_menu_items/category_menu_items.tsx
  i18n/en.json
Labels: 4: Reviews Complete, release-note-none, Contributor

#10114 [MM-42858] Fix Actions Menu Background height in Mobile View
  components/post_view/post_info/post_info.tsx
Labels: 4: Reviews Complete, release-note-none

#10138 Automated cherry pick of #10114
  components/post_view/post_info/post_info.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#10111 [MM-42869] Fix dot menu dark mode hover
  components/dot_menu/__snapshots__/dot_menu.test.tsx.snap
  components/dot_menu/dot_menu.scss
  components/dot_menu/dot_menu.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#10139 Automated cherry pick of #10111
  components/dot_menu/__snapshots__/dot_menu.test.tsx.snap
  components/dot_menu/dot_menu.scss
  components/dot_menu/dot_menu.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#10113 MM-41323: Secure Marketplace URL
  .gitignore
  components/admin_console/plugin_management/__snapshots__/plugin_management.test.tsx.snap
  components/admin_console/plugin_management/plugin_management.tsx
  e2e/cypress/tests/integration/system_console/plugin_marketplace_url_spec.js
Labels: 4: Reviews Complete, release-note-none

#10116 [MM-48892] fix shortcut key double press to activate action
  components/dot_menu/dot_menu.tsx
Labels: 2: Dev Review, CherryPick/Approved, QA Review Done, release-note-none

#10142 Automated cherry pick of #10114
  components/post_view/post_info/post_info.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#10143 Automated cherry pick of #10111
  components/dot_menu/__snapshots__/dot_menu.test.tsx.snap
  components/dot_menu/dot_menu.scss
  components/dot_menu/dot_menu.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#10144 Automated cherry pick of #10116
  components/dot_menu/dot_menu.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#10141 Automated cherry pick of #10116
  components/dot_menu/dot_menu.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#10145 Automated cherry pick of #10134
  components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
  i18n/i18n.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#10127 [MM-42769] - Fix Actions Menu tooltip `X` click and remove `Opt out` link
  components/actions_menu/actions_menu_tutorial_tip.tsx
  components/post_view/post_info/post_info.tsx
  components/widgets/tour_tip/tour_tip.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#10150 Automated cherry pick of #10127
  components/actions_menu/actions_menu_tutorial_tip.tsx
  components/post_view/post_info/post_info.tsx
  components/widgets/tour_tip/tour_tip.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#10148 Automated cherry pick of #10127
  components/actions_menu/actions_menu_tutorial_tip.tsx
  components/post_view/post_info/post_info.tsx
  components/widgets/tour_tip/tour_tip.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#10152 MM-43194: remove plugin-related dispatch on enable
  actions/websocket_actions.jsx
  actions/websocket_actions.test.jsx
Labels: CherryPick/Approved, release-note-none

#10153 Automated cherry pick of #10152
  actions/websocket_actions.jsx
  actions/websocket_actions.test.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#9992 [MM-38615] Permalink Previews for DMs/GMs
  components/post_view/post_body_additional_content/__snapshots__/post_body_additional_content.test.tsx.snap
  components/post_view/post_body_additional_content/post_body_additional_content.test.tsx
  components/post_view/post_message_preview/__snapshots__/post_message_preview.test.tsx.snap
  components/post_view/post_message_preview/index.ts
  components/post_view/post_message_preview/post_message_preview.test.tsx
  components/post_view/post_message_preview/post_message_preview.tsx
  packages/mattermost-redux/src/types/posts.ts
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note

#10155 Automated cherry pick of #10152
  actions/websocket_actions.jsx
  actions/websocket_actions.test.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#10154 Weblate 220407
  i18n/de.json
  i18n/fr.json
  i18n/pl.json
  i18n/sv.json
Labels: 2: Dev Review, release-note-none

#10136 [MM-42916] Fixes context menu gets in the way when highlighting text
  components/code_block/__snapshots__/code_block.test.jsx.snap
  components/code_block/code_block.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, QA Review Done, release-note, Contributor

#10157 Automated cherry pick of #10136
  components/code_block/__snapshots__/code_block.test.jsx.snap
  components/code_block/code_block.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#10086 [MM-42738] Filter and time picker for insights
  components/activity_and_insights/activity_and_insights.scss
  components/activity_and_insights/activity_and_insights.tsx
  components/activity_and_insights/insights/insights.tsx
  components/activity_and_insights/insights/insights_header/insights_header.scss
  components/activity_and_insights/insights/insights_header/insights_header.tsx
  components/activity_and_insights/insights/insights_title/insights_title.tsx
  components/activity_and_insights/insights/time_frame_dropdown/time_frame_dropdown.tsx
  i18n/en.json
  utils/constants.jsx
Labels: 3: QA Review, Setup Cloud Test Server, release-note-none

#10083 Mm 39058 invite to team from add channel
  actions/invite_actions.ts
  components/channel_invite_modal/__snapshots__/channel_invite_modal.test.tsx.snap
  components/channel_invite_modal/channel_invite_modal.test.tsx
  components/channel_invite_modal/channel_invite_modal.tsx
  components/channel_invite_modal/index.ts
  components/invitation_modal/add_to_channels.tsx
  components/invitation_modal/index.tsx
  components/invitation_modal/invitation_modal.test.tsx
  components/invitation_modal/invitation_modal.tsx
  components/invitation_modal/invite_view.tsx
  components/invitation_modal/result_table.tsx
  components/multiselect/__snapshots__/multiselect.test.tsx.snap
  components/multiselect/multiselect.test.tsx
  components/multiselect/multiselect.tsx
  components/multiselect/multiselect_list.tsx
  e2e/cypress/tests/integration/channel_settings/add_users_to_channel_spec.js
  e2e/cypress/tests/integration/enterprise/accessibility/accessibility_modals_dialogs_spec.js
  e2e/cypress/tests/integration/enterprise/guest_accounts/guest_invitation_ui_spec.js
  i18n/en.json
  packages/mattermost-redux/src/actions/teams.ts
  packages/mattermost-redux/src/client/client4.ts
  sass/components/_channel-invite-modal.scss
Labels: 2: Dev Review, Setup Cloud Test Server, QA Review Done, 1: UX Review, release-note-none

#10110 MM-42493: Add throttle to custom emoji and gif search
  components/emoji_picker/components/emoji_picker_search.tsx
  components/emoji_picker/constants/index.ts
  components/emoji_picker/emoji_picker.tsx
  components/gif_picker/components/Search/index.jsx
Labels: 4: Reviews Complete, release-note-none, Contributor

#10121 MM-20575: Migrate 'components/admin_console/license_settings' test to TypeScript
  components/admin_console/license_settings/__snapshots__/license_settings.test.tsx.snap
  components/admin_console/license_settings/license_settings.test.tsx
Labels: 4: Reviews Complete, release-note-none, Contributor

#10156 MM-T639 Webhook DM test
  e2e/cypress/tests/integration/integrations/incoming_webhook/incoming_webhook_creates_dm_spec.js
Labels: release-note-none, Contributor

#10151 MM-41791 : Custom emoji "Next" button out of view when banner is present
  sass/routes/_backstage.scss
Labels: 4: Reviews Complete, release-note-none

#9871 [MM-41905] Adding more hooks and optimizing functional components
  components/add_user_to_group_multiselect/index.ts
  components/add_users_to_group_modal/add_users_to_group_modal.tsx
  components/add_users_to_group_modal/index.ts
  components/update_user_group_modal/index.ts
  components/update_user_group_modal/update_user_group_modal.tsx
  components/user_groups_modal/__snapshots__/user_groups_modal.test.tsx.snap
  components/user_groups_modal/user_groups_list/user_groups_list.tsx
  components/user_groups_modal/user_groups_modal_header/user_groups_modal_header.tsx
  components/view_user_group_modal/__snapshots__/view_user_group_modal.test.tsx.snap
  components/view_user_group_modal/view_user_group_header_sub_menu/index.ts
  components/view_user_group_modal/view_user_group_header_sub_menu/view_user_group_header_sub_menu.tsx
  components/view_user_group_modal/view_user_group_list_item/view_user_group_list_item.tsx
  components/view_user_group_modal/view_user_group_modal_header/view_user_group_modal_header.tsx
Labels: 3: QA Review, release-note-none

#10163 Automated cherry pick of #10161
  utils/route.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#10149 [MM-42795] Cypress test MM-T3326 is broken
  e2e/cypress/tests/integration/onboarding/cloud_user_onboarding_spec.js
Labels: 4: Reviews Complete, QA Review Done, release-note-none

#10137 Update link to Docker instructions
  README.md
Labels: 2: Dev Review, release-note-none

#10102 [MM-41996] Channel Members RHS
  actions/views/rhs.test.ts
  actions/views/rhs.ts
  actions/views/search.js
  components/channel_header/__snapshots__/channel_header.test.jsx.snap
  components/channel_header/channel_header.js
  components/channel_header/channel_header.test.jsx
  components/channel_header/channel_info_button.tsx
  components/channel_header/components/header_icon_wrapper.tsx
  components/channel_header/index.js
  components/channel_info_rhs/channel_info_rhs.tsx
  components/channel_info_rhs/index.ts
  components/channel_info_rhs/menu.test.tsx
  components/channel_info_rhs/menu.tsx
  components/channel_members_dropdown/channel_members_dropdown.jsx
  components/channel_members_dropdown/index.ts
  components/channel_members_rhs/action_bar.test.tsx
  components/channel_members_rhs/action_bar.tsx
  components/channel_members_rhs/channel_members_rhs.tsx
  components/channel_members_rhs/header.tsx
  components/channel_members_rhs/index.ts
  components/channel_members_rhs/member.tsx
  components/channel_members_rhs/member_list.tsx
  components/channel_members_rhs/search.tsx
  components/popover_list_members/__snapshots__/popover_list_members.test.tsx.snap
  components/popover_list_members/index.ts
  components/popover_list_members/popover_list_members.test.tsx
  components/popover_list_members/popover_list_members.tsx
  components/popover_list_members/popover_list_members_item/index.ts
  components/popover_list_members/popover_list_members_item/popover_list_members_item.tsx
  components/search/index.tsx
  components/sidebar_right/index.js
  components/sidebar_right/sidebar_right.jsx
  components/widgets/inputs/input/input.tsx
  e2e/cypress/tests/integration/bot_accounts/in_lists_2_spec.js
  e2e/cypress/tests/integration/channel/channel_info_rhs_spec.js
  e2e/cypress/tests/integration/channel/channel_members_rhs_spec.js
  e2e/cypress/tests/integration/channel/user_to_admin_updates_manage_channel_members_rhs_spec.js
  e2e/cypress/tests/integration/channel/user_to_channel_admin_member_updates_manage_channel_members_rhs_spec.js
  e2e/cypress/tests/support/ui/channel_header.js
  e2e/cypress/tests/support/ui_commands.js
  i18n/en.json
  reducers/views/rhs.ts
  reducers/views/search.test.js
  reducers/views/search.ts
  types/store/rhs.ts
  types/store/views.ts
  utils/constants.jsx
Labels: 1: PM Review, 2: Dev Review, Setup Cloud Test Server, QA Review Done, release-note-none

#10167 MM-39565 - remove A/B test bottom option for add members button
  packages/mattermost-redux/src/constants/config.ts
  packages/mattermost-redux/src/selectors/entities/preferences.ts
Labels: release-note-none

#10168 Added minimum node and npm version requirement
  package.json
Labels: release-note-none

#10128 [MM-42860] Shared card component
  components/activity_and_insights/activity_and_insights.scss
  components/activity_and_insights/insights/card/card.scss
  components/activity_and_insights/insights/card/card.tsx
  components/activity_and_insights/insights/insights.tsx
  components/activity_and_insights/insights/top_channels/top_channels.tsx
  components/card/card_header.tsx
  i18n/en.json
Labels: Setup Cloud Test Server, release-note-none

#10184 [MM-43337] Add image for emails
  images/payment-method-illustration.png
  images/trial-ending-soon.png
Labels: release-note-none

#10192 [MM-43339] Add asset for use in cloud emails
  images/cloud-laptop.png
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#10173 MM-43215: Fixes typo.
  components/admin_console/workspace-optimization/dashboard.tsx
Labels: release-note-none, QA Deferred

#10193 [MM-43339] [MM-43337] Add email asset images to webpack copy so they're exposed publicly
  package-lock.json
  webpack.config.js
Labels: 2: Dev Review, AutoMerge, release-note-none

#10188 Add .gitpod.yml to use mattermost-gitpod-config repo for Gitpod configuration
  .gitpod.yml
Labels: 2: Dev Review, release-note-none

#10074 MM-41909: Allow 1 char channel name
  components/new_channel_modal/new_channel_modal.test.tsx
  components/new_channel_modal/new_channel_modal.tsx
  components/rename_channel_modal/rename_channel_modal.test.tsx
  i18n/en.json
  utils/constants.jsx
  utils/url.test.tsx
  utils/url.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note, Contributor

#10179 [MM-43336] Fix some e2e tests
  e2e/cypress/tests/integration/accessibility/accessibility_dropdowns_spec.js
  e2e/cypress/tests/integration/account_settings/profile/nickname_spec.js
  e2e/cypress/tests/integration/channel_settings/add_users_to_channel_spec.js
  e2e/cypress/tests/integration/enterprise/guest_accounts/guest_experience_ui_spec.js
  e2e/cypress/tests/integration/enterprise/guest_accounts/guest_identification_ui_spec.js
  e2e/cypress/tests/integration/enterprise/ldap/ldap_group_sync_spec.js
  e2e/cypress/tests/integration/enterprise/permissions/team_permissions_spec.js
  e2e/cypress/tests/integration/enterprise/system_console/channel_moderation/helpers.js
  e2e/cypress/tests/integration/enterprise/system_console/channel_moderation/manage_members_spec.js
  e2e/cypress/tests/integration/messaging/center_channel_rhs_overlap_spec.js
  e2e/cypress/tests/integration/multi_team_and_dm/gm_add_user_spec.js
  e2e/cypress/tests/integration/system_console/user_management_not_cloud_spec.js
Labels: 4: Reviews Complete, release-note-none

#9865 MM-41185,MM-41065: fixes mark thread as unread
  actions/post_actions.jsx
  components/threading/global_threads/thread_menu/thread_menu.test.tsx
  components/threading/global_threads/thread_menu/thread_menu.tsx
  packages/mattermost-redux/src/actions/threads.ts
  packages/mattermost-redux/src/client/client4.ts
Labels: 2: Dev Review, release-note

#10199 Fixes minor code style
  package.json
Labels: 2: Dev Review, release-note-none

#10171 fix channel intro components with app filter on
  selectors/plugins.ts
Labels: 4: Reviews Complete, release-note-none

#10205 Make command palette available with shortcuts and from other places
  components/command_palette/command_palette.tsx
  components/command_palette/command_palette_modal/command_palette_modal.scss
  components/command_palette/command_palette_modal/command_palette_modal.tsx
  components/command_palette/command_palette_modal/index.ts
  components/command_palette/index.ts
  components/command_palette/types/index.ts
  components/root/root.jsx
  components/sidebar/channel_navigator/channel_navigator.test.tsx
  components/sidebar/channel_navigator/channel_navigator.tsx
  components/sidebar/channel_navigator/index.ts
  i18n/en.json
  packages/mattermost-redux/src/selectors/entities/preferences.ts
  utils/constants.jsx
Labels: release-note-none

#10201 Skip integrity check for mattermost/marked
  package-lock.json
  skip_integrity_check.js
Labels: 4: Reviews Complete, release-note-none

#10176 [MM-43328] Fix Channel admin not listed in their groups
  actions/views/rhs.test.ts
  actions/views/rhs.ts
  components/channel_members_rhs/channel_members_rhs.tsx
  components/channel_members_rhs/index.ts
  packages/mattermost-redux/src/actions/channels.ts
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, release-note-none

#10206 Automated cherry pick of #10176
  actions/views/rhs.test.ts
  actions/views/rhs.ts
  components/channel_members_rhs/channel_members_rhs.tsx
  components/channel_members_rhs/index.ts
  packages/mattermost-redux/src/actions/channels.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#10196 E2E/Cypress:test case fixed
  e2e/cypress/tests/integration/collapsed_reply_threads/following_1_spec.js
  e2e/cypress/tests/integration/collapsed_reply_threads/following_spec.js
  e2e/cypress/tests/integration/enterprise/accessibility/accessibility_modals_dialogs_spec.js
Labels: release-note-none

#10180 extend registry to register site stats handlers for plugins
  components/analytics/system_analytics/index.ts
  components/analytics/system_analytics/system_analytics.tsx
  packages/types/src/admin.ts
  plugins/registry.js
  reducers/plugins/index.ts
  types/store/plugins.ts
  utils/constants.jsx
Labels: 4: Reviews Complete, release-note-none

#10178 [MM-43075] Channel Info RHS: shortcut
  actions/views/rhs.ts
  components/keyboard_shortcuts/keyboard_shortcuts_modal/__snapshots__/keyboard_shortcuts_modal.test.tsx.snap
  components/keyboard_shortcuts/keyboard_shortcuts_modal/keyboard_shortcuts_modal.tsx
  components/keyboard_shortcuts/keyboard_shortcuts_sequence/keyboard_shortcuts.ts
  components/sidebar_right/index.js
  components/sidebar_right/sidebar_right.jsx
  e2e/cypress/tests/integration/keyboard_shortcuts/ctrl_cmd_alt_I_toggles_channel_info_rhs_spec.js
  i18n/en.json
Labels: 2: Dev Review, Setup Cloud Test Server, QA Review Done, release-note-none

#10147 [MM-43042] Skeleton loader and toggle widgets based on scope
  components/activity_and_insights/activity_and_insights.scss
  components/activity_and_insights/insights/insights.tsx
  components/activity_and_insights/insights/insights_title/insights_title.tsx
  components/activity_and_insights/insights/skeleton_loader/bar_chart_loader/bar_chart_loader.tsx
  components/activity_and_insights/insights/skeleton_loader/circle_loader/circle_loader.tsx
  components/activity_and_insights/insights/skeleton_loader/line_chart_loader/line_chart_loader.tsx
  components/activity_and_insights/insights/skeleton_loader/skeleton_loader.scss
  components/activity_and_insights/insights/skeleton_loader/title_loader/title_loader.tsx
  components/activity_and_insights/insights/top_channels/top_channels.tsx
  components/activity_and_insights/insights/top_reactions/top_reactions.tsx
  components/activity_and_insights/insights/widget_hoc/widget_hoc.tsx
  i18n/en.json
  utils/constants.jsx
Labels: Setup Cloud Test Server, release-note-none

#10203 Made unread msg badge in team sidebar hidden in products
  components/team_sidebar/components/team_button.tsx
  components/team_sidebar/team_sidebar.tsx
Labels: release-note-none

#10209 Weblate 10200
  i18n/bg.json
  i18n/de.json
  i18n/en_AU.json
  i18n/es.json
  i18n/fa.json
  i18n/fr.json
  i18n/hu.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#10213 Automated cherry pick of #10203
  components/team_sidebar/components/team_button.tsx
  components/team_sidebar/team_sidebar.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#9878 MM-37550: show attachment when no text in thread
  components/threading/global_threads/thread_item/attachments/attachment_card/attachment_card.scss
  components/threading/global_threads/thread_item/attachments/attachment_card/index.tsx
  components/threading/global_threads/thread_item/attachments/file_card/file_card.scss
  components/threading/global_threads/thread_item/attachments/file_card/file_card.tsx
  components/threading/global_threads/thread_item/attachments/file_card/index.ts
  components/threading/global_threads/thread_item/attachments/index.tsx
  components/threading/global_threads/thread_item/thread_item.tsx
  e2e/cypress/tests/integration/collapsed_reply_threads/channel_notifications_spec.js
  e2e/cypress/tests/integration/collapsed_reply_threads/files_spec.js
  e2e/cypress/tests/integration/collapsed_reply_threads/following_spec.js
  e2e/cypress/tests/integration/collapsed_reply_threads/global_threads_spec.js
  e2e/cypress/tests/integration/collapsed_reply_threads/replies_spec.js
  e2e/cypress/tests/integration/collapsed_reply_threads/unread_spec.js
  e2e/cypress/tests/support/api/preference.d.ts
  e2e/cypress/tests/support/api/preference.js
  packages/mattermost-redux/src/actions/files.ts
  packages/mattermost-redux/src/actions/threads.ts
  packages/mattermost-redux/src/selectors/entities/files.ts
  packages/types/src/files.ts
  utils/utils.d.ts
  utils/utils.jsx
Labels: 4: Reviews Complete, release-note-none

#10210 Command palette : UI for text input, filters and filter
  components/command_palette/command_palette_modal/chip/chip.scss
  components/command_palette/command_palette_modal/chip/chip.tsx
  components/command_palette/command_palette_modal/chip/index.ts
  components/command_palette/command_palette_modal/command_palette_modal.scss
  components/command_palette/command_palette_modal/command_palette_modal.tsx
  components/command_palette/command_palette_modal/filter_tag/filter_tag.scss
  components/command_palette/command_palette_modal/filter_tag/filter_tag.tsx
  components/command_palette/command_palette_modal/filter_tag/index.ts
  components/command_palette/command_palette_modal/filters/filters.scss
  components/command_palette/command_palette_modal/filters/filters.tsx
  components/command_palette/command_palette_modal/filters/index.ts
  components/command_palette/command_palette_modal/footer/footer.scss
  components/command_palette/command_palette_modal/footer/footer.tsx
  components/command_palette/command_palette_modal/footer/index.ts
  components/command_palette/command_palette_modal/input/index.ts
  components/command_palette/command_palette_modal/input/input.scss
  components/command_palette/command_palette_modal/input/input.tsx
  components/command_palette/command_palette_modal/results/index.ts
  components/command_palette/command_palette_modal/results/results.tsx
  i18n/en.json
Labels: release-note-none

#10219 Command palette : Add command palette list, item and channel to command palette transformer
  components/command_palette/command_palette.tsx
  components/command_palette/command_palette_list/command_palette_list.scss
  components/command_palette/command_palette_list/command_palette_list.tsx
  components/command_palette/command_palette_list_item/command_palette_list_item.scss
  components/command_palette/command_palette_list_item/command_palette_list_item.tsx
  components/command_palette/command_palette_list_item/command_palette_list_item_pictograph.tsx
  components/command_palette/command_palette_manager/command_palette_manager.ts
  components/command_palette/command_palette_modal/command_palette_modal.scss
  components/command_palette/command_palette_modal/command_palette_modal.tsx
  components/command_palette/command_palette_modal/filters/filters.scss
  components/command_palette/demo.json
  components/command_palette/index.ts
  components/command_palette/types/index.ts
  components/command_palette/utils.ts
Labels: release-note-none

#10197 fix the same target in make help output
  Makefile
Labels: 4: Reviews Complete, release-note-none, Contributor

#10221 Automated cherry pick of #10204
  components/admin_console/license_settings/__snapshots__/license_settings.test.tsx.snap
  components/admin_console/license_settings/enterprise_edition/enterprise_edition.scss
  components/admin_console/license_settings/enterprise_edition/enterprise_edition_left_panel.test.tsx
  components/admin_console/license_settings/enterprise_edition/enterprise_edition_left_panel.tsx
  components/admin_console/license_settings/license_settings.tsx
  components/admin_console/license_settings/modals/__snapshots__/upload_license_modal.test.tsx.snap
  components/admin_console/license_settings/modals/upload_license_modal.test.tsx
  components/admin_console/license_settings/modals/upload_license_modal.tsx
  i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#10217 Mm 43084 Consume cloud workspace limits
  actions/cloud.tsx
  components/admin_console/admin_console.test.tsx
  components/admin_console/billing/billing_subscriptions/billing_subscriptions.scss
  components/admin_console/billing/billing_subscriptions/billing_subscriptions.tsx
  components/admin_console/billing/billing_subscriptions/cancel_subscription.tsx
  components/admin_console/billing/billing_subscriptions/contact_sales_card.tsx
  components/admin_console/billing/billing_subscriptions/index.tsx
  components/admin_console/billing/billing_subscriptions/limit_card.tsx
  components/admin_console/billing/billing_subscriptions/limits.test.tsx
  components/admin_console/billing/billing_subscriptions/limits.tsx
  components/common/usage_percent_bar/index.tsx
  components/file_info_preview/index.ts
  components/file_preview/file_progress_preview.tsx
  components/global_header/left_controls/product_menu/product_menu.tsx
  components/integrations/bots/add_bot/add_bot.jsx
  components/picture_selector.tsx
  components/setting_picture.jsx
  i18n/en.json
  packages/mattermost-redux/src/action_types/cloud.ts
  packages/mattermost-redux/src/client/client4.ts
  packages/mattermost-redux/src/reducers/entities/cloud.test.ts
  packages/mattermost-redux/src/reducers/entities/cloud.ts
  packages/mattermost-redux/src/selectors/entities/cloud.ts
  packages/mattermost-redux/src/selectors/entities/preferences.ts
  packages/mattermost-redux/src/store/initial_state.ts
  packages/types/src/cloud.ts
  types/exif2css.d.ts
  utils/file_utils.test.jsx
  utils/file_utils.tsx
  utils/limits.tsx
Labels: 2: Dev Review, release-note-none

#10185 Update LinkTooltip docs
  plugins/registry.js
Labels: release-note-none

#10202 MM-42885 - fix relative path url problem with subpath
  components/admin_console/workspace-optimization/dashboard.tsx
Labels: 3: QA Review, Setup Cloud Test Server, release-note-none

#10229 MM-43302 Check if performance metrics are enabled closer to when we send selector metrics
  actions/telemetry_actions.jsx
Labels: 4: Reviews Complete, release-note

#10215 MM-32589 : Fix CHB "This channel has guests" accessibility
  components/channel_header/channel_header.js
Labels: 4: Reviews Complete, release-note-none, Contributor

#9950 MM-42316: Error message when clicking on test connection button without saving
  components/admin_console/schema_admin_settings.jsx
  i18n/en.json
Labels: 4: Reviews Complete, Lifecycle/1:stale, Setup Cloud Test Server, release-note-none, Contributor

#10119 MM-34314 Migrate 'components/admin_console/permission_schemes_settings/guest_permissions_tree' and associated tests to TypeScript
  components/admin_console/permission_schemes_settings/guest_permissions_tree/__snapshots__/guest_permissions_tree.test.tsx.snap
  components/admin_console/permission_schemes_settings/guest_permissions_tree/guest_permissions_tree.jsx
  components/admin_console/permission_schemes_settings/guest_permissions_tree/guest_permissions_tree.test.tsx
  components/admin_console/permission_schemes_settings/guest_permissions_tree/guest_permissions_tree.tsx
  components/admin_console/permission_schemes_settings/guest_permissions_tree/index.tsx
Labels: 4: Reviews Complete, release-note-none, Contributor

#10164 [MM-43133] Open modal for widgets
  components/activity_and_insights/insights/card/card.tsx
  components/activity_and_insights/insights/insights.tsx
  components/activity_and_insights/insights/insights_modal/insights_modal.scss
  components/activity_and_insights/insights/insights_modal/insights_modal.tsx
  components/activity_and_insights/insights/time_frame_dropdown/time_frame_dropdown.scss
  components/activity_and_insights/insights/time_frame_dropdown/time_frame_dropdown.tsx
  components/activity_and_insights/insights/top_reactions/top_reactions_table/top_reactions_table.tsx
  components/activity_and_insights/insights/widget_hoc/widget_hoc.tsx
  components/user_groups_modal/user_groups_modal.scss
  i18n/en.json
  sass/components/_modal.scss
  utils/constants.jsx
Labels: Setup Cloud Test Server, release-note-none

#10160 MM-20574: Migrate 'components/admin_console/custom_plugin_settings' module and associated tests to TypeScript
  components/admin_console/custom_plugin_settings/__snapshots__/custom_plugin_settings.test.tsx.snap
  components/admin_console/custom_plugin_settings/custom_plugin_settings.test.tsx
  components/admin_console/custom_plugin_settings/custom_plugin_settings.tsx
  components/admin_console/custom_plugin_settings/enable_plugin_setting.ts
  components/admin_console/custom_plugin_settings/index.ts
  packages/types/src/plugins.ts
  types/store/plugins.ts
Labels: 4: Reviews Complete, release-note-none, Contributor

#10195 MM-41565: fixes total thread count
  components/threading/global_threads/global_threads.tsx
Labels: release-note-none, QA Deferred

#10232 Cypress/E2E: Fix message with gif spec
  e2e/cypress/tests/integration/messaging/message_with_gif_spec.js
Labels: Changelog/Not Needed, Docs/Not Needed, 3: QA Review, release-note-none

#10233 Cypress/E2E: Fix user team invite link to sign up spec
  e2e/cypress/tests/integration/onboarding/use_team_invite_link_to_sign_up_spec.js
Labels: Changelog/Not Needed, Docs/Not Needed, release-note-none

#10234 set plugin stat title type to reactnode to enable translations
  packages/types/src/admin.ts
Labels: 4: Reviews Complete, release-note-none, Contributor

#10220 MM-39695 : Fix recently used emoji missing aria-label
  components/post_view/post_recent_reactions/recent_reactions_emoji_item.tsx
  e2e/cypress/tests/integration/accessibility/accessibility_post_spec.js
Labels: 4: Reviews Complete, release-note-none, Contributor

#10224 [MM-43222]: render suggestion list dividers the correct way
  components/__snapshots__/textbox.test.tsx.snap
  components/add_user_to_channel_modal/__snapshots__/add_user_to_channel_modal.test.jsx.snap
  components/add_user_to_channel_modal/add_user_to_channel_modal.jsx
  components/autocomplete_selector.jsx
  components/autocomplete_selector.test.jsx
  components/quick_switch_modal/__snapshots__/quick_switch_modal.test.tsx.snap
  components/quick_switch_modal/quick_switch_modal.tsx
  components/search_bar/search_bar.tsx
  components/suggestion/suggestion_box/suggestion_box.jsx
  components/suggestion/suggestion_list.d.ts
  components/suggestion/suggestion_list.jsx
  components/textbox/textbox.tsx
  e2e/cypress/tests/integration/channel/channel_mention_autocomplete_spec.js
Labels: 4: Reviews Complete, release-note, kind/bug

#10240 Cypress/E2E: Fix environment spec
  e2e/cypress/tests/integration/system_console/environment_spec.js
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, release-note-none

#10236 [MM-43638] Add placeholder to channel members search
  components/channel_members_rhs/search.tsx
  components/widgets/inputs/input/input.tsx
  i18n/en.json
Labels: 4: Reviews Complete, Setup Cloud Test Server, QA Review Done, AutoMerge, release-note-none

#10194 MM-34308: Migrate 'components/admin_console/group_settings' and associated tests to TypeScript
  components/admin_console/admin_definition.jsx
  components/admin_console/group_settings/__snapshots__/group_row.test.tsx.snap
  components/admin_console/group_settings/__snapshots__/group_settings.test.tsx.snap
  components/admin_console/group_settings/group_row.jsx
  components/admin_console/group_settings/group_row.test.tsx
  components/admin_console/group_settings/group_row.tsx
  components/admin_console/group_settings/group_settings.jsx
  components/admin_console/group_settings/group_settings.test.tsx
  components/admin_console/group_settings/group_settings.tsx
Labels: 4: Reviews Complete, release-note-none, Contributor

#10081 MM-41211: Switch to new config settings for session lengths.
  components/admin_console/admin_definition.jsx
  components/admin_console/session_length_settings.jsx
  components/admin_console/workspace-optimization/dashboard.tsx
  e2e/cypress/tests/integration/enterprise/extend_session/email_login_activity_spec.js
  e2e/cypress/tests/integration/enterprise/extend_session/not_extended_when_disabled/helpers.js
  e2e/cypress/tests/integration/enterprise/extend_session/not_extended_when_disabled/with_email_login_spec.js
  e2e/cypress/tests/integration/enterprise/extend_session/not_extended_when_disabled/with_ldap_login_spec.js
  e2e/cypress/tests/integration/enterprise/extend_session/session_length_spec.js
  e2e/cypress/tests/integration/system_console/session_length_spec.js
  e2e/cypress/tests/support/api/on_prem_default_config.json
  e2e/playwright/support/server/default_config.ts
  i18n/en.json
  packages/types/src/config.ts
  utils/admin_console_index.test.jsx
Labels: 3: QA Review, release-note

#10230 MM-42755: consistently run playbook
  components/channel_layout/playbook_runner.tsx
  packages/mattermost-redux/src/selectors/entities/channels.test.js
  packages/mattermost-redux/src/selectors/entities/channels.ts
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#10249 Automated cherry pick of #10236
  components/channel_members_rhs/search.tsx
  components/widgets/inputs/input/input.tsx
  i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#10191 MM-43352: syncs threads on reconnect
  actions/websocket_actions.jsx
Labels: 4: Reviews Complete, release-note-none

#10243 MM-28269 Allow clicking through mobile web view timestamp
  sass/components/_post.scss
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note, QA Deferred

#10237 [MM-43602] Channel Members RHS: improve perf
  components/channel_members_rhs/index.ts
Labels: Setup Cloud Test Server, QA Review Done, release-note-none
