Repository mattermost/mattermost-webapp, pull requests merged in 2022-02, with the labels that each got.

#9719 MM-38332: fixes dm category menu
  components/sidebar/sidebar_category/sidebar_category_sorting_menu/sidebar_category_sorting_menu.tsx
Labels: 4: Reviews Complete, release-note-none

#9708 MM-42320 Remove excess keyboard listeners from post components
  components/post_view/post/post.jsx
  components/rhs_comment/rhs_comment.jsx
  components/rhs_root_post/__snapshots__/rhs_root_post.test.jsx.snap
  components/rhs_root_post/rhs_root_post.jsx
Labels: 4: Reviews Complete, release-note

#9707 MM-41319 Reduced number of listeners registered by MenuWrapper
  components/widgets/menu/menu_wrapper.tsx
Labels: 4: Reviews Complete, release-note

#9729 Cypress/E2E: Fix react_to_center and close_current_dm_redirect specs
  e2e/cypress/integration/files_and_attachments/image_link_preview_spec.js
  e2e/cypress/integration/files_and_attachments/upload_files_spec.js
  e2e/cypress/integration/keyboard_shortcuts/ctrl_cmd_shift_slash/react_to_center_spec.js
  e2e/cypress/integration/multi_team_and_dm/close_current_dm_redirects_spec.js
Labels: Changelog/Not Needed, Docs/Not Needed, release-note-none

#9709 [MM-41189] Remove "Invite to team" feature flag
  components/invitation_modal/index.tsx
  components/invitation_modal/invitation_modal.test.tsx
  components/invitation_modal/invitation_modal.tsx
  components/invitation_modal/invite_as.scss
  components/invitation_modal/invite_as.test.tsx
  components/invitation_modal/invite_as.tsx
  components/invitation_modal/invite_view.test.tsx
  components/invitation_modal/invite_view.tsx
  e2e/cypress/integration/auth_sso/authentication_4_spec.js
  e2e/cypress/integration/enterprise/accessibility/accessibility_input_fields_spec.js
  e2e/cypress/integration/enterprise/guest_accounts/guest_invitation_ui_spec.js
  e2e/cypress/integration/team_settings/closed_team_invite_by_email_spec.js
  i18n/en.json
  packages/mattermost-redux/src/constants/config.ts
  packages/mattermost-redux/src/selectors/entities/preferences.ts
Labels: Setup Cloud Test Server, QA Review Done, release-note-none

#9721 [MM-41248] Add Clear Status 'x' Button to Status Dropdown Menu
  components/status_dropdown/__snapshots__/status_dropdown.test.tsx.snap
  components/status_dropdown/status_dropdown.scss
  components/status_dropdown/status_dropdown.test.tsx
  components/status_dropdown/status_dropdown.tsx
Labels: 4: Reviews Complete, release-note-none

#9733 cherry pick: Translations update from Mattermost Weblate #9728
  i18n/bg.json
  i18n/de.json
  i18n/en_AU.json
  i18n/es.json
  i18n/fr.json
  i18n/hu.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
  i18n/zh-CN.json
Labels: 4: Reviews Complete, release-note-none

#9695 Enable changing channel admin privs in TE
  components/channel_members_dropdown/__snapshots__/channel_members_dropdown.test.jsx.snap
  components/channel_members_dropdown/channel_members_dropdown.jsx
  components/channel_members_dropdown/channel_members_dropdown.test.jsx
  components/channel_members_dropdown/index.js
Labels: QA Review Done, release-note, Contributor

#9742 Automated cherry pick of #9695
  components/channel_members_dropdown/__snapshots__/channel_members_dropdown.test.jsx.snap
  components/channel_members_dropdown/channel_members_dropdown.jsx
  components/channel_members_dropdown/channel_members_dropdown.test.jsx
  components/channel_members_dropdown/index.js
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#9536 MM-39595 Banner Scenarios of trial period
  e2e/cypress/integration/enterprise/cloud/billing/banner_trial_spec.js
Labels: 4: Reviews Complete, QA Review Done, release-note-none, Contributor

#9741 Lock CI from /release-6.4
  .circleci/config.yml
  .gitlab-ci.yml
Labels: release-note-none

#9740 Automated cherry pick of #9646
  components/threading/virtualized_thread_viewer/virtualized_thread_viewer.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#9743 Automated cherry pick of #9646
  components/threading/virtualized_thread_viewer/virtualized_thread_viewer.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#9736 Automated cherry pick of #9541
  plugins/index.js
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#9737 Automated cherry pick of #9700
  components/threading/global_threads_link/global_threads_link.tsx
  components/tutorial/tutorial_tip/index.ts
  components/tutorial/tutorial_tip/tutorial_tip.test.tsx
  components/tutorial/tutorial_tip/tutorial_tip.tsx
  utils/constants.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#9738 Automated cherry pick of #9723
  components/sidebar/__snapshots__/channel_tutorial_tip.test.tsx.snap
  components/sidebar/channel_tutorial_tip.tsx
  sass/components/_tutorial.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#9696 [MM-40920] - Enterprise Trial Activation Tour Point
  actions/views/product_menu.ts
  components/global_header/left_controls/product_menu/__snapshots__/product_menu.test.tsx.snap
  components/global_header/left_controls/product_menu/product_menu.test.tsx
  components/global_header/left_controls/product_menu/product_menu.tsx
  components/tutorial/tutorial_tip/index.ts
  components/tutorial/tutorial_tip/tutorial_tip.test.tsx
  components/tutorial/tutorial_tip/tutorial_tip.tsx
  components/widgets/menu/menu_items/menu_item.scss
  components/widgets/menu/menu_items/menu_start_trial.test.tsx
  components/widgets/menu/menu_items/menu_start_trial.tsx
  e2e/cypress/integration/onboarding/finish_tutorial_spec.js
  e2e/cypress/integration/onboarding/tutorial_guided_tour_spec.js
  i18n/en.json
  reducers/views/index.ts
  reducers/views/product_menu.ts
  sass/components/_tutorial.scss
  selectors/views/product_menu.ts
  types/store/views.ts
  utils/constants.jsx
Labels: 2: Dev Review, Setup Cloud Test Server, QA Review Done, release-note-none

#9745 clean up test output
  components/admin_console/billing/billing_history.tsx
  components/admin_console/billing/billing_subscriptions/billing_subscriptions.tsx
  components/admin_console/billing/billing_summary/billing_summary.tsx
  components/admin_console/billing/company_info_display.tsx
  components/admin_console/billing/payment_info_display.tsx
  components/common/svg_images_components/background_svg.tsx
  components/common/svg_images_components/cloud_trial_svg.tsx
  components/common/svg_images_components/company_svg.tsx
  components/common/svg_images_components/credit_card_svg.tsx
  components/common/svg_images_components/empty_billing_history_svg.tsx
  components/common/svg_images_components/mattermost_cloud_svg.tsx
  components/common/svg_images_components/payment_failed_svg.tsx
  components/common/svg_images_components/payment_success_standard_svg.tsx
  components/common/svg_images_components/private_cloud_svg.tsx
  components/common/svg_images_components/upgrade_svg.tsx
  components/error_page/workspace_user_limit_reached.tsx
  components/next_steps_view/download_section.tsx
  components/next_steps_view/images/download-apps-svg.tsx
  components/purchase_modal/process_payment_setup.tsx
  components/purchase_modal/purchase_modal.tsx
Labels: 2: Dev Review, 4: Reviews Complete, QA Review Done, release-note-none, QA Deferred

#9718 MM-41331 : Remove post dot menu from RHS post when not hovered upon
  components/rhs_comment/rhs_comment.jsx
  components/rhs_root_post/__snapshots__/rhs_root_post.test.jsx.snap
  components/rhs_root_post/rhs_root_post.jsx
  components/rhs_root_post/rhs_root_post.test.jsx
  e2e/cypress/integration/messaging/reactions_spec.js
Labels: 4: Reviews Complete, Docs/Not Needed, release-note

#9746 Update NOTICE.txt
  NOTICE.txt
Labels: 4: Reviews Complete, CherryPick/Approved, AutoMerge, release-note-none

#9748 Automated cherry pick of #9746
  NOTICE.txt
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#9750 Fix failing unit tests in TutorialTip
  components/tutorial/tutorial_tip/tutorial_tip.test.tsx
Labels: 4: Reviews Complete, release-note-none

#9730 Growth spike/add remaining UI elements
  components/admin_console/workspace-optimization/__snapshots__/cta_buttons.test.tsx.snap
  components/admin_console/workspace-optimization/cta_buttons.test.tsx
  components/admin_console/workspace-optimization/cta_buttons.tsx
  components/admin_console/workspace-optimization/dashboard.data.tsx
  components/admin_console/workspace-optimization/dashboard.scss
  components/admin_console/workspace-optimization/dashboard.tsx
  components/admin_console/workspace-optimization/overall-score.tsx
  components/common/accordion/accordion_item.tsx
  components/common/accordion/message_item.tsx
  components/common/svg_images_components/success_icon_svg.tsx
  components/common/svg_images_components/warning_svg.tsx
  components/trial_benefits_modal/trial_benefits_modal.tsx
  i18n/en.json
  sass/base/_css_variables.scss
  utils/constants.jsx
Labels: Setup Cloud Test Server, release-note-none

#9747 [MM-40890] Fix DND Calendar Date Hover
  sass/components/_day-picker.scss
Labels: 4: Reviews Complete, release-note-none

#9744 Cypress/E2E: Potential fix for recently used emoji spec
  e2e/cypress/integration/emoji/recently_used_emoji_1_spec.js
  e2e/cypress/integration/emoji/recently_used_emoji_2_spec.js
  e2e/cypress/integration/mark_as_unread/mark_as_unread_spec.js
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, release-note-none

#9754 Fix and update channel switch performance telemetry tracking
  actions/telemetry_actions.jsx
  components/channel_view/channel_view.tsx
  components/post_view/post_list/post_list.jsx
  components/sidebar/sidebar_channel/sidebar_channel_link/sidebar_channel_link.tsx
Labels: 4: Reviews Complete, release-note-none, QA Deferred

#9698 MM-41329 : Avoid re-rendering of CustomStatusEmoji component on post hovering
  components/channel_header/__snapshots__/channel_header.test.jsx.snap
  components/custom_status/__snapshots__/custom_status_emoji.test.tsx.snap
  components/custom_status/custom_status_emoji.tsx
  components/profile_popover/__snapshots__/profile_popover.test.tsx.snap
  components/rhs_comment/__snapshots__/rhs_comment.test.jsx.snap
  components/rhs_root_post/__snapshots__/rhs_root_post.test.jsx.snap
  components/status_dropdown/__snapshots__/status_dropdown.test.tsx.snap
Labels: 4: Reviews Complete, Docs/Not Needed, release-note

#9753 [MM-41570] Moving next on dismiss on boarding tour and finished value
  components/tutorial/tutorial_tip/tutorial_tip.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, release-note, QA Deferred

#9749 MM-41511 Fix repeated calls to makeGetCategory
  components/sidebar/sidebar_channel/sidebar_channel_link/index.ts
  components/tutorial/tutorial_tip/index.ts
  selectors/onboarding.ts
Labels: 4: Reviews Complete, release-note-none, QA Deferred

#9763 [MM-41570]Moving next on dismiss on boarding tour and finished value
  components/tutorial/tutorial_tip/tutorial_tip.tsx
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#9751 Mm 40894 not able to download license from download history
  components/admin_console/billing/__snapshots__/billing_history.test.tsx.snap
  components/admin_console/billing/billing_history.test.tsx
  components/admin_console/billing/billing_history.tsx
Labels: QA Review Done, Setup Cloud + CWS Test Server, release-note-none

#9761 replace custom svgs with compass svgs
  components/admin_console/workspace-optimization/dashboard.data.tsx
  components/admin_console/workspace-optimization/dashboard.scss
  components/admin_console/workspace-optimization/dashboard.tsx
  components/admin_console/workspace-optimization/overall-score.tsx
  components/common/svg_images_components/configuration_svg.tsx
  components/common/svg_images_components/data_privacy_svg.tsx
  components/common/svg_images_components/easy_management_svg.tsx
  components/common/svg_images_components/performance_svg.tsx
  components/common/svg_images_components/security_svg.tsx
  components/common/svg_images_components/success_icon_svg.tsx
  components/common/svg_images_components/updates_and_errors_svg.tsx
  components/common/svg_images_components/warning_svg.tsx
  components/common/svg_images_components/workspace_access_svg.tsx
  package-lock.json
  package.json
Labels: release-note-none

#9713 MM-40527 Upgrade to redux-persist@6.0.0 and set it up properly
  .eslintrc.json
  actions/global_actions.tsx
  actions/storage.js
  actions/storage.test.js
  e2e/cypress/integration/messaging/helpers.js
  e2e/cypress/integration/messaging/message_draft_persistance_spec.js
  e2e/cypress/integration/messaging/message_draft_then_switch_channel_spec.js
  package-lock.json
  package.json
  packages/mattermost-redux/src/reducers/entities/posts.ts
  packages/mattermost-redux/src/store/configureStore.ts
  packages/mattermost-redux/src/store/helpers.ts
  packages/mattermost-redux/src/store/reducer_registry.test.js
  packages/mattermost-redux/src/store/reducer_registry.ts
  packages/mattermost-redux/src/types/actions.ts
  packages/mattermost-redux/src/types/module.d.ts
  packages/mattermost-redux/test/test_store.js
  reducers/storage.test.js
  reducers/storage.ts
  store/index.js
  stores/browser_store.tsx
  tests/redux-persist_mock.js
  utils/constants.jsx
Labels: 4: Reviews Complete, release-note

#9755 MM-41342 Revert fixes related to using team sidebar in products
  components/root/root.jsx
  sass/base/_structure.scss
  sass/layout/_sidebar-left.scss
  sass/layout/_team-sidebar.scss
  sass/routes/_backstage.scss
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, release-note-none

#9779 Automated cherry pick of #9755
  components/root/root.jsx
  sass/base/_structure.scss
  sass/layout/_sidebar-left.scss
  sass/layout/_team-sidebar.scss
  sass/routes/_backstage.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#9772 feature flag guard for workspace optimization dashboard
  components/admin_console/admin_definition.jsx
  components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.jsx.snap
  components/admin_console/admin_sidebar/admin_sidebar.test.jsx
  components/admin_console/workspace-optimization/dashboard.tsx
  package-lock.json
  package.json
Labels: 2: Dev Review, release-note-none

#9712 MM-41152: fixes RHS results when changing screens
  components/search_results/search_results.tsx
  reducers/views/rhs.ts
Labels: QA Review Done, release-note

#9511 [MM-35298] Send RootId with add to channel request
  components/post_view/post_add_channel_member/post_add_channel_member.test.tsx
  components/post_view/post_add_channel_member/post_add_channel_member.tsx
  components/threading/virtualized_thread_viewer/thread_viewer_row.tsx
Labels: 4: Reviews Complete, release-note-none

#9783 added correct severity levels to the accordion items
  components/admin_console/workspace-optimization/dashboard.data.tsx
  components/admin_console/workspace-optimization/dashboard.tsx
Labels: 1: PM Review, 2: Dev Review, release-note-none

#9782 MM-41578 - replace duplicated item with the ldap feature description
  components/admin_console/billing/plan_details/__snapshots__/plan_details.test.tsx.snap
  components/admin_console/billing/plan_details/plan_details.test.tsx
  components/admin_console/billing/plan_details/plan_details.tsx
  i18n/en.json
Labels: 2: Dev Review, QA Review Done, Setup Cloud + CWS Test Server, release-note-none

#9756 MM-40887 Fix team sidebar covered by global header with announcement bar visible
  sass/layout/_team-sidebar.scss
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note

#9003 MM-36589: user previous unread counts for CRT from ws
  actions/websocket_actions.jsx
  components/threading/global_threads/thread_item/thread_item.tsx
  packages/mattermost-redux/src/actions/threads.ts
Labels: 4: Reviews Complete, release-note-none

#9787 Automated cherry pick of #9756
  sass/layout/_team-sidebar.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#9758 Enable performance telemetry tracking for production deployments
  actions/telemetry_actions.jsx
  actions/telemetry_actions.test.js
  utils/utils.jsx
Labels: 2: Dev Review, release-note, QA Deferred

#9697 MM-41327 : Avoid re-rendering of TextboxLinks component on typing
  components/create_comment/__snapshots__/create_comment.test.jsx.snap
  components/create_comment/create_comment.tsx
  components/create_post/__snapshots__/create_post.test.jsx.snap
  components/create_post/create_post.tsx
  components/edit_channel_header_modal/__snapshots__/edit_channel_header_modal.test.tsx.snap
  components/edit_channel_header_modal/edit_channel_header_modal.tsx
  components/edit_post_modal/__snapshots__/edit_post_modal.test.tsx.snap
  components/edit_post_modal/edit_post_modal.tsx
  components/textbox/textbox_links/textbox_links.tsx
Labels: 4: Reviews Complete, Docs/Not Needed, release-note

#9724 [MM-40582] Use user_updated event's user to state, to prevent extra GetMe() ping
  actions/websocket_actions.jsx
  components/user_settings/general/index.ts
  components/user_settings/general/user_settings_general.test.tsx
  components/user_settings/general/user_settings_general.tsx
Labels: 4: Reviews Complete, release-note, Contributor

#9771 Cypress/E2E: MM-T2077: Profile Picture: Non image file shows an error
  e2e/cypress/fixtures/txt-changed-as-png.png
  e2e/cypress/integration/account_settings/profile/profile_picture_spec.js
Labels: 2: Dev Review, release-note-none, Contributor

#9801 Automated cherry pick of #9707
  components/widgets/menu/menu_wrapper.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#9800 Automated cherry pick of #9708
  components/post_view/post/post.jsx
  components/rhs_comment/rhs_comment.jsx
  components/rhs_root_post/__snapshots__/rhs_root_post.test.jsx.snap
  components/rhs_root_post/rhs_root_post.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#9799 Automated cherry pick of #9732
  components/sidebar/sidebar_channel/__snapshots__/sidebar_channel.test.tsx.snap
  components/sidebar/sidebar_channel/sidebar_channel.tsx
  e2e/cypress/integration/channel_sidebar/category_collapsing_spec.js
  e2e/cypress/integration/channel_sidebar/dm_gm_filtering_sorting_spec.js
  sass/layout/_sidebar-left.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#9764 [MM-36643] Have rudder use the domain given on SiteURL for its cookies.
  components/root/root.jsx
Labels: 4: Reviews Complete, release-note

#9798 MM-41397_License page shows upgrade to Enterprise for E20 licenses
  components/admin_console/license_settings/__snapshots__/license_settings.test.jsx.snap
  components/admin_console/license_settings/enterprise_edition/enterprise_edition_right_panel.test.tsx
  components/admin_console/license_settings/enterprise_edition/enterprise_edition_right_panel.tsx
  components/admin_console/license_settings/license_settings.test.jsx
  components/admin_console/license_settings/license_settings.tsx
  e2e/cypress/integration/enterprise/system_console/about/edition_and_license_spec.js
  i18n/en.json
  utils/license_utils.jsx
  utils/license_utils.test.jsx
Labels: Setup Cloud Test Server, QA Review Done, release-note-none

#9727 Onboarding check list
  components/global_header/global_header.tsx
  components/global_onboarding_list/onboarding_checklist.tsx
  components/global_onboarding_list/onboarding_checklist_animations.tsx
  components/global_onboarding_list/onboarding_checklist_completed.tsx
  components/global_onboarding_list/onboarding_checklist_popover.tsx
  components/global_onboarding_list/onboarding_checklist_task.tsx
  components/next_steps_view/steps.ts
  components/root/index.js
  components/root/root.jsx
  i18n/en.json
  images/completed.svg
  images/onboarding-checklist.svg
  package-lock.json
  package.json
  utils/constants.jsx
Labels: 2: Dev Review, Setup Cloud Test Server, 1: UX Review, release-note-none

#9694 MM-39622: jittery typing on thread explode
  packages/mattermost-redux/src/actions/posts.ts
Labels: 4: Reviews Complete, release-note-none

#9775 MM-40918-Highlighted Enterprise Features after Starting an Enterprise…
  components/common/carousel/carousel.test.tsx
  components/common/carousel/carousel.tsx
  components/common/svg_images_components/guest_access_svg.tsx
  components/common/svg_images_components/ldap_svg.tsx
  components/common/svg_images_components/person_mac_svg.tsx
  components/common/svg_images_components/person_with_box_svg.tsx
  components/common/svg_images_components/person_with_servers_svg.tsx
  components/common/svg_images_components/person_with_sheet_svg.tsx
  components/common/svg_images_components/push_notifications_svg.tsx
  components/trial_benefits_modal/__snapshots__/trial_benefits_modal_step.test.tsx.snap
  components/trial_benefits_modal/__snapshots__/trial_benefits_modal_step_more.test.tsx.snap
  components/trial_benefits_modal/trial_benefits_modal.scss
  components/trial_benefits_modal/trial_benefits_modal.test.tsx
  components/trial_benefits_modal/trial_benefits_modal.tsx
  components/trial_benefits_modal/trial_benefits_modal_step.scss
  components/trial_benefits_modal/trial_benefits_modal_step.test.tsx
  components/trial_benefits_modal/trial_benefits_modal_step.tsx
  components/trial_benefits_modal/trial_benefits_modal_step_more.scss
  components/trial_benefits_modal/trial_benefits_modal_step_more.test.tsx
  components/trial_benefits_modal/trial_benefits_modal_step_more.tsx
  i18n/en.json
Labels: QA Review Done, release-note-none

#9769 MM-41637 Remove API telemetry on most GET requests
  packages/mattermost-redux/src/client/client4.ts
Labels: 4: Reviews Complete, release-note

#9686 MM-41211: Allows SessionLengthSSOInDays to validate and accept a decimals.
  components/admin_console/admin_settings.tsx
  components/admin_console/session_length_settings.jsx
Labels: 4: Reviews Complete, release-note

#9793 Adjust some more ux styles
  components/admin_console/workspace-optimization/chip_list.test.tsx
  components/admin_console/workspace-optimization/chips_list.tsx
  components/admin_console/workspace-optimization/dashboard.data.tsx
  components/admin_console/workspace-optimization/dashboard.scss
  components/admin_console/workspace-optimization/dashboard.tsx
  components/common/chip/chip.tsx
  i18n/en.json
  sass/admin_console_base/_sys_css_variables.scss
Labels: 2: Dev Review, Setup Cloud Test Server, 1: UX Review, release-note-none

#9815 Translations update from Mattermost Weblate
  i18n/bg.json
  i18n/de.json
  i18n/en_AU.json
  i18n/es.json
  i18n/fr.json
  i18n/hu.json
  i18n/it.json
  i18n/ja.json
  i18n/nl.json
  i18n/pl.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
  i18n/zh-CN.json
Labels: Changelog/Not Needed, Docs/Not Needed, release-note-none

#9770 tests : MM-T1228 CTRL/CMD+K - Open DM with user not on the current team
  e2e/cypress/integration/keyboard_shortcuts/ctrl_cmd_k_user_from_other_team_spec.js
Labels: release-note-none, Contributor

#9794 [MM-29724] Allow plugin to add menu items to the user guide dropdown
  components/global_header/center_controls/user_guide_dropdown/__snapshots__/user_guide_dropdown.test.tsx.snap
  components/global_header/center_controls/user_guide_dropdown/index.ts
  components/global_header/center_controls/user_guide_dropdown/user_guide_dropdown.test.tsx
  components/global_header/center_controls/user_guide_dropdown/user_guide_dropdown.tsx
  plugins/registry.js
  reducers/plugins/index.ts
  selectors/plugins.ts
  types/store/plugins.ts
Labels: release-note, QA Deferred

#9813 chore/MM-40559 : Add memoization to getOneClickReactionEmojis (#9653) (6.3)
  actions/emoji_actions.js
  actions/emoji_actions.test.js
  actions/local_storage.jsx
  selectors/emojis.js
  stores/local_storage_store.jsx
  stores/local_storage_store.test.jsx
Labels: 4: Reviews Complete, CherryPick/Done, release-note-none

#9810 MM-41331 : Remove post dot menu from RHS post when not hovered upon (#9718) (6.3)
  components/rhs_comment/rhs_comment.jsx
  components/rhs_root_post/__snapshots__/rhs_root_post.test.jsx.snap
  components/rhs_root_post/rhs_root_post.jsx
  components/rhs_root_post/rhs_root_post.test.jsx
  e2e/cypress/integration/messaging/reactions_spec.js
Labels: CherryPick/Done, AutoMerge, release-note-none

#9811 MM-41329 : Avoid re-rendering of CustomStatusEmoji component on post hovering (#9698) (6.3)
  components/channel_header/__snapshots__/channel_header.test.jsx.snap
  components/custom_status/__snapshots__/custom_status_emoji.test.tsx.snap
  components/custom_status/custom_status_emoji.tsx
  components/profile_popover/__snapshots__/profile_popover.test.tsx.snap
  components/rhs_comment/__snapshots__/rhs_comment.test.jsx.snap
  components/rhs_root_post/__snapshots__/rhs_root_post.test.jsx.snap
  components/status_dropdown/__snapshots__/status_dropdown.test.tsx.snap
Labels: 4: Reviews Complete, CherryPick/Done, release-note-none

#9812 MM-41327 : Avoid re-rendering of TextboxLinks component on typing (#9697) (6.3)
  components/create_comment/__snapshots__/create_comment.test.jsx.snap
  components/create_comment/create_comment.tsx
  components/create_post/__snapshots__/create_post.test.jsx.snap
  components/create_post/create_post.tsx
  components/edit_channel_header_modal/__snapshots__/edit_channel_header_modal.test.tsx.snap
  components/edit_channel_header_modal/edit_channel_header_modal.tsx
  components/edit_post_modal/__snapshots__/edit_post_modal.test.tsx.snap
  components/edit_post_modal/edit_post_modal.tsx
  components/textbox/textbox_links/textbox_links.tsx
Labels: 4: Reviews Complete, CherryPick/Done, release-note-none

#9817 Translations update from Mattermost Weblate
  i18n/de.json
  i18n/en_AU.json
  i18n/hu.json
  i18n/ja.json
  i18n/nl.json
  i18n/pl.json
  i18n/sv.json
  i18n/tr.json
Labels: Changelog/Not Needed, Docs/Not Needed, release-note-none

#9821 MM-40148
  actions/websocket_actions.jsx
  components/threading/global_threads/global_threads.tsx
  components/threading/global_threads_link/global_threads_link.tsx
  packages/mattermost-redux/src/action_types/threads.ts
  packages/mattermost-redux/src/actions/threads.test.js
  packages/mattermost-redux/src/actions/threads.ts
  packages/mattermost-redux/src/client/client4.ts
  packages/mattermost-redux/src/reducers/entities/threads/counts.ts
  packages/mattermost-redux/src/reducers/entities/threads/threads.test.js
Labels: do-not-merge/release-note-label-needed

#9792 Fix error that happens when clicking on some SizeAwareImages
  components/size_aware_image.jsx
Labels: 4: Reviews Complete, release-note-none

#9816 Updated search box behaviour test cases
  e2e/cypress/integration/account_settings/profile/username_spec.js
  e2e/cypress/integration/keyboard_shortcuts/ctrl_cmd_shift_m_spec.js
  e2e/cypress/integration/notifications/at_icon_still_shows_mentions_list_with_deactivated_triggers_spec.js
  e2e/cypress/integration/search/clear_input_spec.js
  e2e/cypress/integration/settings/sidebar/channel_switcher_not_cloud_spec.js
Labels: 4: Reviews Complete, release-note-none

#9791 Cypress/E2E:fixed cloud test cases
  e2e/cypress/integration/files_and_attachments/channel_files_spec.js
  e2e/cypress/integration/mark_as_unread/mark_as_unread_using_shortcuts_spec.js
  e2e/cypress/integration/onboarding/use_team_invite_link_to_sign_up_spec.js
Labels: 4: Reviews Complete, release-note-none

#9796 MM-40755 : Editing the text in the channel switcher does not work as expected
  components/quick_switch_modal/__snapshots__/quick_switch_modal.test.tsx.snap
  components/quick_switch_modal/quick_switch_modal.tsx
  components/suggestion/suggestion_box/suggestion_box.jsx
Labels: 4: Reviews Complete, release-note

#9818 handle differet license states
  components/admin_console/workspace-optimization/dashboard.data.tsx
  components/announcement_bar/contact_sales/contact_us.tsx
  components/announcement_bar/renewal_link/renewal_link.tsx
  components/trial_benefits_modal/trial_benefits_modal.tsx
  i18n/en.json
  utils/constants.jsx
Labels: 2: Dev Review, release-note-none

#9768 MM-41176 Don't send Rudder requests when blocked
  components/root/root.jsx
  components/root/root.test.jsx
Labels: 4: Reviews Complete, release-note, QA Deferred

#9806 CHORE: updated compass-icon package
  package-lock.json
  package.json
Labels: 4: Reviews Complete, release-note, kind/chore

#9757 [MM-40216] Fix Team Statistics Labels and Graph Not Rendering
  components/analytics/team_analytics/team_analytics.tsx
Labels: 4: Reviews Complete, release-note-none

#9803 MM-41096 Adding feature card slide for playbooks.
  components/common/svg_images_components/person_with_checklist.tsx
  components/trial_benefits_modal/__snapshots__/trial_benefits_modal_step.test.tsx.snap
  components/trial_benefits_modal/trial_benefits_modal.test.tsx
  components/trial_benefits_modal/trial_benefits_modal.tsx
  components/trial_benefits_modal/trial_benefits_modal_step.test.tsx
  components/trial_benefits_modal/trial_benefits_modal_step.tsx
  components/trial_benefits_modal/trial_benefits_modal_step_more.test.tsx
  components/trial_benefits_modal/trial_benefits_modal_step_more.tsx
  i18n/en.json
Labels: 2: Dev Review, release-note-none

#9830 Only call getMyFirstChannelForTeams if needed
  packages/mattermost-redux/src/selectors/entities/channels.ts
Labels: 4: Reviews Complete, release-note-none, QA Deferred

#9837 Change Tasklist show condition
  components/root/index.js
Labels: release-note-none

#9828 Remove unused tutorial tip code
  components/create_post/create_post.test.jsx
  components/create_post/create_post_tip.tsx
  components/global_header/left_controls/product_menu/product_menu_tip/__snapshots__/product_menu_tip.test.tsx.snap
  components/global_header/left_controls/product_menu/product_menu_tip/index.tsx
  components/global_header/left_controls/product_menu/product_menu_tip/product_menu_tip.test.tsx
  components/global_header/left_controls/product_menu/product_menu_tip/product_menu_tip.tsx
  components/global_header/right_controls/settings_tip.tsx
  components/next_steps_view/steps/create_first_channel_step/create_first_channel_step.tsx
  components/sidebar/__snapshots__/channel_tutorial_tip.test.tsx.snap
  components/sidebar/add_channel_tutorial_tip.tsx
  components/sidebar/channel_tutorial_tip.test.tsx
  components/sidebar/channel_tutorial_tip.tsx
  components/tutorial/menu_tutorial_tip.tsx
  components/tutorial/tutorial_tip_legacy/tutorial_tip.test.tsx
  i18n/en.json
Labels: 2: Dev Review, release-note, QA Deferred

#9826 MM-41280 - refactor the payment page layout so the content fits well
  components/purchase_modal/icon_message.scss
  components/purchase_modal/purchase.scss
Labels: 2: Dev Review, QA Review Done, Setup Cloud + CWS Test Server, release-note-none

#9838 Fixes for integrating task list and onboarding wizard
  components/channel_layout/center_channel/index.ts
  components/channel_view/__snapshots__/channel_view.test.tsx.snap
  components/channel_view/channel_view.test.tsx
  components/channel_view/channel_view.tsx
  components/channel_view/index.ts
  components/global_header/center_controls/user_guide_dropdown/index.ts
  components/global_header/center_controls/user_guide_dropdown/user_guide_dropdown.test.tsx
  components/global_header/center_controls/user_guide_dropdown/user_guide_dropdown.tsx
  components/main_menu/index.tsx
  components/main_menu/main_menu.test.tsx
  components/main_menu/main_menu.tsx
  components/onboarding_tasklist/onboarding_tasklist.tsx
  components/preparing_workspace/preparing_workspace.tsx
  components/sidebar/sidebar_channel/sidebar_channel_link/sidebar_channel_link.tsx
  components/sidebar/sidebar_next_steps/index.ts
  components/sidebar/sidebar_next_steps/sidebar_next_steps.tsx
  components/threading/global_threads/global_threads.tsx
  plugins/test/main_menu_action.test.jsx
Labels: 2: Dev Review, release-note-none, QA Deferred

#9820 MM-42369 - restrict add members btn to roles with permissions
  components/popover_list_members/popover_list_members.jsx
  components/popover_list_members/popover_list_members.test.jsx
Labels: 2: Dev Review, Setup Cloud Test Server, QA Review Done, release-note-none

#9840 Cherry-pick to 6.4 of "Improving selectors of Textbox component (#9831)"
  components/__snapshots__/textbox.test.tsx.snap
  components/suggestion/at_mention_provider/at_mention_provider.jsx
  components/suggestion/at_mention_provider/at_mention_provider.test.jsx
  components/suggestion/suggestion_box/suggestion_box.test.jsx
  components/textbox/index.ts
  components/textbox/textbox.tsx
  packages/mattermost-redux/src/selectors/entities/channels.ts
  packages/mattermost-redux/src/selectors/entities/utils.ts
Labels: release-note

#9842 Cherry-pick to 6.2 of "Improving selectors of Textbox component (#9831)"
  components/__snapshots__/textbox.test.tsx.snap
  components/suggestion/at_mention_provider/at_mention_provider.jsx
  components/suggestion/at_mention_provider/at_mention_provider.test.jsx
  components/suggestion/suggestion_box/suggestion_box.test.jsx
  components/textbox/index.ts
  components/textbox/textbox.tsx
  packages/mattermost-redux/src/selectors/entities/channels.ts
  packages/mattermost-redux/src/selectors/entities/utils.ts
Labels: release-note

#9841 Cherry-pick to 6.3 of "Improving selectors of Textbox component (#9831)"
  components/__snapshots__/textbox.test.tsx.snap
  components/rhs_root_post/__snapshots__/rhs_root_post.test.jsx.snap
  components/suggestion/at_mention_provider/at_mention_provider.jsx
  components/suggestion/at_mention_provider/at_mention_provider.test.jsx
  components/suggestion/suggestion_box/suggestion_box.test.jsx
  components/textbox/index.ts
  components/textbox/textbox.tsx
  packages/mattermost-redux/src/selectors/entities/channels.ts
  packages/mattermost-redux/src/selectors/entities/utils.ts
Labels: release-note

#9846 MM-41812 Fix instances of CreatePost being leaked
  components/create_post/create_post.tsx
Labels: 4: Reviews Complete, release-note, QA Deferred

#9850 Revert "Automated cherry pick of #9732"
  components/sidebar/sidebar_channel/__snapshots__/sidebar_channel.test.tsx.snap
  components/sidebar/sidebar_channel/sidebar_channel.tsx
  e2e/cypress/integration/channel_sidebar/category_collapsing_spec.js
  e2e/cypress/integration/channel_sidebar/dm_gm_filtering_sorting_spec.js
  sass/layout/_sidebar-left.scss
Labels: 2: Dev Review, release-note-none

#9725 MM-41332 : Move "SERVER_DIR" env var to cli args for emoji_gen file
  build/emoji/emoji_gen.mjs
Labels: 4: Reviews Complete, release-note, QA Deferred, Contributor

#9829 [MM-41851] - Add Start Trial to admin onboarding checklist
  components/onboarding_tasklist/onboarding_tasklist.tsx
  components/onboarding_tasks/constants.ts
  components/onboarding_tasks/onboarding_tasks_manager.tsx
  components/root/root.jsx
  i18n/en.json
  utils/constants.jsx
Labels: Setup Cloud Test Server, QA Review Done, release-note-none

#9859 Automated cherry pick of #9829
  components/onboarding_tasklist/onboarding_tasklist.tsx
  components/onboarding_tasks/constants.ts
  components/onboarding_tasks/onboarding_tasks_manager.tsx
  components/root/root.jsx
  i18n/en.json
  utils/constants.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#9860 Automated cherry pick of #9843
  components/onboarding_tasklist/onboarding_tasklist_completed.tsx
  i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#9835 [MM-41841] Changing group icon for mention suggestion
  components/suggestion/at_mention_provider/at_mention_suggestion.jsx
Labels: release-note

#9788 [MM-41398] Fix Selecting a Status from Recent Status Uses Original Expiration Time
  components/custom_status/custom_status_modal.tsx
  e2e/cypress/integration/custom_status/custom_status_expiry/custom_status_expiry_1_spec.js
Labels: 4: Reviews Complete, release-note-none

#9795 [MM-33679] Fix Accessibility for Custom Status and Modals
  components/custom_status/custom_status_modal.tsx
  components/delete_category_modal/delete_category_modal.tsx
  components/dnd_custom_time_picker_modal/dnd_custom_time_picker_modal.tsx
  components/edit_category_modal/edit_category_modal.tsx
  components/generic_modal.tsx
  components/status_dropdown/__snapshots__/status_dropdown.test.tsx.snap
  components/status_dropdown/status_dropdown.tsx
Labels: 4: Reviews Complete, release-note-none

#9864 Automated cherry pick of #9835
  components/suggestion/at_mention_provider/at_mention_suggestion.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#9839 [MM-41671] Support Email Position+Validation
  components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
  components/admin_console/admin_definition.jsx
  components/admin_console/custom_plugin_settings/__snapshots__/custom_plugin_settings.test.jsx.snap
  components/admin_console/schema_admin_settings.jsx
  components/admin_console/text_setting.test.tsx
  components/admin_console/text_setting.tsx
  components/admin_console/validation.tsx
  e2e/cypress/integration/enterprise/system_console/ui_and_api/notifications_spec.js
  e2e/cypress/integration/system_console/ui_and_api/customization_spec.js
  i18n/en.json
Labels: 4: Reviews Complete, Setup Cloud Test Server, QA Review Done, release-note

#9759 MM-39780: Hides 'Invite People' when guest access and permissions dictate.
  components/main_menu/__snapshots__/main_menu.test.tsx.snap
  components/main_menu/index.tsx
  components/main_menu/main_menu.test.tsx
  components/main_menu/main_menu.tsx
  plugins/test/__snapshots__/main_menu_action.test.jsx.snap
Labels: 3: QA Review, Setup Cloud Test Server, release-note-none

#9869 Fix possible leak in SidebarChannel
  components/sidebar/sidebar_category/sidebar_category.tsx
Labels: 4: Reviews Complete, release-note

#9849 [MM-41904] Optimize group list permissions
  components/user_groups_modal/user_groups_list/index.ts
  packages/mattermost-redux/src/selectors/entities/roles.test.js
  packages/mattermost-redux/src/selectors/entities/roles.ts
  packages/mattermost-redux/test/test_helper.js
Labels: release-note-none

#9874 Automated cherry pick of #9849
  components/user_groups_modal/user_groups_list/index.ts
  packages/mattermost-redux/src/selectors/entities/roles.test.js
  packages/mattermost-redux/src/selectors/entities/roles.ts
  packages/mattermost-redux/test/test_helper.js
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#9584 [MM-38891] - CRT: threads list loading indicator and search guidance …
  components/common/svg_images_components/search_hint_svg.tsx
  components/no_results_indicator/__snapshots__/no_results_indicator.test.tsx.snap
  components/no_results_indicator/no_results_indicator.scss
  components/no_results_indicator/no_results_indicator.test.tsx
  components/no_results_indicator/no_results_indicator.tsx
  components/no_results_indicator/types.ts
  components/search_shortcut/search_shortcut.tsx
  components/threading/global_threads/global_threads.tsx
  components/threading/global_threads/thread_list/__snapshots__/thread_list.test.tsx.snap
  components/threading/global_threads/thread_list/__snapshots__/virtualized_thread_list.test.tsx.snap
  components/threading/global_threads/thread_list/__snapshots__/virtualized_thread_list_row.test.tsx.snap
  components/threading/global_threads/thread_list/thread_list.scss
  components/threading/global_threads/thread_list/thread_list.test.tsx
  components/threading/global_threads/thread_list/thread_list.tsx
  components/threading/global_threads/thread_list/virtualized_thread_list.test.tsx
  components/threading/global_threads/thread_list/virtualized_thread_list.tsx
  components/threading/global_threads/thread_list/virtualized_thread_list_row.test.tsx
  components/threading/global_threads/thread_list/virtualized_thread_list_row.tsx
  e2e/cypress/integration/collapsed_reply_threads/following_spec.js
  i18n/en.json
  utils/constants.jsx
Labels: Setup Cloud Test Server, QA Review Done, release-note

#9855 Translations update from Mattermost Weblate
  i18n/bg.json
  i18n/de.json
  i18n/en_AU.json
  i18n/es.json
  i18n/fa.json
  i18n/fr.json
  i18n/hu.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: Changelog/Not Needed, Docs/Not Needed, release-note-none

#9868 [MM-41408] Remove FF for auto tour
  components/tutorial/tutorial_tip_legacy/index.ts
  packages/mattermost-redux/src/constants/config.ts
  packages/mattermost-redux/src/selectors/entities/preferences.ts
  packages/mattermost-redux/src/types/config.ts
Labels: 4: Reviews Complete, QA Review Done, release-note-none

#9882 fix conflicts for weblate
  i18n/bg.json
  i18n/de.json
  i18n/en_AU.json
  i18n/es.json
  i18n/fa.json
  i18n/fr.json
  i18n/hu.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: Changelog/Not Needed, Docs/Not Needed, release-note-none

#9866 Modify tasklist plugins show condition based on user preference in onboarding flow
  components/onboarding_tasks/onboarding_tasks_manager.tsx
Labels: 2: Dev Review, release-note, QA Deferred

#9884 Automated cherry pick of #9866
  components/onboarding_tasks/onboarding_tasks_manager.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#9886 Fix/weblate conflicts new
  i18n/fa.json
Labels: Changelog/Not Needed, Docs/Not Needed, release-note-none, kind/bug

#9885 Read from myTeams if there is no currentTeam
  components/preparing_workspace/preparing_workspace.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none, QA Deferred

#9889 Automated cherry pick of #9885
  components/preparing_workspace/preparing_workspace.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#9827 Fixed a bug that causing gap to appear in products using team sidebar…
  sass/layout/_team-sidebar.scss
Labels: Setup Cloud Test Server, release-note

#9879 [MM-41817] : Change global header z-index causing issue with profile menu if RHS if is open
  components/global_header/global_header.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none

#9876 Fixing possible (low priority) memory leaks
  components/global_header/center_controls/global_search_nav/global_search_nav.tsx
  components/global_header/left_controls/history_buttons/history_buttons.tsx
Labels: 4: Reviews Complete, release-note-none

#9894 Automated cherry pick of #9879
  components/global_header/global_header.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#9895 Chore/cherry pick translations
  i18n/bg.json
  i18n/de.json
  i18n/en_AU.json
  i18n/es.json
  i18n/fa.json
  i18n/fr.json
  i18n/hu.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none, kind/chore

#9896 Automated cherry pick of #9877
  components/plugin_marketplace/marketplace_modal.scss
  sass/components/_emoticons.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#9797 MM-40415 : Feature flags are not reloaded client-side when server restarts
  actions/websocket_actions.jsx
Labels: 4: Reviews Complete, release-note

#9888 MM-41538 Fix E2E test broken by changes to listeners
  e2e/cypress/integration/mark_as_unread/mark_as_unread_spec.js
Labels: 4: Reviews Complete, release-note-none

#9663 growth-spike: data-gathering and view controller
  components/admin_console/admin_console.tsx
  components/admin_console/admin_definition.jsx
  components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.jsx.snap
  components/admin_console/admin_sidebar/admin_sidebar.test.jsx
  components/admin_console/workspace-optimization/__snapshots__/chips_list.test.tsx.snap
  components/admin_console/workspace-optimization/__snapshots__/cta_buttons.test.tsx.snap
  components/admin_console/workspace-optimization/chips_list.test.tsx
  components/admin_console/workspace-optimization/chips_list.tsx
  components/admin_console/workspace-optimization/cta_buttons.test.tsx
  components/admin_console/workspace-optimization/cta_buttons.tsx
  components/admin_console/workspace-optimization/dashboard.data.tsx
  components/admin_console/workspace-optimization/dashboard.scss
  components/admin_console/workspace-optimization/dashboard.tsx
  components/admin_console/workspace-optimization/overall-score.tsx
  components/announcement_bar/contact_sales/contact_us.tsx
  components/announcement_bar/renewal_link/renewal_link.tsx
  components/common/accordion/__snapshots__/accordion.test.tsx.snap
  components/common/accordion/accordion.scss
  components/common/accordion/accordion.test.tsx
  components/common/accordion/accordion.tsx
  components/common/accordion/accordion_card.tsx
  components/common/accordion/message_item.tsx
  components/common/chip/chip.tsx
  components/common/circular_chart/__snapshots__/circular_chart.test.tsx.snap
  components/common/circular_chart/circular_chart.scss
  components/common/circular_chart/circular_chart.test.tsx
  components/common/circular_chart/circular_chart.tsx
  components/create_post/prewritten_chips.tsx
  components/trial_benefits_modal/trial_benefits_modal.tsx
  i18n/en.json
  package-lock.json
  package.json
  sass/admin_console_base/_sys_css_variables.scss
  sass/base/_css_variables.scss
  utils/constants.jsx
  utils/license_utils.jsx
Labels: 3: QA Review, Setup Cloud Test Server, release-note-none, telemetry

#9899 Automated cherry pick of #9663
  components/admin_console/admin_console.tsx
  components/admin_console/admin_definition.jsx
  components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.jsx.snap
  components/admin_console/admin_sidebar/admin_sidebar.test.jsx
  components/admin_console/workspace-optimization/__snapshots__/chips_list.test.tsx.snap
  components/admin_console/workspace-optimization/__snapshots__/cta_buttons.test.tsx.snap
  components/admin_console/workspace-optimization/chips_list.test.tsx
  components/admin_console/workspace-optimization/chips_list.tsx
  components/admin_console/workspace-optimization/cta_buttons.test.tsx
  components/admin_console/workspace-optimization/cta_buttons.tsx
  components/admin_console/workspace-optimization/dashboard.data.tsx
  components/admin_console/workspace-optimization/dashboard.scss
  components/admin_console/workspace-optimization/dashboard.tsx
  components/admin_console/workspace-optimization/overall-score.tsx
  components/announcement_bar/contact_sales/contact_us.tsx
  components/announcement_bar/renewal_link/renewal_link.tsx
  components/common/accordion/__snapshots__/accordion.test.tsx.snap
  components/common/accordion/accordion.scss
  components/common/accordion/accordion.test.tsx
  components/common/accordion/accordion.tsx
  components/common/accordion/accordion_card.tsx
  components/common/accordion/message_item.tsx
  components/common/chip/chip.tsx
  components/common/circular_chart/__snapshots__/circular_chart.test.tsx.snap
  components/common/circular_chart/circular_chart.scss
  components/common/circular_chart/circular_chart.test.tsx
  components/common/circular_chart/circular_chart.tsx
  components/create_post/prewritten_chips.tsx
  components/trial_benefits_modal/trial_benefits_modal.tsx
  i18n/en.json
  package-lock.json
  package.json
  sass/admin_console_base/_sys_css_variables.scss
  sass/base/_css_variables.scss
  utils/constants.jsx
  utils/license_utils.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#9897 only first admin sees preparing-workspace screen
  components/preparing_workspace/index.tsx
  components/preparing_workspace/preparing_workspace.tsx
  components/root/index.js
  components/root/root.jsx
  components/root/root.test.jsx
  components/root/root_redirect/index.ts
  components/root/root_redirect/root_redirect.tsx
  packages/mattermost-redux/src/selectors/entities/users.ts
Labels: 4: Reviews Complete, release-note-none

#9900 Automated cherry pick of #9897
  components/preparing_workspace/index.tsx
  components/preparing_workspace/preparing_workspace.tsx
  components/root/index.js
  components/root/root.jsx
  components/root/root.test.jsx
  components/root/root_redirect/index.ts
  components/root/root_redirect/root_redirect.tsx
  packages/mattermost-redux/src/selectors/entities/users.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#9898 Cypress/E2E:Added Known Issues
  e2e/cypress/integration/account_settings/profile/username_spec.js
  e2e/cypress/integration/enterprise/oauth/oauth_spec.js
  e2e/cypress/integration/enterprise/system_console/system_scheme_permission_spec.js
  e2e/cypress/integration/enterprise/system_console/team_scheme_permission_spec.js
  e2e/cypress/integration/integrations/custom_slash_commands/custom_slash_commands_spec.js
Labels: 4: Reviews Complete, release-note-none

#9903 MM-34367: Migrate "components/post_view/reaction/reaction.test.jsx" to typescript
  components/post_view/reaction/__snapshots__/reaction.test.tsx.snap
  components/post_view/reaction/reaction.test.tsx
Labels: 4: Reviews Complete, release-note-none, QA Deferred, Contributor

#9902 MM-34368: Migrate "components/post_view/reaction_list/reactions_list.test.jsx" to typescript
  components/post_view/reaction_list/__snapshots__/reactions_list.test.tsx.snap
  components/post_view/reaction_list/reactions_list.test.tsx
Labels: 2: Dev Review, release-note-none, QA Deferred, Contributor

#9893 Fixing a documentation problem in the registerProduct plugin api
  plugins/registry.js
Labels: 4: Reviews Complete, release-note-none

#9861 Typo in en.json
  components/admin_console/billing/billing_subscriptions/billing_subscriptions.tsx
  components/admin_console/billing/plan_details/__snapshots__/plan_details.test.tsx.snap
  components/admin_console/billing/plan_details/plan_details.tsx
  components/preparing_workspace/plugins.tsx
  i18n/en.json
Labels: 4: Reviews Complete, release-note-none, QA Deferred, Contributor

#9685 Keyboard up/down key issue in Channel switcher due to global thread list
  components/threading/global_threads/thread_list/thread_list.tsx
  e2e/cypress/integration/keyboard_shortcuts/ctrl_cmd_k_open_channel_from_global_threads_spec.js
Labels: 4: Reviews Complete, release-note

#9883 [MM-42068] Adding source query param to team and channel group endpoints
  packages/mattermost-redux/src/actions/groups.ts
  packages/mattermost-redux/src/client/client4.ts
  packages/mattermost-redux/src/selectors/entities/groups.test.js
  packages/mattermost-redux/src/selectors/entities/groups.ts
Labels: 3: QA Review, Setup Cloud Test Server, release-note

#9847 MM-41741: fixes leaving an unread channel
  e2e/cypress/integration/channel_sidebar/group_unreads_separately_spec.js
  packages/mattermost-redux/src/selectors/entities/channels.test.js
  packages/mattermost-redux/src/selectors/entities/channels.ts
  reducers/views/channel.test.js
  reducers/views/channel.ts
Labels: 4: Reviews Complete, release-note

#9873 [MM-41970] Should not have the ability to edit/archive ldap groups
  packages/mattermost-redux/src/selectors/entities/roles.test.js
  packages/mattermost-redux/src/selectors/entities/roles.ts
  packages/mattermost-redux/test/test_helper.js
Labels: 3: QA Review, Setup Cloud Test Server, release-note
