Repository mattermost/mattermost-webapp, pull requests merged in 2022-11, with the labels that each got.

#11492 [MM-47995] Undefined ChannelId Logs 400 Error on Page Load
  components/advanced_create_post/advanced_create_post.tsx
Labels: 2: Dev Review, CherryPick/Approved, release-note-none

#11495 Automated cherry pick of #11492
  components/advanced_create_post/advanced_create_post.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#11486 MM-45869-fix-ci: Better styled-components snapshot handling (opt-in per test for now)
  components/app_bar/__snapshots__/app_bar.test.tsx.snap
  components/app_bar/app_bar.test.tsx
  package-lock.json
  package.json
Labels: CherryPick/Approved, release-note-none

#11434 [MM-47622] minor upgrade of emoji-regex from 10.1.0 to 10.2.1
  package-lock.json
  package.json
Labels: 4: Reviews Complete, release-note-none

#11497 MM-45869-fix-ci: manual cherry pick for release-7.5
  components/app_bar/__snapshots__/app_bar.test.tsx.snap
  components/app_bar/app_bar.test.tsx
  package-lock.json
  package.json
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#11439 [MM-47890] Upgrade p-queue from 7.1.0 to 7.3.0
  package-lock.json
  package.json
Labels: 4: Reviews Complete, release-note-none

#11212 MM-44877: screen reader emoji announcement
  components/suggestion/suggestion_list.jsx
Labels: 4: Reviews Complete, release-note-none, Contributor

#11329 MM-47056: Migrate "components/setting_item_max.jsx" to Typescript
  components/__snapshots__/setting_item_max.test.jsx.snap
  components/channel_notifications_modal/components/__snapshots__/expand_view.test.tsx.snap
  components/channel_notifications_modal/components/expand_view.tsx
  components/setting_item_max.test.jsx
  components/setting_item_max.tsx
  components/team_general_tab/open_invite.tsx
  components/team_general_tab/team_general_tab.tsx
  components/user_settings/advanced/join_leave_section/join_leave_section.test.tsx
  components/user_settings/advanced/join_leave_section/join_leave_section.tsx
  components/user_settings/advanced/user_settings_advanced.tsx
  components/user_settings/display/manage_languages/manage_languages.tsx
  components/user_settings/display/manage_timezones/manage_timezones.tsx
  components/user_settings/display/user_settings_display.tsx
  components/user_settings/display/user_settings_theme/user_settings_theme.tsx
  components/user_settings/general/user_settings_general.tsx
  components/user_settings/notifications/desktop_notification_setting/__snapshots__/desktop_notification_settings.test.tsx.snap
  components/user_settings/notifications/desktop_notification_setting/desktop_notification_settings.tsx
  components/user_settings/notifications/email_notification_setting/__snapshots__/email_notification_setting.test.tsx.snap
  components/user_settings/notifications/email_notification_setting/email_notification_setting.tsx
  components/user_settings/notifications/manage_auto_responder/__snapshots__/manage_auto_responder.test.tsx.snap
  components/user_settings/notifications/manage_auto_responder/manage_auto_responder.tsx
  components/user_settings/notifications/user_settings_notifications.tsx
  components/user_settings/security/user_access_token_section/user_access_token_section.tsx
  components/user_settings/security/user_settings_security.tsx
  components/user_settings/sidebar/limit_visible_gms_dms/limit_visible_gms_dms.tsx
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted, release-note-none, Contributor

#11503 e2e/cypress:test cases promoted
  e2e/cypress/tests/integration/account_settings/profile/fullname_edit_spec.ts
  e2e/cypress/tests/integration/integrations/custom_slash_commands/slash_commands_spec.js
  e2e/cypress/tests/integration/integrations/incoming_webhook/attachment_does_not_collapse_spec.ts
  e2e/cypress/tests/integration/messaging/mention_autocomplete_overlap_spec.js
  e2e/cypress/tests/integration/profile_settings/profile_settings_spec.js
Labels: release-note-none

#11464 e2e/cypress:fixed
  e2e/cypress/tests/integration/account_settings/profile/email_spec.ts
  e2e/cypress/tests/integration/channel/channel_info_rhs_spec.js
  e2e/cypress/tests/integration/channel/channel_members_rhs_spec.js
  e2e/cypress/tests/integration/channel_settings/add_users_to_channel_spec.js
  e2e/cypress/tests/integration/files_and_attachments/upload_files_spec.js
Labels: release-note-none

#11509 Automated cherry pick of #11212
  components/suggestion/suggestion_list.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#11417 [MM-47114] Migrate components/setting_picture.jsx to Typescript
  components/__snapshots__/setting_picture.test.tsx.snap
  components/setting_picture.test.tsx
  components/setting_picture.tsx
  components/team_general_tab/team_general_tab.tsx
  components/user_settings/general/user_settings_general.tsx
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted, release-note-none, Contributor

#11500 MM-30079 - Hide or Enable System Console Settings
  components/admin_console/admin_definition.jsx
Labels: 2: Dev Review, QA Review Done, Setup Cloud + CWS Test Server, release-note-none

#11499 MM-47793 Let products be developed using https
  webpack.config.js
Labels: 4: Reviews Complete, release-note-none

#11504 MM-47042_Remove default text for "Custom Brand Text" in login-signup
  components/login/login.tsx
  components/signup/signup.tsx
Labels: 1: PM Review, 2: Dev Review, Setup Cloud Test Server, QA Review Done, release-note-none

#11488 MM-46853 Automatically run Boards product from web app
  scripts/run.js
  webpack.config.js
Labels: 4: Reviews Complete, release-note-none

#11444 [MM-35703]: Maintain scroll position in channel when opening reply message permalinks(Fix reverted PR)
  components/permalink_view/actions.ts
  components/permalink_view/permalink_view.test.tsx
  components/post_view/post_attachment_container/__snapshots__/post_attachment_container.test.tsx.snap
  components/post_view/post_attachment_container/post_attachment_container.test.tsx
  components/post_view/post_attachment_container/post_attachment_container.tsx
  packages/mattermost-redux/src/selectors/entities/teams.ts
  utils/utils.tsx
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted, release-note, Contributor

#11483 [MM-48045] Upgrade redux-thunk to 2.4.1
  package-lock.json
  package.json
Labels: 4: Reviews Complete, release-note-none

#11455 MM-47959, MM-47960 - fix text in dark theme; show cursor as hand in text
  components/new_channel_modal/new_channel_modal.scss
Labels: CherryPick/Approved, release-note-none

#11472 MM-48016 - show tip shown after channel + board with classic style; small code improvements
  components/app_bar/app_bar.scss
  components/app_bar/new_channel_with_board_tour_tip.scss
  components/app_bar/new_channel_with_board_tour_tip.tsx
  e2e/cypress/tests/integration/channel/new_channel_with_board_spec.js
  e2e/cypress/tests/support/ui/channel.js
  packages/components/src/tour_tip/tour_tip.scss
  packages/components/src/tour_tip/tour_tip.tsx
Labels: CherryPick/Approved, Setup Cloud Test Server, 1: UX Review, release-note-none

#11518 Automated cherry pick of #11455
  components/new_channel_modal/new_channel_modal.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#11520 Automated cherry pick of #11472
  components/app_bar/app_bar.scss
  components/app_bar/new_channel_with_board_tour_tip.scss
  components/app_bar/new_channel_with_board_tour_tip.tsx
  e2e/cypress/tests/integration/channel/new_channel_with_board_spec.js
  e2e/cypress/tests/support/ui/channel.js
  packages/components/src/tour_tip/tour_tip.scss
  packages/components/src/tour_tip/tour_tip.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#11489 Add custom runner for web app, packages, and products
  package-lock.json
  package.json
  scripts/run.js
  scripts/runner.js
Labels: 4: Reviews Complete, release-note-none

#11517 Fixing icu errors in translations
  i18n/es.json
  i18n/fa.json
  i18n/hr.json
  i18n/it.json
  i18n/ko.json
  i18n/ro.json
Labels: 4: Reviews Complete, release-note-none, Contributor

#11145 [MM-44873] Screen reader not announcing the current state of user
  components/status_dropdown/__snapshots__/status_dropdown.test.tsx.snap
  components/status_dropdown/status_dropdown.test.tsx
  components/status_dropdown/status_dropdown.tsx
  e2e/cypress/tests/support/ui/global_header.js
  i18n/en.json
Labels: 4: Reviews Complete, release-note, 2. Editor review, Contributor

#11490 [MM-47184] Updating statistics string to total activated users
  components/analytics/system_analytics/system_analytics.tsx
  components/analytics/team_analytics/team_analytics.tsx
  e2e/cypress/tests/integration/enterprise/system_console/reporting/site_statistics_spec.js
  e2e/cypress/tests/integration/system_console/reporting/site_statistics_te_spec.js
  e2e/cypress/tests/integration/system_console/reporting/team_statistics_spec.js
  i18n/en.json
  i18n/en_AU.json
Labels: 3: QA Review, Setup Cloud Test Server, release-note-none

#11479 Fix apiadminlogin ts spec
  e2e/cypress/tests/integration/auth_sso/authentication_3_spec.ts
  e2e/cypress/tests/integration/enterprise/guest_accounts/guest_identification_spec.ts
  e2e/cypress/tests/support/api/user.d.ts
Labels: release-note-none

#11501 [MM-48077] - Notify admin is received for @unknown user
  components/at_sum_members_mention/notification_from_members_modal.tsx
  components/custom_open_pricing_modal_post_renderer/index.tsx
Labels: 4: Reviews Complete, CherryPick/Candidate, Setup Cloud Test Server, QA Review Done, release-note-none

#11505 MM-45313_Cannot access the create account button on safari for iOS
  components/header_footer_route/header_footer_route.scss
Labels: 2: Dev Review, Setup Cloud Test Server, QA Review Done, release-note-none

#11510 [MM-48046] upgrade react-popper
  package-lock.json
  package.json
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none

#11508 [MM-48047] Upgrade react-transition-group
  package-lock.json
  package.json
Labels: 4: Reviews Complete, release-note-none, QA Deferred

#11474 [MM-47222] add info for enduser with no account and when on closed server
  components/access_problem/access_problem.scss
  components/access_problem/index.tsx
  components/common/svg_images_components/access_problem_svg.tsx
  components/header_footer_route/content_layouts/alternate_link.tsx
  components/login/__snapshots__/login.test.tsx.snap
  components/login/login.test.tsx
  components/login/login.tsx
  components/root/root.tsx
  e2e/cypress/tests/integration/signin_authentication/login_close_server_spec.js
  e2e/cypress/tests/integration/signin_authentication/login_open_server_spec.js
  e2e/cypress/tests/utils/constants.js
  i18n/en.json
Labels: Setup Cloud Test Server, release-note-none, QA Deferred

#11525 Automated cherry pick of #11501
  components/at_sum_members_mention/notification_from_members_modal.tsx
  components/custom_open_pricing_modal_post_renderer/index.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#11537 [MM-47222] lint fix
  components/common/svg_images_components/access_problem_svg.tsx
Labels: 2: Dev Review, release-note-none

#11487 [MM-48049] Including users who were removed from group in not_in_group response
  packages/mattermost-redux/src/reducers/entities/users.test.js
  packages/mattermost-redux/src/reducers/entities/users.ts
Labels: 4: Reviews Complete, CherryPick/Approved, AutoMerge, release-note-none

#11542 Automated cherry pick of #11487
  packages/mattermost-redux/src/reducers/entities/users.test.js
  packages/mattermost-redux/src/reducers/entities/users.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#11460 [MM-41906] Add max height and overflow to Multiselect
  sass/components/_channel-invite-modal.scss
Labels: 3: QA Review, Setup Cloud Test Server, release-note-none

#11541 Automated cherry pick of #11487
  packages/mattermost-redux/src/reducers/entities/users.test.js
  packages/mattermost-redux/src/reducers/entities/users.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#11544 Fix `make node_modules` when running in production mode
  Makefile
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#11546 Automated cherry pick of #11544
  Makefile
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#11545 Automated cherry pick of #11544
  Makefile
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#11238 MM-T1539: E2E test to verify :man-gesturing-ok: is rendered with the correct gender
  e2e/cypress/tests/integration/messaging/emoji_gender_spec.ts
Labels: Hacktoberfest, Lifecycle/1:stale, hacktoberfest-accepted, release-note-none, Contributor

#11511 Update member_invitation_ui_spec.ts
  e2e/cypress/tests/integration/enterprise/guest_accounts/member_invitation_ui_spec.ts
Labels: 4: Reviews Complete, release-note-none

#11392 MM-47290 : Migrate "/channel_sidebar" e2e tests to TypeScript
  e2e/cypress/tests/integration/channel_sidebar/category.d.ts
  e2e/cypress/tests/integration/channel_sidebar/category_collapsing_spec.ts
  e2e/cypress/tests/integration/channel_sidebar/category_muting_spec.ts
  e2e/cypress/tests/integration/channel_sidebar/category_sorting_1_spec.ts
  e2e/cypress/tests/integration/channel_sidebar/category_sorting_spec.ts
  e2e/cypress/tests/integration/channel_sidebar/channel_sidebar_spec.ts
  e2e/cypress/tests/integration/channel_sidebar/custom_categories_spec.ts
  e2e/cypress/tests/integration/channel_sidebar/dm_category_spec.ts
  e2e/cypress/tests/integration/channel_sidebar/dm_gm_behaviour_spec.ts
  e2e/cypress/tests/integration/channel_sidebar/dm_gm_filtering_sorting_spec.ts
  e2e/cypress/tests/integration/channel_sidebar/dm_sidebar_not_remove_spec.ts
  e2e/cypress/tests/integration/channel_sidebar/drag_and_drop_spec.ts
  e2e/cypress/tests/integration/channel_sidebar/group_unreads_separately_spec.ts
  e2e/cypress/tests/integration/channel_sidebar/helpers.ts
  e2e/cypress/tests/integration/channel_sidebar/history_channel_switcher_spec.ts
  e2e/cypress/tests/integration/channel_sidebar/hotkeys_spec.ts
  e2e/cypress/tests/integration/channel_sidebar/new_category_badge_spec.ts
  e2e/cypress/tests/integration/channel_sidebar/new_channel_dropdown_spec.ts
  e2e/cypress/tests/integration/channel_sidebar/sidebar_category_menu_spec.ts
  e2e/cypress/tests/integration/channel_sidebar/sidebar_channel_menu_spec.ts
  e2e/cypress/tests/integration/channel_sidebar/unread_filter_spec.ts
  e2e/cypress/tests/support/api/bots.d.ts
  e2e/cypress/tests/support/api/channel.d.ts
  e2e/cypress/tests/support/api/user.d.ts
  e2e/cypress/tests/support/ui_commands.ts
Labels: 4: Reviews Complete, Hacktoberfest, AutoMerge, hacktoberfest-accepted, release-note-none, Contributor

#11445 [MM-47888] Upgrade luxon to 3.0.4
  package-lock.json
  package.json
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none, QA Deferred

#11522 e2e/cypress:demoted test cases
  e2e/cypress/tests/integration/accessibility/accessibility_dropdowns_spec.js
  e2e/cypress/tests/integration/channel/new_channel_with_board_spec.js
  e2e/cypress/tests/integration/collapsed_reply_threads/global_threads_spec.js
  e2e/cypress/tests/integration/enterprise/extend_session/not_extended_when_disabled/with_email_login_spec.js
  e2e/cypress/tests/integration/enterprise/extend_session/not_extended_when_disabled/with_ldap_login_spec.js
  e2e/cypress/tests/integration/enterprise/guest_accounts/member_invitation_ui_spec.ts
  e2e/cypress/tests/integration/enterprise/system_console/about/starter_edition_spec.js
  e2e/cypress/tests/integration/integrations/incoming_webhook/integrations_display_on_team_where_created_spec.js
  e2e/cypress/tests/integration/integrations/incoming_webhook/slack_formatting_spec.js
  e2e/cypress/tests/integration/integrations/outgoing_webhook/disable_override_username_profile_spec.js
  e2e/cypress/tests/integration/integrations/poll_spec.js
  e2e/cypress/tests/integration/mark_as_unread/mark_dm_post_as_unread_spec.js
  e2e/cypress/tests/integration/message_forwarding/forward_message_from_public_channel_spec.js
  e2e/cypress/tests/integration/messaging/message_reply_input_box_expand_spec.js
  e2e/cypress/tests/integration/plugins/plugin_install_spec.js
  e2e/cypress/tests/integration/search_filter/edit_spec.js
  e2e/cypress/tests/support/ui/sidebar_right.js
Labels: 4: Reviews Complete, release-note-none

#11519 [MM-48104] upgrade core-js
  package-lock.json
  package.json
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none, QA Deferred

#11436 MM-47361 : Remove global state & dispatch from logged_in.tsx
  components/logged_in/index.ts
  components/logged_in/logged_in.test.tsx
  components/logged_in/logged_in.tsx
Labels: Hacktoberfest, 3: QA Review, Lifecycle/1:stale, hacktoberfest-accepted, release-note-none, QA Deferred, Contributor

#11547 cherry-picking translations from master
  i18n/bg.json
  i18n/de.json
  i18n/en_AU.json
  i18n/es.json
  i18n/fa.json
  i18n/fr.json
  i18n/hu.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none, Contributor

#11548 Cherry-picking translations
  i18n/bg.json
  i18n/de.json
  i18n/en_AU.json
  i18n/es.json
  i18n/fa.json
  i18n/fr.json
  i18n/hr.json
  i18n/hu.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none, Contributor

#11549 MM-47715 : Update "package/readme" to reflect new jest config file
  packages/README.md
Labels: 4: Reviews Complete, release-note-none

#11494 MM 47620 - upgrade Typescript to 4.7.4
  .eslintrc.json
  components/admin_console/admin_definition.jsx
  components/admin_console/billing/company_info.tsx
  components/admin_console/billing/company_info_edit.tsx
  components/admin_console/billing/payment_info.tsx
  components/admin_console/blockable_link/blockable_link.tsx
  components/admin_console/cluster_settings.jsx
  components/admin_console/database_settings.jsx
  components/admin_console/message_export_settings.jsx
  components/admin_console/push_settings.jsx
  components/announcement_bar/default_announcement_bar/announcement_bar.tsx
  components/app.jsx
  components/app_bar/app_bar.tsx
  components/audit_table/user_row/user_update_active_session_row.tsx
  components/card/card.tsx
  components/custom_open_pricing_modal_post_renderer/index.tsx
  components/emoji_picker/components/emoji_picker_skin.tsx
  components/file_limit_sticky_banner/index.tsx
  components/file_upload/file_upload.tsx
  components/generic_modal.test.tsx
  components/link_tooltip/link_tooltip.tsx
  components/multiselect/multiselect.tsx
  components/notify_admin_cta/notify_admin_cta.tsx
  components/onboarding_tasks/onboarding_video_modal/onboarding_video_modal.tsx
  components/payment_form/card_input.tsx
  components/payment_form/state_selector.tsx
  components/pricing_modal/contact_sales_cta.tsx
  components/pricing_modal/self_hosted_content.tsx
  components/pricing_modal/starter_disclaimer_cta.tsx
  components/rhs_card/rhs_card.tsx
  components/sidebar/channel_filter/channel_filter.tsx
  components/sidebar/sidebar_channel/sidebar_group_channel/sidebar_group_channel.tsx
  components/sidebar/sidebar_channel_list/sidebar_channel_list.tsx
  components/sidebar/sidebar_header/sidebar_header.tsx
  components/suggestion/rhs_suggestion_list.tsx
  components/team_sidebar/team_sidebar.tsx
  e2e/cypress/tests/integration/autocomplete/helpers.ts
  e2e/cypress/tests/support/task_commands.ts
  package-lock.json
  package.json
  packages/components/src/generic_modal/generic_modal.tsx
  tsconfig.json
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none, QA Deferred

#11408 MM-46904: Channel members is able to remove themselves from channel from the RHS members list
  actions/command.ts
  components/activity_and_insights/insights/least_active_channels/channel_actions_menu/channel_actions_menu.tsx
  components/channel_header_dropdown/menu_items/leave_channel/leave_channel.tsx
  components/channel_members_dropdown/__snapshots__/channel_members_dropdown.test.tsx.snap
  components/channel_members_dropdown/channel_members_dropdown.test.tsx
  components/channel_members_dropdown/channel_members_dropdown.tsx
  components/channel_members_dropdown/index.ts
  components/leave_channel_modal/__snapshots__/leave_channel_modal.test.tsx.snap
  components/leave_channel_modal/index.ts
  components/leave_channel_modal/leave_channel_modal.test.tsx
  components/leave_channel_modal/leave_channel_modal.tsx
  components/leave_private_channel_modal/leave_private_channel_modal.tsx
  components/sidebar/sidebar_channel/sidebar_base_channel/sidebar_base_channel.tsx
  i18n/en.json
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted, release-note, Contributor

#10755 MM-45556 Ability to mark a channel as unread
  components/sidebar/sidebar_channel/sidebar_channel_link/index.ts
  components/sidebar/sidebar_channel/sidebar_channel_link/sidebar_channel_link.test.tsx
  components/sidebar/sidebar_channel/sidebar_channel_link/sidebar_channel_link.tsx
  components/sidebar/sidebar_channel/sidebar_channel_menu/__snapshots__/sidebar_channel_menu.test.tsx.snap
  components/sidebar/sidebar_channel/sidebar_channel_menu/index.ts
  components/sidebar/sidebar_channel/sidebar_channel_menu/sidebar_channel_menu.test.tsx
  components/sidebar/sidebar_channel/sidebar_channel_menu/sidebar_channel_menu.tsx
  e2e/cypress/tests/integration/mark_as_unread/mark_as_unread_spec.js
  i18n/en.json
  package-lock.json
  packages/mattermost-redux/src/actions/channels.ts
Labels: 4: Reviews Complete, release-note, Contributor

#11292 [MM-40610] add 5px right border to allow scrollbars
  components/search_results/search_results.tsx
  components/threading/global_threads/thread_list/thread_list.scss
  components/threading/thread_viewer/thread_viewer.scss
  sass/components/_post-right.scss
  sass/components/_post.scss
  sass/components/_scrollbar.scss
  sass/routes/_admin-console.scss
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted, release-note, Contributor

#11394 MM-44859 : Screen reader invite members search results announcement
  components/widgets/inputs/users_emails_input.tsx
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted, release-note-none, Contributor

#11108 [MM-42029] Migrate CRT tour to use tour tip
  components/advanced_create_post/index.ts
  components/advanced_text_editor/advanced_text_editor.tsx
  components/crt_tour/crt_list_tutorial_tip/crt_list_tutorial_tip.tsx
  components/crt_tour/crt_unread_tutorial_tip/crt_unread_tutorial_tip.tsx
  components/crt_tour/crt_welcome_tutorial_tip/crt_welcome_tutorial_tip.tsx
  components/global_header/left_controls/product_menu/product_menu.tsx
  components/global_header/left_controls/product_menu/product_menu_item/product_menu_item.tsx
  components/global_header/right_controls/right_controls.tsx
  components/onboarding_explore_tools_tour/explore_tools_tour_tip.scss
  components/onboarding_explore_tools_tour/onboarding_explore_tools_tour_tip.tsx
  components/onboarding_tasks/onboarding_tasks_manager.tsx
  components/rhs_header_post/rhs_header_post.tsx
  components/sidebar/add_channel_dropdown.tsx
  components/sidebar/sidebar_channel/sidebar_channel_link/index.ts
  components/sidebar/sidebar_channel/sidebar_channel_link/sidebar_channel_link.tsx
  components/sidebar/sidebar_header/sidebar_header.tsx
  components/threading/global_threads/thread_item/thread_item.tsx
  components/threading/global_threads/thread_list/thread_list.tsx
  components/threading/global_threads_link/global_threads_link.tsx
  components/tours/channels_tour_tip.tsx
  components/tours/constant.ts
  components/tours/crt_tour/collapsed_reply_threads_modal/collapsed_reply_threads_modal.scss
  components/tours/crt_tour/collapsed_reply_threads_modal/collapsed_reply_threads_modal.tsx
  components/tours/crt_tour/collapsed_reply_threads_modal/index.ts
  components/tours/crt_tour/crt_list_tutorial_tip.tsx
  components/tours/crt_tour/crt_threads_pane_tutorial_tip.tsx
  components/tours/crt_tour/crt_tour_tip.tsx
  components/tours/crt_tour/crt_unread_tutorial_tip.tsx
  components/tours/crt_tour/crt_welcome_tutorial_tip.tsx
  components/tours/hooks.ts
  components/tours/index.ts
  components/tours/onboarding_explore_tools_tour/boards_tour_tip.tsx
  components/tours/onboarding_explore_tools_tour/explore_tools_tour_manager.tsx
  components/tours/onboarding_explore_tools_tour/index.ts
  components/tours/onboarding_explore_tools_tour/onboarding_explore_tools_tour_tip.tsx
  components/tours/onboarding_explore_tools_tour/playbooks_tour_tip.tsx
  components/tours/onboarding_tour/channels_and_direct_messages_tour_tip.tsx
  components/tours/onboarding_tour/create_and_join_channels_tour_tip.tsx
  components/tours/onboarding_tour/customize_your_experience_tour_tip.tsx
  components/tours/onboarding_tour/hooks.ts
  components/tours/onboarding_tour/index.ts
  components/tours/onboarding_tour/invite_people_tour_tip.tsx
  components/tours/onboarding_tour/onboarding_tour_tip.tsx
  components/tours/onboarding_tour/send_message_tour_tip.tsx
  components/tours/tour_manager.tsx
  components/tours/utils.ts
  components/tutorial/tutorial_tip_legacy/__snapshots__/tutorial_tip.test.tsx.snap
  components/tutorial/tutorial_tip_legacy/hooks.ts
  components/tutorial/tutorial_tip_legacy/index.ts
  components/tutorial/tutorial_tip_legacy/tutorial_tip.test.tsx
  components/tutorial/tutorial_tip_legacy/tutorial_tip.tsx
  components/tutorial/tutorial_tip_legacy/tutorial_tip_backdrop.tsx
  e2e/cypress/tests/integration/collapsed_reply_threads/crt_tour_spec.js
  i18n/en.json
  package-lock.json
  packages/components/src/tour_tip/tour_tip.scss
Labels: 2: Dev Review, QA Review Done, release-note

#11562 [MM-48044] bulk dependency upgrades patch version changes
  package-lock.json
  package.json
Labels: 2: Dev Review, release-note-none, QA Deferred

#11516 MM-45471 - Reveal "File Sharing and Download" System Console settings in Cloud.
  components/admin_console/admin_definition.jsx
Labels: QA Review Done, release-note-none

#11565 Remove Eslint Disable Lines
  components/payment_form/gather_intent/gather_intent.test.tsx
  components/payment_form/gather_intent/gather_intent_modal.test.tsx
  components/payment_form/gather_intent/gather_intent_modal.tsx
  components/payment_form/gather_intent/gather_intent_submitted_modal.tsx
Labels: 2: Dev Review, release-note-none

#11560 e2e/cypress:fixed authenticaton test cases
  e2e/cypress/tests/integration/accessibility/accessibility_dropdowns_spec.js
  e2e/cypress/tests/integration/auth_sso/authentication_1_spec.ts
  e2e/cypress/tests/integration/auth_sso/authentication_4_spec.ts
  e2e/cypress/tests/integration/auth_sso/hide_create_account_spec.ts
  e2e/cypress/tests/integration/channel_sidebar/dm_gm_behaviour_spec.ts
  e2e/cypress/tests/integration/channel_sidebar/hotkeys_spec.ts
  e2e/cypress/tests/integration/channel_sidebar/sidebar_channel_menu_spec.ts
  e2e/cypress/tests/integration/collapsed_reply_threads/following_spec.js
  e2e/cypress/tests/integration/enterprise/auth_sso/authentication_spec.js
  e2e/cypress/tests/integration/enterprise/guest_accounts/guest_identification_spec.ts
  e2e/cypress/tests/integration/keyboard_shortcuts/ctrl_cmd_k_open_channel_from_global_threads_spec.js
  e2e/cypress/tests/integration/onboarding/existing_email_adress_spec.js
  e2e/cypress/tests/integration/onboarding/login_page_link_account_creation_spec.js
  e2e/cypress/tests/integration/system_console/site_configuration/link_customization_cloud_spec.js
  e2e/cypress/tests/integration/system_console/site_configuration/link_customization_e20_1_spec.js
  e2e/cypress/tests/integration/system_console/site_configuration/link_customization_e20_2_spec.js
  e2e/cypress/tests/support/ui/global_header.js
Labels: release-note-none

#11528 MM-47079: Migrate "components/suggestion/search_user_provider.jsx" to Typescript
  components/search/types.ts
  components/suggestion/search_user_provider.tsx
Labels: 2: Dev Review, release-note-none, QA Deferred, Contributor

#11551 MM-47865 - remove deprecated guided channel creation ff
  e2e/playwright/support/server/default_config.ts
Labels: release-note-none

#11568 Downgrade languages to Alpha
  components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
  i18n/i18n.jsx
Labels: 4: Reviews Complete, Changelog/Done, Docs/Not Needed, AutoMerge, release-note

#11569 Automated cherry pick of #11568
  components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
  i18n/i18n.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#11303 MM-22249 : Add automatic lazy loading of syntax highlighting libraries
  components/code_block/__snapshots__/code_block.test.tsx.snap
  components/code_block/code_block.test.tsx
  components/code_block/code_block.tsx
  components/code_preview.tsx
  utils/syntax_highlighting.test.ts
  utils/syntax_highlighting.tsx
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted, release-note-none, Contributor

#11563 [MM-48043] upgrade webpack and related dependencies
  package-lock.json
  package.json
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none, QA Deferred

#11552 MM-47866 - remove deprecated inviteToTeam FF
  e2e/playwright/support/server/default_config.ts
Labels: release-note-none

#11344 MM-44048: Fix Suggestion.Undefined
  components/suggestion/command_provider/app_command_parser/app_command_parser.test.ts
  components/suggestion/command_provider/app_command_parser/app_command_parser.ts
  components/suggestion/command_provider/app_command_parser/app_command_parser_dependencies.ts
  components/suggestion/command_provider/app_provider.tsx
  components/suggestion/command_provider/command_provider.test.tsx
  components/suggestion/command_provider/command_provider.tsx
  components/suggestion/emoticon_provider.jsx
  components/suggestion/suggestion_list.jsx
  i18n/en.json
  packages/types/src/integrations.ts
  utils/constants.tsx
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted, release-note, Contributor

#11567 [MM-48202] Upgrade memoize-one to v6.0.0
  package-lock.json
  package.json
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none, QA Deferred

#11581 Remove the play/check icon in onboarding task list
  components/onboarding_tasklist/onboarding_tasklist_task.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none

#11527 MM-47782 Stop storing compact mode profile colours in localStorage
  components/user_profile/user_profile.tsx
  components/user_profile/utils.ts
Labels: 4: Reviews Complete, release-note

#11573 e2e/Cypress:fixed spec files
  e2e/cypress/tests/integration/channel/channel_info_rhs_spec.js
  e2e/cypress/tests/integration/channel/channel_members_rhs_spec.js
  e2e/cypress/tests/integration/enterprise/guest_accounts/guest_popover_ui_spec.ts
  e2e/cypress/tests/integration/files_and_attachments/image_link_preview_spec.js
  e2e/cypress/tests/integration/integrations/outgoing_webhook/disable_outgoing_webhook_spec.js
  e2e/cypress/tests/integration/mark_as_unread/mark_as_unread_spec.js
  e2e/cypress/tests/integration/messaging/image_attachment_spec.js
  e2e/cypress/tests/integration/messaging/send_message_via_profile_popover_spec.js
  e2e/cypress/tests/integration/system_console/session_length_spec.js
  e2e/cypress/tests/integration/toast/unread_with_bottom_start_toast_spec.js
Labels: release-note-none

#11526 [MM-47931] a/b test for reduced onboarding task list item
  components/onboarding_tasks/onboarding_tasks_manager.test.tsx
  components/onboarding_tasks/onboarding_tasks_manager.tsx
  packages/mattermost-redux/src/selectors/entities/preferences.ts
  packages/types/src/config.ts
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, CherryPick/Approved, Setup Cloud Test Server, QA Review Done, AutoMerge, release-note-none

#11584 Automated cherry pick of #11526
  components/onboarding_tasks/onboarding_tasks_manager.test.tsx
  components/onboarding_tasks/onboarding_tasks_manager.tsx
  packages/mattermost-redux/src/selectors/entities/preferences.ts
  packages/types/src/config.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#11561 MM-48195 - onboarding messaging item not working on guest users
  actions/views/onboarding_tasks.ts
  components/advanced_create_post/index.ts
  components/global_header/right_controls/right_controls.tsx
  components/onboarding_tasks/onboarding_tasks_manager.tsx
  components/tours/constant.ts
  components/tours/hooks.ts
  packages/components/src/tour_tip/tour_tip.tsx
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, CherryPick/Approved, QA Review Done, AutoMerge, Setup Cloud + CWS Test Server, release-note-none

#11585 Automated cherry pick of #11561
  actions/views/onboarding_tasks.ts
  components/advanced_create_post/index.ts
  components/global_header/right_controls/right_controls.tsx
  components/onboarding_tasks/onboarding_tasks_manager.tsx
  components/tours/constant.ts
  components/tours/hooks.ts
  packages/components/src/tour_tip/tour_tip.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#11457 [MM-46112] Allowing special characters in group name
  components/at_mention/at_mention.tsx
  components/create_user_groups_modal/create_user_groups_modal.test.tsx
  components/create_user_groups_modal/create_user_groups_modal.tsx
  components/update_user_group_modal/update_user_group_modal.tsx
  utils/post_utils.ts
Labels: 2: Dev Review, 3: QA Review, Setup Cloud Test Server, release-note

#11502 [MM-39693] Include channel switcher modal header in accessibility
  components/quick_switch_modal/__snapshots__/quick_switch_modal.test.tsx.snap
  components/quick_switch_modal/quick_switch_modal.tsx
Labels: 3: QA Review, Setup Cloud Test Server, release-note-none

#11577 [MM-48204] Upgrade sass and sass-loader
  entry.tsx
  package-lock.json
  package.json
  sass/base/_structure.scss
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none, QA Deferred

#11571 [MM-48317] Fix: Upgrade to enterprise when settling delinquency from Professional
  components/purchase_modal/index.ts
  components/purchase_modal/purchase_modal.tsx
Labels: 2: Dev Review, CherryPick/Approved, release-note-none, QA Deferred

#11591 Automated cherry pick of #11571
  components/purchase_modal/index.ts
  components/purchase_modal/purchase_modal.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#11514 Mm 30941 system roles shows license and environment should be hidden in cloud
  components/admin_console/system_roles/system_role/__snapshots__/system_role_permissions.test.tsx.snap
  components/admin_console/system_roles/system_role/system_role_permissions.test.tsx
  components/admin_console/system_roles/system_role/system_role_permissions.tsx
Labels: Setup Cloud Test Server, QA Review Done, release-note-none

#11523 [MM-48027] improve use case window style
  components/common/accordion/accordion.tsx
  components/worktemplates/components/menu/use_case.tsx
Labels: Docs/Not Needed, Setup Cloud Test Server, QA Review Done, 1: UX Review, release-note-none

#11557 [MM-48020] work template preview page fade illustration animation
  components/worktemplates/components/modal_body_with_illustration.tsx
  components/worktemplates/components/preview.tsx
Labels: 2: Dev Review, Docs/Not Needed, Setup Cloud Test Server, QA Review Done, 1: UX Review, release-note-none

#11554 Cypress/E2E: fix upload of screenshots
  e2e/cypress/run_test_cycle.js
  e2e/cypress/utils/dashboard.js
Labels: 4: Reviews Complete, release-note-none

#11468 Enabled type checks for Playwright and updated config types at packages/types/src/config.ts
  .circleci/config.yml
  .gitlab-ci.yml
  Makefile
  build/contrib/gitlab/.gitlab-ci.yml
  e2e/cypress/tests/support/api/on_prem_default_config.json
  e2e/playwright/.eslintrc.json
  e2e/playwright/.percy.yml
  e2e/playwright/README.md
  e2e/playwright/global_setup.ts
  e2e/playwright/package-lock.json
  e2e/playwright/package.json
  e2e/playwright/playwright.config.ts
  e2e/playwright/support/server/channel.ts
  e2e/playwright/support/server/client.ts
  e2e/playwright/support/server/default_config.ts
  e2e/playwright/support/server/index.ts
  e2e/playwright/support/server/init.ts
  e2e/playwright/support/server/team.ts
  e2e/playwright/support/server/user.ts
  e2e/playwright/support/ui/page/channel.ts
  e2e/playwright/support/ui/page/login.ts
  e2e/playwright/support/ui/page/signup.ts
  e2e/playwright/support/utils/index.ts
  e2e/playwright/support/visual/applitools.ts
  e2e/playwright/support/visual/index.ts
  e2e/playwright/support/visual/percy.ts
  e2e/playwright/test.config.ts
  e2e/playwright/tests/visual/intro_channel.spec.ts
  e2e/playwright/tests/visual/landing_page.spec.ts
  e2e/playwright/tests/visual/login.spec.ts
  e2e/playwright/tests/visual/signup_email.spec.ts
  e2e/playwright/tsconfig.json
  packages/client/src/client4.ts
  packages/types/src/config.ts
  tsconfig.json
Labels: 2: Dev Review, 3: QA Review, release-note-none

#11470 [MM-47362] Remove redux from stores/browser_store
  components/analytics/team_analytics/index.ts
  components/analytics/team_analytics/team_analytics.tsx
  components/delinquency_modal/useDelinquencyModalController.tsx
  stores/browser_store.tsx
Labels: Hacktoberfest, 3: QA Review, hacktoberfest-accepted, release-note-none, Contributor

#11550 MM-48191 : "user_id" being empty in loadMeRest is effecting telemetry
  packages/mattermost-redux/src/actions/roles.ts
  packages/mattermost-redux/src/actions/users.test.js
  packages/mattermost-redux/src/actions/users.ts
  packages/mattermost-redux/src/actions/users_queries.ts
Labels: 4: Reviews Complete, CherryPick/Approved, AutoMerge, release-note-none

#11603 Automated cherry pick of #11550
  packages/mattermost-redux/src/actions/roles.ts
  packages/mattermost-redux/src/actions/users.test.js
  packages/mattermost-redux/src/actions/users.ts
  packages/mattermost-redux/src/actions/users_queries.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#11595 Fix docs link to advanced permissions
  components/admin_console/permission_schemes_settings/permission_team_scheme_settings/permission_team_scheme_settings.tsx
Labels: 4: Reviews Complete, release-note-none

#11524 MM-46959 Update prepare-docker-build job to not delete product files
  .circleci/config.yml
Labels: 4: Reviews Complete, release-note-none

#11594 MM-48401 : Convert "sidebar_category_menu" to functional components and replace with compass icons
  components/sidebar/sidebar_category/__snapshots__/sidebar_category.test.tsx.snap
  components/sidebar/sidebar_category/sidebar_category_menu/__snapshots__/sidebar_category_menu.test.tsx.snap
  components/sidebar/sidebar_category/sidebar_category_menu/index.ts
  components/sidebar/sidebar_category/sidebar_category_menu/sidebar_category_menu.test.tsx
  components/sidebar/sidebar_category/sidebar_category_menu/sidebar_category_menu.tsx
  sass/layout/_sidebar-left.scss
Labels: 4: Reviews Complete, 3: QA Review, release-note-none

#11593 MM-48401 : Convert "sidebar_category_sorting_menu" to functional components and replace with compass icons
  components/sidebar/add_channel_dropdown.tsx
  components/sidebar/sidebar_category/__snapshots__/sidebar_category.test.tsx.snap
  components/sidebar/sidebar_category/sidebar_category_sorting_menu/__snapshots__/sidebar_category_sorting_menu.test.tsx.snap
  components/sidebar/sidebar_category/sidebar_category_sorting_menu/index.ts
  components/sidebar/sidebar_category/sidebar_category_sorting_menu/sidebar_category_sorting_menu.test.tsx
  components/sidebar/sidebar_category/sidebar_category_sorting_menu/sidebar_category_sorting_menu.tsx
  utils/constants.tsx
Labels: 4: Reviews Complete, 3: QA Review, release-note-none

#11590 MM-48379 : Convert "sidebar_channel_menu" to functional component and replace with compass icons
  components/category_menu_items/category_menu_items.tsx
  components/sidebar/sidebar_channel/sidebar_channel_link/__snapshots__/sidebar_channel_link.test.tsx.snap
  components/sidebar/sidebar_channel/sidebar_channel_link/sidebar_channel_link.tsx
  components/sidebar/sidebar_channel/sidebar_channel_menu/__snapshots__/sidebar_channel_menu.test.tsx.snap
  components/sidebar/sidebar_channel/sidebar_channel_menu/index.ts
  components/sidebar/sidebar_channel/sidebar_channel_menu/sidebar_channel_menu.test.tsx
  components/sidebar/sidebar_channel/sidebar_channel_menu/sidebar_channel_menu.tsx
Labels: 4: Reviews Complete, 3: QA Review, release-note-none

#11482 Mm 47645 show license count activated users
  components/admin_console/license_settings/__snapshots__/license_settings.test.tsx.snap
  components/admin_console/license_settings/enterprise_edition/enterprise_edition.scss
  components/admin_console/license_settings/enterprise_edition/enterprise_edition_left_panel.test.tsx
  components/admin_console/license_settings/enterprise_edition/enterprise_edition_left_panel.tsx
  components/admin_console/license_settings/license_settings.tsx
  sass/base/_css_variables.scss
  utils/constants.tsx
Labels: 2: Dev Review, 1: UX Review, release-note

#11607 MM-48423 : Landing on "Team not found" page on clean slate browser
  e2e/cypress/tests/integration/team_settings/archive_team_spec.ts
  packages/mattermost-redux/src/actions/users_queries.ts
Labels: 4: Reviews Complete, release-note

#11156 [MM-44879] Team name on sidebar header not accesible
  components/sidebar/sidebar_header/sidebar_header.tsx
  sass/layout/_sidebar-left.scss
Labels: 4: Reviews Complete, release-note, Contributor

#11485 MM-47277: Migrate /account_settings/security/ e2e tests to TypeScript
  e2e/cypress/tests/integration/account_settings/security/access_history_spec.ts
  e2e/cypress/tests/integration/account_settings/security/active_sessions_spec.ts
  e2e/cypress/tests/integration/account_settings/security/password_spec.ts
Labels: Hacktoberfest, Lifecycle/1:stale, hacktoberfest-accepted, release-note-none, Contributor

#11513 Mm 47647 team system statistics card
  components/admin_console/license_settings/enterprise_edition/enterprise_edition.scss
  components/admin_console/license_settings/enterprise_edition/enterprise_edition_left_panel.test.tsx
  components/admin_console/license_settings/enterprise_edition/enterprise_edition_left_panel.tsx
  components/analytics/__snapshots__/statistic_count.test.tsx.snap
  components/analytics/activated_users_card/index.tsx
  components/analytics/statistic_count.tsx
  components/analytics/system_analytics/system_analytics.tsx
  components/analytics/team_analytics/team_analytics.tsx
  i18n/en.json
  images/icons/warning-icon.svg
  sass/routes/_statistics.scss
  utils/overage_team.ts
Labels: 2: Dev Review, 3: QA Review, 1: UX Review, release-note

#11566 Mm 47646 Global banner that indicate overage users
  components/admin_console/license_settings/license_settings.tsx
  components/announcement_bar/announcement_bar_controller.tsx
  components/announcement_bar/default_announcement_bar/announcement_bar.tsx
  components/announcement_bar/overage_users_banner/index.tsx
  components/announcement_bar/overage_users_banner/overage_users_banner.scss
  components/announcement_bar/overage_users_banner/overage_users_banner.test.tsx
  e2e/cypress/tests/integration/enterprise/overage_users/error_overage_users_spec.ts
  i18n/en.json
  utils/constants.tsx
Labels: 2: Dev Review, 3: QA Review, release-note

#11301 Making some responsive fixes to the people directory
  components/people/directory/directory.scss
  components/people/directory/directory.tsx
  components/people/directory/people_list/people_list.tsx
  components/root/root.tsx
Labels: release-note-none

#11453 MM-47469: Remove global store usage in billing_subscriptions/index.tsx
  components/admin_console/billing/billing_subscriptions/index.tsx
Labels: 4: Reviews Complete, Hacktoberfest, hacktoberfest-accepted, release-note-none, Contributor

#11601 Adjusted mimetype for quicktime videos
  components/audio_video_preview/__snapshots__/audio_video_preview.test.tsx.snap
  components/audio_video_preview/audio_video_preview.tsx
Labels: 4: Reviews Complete, release-note

#11491 Fixed post pasteHandler not saving drafts
  components/advanced_create_post/advanced_create_post.test.jsx
  components/advanced_create_post/advanced_create_post.tsx
Labels: 4: Reviews Complete, release-note-none

#11354 [MM-47145] Adding my insights to free tier
  components/activity_and_insights/insights/hooks.ts
  components/activity_and_insights/insights/insights.tsx
  components/activity_and_insights/insights/insights_header/insights_header.scss
  components/activity_and_insights/insights/insights_title/__snapshots__/insights_title.test.tsx.snap
  components/activity_and_insights/insights/insights_title/insights_title.test.tsx
  components/activity_and_insights/insights/insights_title/insights_title.tsx
  components/widgets/menu/menu_items/menu_item_action.test.tsx
  components/widgets/menu/menu_items/menu_item_action.tsx
  components/widgets/menu/menu_items/restricted_indicator.tsx
  i18n/en.json
  utils/constants.tsx
Labels: 3: QA Review, Setup Cloud Test Server, release-note

#11575 Fixes duplicated threads in thread list
  packages/mattermost-redux/src/reducers/entities/threads/threads.test.js
  packages/mattermost-redux/src/reducers/entities/threads/threadsInTeam.ts
Labels: 4: Reviews Complete, release-note

#11619 MM-46893 : e2e for leave and archive channel destructive
  components/widgets/menu/menu_items/menu_item.scss
  e2e/cypress/tests/integration/channel/leave_and_archive_channel_destructive_spec.ts
Labels: release-note-none, Contributor

#11588 [MM-47606]: Blank message in threads if send leave/join message preference is off
  components/threading/global_threads/thread_pane/thread_pane.test.tsx
  packages/mattermost-redux/src/selectors/entities/posts.test.ts
  packages/mattermost-redux/src/selectors/entities/posts.ts
  packages/mattermost-redux/src/utils/post_list.ts
Labels: 4: Reviews Complete, release-note

#11620 MM-48512 : Add tracing option in redux dev tools
  package-lock.json
  package.json
  packages/mattermost-redux/src/store/configureStore.ts
Labels: 4: Reviews Complete, release-note-none

#11437 [MM-44347] Add popover for user groups
  actions/views/search.js
  components/at_mention/__snapshots__/at_mention.test.tsx.snap
  components/at_mention/at_mention.tsx
  components/at_mention/at_mention_group.tsx
  components/needs_team/needs_team.tsx
  components/user_group_popover/__snapshots__/user_group_popover.test.tsx.snap
  components/user_group_popover/group_member_list/__snapshots__/group_member_list.test.tsx.snap
  components/user_group_popover/group_member_list/group_member_list.test.tsx
  components/user_group_popover/group_member_list/group_member_list.tsx
  components/user_group_popover/group_member_list/index.ts
  components/user_group_popover/index.ts
  components/user_group_popover/user_group_popover.scss
  components/user_group_popover/user_group_popover.test.tsx
  components/user_group_popover/user_group_popover.tsx
  i18n/en.json
  reducers/views/search.test.js
  reducers/views/search.ts
  types/store/views.ts
  utils/constants.tsx
Labels: 3: QA Review, Setup Cloud Test Server, release-note

#11383 [MM-47024][MM-47708] Create remote entrypoint for webapp to be imported by desktop, add basic module registry
  module_registry.ts
  utils/browser_history.tsx
  utils/url.tsx
  webpack.config.js
Labels: 4: Reviews Complete, release-note-none

#11559 [ММ-47196] - Don't show desktop app download link on ChromeOS devices
  components/root/root.tsx
  utils/user_agent.tsx
Labels: 4: Reviews Complete, release-note-none

#11481 [MM-47384] Make OpenID Connect free for all
  components/admin_console/admin_definition.jsx
  components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.tsx.snap
  components/admin_console/admin_sidebar/admin_sidebar.tsx
Labels: Setup Cloud Test Server, release-note-none

#11441 [MM-45789] Don't update redux state unless something has actually changed
  packages/mattermost-redux/src/reducers/entities/channels.ts
Labels: 3: QA Review, Setup Cloud Test Server, release-note

#11346 [MM-48542] Remove integrations limits and usage
  actions/cloud.tsx
  actions/websocket_actions.jsx
  components/admin_console/billing/billing_subscriptions/limits.test.tsx
  components/admin_console/billing/billing_subscriptions/limits.tsx
  components/admin_console/billing/plan_details/feature_list.tsx
  components/cloud_usage_modal/index.test.tsx
  components/cloud_usage_modal/lhs_nearing_limit_modal.tsx
  components/cloud_usage_modal/workspace_limits_panel.tsx
  components/common/hooks/useGetHighestThresholdCloudLimit.ts
  components/common/hooks/useGetMultiplesExceededCloudLimit.test.ts
  components/common/hooks/useGetMultiplesExceededCloudLimit.ts
  components/common/hooks/useGetUsage.ts
  components/common/hooks/useGetUsageDeltas.ts
  components/delinquency_modal/freemium_modal.test.tsx
  components/delinquency_modal/freemium_modal.tsx
  components/pricing_modal/content.tsx
  components/pricing_modal/downgrade_team_removal_modal/index.tsx
  components/pricing_modal/starter_disclaimer_cta.tsx
  components/widgets/menu/menu_items/useWords.test.tsx
  components/widgets/menu/menu_items/useWords.tsx
  i18n/de.json
  i18n/en.json
  i18n/en_AU.json
  i18n/ja.json
  i18n/nl.json
  i18n/pl.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
  packages/client/src/client4.ts
  packages/mattermost-redux/src/action_types/cloud.ts
  packages/mattermost-redux/src/reducers/entities/usage.ts
  packages/mattermost-redux/src/selectors/entities/usage.ts
  packages/mattermost-redux/src/store/initial_state.ts
  packages/types/src/cloud.ts
  utils/constants.tsx
  utils/limits.tsx
  utils/limits_test.tsx
  utils/notify_admin_utils.ts
Labels: 3: QA Review, release-note

#11627 [MM-48510] : Remove duplication of alert banner, in file limit banner and modify alert banner
  components/__snapshots__/alert_banner.test.tsx.snap
  components/alert_banner.scss
  components/alert_banner.tsx
  components/file_limit_sticky_banner/index.tsx
  i18n/en.json
Labels: 4: Reviews Complete, CherryPick/Approved, AutoMerge, Setup Cloud + CWS Test Server, release-note

#11637 Automated cherry pick of #11627
  components/__snapshots__/alert_banner.test.tsx.snap
  components/alert_banner.scss
  components/alert_banner.tsx
  components/file_limit_sticky_banner/index.tsx
  i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#11630 MM-47750 acknowledgements
  actions/websocket_actions.jsx
  components/advanced_create_post/__snapshots__/advanced_create_post.test.jsx.snap
  components/advanced_create_post/advanced_create_post.test.jsx
  components/advanced_create_post/advanced_create_post.tsx
  components/advanced_text_editor/advanced_text_editor.scss
  components/post_priority/post_priority_label.tsx
  components/post_priority/post_priority_picker.scss
  components/post_priority/post_priority_picker.tsx
  components/post_priority/post_priority_picker_item.tsx
  components/post_priority/post_priority_picker_overlay.tsx
  components/post_view/acknowledgements/index.ts
  components/post_view/acknowledgements/post_acknowledgements.scss
  components/post_view/acknowledgements/post_acknowledgements.tsx
  components/post_view/acknowledgements/post_acknowledgements_users_popover.tsx
  components/post_view/post_body/index.ts
  components/post_view/post_body/post_body.tsx
  components/rhs_root_post/__snapshots__/rhs_root_post.test.jsx.snap
  components/rhs_root_post/index.ts
  components/rhs_root_post/rhs_root_post.jsx
  components/toggle.tsx
  i18n/en.json
  packages/client/src/client4.ts
  packages/mattermost-redux/src/action_types/posts.ts
  packages/mattermost-redux/src/actions/posts.ts
  packages/mattermost-redux/src/reducers/entities/posts.ts
  packages/mattermost-redux/src/selectors/entities/general.ts
  packages/mattermost-redux/src/selectors/entities/posts.ts
  packages/mattermost-redux/src/store/initial_state.ts
  packages/types/src/config.ts
  packages/types/src/posts.ts
  sass/components/_post.scss
  sass/components/_toggle.scss
  sass/utils/_mixins.scss
  types/store/draft.ts
  utils/constants.tsx
Labels: 4: Reviews Complete, release-note

#11634 MM-47759 - fix telemetry id for self-hosted trial started from feature discovery pages
  components/admin_console/feature_discovery/__snapshots__/feature_discovery.test.tsx.snap
  components/admin_console/feature_discovery/feature_discovery.tsx
Labels: 2: Dev Review, Setup Cloud Test Server, release-note-none

#11530 [MM-47966] Improve accessibility for profile popovers
  components/add_user_to_channel_modal/__snapshots__/add_user_to_channel_modal.test.tsx.snap
  components/add_user_to_channel_modal/add_user_to_channel_modal.test.tsx
  components/add_user_to_channel_modal/add_user_to_channel_modal.tsx
  components/at_mention/__snapshots__/at_mention.test.tsx.snap
  components/at_mention/at_mention.test.tsx
  components/at_mention/at_mention.tsx
  components/profile_picture/__snapshots__/profile_picture.test.tsx.snap
  components/profile_picture/profile_picture.tsx
  components/profile_popover/__snapshots__/profile_popover.test.tsx.snap
  components/profile_popover/index.ts
  components/profile_popover/profile_popover.scss
  components/profile_popover/profile_popover.test.tsx
  components/profile_popover/profile_popover.tsx
  components/threading/channel_threads/thread_footer/__snapshots__/thread_footer.test.tsx.snap
  components/widgets/users/avatar/avatar.tsx
  components/widgets/users/avatar/index.ts
  components/widgets/users/avatars/__snapshots__/avatars.test.tsx.snap
  components/widgets/users/avatars/avatars.tsx
  sass/components/_links.scss
  sass/components/_mentions.scss
  sass/components/_popover.scss
  sass/components/_post.scss
  sass/components/_status-icon.scss
  utils/a11y_controller.js
  utils/constants.tsx
  utils/post_utils.ts
  utils/utils.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note

#11647 Fix snapshot
  components/drafts/panel/__snapshots__/panel_body.test.tsx.snap
Labels: 2: Dev Review, release-note-none

#11626 MM-48531 Skip building Docker images in CircleCI for master/release builds
  .circleci/config.yml
Labels: 4: Reviews Complete, release-note-none

#11642 MM-48610 Change how Webpack dev server is configured so that it works again
  package-lock.json
  package.json
  packages/components/package.json
  webpack.config.js
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none

#11650 Automated cherry pick of #11530
  components/add_user_to_channel_modal/__snapshots__/add_user_to_channel_modal.test.tsx.snap
  components/add_user_to_channel_modal/add_user_to_channel_modal.test.tsx
  components/add_user_to_channel_modal/add_user_to_channel_modal.tsx
  components/at_mention/__snapshots__/at_mention.test.tsx.snap
  components/at_mention/at_mention.test.tsx
  components/at_mention/at_mention.tsx
  components/profile_picture/__snapshots__/profile_picture.test.tsx.snap
  components/profile_picture/profile_picture.tsx
  components/profile_popover/__snapshots__/profile_popover.test.tsx.snap
  components/profile_popover/index.ts
  components/profile_popover/profile_popover.scss
  components/profile_popover/profile_popover.test.tsx
  components/profile_popover/profile_popover.tsx
  components/threading/channel_threads/thread_footer/__snapshots__/thread_footer.test.tsx.snap
  components/widgets/users/avatar/avatar.tsx
  components/widgets/users/avatar/index.ts
  components/widgets/users/avatars/__snapshots__/avatars.test.tsx.snap
  components/widgets/users/avatars/avatars.tsx
  sass/components/_links.scss
  sass/components/_mentions.scss
  sass/components/_popover.scss
  sass/components/_post.scss
  sass/components/_status-icon.scss
  utils/a11y_controller.js
  utils/constants.tsx
  utils/post_utils.ts
  utils/utils.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#11651 Automated cherry pick of #11647
  components/drafts/panel/__snapshots__/panel_body.test.tsx.snap
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#11558 Upgrade Web app to React 17
  .circleci/config.yml
  .npmrc
  Makefile
  components/__snapshots__/searchable_channel_list.test.jsx.snap
  components/__snapshots__/textbox.test.tsx.snap
  components/admin_console/data_retention_settings/channel_list/__snapshots__/channel_list.test.tsx.snap
  components/admin_console/system_roles/system_role/system_role_users/__snapshots__/system_role_users.test.tsx.snap
  components/admin_console/system_users/list/__snapshots__/system_users_list.test.tsx.snap
  components/admin_console/team_channel_settings/channel/details/__snapshots__/channel_groups.test.tsx.snap
  components/admin_console/team_channel_settings/channel/details/channel_members/__snapshots__/channel_members.test.tsx.snap
  components/admin_console/team_channel_settings/channel/list/__snapshots__/channel_list.test.tsx.snap
  components/admin_console/team_channel_settings/team/details/__snapshots__/team_groups.test.tsx.snap
  components/admin_console/team_channel_settings/team/details/team_members/__snapshots__/team_members.test.tsx.snap
  components/channel_header_dropdown/__snapshots__/channel_header_dropdown.test.tsx.snap
  components/global_header/left_controls/product_menu/product_menu_list/__snapshots__/product_menu_list.test.tsx.snap
  components/main_menu/__snapshots__/main_menu.test.tsx.snap
  components/plugin_marketplace/__snapshots__/marketplace_modal.test.tsx.snap
  components/post_view/channel_intro_message/__snapshots__/channel_intro_message.test.tsx.snap
  components/profile_popover/__snapshots__/profile_popover.test.tsx.snap
  components/select_team/components/__snapshots__/select_team_item.test.tsx.snap
  components/sidebar/__snapshots__/invite_members_button.test.tsx.snap
  components/status_dropdown/__snapshots__/status_dropdown.test.tsx.snap
  components/user_group_popover/__snapshots__/user_group_popover.test.tsx.snap
  components/user_settings/security/__snapshots__/user_settings_security.test.tsx.snap
  e2e/cypress/utils/dashboard.js
  package-lock.json
  package.json
  packages/components/package.json
  packages/mattermost-redux/src/actions/drafts.ts
  plugins/test/__snapshots__/main_menu_action.test.jsx.snap
  tests/setup.js
  webpack.config.js
Labels: 4: Reviews Complete, release-note

#11625 [MM-48028] add intergration section to the preview page
  components/worktemplates/components/modal.tsx
  components/worktemplates/components/preview.tsx
  components/worktemplates/components/preview/section.tsx
  components/worktemplates/dev_data.ts
  i18n/en.json
  packages/types/src/worktemplates.ts
Labels: 2: Dev Review, Setup Cloud Test Server, release-note-none, QA Deferred

#11614 [MM-43072] Remove OAuth 2.0 deprecation notice
  components/admin_console/admin_definition.jsx
  components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.tsx.snap
  components/admin_console/admin_sidebar/admin_sidebar.tsx
  components/admin_console/openid_convert/__snapshots__/openid_convert.test.tsx.snap
  components/admin_console/openid_convert/openid_convert.tsx
  i18n/en.json
Labels: 3: QA Review, Setup Cloud Test Server, release-note

#11658 Automated cherry pick of #11626
  .circleci/config.yml
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#11664 Automated cherry pick of #11597
  components/admin_console/permission_schemes_settings/permission_schemes_settings.test.tsx
  components/admin_console/permission_schemes_settings/permission_schemes_settings.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#11640 MM-47782 Clear unused values from local storage on logout
  actions/storage.js
  actions/storage.test.js
  store/index.js
Labels: 4: Reviews Complete, release-note, QA Deferred

#11648 MM-48648 Change CircleCI to use workspaces for storing intermediate dependencies
  .circleci/config.yml
Labels: 4: Reviews Complete, release-note-none

#11644 MM-47936: Remove feature flag.
  e2e/playwright/support/server/default_config.ts
  packages/mattermost-redux/src/selectors/entities/preferences.ts
Labels: release-note

#11666 Automated cherry pick of #11640
  actions/storage.js
  actions/storage.test.js
  store/index.js
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#11667 Automated cherry pick of #11644
  e2e/playwright/support/server/default_config.ts
  packages/mattermost-redux/src/selectors/entities/preferences.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#11617 [MM-48111] Downgrade error modal z-index incorrect with single team
  components/cloud_subscribe_result_modal/error.tsx
  components/pricing_modal/content.tsx
Labels: 4: Reviews Complete, QA Review Done, Setup Cloud + CWS Test Server, release-note-none

#11535 [MM-46538]: Add Yearly/Monthly toggle UI Changes to Purchases Modal
  components/admin_console/feature_discovery/feature_discovery.tsx
  components/common/hooks/useOpenCloudPurchaseModal.ts
  components/common/hooks/useOpenPricingModal.ts
  components/payment_form/gather_intent/gather_intent.scss
  components/pricing_modal/contact_sales_cta.tsx
  components/pricing_modal/content.tsx
  components/pricing_modal/self_hosted_content.tsx
  components/purchase_modal/index.ts
  components/purchase_modal/purchase.scss
  components/purchase_modal/purchase_modal.tsx
  components/widgets/links/upgrade_link.tsx
  components/yearly_monthly_toggle/index.scss
  components/yearly_monthly_toggle/index.tsx
  e2e/cypress/tests/integration/enterprise/cloud/billing/subscriptions_free_trial_spec.js
  i18n/en.json
  packages/types/src/config.ts
  utils/constants.tsx
Labels: 2: Dev Review, 3: QA Review, 1: UX Review, Setup Cloud + CWS Test Server, release-note-none

#11643 [MM-48613] Send/Delete Drafts Modal Button Fixes
  components/__snapshots__/generic_modal.test.tsx.snap
  components/drafts/draft_actions/__snapshots__/delete_draft_modal.test.tsx.snap
  components/drafts/draft_actions/__snapshots__/send_draft_modal.test.tsx.snap
  components/drafts/draft_actions/delete_draft_modal.tsx
  components/drafts/draft_actions/draft_actions.scss
  components/drafts/draft_actions/draft_actions.tsx
  components/drafts/draft_actions/send_draft_modal.tsx
  components/generic_modal.scss
  i18n/en.json
  packages/components/src/generic_modal/generic_modal.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#11576 MM-47666 Add ability to run Cypress tests in GitHub CI for benchmarking
  .github/workflows/performance-benchmarks.yml
  e2e/cypress/package.json
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none

#11646 MM-48640 Fix everywhere that mattermost-redux is importing web app code
  actions/cloud.tsx
  actions/emoji_actions.js
  actions/post_actions.ts
  actions/views/drafts.ts
  actions/websocket_actions.jsx
  components/actions_menu/index.ts
  components/actions_menu/selectors.ts
  components/add_groups_to_channel_modal/add_groups_to_channel_modal.test.tsx
  components/add_groups_to_channel_modal/add_groups_to_channel_modal.tsx
  components/add_groups_to_team_modal/add_groups_to_team_modal.test.tsx
  components/add_groups_to_team_modal/add_groups_to_team_modal.tsx
  components/admin_console/group_settings/group_details/group_details.tsx
  components/admin_console/team_channel_settings/channel/details/channel_details.tsx
  components/admin_console/team_channel_settings/team/details/team_details.tsx
  components/advanced_create_comment/advanced_create_comment.tsx
  components/advanced_create_post/advanced_create_post.tsx
  components/channel_groups_manage_modal/channel_groups_manage_modal.tsx
  components/cloud_fetch_error/index.tsx
  components/drafts/drafts_link.tsx
  components/root/index.ts
  components/sidebar/sidebar_category/sidebar_category_sorting_menu/index.ts
  components/sidebar/sidebar_channel/sidebar_channel_link/index.ts
  components/sidebar/sidebar_channel/sidebar_channel_menu/index.ts
  components/team_groups_manage_modal/team_groups_manage_modal.tsx
  components/user_settings/sidebar/limit_visible_gms_dms/index.ts
  components/view_user_group_modal/view_user_group_list_item/view_user_group_list_item.tsx
  components/view_user_group_modal/view_user_group_modal.tsx
  packages/mattermost-redux/.eslintrc.json
  packages/mattermost-redux/src/actions/channels.ts
  packages/mattermost-redux/src/actions/cloud.ts
  packages/mattermost-redux/src/actions/drafts.ts
  packages/mattermost-redux/src/actions/emojis.ts
  packages/mattermost-redux/src/actions/groups.test.js
  packages/mattermost-redux/src/actions/groups.ts
  packages/mattermost-redux/src/constants/groups.ts
  packages/mattermost-redux/src/constants/index.ts
  packages/mattermost-redux/src/reducers/entities/posts.ts
  packages/mattermost-redux/src/reducers/entities/threads/counts.ts
  packages/mattermost-redux/src/selectors/entities/apps.test.ts
  packages/mattermost-redux/src/selectors/entities/apps.ts
  packages/mattermost-redux/src/selectors/entities/channel_categories.ts
  packages/mattermost-redux/src/selectors/entities/groups.ts
  packages/mattermost-redux/src/selectors/entities/preferences.ts
  packages/mattermost-redux/src/selectors/entities/utils.test.ts
  packages/mattermost-redux/test/test_helper.ts
  packages/types/src/groups.ts
  utils/constants.tsx
Labels: 4: Reviews Complete, release-note-none, QA Deferred

#11600 [MM-48088]: Ability to migrate from Monthly to Cloud Pro Annual
  actions/cloud.tsx
  components/admin_console/billing/plan_details/plan_pricing.tsx
  components/pricing_modal/content.tsx
  components/purchase_modal/index.ts
  components/purchase_modal/process_payment_setup.tsx
  components/purchase_modal/purchase_modal.tsx
  i18n/en.json
  packages/client/src/client4.ts
  utils/products.ts
Labels: 2: Dev Review, 3: QA Review, Setup Cloud + CWS Test Server, release-note-none

#11671 Automated cherry pick of #11643
  components/__snapshots__/generic_modal.test.tsx.snap
  components/drafts/draft_actions/__snapshots__/delete_draft_modal.test.tsx.snap
  components/drafts/draft_actions/__snapshots__/send_draft_modal.test.tsx.snap
  components/drafts/draft_actions/delete_draft_modal.tsx
  components/drafts/draft_actions/draft_actions.scss
  components/drafts/draft_actions/draft_actions.tsx
  components/drafts/draft_actions/send_draft_modal.tsx
  components/generic_modal.scss
  i18n/en.json
  packages/components/src/generic_modal/generic_modal.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#11604 [MM 48251]: Add Monthly/Yearly Badge on the Subscription Page
  components/admin_console/billing/plan_details/index.tsx
  components/admin_console/billing/plan_details/plan_details.scss
  components/admin_console/billing/plan_details/plan_details.tsx
  i18n/en.json
Labels: 2: Dev Review, 3: QA Review, 1: UX Review, Setup Cloud + CWS Test Server, release-note-none

#11669 Cherry-picking translations from master to cloud
  i18n/bg.json
  i18n/de.json
  i18n/en_AU.json
  i18n/es.json
  i18n/fr.json
  i18n/hr.json
  i18n/hu.json
  i18n/it.json
  i18n/ja.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
  i18n/zh-CN.json
Labels: 4: Reviews Complete, AutoMerge, release-note-none, Contributor

#11662 MM-48614,MM-48638,MM-48641,MM-48642: Saves priority on drafts and other fixes
  actions/views/drafts.ts
  actions/websocket_actions.jsx
  components/advanced_create_post/advanced_create_post.tsx
  components/advanced_create_post/index.ts
  components/advanced_text_editor/advanced_text_editor.tsx
  components/channel_header/index.ts
  components/drafts/channel_draft/channel_draft.tsx
  components/drafts/drafts_link.tsx
  components/drafts/panel/__snapshots__/panel_body.test.tsx.snap
  components/drafts/panel/panel_body.scss
  components/drafts/panel/panel_body.test.tsx
  components/drafts/panel/panel_body.tsx
  components/post_priority/post_priority_picker.scss
  components/post_priority/post_priority_picker.tsx
  components/post_priority/post_priority_picker_item.tsx
  components/post_priority/post_priority_picker_overlay.tsx
  components/post_view/acknowledgements/post_acknowledgements.tsx
  components/search_bar/__snapshots__/search_bar.test.tsx.snap
  components/suggestion/suggestion_box/suggestion_box.jsx
  components/textbox/textbox.tsx
  components/toggle.tsx
  packages/mattermost-redux/src/selectors/entities/channels.ts
  packages/mattermost-redux/src/selectors/entities/posts.ts
  packages/types/src/drafts.ts
  sass/components/_toggle.scss
  sass/responsive/_tablet.scss
  selectors/rhs.ts
  selectors/storage.ts
Labels: 4: Reviews Complete, release-note-none

#11635 MM-48573 : "Back to Team" link from system console is crashing after "needs_team" is migrated to "team_controller"
  components/__snapshots__/list_modal.test.jsx.snap
  components/__snapshots__/searchable_channel_list.test.jsx.snap
  components/access_history_modal/__snapshots__/access_history_modal.test.tsx.snap
  components/admin_console/custom_terms_of_service_settings/__snapshots__/custom_terms_of_service_settings.test.tsx.snap
  components/admin_console/manage_teams_modal/__snapshots__/manage_teams_modal.test.tsx.snap
  components/admin_console/manage_tokens_modal/__snapshots__/manage_tokens_modal.test.tsx.snap
  components/admin_console/permission_schemes_settings/__snapshots__/permission_schemes_settings.test.tsx.snap
  components/admin_console/permission_schemes_settings/permission_system_scheme_settings/__snapshots__/permission_system_scheme_settings.test.tsx.snap
  components/admin_console/permission_schemes_settings/permission_team_scheme_settings/__snapshots__/permission_team_scheme_settings.test.tsx.snap
  components/channel_header/channel_info_button.tsx
  components/channel_info_rhs/index.ts
  components/channel_layout/channel_controller.tsx
  components/common/__snapshots__/infinite_scroll.test.tsx.snap
  components/integrations/edit_command/__snapshots__/edit_command.test.tsx.snap
  components/integrations/edit_incoming_webhook/__snapshots__/edit_incoming_webhook.test.tsx.snap
  components/integrations/edit_outgoing_webhook/__snapshots__/edit_outgoing_webhook.test.tsx.snap
  components/loading_screen.tsx
  components/logged_in/logged_in.test.tsx
  components/login/login.test.tsx
  components/needs_team/needs_team.tsx
  components/plugin_marketplace/__snapshots__/marketplace_modal.test.tsx.snap
  components/post_view/__snapshots__/post_view.test.tsx.snap
  components/post_view/post_list/post_list.tsx
  components/post_view/post_view.tsx
  components/search_results/index.tsx
  components/search_results_item/index.ts
  components/select_team/__snapshots__/select_team.test.tsx.snap
  components/sidebar_right/index.ts
  components/sidebar_right/sidebar_right.tsx
  components/terms_of_service/__snapshots__/terms_of_service.test.tsx.snap
  components/threading/global_threads/thread_list/__snapshots__/virtualized_thread_list_row.test.tsx.snap
  components/view_user_group_modal/__snapshots__/view_user_group_modal.test.tsx.snap
  e2e/cypress/tests/integration/channel/channel_info_rhs_spec.js
  e2e/cypress/tests/integration/channel/open_rhs_coming_from_system_console_spec.ts
  e2e/cypress/tests/support/ui/global_header.d.ts
  e2e/cypress/tests/support/ui/global_header.js
  sass/components/_post.scss
  sass/layout/_sidebar-right.scss
  sass/routes/_loading.scss
Labels: 4: Reviews Complete, release-note

#11678 Manual cherry pick of #11662
  actions/views/drafts.ts
  actions/websocket_actions.jsx
  components/advanced_create_post/advanced_create_post.tsx
  components/advanced_create_post/index.ts
  components/advanced_text_editor/advanced_text_editor.tsx
  components/channel_header/index.ts
  components/drafts/channel_draft/channel_draft.tsx
  components/drafts/drafts_link.tsx
  components/drafts/panel/__snapshots__/panel_body.test.tsx.snap
  components/drafts/panel/panel_body.scss
  components/drafts/panel/panel_body.test.tsx
  components/drafts/panel/panel_body.tsx
  components/post_priority/post_priority_picker.scss
  components/post_priority/post_priority_picker.tsx
  components/post_priority/post_priority_picker_item.tsx
  components/post_priority/post_priority_picker_overlay.tsx
  components/post_view/acknowledgements/post_acknowledgements.tsx
  components/search_bar/__snapshots__/search_bar.test.tsx.snap
  components/suggestion/suggestion_box/suggestion_box.jsx
  components/textbox/textbox.tsx
  components/toggle.tsx
  packages/mattermost-redux/src/actions/drafts.ts
  packages/mattermost-redux/src/selectors/entities/channels.ts
  packages/mattermost-redux/src/selectors/entities/posts.ts
  packages/types/src/drafts.ts
  sass/components/_toggle.scss
  sass/responsive/_tablet.scss
  selectors/rhs.ts
  selectors/storage.ts
Labels: release-note-none

#11598 Mm 47422 signup token
  components/admin_console/admin_console.test.tsx
  components/admin_console/admin_sidebar/admin_sidebar.test.tsx
  components/common/hooks/useLoadStripe.ts
  components/common/hooks/useOpenSelfHostedPurchaseModal.ts
  components/global_header/right_controls/right_controls.tsx
  components/global_header/right_controls/self_hosted_purchase_button/index.tsx
  components/self_hosted_purchase_modal/index.tsx
  e2e/playwright/support/server/default_config.ts
  packages/client/src/client4.ts
  packages/mattermost-redux/src/action_types/cloud.ts
  packages/mattermost-redux/src/reducers/entities/cloud.ts
  packages/mattermost-redux/src/selectors/entities/cloud.ts
  packages/mattermost-redux/src/store/initial_state.ts
  packages/types/src/cloud.ts
  packages/types/src/config.ts
  utils/constants.tsx
Labels: 2: Dev Review, release-note-none

#11531 Add performance tests for channel and team switch
  .github/workflows/performance-benchmarks.yml
  e2e/cypress/tests/integration/performance/channel_switch_spec.js
  e2e/cypress/tests/integration/performance/team_switch_spec.js
  e2e/cypress/tests/integration/performance/utils.js
Labels: 3: QA Review, release-note-none
