Repository mattermost/mattermost-webapp, pull requests merged in 2023-04, with the labels that each got.

#12389 MM-51763 Use STRIPE_PUBLIC_KEY from webpack (7.9)
  components/payment_form/stripe.ts
  webpack.config.js
Labels: 2: Dev Review, release-note-none

#12390 MM-51763 Use STRIPE_PUBLIC_KEY from webpack (7.10)
  components/payment_form/stripe.ts
  webpack.config.js
Labels: 2: Dev Review, release-note-none

#12391 MM-51763 Use STRIPE_PUBLIC_KEY from webpack (7.8)
  components/payment_form/stripe.ts
  webpack.config.js
Labels: 2: Dev Review, release-note-none

#12392 use stripe public key from environment
  components/payment_form/stripe.ts
  webpack.config.js
Labels: 2: Dev Review, release-note-none

#12394 Cherry pick of mattermost/mattermost-server#22491
  components/advanced_text_editor/advanced_text_editor.tsx
  components/textbox/textbox.tsx
  e2e/cypress/tests/integration/collapsed_reply_threads/replies_spec.js
Labels: release-note-none

#12395 Cherry-pick https://github.com/mattermost/mattermost-server/pull/22711 [MM-51489]: Fix issue with compact message mode
  components/post/post_component.tsx
  components/post/post_options.tsx
  sass/components/_post-right.scss
  sass/components/_post.scss
  sass/responsive/_tablet.scss
Labels: 4: Reviews Complete, AutoMerge, release-note

#12396 Cherry-pick https://github.com/mattermost/mattermost-server/pull/22711 [MM-51489]: Fix issue with compact message mode
  components/post/post_component.tsx
  components/post/post_options.tsx
  sass/components/_post-right.scss
  sass/components/_post.scss
  sass/responsive/_tablet.scss
Labels: 4: Reviews Complete, AutoMerge, release-note
