Repository mattermost/mattermost-webapp, pull requests merged in 2023-01, with the labels that each got.

#11877 MM-49414 : Fix failing e2e due to recent a11y changes
  e2e/cypress/tests/integration/accessibility/accessibility_account_settings_spec.js
  e2e/cypress/tests/integration/enterprise/accessibility/accessibility_input_fields_spec.js
  e2e/cypress/tests/integration/notifications/channel_links_show_as_links_spec.js
  e2e/cypress/tests/support/ui/account_settings_modal.js
  e2e/cypress/tests/support/ui/global_header.js
Labels: 3: QA Review, release-note-none

#11862 MM-49371 : Improve typing of `utils/emoji_map.ts`
  components/suggestion/emoticon_provider.jsx
  utils/emoji_map.ts
  utils/text_formatting.tsx
Labels: 4: Reviews Complete, release-note-none

#11798 MM-49058 : Remove unused getChannelRef from SidebarChannel component
  components/sidebar/sidebar_category/__snapshots__/sidebar_category.test.tsx.snap
  components/sidebar/sidebar_category/sidebar_category.test.tsx
  components/sidebar/sidebar_category/sidebar_category.tsx
  components/sidebar/sidebar_channel/__snapshots__/sidebar_channel.test.tsx.snap
  components/sidebar/sidebar_channel/index.ts
  components/sidebar/sidebar_channel/sidebar_channel.test.tsx
  components/sidebar/sidebar_channel/sidebar_channel.tsx
  components/sidebar/sidebar_channel_list/__snapshots__/sidebar_channel_list.test.tsx.snap
  components/sidebar/sidebar_channel_list/sidebar_channel_list.tsx
  components/sidebar/unread_channels/unread_channels.tsx
Labels: 4: Reviews Complete, release-note-none

#11881 fix(cypress): a11y account settings test case
  e2e/cypress/tests/integration/accessibility/accessibility_account_settings_spec.js
  e2e/cypress/tests/integration/settings/display/clock_display_mode_spec.js
  e2e/cypress/tests/integration/system_console/reporting/team_statistics_spec.js
Labels: release-note-none

#11882 Fix(cypress): file upload test case
  e2e/cypress/tests/integration/files_and_attachments/cancel_file_upload_spec.js
  e2e/cypress/tests/integration/multi_team_and_dm/join_open_team_from_dm_spec.js
  e2e/cypress/tests/integration/performance/team_switch_spec.js
Labels: release-note-none

#11879 Simplify form checking, add confirmed_intent state, show modal to admins when purchase is already in progress
  components/common/hooks/useControlModal.ts
  components/common/hooks/useControlSelfHostedPurchaseModal.ts
  components/purchase_in_progress_modal/index.scss
  components/purchase_in_progress_modal/index.tsx
  components/self_hosted_purchase_modal/index.test.tsx
  components/self_hosted_purchase_modal/index.tsx
  i18n/en.json
  packages/client/src/client4.ts
  packages/mattermost-redux/src/selectors/entities/common.ts
  packages/types/src/hosted_customer.ts
  utils/constants.tsx
Labels: release-note-none, QA Deferred

#11823 [MM-48362] replace emojis with icon for onboarding task list
  components/common/svg_images_components/bulls_eye_svg.tsx
  components/common/svg_images_components/channels_svg.tsx
  components/common/svg_images_components/clipboard_svg.tsx
  components/common/svg_images_components/gears_svg.tsx
  components/common/svg_images_components/handshake_svg.tsx
  components/common/svg_images_components/phone_svg.tsx
  components/common/svg_images_components/security_svg.tsx
  components/common/svg_images_components/sunglasses_svg.tsx
  components/common/svg_images_components/wrench_svg.tsx
  components/onboarding_tasklist/onboarding_tasklist.tsx
  components/onboarding_tasklist/onboarding_tasklist_task.tsx
  components/onboarding_tasks/onboarding_tasks_manager.tsx
  i18n/de.json
  i18n/en.json
  i18n/en_AU.json
  i18n/ja.json
  i18n/nl.json
  i18n/pl.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
Labels: 4: Reviews Complete, QA Review Done, release-note-none

#11887 Automated cherry pick of #11824
  components/notify_confirm_modal.tsx
  i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#11888 Automated cherry pick of #11879
  components/common/hooks/useControlModal.ts
  components/common/hooks/useControlSelfHostedPurchaseModal.ts
  components/purchase_in_progress_modal/index.scss
  components/purchase_in_progress_modal/index.tsx
  components/self_hosted_purchase_modal/index.test.tsx
  components/self_hosted_purchase_modal/index.tsx
  i18n/en.json
  packages/client/src/client4.ts
  packages/mattermost-redux/src/selectors/entities/common.ts
  packages/types/src/hosted_customer.ts
  utils/constants.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#11391 enable cloud test
  components/pricing_modal/starter_disclaimer_cta.tsx
  e2e/cypress/tests/integration/enterprise/cloud/billing/after_subscription_spec.js
  e2e/cypress/tests/integration/enterprise/cloud/billing/cloud_pricing_modal_spec.ts
  e2e/cypress/tests/integration/enterprise/cloud/billing/company_information_free_trial_spec.ts
  e2e/cypress/tests/integration/enterprise/cloud/billing/notify_admin_spec.ts
  e2e/cypress/tests/integration/enterprise/cloud/billing/payment_free_trial_spec.ts
  e2e/cypress/tests/integration/enterprise/cloud/billing/subscriptions_free_trial_spec.ts
  e2e/cypress/tests/integration/enterprise/cloud/billing/yearly_subscription_spec.js
  e2e/cypress/tests/integration/enterprise/self-hosted/self_hosted_pricing_modal_spec.js
Labels: 2: Dev Review, 3: QA Review, release-note-none

#11891 Automated cherry pick of #11391
  components/pricing_modal/starter_disclaimer_cta.tsx
  e2e/cypress/tests/integration/enterprise/cloud/billing/after_subscription_spec.js
  e2e/cypress/tests/integration/enterprise/cloud/billing/cloud_pricing_modal_spec.ts
  e2e/cypress/tests/integration/enterprise/cloud/billing/company_information_free_trial_spec.ts
  e2e/cypress/tests/integration/enterprise/cloud/billing/notify_admin_spec.ts
  e2e/cypress/tests/integration/enterprise/cloud/billing/payment_free_trial_spec.ts
  e2e/cypress/tests/integration/enterprise/cloud/billing/subscriptions_free_trial_spec.ts
  e2e/cypress/tests/integration/enterprise/cloud/billing/yearly_subscription_spec.js
  e2e/cypress/tests/integration/enterprise/self-hosted/self_hosted_pricing_modal_spec.js
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#11870 Automated cherry pick of #11803
  components/advanced_create_comment/advanced_create_comment.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#11885 Automated cherry pick of #11805
  components/delinquency_modal/delinquency_modal_controller.test.tsx
  components/delinquency_modal/useDelinquencyModalController.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#11889 Cherry-picking translations
  i18n/de.json
  i18n/en_AU.json
  i18n/fr.json
  i18n/hu.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none, Contributor

#11799 [MM-47489] Move Shared Channels (Experimental) to Professional
  components/admin_console/admin_definition.jsx
  components/admin_console/billing/plan_details/feature_list.tsx
Labels: 4: Reviews Complete, release-note-none

#11790 MM 48456 - replace standard analytics call with getFilteredUserStats lighter call
  components/admin_console/billing/billing_subscriptions/index.tsx
  components/admin_console/billing/plan_details/index.tsx
  components/admin_console/license_settings/index.ts
  components/admin_console/license_settings/license_settings.test.tsx
  components/admin_console/license_settings/license_settings.tsx
  components/admin_console/system_users/index.ts
  components/admin_console/system_users/system_users.test.tsx
  components/admin_console/system_users/system_users.tsx
  components/announcement_bar/cloud_trial_announcement_bar/cloud_trial_announcement_bar.tsx
  components/announcement_bar/cloud_trial_announcement_bar/index.ts
  components/announcement_bar/payment_announcement_bar/index.ts
  components/announcement_bar/show_start_trial_modal/show_start_trial_modal.test.tsx
  components/announcement_bar/show_start_trial_modal/show_start_trial_modal.tsx
  components/common/hooks/useGetTotalUsersNoBots.ts
  components/start_trial_modal/index.tsx
  components/warn_metric_ack_modal/index.ts
  components/warn_metric_ack_modal/warn_metric_ack_modal.test.tsx
  components/warn_metric_ack_modal/warn_metric_ack_modal.tsx
  packages/mattermost-redux/src/actions/users.ts
Labels: 4: Reviews Complete, release-note-none

#11898 [MM-49198] Fix reported device as desktop when coming from mobile app
  components/activity_log_modal/components/activity_log.tsx
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#11895 Mm 49258 purchase in progress reset
  components/common/hooks/useControlSelfHostedPurchaseModal.ts
  components/purchase_in_progress_modal/index.test.tsx
  components/purchase_in_progress_modal/index.tsx
  components/self_hosted_purchase_modal/constants.ts
  components/self_hosted_purchase_modal/index.tsx
Labels: 2: Dev Review, CherryPick/Approved, release-note-none, QA Deferred

#11899 Automated cherry pick of #11895
  components/common/hooks/useControlSelfHostedPurchaseModal.ts
  components/purchase_in_progress_modal/index.test.tsx
  components/purchase_in_progress_modal/index.tsx
  components/self_hosted_purchase_modal/constants.ts
  components/self_hosted_purchase_modal/index.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#11878 MM-47063 Migrate "components/file_preview_modal/image_preview.jsx" to Typescript
  components/file_preview_modal/file_preview_modal.tsx
  components/file_preview_modal/image_preview.tsx
  packages/types/src/files.ts
Labels: 4: Reviews Complete, release-note-none, Contributor

#11717 MM-48834 : Remove `isDev` utils function which access the redux store directly
  actions/channel_actions.ts
  actions/telemetry_actions.jsx
  components/admin_console/billing/payment_info_edit.tsx
  components/purchase_modal/index.ts
  components/self_hosted_purchase_modal/index.tsx
  entry.tsx
  packages/mattermost-redux/src/actions/errors.ts
  packages/mattermost-redux/src/actions/users.ts
  selectors/general.ts
  utils/utils.test.tsx
  utils/utils.tsx
Labels: 4: Reviews Complete, release-note-none

#11814 MM-47359 : avoid passing global state in post_actions.ts to addPostToSearchResults
  actions/post_actions.ts
Labels: 4: Reviews Complete, release-note, Contributor

#11902 Automated cherry pick of #11873
  packages/client/src/client4.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#11896 MM-49395: Update max emoji file size
  i18n/en.json
Labels: 2: Dev Review, release-note-none

#11875 Automated cherry pick of #11706
  actions/notification_actions.test.js
  components/admin_console/admin_definition.jsx
  components/permalink_view/permalink_view.test.tsx
  components/suggestion/switch_channel_provider.test.jsx
  packages/mattermost-redux/src/actions/channels.test.js
  packages/mattermost-redux/src/actions/posts.test.js
  packages/mattermost-redux/src/actions/preferences.test.js
  packages/mattermost-redux/src/actions/teams.test.js
  packages/mattermost-redux/src/actions/users.test.js
  packages/mattermost-redux/src/selectors/entities/channel_categories.test.ts
  packages/mattermost-redux/src/selectors/entities/channels.test.ts
  packages/mattermost-redux/src/selectors/entities/preferences.ts
  utils/post_utils.test.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#11894 Automated cherry pick of #11799
  components/admin_console/admin_definition.jsx
  components/admin_console/billing/plan_details/feature_list.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#11869 [MM-49358] Fix alignment HFT routes
  components/air_gapped_self_hosted_purchase_modal/content.scss
Labels: CherryPick/Approved, Setup Cloud Test Server, release-note-none

#11909 Automated cherry pick of #11869
  components/air_gapped_self_hosted_purchase_modal/content.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#11908 Automated cherry pick of #11869
  components/air_gapped_self_hosted_purchase_modal/content.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#11876 MM-49057 - disable channel creation if add board check is checked but…
  components/new_channel_modal/new_channel_modal.tsx
Labels: CherryPick/Approved, Setup Cloud Test Server, QA Review Done, release-note-none

#11913 Automated cherry pick of #11876
  components/new_channel_modal/new_channel_modal.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#11912 Automated cherry pick of #11876
  components/new_channel_modal/new_channel_modal.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#11901 [MM-49483] Failing preferences request causes infinite loop in onboarding tasklist
  components/onboarding_tasklist/onboarding_tasklist.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, release-note-none

#11871 [MM-47669] - Apply changes recommended by Lighthouse audit
  .github/workflows/performance-benchmarks.yml
  components/__snapshots__/file_upload_overlay.test.tsx.snap
  components/drafts/panel/__snapshots__/panel_body.test.tsx.snap
  components/file_preview_modal/__snapshots__/image_preview.test.jsx.snap
  components/file_preview_modal/image_preview.tsx
  components/file_upload_overlay.tsx
  components/post_view/reaction/__snapshots__/reaction.test.tsx.snap
  components/post_view/reaction/reaction.tsx
  components/sidebar/sidebar_channel/sidebar_channel_link/sidebar_channel_link.tsx
  components/suggestion/at_mention_provider/__snapshots__/at_mention_suggestion.test.tsx.snap
  components/team_sidebar/components/team_button.tsx
  components/threading/channel_threads/thread_footer/__snapshots__/thread_footer.test.tsx.snap
  components/user_group_popover/__snapshots__/user_group_popover.test.tsx.snap
  components/user_group_popover/group_member_list/__snapshots__/group_member_list.test.tsx.snap
  components/widgets/team_icon/team_icon.scss
  components/widgets/users/avatar/__snapshots__/avatar.test.tsx.snap
  components/widgets/users/avatar/avatar.tsx
  components/widgets/users/avatars/__snapshots__/avatars.test.tsx.snap
  e2e/cypress/tests/integration/performance/utils.js
  sass/components/_alerts.scss
  sass/components/_emojisprite.scss
  sass/components/_post.scss
  sass/utils/_flex.scss
Labels: Setup Cloud Test Server, release-note-none

#11818 MM-49162: Fix Pinned RHS not loading in Threads view
  components/sidebar_right/sidebar_right.tsx
Labels: 4: Reviews Complete, release-note

#11914 Removed chai assert from Save Report
  e2e/cypress/save_report.js
Labels: 4: Reviews Complete, release-note-none

#11819 Image utility buttons are not appropriate for all locations
  components/__snapshots__/textbox.test.tsx.snap
  components/channel_header/__snapshots__/channel_header.test.tsx.snap
  components/channel_header/channel_header.tsx
  components/markdown_image/markdown_image.jsx
  components/size_aware_image.jsx
  components/textbox/textbox.tsx
Labels: 4: Reviews Complete, release-note-none, Contributor

#11915 Self hosted purchase compliance wording
  components/purchase_modal/icon_message.scss
  components/self_hosted_purchase_modal/error.tsx
  i18n/en.json
Labels: 1: PM Review, 2: Dev Review, CherryPick/Approved, release-note-none, QA Deferred

#11918 Automated cherry pick of #11901
  components/onboarding_tasklist/onboarding_tasklist.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#11919 Automated cherry pick of #11915
  components/purchase_modal/icon_message.scss
  components/self_hosted_purchase_modal/error.tsx
  i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#11916 Automated cherry pick of #11901
  components/onboarding_tasklist/onboarding_tasklist.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#11917 Automated cherry pick of #11915
  components/purchase_modal/icon_message.scss
  components/self_hosted_purchase_modal/error.tsx
  i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#11903 MM-48388 : Attach the improved menu to sidebar category menus
  components/sidebar/sidebar_category/__snapshots__/sidebar_category.test.tsx.snap
  components/sidebar/sidebar_category/sidebar_category.tsx
  components/sidebar/sidebar_category/sidebar_category_menu/__snapshots__/sidebar_category_menu.test.tsx.snap
  components/sidebar/sidebar_category/sidebar_category_menu/index.ts
  components/sidebar/sidebar_category/sidebar_category_menu/sidebar_category_menu.test.tsx
  components/sidebar/sidebar_category/sidebar_category_menu/sidebar_category_menu.tsx
  components/sidebar/sidebar_category/sidebar_category_sorting_menu/__snapshots__/sidebar_category_sorting_menu.test.tsx.snap
  components/sidebar/sidebar_category/sidebar_category_sorting_menu/sidebar_category_sorting_menu.test.tsx
  components/sidebar/sidebar_category/sidebar_category_sorting_menu/sidebar_category_sorting_menu.tsx
  components/sidebar/sidebar_menu/__snapshots__/sidebar_menu.test.tsx.snap
  components/sidebar/sidebar_menu/index.ts
  components/sidebar/sidebar_menu/sidebar_menu.test.tsx
  components/sidebar/sidebar_menu/sidebar_menu.tsx
  sass/layout/_sidebar-left.scss
  utils/constants.tsx
Labels: release-note-none

#11925 Automated cherry pick of #11904
  components/pricing_modal/self_hosted_content.tsx
  i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#11927 Manual cherry pick of #11904
  components/pricing_modal/self_hosted_content.tsx
  i18n/en.json
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#11780 MM-47295 : Emoji e2e tests to typescript migration
  e2e/cypress/tests/integration/emoji/custom_emoji_1_1_spec.ts
  e2e/cypress/tests/integration/emoji/custom_emoji_1_spec.ts
  e2e/cypress/tests/integration/emoji/custom_emoji_2_1_spec.ts
  e2e/cypress/tests/integration/emoji/custom_emoji_2_spec.ts
  e2e/cypress/tests/integration/emoji/custom_emoji_3_spec.ts
  e2e/cypress/tests/integration/emoji/recently_used_emoji_1_spec.ts
  e2e/cypress/tests/integration/emoji/recently_used_emoji_2_spec.ts
  e2e/cypress/tests/integration/emoji/sorted_emojis_spec.ts
  e2e/cypress/tests/support/ui/emoji.d.ts
  e2e/cypress/tests/support/ui/emoji.js
  e2e/cypress/tests/support/ui/emoji.ts
  e2e/cypress/tests/support/ui_commands.ts
Labels: 4: Reviews Complete, release-note, Contributor

#11820 MM-T2503 Boolean value check
  e2e/cypress/tests/integration/interactive_dialog/demo_boolean_spec.ts
Labels: 4: Reviews Complete, release-note-none

#11826 MM-T624 Viewing attachments with invalid URL
  e2e/cypress/tests/integration/integrations/incoming_webhook/invalid_attachment_URL_webhook_spec.ts
Labels: 4: Reviews Complete, release-note-none

#11847 MM-T5208 - Continue to show global Threads item when unread filter is enabled
  e2e/cypress/tests/integration/channel_sidebar/unread_filter_spec.ts
Labels: 4: Reviews Complete, release-note-none

#11693 Initial E2e fixes for post components
  components/message_with_additional_content.tsx
  components/new_post/index.tsx
  components/new_post/post_component.tsx
  components/new_post/post_options.tsx
  components/new_post/user_profile.tsx
  components/post_view/commented_on/__snapshots__/commented_on.test.tsx.snap
  components/post_view/commented_on/commented_on.tsx
  components/post_view/post_flag_icon/post_flag_icon.tsx
  components/post_view/post_reaction/post_reaction.tsx
  components/rhs_comment/__snapshots__/rhs_comment.test.tsx.snap
  components/rhs_comment/rhs_comment.tsx
  components/rhs_root_post/__snapshots__/rhs_root_post.test.jsx.snap
  components/rhs_root_post/rhs_root_post.jsx
  e2e/cypress/tests/integration/messaging/system_message_limited_options_spec.js
  e2e/cypress/tests/integration/multi_team_and_dm/gm_header_spec.js
  e2e/cypress/tests/integration/notifications/reply_notifications_spec.js
  e2e/cypress/tests/integration/scroll/channel_scroll_spec.js
  e2e/cypress/tests/support/ui_commands.ts
Labels: release-note

#11932 Automated cherry pick of #11837
  components/advanced_create_post/advanced_create_post.tsx
  components/advanced_text_editor/advanced_text_editor.scss
  components/post_priority/post_priority_picker.scss
  components/post_priority/post_priority_picker.tsx
  components/post_view/acknowledgements/post_acknowledgements.scss
  components/post_view/acknowledgements/post_acknowledgements.tsx
  components/post_view/post_body/post_body.tsx
  components/post_view/post_info/post_info.tsx
  components/rhs_root_post/rhs_root_post.jsx
  components/search_results_item/__snapshots__/search_results_item.test.tsx.snap
  components/search_results_item/index.ts
  components/search_results_item/search_results_item.tsx
  i18n/en.json
  packages/client/src/client4.ts
  packages/types/src/posts.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#11933 MM-49516: fixes toggle switch alignment
  components/admin_console/team_channel_settings/line_switch.tsx
  sass/components/_line-switch.scss
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none, QA Deferred

#11942 Automated cherry pick of #11911
  components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
  i18n/i18n.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#11943 Automated cherry pick of #11933
  components/admin_console/team_channel_settings/line_switch.tsx
  sass/components/_line-switch.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#11941 Automated cherry pick of #11933
  components/admin_console/team_channel_settings/line_switch.tsx
  sass/components/_line-switch.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#11860 [MM-47487] Remove cloud professional file storage limit
  components/admin_console/billing/billing_subscriptions/index.tsx
  components/admin_console/billing/billing_subscriptions/limit_reached_banner.test.tsx
  components/admin_console/billing/billing_subscriptions/limit_reached_banner.tsx
  components/admin_console/billing/billing_subscriptions/limits.test.tsx
  components/admin_console/billing/billing_subscriptions/limits.tsx
  components/admin_console/billing/billing_subscriptions/single_inline_limit.scss
  components/admin_console/billing/billing_subscriptions/single_inline_limit.tsx
  components/admin_console/billing/plan_details/feature_list.tsx
  components/admin_console/team_channel_settings/team/details/team_profile.test.tsx
  components/announcement_bar/cloud_trial_ended_announcement_bar/cloud_trial_ended_announcement_bar.test.tsx
  components/announcement_bar/show_tree_days_left_trial_modal/show_three_days_left_trial_modal.test.tsx
  components/cloud_usage_modal/index.test.tsx
  components/cloud_usage_modal/lhs_nearing_limit_modal.tsx
  components/common/hooks/useGetHighestThresholdCloudLimit.test.ts
  components/common/hooks/useGetMultiplesExceededCloudLimit.test.ts
  components/delinquency_modal/freemium_modal.tsx
  components/pricing_modal/content.tsx
  components/pricing_modal/downgrade_team_removal_modal/downgrade_team_removal_modal.test.tsx
  components/search_results/search_limits_banner.test.tsx
  components/sidebar/sidebar_header/sidebar_header.test.tsx
  components/widgets/menu/menu_items/menu_cloud_trial.test.tsx
  components/widgets/menu/menu_items/menu_item_cloud_limit.test.tsx
  components/widgets/menu/menu_items/useWords.test.tsx
  i18n/en.json
  utils/limits.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, AutoMerge, Setup Cloud + CWS Test Server, release-note

#11939 Automated cherry pick of #11911
  components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
  i18n/i18n.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#11944 Automated cherry pick of #11860
  components/admin_console/billing/billing_subscriptions/index.tsx
  components/admin_console/billing/billing_subscriptions/limit_reached_banner.test.tsx
  components/admin_console/billing/billing_subscriptions/limit_reached_banner.tsx
  components/admin_console/billing/billing_subscriptions/limits.test.tsx
  components/admin_console/billing/billing_subscriptions/limits.tsx
  components/admin_console/billing/billing_subscriptions/single_inline_limit.scss
  components/admin_console/billing/billing_subscriptions/single_inline_limit.tsx
  components/admin_console/billing/plan_details/feature_list.tsx
  components/admin_console/team_channel_settings/team/details/team_profile.test.tsx
  components/announcement_bar/cloud_trial_ended_announcement_bar/cloud_trial_ended_announcement_bar.test.tsx
  components/announcement_bar/show_tree_days_left_trial_modal/show_three_days_left_trial_modal.test.tsx
  components/cloud_usage_modal/index.test.tsx
  components/cloud_usage_modal/lhs_nearing_limit_modal.tsx
  components/common/hooks/useGetHighestThresholdCloudLimit.test.ts
  components/common/hooks/useGetMultiplesExceededCloudLimit.test.ts
  components/delinquency_modal/freemium_modal.tsx
  components/pricing_modal/content.tsx
  components/pricing_modal/downgrade_team_removal_modal/downgrade_team_removal_modal.test.tsx
  components/search_results/search_limits_banner.test.tsx
  components/sidebar/sidebar_header/sidebar_header.test.tsx
  components/widgets/menu/menu_items/menu_cloud_trial.test.tsx
  components/widgets/menu/menu_items/menu_item_cloud_limit.test.tsx
  components/widgets/menu/menu_items/useWords.test.tsx
  i18n/en.json
  utils/limits.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#11940 MM-49487: fixes post priority picker in safari
  components/post_priority/post_priority_picker_item.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, AutoMerge, release-note-none, QA Deferred

#11946 Automated cherry pick of #11940
  components/post_priority/post_priority_picker_item.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#11945 Automated cherry pick of #11940
  components/post_priority/post_priority_picker_item.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#11734 Migrate A11yController to TypeScript
  utils/a11y_controller.ts
  utils/constants.tsx
Labels: 4: Reviews Complete, release-note-none

#11849 [MM-48994]: disabled ability to apply markdown in preview mode
  components/advanced_create_comment/advanced_create_comment.tsx
  components/advanced_create_post/advanced_create_post.tsx
Labels: 4: Reviews Complete, release-note-none, kind/bug

#11929 chore: fix emoji tests
  e2e/cypress/tests/fixtures/gif-image-file.gif
  e2e/cypress/tests/integration/emoji/custom_emoji_1_spec.ts
  e2e/cypress/tests/integration/enterprise/self-hosted/self_hosted_pricing_modal_spec.js
  e2e/cypress/tests/integration/enterprise/system_console/reporting/site_statistics_spec.js
  e2e/cypress/tests/integration/integrations/builtin_commands/invite_command_spec.js
  e2e/cypress/tests/integration/integrations/incoming_webhook/edit_incoming_webhook_spec.js
  e2e/cypress/tests/integration/integrations/incoming_webhook/inapp_username_profile_override_spec.js
  e2e/cypress/tests/integration/multi_team_and_dm/multi_team_join_spec.js
  e2e/cypress/tests/integration/system_console/environment_spec.js
  e2e/cypress/tests/utils/admin_console.js
Labels: release-note-none

#11936 [MM-49559] - Fix emoji sprite in mozila firefox
  components/post_view/reaction/reaction.scss
  sass/components/_emojisprite.scss
Labels: release-note-none, QA Deferred

#11950 Automated cherry pick of #11947
  components/preparing_workspace/preparing_workspace.scss
  components/root/root.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#11953 Automated cherry pick of #11936
  components/post_view/reaction/reaction.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#11954 Automated cherry pick of #11849
  components/advanced_create_comment/advanced_create_comment.tsx
  components/advanced_create_post/advanced_create_post.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#11951 Automated cherry pick of #11936
  components/post_view/reaction/reaction.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#11952 Automated cherry pick of #11849
  components/advanced_create_comment/advanced_create_comment.tsx
  components/advanced_create_post/advanced_create_post.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#11834 [MM-49230]: Disable confirm button once clicked
  components/move_thread_modal/move_thread_modal.tsx
Labels: 4: Reviews Complete, release-note-none

#11922 [MM-49515] Show board insights for boards 'product'
  components/activity_and_insights/insights/insights.tsx
  components/activity_and_insights/insights/top_boards/top_boards.tsx
  components/activity_and_insights/insights/top_boards/top_boards_table/top_boards_table.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, AutoMerge, release-note-none

#11964 [MM-49515] Show board insights for boards 'product'
  components/activity_and_insights/insights/insights.tsx
  components/activity_and_insights/insights/top_boards/top_boards.tsx
  components/activity_and_insights/insights/top_boards/top_boards_table/top_boards_table.tsx
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#11963 [MM-49515] Show board insights for boards 'product'
  components/activity_and_insights/insights/insights.tsx
  components/activity_and_insights/insights/top_boards/top_boards.tsx
  components/activity_and_insights/insights/top_boards/top_boards_table/top_boards_table.tsx
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#11969 Automated cherry pick of #11877
  e2e/cypress/tests/integration/accessibility/accessibility_account_settings_spec.js
  e2e/cypress/tests/integration/enterprise/accessibility/accessibility_input_fields_spec.js
  e2e/cypress/tests/integration/notifications/channel_links_show_as_links_spec.js
  e2e/cypress/tests/support/ui/account_settings_modal.js
  e2e/cypress/tests/support/ui/global_header.js
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#11960 MM-49563 Append query parameter to remote_entry.js files to fix bad caching on community
  webpack.config.js
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#11976 Automated cherry pick of #11960
  webpack.config.js
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#11935 [MM-47964] - Update limits in Cloud Pricing Modal
  components/pricing_modal/content.tsx
  components/pricing_modal/self_hosted_content.tsx
  i18n/en.json
  utils/limits.tsx
Labels: 4: Reviews Complete, Docs/Done, CherryPick/Approved, QA Review Done, AutoMerge, release-note-none

#11981 Automated cherry pick of #11935
  components/pricing_modal/content.tsx
  components/pricing_modal/self_hosted_content.tsx
  i18n/en.json
  utils/limits.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#11965 MM-47938 Ensure feature flag is set before running E2E test
  e2e/cypress/tests/integration/channel/new_channel_with_board_spec.js
  e2e/playwright/support/server/default_config.ts
Labels: 4: Reviews Complete, release-note-none

#11716 [MM-47896] E2E tests for GM and Channel name collision
  e2e/cypress/tests/integration/channel_settings/channel_name_validations_spec.ts
Labels: 4: Reviews Complete, release-note-none

#11816 [MM 48440]: Remove the "Only visible to you" text
  components/rhs_comment/rhs_comment.tsx
  packages/types/src/posts.ts
  utils/constants.tsx
Labels: 4: Reviews Complete, release-note-none

#11813 MM-48567 Made registerChannelIntroButtonAction usable by all plugins
  components/post_view/channel_intro_message/__snapshots__/add_members_button.test.tsx.snap
  components/post_view/channel_intro_message/__snapshots__/channel_intro_message.test.tsx.snap
  components/post_view/channel_intro_message/add_members_button.test.tsx
  components/post_view/channel_intro_message/add_members_button.tsx
  components/post_view/channel_intro_message/channel_intro_message.test.tsx
  components/post_view/channel_intro_message/channel_intro_message.tsx
  components/post_view/channel_intro_message/index.ts
  components/post_view/channel_intro_message/pluggable_intro_buttons/index.ts
  components/post_view/channel_intro_message/pluggable_intro_buttons/pluggable_intro_buttons.tsx
  i18n/en.json
  plugins/registry.ts
  selectors/plugins.ts
Labels: 4: Reviews Complete, release-note, QA Deferred

#11980 Add artificial delay before creating a second team in team_switch_spec
  e2e/cypress/tests/integration/performance/channel_switch_spec.js
  e2e/cypress/tests/integration/performance/team_switch_spec.js
Labels: 2: Dev Review, release-note-none, QA Deferred

#11892 [MM-49391] Add width and height attributes to App bar icons
  components/app_bar/app_bar.scss
Labels: 2: Dev Review, 3: QA Review, release-note-none

#11838 [MM-47800] Dismiss profile popover when opening a modal through keyboard shortcut
  components/profile_popover/__snapshots__/profile_popover.test.tsx.snap
  components/profile_popover/index.ts
  components/profile_popover/profile_popover.test.tsx
  components/profile_popover/profile_popover.tsx
  components/user_group_popover/useShouldClose.ts
  components/user_group_popover/user_group_popover.test.tsx
  components/user_group_popover/user_group_popover.tsx
Labels: Setup Cloud Test Server, release-note-none

#11846 [MM-49179] Global Drafts Onboarding Tour Point
  actions/views/drafts.ts
  components/drafts/drafts_link/__snapshots__/drafts_link.test.tsx.snap
  components/drafts/drafts_link/drafts_link.scss
  components/drafts/drafts_link/drafts_link.test.tsx
  components/drafts/drafts_link/drafts_link.tsx
  components/drafts/drafts_link/drafts_tour_tip/drafts_tour_tip.tsx
  components/sidebar/sidebar_list/sidebar_list.tsx
  e2e/cypress/tests/support/api/preference.d.ts
  e2e/cypress/tests/support/api/preference.js
  e2e/cypress/tests/support/api/user.js
  e2e/cypress/tests/support/index.js
  i18n/en.json
  packages/mattermost-redux/src/constants/preferences.ts
  selectors/drafts.ts
Labels: 4: Reviews Complete, release-note-none

#11994 Automated cherry pick of #11812
  components/global_header/center_controls/user_guide_dropdown/__snapshots__/user_guide_dropdown.test.tsx.snap
  components/global_header/center_controls/user_guide_dropdown/user_guide_dropdown.tsx
  components/global_header/left_controls/product_menu/__snapshots__/product_menu.test.tsx.snap
  components/global_header/left_controls/product_menu/product_menu.tsx
  components/global_header/right_controls/at_mentions_button/__snapshots__/at_mentions_button.test.tsx.snap
  components/global_header/right_controls/at_mentions_button/at_mentions_button.tsx
  components/global_header/right_controls/plan_upgrade_button/index.tsx
  components/global_header/right_controls/saved_posts_button/__snapshots__/saved_posts_button.test.tsx.snap
  components/global_header/right_controls/saved_posts_button/saved_posts_button.tsx
  components/global_header/right_controls/settings_button/settings_button.tsx
  components/status_dropdown/__snapshots__/status_dropdown.test.tsx.snap
  components/status_dropdown/status_dropdown.tsx
  i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#11987 [MM-48394] Wrangler UI/UX tweaks
  components/forward_post_modal/forward_post_modal.scss
  components/move_thread_modal/move_thread_modal.tsx
Labels: release-note-none

#11984 Cypress/E2E: Fix flaky tests
  e2e/cypress/tests/integration/bot_accounts/bot_api_1_spec.js
  e2e/cypress/tests/integration/bot_accounts/bot_api_2_spec.js
  e2e/cypress/tests/integration/bot_accounts/bot_api_not_cloud_spec.js
  e2e/cypress/tests/integration/bot_accounts/bot_channel_intro_spec.js
  e2e/cypress/tests/integration/bot_accounts/create_bot_spec.js
  e2e/cypress/tests/integration/bot_accounts/crud_not_cloud_spec.js
  e2e/cypress/tests/integration/bot_accounts/crud_spec.js
  e2e/cypress/tests/integration/bot_accounts/display_name_spec.js
  e2e/cypress/tests/integration/bot_accounts/edit_bot_spec.js
  e2e/cypress/tests/integration/bot_accounts/edit_bot_username_spec.js
  e2e/cypress/tests/integration/bot_accounts/in_lists_1_spec.js
  e2e/cypress/tests/integration/bot_accounts/in_lists_2_spec.js
  e2e/cypress/tests/integration/bot_accounts/in_teams_and_channels_spec.js
  e2e/cypress/tests/integration/bot_accounts/managing_bot_accounts_not_cloud_spec.js
  e2e/cypress/tests/integration/bot_accounts/post_message_spec.js
  e2e/cypress/tests/integration/bot_accounts/promote_demote_spec.js
  e2e/cypress/tests/integration/bot_accounts/sidebar_display_spec.js
  e2e/cypress/tests/integration/bot_accounts/tags_spec.js
  e2e/cypress/tests/integration/enterprise/bot_accounts/managing_bot_accounts_spec.js
  e2e/cypress/tests/integration/enterprise/system_console/compliance/download_bot_compliance_export_file_spec.js
  e2e/cypress/tests/integration/integrations/builtin_commands/invite_command_spec.js
  e2e/cypress/tests/integration/integrations/integrations_spec.js
  e2e/cypress/tests/integration/keyboard_shortcuts/alt_option_plus_up_down_spec.js
  e2e/cypress/tests/integration/mark_as_unread/bot_post_mark_as_unread_spec.js
  e2e/cypress/tests/integration/messaging/header_not_cloud_spec.js
  e2e/cypress/tests/integration/messaging/message_reply_bot_post_spec.js
  e2e/cypress/tests/integration/multi_team_and_dm/multi_team_join_spec.js
  e2e/cypress/tests/integration/multi_team_and_dm/send_dm_user_no_team_spec.js
  e2e/cypress/tests/integration/performance/team_switch_spec.js
  e2e/cypress/tests/integration/plugins/demo_plugin/helper.js
  e2e/cypress/tests/integration/plugins/demo_plugin/webhook_spec.js
  e2e/cypress/tests/integration/plugins/plugin_buttons_spec.js
  e2e/cypress/tests/integration/system_console/search_box_not_cloud_spec.js
  e2e/cypress/tests/integration/toast/unread_with_bottom_start_toast_spec.js
  e2e/cypress/tests/plugins/post_message_as.js
  e2e/cypress/tests/support/api/bots.d.ts
  e2e/cypress/tests/support/api/bots.js
  e2e/cypress/tests/support/api/plugin.js
  e2e/cypress/tests/support/index.js
  e2e/cypress/tests/utils/plugins.js
Labels: 2: Dev Review, 3: QA Review, release-note-none

#12004 Have Cypress use custom site URL if set
  e2e/cypress/cypress.config.ts
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#10560 Break generated "emoji_data.go" file across multiple lines
  Makefile
  build/emoji/emoji_gen.mjs
Labels: 4: Reviews Complete, release-note-none, Contributor

#12009 fixes build due to merged tag feature
  components/drafts/drafts_link/drafts_tour_tip/drafts_tour_tip.tsx
  components/post_priority/post_priority_badge.tsx
Labels: 4: Reviews Complete, release-note-none, QA Deferred, kind/bug

#12006 Bump product wait timeout to 5 seconds
  webpack.config.js
Labels: 4: Reviews Complete, release-note-none

#9279 Mm 39202 disable run deletion job button when keep forever
  components/admin_console/data_retention_settings/__snapshots__/data_retention_settings.test.tsx.snap
  components/admin_console/data_retention_settings/data_retention_settings.tsx
  components/card/title_and_button_card_header/title_and_button_card_header.tsx
Labels: 4: Reviews Complete, Lifecycle/1:stale, Setup Cloud Test Server, release-note-none

#11855 [MM-48920] Fix updating channel moderation with WS
  packages/mattermost-redux/src/reducers/entities/channels.ts
Labels: 3: QA Review, Setup Cloud Test Server, release-note-none

#11928 Mm 49227
  components/admin_console/license_settings/enterprise_edition/enterprise_edition_left_panel.tsx
  e2e/cypress/tests/integration/enterprise/self-hosted/self_hosted_pricing_modal_spec.ts
  e2e/cypress/tests/integration/enterprise/self-hosted/self_hosted_purchase_spec.ts
Labels: 2: Dev Review, 3: QA Review, release-note-none

#11865 [MM-42529] DM thread does not get disabled when the user is deactivated
  components/threading/virtualized_thread_viewer/virtualized_thread_viewer.tsx
Labels: 3: QA Review, Setup Cloud Test Server, release-note-none

#11872 [MM-48290] Fix white screen when guest is removed from last channel while on Threads
  components/threading/global_threads/thread_item/index.ts
Labels: 3: QA Review, Setup Cloud Test Server, release-note-none

#11553 MM-22896: Update profile popover UI
  components/at_mention/at_mention.test.tsx
  components/at_mention/at_mention.tsx
  components/profile_popover/__snapshots__/profile_popover.test.tsx.snap
  components/profile_popover/index.ts
  components/profile_popover/profile_popover.scss
  components/profile_popover/profile_popover.test.tsx
  components/profile_popover/profile_popover.tsx
  e2e/cypress/tests/integration/account_settings/profile/username_spec.ts
  e2e/cypress/tests/integration/channel_settings/add_users_to_channel_spec.ts
  e2e/cypress/tests/integration/custom_status/custom_status_expiry/custom_status_expiry_2_spec.ts
  e2e/cypress/tests/integration/enterprise/profile_popover/profile_popover_spec.js
  e2e/cypress/tests/integration/integrations/incoming_webhook/inapp_username_profile_override_spec.js
  e2e/cypress/tests/integration/messaging/autocomplete_spec.js
  e2e/cypress/tests/integration/messaging/send_message_via_profile_popover_spec.js
  i18n/en.json
  packages/client/src/client4.ts
  packages/mattermost-redux/src/selectors/entities/common.ts
  plugins/call_button/call_button.scss
  plugins/call_button/call_button.tsx
  sass/components/_popover.scss
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note, Contributor

#12020 MM-49645 - Update Software Evaluation Links to use the new Software And Services License Agreement Link
  components/admin_console/feature_discovery/__snapshots__/feature_discovery.test.tsx.snap
  components/admin_console/feature_discovery/feature_discovery.tsx
  components/admin_console/license_settings/trial_banner/trial_banner.tsx
  components/cloud_start_trial/request_business_email_modal.tsx
  components/feature_restricted_modal/feature_restricted_modal.tsx
  components/learn_more_trial_modal/learn_more_trial_modal_step.tsx
  components/onboarding_tasklist/onboarding_tasklist_completed.tsx
  components/pricing_modal/start_trial_caution.tsx
  components/start_trial_modal/index.tsx
  i18n/bg.json
  i18n/de.json
  i18n/en.json
  i18n/en_AU.json
  i18n/es.json
  i18n/fa.json
  i18n/fr.json
  i18n/hu.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
  i18n/zh-CN.json
  i18n/zh-TW.json
  utils/constants.tsx
Labels: 2: Dev Review, release-note-none, QA Deferred

#12015 MM-49615 - Fix Downgrade Success/Failure Text Alignment
  components/purchase_modal/icon_message.scss
Labels: 2: Dev Review, release-note-none

#12013 Self-hosted purchase tweaks (Mm-49493, MM-49494, MM-49497, MM-49500)
  components/common/hooks/useControlSelfHostedPurchaseModal.ts
  components/pricing_modal/content.scss
  components/purchase_in_progress_modal/index.test.tsx
  components/purchase_in_progress_modal/index.tsx
  components/self_hosted_purchase_modal/self_hosted_purchase_modal.scss
  components/self_hosted_purchase_modal/success_page.tsx
  i18n/en.json
Labels: 2: Dev Review, release-note, QA Deferred

#12032 Self-hosted purchase not available case (for v7.8)
  components/pricing_modal/self_hosted_content.tsx
Labels: 2: Dev Review, CherryPick/Approved, release-note, QA Deferred

#12035 Automated cherry pick of #12032
  components/pricing_modal/self_hosted_content.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#11867 [MM-40111] Reset theme in system console modals
  components/admin_console/admin_console.test.tsx
  components/admin_console/admin_console.tsx
  components/admin_console/index.ts
  components/header_footer_route/header_footer_route.scss
  sass/base/_structure.scss
Labels: 3: QA Review, Setup Cloud Test Server, release-note-none

#12005 Cypress/E2E: Upgrade to cypress@12.3 and other dependencies
  e2e/cypress/cypress.config.ts
  e2e/cypress/package-lock.json
  e2e/cypress/package.json
  e2e/cypress/patches/@testing-library+cypress+9.0.0.patch
  e2e/cypress/tests/integration/bot_accounts/bot_channel_intro_spec.js
  e2e/cypress/tests/integration/bot_accounts/sidebar_display_spec.js
  e2e/cypress/tests/integration/channel/channel_mention_autocomplete_spec.js
  e2e/cypress/tests/integration/channel_sidebar/category_collapsing_spec.ts
  e2e/cypress/tests/integration/collapsed_reply_threads/crt_tour_spec.js
  e2e/cypress/tests/integration/enterprise/system_console/reporting/site_statistics_spec.js
  e2e/cypress/tests/integration/files_and_attachments/cancel_file_upload_spec.js
  e2e/cypress/tests/integration/files_and_attachments/file_preview_audio_spec.js
  e2e/cypress/tests/integration/files_and_attachments/file_preview_generic_spec.js
  e2e/cypress/tests/integration/files_and_attachments/file_preview_image_spec.js
  e2e/cypress/tests/integration/files_and_attachments/file_preview_video_spec.js
  e2e/cypress/tests/integration/files_and_attachments/image_link_preview_new_window_spec.js
  e2e/cypress/tests/integration/files_and_attachments/image_link_preview_spec.js
  e2e/cypress/tests/integration/files_and_attachments/upload_files_spec.js
  e2e/cypress/tests/integration/integrations/message_to_channel_via_slash_command_spec.js
  e2e/cypress/tests/integration/keyboard_shortcuts/keyboard_shortcuts_1_spec.js
  e2e/cypress/tests/integration/keyboard_shortcuts/keyboard_shortcuts_2_spec.js
  e2e/cypress/tests/integration/menus/status_dropdown_spec.js
  e2e/cypress/tests/integration/messaging/autocomplete_spec.js
  e2e/cypress/tests/integration/messaging/long_draft_spec.js
  e2e/cypress/tests/integration/messaging/message_draft_persistance_spec.js
  e2e/cypress/tests/integration/messaging/message_reply_gm_spec.js
  e2e/cypress/tests/integration/messaging/post_pre_header_spec.js
  e2e/cypress/tests/integration/messaging/post_textbox_height_spec.js
  e2e/cypress/tests/integration/messaging/send_message_via_profile_popover_spec.js
  e2e/cypress/tests/integration/multi_team_and_dm/gm_header_spec.js
  e2e/cypress/tests/integration/scroll/fixed_width_spec.js
  e2e/cypress/tests/integration/settings/display/timezone_display_mode_spec.js
  e2e/cypress/tests/support/index.js
Labels: 4: Reviews Complete, release-note-none

#12037 Automated cherry pick of #11967
  components/team_sidebar/components/team_button.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#12040 Automated cherry pick of #12020
  components/admin_console/feature_discovery/__snapshots__/feature_discovery.test.tsx.snap
  components/admin_console/feature_discovery/feature_discovery.tsx
  components/admin_console/license_settings/trial_banner/trial_banner.tsx
  components/cloud_start_trial/request_business_email_modal.tsx
  components/feature_restricted_modal/feature_restricted_modal.tsx
  components/learn_more_trial_modal/learn_more_trial_modal_step.tsx
  components/onboarding_tasklist/onboarding_tasklist_completed.tsx
  components/pricing_modal/start_trial_caution.tsx
  components/start_trial_modal/index.tsx
  i18n/bg.json
  i18n/de.json
  i18n/en.json
  i18n/en_AU.json
  i18n/es.json
  i18n/fa.json
  i18n/fr.json
  i18n/hu.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
  i18n/zh-CN.json
  i18n/zh-TW.json
  utils/constants.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#12042 Automated cherry pick of #11867
  components/admin_console/admin_console.test.tsx
  components/admin_console/admin_console.tsx
  components/admin_console/index.ts
  components/header_footer_route/header_footer_route.scss
  sass/base/_structure.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#12043 Automated cherry pick of #11937
  components/pricing_modal/pricing_modal.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#12033 MM-49632 Correctly count GraphQL requests during performance events
  actions/telemetry_actions.jsx
Labels: 4: Reviews Complete, release-note

#12031 MM-49714 Start Boards product as long as Focalboard is found
  scripts/dev-server.js
  scripts/run.js
  scripts/utils.js
Labels: 4: Reviews Complete, release-note-none

#12045 [MM-49810] Fix UTM params not sent to rudder
  components/root/root.tsx
Labels: 2: Dev Review, Setup Cloud Test Server, release-note-none, QA Deferred

#12017 MM-49617 - Add Contact Support CTA for Downgrade to Starter if the Current Subscription is Yearly
  components/pricing_modal/content.tsx
  e2e/cypress/tests/integration/enterprise/cloud/billing/cloud_pricing_modal_spec.ts
  i18n/en.json
Labels: 2: Dev Review, Setup Cloud Test Server, release-note-none, QA Deferred

#11304 People directory groups page
  components/people/directory/directory.scss
  components/people/directory/directory.tsx
  components/people/directory/people_list/people_list.tsx
  components/people/groups/group_list/group_list.tsx
  components/people/groups/group_list/index.ts
  components/people/groups/groups.tsx
  components/people/people.tsx
  i18n/en.json
  packages/mattermost-redux/src/actions/groups.ts
Labels: release-note-none

#12048 Automated cherry pick of #12045
  components/root/root.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#11920 MM-48325, MM-49501: announcement-bar placement in mobile view
  sass/base/_structure.scss
Labels: 4: Reviews Complete, release-note

#12050 Automated cherry pick of #11920
  sass/base/_structure.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#11966 Add additional debugging information to benchmark tests
  .github/workflows/performance-benchmarks.yml
Labels: 4: Reviews Complete, release-note-none

#11839 [MM-49260] Fixing accessibility issues for insights
  components/activity_and_insights/activity_and_insights_link/activity_and_insights_link.tsx
  components/activity_and_insights/insights/card/__snapshots__/card.test.tsx.snap
  components/activity_and_insights/insights/card/card.tsx
  components/activity_and_insights/insights/least_active_channels/channel_actions_menu/channel_actions_menu.tsx
  components/activity_and_insights/insights/top_threads/top_threads_item/top_threads_item.tsx
  components/activity_and_insights/insights/top_threads/top_threads_table/top_threads_table.tsx
  components/drafts/drafts_link/drafts_link.tsx
  components/threading/global_threads_link/global_threads_link.tsx
  i18n/en.json
Labels: 3: QA Review, release-note-none

#12054 Automated cherry pick of #11839
  components/activity_and_insights/activity_and_insights_link/activity_and_insights_link.tsx
  components/activity_and_insights/insights/card/__snapshots__/card.test.tsx.snap
  components/activity_and_insights/insights/card/card.tsx
  components/activity_and_insights/insights/least_active_channels/channel_actions_menu/channel_actions_menu.tsx
  components/activity_and_insights/insights/top_threads/top_threads_item/top_threads_item.tsx
  components/activity_and_insights/insights/top_threads/top_threads_table/top_threads_table.tsx
  components/drafts/drafts_link/drafts_link.tsx
  components/threading/global_threads_link/global_threads_link.tsx
  i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#11804 Correct inline image container button positions
  components/size_aware_image.jsx
  components/size_aware_image.test.jsx
  e2e/cypress/tests/integration/files_and_attachments/image_link_preview_spec.js
  e2e/cypress/tests/integration/messaging/image_attachment_spec.js
  sass/components/_files.scss
  sass/layout/_markdown.scss
Labels: 4: Reviews Complete, release-note-none, Contributor

#12055 Automated cherry pick of #11804
  components/size_aware_image.jsx
  components/size_aware_image.test.jsx
  e2e/cypress/tests/integration/files_and_attachments/image_link_preview_spec.js
  e2e/cypress/tests/integration/messaging/image_attachment_spec.js
  sass/components/_files.scss
  sass/layout/_markdown.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#11844 MM-47855 - True Up Review Front-End
  actions/hosted_customer.tsx
  components/analytics/system_analytics/system_analytics.tsx
  components/analytics/team_analytics/team_analytics.tsx
  components/analytics/true_up_review.scss
  components/analytics/true_up_review.tsx
  components/common/hooks/useCWSAvailabilityCheck.ts
  e2e/cypress/tests/integration/system_console/true_up_review_spec.js
  i18n/en.json
  packages/client/src/client4.ts
  packages/mattermost-redux/src/action_types/hosted_customer.ts
  packages/mattermost-redux/src/reducers/entities/cloud.ts
  packages/mattermost-redux/src/reducers/entities/hosted_customer.ts
  packages/mattermost-redux/src/selectors/entities/hosted_customer.ts
  packages/mattermost-redux/src/store/initial_state.ts
  packages/types/src/cloud.ts
  packages/types/src/hosted_customer.ts
  utils/constants.tsx
Labels: 2: Dev Review, 3: QA Review, release-note-none

#12030 MM-49764: Fixes truncation of username when not needed
  sass/components/_suggestion-list.scss
Labels: 4: Reviews Complete, release-note-none

#12059 Automated cherry pick of #12030
  sass/components/_suggestion-list.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#12053 Temporarily increase team switch benchmark
  .github/workflows/performance-benchmarks.yml
  e2e/cypress/tests/integration/performance/team_switch_spec.js
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none

#12067 Automated cherry pick of #11884
  components/user_groups_modal/__snapshots__/user_groups_modal.test.tsx.snap
  components/user_groups_modal/user_groups_list/__snapshots__/user_groups_list.test.tsx.snap
  components/user_groups_modal/user_groups_list/user_groups_list.tsx
  components/user_groups_modal/user_groups_modal.scss
  components/user_groups_modal/user_groups_modal.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#12065 Cherry-picking translations
  i18n/bg.json
  i18n/de.json
  i18n/en_AU.json
  i18n/es.json
  i18n/fa.json
  i18n/fr.json
  i18n/hu.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt-BR.json
  i18n/ro.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-CN.json
  i18n/zh-TW.json
Labels: 2: Dev Review, Changelog/Not Needed, Docs/Not Needed, release-note-none, Contributor

#11982 Mm 49611
  actions/cloud.tsx
  components/admin_console/billing/billing_subscriptions/limits.test.tsx
  components/admin_console/billing/billing_subscriptions/limits.tsx
  components/admin_console/billing/plan_details/feature_list.tsx
  components/cloud_usage_modal/index.test.tsx
  components/cloud_usage_modal/lhs_nearing_limit_modal.tsx
  components/cloud_usage_modal/workspace_limits_panel.tsx
  components/common/hooks/useGetHighestThresholdCloudLimit.ts
  components/common/hooks/useGetMultiplesExceededCloudLimit.test.ts
  components/common/hooks/useGetMultiplesExceededCloudLimit.ts
  components/common/hooks/useGetUsage.ts
  components/common/hooks/useGetUsageDeltas.ts
  components/delinquency_modal/freemium_modal.test.tsx
  components/delinquency_modal/freemium_modal.tsx
  components/pricing_modal/downgrade_team_removal_modal/index.tsx
  components/pricing_modal/starter_disclaimer_cta.tsx
  components/widgets/menu/menu_items/useWords.test.tsx
  components/widgets/menu/menu_items/useWords.tsx
  i18n/en.json
  packages/client/src/client4.ts
  packages/mattermost-redux/src/store/initial_state.ts
  packages/types/src/boards.ts
  packages/types/src/cloud.ts
  utils/constants.tsx
  utils/limits.tsx
  utils/limits_test.tsx
  utils/notify_admin_utils.ts
Labels: 4: Reviews Complete, release-note

#12016 [MM-46856] Work Template execution
  components/global_header/left_controls/product_menu/product_menu_list/index.ts
  components/work_templates/components/menu.tsx
  components/work_templates/components/menu/use_case.tsx
  components/work_templates/components/preview.tsx
  components/work_templates/components/preview/section.tsx
  components/work_templates/index.tsx
  images/worktemplates/product_teams/feature_release/board-ma.png
  images/worktemplates/product_teams/feature_release/board-pt.png
  images/worktemplates/product_teams/feature_release/channel.png
  images/worktemplates/product_teams/feature_release/feature_release.png
  images/worktemplates/product_teams/feature_release/integrations.png
  images/worktemplates/product_teams/feature_release/playbook.png
  packages/client/src/client4.ts
  packages/mattermost-redux/src/actions/work_templates.ts
  packages/types/src/work_templates.ts
  selectors/work_template.ts
  webpack.config.js
Labels: 2: Dev Review, QA Review Done, release-note-none

#12022 Fix spurious redirect on playbooks upgrade
  components/team_controller/team_controller.tsx
Labels: 3: QA Review, release-note-none

#12072 [MM-49929] Work templates: allow simple users to list marketplace plugins
  actions/marketplace.ts
  components/work_templates/index.tsx
  packages/client/src/client4.ts
Labels: 2: Dev Review, release-note-none, QA Deferred

#11397 Remove old post components code and update tests
  components/post/index.tsx
  components/post/post_component.tsx
  components/post/post_options.tsx
  components/post/user_profile.tsx
  components/post_view/combined_user_activity_post/index.ts
  components/post_view/post/__snapshots__/post.test.tsx.snap
  components/post_view/post/index.test.ts
  components/post_view/post/index.ts
  components/post_view/post/post.test.tsx
  components/post_view/post/post.tsx
  components/post_view/post_body/index.ts
  components/post_view/post_body/post_body.tsx
  components/post_view/post_list_row/__snapshots__/post_list_row.test.tsx.snap
  components/post_view/post_list_row/post_list_row.test.tsx
  components/post_view/post_list_row/post_list_row.tsx
  components/rhs_comment/__snapshots__/rhs_comment.test.tsx.snap
  components/rhs_comment/index.ts
  components/rhs_comment/rhs_comment.test.tsx
  components/rhs_comment/rhs_comment.tsx
  components/rhs_root_post/__snapshots__/rhs_root_post.test.jsx.snap
  components/rhs_root_post/index.ts
  components/rhs_root_post/rhs_root_post.jsx
  components/rhs_root_post/rhs_root_post.test.jsx
  components/search_results/search_results.tsx
  components/search_results_item/__snapshots__/search_results_item.test.tsx.snap
  components/search_results_item/index.test.ts
  components/search_results_item/index.ts
  components/search_results_item/search_results_item.test.tsx
  components/search_results_item/search_results_item.tsx
  components/threading/virtualized_thread_viewer/reply/reply.tsx
  components/threading/virtualized_thread_viewer/root_post/index.ts
  components/threading/virtualized_thread_viewer/root_post/root_post.tsx
  components/threading/virtualized_thread_viewer/thread_viewer_row.tsx
Labels: release-note

#12044 [MM-49265] Update translations when config is changed
  components/admin_console/admin_definition.jsx
  i18n/en.json
Labels: 3: QA Review, Setup Cloud Test Server, release-note-none

#12036 [MM-48800] Refresh bindings on plugin activation
  actions/websocket_actions.jsx
Labels: 3: QA Review, release-note

#12074 [MM-48003] Work Templates: add telemetry
  components/work_templates/components/customize.tsx
  components/work_templates/components/menu.tsx
  components/work_templates/components/preview.tsx
  components/work_templates/index.tsx
  utils/constants.tsx
Labels: 2: Dev Review, Setup Cloud Test Server, release-note-none, QA Deferred

#12049 MM-49632 Reduce the rate that channels are resynced on focus
  components/team_controller/team_controller.tsx
Labels: 4: Reviews Complete, release-note

#11934 [MM-47407] Fixes: Pdf renderer not rendering all the pages
  components/file_preview_modal/file_preview_modal.scss
  components/pdf_preview.jsx
Labels: 4: Reviews Complete, release-note

#12081 Automated cherry pick of #12022
  components/team_controller/team_controller.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#12083 Automated cherry pick of #11934
  components/file_preview_modal/file_preview_modal.scss
  components/pdf_preview.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#12082 [MM-50007] WorkTemplate: disable "private" button when a template contains a playbook without an enterprise license
  components/work_templates/components/customize.tsx
  components/work_templates/index.tsx
  i18n/en.json
Labels: 2: Dev Review, release-note-none, QA Deferred

#12058 MM-49632 Don't block center channel during team switch
  components/channel_layout/channel_controller.tsx
  components/team_controller/actions/index.test.ts
  components/team_controller/actions/index.ts
  components/team_controller/team_controller.tsx
  packages/mattermost-redux/src/action_types/channels.ts
  packages/mattermost-redux/src/reducers/requests/channels.ts
  packages/mattermost-redux/src/store/initial_state.ts
  packages/types/src/requests.ts
Labels: 4: Reviews Complete, release-note

#12084 Add link to true-up review documentation
  components/analytics/true_up_review.tsx
  i18n/en.json
  utils/constants.tsx
Labels: release-note-none, QA Deferred

#11893 [MM-48788] Fixing style for data retention form selectors
  components/widgets/inputs/dropdown_input_hybrid.scss
Labels: 3: QA Review, Setup Cloud Test Server, release-note-none

#12104 Automated cherry pick of #11985
  NOTICE.txt
  components/admin_console/feature_discovery/feature_discovery.tsx
  components/common/hooks/useOpenCloudPurchaseModal.ts
  components/common/svg_images_components/woman_credit_card_and_laptop_svg.tsx
  components/pricing_modal/card.tsx
  components/pricing_modal/content.tsx
  components/pricing_modal/self_hosted_content.tsx
  components/purchase_modal/index.ts
  components/purchase_modal/purchase.scss
  components/purchase_modal/purchase_modal.tsx
  components/self_hosted_purchase_modal/consequences.tsx
  components/self_hosted_purchase_modal/index.test.tsx
  components/self_hosted_purchase_modal/seats_calculator.tsx
  components/self_hosted_purchase_modal/self_hosted_card.tsx
  components/self_hosted_purchase_modal/self_hosted_purchase_modal.scss
  components/switch_to_yearly_plan_confirm_modal/index.tsx
  components/switch_to_yearly_plan_confirm_modal/switch_to_yearly_plan_confirm_modal.scss
  components/widgets/links/upgrade_link.tsx
  components/yearly_monthly_toggle/index.scss
  components/yearly_monthly_toggle/index.tsx
  e2e/cypress/tests/integration/enterprise/cloud/billing/cloud_pricing_modal_spec.ts
  e2e/cypress/tests/integration/enterprise/cloud/billing/yearly_subscription_spec.js
  i18n/en.json
  package-lock.json
  package.json
  packages/mattermost-redux/src/selectors/entities/preferences.ts
  packages/types/src/config.ts
  utils/constants.tsx
  utils/products.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#11996 [MM-48637] remove the redundant grid spacing for smaller screen
  components/announcement_bar/configuration_bar/__snapshots__/configuration_bar.test.tsx.snap
  components/announcement_bar/configuration_bar/configuration_bar.test.tsx
  components/announcement_bar/configuration_bar/configuration_bar.tsx
  i18n/en.json
Labels: release-note-none, QA Deferred

#11983 MM-49570: fix grid blowout in system console mobile-view
  components/admin_console/admin_console.tsx
  sass/base/_structure.scss
Labels: 4: Reviews Complete, release-note

#12087 Removed unused eslint-disables for no-string-refs
  components/add_user_to_channel_modal/add_user_to_channel_modal.tsx
  components/admin_console/file_upload_setting.jsx
  components/admin_console/license_settings/license_settings.tsx
  components/admin_console/manage_roles_modal/manage_roles_modal.tsx
  components/admin_console/password_settings.jsx
  components/admin_console/plugin_management/plugin_management.tsx
  components/admin_console/push_settings.jsx
  components/admin_console/schema_admin_settings.jsx
  components/admin_console/system_user_detail/system_user_detail.tsx
  components/analytics/doughnut_chart.tsx
  components/analytics/line_chart.tsx
  components/channel_notifications_modal/channel_notifications_modal.tsx
  components/create_team/components/display_name.tsx
  components/create_team/components/team_url/team_url.tsx
  components/file_preview/file_preview.tsx
  components/file_preview_modal/popover_bar/popover_bar.tsx
  components/multiselect/multiselect_list.tsx
  components/post_view/embedded_bindings/embedded_binding/embedded_binding.tsx
  components/post_view/message_attachments/message_attachment/message_attachment.tsx
  components/post_view/reaction_list/reaction_list.tsx
  components/post_view/show_more/show_more.tsx
  components/searchable_channel_list.jsx
  components/team_general_tab/team_general_tab.tsx
  components/user_settings/advanced/user_settings_advanced.tsx
  components/user_settings/display/user_settings_display.tsx
  components/user_settings/general/user_settings_general.tsx
  components/user_settings/security/user_access_token_section/user_access_token_section.tsx
Labels: 4: Reviews Complete, release-note-none
