Repository mattermost/mattermost-webapp, pull requests merged in 2023-03, with the labels that each got.

#12007 [MM-45850]: Migrate dot menu to MUI menu and post reminders
  components/dot_menu/__snapshots__/dot_menu.test.tsx.snap
  components/dot_menu/dot_menu.scss
  components/dot_menu/dot_menu.test.tsx
  components/dot_menu/dot_menu.tsx
  components/dot_menu/dot_menu_empty.test.tsx
  components/dot_menu/dot_menu_mobile.test.tsx
  components/dot_menu/index.ts
  components/dot_menu/post_reminder_submenu.tsx
  components/dot_menu/utils.tsx
  components/menu/menu.tsx
  components/menu/menu_item.tsx
  components/menu/menu_styled.tsx
  components/post_markdown/index.ts
  components/post_markdown/post_markdown.test.tsx
  components/post_markdown/post_markdown.tsx
  components/post_markdown/system_message_helpers.tsx
  components/post_reminder_custom_time_picker_modal/index.ts
  components/post_reminder_custom_time_picker_modal/post_reminder_custom_time_picker_modal.scss
  components/post_reminder_custom_time_picker_modal/post_reminder_custom_time_picker_modal.tsx
  e2e/cypress/tests/integration/accessibility/accessibility_post_spec.js
  e2e/cypress/tests/integration/archived_channel/archive_channel_post_spec.ts
  e2e/cypress/tests/integration/archived_channel/post_menu_spec.ts
  e2e/cypress/tests/integration/keyboard_shortcuts/dot_menu_spec.js
  e2e/cypress/tests/integration/mark_as_unread/helpers.js
  e2e/cypress/tests/integration/message_forwarding/forward_message_from_gm_spec.js
  e2e/cypress/tests/integration/message_forwarding/forward_message_from_private_channel_spec.js
  e2e/cypress/tests/integration/message_forwarding/forward_message_from_public_channel_spec.js
  e2e/cypress/tests/integration/messaging/center_channel_rhs_overlap_spec.js
  e2e/cypress/tests/integration/messaging/channel_and_posts_links_spec.js
  e2e/cypress/tests/integration/messaging/channel_read_after_permalink_spec.js
  e2e/cypress/tests/integration/messaging/message_permalink_spec.js
  e2e/cypress/tests/integration/messaging/message_spec.js
  e2e/cypress/tests/integration/messaging/permalink_loading_indicator_spec.js
  e2e/cypress/tests/integration/messaging/post_header_spec.js
  e2e/cypress/tests/integration/subpath/subpath_channel_routing_spec.js
  e2e/cypress/tests/integration/toast/permalink_post_spec.js
  e2e/cypress/tests/integration/toast/permalink_post_with_new_message_spec.js
  e2e/cypress/tests/support/ui/post.ts
  e2e/cypress/tests/support/ui/post_dropdown_menu.d.ts
  e2e/cypress/tests/support/ui/post_dropdown_menu.js
  i18n/en.json
  packages/client/src/client4.ts
  packages/components/src/generic_modal/generic_modal.tsx
  packages/mattermost-redux/src/actions/posts.ts
  packages/mattermost-redux/src/constants/posts.ts
  packages/types/src/posts.ts
  utils/constants.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note

#12271 [MM-50798]: Fix custom status emoji search issue
  components/custom_status/custom_status_modal.tsx
Labels: 2: Dev Review, CherryPick/Approved, Setup Cloud Test Server, release-note, QA Deferred

#12288 Cherry pick MM-50798 and MM-50321
  components/custom_status/custom_status_modal.tsx
  components/post/user_profile.tsx
  components/post_view/post_header_custom_status/post_header_custom_status.tsx
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#12290 Cherry pick [MM-50475][MM-50775] - Post component fixes
  components/post/post_component.tsx
  package-lock.json
Labels: CherryPick/Approved, release-note-none

#12291 Align post paddings for same user threads not relevant to root
  sass/components/_post.scss
Labels: 2: Dev Review, CherryPick/Approved, release-note-none

#12289 Update subpackage versions to 7.9.0 (#12283)
  package-lock.json
  package.json
  packages/client/package.json
  packages/types/package.json
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, CherryPick/Done, AutoMerge, release-note-none

#12258 MM-50726 Align subscribeCloudSubscription type with the standard ActionResult type
  actions/cloud.tsx
  components/admin_console/billing/delete_workspace/delete_workspace_modal.tsx
  components/cloud_subscribe_with_loading_modal/index.tsx
  components/pricing_modal/content.tsx
  components/purchase_modal/index.ts
  components/purchase_modal/process_payment_setup.tsx
  components/purchase_modal/purchase_modal.tsx
  packages/client/src/client4.ts
Labels: 2: Dev Review, release-note-none, QA Deferred

#12293 Cherry pick of #12291
  sass/components/_post.scss
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#12029 [MM-49745] Telemetry to track team invite links
  components/invitation_modal/invite_view.tsx
  utils/utils.tsx
Labels: release-note-none, telemetry

#12255 [MM-47311] - Migrate /enterprise/profile_popover e2e tests to TypeScript
  e2e/cypress/tests/integration/enterprise/profile_popover/profile_popover_spec.ts
  e2e/cypress/tests/integration/enterprise/profile_popover/profile_popover_spec_user_a_b_spec.ts
Labels: 4: Reviews Complete, release-note-none, Contributor

#12189 [MM-50229] Fix right-click paste for user invites
  components/widgets/inputs/users_emails_input.test.tsx
  components/widgets/inputs/users_emails_input.tsx
Labels: release-note-none

#12292 MM-51000 fix withBackupValue
  components/common/hooks/useGetUsageDeltas.test.ts
  components/common/hooks/useGetUsageDeltas.ts
Labels: 4: Reviews Complete, release-note

#11609 [MM-47391] Upgrade date picker to v8 and making it accessible
  components/custom_status/__snapshots__/custom_status_suggestion.test.tsx.snap
  components/custom_status/__snapshots__/expiry_menu.test.tsx.snap
  components/custom_status/custom_status.scss
  components/custom_status/custom_status_modal.tsx
  components/custom_status/custom_status_suggestion.tsx
  components/custom_status/date_time_input.tsx
  components/custom_status/expiry_menu.tsx
  components/date_picker/date_picker.scss
  components/date_picker/date_picker.tsx
  components/date_picker/index.ts
  components/dnd_custom_time_picker_modal/dnd_custom_time_picker_modal.scss
  components/dnd_custom_time_picker_modal/dnd_custom_time_picker_modal.tsx
  components/dnd_custom_time_picker_modal/index.ts
  components/drafts/draft_actions/__snapshots__/delete_draft_modal.test.tsx.snap
  components/drafts/draft_actions/__snapshots__/send_draft_modal.test.tsx.snap
  components/emoji_picker/emoji_picker_overlay.tsx
  components/new_channel_modal/__snapshots__/new_channel_modal.test.tsx.snap
  components/post_reminder_custom_time_picker_modal/post_reminder_custom_time_picker_modal.scss
  components/post_reminder_custom_time_picker_modal/post_reminder_custom_time_picker_modal.tsx
  components/product_notices_modal/__snapshots__/product_notices.test.tsx.snap
  components/suggestion/search_date_suggestion/search_date_suggestion.tsx
  components/suggestion/suggestion_box/suggestion_box.jsx
  components/suggestion/suggestion_date.tsx
  e2e/cypress/tests/integration/custom_status/custom_status_expiry/custom_status_expiry_3_spec.ts
  e2e/cypress/tests/integration/custom_status/custom_status_expiry/custom_status_expiry_4_spec.ts
  i18n/en.json
  package-lock.json
  package.json
  packages/components/src/generic_modal/generic_modal.tsx
  sass/components/_popover.scss
  sass/responsive/_mobile.scss
  utils/utils.tsx
Labels: 3: QA Review, release-note

#11926 [MM-45003] Don't emit logged in event until mfa setup is complete
  components/logged_in/logged_in.tsx
Labels: 3: QA Review, Lifecycle/frozen, release-note-none

#12294 Update NOTICE.txt
  NOTICE.txt
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#12312 Update NOTICE.txt (7.9)
  NOTICE.txt
Labels: Changelog/Not Needed, Docs/Not Needed, CherryPick/Done, AutoMerge, release-note-none

#12306 [MM-51032]: fix post reminder timezone, DND submenu and post reminder ephemeral message not to respecting user set timezone
  components/dot_menu/post_reminder_submenu.tsx
  components/post_markdown/index.ts
  components/post_markdown/post_markdown.tsx
  components/post_markdown/system_message_helpers.tsx
  components/status_dropdown/status_dropdown.tsx
Labels: CherryPick/Approved, Setup Cloud Test Server, release-note, QA Deferred

#12200 [MM-50414] Allow admins to change own email
  components/admin_console/reset_email_modal/__snapshots__/reset_email_modal.test.tsx.snap
  components/admin_console/reset_email_modal/index.ts
  components/admin_console/reset_email_modal/reset_email_modal.test.tsx
  components/admin_console/reset_email_modal/reset_email_modal.tsx
  components/admin_console/system_users/system_users_dropdown/system_users_dropdown.tsx
  i18n/en.json
Labels: Setup Cloud Test Server, release-note-none

#12193 [MM-50430] Fix Forgot Password link when email login is enabled
  components/login/__snapshots__/login.test.tsx.snap
  components/login/login.tsx
Labels: Setup Cloud Test Server, release-note-none

#12080 MM-49808: Starting call from profile popover will start call in DM
  components/profile_popover/__snapshots__/profile_popover.test.tsx.snap
  components/profile_popover/index.ts
  components/profile_popover/profile_popover.test.tsx
  components/profile_popover/profile_popover.tsx
  components/profile_popover_call_button/index.tsx
  components/profile_popover_call_button/profile_popover_call_button.tsx
  plugins/call_button/call_button.scss
  plugins/call_button/call_button.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, Lifecycle/frozen, release-note, Contributor

#12310 MM-51019 - Add a Feature Flag for In-Product Expansion
  e2e/playwright/support/server/default_config.ts
  packages/types/src/config.ts
Labels: 2: Dev Review, release-note-none, QA Deferred

#12314 cherry-pick-MM-51032
  components/dot_menu/post_reminder_submenu.tsx
  components/post_markdown/index.ts
  components/post_markdown/post_markdown.tsx
  components/post_markdown/system_message_helpers.tsx
  components/status_dropdown/status_dropdown.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#12284 [MM-50284]: Fixes letter spacing on main titles for login and create account screens
  components/login/login.scss
  components/signup/signup.scss
Labels: 2: Dev Review, 3: QA Review, Setup Cloud Test Server, 1: UX Review, release-note-none

#12315 MM-49808 Cherry-pick
  components/profile_popover/__snapshots__/profile_popover.test.tsx.snap
  components/profile_popover/index.ts
  components/profile_popover/profile_popover.test.tsx
  components/profile_popover/profile_popover.tsx
  components/profile_popover_call_button/index.tsx
  components/profile_popover_call_button/profile_popover_call_button.tsx
  plugins/call_button/call_button.scss
  plugins/call_button/call_button.tsx
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#12230 MM-50576 Remove most places where a selector factory isn't reused properly
  components/announcement_bar/overage_users_banner/index.tsx
  components/delinquency_modal/index.ts
  components/dot_menu/index.ts
  components/post/index.tsx
  components/rhs_header_post/index.ts
Labels: 4: Reviews Complete, release-note, QA Deferred

#12251 MM-50417 Fixed centre channel being visible before channels are loaded with GraphQL
  components/team_controller/team_controller.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, QA Review Done, release-note-none

#12286 MM-50803 Fix restore post modal styles applying to other modals
  sass/components/_post.scss
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#12317 Manual Cherry pick MM 50534 release 7.9
  components/announcement_bar/overage_users_banner/overage_users_banner.test.tsx
  components/common/hooks/useExpandOverageUsersCheck.ts
  packages/client/src/client4.ts
  packages/mattermost-redux/src/action_types/cloud.ts
  packages/mattermost-redux/src/actions/cloud.ts
  packages/mattermost-redux/src/reducers/entities/cloud.ts
  packages/types/src/cloud.ts
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#12318 MM-50803 Fix restore post modal styles applying to other modals
  sass/components/_post.scss
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, CherryPick/Done, AutoMerge, release-note-none

#11540 Noted that developer config settings require restart
  components/admin_console/admin_definition.jsx
  i18n/en.json
Labels: 4: Reviews Complete, Lifecycle/frozen, release-note

#12221 [MM-49252] Fix scroll to new messages
  components/advanced_text_editor/advanced_text_editor.tsx
  e2e/cypress/tests/integration/collapsed_reply_threads/unread_spec.js
Labels: Setup Cloud Test Server, release-note-none

#12303 [MM-51008] Fix RHS search result hover for larger text
  sass/components/_post.scss
Labels: CherryPick/Approved, Setup Cloud Test Server, release-note-none

#12324 Cherry pick of #12303
  sass/components/_post.scss
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#12052 [MM-49821] Allow pasting multiple emails into invite modal
  components/invitation_modal/invite_view.tsx
  components/widgets/inputs/users_emails_input.test.tsx
  components/widgets/inputs/users_emails_input.tsx
Labels: Lifecycle/frozen, Setup Cloud Test Server, release-note

#12309 [MM-51031] Fix header text
  components/post/post_component.tsx
  i18n/en.json
Labels: CherryPick/Approved, Setup Cloud Test Server, release-note-none

#12326 Cherry pick of 12309
  components/post/post_component.tsx
  i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#12329 Cherry pick of MM-50281, PR-12269
  components/channel_move_to_sub_menu/index.tsx
  components/menu/menu.tsx
  components/menu/menu_item.tsx
  components/menu/sub_menu.tsx
  components/sidebar/sidebar_category/sidebar_category.tsx
  components/sidebar/sidebar_category/sidebar_category_menu/sidebar_category_menu.tsx
  components/sidebar/sidebar_category/sidebar_category_sorting_menu/sidebar_category_sorting_menu.tsx
  components/sidebar/sidebar_channel/sidebar_channel_menu/sidebar_channel_menu.tsx
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#12264 MM-50308 status in more places
  components/channel_members_rhs/member.tsx
  components/suggestion/at_mention_provider/__snapshots__/at_mention_suggestion.test.tsx.snap
  components/suggestion/at_mention_provider/at_mention_suggestion.tsx
  components/user_list_row/user_list_row.tsx
  components/user_list_row_with_error/user_list_row_with_error.tsx
  sass/components/_suggestion-list.scss
Labels: 3: QA Review, Setup Cloud Test Server, release-note

#11262 MM: 42267: Browse channel UI Update and ability to hide joined channels
  actions/channel_actions.test.ts
  actions/channel_actions.ts
  components/__snapshots__/searchable_channel_list.test.jsx.snap
  components/common/svg_images_components/magnifying_glass_svg.tsx
  components/generic_modal.scss
  components/more_channels/__snapshots__/more_channels.test.tsx.snap
  components/more_channels/__snapshots__/searchable_channel_list.test.jsx.snap
  components/more_channels/index.ts
  components/more_channels/more_channels.scss
  components/more_channels/more_channels.test.tsx
  components/more_channels/more_channels.tsx
  components/more_channels/searchable_channel_list.jsx
  components/more_channels/searchable_channel_list.test.jsx
  components/searchable_channel_list.jsx
  e2e/cypress/tests/integration/channel/archived_channels_1_spec.js
  e2e/cypress/tests/integration/channel/more_channels_spec.js
  e2e/cypress/tests/integration/channel/more_public_channels_spec.js
  e2e/cypress/tests/integration/channel_sidebar/new_channel_dropdown_spec.ts
  e2e/cypress/tests/integration/enterprise/accessibility/accessibility_modals_dialogs_spec.js
  e2e/cypress/tests/integration/enterprise/ldap/ldap_group_sync_spec.js
  i18n/en.json
  packages/components/src/generic_modal/generic_modal.tsx
  sass/components/_channel-invite-modal.scss
  utils/constants.tsx
Labels: Hacktoberfest, 3: QA Review, Setup Cloud Test Server, hacktoberfest-accepted, release-note, Contributor

#12333 MM-51242 : Increase member per page count to 200 in gQL
  actions/channel_queries.ts
Labels: 4: Reviews Complete, release-note-none

#12337 [MM-51009] - Remove redundant CSS rule for timestamps in compact mode (#12331)
  sass/responsive/_tablet.scss
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#12339 Fix typo in e2e test helper function uploadPluginX
  e2e/playwright/support/server/client.ts
Labels: 4: Reviews Complete, release-note-none

#12340 Playwright/E2E: fix storage state path
  e2e/playwright/support/browser_context.ts
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#12362 [MM-49090]: Exclude file count on channel stats api call on from channel header
  actions/global_actions.tsx
  actions/views/rhs.ts
  components/channel_info_rhs/channel_info_rhs.test.tsx
  components/channel_info_rhs/channel_info_rhs.tsx
  components/channel_info_rhs/index.ts
  components/channel_info_rhs/menu.test.tsx
  components/channel_info_rhs/menu.tsx
  packages/client/src/client4.ts
  packages/mattermost-redux/src/actions/channels.ts
Labels: 4: Reviews Complete, release-note

#12316 [Debugbar]: adds search in individual tabs
  components/debugbar/apicalls.tsx
  components/debugbar/components/code.tsx
  components/debugbar/components/index.tsx
  components/debugbar/components/input.tsx
  components/debugbar/components/query.tsx
  components/debugbar/components/time.tsx
  components/debugbar/debugbar.scss
  components/debugbar/debugbar.tsx
  components/debugbar/emailssent.tsx
  components/debugbar/logs.tsx
  components/debugbar/sqlqueries.tsx
  components/debugbar/storecalls.tsx
  components/debugbar/systeminfo.tsx
  packages/mattermost-redux/src/actions/debugbar.ts
  packages/mattermost-redux/src/reducers/entities/debugbar.ts
  packages/mattermost-redux/src/selectors/entities/debugbar.ts
  packages/types/src/debugbar.ts
Labels: release-note-none

#12382 Mm 50952 RFQA can save notifications
  components/admin_console/admin_definition.jsx
  components/admin_console/schema_admin_settings.jsx
Labels: 4: Reviews Complete, release-note-none

#12384 Mm 51287 cherry pick
  components/admin_console/billing/billing_history.test.tsx
  components/admin_console/billing/billing_history.tsx
  utils/constants.tsx
Labels: 2: Dev Review, release-note

#12385 Update NOTICE.txt
  NOTICE.txt
Labels: 4: Reviews Complete, Changelog/Done, AutoMerge, release-note-none

#12388 Cherry pick of mattermost/mattermost-server#22655
  components/post_priority/post_priority_picker.tsx
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#12386 make autolinked board ff false as default
  e2e/playwright/support/server/default_config.ts
  e2e/playwright/tests/visual/channels/intro_channel.spec.ts
Labels: release-note-none
