Repository mattermost/mattermost-webapp, pull requests merged in 2023-06, with the labels that each got.

#12404 [MM-52996] fix server ci after renaming the project
  .github/workflows/ci.yml
  Makefile
  build/emoji/emoji_gen.mjs
Labels: 4: Reviews Complete, release-note-none

#12410 feat(ci): Migrate CircleCI to GHA
  .circleci/config.yml
  .github/workflows/ci.yml
  .github/workflows/performance-benchmarks.yml
Labels: 2: Dev Review, release-note-none, kind/feature

#12408 fix(ci): Fixes for CI
  .github/workflows/ci.yml
Labels: 2: Dev Review, release-note-none, kind/bug

#12409 fix(ci): CI fixes
  .github/workflows/ci.yml
Labels: 2: Dev Review, release-note-none, kind/bug

#12405 Cherrypick 23226 for v7.8
  components/forward_post_modal/forward_post_modal.tsx
  components/post_view/post_body_additional_content/post_body_additional_content.tsx
  components/post_view/post_message_preview/__snapshots__/post_message_preview.test.tsx.snap
  components/post_view/post_message_preview/index.ts
  components/post_view/post_message_preview/post_message_preview.test.tsx
  components/post_view/post_message_preview/post_message_preview.tsx
  packages/mattermost-redux/src/reducers/entities/posts.test.ts
  packages/mattermost-redux/src/reducers/entities/posts.ts
Labels: 4: Reviews Complete, release-note-none

#12406 Cherrypick 23226 for v7.9
  components/forward_post_modal/forward_post_modal.tsx
  components/post_view/post_body_additional_content/post_body_additional_content.tsx
  components/post_view/post_message_preview/__snapshots__/post_message_preview.test.tsx.snap
  components/post_view/post_message_preview/index.ts
  components/post_view/post_message_preview/post_message_preview.test.tsx
  components/post_view/post_message_preview/post_message_preview.tsx
  packages/mattermost-redux/src/reducers/entities/posts.test.ts
  packages/mattermost-redux/src/reducers/entities/posts.ts
Labels: 4: Reviews Complete, release-note-none

#12407 Cherrypick 23226 for v7.10
  components/forward_post_modal/forward_post_modal.tsx
  components/post_view/post_body_additional_content/post_body_additional_content.tsx
  components/post_view/post_message_preview/__snapshots__/post_message_preview.test.tsx.snap
  components/post_view/post_message_preview/index.ts
  components/post_view/post_message_preview/post_message_preview.test.tsx
  components/post_view/post_message_preview/post_message_preview.tsx
  packages/mattermost-redux/src/reducers/entities/posts.test.ts
  packages/mattermost-redux/src/reducers/entities/posts.ts
Labels: 2: Dev Review, release-note-none
