Repository mattermost/mattermost-webapp, pull requests merged in 2023-02, with the labels that each got.

#11962 [MM-49528]- Webapp: remove right-click hijacking on code blocks in messages
  components/code_block/__snapshots__/code_block.test.tsx.snap
  components/code_block/code_block.test.tsx
  components/code_block/code_block.tsx
  e2e/cypress/tests/fixtures/markdown/markdown_carriage_return_two_lines.html
  e2e/cypress/tests/fixtures/markdown/markdown_code_block.html
  e2e/cypress/tests/fixtures/markdown/markdown_not_autolink.html
  e2e/cypress/tests/fixtures/markdown/markdown_not_in_code_block.html
  i18n/de.json
  i18n/en.json
  i18n/en_AU.json
  i18n/es.json
  i18n/fr.json
  i18n/hu.json
  i18n/ja.json
  i18n/nl.json
  i18n/pl.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
  utils/__snapshots__/message_html_to_component.test.jsx.snap
  utils/message_html_to_component.jsx
Labels: 4: Reviews Complete, release-note, Contributor

#12113 Cherry-picking translations
  i18n/de.json
  i18n/en_AU.json
  i18n/es.json
  i18n/fa.json
  i18n/hu.json
  i18n/ja.json
  i18n/nl.json
  i18n/pl.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
  i18n/zh-CN.json
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none, Contributor

#12068 Remove board limits from modals, update text
  components/admin_console/billing/plan_details/feature_list.tsx
  components/pricing_modal/downgrade_team_removal_modal/index.tsx
  i18n/en.json
Labels: 4: Reviews Complete, release-note

#12111 [MM-49974] Fix Spacing Between Timestamp and Draft Tag
  components/drafts/panel/panel_header.scss
Labels: 4: Reviews Complete, CherryPick/Approved, release-note-none

#12117 team edition should not try to contact portal
  components/common/hooks/useCWSAvailabilityCheck.ts
  components/common/hooks/useCanSelfHostedSignup.ts
Labels: CherryPick/Approved, release-note, QA Deferred

#12118 Automated cherry pick of #12111
  components/drafts/panel/panel_header.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#11930 [MM-44302] switch channel: add condition to remove unread styling for archived channels and filter archived channels from local data
  components/suggestion/switch_channel_provider.jsx
Labels: release-note

#12089 MM-49626: Changed the order of Leave Channel and Archive Channel to be the same as in mobile
  components/channel_header_dropdown/__snapshots__/channel_header_dropdown.test.tsx.snap
  components/channel_header_dropdown/channel_header_dropdown_items.tsx
Labels: 4: Reviews Complete, release-note-none, Contributor

#12091 MM-50048 : Remove any unnecessary eslint disables
  build/emoji/emoji_gen.mjs
  components/admin_console/admin_settings.tsx
  components/admin_console/filter/filter.tsx
  components/admin_console/group_settings/group_details/group_details.tsx
  components/admin_console/jobs/job_download_link.tsx
  components/admin_console/license_settings/enterprise_edition/enterprise_edition_left_panel.tsx
  components/admin_console/license_settings/license_settings.tsx
  components/admin_console/team_channel_settings/channel/details/channel_details.tsx
  components/admin_console/team_channel_settings/channel/details/channel_members/channel_members.tsx
  components/admin_console/team_channel_settings/team/details/team_details.tsx
  components/advanced_text_editor/texteditor_actions/texteditor_actions.tsx
  components/channel_selector_modal/channel_selector_modal.tsx
  components/cloud_start_trial/request_business_email_modal.tsx
  components/common/hocs/cloud/with_get_cloud_subscription.tsx
  components/create_team/components/display_name.tsx
  components/delinquency_modal/delinquency_modal_controller.tsx
  components/file_upload/file_upload.tsx
  components/gif_picker/components/SearchGrid/SearchGrid.tsx
  components/help/help_controller.tsx
  components/list_modal.tsx
  components/markdown/markdown.tsx
  components/new_channel_modal/new_channel_modal.tsx
  components/payment_form/card_input.tsx
  components/payment_form/stripe.ts
  components/post_markdown/index.ts
  components/post_markdown/post_markdown.tsx
  components/post_view/post_recent_reactions/post_recent_reactions.tsx
  components/post_view/reaction/reaction.tsx
  components/purchase_modal/purchase_modal.tsx
  components/root/root.tsx
  components/self_hosted_purchase_modal/index.tsx
  components/spinner_button.tsx
  components/suggestion/command_provider/app_command_parser/app_command_parser.ts
  components/team_sidebar/components/team_button.tsx
  components/user_settings/general/user_settings_general.tsx
  components/user_settings/security/user_settings_security.tsx
  packages/client/src/websocket.ts
  packages/components/rollup.config.js
  packages/mattermost-redux/src/actions/posts.ts
  packages/mattermost-redux/src/actions/roles.ts
  packages/mattermost-redux/src/utils/gfycat_sdk.ts
  plugins/pluggable/pluggable.tsx
  root.tsx
  types/external/react-bootstrap.d.ts
  utils/latinise.tsx
  utils/policy_roles_adapter.ts
Labels: 4: Reviews Complete, release-note-none

#12100 [MM-50059] Remove experimental warning about apps
  packages/client/src/client4.ts
  packages/mattermost-redux/src/action_types/apps.ts
  packages/mattermost-redux/src/actions/apps.ts
  packages/mattermost-redux/src/constants/apps.ts
  packages/mattermost-redux/src/reducers/entities/apps.ts
  packages/mattermost-redux/src/selectors/entities/apps.ts
  packages/mattermost-redux/src/utils/marketplace.ts
  packages/types/src/apps.ts
  packages/types/src/marketplace.ts
Labels: 4: Reviews Complete, release-note-none

#12122 Revert "merge in fix to not contact portal if on team edition"
  components/common/hooks/useCanSelfHostedSignup.ts
Labels: release-note-none

#12123 Revert "Revert "merge in fix to not contact portal if on team edition…
  components/common/hooks/useCanSelfHostedSignup.ts
Labels: release-note-none

#12115 [MM-50081] Add work template Onboarding list entry
  actions/views/onboarding_tasks.ts
  components/common/svg_images_components/newspaper_svg.tsx
  components/global_header/left_controls/product_menu/product_menu_list/product_menu_list.tsx
  components/onboarding_tasks/constants.ts
  components/onboarding_tasks/onboarding_tasks_manager.tsx
  components/work_templates/index.tsx
  i18n/en.json
  utils/constants.tsx
Labels: 2: Dev Review, Setup Cloud Test Server, release-note-none, QA Deferred

#12112 [MM-50077] Race condition on work template execution
  actions/views/channel.test.js
  actions/views/channel.ts
  components/work_templates/index.tsx
Labels: 2: Dev Review, Setup Cloud Test Server, release-note-none, QA Deferred

#12114 [MM-50082] Work templates: copy + other tweaks
  components/global_header/left_controls/product_menu/product_menu_list/__snapshots__/product_menu_list.test.tsx.snap
  components/global_header/left_controls/product_menu/product_menu_list/index.ts
  components/global_header/left_controls/product_menu/product_menu_list/product_menu_list.tsx
  components/sidebar/__snapshots__/sidebar.test.tsx.snap
  components/sidebar/add_channel_dropdown.tsx
  components/sidebar/index.ts
  components/sidebar/sidebar.test.tsx
  components/sidebar/sidebar.tsx
  components/sidebar/sidebar_header/sidebar_header.test.tsx
  components/sidebar/sidebar_header/sidebar_header.tsx
  components/work_templates/components/customize.tsx
  components/work_templates/components/preview.tsx
  components/work_templates/components/preview/accordion.tsx
  components/work_templates/index.tsx
  i18n/en.json
  sass/layout/_sidebar-left.scss
Labels: 2: Dev Review, release-note-none, QA Deferred

#12046 Mm 49772
  components/common/hooks/useCanSelfHostedSignup.ts
  components/pricing_modal/self_hosted_content.tsx
  components/self_hosted_purchase_modal/index.tsx
Labels: CherryPick/Approved, release-note, QA Deferred

#12119 cherry-pick MM-50049
  components/common/hooks/useCanSelfHostedSignup.ts
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, release-note

#12131 Automated cherry pick of #12046
  components/common/hooks/useCanSelfHostedSignup.ts
  components/pricing_modal/self_hosted_content.tsx
  components/self_hosted_purchase_modal/index.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#12105 [MM-49943 ] Fixing initial load for insights types on free tier
  components/activity_and_insights/insights/hooks.ts
  components/activity_and_insights/insights/insights.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, release-note-none

#12076 [MM-49863] Check for team Id in product notices
  components/product_notices_modal/product_notices_modal.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, release-note

#12101 Mm 49496 prevent admins whose purchase attempt was screened from immediately retrying
  components/announcement_bar/purchase_link/purchase_link.tsx
  components/common/hooks/useCanSelfHostedSignup.ts
  components/common/hooks/useControlModal.ts
  components/common/svg_images_components/access_denied_happy_svg.tsx
  components/pricing_modal/self_hosted_content.tsx
  components/screening_in_progress_modal/content.scss
  components/screening_in_progress_modal/index.test.tsx
  components/screening_in_progress_modal/index.tsx
  components/self_hosted_purchase_modal/error.tsx
  e2e/cypress/tests/integration/enterprise/self-hosted/self_hosted_purchase_spec.ts
  i18n/en.json
  utils/constants.tsx
Labels: 2: Dev Review, release-note, QA Deferred

#12137 Automated cherry pick of #12076
  components/product_notices_modal/product_notices_modal.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#12138 Automated cherry pick of #12105
  components/activity_and_insights/insights/hooks.ts
  components/activity_and_insights/insights/insights.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#12133 Automated cherry pick of #12105
  components/activity_and_insights/insights/hooks.ts
  components/activity_and_insights/insights/insights.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#12134 Automated cherry pick of #12076
  components/product_notices_modal/product_notices_modal.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#12098 [MM-33593] Inconsistent styling of modal headers in the system console
  sass/components/_modal.scss
Labels: Setup Cloud Test Server, release-note-none

#12140 MM-50295: Fix e2e tests related to clicking username on message posted by bot
  components/post/user_profile.tsx
Labels: 4: Reviews Complete, release-note-none, Contributor

#12146 Automated cherry pick of #12140
  components/post/user_profile.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#11204 MM-47078 : Migrate "components/suggestion/modal_suggestion_list.jsx" to Typescript
  components/apps_form/apps_form_field/apps_form_field.tsx
  components/interactive_dialog/dialog_element/dialog_element.tsx
  components/suggestion/modal_suggestion_list.tsx
Labels: 4: Reviews Complete, release-note-none, Contributor

#12086 Change collapsed post fadeout to use mask-image
  components/post_view/show_more/__snapshots__/show_more.test.tsx.snap
  components/post_view/show_more/show_more.tsx
  e2e/cypress/tests/integration/integrations/incoming_webhook/attachment_does_not_collapse_spec.ts
  e2e/cypress/tests/integration/messaging/collapsed_message_spec.js
  e2e/cypress/tests/integration/messaging/long_post_attachments_spec.js
  sass/components/_post.scss
  utils/utils.tsx
Labels: 4: Reviews Complete, release-note

#12039 [MM-49770] Track "Invite People" (x2) and "Invite Members" links
  components/main_menu/__snapshots__/main_menu.test.tsx.snap
  components/main_menu/main_menu.tsx
  components/post_view/channel_intro_message/add_members_button.tsx
  components/sidebar/__snapshots__/invite_members_button.test.tsx.snap
  components/sidebar/invite_members_button.test.tsx
  components/sidebar/invite_members_button.tsx
  components/sidebar/sidebar_category/__snapshots__/sidebar_category.test.tsx.snap
  components/sidebar/sidebar_category/index.ts
  components/sidebar/sidebar_category/sidebar_category.test.tsx
  components/sidebar/sidebar_category/sidebar_category.tsx
  components/widgets/menu/menu_items/menu_item_toggle_modal_redux.tsx
  plugins/test/__snapshots__/main_menu_action.test.jsx.snap
  tsconfig.json
Labels: Setup Cloud Test Server, release-note-none, telemetry

#12096 [MM-49973] Bot and guest tags truncated on suggestion autocomplete
  sass/components/_suggestion-list.scss
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, release-note-none

#12145 [OSF] Allows opening the work template modal from a slash command
  actions/command.ts
  i18n/en.json
Labels: 2: Dev Review, release-note-none

#12150 Automated cherry pick of #12096
  sass/components/_suggestion-list.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#12149 Automated cherry pick of #12096
  sass/components/_suggestion-list.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#11958 MM48320 - refactor create channel with board from webapp to pluggable
  components/new_channel_modal/new_channel_modal.scss
  components/new_channel_modal/new_channel_modal.tsx
  components/new_channel_modal/new_channel_modal_with_board.test.tsx
  components/new_channel_modal/selectors.ts
  i18n/en.json
  packages/client/src/client4.ts
  packages/mattermost-redux/src/actions/boards.ts
  packages/types/src/boards.ts
  plugins/registry.ts
  reducers/plugins/index.ts
  types/store/plugins.ts
Labels: 4: Reviews Complete, Setup Cloud Test Server, release-note-none, QA Deferred

#12129 chore(flaky): Fix Master Onprem and Cloud tests
  e2e/cypress/tests/integration/bot_accounts/display_name_spec.js
  e2e/cypress/tests/integration/collapsed_reply_threads/replies_spec.js
  e2e/cypress/tests/integration/enterprise/cloud/billing/yearly_subscription_spec.js
  e2e/cypress/tests/integration/enterprise/system_console/reporting/site_statistics_spec.js
Labels: release-note-none

#12148 Fix post component merge errors and bugs
  components/post/index.tsx
  components/post/post_component.tsx
  components/post/user_profile.tsx
  e2e/cypress/tests/support/ui/post.ts
  sass/components/_post.scss
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#12158 Automated cherry pick of #12148
  components/post/index.tsx
  components/post/post_component.tsx
  components/post/user_profile.tsx
  e2e/cypress/tests/support/ui/post.ts
  sass/components/_post.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#11069 MM-45494: Edit message history
  actions/views/rhs.test.ts
  actions/views/rhs.ts
  components/activity_and_insights/activity_and_insights_link/activity_and_insights_link.tsx
  components/apps_form/apps_form_component.test.tsx
  components/drafts/drafts_link/drafts_link.tsx
  components/edit_post/edit_post.tsx
  components/edit_post/index.ts
  components/info_toast/__snapshots__/info_toast.test.tsx.snap
  components/info_toast/info_toast.scss
  components/info_toast/info_toast.test.tsx
  components/info_toast/info_toast.tsx
  components/markdown/index.ts
  components/more_channels/index.ts
  components/more_channels/more_channels.test.tsx
  components/more_channels/more_channels.tsx
  components/post_edit_history/__snapshots__/post_edit_history.test.tsx.snap
  components/post_edit_history/edited_post_item/__snapshots__/edited_post_item.test.tsx.snap
  components/post_edit_history/edited_post_item/edited_post_item.test.tsx
  components/post_edit_history/edited_post_item/edited_post_item.tsx
  components/post_edit_history/edited_post_item/index.ts
  components/post_edit_history/index.ts
  components/post_edit_history/post_edit_history.test.tsx
  components/post_edit_history/post_edit_history.tsx
  components/post_edit_history/restore_post_modal.tsx
  components/post_markdown/post_markdown.tsx
  components/post_view/post_edited_indicator/index.ts
  components/post_view/post_edited_indicator/post_edited_indicator.tsx
  components/post_view/post_message_view/post_message_view.tsx
  components/quick_switch_modal/index.tsx
  components/quick_switch_modal/quick_switch_modal.test.tsx
  components/quick_switch_modal/quick_switch_modal.tsx
  components/search/index.tsx
  components/sidebar/index.ts
  components/sidebar/sidebar.test.tsx
  components/sidebar/sidebar.tsx
  components/sidebar/sidebar_channel/sidebar_channel_link/index.ts
  components/sidebar/sidebar_channel/sidebar_channel_link/sidebar_channel_link.test.tsx
  components/sidebar/sidebar_channel/sidebar_channel_link/sidebar_channel_link.tsx
  components/sidebar_right/index.ts
  components/sidebar_right/sidebar_right.tsx
  components/threading/global_threads_link/global_threads_link.tsx
  e2e/cypress/tests/integration/messaging/message_edit_post_history_spec.ts
  i18n/en.json
  packages/client/src/client4.ts
  packages/mattermost-redux/src/action_types/posts.ts
  packages/mattermost-redux/src/actions/posts.test.js
  packages/mattermost-redux/src/actions/posts.ts
  packages/mattermost-redux/src/reducers/entities/posts.test.ts
  packages/mattermost-redux/src/reducers/entities/posts.ts
  packages/mattermost-redux/src/store/initial_state.ts
  packages/types/src/posts.ts
  reducers/views/rhs.ts
  sass/components/_post.scss
  selectors/posts.ts
  utils/constants.tsx
Labels: QA Review Done, release-note, Contributor

#12141 [MM-50306] - Clickable username in RHS
  components/channel_members_rhs/member.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, AutoMerge, release-note

#11938 [MM-48499] Custom Emoji delete modal does not use theme properly
  components/emoji/emoji_page.tsx
  components/emoji/index.ts
Labels: 3: QA Review, Setup Cloud Test Server, release-note-none

#12124 bugfix: MM-49854
  components/post_priority/post_priority_badge.tsx
  components/threading/global_threads/thread_item/__snapshots__/thread_item.test.tsx.snap
  components/threading/global_threads/thread_item/thread_item.scss
  components/threading/global_threads/thread_item/thread_item.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, QA Review Done, AutoMerge, release-note-none, kind/bug

#12163 Automated cherry pick of #12124
  components/post_priority/post_priority_badge.tsx
  components/threading/global_threads/thread_item/__snapshots__/thread_item.test.tsx.snap
  components/threading/global_threads/thread_item/thread_item.scss
  components/threading/global_threads/thread_item/thread_item.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#12107 MM-49088: fixes file uploading state
  components/advanced_create_comment/advanced_create_comment.tsx
  components/advanced_create_post/advanced_create_post.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#12162 Automated cherry pick of #12124
  components/post_priority/post_priority_badge.tsx
  components/threading/global_threads/thread_item/__snapshots__/thread_item.test.tsx.snap
  components/threading/global_threads/thread_item/thread_item.scss
  components/threading/global_threads/thread_item/thread_item.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#12120 MM-49976: Fix tag, custom status position in channel switcher
  components/suggestion/switch_channel_provider.jsx
  sass/components/_suggestion-list.scss
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#12164 Automated cherry pick of #12107
  components/advanced_create_comment/advanced_create_comment.tsx
  components/advanced_create_post/advanced_create_post.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#12063 MM-38465 Add Discard Modal for Company Information Edit
  components/admin_console/billing/company_info_edit.tsx
Labels: QA Review Done, Setup Cloud + CWS Test Server, release-note-none

#12155 MM-58280: Don't show the message count for all posts in a thread if CRT is disabled.
  components/post/post_options.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, release-note

#12168 Automated cherry pick of #12155
  components/post/post_options.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#12171 Automated cherry pick of #11930
  components/suggestion/switch_channel_provider.jsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#12173 Automated cherry pick of #12120
  components/suggestion/switch_channel_provider.jsx
  sass/components/_suggestion-list.scss
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#12094 MM-49868: Remove OpenId-custom free feature from cloud starter
  components/admin_console/admin_definition.jsx
  components/admin_console/feature_discovery/features/index.ts
  components/admin_console/feature_discovery/features/openid_custom.tsx
  components/admin_console/schema_admin_settings.jsx
  i18n/en.json
  utils/constants.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud + CWS Test Server, release-note

#12175 Automated cherry pick of #12094
  components/admin_console/admin_definition.jsx
  components/admin_console/feature_discovery/features/index.ts
  components/admin_console/feature_discovery/features/openid_custom.tsx
  components/admin_console/schema_admin_settings.jsx
  i18n/en.json
  utils/constants.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#12153 Fix React warnings about missing keys for Markdown elements
  utils/message_html_to_component.jsx
Labels: 4: Reviews Complete, release-note-none

#12166 Mm 47276
  utils/post_utils.test.tsx
  utils/test_helper.ts
Labels: 2: Dev Review, release-note-none

#12128 MM-50073 : Infinite recursion when opening New Category modal from Channel Move To menu
  components/__snapshots__/generic_modal.test.tsx.snap
  components/delete_category_modal/delete_category_modal.tsx
  components/edit_category_modal/edit_category_modal.tsx
  components/menu/menu.tsx
  components/more_direct_channels/__snapshots__/more_direct_channels.test.tsx.snap
  components/more_direct_channels/more_direct_channels.tsx
  packages/components/src/generic_modal/generic_modal.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, QA Review Done, release-note-none

#12176 Automated cherry pick of #12128
  components/__snapshots__/generic_modal.test.tsx.snap
  components/delete_category_modal/delete_category_modal.tsx
  components/edit_category_modal/edit_category_modal.tsx
  components/menu/menu.tsx
  components/more_direct_channels/__snapshots__/more_direct_channels.test.tsx.snap
  components/more_direct_channels/more_direct_channels.tsx
  packages/components/src/generic_modal/generic_modal.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#12167 [MM-50349] Add Feature Flag to Disable Tour Tips
  components/post/index.tsx
  components/post/post_component.tsx
  components/post/post_options.tsx
  components/rhs_header_post/index.ts
  packages/mattermost-redux/src/selectors/entities/preferences.ts
  selectors/drafts.ts
Labels: 4: Reviews Complete, CherryPick/Approved, QA Review Done, AutoMerge, release-note-none

#12177 Automated cherry pick of #12167
  components/post/index.tsx
  components/post/post_component.tsx
  components/post/post_options.tsx
  components/rhs_header_post/index.ts
  packages/mattermost-redux/src/selectors/entities/preferences.ts
  selectors/drafts.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#12180 Feature flag to disable the drafts tour tip
  components/rhs_header_post/index.ts
  packages/mattermost-redux/src/selectors/entities/preferences.ts
  selectors/drafts.ts
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#12027 [MM-49744] Telemetry to track click on "Join Now" button
  components/invitation_modal/invite_view.tsx
  components/signup/signup.tsx
  utils/utils.tsx
Labels: 3: QA Review, release-note-none

#12178 Cherry-picking translations from master
  i18n/bg.json
  i18n/de.json
  i18n/en_AU.json
  i18n/es.json
  i18n/fa.json
  i18n/fr.json
  i18n/hu.json
  i18n/it.json
  i18n/ja.json
  i18n/ko.json
  i18n/nl.json
  i18n/pl.json
  i18n/ru.json
  i18n/sv.json
  i18n/tr.json
  i18n/zh-CN.json
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none, Contributor

#12161 MM-50078-unable-to-click-the-create-button-after-fixing-the-name-of-the-work-template
  components/work_templates/index.tsx
Labels: 2: Dev Review, Setup Cloud Test Server, QA Review Done, release-note-none

#12144 MM-49503 - Show in-app Pricing Modal in Edition & License After a License is Uploaded
  components/admin_console/license_settings/enterprise_edition/enterprise_edition.scss
  components/admin_console/license_settings/enterprise_edition/enterprise_edition_left_panel.test.tsx
  components/admin_console/license_settings/enterprise_edition/enterprise_edition_left_panel.tsx
Labels: QA Review Done, release-note-none

#11923 [MM-48029] add notify admin for work template integrations
  components/activity_and_insights/insights/insights_title/insights_title.tsx
  components/announcement_bar/notify_admin_downgrade_delinquency_bar/index.tsx
  components/center_message_lock/index.tsx
  components/common/hooks/useGetNotifyAdmin.ts
  components/custom_open_plugin_install_post_renderer/index.tsx
  components/custom_open_pricing_modal_post_renderer/index.tsx
  components/file_limit_sticky_banner/index.tsx
  components/global_header/left_controls/product_menu/product_menu_list/product_menu_list.tsx
  components/invitation_modal/invite_as.tsx
  components/main_menu/main_menu.tsx
  components/notify_admin_cta/notify_admin_cta.tsx
  components/pricing_modal/content.tsx
  components/root/root.tsx
  components/widgets/menu/menu_items/useWords.tsx
  components/work_templates/components/preview.tsx
  components/work_templates/components/preview/section.tsx
  i18n/en.json
  utils/constants.tsx
  utils/notify_admin_utils.ts
Labels: QA Review Done, 1: UX Review, release-note-none

#12143 Fix Docker images not being built for cloud-* branches
  .circleci/config.yml
Labels: 4: Reviews Complete, release-note-none

#12188 Automated cherry pick of #12127
  package-lock.json
  package.json
  packages/components/package.json
  packages/components/src/focus_trap/index.tsx
  packages/components/src/index.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#12154 MM-50323 : Autofocus on custom status modal on open
  components/custom_status/custom_status_modal.tsx
  components/forward_post_modal/forward_post_modal.tsx
  components/tours/crt_tour/collapsed_reply_threads_modal/collapsed_reply_threads_modal.tsx
Labels: 4: Reviews Complete, release-note-none

#12108 MM-48246 - AB test open RHS with linked board
  components/onboarding_tasklist/onboarding_tasklist.tsx
  components/onboarding_tasks/constants.ts
  components/search_results_header/search_results_header.test.tsx
  components/search_results_header/search_results_header.tsx
  i18n/en.json
  packages/components/src/tour_tip/tour_tip.scss
  packages/mattermost-redux/src/actions/boards.ts
  packages/mattermost-redux/src/constants/preferences.ts
  packages/mattermost-redux/src/selectors/entities/preferences.ts
  plugins/rhs_plugin/auto_show_linked_board_tourtip.tsx
  plugins/rhs_plugin/index.js
  plugins/rhs_plugin/rhs_plugin.jsx
  selectors/plugins.ts
Labels: 2: Dev Review, Setup Cloud + CWS Test Server, release-note-none, QA Deferred

#12187 [MM-50080] Limit max length for the name field
  components/work_templates/components/customize.tsx
Labels: 2: Dev Review, Setup Cloud Test Server, QA Review Done, release-note-none

#12156 MM-50296: fixes click to open thread
  components/post/post_component.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, QA Review Done, release-note-none

#12195 chore(cypress): demote workspace_deletion_spec test
  e2e/cypress/tests/integration/system_console/workspace_deletion_spec.js
Labels: release-note-none

#12184 Fix C# syntax highlighting
  utils/constants.tsx
Labels: 4: Reviews Complete, release-note

#12102 [MM-49921] Cloud export compliance
  actions/cloud.tsx
  components/admin_console/billing/billing_history.scss
  components/admin_console/billing/delete_workspace/delete_workspace_modal.tsx
  components/payment_form/address_form.tsx
  components/payment_form/payment_form.scss
  components/purchase_modal/icon_message.scss
  components/purchase_modal/index.ts
  components/purchase_modal/process_payment_setup.tsx
  components/purchase_modal/purchase.scss
  components/purchase_modal/purchase_modal.tsx
  i18n/en.json
  packages/client/src/client4.ts
  packages/types/src/cloud.ts
  utils/utils.tsx
Labels: 4: Reviews Complete, release-note-none, QA Deferred

#12090 [MM-47074] : Migrate "components/suggestion/generic_channel_provider.jsx" to Typescript
  actions/channel_actions.ts
  components/interactive_dialog/dialog_element/dialog_element.tsx
  components/post_view/message_attachments/action_menu/action_menu.tsx
  components/suggestion/generic_channel_provider.tsx
Labels: 4: Reviews Complete, QA Review Done, release-note-none, Contributor

#11181 Admin log table
  components/admin_console/admin_console.tsx
  components/admin_console/data_grid/data_grid.tsx
  components/admin_console/data_grid/data_grid_search.tsx
  components/admin_console/data_retention_settings/channel_list/channel_list.tsx
  components/admin_console/full_log_event_modal/full_log_event_modal.tsx
  components/admin_console/full_log_event_modal/index.ts
  components/admin_console/server_logs/index.ts
  components/admin_console/server_logs/log_list.scss
  components/admin_console/server_logs/log_list.tsx
  components/admin_console/server_logs/logs.tsx
  components/admin_console/user_grid/user_grid.tsx
  e2e/cypress/tests/integration/system_console/reporting/server_logs_spec.js
  i18n/en.json
  packages/client/src/client4.ts
  packages/mattermost-redux/src/actions/admin.test.js
  packages/mattermost-redux/src/actions/admin.ts
  packages/mattermost-redux/src/selectors/entities/admin.ts
  packages/types/src/admin.ts
  sass/routes/_admin-console.scss
Labels: 2: Dev Review, Setup Cloud Test Server, release-note

#12204 Revert "[feat] Addition of CD workflow"
  .github/workflows/cd.yml
Labels: release-note-none

#12205 Automated cherry pick of #12107
  components/advanced_create_comment/advanced_create_comment.tsx
  components/advanced_create_post/advanced_create_post.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#11822 Remove user id from bindings request
  actions/apps.ts
  components/actions_menu/actions_menu.test.tsx
  components/actions_menu/actions_menu.tsx
  components/actions_menu/actions_menu_empty.test.tsx
  components/actions_menu/actions_menu_mobile.test.tsx
  components/actions_menu/index.ts
  packages/client/src/client4.ts
  packages/mattermost-redux/src/actions/apps.ts
Labels: 4: Reviews Complete, release-note-none

#12201 Fix post component date separator and mobile view
  components/post/post_component.tsx
  components/post/post_options.tsx
  sass/components/_post.scss
  sass/components/_search.scss
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, Setup Cloud Test Server, AutoMerge, release-note

#12208 MM-50506 Add -webkit-mask-image to support Chrome and Electron
  sass/components/_post.scss
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note, QA Deferred

#12207 MM-50226 Remove 'here' from the true-up docs link.
  components/analytics/true_up_review.tsx
  i18n/en.json
Labels: 2: Dev Review, release-note-none, QA Deferred

#12092 Playwright/E2E: Upgrade dependencies and test app, and add form-data to packages/client
  NOTICE.txt
  e2e/playwright/README.md
  e2e/playwright/global_setup.ts
  e2e/playwright/package-lock.json
  e2e/playwright/package.json
  e2e/playwright/support/server/client.ts
  e2e/playwright/support/server/default_config.ts
  e2e/playwright/support/server/init.ts
  e2e/playwright/support/ui/page/login.ts
  e2e/playwright/support/ui/style.ts
  e2e/playwright/tests/visual/intro_channel.spec.ts
  e2e/playwright/tests/visual/intro_channel.spec.ts-snapshots/intro-to-channel-as-regular-user-chrome-linux.png
  e2e/playwright/tests/visual/intro_channel.spec.ts-snapshots/intro-to-channel-as-regular-user-firefox-linux.png
  e2e/playwright/tests/visual/intro_channel.spec.ts-snapshots/intro-to-channel-as-regular-user-ipad-linux.png
  e2e/playwright/tests/visual/intro_channel.spec.ts-snapshots/intro-to-channel-as-regular-user-iphone-linux.png
  e2e/playwright/tests/visual/landing_page.spec.ts-snapshots/landing-login-chrome-linux.png
  e2e/playwright/tests/visual/landing_page.spec.ts-snapshots/landing-login-firefox-linux.png
  e2e/playwright/tests/visual/landing_page.spec.ts-snapshots/landing-login-ipad-linux.png
  e2e/playwright/tests/visual/landing_page.spec.ts-snapshots/landing-login-iphone-linux.png
  e2e/playwright/tests/visual/login.spec.ts-snapshots/login-chrome-linux.png
  e2e/playwright/tests/visual/login.spec.ts-snapshots/login-error-chrome-linux.png
  e2e/playwright/tests/visual/login.spec.ts-snapshots/login-error-firefox-linux.png
  e2e/playwright/tests/visual/login.spec.ts-snapshots/login-error-ipad-linux.png
  e2e/playwright/tests/visual/login.spec.ts-snapshots/login-error-iphone-linux.png
  e2e/playwright/tests/visual/login.spec.ts-snapshots/login-firefox-linux.png
  e2e/playwright/tests/visual/login.spec.ts-snapshots/login-ipad-linux.png
  e2e/playwright/tests/visual/login.spec.ts-snapshots/login-iphone-linux.png
  e2e/playwright/tests/visual/signup_email.spec.ts-snapshots/signup-email-chrome-linux.png
  e2e/playwright/tests/visual/signup_email.spec.ts-snapshots/signup-email-error-chrome-linux.png
  e2e/playwright/tests/visual/signup_email.spec.ts-snapshots/signup-email-error-firefox-linux.png
  e2e/playwright/tests/visual/signup_email.spec.ts-snapshots/signup-email-error-ipad-linux.png
  e2e/playwright/tests/visual/signup_email.spec.ts-snapshots/signup-email-error-iphone-linux.png
  e2e/playwright/tests/visual/signup_email.spec.ts-snapshots/signup-email-firefox-linux.png
  e2e/playwright/tests/visual/signup_email.spec.ts-snapshots/signup-email-ipad-linux.png
  e2e/playwright/tests/visual/signup_email.spec.ts-snapshots/signup-email-iphone-linux.png
  e2e/playwright/tsconfig.json
  package-lock.json
  packages/client/package.json
  packages/client/src/client4.ts
  packages/types/package.json
  packages/types/src/config.ts
Labels: 4: Reviews Complete, AutoMerge, release-note-none

#12214 fix: docker build tag
  .github/workflows/ci.yml
Labels: 4: Reviews Complete, release-note-none

#12215 [CLD-5125] CI Bump-Up runners for Performance Testing
  .github/workflows/performance-benchmarks.yml
Labels: release-note-none

#12198 Add onModalDismissed to plugin file preview
  components/file_preview_modal/__snapshots__/file_preview_modal.test.tsx.snap
  components/file_preview_modal/file_preview_modal.tsx
  types/store/plugins.ts
Labels: 3: QA Review, release-note-none

#12212 Change webpack output for Boards from red to blue
  scripts/utils.js
Labels: 4: Reviews Complete, release-note-none

#11707 Apps - Allow call response "navigate" on apps modal form submit
  components/apps_form/apps_form_container.tsx
Labels: 3: QA Review, release-note-none

#12222 Automated cherry pick of #12215
  .github/workflows/performance-benchmarks.yml
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#12223 Automated cherry pick of #11707
  components/apps_form/apps_form_container.tsx
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#12224 Automated cherry pick of #12209
  components/admin_console/billing/plan_details/plan_details.tsx
  i18n/en.json
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#12226 chore(cypress): fix cloud tests
  e2e/cypress/tests/integration/channel_sidebar/dm_gm_filtering_sorting_spec.ts
  e2e/cypress/tests/integration/enterprise/cloud/billing/company_information_free_trial_spec.ts
  e2e/cypress/tests/integration/enterprise/cloud/billing/notify_admin_spec.ts
  e2e/cypress/tests/integration/enterprise/profile_popover/profile_popover_spec.js
Labels: 4: Reviews Complete, release-note-none

#12235 [CLD-5125] CI Revisit performance benchs sizing
  .github/workflows/performance-benchmarks.yml
Labels: release-note-none

#12217 MM-50572 - Allow Enterprise-Monthly to See Contact Support CTA Rather Than a Blank Section
  components/admin_console/billing/billing_subscriptions/index.tsx
  e2e/cypress/tests/integration/system_console/workspace_deletion_spec.js
Labels: CherryPick/Approved, release-note-none

#12238 Automated cherry pick of #12217
  components/admin_console/billing/billing_subscriptions/index.tsx
  e2e/cypress/tests/integration/system_console/workspace_deletion_spec.js
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#12239 Automated cherry pick of #12218
  components/common/hooks/useControlSelfHostedPurchaseModal.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#12240 Automated cherry pick of #12226
  e2e/cypress/tests/integration/channel_sidebar/dm_gm_filtering_sorting_spec.ts
  e2e/cypress/tests/integration/enterprise/cloud/billing/company_information_free_trial_spec.ts
  e2e/cypress/tests/integration/enterprise/cloud/billing/notify_admin_spec.ts
  e2e/cypress/tests/integration/enterprise/profile_popover/profile_popover_spec.js
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#12241 Automated cherry pick of #12235
  .github/workflows/performance-benchmarks.yml
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#12242 MM-50723 quick fix for subscribing to a cloud product so that successes display as successes.
  actions/cloud.tsx
  components/purchase_modal/index.ts
Labels: 4: Reviews Complete, CherryPick/Approved, AutoMerge, release-note-none, QA Deferred

#12243 Automated cherry pick of #12242
  actions/cloud.tsx
  components/purchase_modal/index.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, AutoMerge, release-note-none

#12179 MM-49474 - Collect Reason for Downgrade to Free
  components/admin_console/billing/delete_workspace/delete_workspace_modal.tsx
  components/cloud_subscribe_with_loading_modal/index.tsx
  components/feedback_modal/downgrade_feedback.tsx
  components/feedback_modal/feedback.tsx
  components/pricing_modal/content.tsx
  components/pricing_modal/downgrade_team_removal_modal/index.tsx
  components/purchase_modal/index.ts
  components/purchase_modal/process_payment_setup.tsx
  components/purchase_modal/purchase_modal.tsx
  e2e/cypress/tests/integration/enterprise/cloud/billing/cloud_pricing_modal_spec.ts
  e2e/cypress/tests/integration/enterprise/cloud/billing/downgrade_feedback_modal_spec.ts
Labels: Setup Cloud + CWS Test Server, release-note, QA Deferred

#11989 [MM-47478] - Tall single images aren't scaled properly
  components/single_image_view/single_image_view.tsx
Labels: 4: Reviews Complete, Setup Cloud Test Server, QA Review Done, release-note, Contributor

#11325 [MM-47369] Remove mention counts of muted channels on the browser and desktop tabs
  packages/mattermost-redux/src/selectors/entities/channels.test.ts
  packages/mattermost-redux/src/selectors/entities/channels.ts
Labels: Setup Cloud Test Server, QA Review Done, release-note-none

#11949 [MM-46944] : Tighten up spaces between categories in the LHS
  components/sidebar/sidebar_category/__snapshots__/sidebar_category.test.tsx.snap
  components/sidebar/sidebar_category/sidebar_category.tsx
  sass/layout/_sidebar-left.scss
Labels: Setup Cloud Test Server, QA Review Done, release-note, Contributor

#12170 Added telemetry, test and bug fix for true up notifications
  components/analytics/true_up_review.test.tsx
  components/analytics/true_up_review.tsx
  components/announcement_bar/overage_users_banner/index.tsx
  components/announcement_bar/overage_users_banner/overage_users_banner.test.tsx
  components/common/hooks/useExpandOverageUsersCheck.ts
  components/invitation_modal/overage_users_banner_notice/index.tsx
  components/invitation_modal/overage_users_banner_notice/overage_users_banner_notice.test.tsx
  e2e/cypress/tests/integration/enterprise/overage_users/error_overage_users_spec.ts
  i18n/en.json
  utils/license_utils.ts
Labels: 3: QA Review, Setup Cloud Test Server, release-note

#12247 Automated cherry pick of #12170
  components/analytics/true_up_review.test.tsx
  components/analytics/true_up_review.tsx
  components/announcement_bar/overage_users_banner/index.tsx
  components/announcement_bar/overage_users_banner/overage_users_banner.test.tsx
  components/common/hooks/useExpandOverageUsersCheck.ts
  components/invitation_modal/overage_users_banner_notice/index.tsx
  components/invitation_modal/overage_users_banner_notice/overage_users_banner_notice.test.tsx
  e2e/cypress/tests/integration/enterprise/overage_users/error_overage_users_spec.ts
  i18n/en.json
  utils/license_utils.ts
Labels: Changelog/Not Needed, Docs/Not Needed, AutomatedCherryPick, release-note-none

#12227 MM-50573 Clean up WebSocket listeners when connection is closed
  actions/websocket_actions.jsx
  actions/websocket_actions.test.jsx
  components/team_controller/team_controller.tsx
  packages/client/src/websocket.ts
Labels: 4: Reviews Complete, release-note, QA Deferred

#12249 Cherry-picking translations
  i18n/de.json
  i18n/fa.json
  i18n/nl.json
  i18n/pl.json
  i18n/ru.json
  i18n/sv.json
  i18n/uk.json
  i18n/vi.json
  i18n/zh-TW.json
Labels: 4: Reviews Complete, Changelog/Not Needed, Docs/Not Needed, AutoMerge, release-note-none

#12244 clear limits on subscription change
  components/common/hooks/useGetLimits.ts
  packages/mattermost-redux/src/reducers/entities/cloud.test.ts
  packages/mattermost-redux/src/reducers/entities/cloud.ts
Labels: 4: Reviews Complete, release-note, QA Deferred

#12259 clear limits on subscription change (#12244)
  components/common/hooks/useGetLimits.ts
  packages/mattermost-redux/src/reducers/entities/cloud.test.ts
  packages/mattermost-redux/src/reducers/entities/cloud.ts
Labels: release-note

#12229 MM-50238 - Add a Success Page for Changes to Annual Subscriptions.
  components/purchase_modal/process_payment_setup.tsx
  components/purchase_modal/purchase_modal.tsx
  i18n/en.json
Labels: release-note-none, QA Deferred

#12228 Convert utils tests to TypeScript
  packages/mattermost-redux/src/utils/channel_utils.test.js
  packages/mattermost-redux/src/utils/channel_utils.test.ts
  packages/mattermost-redux/src/utils/emoji_utils.test.ts
  packages/mattermost-redux/src/utils/file_utils.test.js
  packages/mattermost-redux/src/utils/file_utils.test.ts
  packages/mattermost-redux/src/utils/helpers.test.ts
  packages/mattermost-redux/src/utils/i18n_utils.test.ts
  packages/mattermost-redux/src/utils/integration_utils.test.js
  packages/mattermost-redux/src/utils/integration_utils.test.ts
  packages/mattermost-redux/src/utils/notify_props.test.js
  packages/mattermost-redux/src/utils/notify_props.test.ts
  packages/mattermost-redux/src/utils/post_list.test.ts
  packages/mattermost-redux/src/utils/post_utils.test.js
  packages/mattermost-redux/src/utils/post_utils.test.ts
  packages/mattermost-redux/src/utils/theme_utils.test.ts
  packages/mattermost-redux/src/utils/user_utils.test.js
  packages/mattermost-redux/src/utils/user_utils.test.ts
  packages/mattermost-redux/test/test_helper.ts
  utils/channel_utils.test.ts
  utils/emoji_utils.test.tsx
  utils/file_utils.test.ts
  utils/markdown/helpers.test.ts
  utils/markdown/index.test.ts
  utils/notifications.test.ts
  utils/notifications.ts
  utils/policy_roles_adapter.test.ts
  utils/route.test.ts
  utils/team_utils.test.ts
  utils/test_helper.ts
  utils/text_formatting.test.ts
  utils/text_formatting.tsx
  utils/text_formatting_at_mentions.test.jsx
  utils/text_formatting_at_mentions.test.ts
  utils/text_formatting_channel_links.test.ts
  utils/text_formatting_email.test.ts
  utils/text_formatting_hashtags.test.ts
  utils/text_formatting_imgs.test.ts
  utils/text_formatting_links.test.ts
  utils/text_formatting_mention_highlighting.test.ts
  utils/text_formatting_search_highlighting.test.ts
  utils/url.test.tsx
  utils/youtube.test.ts
Labels: 4: Reviews Complete, release-note-none

#12250 Add a limit of 5000 lines to the web app runner
  scripts/runner.js
Labels: 4: Reviews Complete, release-note-none

#12213 E2E/Playwright: Add user browser context, reorganize env variables and update screenshots
  .gitignore
  e2e/playwright/.prettierignore
  e2e/playwright/global_setup.ts
  e2e/playwright/package-lock.json
  e2e/playwright/package.json
  e2e/playwright/playwright.config.ts
  e2e/playwright/support/browser_context.ts
  e2e/playwright/support/server/init.ts
  e2e/playwright/support/ui/page/landing_login.ts
  e2e/playwright/support/ui/page/login.ts
  e2e/playwright/support/ui/page/signup.ts
  e2e/playwright/support/ui/style.ts
  e2e/playwright/support/visual/applitools.ts
  e2e/playwright/support/visual/index.ts
  e2e/playwright/support/visual/percy.ts
  e2e/playwright/test.config.ts
  e2e/playwright/tests/visual/intro_channel.spec.ts
  e2e/playwright/tests/visual/intro_channel.spec.ts-snapshots/intro-to-channel-as-regular-user-chrome-linux.png
  e2e/playwright/tests/visual/intro_channel.spec.ts-snapshots/intro-to-channel-as-regular-user-firefox-linux.png
  e2e/playwright/tests/visual/intro_channel.spec.ts-snapshots/intro-to-channel-as-regular-user-ipad-linux.png
  e2e/playwright/tests/visual/intro_channel.spec.ts-snapshots/intro-to-channel-as-regular-user-iphone-linux.png
  e2e/playwright/tests/visual/landing_page.spec.ts
  e2e/playwright/tests/visual/login.spec.ts
  e2e/playwright/tests/visual/signup_email.spec.ts
Labels: 4: Reviews Complete, release-note-none

#12262 hotfix(ci): Fix docker image build for Spinwick environments
  .github/workflows/ci.yml
Labels: release-note-none, kind/bug

#12254 [MM-50561]: Add email in profile popover
  components/profile_popover/profile_popover.scss
  components/profile_popover/profile_popover.tsx
Labels: 4: Reviews Complete, CherryPick/Approved, Setup Cloud Test Server, AutoMerge, release-note

#12126 MM-50281 : Make menus gets clicked on "Space" bar
  components/channel_move_to_sub_menu/index.tsx
  components/menu/menu.tsx
  components/menu/menu_item.tsx
  components/menu/sub_menu.tsx
  components/sidebar/sidebar_category/sidebar_category.tsx
  components/sidebar/sidebar_category/sidebar_category_menu/sidebar_category_menu.tsx
  components/sidebar/sidebar_category/sidebar_category_sorting_menu/sidebar_category_sorting_menu.tsx
  components/sidebar/sidebar_channel/sidebar_channel_menu/sidebar_channel_menu.tsx
Labels: CherryPick/Approved, release-note, QA Deferred

#12269 Fix type check for 'sub_menu' file
  components/menu/sub_menu.tsx
Labels: 4: Reviews Complete, release-note-none, QA Deferred

#12265 [MM-50475][MM-50775] - Post component fixes
  components/post/post_component.tsx
  package-lock.json
Labels: 3: QA Review, CherryPick/Approved, Setup Cloud Test Server, 1: UX Review, release-note

#12270 Add email in profile popover
  components/profile_popover/profile_popover.scss
  components/profile_popover/profile_popover.tsx
Labels: release-note

#12257 MM-50781 - Change Request Param Naming for Delete and Downgrade Feedback to be In Sync with the Backend
  actions/cloud.tsx
  components/admin_console/billing/delete_workspace/delete_feedback.tsx
  components/admin_console/billing/delete_workspace/delete_workspace_modal.tsx
  components/admin_console/billing/delete_workspace/downgrade_feedback.tsx
  components/feedback_modal/downgrade_feedback.tsx
  components/feedback_modal/feedback.tsx
  components/purchase_modal/process_payment_setup.tsx
  components/purchase_modal/purchase_modal.tsx
  packages/client/src/client4.ts
  packages/types/src/cloud.ts
Labels: 2: Dev Review, release-note-none

#12069 Fix App Bar scroll issue
  components/app_bar/__snapshots__/app_bar.test.tsx.snap
  components/app_bar/app_bar.scss
  components/app_bar/app_bar.tsx
Labels: 4: Reviews Complete, QA Review Done, release-note-none

#12274 Revert "[MM-50475][MM-50775] - Post component fixes (#12265)"
  components/post/post_component.tsx
  package-lock.json
Labels: release-note-none

#12282 MM-50818 Add more comments to explain how shared modules are configured
  webpack.config.js
Labels: 4: Reviews Complete, release-note-none

#12283 Update subpackage versions to 7.9.0
  package-lock.json
  package.json
  packages/client/package.json
  packages/types/package.json
Labels: 4: Reviews Complete, CherryPick/Candidate, release-note-none

#12219 MM 47849 - tourtip after template creation
  components/global_header/left_controls/product_menu/product_menu.tsx
  components/tours/channels_tour_tip.tsx
  components/tours/constant.ts
  components/tours/hooks.ts
  components/tours/onboarding_explore_tools_tour/boards_tour_tip.tsx
  components/tours/onboarding_explore_tools_tour/explore_tools_tour_manager.tsx
  components/tours/tour_manager.tsx
  components/tours/worktemplate_explore_tour/boards_tour_tip.tsx
  components/tours/worktemplate_explore_tour/index.ts
  components/tours/worktemplate_explore_tour/playbooks_tour_tip.tsx
  components/tours/worktemplate_explore_tour/useShowTourTip.tsx
  components/tours/worktemplate_explore_tour/worktemplate_explore_tour_tip.tsx
  components/work_templates/hooks.ts
  components/work_templates/index.tsx
  components/work_templates/utils.ts
  i18n/en.json
  packages/components/src/tour_tip/tour_tip.scss
  packages/components/src/tour_tip/tour_tip.tsx
  packages/components/src/tour_tip/tour_tip_backdrop.tsx
  packages/mattermost-redux/src/action_types/work_templates.ts
  packages/mattermost-redux/src/actions/work_templates.ts
  packages/mattermost-redux/src/reducers/entities/work_templates.ts
  packages/mattermost-redux/src/selectors/entities/general.ts
  packages/mattermost-redux/src/store/initial_state.ts
  packages/types/src/work_templates.ts
  plugins/rhs_plugin/auto_show_linked_board_tourtip.tsx
  plugins/rhs_plugin/index.js
  plugins/rhs_plugin/index.ts
  plugins/rhs_plugin/rhs_plugin.jsx
  plugins/rhs_plugin/rhs_plugin.tsx
  plugins/useGetPluginsActivationState.ts
  types/store/plugins.ts
  utils/constants.tsx
Labels: Setup Cloud Test Server, release-note-none, QA Deferred
